### ISSUE TITLE
Use Salt to create config and manage services

### ISSUE THREAD

**Issue by votdev** [openmediavault/openmediavault#100]

**Comment by ryecoaaron** [comment]
I love this idea :)

**Comment by votdev** [comment]
@tooomm I know that, but there are still no Debian packages and OMV only uses that, so there should s no way to install Salt with Python 3 via PIP.

**Comment by ryecoaaron** [comment]
I assume OMV 5.x will use Debian Buster (10.x)?  Does that "fix" the problem?

**Comment by votdev** [comment]
Currently OMV5 is using Debian 9. I didn’t have checked the Salt packages in 10, but the Salt project itself does not provide Python 3 packages. I also think that OMV will make a exception and will not use the Debian packages, instead the more up to date upstream packages will bevuseg and integrated into the OMV repository.
