### ISSUE TITLE
plug-in ClamAV - delayed error when "extra Options" contain error

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1000]
**Describe the bug**

default "Quarantine" config 'None' can't be changed

**To Reproduce**

1. Go to '.AntiVirus'
2. Click on 'Quarantine'
3. select a shared folder, click "save" and "apply changes"

```
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color clamav 2>&1' with exit code '1': raspberrypi:
----------
          ID: remove_clamav_clamdscan_cron
    Function: file.absent
        Name: /etc/cron.d/openmediavault-clamdscan
      Result: True
     Comment: Removed file /etc/cron.d/openmediavault-clamdscan
     Started: 19:48:04.004191
    Duration: 28.965 ms
     Changes:
              ----------
              removed:
                  /etc/cron.d/openmediavault-clamdscan
----------
          ID: remove_clamav_clamdscan_cron_scripts
    Function: module.run
      Result: True
     Comment: file.find: []
     Started: 19:48:04.035948
    Duration: 5.946 ms
     Changes:
              ----------
              file.find:
----------
          ID: remove_clamav_daemon_logrotate
    Function: file.absent
        Name: /etc/logrotate.d/clamav-daemon
      Result: True
     Comment: Removed file /etc/logrotate.d/clamav-daemon
     Started: 19:48:04.042414
    Duration: 2.76 ms
     Changes:
              ----------
              removed:
                  /etc/logrotate.d/clamav-daemon
----------
          ID: remove_clamav_freshclam_logrotate
    Function: file.absent
        Name: /etc/logrotate.d/clamav-freshclam
      Result: True
     Comment: Removed file /etc/logrotate.d/clamav-freshclam
     Started: 19:48:04.045670
    Duration: 2.643 ms
     Changes:
              ----------
              removed:
                  /etc/logrotate.d/clamav-freshclam
----------
          ID: configure_clamd_apparmor_profile
    Function: file.replace
        Name: /etc/apparmor.d/usr.sbin.clamd
      Result: True
     Comment: No changes needed to be made
     Started: 19:48:04.048804
    Duration: 20.483 ms
     Changes:
----------
          ID: configure_clamd_apparmor_local_profile
    Function: file.append
        Name: /etc/apparmor.d/local/usr.sbin.clamd
      Result: True
     Comment: File /etc/apparmor.d/local/usr.sbin.clamd is in correct state
     Started: 19:48:04.069824
    Duration: 28.699 ms
     Changes:
----------
          ID: reload_clamd_apparmor_profile
    Function: cmd.run
        Name: apparmor_parser -r /etc/apparmor.d/usr.sbin.clamd
      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 19:48:04.104603
    Duration: 0.031 ms
     Changes:
----------
          ID: configure_clamav_freshclam
    Function: file.managed
        Name: /etc/clamav/freshclam.conf
      Result: True
     Comment: File /etc/clamav/freshclam.conf is in the correct state
     Started: 19:48:04.104926
    Duration: 238.997 ms
     Changes:
----------
          ID: stop_clamav_freshclam_service_to_force_db_download
    Function: service.dead
        Name: clamav-freshclam
      Result: True
     Comment: onlyif condition is false
     Started: 19:48:04.403454
    Duration: 7304.718 ms
     Changes:
----------
          ID: start_clamav_freshclam_service
    Function: service.running
        Name: clamav-freshclam
      Result: True
     Comment: The service clamav-freshclam is already running
     Started: 19:48:11.712024
    Duration: 220.243 ms
     Changes:
----------
          ID: wait_for_clamav_freshclam_db_download
    Function: file.exists
        Name: /var/lib/clamav/main.cvd
      Result: True
     Comment: Path /var/lib/clamav/main.cvd exists
     Started: 19:48:11.933615
    Duration: 84.003 ms
     Changes:
----------
          ID: configure_clamav_freshclam_logrotate
    Function: file.managed
        Name: /etc/logrotate.d/clamav-freshclam
      Result: True
     Comment: File /etc/logrotate.d/clamav-freshclam updated
     Started: 19:48:12.018770
    Duration: 16.328 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
              user:
                  clamav
----------
          ID: configure_clamav_daemon
    Function: file.managed
        Name: /etc/clamav/clamd.conf
      Result: True
     Comment: File /etc/clamav/clamd.conf is in the correct state
     Started: 19:48:12.035643
    Duration: 347.781 ms
     Changes:
----------
          ID: start_clamav_daemon_service
    Function: service.running
        Name: clamav-daemon
      Result: False
     Comment: Service clamav-daemon is already enabled, and is dead
     Started: 19:48:12.385869
    Duration: 519.778 ms
     Changes:
----------
          ID: stop_clamav_onaccess_service
    Function: service.dead
        Name: clamav-onaccess
      Result: True
     Comment: The service clamav-onaccess is already dead
     Started: 19:48:12.906934
    Duration: 235.428 ms
     Changes:
----------
          ID: configure_clamav_clamdscan_cron
    Function: file.managed
        Name: /etc/cron.d/openmediavault-clamdscan
      Result: True
     Comment: File /etc/cron.d/openmediavault-clamdscan updated
     Started: 19:48:13.143530
    Duration: 93.372 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_clamav_daemon_logrotate
    Function: file.managed
        Name: /etc/logrotate.d/clamav-daemon
      Result: True
     Comment: File /etc/logrotate.d/clamav-daemon updated
     Started: 19:48:13.237441
    Duration: 13.702 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
              user:
                  clamav

Summary for raspberrypi
-------------
Succeeded: 16 (changed=7)
Failed:     1
-------------
Total states run:     17
Total run time:    9.164 s in /usr/share/php/openmediavault/system/process.inc:195
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusIc...', '/tmp/bgoutputxt...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```
**Expected behavior**

Config change is applied

**Screenshots**

**Reference to Forum**

URL link to [forum post](https://forum.openmediavault.org/index.php?thread/32158-clamav-logfile-file-information-cryptic-or-useless/&postID=237070#post237070)

**openmediavault Server (please complete the following information):**

- OS version: Linux nas 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
- openmediavault version: [dpkg -l | grep openmediavault]
```
root@nas:~# dpkg -l | grep openmediavault
ii  openmediavault                  5.6.3-1                             all          openmediavault - The open network attached storage solution
ii  openmediavault-apttool          3.6                                 all          apt tool plugin for OpenMediaVault.
ii  openmediavault-backup           5.2.4                               all          backup plugin for OpenMediaVault.
ii  openmediavault-clamav           5.0.11-1                            all          openmediavault ClamAV plugin
ii  openmediavault-flashmemory      5.0.8                               all          folder2ram plugin for OpenMediaVault
ii  openmediavault-keyring          1.0                                 all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg     5.6                                 all          OMV-Extras.org Package Repositories for OpenMediaVault
root@nas

```

**Comment by mi-hol** [comment]
After installing released OMV version 5.6.3 the error happens no longer in "Quarantine' but when "Scheduled jobs" is 'added'

```
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color clamav 2>&1' with exit code '1': raspberrypi:
----------
          ID: remove_clamav_clamdscan_cron
    Function: file.absent
        Name: /etc/cron.d/openmediavault-clamdscan
      Result: True
     Comment: Removed file /etc/cron.d/openmediavault-clamdscan
     Started: 12:48:30.840714
    Duration: 30.479 ms
     Changes:
              ----------
              removed:
                  /etc/cron.d/openmediavault-clamdscan
----------
          ID: remove_clamav_clamdscan_cron_scripts
    Function: module.run
      Result: True
     Comment: file.find: []
     Started: 12:48:30.874186
    Duration: 6.534 ms
     Changes:
              ----------
              file.find:
----------
          ID: remove_clamav_daemon_logrotate
    Function: file.absent
        Name: /etc/logrotate.d/clamav-daemon
      Result: True
     Comment: Removed file /etc/logrotate.d/clamav-daemon
     Started: 12:48:30.881304
    Duration: 3.072 ms
     Changes:
              ----------
              removed:
                  /etc/logrotate.d/clamav-daemon
----------
          ID: remove_clamav_freshclam_logrotate
    Function: file.absent
        Name: /etc/logrotate.d/clamav-freshclam
      Result: True
     Comment: Removed file /etc/logrotate.d/clamav-freshclam
     Started: 12:48:30.884926
    Duration: 2.991 ms
     Changes:
              ----------
              removed:
                  /etc/logrotate.d/clamav-freshclam
----------
          ID: configure_clamd_apparmor_profile
    Function: file.replace
        Name: /etc/apparmor.d/usr.sbin.clamd
      Result: True
     Comment: No changes needed to be made
     Started: 12:48:30.888456
    Duration: 22.801 ms
     Changes:
----------
          ID: configure_clamd_apparmor_local_profile
    Function: file.append
        Name: /etc/apparmor.d/local/usr.sbin.clamd
      Result: True
     Comment: File /etc/apparmor.d/local/usr.sbin.clamd is in correct state
     Started: 12:48:30.911832
    Duration: 30.159 ms
     Changes:
----------
          ID: reload_clamd_apparmor_profile
    Function: cmd.run
        Name: apparmor_parser -r /etc/apparmor.d/usr.sbin.clamd
      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 12:48:30.948492
    Duration: 0.033 ms
     Changes:
----------
          ID: configure_clamav_freshclam
    Function: file.managed
        Name: /etc/clamav/freshclam.conf
      Result: True
     Comment: File /etc/clamav/freshclam.conf is in the correct state
     Started: 12:48:30.948862
    Duration: 242.168 ms
     Changes:
----------
          ID: stop_clamav_freshclam_service_to_force_db_download
    Function: service.dead
        Name: clamav-freshclam
      Result: True
     Comment: onlyif condition is false
     Started: 12:48:31.245511
    Duration: 7370.215 ms
     Changes:
----------
          ID: start_clamav_freshclam_service
    Function: service.running
        Name: clamav-freshclam
      Result: True
     Comment: The service clamav-freshclam is already running
     Started: 12:48:38.619488
    Duration: 219.443 ms
     Changes:
----------
          ID: wait_for_clamav_freshclam_db_download
    Function: file.exists
        Name: /var/lib/clamav/main.cvd
      Result: True
     Comment: Path /var/lib/clamav/main.cvd exists
     Started: 12:48:38.840363
    Duration: 89.754 ms
     Changes:
----------
          ID: configure_clamav_freshclam_logrotate
    Function: file.managed
        Name: /etc/logrotate.d/clamav-freshclam
      Result: True
     Comment: File /etc/logrotate.d/clamav-freshclam updated
     Started: 12:48:38.931340
    Duration: 18.567 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
              user:
                  clamav
----------
          ID: configure_clamav_daemon
    Function: file.managed
        Name: /etc/clamav/clamd.conf
      Result: True
     Comment: File /etc/clamav/clamd.conf is in the correct state
     Started: 12:48:38.950634
    Duration: 348.59 ms
     Changes:
----------
          ID: start_clamav_daemon_service
    Function: service.running
        Name: clamav-daemon
      Result: False
     Comment: Service clamav-daemon is already enabled, and is dead
     Started: 12:48:39.301777
    Duration: 525.733 ms
     Changes:
----------
          ID: stop_clamav_onaccess_service
    Function: service.dead
        Name: clamav-onaccess
      Result: True
     Comment: The service clamav-onaccess is already dead
     Started: 12:48:39.828830
    Duration: 242.187 ms
     Changes:
----------
          ID: configure_clamav_clamdscan_cron
    Function: file.managed
        Name: /etc/cron.d/openmediavault-clamdscan
      Result: True
     Comment: File /etc/cron.d/openmediavault-clamdscan updated
     Started: 12:48:40.072203
    Duration: 95.74 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_clamav_clamdscan_cron_script_3d5ae484-d3f9-4265-91c5-0bccfcc7c621
    Function: file.managed
        Name: /var/lib/openmediavault/cron.d/clamdscan-3d5ae484-d3f9-4265-91c5-0bccfcc7c621
      Result: True
     Comment: File /var/lib/openmediavault/cron.d/clamdscan-3d5ae484-d3f9-4265-91c5-0bccfcc7c621 updated
     Started: 12:48:40.168487
    Duration: 201.117 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0750
----------
          ID: configure_clamav_daemon_logrotate
    Function: file.managed
        Name: /etc/logrotate.d/clamav-daemon
      Result: True
     Comment: File /etc/logrotate.d/clamav-daemon updated
     Started: 12:48:40.370190
    Duration: 14.373 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
              user:
                  clamav

Summary for raspberrypi
-------------
Succeeded: 17 (changed=8)
Failed:     1
-------------
Total states run:     18
Total run time:    9.464 s in /usr/share/php/openmediavault/system/process.inc:195
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatus43...', '/tmp/bgoutputnl...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

**Comment by mi-hol** [comment]
Good usability requires that errors are detected at time of data entry.
For "extra Options" this goal is not achieved currently, because an error is only detected in in user unfriendly way when  a scheduled job is added. Error and its root cause are not detectable for an average user.

**Comment by ryecoaaron** [comment]
It would be very difficult to parse extra options on the client side for errors.  The "average" user should not be using extra options unless they know what they are doing.

**Comment by mi-hol** [comment]
Are typos intentional? Usually not, but they are a fact of life that needs correct handling. 
Just saying "typos are not allowed" is simply not good enough as solution.

**Comment by mi-hol** [comment]
Currently displayed error message seems to cut off the real root cause of error

command displayed is
`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color clamav`

When copied, this command is successfully executed via shell!

**Comment by ryecoaaron** [comment]
@mi-hol You evidently have no clue how hard it would be to make a javascript client-side parser for clamav config (and then any other plugin with extra options box).  Please feel free to write it.  This has not been a issue worth investing a ridiculous amount of time into.  It would be a nightmare to maintain as well.

**Comment by mi-hol** [comment]
I didn't mention a "javascript client-side parser for clamav config" as the solution.
I prefer simple solution.
With the extra step "apply change" available, why not execute the command and tell the user the result?

**Comment by ryecoaaron** [comment]
> Good usability requires that errors are detected at time of data entry.

Uh, that is exactly what you asked for.

If you are just looking for a more verbose salt output, normally it does tell you why it failed.  Maybe clamav doesn't report a verbose reason why it failed.  In that case, salt can't tell you.  This is very service dependent.  If salt isn't telling you in this case, then perhaps the logs do.

**Comment by mi-hol** [comment]
> > Good usability requires that errors are detected at time of data entry.
> 
> Uh, that is exactly what you asked for.
> 
> If you are just looking for a more verbose salt output, normally it does tell you why it failed. Maybe clamav doesn't report a verbose reason why it failed. In that case, salt can't tell you. This is very service dependent. If salt isn't telling you in this case, then perhaps the logs do.

Right, it wasn't my intent, to limit possible solutions though.
So modifying requirement to 'Good usability requires that errors are detected best at time of data entry & latest at time of permanent save (apply change)'

The first issue to fix seems the be the 'incomplete error message from ClamAV plugin'.
To further diagnose the full path to ClamAV plug-ins log is required. 
I fail to find this in the currently provide error message.
Any hint?

**Comment by ryecoaaron** [comment]
> So modifying requirement to 'Good usability requires that errors are detected best at time of data entry & latest at time of permanent save (apply change)'

When you save something in the web interface, it is saved to the database immediately.  When you apply, it changes config files and restarts services (if applicable).  The only way to check the extra options is to apply (unless you want to write an options parser).  I'm still not sure why you are tying to "fix" this.  If it fails to apply, look at your options and fix it.  Then save & apply again.  If you are using extra options and salt doesn't tell you the exact error and can't look at logs and you don't know how to google, you shouldn't be using extra options.

Did you look in the log viewer under AntiVirus?  The plugin itself does not generate logs.  ClamAV is what should generate logs if there is an error.

**Comment by votdev** [comment]
> Good usability requires that errors are detected at time of data entry.
> For "extra Options" this goal is not achieved currently, because an error is only detected in in user unfriendly way when a scheduled job is added. Error and its root cause are not detectable for an average user.

It is not the intention of OMV to prevent users from entering incorrect values in the `Extra options`. It is simply not possible to do that without writing a parser that knows every possible config option of the service it handles. That can't be done, or at least i will not do it because it is error-prone and expensive to maintain all possible config options. It's simply not worth. If a user is using this field, they are responsible for what they enter because it is out of the control of OMV what is entered here. IMO i would remove this fields everywhere in the UI, but this will remove the ability to allow power users to enhance/customize the services beyond what OMV supports out-of-the-box.

Related to error reports. OMV and Salt can only report what the service/command/... provides. Both are not responsible for that, they can only deliver what they get.

**Comment by votdev** [comment]
I close this issue because the initial error reported seems to be fixed by installing the latest plugin version (which should be done by default after installation).

By the way, why do you want to set the log file, it is set to `/var/log/clamav/clamav.log` by default.

* https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault-clamav/srv/salt/omv/deploy/clamav/files/etc-clamav-clamd_conf.j2#L56
* https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault-clamav/srv/salt/omv/deploy/clamav/files/etc-clamav-clamd_conf.j2#L145

**Comment by mi-hol** [comment]
> I close this issue because the initial error reported seems to be fixed by installing the latest plugin version
Sorry but that is an incorrect conclusion

Over several iterations it only became clear what input field is actually causing the error.

Current implementation doesn't report the full command causing the error, hence **troubleshooting by user is impossible**.

I hope you can proof me to be wrong by identifying the root cause from the full error message copied into first post.
Obviously I failed to find a usefull message to use for an internet search

Note: From my view its highly like a general deficiency for all plug-ins because they share common code.

**Comment by votdev** [comment]
> Current implementation doesn't report the full command causing the error, hence troubleshooting by user is impossible.

But in this case the user IS responsible for the fault by adding something via `Extra Options` that is NOT officially supported by OMV. That is why I do not see OMV as responsible.

I fully understand that the problem search is unsatisfactory, but OMV can only deliver the error message that it receives itself.

**Comment by ryecoaaron** [comment]
> From my view its highly like a general deficiency for all plug-ins because they share common code.

Don't assume because that is not true at all.  Some services report better errors than clamav.

> hence troubleshooting by user is impossible.

Definitely not impossible.  That is what logs and the command line are for.

**Comment by mi-hol** [comment]
> Definitely not impossible. That is what logs and the command line are for.

@ryecoaaron 
So what is preventing you to providing the search string allowing troubleshooting from first post?

**Comment by ryecoaaron** [comment]
> So what is preventing you to provide the magic "internet search string" allowing troubleshooting from first post?

And how would I do that?  I don't have access to the logs.  As I mentioned before, if the salt output doesn't have what you need, then you need to rely on the logs.  The logs AND/OR the salt output ideally give you something to search for. 

You say the salt command from the command line is working but what is the return code?  Just because the second execution worked doesn't mean the first did.

**Comment by votdev** [comment]
So, now everybody take a deep breath. I hate such discussions like this here.

@mi-hol I really lost track what the problem now is. Please rephrase is again (i do not have the time to start reading from the top), so we are all on the same line.

> first post?

Which do you mean, i'm confused. Please cross-link to the post you are talking about. Do you mean [this](https://github.com/openmediavault/openmediavault/issues/1000#issue-849711306) or [that](https://github.com/openmediavault/openmediavault/issues/1000#issuecomment-814814217)? I hate guessing what you mean. This might help to prevent false assumptions.

I will summarize what IMO the problem. I hope i'm right. 
You have added something to `Extra Options` that will cause clamav to fail. No you have to know that OMV is using Salt to build the configuration files and to start/stop/restart the corresponding services. If the magically `Extra Options` entry is the root cause of the failure OMV/Salt can not give you any detailed hint if clamav is not doing that. The incorrect configuration stops systemd from starting the clamav unit file. Systemd is not really verbose in that case, so Salt -> OMV -> UI can not give you more information.

```
          ID: start_clamav_daemon_service
    Function: service.running
        Name: clamav-daemon
      Result: False
     Comment: Service clamav-daemon is already enabled, and is dead
     Started: 12:48:39.301777
    Duration: 525.733 ms
```

 What you need to do is simply run the faulty systemd unit file yourself by executing `systemd restart clamav-daemon`. If clamav is not more vebose, then you will get a hint on STDOUT. If not, then you need to run `journalctl -f` in parallel to get the syslog output.
I know, not really novice friendly, but it's really not possible to do it another way. OMV always tries to be as error/debug friendly as possible; by default.

**Comment by mi-hol** [comment]
closed via https://github.com/mi-hol/openmediavault-docs/pull/2
