### ISSUE TITLE
Changeable top bar color

### ISSUE THREAD

**Issue by sebeksd** [openmediavault/openmediavault#1002]
**Is your feature request related to a problem? Please describe.**
From few days I'have two separate OMV servers and sometimes I start doing something on wrong server before I realize.

**Describe the solution you'd like**
Simple solution will be to add color settings for the top bar (no complicated themes support needed) this will allow to visualize different servers in clear way.
I think it would be beneficial for both OMV 5 and OMV 6.

**Describe alternatives you've considered**
no idea

**Additional context**
![image](https://user-images.githubusercontent.com/18705953/114139618-921f0e00-990f-11eb-8281-434fc4132891.png)
![image](https://user-images.githubusercontent.com/18705953/114139656-9ba87600-990f-11eb-92dd-59d708cf5094.png)

**Comment by votdev** [comment]
OMV5 already allows you customize the UI via CSS file: `/var/www/openmediavault/css/theme-custom.css`.

OMV6 will not provide UI customizations and themes anymore.

Both versions display the hostname of the system in the upper right corner of the UI for identification.

**Comment by sebeksd** [comment]
> Both versions display the hostname of the system in the upper right corner of the UI for identification.
I'm using Ultra wide monitor, right corner is "far away" for me :P In my case it's easier to look on address bar, this still require me to look somewhere with intent to verify I'm on right server, color would not require me to look anywhere.

> OMV5 already allows you customize the UI via CSS file: /var/www/openmediavault/css/theme-custom.css.
I will use this for now, thanks :)
