### ISSUE TITLE
[FR] Include previous flags in notification about the change of filesystem flags

### ISSUE THREAD

**Issue by rabelux** [openmediavault/openmediavault#1009]
I recently received an email informing me about a change of the filesystem flags. Unfortunately it only contains information about the new flags, so that I can't really evaluate the changes that have been made.
So my question is:

Is it possible to include the flags prior to the change? That way it woud be possible to track changes.

Background:
I mounted a drive and created a new filesystem in the web-ui. Apparently that changed flags of a previously mounted drive, as I received the notification-email without actively changing anything. That's why it would have been interesting to see the changes as I don't know what the previous setting was.

**Comment by votdev** [comment]
That's not possible, the content of the message is fully under control of [monit](https://mmonit.com/monit/documentation/monit.html). You should request that feature there, so it will be available someday in OMV.

**Comment by rabelux** [comment]
Update: I did open an [issue](https://bitbucket.org/tildeslash/monit/issues/979) and the desired feature has been implemented in the dev version.
As debian is quite conservative with updates I guess we're talking about years until this feature will be available?

**Comment by votdev** [comment]
> As debian is quite conservative with updates I guess we're talking about years until this feature will be available?

This might happen, but we'll see. If it is packaged by Debian in testing or a new version (surely not Bullseye since there already was the feature freeze) the package can be rebuild for the OMV stable version.
