### ISSUE TITLE
Ability to give SMB shares a different name to the shared folder name

### ISSUE THREAD

**Issue by djmattyg007** [openmediavault/openmediavault#1011]
**Is your feature request related to a problem? Please describe.**
I've prefixed all of my samba shares with `samba-` to distinguish them from non-samba shared folders (for example, those I intend to use with NFS and so on). It's unnecessary for this prefix to be present in the name of the matching samba share.

**Describe the solution you'd like**
An optional field to let you set a custom name for a samba share, overriding the value that comes from the shared folder.

**Describe alternatives you've considered**
Changing the names of the shared folders to remove the prefix. However I don't see why that should be necessary as I'd prefer to treat them as internal private identifiers.

**Comment by ryecoaaron** [comment]
Why can't you just change the name of the sharedfolder?  The shared folder name doesn't have to match the directory it represents.

**Comment by votdev** [comment]
This way it's much more complicated to take care share names are unique. The current workflow allows you to modify the shared folder name, thus there is no need to support this feature request.
