### ISSUE TITLE
UI: Dialogs always force focus / No multitasking

### ISSUE THREAD

**Issue by tooomm** [openmediavault/openmediavault#1012]
**Is your feature request related to a problem? Please describe.**
Once one opens a dialog the rest of the system/web gui is no longer accessible. The interaction is limited to the dialog which takes all focus.
Many tasks are performed in newly opened dialogs and often take a while (some take hours!).

**Describe the solution you'd like**
It would be nice if dialog windows could go to the background, could be minimized or get transparent etc. and allow to navigate and control the rest of the UI still.
I would love to double check or adjust other settings or perform another task while another task is running.
Some kind of multi tasking would be great.

Does this behavior change with the new interface in OMV 6 maybe?

**Comment by votdev** [comment]
The OMV interface is a single page application that does not and will never support the requested behavior. The UI is not designed to run longer tasks, these should be executed by cron or other daemons in the backend.
As a workaround, if a user really wants to misuse the UI, they can log into a separate instance of the UI to run such long running tasks.
