### ISSUE TITLE
Formatted drive and now shows "Missing"

### ISSUE THREAD

**Issue by wdavies414** [openmediavault/openmediavault#1013]
Hello,
On the File Systems tab I have a drive that has a status of "missing".  I know this is a drive that I recently formatted.  I would like to remove it from the list in OMV's File System tab, but all of the options (Create, Resize, Delete) are greyed-out/not available. Is there a config file I can change or command that will remove this now non-existent drive from my file system?

![Screenshot 2021-04-23 152614](https://user-images.githubusercontent.com/69095881/115931447-56746000-a448-11eb-92b0-75c063db19d8.jpg)

#########
 
Results of "blkid -o full"
/dev/mmcblk0p1: LABEL_FATBOOT="boot" LABEL="boot" UUID="592B-C92C" TYPE="vfat" PARTUUID="16da416c-01"
/dev/mmcblk0p2: LABEL="rootfs" UUID="706944a6-7d0f-4a45-9f8c-7fb07375e9f7" TYPE="ext4" PARTUUID="16da416c-02"

###########

Results of "mount"
/dev/mmcblk0p2 on / type ext4 (rw,noatime,nodiratime)
devtmpfs on /dev type devtmpfs (rw,relatime,size=1827800k,nr_inodes=97773,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=40,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
mqueue on /dev/mqueue type mqueue (rw,relatime)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
sunrpc on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
tmpfs on /tmp type tmpfs (rw,relatime)
/dev/mmcblk0p1 on /boot type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
/dev/mmcblk0p2 on /var/folder2ram/var/log type ext4 (rw,noatime,nodiratime)
folder2ram on /var/log type tmpfs (rw,relatime)
/dev/mmcblk0p2 on /var/folder2ram/var/tmp type ext4 (rw,noatime,nodiratime)
folder2ram on /var/tmp type tmpfs (rw,relatime)
/dev/mmcblk0p2 on /var/folder2ram/var/lib/openmediavault/rrd type ext4 (rw,noatime,nodiratime)
folder2ram on /var/lib/openmediavault/rrd type tmpfs (rw,relatime)
/dev/mmcblk0p2 on /var/folder2ram/var/spool type ext4 (rw,noatime,nodiratime)
folder2ram on /var/spool type tmpfs (rw,relatime)
/dev/mmcblk0p2 on /var/folder2ram/var/lib/rrdcached type ext4 (rw,noatime,nodiratime)
folder2ram on /var/lib/rrdcached type tmpfs (rw,relatime)
/dev/mmcblk0p2 on /var/folder2ram/var/lib/monit type ext4 (rw,noatime,nodiratime)
folder2ram on /var/lib/monit type tmpfs (rw,relatime)
/dev/mmcblk0p2 on /var/folder2ram/var/cache/samba type ext4 (rw,noatime,nodiratime)
folder2ram on /var/cache/samba type tmpfs (rw,relatime)
overlay on /var/lib/docker/overlay2/ebe8b2e7aa7d08a1e1bc3bfd426374a798c227d9b96fa3a0e5ee64f74173a983/merged type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/GPLB7SZJ7DDRS3FCG7LVL2OEIX:/var/lib/docker/overlay2/l/NQK7SIP4OITKYDGFHFAOTA7G2T:/var/lib/docker/overlay2/l/LJAYJTRUGCYUV7RYW7BHZIWK2D,upperdir=/var/lib/docker/overlay2/ebe8b2e7aa7d08a1e1bc3bfd426374a798c227d9b96fa3a0e5ee64f74173a983/diff,workdir=/var/lib/docker/overlay2/ebe8b2e7aa7d08a1e1bc3bfd426374a798c227d9b96fa3a0e5ee64f74173a983/work)
nsfs on /run/docker/netns/77c3604ea1d5 type nsfs (rw)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=391976k,mode=700,uid=1000,gid=1000)
 
############

Results of omv-confdbadm read --prettify "conf.system.filesystem.mountpoint"
Traceback (most recent call last):
  File "/usr/sbin/omv-confdbadm", line 76, in <module>
    sys.exit(main())
  File "/usr/sbin/omv-confdbadm", line 72, in main
    return cmd_inst.execute(*sys.argv)
  File "/usr/share/openmediavault/confdbadm/commands.d/read.py", line 73, in execute
    objs = db.get(cmd_args.id, cmd_args.uuid)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 723, in execute
    elements = self._execute_xpath()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 408, in _execute_xpath
    root_element = self._get_root_element()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 399, in _get_root_element
    self._load()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 378, in _load
    self._root_element = lxml.etree.parse(self._database_file)
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
OSError: Error reading file '/etc/openmediavault/config.xml': failed to load external entity "/etc/openmediavault/config.xml"

**Comment by votdev** [comment]
The drive is still referenced by a shared folder. After you deleted that shared folder, then the delete button is clickable for the missing device.


> Results of omv-confdbadm read --prettify "conf.system.filesystem.mountpoint"
> Traceback (most recent call last):
> File "/usr/sbin/omv-confdbadm", line 76, in
> sys.exit(main())
> File "/usr/sbin/omv-confdbadm", line 72, in main
> return cmd_inst.execute(*sys.argv)
> File "/usr/share/openmediavault/confdbadm/commands.d/read.py", line 73, in execute
> objs = db.get(cmd_args.id, cmd_args.uuid)
> File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
> query.execute()
> File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 723, in execute
> elements = self._execute_xpath()
> File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 408, in _execute_xpath
> root_element = self._get_root_element()
> File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 399, in _get_root_element
> self._load()
> File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 378, in _load
> self._root_element = lxml.etree.parse(self._database_file)
> File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
> File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
> File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
> File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
> File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
> File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
> File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
> File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
> OSError: Error reading file '/etc/openmediavault/config.xml': failed to load external entity "/etc/openmediavault/config.xml"

You should run that command as `root`, otherwise i couldn't explain the error message `failed to load external entity "/etc/openmediavault/config.xml"`.

**Comment by mi-hol** [comment]
@wdavies414 did the suggested workaround resolve the issue?
Please close this issue if it worked

**Comment by wdavies414** [comment]
Sorry about the delay.  I looked in the "Shared Folders" tab and the drive is referenced twice; two separate folders on the drive (named 'media' and 'one').  However, when I mark either of the shares (yellow) the "Delete" button is not available to remove the share referencing the drive I want to remove.  Still can't remove the drive.

**Comment by votdev** [comment]
You have to ensure that the shared folder is not referenced by any service (SMB, FTP, ...). It might happen that a shared folder was used by a plugin that is already uninstalled but the plugin doesn't purge the database during uninstallation. Because of that OMV still shows the shared folder as referenced. I remember that omv-extras.org has a plugin to remove shared folder references, maybe that helps you or you have to manually remove the plugin configuration from the database, but that's tricky and you can destroy your installation if you're doing something wrong. Another solution is to reinstall that plugin, cleanup the configuration and uninstall the plugin again.

**Comment by wdavies414** [comment]
I will see if I can find the Plugin. I guess that it could have been related to the initial install of Portainer.

**Comment by ryecoaaron** [comment]
portainer would not cause a shared folder to show as referenced.  If you install the resetperms plugin, it has a tab that will show you everything in use for each shared folder.

**Comment by wdavies414** [comment]
Yeah, I have "shared folders" list in the "Shared Folders" tab, but, as mentioned on 13 May, the "Delete" button is not available for those shares--even when I select one (yellow).  That is what I am trying to do...remove the shares that are showing in the Shared Folders tab.

**Comment by ryecoaaron** [comment]
I understand what you are trying to do and lots of people have wanted that same thing.  That is why I created the "shared folders in use" tab in the resetperms plugin to show you want services are using what shared folders.  This makes it easy to remove the shared folder and then have the "Delete" button enabled.

**Comment by wdavies414** [comment]
Thanks for clarifying, but I'm looking at the "Shared Folders in Use" tab and I don't see an option to remove/edit/delete the shares. Do I need to manually remove the shares by changing a config file, deleting the listed folders from the directory or some other method? How do I easily remove the shared folders?

**Comment by wdavies414** [comment]
This is what is listed in my "shared folders in use" tab.  Does this help or would other/additional info. make it easier to assist me? Thanks.

![image](https://user-images.githubusercontent.com/69095881/119416707-7ac69500-bcb1-11eb-91c5-42eba7dc4e93.png)

**Comment by ryecoaaron** [comment]
If you are trying to delete the "one" shared folder, you need to set the shared folder to "none" in  Access RIghts Management -> User -> Settings -> Location.  If you are trying to delete the media shared folder, you need to set the reset permissions shared folder to "none".

**Comment by wdavies414** [comment]
@ryecoaaron - Thanks. That removed the share.  I still have a status of "Missing" on what I think is a mount point (/dev/disk/by-label/Prime6TB) in the File Systems tab.  When selecting this item (yellow) the "Delete" option is still not available.  We're so close that I can almost taste the success!!

**Comment by wdavies414** [comment]
not solved. no responses. closing.

**Comment by ryecoaaron** [comment]
@wdavies414 this is why threads in the forum are better - lots more people who can respond who might have time.  The missing status has been covered lots of times in the forum too.  If you can't delete the missing filesystem from the Filesystems tab, you will have to remove the appropriate mntent entry from /etc/openmediavault/config.xml
