### ISSUE TITLE
Auto-scrolling in task dialog does not work

### ISSUE THREAD

**Issue by votdev** [openmediavault/openmediavault#1019]
If new content is appended to the displayed text, then the text is not scrolled to the end automatically, although the code already exists that should do that.

Maybe it does not work because of the flex layout in combination with the scollbar library.

References:
* https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/src/app/shared/components/task-dialog/task-dialog.component.ts#L118
* https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/src/app/shared/components/task-dialog/task-dialog.component.html#L12

**Comment by mi-hol** [comment]
is it the same issue as in #1063 ?
