### ISSUE TITLE
[BUG] NFS configuration from web UI has wrong implementation

### ISSUE THREAD

**Issue by ericcotelnu** [openmediavault/openmediavault#1021]
Issue

From the web UI, when configuring allowed source clients, it denies having spaces in the clients textbox, even though the NFS exports file, and the server, expect a space.

e.g.:

go to NFS, click on shares at the top. configure one. I go to Clients textbox, add my IPv4 host/subnet, try to add my IPv6 host/subnet, won't let me put in a space, even though it's **supposed** to have a space. See man exports(5), near the bottom, the given example.

**openmediavault Server**

- OS version: Linux [hostname removed for privacy] 4.14.222-odroidxu4 #1 SMP PREEMPT Mon Mar 8 07:50:47 UTC 2021 armv7l GNU/Linux
- openmediavault version: openmediavault 5.6.5-1      all          openmediavault - The open network attached storage solution

**Client (please complete the following information):**

- Device: Win10 Pro, MS Edge web client (latest stable)

**Comment by votdev** [comment]
OMV does not reflect the `/etc/exports` configuration syntax, so please don't expert that the UI behaves like that. The dialog and field hint does not mention that it is allowed to enter multiple IP addresses or FQDN. If you want to allow clients to access the shared folder with IPv6, please create a new NFS share. OMV will merge them underneath for you.
