### ISSUE TITLE
Web GUI cannot recognize User its name is pure number.

### ISSUE THREAD

**Issue by 618116** [openmediavault/openmediavault#1025]
If user's name is set pure number, like "1234" or "618116", OMV's web GUI does not show the user.

The user is successfully added to /etc/passwd, and can be used from ssh or other functions. Only OMV Web GUI cannot recognize the user.

**Comment by votdev** [comment]
According to the [useradd man page](https://manpages.debian.org/buster/passwd/useradd.8.de.html) it is recommended that usernames begin with a lower case letter or an underscore. Debian by default is not limited to that, but this makes it harder for the current implementation.

Internally an [user object](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/user.inc#L49) can be created by a UID or username. The class was designed based upon the prerequisite that a username can't start with a digit. If the username is `1234`, then this implementation assumes this is the UID of the user and a different code path is executed.

The problem becomes more difficult when it comes to user/group import (e.g. https://forum.openmediavault.org/index.php?thread/38298-cannot-assign-imported-user-to-groups-error-message-the-group-does-not-exist/; https://github.com/openmediavault/openmediavault/commit/a975de8af0c3005ecb3331f47e37dd130b67cffa#diff-fdd48e66484479fbcea5ee59eabaf431936da13ba3889561a6bd57685323dc3e).

**Comment by 618116** [comment]
If there is a limitation of implementation, I wii be happy if the limitation is clear in the UI. Thanks for your effort.

**Comment by votdev** [comment]
Numeric user name in OMV6.
![Bildschirmfoto vom 2021-05-07 15-47-24](https://user-images.githubusercontent.com/1897962/117459362-99a3f800-af4b-11eb-838f-aa238600706a.png)
