### ISSUE TITLE
Proposed fix for Monit/nginx random connection failure notifications

### ISSUE THREAD

**Issue by cubemin** [openmediavault/openmediavault#1027]
Problem:
Random occasional emails stating "Monitoring restart - Connection failed nginx" almost immediately followed by "Monitoring alert - Connection succeeded nginx" due to timeout receiving HTTP data from nginx web server.

Temporary solution:
Editing `/srv/salt/omv/deploy/monit/services/files/nginx.j2` and changing `timeout 15 seconds for 2 times within 3 cycles` to `timeout 25 seconds for 3 times within 4 cycles` then issuing `omv-salt deploy run nginx` - this has been tested and verified to stop the random notifications as it relaxes the conditions for monit to restart nginx.

Proposal/request:
The above change is overwritten when OpenMediaVault is updated to a newer version, reverting the fix. Would like to see the change be made permanent in future releases.

**Comment by votdev** [comment]
To me it looks like your system is under-powered and the load is too high. Will try to include [environment variables](https://openmediavault.readthedocs.io/en/5.x/various/advset.html#environmental-variables) to allow customization of this setting.
In the meantime you should find out what causes the system to have such a huge load that the webserver does not respond anymore.

**Comment by votdev** [comment]
May i ask what hardware you are using?

**Comment by cubemin** [comment]
Hi Volker,

my server is an x64 build (Asus H370 micro-ATX mobo) with a Pentium Gold
G5420 CPU and 16GB RAM. So, definitely not lacking in processing power.

Allowing the monit settings to be configurable via env variables would be
great. Having said that - I can't think of any reason why the load average
would spike and cause nginx to not respond. Performance statistics reveal
nothing as far as I can tell.

Before I changed the nginx config file, it could be days without any emails
from monit - then several in one day, but at random times and mostly when
I'm not even using the server. I also never have any issues logging into
the GUI and using it.

What would be the best way to track down such spurious load spikes?

Thanks for looking into this. Have a great week!

- Jan

**Comment by votdev** [comment]
> What would be the best way to track down such spurious load spikes?

If possible, try to immediately log in via SSH and run `top` to see which processes are running wild when you receive such an email.
