### ISSUE TITLE
Scrollbars in web view configuration windows are hard to catch

### ISSUE THREAD

**Issue by godfuture** [openmediavault/openmediavault#103]
It is hard to scroll the configuration windows in omv web view, as the cursor switches to windows resize mode too quick. In the screenshot the cursor should already be in resize mode, but the screenshot app let it appear as arrow again. So please just imagine it to be the resize arrow, not the native cursor at its shown position.

![omv_hard_to_scroll](https://user-images.githubusercontent.com/4669278/39920133-0c5eed32-5527-11e8-9541-4c7e0f28c54e.png)

Firefox 59.0.2
Release: 4.1.6
Linux 4.15.0-0.bpo.2-amd64 #1 SMP Debian 4.15.11-1~bpo9+1 (2018-04-07) x86_64 GNU/Linux

**Comment by votdev** [comment]
The scroll bar size and behavior is controlled by the client window manager.
I assume you are using Linux with a theme that is using a small scroll bar, right?

**Comment by godfuture** [comment]
Windows 10 Pro x64 with latest updates. Are there different themes for windows? I did not change anything...I guess its the default!

**Comment by mi-hol** [comment]
4.x is EOL
