### ISSUE TITLE
Use htop or glances instead of top

### ISSUE THREAD

**Issue by MaxiMii05** [openmediavault/openmediavault#1030]
**Is your feature request related to a problem? Please describe.**
CPU utilization show in `top` can exceed 100%. This may be confusing to users that are new to Linux. Also, `top` fluctuates a lot in its readings and in general only provides a very brief overview.

**Describe the solution you'd like**
Use `htop` in the GUI (System Information -> Processes) instead of `top`. The bars at the top give a live representation of actual CPU and memory utilisation. It's less confusing to new users and shows more useful information about the task that are running.

**Describe alternatives you've considered**
I would actually prefer `glances` as this provides even more information, e.g. about running docker containers, CPU temperature etc. The problem is that `glances` takes a lot of screen real estate in order to show all the information. It might not fit inside of the GUI.

**Additional context**
Linux has two different ways of showing CPU utilization. Instead of taking the average of all threads, `top` adds the usage of all individual threads together. This can cause readings of over 100%. In a terminal, this behaviour can be toggled with `Shift + i`.

This change could be introduced in OMV 6.x.

**Comment by ryecoaaron** [comment]
The problem with htop or just looking at cpu is that are not looking at io wait then.  io wait can cause high system load while cpu is still relatively low.  I know you can still the system load in htop but you can't see the io wait info.  Maybe it could be selectable to switch between htop and top.

glances duplicates a lot of info already found in the omv web interface.  I think the correct thing to do in OMV 6 would be to add the widgets to the dashboard to get the same info that glances provides.  The only missing widget I see now is the process list.

**Comment by MaxiMii05** [comment]
> I know you can still the system load in htop but you can't see the io wait info.

[It seems that `htop` can be configured to show io wait.](https://serverfault.com/questions/848714/htop-show-i-o-wait-percentage) The GUI could show a configured instance of `htop` with io wait enabled.

> glances duplicates a lot of info already found in the omv web interface.

I don't see this as a problem as the "Processes" section [still exists within OMV6.](https://www.openmediavault.org/?p=2863) And in my opinion, `glances` is preferable for this for the reasons I stated above. Realistically, the overview "not fitting into the GUI" probably won't be a problem as well.

> The only missing widget I see now is the process list.

There's also information about running docker images, network traffic, temperature sensors and so on, which are all integrated into `glances`. If all this can get implemented into the OMV dashboard, then that's fine by me as well.

**Comment by mi-hol** [comment]
@votdev may I suggest a review and decision?

**Comment by votdev** [comment]
I'm happy with the current implementation based on `top`.
I can only say this is an open source project and contributions from the community are welcome. I have not to do everything on my own.
