### ISSUE TITLE
PHP 7.3 EOL for security fixes December 6, 2021

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1036]
**Is your feature request related to a problem? Please describe.**
PHP Lifecycle (EOL) published PHP 7.3 EOL for security fixes December 6, 2021
[PHP EOL Announcements](https://endoflife.software/programming-languages/server-side-scripting/php)

**Describe the solution you'd like**
Use a supported PHP version, best options seems PHP 8

**Comment by mi-hol** [comment]
According to [migration doc](https://www.php.net/manual/en/migration80.incompatible.php) with PHP 8 incompatible source code could be potentially :

"The ability to call non-static methods statically has been removed. Thus is_callable() will fail when checking for a non-static method with a classname (must check with an object instance)."

 is_callable() is used in:
openmediavault/deb/openmediavault/usr/share/php/openmediavault/engine/notify/dispatcher.inc /
deb/openmediavault/usr/share/openmediavault/engined/rpc/logfile.inc

**Comment by ryecoaaron** [comment]
OMV uses the version of php supplied by Debian (7.3 for Debian 10/OMV 5.x, 7.4 for Debian 11/OMV 6.x).  Debian 8 is only in experimental.  And just because PHP has an EOL, doesn't mean the distro can't support it longer (very typical for Debian, Ubuntu, Red Hat, etc).

**Comment by mi-hol** [comment]
Well at least red hat is now providing a more flexible approach regarding supported programming languages.
I always wonders how distributions can claim to "support" programming languages after EOL and I've yet to see an example where this claim was kept.

**Comment by ryecoaaron** [comment]
Red hat is off topic.

And why can Debian support 50k+ packages but not support a programming language??  When php 7.0 went EOL, Debian would either fix security issues or backport security fixes from a newer, non-EOL version of PHP.  If you don't believe Debian is supporting php for as long as the release is supported, you should take that up with Debian.  This is not an OMV issue.

**Comment by votdev** [comment]
We can start talking about migrating to PHP8 if i see a note from Debian where the announce to stop supporting PHP7 in Bullseye. If they do not drop a PHP version from the start of a new release, they surely support it until the EOL of the Debian release.

PHP8 will not work for OMV because the php-pam package will surely not work anymore which will break the authentication part (for the UI) of the omv-engine.

The plan for OMV 7 is to replace the PHP based RPC interface by a Python based REST API, so no PHP will be needed anymore.

**Comment by votdev** [comment]
I close this because Debian 11 (Bullseye) is using [PHP 7.4](https://packages.debian.org/bullseye/php7.4) which has security updates till [November 28, 2022](https://endoflife.software/programming-languages/server-side-scripting/php).

**Comment by mi-hol** [comment]
> PHP8 will not work for OMV because the php-pam package will surely not work anymore which will break the authentication part (for the UI) of the omv-engine.

There is a version of [php-pam compatible with PHP 8](https://github.com/amishmm/php-pam/releases) but its not yet in PECL.
I've asked the maintainer about owning the orphaned official version in PECL.

I wonder if moving to this version would "kill" several issues like PHP8 & portability f OMV to Ubuntu
