### ISSUE TITLE
 Unclean termination of omv-engine after update

### ISSUE THREAD

**Issue by OMMJAI** [openmediavault/openmediavault#1037]
<img width="1341" alt="Screenshot 2021-05-29 at 13 01 41" src="https://user-images.githubusercontent.com/79408730/120062352-669ee100-c07f-11eb-8fe7-b05448a14728.png">
<img width="1352" alt="Screenshot 2021-05-29 at 13 01 15" src="https://user-images.githubusercontent.com/79408730/120062353-6acafe80-c07f-11eb-865a-af59d06ce2bd.png">
I receive these errors every time time omv is updated any idea how to clean this up

**Comment by votdev** [comment]
Never saw that. Please tell us which hardware platform you are using.

**Comment by votdev** [comment]
Can't reproduce this:
```
May 29 10:18:54 omv5box monit[489]: 'omv-engined' restart on user request
May 29 10:18:54 omv5box monit[489]: Monit daemon with PID 489 awakened
May 29 10:18:54 omv5box monit[489]: Awakened by User defined signal 1
May 29 10:18:54 omv5box monit[489]: 'omv-engined' trying to restart
May 29 10:18:54 omv5box monit[489]: 'omv-engined' stop: '/bin/systemctl stop openmediavault-engined'
May 29 10:18:54 omv5box systemd[1]: Stopping The OpenMediaVault engine daemon that processes the RPC request...
May 29 10:18:54 omv5box systemd[1]: openmediavault-engined.service: Succeeded.
May 29 10:18:54 omv5box systemd[1]: Stopped The OpenMediaVault engine daemon that processes the RPC request.
May 29 10:18:54 omv5box monit[489]: 'omv-engined' start: '/bin/systemctl start openmediavault-engined'
May 29 10:18:54 omv5box systemd[1]: Starting The OpenMediaVault engine daemon that processes the RPC request...
May 29 10:18:54 omv5box systemd[1]: openmediavault-engined.service: Can't open PID file /run/omv-engined.pid (yet?) after start: No such file or directory
May 29 10:18:54 omv5box systemd[1]: openmediavault-engined.service: Supervising process 3113 which is not our child. We'll most likely not notice when it exits.
May 29 10:18:54 omv5box systemd[1]: Started The OpenMediaVault engine daemon that processes the RPC request.
May 29 10:18:54 omv5box monit[489]: 'omv-engined' restart action done

```

**Comment by OMMJAI** [comment]
> Never saw that. Please tell us which hardware platform you are using.

Using x86
hp ml350 g6
Started getting these errors since last 2-3 updates of omv
Is left over process anything to be concerned about or can I ignore it

**Comment by OMMJAI** [comment]
May 29 10:18:54 omv5box systemd[1]: openmediavault-engined.service: Supervising process 3113 which is not our child. We'll most likely not notice when it exits.>
Is this also normal

**Comment by votdev** [comment]
> Is left over process anything to be concerned about or can I ignore it

You can ignore it

**Comment by votdev** [comment]
> `May 29 10:18:54 omv5box systemd[1]: openmediavault-engined.service: Supervising process 3113 which is not our child. We'll most likely not notice when it exits.`
> Is this also normal

No idea what systemd is complaining about here because the unit file explicitly tells systemd that `omv-engined` is a forking daemon. 

```
[Service]
Type=forking
PIDFile=/run/omv-engined.pid
ExecStart=/usr/sbin/omv-engined
...
```

Because of that the PID systemd knows about after the exec has been started is terminated after the daemon has been forked. The PID file contains the PID (here 3113) of the real daemon  process. 


```
root@omv5box:/home/vagrant# systemctl status openmediavault-engined.service 
● openmediavault-engined.service - The OpenMediaVault engine daemon that processes the RPC request
   Loaded: loaded (/lib/systemd/system/openmediavault-engined.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-05-29 10:18:54 UTC; 39min ago
  Process: 3102 ExecStart=/usr/sbin/omv-engined (code=exited, status=0/SUCCESS)
 Main PID: 3113 (omv-engined)
    Tasks: 1 (limit: 2339)
   Memory: 10.0M
   CGroup: /system.slice/openmediavault-engined.service
           └─3113 omv-engined

root@omv5box:/home/vagrant# cat /run/omv-engined.pid
3113
```

With this information the message sounds reasonable, because indeed systemd is now supervising a process that was not started by itself. But thats how forking daemons work.

Because of that you can ignore that, too.
