### ISSUE TITLE
Improper Addition of New Disk

### ISSUE THREAD

**Issue by gderf** [openmediavault/openmediavault#104]
OMV 4.1.6 (AMD64)

When adding a new disk to the system, an improper entry is made into the fstab section of config.xml. The result of this is that the new disk does not appear in any drop-down lists where drives may be selected and also results in an incorrect /etc/fstab entry.

Below is the defective mtent entry in config.xml:

> <mntent>
        <uuid>a9c72e53-4144-4975-9bee-269bf9c7089e</uuid>
        <fsname>/dev/disk/by-label/d5</fsname>
        <dir>srv/dev-disk-by-label-d5</dir>
        <type>ext4</type>
        <opts>defaults,nofail,user_xattr,exec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl</opts>
        <freq>0</freq>
        <passno>2</passno>
        <hidden>0</hidden>
      </mntent>

The error is in this line:
`<dir>srv/dev-disk-by-label-d5</dir>`

(missing forward slash just before srv)

The correct line is:

`<dir>/srv/dev-disk-by-label-d5</dir>`

**Comment by votdev** [comment]
Please check the /etc/default/openmediavault file how OMV_MOUNT_DIR is defined. This must be srv instead of /srv in your case.

**Comment by votdev** [comment]
Can not reproduce this behavior. He most possible reason might be that the file /etc/default/openmediavault was modified manually.

**Comment by gderf** [comment]
Yes, I have made other changes to /etc/default/openmediavault over the years.

Makes no difference how I have it in /etc/default/openmediavault - config.xml is written without the forward slash and the disk remains missing in drop down lists.

What else can I do to help tracking this down?

**Comment by votdev** [comment]
You need to restart omv-engined after changing the settings in /etc/default/openmediavault.

``# monit restart omv-engined``

**Comment by gderf** [comment]
Thank you, this is now solved.

Perhaps adding a hint about having to run the "monit restart omv-engined" command to the top of /etc/defualt/openmediavalut file could be considered.

The content was:

OMV_MOUNT_DIR="srv"

I have no idea when it got changed away from proper and it has been a very long time since I have added a new disk to OMV making the error unnoticed until now.

Thanks again.
