### ISSUE TITLE
[GUIDE] Add custom log files to WebUI - not working

### ISSUE THREAD

**Issue by Kamikaze01git** [openmediavault/openmediavault#1049]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**
chek

**Describe the bug**
Canot add custom log files to WebUI with this [guide from 20106](https://forum.openmediavault.org/index.php?thread/15438-guide-add-custom-log-files-to-webui/)

**To Reproduce**
use attached [FilesToReproduce.zip](https://github.com/openmediavault/openmediavault/files/6677035/FilesToReproduce.zip) Files and follow the guide from 2016

1. Go to '/var/log/' and copy my attached MyLogFile.log into folder
1. Go to '/usr/share/openmediavault/engined/inc/' and copy my attached 99mylogspecs.inc into folder
2. Go to '/var/www/openmediavault/js/omv/module/admin/diagnostic/log/plugin' and copy my attached MyLogFile.js into folder
3. Restart OMV
4. Nothing changed in the WebGUI / Logs

**Expected behavior**
There sould be an extra custom Log in the WebGUI named "MyLogFile" with some dummy rsync entries.

**Screenshots**
![image](https://user-images.githubusercontent.com/80671394/122508982-3c4b9e00-d003-11eb-8fdc-64e58eeddb7a.png)

**Reference to Forum**
[Guide from 2016](https://forum.openmediavault.org/index.php?thread/15438-guide-add-custom-log-files-to-webui/)
[Discussion Thread](https://forum.openmediavault.org/index.php?thread/39429-add-additional-log-file-to-the-web-gui/)

**openmediavault Server (please complete the following information):**
- OS version:
Linux _Hostname_ 5.10.0-0.bpo.5-amd64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) x86_64 GNU/Linux

- openmediavault version:
ii  omvextras-unionbackend           5.0.2                               all          union filesystems backend plugin for openmediavault
ii  openmediavault                   5.6.9-1                             all          openmediavault - The open network attached storage solution
ii  openmediavault-backup            5.2.4                               all          backup plugin for OpenMediaVault.
ii  openmediavault-keyring           1.0                                 all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg      5.6.1                               all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-unionfilesystems  5.1.2                               all          Union filesystems plugin for OpenMediaVault.

**Client (please complete the following information):**

- Device: PC
- OS: Windwos 10 (20H2)
- Browser: Google Chrome
- Version 91.0.4472.106 

**Additional context**
for _99mylogsprecs.inc_ i orienteted myself on 90logfilespecs.inc in the same directory
for _MyLogFile.js_ i orienteted myself on Rsync.js in the same directory
also tried different ways (eg the date format in 99mylogspecs.inc)

**Comment by ryecoaaron** [comment]
This really should be a forum thread since OMV isn't causing the problem....

Did you set permissions on the javascript files?
Did you open the browser's F12 debugger to see if there is an error?
DId you start omv-engined in debug mode to see if there is an error?

**Comment by ryecoaaron** [comment]
Also, your filename is wrong in php register file
  "filename" => "MyLogFile",

**Comment by Kamikaze01git** [comment]
> This really should be a forum thread since OMV isn't causing the problem....

yeah - but forum told me to open github issue

************
> Did you set permissions on the javascript files?

Permission set on all files the same
![image](https://user-images.githubusercontent.com/80671394/123080182-f33d8480-d41c-11eb-97c5-86575f3930d5.png)

![image](https://user-images.githubusercontent.com/80671394/123081995-d99d3c80-d41e-11eb-9046-31fb3381ece8.png)

************
> Did you open the browser's F12 debugger to see if there is an error?
> DId you start omv-engined in debug mode to see if there is an error?

no - i am not a programmer and not that experienced,... just followed the guid in the forum (which did not work).


************
> Also, your filename is wrong in php register file
> "filename" => "MyLogFile",

this is the name of the Test-Log i think...
i orientedet me on existing 90logfilespecs.ing
![image](https://user-images.githubusercontent.com/80671394/123079315-1d427700-d41c-11eb-8ad6-b9dc7f72250a.png)

so this is my 99mylogspecs.inc
![image](https://user-images.githubusercontent.com/80671394/123082647-8c6d9a80-d41f-11eb-836d-9c2edd8c142c.png)

**Comment by ryecoaaron** [comment]
> yeah - but forum told me to open github issue

Link?

> no - i am not a programmer and not that experienced,... just followed the guid in the forum (which did not work).

But it is not hard to see if there is an error.  Hard to help if you can't provide debug output.  And the guide is five years old written for a different version of OMV.

I guess maybe the filename isn't causing the error.  Never tried making them different in my plugins.

So, I just wasted a lot of time on this and it works.  Not sure what actually fixed but I am guessing the part that a plugin normally does.  try (as root not sudo):
monit stop omv-engined
source /usr/share/openmediavault/scripts/helper-functions
omv_install_locale
omv_install_fixperms
omv_purge_internal_cache
omv-engined -df

**Comment by mi-hol** [comment]
> Hard to help if you can't provide debug output.

Searching for "debug" has no hit in OMV doc.
Is there a guide that explains how to get debug output?
I could use it to add this to OMV doc

**Comment by ryecoaaron** [comment]
aaron@omv5dev:~$ sudo omv-engined -h
The RPC daemon. RPC request will be received via socket.
Usage:
  omv-engined [options]

OPTIONS:
  -d --debug       Enable debug mode
  -f --foreground  Run in foreground
  -h --help        Print a help text
  -x --xdebug      Enable XDebug compatibility mode

**Comment by mi-hol** [comment]
@Kamikaze01git could you try to login as user root and execute the commands below to get more information?

```
monit stop omv-engined
source /usr/share/openmediavault/scripts/helper-functions
omv_install_locale
omv_install_fixperms
omv_purge_internal_cache
omv-engined -df
```

**Comment by Kamikaze01git** [comment]
I entered the above commands yesterday in the early morning, and the last command _"omv-engined -df"_ took **all day and all night**. I don't know what exactly happened here, but the output went through every single process... And that took a really (REALLY) long time.

**BUT:**
Now in the morning, after a restart **IT WORKS** !! I didn't believe in it anymore, but now I have the desired custom log in WegGui.
![image](https://user-images.githubusercontent.com/80671394/123371200-8d1e4200-d581-11eb-85e8-13a6b8c45f2d.png)

Yippi Yippi YEAH !!!
Thank you all for your really dedicated help
@ryecoaaron 🥇 
@mi-hol  🥇

**Comment by ryecoaaron** [comment]
omv-engined -df never ends because it is running the engine in the foreground and daemon mode. If that doesn’t show errors, then your system should be ok. Rebooting is the easiest way to get it out of debug mode.

**Comment by Kamikaze01git** [comment]
LooL
You should have told me that before!!
I left my machine running whole day and night :-D

Anyway: now it worked an is up running.

Thank U again for your help !!
