### ISSUE TITLE
Issues with encryption

### ISSUE THREAD

**Issue by thebang2** [openmediavault/openmediavault#105]
Installed OMV with debian-nas-stretch-18.069-armhf.img.gz und linux-image-3.16.39-1-nsa325-armel.zip on my NAS-542. Tried to crypt my Raid with Luks, but  is not working:

As I understand, Luks0pen is waiting for udev:
```
--> cryptsetup.log.txt
# Udev cookie 0xd4d4ab0 (semid 32769) waiting for zero
```

Inside the udev log, the requist is visible. Look like it takes to long and is killed.
```
--> udev.log.txt
May 11 19:33:52 debian-nas systemd-udevd[275]: seq 923 '/devices/virtual/block/dm-0' is taking a long time
May 11 19:35:51 debian-nas systemd-udevd[275]: seq 923 '/devices/virtual/block/dm-0' killed
```

```
--> dmesg.log.txt
[  699
.615779] ocf_crypt_convert: rd work was not finished in 300000 msecs, 8 pending 0 completed.
[  699.624585] kcryptd_crypt_read_convert() ocf_crypt_convert failed
[  699.632272] Buffer I/O error on device dm-0, logical block 976691184
```

Is this a known problem?
[cryptsetup.log.txt]

(https://github.com/openmediavault/openmediavault/files/1998590/cryptsetup.log.txt)
[dmesg.log.txt](https://github.com/openmediavault/openmediavault/files/1998591/dmesg.log.txt)
[udev.log.txt](https://github.com/openmediavault/openmediavault/files/1998592/udev.log.txt)

**Comment by ryecoaaron** [comment]
This should be filed here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/issues

**Comment by ryecoaaron** [comment]
And just a warning that omv-extras doesn’t supprt armel on OMV 3.x and 4.x.

**Comment by thebang2** [comment]
Sorry, my  fault - I mean "linux-image-3.2.96-3-nas5xx-armhf.zip" for the NAS542, not armel for nas325 - copy-paste error...

Sorry for asking, this is my first report - should I recreate this in the luksencryption-area or is it possible to move this issue?

**Comment by votdev** [comment]
Please create a new report, it's not possible to move them.
