### ISSUE TITLE
Dashbord Ordering objects (6.x)

### ISSUE THREAD

**Issue by long-walk** [openmediavault/openmediavault#1055]
**Describe the bug**

The Dasbord has some problems if you add all content that exist.
* If you like to have the setup from firs Screenshot you need to suggest how many space the next elements need to  be aligned.
* ---If screen is loaded the order moves until content has loaded.--- fixed in omv 10.0-11
* if you like to modify the order the preferences window is not like saved before and you have to reorder the full list

**Expected behavior**
maybe you can make 3 columns in the Setup window to drag an drop it to the right column then you can save the order of every column separately. 

**Screenshots**

![omv2](https://user-images.githubusercontent.com/56696022/123560136-d698a800-d7a0-11eb-9cbf-e68146ea3aa7.jpg)
![omv3](https://user-images.githubusercontent.com/56696022/123560140-da2c2f00-d7a0-11eb-81e9-a0a16bb17fc3.jpg)
![omv4](https://user-images.githubusercontent.com/56696022/123560143-dbf5f280-d7a0-11eb-8b18-aef8a369269d.jpg)

- OS version: [uname -a]
Linux NAS 5.10.0-7-686 #1 SMP Debian 5.10.40-1 (2021-05-28) i686 GNU/Linux
ii  openmediavault                 6.0-10                         all          openmediavault - The open network attached storage solution
ii  openmediavault-diskstats       6.0-2                          all          openmediavault disk monitoring plugin
ii  openmediavault-keyring         1.0                            all          GnuPG archive keys of the OpenMediaVault archive

**Client (please complete the following information):**

- Device: PC
- OS: Fedora 33
- Browser: Self compiled Firefox  
- 91.0a1 (2021-06-26) (64-bit)

**Additional context**

Thanks for your grate work for this Project

**Comment by votdev** [comment]
For the moment ordering of the widgets does not work and i assume it will not be enabled anymore because the ordering is done automatically by the layout engine. I think the ability to reorder the configuration items implies that the order of the widgets is the same on the dashboard. Removing the ability to reorder the boxes in the settings page should help here.

**Comment by long-walk** [comment]
Yes the ordering option suggest that you can order the Dashboard and in real you can order the dashboard if I put in the items in this order to the Settings you get the right order like in the fist picture.  
![omv5](https://user-images.githubusercontent.com/56696022/123647895-c7f5d380-d828-11eb-985b-107d656f6eb1.jpg)
but if you open the settings again the order is now another and if you save it it you get now another order. Expected is that if you open the Settings then save it without any changes that the Dasbord order stays as before but it changed.
If you remove the order option than you have to remove all items from the screen and add them again in the right order to get the  same order again.

**Comment by long-walk** [comment]
Yes the ordering option suggest that you can order the Dashboard and in real you can order the dashboard if I put in the items in this order to the Settings you get the right order like in the fist picture.  
![omv5](https://user-images.githubusercontent.com/56696022/123647895-c7f5d380-d828-11eb-985b-107d656f6eb1.jpg)
but if you open the settings again the order is now another and if you save it it you get now another order. Expected is that if you open the Settings then save it without any changes that the Dasbord order stays as before but it changed.
If you remove the order option than you have to remove all items from the screen and add them again in the right order to get the  same order again.

**Comment by votdev** [comment]
The design of the page has been modified to do not imply that any sorting is possible.

![Bildschirmfoto vom 2021-06-28 20-15-24](https://user-images.githubusercontent.com/1897962/123684524-ddc9bf80-d84d-11eb-9b3c-f31d706afdf2.png)
