### ISSUE TITLE
Cannot make use of VLAN-aware bridging via Webinterface

### ISSUE THREAD

**Issue by marcquark** [openmediavault/openmediavault#1059]
**Describe the bug**

In a setup where Openmediavault's main network interface is a bridge (this is useful e.g. when running VMs on the machine that should be bridged to the physical network), it is not possible to create a VLAN interface on top of that bridge. Netplan throws an error stating the the bridge interface is not defined. That's because the ordering of interfaces is twisted.
```
root@nas:/etc/netplan# ls -alh
total 32K
drwxr-xr-x   2 root root 4.0K Jun 30 18:19 .
drwxr-xr-x 123 root root  12K Jun 30 18:17 ..
-rw-r--r--   1 root root   43 Jun 30 18:17 10-openmediavault-default.yaml
-rw-r--r--   1 root root  117 Jun 30 18:17 50-openmediavault-br0.10.yaml
-rw-r--r--   1 root root  365 Jun 30 18:17 60-openmediavault-br0.yaml
```
The issue is easily fixed by hand by turning the "50-" prefix into, for example, "70" and then running `netplan apply`

**To Reproduce**

1. Create an interface br0
2. Try to add a VLAN to the bridge like br0.10

**Expected behavior**

The order should be fixed so that VLANs on bridges are defined after the bridges, otherwise netplan 

**Screenshots**

-

**Reference to Forum**

-

**openmediavault Server (please complete the following information):**

- OS version: Linux nas 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux
- openmediavault version: 5.6.10
Openmediavault was installed ontop of Debian manually, but that shouldn't make any difference in this case.

**Client (please complete the following information):**

(not applicable)

**Additional context**

How would i go about creating a PR to fix this behaviour in Openmediavault 6, but also to have the fix backported into OMV5?

**Comment by marcquark** [comment]
Since Linux supports both bridges ontop of VLAN devices aswell as VLANs ontop of bridges, this is not trivially solved by changing the order completely. The VLANs with index 50 would probably have to use a more refined filter query to get all interfaces of type VLAN whose vlan_raw_device name does not contain "br", and then another file with index 70 would have to be created with all interfaces of type VLAN whose vlan_raw_device _does_ contain "br".
I'm not sure whether this is currently possible with `omv_conf.get_by_filter` as seen in https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/50vlan.sls

**Comment by PrplHaz4** [comment]
A similar issue came up in the KVM plugin - might be worth looking at how that manages the interface setup...

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-kvm

**Comment by ryecoaaron** [comment]
The kvm plugin uses OMV provided functions.

**Comment by marcquark** [comment]
It kinda works when doing it the other way round i.e. creating a VLAN interface and then adding a bridge with said interface as slave. However setting that up involved manually editing config.xml at least twice, because the Web GUI did not offer me the appropriate interfaces to select. That could just be related to my setup though, i'm not entirely sure. Anyway, i now at least have a configuration that i'm able to "Apply" without errors

**Comment by votdev** [comment]
Building the network interface configuration is already very complex and the UI is not designed to support all possible scenarios out in the wild. From the projects point of view all relevant setups are possible. If the community wants to have more, then contributions are welcome.

> How would i go about creating a PR to fix this behaviour in Openmediavault 6, but also to have the fix backported into OMV5?

Such big and error-prone changes will not be backported to OMV5, new features like this will only go into OMV6.

**Comment by hoppel118** [comment]
Hi, I am using Openmediavault 6 and would like to create a bridge with vlan interfaces ontop.

The bridge works as expected. But when I try to create a vlan interface on it, I get the following error message:

```
500 - Internal Server Error
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color systemd-networkd 2>&1' with exit code '1': debian: ---------- ID: remove_systemd_networkd_config_files Function: module.run Result: True Comment: file.find: [] Started: 16:08:15.368985 Duration: 1.238 ms Changes: ---------- file.find: ---------- ID: remove_empty_systemd_networkd_config_files Function: module.run Result: True Comment: file.find: [] Started: 16:08:15.370332 Duration: 0.89 ms Changes: ---------- file.find: ---------- ID: remove_netplan_config_files Function: module.run Result: True Comment: file.find: ['/etc/netplan/10-openmediavault-default.yaml', '/etc/netplan/20-openmediavault-eno1.yaml', '/etc/netplan/60-openmediavault-br0.yaml'] Started: 16:08:15.371312 Duration: 1.168 ms Changes: ---------- file.find: - /etc/netplan/10-openmediavault-default.yaml - /etc/netplan/20-openmediavault-eno1.yaml - /etc/netplan/60-openmediavault-br0.yaml ---------- ID: configure_etc_network_interfaces Function: file.managed Name: /etc/network/interfaces Result: True Comment: File /etc/network/interfaces is in the correct state
```

The issue is "Closed", but its not solved.

Any idea for a workaround?

Thanks Hoppel

**Comment by marcquark** [comment]
As briefly touched on in this discussion, adding support for combinations of bridges and VLANs to the UI is not a trivial change to the code. Hence at least i personally ditched the idea. Instead, one can always go to `/etc/netplan` and manually add yaml files there. OMV won't touch them. So you could just create `90-whatever.yaml` and add your VLANs there. Hope that helps.
