### ISSUE TITLE
Allow multiple UPS devices to be monitored

### ISSUE THREAD

**Issue by syphr42** [openmediavault/openmediavault#1060]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
OMV currently allows you to monitor a single device (local or remote). However, for a network storage server it is not uncommon to have two power supplies and for them to be connected to separate UPS devices (as is the case for me). I would like to monitor both which NUT can do, but it is not currently possible to configure that in OMV.

**Describe alternatives you've considered**
Without fighting the OMV config, I guess I would have to attach my UPS monitors to another machine and then write an intermediate script that would monitor them remotely as a NUT client and shutdown the OMV machine when it detects low battery. Essentially recreate the NUT client, I believe. Enhancing OMV seems like a better route.

**Additional context**
No other context on this.

**Comment by votdev** [comment]
Please don't expect this implemented from the OMV developers because the current plugin matches 99.9% of all user requirements. If this feature is really required, contributions from the community are welcome.

**Comment by insp1re2600** [comment]
> Please don't expect this implemented from the OMV developers because the current plugin matches 99.9% of all user requirements. If this feature is really required, contributions from the community are welcome.

cant even monitor one ups in omv 6 nevermind multiple.

**Comment by mi-hol** [comment]
> cant even monitor one ups in omv 6

This issue was resolved

**Comment by insp1re2600** [comment]
Fucked

**Comment by insp1re2600** [comment]
Slam my cock up ya
