### ISSUE TITLE
openmediavault 6.x should mark alpha in download page

### ISSUE THREAD

**Issue by YangshengLu** [openmediavault/openmediavault#1067]
openmediavault is not stable release. But from official site: https://www.openmediavault.org/ to download page, user cann't find any preview or alpha mark on download link. They could be wrong to use 6.x in production environment.
![image](https://user-images.githubusercontent.com/4264470/126056335-9c9ed15d-d438-4283-9b1d-a73a7245c75e.png)
![image](https://user-images.githubusercontent.com/4264470/126056378-4c7c07fc-eefa-4c98-a396-f68316a56b7f.png)

**Comment by votdev** [comment]
Fixed.
- Homepage has been adapted: https://www.openmediavault.org/?page_id=77
- `Latest download` link on Sourceforge has been set to 5.x

**Comment by mi-hol** [comment]
> * `Latest download` link on Sourceforge

should this be labeled "Latest stable version" instead to align wording with OMV homepage?

**Comment by votdev** [comment]
> > * `Latest download` link on Sourceforge
> 
> should this be labeled "Latest stable version" instead to align wording with OMV homepage?

IMO the SF wording is incorrect or not specific enough. Should i change a correct and specific wording on the OMV side to something that is less correct? I don't think so. I assume everyone has enough brainpower to understand the connection.
