### ISSUE TITLE
Add PUID/PGID column in user/group section

### ISSUE THREAD

**Issue by ken8521** [openmediavault/openmediavault#1068]
Since PUID/PGID's come up a lot for dockers, would it be possible to add a column for the PUID/PGID to be displayed in the webUI under the users/groups section?

Unless I'm missing it somewhere, it seems the only place to get this info is from the command line, which as we all know many new users have an aversion to.

**Comment by votdev** [comment]
OMV6:
![Peek 2021-07-27 11-11](https://user-images.githubusercontent.com/1897962/127128544-467111ce-9475-45c7-80ca-47910431d695.gif)

**Comment by ken8521** [comment]
Hmm, Obviously I was missing it.
