### ISSUE TITLE
Cannot update OMV

### ISSUE THREAD

**Issue by Tzushca** [openmediavault/openmediavault#1069]
Since a week ago I started having problems with the updates and I constantly get this error when trying to check for updates:\

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; apt-get update 2>&1' with exit code '100': Get:1 file:/var/cache/openmediavault/archives InRelease Ign:1 file:/var/cache/openmediavault/archives InRelease Get:2 file:/var/cache/openmediavault/archives Release Ign:2 file:/var/cache/openmediavault/archives Release Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Get:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Hit:5 http://security.debian.org/debian-security buster/updates InRelease Hit:6 http://httpredir.debian.org/debian buster-backports InRelease Hit:7 https://download.docker.com/linux/debian buster InRelease Hit:8 http://deb.debian.org/debian buster InRelease Hit:9 https://openmediavault.github.io/packages usul InRelease Hit:10 http://deb.debian.org/debian buster-updates InRelease Hit:11 http://packages.openmediavault.org/public usul InRelease Err:12 https://dl.bintray.com/openmediavault-plugin-developers/usul buster InRelease 403 Forbidden [IP: 52.38.32.109 443] Err:13 https://dl.bintray.com/openmediavault-plugin-developers/usul-extras buster InRelease 403 Forbidden [IP: 52.38.32.109 443] Reading package lists... E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/dists/buster/InRelease 403 Forbidden [IP: 52.38.32.109 443] E: The repository 'https://dl.bintray.com/openmediavault-plugin-developers/usul buster InRelease' is not signed. E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul-extras/dists/buster/InRelease 403 Forbidden [IP: 52.38.32.109 443] E: The repository 'https://dl.bintray.com/openmediavault-plugin-developers/usul-extras buster InRelease' is not signed.

In details:
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; apt-get update 2>&1' with exit code '100': Get:1 file:/var/cache/openmediavault/archives  InRelease
Ign:1 file:/var/cache/openmediavault/archives  InRelease
Get:2 file:/var/cache/openmediavault/archives  Release
Ign:2 file:/var/cache/openmediavault/archives  Release
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Hit:5 http://deb.debian.org/debian buster InRelease
Hit:6 http://security.debian.org/debian-security buster/updates InRelease
Hit:7 http://deb.debian.org/debian buster-updates InRelease
Hit:8 http://httpredir.debian.org/debian buster-backports InRelease
Hit:9 http://packages.openmediavault.org/public usul InRelease
Hit:10 https://download.docker.com/linux/debian buster InRelease
Hit:11 https://openmediavault.github.io/packages usul InRelease
Err:12 https://dl.bintray.com/openmediavault-plugin-developers/usul buster InRelease
  403  Forbidden [IP: 35.164.5.2 443]
Err:13 https://dl.bintray.com/openmediavault-plugin-developers/usul-extras buster InRelease
  403  Forbidden [IP: 35.164.5.2 443]
Reading package lists...

E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/dists/buster/InRelease  403  Forbidden [IP: 35.164.5.2 443]
E: The repository 'https://dl.bintray.com/openmediavault-plugin-developers/usul buster InRelease' is not signed.
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul-extras/dists/buster/InRelease  403  Forbidden [IP: 35.164.5.2 443]
E: The repository 'https://dl.bintray.com/openmediavault-plugin-developers/usul-extras buster InRelease' is not signed. in /usr/share/openmediavault/engined/rpc/apt.inc:245
Stack trace:
#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): Engined\Rpc\Apt->Engined\Rpc\{closure}('/tmp/bgstatusgY...', '/tmp/bgoutputH9...')
#1 /usr/share/openmediavault/engined/rpc/apt.inc(249): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#2 [internal function]: Engined\Rpc\Apt->update(NULL, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('update', NULL, Array)
#5 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Apt', 'update', NULL, Array, 1)
#6 {main}

Can you please help!

Thank you!

**Comment by ryecoaaron** [comment]
https://forum.openmediavault.org/index.php?thread/37980-omv-extras-repos-moving-to-github/
