### ISSUE TITLE
[Feature request] Improve notification

### ISSUE THREAD

**Issue by Ansem93** [openmediavault/openmediavault#107]
Hi, I wanted to ask if it's possible to improve notification with some of this suggestion:
1) Let us choose if we want a notification every time we log on the webinterface
2) More control on notification from CPU/RAM/HDD monitoring. Example: let us choose the % of CPU usage or the temp of the hard driver for what we want a notificatin. So I can set to recieve an email when the CPU is at 50% or when the hdd1(or any if set up threshold for every HDD is too complicated) reach 45°
3) Maybe I'm doing something wrong, but I never recieved an email saying that the SMART test was OK. There is some way to send a weekly/monthly report with SMART test of every HDD even if there is nothing wrong? Something like hdd1 - OK, hdd2 - OK, ecc.

**Comment by votdev** [comment]
1. You will only get this email if no cookie exists. Make sure the browser does not remove them after closing. And no, there won't be an option to diable this, sorry.
2. You can modify the settings via environment variables, see https://github.com/openmediavault/openmediavault/blob/4.x/deb/openmediavault/usr/share/openmediavault/mkconf/monit.d/system or https://github.com/openmediavault/openmediavault/blob/4.x/deb/openmediavault/usr/share/openmediavault/mkconf/monit.d/filesystem. There will be no UI to modify them.
3. If smartctl does not output anything, then you won't get an email.

**Comment by Ansem93** [comment]
1) I usually use this app this I only check for update: https://play.google.com/store/apps/details?id=com.dev.doods.omvremote2 . Should I link this page to the developer so that he can correct the application?
2) Sadly to hear that, edit files is a lot more difficult and easy to make something wrong :( 
3) I don't know how smartctl works :( there is no way to force an output when using the "smart" page of the webwui?

**Comment by Ansem93** [comment]
Thanks for the answers! :)
