### ISSUE TITLE
Shared Folders not showing ZFS filesystems (single drive zpools) currently

### ISSUE THREAD

**Issue by ylluminate** [openmediavault/openmediavault#1070]
There currently appears to be a bug wherein ZFS filesystems aren't enumerated by `getCandidates` in [Shared Folders](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/src/app/pages/storage/shared-folders/shared-folder-form-page.component.ts#L73) (_and apparently defined here in [`engined/rpc/sharemgmt.inc`](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/sharemgmt.inc#L63)_), eg:

![shared folders add device](https://p153.p0.n0.cdn.getcloudapp.com/items/9ZuQlx7D/69c8bbde-9a4b-4d2d-896d-cc59b9b6797d.png?v=9c92f1e62b2f42d278231f0acd09ee05)

The above list is empty and has no drives in my case. 

This, for example, also holds true for [other plugins](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/issues/29) that use this function for device enumeration.

**Expected behavior**

This should enumerate (simple, single drive) ZFS volumes. In this particular case, ZFS is being used as a simple filesystem without raidz[1,2,3] and only on singular drives to facilitate compression and broad support (since in my case ZFS is supported on more systems locally than EXT4, for example).

**openmediavault Server (please complete the following information):**

- OS version: `5.10.0-0.bpo.7-amd64 #1 SMP Debian 5.10.40-1~bpo10+1 (2021-06-04)`
- openmediavault version: `5.6.13-1`

**Comment by ryecoaaron** [comment]
This is not an OMV bug.  It is probably something with the zfs plugin's backend.

**Comment by ylluminate** [comment]
Thanks @ryecoaaron, I know you're overly busy with your 6 efforts, I'm in the process of understanding how/where [conf.system.sharedfolder](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/sharemgmt.inc#L70) is set/generated so I can understand the full pipeline. I suspect then this can give me some understanding of how it's done properly and then I can address [openmediavault-zfs](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs)'s backend such that it provides whatever is necessary in a correct manner.

**Comment by ryecoaaron** [comment]
There are lots of people using the zfs plugin and I assume they are creating sharedfolders.  I'm wondering how your zfs seutp is done.  Can you please post on the forum to have more eyes on this.

**Comment by ylluminate** [comment]
Sure thing @ryecoaaron: https://forum.openmediavault.org/index.php?thread/39866-simple-single-disk-zfs-volumes-not-showing-up-in-shared-folders/

**Comment by votdev** [comment]
Have you mounted the file system? The dropdown box only shows file systems that have an existing mount point configuration object in the database.

What is the output of `omv-confdbadm read --prettify conf.system.filesystem.mountpoint`?

**Comment by ylluminate** [comment]
@ryecoaaron thanks for suggesting that I post that to the forum - a second review just doing various sanity checks revealed some additional critical information and @votdev was correct in his assertion that the issue was that mountpoints were not defined during my zpool creation. I was under some wrong impressions and updated the forum post accordingly and this can be considered resolved.

Thanks again!

**Comment by mhalano** [comment]
Related to this, using OMV7 with ZFS 2.3.1, my ZFS is mounted, but under /zfspool, the default mount point. To show up should I put under other place, like /mnt?

**Comment by votdev** [comment]
> Related to this, using OMV7 with ZFS 2.3.1, my ZFS is mounted, but under /zfspool, the default mount point. To show up should I put under other place, like /mnt?

Filesystems MUST be under the control of OMV to be shown in the shared folder dialog. This seems not to be the case here.

**Comment by mhalano** [comment]
@votdev I understand. I'm using ZFS-plugin. There is a way to do that? I tried to manually umount and mount over the web GUI but I got a 400 error because zfspool doesn't seem a valid device.

**Comment by ryecoaaron** [comment]
Did you click the Discover button in the zfs plugin?

**Comment by mhalano** [comment]
Actually I wasn't, but now I did and did the trick. Thanks. I presumed that I didn't because my zpools were being showed correctly. Thanks.

**Comment by mhalano** [comment]
My last problem, is it just detect my main pool, called zpool, not my subpool, called zfspool/media. I could create a shared folder and export over NFS, but it's using zfspool, even I would like to create using zfspool/media.

**Comment by mhalano** [comment]
NVM. I found that I need to discover all the pools. So I clicked in the subpool and started showing.
