### ISSUE TITLE
Stop touching /root/.{profile,bashrc} please.

### ISSUE THREAD

**Issue by derkallevombau** [openmediavault/openmediavault#1071]
OMV is great and I really appreciate votdev's work, so I have sort of a bad conscience to complain, but there is one thing that really gets on my nerves:

It didn't happen for a long time, but the last upgrade wiped out everything I had written into my /root/.{profile,bashrc}.
It's not a real problem since I have them in version control, but I would really appreciate it if OMV would stop touching these files.

Of course, OMV has to manage the config files of the services that can be configured via the web-if, but I don't see any reason why it would need to change root's .profile and/or .bashrc., especially since it doesn't write anything related to OMV to these files.

**Comment by ryecoaaron** [comment]
OMV should only overwrite it on setup.  Not sure what you did to trigger setup again.  And OMV is maintaining these files to eliminate emails from cron - https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/setup/shell/30root_profile.sls#L31.  If that line isn't there, people get emails on a lot of cron jobs (which run as root) when they shouldn't.  Lots of people complained about the emails.  You are the first I have seen that sets up bashrc and profile for the root user.

**Comment by votdev** [comment]
As mentioned by @ryecoaaron, these files are only touched during the first package installation (e.g. while building the ISO image). The mentioned files are not overwritten, they replace or append required things. Because of that i close this issue.
