### ISSUE TITLE
Could upgrade samba to 4.13?

### ISSUE THREAD

**Issue by akong77** [openmediavault/openmediavault#1073]
**Is your feature request related to a problem? Please describe.**
It's a samba bug.Please see this url.
https://bugzilla.redhat.com/show_bug.cgi?id=1780802

**Describe the solution you'd like**
It's problem maybe upgrade to samba 4.13 will fix it.

**Describe alternatives you've considered**
I think install other debian repo to upgrade it.But I think report to OMV first.
This repo url is https://apt.van-belle.nl/

**Additional context**
Please upgrade to samba 4.13 on OMV 5 if can do it.

**Comment by votdev** [comment]
OMV is strictly tied to what the Debian repository delivers. So for SMB this is right at the moment [4.9.5](https://packages.debian.org/buster/samba) for Debian 10 which is the base of OMV5. You can add additional repositories that deliver newer versions, but without warranty if the configuration build by OMV will work with that version.
