### ISSUE TITLE
 publish new releases via RSS feed on blog.openmediavault.org or github's "release" feature

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1074]
**Is your feature request related to a problem? Please describe.**
From my view many OMV instances (mainly of non-IT users) have NOT activated email notifications for a number of reasons. 
Often email is not used at all by this user community, instead they only use instant messaging.
This leaves these users unaware of new OMV version releases.

**Describe the solution you'd like**
Publish new releases via RSS feed because it's a user friendly and low effort approach to get notified. (i.e. GitLab https://about.gitlab.com/atom.xml)
RSS as a source is supported by the major email readers this means that the classic "email" user based can be reached too.

**Describe alternatives you've considered**

1. github's "watch" feature allows for simple subscribing to new release announcements
2. email from OMV instance

**Additional context**
start of conversation in

**Comment by votdev** [comment]
RSS feed is available via https://www.openmediavault.org/?feed=(rss|rss2|rdf|atom), e.g. https://www.openmediavault.org/?feed=atom.

The page footer contains a link to subscribe to RSS with atom format.
![Auswahl_002](https://user-images.githubusercontent.com/1897962/130616358-55930d0e-1027-419b-ae25-2d4fb5a2ba1f.png)
