### ISSUE TITLE
Need help to install cloudflared on raspberry pi 4

### ISSUE THREAD

**Issue by Kate222** [openmediavault/openmediavault#1075]
I currently use rpi 4 to host OMV. I have found this article regarding installing Cloudflared to rpi4. 
https://dev.to/omarcloud20/a-free-cloudflare-tunnel-running-on-a-raspberry-pi-1jid
I am not sure which one to use. Could anyone give me any suggestions? Many thanks

**Comment by mi-hol** [comment]
a better place to ask this is the OMV forum
