### ISSUE TITLE
github: enable automatically scanning your code for vulnerabilities and errors?

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1076]
**Is your feature request related to a problem? Please describe.**
Avoiding security issues is getting harder every day, maybe GH automation can help to retain the high code quality with less effort?

**Describe the solution you'd like**
Please see the feature description in https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning

**Describe alternatives you've considered**
none

**Comment by votdev** [comment]
This feature is already enabled.

**Comment by mi-hol** [comment]
I thought this would be visible via a required config file in .github/workflows/codeql-analysis.yml but there is none for openmediavault
