### ISSUE TITLE
github project 6.x seems to require update

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1077]
**Is your feature request related to a problem? Please describe.**
1. feature seems implemented but still shows as "in progress" in project view
![image](https://user-images.githubusercontent.com/22799428/130650243-ccf0865a-be87-47ba-99bf-2b84fca056e2.png)

2. with Debian 11 released, will anything from "planned" be worked on before release of 6.0?

**Comment by votdev** [comment]
2. If no version label and project has been assigned to a feature/issue, then it is still open and there are no plans to implement it in near future.
