### ISSUE TITLE
UI design of the bredcrumbs navigation

### ISSUE THREAD

**Issue by Tschoepler** [openmediavault/openmediavault#1081]
hi,

i always stumble over the breadcrumbs navigation in the top toolbar of omv as they are made with buttons rather then links. which is the default ux/ui pattern for breadcrumbs, as the elements in it are links leading to another page and not buttons for actions. also they conflict visually often with the (correct) buttons in each section's/page's toolbar.

hence, this is my humble request/proposal to change the design of the breadcrumbs to links (keep the home icon is fine but as a simple plain button without outline).

see also https://www.nngroup.com/articles/breadcrumbs/ for reference/best practices.

current implementation:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/2727803/131260769-5db2af09-f678-41b0-80cc-334b2ece4c68.png">

best,
jakob

**Comment by votdev** [comment]
OMV5 does not get any code changes anymore because it is in maintenance mode since some time. Active development is done in OMV6.

**Comment by votdev** [comment]
Breadcrumbs have been [refactored](https://github.com/openmediavault/openmediavault/commit/03ef56cbdc22167cf2824759e0758d4094d2d6d3) for OMV6.

![Bildschirmfoto von 2021-09-11 15-17-53](https://user-images.githubusercontent.com/1897962/132949160-b9359046-1ce5-4241-bb99-accd94de1eca.png)

**Comment by Tschoepler** [comment]
nice to see.

but why the color coding in the border-bottom of the breadcrumb? if you want to highlight the current position why not just make "Users" bold. this adds extra visual noise, when breadcrumbs should really just sit there and be quiet until needed. also the current page is obviously always the last one in the breadcrumb trail and i think your user group knows that as they are probably all power users (not uncommon at all to now highlight the last/active item as it is obvious and a very well known pattern on the web). but if you still think this needs some extra hinting, then i would suggest to go with bold font-weight instead of color coding both. or i just dont get why "user management" is marked yellow > is there a warning in user management? :/

best

**Comment by votdev** [comment]
> nice to see. this is much better.
> 
> i wonder why you use the color coding in the border-bottom of the breadcrumbs? if you want to highlight the current position why not just make "Users" bold. this adds extra visual noise, when breadcrumbs should really just sit there and be quiet until needed. also the current page is obviously always the last one in the breadcrumb trail and i think your user group knows that as they are probably all power users (not uncommon at all to now highlight the last/active item as it is obvious and a very well known pattern on the web). but if you still think this needs some extra hinting, then i would suggest to go with bold font-weight instead of color coding both. or i just dont get why "user management" is marked yellow > is there a warning in user management? :/
> 
> best

Thanks for all your suggestions, but i will keep the design as it is. Most of the design is inspired by design systems i know and i'm using in other projects.

**Comment by Tschoepler** [comment]
out of interest > which systems are they?
