### ISSUE TITLE
Constructor of services injected via DI is called to late

### ISSUE THREAD

**Issue by votdev** [openmediavault/openmediavault#1083]
The constructor of services that are injected via DI is called too late, e.g. [SystemInformationService](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/src/app/shared/services/system-information.service.ts). Because of that the [observable](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/src/app/shared/services/system-information.service.ts#L53) is not initiated and the [subscribers](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/src/app/core/components/top-bar/top-bar.component.ts#L89) are not notified on changes. This issue may apply to other services as well.

Resulting problems:
- The `Pending configuration changes` dialog is not shown
- The hostname is not displayed in the upper right corner of the header bar
- The `System Information` dashboard widget does not show any content

Tried to fix that with https://github.com/openmediavault/openmediavault/commit/3efe50b6dcd2a9e503ed29491f7b9de52a07a90c without success. The changes were undone via https://github.com/openmediavault/openmediavault/commit/d4f51fc38355086857001d34ad74f0c584d532b8.

IMO it seems to be a bug in Angular 12.2.3 that is related to DI or it is an Ivy issue.

The current workaround is to reload the page because this behavior only appears when the browser is started and the OMV workbench is opened the first time. The issue also does not appear in a new tab after the page was loaded once.

References:
- https://forum.openmediavault.org/index.php?thread/40111-apply-changes-dialog-not-showing/

**Comment by mi-hol** [comment]
@votdev The commit comment "Downgrading rxjs from 7.3.0 to 6.6.7 seems to fix the issue." seems to warrant a new issue because upgrading to a later version should be monitored for a fix of root cause.
What is your view?

**Comment by votdev** [comment]
> @votdev The commit comment "Downgrading rxjs from 7.3.0 to 6.6.7 seems to fix the issue." seems to warrant a new issue because upgrading to a later version should be monitored for a fix of root cause.
> What is your view?

Thanks to the [semantic versioning](https://docs.npmjs.com/about-semantic-versioning) in [package.json](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/package.json#L74) it is ensured that only minor versions will be upgraded.
