### ISSUE TITLE
[plugins] openmediavault-iscsitarget 3.1.6

### ISSUE THREAD

**Issue by onixd** [openmediavault/openmediavault#1084]
I have OMV 5.6.13 and try to install plugin openmediavault-iscsitarget 3.1.6, error:

--------------------------------------------------------------------------------------------------------------
 openmediavault-iscsitarget : Depends: iscsitarget but it is not installable
 Depends: iscsitarget-dkms but it is not installable
---------------------------------------------------------------------------------------------------------------

Download iscsitarget-module-2.6.31.14-hmnhdce_1.4.20.2-1_armel.deb and iscsitarget-module-dkms_0.3_all.deb, both won`t install:

---------------------------------------------------------------------------------------------------------------
Failed to upload package 'iscsitarget-module-2.6.31.14-hmnhdce_1.4.20.2
-1_armel.deb'. The package name does not match the plugin naming convention.
----------------------------------------------------------------------------------------------------------------

**Comment by ryecoaaron** [comment]
This plugin does not work on OMV 5.x and hasn't since OMV 3.x.
