### ISSUE TITLE
OMV6 Testing Issues with SMB shares

### ISSUE THREAD

**Issue by ThePapaw** [openmediavault/openmediavault#1085]
I am having issues with OMV6 installed on a external USB on a PC seeing SMB shares correctly from Nvidea Shield devices. The server (named NAS) can be mounted and explored fine with a android file explorer, but when I try to access any shared folders via SMB from Kodi or any other apps installed, they don't see anything.

All my PC on the same network see it fine, and map drives ok, but will not see SMB shares either.

Oddly though, a preconfigured copy of Kodi on the Nvidea Shields does read and write to the correct locations. I have another app that uses network shares for photos, it will not see the server, but does see the shared folders in the server. For example, the server name is NAS. The apps do not see it, but see shared folders on it, but not via SMB, if that makes any sense.

Not sure if I posted this in the right place and know it sounds confusing, posted in the fiorms and was told to come by here as well.

Also, I have a lot of issues with different web browsers as well, one time they work, next time they don't, especially chromium based browsers. FF and Edge works most of the time.

OMV5 works just fine with the same setup

**Comment by mi-hol** [comment]
Sounds like a configuration issue for SMB v3 protocol.
I'd recommend to discuss this issue further in the OMV forum
