### ISSUE TITLE
[Suggestion] [openmediavault-usbbackup] After unmounting, put disk into sleep state 

### ISSUE THREAD

**Issue by HannesJo0139** [openmediavault/openmediavault#1086]
I know that in general, linux does not have sth like an eject button for usb drives. After unmounting (or locking if needed), a drive can be unplugged securely. Modern drives will park their heads immediately when unmounted, so even if it's still spinning, it is objectively not necessary to do anything else. 

Nevertheless, I think there is major psychological factor here. Perhaps that is why eg ubuntu even offers a eject button and udisksctl has a power-off command. Lots of unexperienced users feel uncertain about it. They search for such a button, ask in forums, struggling to simply unplug their usb drive eg after a backup. Even me as a lets say semi-experienced user who is well informed about the facts: I noticed that it always feels a bit wrong to unplug my usb drive, feeling that it is still spinning.

So when I developed my own usbbackup plugin in order to handle encrypted drives, I looked for a solution for that and found that after unmounting and locking the drive, I can additionally send a `hdparm -Y /dev/disk/by-uuid/...` command, putting the drive to the lowest power consumption mode and causing it to shutdown. I wonder if you would consider adding that command to your usbbackup plugin as well or if you have any cons about it? Since OMV is designed to make a setup and it's handling as easy as possible for unexperienced users, one could even think of adding a eject button to the OMV GUI that would just use that command.

**Comment by votdev** [comment]
Sounds like a good idea to me. Does the disk spin up again when you plug the enclosure again? There was an equal idea to run the `eject` command, but the disk never gets recognized by the system until it was rebooted. See https://github.com/openmediavault/openmediavault/issues/763 and https://github.com/votdev/openmediavault/commit/fe5ef49448453b370b51bb27a5773a8b998dc6b0.

**Comment by votdev** [comment]
I checked the `hdparm` manual and indeed, `-Y` requires a reset/reboot of the system to access the disk again.

> A hard or soft reset is required before the drive can be accessed again.

I think `-y` is the better solution then. It will stop spinning the disk which will indicate users that they can unplug the disk/enclosure.

**Comment by votdev** [comment]
@HannesJo0139 Please have a look on PR #1087.

**Comment by HannesJo0139** [comment]
> > A hard or soft reset is required before the drive can be accessed again.

Well actually that part of hdparm manpage kind of confused me, cause in fact I don't need to reboot the system. Unplugging and plugging in again works like a charm even with -Y, while using -y I don't have to unplug and plugin again. Perhaps it is just about reset of the IDE controller or so? The manpage also says `(the Linux IDE driver will automatically handle issuing a reset if/when needed)`. 

Anyway, -y also does the trick. PR looks good! Thank U!
