### ISSUE TITLE
[Feature Request] Advanced details on dashboard

### ISSUE THREAD

**Issue by JS-E** [openmediavault/openmediavault#109]
Hey, 

Love OMV, but i'd really like to see some more advanced information on the dashboard screen, especially the ability to save the dashboard layout.

-CPU clock speeds/usage (by core)
-Top process
-Top Ram hog
-Top disk usage
-Top network usage process
-Update speed of page

Keep up the good work, this stuff is awesome 👍

**Comment by oneindelijk** [comment]
I second that

**Comment by mi-hol** [comment]
@JS-E @oneindelijk with Cockpit and many more tools available via container is this still a relevant request?

**Comment by votdev** [comment]
I think it is still relevant, because openmediavault workbench is the UI of OMV and not other tools. Because i'm not responsible for all features, i will add the label for external user contributions.
