### ISSUE TITLE
Make it possible to run custom nginx server blocks on port 80/443 

### ISSUE THREAD

**Issue by djmattyg007** [openmediavault/openmediavault#1093]
**Is your feature request related to a problem? Please describe.**

I'm struggling to sensibly set up a custom nginx server block because it claims there are port conflicts. I want to run a second server block on the same port as the main web GUI, but nginx fails to start.

**Describe the solution you'd like**

The configuration used for binding ports in the default nginx server block should be changed to avoid use of the `ipv6only` directive. Instead, two listen directives should be used - one for IPv4 and one for IPv6.

**Describe alternatives you've considered**

I can't think of one. Any change I make to the generated config file in /etc/nginx would be blown away the next time salt runs. Any change I make to the template would be blown away the next time openmediavault is updated.

**Additional context**

I think this patch solves the problem:

```patch
diff --git a/deb/openmediavault/srv/salt/omv/deploy/nginx/files/site-webgui.j2 b/deb/openmediavault/srv/salt/omv/deploy/nginx/files/site-webgui.j2
index aac15c938..24fd856a3 100644
--- a/deb/openmediavault/srv/salt/omv/deploy/nginx/files/site-webgui.j2
+++ b/deb/openmediavault/srv/salt/omv/deploy/nginx/files/site-webgui.j2
@@ -41,7 +41,8 @@ server {
 {%- endif %}
     }
 {%- if ipv6_enabled | to_bool %}
-    listen [::]:{{ config.port }} default_server ipv6only=off;
+    listen *:{{ config.port }} default_server;
+    listen [::]:{{ config.port }} default_server;
 {%- else %}
     listen {{ config.port }} default_server;
 {%- endif %}
@@ -53,7 +54,8 @@ server {
 {%- endif %}
 {%- if config.enablessl | to_bool %}
 {%- if ipv6_enabled | to_bool %}
-    listen [::]:{{ config.sslport }} default_server ipv6only=off ssl deferred;
+    listen *:{{ config.sslport }} default_server ssl deferred;
+    listen [::]:{{ config.sslport }} default_server ssl deferred;
 {%- else %}
     listen {{ config.sslport }} default_server ssl deferred;
 {%- endif %}
```

**Comment by votdev** [comment]
This looks OK to me. Nevertheless, for the time being I would only make this change in OMV6, since there is still the possibility of breaking existing OMV5 installations with this change.
