### ISSUE TITLE
Run rsync in dry-run mode without having to edit task (and apply)

### ISSUE THREAD

**Issue by Adam5Wu** [openmediavault/openmediavault#1094]
**Is your feature request related to a problem? Please describe.**

I have a manual-triggered rsync task, which I'd often like to dry-run first to get an impression of the operations.
Currently I have to:
1. edit task - toggle on "trial run" - save - wait for the top "apply" banner - click apply and wait - run task in dry-run; and then
2. edit task - toggle off "trial run" - save - wait for the top "apply" banner - click apply and wait - run task to commit updates;

The process get old rather quickly.

**Describe the solution you'd like**

The dry-run feature is primarily intended for interactive uses, so it should not be part of rsync task configuration. Not just for manual-triggered rsync, even for scheduled tasks I can hardly think of any use for someone to set the task to be always in dry-run mode.

- Remove "Trial run" toggle from rsync task settings, instead add a "Trial Run" action button
- Clicking the "Trial Run" button will bring out a task execution dialog, just like clicking the "Run" button; except that
- Clicking "Start" in the "Trial Run" task execution dialog will run the rsync in dry-run mode.

**Describe alternatives you've considered**

Add a "Trial run" button on the rsync task's "Run" dialog, alongside with "Start" button, and clicking the "Trial run" will run the task in dry-run mode. Given the current "Run" dialog is shared across all task executions, this approach would require sub-classing a dedicated dialog for rsync tasks, which could be a lot more work.

**Additional context**
(None)

**Comment by votdev** [comment]
I understand your needs, but it is technically and by design (how the configuration is deployed) not possible.

**Comment by votdev** [comment]
To simplify your workflow create a duplicate rsync job with the enabled `dry run` knob for testing.
