### ISSUE TITLE
[OMV-Extras Issue] Can't enable Extras repository

### ISSUE THREAD

**Issue by gonk-0612** [openmediavault/openmediavault#1098]
After enabling the Extras repository and pressing the save button, a "Saving..." message pops up and after several minutes results in an error: "connection error" or sometimes "An error occurred" with no further description. The switch in the GUI stays on, but no new plug-ins show up. The same happens when turning it back off.

**Comment by ryecoaaron** [comment]
This should be filed here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues

When you open the new issue, please provide the version of OMV and how you installed.
