### ISSUE TITLE
Configuration option for the WebGUI listen interface

### ISSUE THREAD

**Issue by SerialDestructor** [openmediavault/openmediavault#1099]
**Is your feature request related to a problem? Please describe.**
I would like to use nginx to proxy a few docker containers. I added an additional IP, and I want to make the webGUI listen on a specific IP only.

**Describe the solution you'd like**
In the site-webgui.j2 file, create another condition which for a environment variable in which can specified on what IP-address(es) the webGUI needs to listen on.

**Describe alternatives you've considered**
Running an nginx instance in Docker itself, however, it still needs to be proxied out somehow. And since the default configuration listens on _all_ interfaces, that still creates a problem.

**Comment by votdev** [comment]
Is #1101 something you are looking for?

**Comment by SerialDestructor** [comment]
Yes, looks good to me. Thanks!
