### ISSUE TITLE
Option to Enable Save & Apply

### ISSUE THREAD

**Issue by MKE1138** [openmediavault/openmediavault#1100]
It would be really helpful if there was the option to "Save & Apply". It would make using OMV more efficient, and would save some hassles. If there's any reason why this was considered and not implemented, I wasn't aware of it so I apologize if that's the case.

**Comment by votdev** [comment]
The problem is the plug-in infrastructure and the database versioning + migration in case of different versions.
The feature is on the todo list but don't expect it in OMV6.

**Comment by MKE1138** [comment]
Cool, I suspected there was a good reason.

**Comment by votdev** [comment]
Duplicates https://github.com/openmediavault/openmediavault/issues/102.
