### ISSUE TITLE
Allow for additional IP's on one interface

### ISSUE THREAD

**Issue by SerialDestructor** [openmediavault/openmediavault#1102]
**Is your feature request related to a problem? Please describe.**
This is somewhat related to https://github.com/openmediavault/openmediavault/pull/1101. I would like to assign a second IP to the main network interface.

**Describe the solution you'd like**
The netplan config is generated by the [ethernet.j2](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/files/ethernet.j2). A simple solution would be to make a omv-env variabele where more IP's can be specified. 

**Describe alternatives you've considered**
Connecting another network interface to the box running OpenMediaVault. However, in some situations, this is not feasible.

**Comment by ryecoaaron** [comment]
Even using an environment variable, this still is a somewhat complicated change since you would have to parse the environment variable for more than one address.  If you are going to be doing stuff from the command line, it might be easier to maintain your own netplan config and not use the Interfaces tab for configuring your NIC.

**Comment by SerialDestructor** [comment]
Is there any 'documented' way to override the netplan config?

**Comment by ryecoaaron** [comment]
Yep.  Any normal netplan config docs.  If you delete the adapter in the web interface and create files in /etc/netplan that don't have openmediavault in the name, omv will not change those files and will not create files for the adapter.

**Comment by votdev** [comment]
This feature request does not fit in how OMV is designed and works.
