### ISSUE TITLE
Why is avahi-daemon an OMV dependency? 

### ISSUE THREAD

**Issue by neo-neo1** [openmediavault/openmediavault#1105]
Looking through logs I noticed avahi-daemon is running as a required dependency for OMV. Why is it required? For the security conscious who harden our setups this is a large oversight. And for the purists who disable services they don't use or need. It's generally a poor practice to run services which aren't utilized by the user. Either don't mark avahi-daemon as a dependency or at least give us an option to disable it.

**Comment by votdev** [comment]
The main aim of OMV is to simplify things for the user. Announcing services is one of these things. OMV already provides a UI to disable the announcement for services.

**Comment by neo-neo1** [comment]
> OMV already provides a UI to disable the announcement for services.


OMV does not give an option to disable mDNS in the services. My biggest concern is it doesn’t even notify it is running. Just the general Apple “we know better than you what you need” methodology is applied here.

**Comment by votdev** [comment]
I have to correct my previous statement, the UI has been removed in OMV5 because Zeroconf is an essential feature of OMV. But there are environment variables like OMV_PROFTPD_ZEROCONF_ENABLED to disable there services. Check out the files in https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/srv/salt/omv/deploy/avahi/services for the names of the variables.

**Comment by neo-neo1** [comment]
> I have to correct my previous statement, the UI has been removed in OMV5 because Zeroconf is an essential feature of OMV. But there are environment variables like OMV_PROFTPD_ZEROCONF_ENABLED to disable there services. Check out the files in https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/srv/salt/omv/deploy/avahi/services for the names of the variables. See the [documentation](https://openmediavault.readthedocs.io/en/5.x/various/advset.html) how to customize the OMV deployment.

Thanks I’ll have a look. I already disabled the avahi-daemon service but the intent of my post was to have a UI facing option. I’m curious to which is avahi an essential service for OMV?

**Comment by votdev** [comment]
> Thanks I’ll have a look. I already disabled the avahi-daemon service but the intent of my post was to have a UI facing option. I’m curious to which is avahi an essential service for OMV?

I'm sorry, there will be no UI to configure this essential feature of OMV. That's why the UI has been removed in OMV5.

**Comment by votdev** [comment]
> Just the general Apple “we know better than you what you need” methodology is applied here.

Yes, a little bit, but there are solutions that allow 'power' users to customize the OMV default behavior.

It seems i have to mention it again: OMV is no webmin replacement that allows the user to customize every possible feature and knob of a service that is used in OMV. It is a ready-to-use solution for end-users.
