### ISSUE TITLE
Is the link to freenode on the website still current?

### ISSUE THREAD

**Issue by frainz-de** [openmediavault/openmediavault#1113]
The link at the bottom of https://www.openmediavault.org/ still points to https://webchat.freenode.net/?channels=openmediavault. However, the official channel seems to have moved to libera.chat.

**To Reproduce**

1. Go to https://webchat.freenode.net/?channels=openmediavault
2. Scroll to the bottom
3. Click on 'IRC'

**Expected behavior**

The link points https://web.libera.chat/ or similar.

**Client (please complete the following information):**

- Any Browser

**Comment by frainz-de** [comment]
https://web.libera.chat/#openmediavault should work. But the channel is really quiet so I'm not sure if we should direct people there

**Comment by votdev** [comment]
OK, then i will remove it.
