### ISSUE TITLE
Wireless Bridged AP config is destroyed on OMV install

### ISSUE THREAD

**Issue by DonJuane** [openmediavault/openmediavault#1115]
Per the officially supported Raspberry Pi documentation, the wireless bridged AP is rendered inoperable by the installation of OVM.   Please add information or support on how to re-enable this important feature of the OS as outlined in this document:
https://www.raspberrypi.com/documentation/computers/configuration.html#setting-up-a-bridged-wireless-access-point

Thank you.

**Comment by DonJuane** [comment]
So should I try something like this:
https://askubuntu.com/questions/1222278/detailed-how-to-or-example-needed-to-setup-an-access-point-using-netplan

**Comment by ryecoaaron** [comment]
yep
