### ISSUE TITLE
Recent Update kills 5.0GHz WIFI

### ISSUE THREAD

**Issue by therealkitman** [openmediavault/openmediavault#1118]
I let OMV5 on my Pi4 (8GB) do it's update/upgrade via the web UI this morning 15 October 2021. After rebooting I found that the wifi 5GHz connection on wlan0 was dead, the wlan0 interface was always down. Had to reconnect to the Pi4 via eth0.

What I found is that the 2.4GHz still works ok, but no way can I get 5.0Ghz working again - had been working faultlessly for weeks since I first installed OMV5.

I reported this here for comment [https://forum.openmediavault.org/index.php?thread/40490-recent-update-kills-5-0ghz-wifi/&postID=285197#post285197](https://forum.openmediavault.org/index.php?thread/40490-recent-update-kills-5-0ghz-wifi/&postID=285197#post285197). That url also has a link to journalctl.txt of the journal of connecting both 5Ghz (failed) and 2.4GHz (succeeded) wifi.

**openmediavault Server (please complete the following information):**

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux

pi@raspberrypi:~ $ dpkg -l | grep openmediavault
ii  openmediavault                  5.6.17-1                            all          openmediavault - The open network attached storage solution
ii  openmediavault-flashmemory      5.0.8                               all          folder2ram plugin for OpenMediaVault
ii  openmediavault-keyring          1.0                                 all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg     5.6.2                               all          OMV-Extras.org Package Repositories for OpenMediaVault

Why did 5GHz wifi die?

**Comment by mi-hol** [comment]
Did you consider the suggestion provided in forum post https://forum.openmediavault.org/index.php?thread/40490-recent-update-kills-5-0ghz-wifi/&postID=284559#post284559 ?

**Comment by votdev** [comment]
What packages have been updated? I guess the kernel. But for openmediavault the changes within the last versions were related to the upgrade tool to OMV6 or SMART; nothing that touches the network configuration.

**Comment by therealkitman** [comment]
> Could you add a log from the working 5GHz setup?

Since 5GHz doesn't work I fail to see how I can get a working log.

**Comment by therealkitman** [comment]
> What packages have been updated?

That is hard to say. I just select all packages that are listed for upgrades and let the system do it's thing. As I mentioned in the forum link in the first post above, I installed Raspberry Pi OS Lite and upgraded it and both 2.4 and 5.0Ghz wifi work ok. It is only OMV5 upgrade after around 16 Oct that caused the issue whereas pre-16 Oct 5Ghz was working ok.

**Comment by therealkitman** [comment]
I just let OMV5 do an update this morning on my RPi4 and now I have no ethernet or 2.4GHz wifi connection. Either the RPi4 is flakey or OMV5 is questionable on it. I've used OMV5 on PCs without issue in the past, so I just give up on the RPi4.

Closing this issue.

Regards.

**Comment by mi-hol** [comment]
> Since 5GHz doesn't work I fail to see how I can get a working log.

i.e. from a backup  pre-16 Oct
Backup is in our views a "must have" independent of OS used.

**Comment by ryecoaaron** [comment]
I have four RPi4 running OMV 5.x and they are fully up to date.  None have lost network (wireless or wired).  I have a feeling your sd card and/or RPi and/or power supply are having problems.

**Comment by therealkitman** [comment]
> I have five RPi4 (two RPi4, one RPi400, two CM4) running OMV 5.x and they are fully up to date. None have lost network (wireless or wired). I have a feeling your sd card and/or RPi and/or power supply are having problems.

Even though I closed this, I did some 'final' checks. I was booting using a USB thumbdrive. When I looked at the /root partition it was not accessible after the last OMV5 update. Then further to my horror I realized the USB was only 4GB and I suspect working on the borderline of requirements. 

I have since purchased some 32GB USB3 thumbdrives. One has been running opensuse's tumbleweed/XFCE on the RPi4 without any issue after several updates - that is NFS works ok on ethernet and 5GHz wifi. 

I'll burn another OMV5 image on the 32GB USB and retest so I can be fair to OMV5 and see what happens.

**Comment by therealkitman** [comment]
My RPi4 is now running on the new USB drive. Ethernet and wifi 5.0Ghz are working. If I don't update this thread after a reasonable time of testing then you'll know it was my original 4GB USB drive that caused the issues - in which case I am extremely embarrassed and apologize :(
