### ISSUE TITLE
Integrate ledmon 

### ISSUE THREAD

**Issue by archerne** [openmediavault/openmediavault#1123]
**Is your feature request related to a problem? Please describe.**
I was trying to find a way to turn the Harddrive LED light on, on the harddrive that i was trying to locate in the enclosure. OMV does not currently have a "locate this disk" option or feature

**Describe the solution you'd like**
I did `apt-get install ledmon` and then was able to do `ledctl locate=/dev/sdc`. It would be really great if this could be integrated on to the Disks page

**Comment by votdev** [comment]
Sadly this requires special hardware and i assume that 99% of the OMV users do not have enclosures that support this feature. But with the next versions `5.6.19` and `6.0-33` the WWN (beside the serial no.) of the disk will be displayed in the UI which should help to identify a disk.

**Comment by donhwy** [comment]
I think this would be a great feature. Maybe you could add a note about it on the disk page?

**Comment by mi-hol** [comment]
> add a note about it on the disk page?

documentation is maintained in https://github.com/openmediavault/openmediavault-docs pull requests are welcome there
