### ISSUE TITLE
OMV6 on Debian Bullseye filesystem missing... on purpose???

### ISSUE THREAD

**Issue by jscoys** [openmediavault/openmediavault#1124]
Hey guys,

I installed a Debian Bullseye on a VM in the cloud to do some tests, and what was working several weeks ago is not working anymore...

If I have brand new disk without filesystems on it, OMV allows me to create fs on them and then I can mount them.

BUT now (and apparently it's on purpose), if I want to access the fs from my boot disk for instance, created by my Debian OS, because I wanna create a directory at the root of this disk, to share it via Samba or whatever... well I can't anymore because it's not an fs created by OMV, so OMV doesn't show this fs... it's really impacting honestly and I don't know why you did that guys?

<img width="360" alt="2021-11-05 01_09_23-openmediavault_changelog at master · openmediavault_openmediavault · GitHub and " src="https://user-images.githubusercontent.com/6160983/140461741-6fd0c78c-3c4f-4f78-8ec0-1d137ab73f71.png">

If we can't select fs not creating by OMV, it means that we can't use OMV anymore to associate shared folders on those fs, nor do any Samba shares, it's a big feature drop IMO.

Also it won't be possible to add any pre-existing disks with data on it, because it requires to have a pre-existing fs not created by OMV...

Or maybe I'm missing something?

Thx for your help in my understanding.

**Comment by jscoys** [comment]
https://i.imgur.com/wXp25QZ.png
https://i.imgur.com/vtb17HX.png
https://i.imgur.com/AXeAkHA.png

**Comment by jscoys** [comment]
Nothing is showing in the filesystem list to setup a mount
![image](https://user-images.githubusercontent.com/6160983/140462622-d5646466-3fc3-46b8-94d6-278dc060a2f4.png)

**Comment by MatthiasMoustie** [comment]
I also had this problem. For now, OMV 6 is running in a small setup and had no additional drives. For me, installing following plugin was a solution. No idea if this one is intended for this purpose. After I installed it, the root drive became visible in the dropdown.
<img width="1306" alt="Schermafbeelding 2021-11-05 om 08 48 35" src="https://user-images.githubusercontent.com/47563831/140476613-2bdad99f-42b3-41e4-830b-0d0acf8bd380.png">

**Comment by votdev** [comment]
This behavior is by intention. OMV separates the root OS drive from the data drives because of security. If the root OS disks dies, the main data is not affected and vice verse; that's the reason. By the way, this design decision and the impacts exists since OMV1.

To satisfy the need to access the root file system, the `openmediavault-sharerootfs` plugin was introduced.

> Also it won't be possible to add any pre-existing disks with data on it, because it requires to have a pre-existing fs not created by OMV...

That's incorrect, simply use the `Mount` button in the file system page to mount an existing file system.

![Peek 2021-10-23 21-47](https://user-images.githubusercontent.com/1897962/140481247-beb3e9b0-7bae-4cc5-9eff-e2a176f0f826.gif)

**Comment by jscoys** [comment]
Hey guys thx a lot! You took the time to help me I appreciate!
Take care and thx again!

**Comment by votdev** [comment]
I will take that as an indication that the UI needs some improvements here. Maybe a modal dialog should guide the user here by requiesting 'Do you want to create a new file system or mount an existing one'.

**Comment by jscoys** [comment]
Well maybe it's also I'm totally noob at OMV and I'm just playing with for 3 weeks...

As a new user it wasn't obvious that the first time it worked because I installed by mistake the rootfs... and doing a fresh install weeks after I was telling myself "Where is my root fs?", I didn't do the link between the plugin and this lol
