### ISSUE TITLE
Custom /etc/issue being overwritten despite Adv Config Option setting

### ISSUE THREAD

**Issue by cmangiarelli** [openmediavault/openmediavault#1125]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**
Side Note: I'd tried to register on the forum, but I created an account linked to my GitHub and the verification email got lost in transit. I requested a lost password email, but never received it. While I could create a bogus forum account, I have been trying to find a way to get a forum admin's attention. If I try to create a new account linked to Github, it tells me I already have one (but won't let me log in). If a forum admin is reading this, please help me resolve the problem. Thanks.

**Describe the bug**

After recently upgrading OMV4 to OMV5 (using the scripts on the forum), I noticed that my custom /etc/issue was being replaced by the default one after every reboot. I did a clean install of OMV5, and the issue persists. Both OMV5 instances are at the latest version 5.6.18-2.

I have "OMV_ISSUE_APPLY_PRELOGIN_MESSAGE=NO" listed in /etc/default/openmediavault (same is returned using omv-env get"). I also ran "omv-salt stage run prepare" and " omv-salt stage run deploy" to ensure the setting was being applied. I tried swapping it back to "yes" and then to "no"; rebooting after each salt deploy.

**Expected behavior**

With the proper setting configured, I expect my custom /etc/issue to persist after reboot.

**openmediavault Server (please complete the following information):**

- OS version: Linux drt-mv-001 5.10.0-0.bpo.9-amd64 #1 SMP Debian 5.10.70-1~bpo10+1 (2021-10-10) x86_64 GNU/Linux
- openmediavault version: openmediavault     5.6.18-2     all     openmediavault - The open network attached storage solution

**Comment by votdev** [comment]
I see that this environment variable has not been implemented in OMV5 when switching to the Salt based configuration backend. I'll re-introduce it in OMV6 because OMV5 has a feature freeze.

**Comment by cmangiarelli** [comment]
In case others see this, I resolved it on OMV5 with an hourly CRON command:

cmp -s /etc/issue /etc/issue.911 || cp /etc/issue.911 /etc/issue; agetty --reload

Job frequency can be set according to user preference.

**Comment by votdev** [comment]
I remember now why i removed the environment variable; simply disable this behaviour via `systemctrl disable openmediavault-issue`.

**Comment by votdev** [comment]
The feature has been backported to OMV5 with version `5.6.19` because

> cmp -s /etc/issue /etc/issue.baseline || cp /etc/issue.baseline /etc/issue; agetty --reload

gave me the idea to reload the file after changes have been applied. This was something that seems to be a good improvement.
