### ISSUE TITLE
Samba flush ram

### ISSUE THREAD

**Issue by Mister-XY** [openmediavault/openmediavault#1126]
Hello, I am using OMV 6 6.0.33 and have noticed that my RAM memory is full when I do something via Samba. For example, if I When I watch a movie, the RAM fills up very slowly, but at some point it is full, when I copy a file via Samba, the RAM is very full very quickly. The problem with this is that the RAM is not released again and then permanently hangs at 96%. Even if I don't copy or read anything anymore. 

Kernel is Kernel
Linux 5.14.0-0.bpo.2-amd64

**Comment by votdev** [comment]
Please have a look at https://www.linuxatemyram.com/

**Comment by Mister-XY** [comment]
That mean, all RAM is free but use for cache.

![nas ram](https://user-images.githubusercontent.com/10309056/140611579-70bb3851-76fa-4dc3-8f61-ca2a510f2461.jpg)

**Comment by votdev** [comment]
You're right, the widget is using the incorrect values. According to https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory the `available` metric must be used instead of `free`.

Fixed by https://github.com/openmediavault/openmediavault/commit/62aa171b5202b9145756492cc79c075205f70753.
