### ISSUE TITLE
Support ed25519 SSH keys

### ISSUE THREAD

**Issue by Saxodwarf** [openmediavault/openmediavault#1127]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**
When trying to import an ed25519 SSH key, the validation message says "Invalid SSH public key", even though it is perfectly valid.
When manually adding the public key in the `authorized_key` file of the user, the user can connect, so I know that the key is valid.

**To Reproduce**
I'm sorry in advance if the buttons and menus names are not correct, my UI is in french so I'm reverse-translating everything.

1. Go to 'Users'
2. Select a user
3. Click on 'Edit'
4. Go to the "Public key" tab
5. Click on "Add"
6. Paste an ed25519 SSH key
7. See the error message

**Expected behavior**
The validation function should recognizes ed25519 SSH keys as valid.

**Screenshots**
![image](https://user-images.githubusercontent.com/40502346/140799313-75374c2a-507c-4c0a-8607-f825085a70bf.png)

**Reference to Forum**

The same issue has been brought up [in the forum here](https://forum.openmediavault.org/index.php?thread/40638-bug-user-public-key-ui-don-t-allow-ed25519-key-limited-to-rsa/) (although not by me).

**openmediavault Server (please complete the following information):**

- OS version: `Linux My-NAS 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux`
- openmediavault version: `5.6.12-1`

**Client (please complete the following information):**

- Device: PC
- OS: Debian 11
- Browser: Firefox ESR
- Version: 78.15.0esr (64 bits)

**Additional context**

**Comment by votdev** [comment]
The dialog is really picky, so make sure the are no blanks or line breaks at the end of the line.

**Comment by Saxodwarf** [comment]
I just double checked and no, there are no extra blanks nor line breaks at the end of the line.

Actually, if I just replace the `ed25519` part of the key with `rsa`, then the validation passes, even though the key is not valid anymore wince there is a mismatch between its announced type and its actual type.

**Comment by votdev** [comment]
I'll put that on the feature list for OMV6. OMV5 will not get any new features anymore.

**Comment by Saxodwarf** [comment]
Ok, thanks.

I just saw that the RC1 for OMV6 was released today.
May I ask when the stable version for OMV6 is expected ? Is there a fixed schedule, or is it more an "It will be ready when it is ready" kind of release schedule ?

Thanks for the work on  OMV by the way, it really is a great piece of software.

**Comment by votdev** [comment]
> I just saw that the RC1 for OMV6 was released today. May I ask when the stable version for OMV6 is expected ? Is there a fixed schedule, or is it more an "It will be ready when it is ready" kind of release schedule ?

Right, it will be ready when it's ready. Same procedure since 12 years now.
