### ISSUE TITLE
Requesting inclusion of 2 modules in kernel

### ISSUE THREAD

**Issue by hapklaar** [openmediavault/openmediavault#1129]
I'm very happy with my Thecus N5550 running OMV for over a year now. The only thing that bothered me was that the HDD leds were no longer functioning with OMV as Thecus had some strange way of addressing them and OMV did not support this.

A little while later I found a [github page](https://github.com/ipilcher/n5550) detailing how to get the leds working on a debian based linux installed on the Thecus. Ian was so kind to help me get these leds working on OMV, thread can be found [here](https://github.com/ipilcher/n5550/issues/18).

The hardest part of the entire exercise is getting 2 required modules compiled and loaded that are not included in the kernel by default. This also keeps it from being upgrade proof unfortunately. The modules involved are GPIO_ICH and LEDS_PCA9532.

Would it be possible to include these 2 modules in future kernels to get support for this configuration?

**Comment by votdev** [comment]
But i you would like to see this in OMV, why not contributing a plugin that builds the modules based on DKMS?

**Comment by hapklaar** [comment]
> But if you would like to see this in OMV, why not contributing a plugin that builds these modules based on DKMS?

I have no idea how to do that unfortunately... But if that's possible and the way to go, maybe that could be the actual feature request

**Comment by ryecoaaron** [comment]
If you are running the 64 bit version of OMV, you can add the proxmox kernel via omv-extras. Both of those modules are enabled as modules in the proxmox kernel.

**Comment by hapklaar** [comment]
> If you are running the 64 bit version of OMV, you can add the proxmox kernel via omv-extras. Both of those modules are enabled as modules in the proxmox kernel.

I believe I am. Going to investigate, thanks for pointing this out.
