### ISSUE TITLE
Bug : User public key UI don't allow ​ed25519​ key (limited to rsa)

### ISSUE THREAD

**Issue by xoddark** [openmediavault/openmediavault#1130]
**Describe the bug**
Hello,
When I tried to add an ed25519 OpenSSH key to an user by UI, the UI don't allow me to validate.

**To Reproduce**

1. Go to 'Admin' -> 'Access Rights Management' -> 'User'
2. Select an user and Click on 'edit'
3. Go to 'Public keys' tab
4. Cicl on 'Add' button
5. past an ed25519 OpenSSH public key
6. See than ui don't want to validate it

**Expected behavior**

ed25519 public key should be accepted.
There are valid openssh key and regulary used today. 

**Screenshots**

![OMV_openssh_ed25519_pubkey](https://user-images.githubusercontent.com/71768883/141001666-dbb86316-ffed-4841-a532-230a60a52381.png)

**Reference to Forum**

https://forum.openmediavault.org/index.php?thread/40638-bug-user-public-key-ui-don-t-allow-ed25519-key-limited-to-rsa/&postID=285872#post285872

**openmediavault Server (please complete the following information):**

- OS version: Linux omv 5.10.63-rockchip64 #21.08.2 SMP PREEMPT Wed Sep 8 10:57:23 UTC 2021 aarch64 GNU/Linux
- openmediavault version: 5.6.18-2

**Client (please complete the following information):**
Stock Firefox browser

**Comment by ryecoaaron** [comment]
This was just fixed - https://github.com/openmediavault/openmediavault/issues/1127

**Comment by xoddark** [comment]
Good,

Sorry for duplicate. I have search some days ago and found nothing.
