### ISSUE TITLE
OMV 6.x omv-release-upgrade wrong Bullseye security repo

### ISSUE THREAD

**Issue by geckolinux** [openmediavault/openmediavault#1131]
Hi there, I just tried `omv-release-upgrade` on my old (and only) NAS with its armel processor, currently happily running OMV 5.6.19. It starts to download all the package lists but eventually fails with:

```
Err:12 http://security.debian.org bullseye/updates Release                                                                     
  404  Not Found [IP: 151.101.6.132 80]
Hit:6 https://openmediavault.github.io/packages shaitan InRelease                                   
Hit:7 http://mirrors.edge.kernel.org/debian bullseye InRelease                                      
Reading package lists... Done                                                                                                                                                                
E: The repository 'http://security.debian.org bullseye/updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Skipping acquire of configured file 'main/binary-armel/Packages' as repository 'https://openmediavault-plugin-developers.github.io/packages/debian usul InRelease' doesn't support architecture 'armel'
N: Skipping acquire of configured file 'stable/binary-armel/Packages' as repository 'https://download.docker.com/linux/debian buster InRelease' doesn't support architecture 'armel'
```
Will armel ever be supported for OMV 6.x?

And for now, what should I do with my system, as I assume the failed  `omv-release-upgrade` has made a mess of my system. I did backup the `/etc/apt/sources.*` , but I saw some other changes toward the start of the script:

```
removed '/var/cache/openmediavault/archives/openmediavault-omvextrasorg_latest_all5.deb'
Adding 'local diversion of /usr/sbin/omv-mkaptidx to /usr/sbin/omv-mkaptidx.real'
Adding 'local diversion of /etc/pam.d/openmediavault to /etc/pam.d/openmediavault.real'
Adding 'local diversion of /etc/pam.d/openmediavault-common-auth to /etc/pam.d/openmediavault-common-auth.real'
Adding 'local diversion of /etc/pam.d/openmediavault-webgui to /etc/pam.d/openmediavault-webgui.real'
'/etc/openmediavault/config.xml' -> '/etc/openmediavault/config.xml.5x.bak'
```

Thanks a lot for the help and for your fantastic product!

**Comment by votdev** [comment]
OMV supports the armel platform as you can see here in the package repository: https://packages.openmediavault.org/public/dists/shaitan/main/.

omv-extras.org instead does not deliver armel packages according to https://github.com/OpenMediaVault-Plugin-Developers/packages/tree/master/debian/dists/shaitan/main.

To undo all changes you need to run the following commands:
```
# dpkg-divert --remove --rename /usr/sbin/omv-mkaptidx
# dpkg-divert --remove --rename /etc/pam.d/openmediavault
# dpkg-divert --remove --rename /etc/pam.d/openmediavault-common-auth
# dpkg-divert --remove --rename /etc/pam.d/openmediavault-webgui
```

Open the files `/etc/apt/sources.list` and `/etc/apt/apt.conf` and replace `bullseye` by `buster`.

Finally run the following command to re-deploy all configurations.
```
# omv-salt stage run all
```

**Comment by geckolinux** [comment]
Thanks for the fast reply. It looks like I had two red herrings:
1. I thought I removed OMV Extras before the upgrade, but it was still installed.
2. I also ran into this Debian bug: https://the-codeslinger.com/2020/03/26/debian-bullseye-the-repository-does-not-have-a-release-file/
After fixing those issues the upgrade is now in process.

**Comment by ryecoaaron** [comment]
omv-extras stopped supporting armel early in the 3.x release.

**Comment by geckolinux** [comment]
> omv-extras stopped supporting armel early in the 3.x release.

Weird, the BorgBackup plugin from OMV Extras was definitely installed and working in 5.x, although I did remove it before attempting the upgrade (as the BorgBackup plugin isn't supported yet for any architectures on 6.x).

> `The repository 'http://security.debian.org bullseye/updates Release' does not have a Release file.`

Looks like this is the main issue with omv-release-upgrade, fixed by changing to:
`deb http://security.debian.org/debian-security/ bullseye-security main`

And again, many thanks to the OMV project for supporting armel still, I imagine it's not very common but there are still some perfectly good devices out there whose manufacturers let go to pasture eons ago, and OMV is by far the best way to keep them in service.

**Comment by votdev** [comment]
> > `The repository 'http://security.debian.org bullseye/updates Release' does not have a Release file.`
> 
> Looks like this is the main issue with `omv-release-upgrade`, fixed by changing to: `deb http://security.debian.org/debian-security/ bullseye-security main`

Fixed by e96aa7a1bb75951e611afb4344616e93c5123c68.

**Comment by geckolinux** [comment]
@votdev  Fantastic, want me to close this bug report now?

**Comment by ryecoaaron** [comment]
Most OMV plugins really aren’t arch specific. That is the borg plugin still worked. I just didnt want to keep having maintain another repo and compile armel binaries for things like snapraid.

**Comment by geckolinux** [comment]
@ryecoaaron Hmm I see, now that you mention it I think I remember that I installed the .deb file manually.
