### ISSUE TITLE
OMV6 won't mount file system

### ISSUE THREAD

**Issue by swampy1977** [openmediavault/openmediavault#1132]
I am running OMV6 on Bullseye, previous version 5 on Buster mounted my USB HDD without any issues. However, afert upgrading to version 6 this is not possible.

**Comment by votdev** [comment]
Which platform are you running, ARM, AMD64? How can we reproduce that? What is the error message if there is one? Have you realized that the file system page has been [redesigned](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/debian/changelog#L13)? You need to press the `+` button to add a new or existing file system.

**Comment by amack-ctrl** [comment]
@mi-hol I'm running into the same issue. I saw the redesign (eh liked the old UI better, but that's change).
When I try to wipe/edit my disks nothing happens, when I try to create a new file system under the devices drop down literally nothing drops down; it's super weird.

**Comment by votdev** [comment]
@amack-ctrl and @swampy1977 Please post the output of the following commands:
```
# omv-rpc -u admin 'FileSystemMgmt' 'getList' '{"start":0,"limit":-1}' | jq
# omv-rpc -u admin 'FileSystemMgmt' 'getMountCandidates' | jq
# omv-rpc -u admin 'FileSystemMgmt' 'enumerateFilesystems' | jq
# omv-confdbadm read --prettify conf.system.filesystem.mountpoint
# mount
```

**Comment by swampy1977** [comment]
> Which platform are you running, ARM, AMD64? How can we reproduce that? What is the error message if there is one? Have you realized that the file system page has been [redesigned](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/debian/changelog#L13)? You need to press the `+` button to add a new or existing file system.

I am running it on Raspberry Pi 4B. Of course I know how to add existing file system. Latest update seemed to have fix this issue.

**Comment by the-master-r** [comment]
i have the exact same isue on a new install

> @mi-hol I'm running into the same issue. I saw the redesign (eh liked the old UI better, but that's change). When I try to wipe/edit my disks nothing happens, when I try to create a new file system under the devices drop down literally nothing drops down; it's super weird.

@votdev 
this are the outputs of the comands you requested 

# omv-rpc -u admin 'FileSystemMgmt' 'getList' '{"start":0,"limit":-1}' | jq
gave :

{
  "total": 0,
  "data": []
}
# omv-rpc -u admin 'FileSystemMgmt' 'getMountCandidates' | jq
gave : [ ]
# omv-rpc -u admin 'FileSystemMgmt' 'enumerateFilesystems' | jq
gave :
[
  {
    "devicename": "nvme0n1p1",
    "devicefile": "/dev/disk/by-uuid/5fd65667-13b4-4811-b80c-ae4279e4fc63",
    "predictabledevicefile": "/dev/disk/by-uuid/5fd65667-13b4-4811-b80c-ae4279e4fc63",
    "canonicaldevicefile": "/dev/nvme0n1p1",
    "parentdevicefile": "/dev/nvme0n1",
    "devlinks": [
      "/dev/disk/by-id/nvme-ADATA_SX6000LNP_2L402914GNCF-part1",
      "/dev/disk/by-id/nvme-eui.324c3430323931344ce00018474e4346-part1",
      "/dev/disk/by-partuuid/86980676-01",
      "/dev/disk/by-path/pci-0000:08:00.0-nvme-1-part1",
      "/dev/disk/by-uuid/5fd65667-13b4-4811-b80c-ae4279e4fc63"
    ],
    "uuid": "5fd65667-13b4-4811-b80c-ae4279e4fc63",
    "label": "",
    "type": "ext4",
    "blocks": "121499304",
    "mounted": true,
    "mountpoint": "/",
    "used": "4.95 GiB",
    "available": "112723001344",
    "size": "124415287296",
    "percentage": 5,
    "description": "/dev/nvme0n1p1 [EXT4, 4.95 GiB (5%) used, 104.98 GiB available]",
    "propposixacl": true,
    "propquota": true,
    "propresize": true,
    "propfstab": true,
    "propcompress": false,
    "propautodefrag": false,
    "hasmultipledevices": false,
    "devicefiles": [
      "/dev/nvme0n1p1"
    ],
    "comment": "",
    "_readonly": true,
    "_used": true,
    "propreadonly": false
  },
  {
    "devicename": "sdg",
    "devicefile": "/dev/disk/by-uuid/7669b402-8eda-49bb-99f5-b936fb046270",
    "predictabledevicefile": "/dev/disk/by-uuid/7669b402-8eda-49bb-99f5-b936fb046270",
    "canonicaldevicefile": "/dev/sdg",
    "parentdevicefile": "/dev/sdg",
    "devlinks": [
      "/dev/disk/by-id/ata-ST5000LM000-2U8170_WCJ4PZLE",
      "/dev/disk/by-id/wwn-0x5000c500d53faf86",
      "/dev/disk/by-path/pci-0000:07:00.0-ata-2",
      "/dev/disk/by-path/pci-0000:07:00.0-ata-2.0",
      "/dev/disk/by-uuid/7669b402-8eda-49bb-99f5-b936fb046270"
    ],
    "uuid": "7669b402-8eda-49bb-99f5-b936fb046270",
    "label": "",
    "type": "ext4",
    "blocks": "4844127148",
    "mounted": true,
    "mountpoint": "/srv/dev-disk-by-uuid-7669b402-8eda-49bb-99f5-b936fb046270",
    "used": "4.15 TiB",
    "available": "139384950784",
    "size": "4960386199552",
    "percentage": 98,
    "description": "/dev/sdg [EXT4, 4.15 TiB (98%) used, 129.81 GiB available]",
    "propposixacl": true,
    "propquota": true,
    "propresize": true,
    "propfstab": true,
    "propcompress": false,
    "propautodefrag": false,
    "hasmultipledevices": false,
    "devicefiles": [
      "/dev/sdg"
    ],
    "comment": "",
    "_readonly": false,
    "_used": false,
    "propreadonly": false
  },
  {
    "devicename": "sda1",
    "devicefile": "/dev/disk/by-uuid/cf2de943-dbbd-4a45-9837-4da096062ae5",
    "predictabledevicefile": "/dev/disk/by-uuid/cf2de943-dbbd-4a45-9837-4da096062ae5",
    "canonicaldevicefile": "/dev/sda1",
    "parentdevicefile": "/dev/sda",
    "devlinks": [
      "/dev/disk/by-id/ata-ST2000LM003_HN-M201RAD_S362J9AH814432-part1",
      "/dev/disk/by-id/wwn-0x50004cf212789df8-part1",
      "/dev/disk/by-partuuid/19e77aa3-79a9-4607-887f-cd8af4b85c36",
      "/dev/disk/by-path/pci-0000:00:17.0-ata-3-part1",
      "/dev/disk/by-path/pci-0000:00:17.0-ata-3.0-part1",
      "/dev/disk/by-uuid/cf2de943-dbbd-4a45-9837-4da096062ae5"
    ],
    "uuid": "cf2de943-dbbd-4a45-9837-4da096062ae5",
    "label": "",
    "type": "ext4",
    "blocks": "1922659888",
    "mounted": true,
    "mountpoint": "/srv/dev-disk-by-uuid-cf2de943-dbbd-4a45-9837-4da096062ae5",
    "used": "1.41 TiB",
    "available": "414157328384",
    "size": "1968803725312",
    "percentage": 79,
    "description": "/dev/sda1 [EXT4, 1.41 TiB (79%) used, 385.71 GiB available]",
    "propposixacl": true,
    "propquota": true,
    "propresize": true,
    "propfstab": true,
    "propcompress": false,
    "propautodefrag": false,
    "hasmultipledevices": false,
    "devicefiles": [
      "/dev/sda1"
    ],
    "comment": "",
    "_readonly": false,
    "_used": false,
    "propreadonly": false
  },
  {
    "devicename": "sdf",
    "devicefile": "/dev/disk/by-uuid/3a7c25c9-a4fe-4e44-9568-80048c2f4da6",
    "predictabledevicefile": "/dev/disk/by-uuid/3a7c25c9-a4fe-4e44-9568-80048c2f4da6",
    "canonicaldevicefile": "/dev/sdf",
    "parentdevicefile": "/dev/sdf",
    "devlinks": [
      "/dev/disk/by-id/ata-ST5000LM000-2U8170_WCJ4RG9X",
      "/dev/disk/by-id/wwn-0x5000c500d5438e3d",
      "/dev/disk/by-path/pci-0000:07:00.0-ata-1",
      "/dev/disk/by-path/pci-0000:07:00.0-ata-1.2.0",
      "/dev/disk/by-uuid/3a7c25c9-a4fe-4e44-9568-80048c2f4da6"
    ],
    "uuid": "3a7c25c9-a4fe-4e44-9568-80048c2f4da6",
    "label": "",
    "type": "ext4",
    "blocks": "4844127148",
    "mounted": true,
    "mountpoint": "/srv/dev-disk-by-uuid-3a7c25c9-a4fe-4e44-9568-80048c2f4da6",
    "used": "3.66 TiB",
    "available": "683427946496",
    "size": "4960386199552",
    "percentage": 86,
    "description": "/dev/sdf [EXT4, 3.66 TiB (86%) used, 636.49 GiB available]",
    "propposixacl": true,
    "propquota": true,
    "propresize": true,
    "propfstab": true,
    "propcompress": false,
    "propautodefrag": false,
    "hasmultipledevices": false,
    "devicefiles": [
      "/dev/sdf"
    ],
    "comment": "",
    "_readonly": false,
    "_used": false,
    "propreadonly": false
  },
  {
    "devicename": "sde",
    "devicefile": "/dev/disk/by-uuid/295f3d7f-8ecd-430f-b4f3-48fb6421360e",
    "predictabledevicefile": "/dev/disk/by-uuid/295f3d7f-8ecd-430f-b4f3-48fb6421360e",
    "canonicaldevicefile": "/dev/sde",
    "parentdevicefile": "/dev/sde",
    "devlinks": [
      "/dev/disk/by-id/ata-ST5000LM000-2U8170_WCJ4RFF8",
      "/dev/disk/by-id/wwn-0x5000c500d5435fb1",
      "/dev/disk/by-path/pci-0000:07:00.0-ata-1",
      "/dev/disk/by-path/pci-0000:07:00.0-ata-1.0",
      "/dev/disk/by-uuid/295f3d7f-8ecd-430f-b4f3-48fb6421360e"
    ],
    "uuid": "295f3d7f-8ecd-430f-b4f3-48fb6421360e",
    "label": "",
    "type": "ext4",
    "blocks": "4844127148",
    "mounted": true,
    "mountpoint": "/srv/dev-disk-by-uuid-295f3d7f-8ecd-430f-b4f3-48fb6421360e",
    "used": "4.25 TiB",
    "available": "30415167488",
    "size": "4960386199552",
    "percentage": 100,
    "description": "/dev/sde [EXT4, 4.25 TiB (100%) used, 28.32 GiB available]",
    "propposixacl": true,
    "propquota": true,
    "propresize": true,
    "propfstab": true,
    "propcompress": false,
    "propautodefrag": false,
    "hasmultipledevices": false,
    "devicefiles": [
      "/dev/sde"
    ],
    "comment": "",
    "_readonly": false,
    "_used": false,
    "propreadonly": false
  },
  {
    "devicename": "sdb",
    "devicefile": "/dev/disk/by-uuid/88c471b2-4a18-427d-82c6-4f6a3893daf3",
    "predictabledevicefile": "/dev/disk/by-uuid/88c471b2-4a18-427d-82c6-4f6a3893daf3",
    "canonicaldevicefile": "/dev/sdb",
    "parentdevicefile": "/dev/sdb",
    "devlinks": [
      "/dev/disk/by-id/ata-ST5000LM000-2U8170_WCJ4RCLN",
      "/dev/disk/by-id/wwn-0x5000c500d52e3ab8",
      "/dev/disk/by-path/pci-0000:00:17.0-ata-4",
      "/dev/disk/by-path/pci-0000:00:17.0-ata-4.0",
      "/dev/disk/by-uuid/88c471b2-4a18-427d-82c6-4f6a3893daf3"
    ],
    "uuid": "88c471b2-4a18-427d-82c6-4f6a3893daf3",
    "label": "",
    "type": "ext4",
    "blocks": "4844127148",
    "mounted": true,
    "mountpoint": "/srv/dev-disk-by-uuid-88c471b2-4a18-427d-82c6-4f6a3893daf3",
    "used": "1.97 TiB",
    "available": "2533500620800",
    "size": "4960386199552",
    "percentage": 47,
    "description": "/dev/sdb [EXT4, 1.97 TiB (47%) used, 2.30 TiB available]",
    "propposixacl": true,
    "propquota": true,
    "propresize": true,
    "propfstab": true,
    "propcompress": false,
    "propautodefrag": false,
    "hasmultipledevices": false,
    "devicefiles": [
      "/dev/sdb"
    ],
    "comment": "",
    "_readonly": false,
    "_used": false,
    "propreadonly": false
  },
  {
    "devicename": "md127",
    "devicefile": "/dev/disk/by-uuid/45ad5b1a-142d-48fa-ba36-90ec5ac9f9d5",
    "predictabledevicefile": "/dev/disk/by-uuid/45ad5b1a-142d-48fa-ba36-90ec5ac9f9d5",
    "canonicaldevicefile": "/dev/md127",
    "parentdevicefile": "/dev/md127",
    "devlinks": [
      "/dev/disk/by-id/md-name-omv-shutle:motion",
      "/dev/disk/by-id/md-uuid-0dd16c74:f64d88c7:34360480:ca295fd3",
      "/dev/disk/by-label/raid1",
      "/dev/disk/by-uuid/45ad5b1a-142d-48fa-ba36-90ec5ac9f9d5",
      "/dev//dev/md/motion"
    ],
    "uuid": "45ad5b1a-142d-48fa-ba36-90ec5ac9f9d5",
    "label": "raid1",
    "type": "ext4",
    "blocks": "3844421432",
    "mounted": true,
    "mountpoint": "/srv/dev-disk-by-uuid-45ad5b1a-142d-48fa-ba36-90ec5ac9f9d5",
    "used": "3.51 TiB",
    "available": "74298564608",
    "size": "3936687546368",
    "percentage": 99,
    "description": "/dev/md127 [EXT4, 3.51 TiB (99%) used, 69.19 GiB available]",
    "propposixacl": true,
    "propquota": true,
    "propresize": true,
    "propfstab": true,
    "propcompress": false,
    "propautodefrag": false,
    "hasmultipledevices": false,
    "devicefiles": [
      "/dev/md127"
    ],
    "comment": "",
    "_readonly": false,
    "_used": false,
    "propreadonly": false
  },
  {
    "devicename": "nvme0n1p5",
    "devicefile": "/dev/disk/by-uuid/4b71c362-dfb0-4833-968b-e07552f6b3ac",
    "predictabledevicefile": "/dev/disk/by-uuid/4b71c362-dfb0-4833-968b-e07552f6b3ac",
    "canonicaldevicefile": "/dev/nvme0n1p5",
    "parentdevicefile": "/dev/nvme0n1",
    "devlinks": [
      "/dev/disk/by-id/nvme-ADATA_SX6000LNP_2L402914GNCF-part5",
      "/dev/disk/by-id/nvme-eui.324c3430323931344ce00018474e4346-part5",
      "/dev/disk/by-partuuid/86980676-05",
      "/dev/disk/by-path/pci-0000:08:00.0-nvme-1-part5",
      "/dev/disk/by-uuid/4b71c362-dfb0-4833-968b-e07552f6b3ac"
    ],
    "uuid": "4b71c362-dfb0-4833-968b-e07552f6b3ac",
    "label": "",
    "type": "swap",
    "blocks": "-1",
    "mounted": false,
    "mountpoint": "",
    "used": "-1",
    "available": "-1",
    "size": "-1",
    "percentage": -1,
    "description": "/dev/nvme0n1p5 [SWAP, 976.00 MiB]",
    "propposixacl": false,
    "propquota": false,
    "propresize": false,
    "propfstab": false,
    "propcompress": false,
    "propautodefrag": false,
    "hasmultipledevices": false,
    "devicefiles": [
      "/dev/nvme0n1p5"
    ],
    "comment": "",
    "_readonly": false,
    "_used": false,
    "propreadonly": false
  }
]
#omv-confdbadm read --prettify conf.system.filesystem.mountpoint
gave : 
[ ]
#mount 
gave :
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=3754396k,nr_inodes=938599,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=757956k,mode=755,inode64)
/dev/nvme0n1p1 on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=758)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
sunrpc on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
tmpfs on /tmp type tmpfs (rw,relatime,inode64)
/dev/nvme0n1p1 on /var/folder2ram/var/log type ext4 (rw,relatime,errors=remount-ro)
folder2ram on /var/log type tmpfs (rw,relatime,inode64)
/dev/nvme0n1p1 on /var/folder2ram/var/tmp type ext4 (rw,relatime,errors=remount-ro)
folder2ram on /var/tmp type tmpfs (rw,relatime,inode64)
/dev/nvme0n1p1 on /var/folder2ram/var/lib/openmediavault/rrd type ext4 (rw,relatime,errors=remount-ro)
folder2ram on /var/lib/openmediavault/rrd type tmpfs (rw,relatime,inode64)
/dev/nvme0n1p1 on /var/folder2ram/var/spool type ext4 (rw,relatime,errors=remount-ro)
folder2ram on /var/spool type tmpfs (rw,relatime,inode64)
/dev/nvme0n1p1 on /var/folder2ram/var/lib/rrdcached type ext4 (rw,relatime,errors=remount-ro)
folder2ram on /var/lib/rrdcached type tmpfs (rw,relatime,inode64)
/dev/nvme0n1p1 on /var/folder2ram/var/lib/monit type ext4 (rw,relatime,errors=remount-ro)
folder2ram on /var/lib/monit type tmpfs (rw,relatime,inode64)
/dev/nvme0n1p1 on /var/folder2ram/var/cache/samba type ext4 (rw,relatime,errors=remount-ro)
folder2ram on /var/cache/samba type tmpfs (rw,relatime,inode64)
/dev/md127 on /srv/dev-disk-by-uuid-45ad5b1a-142d-48fa-ba36-90ec5ac9f9d5 type ext4 (rw,relatime,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
/dev/sdg on /srv/dev-disk-by-uuid-7669b402-8eda-49bb-99f5-b936fb046270 type ext4 (rw,relatime,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
/dev/sdb on /srv/dev-disk-by-uuid-88c471b2-4a18-427d-82c6-4f6a3893daf3 type ext4 (rw,relatime,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
/dev/sde on /srv/dev-disk-by-uuid-295f3d7f-8ecd-430f-b4f3-48fb6421360e type ext4 (rw,relatime,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
/dev/sdf on /srv/dev-disk-by-uuid-3a7c25c9-a4fe-4e44-9568-80048c2f4da6 type ext4 (rw,relatime,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
/dev/sda1 on /srv/dev-disk-by-uuid-cf2de943-dbbd-4a45-9837-4da096062ae5 type ext4 (rw,relatime,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)

**Comment by votdev** [comment]
Could you please also post `cat /etc/fstab`

**Comment by the-master-r** [comment]
Read problem #2 - [Solutions to common problems](https://forum.openmediavault.org/index.php?thread/21269-solutions-to-common-problems/)

this was my isue to solve it i ran 
# nano /etc/fstab and commented out all the mounted drives exept the boot and swap 

resulting in this 
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/nvme0n1p1 during installation
UUID=5fd65667-13b4-4811-b80c-ae4279e4fc63 /               ext4    errors=remount-ro 0       1
# swap was on /dev/nvme0n1p5 during installation
UUID=4b71c362-dfb0-4833-968b-e07552f6b3ac none            swap    sw              0       0
# >>> [openmediavault]
#/dev/disk/by-uuid/cf2de943-dbbd-4a45-9837-4da096062ae5         /srv/dev-disk-by-uuid-cf2de943-dbbd-4a45-9837-4da096062ae5      ext4    defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2
#/dev/disk/by-uuid/295f3d7f-8ecd-430f-b4f3-48fb6421360e         /srv/dev-disk-by-uuid-295f3d7f-8ecd-430f-b4f3-48fb6421360e      ext4    defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2
#/dev/disk/by-uuid/3a7c25c9-a4fe-4e44-9568-80048c2f4da6         /srv/dev-disk-by-uuid-3a7c25c9-a4fe-4e44-9568-80048c2f4da6      ext4    defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2
#/dev/disk/by-uuid/45ad5b1a-142d-48fa-ba36-90ec5ac9f9d5         /srv/dev-disk-by-uuid-45ad5b1a-142d-48fa-ba36-90ec5ac9f9d5      ext4    defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2
#/dev/disk/by-uuid/88c471b2-4a18-427d-82c6-4f6a3893daf3         /srv/dev-disk-by-uuid-88c471b2-4a18-427d-82c6-4f6a3893daf3      ext4    defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2
#/dev/disk/by-uuid/7669b402-8eda-49bb-99f5-b936fb046270         /srv/dev-disk-by-uuid-7669b402-8eda-49bb-99f5-b936fb046270      ext4    defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2
# <<< [openmediavault]

**Comment by the-master-r** [comment]
I gues The reason omv failed here was because I have a dead drive that can't be mounted resulting in omv only partially adding the drives
