### ISSUE TITLE
SMB with OMV 6 and kodi Android TV

### ISSUE THREAD

**Issue by Alak69** [openmediavault/openmediavault#1134]
Hello,

I'm a french user and my english is not true :)

I have a problem whit the protocol SMB and OMV6. In OMV5, the protocol SMB 1 is supported in default (server min protocol = NT1) but whit OMV6 not... And when i go on Android TV, my serveur OMV6 is not accessible via kodi for sample.

I'm resolving the problem with add a line in /etc/samba/smb.conf in OMV6. 

workgroup = MSHOME
server min protocol = NT1
server string = %h server

But my synology serveur is true with android with SMB v2. And i not understand why OMV (5 or 6) is not true with SMB v2 in android TV. Synology have a Linux base...

Have you a solution ? In the net, some user have the same problem whit OMV or Debian. Only this solution was reporting and the protocol use in kodi android tv is SMB1 no secur...

**Comment by votdev** [comment]
You should have a look into the Samba changelog and documentation because SMB1 handling has been changed in Samba 4.11. OMV5 is using Samba 4.9, whereas OMV6 is using Samba 4.13.

**Comment by votdev** [comment]
> I have a problem whit the protocol SMB and OMV6. In OMV5, the protocol SMB 1 is supported in default (server min protocol = NT1) but whit OMV6 not... And when i go on Android TV, my serveur OMV6 is not accessible via kodi for sample.

Samba 4.11 has disabled SMB1 support by default (OMV5 is using 4.9; OMV6 uses 4.13). OMV does not enable it because SMB1 is outdated.

> But my synology serveur is true with android with SMB v2. And i not understand why OMV (5 or 6) is not true with SMB v2 in android TV. Synology have a Linux base...

Good question, something in the smb.conf configuration seems to be different.

I pass the solution to this problem on to the community because I do not use this software myself and therefore cannot test it. Suggestions for solutions from the OMV community are therefore welcome.

**Comment by Alak69** [comment]
Yes I suspect that the samba version upgrade is involved. What appeals to me is that it is necessary to add a line in the smb.conf file to regain access under android TV. Why with a Synology server, Android TV exchanges in SMb2 without worry, but with OMV 5 or 6 Android TV gives a negotiation error with the smb 2? And that it is necessary to be satisfied with the Smb 1?

The smb1 has additional security concerns.

**Comment by votdev** [comment]
The best solution would be to extract the smv.conf file from the Synology server and compare it with the OMV configuration.

**Comment by Alak69** [comment]
Yes ! It is true Votdev ! I'm stupid... I'm not open smb.conf in my Synology to compare the file. And i'm not verifie version of samba in synology...

**Comment by Alak69** [comment]
The file smb.conf in synology is short 

[global]
    printcap name=cups
    winbind enum groups=yes
    include=/var/tmp/nginx/smb.netbios.aliases.conf
    encrypt passwords=yes
    min protocol=NT1
    security=user
    local master=no
    realm=*
    syno sync dctime=no
    passdb backend=smbpasswd
    printing=cups
    max protocol=SMB3
    winbind enum users=yes
    load printers=yes
    workgroup=MSHOME

And it is hard to compare.

**Comment by Alak69** [comment]
And the version of samba in synology is 4.10.18

I am not educated enough with Debian to understand why android TV swaps without worry in SMB2 with Synology and only in SMB1 with OMV which I can see with X-plore. Even if I remove in the synology file the line

min protocol = NT1

the nas is still visible on Android .

**Comment by votdev** [comment]
> I am not educated enough with Debian to understand why android TV swaps without worry in SMB2 with Synology and only in SMB1 with OMV which I can see with X-plore. Even if I remove in the synology file the line
> 
> min protocol = NT1

Have you restarted the daemon afterwards?

**Comment by votdev** [comment]
You can start SMB on OMV with debug logging. Don't know the arguments to be added in `Extra options`, but with that enabled the daemon will give some more details why it does not allow connections from Kodi.
Run `journalctl -f` in the CLI to see the debug output.

**Comment by Alak69** [comment]
Yes i have restarted the deamon ^^ :)

Yes I will test debug mode (which I do not know more about, it will train me) and look at the log when trying to connect from android. Have more details on the failure of negotiation in SMB2. But hey for now I'm disconnecting OMV 6 a bit :) I updated last night on one of my servers, just to see. And I love the new interface and everything in between! Its a good job !

Thank you for your leads anyway :)

Finally apart from this little problem to be resolved, my OMV6 server is running perfectly. My centralized MariaDB database for Kodi took the shock perfectly. And everything is functional ... It must be said that this server is mainly used for centralized sharing and for this kodi database.

**Comment by CraneJen** [comment]
enable samba protocol 1
```
[global]
server min protocol = CORE
```
