### ISSUE TITLE
OMV6 omv-release-upgrade /etc/apt/sources still wrong?

### ISSUE THREAD

**Issue by geckolinux** [openmediavault/openmediavault#1142]
Hi there, I think there might still be an additional problem with the `omv-release-upgrade` script from OMV5 -> OMV6 after my initial report in #1131.

After manually fixing the Debian security repo and a successful upgrade, these are my current APT sources:

```
================================================================================
= Configured APT data sources
================================================================================
/etc/apt/sources.list:
======================
deb http://mirrors.kernel.org/debian/ bullseye main
##deb-src http://mirrors.kernel.org/debian/ bullseye main

#deb http://security.debian.org/debian-security/ bullseye-security main
#deb-src http://security.debian.org/debian-security/ bullseye-security main
--------------------------------------------------------------------------------
/etc/apt/sources.list.d:
========================
total 20K
drwxr-xr-x 2 root root 4.0K Nov 9 19:22 .
drwxr-xr-x 14 root root 4.0K Nov 9 19:11 ..
-rw-r--r-- 1 root root 196 Nov 9 19:22 openmediavault.list
-rw-r--r-- 1 root root 60 May 28 10:08 openmediavault-local.list
-rw-r--r-- 1 root root 178 Nov 9 19:22 openmediavault-os-security.list
--------------------------------------------------------------------------------
/etc/apt/sources.list.d/openmediavault-local.list:
==================================================
deb [trusted=yes] file:/var/cache/openmediavault/archives /
/etc/apt/sources.list.d/openmediavault-os-security.list:
========================================================
deb http://security.debian.org/debian-security bullseye-security main contrib non-free
deb-src http://security.debian.org/debian-security bullseye-security main contrib non-free
/etc/apt/sources.list.d/openmediavault.list:
============================================
deb http://packages.openmediavault.org/public/ usul main
deb https://openmediavault.github.io/packages/ usul main
# deb http://downloads.sourceforge.net/project/openmediavault/packages/ usul main
```

I noticed that the APT sources are still pointing to OMV usul. And does OMV normally prefer to define the main Debian repo in `/etc/apt/sources.list` or in a `/etc/apt/sources.list.d/openmediavault*` list?

The weirdness might have been because I had to install an old version of Debian first on my old NAS before I could upgrade it to Buster, where I originally installed OMV5.

On OMV5 I had more update options, including an option to enable or disable automatic unattended installation of updates. This no longer appears to be available, or maybe it's due to my APT sources still being wrong?

![Screenshot from 2021-11-16 07-43-02](https://user-images.githubusercontent.com/2692138/141987651-be9f4488-bc0e-466e-b287-da3a8e7e65c1.png)

**Comment by votdev** [comment]
> And does OMV normally prefer to define the main Debian repo in `/etc/apt/sources.list` or in a `/etc/apt/sources.list.d/openmediavault*` list?

OMV does not touch the main Debian repository configuration. OMV assumes everything is ok here; that should be the default if it is installed using Debian ISO or an ARM based image.

**Comment by votdev** [comment]
I can not reproduce the problem. Using the OMV5 Vagrant box, run `omv-release-upgrade`; check results; all fine.

**Comment by geckolinux** [comment]
OK thanks for confirming. So I just need to change the OMV repo and I'm good?

```
deb http://packages.openmediavault.org/public/ shaitan main
deb https://openmediavault.github.io/packages/ shaitan main
```

Also, regarding the automatic unattended updates could you please confirm if that is still supported or not? Thanks!

**Comment by geckolinux** [comment]
> OMV does not touch the main Debian repository configuration. 

I'm pretty sure that OMV did comment out the security repo that I manually fixed in `/etc/apt/sources.list` 
```
#deb http://security.debian.org/debian-security/ bullseye-security main
#deb-src http://security.debian.org/debian-security/ bullseye-security main
```
Of course it did properly re-add it to `/etc/apt/sources.list.d/openmediavault-os-security.list`.

**Comment by votdev** [comment]
> OK thanks for confirming. So I just need to change the OMV repo and I'm good?
> 
> ```
> deb http://packages.openmediavault.org/public/ shaitan main
> deb https://openmediavault.github.io/packages/ shaitan main
> ```
> 

The OMV APT configuration is deployed by default on package installation; for the upgrade path this is done manually by `omv-release-upgrade`, see https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/50-rebuild-apt-conf.

If you want to trigger a rebuild, run `omv-salt deploy run apt` in the CLI.

> Also, regarding the automatic unattended updates could you please confirm if that is still supported or not?

`cron-apt` is still enabled by default and i remember that i got email notification on my test system. So yes, it should work.

**Comment by votdev** [comment]
> I'm pretty sure that OMV did comment out the security repo that I manually fixed in `/etc/apt/sources.list`

This is by intention, see https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/usr/share/openmediavault/release-upgrade/pre.d/20-apt-update-source-list#L50.

It is added later automatically to `/etc/apt/sources.list.d/openmediavault-os-security.list`, see https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/apt/files/etc-apt-sources_list_d-openmediavault-os-security_list.j2.

**Comment by geckolinux** [comment]
> `cron-apt` is still enabled by default and i remember that i got email notification on my test system. So yes, it should work.

OK, thanks. I can't seem to find a GUI option in OMV for enabling/disabling that, is it now basically mandatory or did that option get dropped for OMV6?

**Comment by votdev** [comment]
> > `cron-apt` is still enabled by default and i remember that i got email notification on my test system. So yes, it should work.
> 
> OK, thanks. I can't seem to find a GUI option in OMV for enabling/disabling that, is it now basically mandatory or did that option get dropped for OMV6?

There never was an option in the UI to disable this because it is an essential feature of OMV. You can disable it via environment variables, but nothing more.

**Comment by geckolinux** [comment]
> If you want to trigger a rebuild, run `omv-salt deploy run apt` in the CLI.

Hmm, it's still not fixing the `/etc/apt/sources.list.d/openmediavault.list` :
```
deb http://packages.openmediavault.org/public/ usul main
deb https://openmediavault.github.io/packages/ usul main
# deb http://downloads.sourceforge.net/project/openmediavault/packages/ usul main
```

```
root@OpenMediaVault:~# omv-salt deploy run apt
lacie:
----------
          ID: configure_apt_sources_list_openmediavault
    Function: file.managed
        Name: /etc/apt/sources.list.d/openmediavault.list
      Result: True
     Comment: File /etc/apt/sources.list.d/openmediavault.list is in the correct state
     Started: 08:46:30.418705
    Duration: 1569.544 ms
     Changes:   
----------
          ID: remove_apt_proxy
    Function: file.absent
        Name: /etc/apt/apt.conf.d/99openmediavault-proxy
      Result: True
     Comment: File /etc/apt/apt.conf.d/99openmediavault-proxy is not present
     Started: 08:46:31.991433
    Duration: 14.336 ms
     Changes:   
----------
          ID: remove_apt_pref_kernel_backports
    Function: file.absent
        Name: /etc/apt/preferences.d/openmediavault-kernel-backports.pref
      Result: True
     Comment: File /etc/apt/preferences.d/openmediavault-kernel-backports.pref is not present
     Started: 08:46:32.008891
    Duration: 14.134 ms
     Changes:   
----------
          ID: remove_apt_sources_list_kernel_backports
    Function: file.absent
        Name: /etc/apt/sources.list.d/openmediavault-kernel-backports.list
      Result: True
     Comment: File /etc/apt/sources.list.d/openmediavault-kernel-backports.list is not present
     Started: 08:46:32.026126
    Duration: 13.814 ms
     Changes:   
----------
          ID: remove_apt_sources_list_omv_security_obsolete
    Function: file.absent
        Name: /etc/apt/sources.list.d/openmediavault-debian-security.list
      Result: True
     Comment: File /etc/apt/sources.list.d/openmediavault-debian-security.list is not present
     Started: 08:46:32.043036
    Duration: 13.92 ms
     Changes:   
----------
          ID: remove_apt_sources_list_security_0
    Function: module.run
      Result: True
     Comment: pkg.del_repo: Repo 'deb http://security.debian.org/debian-security bullseye-security main contrib non-free' has been removed from /etc/apt/sources.list.d/openmediavault-os-security.list.
     Started: 08:46:32.094093
    Duration: 103095.811 ms
     Changes:   
              ----------
              pkg.del_repo:
                  Repo 'deb http://security.debian.org/debian-security bullseye-security main contrib non-free' has been removed from /etc/apt/sources.list.d/openmediavault-os-security.list.
----------
          ID: remove_apt_sources_list_security_1
    Function: module.run
      Result: True
     Comment: pkg.del_repo: File /etc/apt/sources.list.d/openmediavault-os-security.list containing repo 'deb-src http://security.debian.org/debian-security bullseye-security main contrib non-free' has been removed.
     Started: 08:48:15.276618
    Duration: 102567.009 ms
     Changes:   
              ----------
              pkg.del_repo:
                  File /etc/apt/sources.list.d/openmediavault-os-security.list containing repo 'deb-src http://security.debian.org/debian-security bullseye-security main contrib non-free' has been removed.
----------
          ID: configure_apt_sources_list_os_security
    Function: file.managed
        Name: /etc/apt/sources.list.d/openmediavault-os-security.list
      Result: True
     Comment: File /etc/apt/sources.list.d/openmediavault-os-security.list updated
     Started: 08:49:57.868687
    Duration: 5791.2 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: refresh_apt_database
    Function: module.run
      Result: True
     Comment: pkg.refresh_db: Success
     Started: 08:50:03.686467
    Duration: 106360.727 ms
     Changes:   
              ----------
              pkg.refresh_db:
                  ----------
                  file:/var/cache/openmediavault/archives InRelease:
                      False
                  file:/var/cache/openmediavault/archives Packages:
                      True
                  file:/var/cache/openmediavault/archives Release:
                      False
                  file:/var/cache/openmediavault/archives Translation-C:
                      False
                  file:/var/cache/openmediavault/archives Translation-en:
                      False
                  file:/var/cache/openmediavault/archives Translation-en_US:
                      False
                  http://mirrors.edge.kernel.org/debian bullseye InRelease:
                      None
                  http://packages.openmediavault.org/public usul InRelease:
                      None
                  http://security.debian.org/debian-security bullseye-security InRelease:
                      True
                  http://security.debian.org/debian-security bullseye-security/main Sources:
                      True
                  http://security.debian.org/debian-security bullseye-security/main Translation-en:
                      True
                  http://security.debian.org/debian-security bullseye-security/main armel Packages:
                      True
                  https://openmediavault.github.io/packages usul InRelease:
                      None

Summary for lacie
------------
Succeeded: 9 (changed=4)
Failed:    0
------------
Total states run:     9
Total run time: 319.440 s

**Comment by votdev** [comment]
Please post the content of the following files

* /srv/pillar/omv/default.sls
* /srv/pillar/omv/productinfo.sls
* /usr/share/openmediavault/productinfo.xml

**Comment by geckolinux** [comment]
[default.sls](https://github.com/openmediavault/openmediavault/files/7547279/default.sls.txt)

[productinfo.sls](https://github.com/openmediavault/openmediavault/files/7547280/productinfo.sls.txt)

[productinfo.xml](https://github.com/openmediavault/openmediavault/files/7547281/productinfo.xml.txt)

Interesting, the OMV version is wrong in `productinfo.sls`

**Comment by votdev** [comment]
> Interesting, the OMV version is wrong in `productinfo.sls`

Yes. On every package installation/update the Salt pillar data is updated, see https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/debian/openmediavault.postinst#L190.

In your case something went wrong. To fix that run `omv-salt stage run prepare; omv-salt deploy run apt`.

**Comment by geckolinux** [comment]
Ah, OK. It might have gone wrong during my first failed attempt with `omv-release-upgrade` in #1131.

I'm getting this error on `omv-salt stage run prepare; omv-salt deploy run apt`
```
lacie:
----------
          ID: run_state_patch
    Function: salt.state
      Result: False
     Comment: Run failed on minions: lacie
     Started: 09:46:34.191747
    Duration: 6102.751 ms
     Changes:   
              lacie:
              ----------
                        ID: patch_network_module_pr_59829
                  Function: file.patch
                      Name: /lib/python3/dist-packages/salt/modules/network.py
                    Result: False
                   Comment: /lib/python3/dist-packages/salt/modules/network.py does not exist
                   Started: 09:46:40.186073
                  Duration: 34.738 ms
                   Changes:   
              ----------
                        ID: patch_fileserver_root_pr_60536
                  Function: file.patch
                      Name: /lib/python3/dist-packages/salt/fileserver/roots.py
                    Result: False
                   Comment: /lib/python3/dist-packages/salt/fileserver/roots.py does not exist
                   Started: 09:46:40.223638
                  Duration: 28.935 ms
                   Changes:   
              
              Summary for lacie
              ------------
              Succeeded: 0
              Failed:    2
              ------------
              Total states run:     2
              Total run time:  63.673 ms

Summary for lacie
------------
Succeeded: 0
Failed:    1

**Comment by geckolinux** [comment]
...which doesn't make any sense, because:

```
salt-common is already the newest version (3003+ds-1).
salt-common set to manually installed.
```

**Comment by votdev** [comment]
> ...which doesn't make any sense, because:
> 
> ```
> salt-common is already the newest version (3003+ds-1).
> salt-common set to manually installed.
> ```

Right, doesn't make sense. If Salt is installed, the files must exist, otherwise Salt wouldn't work correct.
```
root@omv6box:/home/vagrant# ls -alh /lib/python3/dist-packages/salt/fileserver/
total 184K
drwxr-xr-x  3 root root 4.0K Nov 15 13:17 .
drwxr-xr-x 44 root root 4.0K Nov 15 13:16 ..
-rw-r--r--  1 root root  31K Mar 24  2021 __init__.py
drwxr-xr-x  2 root root 4.0K Nov 15 13:17 __pycache__
-rw-r--r--  1 root root  14K Mar 24  2021 azurefs.py
-rw-r--r--  1 root root 5.7K Mar 24  2021 gitfs.py
-rw-r--r--  1 root root  29K Mar 24  2021 hgfs.py
-rw-r--r--  1 root root  12K Mar 24  2021 minionfs.py
-rw-r--r--  1 root root  16K Nov 15 13:17 roots.py
-rw-r--r--  1 root root  25K Mar 24  2021 s3fs.py
-rw-r--r--  1 root root  26K Mar 24  2021 svnfs.py
root@omv6box:/home/vagrant# ls -alh /lib/python3/dist-packages/salt/modules/netwo*
-rw-r--r-- 1 root root 64K Nov 15 13:17 /lib/python3/dist-packages/salt/modules/network.py
root@omv6box:/home/vagrant# dpkg -l | grep salt
ii  salt-common                    3003+ds-1                      all          shared libraries that salt requires for all packages
ii  salt-minion                    3003+ds-1                      all          client package for salt, the distributed remote execution system
```

**Comment by votdev** [comment]
This issue has been closed because it seems it is a user related problem and no general one.

**Comment by geckolinux** [comment]
```
root@OpenMediaVault:~# ls -alh /lib/python3/dist-packages/salt/fileserver/
ls: cannot access '/lib/python3/dist-packages/salt/fileserver/': No such file or directory

root@OpenMediaVault:~# ls -alh /usr/lib/python3/dist-packages/salt/fileserver/
total 184K
drwxr-xr-x  3 root root 4.0K Nov  9 19:14 .
drwxr-xr-x 44 root root 4.0K Nov  9 19:14 ..
-rw-r--r--  1 root root  14K Mar 24  2021 azurefs.py
-rw-r--r--  1 root root 5.7K Mar 24  2021 gitfs.py
-rw-r--r--  1 root root  29K Mar 24  2021 hgfs.py
-rw-r--r--  1 root root  31K Mar 24  2021 __init__.py
-rw-r--r--  1 root root  12K Mar 24  2021 minionfs.py
drwxr-xr-x  2 root root 4.0K Nov  9 19:15 __pycache__
-rw-r--r--  1 root root  16K Mar 24  2021 roots.py
-rw-r--r--  1 root root  25K Mar 24  2021 s3fs.py
-rw-r--r--  1 root root  26K Mar 24  2021 svnfs.py
```

So there's the difference. The `python3` packages are in `/usr/lib/` , not `/lib/` . Any suggestions on how I should proceed?

**Comment by votdev** [comment]
> So there's the difference. The `python3` packages are in `/usr/lib/` , not `/lib/` . Any suggestions on how I should proceed?

A well known problem: https://wiki.debian.org/UsrMerge

**Comment by geckolinux** [comment]
That's what I suspected. Like I said, I originally had to do a fresh install with an old Debian version, I believe it was Jessie, and from there I had to `dist-upgrade` it. So it looks to me like like this issue could be avoided by requiring the `usrmerge` package as a dependency of OMV?

**Comment by votdev** [comment]
> So it looks to me like like this issue could be avoided by requiring the `usrmerge` package as a dependency of OMV?

No, this is not the job of OMV and is no problem for official Debian systems nowadays.
