### ISSUE TITLE
Sabrent NVMe (SB-ROCKET-256) not populating info properly/no S.M.A.R.T.

### ISSUE THREAD

**Issue by Hukuma1** [openmediavault/openmediavault#1144]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

Sabrent 256GB (SB-ROCKET-256) does not properly show information under `Storage -> Disks`. And unable to monitor it under `S.M.A.R.T. -> Devices`.

**Expected behavior**

Model: SB-ROCKET-256
Serial Number: XXXX
Vendor: Sabrent

**Screenshots**

<img width="1038" alt="sabrentomv" src="https://user-images.githubusercontent.com/54511555/142052584-065b9b73-9659-4504-a97b-82e0162970cd.png">

Not sure if related, but under S.M.A.R.T. I am unable to enable it/check status of the drive either:
<img width="1035" alt="sabrentomvsmart" src="https://user-images.githubusercontent.com/54511555/142053204-cf77fe37-3ace-4e6a-802f-3fafc6e0d149.png">

**openmediavault Server (please complete the following information):**

- OS version: Linux NAS 5.10.0-9-amd64 # 1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
- openmediavault version: 6.0.1-1

**Client (please complete the following information):**

- Device: Desktop
- OS: Windows 11
- Browser: Google Chrome
- Version: 96

Had the same issue(s) on OMV5. Just wanted to submit a ticket finally.

Under `S.M.A.R.T. -> Devices -> Details -> Extended Information`

```
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.10.0-9-amd64] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       Sabrent
Serial Number:                      XXXXXXXXXXXXXXXXXXXX
Firmware Version:                   RKT303.3
PCI Vendor/Subsystem ID:            0x1987
IEEE OUI Identifier:                0x6479a7
Total NVM Capacity:                 256,060,514,304 [256 GB]
Unallocated NVM Capacity:           0
Controller ID:                      1
NVMe Version:                       1.3
Number of Namespaces:               1
Namespace 1 Size/Capacity:          256,060,514,304 [256 GB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            6479a7 45d02005d0
Local Time is:                      Tue Nov 16 11:30:21 2021 PST
Firmware Updates (0x12):            1 Slot, no Reset required
Optional Admin Commands (0x0017):   Security Format Frmw_DL Self_Test
Optional NVM Commands (0x005d):     Comp DS_Mngmt Wr_Zero Sav/Sel_Feat Timestmp
Log Page Attributes (0x08):         Telmtry_Lg
Maximum Data Transfer Size:         512 Pages
Warning  Comp. Temp. Threshold:     75 Celsius
Critical Comp. Temp. Threshold:     80 Celsius

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +     5.55W       -        -    0  0  0  0        0       0
 1 +     4.49W       -        -    1  1  1  1        0       0
 2 +     3.97W       -        -    2  2  2  2        0       0
 3 -   0.0490W       -        -    3  3  3  3     2000    2000
 4 -   0.0018W       -        -    4  4  4  4    25000   25000

Supported LBA Sizes (NSID 0x1)
Id Fmt  Data  Metadt  Rel_Perf
 0 +     512       0         2
 1 -    4096       0         1

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        35 Celsius
Available Spare:                    100%
Available Spare Threshold:          5%
Percentage Used:                    11%
Data Units Read:                    2,809,633 [1.43 TB]
Data Units Written:                 12,667,844 [6.48 TB]
Host Read Commands:                 157,264,280
Host Write Commands:                439,366,616
Controller Busy Time:               1,618
Power Cycles:                       40
Power On Hours:                     6,681
Unsafe Shutdowns:                   33
Media and Data Integrity Errors:    0
Error Information Log Entries:      128
Warning  Comp. Temperature Time:    0
Critical Comp. Temperature Time:    0

Error Information (NVMe Log 0x01, 16 of 63 entries)
No Errors Logged
```

**Comment by votdev** [comment]
NVMe devices do not provide SMART attributes that are used to assess the current status, that's why the UI shows `Unknown`.

I will close the issue because this behaviour is by technical reasons of NVMe devices.

**Comment by votdev** [comment]
> Not sure if related, but under S.M.A.R.T. I am unable to enable it/check status of the drive either:

What do you exactly mean with this statement? I can't follow you, sorry.

**Comment by Hukuma1** [comment]
Oh I see. I was under the impression since the drive supports SMART commands it would be like my other HDDs.

https://www.sabrent.com/product/SB-ROCKET-256/256gb-rocket-nvme-pcie-m-2-2280-internal-ssd-high-performance-solid-state-drive/#description
```
Supports SMART and TRIM commands. Supports ONFi 2.3, ONFi 3.0, ONFi 3.2 and ONFi 4.0 interface.
```

**Comment by mi-hol** [comment]
@votdev 
https://nvmexpress.org/resources/nvm-express-technology-features/nvme-features-for-error-reporting-smart-log-pages-failures-and-management-capabilities-in-nvme-architectures/ would suggest that SMART is available for NVMe too
"Monitoring Endurance
The easy way to monitor endurance of an NVMe SSD is the SMART Percentage Used field, which is like a gas gauge for the endurance that shows the actual wear out of the drive. Most applications use this to report the endurance used or SSD life left (100% – % used) as a percentage. The available spares field can be set by the vendor to send a notification to the host when spares are below a certain threshold – this is just another way to represent endurance and is less frequently used."

**Comment by mi-hol** [comment]
@Hukuma1  did openmediavault 5.6.22 resolve the issue?

**Comment by Hukuma1** [comment]
Awesome! I ended up upgrading to OMV6 a bit ago but it looks like it's working in `6.0.6-1` as well. :) Thanks for your work!

<img width="604" alt="omvsmart" src="https://user-images.githubusercontent.com/54511555/147610656-191abe24-891a-4d4b-9863-352527c53293.png">
