### ISSUE TITLE
Support for XFS folder quota (OMV6)

### ISSUE THREAD

**Issue by Messinger** [openmediavault/openmediavault#1147]
XFS can setup folder related quotas. (short description:  https://fabianlee.org/2020/01/13/linux-using-xfs-project-quotas-to-limit-capacity-within-a-subdirectory/)

This is sometimes helpfull for automated backups running with one user but multilple devices store their backup into multiple folders. With this feature you can ensure the devices are not inflecting each other in an easy way.

**Describe the solution you'd like**
The perfect solution would be a interface (plugin?) managing this. ;) 

But as alternative: I would like that an option exists when mounting a XFS files system if the prjquota should be enabled on mount or not. 

At this point it could be possible managing this folder related quota at least via cmdline. 

Same/similar would be nice for any FS supporting folder/project based quotas.

**Comment by votdev** [comment]
I would also prefer to see that as a plugin because no other file system supports that.

**Comment by Messinger** [comment]
Managing the folder-quota as plugin - of course, because other FS supporting this (ZFS, BTRFS) handle this different. 

But the required flag for XFS should be set in general by OMV mount dialog, shouldn't it?  I don't know if a plugin is able to overlay the mount settings of OMV. Eg, when creating/mounting a XFS the prquota option should always set (like usrquota and grpquota) or offered as a checkbox.

**Comment by votdev** [comment]
You can already customize the default mount options that OMV is using when a file system is mounted via UI. Set the environment variable `OMV_FSTAB_MNTOPS_XFS` to what you want. Please have a look at https://openmediavault.readthedocs.io/en/5.x/various/advset.html#environmental-variables and https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/globals.inc#L83.

**Comment by votdev** [comment]
> But the required flag for XFS should be set in general by OMV mount dialog, shouldn't it?

This is not what i would like to see in OMV, because OMV is not a webmin replacement where you can configure every possible feature. If there is a coherent concept to implement it in a user-friendly way I see no problem. What I do not want to see under all circumstances is to offer the user a list of checkboxes that shows, for example:

- defaults
- nofail
- usrquota
- grpquota
- prjquota

**Comment by Messinger** [comment]
Yes, of course, this makes sense. 

I thought more about the ability to give a second way for defining quota (which is part of NAS) and that `prquota` could be part of the list in globals.inc in general. (It would not disturb the current settings/workflow)

But if you say no - of course no problem. 

Thanks!
