### ISSUE TITLE
OMV6 - Receive a "Done" confirmation on script/command end.

### ISSUE THREAD

**Issue by cravas** [openmediavault/openmediavault#1149]
**Is your feature request related to a problem? Please describe.**
There's no information that any script and/or command has ended.
Only the highlighted `Close` button which is somewhat hard to see (on some screens).

**Describe the solution you'd like**
Receive a "`Done`" confirmation on script/command end.

**Additional context**
![image](https://user-images.githubusercontent.com/21242022/142892310-e0c63f9a-b66f-4303-a502-56fba69bcede.png)

**Comment by votdev** [comment]
There is a progress bar at the top of the output which moves continuously as long as the job is being processed. Additionally the `Close` button is enabled which also indicates that the job/task/whatever is done.

The `Done` has been removed by intention because it might be interpreted as content of the executed task which is incorrect. To  avoid irritation for the user it has been removed.

**Comment by cravas** [comment]
> The `Done` text has been removed by intention because it might be interpreted as content of the executed task which is incorrect. To avoid irritation for the user it has been removed.

Fair enough.

But, can at least the Button background become highlighted when finished? 
Seeing with "fresh eyes", I can notice the bar disappear from the Top and the "Close" letters become dark.

If the button becomes with color (maybe the Blue used on the Top of the Window), it will be more perceptable:
![image](https://user-images.githubusercontent.com/21242022/142990918-bbaaa67d-ee10-40b5-a21f-2c0a8f0c1027.png)

Nonetheless, thank you for the work, ;)

**Comment by votdev** [comment]
> If the button becomes with color (maybe the Blue used on the Top of the Window), it will be more perceptable

According to the Material design which is used by OMV only primary actions should use colored buttons. Closing a dialog is not a primary action. So i fear this is no option.

**Comment by cravas** [comment]
> 

Well, we'll have to live with it, :)

Thank just the same.

**Comment by cravas** [comment]
> Did some improvements that will hopefully help to fix this issue:

Thank you for taking it in consideration.
Will test it tomorrow morning, ;)
