### ISSUE TITLE
Omv5 updated to omv6, kernel stuck at 5.10

### ISSUE THREAD

**Issue by ibos** [openmediavault/openmediavault#1150]
I did an inplace update to OMV 5 on x86 64 bit system, everything seems to go smooth, but the kernel is stuck at 5.10. i can see the update to 5.14 in the updates list, but the install fails. The update only shows up if I have backports from omv-extra checked on.
Output:
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages have been kept back:
  linux-image-amd64
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by votdev** [comment]
Packages are held back by default if they contain new dependencies which might apply to the new kernel package you are talking about. Please run `apt-get dist-upgrade` from the console to install the package.

**Comment by ibos** [comment]
That fixed it. Thanks. Just curious if the kernel having been kept on 5.10 was due to previously having installed backports, or if it was expected that the kernel does not update to 5.14 with OMV 6 when installing over OMV 5 using the omv-release-upgrade command?

**Comment by mi-hol** [comment]
@ibos this question is best raised at OMV forum.
closing issue.
