### ISSUE TITLE
Enhance OMV installation to prevent installation on "Desktop OS" to prevent the typical errors later

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1153]
**Is your feature request related to a problem? Please describe.**
Especially RPI users don't understand which Debian OS "flavor" to select as foundation for an OMV build.
An error made results much later in issues the users can't solve by themselves.
The net result are many forum posts and bad reputation for OMV!

**Describe the solution you'd like**
1.) Check the typical "indicators" of a desktop OS flavor and abort installation.
Display a clear message about  the reasons
2) Add a "fallback" switch to bypass this check to handle exceptions in case  the check produces incorrect results

**Describe alternatives you've considered**
Documentation doesn't help because inexperienced users simply fail to understand the text 

**Additional context**
one of many occasions:
https://forum.openmediavault.org/index.php?thread/40989-nach-omv-aufsetzen-keinen-zugriff-mehr-auf-die-festplatten/&postID=289581#post289581

**Comment by ryecoaaron** [comment]
Most of these "features" belong in the install script not OMV.  And how would you determine if a desktop environment is in use?  Just having many of the desktop packages installed does not mean they will be an issue to OMV.  The remotedesktop plugin used to install quite a few xfce packages for instance.

**Comment by mi-hol** [comment]
> Most of these "features" belong in the install script not OMV. 

true, shall I move it to omv-extras.org repo?

> how would you determine if a desktop environment is in use? 

Unfortunately I'm lacking the deep technical background to suggest a reliable solution, but hope that other can provide their knowledge to get there

> Just having many of the desktop packages installed does not mean they will be an issue to OMV. The remotedesktop plugin used to install quite a few xfce packages for instance.

true, but plugins are only installed **after OMV**, hence I'd believe this can be ignored

**Comment by ryecoaaron** [comment]
Sure.
I know how to determine if a desktop is installed.  I was asking how you would do it.
OMV is "installed" every time you update to a new version.  And failing a check in the omv package while installing the omv package would cause the debian package to fail = bad idea.

**Comment by mi-hol** [comment]
> OMV is "installed" every time you update to a new version

I had associated https://wiki.omv-extras.org/doku.php?id=installing_omv5_raspberry_pi with installation.
Are you saying that this downloaded script is used for each update too?

**Comment by ryecoaaron** [comment]
No.  I am saying that when you have openmediavault 6.0.3 installed and you run apt-get dist-upgrade (or upgrade from the web interface) to install 6.0.4, you are installing the package again.  I was just explaining that you can't put these checks in the openmediavault package itself.

**Comment by mi-hol** [comment]
> I know how to determine if a desktop is installed

I would try to update the install script on my own, given you'd provide me a hint regarding "how to" :)

**Comment by ryecoaaron** [comment]
That quite alright.  I can do the updating.  Still trying to decide if I really want to add this.

**Comment by mi-hol** [comment]
shall I crunch some numbers for how many times new users picked the wrong OS flavor and cried for help on forum?

**Comment by ryecoaaron** [comment]
Do you know how many of those people are going to pick the desktop version, run the script, and still cried for help on the forum?

**Comment by mi-hol** [comment]
not sure to get the intent of your question.
"are going to" is forward looking, while I can only look backwards in past posts and count occurrences for a month or so.

**Comment by ryecoaaron** [comment]
I have 12 years of watching patterns of OMV users and know people are still going to cry for help (especially RPi users) on the forum.  I added a check for display manager packages.  This isn't perfect (people could still have a desktop environment installed and start with startx) but it is the most I want to add.
