### ISSUE TITLE
SMART status "unknown" for QNAP TR-004

### ISSUE THREAD

**Issue by mirogl** [openmediavault/openmediavault#1154]
Hi,
I have a QNAP TR-004 attached to openmediavault 6.0.5-2. The QNAP TR-004 has 4x 1TB SSD drives in hardware RAID-5 mode attached.

In the settings of openmediavault 
Storage -> S.M.A.R.T. -> Devices -> Details  
the status is "unknown" and under
-> Extended Informations
i get no SMART infos.

see current output "Extended Informations" below:

`smartctl 7.2 2020-12-30 r5155 [armv7l-linux-5.10.63-v7l+] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     JMicron H/W RAID5
Serial Number:    <removed>
Firmware Version: 0965
User Capacity:    3,000,470,863,872 bytes [3.00 TB]
Sector Size:      512 bytes logical/physical
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ATA/ATAPI-7 (minor revision not indicated)
Local Time is:    Thu Dec  2 22:48:27 2021 CET
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
AAM feature is:   Unavailable
APM level is:     254 (maximum performance)
Rd look-ahead is: Disabled
Write cache is:   Disabled
DSN feature is:   Unavailable
ATA Security is:  Disabled, NOT FROZEN [SEC1]
Wt Cache Reorder: Unavailable

=== START OF READ SMART DATA SECTION ===
SMART Status not supported: Incomplete response, ATA output registers missing
SMART overall-health self-assessment test result: PASSED
Warning: This result is based on an Attribute check.

General SMART Values:
Offline data collection status:  (0x00)	Offline data collection activity
					was never started.
					Auto Offline Data Collection: Disabled.
Total time to complete Offline
data collection: 		(    0) seconds.
Offline data collection
capabilities: 			 (0x00) 	Offline data collection not supported.
SMART capabilities:            (0x0000)	Automatic saving of SMART data					is not implemented.
Error logging capability:        (0x00)	Error logging NOT supported.
					No General Purpose Logging support.

General Purpose Log Directory not supported

SMART Log Directory Version 0
Address    Access  R/W   Size  Description
0x00           SL  R/O      1  Log Directory

SMART Extended Comprehensive Error Log (GP Log 0x03) not supported

SMART Error Log not supported

SMART Extended Self-test Log (GP Log 0x07) not supported

SMART Self-test Log not supported

Selective Self-tests/Logging not supported

SCT Commands not supported

Device Statistics (GP/SMART Log 0x04) not supported

Pending Defects log (GP Log 0x0c) not supported

SATA Phy Event Counters (GP Log 0x11) not supported`

but when i make a manual query via smartctl, i got the SMART infos:

I have to address every drive manually (with 0..3)

```
sudo smartctl --all --device jmb39x-q,0 /dev/sdb
sudo smartctl --all --device jmb39x-q,1 /dev/sdb
sudo smartctl --all --device jmb39x-q,2 /dev/sdb
sudo smartctl --all --device jmb39x-q,3 /dev/sdb
```

below the output for one query, which shows the SMART data for the first disk.

`sudo smartctl --all --device jmb39x-q,0 /dev/sdb
smartctl 7.2 2020-12-30 r5155 [armv7l-linux-5.10.63-v7l+] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Crucial/Micron Client SSDs
Device Model:     CT1000MX500SSD1
Serial Number:    <removed>
LU WWN Device Id: 5 00a075 1e589fed1
Firmware Version: M3CR033
User Capacity:    1,000,204,886,016 bytes [1.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    Solid State Device
Form Factor:      2.5 inches
TRIM Command:     Available
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ACS-3 T13/2161-D revision 5
SATA Version is:  SATA 3.3, 6.0 Gb/s (current: 3.0 Gb/s)
Local Time is:    Thu Dec  2 22:58:56 2021 CET
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART Status not supported: NO DATA ATA commands not implemented [JMB39x]
SMART overall-health self-assessment test result: PASSED
Warning: This result is based on an Attribute check.

General SMART Values:
Offline data collection status:  (0x80) Offline data collection activity
                                        was never started.
                                        Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0) The previous self-test routine completed
                                        without error or no self-test has ever
                                        been run.
Total time to complete Offline
data collection:                (    0) seconds.
Offline data collection
capabilities:                    (0x7b) SMART execute Offline immediate.
                                        Auto Offline data collection on/off support.
                                        Suspend Offline collection upon new
                                        command.
                                        Offline surface scan supported.
                                        Self-test supported.
                                        Conveyance Self-test supported.
                                        Selective Self-test supported.
SMART capabilities:            (0x0003) Saves SMART data before entering
                                        power-saving mode.
                                        Supports SMART auto save timer.
Error logging capability:        (0x01) Error logging supported.
                                        General Purpose Logging supported.
Short self-test routine
recommended polling time:        (   2) minutes.
Extended self-test routine
recommended polling time:        (  30) minutes.
Conveyance self-test routine
recommended polling time:        (   2) minutes.
SCT capabilities:              (0x0031) SCT Status supported.
                                        SCT Feature Control supported.
                                        SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x002f   100   100   000    Pre-fail  Always       -       0
  5 Reallocate_NAND_Blk_Cnt 0x0032   100   100   010    Old_age   Always       -       0
  9 Power_On_Hours          0x0032   100   100   000    Old_age   Always       -       28
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       8
171 Program_Fail_Count      0x0032   100   100   000    Old_age   Always       -       0
172 Erase_Fail_Count        0x0032   100   100   000    Old_age   Always       -       0
173 Ave_Block-Erase_Count   0x0032   100   100   000    Old_age   Always       -       1
174 Unexpect_Power_Loss_Ct  0x0032   100   100   000    Old_age   Always       -       2
180 Unused_Reserve_NAND_Blk 0x0033   000   000   000    Pre-fail  Always       -       25
183 SATA_Interfac_Downshift 0x0032   100   100   000    Old_age   Always       -       0
184 Error_Correction_Count  0x0032   100   100   000    Old_age   Always       -       0
187 Reported_Uncorrect      0x0032   100   100   000    Old_age   Always       -       0
194 Temperature_Celsius     0x0022   069   049   000    Old_age   Always       -       31 (Min/Max 0/51)
196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       0
197 Current_Pending_ECC_Cnt 0x0032   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0030   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x0032   100   100   000    Old_age   Always       -       0
202 Percent_Lifetime_Remain 0x0030   100   100   001    Old_age   Offline      -       0
206 Write_Error_Rate        0x000e   100   100   000    Old_age   Always       -       0
210 Success_RAIN_Recov_Cnt  0x0032   100   100   000    Old_age   Always       -       0
246 Total_LBAs_Written      0x0032   100   100   000    Old_age   Always       -       1143941803
247 Host_Program_Page_Count 0x0032   100   100   000    Old_age   Always       -       9325152
248 FTL_Program_Page_Count  0x0032   100   100   000    Old_age   Always       -       5377836

SMART Error Log Version: 1
No Errors Logged

Read SMART Self-test Log failed: ATA command not implemented due to truncated response [JMB39x]

Read SMART Selective Self-test Log failed: ATA command not implemented due to truncated response [JMB39x]

`
So - can this be fixed / configured, that the correct SMART data can be showed for the QNAP TR-004 in openmediavault or can be configured, which smartctl commands will be used for status / details ?

Here my infos

- OS version: [uname -a]
Linux nas 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux
- openmediavault version: [dpkg -l | grep openmediavault]
 openmediavault                       6.0.5-2 
**Client (please complete the following information):**
- Raspberry Pi 4
- Raspbian GNU/Linux 11 (bullseye)

Thanks
Miro

**Comment by votdev** [comment]
OMV only sees the RAID device and for that there are no SMART attributes available to assess the disk. OMV does not support SMART monitoring for devices BEHIND a RAID. If you disable the RAID feature of your controller so that OMV can see ALL disks attached to it, then you can see and monitor the SMART attributes.

**Comment by mirogl** [comment]
Ciao @votdev 
Thanks - I understand the definition form your side and it is correct, but on the other side currently I'm blind on my side regarding SMART.

I'm not sure, if a software raid with a raspberry pi 4 would have a performance impact on the rasperry pi 4 - therefore i took a external enclosure with hardware raid5. So is it reccomended to use the software RAID function form OMV for RAID5 or will it lead to a much higher CPU load on the server ?

Do i have any possibility to integrate this custom smartctl commands into the openmediavault dasboard ? I did't find any infos about a customization feature there.

Thanks
Miro

**Comment by votdev** [comment]
> I'm not sure, if a software raid with a raspberry pi 4 would have a performance impact on the rasperry pi 4 - therefore i took a external enclosure with hardware raid5. So is it recommended from your opinion to use the software RAID function form OMV for RAID5 or will it lead to a much higher CPU load on the server ?

IMO a Pi is the absolute wrong hardware for a NAS. You have to do your own tests to decide which way to go. I will not give any advices here.

> Do i have any possibility to integrate this custom smartctl commands into the openmediavault dasboard ? I did't find any infos about a customization feature there.

I'm sorry, it is not possible because OMV does not know about the hardware behind the RAID. It was a design decision to do not support that otherwise tons of hardware must be specified somehow, implemented and maintained.

**Comment by mirogl** [comment]
Hi @votdev 
Many thanks - for me  openmediavault  works perfect with the Pi4 - no issues. Regarding the SMART feature I fully understand your statement and will try the hint from the forum i found, if i got some time. 

https://forum.openmediavault.org/index.php?thread/21878-smartctl-and-smart-panel/&postID=168473&highlight=smartctl#post168473

Currently it is enough for me to use crontab and some automated tests.

Thanks
Miro

**Comment by votdev** [comment]
Trust me, this will not work with your setup. The disks behind your hadware/RAID is not visible to the Linux kernel; the code you mentioned is totally different. The disks for the HP and Areca RAID are visible to the kernel, but must be addressed with special smartctl arguments to get it working. Note, the HP and Areca controllers must be flashedand configured in a non-RAID mode, otherwise the disks are also hidden to the Linux kernel and OMV. In your case Linux and OMV only sees /dev/sdb, nothing more.

**Comment by mirogl** [comment]
Hi @votdev 
Thanks - ok. So i will keep the crontab skript solution. Many thanks.
Miro
