### ISSUE TITLE
OMV upgrades mixing up UUIDs

### ISSUE THREAD

**Issue by MarcS1975** [openmediavault/openmediavault#1155]
After a recent upgrade to 5.6.21-1 I cannot mount all my drives.

I have 7 encrypted drives and all can be unlocked after booting but only 6 drives mount as expected.
1 disk always brings an error message when trying to mount using fstab.

**Reproduce**
1. reboot
2. unlock drives in OMV GUI encryption
3. all drives unlock

**Error Message**
_Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; mount -v --source '/dev/disk/by-uuid/b6c87626-ea4b-4661-abbd-d3b5a2137ea9' 2>&1' with exit code '1': mount: /dev/disk/by-uuid/b6c87626-ea4b-4661-abbd-d3b5a2137ea9: can't find mount source /dev/disk/by-uuid/b6c87626-ea4b-4661-abbd-d3b5a2137ea9 in /etc/fstab._

(I can mount the drive manually to /mnt/temp and access all files.)

**Comment by votdev** [comment]
https://forum.openmediavault.org/index.php?thread/41023-mount-problem-luks-after-upgrade/

**Comment by votdev** [comment]
@ryecoaaron I think this is LUKS related.

@MarcS1975 Please provide more details about your system, the best would be to provide the report that can be generated via UI.

**Comment by MarcS1975** [comment]
Thanks but the two OMV forum posts were by me and unfortunately did not resolve the issue.
The conclusion we came to is that there is something wrong with UUIDs in config.xml and fstab but none of us knows how they really work together.
Unlocking the drive in LUKS works and mounting it manually also works (mount /dev/mapper/sdg-crypt /mnt/temp)

What report would you like me to run in GUI?

**Comment by MarcS1975** [comment]
Just saw your forum reply now.....will respond there. thanks

**Comment by ryecoaaron** [comment]
It is LUKS related but it seems like something was changed outside of the plugin and the database doesn't match the setup now.  The plugin hasn't changed in almost 2 years.  So, I don't know why it would stop working now.

**Comment by MarcS1975** [comment]
The strange thing is that 6 disks work fine and only 1 has that mismatch.
Is there a way to rebuild the database?

**Comment by ryecoaaron** [comment]
I would try fixing the bad entry in the mntent section in /etc/openmediavault/config.xml with the correct uuid from an unlocked container in blkid

**Comment by MarcS1975** [comment]
When looking at the mntent section, I can recognise entries for each disks but non of the UUID's mentioned match any of the UUIDs in the fstab or in 'df'. The fstab also has a mix of device definitions by label and some (a few) by UUID).
How do the UUIDs get generated or read into config.xml?
Is it possible to reset that and just read all the devices present in the system from scratch.

**Comment by ryecoaaron** [comment]
The device definitions are probably different because of when you created them on different versions of OMV.

Which UUIDs?  The actual uuid field in the mntent entry is generated (not from the filesystem uuid).

If you don't have any sharedfolders (or just point them to something else temporarily), you could delete all of the mntent entries, unmount the filesystems, and re-mount them in the web interface.  That is a pain but so is trying to walk someone through fixing this.  I don't think this is an OMV "bug" or a plugin bug.  It might be easier to work on this on the forum since more people could help.
