### ISSUE TITLE
升级报错

### ISSUE THREAD

**Issue by Michael-gu** [openmediavault/openmediavault#1158]
Setting up openmediavault (6.0.5-3) ...
Creating configuration database ...
Migrating configuration database ...
Setting up Salt environment ...
**[ERROR   ] Command '/usr/bin/patch' failed with return code: 1
[ERROR   ] stdout: patching file /tmp/__salt.tmp.81ns2d4u (read from /lib/python3/dist-packages/salt/modules/network.py)
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file /tmp/__salt.tmp.lotnh4dz
[ERROR   ] retcode: 1
[ERROR   ] Command '/usr/bin/patch' failed with return code: 1
[ERROR   ] stdout: patching file /tmp/__salt.tmp.ksw3qaim (read from /lib/python3/dist-packages/salt/fileserver/roots.py)
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file /tmp/__salt.tmp.5_cwyaty
[ERROR   ] retcode: 1**
Processing system modifications ...
Processing triggers for rsyslog (8.2102.0-2) ...
Processing triggers for openmediavault (6.0.5-3) ...
Restarting engine daemon ...
Updating workbench configuration files ...

**Comment by ryecoaaron** [comment]
This isn’t a problem since the patch has already been applied. No need to worry about anything.
