### ISSUE TITLE
Duplicating the system disk in the USB Backup plugin OMV6

### ISSUE THREAD

**Issue by sashaoshurkov** [openmediavault/openmediavault#1161]
Hello,

I am using the latest OMV 6. In the USB Backup plugin settings, I see a duplication of my system disk. Can you check this error only with me or not?

Screenshot of the problem ibb.co/N1wDH6L

**Comment by mi-hol** [comment]
@sashaoshurkov could you please add the screenshot directly into your post (via edit post)?

**Comment by sashaoshurkov** [comment]
> @sashaoshurkov could you please add the screenshot directly into your post (via edit post) and add the information requested in issue template?
Here is a list of my drives. KINGSTON SV300S37A60G is a system disk.
![pic1](https://user-images.githubusercontent.com/1682848/145798503-48af994f-bd33-4546-9c0f-c54f003bc3fb.PNG)

When adding or editing a task in the USB Backup plugin, my system disk appears twice in the list.
![pic2](https://user-images.githubusercontent.com/1682848/145798534-46d5ea58-076e-4cd2-b5e8-95f70b8a9faf.PNG)

**Comment by mi-hol** [comment]
> and add the information requested in issue template. 

With "issue template" I meant below copied text.
To get a bug fix specifically "**To Reproduce**" and versions are a must have.

**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

A clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**

A clear and concise description of what you expected to happen.

**Screenshots**

If applicable, add screenshots to help explain your problem.

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: [uname -a]
- openmediavault version: [dpkg -l | grep openmediavault]

**Client (please complete the following information):**

- Device: [e.g. iPhone6]
- OS: [e.g. iOS8.1]
- Browser [e.g. stock browser, safari]
- Version [e.g. 22]

**Additional context**

Add any other context about the problem here.

**Comment by sashaoshurkov** [comment]
@mi-hol 

The author of the usbbackup plugin is Volker Theile. This plugin is not part of the omv-extras repository.

**openmediavault Server (please complete the following information):**

- OS version: Linux PEDRO-NAS 5.14.0-0.bpo.2-amd64 #1 SMP Debian 5.14.9-2~bpo11+1 (2021-10-10) x86_64 GNU/Linux
- openmediavault version: openmediavault 6.0.5-3, openmediavault-usbbackup 6.0-9

**Client (please complete the following information):**

- OS: Windows 10, Android 11
- Browser: Google Chrome
- Version: 96

**Comment by mi-hol** [comment]
Did you discuss the issue in OMV forum?

**Comment by sashaoshurkov** [comment]
No. You can close this issue. I just wanted the OMV to work perfectly, so I reported the bug I found. For me personally, this bug is not a problem.

**Comment by ryecoaaron** [comment]
@sashaoshurkov  This particular issue is a bug and has been reported by a couple of people on the forum.  So, it should stay open.  I will give it a look but not promising anything.

@mi-hol The super long form is going to make people not want to report simple bugs like this where you just drop down the device list in the plugin.  Trying enforce filling it out for simple issues like this won't help anyone.

**Comment by ryecoaaron** [comment]
I don't see any code changes in the last couple of years that would cause this.  Should be the same code as omv5.  I need to plug something into my physical server to test.  Do you only ever see one device doubled?  What is the output of:  sudo blkid when you are seeing the doubled device.

**Comment by ryecoaaron** [comment]
It seems to be showing the device for every partition that has an OMV backend.  In your case, sdb has three partitions but swap does not have an OMV backend.  I plugged in two usb sticks that had two partitions each and each device was doubled in the device dropdown.  I think the fix is to unique the list but Volker may have a different idea.  Shouldn't be hard to fix either way.

**Comment by sashaoshurkov** [comment]
It may be worth excluding the system drive altogether. Who will make backups using the USB Backup plugin to the system disk, especially the principle of operation of the USB Backup plugin involves removing and connecting the disk, which is impossible to do with the system drive.

**Comment by ryecoaaron** [comment]
In my case, it isn’t duplicating the system disk but I agree.

**Comment by mi-hol** [comment]
but isn't there a specific plug-in to enable usage of system drive for data storage?

**Comment by ryecoaaron** [comment]
The sharerootfs plugin is used to create shared folders on the system drive.  The usb backup plugin is designed to rsync the contents of a drive when it is connected to the system.  Since you can't disconnect the system drive while it is running, there is no reason to list the system drive in the usb backup device list.

**Comment by votdev** [comment]
> It may be worth excluding the system drive altogether. Who will make backups using the USB Backup plugin to the system disk, especially the principle of operation of the USB Backup plugin involves removing and connecting the disk, which is impossible to do with the system drive.

The root file system is already filtered, see https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-usbbackup/usr/share/openmediavault/engined/rpc/usbbackup.inc#L68.

Could you please post the output of `mount`?

**Comment by votdev** [comment]
Please note that the USB backup plugin can not handle USB devices with multiple partitions and file systems. It assumes ONE file system per device.

**Comment by sashaoshurkov** [comment]
> The root file system is already filtered, see https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-usbbackup/usr/share/openmediavault/engined/rpc/usbbackup.inc#L68.
> 
> Could you please post the output of `mount`?

Dear @votdev,

It is possible that the system disk filtering function does not work quite correctly. Therefore, in the usb backup plugin, I see my two partitions (_/dev/sda1 on /boot/efi_ and _/dev/sda2 on / type ext4_) on the system disk

# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=1935000k,nr_inodes=483750,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=392896k,mode=755,inode64)
**/dev/sda2 on / type ext4 (rw,relatime,errors=remount-ro)**
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12996)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
sunrpc on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
/dev/sdb1 on /srv/dev-disk-by-uuid-146358f2-e264-82e8-386f-5d45039d996b type ext4 (rw,relatime,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
**/dev/sda1 on /boot/efi type vfat** (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro)
tmpfs on /tmp type tmpfs (rw,relatime,inode64)
overlay on /var/lib/docker/overlay2/3efdb8a3dbac31267985ca6aa549c4e553ba52b9458de090c2b8f140671504ae/merged type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/2EHJVNGOPXJCYOCRGQRZ4DYYN6:/var/lib/docker/overlay2/l/ZT3FQX5X7HO4XBN3TVOL2ZULX4:/var/lib/docker/overlay2/l/HZ7NNDWWYEA6OQ5QW4THDDQAWW:/var/lib/docker/overlay2/l/CZCG7CSAEXT64OCS64ILSRJCJ6,upperdir=/var/lib/docker/overlay2/3efdb8a3dbac31267985ca6aa549c4e553ba52b9458de090c2b8f140671504ae/diff,workdir=/var/lib/docker/overlay2/3efdb8a3dbac31267985ca6aa549c4e553ba52b9458de090c2b8f140671504ae/work)
overlay on /var/lib/docker/overlay2/0c3efce1ad23390b49110b6b055d4be2517088fcd30300eef8c78d2164394c9c/merged type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/GJ6QHIKEKDE5Q6SAYG3BE7Q6HA:/var/lib/docker/overlay2/l/OAW5LSTMGUSOHPCCUH4TYDVJXK:/var/lib/docker/overlay2/l/4P5SWLJIMB2YXZSHTFJP6M2PDD:/var/lib/docker/overlay2/l/4SYB5P3WDFI3SAMDIODTIVSXFO,upperdir=/var/lib/docker/overlay2/0c3efce1ad23390b49110b6b055d4be2517088fcd30300eef8c78d2164394c9c/diff,workdir=/var/lib/docker/overlay2/0c3efce1ad23390b49110b6b055d4be2517088fcd30300eef8c78d2164394c9c/work)
overlay on /var/lib/docker/overlay2/abb759bfe08642bbb3a24e4354714d328352077313821388c2a2511f450a5b8d/merged type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/FWKIGA3KDTQYWKXVWID4UBQHMT:/var/lib/docker/overlay2/l/5ZIY4TJXNMDYFVB74NZ4PNLBIR:/var/lib/docker/overlay2/l/FPUPWWZDG3K2VXN2ZRRDI7L4PN:/var/lib/docker/overlay2/l/UE2QWZ536F4C2M4YIOOOZ2WTNQ,upperdir=/var/lib/docker/overlay2/abb759bfe08642bbb3a24e4354714d328352077313821388c2a2511f450a5b8d/diff,workdir=/var/lib/docker/overlay2/abb759bfe08642bbb3a24e4354714d328352077313821388c2a2511f450a5b8d/work)
nsfs on /run/docker/netns/bef834a0b367 type nsfs (rw)
nsfs on /run/docker/netns/fc9284634e5f type nsfs (rw)
nsfs on /run/docker/netns/eaa44b7ce124 type nsfs (rw)
overlay on /var/lib/docker/overlay2/23b41533929b0f961aa62ca63af09aa0707a0056770c731a013cce7ab78ac3e8/merged type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/UDB6DFBKJUH4WUPHA6WCGR6OYF:/var/lib/docker/overlay2/l/UZNTACA7TCZ5BS7XJEFJ2VEHAG:/var/lib/docker/overlay2/l/OOFFHKHN67PR5BWE75HPPHMV66:/var/lib/docker/overlay2/l/XIA2RINMOV4UJ2M6YGT5EO3EN5:/var/lib/docker/overlay2/l/TAA3NPOIZESHVUL2IYD3IBRCKS:/var/lib/docker/overlay2/l/CQH7ZSUHQS53UMUFHIJL7GW2JW:/var/lib/docker/overlay2/l/S4A54TIA32HXNKUJDQC3OVTHUO:/var/lib/docker/overlay2/l/KJLFD6BKKS5H3NTWJL7JBD7FNC:/var/lib/docker/overlay2/l/V47WEYM2MIRPQTVW2VS3MUQAM3,upperdir=/var/lib/docker/overlay2/23b41533929b0f961aa62ca63af09aa0707a0056770c731a013cce7ab78ac3e8/diff,workdir=/var/lib/docker/overlay2/23b41533929b0f961aa62ca63af09aa0707a0056770c731a013cce7ab78ac3e8/work)
nsfs on /run/docker/netns/1fbe576aafdc type nsfs (rw)
overlay on /var/lib/docker/overlay2/36b9834629057460c0fe6508ba3bfbc3fe46a8f3a158a07128773b5ee8b8a9e9/merged type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/5HM3WWXXQT57LE34NKONUTG5CA:/var/lib/docker/overlay2/l/RYXWECFHKJW5R5FTKYWXGJTDG4:/var/lib/docker/overlay2/l/IA5DVT6EUCSBD5LMKQUAAVMBM3:/var/lib/docker/overlay2/l/EOWZTC6VXIQVJCGBOMTMKAQ2KV:/var/lib/docker/overlay2/l/DYDHGFWHNIWIRQ3SRYTM7QULDU:/var/lib/docker/overlay2/l/322Q34B7ZDXPXIVN47LXSOYUA4:/var/lib/docker/overlay2/l/GQJPY6Z4OB24EO42CVL6WFHVJK:/var/lib/docker/overlay2/l/KSD63LIYTUZFVD7OMTXKYWIU2V:/var/lib/docker/overlay2/l/Z26KWFQAW7IN7G2Z3PNRYLHZIM:/var/lib/docker/overlay2/l/AY6WYZFMLXMNZ7CKXBI7XF4OLW,upperdir=/var/lib/docker/overlay2/36b9834629057460c0fe6508ba3bfbc3fe46a8f3a158a07128773b5ee8b8a9e9/diff,workdir=/var/lib/docker/overlay2/36b9834629057460c0fe6508ba3bfbc3fe46a8f3a158a07128773b5ee8b8a9e9/work)
nsfs on /run/docker/netns/ebc9ed08cbf1 type nsfs (rw)
overlay on /var/lib/docker/overlay2/30065a9e2cdfb3c9d48c07bd269d50cdf48f61f3177a6f1d376a2eeadc2d132e/merged type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/5X4G3JJM2EXQMPZSMYLTPQC4IS:/var/lib/docker/overlay2/l/FXBYKUG3ACDKHP6BF3DOKMQ2QB:/var/lib/docker/overlay2/l/OEHKOJGWPDBYFGEESZM62VWOBI:/var/lib/docker/overlay2/l/J5EHGSVVWVDYCZ36TPLV7MFPUV:/var/lib/docker/overlay2/l/E24H6QDFGP3VCV7KL2MAO7QYE7:/var/lib/docker/overlay2/l/CT6YB5OHAJPDAMTTXWK23EFBIL,upperdir=/var/lib/docker/overlay2/30065a9e2cdfb3c9d48c07bd269d50cdf48f61f3177a6f1d376a2eeadc2d132e/diff,workdir=/var/lib/docker/overlay2/30065a9e2cdfb3c9d48c07bd269d50cdf48f61f3177a6f1d376a2eeadc2d132e/work)
nsfs on /run/docker/netns/16382981a89c type nsfs (rw)

**Comment by votdev** [comment]
As told, it does not make sense to support devices with multiple file systems as target destination for a backup. The plugin only supports one file system per device.

**Comment by votdev** [comment]
> It is possible that the system disk filtering function does not work quite correctly

The duplicate entry is caused by the fact that your KINGSTON device has multiple file systems. The plugin determines the parent device for each file system found and lists it in the UI. Your device has 3 file systems, one is skipped (SWAP), thus two entries are listed. As mentioned, the plugin only supports ONE file system per device, so the plugin works correct, but will not work finally. Need to skip devices like your KINGSTON with multiple file systems.

**Comment by sashaoshurkov** [comment]
> > It is possible that the system disk filtering function does not work quite correctly
> 
> The duplicate entry is caused by the fact that your KINGSTON device has multiple file systems. The plugin determines the parent device for each file system found and lists it in the UI. Your device has 3 file systems, one is skipped (SWAP), thus two entries are listed. As mentioned, the plugin only supports ONE file system per device, so the plugin works correct, but will not work finally. Need to skip devices like your KINGSTON with multiple file systems.

Thank @votdev 
But all the same it is strange. KINGSTON device is my system disk, according to the idea it should not have been visible at all, even though there are several partitions on it.

**Comment by ryecoaaron** [comment]
It is visible because it has extra partitions on it that aren't your system partition.  The new code should exclude those too.

**Comment by sashaoshurkov** [comment]
I just thought that a function that checks for the presence of a system partition will automatically exclude this entire drive. Well, okay, this is a philosophical topic :) Yes, thanks, I have already installed the update and checked, it works.

**Comment by votdev** [comment]
I don't know how to interpret your data because here everything is working as expected. Can you run the following script and post its output?
```
#!/usr/bin/php7.4 -c/etc/openmediavault
<?php
require_once("openmediavault/autoloader.inc");

$rootDeviceFile = \OMV\System\System::getRootDeviceFile();
printf("Root file system: %s\n", $rootDeviceFile);

$isRoot = \OMV\System\System::isRootDeviceFile($rootDeviceFile);
printf("Is root device: %s\n", $isRoot ? "yes" : "no");

$deviceFile = substr($rootDeviceFile, 0, -1);
printf("Device file: %s\n", $deviceFile);

$isRoot = \OMV\System\System::isRootDeviceFile($deviceFile);
printf("Is root device (strict): %s\n", $isRoot ? "yes" : "no");

$isRoot = \OMV\System\System::isRootDeviceFile($deviceFile, FALSE);
printf("Is root device (lax): %s\n", $isRoot ? "yes" : "no");
```

**Comment by sashaoshurkov** [comment]
```
# ./test.sh
Root file system: /dev/sda2
Is root device: yes
Device file: /dev/sda
Is root device (strict): no
Is root device (lax): yes
```

**Comment by votdev** [comment]
> ```
> # ./test.sh
> Root file system: /dev/sda2
> Is root device: yes
> Device file: /dev/sda
> Is root device (strict): no
> Is root device (lax): yes
> ```

It seems everything works as expected, or i'm wrong?
