### ISSUE TITLE
smbpasswd is not updated when the user uses the change password function.

### ISSUE THREAD

**Issue by Imp3** [openmediavault/openmediavault#1166]
**Describe the bug**

On 6.x fresh iso install from today.

When a user (unpriviledged or admin does not matter) uses the change password form the smbpasswd is not updated.
When a Admin edits the user and changes the password the smbpasswd is updated.

From my initial investigation it seems that the password chnage dialog is not emitting a OMV_NOTIFY_MODIFY for 		"org.openmediavault.conf.system.usermngmnt.user" whereas the usermgmnt.User page does.

Code in the SMB Plugin responsible for password change: https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/module/samba.inc#L198

I don't know the codebase too well and I don't know where these events originate from.
I saw that the password is not part of the event payload (which may be the reason why it's not emitted on password change?)

**To Reproduce**

1. enable smb
2. add user test with password test
3. login with user test
4. change password for user test with the change password dialog to test2
5. use smbclient -L $OMVIP -U test
6. pwd test works
7. pwd test2 does not work

**Expected behavior**

6. pwd test2 works
7. pwd test does not work

**openmediavault Server (please complete the following information):**

- Device: KVM VM
- OS version: Linux nas 5.14.0-0.bpo.2-amd64 SMP Debian 5.14.9-2~bpo11+1 (2021-10-10) x86_64 GNU/Linux
- openmediavault version: 6.0.5-3

**Client:**

- OS: Windows 10
- Browser irrelevant (not a frontend issue) but chrome
- Version 92

**Comment by ryecoaaron** [comment]
This [line](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/usermgmt.inc#L607) in the usermgmt rpc should trigger the samba module if the user is not new (exists).  Does it work if you change something else in addition to the password?

**Comment by Imp3** [comment]
Ah thanks for the Info. I had a look in this file and it seems [this](https://github.com/openmediavault/openmediavault/blob/e3db2c21db67ecbee432f2917fe592bb6e7f81d3/deb/openmediavault/usr/share/openmediavault/engined/rpc/usermgmt.inc#L1155) function is called when the password is updated via the form on the top right which does not call the dispatcher.

Yes it absolutely works when I use the change user form as admin to change a users password but I don't want to know the users password ideally :)

When I change other user settings after they have changed their password the smbpasswd is also not updated.
I think the password (which the user has chosen) is not in the context by now it's only in the /etc/shadow file.

When I change the password via the user form as admin it works as I said anyways but then I als know the users password.

**Comment by ryecoaaron** [comment]
Funny, I don't think this has ever worked.  A user can call smbpasswd though.  This will require some thought.

**Comment by Imp3** [comment]
After some reading, I naively think it would be enough to get all the user context information from the db update with the password and emit a event in the setPasswordByContext method? The only user of that method seems to be UserPasswordFormPageComponent from [here](https://github.com/openmediavault/openmediavault/blob/a75719d25c26ac73646565764f29d3f37dba5a0e/deb/openmediavault/workbench/src/app/pages/usermgmt/users/user-password-form-page.component.ts#L26)

Something like:

```php
function setPasswordByContext($params, $context) {
    // Validate the RPC caller context.
    $this->validateMethodContext($context, [
	    "role" => OMV_ROLE_EVERYONE
    ]);
    // Validate the parameters of the RPC service method.
    $this->validateMethodParams($params, "rpc.usermgmt.setpasswordbycontext");
    $user = new \OMV\System\User($context['username']);
    $user->assertExists();
    $user->changePassword($params['password']);

    $filter = [
        "operator" => "stringEquals",
        "arg0" => "name",
        "arg1" => $context['username']
    ];
    $db = \OMV\Config\Database::getInstance();
    if ($db->exists("conf.system.usermngmnt.user", $filter)) {
        $object = $db->getByFilter("conf.system.usermngmnt.user", $filter, 1);
        $objectAssoc = array_merge($object->getAssoc(), $params);
        $dispatcher = \OMV\Engine\Notify\Dispatcher::getInstance();
        $dispatcher->notify(OMV_NOTIFY_MODIFY, "org.openmediavault.conf.system.usermngmnt.user", $objectAssoc, $objectAssoc);
    }
}
```

but as I said I don't know the code very well, neither any side effects. I also don't have a test system I could only hot patch on my evaluation server :)

I can try to make PR tomorrow?

**Comment by ryecoaaron** [comment]
Users never see the apply bar. so it would have to make the change right away. Feel free to try a PR. Not sure when Volker is going to be back and I can’t merge a PR.
