### ISSUE TITLE
Coexist with proxmox, perhaps with alternate dependency on pve-ha-manager/watchdog-mux.

### ISSUE THREAD

**Issue by dsjstc** [openmediavault/openmediavault#1167]
**Is your feature request related to a problem? Please describe.**
Judging by the forums, desire for side-by-side use of OMV with Proxmox is a surprisingly common use-case -- largely because OMV doesn't trivially virtualize or containerize.

Side-by-side use is impossible, since OMV requires the watchdog package.  Proxmox has a package conflict with watchdog, since it provides it's own "watchdog-mux" service in the pve-ha-manager package.

**Describe the solution you'd like**
It would be great if OMV could find a way to coexist on bare metal with Proxmox.  Perhaps the watchdog-mux service provided by Proxmox's pve-ha-manager would work?

**Describe alternatives you've considered**
Alternatives include:
1) [changing watchdog to a suggestion](https://github.com/openmediavault/openmediavault/issues/224).
2) Convince Proxmox to change pve-ha-manager to a suggestion.

**Additional context**

**Comment by ryecoaaron** [comment]
I know it isn't quite the same but this is why I wrote the KVM plugin.  I switched from proxmox to OMV + KVM plugin myself.

**Comment by votdev** [comment]
A possible solution might be to add `watchdog | watchdog-mux` to the [control](https://github.com/openmediavault/openmediavault/blob/e3db2c21db67ecbee432f2917fe592bb6e7f81d3/deb/openmediavault/debian/control#L20) file, but adding a dependency of a package that is not in the official Debian repository does not feel right.

**Comment by donhwy** [comment]
OMV runs very well as a proxmox vm. Just install from iso. Use proxmox to manage disks and allocate virtual disks as needed to OMV. Disks can be resized as needed too. Have been using it for years.

**Comment by N0NameN0** [comment]
@dsjstc : so finally found a solution ? i'm facing the exact same case... :)

**Comment by votdev** [comment]
OMV is OSS, so feel free to contribute a patch that is tested and does not break existing installations. I'm not in favor of patching it because `watchdog-mux` is not in the official Debian nor the OMV repositories.

**Comment by N0NameN0** [comment]
even without talking about a official patch, i'm looking for a quick and dirty workaround to be able to install OMV on my proxmox (host level not vm )  ;)

**Comment by ryecoaaron** [comment]
You would have to remove the dependency and rebuild the package.  Have you tried the kvm plugin?

**Comment by ryecoaaron** [comment]
@N0NameN0 Whichever one you can build.  libvirt supports lxc containers.  Maybe I will look at adding that to the kvm plugin.

**Comment by N0NameN0** [comment]
would be nice to have LXC support to your plugin !! ;)

**Comment by N0NameN0** [comment]
@ryecoaaron : anyway i'm not able to rebuild the package ( lack of information ;) )

**Comment by ryecoaaron** [comment]
While I think building your own package is walking on thin ice, search for fakeroot on the forum.

**Comment by N0NameN0** [comment]
@ryecoaaron : i finally moved to modify the control file as mentioned by @votdev and rebuild. all seems ok. Thnx for the workaround guys.

**Comment by ryecoaaron** [comment]
Just don't install updates especially from the Updates tab in OMV or it will uninstall proxmox or openmediavault (depending on which update you install).

**Comment by donhwy** [comment]
Running OMV as a vm on Proxmox gives you the best of both without patching either. Good luck.

**Comment by N0NameN0** [comment]
@donhwy  : it was not an option for me since i don't want to passthru my GPU to the KVM/QEMU (transcoding...)

**Comment by dsjstc** [comment]
I built from master and can confirm it now coexists peacefully with Proxmox 7.  You've made one very happy homelabber here @votdev -- thanks very much!

**Comment by votdev** [comment]
> I built from master and can confirm it now coexists peacefully with Proxmox 7. You've made one very happy homelabber here @votdev -- thanks very much!

A big thank you also goes to @ryecoaaron for giving the systemd hint.
