### ISSUE TITLE
Samba Broken on OMV 6.0.6

### ISSUE THREAD

**Issue by DavidBerdik** [openmediavault/openmediavault#1168]
After updating to OMV 6.0.6, Samba appears to be broken. Tracing back the error leads me to line 75 of `shares.j2`.

https://github.com/openmediavault/openmediavault/blob/0fc2562522392b9142ed6223ee87aca6364be791/deb/openmediavault/srv/salt/omv/deploy/samba/files/shares.j2#L75

I have not tested this, but I think this line should be changed to the following:

```
{%- if share.sharedfolderref | salt['omv_conf.omv_conf_get_by_identifier']('conf.system.sharedfolder') | attr('mntentref') | salt['omv_conf.omv_conf_get_by_identifier']('conf.system.filesystem.mountpoint') | attr('type') == 'btrfs' %}
```

**Comment by votdev** [comment]
> I have not tested this, but I think this line should be changed to the following:

With the latest package version some [OMV Salt module functions](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/_modules/omv_conf.py#L48) are implemented as Jinja filter, so your changes are not necessary.

**Comment by votdev** [comment]
Please run `omv-salt stage run prepare` to re-sync the new OMV Salt modules.

**Comment by votdev** [comment]
By the way, how does the Salt error message look like?

**Comment by votdev** [comment]
> I realize that in the issue I linked to, you stated that you don't want to make `usrmerge` an OMV dependency, but I would ask that you please reconsider your stance on that. It seems to me like this problem could be avoided by making it one.

usrmerge was only necessary when migrating Debian 9 to Debian 10. With Debian 11 there shouldn't be systems out there that do not have a merged-usr root filesystem layout. So it does not make sense to me to add this dependency.

**Comment by DavidBerdik** [comment]
> usrmerge was only necessary when migrating Debian 9 to Debian 10. With Debian 11 there shouldn't be systems out there that do not have a merged-usr root filesystem layout. So it does not make sense to me to add this dependency.

Fair enough. I suppose the question then becomes: Why was my server not automatically reconfigured like this when I previously moved from Debian 9 to 10 and why did the issue remain when moving from 10 to 11? Also, if this has been an issue on my server for a while, why have I not encountered problems before?

**Comment by votdev** [comment]
> Also, if this has been an issue on my server for a while, why have I not encountered problems before?

Maybe because Debian fully converted all packages to the now default file system layout which might not be the case for Debian 10.

**Comment by DavidBerdik** [comment]
> Maybe because Debian fully converted all packages to the now default file system layout which might not be the case for Debian 10.

Ah that's understandable. It still doesn't really clear up the whole matter of why the update was never installed in the first place, though. I don't really understand it.

**Comment by ryecoaaron** [comment]
Debian puts in your hands to make the usrmerge change when upgrading. omv-release-upgrade could check for the symlinks and install the usrmerge package if not found.

**Comment by votdev** [comment]
> Debian puts in your hands to make the usrmerge change when upgrading. omv-release-upgrade could check for the symlinks and install the usrmerge package if not found.

Please review https://github.com/openmediavault/openmediavault/pull/1169

**Comment by DavidBerdik** [comment]
> Debian puts in your hands to make the usrmerge change when upgrading. omv-release-upgrade could check for the symlinks and install the usrmerge package if not found.

Ah well that would explain it, then. I didn't know about this.

> Please review #1169

Great! Thank you!
