### ISSUE TITLE
OMV6 keeps shadowing actual tmp

### ISSUE THREAD

**Issue by Pingger** [openmediavault/openmediavault#1173]
**Describe the bug**

OMV6 keeps mount an additional `/tmp` using `tmpfs` with ~200MB size, which is far too small for any use at all. Additionally there is already a 32GB SSD Partition mounted, that gets shadowed and several applications crash, because of this

**To Reproduce**

1. install OMV6
2. Run tmp-heavy application (e.g. install netdata)
3. tmp-heavy application crashes, out of disk-space

Alternatively (additionally as an attempt to work around the issue):
4. umount /tmp
-> actual tmp is available again
5. tmp-heavy application works as expected UNTIL some periodic background task of OMV5 AGAIN mounts that borked 200MB tmpfs on /tmp and shadows the actual `/tmp`

**Expected behavior**
OMV6 not shadowing `/tmp` AT ALL! Especially not with a 200MB programm-crasher

**Screenshots**

With the actual mount shadowed:
![image](https://user-images.githubusercontent.com/4761298/147841888-8703eda3-e32d-4b7a-bc4d-d4ba675cef90.png)

With original mount (after `umount -lazy /tmp`, lazy, because otherwise it is not unmountable):
![image](https://user-images.githubusercontent.com/4761298/147841911-b6d5a8e6-834d-4536-8a68-73cf78844ef8.png)

**Reference to Forum**

N/A

**openmediavault Server (please complete the following information):**

- OS version: Linux <hostname> 5.10.63-v7+ #1488 SMP Thu Nov 18 16:14:44 GMT 2021 armv7l GNU/Linux
- openmediavault version:  6.0.6-1

**Client (please complete the following information):**
N/A

**Additional Context**
I can verify, that the following applications have issues:
netdata-installer
my own ffmpeg wrapper, for transcoding videos inside the tempfolder
tmux, sessions no longer work properly (since those are also stored in /tmp)
**systemd**, because it suddenly can't access its own files
apache2 over systemd, because of the "PrivateTmp"-Setting of systemd
chrony over systemd, because of the "PrivateTmp"-Setting of systemd (this is a dependeny of omv! that doesn't work! because of OMV!)

**Comment by votdev** [comment]
I've never had any issues with tmpfs in the last 12 years of OMV and this is the first reported problem. So the default Debian settings seem not to cause huge problems. OMV itself uses the Debian defaults for managing tmp. What is your expectation how to so solve the problem? The question is, how should OMV solve the problem? The size of a tmp depends on the special requirements of the user. There is surely no right or wrong setting.

**Comment by Pingger** [comment]
I see two possible solutions:
1. (simple) Setting to just disable OMV managing the /tmp folder and leaving it as is. Just like EVERY other software does
2. (extended) configuration, for /tmp. how large, tmpfs or physical drive, ...

**Comment by votdev** [comment]
OMV follows the philosophy: Don't touch anything that is not necessary. This applies to the /tmp configuration. This is done by the Debian tools and infrastructure OMV relies on. In you case the settings are managed surely by Raspbian or any other derivate for ARM platforms.

**Comment by votdev** [comment]
@ryecoaaron I see folder2ram is involved here, can you comment on it please?

**Comment by votdev** [comment]
I closed the issue because it seems the issue is raised by an external plugin. Please report the problem [here](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-flashmemory/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

**Comment by ryecoaaron** [comment]
folder2ram (openmediavault-flashmemory plugin) puts things in tmpfs to avoid writing to disk and prematurely wearing it out.  If you don't want this, uninstall the plugin.  There is no way for the plugin to avoid the writes and not use tmpfs.

**Comment by Pingger** [comment]
no additional plugins at all are installed, this is literally the standard installation using your installscript

**Comment by ryecoaaron** [comment]
And the installscript installs the flashmemory plugin.  Look in the Plugins tab and uninstall it if you are having issues with tmpfs.  If you want to use the install script and not install the flashmemory plugin (not recommended if using an SD card), add the -f flag - https://github.com/OpenMediaVault-Plugin-Developers/installScript/blob/master/install#L84

**Comment by votdev** [comment]
You can [disable the installation of the plugin](https://github.com/OpenMediaVault-Plugin-Developers/installScript/blob/master/install#L316) with the `-f` parameter.

Now that it is installed, simply uninstall it if it does not match your requirements.

**Comment by Pingger** [comment]
since disabling the plugin didn't solve the issue, my solution was to completely uninstall OMV and then the issue was gone ... 
My temporary "workaround" was
```
while true; do
    unmount --lazy /tmp
    mount /tmp
    sleep 0.1
done;
```
(and it was surprisingly effective)
