### ISSUE TITLE
Vagrant file is freezing because it cannot handle correctly  network interface names

### ISSUE THREAD

**Issue by alansenairj** [openmediavault/openmediavault#1178]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

https://forum.openmediavault.org/index.php?thread/41554-vagrant-file-is-freezing-with-message-omv6box-waiting-for-machine-to-reboot/#post297126

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

https://forum.openmediavault.org/index.php?thread/41554-vagrant-file-is-freezing-with-message-omv6box-waiting-for-machine-to-reboot/#post297126

**Describe the bug**

Vagrant file is not ending to run because network is not configured. 
Vagrant file from github is not working here. It cannot finish installation. It is stopped with this message:

You need to update guest additions: 

    omv6box: The guest additions on this VM do not match the installed version of
    omv6box: VirtualBox! In most cases this is fine, but in rare cases it can
    omv6box: prevent things such as shared folders from working properly. If you see
    omv6box: shared folder errors, please make sure the guest additions within the
    omv6box: virtual machine match the version of VirtualBox you have installed on
    omv6box: your host and reload your VM.
    omv6box: 
    omv6box: Guest Additions Version: 6.0.0 r127566
    omv6box: VirtualBox Version: 6.1

**==> omv6box: Waiting for machine to reboot...**

If I use console and do dhclient on ensp03 and ensp08 it works. But you have a problem with script to configure network. 

    omv6box: [ERROR   ] Interface "ens8" not in available interfaces: "lo", "enp0s3", "enp0s8", "enp0s9"
    omv6box: jq: error (at <stdin>:3): Cannot index string with number
    omv6box: Traceback (most recent call last):
    omv6box:   File "/usr/sbin/omv-confdbadm", line 76, in <module>
    omv6box:     sys.exit(main())
    omv6box:   File "/usr/sbin/omv-confdbadm", line 72, in main
    omv6box:     return cmd_inst.execute(*sys.argv)
    omv6box:   File "/usr/share/openmediavault/confdbadm/commands.d/populate.py", line 50, in execute
    omv6box:     openmediavault.procutils.check_call([script_path])
    omv6box:   File "/usr/lib/python3/dist-packages/openmediavault/procutils.py", line 58, in check_call
    omv6box:     return subprocess.check_call(*popenargs, **kwargs)
    omv6box:   File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    omv6box:     raise CalledProcessError(retcode, cmd)
    omv6box: subprocess.CalledProcessError: Command '['/usr/share/openmediavault/confdb/populate.d/40interfaces.sh']' returned non-zero exit status 5.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what

You must edit this script to get correct IF name: 

![image](https://user-images.githubusercontent.com/20565821/149060585-3fc069e7-aec8-4919-ab9c-26772f7f3dd5.png)

I'm using Fedora 35 to install it. My VBox is 6.1 version (latest)

I installed libvirt too.

**To Reproduce**

1. Go to '...' clone repo - run it using vbox.

**Expected behavior**

**Screenshots**

**Reference to Forum**

[URL link to forum post](https://forum.openmediavault.org/index.php?thread/41554-vagrant-file-is-freezing-with-message-omv6box-waiting-for-machine-to-reboot/#post297126)

**openmediavault Server (please complete the following information):**

- OS version: [uname -a]
- openmediavault version: [dpkg -l | grep openmediavault]

![image](https://user-images.githubusercontent.com/20565821/149060730-2ff04243-5b15-4c1c-9e44-6d3c652c3b8d.png)

![image](https://user-images.githubusercontent.com/20565821/149060867-8774354c-18a3-4cd6-ac20-49ae7bf27480.png)

**Client (please complete the following information):**

**Additional context**

**Comment by alansenairj** [comment]
This is my Vagrant file: 

# Default values.
hostname = "omv6box"

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bullseye64"
	config.vm.define hostname
	config.vm.provision :shell, reboot: true, :path => "patch.sh"
	config.vm.provision :shell, :path => "install.sh"
	config.vm.network "private_network", ip: "192.168.56.200" #, auto_config: false
	config.vm.network "private_network", ip: "192.168.56.201"
	config.vm.hostname = hostname
	config.vm.boot_timeout = 200
#	config.vm.provision :shell, :inline => "/etc/init.d/networking restart"
	config.vm.provider :virtualbox do |vb|
		vb.gui = true
	  end
#	config.ssh.private_key_path = "/home/alan/SRVs/Vagrant_Ubuntu/opv64/openmediavault/vagrant/id_rsa"

	config.vm.provider :virtualbox do |prov|
		prov.name = hostname
		prov.memory = "2048"
		# Add some disks.
		for i in 0..2 do
			filename = "./disks/#{hostname}-disk#{i}.vmdk"
			unless File.exist?(filename)
				prov.customize ["createmedium", "disk", "--filename", filename,
					"--size", 1000 * 1024]
				prov.customize ["storageattach", :id, "--storagectl",
					"SATA Controller", "--port", i + 1, "--device", 0,
					"--type", "hdd", "--medium", filename]
			end
		end
	end
	config.vm.provider :libvirt do |prov|
		prov.memory = "2048"
		# Add some disks.
		for i in 0..2 do
			prov.storage :file, :size => "1G", :bus => "scsi"
		end
	end
	config.vm.synced_folder "/home/alan/SRVs/Vagrant_Ubuntu/opv64/openmediavault/files", "/home/vagrant/openmediavault",
		:type => "nfs",
		:nfs_version => 4
	config.vm.provision :shell, :inline => "systemctl restart networking"		
end

**Comment by votdev** [comment]
Can you please post the `/etc/network/interfaces` content right after the installation breaks?

**Comment by votdev** [comment]
Have you tried `vagrant up --provider libvirt`? Seems there is a problem with VirtualBox. I have not tested that since years now because i fully switched to libvirt. Maybe i simply have to remove the VagrantBox support to reduce problems.

**Comment by alansenairj** [comment]
Ok! I installed ISO with no problems. I will leave it. It is giving a mesage about network interface eth1 not found.
