### ISSUE TITLE
omv-5.x-Secondary development translation

### ISSUE THREAD

**Issue by byjos** [openmediavault/openmediavault#1179]
hello，I have a problem with translation during development and would like to ask for help.
In the secondary development function, add functions under the service, add folders and corresponding files，add the translation in the js code as follows:
![image](https://user-images.githubusercontent.com/25920168/149120081-1c1422e1-43fd-46e8-a3f9-b7bb246436ba.png)

path ：/var/www/openmediavault/js/omv/module/admin/service/vpn/Shares.js
I don't really know how to get these translations to work。

![image](https://user-images.githubusercontent.com/25920168/149120528-8ebf75cf-7eea-4d91-b829-5625ce814d76.png)
Add an entry in this translation file, use the msgfmt command to generate mo, but it still does not take effect. I don't know how the translation principle works. I would like to ask.

path：/usr/share/openmediavault/locale/zh_CN/openmediavault.po

**Comment by votdev** [comment]
You need to convert the PO files into JSON using `omv-mki18ndict` in the OMV system.

**Comment by mi-hol** [comment]
@byjos did the proposed solution work?
Please close if it worked

**Comment by byjos** [comment]
> You need to convert the PO files into JSON using `omv-mki18ndict` in the OMV system.

Thanks for your help,！it's ok！
