### ISSUE TITLE
Filesystem "false" after import ZFS pools

### ISSUE THREAD

**Issue by g2ufo** [openmediavault/openmediavault#1184]
Latest OMV 6.0.8-1 (Shaitan) and latest zfs plugin with proxmox kernel.
Filesystem "false" after import ZFS pools.
But all pools is OK and share work fine
![Screenshot_1](https://user-images.githubusercontent.com/51451549/149509275-5b31fb28-d397-4cfd-b486-5f2e145a65a8.jpg)

**Comment by ryecoaaron** [comment]
This should be filed here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/issues
