### ISSUE TITLE
ZFS plugin properties configuration on omv 6

### ISSUE THREAD

**Issue by g2ufo** [openmediavault/openmediavault#1185]
Please add zfs properties configuration of zfs pool as in omv5.
I mean zfs get, zfs set, inherited

**Comment by ryecoaaron** [comment]
This should be filed here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/issues

And the zfs plugin is still work in progress since it needs to be completely rewritten.  Be patient.
