### ISSUE TITLE
nginx default_server should be able to be turned off

### ISSUE THREAD

**Issue by mortee** [openmediavault/openmediavault#1189]
I want to make a different web app be the default on my NAS, but the fact that OMV unconditionally adds default_server to the nginx site config makes this impossible.

I think a toggle called "Make default web server" should be added in General Settings / Web Administration / General Settings, and in the nginx config the default_server directive made dependent on this setting.

If extending the control panel is considered too much clutter, then an environment variable could also control this behaviour, provided that it's clearly documented.

[Apparently](https://forum.openmediavault.org/index.php?thread/12307-changing-omv-default-behavior-nginx-configuration/) back in the v2.x days, the config used to be the same as it is currently, then the default_server directive was _removed_, and got added back in v5.3.4

**Comment by mortee** [comment]
As discussed in the comments on https://github.com/openmediavault/openmediavault/issues/620

**Comment by votdev** [comment]
> I think a toggle called "Make default web server" should be added in General Settings / Web Administration / General Settings, and in the nginx config the default_server directive made dependent on this setting.

This is not possible because OMV is an appliance and no webmin. Serving OMV has the highest priority, everything else is customization via environment variables.

**Comment by mortee** [comment]
I'm OK with the env variable solution too, as long as it can be done in any way.

**Comment by ryecoaaron** [comment]
Why not nginx in docker with OMV on non-standard port or docker using macvlan?

**Comment by mortee** [comment]
Because I just want to change the default site to a dummy honeypot, not totally rearchitect my NAS which is otherwise working fine.

**Comment by ryecoaaron** [comment]
Ok.  But spoofing the address header is still possible meaning it is much protection.  Just my .02

**Comment by mortee** [comment]
Come again?

**Comment by ryecoaaron** [comment]
Your honeypot may not be as safe as you think since you can spoof the address header and view a different virtual host if you know what the internal url is.

**Comment by ryecoaaron** [comment]
That is why I tell people to not put the OMV nginx instance on the internet.

**Comment by mortee** [comment]
Thanks for the advice. Anyhow, I just want to reduce the immediately obvious attack vectors. If just coming in by my IP a dummy certificate is presented which doesn't list the specific sites my box serves, it greatly reduces the chance of the casual attacker figuring out what might be vulnerable here. For now, that's good enough for me.
