### ISSUE TITLE
Changelog with Date

### ISSUE THREAD

**Issue by GUNT0815** [openmediavault/openmediavault#1191]
Could you pleae extend the changelog and add the date of the release publication next to the release number. This would allow to check the time-related maturity of a release or release candidate or beta version in order to "qualified" trigger the update/upgrades.

**Comment by votdev** [comment]
Let's see if that's somehow possible. By default the time is set when the version is bumped; which is normally after the latest version is released. Changing the time before a release means an, IMO, unnecessary commit for the changelog.

**Comment by GUNT0815** [comment]
Maybe there is a misunderstanding. I look at the changelog txt file and would like to see the date of the commit. I do not want to change the software dev procedure, but want to see in the changelog txt the date of the releases/commits ;-)

**Comment by ryecoaaron** [comment]
Wouldn't that require every line in the changelog to have a specific commit?  That isn't always the case.

**Comment by votdev** [comment]
Worthful changes are done via Issue/PR and  their ID is mentioned in the changelog. 
```
* Issue #1181: Use 'Warning' color for SMART assessment status 'BAD_SECTOR'.
```
If you want to know when it is merged simply use this URL `https://github.com/openmediavault/openmediavault/issues/<ID>`.

P.S.: never saw that type of changelog and i'm not really enthusiastisch about this format.

**Comment by ryecoaaron** [comment]
On gitlab, there is way to see a clickable list of commits between tags.  It is very handy but I don't see that option on github.

**Comment by votdev** [comment]
> On gitlab, there is way to see a clickable list of commits between tags. It is very handy but I don't see that option on github.

@ryecoaaron I do not use tags because the OMV repo contains multiple Debian packages, thus a tag can not be associated with a package. If the packages were splitted into different repos (like it is done in omv-extras) i already would have introduced tags.

**Comment by votdev** [comment]
> On gitlab, there is way to see a clickable list of commits between tags. It is very handy but I don't see that option on github.


@ryecoaaron I do not use tags because the OMV repo contains multiple Debian packages, thus a tag can not be associated with a package. If the packages were splitted into different repos (like it is done in omv-extras) i already would have introduced tags. Splitting it up does not make sense because the Debian build scripts are sharing various scripts that are located in the parent directory which would then be unreachable.
I know this has nothing to do with the current issue here, but worth to mention.

**Comment by ryecoaaron** [comment]
makes sense.  The tag could have the package name in it though.

**Comment by mi-hol** [comment]
Maybe following the [rules of "semantic versioning"](https://semver.org/spec/v2.0.0.html) would have a greated benefit for the user community than adding a date.
For example adding "conflicts" to prevent installation on a desktop would have resulted in a 7.0.0 version instead of hiding the impact in a minor bugfix patch like 6.0.8

**Comment by votdev** [comment]
> Maybe following the rules of "semantic versioning" would have a greated benefit for the user community than adding a date.

OMV already uses semantic versioning.

> For example adding "conflicts" to prevent installation on a desktop would have resulted in a 7.0.0 version instead of hiding the impact in a minor bugfix patch like 6.0.8

OMV6 has not been declared as stable nor released officially till now, so it is no problem to introduce breaking changes at the current stage. It is also clearly stated in the release candidate blog post that it is not meant for production use.

**Comment by mi-hol** [comment]
> stated in the release candidate blog post

well semver has the rule to flag "A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–." Blog posts are often **unknown** to users and not used by apt when updates are applied, therefore only above quoted rule in the version number is a reliable approach to convey the information.


> OMV already uses semantic versioning.

There seems room for improvement

**Comment by votdev** [comment]
> > stated in the release candidate blog post
> 
> well semver has the rule to flag "A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–."
> 

`openmediavault (6.0.9-4) unstable; urgency=low` 

---> unstable <---- Nothing more to say. 

> Blog posts are often **unknown** to users and not displayed by apt when updates are applied, therefore only above quoted rule in the version number is a reliable approach to convey this vital information.
> 
> > OMV already uses semantic versioning.
> 
> There seems room for improvement

No, all is going right.

**Comment by votdev** [comment]
> Blog posts are often unknown to users and not displayed by apt when updates are applied, 

If the user does not read the blog, then this it his problem, not mine and not the project. The changelog clearly mentions `unstable`.
