### ISSUE TITLE
Flashmemory error when update from 5 to 6

### ISSUE THREAD

**Issue by gvonkreisler** [openmediavault/openmediavault#1193]
openmediavault-flashmemory
W: --force-yes is deprecated, use one of the options starting with --allow instead.

E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by votdev** [comment]
> W: --force-yes is deprecated, use one of the options starting with --allow instead.

This is only a warning and is not the reason for the aborted upgrade.

Please provide us more information if possible. Otherwise we can not reproduce it.

> openmediavault-flashmemory

@ryecoaaron Any idea?

**Comment by gvonkreisler** [comment]
Hey,
the OMV is installed as VBOX image with ZFS plugin.
Got the last update from 5, then I did a upgrade to 6.
Now omv is "KAPUT" ;)
The apt source is corrupt, omv webserver and ssh are down.
LG
GVK

**Comment by gvonkreisler** [comment]
P.s is there any system log I can send ?

**Comment by votdev** [comment]
Maybe something helpful is in `/var/log/dpkg.log` or `/var/log/apt/term.log`.

**Comment by ryecoaaron** [comment]
Definitely need more info. I have upgraded flashmemory many times without any issue.

**Comment by gvonkreisler** [comment]
OK, 
looks like SMB is also broken... and I got a 4k screen ...
the last two entrys in dpkg.log 
status half.configured omv-flmemory
remove flashmemory 5.0.9 <none>

In apt log
installing flashm. was halted because of to many errors.

I haven`t installed flasmemory at all.
 Greatings

**Comment by gvonkreisler** [comment]
BTW,
 @ Volker.
I am  using OMV when you made your announcement for the first version.
Thank you for your work.
And this is not an emergency my servers are running all on version 4.
LG
Schorsch

**Comment by gvonkreisler** [comment]
P.s 
Monday I can sent the VBOX drive with WETransfer. 
LG

**Comment by votdev** [comment]
> P.s Monday I can sent the VBOX drive with WETransfer. LG

That's a new way of debugging, but great idea. :-)

**Comment by gvonkreisler** [comment]
Ok. send me your address to info@mediafields.de
LG

**Comment by mi-hol** [comment]
@votdev is stale bot inactive? Issue should have been closed latest 1May automatically?
