### ISSUE TITLE
S.M.A.R.T set own health status limit values (CrystalDisk)

### ISSUE THREAD

**Issue by Bullnados** [openmediavault/openmediavault#1194]
Healt Status Setting (Zustandseinstellung) like in CrystalDiskInfo

**Is your feature request related to a problem? Please describe.**
Problem: Reported_Uncorrect secotres 2, but they are not increasing since years, but OMV shows them as bad

**Describe the solution you'd like**
Possibility to set own values when a value is bad. Benefit would be that you can identify easier increasing numbers

**Comment by votdev** [comment]
I don't know CrystalDiskInfo nor how it works, but modifying SMART values to suppress a warning message seems not the right approach to me. smartd will inform you if the attribute 187 (Reported_Uncorrect) will change its value, so there is no need to override it to see a difference.

Please check https://www.backblaze.com/blog/hard-drive-smart-stats/ to get some insights about attribute 187 and how to interpret this value: 

> once SMART 187 goes above zero, we schedule the drive for replacement.

If you think such a feature makes sense to you, please open a feature request at smartmontools which is IMO the better place to include.
