### ISSUE TITLE
Failing compile due to TypeError

### ISSUE THREAD

**Issue by jannesmyr** [openmediavault/openmediavault#1196]
When im trying to install openmediavault on my raspberrypi with this command:

> wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash

after 10 minutes I lose connection due to following issue:

`Rendering SLS 'base:omv.deploy.watchdog.default' failed: Jinja error: '>' not supported between instances of 'str' and 'int'`

**Comment by votdev** [comment]
As workaround download the install script and modify line

https://github.com/OpenMediaVault-Plugin-Developers/installScript/blob/ca7da1b1d9733d2dd3230807c4837cbd9562d307/install#L360

to `omv_set_default "OMV_WATCHDOG_SYSTEMD_RUNTIMEWATCHDOGSEC" "14s" true`.

**Comment by ryecoaaron** [comment]
I added the 's' to the script.  I thought it was redundant since the default unit is seconds.

**Comment by votdev** [comment]
> I thought it was redundant since the default unit is seconds.

That was the right assumption. I missed that case (value without unit) while implementing the Jinja filter.
