### ISSUE TITLE
SMB share use acl

### ISSUE THREAD

**Issue by shangjiaxuan** [openmediavault/openmediavault#1200]
**Is your feature request related to a problem? Please describe.**
In samba share, when using acl to control access, the samba documentation says [`Do not set ANY additional share parameters, such as force user or valid users. Adding them to the share definition can prevent you from configuring or using the share.`](https://wiki.samba.org/index.php/Setting_up_a_Share_Using_Windows_ACLs). Currently always write these entries from the user access config, and there's no switch to turn if off (also writes a null `vfs objects =`, which should be `vfs objects = acl_xattr` when using full acl support). The filesystem is zfs created outside omv.

**Describe the solution you'd like**
Add a switch where user can specify using full acl manually, without redundant permissions entries that breaks it.

**Describe alternatives you've considered**
A script to change the config file inserted after omv does this, and remove these entries. Or manually add everyone to rw list, and only configure acl from ssh command line (cannot change permissions as client user with enough permissions), new files written by client still cannot get correct permissions set.

**Additional context**
I think the description is sufficient.

**Comment by votdev** [comment]
`acl_xattr`is for NTFS only, not ZFS.

Could you please describe how to reproduce an empty `vfs objects` entry in the smb.conf?

**Comment by shangjiaxuan** [comment]
According to the doc [here](https://www.samba.org/samba/docs/current/man-html/vfs_acl_xattr.8.html), this vfs_bject is used for storing windows acl in extented filesystem attribute in filesystems that support xattr (similar to rsync's `fake root` that stores permissions in `xattr` as unprivileged user). ZFS can be configured to use `xattr=sa` and store the acl info in inode.

The following is an excerpt from config.xml that will result in that entry being added to every share:

```
    <smb>
      <enable>1</enable>
      <workgroup>WORKGROUP</workgroup>
      <serverstring>%h server</serverstring>
      <loglevel>0</loglevel>
      <usesendfile>1</usesendfile>
      <aio>1</aio>
      <timeserver>1</timeserver>
      <winssupport>0</winssupport>
      <winsserver></winsserver>
      <homesenable>0</homesenable>
      <homesbrowseable>1</homesbrowseable>
      <homesrecyclebin>0</homesrecyclebin>
      <extraoptions>min receivefile size = 16384
getwd cache = yes

idmap uid = xxx-xxx
idmap gid = xxx-xxx
idmap backend = idmap_rid:raspberrypi=xxx-xxx
nt acl support = yes
inherit acls = yes
acl_xattr:ignore system acls = yes
admin users = "RASPBERRYPI\Domain Admins"

map acl inherit = yes
map archive = no
map hidden = no
map read only = no
map system = no
store dos attributes = yes
inherit permissions = yes
vfs objects = acl_xattr</extraoptions>
      <shares>
        <share>
          <uuid>de7c0db6-9610-4f15-aab6-ae796814128d</uuid>
          <enable>1</enable>
          <sharedfolderref>a557bf82-2dc9-4bc8-ae85-743765d8824f</sharedfolderre>
          <comment>shared</comment>
          <guest>no</guest>
          <readonly>0</readonly>
          <browseable>1</browseable>
          <recyclebin>0</recyclebin>
          <recyclemaxsize>0</recyclemaxsize>
          <recyclemaxage>0</recyclemaxage>
          <hidedotfiles>0</hidedotfiles>
          <inheritacls>1</inheritacls>
          <inheritpermissions>0</inheritpermissions>
          <easupport>1</easupport>
          <storedosattributes>1</storedosattributes>
          <hostsallow></hostsallow>
          <hostsdeny></hostsdeny>
          <audit>0</audit>
          <timemachine>0</timemachine>
          <extraoptions></extraoptions>
        </share>
        <!--Other shares-->
      </shares>
    </smb>
```

**Comment by shangjiaxuan** [comment]
Release version may be relevant: `6.0.10-1`

**Comment by votdev** [comment]
> (Also it seems to be setting `fruit:aapl = yes` despite time machine not being enabled? Did not look deep into that, but there was a recent CVE related to that feature in samba?)

This is no problem because this option is always set to `yes` by default even if it is not defined in smb.conf.

**Comment by votdev** [comment]
You can not set `vfs object` in the `Extra options` field. OMV will set this depending on your share configuration. You can set the default value by using the `OMV_SAMBA_SHARE_VFSOBJECTS` environment variable. Please check the [documentation](https://openmediavault.readthedocs.io/en/5.x/various/advset.html#environmental-variables) how to do that.

Please note that OMV supports only a specific number of features per service. We try to allow users to customize them as much as possible, but we can not support ALL features of SMB or other services provided by OMV.

**Comment by votdev** [comment]
> **Describe the solution you'd like**
> Add a switch where user can specify using full acl manually, without redundant permissions entries that breaks it.

This is hard to implement when Windows ACL is not supported by OMV. I have a problem implementing something that does not relate to anything that the OMV UI supports. If you have a suggestion how to do that in a way that it fits to the OMV setup i'm happy to discuss this.

**Comment by shangjiaxuan** [comment]
Thank you for pointing out the omv environment settings. That really can solve much of the current issue by making windows show the correct permissions instead of a generic error (Though that sets every share with the same value, that's what I want.). As long as omv does not break the manual configured part, that should not be a problem,

Here's a suggestion for the `valid user` problem. Normally through omv, you can configure permissions on specific shared folders in the user an group tab, and currently cannot remove easily without manually removing all of that config from config.xml (silently fails, no change after de-selecting).

Current the samba share always uses that to set the valid user entries, and anything that is not null interferes with acl. I'm suggesting to add a toggle specific to shares to ignore that setting and do not produce those entries. I think that would be sufficient for users that want more customization.

**Comment by votdev** [comment]
> you can configure permissions on specific shared folders in the user an group tab, and currently cannot remove easily without manually removing all of that config from config.xml (silently fails, no change after de-selecting).

That is the main problem. Why not opening a simple bug report that this is not working instead of opening a feature request which requests weird things????

**Comment by shangjiaxuan** [comment]
Right, but shared folders may be shared across multiple protocols, and setting those permissions on protocol that do not use acl can become wanted. But you are right, my current problem only involves cleaning up all the permission entries.

But I guess that wouldn't be simple either, given that the permissions settings normally map to 'valid user' entry. Deselecting the `read write` option or selecting "no permissions" on each user and group neither map to removing the entire entry (`valid users`,`invalid users ` and `read list` `write list`). Deselecting does not logically map to a removal from `valid users`, and that is required.

**Comment by votdev** [comment]
After digging a little bit deeper into Windows ACL i have to reject this feature request. OMV will only support POSIX ACL.
But OMV already gives you all what you need to customize the `smb.conf` that way you need it.

- There is the `Extra options` field per share
- Salt, the configuration deployment engine, allows you to add [custom states](https://openmediavault.readthedocs.io/en/5.x/various/advset.html#the-saltstack-states). You can use the [ini_manage module](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.ini_manage.html) to remove the `valid users`, `invalid users`, `read list` and `write list` options in `smb.conf`.

**Comment by shangjiaxuan** [comment]
omv 6.0.10-1 seems not to be respecting the `OMV_SAMBA_SHARE_VFSOBJECTS` environment variable.  This may be a bug. Currently using regex in a sls to force it.

**Comment by votdev** [comment]
> omv 6.0.10-1 seems not to be respecting the `OMV_SAMBA_SHARE_VFSOBJECTS` environment variable. This may be a bug. Currently using regex in a sls to force it.

Can not confirm that. Have you followed the [guide](https://openmediavault.readthedocs.io/en/5.x/various/advset.html#environmental-variables) how to handle env variables in OMV?

```
root@omv6box:/home/vagrant# omv-env set OMV_SAMBA_SHARE_VFSOBJECTS "foo"
root@omv6box:/home/vagrant# omv-salt stage run prepare 1>/dev/null
root@omv6box:/home/vagrant# omv-salt deploy run samba 1>/dev/null
root@omv6box:/home/vagrant# cat /etc/samba/smb.conf | grep foo
path = /foo/data/
vfs objects = foo recycle
```

**Comment by shangjiaxuan** [comment]
I think I found it to be my problem. Originally I had the item in global section, and that produced empty share entry. I tried to edit the shares.j2 and forgot to revert after removing that entry from global.
