### ISSUE TITLE
Download time

### ISSUE THREAD

**Issue by lgLindstrom** [openmediavault/openmediavault#1201]
Takes ridiculous long time to download from Sourceforge. Please add mirrors.

**Comment by ryecoaaron** [comment]
sourceforge has many mirrors.  Did you try picking another one?

**Comment by lgLindstrom** [comment]
Was never offered to select a mirror. Just a big green button.

Den tis 1 feb. 2022 19:55Aaron Murray ***@***.***> skrev:

**Comment by ryecoaaron** [comment]
When you click the big green button and it is slow, the screen should have a button that says "Problems downloading?".  If you click that, it will let you select from 24 different mirrors.
![image](https://user-images.githubusercontent.com/1914475/152054983-be8fa5fa-ffab-4dc5-b0db-70f82b387fc9.png)

**Comment by lgLindstrom** [comment]
Thanks for the tip!

Den tis 1 feb. 2022 22:33Aaron Murray ***@***.***> skrev:
