### ISSUE TITLE
pam issue during omv5 to omv6 upgrade

### ISSUE THREAD

**Issue by dsm1212** [openmediavault/openmediavault#1202]
**Describe the bug**

I ran omv-release-upgrade and there was a problem upgrading Pam. The omv files in /etc/pam.d had references to pam_tally2 which is apparently no longer supported. At that point apt was wedged and needed this manually corrected.

**To Reproduce**
Run omv-release-update

**Expected behavior**
Should not get an error about the omv pam config files.

**Reference to Forum**

Is discussed here: https://forum.openmediavault.org/index.php?thread/41922-omv-5-to-omv-6-upgrade-issue/#post301260

**openmediavault Server (please complete the following information):**

- OS version: was upgrading from buster to bullseye
- openmediavault version: 
# dpkg -l | grep openm
ii openmediavault 5.6.24-1 all openmediavault - The open network attached storage solution
ii openmediavault-diskstats 5.1.1-2 all openmediavault disk monitoring plugin
ii openmediavault-keyring 1.0 all GnuPG archive keys of the OpenMediaVault archive
ii openmediavault-nut 5.2.2-1 all openmediavault Network UPS Tools (NUT) plugin
ii openmediavault-omvextrasorg 5.6.5 all OMV-Extras.org Package Repositories for OpenMediaVault
ii openmediavault-symlinks 5.0 all OpenMediaVault symlinks plugin

**Additional context**
There was another error during upgrade that I had to fix but I believe it happened after this one so I will report separately. THe issue was that proftpd would not update to a not supported entry in the proftpd.conf file.

The only reason I can see that others would not have reported this is that possibly if the omv upgrade happened before pam maybe it would work. So my guess is that the ordering of these changes on my system when dist-upgrade ran was different than others.

**Comment by votdev** [comment]
The issue should be adressed already in `omv-release-upgrade` by https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/usr/share/openmediavault/release-upgrade/pre.d/50-patch-omv-pam-conf.

**Comment by votdev** [comment]
Have you upgraded to `openmediavault 5.6.24` before the upgrade to OMV6?
