### ISSUE TITLE
proftpd won't update on upgrade from omv5 to omv6

### ISSUE THREAD

**Issue by dsm1212** [openmediavault/openmediavault#1203]
**Describe the bug**
During upgrade I found that proftpd-core would not execute post install. Journal log showed the issue was the line Identlookups in /etc/proftpd/porftpd.conf. This failure to start cascaded into other errors and dist-upgrade failed. OMV had a dependency such that it would not run the post upgrade due to this.

**To Reproduce**

Run omv-release-upgrade.

**Expected behavior**

Clean upgrade

**Reference to Forum**

More info here: https://forum.openmediavault.org/index.php?thread/41922-omv-5-to-omv-6-upgrade-issue/#post301260

**openmediavault Server (please complete the following information):**

**Additional context**

I think all I had ever done with ftp was to enable it from the OMV web so this setting should be there on other omv5 installations. Maybe somehow this happened because of the pam error cascading. Or maybe it would have been dealt with if OMV upgrade had already run. I can post more of my omv5 config if you can tell me what you want. I have it backed up to a usb.

**Comment by dsm1212** [comment]
OMV6 shows I do NOT have ftp enabled. I can sftp to the box, but is that available because I have SSH enabled? Anyhow I'm not entirely sure what uses or configured proftpd. I just wanted to add that ftp is not enabled and I don't think it was on omv5 either.

**Comment by votdev** [comment]
Have you upgraded to `openmediavault 5.6.24` before the upgrade to OMV6?

**Comment by dsm1212** [comment]
Interesting, I was completely up to date with check-updates. Is there a log or something I can check for sure? Or maybe those files are moved aside somewhere?

**Comment by votdev** [comment]
Can not reproduce this with the latest fixes.

**Comment by dsm1212** [comment]
Is ok, can I suggest we change omv-release-upgrade to create a log file including printing some versions? After reboot I lost that off my screen and it's unfortunate.

**Comment by ryecoaaron** [comment]
any apt package info you would want should be in /var/log/apt/term.log or history.log.

**Comment by dsm1212** [comment]
Thanks. So term.log is interesting. During my first run of omv-update-release I can see it was pulling the wrong versions and it appears to have terminated abruptly. The last line for example is:

Processing triggers for dictionaries-common (1.28.3~bpo10+1) ...

But the version in the correct bullseye main repo, and what i have installed now, is 1.28.4. So, somehow during my run of omv-release-upgrade sources were not correct. The upgrade script does an update prior to the dist-upgrade, but it either must have failed or my sources.list was wrong or maybe there was a network issue getting the update. On the next try using the fix script I can see it pulled the correct versions. I doubt I will figure out why this happened, but anyhow, this probably led to the mess and I'm lucky it turned out ok :-).

steve
