### ISSUE TITLE
Error in ACL setting after Delete User

### ISSUE THREAD

**Issue by chodorenko** [openmediavault/openmediavault#1206]
Hello,
if OVM Add on Domain user database change in external server and after i delete user and try setup ACL  on Directory i retrieve Error 

{
    "pid": 24392,
    "running": false,
    "outputfilename": "\/tmp\/bgoutputWz8QTx",
    "result": "",
    "error": {
        "code": 0,
        "message": "Failed to execute command 'export PATH=\/bin:\/sbin:\/usr\/bin:\/usr\/sbin:\/usr\/local\/bin:\/usr\/local\/sbin; export LANG=C.UTF-8; setfacl --remove-all -M '\/tmp\/setfaclib5udu' -- '\/srv\/dev-disk-by-uuid-b7a9d062-bb86-44b7-b007-9184debf152d\/BUH\/Bank_hoster.by' 2>&1' with exit code '2': setfacl: Invalid argument in line 13 of file \/tmp\/setfaclib5udu",
        "trace": "OMV\\ExecException: Failed to execute command 'export PATH=\/bin:\/sbin:\/usr\/bin:\/usr\/sbin:\/usr\/local\/bin:\/usr\/local\/sbin; export LANG=C.UTF-8; setfacl --remove-all -M '\/tmp\/setfaclib5udu' -- '\/srv\/dev-disk-by-uuid-b7a9d062-bb86-44b7-b007-9184debf152d\/BUH\/Bank' 2>&1' with exit code '2': setfacl: Invalid argument in line 13 of file \/tmp\/setfaclib5udu in \/usr\/share\/openmediavault\/engined\/rpc\/sharemgmt.inc:1061\nStack trace:\n#0 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(588): Engined\\Rpc\\ShareMgmt->Engined\\Rpc\\{closure}('\/tmp\/bgstatusZv...', '\/tmp\/bgoutputWz...')\n#1 \/usr\/share\/openmediavault\/engined\/rpc\/sharemgmt.inc(1068): OMV\\Rpc\\ServiceAbstract->execBgProc(Object(Closure), NULL, Object(Closure))\n#2 [internal function]: Engined\\Rpc\\ShareMgmt->setFileACL(Array, Array)\n#3 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(123): call_user_func_array(Array, Array)\n#4 \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod('setFileACL', Array, Array)\n#5 \/usr\/sbin\/omv-engined(537): OMV\\Rpc\\Rpc::call('ShareMgmt', 'setFileACL', Array, Array, 1)\n#6 {main}"
    }
}

Some user not exist in Active Directory domain now.  Script backup exist ACL from object to /tmp/setfaclxxxxx and add changes for new users. After Script Apply new user settings and retrieve Error (User do not exist and cant setup ACL)

**To Reproduce**

1. Create user 
2. Setup ACL on Filesystem
3. Delete user
4. Add in ACL rights for different user

**Expected behavior**
Setup ACL only for exist users

**Screenshots**
https://drive.google.com/file/d/12mdiG0ddAPNlPql5Ds4BKxuTcYfwgHlw/view?usp=drivesdk

**openmediavault Server :**
- OS version: Debian 10.11, Linux storage 5.10.0-0.bpo.5-amd64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) x86_64 GNU/Linux
- openmediavault version: 5.6.25-1

**Comment by votdev** [comment]
> 2. Setup ACL on Filesystem

You mean the ACL dialog for shared folders?

**Comment by votdev** [comment]
I can not reproduce the issue. Please describe what to do steps by step so that i can try to reproduce it. Which plugins are you using. Are you talking about an AD setup?

**Comment by chodorenko** [comment]
> > 2. Setup ACL on Filesystem
> 
> You mean the ACL dialog for shared folders?

Yes Acl for Shared folder as view on it screen https://drive.google.com/file/d/1C3bnpb-Kr5JdWxBnte8CJXdcKQ9HpgXH/view?usp=drivesdk

I use Active Directory Users and on one folder i create ACL for one User, after some time i delete its user from AD (not from acl) and go to its menu for add rights for new user. i search it user and add RW rights. (not deselect old user) 
After i apply rights i retrieve its error(see on first message).

i view file /tmp/setfaclXXXX and view on it file on line 13 username of deleted user. In getent passwd its user not present.

**Comment by chodorenko** [comment]
Ok , Please close Issue , i reopen if again retrieve its error.

**Comment by votdev** [comment]
The question is how should setfacl should behave correctly. I don't know exactly how user land apps should react when you process non existing users, but `chown` for example accepts to change the owner of a file to a UID that does not exist. Same is to `setfacl` as you see in the video. So i assume the problem lies somewhere in the NSS area.

```
root@omv5box:~# getent passwd | grep 1003
root@omv5box:~# touch test.md
root@omv5box:~# ls -alh *.md
-rw-r--r-- 1 root root 0 Feb  9 19:45 test.md
root@omv5box:~# chown 1003:1003 test.md
root@omv5box:~# echo $?
0
root@omv5box:~# ls -alh *.md
-rw-r--r-- 1 1003 1003 0 Feb  9 19:45 test.md
root@omv5box:~# echo $?
```
