### ISSUE TITLE
md raid disk list in diagnostics disk I/O inconsistent

### ISSUE THREAD

**Issue by dsm1212** [openmediavault/openmediavault#1215]
Minor issue...

omv 6.10.12-2 but it's been this way since I updated to omv6.

Under diagnostics -> performance statistics -> disk I/O...

My system has two md raid1 partitions. /dev/md0 and /dev/md126. For some reason /dev/md0 is listed twice on the statistics page and /dev/md126 is listed once. I think probably /dev/md0 should only be present once. I do have a /dev/md127 which is swap raid 0 (I know raid is not necessary for swap :-)). That is not displayed (and doesn't need to be), but maybe that partition is somehow causing this?

- OS version: Linux warehouse21 5.15.0-0.bpo.2-amd64 #1 SMP Debian 5.15.5-2~bpo11+1 (2022-01-02) x86_64 GNU/Linux
- openmediavault version: 
-# dpkg -l | grep openmediavault
ii  openmediavault                   6.0.12-2                               all          openmediavault - The open network attached storage solution
ii  openmediavault-diskstats         6.0-5                                  all          openmediavault disk monitoring plugin
ii  openmediavault-keyring           1.0                                    all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-nut               6.0-6                                  all          openmediavault Network UPS Tools (NUT) plugin
ii  openmediavault-omvextrasorg      6.0.7                                  all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-sharerootfs       6.0-3                                  all          openmediavault share root filesystem plugin
ii  openmediavault-symlinks          6.0.4                                  all          OpenMediaVault symlinks plugin

**Client (please complete the following information):**

- Device: PC
- OS: windows 11
- Browser chrome

# cat /proc/mdstat
Personalities : [raid0] [raid1] [linear] [multipath] [raid6] [raid5] [raid4] [raid10]
md0 : active raid1 sdc1[1] sdb1[0]
      31138560 blocks super 1.2 [2/2] [UU]
      bitmap: 0/1 pages [0KB], 65536KB chunk

md126 : active raid1 sdc6[1] sdb6[0]
      204425344 blocks super 1.2 [2/2] [UU]
      bitmap: 0/2 pages [0KB], 65536KB chunk

md127 : active raid0 sdc5[1] sdb5[0]
      16758784 blocks super 1.2 512k chunks

**Comment by votdev** [comment]
Please post the output of `omv-rpc -u admin 'FileSystemMgmt' 'enumerateMountedFilesystems' '{"includeroot": true}' | jq`.

**Comment by votdev** [comment]
Fixed in `openmediavault 6.0.13`.
