### ISSUE TITLE
sshd_config is overwritten by changes in the UI

### ISSUE THREAD

**Issue by OfficialMuffin** [openmediavault/openmediavault#1216]
To be able to access SSH as a regular non-sudo user, I have to add `AllowUser user` to the sshd_config file. After, when adding ssh keys to the GUI, the sshd-config file is modified and my changes wiped meaning I am unable to get back into the system through SSH without re-adding the `AllowUsers` line back in.

**Comment by ryecoaaron** [comment]
This is known because OMV controls that file.  All you have to do is add your user to the ssh group.  No need to modify the sshd config.

**Comment by votdev** [comment]
Thjat is how OMV works, it is the master of the configuration files. Modifying them manually breaks things and you'll loose your customization as soon as OMV recreates the config files. If you want to add custom setting use the 'Extra options' field or the [environment variables](https://openmediavault.readthedocs.io/en/5.x/various/advset.html#environmental-variables) provided by OMV.

**Comment by OfficialMuffin** [comment]
Ah thanks for your help
