### ISSUE TITLE
diagnostic log for ups is not laid out properly

### ISSUE THREAD

**Issue by dsm1212** [openmediavault/openmediavault#1221]
**To Reproduce**

Go to the Diagnostix->System Logs and select the UPS log.

The tabular layout is just wonky. The contents of the table are not aligned with the columns and the columns are not correct. Also the dates are not displayed correctly. On my system they are were showing december 2022 yesterday and now today they show jan 30, 2022. Is very strange because I look at journalctl and the upsd/upsmon logs look ok. I'm not sure what is going on. My ups is working, if I go to the Diagnostics->Services-UPS is ok and I get some ups status events when I reboot. Let me know the exact command you use to get the log and I'll attach the output so you have it.

**Expected behavior**
A readable and accurate log listing.

**Screenshots**
![Screen Shot 2022-02-19 at 8 35 30 PM](https://user-images.githubusercontent.com/7332569/154824965-4a83b924-88a6-4887-bb09-fb87f06acfe7.png)

**openmediavault Server (please complete the following information):**

- OS version: [uname -a]
Linux warehouse21 5.15.0-0.bpo.2-amd64 #1 SMP Debian 5.15.5-2~bpo11+1 (2022-01-02) x86_64 GNU/Linux

- openmediavault version: [dpkg -l | grep openmediavault]
# dpkg -l | grep openmediavault
ii  openmediavault                   6.0.12-2                               all          openmediavault - The open network attached storage solution
ii  openmediavault-diskstats         6.0-5                                  all          openmediavault disk monitoring plugin
ii  openmediavault-keyring           1.0                                    all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-nut               6.0-6                                  all          openmediavault Network UPS Tools (NUT) plugin
ii  openmediavault-omvextrasorg      6.0.7                                  all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-sharerootfs       6.0-3                                  all          openmediavault share root filesystem plugin
ii  openmediavault-symlinks          6.0.4                                  all          OpenMediaVault symlinks plugin

**Client (please complete the following information):**

- Device: macbook
- OS: catalina
- Browser chrome

**Additional context**

UPS info from services screen:
Init SSL without certificate database
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 20
battery.mfr.date: CPS
battery.runtime: 4425
battery.runtime.low: 300
battery.type: PbAcid
battery.voltage: 26.5
battery.voltage.nominal: 24
device.mfr: CPS
device.model: CST135UC
device.serial: CYALT2000066
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 10
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.version: 2.7.4
driver.version.data: CyberPower HID 0.4
driver.version.internal: 0.41
input.voltage: 121.0
input.voltage.nominal: 120
output.voltage: 121.0
ups.beeper.status: enabled
ups.delay.shutdown: 20
ups.delay.start: 30
ups.load: 10
ups.mfr: CPS
ups.model: CST135UC
ups.productid: 0601
ups.realpower.nominal: 810
ups.serial: CYALT2000066
ups.status: OL
ups.test.result: No test initiated
ups.timer.shutdown: -60
ups.timer.start: -60
ups.vendorid: 0764

**Comment by votdev** [comment]
Please post some of the lines in `/var/log/nut.log`.

**Comment by votdev** [comment]
Fixed in `openmediavault-nut 6.0-7`.

**Comment by votdev** [comment]
Cannot confirm a problem with the dates.

The system is in UTC, the browser displays the correct time in UTC+1.

![Bildschirmfoto vom 2022-02-20 12-12-41](https://user-images.githubusercontent.com/1897962/154839870-6d8ce691-0168-4f16-803a-9cdae4a34d0e.png)

**Comment by dsm1212** [comment]
Layout is good now, thanks. It seems the problem is that the nut log doesn't have year in it. Only month-day. I'm not sure how you can deal with that unless you can get the year into the log. Wait, actually if I do journalctl -a, none of the logs are showing year. Where is that configured?

**Comment by dsm1212** [comment]
Probably nut.log is the only one with contents more than 12 months old.  We just rolled over the year so it became obvious. Aside from adding year to the logs, I guess I could jsut delete the nut log once per year manually. Or maybe give it a different rotation poicy. Any other suggestion?

**Comment by votdev** [comment]
I switched to journalctl to retrieve the log output. The problem seems that nut does not write the year, so there is no way to get this information.
See https://github.com/openmediavault/openmediavault/commit/c3bb54bfeed6a9504adff074b21231713269f197

**Comment by dsm1212** [comment]
Sounds good, thanks

**Comment by dsm1212** [comment]
Just following up after updating... Looks good now, thanks.
