### ISSUE TITLE
ACL recusive permissions won't enable

### ISSUE THREAD

**Issue by runeverstraeten** [openmediavault/openmediavault#1228]
**The bug:**

I'm currently using OVM about for a year.

I have a shared folder but it ain't possible to drag and drop a folder with files to my server. I always have to add a clear folder and a my files separate from my folder. It got pretty annoying everytime creating my folders one by one and adding the files.

It gave me the following error 'The operation cannot be completed because you do not have permissions to access the components.' 

So i went looking for the cause of this problem, then i found the following;

It is not possible to enable recursive permission for my file directories, every time I enable this in my 'ACL' and save it, it doesn't save. When I go back to the ACL settings it is always disabled.

**Reproduce:**

1. Go to 'Shared Folders'
2. Click on your shared folder and 'ACL'
3. Click on 'recusive'
4. Save the settings
5. Reopen the 'ACL' and the recusive permissions will still be disabled.

**Expected behavior**

Hopefully this bug can be solved in one of the next upgrades, if that won't happen is there anyone who solved the problem. And can explain me how to solve it myself.

**Screenshots**
Recusive permissions are disabled.
<img width="1440" alt="Reproduce-1" src="https://user-images.githubusercontent.com/60828533/155394215-2bd3e444-44e0-4baf-95fa-800aafce2e3e.png">
Recusive permissions are enabled.
<img width="1440" alt="Reproduce-4" src="https://user-images.githubusercontent.com/60828533/155394237-ae534c5f-feb3-4e3b-8d2b-b3623c380669.png">
Save the recusive permissions.
<img width="1439" alt="Reproduce-3" src="https://user-images.githubusercontent.com/60828533/155394233-eb6bde36-2b10-4fdf-84eb-9fc5c380bef7.png">
Close the settings.
<img width="1440" alt="Reproduce-2" src="https://user-images.githubusercontent.com/60828533/155394225-0bbebf89-82e3-4be2-9375-034baec7f0c2.png">
Reopen the settings.
As u see it's again disabled --> thats the bug.
<img width="1439" alt="Reproduce-5" src="https://user-images.githubusercontent.com/60828533/155394241-d6cb062e-7a61-4c96-b987-d4cf0d516371.png">

**Software:**
- OS version: Linux 5.10.63-v7l+
- openmediavault version: 5.6.25-1 (Usul)

**Hardware:**
- Device: RASPBERRY PI 4, 8 GB RAM

**Comment by votdev** [comment]
I think you misunderstand the behaviour of the `Recursive` checkbox. This checkbox is used to tell the backend that the user/group privileges are recursively applied to all files/directories below the selected one. Please check the [manpage of setfacl](https://manpages.debian.org/bullseye/acl/setfacl.1.en.html#R,) for more information.

I will check to separate the checkboxes visually to prevent such a misunderstanding.

**Comment by votdev** [comment]
The UI in OMV6 has been improved this way:
![Bildschirmfoto vom 2022-02-24 00-01-40](https://user-images.githubusercontent.com/1897962/155424134-86679f6c-17c6-480f-bdd6-c3c50c8af3b1.png)
