### ISSUE TITLE
Device identification with the same ID - Genesys devices

### ISSUE THREAD

**Issue by maxfb87** [openmediavault/openmediavault#1229]
Hi, i have a raspberry pi2 B with n.2 usb to sata adapters and OMV identifies only one hard disk.

Following [this](https://forum.openmediavault.org/index.php?thread/29145-device-identification-in-case-of-same-sn/&pageNo=1) thread and [this](https://github.com/openmediavault/openmediavault/pull/746) PR, i've added these two files and the problem seems resolved.

-  /usr/local/bin/genesys-sn.sh
#!/bin/sh
SN=$(hdparm -I $1 | grep 'Serial\ Number' | awk -F ':' '{print $2}' | tr -d [:blank:])
echo "ID_SERIAL_SHORT=${SN}"
echo "ID_SERIAL=${ID_VENDOR}_${ID_MODEL}_${SN}-${ID_INSTANCE}"

- chmod +x /usr/local/bin/genesys-sn.sh

- /lib/udev/rules.d/99-genesys.rules
ACTION=="add", SUBSYSTEM=="block", ATTRS{idVendor}=="05e3", ATTRS{idProduct}=="0718", IMPORT{program}="/usr/local/bin/genesys-sn.sh $devnode", SYMLINK="disk/by-path/$env{ID_PATH}", SYMLINK+="disk/by-id/usb-$env{ID_SERIAL}"

I'm writing here to help if anybody else have the same problem (according to [this](https://openmediavault.readthedocs.io/en/5.x/troubleshooting.html)).

**Comment by votdev** [comment]
Is it somehow possible to implement it using the OMV/UDEV infrastructure?

- https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/etc/udev/rules.d/61-openmediavault-dev-disk-by-id.rules
- https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/lib/udev/serial_id

The `serial_id` command does exactly the same like your script, the rest is done using `ID_VENDOR`, `ID_MODEL`, `ID_INSTANCE` that is provided by UDEV.

If you convert the rule to the OMV way we can merge this into the OMV core. This way everyone using this device will get this improvement automatically.

**Comment by maxfb87** [comment]
Nice... i tried adding this device to file "61-openmediavault-dev-disk-by-id.rules" and it works!
I have created also a PR #1233 so everyone can benefit.
