### ISSUE TITLE
Guide for compiling openmediavault

### ISSUE THREAD

**Issue by ryanmusic** [openmediavault/openmediavault#123]
Hello,

I am interested in compile source code of omv, is there any readme or guideline that describes the steps of the compilation?

**Comment by votdev** [comment]
- Checkout the git repository
- Execute the following scripts:
```
$ apt-get install make
$ cd <omvrepo>/deb
$ make install_build_tools
$ make clean build
```
After that you have all openmediavault Debian packages in this directory.

**Comment by ryanmusic** [comment]
Hello @votdev, thanks for getting back. I tried to follow your steps but had no luck. I also see Vagrant file in the repo, should I use any specific environment or toolchain to build these Debian packages?

And seems like there's no build target:
make: *** No rule to make target 'build'.  Stop.
