### ISSUE TITLE
[Suggestion] [openmediavault-usbbackup] Option to specify command/script after backup

### ISSUE THREAD

**Issue by theTitanhunter** [openmediavault/openmediavault#1230]
I would like to execute a command after the backup is complete. In my example, the external HDD is plugged into a smart outlet. After the backup is complete, it would be great to execute a command/script that "unplugs" the HDD from power.

Maybe there could be another input field after the advanced options where you could specify the command or script you want to get executed after the rsync job is done. I think this would be a great expansion for the plugin and would add the possibility for many use cases.

**Comment by HannesJo0139** [comment]
Hmm the drive already goes to a sleep state automatically what even causes many (at least mine) usb controllers to turn it off completely. Modern power supplies typ. consume <1W when no plugged device is operating. So I wonder if it would bring any actual benefit towards power consumption.

**Comment by Jip-Hop** [comment]
I think pre/post scripts could be useful. For example to take a snapshot (ZFS/BTRFS) of the external disk before or after the backup job.
