### ISSUE TITLE
Add a Dashboard docker widget

### ISSUE THREAD

**Issue by dsm1212** [openmediavault/openmediavault#1237]
I would like to see a widget for showing docker container status in a grid. Probably just the output of

docker ps --format "{{.Names}}, {{.Status}}"

Here is some output from that:

gluetun, Up 58 minutes (healthy)
swag, Up 59 minutes
authelia, Up 59 minutes (healthy)
dropbox, Up 59 minutes
unifi-controller, Up 59 minutes
duckdns, Up 59 minutes
plex, Up 59 minutes (healthy)
pihole, Up 59 minutes (healthy)
unbound, Up 59 minutes (healthy)
portainer, Up 59 minutes

The status is a string that has uptime and if the container has a health check the end of the string will be (healthy) or (unhealthy).

The text of the item in the grid is the Names value and maybe uptime, or just the name.
The grid item should show green if there is no health string or if it contains "(healthy)". Otherwise it should show red.

**Comment by dsm1212** [comment]
Ah, there is a third health status "(health: starting)". I guess that could be yellow.

**Comment by ryecoaaron** [comment]
This would be an omv-extras widget since omv-extras installs docker.  And there already is a widget create - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/usr/share/openmediavault/workbench/dashboard.d/containers.yaml

**Comment by dsm1212** [comment]
Sorry, I don't know how I miss that. Table instead of a grid, but is good enough. THx
