### ISSUE TITLE
No processor information on ODroid HC4 (DietPI)

### ISSUE THREAD

**Issue by KainAlive** [openmediavault/openmediavault#1238]
I'm running OMV on my ODroid HC4 on top of DietPI as operating system (debian based). 
OMV was installed using the install script.

As the title says, OMV doesn't seem to recognize the CPU which (also see screenshot). 
![image](https://user-images.githubusercontent.com/33988011/156936193-aa5b29c2-a4d8-4080-8456-6f21340c2836.png)

**Comment by ryecoaaron** [comment]
That is because the hc4 doesn't really report useful information in /proc/cpuinfo

**Comment by votdev** [comment]
I'm closing this issue because there is nothing to fix. If there is not enough data available, then it can not be displayed.
