### ISSUE TITLE
OMV 6 Performance Statistics not work perfectly

### ISSUE THREAD

**Issue by Hemant2000-karens** [openmediavault/openmediavault#1239]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

The Monitor, or performance statistics not work perfectly, or generate graph after clicking on refresh button present in this area, and after installation of OS, it generate graph, but only until shutdown, once system shutdown after installation of OS, then graph remains constant or you can say, no progress.

**To Reproduce**

No way to re-produce as per my knowledge.

**Expected behaviour**

It should generate graph continuously 

**Screenshots**

<img width="1552" alt="Screenshot 2022-03-07 at 9 53 53 PM" src="https://user-images.githubusercontent.com/58652350/157075793-08c305eb-4e89-44ee-9bc5-66cb106863ab.png">

**openmediavault Server (please complete the following information):**

- OS version: omv 5.6.26-1 (USUL)
- openmediavault version: [dpkg -l | grep openmediavault]

**Client (please complete the following information):**

- Device: any device(Mac/PC/Mobile/Tablet)
- OS: [Cross-Platform]
- Browser [e.g. stock browser, safari, chrome, opera, any]

**Comment by votdev** [comment]
What hardware are you using? If there is no hardware clock available, then the time series datatabase can not work correct because the times are incorrect and cannot be inserted.
Are there any error messages related to rrdcached in the syslog?

**Comment by Hemant2000-karens** [comment]
my server has hardware clock, and it working, but after pressing refresh then it not create graph.

<img width="682" alt="Screenshot 2022-03-08 at 7 40 40 PM" src="https://user-images.githubusercontent.com/58652350/157254479-f91d805a-4a19-409f-a8fe-e51d73a69fef.png">

**Comment by votdev** [comment]
I'm not sure if it makes sense to digg into this issue because OMV5 will be EOL within some weeks. You should better use OMV6 now.

**Comment by Hemant2000-karens** [comment]
OK, then how to upgrade omv6, without reinstalling oS

**Comment by votdev** [comment]
On a x64 installation you can simply run `omv-release-upgrade`. On ARM based SBC i think there is a helper script that will do that for you. @ryecoaaron can you comment on that please?

**Comment by Hemant2000-karens** [comment]
Thanks !! it done

**Comment by Hemant2000-karens** [comment]
<img width="366" alt="Screenshot 2022-03-09 at 1 26 28 AM" src="https://user-images.githubusercontent.com/58652350/157315188-928d6b4e-2c5f-4931-b263-a56f6b9f5574.png">


about system

**Comment by votdev** [comment]
Please provide the output of the following commands:
```
# ls -alh /var/lib/rrdcached/db/localhost/load/
# cat /etc/collectd/collectd.conf.d/load.conf
# cat /proc/loadavg
# systemctl status collectd
# systemctl status rrdcached
# journalctl --no-pager -u rrdcached.service
# journalctl --no-pager -u collectd.service
```
Please post pure text, no screenshots.

**Comment by Hemant2000-karens** [comment]
**ls -alh /var/lib/rrdcached/db/localhost/load/**
total 440K
drwxr-xr-x  2 root root 4.0K Mar  1 22:23 .
drwxr-xr-x 15 root root 4.0K Mar  1 22:39 ..
-rw-r--r--  1 root root 432K Mar  3 09:06 load.rrd

**cat /etc/collectd/collectd.conf.d/load.conf**
LoadPlugin load

**cat /proc/loadavg**
0.37 0.14 0.05 1/194 70268


** systemctl status collectd**
collectd.service - Statistics collection and monitoring daemon
     Loaded: loaded (/lib/systemd/system/collectd.service; disabled; vendor pre>
    Drop-In: /etc/systemd/system/collectd.service.d
             └─openmediavault.conf
     Active: inactive (dead)
       Docs: man:collectd(1)
             man:collectd.conf(5)
             https://collectd.org

**systemctl status rrdcached**

rrdcached.service - LSB: start or stop rrdcached
     Loaded: loaded (/etc/init.d/rrdcached; generated)
     Active: active (running) since Tue 2022-03-08 22:44:58 IST; 10h ago
       Docs: man:systemd-sysv-generator(8)
      Tasks: 7 (limit: 3781)
     Memory: 7.0M
        CPU: 1.873s
     CGroup: /system.slice/rrdcached.service
             └─960 /usr/bin/rrdcached -B -F -f 3600 -w 900 -b /var/lib/rrdcache>

Mar 08 22:44:58 hemantstorage systemd[1]: Starting LSB: start or stop rrdcached>
Mar 08 22:44:58 hemantstorage rrdcached[944]: rrdcached started.
Mar 08 22:44:58 hemantstorage systemd[1]: Started LSB: start or stop rrdcached


**journalctl --no-pager -u rrdcached.service**
-- Journal begins at Tue 2022-03-08 08:32:35 IST, ends at Wed 2022-03-09 09:09:02 IST. --
Mar 08 20:28:45 hemantstorage systemd[1]: Starting LSB: start or stop rrdcached...
Mar 08 20:28:45 hemantstorage rrdcached[20768]: rrdcached started.
Mar 08 20:28:45 hemantstorage systemd[1]: Started LSB: start or stop rrdcached.
Mar 08 20:34:46 hemantstorage systemd[1]: Stopping LSB: start or stop rrdcached...
Mar 08 20:34:46 hemantstorage rrdcached[14060]: rrdcached has been stopped.
Mar 08 20:34:46 hemantstorage systemd[1]: rrdcached.service: Succeeded.
Mar 08 20:34:46 hemantstorage systemd[1]: Stopped LSB: start or stop rrdcached.
-- Boot 22c612c464564bacbf5291a264a083cc --
Mar 08 20:35:36 hemantstorage systemd[1]: Starting LSB: start or stop rrdcached...
Mar 08 20:35:36 hemantstorage rrdcached[921]: rrdcached started.
Mar 08 20:35:36 hemantstorage systemd[1]: Started LSB: start or stop rrdcached.
Mar 08 22:08:05 hemantstorage systemd[1]: Stopping LSB: start or stop rrdcached...
Mar 08 22:08:06 hemantstorage rrdcached[59332]: rrdcached has been stopped.
Mar 08 22:08:06 hemantstorage systemd[1]: rrdcached.service: Succeeded.
Mar 08 22:08:06 hemantstorage systemd[1]: Stopped LSB: start or stop rrdcached.
Mar 08 22:08:06 hemantstorage systemd[1]: rrdcached.service: Consumed 4.225s CPU time.
-- Boot 2e0c3e5798414698a8450f2cb4801d1c --
Mar 09 03:59:51 hemantstorage systemd[1]: Starting LSB: start or stop rrdcached...
Mar 09 03:59:51 hemantstorage rrdcached[1082]: rrdcached started.
Mar 09 03:59:51 hemantstorage systemd[1]: Started LSB: start or stop rrdcached.
Mar 08 22:35:18 hemantstorage systemd[1]: Stopping LSB: start or stop rrdcached...
Mar 08 22:35:19 hemantstorage rrdcached[3545]: rrdcached has been stopped.
Mar 08 22:35:19 hemantstorage systemd[1]: rrdcached.service: Succeeded.
Mar 08 22:35:19 hemantstorage systemd[1]: Stopped LSB: start or stop rrdcached.
-- Boot 61b5d6e26d6a4ecb81599cf4c6a6bcff --
Mar 08 22:37:36 hemantstorage systemd[1]: Starting LSB: start or stop rrdcached...
Mar 08 22:37:36 hemantstorage rrdcached[947]: rrdcached started.
Mar 08 22:37:36 hemantstorage systemd[1]: Started LSB: start or stop rrdcached.
Mar 08 22:41:29 hemantstorage systemd[1]: Stopping LSB: start or stop rrdcached...
Mar 08 22:41:30 hemantstorage rrdcached[2031]: rrdcached has been stopped.
Mar 08 22:41:30 hemantstorage systemd[1]: rrdcached.service: Succeeded.
Mar 08 22:41:30 hemantstorage systemd[1]: Stopped LSB: start or stop rrdcached.
-- Boot 5c8e3a8970ea453385eb0b91eb2a495a --
Mar 08 22:42:18 hemantstorage systemd[1]: Starting LSB: start or stop rrdcached...
Mar 08 22:42:18 hemantstorage rrdcached[944]: rrdcached started.
Mar 08 22:42:18 hemantstorage systemd[1]: Started LSB: start or stop rrdcached.
Mar 08 22:44:10 hemantstorage systemd[1]: Stopping LSB: start or stop rrdcached...
Mar 08 22:44:11 hemantstorage rrdcached[2225]: rrdcached has been stopped.
Mar 08 22:44:11 hemantstorage systemd[1]: rrdcached.service: Succeeded.
Mar 08 22:44:11 hemantstorage systemd[1]: Stopped LSB: start or stop rrdcached.
-- Boot 99bf8a60b7e542c889c8e01104f53605 --
Mar 08 22:44:58 hemantstorage systemd[1]: Starting LSB: start or stop rrdcached...
Mar 08 22:44:58 hemantstorage rrdcached[944]: rrdcached started.
Mar 08 22:44:58 hemantstorage systemd[1]: Started LSB: start or stop rrdcached.

**journalctl --no-pager -u collectd.service**

-- Journal begins at Tue 2022-03-08 08:32:35 IST, ends at Wed 2022-03-09 09:09:02 IST. --
-- No entries --

**Comment by Hemant2000-karens** [comment]
Started producing graphs after starting collectd

**Comment by votdev** [comment]
There must be something in the syslog if the service is dead. Second, `monit` is monitoring this service and will restart it automatically if it fails. This will also report any problems.

Please try to get some information this way:
```
# cat /var/log/syslog | grep collectd
```

**Comment by votdev** [comment]
There is only one reason why collectd is not started and does not send notifications if it is dead; you have disabled `Monitoring`.

Please execute and post the output of this command:
```
# omv-confdbadm read --prettify conf.system.monitoring.perfstats
```

**Comment by Hemant2000-karens** [comment]
{
    "enable": false
}

it is enabled,

and Started producing graphs after starting collectd

`by command sudo systemctl start/enable collectd`

**Comment by votdev** [comment]
> { "enable": false }
> 
> it is enabled,

It is not enabled. This is the problem. Go to `System | Monitoring` and enable it.

**Comment by votdev** [comment]
Closing because it seems to be a user error. The RRD pages will now display an alert box when monitoring is disabled.
