### ISSUE TITLE
[Feature request] Write what we selected in the prompt "are you sure?"

### ISSUE THREAD

**Issue by Ansem93** [openmediavault/openmediavault#124]
HI, I wanted to ask if it would be possibile to write what we selected in the prompt insted of "are you sure you want to delete this item?"
I would like something like
" Are you sure you want to delete ' [NAME OF WHAT I SELECTED]'? "

Most of the time I find myself double or triple check if I selected the right item and still feel anxiety while pressing yes.

**Comment by mi-hol** [comment]
@votdev is this request related to message catalog i.e.openmediavault/deb/openmediavault-usbbackup/usr/share/openmediavault/locale/openmediavault-usbbackup.pot ?


msgid "Delete"msgstr ""
msgid "Delete files on the receiving side that don't exist on sender."msgstr ""

**Comment by votdev** [comment]
> @votdev is this request related to message catalog i.e.openmediavault/deb/openmediavault-usbbackup/usr/share/openmediavault/locale/openmediavault-usbbackup.pot ?
> msgid "Delete"msgstr ""
> 
> msgid "Delete files on the receiving side that don't exist on sender."msgstr ""

No, it is related to the delete dialog message text. The message should display the name or any other property of the selected entry.

I'll check if this is possible in OMV6.

**Comment by votdev** [comment]
Example:
![Bildschirmfoto vom 2021-06-12 23-48-59](https://user-images.githubusercontent.com/1897962/121789755-da410200-cbd8-11eb-94c6-6e6c512684c9.png)
