### ISSUE TITLE
Add Snapshots for BTRFS

### ISSUE THREAD

**Issue by prk0ghy** [openmediavault/openmediavault#1241]
**Is your feature request related to a problem? Please describe.**
I use BTRFS with my openmediavault installation, however it always bothers me, that not many of the features are available via the web ui. As described in the documentation https://openmediavault.readthedocs.io/en/5.x/administration/storage/filesystems.html?highlight=snapshot snapshots are not available.

**Describe the solution you'd like**
I would love to have some way to enable snapshots via webui. It would be great if you can configure snapshots and also access them some way.

**Describe alternatives you've considered**
Snapshots should not replace a good backups but since I want an easy way to roll back changes or get back files this feature would be greatly apprecheated. Configuring from commandline would also be possible but for now I deem it to complicated for comfort.

**Additional context**
Tutorial i found on how to set it up from commandline.
https://linuxhint.com/use-btrfs-snapshots/

**Comment by votdev** [comment]
These features are all planned, but the community seems to have a problem with it: https://github.com/openmediavault/openmediavault/issues/101

**Comment by paulsijben** [comment]
Hopefully to add weight to the ask. 
I am setting up a Pi-based NAS. Tried openmediavault, like it a lot, but the absence of snapshots is an issue for me. So now I am trying Rockstor, which I already like way less, but at least it supports snapshots...

**Comment by PrplHaz4** [comment]
Adding more BTRFS-specific features to OMV would go a long way towards more broad BTRFS adoption.  Some BTRFS features like RAID array management (add, remove, replace, configure) and snapshots are pretty much standard NAS functionality at this point.

IMO, this will also greatly increase the support burden for maintainers, so it would be good to have a plan for enabling the community to take on some of the support aspects.
