### ISSUE TITLE
DashBoard have unexpected behaviour (Safari related)

### ISSUE THREAD

**Issue by Hemant2000-karens** [openmediavault/openmediavault#1242]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**
The dashboard information table behaves unexpected errors, like text and background invisible.
it works fine if less number of components keeps in dashboard, but If I add CPU, or anything else, then memory grid fails to load all it text, and white background.

**To Reproduce**

For current, I just have to avoid to keep some of the dashboard component in the DashBoard .

**Expected behavior**

It should be work fine no matter, how much component are there or not.

**Screenshots**

**openmediavault Server (please complete the following information):**

- OS version: [6.0 (Shaitan)]
- openmediavault version: openmediavault  6.0.16-1

**Client (please complete the following information):**

- Device: [e.g. Mac]
- OS: [e.g. MacOS 12 Monterey(build - 21D62)]
- Version [e.g. 15.3]

**Additional context**

**Comment by votdev** [comment]
What browser are you using? I have never experienced this behaviour. Are there any error messages in the browser dev tools (console)?

**Comment by Hemant2000-karens** [comment]
I am using safari, version 15.3, on chrome it good, but I am safari user.
and only this error is shown in dev tool.

<img width="1112" alt="Screenshot 2022-03-09 at 12 41 21 PM" src="https://user-images.githubusercontent.com/58652350/157390800-97307846-7f7e-4332-aa65-5a2462e50c65.png">

**cat /var/log/syslog | grep collectd**
Mar  8 20:36:41 hemantstorage monit[598]: HttpRequest: error -- client []: HTTP/1.0 400 There is no service named "collectd"
Mar  8 20:36:41 hemantstorage monit[3485]: There is no service named "collectd"
Mar  9 09:12:59 hemantstorage collectd[73303]: plugin_load: plugin "cpu" successfully loaded.
Mar  9 09:12:59 hemantstorage collectd[73303]: plugin_load: plugin "df" successfully loaded.
Mar  9 09:12:59 hemantstorage collectd[73303]: plugin_load: plugin "disk" successfully loaded.
Mar  9 09:12:59 hemantstorage collectd[73303]: plugin_load: plugin "interface" successfully loaded.
Mar  9 09:12:59 hemantstorage collectd[73303]: plugin_load: plugin "load" successfully loaded.
Mar  9 09:12:59 hemantstorage collectd[73303]: plugin_load: plugin "memory" successfully loaded.
Mar  9 09:12:59 hemantstorage collectd[73303]: plugin_load: plugin "rrdcached" successfully loaded.
Mar  9 09:12:59 hemantstorage collectd[73303]: plugin_load: plugin "syslog" successfully loaded.
Mar  9 09:12:59 hemantstorage collectd[73303]: plugin_load: plugin "unixsock" successfully loaded.
Mar  9 09:12:59 hemantstorage collectd[73303]: plugin_load: plugin "uptime" successfully loaded.
Mar  9 09:12:59 hemantstorage collectd[73303]: Systemd detected, trying to signal readiness.
Mar  9 09:12:59 hemantstorage collectd[73303]: Initialization complete, entering read-loop.
Mar  9 10:35:18 hemantstorage collectd[73303]: Exiting normally.
Mar  9 10:35:18 hemantstorage collectd[73303]: collectd: Stopping 5 read threads.
Mar  9 10:35:18 hemantstorage collectd[73303]: collectd: Stopping 5 write threads.
Mar  9 10:36:07 hemantstorage collectd[948]: plugin_load: plugin "cpu" successfully loaded.
Mar  9 10:36:07 hemantstorage collectd[948]: plugin_load: plugin "df" successfully loaded.
Mar  9 10:36:07 hemantstorage collectd[948]: plugin_load: plugin "disk" successfully loaded.
Mar  9 10:36:07 hemantstorage collectd[948]: plugin_load: plugin "interface" successfully loaded.
Mar  9 10:36:07 hemantstorage collectd[948]: plugin_load: plugin "load" successfully loaded.
Mar  9 10:36:07 hemantstorage collectd[948]: plugin_load: plugin "memory" successfully loaded.
Mar  9 10:36:07 hemantstorage collectd[948]: plugin_load: plugin "rrdcached" successfully loaded.
Mar  9 10:36:07 hemantstorage collectd[948]: plugin_load: plugin "syslog" successfully loaded.
Mar  9 10:36:07 hemantstorage collectd[948]: plugin_load: plugin "unixsock" successfully loaded.
Mar  9 10:36:07 hemantstorage collectd[948]: plugin_load: plugin "uptime" successfully loaded.
Mar  9 10:36:07 hemantstorage collectd[948]: Systemd detected, trying to signal readiness.
Mar  9 10:36:07 hemantstorage collectd[948]: Initialization complete, entering read-loop.

**Comment by Hemant2000-karens** [comment]
when I am hovering this code, then it is hovered to memory status, on dashboard
<img width="1112" alt="Screenshot 2022-03-09 at 12 46 37 PM" src="https://user-images.githubusercontent.com/58652350/157391534-9d9e8a29-e93e-47dd-8637-83613cedf40b.png">

**Comment by votdev** [comment]
Hmmm, seems to be a problem specific to Safari. Too bad i do not have an Mac for testing. Will try my best to find a solution.

**Comment by Hemant2000-karens** [comment]
you can get MacBook Air base model at very low cost, or from student discount, verified by unidays, for testing

**Comment by Hemant2000-karens** [comment]
for $999 usd mrp or $899 student discount

**Comment by votdev** [comment]
According to information i've found it seems to me a bug in Safari.

Does [this demo site](https://www.chartjs.org/docs/latest/samples/other-charts/doughnut.html) works for you?

**Comment by Hypfer** [comment]
> you can get MacBook Air base model at very low cost, or from student discount, verified by unidays, for testing

Are you going to buy one and donate it to the omv Dev team then, given that it is this affordable?

**Comment by Hemant2000-karens** [comment]
I can surely provide or donate, but currently I myself a student, who is studying from parents money. But if I will earn, then I am ready to donate OMV, since it makes my dream, or project successful.

**Comment by Hemant2000-karens** [comment]
> Does [this demo site](https://www.chartjs.org/docs/latest/samples/other-charts/doughnut.html) works for you?

yeah, it works fine.

**Comment by Hemant2000-karens** [comment]
After removing some of the component it works, 🤔 , how ??
<img width="1552" alt="Screenshot 2022-03-09 at 3 19 58 PM" src="https://user-images.githubusercontent.com/58652350/157416929-7a365b74-c9b1-4622-b525-a2216da335d9.png">

**Comment by votdev** [comment]
> > Does [this demo site](https://www.chartjs.org/docs/latest/samples/other-charts/doughnut.html) works for you?
> 
> yeah, it works fine.

OK thx. According to https://blog.elantha.com/resizeobserver-loop-limit-exceeded/ it seems to me that the chart.js library could prevent that by improving their code, but this is out of my control.

I'll try to have a look into the OMV code trying to improve the chart component by improve the flex/responsible layout. But a responsible layout requires resizing to immediately adopt the view on page resize; that's what responsible design is used for.

**Comment by Hemant2000-karens** [comment]
Actually, I don't understand that on the particular area of frame it causes problems.
that is top centre, or top right.
<img width="1552" alt="Screenshot 2022-03-08 at 8 43 48 PM" src="https://user-images.githubusercontent.com/58652350/157418906-f1e67d87-5e44-4bb2-91e8-3808d9069644.png">
<img width="1552" alt="Screenshot 2022-03-08 at 8 43 24 PM" src="https://user-images.githubusercontent.com/58652350/157418916-c510cc45-87bf-4c48-8ef1-00584cc364cf.png">

<img width="1552" alt="Screenshot 2022-03-08 at 11 04 35 PM" src="https://user-images.githubusercontent.com/58652350/157418887-daa2cc5c-4276-4c3b-8215-533ffb76ced0.png">

**Comment by votdev** [comment]
I can't help here because i have to sit in front of the browser to do some tests. Without having a Mac this is not possible. I can not reproduce the issue on Linux with Firefox and Chrome.

**Comment by Hemant2000-karens** [comment]
add in the css of the of the parent div or parent element of memory graph, or which is not responding correctly.

` -webkit-transform: translate3d(0, 0, 0);`

**Comment by Hemant2000-karens** [comment]
See, by adding ` -webkit-transform: translate3d(0, 0, 0);` as attribute, it shows data part.
as you can compare it with old image, present above.

<img width="1440" alt="Screenshot 2022-03-09 at 3 48 22 PM" src="https://user-images.githubusercontent.com/58652350/157422092-b2a65bc5-f50d-4178-8d38-5923a9db2a0f.png">

**Comment by Hemant2000-karens** [comment]
@votdev have you accessed to my control panel ??, since I got email, and IP address if of Germany 🇩🇪

**Comment by Hemant2000-karens** [comment]
Tell me @votdev how my server is being controlled from Germany, and it is breach of my privacy and security, now who is responsible, for not able to provide privacy.

Mar  9 16:05:26 hemantstorage sshd[72063]: Connection closed by 77.21.194.85 port 46638
Mar  9 16:06:07 hemantstorage sshd[72067]: banner exchange: Connection from 77.21.194.85 port 46640: could not read protocol version
Mar  9 16:06:07 hemantstorage sshd[72068]: banner exchange: Connection from 77.21.194.85 port 46642: could not read protocol version
Mar  9 16:06:08 hemantstorage sshd[72069]: Unable to negotiate with 77.21.194.85 port 46644: no matching host key type found. Their offer: ssh-dss [preauth]
Mar  9 16:06:09 hemantstorage sshd[72071]: Connection closed by 77.21.194.85 port 46646 [preauth]
Mar  9 16:06:10 hemantstorage sshd[72073]: Connection closed by 77.21.194.85 port 46648 [preauth]
Mar  9 16:06:11 hemantstorage sshd[72075]: Unable to negotiate with 77.21.194.85 port 46650: no matching host key type found. Their offer: ecdsa-sha2-nistp384 [preauth]
Mar  9 16:06:12 hemantstorage sshd[72077]: Unable to negotiate with 77.21.194.85 port 46652: no matching host key type found. Their offer: ecdsa-sha2-nistp521 [preauth]
Mar  9 16:06:13 hemantstorage sshd[72079]: Connection closed by 77.21.194.85 port 46654 [preauth]
Mar  9 16:29:49 hemantstorage openmediavault-webgui[72445]: Authorized login from 77.21.194.85 [username=admin, user-agent=Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0]


IP address location is Germany, so what I can guess

**Comment by votdev** [comment]
> @votdev have you accessed to my control panel ??, since I got email, and IP address if of Germany de

Surely not. Why should i do that?

**Comment by votdev** [comment]
But everyone who can watch your screenshots here can do that.

**Comment by Hemant2000-karens** [comment]
sorry, for that, because I don't know other than you and you are the master, so I think you have master key, I got feared, because anyone can get feared, if without his/her concern, something happens .

By the way, I have changed password, so I think it is safe for now

**Comment by votdev** [comment]
> sorry, for that, because I don't know other than you and you are the master, so I think you have master key, I got feared, because anyone can get feared, if without his/her concern, something happens .
> 
> By the way, I have changed password, so I think it is safe for now

There is ABSOLUTELY NO master key. How did you come up with this idea?

**Comment by ryecoaaron** [comment]
There is no master key.  You shouldn't put your OMV web interface on the internet.

**Comment by Hemant2000-karens** [comment]
> > sorry, for that, because I don't know other than you and you are the master, so I think you have master key, I got feared, because anyone can get feared, if without his/her concern, something happens .
> > By the way, I have changed password, so I think it is safe for now
> 
> There is ABSOLUTELY NO master key. How did you come up with this idea?

Because I create a master key in some of the software, so that if anyone stucks in login, or verification, I can pass them out, if concern is genuine.

**Comment by Hemant2000-karens** [comment]
> There is no master key. You shouldn't put your OMV web interface on the internet.

I know, and I agree, but I have to operate my server from distance, because server is another location, and for education, I am I other city, and I created this, as cloud storage, to store, my projects and class recordings

**Comment by ryecoaaron** [comment]
> Because I create a master key in some of the software, so that if anyone stucks in login, or verification, I can pass them out, if concern is genuine.

This is ridiculous.  Look at the source code.  You will see there is no master key.

> I know, and I agree, but I have to operate my server from distance, because server is another location, and for education, I am I other city, and I created this, as cloud storage, to store, my projects and class recordings

Use VPN.

**Comment by votdev** [comment]
> > > sorry, for that, because I don't know other than you and you are the master, so I think you have master key, I got feared, because anyone can get feared, if without his/her concern, something happens .
> > > By the way, I have changed password, so I think it is safe for now
> > 
> > 
> > There is ABSOLUTELY NO master key. How did you come up with this idea?
> 
> Because I create a master key in some of the software, so that if anyone stucks in login, or verification, I can pass them out, if concern is genuine.

Uaaahhhh, that is really bad bad security design. If I did that, OMV's reputation would be ruined.

**Comment by Hemant2000-karens** [comment]
yes, but no worry I tried to prevent this, if next time happens, I will take new step to avoid this. but currently I have changed password, and @ryecoaaron sorry, I can't use vpn but next time I will take care of mistake done by me 

@votdev and @ryecoaaron thanks to both, for helping me, although you both make fun of me, I don't care for that

**Comment by votdev** [comment]
> although you both make fun of me, I don't care for that

Nobody said that, that's just your own opinion.

**Comment by Hemant2000-karens** [comment]
delete all above, it is looking like WhatsApp chat, 
what is rrdcached ?

**Comment by Hemant2000-karens** [comment]
@ryecoaaron kindly delete personal chat.

**Comment by ryecoaaron** [comment]
> kindly delete personal chat.

I was trying to help your bad situation and defend OMV from your accusations.  This should have been a forum post first.  If it looks like a chat, you made it that way.  I'm not going to delete my posts just because you did to save face.

**Comment by Hemant2000-karens** [comment]
> > kindly delete personal chat.
> 
> I was trying to help your bad situation and defend OMV from your accusations. This should have been a forum post first. If it looks like a chat, you made it that way. I'm not going to delete my posts just because you did to save face.

I have taken my accuse back

**Comment by Hemant2000-karens** [comment]
when I had cleared my misunderstand, and I also didn't wants to save my face, so that from my mistake other can learn

**Comment by Hemant2000-karens** [comment]
Hey @votdev and @ryecoaaron please forgive me, for making allegations on you & omv, you know very well that in which circumstances I alleged you, I thought that you logged in to check & fix bugs, but when you state that you didn't does that, then I panic & alleged you.

I also wants to be good user and supporter of OMV even I expressed my respect and love OMV .

I heartily apologise to you and all your members, and I promise that from next time I will be careful about IP address port password data ,etc or screenshots, but I would like that kindly fix the bugs for which this started.

I have blocked IP of that unwanted person and changed strong password

**Comment by Hemant2000-karens** [comment]
> add in the css of the of the parent div or parent element of memory graph, or which is not responding correctly.
> 
> ` -webkit-transform: translate3d(0, 0, 0);`

See this and try to fix problem.

thank you
