### ISSUE TITLE
OMV5 to OMV6 : The property 'comment' does not exist in the model 'conf.system.filesystem.mountpoint'.

### ISSUE THREAD

**Issue by nlienard** [openmediavault/openmediavault#1243]
I was on Debian 10 / OMV5
I migrated to Debian 11 then to OMV6.

During upgrade, apt got stuck a lot of times and had to modify  /var/lib/dpkg/info/openmediavault-shairport.postrm and   /var/lib/dpkg/info/openmediavault-netatalk.postrm to remove reference to non-existing files.

Then finally i did " omv-confdbadm migrate "conf" "5.0.0"

But when going to the web interface, I got many errors like this one:

```
The property 'comment' does not exist in the model 'conf.system.filesystem.mountpoint'.

OMV\AssertException: The property 'comment' does not exist in the model 'conf.system.filesystem.mountpoint'. in /usr/share/php/openmediavault/config/configobject.inc:71
Stack trace:
#0 /usr/share/php/openmediavault/config/configobject.inc(187): OMV\Config\ConfigObject->assertExists('comment')
#1 /usr/share/php/openmediavault/config/configobject.inc(272): OMV\Config\ConfigObject->set('comment', '', false)
#2 /usr/share/php/openmediavault/config/configobject.inc(234): OMV\Config\ConfigObject->setFlatAssoc(Array, false, false)
#3 /usr/share/php/openmediavault/config/database.inc(182): OMV\Config\ConfigObject->setAssoc(Array, false)
#4 /usr/share/openmediavault/engined/rpc/fstab.inc(208): OMV\Config\Database->getByFilter('conf.system.fil...', Array)
#5 [internal function]: Engined\Rpc\FsTab->getByFsName(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getByFsName', Array, Array)
#8 /usr/share/openmediavault/engined/rpc/raidmgmt.inc(82): OMV\Rpc\Rpc::call('FsTab', 'getByFsName', Array, Array)
#9 [internal function]: Engined\Rpc\RaidMgmt->enumerateDevices(NULL, Array)
#10 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#11 /usr/share/openmediavault/engined/rpc/raidmgmt.inc(123): OMV\Rpc\ServiceAbstract->callMethod('enumerateDevice...', NULL, Array)
#12 [internal function]: Engined\Rpc\RaidMgmt->getList(Array, Array)
#13 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#14 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getList', Array, Array)
#15 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('RaidMgmt', 'getList', Array, Array, 1)
#16 {main}
```

OS:

```
root@NAS:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

Packages:

```
root@NAS:~# dpkg -l|grep openme
ii  openmediavault                  6.0.17-1                             all          openmediavault - The open network attached storage solution
rc  openmediavault-dnsmasq          3.1.5                                all          OpenMediaVault dnsmasq (local DNS and DHCP server) plugin
rc  openmediavault-forkeddaapd      4.0.7-1                              all          OpenMediaVault forked-daapd (DAAP server) plugin
ii  openmediavault-keyring          1.0                                  all          GnuPG archive keys of the OpenMediaVault archive
rc  openmediavault-letsencrypt      3.4.5                                all          Generate free and valid SSL certificates for OMV
rc  openmediavault-minidlna         5.0.5                                all          OpenMediaVault miniDLNA (DLNA server) plugin
rc  openmediavault-netatalk         4.0.7-1                              all          OpenMediaVault netatalk (AppleTalk Protocol Suite) plugin
ii  openmediavault-nut              6.0-8                                all          openmediavault Network UPS Tools (NUT) plugin
rc  openmediavault-omvextrasorg     5.4.5                                all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-shairport        6.0-7                                all          openmediavault shairport (AirPlay/RAOP receiver) plugin
ii  openmediavault-sharerootfs      6.0-3                                all          openmediavault share root filesystem plugin
```

Let me know if you have anay clue.

Thanks

**Comment by votdev** [comment]
- netatalk plugin has not been removed completely. It has been removed in OMV5. So it is not surprising that it now fails. It should hav ebeen removed before the system was migrated from OMV4 -> OMV5.

- openmediavault-dnsmasq and openmediavault-letsencrypt are from OMV3. They had to be removed when BEFORE the migration of OMV3 -> OMV4.

All those plugins can not removed NOW because the assume helper files and scripts that do not exist anymore. Because of that the documentation and release announcements tell to remove them BEFORE the migration.

I suggest to install the system from scratch to fix all those issues.

**Comment by nlienard** [comment]
I don't care about the pluggin, they are now removed (see the reference "rc"), i just want to fix the issue about the comment field of conf.system.filesystem.mountpoint'.

**Comment by nlienard** [comment]
Just run the commande with 6.0

```
root@NAS:/etc/openmediavault# omv-confdbadm migrate "conf" "6.0"
  Running migration conf_6.0.0
INFO: The node 'homesenable' already exists at XPath '/config/services/ftp'.
INFO: The node 'comment' already exists at XPath '/config/system/fstab/mntent'.
INFO: The node 'usagewarnthreshold' already exists at XPath '/config/system/fstab/mntent'.
INFO: The node 'tempdiff' already exists at XPath '/config/services/smart/monitor/device'.
INFO: The node 'tempmax' already exists at XPath '/config/services/smart/monitor/device'.
  Running migration conf_6.0.7
INFO: The node 'homesrecyclebin' already exists at XPath '/config/services/smb'.
root@NAS:/etc/openmediavault#
```

Does it sounds good ?

On web gui, still same error :(

thanks

**Comment by nlienard** [comment]
just did but same issue:

```
root@NAS:/etc/openmediavault# monit restart omv-engined
root@NAS:/etc/openmediavault#
```

error:

```
The property 'comment' does not exist in the model 'conf.system.filesystem.mountpoint'.

OMV\AssertException: The property 'comment' does not exist in the model 'conf.system.filesystem.mountpoint'. in /usr/share/php/openmediavault/config/configobject.inc:71
Stack trace:
#0 /usr/share/php/openmediavault/config/configobject.inc(187): OMV\Config\ConfigObject->assertExists('comment')
#1 /usr/share/php/openmediavault/config/configobject.inc(272): OMV\Config\ConfigObject->set('comment', '', false)
#2 /usr/share/php/openmediavault/config/configobject.inc(234): OMV\Config\ConfigObject->setFlatAssoc(Array, false, false)
#3 /usr/share/php/openmediavault/config/database.inc(182): OMV\Config\ConfigObject->setAssoc(Array, false)
#4 /usr/share/openmediavault/engined/rpc/fstab.inc(208): OMV\Config\Database->getByFilter('conf.system.fil...', Array)
#5 [internal function]: Engined\Rpc\FsTab->getByFsName(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getByFsName', Array, Array)
#8 /usr/share/openmediavault/engined/rpc/raidmgmt.inc(82): OMV\Rpc\Rpc::call('FsTab', 'getByFsName', Array, Array)
#9 [internal function]: Engined\Rpc\RaidMgmt->enumerateDevices(NULL, Array)
#10 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#11 /usr/share/openmediavault/engined/rpc/raidmgmt.inc(123): OMV\Rpc\ServiceAbstract->callMethod('enumerateDevice...', NULL, Array)
#12 [internal function]: Engined\Rpc\RaidMgmt->getList(Array, Array)
#13 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#14 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getList', Array, Array)
#15 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('RaidMgmt', 'getList', Array, Array, 1)
#16 {main}
```

Any way to check the db config ?

**Comment by nlienard** [comment]
After loggin off - loggin on , i don't see the error anymore.

When parsing all the menu, i got this error:

```
The property 'homesrecyclebin' does not exist in the model 'conf.service.smb'.

OMV\AssertException: The property 'homesrecyclebin' does not exist in the model 'conf.service.smb'. in /usr/share/php/openmediavault/config/configobject.inc:71
Stack trace:
#0 /usr/share/php/openmediavault/config/configobject.inc(187): OMV\Config\ConfigObject->assertExists('homesrecyclebin')
#1 /usr/share/php/openmediavault/config/configobject.inc(272): OMV\Config\ConfigObject->set('homesrecyclebin', '0', false)
#2 /usr/share/php/openmediavault/config/configobject.inc(234): OMV\Config\ConfigObject->setFlatAssoc(Array, false, false)
#3 /usr/share/php/openmediavault/config/database.inc(99): OMV\Config\ConfigObject->setAssoc(Array, false)
#4 /usr/share/openmediavault/engined/rpc/smb.inc(59): OMV\Config\Database->get('conf.service.sm...')
#5 [internal function]: Engined\Rpc\Smb->getSettings(NULL, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getSettings', NULL, Array)
#8 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('SMB', 'getSettings', NULL, Array, 1)
#9 {main}
```

**Comment by nlienard** [comment]
i switched to another browser that i never use (chrome instead of ff), clearing cache to be sure,  and still got this error:

```
The property 'comment' does not exist in the model 'conf.system.filesystem.mountpoint'.

OMV\AssertException: The property 'comment' does not exist in the model 'conf.system.filesystem.mountpoint'. in /usr/share/php/openmediavault/config/configobject.inc:71
Stack trace:
#0 /usr/share/php/openmediavault/config/configobject.inc(187): OMV\Config\ConfigObject->assertExists('comment')
#1 /usr/share/php/openmediavault/config/configobject.inc(272): OMV\Config\ConfigObject->set('comment', '', false)
#2 /usr/share/php/openmediavault/config/configobject.inc(234): OMV\Config\ConfigObject->setFlatAssoc(Array, false, false)
#3 /usr/share/php/openmediavault/config/database.inc(182): OMV\Config\ConfigObject->setAssoc(Array, false)
#4 /usr/share/openmediavault/engined/rpc/fstab.inc(208): OMV\Config\Database->getByFilter('conf.system.fil...', Array)
#5 [internal function]: Engined\Rpc\FsTab->getByFsName(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getByFsName', Array, Array)
#8 /usr/share/openmediavault/engined/rpc/raidmgmt.inc(82): OMV\Rpc\Rpc::call('FsTab', 'getByFsName', Array, Array)
#9 [internal function]: Engined\Rpc\RaidMgmt->enumerateDevices(NULL, Array)
#10 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#11 /usr/share/openmediavault/engined/rpc/raidmgmt.inc(123): OMV\Rpc\ServiceAbstract->callMethod('enumerateDevice...', NULL, Array)
#12 [internal function]: Engined\Rpc\RaidMgmt->getList(Array, Array)
#13 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#14 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getList', Array, Array)
#15 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('RaidMgmt', 'getList', Array, Array, 1)
#16 {main}
```

**Comment by votdev** [comment]
It seems your backend does not match the frontend. The mentioned properties have been introduced in OMV6. The UI seems to be up-to-date, but the backend not; even if the omv-engined process has been restarted. I do not have a better idea than reinstalling the package via `apt-get install --reinstall openmediavault`.

**Comment by votdev** [comment]
> [ERROR   ] /lib/python3/dist-packages/salt/modules/network.py does not exist

This does not sound good. This file MUST exists if Salt is installed correctly. Please make sure SaltStack is installed correctly from the OMV package repository.

One note, this seems to be an user/install problem and not a bug. The bugtracker is not meant to discuss such issues, the [forum](https://forum.openmediavault.org/) is a better place to do so; additional a much broader audience will notice your issue and can help to fix it.

**Comment by nlienard** [comment]
the file exists but another path;

```
root@NAS:/etc/openmediavault# find /usr -name network.py
/usr/lib/python3/dist-packages/salt/modules/network.py <=========== HERE
/usr/lib/python3/dist-packages/salt/utils/dockermod/translate/network.py
/usr/lib/python3/dist-packages/salt/utils/network.py
/usr/lib/python3/dist-packages/salt/states/network.py
/usr/lib/python3/dist-packages/salt/runners/network.py
```

**Comment by ryecoaaron** [comment]
Hard to tell without the full upgrade output.  I'm guessing the usrmerge install failed.

**Comment by ryecoaaron** [comment]
If usrmerge failed to install,  the upgrade will continue since it has an or statement.

**Comment by votdev** [comment]
Please post the output of `$ cat /usr/share/openmediavault/datamodels/conf.service.smb.json`.

**Comment by votdev** [comment]
> Still seems like a client side issue. Try ctrl-shift-R.

No, it's a backend issue. It seems there are not all files installed/updated properly.

**Comment by nlienard** [comment]
> > Still seems like a client side issue. Try ctrl-shift-R.
> 
> No, it's a backend issue. It seems there are not all files installed/updated properly.

Same issue after Ctrl+Shift+R

**Comment by votdev** [comment]
> here the output
> 
> ```
> root@NAS:~# cat /usr/share/openmediavault/datamodels/conf.service.smb.json
> {
>         "type": "config",
>         "id": "conf.service.smb",
>         "title": "SMB/CIFS",
>         "queryinfo": {
>                 "xpath": "//services/smb",
>                 "iterable": false
>         },
>         "properties": {
>                 "enable": {
>                         "type": "boolean",
>                         "default": false
>                 },
>                 "workgroup": {
>                         "type": "string",
>                         "default": "WORKGROUP"
>                 },
>                 "serverstring": {
>                         "type": "string",
>                         "default": "%h server"
>                 },
>                 "loglevel": {
>                         "type": "integer",
>                         "enum": [ 0, 1, 2, 3, 10 ],
>                         "default": 0
>                 },
>                 "usesendfile": {
>                         "type": "boolean",
>                         "default": true
>                 },
>                 "aio": {
>                         "type": "boolean",
>                         "default": true
>                 },
>                 "timeserver": {
>                         "type": "boolean",
>                         "default": false
>                 },
>                 "winssupport": {
>                         "type": "boolean",
>                         "default": false
>                 },
>                 "winsserver": {
>                         "type": "string"
>                 },
>                 "homesenable": {
>                         "type": "boolean",
>                         "default": false
>                 },
>                 "homesbrowseable": {
>                         "type": "boolean",
>                         "default": true
>                 },
>                 "homesrecyclebin": {
>                         "type": "boolean",
>                         "default": false
>                 },
>                 "extraoptions": {
>                         "type": "string"
>                 },
>                 "shares": {
>                         "type": "object",
>                         "properties": {
>                                 "share": {
>                                         "type": "array",
>                                         "items": {
>                                                 "type": "object",
>                                                 "properties": {
>                                                         "uuid": {
>                                                                 "type": "string",
>                                                                 "format": "uuidv4"
>                                                         },
>                                                         "enable": {
>                                                                 "type": "boolean",
>                                                                 "default": false
>                                                         },
>                                                         "sharedfolderref": {
>                                                                 "type": "string",
>                                                                 "format": "uuidv4"
>                                                         },
>                                                         "comment": {
>                                                                 "type": "string"
>                                                         },
>                                                         "guest": {
>                                                                 "type": "string",
>                                                                 "enum": [ "no", "allow", "only" ],
>                                                                 "default": "no"
>                                                         },
>                                                         "readonly": {
>                                                                 "type": "boolean",
>                                                                 "default": false
>                                                         },
>                                                         "browseable": {
>                                                                 "type": "boolean",
>                                                                 "default": true
>                                                         },
>                                                         "recyclebin": {
>                                                                 "type": "boolean",
>                                                                 "default": false
>                                                         },
>                                                         "recyclemaxsize": {
>                                                                 "type": "integer",
>                                                                 "minimum": 0,
>                                                                 "default": 0
>                                                         },
>                                                         "recyclemaxage": {
>                                                                 "type": "integer",
>                                                                 "minimum": 0,
>                                                                 "default": 0
>                                                         },
>                                                         "hidedotfiles": {
>                                                                 "type": "boolean",
>                                                                 "default": true
>                                                         },
>                                                         "inheritacls": {
>                                                                 "type": "boolean",
>                                                                 "default": true
>                                                         },
>                                                         "inheritpermissions": {
>                                                                 "type": "boolean",
>                                                                 "default": false
>                                                         },
>                                                         "easupport": {
>                                                                 "type": "boolean",
>                                                                 "default": false
>                                                         },
>                                                         "storedosattributes": {
>                                                                 "type": "boolean",
>                                                                 "default": false
>                                                         },
>                                                         "hostsallow": {
>                                                                 "type": "string"
>                                                         },
>                                                         "hostsdeny": {
>                                                                 "type": "string"
>                                                         },
>                                                         "audit": {
>                                                                 "type": "boolean",
>                                                                 "default": false
>                                                         },
>                                                         "timemachine": {
>                                                                 "type": "boolean",
>                                                                 "default": false
>                                                         },
>                                                         "extraoptions": {
>                                                                 "type": "string"
>                                                         }
>                                                 }
>                                         }
>                                 }
>                         }
>                 }
>         }
> }
> root@NAS:~#
> ```

OK, the datamodel is correct. Please reboot the system, it seems the omv-engined process is not restarted correctly. Maybe there are multiple processes running in parallel due testing.

**Comment by nlienard** [comment]
Finally, it rebooted well 👍 

now the error is different on STORAGE/ FILESYSTEM:

```
Failed to connect to socket: No such file or directory

OMV\Rpc\Exception: Failed to connect to socket: No such file or directory in /usr/share/php/openmediavault/rpc/rpc.inc:141
Stack trace:
#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call()
#1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#2 {main}
```

**Comment by nlienard** [comment]
After unmasking it it looks ok:

```
root@NAS:/var/log# systemctl unmask openmediavault-engined
Removed /etc/systemd/system/openmediavault-engined.service.
root@NAS:/var/log#

root@NAS:/var/log# systemctl status  openmediavault-engined
* openmediavault-engined.service - The OpenMediaVault engine daemon that processes the RPC request
     Loaded: loaded (/lib/systemd/system/openmediavault-engined.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-03-14 16:12:04 CET; 9s ago
    Process: 3900 ExecStart=/usr/sbin/omv-engined (code=exited, status=0/SUCCESS)
   Main PID: 3902 (omv-engined)
     Memory: 10.4M
     CGroup: /system.slice/openmediavault-engined.service
             `-3902 omv-engined

Mar 14 16:12:04 NAS systemd[1]: Starting The OpenMediaVault engine daemon that processes the RPC request...
Mar 14 16:12:04 NAS systemd[1]: Started The OpenMediaVault engine daemon that processes the RPC request.
```
