### ISSUE TITLE
Allow broader set of acceptable file path characters

### ISSUE THREAD

**Issue by jdevl32** [openmediavault/openmediavault#1244]
Reference code:
https://github.com/openmediavault/openmediavault/blob/46e72540ea8402e66419930721bca288b183c3e8/deb/openmediavault/usr/share/php/openmediavault/datamodel/schema.inc#L60

This regex for "dirpath" causes new NFS share requests to fail unexpectedly for names including characters that are normally acceptable in most file systems (such as '$', '+' and '=', among others).  I have used such characters for share path names in prior versions of OMV with success, so it seems that the set of valid characters has recently become more restrictive.  I suggest making the restriction to only _not_ these characters:  \/:*?"<>|

**Comment by votdev** [comment]
I'm really worried about adding new allowed characters because this might break existing setups or might produce unexpected side-effects. A simple workaround is to only use the supported characters.
