### ISSUE TITLE
Allow additional SMB options for home directories

### ISSUE THREAD

**Issue by marekbeckmann** [openmediavault/openmediavault#1245]
**Is your feature request related to a problem? Please describe.**
I want to offer users the ability to use shadow copies, to restore previous versions of a file. I do this, by specifying additional SMB options in the shares settings, however, this is not possible for home directory shares.

**Describe the solution you'd like**
List the home share under SMB shares with all the usual functionality, including the ability to specify additional config options. 

**Describe alternatives you've considered**
Manually editing the `smb.conf` works, however, changes are overwritten regularly (i.e because of updates), making the approach somewhat unreliable. 

**Additional context**
This is the config I want to add: 
```INI
vfs objects = shadow_copy2
shadow: snapdir = .zfs/snapshot
shadow: sort = desc
shadow: format = zfs-auto-snap_%S-%Y-%m-%d-%H%M
shadow:localtime = no
```
**My System**
OS: Debian 10 
OMV Version: 5.6.24-1 (Usul)

I would really appreciate it if this feature was added.

**Comment by ryecoaaron** [comment]
Just put it in the share’s extra options box instead of editing smb.conf.

**Comment by marekbeckmann** [comment]
> Just put it in the share’s extra options box instead of editing smb.conf.

Well that's my problem. There is no shares extra box for the home directories.

**Comment by votdev** [comment]
> Just put it in the share’s extra options box instead of editing smb.conf.

That does not work for the `vfs objects` line. The problem here is that building the smb.conf is very complex because many config options depend on others.

I don't think that this will make it into OMV6 because it needs some refactoring of the SMB config Salt state.

**Comment by donhwy** [comment]
If you put changes you want in /etc/samba/smb.d/home.conf and add include = /etc/samba/smb.d/home.conf to extxra options it will not be over written. You can test it with testparm.

**Comment by donhwy** [comment]
Should be /etc/samba/smb.conf.d/home.conf . Sorry

**Comment by votdev** [comment]
You can also use custom [SaltStack states](https://openmediavault.readthedocs.io/en/5.x/various/advset.html#the-saltstack-states). But this requires a little bit knowledge about Salt.

**Comment by donhwy** [comment]
Maybe you could add breif instructions for this as an advanced tooltip or popup of some kind?

**Comment by votdev** [comment]
Already available in OMV6.
