### ISSUE TITLE
Network info via api

### ISSUE THREAD

**Issue by donhwy** [openmediavault/openmediavault#1247]
**Is your feature request related to a problem? Please describe.**

This came up in the forum. I don't know how many use home assistant but it looks interesting.
[https://forum.openmediavault.org/index.php?thread/42487-omv-6-api/&pageNo=1](url)

**Describe the solution you'd like**

The info is available in the web ui so I hope it is not to much work to make it available in the api

**Describe alternatives you've considered**

The snmp plugin also provides this info. That is what I use.

**Additional context**
Thanks for considering this.

**Comment by votdev** [comment]
> The info is available in the web ui so I hope it is not to much work to make it available in the api

If the data is displayed in the UI, then it is available via RPC API; because the UI is using it to fetch the data.

You should get a little bit more clearer which data you are interested in. Please understand that i do not have the time to read the whole forum post to pick the information. Please describe it here.

**Comment by donhwy** [comment]
I asked the dev to fill in more info for you.

**Comment by tomaae** [comment]
I think there was some misunderstanding.
I was asking if it was possible to get current bandwidth per adapter (RX/TX) from API.
Only way it is available in OMV UI I could find are RRD graphs.
If it was made available tho, it would be useful for automation flows. For example, I use bandwidth data to trigger NAS offsite backups/sync during low usage periods.

**Comment by SamJongenelen** [comment]
So, i'm new to the language, but have found the relevant API code in the OMV repository:
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/network.inc

RPC name: 
>  Network
The object is return as following: 

>  $obj['type'] = $iface->getType();
			$obj['description'] = $iface->getDescription();
			$obj['stats'] = !$stats ? [] : $stats;
			$obj['gateway'] = !$gateway ? "" : $gateway;
			$obj['gateway6'] = !$gateway6 ? "" : $gateway6;
			$obj['address'] = !$address ? "" : $address;
			$obj['address6'] = !$address6 ? "" : $address6;
			$obj['prefix'] = !$prefix ? -1 : $prefix;
			$obj['prefix6'] = !$prefix6 ? -1 : $prefix6;
			$obj['netmask'] = !$netmask ? "" : $netmask;
			$obj['netmask6'] = !$netmask6 ? -1 : $netmask6;
			$obj['ether'] = !$ether ? "" : $ether;
			$obj['mtu'] = $iface->getMTU();
			$obj['state'] = !$state ? gettext("UNKNOWN") : $state;
			$obj['link'] = $iface->getLink();
			$obj['speed'] = !$speed ? -1 : $speed;
