### ISSUE TITLE
Please support boot in UEFI mode

### ISSUE THREAD

**Issue by ky0nch3ng** [openmediavault/openmediavault#125]
Please support boot in UEFI mode

**Comment by ky0ncheng** [comment]
If you use server with amd cpu, debian use old kernel 4.9.x exists boot error, you can use another distro as based OS, suck as [deepin](https://www.distrowatch.com/table.php?distribution=deepin)

**Comment by hauntingEcho** [comment]
last I knew, [Debian 10 intends to support UEFI SecureBoot](https://www.phoronix.com/scan.php?page=news_item&px=Debian-UEFI-SecureBoot-2018).

**Comment by EruIluvatar** [comment]
Erm UEFI is supported already?
My omv 4 is running in UEFI mode since a long time:

```
sudo dmesg | grep -i EFI
[sudo] Passwort für s: 
[    0.000000] efi: EFI v2.40 by American Megatrends
[    0.000000] efi:  ACPI=0x5b682000  ACPI 2.0=0x5b682000  SMBIOS=0xf05b0  MPS=0xfd640 
[    0.000000] ACPI: UEFI 0x000000005B68F3C0 000042 (v01 ALASKA A M I    00000000      00000000)
[    0.000000] clocksource: refined-jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645519600211568 ns
[    0.133366] Registered efivars operations
[    6.449134] EFI Variables Facility v0.08 2004-May-17
[    6.488052] pstore: Registered efi as persistent store backend
s@homeserver:~$ sudo efibootmgr
BootCurrent: 0000
Timeout: 5 seconds
BootOrder: 0000,0002
Boot0000* debian
Boot0002  Hard Drive
```

**Comment by ky0nch3ng** [comment]
@hauntingEcho @EruIluvatar Let us waiting new debian version to solve it.

**Comment by n00ris** [comment]
You may mixed up just UEFI boot support without secure boot (this is possible with Debian 9 / OMV4) and UEFI boot support with SecureBoot. 
Debian 10 is out and does have secure boot support (https://wiki.debian.org/SecureBoot). 
Is it possible to reopen this bug to get at least UEFI boot support without secure boot (for provided install iso and installation itself, for OMV 5 sufficient for me.)

**Comment by n00ris** [comment]
Nevermind, 
found closed https://github.com/openmediavault/openmediavault/issues/363
Need to test.
