### ISSUE TITLE
Dashboard: services (table view) looses "status" on Chromium based browser

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1254]
**Describe the bug**

Dashboard: services (table view) looses "status"

**To Reproduce**

1. login 
2. wait a few seconds
3. for Edge: additionally scroll in services table view

**Expected behavior**

Dashboard: services (table view) shows "status"

**Screenshots**
first , directly after login
![2022-03-23 12_20_21-openmediavault Workbench - Vivaldi](https://user-images.githubusercontent.com/22799428/159688869-d6ea5c25-c5e7-422c-a427-7ef4bd5de52f.png)

then after a few seconds, status disappears
![image](https://user-images.githubusercontent.com/22799428/159688742-16ad9bce-1c48-4226-862d-378105c0c38a.png)

Edge: 
![image](https://user-images.githubusercontent.com/22799428/159689867-60083fa0-8361-4b48-8957-acd8e56b5801.png)

**Reference to Forum**

none

**openmediavault Server (please complete the following information):**

- OS version: Linux 5.10.103-v8+ (RPi CM4 64bit) 
- openmediavault version: 6.0.17-1

**Client (please complete the following information):**

- Device: PC
- OS: Windows 11
- Browser: Vivaldi & Edge 
- Version: 5.1.2567.66 (Stable channel) (64-bit)  & Version 99.0.1150.46 (Official build) (64-bit)

**Additional context**

**Comment by mi-hol** [comment]
just upgraded to openmediavault version: 6.0.18-1 and bug disappeared

**Comment by mi-hol** [comment]
I thought openmediavault version: 6.0.18-1 had fixed this issue but it reappeared now.
![image](https://user-images.githubusercontent.com/22799428/159986900-e102d9ed-17dd-40e9-8f6a-03d5b8c1ce19.png)

**Comment by votdev** [comment]
I'm not able to reproduce the issue with Chrome 99.0.4844.82 and FireFox 98.0.2. I'm wondering because both widgets are using the same RPC endpoint to fetch the data.

**Comment by votdev** [comment]
Maybe a display bug in Edge? But without having a Windows machine i can not test it.

**Comment by mi-hol** [comment]
> Maybe a display bug in Edge?

Its happening consistently with both of my Chromium based browsers, will try to dig a bit deeper with Chromium 
Browser: Vivaldi & Edge
Version: 5.1.2567.66 (Stable channel) (64-bit) & Version 99.0.1150.46 (Official build) (64-bit)

**Comment by mi-hol** [comment]
I was able to reproduce issue on Chrome for Windows Version 100.0.4896.75 (Official Build) (64-bit)
It seems to be related to a screen refresh/redraw event, could therefore be a driver or framework related issue too.

How to reproduce:
- configure dashboard to show "Services (table)" and "System Information"
- initial display of dashboard  with "Services (table)" is correct
- after refresh of dashboard content, "checked icons" on "Services (table)" disappear

**Comment by mi-hol** [comment]
fixed in Version: 6.3.7-1 (Shaitan)
Processor: BCM2835
Kernel: Linux 6.1.19-v8+
