### ISSUE TITLE
Encrypted OMV Installation

### ISSUE THREAD

**Issue by trymeouteh** [openmediavault/openmediavault#1258]
**Is your feature request related to a problem? Please describe.**
Have an option during installation to encrypt OMV installation with LUKS

**Describe the solution you'd like**
Have an option during installation to encrypt OMV installation with LUKS and when enabled, user provides a password/passphrase which is needed every time after boot to decrypt the OS and boot into OMV

**Describe alternatives you've considered**
None

**Additional context**
Many Linux distros allow you to encrypt your installation such as Ubuntu, Manjaro, Linux Mint. This should be an optional feature the user can decrypt their system over ssh or if they have a display and keyboard hooked up to their NAS can type in the password on boot. 

 do not have my NAS running 24/7 and only have it on when I am using the NAS.

**Comment by ryecoaaron** [comment]
You can do this by installing from the Debian installer and running the install script. Most users do not need to encrypt the OS disk.

**Comment by trymeouteh** [comment]
By downloading the debian ISO from debian.org? Where do I get the install script?

**Comment by ryecoaaron** [comment]
Yes. https://github.com/OpenMediaVault-Plugin-Developers/installScript

**Comment by votdev** [comment]
Closing because it can be done via the official Debian ISO image and a [manual installation](https://forum.openmediavault.org/index.php?thread/39490-install-omv6-on-debian-11-bullseye/) of OMV or using the solution suggested above.
