### ISSUE TITLE
Encrypt Disks (Built In, Not A Plugin)

### ISSUE THREAD

**Issue by trymeouteh** [openmediavault/openmediavault#1259]
**Describe the solution you'd like**
A LUKS encryption feature/setting for your disks that is built into OMV and is not an plugin

**Additional context**
Encrypting disks is good for physical security and should be available out of the box. Plugins can be outdated and cause issues when OMV has an update. By having encryption option built into OMV, OMV will have a stable encryption feature for disks.

**Comment by ryecoaaron** [comment]
Not being a plugin just means one person needs to maintain it and has a larger chance of being out of date. The plugin is current up to date for omv 6.x. When have you seen it out of date?
