### ISSUE TITLE
Shared folders showing not referenced but are referenced in rsnapshot

### ISSUE THREAD

**Issue by jbrizz** [openmediavault/openmediavault#126]
OMV 4.1.8.2-1
rsnapshot 4.1.3

I have some Shared folders configured as destination folders in rsnapshot and rsnapshot is working as it should, but in Shared Folders the folders all show No under Referenced.

Unsure if it's an OMV bug or a plugin bug.

**Comment by votdev** [comment]
I assume it's a plugin bug.

**Comment by ryecoaaron** [comment]
The shared folder entries the plugin uses do not have 'sharedfolderref' in the name.  I will have to fix this.  This can be closed here.

**Comment by votdev** [comment]
Please leave a comment to the issue or PR for later reference.

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot/issues/21
