### ISSUE TITLE
Photoprism puts storage files in wrong place

### ISSUE THREAD

**Issue by aldobranti** [openmediavault/openmediavault#1262]
This is OMV 6.0.18 with photoprism freshly installed from repo

Adding the photoprism service leads to a 50Gb pile of storagennnnn files into /var/tmp and blows up my small root disk
I previously set the storage in the UI to a shared dir on a disk where there is that kind of space

Despite podman claim to be CLI compatible with Docker, I cannot understand the systemd unit files
I am happy to try out any podman cli commands to help sort this

I had previously used docker to run photoprism on omv
`docker run --name photoprism --security-opt seccomp=unconfined --security-opt apparmor=unconfined -p 2342:2342 -e PHOTOPRISM_UPLOAD_NSFW=true -e PHOTOPRISM_ADMIN_PASSWORD=redacted -v /srv/dev-disk-by-label-DeskTop1Tb/ImageWillsMac/PhotoPrismStorage:/photoprism/storage -v /srv/dev-disk-by-label-DeskTop1Tb/ImageWillsMac/Pictures:/photoprism/originals photoprism/photoprism pi@pi-vault:~/Docker/Photoprism $ docker run --name photoprism --security-opt seccomp=unconfined --security-opt apparmor=unconfined -p 2342:2342 -e PHOTOPRISM_UPLOAD_NSFW=true -e PHOTOPRISM_ADMIN_PASSWORD=admin -v /srv/dev-disk-by-label-DeskTop1Tb/ImageWillsMac/PhotoPrismStorage:/photoprism/storage -v /srv/dev-disk-by-label-DeskTop1Tb/ImageWillsMac/Pictures:/photoprism/originals photoprism/photoprism`

those storage locations are the one I selected for the photoprism config and there is enough space for the storage files

**Comment by votdev** [comment]
I think this issue is related to podman, but maybe we can find a solution. How are the files named?

> Despite podman claim to be CLI compatible with Docker, I cannot understand the systemd unit files
I am happy to try out any podman cli commands to help sort this

The systemd unit file simply calls podman to start and stop the container. Nothing more.

**Comment by aldobranti** [comment]
I deleted all the /var/tmp/storage* directories that had blown up the free disk
I ran the photoprism omv6 service for a few minutes, here are some of the new storage* directories
`# ls -l /var/tmp/storage*/
/var/tmp/storage252248999/:
total 394000
-rw------- 1 root root       309 Mar 26 10:05 1
-rw------- 1 root root      5781 Mar 26 10:05 2
-rw------- 1 root root  30057008 Mar 26 10:06 3
-rw------- 1 root root       278 Mar 26 10:05 4
-rw------- 1 root root 175266172 Mar 26 10:07 5
-rw------- 1 root root 198097235 Mar 26 10:07 6
-rw------- 1 root root      1092 Mar 26 10:05 7

/var/tmp/storage476639188/:
total 129932
-rw------- 1 root root 30057008 Mar 26 10:09 1
-rw------- 1 root root      309 Mar 26 10:09 2
-rw------- 1 root root     5781 Mar 26 10:09 3
-rw------- 1 root root 49875325 Mar 26 10:09 4
-rw------- 1 root root      278 Mar 26 10:09 5
-rw------- 1 root root 53090641 Mar 26 10:09 6
-rw------- 1 root root     1092 Mar 26 10:09 7
`
running the container under docker does not put anything in /var and there are no similarly named directories in the designated storage area
here are the docker volume mapping I successfully use: 
`-v /srv/dev-disk-by-label-DeskTop1Tb/ImageWillsMac/PhotoPrismStorage:/photoprism/storage \
 -v /srv/dev-disk-by-label-DeskTop1Tb/ImageWillsMac/Pictures:/photoprism/originals`

as far as I can see the volume mapping from the unit file adds a storage directory to my path specified in the UI

`-v /srv/dev-disk-by-uuid-2a4ce0b2-ce0b-4ef3-a5c3-59a50b075668/ImageWillsMac/Pictures/:/photoprism/originals/ \
-v /srv/dev-disk-by-uuid-2a4ce0b2-ce0b-4ef3-a5c359a50b075668/ImageWillsMac/PhotoPrismStorage//storage/:/photoprism/storage/`

viz, see my screen dump of the GUI

![image](https://user-images.githubusercontent.com/9655839/160361633-65c9da83-28af-4d85-a17d-3a66c0a662e3.png)

[hope that works ;)]

**Comment by aldobranti** [comment]
You seem to have fixed this in Photoprism 6.01-3 
One comment : seemed to be a problem in adding proxy directory to the storage share -- had to do this manually before the plugin could be enabled, see screenshot
![image](https://user-images.githubusercontent.com/9655839/161506523-9bb35f17-b536-42f9-a290-27f84bb1d4c2.png)

PS why do omv error boxes disappear so fast ?

**Comment by votdev** [comment]
> You seem to have fixed this in Photoprism 6.01-3 One comment : seemed to be a problem in adding proxy directory to the storage share -- had to do this manually before the plugin could be enabled, see screenshot ![image](https://user-images.githubusercontent.com/9655839/161506523-9bb35f17-b536-42f9-a290-27f84bb1d4c2.png)

The problem has been identified and will be fixed in the next version.

> PS why do omv error boxes disappear so fast ?

You can copy the error message to clipboard in the notification sidebar.
