### ISSUE TITLE
Possible vulnerability report

### ISSUE THREAD

**Issue by enferas** [openmediavault/openmediavault#1266]
Hello,

I would like to report for possible vulnerability but the email security@openmediavault.org is not working.

Could you please let me know how I can do the report ?

**Comment by votdev** [comment]
You'll find emails in the code and the imprint of the homepage.

**Comment by votdev** [comment]
> Hello,
> 
> I would like to report for possible vulnerability but the email [security@openmediavault.org](mailto:security@openmediavault.org) is not working.
> 
> Could you please let me know how I can do the report ?

The security email is now available.
