### ISSUE TITLE
Dead link in Antivirus plugin to the manual page

### ISSUE THREAD

**Issue by daven-que** [openmediavault/openmediavault#1271]
The link in https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-clamav/usr/share/openmediavault/locale/openmediavault-clamav.pot to the manual page is dead.
`msgid "Please check the <a href='https://github.com/vrtadmin/clamav-faq/raw/master/manual/clamdoc.pdf' target='_blank'>manual page</a> for more details."`

The current link to the manual is `'https://docs.clamav.net/'` (manual is now web page and not a pdf).

This dead link is also included in all the openmediavault-clamav.po file in the locale subdirectories, and would need to be updated in each and every one of them as well.

FYI, the source code for the manual web page can be found at https://github.com/Cisco-Talos/clamav-documentation - the vrtadmin account referenced in the dead link appears to have been replaced by Cisco-Talos.

**Comment by votdev** [comment]
The mentioned text is not used in the code anymore, thus i regenerated the POT file. See https://github.com/openmediavault/openmediavault/commit/29317699e7a63ad9dd60e2162f5f557dc6c99222

**Comment by votdev** [comment]
If you refer to OMV5, this release is EOL soon, so only security issues will be fixed.

**Comment by daven-que** [comment]
I did indeed find the dead link in OMV5, then simply searched the latest source code for the string.  Thanks for the fix, even though it was no longer used.  I'm looking forward to OMV6 transitioning from Testing to Stable.
