### ISSUE TITLE
Apply settings faile after editing rsync 'Modules'

### ISSUE THREAD

**Issue by sebeksd** [openmediavault/openmediavault#1272]
**Describe the bug**

After adding 4 modules in rsync Modules tab I tried to apply settings but it fails:

`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color rsyncd 2>&1' with exit code '1': Vault:
----------
          ID: configure_rsyncd_conf
    Function: file.managed
        Name: /etc/rsyncd.conf
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'users'
     Started: 18:05:24.206893
    Duration: 194.728 ms
     Changes:
----------
          ID: remove_rsyncd_secrets
    Function: module.run
      Result: True
     Comment: file.find: []
     Started: 18:05:24.403995
    Duration: 9.479 ms
     Changes:
              ----------
              file.find:
----------
          ID: configure_rsyncd_secrets_Server-backups
    Function: file.managed
        Name: /var/lib/openmediavault/rsyncd-Server-backups.secrets
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'users'
     Started: 18:05:24.413934
    Duration: 26.144 ms
     Changes:
----------
          ID: configure_rsyncd_secrets_CS-Configs
    Function: file.managed
        Name: /var/lib/openmediavault/rsyncd-CS-Configs.secrets
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'users'
     Started: 18:05:24.440560
    Duration: 17.935 ms
     Changes:
----------
          ID: configure_rsyncd_secrets_Server-homes
    Function: file.managed
        Name: /var/lib/openmediavault/rsyncd-Server-homes.secrets
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'users'
     Started: 18:05:24.458886
    Duration: 20.882 ms
     Changes:
----------
          ID: configure_rsyncd_secrets_Server-nextcloud
    Function: file.managed
        Name: /var/lib/openmediavault/rsyncd-Server-nextcloud.secrets
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'users'
     Started: 18:05:24.480139
    Duration: 14.962 ms
     Changes:
----------
          ID: start_rsyncd_service
    Function: service.running
        Name: rsync
      Result: False
     Comment: One or more requisite failed: omv.deploy.rsyncd.default.configure_rsyncd_conf
     Started: 18:05:24.552072
    Duration: 0.019 ms
     Changes:

Summary for Vault
------------
Succeeded: 1 (changed=1)
Failed:    6
------------
Total states run:     7
Total run time: 284.149 ms

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color rsyncd 2>&1' with exit code '1': Vault:
----------
          ID: configure_rsyncd_conf
    Function: file.managed
        Name: /etc/rsyncd.conf
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'users'
     Started: 18:05:24.206893
    Duration: 194.728 ms
     Changes:
----------
          ID: remove_rsyncd_secrets
    Function: module.run
      Result: True
     Comment: file.find: []
     Started: 18:05:24.403995
    Duration: 9.479 ms
     Changes:
              ----------
              file.find:
----------
          ID: configure_rsyncd_secrets_Server-backups
    Function: file.managed
        Name: /var/lib/openmediavault/rsyncd-Server-backups.secrets
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'users'
     Started: 18:05:24.413934
    Duration: 26.144 ms
     Changes:
----------
          ID: configure_rsyncd_secrets_CS-Configs
    Function: file.managed
        Name: /var/lib/openmediavault/rsyncd-CS-Configs.secrets
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'users'
     Started: 18:05:24.440560
    Duration: 17.935 ms
     Changes:
----------
          ID: configure_rsyncd_secrets_Server-homes
    Function: file.managed
        Name: /var/lib/openmediavault/rsyncd-Server-homes.secrets
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'users'
     Started: 18:05:24.458886
    Duration: 20.882 ms
     Changes:
----------
          ID: configure_rsyncd_secrets_Server-nextcloud
    Function: file.managed
        Name: /var/lib/openmediavault/rsyncd-Server-nextcloud.secrets
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'users'
     Started: 18:05:24.480139
    Duration: 14.962 ms
     Changes:
----------
          ID: start_rsyncd_service
    Function: service.running
        Name: rsync
      Result: False
     Comment: One or more requisite failed: omv.deploy.rsyncd.default.configure_rsyncd_conf
     Started: 18:05:24.552072
    Duration: 0.019 ms
     Changes:

Summary for Vault
------------
Succeeded: 1 (changed=1)
Failed:    6
------------
Total states run:     7
Total run time: 284.149 ms in /usr/share/php/openmediavault/system/process.inc:197
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(170): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatus5Y...', '/tmp/bgoutputB3...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(192): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}`

**To Reproduce**

1. Go to rsync Modules
2. Add new module
3. Save
4. Try to apply settings
5. Error

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/18705953/162020677-99a31902-506f-479d-afd1-c6ba5924f14c.png)

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: Linux Vault 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
- openmediavault version: 
ii  openmediavault                       6.0.21-1                         all          openmediavault - The open network attached storage solution
ii  openmediavault-backup                6.0.4                            all          backup plugin for OpenMediaVault.
ii  openmediavault-flashmemory           6.1                              all          folder2ram plugin for openmediavault
ii  openmediavault-keyring               1.0                              all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg          6.0.8                            all          OMV-Extras.org Package Repositories for OpenMediaVault

**Client (please complete the following information):**

- Device: PC
- OS: Windows
- Browser Chrome
- Version 

**Additional context**

This OS was installed yesterday from all newest packages, I was migrating from old x32 OMV5 to x64 OMV6, all configuration was made through WebUI

**Comment by votdev** [comment]
Fixed in `openmediavault 6.0.22`.
