### ISSUE TITLE
Create a Virtual machine option in OMV 6.0.0(shaitan)

### ISSUE THREAD

**Issue by Hemant2000-karens** [openmediavault/openmediavault#1273]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
NO

**Describe alternatives you've considered**
I can use cockpit but in OMV 6, installation of cockpit is not there, and by installation terminal, I have fear, because I am not near by server. I want VM, but web based like in OMV 5 in cockpit it work, so that I can use full resource of my server for my other works.

Currently I am looking for alternative to get linux platform to work, because everything in doing in terminal is not good idea.

**Additional context**
NO

**Comment by ryecoaaron** [comment]
Have you tried the kvm plugin? I removed cockpit because the kvm plugin took its place.

**Comment by Hemant2000-karens** [comment]
How to do, kindly guide me, because I have install qemu-kvm and then it need one more package, which I didn't get libvirt-bin

**Comment by Hemant2000-karens** [comment]
And in fear, that current used port will not work due to conflict then I can't do my current academic work, and also I am not at server place to re-install OS

**Comment by ryecoaaron** [comment]
no command line needed. Just install omv-extras and go to the plugin tab. The openmediavault-kvm plugin is integrated into omv

**Comment by Hemant2000-karens** [comment]
Now, how I can add boot drive, and iso, because here I didn't getting any ISO + add optio
<img width="1203" alt="Screenshot 2022-04-09 at 7 31 22 PM" src="https://user-images.githubusercontent.com/58652350/162577587-70be5c58-63bf-4d92-b071-63ae0075a818.png">
n

**Comment by Hemant2000-karens** [comment]
this message were coming, 
<img width="1189" alt="Screenshot 2022-04-09 at 7 35 28 PM" src="https://user-images.githubusercontent.com/58652350/162578405-e2e513f6-6564-436b-b5f2-75a9ab7cf58e.png">

**Comment by Hemant2000-karens** [comment]
KMV is not working properly, as I cannot delete vm, nor add iSO to boot, fix it

**Comment by Hemant2000-karens** [comment]
@votdev @ryecoaaron add this under bugs label too.

**Comment by ryecoaaron** [comment]
@Hemant2000-karens   This does not belong on the OMV issues.  It belongs https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-kvm/issues.  But most of these questions have been answered on the forum.  Please do not use the issues to learn how to use a plugin or issue commands to people to fix things.

> KMV is not working properly, as I cannot delete vm, nor add iSO to boot, fix it

KVM does work.  The plugin does not currently like spaces in the filename.  I will fix that but just remove the space until then.  If you want an iso to boot from, put one in the pool or create a new pool from a folder with an iso in it.
