### ISSUE TITLE
Saving changes became too annoying lately ...

### ISSUE THREAD

**Issue by momo42** [openmediavault/openmediavault#1275]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

This example is a good one. ^^
I'm always frustrated when I have to save many small changes in OMV6. I wished for a long time that at some point it would get easier to confirm changes in OMV. To my horror, since a recent update even more clicks are needed now.

Example: To save changed privileges of a shared folder you need four clicks now with two seconds long waiting periods in between:

- make the change you need
- click the blue Save button bottom right
- wait some seconds for the yellow bar on top to appear
- click the Check mark (Apply) on top right corner of the screen
- click the 'Confirm' check box center left
- click the red 'Yes' button center right
- wait seconds for the spinning circle to disappear

Please don't be offended @votdev, but this must be a joke. m(
I completely understand that you want to avoid complaints from inexperienced users that accidentally deleted their family photos and so on but making saving changes more and more annoying for all of us is the wrong solution to that. What comes next? Some more checkboxes spread over the whole screen and a count down timer between changes? :-D

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

Even before introducing the new check box it was a pain in the ass to set many changes in a row in OMV. This has to be made easier not harder.
PLEASE rethink you decision or consider making it **opt-out** - for my sake with a large red banner "You have been warned!!!!1!1" or so.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

terrible anger outbursts whenever I have to save changes? ;)

**Comment by votdev** [comment]
As already mentioned in the forum, this design decisions was done based on many years of experience with user posts in the forum that they lost there data because they clicked the `OK` button too fast. With the `Confirm` check a user has some more time to rethink his action. If a user now looses data, it's really not the fault of OMV. I know this requires some more clicks, but is safety not worth it? I also know that i can not make every user happy. One one side there are users that want this additional check, on the others there are users like you that do not like it.
Lets see how it goes and if there are more users complaining about that.

> PLEASE rethink you decision or consider making it opt-out - for my sake with a large red
> banner "You have been warned!!!!1!1" or so.

An opt-out is too complicated and expensive to implement. If the community contributes a solution then i will have a look into it.

**Comment by momo42** [comment]
I understand your reflex for doing that but with all due respect: Too much is too much.
I want to refer to Murphy's law, which says:
[**"If you make something idiot-proof, someone will just make a better idiot."**](https://en.wikipedia.org/wiki/Idiot-proof)
In case of folder privileges the idiot has to set the potentially hazardous changes, after that he has to confirm four times(!) in a row with thinking time in between that he is an idiot and after that something may explode...
In my opinion even asking three times is too much. Asking two times may be ok but just for dangerous stuff and not everywhere. No matter what you do, you won't be able to save everyone from their own stupidity.
My experience with family and friends shows that introducing such repetitive click patterns is not just annoying for **every** user. Idiots are also the fastest learners in terms of mechanically clicking away any warning or confirmation stuff. So in the end you may achieve nothing but frustration on both sides.
I bet there is also scientific evidence for that fact.
Anyway I hope you are not angry with me for bringing this discussion to Github. Didn't find a corresponding forum thread.
Would be nice to have a link here. :)

**Comment by votdev** [comment]
https://forum.openmediavault.org/index.php?thread/42779-disable-confirm

**Comment by ryecoaaron** [comment]
Volker and I probably check this box significantly more than anyone while testing and using OMV.  And yet, I am not filled with any anger about it.  I just check the box and continue on.

**Comment by momo42** [comment]
Anger is the wrong term. I meant that sarcastically, of course.
I just don't think that adding more hurdles is of any use. If 3 confirmations to save changes weren't enough to stop users from trashing their systems, what makes you two believe that 4 is the right number? And if it indeed helps to reduce cases of data loss, why not going with 6 or additionally adding some captchas to have even more fun?
I'm having a really hard time staying serious on this topic.

Anyway just wanted to say thank you both for your great work. I've thought for a while about whether I should really waste your time with this discussion, but I'm strongly convinced that this is a step in the wrong direction - regardless of how many people agree or disagree with me.

**Comment by ryecoaaron** [comment]
To say there are 3 and 4 confirmations is not correct.

When you click save, this write the change to the database and marks the module dirty.
When you click apply, the executes the saltstack deploy.  These were separated because saltstack takes a long time to run on slow systems and allows multiple changes to be executed at the same time (to be faster).  This was not done to add a safety or confirmation step at all.
So, the only confirmation was to make sure you wanted to apply.  Now you have to check a box to confirm your apply.  That makes two confirmations but they are on the same dialog.

Either way, it isn't my decision but I like the extra checkbox for some use cases.  Example:  The delete and delete + storage menu button on the kvm plugin.  The plain delete button does not have the confirmation checkbox because delete the VM really isn't that dangerous because the virtual disks are not deleted.  Delete + storage is dangerous and has the extra confirmation checkbox.  Not only is an extra step to make sure the user wants to delete the storage too but it is visually different to help the user notice the action is more extreme.

**Comment by gregeeh** [comment]
I really dislike all the confirmations you must go through and think the user has to take responsibility for their actions.  It should not be up to the programmer to stop you being an idiot.

@momo42 quote from Murphy is spot on.  So rather then decide if all the confirmations are a good thing or a bad thing why not give the user the option to turn them ON/OFF?  If they turn them OFF throw up a big red flag, flashing lights, whatever you want and a statement you do so at your own risk and the programmer will not be responsible.

Would that not make everyone happy?

**Comment by ryecoaaron** [comment]
If you think it is easy to add that option, submit the PR.

And the safety code to prevent you from formatting a drive that is in use should be removed too? There are LOTS of things in omv code to prevent people from doing bad things. An extra checkbox seems to be destroying the product though. Most software products dont have an option to turn off the guardrails.

**Comment by gregeeh** [comment]
@ryecoaaron  - I never said it's easy as I'm no programmer and because other products do not have the option of turn OFF the guardrails does not mean OVM cannot.

I was thinking of just removing the confirm checkbox to make it the same as OMV5.  Maybe an option under General Settings?  You turn it OFF you get all the warnings in the world and then it's gone, back to OMV5.

As I said before, I'm no programmer so what sounds easy might not be that easy.  At the end of the day it's just my two cents worth.  I did not intend any disrespect and I love the product.

**Comment by ryecoaaron** [comment]
My point is that it is not easy to make it an option. That is a lot of time better spent on other things in my opinion. Most devs don’t like to revert a bunch of code and time because a very small percentage of people don’t like a design change. But as I said, it isn’t up to me anyway.

**Comment by isigold** [comment]
Just speaking from my experience as a user of omv:
Without telling what changes are confirmed, the checkmark only serves as a (minor) annoyance to the user that is mindlessly checked.
at least that is how I used the checkbox after it appeared.

I would like to see a summary of the changes that are applied and that would allow me to review and rethink them.

**Comment by votdev** [comment]
> I would like to see a summary of the changes

this is technical not possible, it does not make sense to display a XML diff to the user.

**Comment by snakyjake1** [comment]
Too many clicks:
1)  Save.
2)  Check mark.
3)  Confirm.
4)  Yes.

**Comment by logopk** [comment]
BTW why are OK and the Confirm Box on the opposite ends of the dialog!?

I'm annoyed that to install updates (what is already a deliberate act to do) I have to click confirm and yes.

After that the dialog does not close by itself. And then I have to apply the confirmation.

Please 🙏🏼 make this easier...

**Comment by Virtlink** [comment]
It is good to ensure the user is aware of the changes that will be applied, and explicitly consents to applying these changes. However, the current implementation is not achieving this.

Most importantly, the dialog does not tell the user anything about the changes that will be applied. Whether you are just changing the Auto logout timeout or deleting your whole family photo album, the dialog (and effort) is the same. And on top of that, the frequency by which the apply dialog comes up makes it an automatic gesture to click Save, click Apply, check Confirm, click Yes. Over and over, the user will not be thinking about the impact any more.

Firstly, the dialog should list the changes being made. Secondly, the dialog should be less invasive (be simpler) when the changes have less impact, such that the extra clicks and confirm checkbox correctly emphasize the severity of an impactful change.

**Comment by ryecoaaron** [comment]
If you are clicking apply every time you make change, you are doing it wrong. you should make and save multiile changes before clicking apply in most situations.

**Comment by logopk** [comment]
> 

Nope, I usually only apply software updates and that requires the above number of clicks. Nothing to reduce!

**Comment by DjoeC** [comment]
Please remove the extra confirm step or at least make it an optional setting.  Save + Apply in warning color yellow should be sufficient.  Stupid behaviour can never be prevented.

**Comment by gitget0** [comment]
+1

It would be nice to have fewer confirmation prompts.

OpenWRT has a similar confirmation flow. The difference is they have 2 buttons on each page: Save / Save & Apply:
When you click 'Save', you never get any prompt whatsoever, it just saves your settings as 'pending'.
When you click 'Save & Apply', you get one confirmation prompt, after which all your saved 'pending' changes are applied.

_"If you make something idiot-proof, someone will just make a better idiot."_

**Comment by donhwy** [comment]
If you want easy use the cli.
apt update
apt dist-upgrade    ### Shows what will be upgraded
press enter            ### Done. Might have to hit apply in the web ui.

**Comment by TheMelmacian** [comment]
> > I would like to see a summary of the changes
> 
> this is technical not possible, it does not make sense to display a XML diff to the user.

I agree that showing diffs of changed xml files doesn't make much sense. But showing a list of user actions in the confirm dialog that triggered the config changes would be a very cool feature:

- mounted file system: <mount point>, <comment>
- created shared folder: <folder path>, admin:rw user:rw others r-, <comment>
- created/changed r-sync task: <active>; <type>; <source path> => <destination path>; <cron expression>
...

**Comment by craigmpeters** [comment]
The same people who do not read prompts are the same people who blindly tick and press confirm

**Comment by HannesJo0139** [comment]
Oh I was not even aware there already is an open issue when I asked for the same. However, changelog of 6.0.35-1 says 'Remove checkbox in the confirmation dialog..'. Cannot find any statement but sounds like votdev changed his mind. Thanks!

https://github.com/openmediavault/openmediavault/issues/1341

**Comment by votdev** [comment]
Improved with https://github.com/openmediavault/openmediavault/commit/98a3170b072840622c3e68bf8cdb0adeafce30e8.
