### ISSUE TITLE
Wrong group list header titles in add user dialoge in omv 5.x

### ISSUE THREAD

**Issue by myomv100** [openmediavault/openmediavault#1278]
Hello everyone,

First of all, I am not sure if this is intended to be like this or not. However, When you switch tab to group, it shows two types of groups. One is "User Accounts" and the other is "System accounts". 

Shall these headers be replaced with "User groups" and "System groups"  ?

![image](https://user-images.githubusercontent.com/53077134/163551476-49524106-9605-476c-9460-5d71fbcb20dc.png)

Steps to reproduce:
1. Go to 'Access Right Management'
2. Click on 'Users'
2. Click on 'Add'
3. Switch tab to group to select a group

OMV Ver:
OMV  5.6.26-1 (Usul)

**Comment by votdev** [comment]
I'll close that issue as `Known issue` because OMV5 is end-of-life in some days. Because of that i will not touch any code, especially ExtJS related Javascript, anymore.
