### ISSUE TITLE
Auto-adjust column width in views and dialogs

### ISSUE THREAD

**Issue by godfuture** [openmediavault/openmediavault#128]
Header rows in tables tend to be too short to read its full content. For this I have to vertically align the column width. Sometimes I can't even adjust the width of the column at all. Negative example is the SMART values table (SMART -> devices -> information > attributes) where not all columns are adjustable.

To solve this once and for all, I thought an automatic adjustment might help to keep the tables readable.

**Comment by votdev** [comment]
Fixed in openmediavault 4.1.9.
