### ISSUE TITLE
OMV 6.x OneDrive Plugin - omv-onedrive-auth missing ?

### ISSUE THREAD

**Issue by ceejayemm** [openmediavault/openmediavault#1280]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**
Installed openmediavault-onedrive 6.0.1 plugin and configured it within OMV. Then, as noted in the header, tried to run omv-onedrive-auth but this could not be found. Searched /usr/sbin, program not there.

omv-onedrive-auth seems to be missing from plugin installation.

**To Reproduce**
As above

**Expected behavior**
Expected to execute omv-onedrive-auth to finish configuration of plugin

**Screenshots**
None

**Reference to Forum**
None

**openmediavault Server (please complete the following information):**
OMV test rig on VirtualBox (6.1.32) Windows host
- OS version: [uname -a] 
- Linux openmediavault6 5.16.0-0.bpo.4-amd64 #1 SMP PREEMPT Debian 5.16.12-1~bpo11+1 (2022-03-08) x86_64 GNU/Linux
- openmediavault version: [dpkg -l | grep openmediavault]
- ii  openmediavault                   6.0.22-1                     all          openmediavault - The open network attached storage solution
ii  openmediavault-flashmemory       6.1                          all          folder2ram plugin for openmediavault
ii  openmediavault-keyring           1.0                          all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg      6.0.8                        all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-onedrive          6.0.1-1                      all          openmediavault OneDrive plugin
ii  openmediavault-owntone           6.0-6                        all          openmediavault OwnTone plugin
ii  openmediavault-photoprism        6.0.1-4                      all          openmediavault PhotoPrism plugin
ii  openmediavault-remotemount       6.0                          all          Remote mount plugin for OpenMediaVault.

**Client (please complete the following information):**

- Device: [e.g. iPhone6] VirtualBox v6.1.32 on Windows Host
- OS: [e.g. iOS8.1] Windows 10 Pro 64bit
- Browser [e.g. stock browser, safari] MS Edge
- Version [e.g. 22]  v100.0.1185.39 (Official build) (64-bit)

**Additional context**

**Comment by votdev** [comment]
Fixed by 66d8c49264bd7b9d55a81f733e3b5d1ae828e47e.
