### ISSUE TITLE
OMV 6.x OneDrive Plugin - store data in a dedicated folder

### ISSUE THREAD

**Issue by molnarti** [openmediavault/openmediavault#1282]
**Is your feature request related to a problem? Please describe.**
Currently the OneDrive plugin used the OMV shared folder directly to store the contents of the files. This creates a quite messed up folder structure unless there is a dedicated OMV shared folder just for OneDrive.

**Describe the solution you'd like**
OneDrive plugin should have an option like "Store files in a subfolder" that would create a new folder within the shared folder like '`user@live.com's OneDrive`' (maybe using @ and ' in a folder name is a bad idea, alternatives are welcome).

**Describe alternatives you've considered**
I have considered creating a dedicated shared folder for OneDrive, but I like to keep the number of shared folders on the necessary minimum so i don't have to map too many network drives in windows.

**Additional context**

**Comment by votdev** [comment]
Simply create a separate sub-shared folder for that.

**Comment by votdev** [comment]
The feature request has been rejected because it does not fit the way how openmediavault handles shared folders.
