### ISSUE TITLE
Importing User Fails

### ISSUE THREAD

**Issue by g-reno** [openmediavault/openmediavault#1285]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

Background:

I have one very old Fedora 17 Linux machine that refuses to negotiate using SMB2 protocol with my RaspberryPi 4 OS Lite. This is the lowest supposedly common SMB protocol between the two. Yesterday I found that Fedora for whatever reason quietly disabled SMB2 in the version of Samba they shipped with that release. RPi 4 OS uses Samba 4.13 which can use SMB2 if configured to use it. But was never able to get these two to talk. Always getting protocol negotiation error. So I gave up on SMB sharing between these two and instead now trying NFS. The issue with NFS is that you must match UID/GID between machines or you get weird behavior. Sometimes files won't move/copy or if they will move/copy but you'll lose timestamps. In order to everything to work properly you have to match UID/GID between the machines.

**Describe the bug**
So today on each machine I created what will be a known system account for use with OMV NFS that will enable matching UID/GID like this:
`pi@raspberrypi-nas:~ $ sudo useradd -r --uid 975 -U omvnfs
pi@raspberrypi-nas:~ $ grep omvnfs /etc/passwd
omvnfs:x:975:975::/home/omvnfs:/bin/bash
pi@raspberrypi-nas:~ $ grep omvnfs /etc/group
omvnfs:x:975:
pi@raspberrypi-nas:~ $ 
`
I go into OMV6 and try to import this user. It acts like it succeeded but no new user appears in the list of users. 
I try a second time and this time get this error:
`500 - Internal Server Error
The user '975' already exists
`
**To Reproduce**

1. Add user on CLI per above.
2. Go into OMV6 and click on Users
3. Click on +
4. Select Import
5. Enter required information for the user being imported
6. Click Import
7. Import fails.

**Expected behavior**

1...6
7. Import succeeds.

**Screenshots**

**Reference to Forum**

URL link to forum post
https://forum.openmediavault.org/index.php?thread/42920-importing-user-fails/

**openmediavault Server (please complete the following information):**

- OS version: [uname -a]
Linux raspberrypi-nas 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

- openmediavault version: [dpkg -l | grep openmediavault]
ii  openmediavault                       6.0.22-1                         all          openmediavault - The open network attached storage solution
ii  openmediavault-flashmemory           6.1                              all          folder2ram plugin for openmediavault
ii  openmediavault-keyring               1.0                              all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg          6.0.8                            all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-resetperms            6.0                              all          Reset Permissions

**Client (please complete the following information):**

Computer

Fedora 17

Firefox
83

**Additional context**

To use NFS with OMV there needs to be a known system user that can added to OMV and all NFS clients in order to have proper NFS file sharing behavior.  Using a system account uid (975) as I did significantly diminishes the possiblity of UID conflicts.  The User account functionality in OMV needs to allow for system accounts above uid 200 to be used.

**Comment by votdev** [comment]
The OMV UI only displays users with IDs between UID_MIN and UID_MAX as defined in `/etc/login.defs`. This is by intention and will not be changed. Use a UID that is between that defined range and you're fine.
