### ISSUE TITLE
Wetty Plugin can't be enabled due to line 50 error

### ISSUE THREAD

**Issue by ken8521** [openmediavault/openmediavault#1286]
- OS version: Linux omv6-test 5.14.0-0.bpo.2-amd64 #1 SMP Debian 5.14.9-2~bpo11+1 (2021-10-10) x86_64 GNU/Linux
- openmediavault version: 6.0.23-1

**Client (please complete the following information):**

- Device: Linux PC
- OS: Ubuntu 22.04
- Browser Chrome
- Version   100.0.4896.127

When trying to enable the plugin, the following error occurs...

500 - Internal Server Error
Invalid RPC response. Please check the syslog for more information.

Relevant syslog entry...

>Apr 24 06:58:07 omv6-test omv-engined[12717]: PHP Fatal error: Uncaught Error: Call to protected method OMV\Config\ConfigObject::assertValue() from context 'Engined\Rpc\OMVRpcServiceWeTTY' in /usr/share/openmediavault/engined/rpc/wetty.inc:50
Apr 24 06:58:07 omv6-test omv-engined[12717]: Stack trace:
Apr 24 06:58:07 omv6-test omv-engined[12717]: #0 [internal function]: Engined\Rpc\OMVRpcServiceWeTTY->set(Array, Array)
Apr 24 06:58:07 omv6-test omv-engined[12717]: #1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
Apr 24 06:58:07 omv6-test omv-engined[12717]: #2 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('set', Array, Array)
Apr 24 06:58:07 omv6-test omv-engined[12717]: #3 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('WeTTY', 'set', Array, Array, 1)
Apr 24 06:58:07 omv6-test omv-engined[12717]: #4 {main}
Apr 24 06:58:07 omv6-test omv-engined[12717]:   thrown in /usr/share/openmediavault/engined/rpc/wetty.inc on line 50
Apr 24 06:58:33 omv6-test postfix/postdrop[12746]: warning: unable to look up public/pickup: No such file or directory
Apr 24 06:58:44 omv6-test omv-engined[12763]: PHP Fatal error: Uncaught Error: Call to protected method OMV\Config\ConfigObject::assertValue() from context 'Engined\Rpc\OMVRpcServiceWeTTY' in /usr/share/openmediavault/engined/rpc/wetty.inc:50
Apr 24 06:58:44 omv6-test omv-engined[12763]: Stack trace:
Apr 24 06:58:44 omv6-test omv-engined[12763]: #0 [internal function]: Engined\Rpc\OMVRpcServiceWeTTY->set(Array, Array)
Apr 24 06:58:44 omv6-test omv-engined[12763]: #1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
Apr 24 06:58:44 omv6-test omv-engined[12763]: #2 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('set', Array, Array)
Apr 24 06:58:44 omv6-test omv-engined[12763]: #3 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('WeTTY', 'set', Array, Array, 1)
Apr 24 06:58:44 omv6-test omv-engined[12763]: #4 {main}
Apr 24 06:58:44 omv6-test omv-engined[12763]:   thrown in /usr/share/openmediavault/engined/rpc/wetty.inc on line 50

**Comment by votdev** [comment]
Update is now available.
