### ISSUE TITLE
OMV6: Keep menu expanded

### ISSUE THREAD

**Issue by snakyjake1** [openmediavault/openmediavault#1287]
**Is your feature request related to a problem? Please describe.**
I do not like the left menu collapsing.

**Describe the solution you'd like**
I want to keep the left menu expanded.
I want a more compact menu.
I prefer to scroll.

**Describe alternatives you've considered**
OMV5

**Comment by ryecoaaron** [comment]
It doesn't collapse if your screen has enough area.
