### ISSUE TITLE
OMV6: Sort plugins by added date

### ISSUE THREAD

**Issue by snakyjake1** [openmediavault/openmediavault#1288]
**Is your feature request related to a problem? Please describe.**
I can't see which plugins are new or added.

**Describe the solution you'd like**
I would like to see/sort plugins by new added date.  Either sorted, or an icon that says "new".
Also would be nice to see the date added.

**Comment by ryecoaaron** [comment]
Added to what?  If you use the file date, the order would be changing all the time with updates.

**Comment by votdev** [comment]
This is technically not possible because the Debian APT package repository does not provide that information.

**Comment by snakyjake1** [comment]
The problem I'm trying to solve is knowing when new plugins are added.

**Comment by votdev** [comment]
> The problem I'm trying to solve is knowing when new plugins are added.

There is no information available in the Debian package repository/database that will help you here. It's technically not possible.

You can see ALL available information in `/var/lib/openmediavault/apt/pluginsindex.json`. They are already displayed in the UI.

**Comment by votdev** [comment]
> The problem I'm trying to solve is knowing when new plugins are added.

Check the blog (+RSS) and Twitter to get the latest information.
