### ISSUE TITLE
OMV6: Plugin clickabel link to homepage, changelog.

### ISSUE THREAD

**Issue by snakyjake1** [openmediavault/openmediavault#1290]
**Is your feature request related to a problem? Please describe.**
The plugins don't have a clickable link for more information about the plugin, including a change log.

**Describe the solution you'd like**
A clickable link to a plugins information page, including a change log.

**Comment by votdev** [comment]
There is no other page containing the information than the changelog within the Debian package. But this can be displayed this way:

![Peek 2022-04-25 19-11](https://user-images.githubusercontent.com/1897962/165139483-8dca4254-0940-400f-bdce-c0fdff44ef44.gif)

**Comment by votdev** [comment]
![Peek 2022-04-25 19-16](https://user-images.githubusercontent.com/1897962/165140415-61e64481-0db3-443d-9b66-49bccd9707bb.gif)

![Peek 2022-04-25 19-17](https://user-images.githubusercontent.com/1897962/165140434-f0d160df-e5fe-407a-ab1b-5112ff5e29e1.gif)

**Comment by ryecoaaron** [comment]
It assumes the home page tells something about the plugin.  I don't think that is the case for most of the plugins.

**Comment by votdev** [comment]
> It assumes the home page tells something about the plugin. I don't think that is the case for most of the plugins.

Yes, but it doesn't. Maybe it applies to packages from the Debian repository. Can't check it right now because my system is up-to-date.

**Comment by ryecoaaron** [comment]
Ah, I thought you only added it to the Plugin tab.  If it is on the Updates tab, it might be useful for non-plugins.
