### ISSUE TITLE
Too many frivolous notifications

### ISSUE THREAD

**Issue by snakyjake1** [openmediavault/openmediavault#1295]
**Is your feature request related to a problem? Please describe.**
Too many frivolous notifications.

I already have to make the change then:

1. Save
2. Apply
3. Confirm
4. Click Yes.

Then I get a notification alerts:
![image](https://user-images.githubusercontent.com/8312560/165434285-986e579a-6c92-4ea0-9307-fa752a7a7281.png)

**Describe the solution you'd like**
I don't need notification alerts to tell me what I just did, especially since I had to do do four actions to really tell OMV to do it.

**Describe alternatives you've considered**
Or let the user decide what type of notification alerts to receive/ignore.

**Additional context**
Too many alerts will just make people ignore them.
OMV6

**Comment by votdev** [comment]
The notifications are helpful to understand what has happened and can be used to check which actions has been done during the active session.
