### ISSUE TITLE
[Suggestion] Nativ WebDav-Support

### ISSUE THREAD

**Issue by Chiller2019** [openmediavault/openmediavault#1298]
**Describe the solution you'd like**
I wish a native support for WebDav without a docker-instance with login credentials synchronize with the user in OMV like TrueNAS.

**Describe alternatives you've considered**
Actually alternative is to create a docker-instance with webdav, with new user's etc. - Thats really annoying because there a two systems for one feature/problem.

Kind regards
Julian

**Comment by ryecoaaron** [comment]
I did a quick port of the old webdav plugin to OMV 6.x and switched from sabre to native nginx module.  It still needs some work but it is a start.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-webdav

**Comment by Chiller2019** [comment]
> I did a quick port of the old webdav plugin to OMV 6.x and switched from sabre to native nginx module. It still needs some work but it is a start. https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-webdav

Thx very much for your work! Maybe one day it will be implemented in omv-extras :)

But, how can I install this Plugin in OMV6? - Any Guides? Cant find in forum about installation from Plugins in OMV6.


Kind regards

**Comment by ryecoaaron** [comment]
It is an omv-extras plugin.  And you can't install it until I finish it.  I need to figure out how to test webdav stuff better.
