### ISSUE TITLE
Not Read/Write old files in HDD, while in same location

### ISSUE THREAD

**Issue by Hemant2000-karens** [openmediavault/openmediavault#1311]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

Hello, recently I have re-installed OMV-6 (shaitan), due to some errors caused by applications, so after re-installation, I have mounted the disk, and it is mount to the previous location, and I have made shared folder with same name, in the location, and it contained some files, which is there before re-installation, and I can access by root, but as user I can't. So kindly, help.

**To Reproduce**

**Expected behavior**

As I re-installed, it is okay that it will not show, files, but when I created file-system, and shared folder, at same hdd, same location/path, then either it should give error, or let me access to my old files, as I used to earlier (before reinstalling the OS).

**Screenshots**

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: 6.0.27-1 (Shaitan)
- openmediavault version: [dpkg -l | grep openmediavault]

**Client (please complete the following information):**

**Additional context**

**Comment by votdev** [comment]
I assume the UIDs of the users have been changed after the new installation. Go to the shared folder page, select a share and press the ACL button. Adapt the privileges recursively and you should be able to access the files with the specific user again.

**Comment by Hemant2000-karens** [comment]
No, it not worked, could you test it, in other drive. After doing, even I restarted the system completely.

<img width="654" alt="Screenshot 2022-05-25 at 8 30 40 PM" src="https://user-images.githubusercontent.com/58652350/170295019-cf9a0a09-f55e-4b83-b28d-cc0e2bfa64eb.png">
<img width="1080" alt="Screenshot 2022-05-25 at 8 30 29 PM" src="https://user-images.githubusercontent.com/58652350/170295036-7f6889d1-ac61-4f2e-8e5e-1ff2d3a4a253.png">

On root Access, you will get all the content.
<img width="582" alt="Screenshot 2022-05-25 at 8 37 10 PM" src="https://user-images.githubusercontent.com/58652350/170295465-7eed837b-b473-450e-8fac-6f624e034098.png">

**Comment by Hemant2000-karens** [comment]
have you tried it ?

**Comment by mi-hol** [comment]
@votdev should I flag importance of "UIDs of the users have to be the same as in previous installation" 
in guide "[(Re)Installation of OpenMediaVault 1.0.X](https://forum.openmediavault.org/index.php?thread/5620-re-installation-of-openmediavault/)" and update it to reflect V6?

**Comment by Hemant2000-karens** [comment]
Yeah !! @votdev and @ryecoaaron thanks, for guide, I changed UUID with fresh installation, and I can access all my old files, without issue, but would like to request, kindly do something which holds UUID same in n numbers of re-installation, if the hardware (HDD/SSD) is same, as previous.
