### ISSUE TITLE
Extremely low write speed after upgrading to 6.x

### ISSUE THREAD

**Issue by phmg701** [openmediavault/openmediavault#1314]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

Extremely low write speed after upgrading to version 6.
Writing starts as expected then speed suddenly drops in a cycle.

**To Reproduce**

Copy a file of more than 100MiB

**Expected behavior**

Same speed as version 5, no speed drops

**Screenshots**

See forum post below.

**Reference to Forum**

https://forum.openmediavault.org/index.php?thread/43139-very-low-speed-on-smb-after-upgrading-from-5-x-to-6-x/

**openmediavault Server (please complete the following information):**

- OS version: Linux NAS04 5.16.0-0.bpo.4-amd64 #1 SMP PREEMPT Debian 5.16.12-1~bpo11+1 (2022-03-08) x86_64 GNU/Linux

- openmediavault 6.0.27-1 

**Client (please complete the following information):**

- Device: PC over SMB and SFTP (WinSCP)
- OS: Windows 11
- Browser: Mozilla Firefox / Google Chrome
- Version: latest as of today

**Additional context**

Read speed is same as with version 5 and I never experienced anything similar before upgrading do version 6

Thanks!!!

**Comment by votdev** [comment]
I'm not sure how to help here. OMV6 does not have huge changes in the SMB configuration, so i assume this is not the problem. Changing from Debian 10 to 11 means the SMB server has been updated and the kernel as well. So there are many reasons that may cause this problem. Talking about SMB server and kernel means that this is out of the scope of the OMV project, which builds and uses Debian but does not maintain these packages. If there is a problem, the OMV project can not do anything. Sorry.

**Comment by votdev** [comment]
Based on your forum comments the problem seems to be below the SMB/SFTP servers. Network driver issues, caches, MDADM. This [issue](https://forum.openmediavault.org/index.php?thread/43360-bad-read-speed-on-rasppi-but-good-write/&postID=314270#post314270) is maybe not related to you, but an idea to start searching for the reason.

**Comment by phmg701** [comment]
Thanks for the quick reply!
Could that be related to the system approaching full capacity limit on the RAID5 Array? Less than 90GiB left of the 8TiB filesystem. Perhaps it's something related with thin/thick provisioning of EXT4 (lazy initialization)?

**Comment by phmg701** [comment]
Debian / OMV updates as of today seem to fix any issue.
