### ISSUE TITLE
OMV6: Bring back the WebUI from v5.x

### ISSUE THREAD

**Issue by gitget0** [openmediavault/openmediavault#1315]
The new UI is a bit confusing, and there's a lot more clicking and a lot more scrolling to perform the same operations as before.

Personally, I don't think that an exaggeratedly large interface (current OMV 6) is suited to something as complex as OMV.

For example:
* vertical lists (i.e. permissions) require much more scrolling, for no added information
* pop-up menus are no longer used - they provided useful context (the parent page behind) and also required only 1 click to save/close & return to the parent page
* tabs are no longer used either - they also provided visual context and a better structure, and less clicking around
* the navigation panel does not allow multiple categories to be expanded simultaneously - so you have to keep clicking around until you find the menu item you need, and then start all over again next time

The previous interface was much easier to understand and navigate.
If anyone can help with restoring the previous OMV 5.x WebUI, I will make a dark version using Stylebot and post the CSS here.

Thanks.

**Comment by votdev** [comment]
Thank you for your response, but it is not possible to switch to the UI framework of OMV5 because this is dead since years and did not get security updates anymore.

A new framework means new look, behaviour and workflows. The new UI is based on Google Material which also supports mobile devices and other touch devices. Because of that user experience is a little bit different to a desktop only UI.

**Comment by gitget0** [comment]
Thanks for your reply - and sorry, I should have started my previous message by thanking you for all the work and appreciating how awesome OMV is. I love it.

The new interface certainly looks and feels more modern, and I take your point about mobile compatibility - it is nice to have, although I would suspect that most people who use OMV do so from their desktops primarily.

At the moment, the new interface seems to be a security/backend improvement, and a slight step down in the user experience on the frontend (which takes away from how awesome OMV is). I would offer to provide some more detail as to why I think this, but the majority of what I would suggest for improving the user experience was already implemented in OMV5, so you're probably well aware of it already.

Sorry if this seems like a stupid question, but do you have any pointers on how I could go about setting up a development environment to try to see if there's anything productive that I could help with?

**Comment by votdev** [comment]
> At the moment, the new interface seems to be a security/backend improvement, and a slight step down in the user experience on the frontend (which takes away from how awesome OMV is). I would offer to provide some more detail as to why I think this, but the majority of what I would suggest for improving the user experience was already implemented in OMV5, so you're probably well aware of it already.

The UI is using all features and concepts of the Angular Material framework. I don't think it makes sense to implement workflows that do not fit into the Material concept and the underlying framework. The framework was chosen to support desktop and touch devices and to simplify the implementation by following the concepts of the framework.

You can surely bring up your ideas, but don't expect to much response.

You can setup a Vagrant based virtual machine using [this](https://github.com/openmediavault/openmediavault/tree/master/vagrant), and the UI can be found [here](https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/workbench). If you are familar with npm it shouldn't be a problem to get it started.
