### ISSUE TITLE
UI/UX suggestions

### ISSUE THREAD

**Issue by Hukuma1** [openmediavault/openmediavault#1316]
Just a couple of things that are evident in the now stable release of v6:

Just updated to Dark Theme (cheers for this!) and noticed some color issues. Can't confirm if the contrast fails on light theme, not sure how to flip back to test.

1. Contrast is failing on certain elements. This is important for accessibility. [I'm using a free Chrome extension](https://chrome.google.com/webstore/detail/wcag-color-contrast-check/plnahcmalebffmaghcpcmpaciebdhgdf?hl=en) to showcase it. I didn't check all the menu items, just the dashboard.

<img width="859" alt="contrastfail" src="https://user-images.githubusercontent.com/54511555/171218949-f834a793-ee7d-4ece-85d1-1ed879433049.png">

2. When I originally upgraded to v6 I thought this graphic was a joke placeholder. But it's still here. ;) The old-school pixel art stopwatch really doesn't fit into the theme.
![stopwatch](https://user-images.githubusercontent.com/54511555/171220756-34aa9d5e-0842-4672-b57d-aba3a3032866.png)

3. I noticed for most updates we now get an "END OF LINE" or something equivalent letting the user know the updates were fine and we can close the dialogue. And sometimes it doesn't. Like this screen when I was updating to latest version. It just sat there for a few minutes until I realized I should probably close it and check if it updated fine (it did).
<img width="663" alt="updatenotification" src="https://user-images.githubusercontent.com/54511555/171222417-d049184f-c035-4314-8b43-3a5e7f66d34b.png">

4. Speaking of notifications. I think we should make them with better practices. [Looking over examples from this UX site](https://uxdesign.cc/are-you-sure-you-want-to-do-this-microcopy-for-confirmation-dialogues-1d94a0f73ac6), we can improve the update dialog box as a start?
<img width="458" alt="updatedialog" src="https://user-images.githubusercontent.com/54511555/171223948-967b4665-9e14-4723-bd65-4917a2bc7ac8.png">

Instead of title being `Confirmation`, make it something like `Update?` Instead of `Yes` make it say `Update`. Do we want it to be a warning dialog? And regarding the confirm checkbox on the opposite side of the dialog. This type of action is generally reserved for the ultimate permanent action stuff. Is this how we feel about updates, very dangerous? And if it was just to prevent people from fat fingering accidentally the 'Yes' button before, how about we remove the checkbox, and just have the default button selected be `No`?

Shutdown system dialog same thing. Although there I would tend to agree it should be a warning, and button in red.

**Comment by votdev** [comment]
1. Any suggestion how to improve it?
2. Seems you're not old enough to identify where this icon comes from. There are several things in the UI and UI code that honours the Commodore Amiga computer. So the icon and all other things will stay.
3. If the EOL message does appear, then something went wrong and the background task has not been finished.
4. You're right, but this will require to update many code places which i want to prevent by simply using a generic dialog. Feel free to submit a PR that changes all relevant code. Please note that changing the dialog title everywhere will require to translate them as well. Second, finding a good title is really difficult.

**Comment by votdev** [comment]
Color contrast has been fixed with fc2085804d72644af5387cc80c4a0058793a04df. Note, the `Success` notification toast still uses green/white colors because it can not be customized due the fact that the icon is a background SVG image whose color can not be modified via CSS. IMO the contrast and readability is OK in that case.

**Comment by Hukuma1** [comment]
1. My first thoughts were to first of all make dark theme darker. Then to improve readability add a small border to the progress bar text (`background-color: #00000099`).
 
-Text color from `#FFFFFF` to ghost white `#f8f8ff`
-Background color from `#303030` to `#191919`
-Table color from `#424242` to `#272727`
-Table progress bar fill background from `#0000001a` to `#00000075`
-S.M.A.R.T/Services button text color from `#FFFFFF` to `#272727`

![darker1](https://user-images.githubusercontent.com/54511555/171282753-1a8b9ee8-8332-4208-ba88-3ea1e8ade176.png)

![darker2](https://user-images.githubusercontent.com/54511555/171282760-612a0a90-f64f-49d8-baa7-71d503e42d3b.png)

2. Guess not. I didn't realize it was some easter egg/homage to a past system. Just giving input as an end user of the current system and stating it doesn't fit with Angular's Material UI design principals. Cool to know the backstory for the motivation now though!

3. Wonder if the EOL not showing up has something to do with me updating it while accessing the site via reverse proxy? Maybe? Not a deal breaker.

4. Ah, that would be a headache indeed. Especially having to translate all of them individually. :/

**Comment by votdev** [comment]
> 1. My first thoughts were to make dark theme darker. Then to improve readability add a small border to the progress bar text (`background-color: #00000099`).
> 
> 
> -Text color from `#FFFFFF` to ghost white `#f8f8ff` -Background color from `#303030` to `#191919` -Table color from `#424242` to `#272727` -Table progress bar fill background from `#0000001a` to `#00000075` -S.M.A.R.T/Services button text color from `#FFFFFF` to `#272727` -Hover blue effect from `#5dacdf` to `#195780`

The colors of the dark theme are predefined by Angular Material framework. I think they have chosen the colors by intention.

**Comment by votdev** [comment]
I'll close the issue as resolved because i do not want to override colors that are defined by Angular Material. I think they know what they are doing. Second, i will not customize the Material theme too much to reduce maintenance and migration burden.
