### ISSUE TITLE
OMV6 as Access Point

### ISSUE THREAD

**Issue by piter-pit** [openmediavault/openmediavault#1317]
**Is your feature request related to a problem? Please describe.**

OMV uses systemd-networkd and removes dhcpcd during installation - any tutorial to set up AP (hostapd - [link](https://www.raspberrypi.com/documentation/computers/configuration.html#setting-up-a-bridged-wireless-access-point) ) does not work without dhcpcd.
Reinstallation of dhcpd5 with "sudo apt install dhcpcd5" does not bring the solution
RaspAP also does not work also.
I was not able to manage systemd-networkd to handle without dhcpcd.

Option to install OMV with bypassing the networks configuration allows for proper operation as AP but it requires full system reinstallation.

**Describe the solution you'd like**
would be nice to have clear tutorial how to activate AP (bridged and NATed) on working OMV or how to revert network configuration to avoid system reinstallation

**Describe alternatives you've considered**

**Additional context**
link to [OMV forum](https://forum.openmediavault.org/index.php?thread/43315-omv6-as-access-point/&postID=313630#post313630)

**Comment by votdev** [comment]
I think the [documentation](https://github.com/openmediavault/openmediavault-docs) repository is the right place for this.

If it is possible to get this working, fine. But OMV is primarily designed as NAS appliance, so the main focus is to get the network running to fulfil this requirement.

**Comment by votdev** [comment]
Superseded by https://github.com/openmediavault/openmediavault-docs/issues/102.
