### ISSUE TITLE
Separate "Hibernation" and "Standby" into two separate actions

### ISSUE THREAD

**Issue by glics** [openmediavault/openmediavault#1319]
**Is your feature request related to a problem? Please describe.**
Right now, when the Standby button is clicked through the Workbench, OpenMediaVault prefers to put the system into hibernation, if possible:

https://github.com/openmediavault/openmediavault/blob/94812efe10f3bd694afda295016d8a22a493feff/deb/openmediavault/usr/share/php/openmediavault/system/powermanagement.inc#L124-L133

**Describe the solution you'd like**
Have two separate menu buttons for hibernation and standby/sleep

**Describe alternatives you've considered**
It should be at least possible to have a configuration option for this behavior, i.e. in OMV's Power Management settings menu; I understand that this would introduce complexity into the `standby()` function in the snippet above, so it might not be the preferred solution. Still I think it's worth to poll the community if there's interest in such a feature.

**Additional context**
For some people, Wake-on-LAN might be supported in S3 Sleep but not in S4 Hibernation, so they might be having an undesired behavior right now. 
As for myself, I had a problem with the size of the swap partition created by the installer so S4 Hibernation would just put the machine into an unusable state until a forced reboot. That is out of scope for this issue though.

Hope to see some interest, if there are any questions or clarifications needed I'll be happy to help if I can :smile:

**Comment by glics** [comment]
As a little addendum, the `isStateSupported` function should probably honor the systemd configuration set in `/etc/systemd/sleep.conf` or `/etc/systemd/sleep.conf.d/`;
There are other paths that systemd checks, they are documented in the man page for [systemd-sleep.conf(5)](https://manpages.debian.org/testing/systemd/systemd-sleep.conf.5.en.html).
Sleep, hybrid sleep, hybernation etc. can be disabled from these configurations, while remaining supported by the hardware - therefore still present in `/sys/power/state`.

Also, here is a workaround, in case anyone stumbles upon this issue:
It is possible via this config file to override the behavior of `systemctl hibernate` by adding `HibernateMode=mem` under the `[Sleep]` section; this will echo `mem` to `/sys/power/state` in place of its usual value, `disk`, effectively replacing hibernation with sleep. 
Please be sure to do your homework before editing any config file:
[systemd-sleep.conf(5)](https://manpages.debian.org/bullseye/systemd/systemd-sleep.conf.5.en.html), [systemd-hibernate.service(8) aka systemd-suspend.service(8)](https://manpages.debian.org/bullseye/systemd/systemd-hibernate.service.8.en.html)

**Comment by auanasgheps** [comment]
I totally endorse this issue.
I actually had to open [this thread](https://forum.openmediavault.org/index.php?thread/43562-clarifications-about-omv6-power-management-and-new-environment-variables/) to figure out there's a variable to override it, but it isn't straightforward.
Additionally, looks like this variable is ignored when configuring a Power Management scheduled task, see #1330
