### ISSUE TITLE
Blog section on website loads the three latest enries repeatedly

### ISSUE THREAD

**Issue by frainz-de** [openmediavault/openmediavault#1322]
**Describe the bug**

On the [blog section](https://www.openmediavault.org/blog.html) of the Openmediavault website, scrolling down should load older entries. Instead, the most recent three entries are shown repeatedly

**To Reproduce**

1. Go to https://www.openmediavault.org/blog.html
2. Scroll down to the site
4. Notice that the content repeats itself

**Expected behavior**

Scrolling down reveals older entries.

**Client (please complete the following information):**

- Device: Thinkpad T495
- OS: somewhat current Manjaro
- Browser Firefox 100.0.2

**Comment by votdev** [comment]
See https://github.com/openmediavault/openmediavault/issues/1323
