### ISSUE TITLE
infinite scrolling on https://www.openmediavault.org/blog.html not working correctly

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1323]
infinite scrolling on https://www.openmediavault.org/blog.html not working correctly.
Using Chromium based Vivaldi browser it is impossible to get blog posts before 31. May 2022 

**To Reproduce**

1. Go to 'https://www.openmediavault.org/blog.html '
2. press key "page down" several time
3. See error that no older news shows

**Expected behavior**

Scrolling to all news should be possible

**Screenshots**

![image](https://user-images.githubusercontent.com/22799428/173201912-759e38bf-c4c9-4ac6-8de5-e0c434e3b597.png)

**Client (please complete the following information):**

- Device: Laptop
- OS: Windows 11
- Browser Vivaldi
<html>
<body>

Vivaldi | 5.3.2679.38 (Stable channel) (Pending update 5.3.2679.51) (64-bit)
-- | --
Revision | cbd5b1203ac1b0b8da3d45904041afec3a888194
OS | Windows 11 Version 21H2 (Build 22000.708)
JavaScript | V8 10.2.154.4
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.72 Safari/537.36

</body>
</html>

**Comment by votdev** [comment]
Feature has been disabled. Seems to be a bug in the theme.

**Comment by mi-hol** [comment]
Did you test the change?
When I just tried to go to page 2 I got a "page not found" error
URL: https://www.openmediavault.org/blog.html/?paged=2

**Comment by votdev** [comment]
No, i simple unchecked the previously checked button, nothing more. Seems there is a serious bug in the theme or WP.

**Comment by votdev** [comment]
Finally fixed. Infinite scroll would also work now, but i find it better to see how much pages exist.
