### ISSUE TITLE
yaml highlighting text area component

### ISSUE THREAD

**Issue by ryecoaaron** [openmediavault/openmediavault#1326]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a yaml-highlighting text area for plugins to use.

**Describe the solution you'd like**
A text area component that could be added to a form or datatable page that would highlight yaml code for editing.

**Describe alternatives you've considered**
Using normal text area now.

**Comment by votdev** [comment]
After some research these are the problems:
- The Monaco editor is not supported in mobile browsers or mobile web frameworks. 
- A <textarea> form field does not support customization of the displayed content.

This means if we want to support syntax highlighting as an editor (and not only to display it) it is necessary to implement a new Angular form control which is using [HighlightJS](https://highlightjs.org/) or [PrismJS](https://prismjs.com/) (the later is my favorite).

**Comment by votdev** [comment]
Good examples for PrismJS:
- https://techincent.com/code-syntax-highlighter-angular-with-prism-js/
- https://github.com/angular-patterns/ng-prismjs

**Comment by votdev** [comment]
Looking what other projects are using (e.g. Portainer), i found [CodeMirror](https://codemirror.net) for which an [Angular component](https://github.com/scttcper/ngx-codemirror) exists.
