### ISSUE TITLE
[Bug] GUI Log: Order of entries not correct when they occured in the same second

### ISSUE THREAD

**Issue by HannesJo0139** [openmediavault/openmediavault#1344]
When a log has multiple events in the same second, they are no longer shown in correct order by the gui. See screen at  02:40:12.

----
<img width="846" alt="Bildschirmfoto 2022-07-07 um 02 45 00" src="https://user-images.githubusercontent.com/42114183/177666442-5491da89-9f76-4ef0-8675-c076d81cf3af.png">
<img width="955" alt="Bildschirmfoto 2022-07-07 um 02 45 30" src="https://user-images.githubusercontent.com/42114183/177666451-e8522c92-232a-4ee0-8483-3fc7ecb7598b.png">

**Comment by ryecoaaron** [comment]
The log viewer allows sorting the columns.  That means it does an initial sort.  If the times are the same, how would you know how to sort them in the correct order?

**Comment by HannesJo0139** [comment]
> The log viewer allows sorting the columns. That means it does an initial sort. If the times are the same, how would you know how to sort them in the correct order?

Re-sorting by date is not only unnecessary, but as you correctly pointed out, it can not work properly with the given timestamp resolution. Under the hood, the GUI should keep the sorting by occurrence in the file.

**Comment by votdev** [comment]
> > The log viewer allows sorting the columns. That means it does an initial sort. If the times are the same, how would you know how to sort them in the correct order?
> 
> Obviously. Re-sorting by date is not only unnecessary, but as you correctly pointed out, it can not work properly with the given timestamp resolution. Under the hood, the GUI should keep the sorting by occurrence in the file.

Would be great to see a PR by you with a fix if possible.
