### ISSUE TITLE
More userfriendlyness for mountpoints, filesystem names and drive names

### ISSUE THREAD

**Issue by henfri** [openmediavault/openmediavault#1345]
**Is your feature request related to a problem? Please describe.**
The way OMV is letting the User identify 
- Harddrives
- Shared Folders
- Mountpoints
and associate them to each other is certainly logical from a developers point of view, but not from a users perspective

**Describe the solution you'd like**
I want to be able to easily identify drives/filesystems/mountpoints
Instead of 
`/dev/sda WDC WD120EMFZ-11A6JA0 Y5J5E31C`
OMV should call it something userfriendly.
a) ask the user when it appears for the first name for a name that it should give this drive
b) call the first drive it ever sees "Disk 1", the second "Disk 2" ... or: "Disk 1 - 12TB - Western Digital"
(b) could be also the default suggestion for (a) in the Gui.

When then in the Filesystem Dialog, I don't want
`/dev/sdb1 UUID=c4a6a2c9-5cf0-49b8-812a-0784953f9ab3`

I want [what I have used as Name above] e.g. "Disk 1 - 12TB - Western Digital - Partition1"

**Describe alternatives you've considered**

For Shares, what I want is already prepared: When using a "Comment" for the Filesystem that I generate, this Comment is shown in the Filesystem Selection Box when creating a share. That is in principle good. But the Comment seems very optional. I think that you should encourage (or even enforce) the proper naming of a Filesystem. This way, it is properly identifyable when creating shares.

**Additional context**
I think that would make OMV much more userfriendly

**Comment by votdev** [comment]
The concept of OMV is using the UI to configure the system. The UI hides the user from the internally used device files and mount paths. The mount paths are build that way to ensure they are generic and predictable.
The UI provides helpers to copy the mount path easily to use them externally (custom shell scripts, Container UIs, ...). The UI provides comments to help the user to order and identify the disks, shared folders, etc.
