### ISSUE TITLE
OMV_NFSD_COUNT is ignored in 6.x

### ISSUE THREAD

**Issue by plague-doctor** [openmediavault/openmediavault#1346]
**Describe the bug**

OMV_NFSD_COUNT variable is ignored in 6.x

**To Reproduce**

1. Set the variable: `omv-env set -- OMV_NFSD_COUNT 32`
2. Reboot OMV server
4. Check the variable: `omv-env get OMV_NFSD_COUNT` returns: `OMV_NFSD_COUNT=32`
5. Check the processes: `ps -aux | grep nfsd` returns: default 8 processes.

**Expected behavior**

In step 5 to see 32 running processes.

**Comment by ryecoaaron** [comment]
This variable is still supported - https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/nfs/files/etc-default-nfs-kernel-server.j2#L1.  There is no need to reboot the server but you do need to prepare saltstack.   Look at the Apply Changes section -  https://openmediavault.readthedocs.io/en/5.x/various/advset.html
