### ISSUE TITLE
web interface error

### ISSUE THREAD

**Issue by HACKER-3000** [openmediavault/openmediavault#135]
Fehler #0:
OMV\Exception: Failed to read file '/tmp/bgstatusZqwnty' (size=0). in /usr/share/php/openmediavault/json/file.inc:199
Stack trace:
#0 /usr/share/php/openmediavault/json/file.inc(214): OMV\Json\File->getContents()
#1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(314): OMV\Json\File->read()
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(544): OMV\Rpc\ServiceAbstract->finalizeBgProcStatus('/tmp/bgstatusZq...', '', Object(OMV\Exception))
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#4 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(440): OMV\Rpc\ServiceAbstract->callMethodBg('getList', Array, Array)
#5 [internal function]: OMVRpcServiceFileSystemMgmt->getListBg(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getListBg', Array, Array)
#8 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('FileSystemMgmt', 'getListBg', Array, Array, 1)
#9 {main}

**Comment by votdev** [comment]
Which version are we talking about?

**Comment by votdev** [comment]
Please update via CLI or WebUI. The error has been fixed in one of the latest version (not included in the latest ISO).

**Comment by HACKER-3000** [comment]
thx. but why not inclue in iso?

**Comment by votdev** [comment]
Because you can update it later easily. So there is no need to create and upload new ISO's everytime.

**Comment by HACKER-3000** [comment]
the porblem is the update gui does not work °^°

**Comment by votdev** [comment]
Then use the CLI: ``omv-update``

The issue your running into only happens on a small number of systems. Nd since there are multiple ways to update the system there is currently no need to release a new ISO. Keep in mind that creating and releasing a new ISO will finally take hours. This time can be used more efficient in other OMV things.
