### ISSUE TITLE
Debian's xattr -l crashes with UnicodeDecodeError on Finder Tags in xattr com.apple.metadata:_kMDItemUserTags (encoded as Binary Property List, PLIST)

### ISSUE THREAD

**Issue by porg** [openmediavault/openmediavault#1350]
## Foreword
- **Could someone with an existing Debian account please file that on my behalf?**
	- Debian has no web based issue tracker like Github or Bugzilla or a Forum but an ancient way of bug reporting (custom Terminal tool, Terminal based mail delivery). Would take me further hours to setup and learn, and would unlikely ever use again.
- I found this bug here along the way during the 2 days I spent on the related matter:
	- https://github.com/WayneD/rsync/issues/337
	- https://github.com/openmediavault/openmediavault/issues/1163#issuecomment-1182012948
- I hope that OMV maintainers or Debian Pros have Debian bug reporting up and running. Would appreciate your help!
	- @votdev or @stalinCCCP415 maybe?

## Problem
- Debian's command line tool xattr with it's -l List mode with its mixed hex/plaintext output, will choke if the raw data contains certain special byte orders, which cannot be interpreted as ASCII or UTF-8.
- It shows the xattrs which work.
- And upon encountering the first key/value with such an unhandlable value it does not even show the key name, but crashes right away. It also does not continue with the remaining xattrs for that file. It also does not continue to the next files in the listing queue. It is a total crash, aborting all remaining tasks.
- In theory this bug could happen on any xattr that has such a raw binary value, which cannot be interpreted as plaintext.
- In practise I encountered it with files coming from a Mac via SMB which have Finder tags encoded as binary property lists in the xattr `com.apple.metadata:_kMDItemUserTags`.

## Background Info

- MacOS stores the Finder tags in an xattr named `com.apple.metadata:_kMDItemUserTags` as a binary PLIST.

## Expected
- Byte portions which cannot be interpreted as text with any of the known/usual character encodings should simply show an "unknown character" symbol, instead of crashing.
- Or if that's not possible then at least the key name, and for the value only show a hexadecimal representation without a plaintext interpretation.
- And continue to the next key/values pairs of the current file.
- And continue with the next files in the queue.

## Reproduction

1. From a Mac copy files with different metadata (none, with Finder flag(s), label, both) to a Debian based NAs via SMB.
2. The server runs Samba with the vfs_fruit module which supports Mac-specific SMB protocol extensions (like how xattr get mapped).
3. xattr -l <macfiles> crashes (if at least one xattr with unhandleable bytes)

## Detailed Log

- $: This happens on the Mac.
- §: This happens on the NAS (running Debian based Open Media Vault) via SSH.

### Syncing via rsync (sender on the mac, receiver on the NAS)

```

$ xattr -l ~/mac/path/0.txt   # Has no special Finder metadata at all.
# Returns NULL.

$ xattr -l ~/mac/path/1.txt   # With "hide suffix" flag.

com.apple.FinderInfo:
00000000  00 00 00 00 00 00 00 00 00 10 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000020

$ xattr -l ~/mac/path/2.txt  # With "hide suffix" flag + Finder tags.

com.apple.FinderInfo:
00000000  00 00 00 00 00 00 00 00 00 10 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000020

com.apple.metadata:_kMDItemUserTags:
00000000  62 70 6C 69 73 74 30 30 A2 01 02 54 43 68 61 74  |bplist00...TChat|
00000010  5D 43 6F 6C 6C 61 62 6F 72 61 74 69 6F 6E 08 0B  |]Collaboration..|
00000020  10 00 00 00 00 00 00 01 01 00 00 00 00 00 00 00  |................|
00000030  03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000040  1E                                               |.|
00000041


$ xattr -l ~/mac/path/3.txt  # With Finder Tag "Artwork" without any color.

com.apple.metadata:_kMDItemUserTags:
00000000  62 70 6C 69 73 74 30 30 A1 01 57 41 72 74 77 6F  |bplist00..WArtwo|
00000010  72 6B 08 0A 00 00 00 00 00 00 01 01 00 00 00 00  |rk..............|
00000020  00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 12                                      |....|
00000034

$ xattr -l ~/mac/path/3.txt # Meanwhile tag "Automation" was added to the end.

com.apple.metadata:_kMDItemUserTags:
00000000  62 70 6C 69 73 74 30 30 A2 01 02 57 41 72 74 77  |bplist00...WArtw|
00000010  6F 72 6B 5A 41 75 74 6F 6D 61 74 69 6F 6E 08 0B  |orkZAutomation..|
00000020  13 00 00 00 00 00 00 01 01 00 00 00 00 00 00 00  |................|
00000030  03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000040  1E                                               |.|
00000041

$ xattr -l ~/mac/path/3.txt # Meanwhile tag "Billing" was inserted at start.

com.apple.metadata:_kMDItemUserTags:
00000000  62 70 6C 69 73 74 30 30 A3 01 02 03 57 42 69 6C  |bplist00....WBil|
00000010  6C 69 6E 67 57 41 72 74 77 6F 72 6B 5A 41 75 74  |lingWArtworkZAut|
00000020  6F 6D 61 74 69 6F 6E 08 0C 14 1C 00 00 00 00 00  |omation.........|
00000030  00 01 01 00 00 00 00 00 00 00 04 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00 00 00 27                 |..........'|
0000004b	

$ xattr -l ~/mac/path/3.txt  # Tag set changed to: "Graphics", "Utility", "Conversion"
com.apple.metadata:_kMDItemUserTags:
00000000  62 70 6C 69 73 74 30 30 A3 01 02 03 58 47 72 61  |bplist00....XGra|
00000010  70 68 69 63 73 57 55 74 69 6C 69 74 79 5A 43 6F  |phicsWUtilityZCo|
00000020  6E 76 65 72 73 69 6F 6E 08 0C 15 1D 00 00 00 00  |nversion........|
00000030  00 00 01 01 00 00 00 00 00 00 00 04 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00 00 00 00 28              |...........(|
0000004c

$ rsync --archive --xattrs --delete --verbose --stats --progress \
--itemize-changes --human-readable ~/mac/path odroid.local::Shared-rsync/path/
# Rsync on Linux performs a minimap mapping: Only adds the "user." prefix.
# We will see this soon.

§ xattr -l ~/nas/path/0.txt   # Shows no xattr as file indeed has none.
# Returns NULL     

§ xattr -l ~/nas/path/1.txt   # Shows its sole xattr.
user.com.apple.FinderInfo:
0000   00 00 00 00 00 00 00 00 00 10 00 00 00 00 00 00    ................
0010   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................

§ xattr -l ~/nas/path/2.txt   # Shows first xattr, then crashes.
user.com.apple.FinderInfo:
0000   00 00 00 00 00 00 00 00 00 10 00 00 00 00 00 00    ................
0010   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................

Traceback (most recent call last):
  File "/usr/bin/xattr", line 11, in <module>
    load_entry_point('xattr==0.9.6', 'console_scripts', 'xattr')()
  File "/usr/lib/python3/dist-packages/xattr/tool.py", line 196, in main
    attr_value = attr_value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 8: invalid start byte

$ xattr -l ~/nas/path/3.txt   # Crashes on first xattr already
Traceback (most recent call last):
  File "/usr/bin/xattr", line 11, in <module>
    load_entry_point('xattr==0.9.6', 'console_scripts', 'xattr')()
  File "/usr/lib/python3/dist-packages/xattr/tool.py", line 196, in main
    attr_value = attr_value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 8: invalid start byte

§ rm ~/nas/path/*             # Deleting for next round of tests.


```

### Now copying to NAS via SMB

```
$ cp ~/mac/path/* /Volumes/Mounted-SMB-Share/path/
```

- Samba performs a more complex mapping (verified for custom xattr, assumed for com.apple.* xattrs too)
	- Which is practically correct. Results in correct display of Finder tags on the NAS viewed in Finder.
- Due to the Debian `xattr -l` display bug I could never explicitly inspect on the NAS.
- But from custom Mac xattrs with pure ASCII key/value, the transformation which happenes is:
	- key "myTest" with value "Hello" got prefixed with "user.DosStream." so "user.DosStream.myTest"
	- I assume the same to have happened with `com.apple.FinderInfo` and `com.apple.metadata:_kMDItemUserTags`
- So after the SMB sync the crashing is a bit different:
	- `§ xattr -l ~/nas/path/1.txt` returns NULL
	- `§ xattr 1.txt throughout 3.txt` all run right into the same error imediately
	- So seemingly something different happened with `1.txt` in rsync vs SMB which just has the byte-harmless `com.apple.FinderInfo`.

	
### [Odroid Home Cloud 2](https://www.hardkernel.com/shop/odroid-hc2-home-cloud-two/) — Single Board Computer (SBC) acting as a Network Attached Storage (NAS)
- OpenMediaVault 5.6.21-2 (Debian based) Linux 4.14.222-odroidxu4
	- `xattr --version` returns no version info, `man xattr` says "May  8, 2010"
	- **rsync  version 3.1.3  protocol version 31**
		- Capabilities: 64-bit files, 64-bit inums, 32-bit timestamps, 64-bit long ints, socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace, append, ACLs, xattrs, iconv, symtimes, prealloc
	- **Samba, using module vfs_fruit** for "Enhanced OS X and Netatalk interoperability", see config file:

<details><summary>/etc/samba/smb.conf 👈 Click to expand</summary>

``` ini
# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.
#======================= Global Settings =======================
[global]
workgroup = WORKGROUP
server string = %h server
dns proxy = no
log level = 2
log file = /var/log/samba/log.%m
max log size = 1000
logging = syslog
panic action = /usr/share/samba/panic-action %d
encrypt passwords = true
passdb backend = tdbsam
obey pam restrictions = no
unix password sync = no
passwd program = /usr/bin/passwd %u
passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
pam password change = yes
socket options = TCP_NODELAY IPTOS_LOWDELAY
guest account = nobody
load printers = no
disable spoolss = yes
printing = bsd
printcap name = /dev/null
unix extensions = yes
wide links = no
create mask = 0777
directory mask = 0777
use sendfile = yes
aio read size = 16384
aio write size = 16384
time server = no
wins support = no
multicast dns register = no
# Special configuration for Apple's Time Machine  # Coming from GUI autoconfig
fruit:aapl = yes                                  # Coming from GUI autoconfig
# Extra options
# OMV default extra options
min receivefile size = 16384
write cache size = 524288
getwd cache = yes
socket options = TCP_NODELAY IPTOS_LOWDELAY

# Recommendations from
# https://wiki.samba.org/index.php/Configure_Samba_to_Work_Better_with_Mac_OS_X
# man vfs_fruit

min protocol = SMB2
ea support = yes

vfs objects = fruit streams_xattr  # https://support.apple.com//HT207128 
                                   #  would recommended "catia fruit streams_xattr". Did not try that yet.
fruit:aapl = yes                   # Manually by me in extra options of GUI

fruit:metadata = stream
fruit:posix_rename = yes 
fruit:veto_appledouble = no
fruit:nfs_aces = no
fruit:wipe_intentionally_left_blank_rfork = yes 
fruit:delete_empty_adfiles = yes 
#======================= Share Definitions =======================
[Shared]
path = /srv/dev-disk-by-label-share/Shared/
guest ok = no
guest only = no
read only = no
browseable = yes
inherit acls = yes
inherit permissions = no
ea support = no
store dos attributes = no
vfs objects =                        # Coming from GUI autoconfig. Afraid this nullifies.
printable = no
create mask = 0664
force create mode = 0664
directory mask = 0775
force directory mode = 0775
hide special files = yes
follow symlinks = yes
hide dot files = no

# These seem to be derived from the settings for the share folder by the autoconfig:
valid users = "wife","me"
invalid users = @"kids"
read list = "wife"
write list = "me"

vfs objects = fruit streams_xattr  # Hence manually aded by me in extra options of GUI.
```

</details>

### MacBook Pro (Mid 2014)
- MacOS 11.6.7 Big Sur
	- **rsync  version 3.2.4  protocol version 31** (installed via [HomeBrew](https://brew.sh))
		- Capabilities: 64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints, socketpairs, symlinks, symtimes, hardlinks, hardlink-specials, hardlink-symlinks, IPv6, atimes, batchfiles, inplace, append, ACLs, xattrs, optional protect-args, iconv, no prealloc, stop-at, crtimes, file-flags
		- Optimizations: no SIMD-roll, no asm-roll, openssl-crypto, no asm-MD5
		- Checksum list: xxh128 xxh3 xxh64 (xxhash) md5 md4 none
		- Compress list: zstd lz4 zlibx zlib none

**Comment by votdev** [comment]
Closing because i am not familar with the bug and can not answer questions from the package maintainers.

**Comment by porg** [comment]
As I wrote, until I understand all that very technical and bureaucratic instructions from Debian, it will take me hours.

If you could give me the correct email template here, with all the single-line headers at the start of the email body as really needed, and not just our given example (which seems unrelated), then I give it a shot!

That would really help me.

**Comment by porg** [comment]
- I will try to submit with just two lines.
- I assume email subject is the bug title.
- Give me this last help please, and we are through it: What's the appropriate package and what version is integrated in OpenMediaVault 5.6.21-2 (Debian based) Linux 4.14.222-odroidxu4 ? I myself have no ideas on that.

**Comment by votdev** [comment]
> I will try to submit with just two lines.

No, the first two lines are important to identify which package is involved in the bug report. The rest of the email you should simply contain everything you posted above as error description.

> Give me this last help please, and we are through it: What's the appropriate package and what version is integrated in OpenMediaVault 5.6.21-2 (Debian based) Linux 4.14.222-odroidxu4 ? I myself have no ideas on that.

I have no idea because OMV5 is EOL and i have no instance running anymore. But you can do a `dpkg -l | grep xattr` to find out the version. By the way, `xattr` is not installed in OMV by default.

You are using OMV5, so Buster is the Debian release. So i think 0.9.6 is the version of the [xattr](https://packages.debian.org/buster/xattr) package.

**Comment by porg** [comment]
## Thanks for your help!
- From your hint that xattr is not included in OMV by default I recall that I must have manually installed it.
```
$ dpkg -l | grep xattr
ii  python3-xattr                      0.9.6-1                             armhf        module for manipulating filesystem extended attributes - Python 3
ii  xattr                              0.9.6-1                             armhf        tool for manipulating filesystem extended attributes
```

- So my email will be:

```
SUBJECT:
xattr -l crashes with UnicodeDecodeError on Finder Tags in xattr com.apple.metadata:_kMDItemUserTags (Binary PLIST)

BODY:
Package: xattr
Version: 0.9.6-1

Description from this issue in as many lines as I want.
…
```

## Offtopic
- Learned from your post that OMV5 is EOL and that there is OMV6 now.
  - Because I had clicked OMV > Extras > Updates > dist-upgrade
  - Told me nothing new.
  - I had expected that if there's a new major OMV version, I'd be informed here. Not?
- Anyways I now know. Feedback to the OMV website:
  - https://openmediavault.readthedocs.io/en/stable/installation/
    - Not a single word of "upgrade".
    - A remark how to upgrade from an existing installation there would be fine.
  - [OMV6 (Shaitan) RC1 released](https://www.openmediavault.org/?p=3010) mentions:
    > OMV5 systems with version 5.6.18 or later can be upgraded via the command line tool `omv-release-upgrade`. 
  - All of the few plugins I have on OMV5 are listed as supported on OMV6.
  - So I will give `omv-release-upgrade` a try now.

## So I will try xattr on OMV6 (Debian 11)
- Before finally reporting to Debian.
