### ISSUE TITLE
[Future Bug] Do not set or configure 'force_http_2' for 'onedrive' plugin

### ISSUE THREAD

**Issue by abraunegg** [openmediavault/openmediavault#1351]
In reviewing https://github.com/openmediavault/openmediavault/commit/c05ee0d549ac0397b952a53ce311c0fb14628221

I have noticed this:
```
{%- set force_http_2 = salt['pillar.get']('default:OMV_ONEDRIVE_FORCEHTTP2', 'true') -%}
```
![image](https://user-images.githubusercontent.com/4956234/178586323-80eeaf87-04c1-4180-a7be-cc911b5c5b4e.png)

The flag 'force_http_2' is depreciated and removed post v2.4.19, and if this is being set via application configuration currently, it should be removed - as when v2.4.20 is released, having this option 'enabled' will cause the application to not start as it is an unknown configuration option.

Regarding the application use of 'curl':

* If your system utilises curl < 7.47.0, curl defaults to HTTP/1.1 for HTTPS operations. The client will use HTTP/1.1.
* If your system utilises curl >= 7.47.0 and < 7.62.0, curl will prefer HTTP/2 for HTTPS but will stick to HTTP/1.1 by default. The client will use HTTP/1.1 for HTTPS operations.
* If your system utilises curl >= 7.62.0, curl defaults to prefer HTTP/2 over HTTP/1.1 by default. The client will utilse HTTP/2 for most HTTPS operations and HTTP/1.1 for others. This difference is governed by the OneDrive platform and not this client.

Reference: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#curl-compatibility

Please remove any OMV configuration reference to 'force_http_2'

**Comment by votdev** [comment]
Thx for reporting this issue.
