### ISSUE TITLE
OMV 6 - 502 Bad Gatway 

### ISSUE THREAD

**Issue by prashantdwivedi** [openmediavault/openmediavault#1352]
Fresh Setup of OMV 6 on raspberry pi 4 (4GB) model.

During Login with username and password, it says 502 bad gateway. Below Image
![CleanShot 2022-07-13 at 10 27 40@2x](https://user-images.githubusercontent.com/6306052/178654192-7ab125db-d3a7-493b-8cdb-40515ab9c76d.png)

On raspberry pi OS is that and for burn on SD card use **Raspberry Pi Imager v1.7.2**
<img width="568" alt="CleanShot 2022-07-13 at 10 30 48@2x" src="https://user-images.githubusercontent.com/6306052/178654484-b5ccc38c-8e12-484a-8585-f1dac441c079.png">

Guide Follow to install OMV 6
https://wiki.omv-extras.org/doku.php?id=installing_omv6_raspberry_pi

Some other images may help
<img width="1130" alt="CleanShot 2022-07-13 at 10 36 37@2x" src="https://user-images.githubusercontent.com/6306052/178655065-3367c1bf-0f0b-4023-b8da-34d63450f2a6.png">
<img width="1272" alt="CleanShot 2022-07-13 at 10 37 34@2x" src="https://user-images.githubusercontent.com/6306052/178655208-4e7f0869-07a3-4ea1-a493-719e0bed0e5f.png">

Please help to solve that issue 🙏

**Comment by votdev** [comment]
Please try running `omv-salt deploy run phpfpm nginx`. Does it help?

**Comment by prashantdwivedi** [comment]
I try early that method you mentioned which not work sadly.

**Comment by votdev** [comment]
Any useful information when running the commands:
```
# cat /var/log/php7.4-fpm.log
# cat /var/log/nginx/openmediavault-webgui_error.log
```

**Comment by sebeksd** [comment]
I have OMV6 server running for months and I saw this happened to me like two or three times after restart. Every time SSH worked fine but WebUI was trowing 502 even if I was previously logged in.
Doing machine restart always helped to fix that issue. I guess in my case some service did not start correctly or had a problem to bind to port or something like that. On OMV5 (this server was updated from OMV5) this problem never occurred (I think).

**Comment by Vitaly1985** [comment]
> Fresh Setup of OMV 6 on raspberry pi 4 (4GB) model.
> 
> During Login with username and password, it says 502 bad gateway. Below Image ![CleanShot 2022-07-13 at 10 27 40@2x](https://user-images.githubusercontent.com/6306052/178654192-7ab125db-d3a7-493b-8cdb-40515ab9c76d.png)
> 
> On raspberry pi OS is that and for burn on SD card use **Raspberry Pi Imager v1.7.2** <img alt="CleanShot 2022-07-13 at 10 30 48@2x" width="568" src="https://user-images.githubusercontent.com/6306052/178654484-b5ccc38c-8e12-484a-8585-f1dac441c079.png">
> 
> Guide Follow to install OMV 6 https://wiki.omv-extras.org/doku.php?id=installing_omv6_raspberry_pi
> 
> Some other images may help <img alt="CleanShot 2022-07-13 at 10 36 37@2x" width="1130" src="https://user-images.githubusercontent.com/6306052/178655065-3367c1bf-0f0b-4023-b8da-34d63450f2a6.png"> <img alt="CleanShot 2022-07-13 at 10 37 34@2x" width="1272" src="https://user-images.githubusercontent.com/6306052/178655208-4e7f0869-07a3-4ea1-a493-719e0bed0e5f.png">
> 
> Please help to solve that issue 🙏

Hello guys!


> Fresh Setup of OMV 6 on raspberry pi 4 (4GB) model.
> 
> During Login with username and password, it says 502 bad gateway. Below Image ![CleanShot 2022-07-13 at 10 27 40@2x](https://user-images.githubusercontent.com/6306052/178654192-7ab125db-d3a7-493b-8cdb-40515ab9c76d.png)
> 
> On raspberry pi OS is that and for burn on SD card use **Raspberry Pi Imager v1.7.2** <img alt="CleanShot 2022-07-13 at 10 30 48@2x" width="568" src="https://user-images.githubusercontent.com/6306052/178654484-b5ccc38c-8e12-484a-8585-f1dac441c079.png">
> 
> Guide Follow to install OMV 6 https://wiki.omv-extras.org/doku.php?id=installing_omv6_raspberry_pi
> 
> Some other images may help <img alt="CleanShot 2022-07-13 at 10 36 37@2x" width="1130" src="https://user-images.githubusercontent.com/6306052/178655065-3367c1bf-0f0b-4023-b8da-34d63450f2a6.png"> <img alt="CleanShot 2022-07-13 at 10 37 34@2x" width="1272" src="https://user-images.githubusercontent.com/6306052/178655208-4e7f0869-07a3-4ea1-a493-719e0bed0e5f.png">
> 
> Please help to solve that issue 🙏



> Fresh Setup of OMV 6 on raspberry pi 4 (4GB) model.
> 
> During Login with username and password, it says 502 bad gateway. Below Image ![CleanShot 2022-07-13 at 10 27 40@2x](https://user-images.githubusercontent.com/6306052/178654192-7ab125db-d3a7-493b-8cdb-40515ab9c76d.png)
> 
> On raspberry pi OS is that and for burn on SD card use **Raspberry Pi Imager v1.7.2** <img alt="CleanShot 2022-07-13 at 10 30 48@2x" width="568" src="https://user-images.githubusercontent.com/6306052/178654484-b5ccc38c-8e12-484a-8585-f1dac441c079.png">
> 
> Guide Follow to install OMV 6 https://wiki.omv-extras.org/doku.php?id=installing_omv6_raspberry_pi
> 
> Some other images may help <img alt="CleanShot 2022-07-13 at 10 36 37@2x" width="1130" src="https://user-images.githubusercontent.com/6306052/178655065-3367c1bf-0f0b-4023-b8da-34d63450f2a6.png"> <img alt="CleanShot 2022-07-13 at 10 37 34@2x" width="1272" src="https://user-images.githubusercontent.com/6306052/178655208-4e7f0869-07a3-4ea1-a493-719e0bed0e5f.png">
> 
> Please help to solve that issue 🙏

Hi guys. I encountered the identical "502 Bad request" issue after updating omv 5 --> omv 6. Upgrading to omv 7 did not solve the problem. ngonx, php7.4, and openmediavault services are active and running. I tried to follow the recommendations from this post, but it didn't help me solve the problem. I am ready to provide all the necessary information by mistake from the logs. Please help me, I've already broken my head....

**Comment by Vitaly1985** [comment]
> > Fresh Setup of OMV 6 on raspberry pi 4 (4GB) model.
> > During Login with username and password, it says 502 bad gateway. Below Image ![CleanShot 2022-07-13 at 10 27 40@2x](https://user-images.githubusercontent.com/6306052/178654192-7ab125db-d3a7-493b-8cdb-40515ab9c76d.png)
> > On raspberry pi OS is that and for burn on SD card use **Raspberry Pi Imager v1.7.2** <img alt="CleanShot 2022-07-13 at 10 30 48@2x" width="568" src="https://user-images.githubusercontent.com/6306052/178654484-b5ccc38c-8e12-484a-8585-f1dac441c079.png">
> > Guide Follow to install OMV 6 https://wiki.omv-extras.org/doku.php?id=installing_omv6_raspberry_pi
> > Some other images may help <img alt="CleanShot 2022-07-13 at 10 36 37@2x" width="1130" src="https://user-images.githubusercontent.com/6306052/178655065-3367c1bf-0f0b-4023-b8da-34d63450f2a6.png"> <img alt="CleanShot 2022-07-13 at 10 37 34@2x" width="1272" src="https://user-images.githubusercontent.com/6306052/178655208-4e7f0869-07a3-4ea1-a493-719e0bed0e5f.png">
> > Please help to solve that issue 🙏
> 
> Hi guys. I encountered the identical "502 Bad gateway" issue after updating omv 5 --> omv 6. Upgrading to omv 7 did not solve the problem. ngonx, php7.4, and openmediavault services are active and running. I tried to follow the recommendations from this post, but it didn't help me solve the problem. I am ready to provide all the necessary information by mistake from the logs. Please help me, I've already broken my head....


Is there anyone here who can help me with this error, or do I need to create a new post for this error?

**Comment by Youngblood50** [comment]
This happened to me after updating from 7 to 8. The command "omv-salt deploy run phpfpm nginx" fixed it for me.
