### ISSUE TITLE
[BUG] 6.0.31-1 fix for issue #1330 seems to have broken installation for Raspberry Pi 4 

### ISSUE THREAD

**Issue by yamsy345** [openmediavault/openmediavault#1353]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

6.0.31-1 fix for issue #1330 seems to have broken installation for Raspberry Pi 4 
( Please excuse my OpenSource bug reporting etiquettes, if inappropriate. This is my 1st time doing so.)

Installation fails wth the following error:

  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 472, in _check_enum
    raise SchemaValidationException(
openmediavault.json.schema.SchemaValidationException: standbymode: Invalid value 'poweroff|suspend|hibernate|suspendhybrid', allowed values are 'poweroff, suspend, hibernate, suspendhybrid'.

**To Reproduce**

Use the install script method as per https://github.com/OpenMediaVault-Plugin-Developers/installScript
trying to install OMV on RPI.

**Expected behavior**

OMV installs successfully

**Screenshots**

**Reference to Forum**

[URL link to forum post](https://forum.openmediavault.org/index.php?thread/43885-latest-openmediavault-6-0-31-1-does-not-connect-to-nvidia/&postID=318416&highlight=openmediavault.json.schema.SchemaValidationException%2Bstandbymode#post318416)

**openmediavault Server fail to install on Raspberry Pi 4 :**

- OS version: Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
- openmediavault version: 
rc  openmediavault                       6.0.31-1                         all          openmediavault - The open network attached storage solution
rc  openmediavault-flashmemory           6.2                              all          folder2ram plugin for openmediavault
ii  openmediavault-keyring               1.0                              all          GnuPG archive keys of the OpenMediaVault archive
rc  openmediavault-omvextrasorg          6.1                              all          OMV-Extras.org Package Repositories for OpenMediaVault

**Client (please complete the following information):**

**Additional context**

**Comment by votdev** [comment]
Fixed with https://github.com/openmediavault/openmediavault/commit/a26e07e5e5d03883da12bd6cb5c4159ff0a748ef.

**Comment by yamsy345** [comment]
Thank you

**Comment by yamsy345** [comment]
Hi votdev,

With new build also same error:

- snip - (install script progress) 

Total run time:  46.267 s
Processing triggers for openmediavault (6.0.31-2) ...
Updating workbench configuration files ...

- snip - (install script error)

openmediavault.json.schema.SchemaValidationException: standbymode: Invalid value 'poweroff|suspend|hibernate|suspendhybrid', allowed values are 'poweroff, suspend, hibernate, suspendhybrid'.

; line 25


** Comment : Not sure if it is a data type error, String received when List is expected

Thanks

**Comment by votdev** [comment]
Can not reproduce that setting up a new [Vagrant box](https://github.com/openmediavault/openmediavault/tree/master/vagrant).

**Comment by votdev** [comment]
I don't know your installation process, but if the you run the omv-extras.org installation script you may need to delete `/etc/openmediavault/config.xml` beforehand.

**Comment by yamsy345** [comment]
Hi votdev,

Thanks for the pointer to the config.xml. 

However, I had nuked the RPI OS installation. Afterward, install went through smoothly.

Appreciate it.

Regards.
