### ISSUE TITLE
user@host:CurrentDir  should be the default in .bashrc

### ISSUE THREAD

**Issue by porg** [openmediavault/openmediavault#1354]
`$ user@host:CurrentDir` would be a far more user friendly default.

`$ user@host:/full/paths/especially-with-long-drive-names/leave-you-no-space-anymore/`

In .bashrc change the `\w` (lowercase) to `\W` (uppercase)

    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
                                                                                           ^^
               this one waaaaaay over here ------------------------------------------------+    

Found this [hint on StackExchange](https://superuser.com/questions/60555/show-only-current-directory-name-not-full-path-on-bash-prompt/60563#60563).

**Comment by votdev** [comment]
Customizing the CLI is not the job of OMV, this can be done individually by every user itself.

**Comment by ryecoaaron** [comment]
That is the default when the user's shell is /bin/bash.  The default shell is /bin/sh and it does not customize the prompt.

**Comment by ryecoaaron** [comment]
Oh, nevermind.  I disagree with shortening to just the current directory name.  I want to see the full path.

**Comment by votdev** [comment]
> Oh, nevermind. I disagree with shortening to just the current directory name. I want to see the full path.

Full ACK. That's why i wrote `this should be done individually by every user itself based on his preferences.`

**Comment by ryecoaaron** [comment]
I know.  I was just responding to my own comment and hit enter too early.

**Comment by porg** [comment]
Thanks for the infos. Accepting that you do not see this as part of the distro experience.
