### ISSUE TITLE
Dashboard: Consistent status colors + Add "Edit" button (to add/remove widgets)

### ISSUE THREAD

**Issue by porg** [openmediavault/openmediavault#1355]
<img width="1440" alt="OMV6 Dashboard - Edit layout button + Consistent colors" src="https://user-images.githubusercontent.com/737143/178966425-3154d170-e6d8-4238-b8c5-9378514e0e9e.png">

**Comment by votdev** [comment]
I think the currently used colors of the memory widget are ok because of:

- A red color indicates 'Uff, my system is using that much RAM'
- A green color indicated 'Nice, my system has already that amount of free RAM'

I can not link any of those feelings to a gray color.

**Comment by porg** [comment]
My advice as a UX designer doing this professionally full time for 10 years now:
- Per itself your color associations for the RAM module make sense
- But in the context of the dashboard, whose main goal is to provide an overview, comparability and orientation is very important.
- Having a a color inconsistency between the different dashboard widgets is a high burden on the mind and makes quickly comparability hard.

**Comment by porg** [comment]
If you have that association for RAM, then you would consequently need it to apply to CPU too.

There the load is "green" and not red.

it is simply inconsistent as it currently is and thus unintuitive to the subconscious.

**Comment by porg** [comment]
> The dashboard widgets can be configured via the 'Wheel' icon in the top navigation bar which contains the user settings for the UI.

- That feels wrong:
  - That settings menu feels "global".
  - Which widgets to add/remove to the Dashboard is a setting I'd rather expect "locally" on a specific page (screen).
- If you leave it there, there's some room for improvement:
  - It just says "Dashboard" and has the usual icon.
    - That gives me the feeling this is just a shortcut (favorite) to the Dashboard.
      - Which on further thought makes no sense, as the Dashboard is a top menu entry anyhow.
      - But that's the impression it makes.
  - I recommend to change the label to "Configure Dashboard" or "Dashboard Settings"?

**Comment by votdev** [comment]
Could you please suggest a solution for that, e.g. which color’s to use? Maybe as a PR?
You want to see it fixed, so please provide a solution.

**Comment by porg** [comment]
The solution is in my initial post: For RAM
- used = green
- free = grey

**Comment by porg** [comment]
As a comment and not as a PR for two reasons:
- as a designer I sometimes do commits (of HTML markup and CSS) but not of code
- I do not know where the source code for this is, and how it's all structured
- Hence an instruction in a comment and not a PR.
- I hope that's ok.

**Comment by votdev** [comment]
> The solution is in my initial post: For RAM
> 
>     * used = green
> 
>     * free = grey

IMO a bad design decision because grey is used as neutral background color by the Dashboard widgets and free memory is nothing neutral.
Second, the color `green` implies positive information, but used memory isn't something positive. It should get attention, that's why `red` is the right color.

**Comment by porg** [comment]
- Yes I agree on that detail argument too.
  - But in screen type like a Dashboard comparability/consistency an even higher goal.
  - To improve the design as a whole and satisfy all design requirements, namely meaningful color associations per widget + overall consistency, requires more conceptional work due to the interdependencies → My free time is over, would have to do this at a later time.
- So currently doing nothing or the quick fix are the only options.
  - The proposed quick fix which would improve overall consistency and sacrifice the optimal color associations for the RAM widget.
  - Your call now.
