### ISSUE TITLE
omv-release-upgrade from OMV5 to OMV6 reported success but in actuality the system was unstable then a fresh reinstall necessary

### ISSUE THREAD

**Issue by porg** [openmediavault/openmediavault#1356]
## How I had installed my OMV5 back then

As instructed at: https://wiki.omv-extras.org/doku.php?id=installing_omv5_armbian_buster
1. Installed Armbian Buster (Debian 10) from https://www.armbian.com/odroid-xu4/
2. Installed OMV5 via one liner: `wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash`

## How I upgraded to OMV6

1. Checked that the few plugins that I use are supported by OMV6. They all were.
2. Ran: sudo omv-release-upgrade
Worked without issues. At the end of the installation I had a full screen telling me all went fine.
3. Rebooted.
4. Connected via shell. Ran sudo apt-get update ; sudo apt-get upgrade -y
5. Rebooted (not necessary, but to be sure)

It all seemed fine at first.
- But when I attempted to install docker and portainer, which I both did not have on OMV5, I got strange errors.
- After a fresh install, the same installations worked fine without issues.

## Followup
- Nothing to act upon in the code base.
- But please do some updates on the website:
  - The [OMV6 (Shaitan) RC1 release note](https://www.openmediavault.org/?p=3010) states:
      > OMV5 systems with version 5.6.18 or later can be upgraded via the command line tool `omv-release-upgrade`.
     > Please note that this migration path has not yet been tested with many systems. 
  - But the [main official web page on the topic of Installation](https://openmediavault.readthedocs.io/en/stable/installation/)
    - Not a single word of "upgrade".
      - Should explicitly mention how to "upgrade". This is not self explanatory! Nothing which one should implicitly know!
      - That there is the possibility of `omv-release-upgrade` but that it is at your own risk.
      - The recommended upgrade path is by a fresh install.
      -  Users sure prefer a clear info here, as opposed only finding that out after a lot of forum search or from own experience.
      - Appreciated!

**Comment by flmaxey** [comment]
This issue has been reported to the wrong project.  The main openmediavault project supports the server's software and GUI **on amd64 only**.  

OMV-Extras supports 32bit installs, Armbian installs, and Raspberry PI installs.  OMV-Extras also supports alternate installs on amd64's (64 bit), on rare occasions, when the primary method (amd64 ISO installation) fails.
____________________________________________________________

On R-PI's and Armbian, only the "current" version of OMV is supported.  To increase the chances of success, **clean installs are recommended** versus CLI upgrades.  CLI upgrades are at the user's risk.   In any case, a full OS backup is recommended before doing any type of upgrade.

**Comment by votdev** [comment]
> But when I attempted to install docker and portainer, which I both did not have on OMV5, I got strange errors.

Closing this issue because without useful error messages we can not harden the upgrade.

**Comment by porg** [comment]
- Yeah sorry if that part was too vague. Only an "experience report".
- But nothing concrete enough to improve the situation.
- What I learned for the future
  - On my next omv-release-upgrade from 6 to 7 I will do this:
  - Save the Root-FS before and after.
  - If 7 upgraded that way again turn out to behaves instable, I will wipe it again, but then have the RootFS backed up after the upgrade, and later can "excavate" whatever log files you tell me you need.
