### ISSUE TITLE
/root/ misses .profile hence .bashrc is never sourced when logging in as root

### ISSUE THREAD

**Issue by porg** [openmediavault/openmediavault#1358]
## Environment
- Open Media Vault 6

## How I found out
- I wanted to customize the look & feel when logging in as root via SSH.
- Changed `.bashrc` to my needs.
  - When running `source ~/.bashrc` it always took effect.
  - But never took effect when logging in.
- Reason seems to be that there needs to be a `.profile` in which itself is a conditional mechanism that sources `.bashrc`.
- Did it as per [this instruction](https://askubuntu.com/questions/1225184/bashrc-not-run-when-logging-in-as-root/1225267#1225267) and now on login I always get my customization as in the .bashrc.

**Comment by votdev** [comment]
As mentioned in a previous issue, it's not part of OMV to pre-configure the shell. If this is necessary, the administrator can do this on it's own.

**Comment by votdev** [comment]
Keep in mind that the underlying OS is doing that customization in most cases, e.g. PiOS and other Debian based distros for SBC that are supported by OMV.

**Comment by porg** [comment]
I installed Armbian's https://www.armbian.com/odroid-xu4/ edition, and then OMV6 with the one liner install script.

So Armbian would be the correct place to report to?

**Comment by votdev** [comment]
> I installed Armbian's https://www.armbian.com/odroid-xu4/ edition, and then OMV6 with the one liner install script.
> 
> So Armbian would be the correct place to report to?

IMO the best solution to report it upstream.

**Comment by porg** [comment]
- Ok. Will do that.
- Closing this issue here now.
