### ISSUE TITLE
Enable backport only from latest LTS kernel?

### ISSUE THREAD

**Issue by Ansem93** [openmediavault/openmediavault#136]
Hi,
I wanted to know if it's possible to update the kernel using only the backport from latest LTS versions.
What I mean is: right now the lates LTS kernel is the 4.14, but if we enable the backport kernel we will recieve the 4.16.

Since OMV is made for NAS I think that stability should be valued more than latest features.
So my proposal is: there is some way to choose if we want the latest LTS kernel or just the latest stable?

P.S. I don't know if the the backport of the LTS version is manteined once the next stable is out. Of course if there is no new backport of the LTS kernel once the next stable is out this request has no sense :(

**Comment by votdev** [comment]
Please use the forum to ask that question.
