### ISSUE TITLE
Sign In won't proceed when password manager inputs credentials

### ISSUE THREAD

**Issue by wallzero** [openmediavault/openmediavault#1361]
**Describe the bug**

When credentials are input in OMV v6 with a password manager, the sign in form does not recognize any text in the fields.

**To Reproduce**

1. Go to the sign in page
2. Use a password manager to input credentials into the fields
3. The sign in form complains no credentials have been entered; pressing "Log in" doesn't work

**Expected behavior**

After a password manager inputs credentials the user should be able to click "Log in"

**Screenshots**

![Screenshot from 2022-07-24 12-20-17](https://user-images.githubusercontent.com/1195271/180662602-2c9a0fd3-d1cb-42eb-90d9-b3bc2982f161.png)

**openmediavault Server (please complete the following information):**

- OS version: Linux media 5.15.39-1-pve 1 SMP PVE 5.15.39-1 (Wed, 22 Jun 2022 17:22:00 +0200) x86_64 GNU/Linux
- openmediavault version: 6.0.31-2 (Shaitan) 

**Client (please complete the following information):**

- Device: Desktop
- Browser Firefox
- Version 102.0.1

**Work around**

If I remove a single character from each field and reenter it, the form resolves and "Log in" proceeds.

**Additional context**

This happens on both my desktop with Firefox and the Tusk plugin

**Comment by votdev** [comment]
Isn't the problem more with the password manager? The name and password fields are simple HTML input fields without any magic function. The Firefox password manager works without problems.

**Comment by wallzero** [comment]
The login page [is in Angular](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/src/app/core/pages/login-page/login-page.component.ts) and I had assumed there was more logic going on in the background.

I had thought AuthPass on my Android Phone shared the behavior but I just tested it again and now it was working. Although Tusk is still exhibiting the same issue.

If both AuthPass and Firefox password manager are working then I'll assume it's an issue with how Tusk is inputting text into form fields. I'll close this and raise an issue with that project.
