### ISSUE TITLE
Shared Folders → Privileges → Open Instance: Name should be shown in header area of UI

### ISSUE THREAD

**Issue by porg** [openmediavault/openmediavault#1364]
## Usability Issue
- Mostly everywhere in OMV6's UI when going from overview (master) to opening an instance (detail), the instance name is shown somewhere. Either as a field or headline.
- When opening an instance at:
  - Shared Folders → Privileges
  - Shared Folders → ACLs
- no instance name is shown, which can be disorienting: "What have I opened? Not that I change the wrong one…"

**Proposal**: Show the instance name in these detail views too.

## Annotated Screenshots

![Shared Folders 1 Share Instance - Clear which one I look at](https://user-images.githubusercontent.com/737143/181312076-2fbcbd55-73c3-4d52-a1c0-4124b6b4c787.png)

![Shared Folders 2 Share Privilege Instance - Unclear which one I look at](https://user-images.githubusercontent.com/737143/181312081-18e7da18-7172-48f6-8f6f-b53691b03f92.png)

![Shared Folders 3 Share Privilege Instance - Name should be shown somewhere](https://user-images.githubusercontent.com/737143/181312086-480a0b75-56ca-4985-aa68-ab500d6c4129.png)

**Comment by votdev** [comment]
I clearly understand that need and would like to see that as well, but you can be sure that it would be implemented already if it would be that simple to implement. I don't want to go into details, but technically it is not possible right now; e.g. the privileges page does not know anything about the name, it has only a UUID that is referenced by the shared folder.

**Comment by porg** [comment]
Ok. At least it's in the issue tracker now for reference.Maybe
