### ISSUE TITLE
omv_sysinfo_msg loses leading spaces

### ISSUE THREAD

**Issue by nrandon** [openmediavault/openmediavault#1365]
**Describe the bug**

In /usr/share/openmediavault/scripts/helper-functions, the helper function 'omv_msg' currently reads:
```
224 # omv_msg <message>
225 # Print the message to standard out (STDOUT).
226 omv_msg() {
227     echo $*
228 }
```
Line 227 the $* is not quoted, which means that if there is an input that start with spaces, the leading spaces are removed. Is this by design ? As I am trying to use 'omv_sysinfo_msg' in a custom plugin and my output is indented (a bit like, but not YAML) and the indent are removed.

**To Reproduce**

To output some indented YAML in a script using 'omv_sysinfo_msg', example script is as follows:
```
#!/bin/bash
source /usr/share/openmediavault/sysinfo/functions
A="\
Fred: 1
   address: somewhere
Mary: 2
  address: somewhere"
omv_sysinfo_msg "${A}"
echo "${A}"
```

**Expected behaviour**

Leading spaces in output to be preserved by 'omv_msg' unless this is by design for some reason.

**openmediavault Server (please complete the following information):**

- OS version: `Linux bcroftmvault 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux`
- openmediavault version: 
```
ii  openmediavault                       6.0.31-2                               all          openmediavault - The open network attached storage solution
ii  openmediavault-keyring               1.0                                    all          GnuPG archive keys of the OpenMediaVault archive```

**Comment by votdev** [comment]
I had to revert the previous commit because all helper methods like omv_msg, omv_warning or omv_error should result in a one-liner. This is by design. I adapted the documentation of the functions and added the `omv_print` function.

**Comment by nrandon** [comment]
Hi I see the revert but not new omv_print function and associated omv_sysinfo_print_msg function  did I miss something ? @votdev

**Comment by votdev** [comment]
See https://github.com/openmediavault/openmediavault/commit/04e0f7af459e5ec149b7ded06e83fccb52f01b57.

**Comment by votdev** [comment]
> Hi I see the revert but no new `omv_print` function and associated `omv_sysinfo_print_msg` function (or equivalent), did I miss something ? @votdev

It does not make sense to print a multiline message to syslog, because of that all those methods will filter blanks and newlines.
