### ISSUE TITLE
User session not working with lastest stable iso (openmediavault_6.0.24-amd64.iso)

### ISSUE THREAD

**Issue by Knodd** [openmediavault/openmediavault#1368]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

When installing openmediavault using 6.0.24 iso I was not able to run a program that needed systemd (Jotta cli backup).
Followed this guide: [https://docs.jottacloud.com/en/articles/1436855-jottacloud-cli-for-linux-debian-packages](https://docs.jottacloud.com/en/articles/1436855-jottacloud-cli-for-linux-debian-packages) and when I got to `run_jottad` the error was "failed to connect to bus: no such file or directory"
logging in (both console and ssh) and running
`loginctl list-users` reported: "No users"
jotta-cli worked fine on omv5, and after last update it´s really not supposed to run as root, but creating new users and logging in did not help
I also updated with `apt-get update` and `apt-get upgrade` but this did not help

I had also tried to install omv 6 in an LXC container and did not have this problem with jotta there (but here I could not use ovm since there was no disks to mount and omv did not recognize root file system as a disk. BTW Turnkey file server can share root FS from LXC and it would be great if omv could do that too )

The LXC install was made installing omv with script from here [https://github.com/OpenMediaVault-Plugin-Developers/installScript](https://github.com/OpenMediaVault-Plugin-Developers/installScript) on top of a debian lxc template so I made a VM with Debian 11.4 and then installed openmediavault on top using the same script. I had no problems here and was about to start migrating disks and setting to the new VM when I stumbeld over the solution:
`apt-get reinstall libpam-systemd`
Then exit, log back in and problem solved!

**To Reproduce**

1. Install omv from stable iso (6.0.24)
2. Login (as root or as any other user you create with console or ssh)
3. Run `loginctl list-users` -> No users
Here we should see the user session listed

Steps to fix:
1. Run `apt-get reinstall libpam-systemd`
2. Run `exit` to log out
3. Log back in
4. Run `loginctl list-users` -> 1 user session
Now systemd works

To bypass the error:
1. Install Debian 11.4
2. Install openmediavault with script here: [https://github.com/OpenMediaVault-Plugin-Developers/installScript](https://github.com/OpenMediaVault-Plugin-Developers/installScript)
Here we have no problem, if you log in as root after install and run `loginctl list-users` -> 1 user session

**Expected behavior**

I expected user session to work like in omv5

**Screenshots**
After install from iso 
<img width="1071" alt="Screenshot 2022-08-03 at 20 34 26" src="https://user-images.githubusercontent.com/5361815/182692217-5b30e81d-8b9e-4265-936b-e5b749c59b21.png">

After `apt-get reinstall libpam-systemd` and logging out and back in with same user (root)
<img width="1071" alt="Screenshot 2022-08-03 at 21 24 36" src="https://user-images.githubusercontent.com/5361815/182692399-41deee1a-0fed-4c01-a92a-e4546f9b6531.png">

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: `Linux omv 5.18.0-0.bpo.1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.2-1~bpo11+1 (2022-06-14) x86_64 GNU/Linux`
- openmediavault version:
```
ii  openmediavault                   6.0.33-1                       all          openmediavault - The open network attached storage solution
ii  openmediavault-downloader        6.0.1                          all          OpenMediaVault downloader plugin
ii  openmediavault-filebrowser       6.0.2-1                        all          openmediavault File Browser plugin
ii  openmediavault-flashmemory       6.2                            all          folder2ram plugin for openmediavault
ii  openmediavault-keyring           1.0                            all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-locate            6.0                            all          locate plugin for OpenMediaVault.
ii  openmediavault-omvextrasorg      6.1.1                          all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-resetperms        6.0.2                          all          Reset Permissions
ii  openmediavault-sharerootfs       6.0-4                          all          openmediavault share root filesystem plugin
```
Both working and non-working installed in proxmox VM (same config)

**Client (please complete the following information):**

- Proxmox console in browser
- SSH session in MacOS terminal

**Additional context**

**Comment by votdev** [comment]
> BTW Turnkey file server can share root FS from LXC and it would be great if omv could do that too

Install the `openmediavault-sharerootfs` plugin to get this feature.

**Comment by Knodd** [comment]
> > BTW Turnkey file server can share root FS from LXC and it would be great if omv could do that too
> 
> Install the `openmediavault-sharerootfs` plugin to get this feature.

It didn’t work since root FS is not a disk it can’t be mounted as file system and the share can only be created from a file system.
I might have configured it wrong. Have you tested it?

**Comment by votdev** [comment]
> > > BTW Turnkey file server can share root FS from LXC and it would be great if omv could do that too
> > 
> > 
> > Install the `openmediavault-sharerootfs` plugin to get this feature.
> 
> It didn’t work since root FS is not a disk it can’t be mounted as file system and the share can only be created from a file system. I might have configured it wrong. Have you tested it?

OMV does not work in containers.

**Comment by votdev** [comment]
I was not able to reproduce the `libpam-systemd` problem in a fresh installation using the ISO in a VMWare setup.

**Comment by Knodd** [comment]
So running `loginctl list-users` works on a fresh iso-installation of 6.0.24 for you? I tested it 3 times to be sure before I reported it…

**Comment by Knodd** [comment]
> > > > BTW Turnkey file server can share root FS from LXC and it would be great if omv could do that too
> > > 
> > > 
> > > Install the `openmediavault-sharerootfs` plugin to get this feature.
> > 
> > 
> > It didn’t work since root FS is not a disk it can’t be mounted as file system and the share can only be created from a file system. I might have configured it wrong. Have you tested it?
> 
> OMV does not work in containers.

Would love it if it did, but honestly I think omv is worth the extra resources of a VM so I’ll stick with the VM 👍

**Comment by Knodd** [comment]
> > So running `loginctl list-users` works on a fresh iso-installation of 6.0.24 for you?
> 
> Yes

Ok, then it’s likely not a general problem with the installer image but more of an isolated issue caused by som quirk in my install process.
Guess the issue can be closed and if somebody else is unfortunate enough to have the same issue they’ll find the solution here.
