### ISSUE TITLE
Would support for IPFS (InterPlanetary File-System) protocol for media sharing be feasible for OMV?

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1370]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated with SMB protocol for use case "media sharing" due to protocol and performance issues on the various end user devices

**Describe the solution you'd like**
A new open source approach for peer-to-peer network support  is getting attractive.
IPFS has a new approach to file sharing targeting use case "media sharing" , details are explained [here](https://ipfs.tech/#how).
How about adding IPFS to OMV capabilities?

**Describe alternatives you've considered**
Old style SMB protocol

**Additional context**
Blog posts on [IPFS ](https://blog.ipfs.io/2022-08-01-ipfs-and-ffmpeg/)and [Phoronix ](https://www.phoronix.com/news/IPFS-FFmpeg-Open-Source-More) explain the reasoning & benefits quite well.

**Comment by ryecoaaron** [comment]
This doesn't belong in core OMV.  If someone desires it, they should write a plugin.

That said, I think IPFS and SMB are not trying to serve the same use cases.  I can almost guarantee that IPFS performance cannot be better than SMB on a local network.  If you are not referring to a local network, then you should not be using SMB.

**Comment by votdev** [comment]
I do not see any sense in this, but OMV supports plugins, so if someone wants it, then this should be easily possible as plugin.
