### ISSUE TITLE
Changing one global value of Photoprism plugin

### ISSUE THREAD

**Issue by gaston-arg** [openmediavault/openmediavault#1372]
**Is your feature request related to a problem? Please describe.**
 It's currently not possible to set the PHOTOPRISM_SITE_URL value of Photoprism, which allows to configure the website URL. As a consequence, the sharing link of an album redirects to the default location, which is http://localhost, making it impossible to share this link with the outside world. 

**Describe the solution you'd like**
To enable the change of this value. 

**Additional context**
This feature is part of the official Photoprism doc: https://docs.photoprism.app/getting-started/config-options/

**Comment by votdev** [comment]
Use the [OMV_PHOTOPRISM_APP_CONTAINER_START_OPTIONS](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-photoprism/srv/salt/omv/deploy/photoprism/files/container-photoprism-app.service.j2) [environment variable](https://openmediavault.readthedocs.io/en/stable/various/advset.html#environmental-variables) to append additional env vars to the container.

Use the following commands:
```
# omv-env set -- OMV_PHOTOPRISM_APP_CONTAINER_START_OPTIONS "-e PHOTOPRISM_SITE_URL=https://foo.bar"
```
