### ISSUE TITLE
Standby scheduled task still uses hibernate command despite configuration

### ISSUE THREAD

**Issue by auanasgheps** [openmediavault/openmediavault#1373]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**
This is a followup to #1330.

I have configured the new option in System > Power Management to Suspend. 
I enabled the "standby" Power Management job, but it issued a hibernate command.

This action has crashed my server, because there's not enough space in my /swap partition to hibernate. 

I'm away and I cannot recover it, but I'm sure this is what has happened, because is the same behaviour before I opened #1330. 

Since my system has crashed, I managed to replicate the issue in a VM. The screenshots below are from a VM running OMV 6.0.34, whilst my system was running 6.0.33.

**To Reproduce**

1. Go to "System > Power > Settings"
2. Set "Standby Mode" to "Suspend"
3. Go to "System > Power > Scheduled Tasks"
4. Enable an existing Standby job or create a new one
5. Wait for it to be executed
6. See hibernation being executed.

**Expected behavior**

Suspend should be issued instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/20586878/184506539-3503696b-54a2-43d6-96dd-a4de727df5e2.png)
![image](https://user-images.githubusercontent.com/20586878/184506547-f1da69a7-ac4b-4409-9c44-c75a652e9458.png)
The configuration looks correct, but...
![image](https://user-images.githubusercontent.com/20586878/184506529-3b064d0d-d076-4272-a355-c4bd6b132176.png)

**Reference to Forum**
N/A

**openmediavault Server (please complete the following information):**

- OS version: currently I can't check the real hardware.
- openmediavault version: 6.0.33-1 real hardware, 6.0.34 in VM

**Client (please complete the following information):**

N/A

**Additional context**

If I issue a manual command with `systemctl suspend`, the VM actually prints supend messages, see below.
That's how I suspended my system when I noticed the bug early on #1330.

```
Aug 13 20:40:16 omv6 systemd[1]: Reached target Sleep.
Aug 13 20:40:16 omv6 systemd[1]: Starting Suspend...
Aug 13 20:40:16 omv6 systemd-sleep[2924]: Suspending system...
Aug 13 20:40:16 omv6 kernel: [  446.971861] PM: suspend entry (s2idle)
```

**Comment by votdev** [comment]
Please post the output of the file `/etc/cron.d/openmediavault-powermngmt`. If i apply the settings as mentioned above and create a new scheduled task, the file looks like
```
# cat /etc/cron.d/openmediavault-powermngmt
# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
# m h dom mon dow user    command
52 7 * * * root systemctl suspend >/dev/null 2>&1
```

Please delete and re-create existing scheduled jobs to apply the new power management settings.

**Comment by votdev** [comment]
Added `Please note, existing tasks in 'System | Power Management | Scheduled Tasks' will not be migrated and may behave unexpectedly as they execute different commands than configured now. Delete and recreate them to make sure they are doing the right thing.` to the changelog.

**Comment by auanasgheps** [comment]
Nope, still creates a hibernate task.

In fact in the VM I didn't had a stanbdy job, so I created a new one and replicated the issue. 

![image](https://user-images.githubusercontent.com/20586878/184627343-944ff4ce-dedc-417d-99e9-4724e8cdc0cc.png)
