### ISSUE TITLE
 Please support OneDriveGUI(alreday have a official solution

### ISSUE THREAD

**Issue by penwong** [openmediavault/openmediavault#1380]
**Is your feature request related to a problem? Please describe.**
About bpozdena/OneDriveGUI, A simple GUI for OneDrive Linux client, with multi-account support

here is the link of it, https://github.com/bpozdena/OneDriveGUI

i'm new to linux /omv, and i believe this feature will help people like me.
thanks for reading, have a nice day

**Comment by votdev** [comment]
This seems to be a desktop GUI application which is based on QT and no web UI.
