### ISSUE TITLE
Incorrect color for device usage in file systems tab

### ISSUE THREAD

**Issue by ricardoj-br** [openmediavault/openmediavault#1384]
I have two BTRFS devices attached to OMV.

![Demari_OMV_FS_Usage-01](https://user-images.githubusercontent.com/20463353/188456207-038e0c5f-e260-4f5a-b443-7d2a8f43698f.png)

![Demari_OMV_FS_Usage-02](https://user-images.githubusercontent.com/20463353/188457067-1596d30d-5c94-4dc2-9d80-b3e81894660b.png)

On file systems tab the usage is correct but device /dev/sdc has "red" color with 10% usage.

**Comment by votdev** [comment]
Can you please post the output of the `omv-rpc -u admin 'FileSystemMgmt' 'getList' '{"start":0,"limit":-1}' | jq` CLI command?

**Comment by votdev** [comment]
Please also post the output of `df -PT /dev/sdc`.

**Comment by ricardoj-br** [comment]
Hi Volker!

Thank you for your reply.

Regards,

Ricardo Jorge

===============================================

Can you please post the output of the omv-rpc -u admin 'FileSystemMgmt'
'getList' '{"start":0,"limit":-1}' | jq CLI command?

# omv-rpc -u admin 'FileSystemMgmt' 'getList' '{"start":0,"limit":-1}' | jq
{
  "total": 2,
  "data": [
    {
      "devicename": "sdb",
      "devicefile":
"/dev/disk/by-uuid/9bb0066f-4738-4de8-a781-cf5b4b544295",
      "predictabledevicefile":
"/dev/disk/by-uuid/9bb0066f-4738-4de8-a781-cf5b4b544295",
      "canonicaldevicefile": "/dev/sdb",
      "parentdevicefile": "/dev/sdb",
      "devlinks": [
        "/dev/disk/by-id/ata-Hitachi_HUA723030ALA641_YVG4N0PA",
        "/dev/disk/by-id/wwn-0x5000cca234c21ca5",
        "/dev/disk/by-label/NAS02",
        "/dev/disk/by-path/pci-0000:00:17.0-ata-2",
        "/dev/disk/by-path/pci-0000:00:17.0-ata-2.0",
        "/dev/disk/by-uuid/9bb0066f-4738-4de8-a781-cf5b4b544295"
      ],
      "uuid": "9bb0066f-4738-4de8-a781-cf5b4b544295",
      "label": "NAS02",
      "type": "btrfs",
      "blocks": "2930266584",
      "mounted": true,
      "mountpoint": "/srv/dev-disk-by-label-NAS02",
      "used": "741.90 GiB",
      "available": "2200553918464",
      "size": "3000592982016",
      "percentage": "26",
      "description": "/dev/sdb [BTRFS, 741.90 GiB (26%) used, 2.00 TiB
available]",
      "propposixacl": true,
      "propquota": false,
      "propresize": false,
      "propfstab": true,
      "propcompress": true,
      "propautodefrag": true,
      "hasmultipledevices": false,
      "devicefiles": [
        "/dev/sdb"
      ],
      "comment": "",
      "_readonly": false,
      "_used": true,
      "propreadonly": false,
      "usagewarnthreshold": 85,
      "mountopts":
"compress=zstd:3,space_cache,autodefrag,noatime,defaults,nofail",
      "status": 1
    },
    {
      "devicename": "sdc",
      "devicefile":
"/dev/disk/by-uuid/62ee0aa4-9b09-43ae-865c-266ea05c5c50",
      "predictabledevicefile":
"/dev/disk/by-uuid/62ee0aa4-9b09-43ae-865c-266ea05c5c50",
      "canonicaldevicefile": "/dev/sdc",
      "parentdevicefile": "/dev/sdc",
      "devlinks": [
        "/dev/disk/by-id/ata-Hitachi_HUA723030ALA641_YHHTP7BC",
        "/dev/disk/by-id/wwn-0x5000cca225d95022",
        "/dev/disk/by-label/NAS01",
        "/dev/disk/by-path/pci-0000:00:17.0-ata-3",
        "/dev/disk/by-path/pci-0000:00:17.0-ata-3.0",
        "/dev/disk/by-uuid/62ee0aa4-9b09-43ae-865c-266ea05c5c50"
      ],
      "uuid": "62ee0aa4-9b09-43ae-865c-266ea05c5c50",
      "label": "NAS01",
      "type": "btrfs",
      "blocks": "2930266584",
      "mounted": true,
      "mountpoint": "/srv/dev-disk-by-label-NAS01",
      "used": "274.59 GiB",
      "available": "2701967736832",
      "size": "3000592982016",
      "percentage": "9",
      "description": "/dev/sdc [BTRFS, 274.59 GiB (9%) used, 2.45 TiB
available]",
      "propposixacl": true,
      "propquota": false,
      "propresize": false,
      "propfstab": true,
      "propcompress": true,
      "propautodefrag": true,
      "hasmultipledevices": false,
      "devicefiles": [
        "/dev/sdc"
      ],
      "comment": "",
      "_readonly": false,
      "_used": true,
      "propreadonly": false,
      "usagewarnthreshold": 85,
      "mountopts":
"compress=zstd:3,space_cache,autodefrag,noatime,defaults,nofail",
      "status": 1
    }
  ]
}


Please also post the output of df -PT /dev/sdc.

# df -PT /dev/sdc
Sist. Arq.     Tipo  Blocos de 1024     Usado Disponível Capacid. Montado em
/dev/sdc       btrfs     2930266584 288459592 2639163608      10%
/root/Dados

# df -PT /dev/sdb
Sist. Arq.     Tipo  Blocos de 1024     Usado Disponível Capacid. Montado em
/dev/sdb       btrfs     2930266584 778467912 2149501896      27%
/export/VMS
===============================================

Em seg., 5 de set. de 2022 às 12:27, Volker Theile ***@***.***>
escreveu:

**Comment by votdev** [comment]
WIll be fixed in `openmediavault 6.0.39`.
