### ISSUE TITLE
Samba/CIFS: Wrong autogenerated config fails inherit permissions

### ISSUE THREAD

**Issue by ovear** [openmediavault/openmediavault#1385]
**Describe the bug**

OMV generated wrong samba config file which caused weird(unintentional) action.

When enable "inherit permissions" in samba share config, it doesn't work as expceted. The newly created/renamed files are not honer parent directory permission.

**To Reproduce**

1. Install omv 6 latest version
2. Create a new user
3. Create share directory with permission like (2)750
4. Change share directory's owner to new user(for test purpose)
5. Create samba share directory with "inherit permissions" enabled
6. Create file use "right click - new file" - file permission 640 which is good, and honored parent directory permission
7. Rename this file or copy & paste a new file from pc - file permission fixed to 660.
8. Samba "dos permission store" also broke, files are not able to mark as archived(also samba default action)

**Expected behavior**

"inherit permissions" works as expcted

**Potential solution**

After test a few hours, i think this may caused by upstream(samba) itself and misconfig. I installed latest samba pure new Linux system manually with config generated by OMV, it shows same action.

There are 2 solution to fix this currently i found through tons of tests.

1. Enable "store dos attributes" when enable "inherit permissions" which is also default behavior of samba.
2. Disable "map archive" when enable "inherit permissions".

I am not sure there is any other solustion, and it seems nearly no discussion on the Internet(may be wrong keywords). 

**openmediavault Server (please complete the following information):**
```
- OS version: Linux OMV 5.18.0-0.deb11.3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.14-1~bpo11+1 (2022-07-28) x86_64 GNU/Linux
- openmediavault version: openmediavault 6.0.38-1
```
**Client (please complete the following information):**

- Device: PC
- OS: Both windows 10/11 and Arch Linux

**Comment by votdev** [comment]
What file system type are you using to host your shared folders? EXT4, XFS, JFS, BTRFS, FAT16 or NTFS?

**Comment by ovear** [comment]
> What file system type are you using to host your shared folders? EXT4, XFS, JFS, BTRFS, FAT16 or NTFS?

I am using EXT4.

**Comment by ovear** [comment]
Hi,
Does this issue fixed now?
