### ISSUE TITLE
smbd log spam every 10 seconds

### ISSUE THREAD

**Issue by ET-Bent** [openmediavault/openmediavault#139]
When using Samba logging set via OMVs interface the syslog is spammed every 10 seconds:

```SMB/CIFS -> Settings -> Advanced Settings```

![selection_063](https://user-images.githubusercontent.com/5788982/42873354-19137e20-8a7f-11e8-943b-24838e647258.jpg)

#### Error:

```bash
Jul 18 11:17:01 nas smbd[3085]: [2018/07/18 11:17:01.455444,  1] ../source3/printing/printer_list.c:234(printer_list_get_last_refresh)
Jul 18 11:17:01 nas smbd[3085]:   Failed to fetch record!
Jul 18 11:17:01 nas smbd[3085]: [2018/07/18 11:17:01.455503,  1] ../source3/smbd/server_reload.c:69(delete_and_reload_printers)
Jul 18 11:17:01 nas smbd[3085]:   pcap cache not loaded
Jul 18 11:17:01 nas smbd[3086]: [2018/07/18 11:17:01.564618,  1] ../lib/param/loadparm.c:1729(lpcfg_do_global_parameter)
Jul 18 11:17:01 nas smbd[3086]:   WARNING: The "syslog" option is deprecated
```

**System:**
```
OMV 4.1.8.2-1 (Arrakis)
Linux 4.16.0-0.bpo.2-amd64 #1 SMP Debian 4.16.16-2~bpo9+1 (2018-06-26) x86_64 GNU/Linux
Debian 9.5 Stretch
```

**Comment by votdev** [comment]
What do you expect if you enable logging? This is normal behaviour. If you won't have  logging enabled select None.

**Comment by ET-Bent** [comment]
* I was mostly referencing to this:

```bash
Jul 18 11:17:01 nas smbd[3086]:   WARNING: The "syslog" option is deprecated
```

which is caused by using smbd's deprecated logging. This is what is being spammed every 10s. I should have been more precise. Of course the rest of the logging is to be expected.

**Comment by ET-Bent** [comment]
`OMV 4.1.8.2-1 (Arrakis)` @votdev

**Comment by ET-Bent** [comment]
thanks for the quick response and fix; perfect I appreciate that! :+1: @votdev

**Comment by ryecoaaron** [comment]
This fix did not remove the 'syslog only = X' setting.

**Comment by votdev** [comment]
> This fix did not remove the 'syslog only = X' setting.

Is this deprecated, too?

**Comment by votdev** [comment]
Deprecated means that it will be removed in a later version. So there is no action required for OMV4, but OMV5 should be adapted.

**Comment by ryecoaaron** [comment]
Yes, I know that but you removed "syslog =" even though it was deprecated.  So, I figured you might want to remove this option as well.

**Comment by votdev** [comment]
If 46a8daae8fe7a22023575332d6c2a2e75f10081c works well we can backport it to OMV4 later. For the moment i don't want to change critical issues.

**Comment by ryecoaaron** [comment]
I guess if someone wants to log to a file, the syslog only option is causing an issue - https://forum.openmediavault.org/index.php/Thread/24666-OMV-SMB-CIFS-Redirect-LOGs-to-var-log-samba/

**Comment by ricardoj-br** [comment]
Option ( syslog only = yes ) must be removed from /etc/samba/smb.conf so the LOGs can be redirected to the path configured in ( log file = path ).

Regards,

Ricardo Jorge
