### ISSUE TITLE
SMB - improve performance for Mac OS "file copy" on server by setting "fruit:copyfile = yes"

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1393]
Mac OS seems to require an additional setting to use "file copy" on server.
See https://wiki.samba.org/index.php/Server-Side_Copy#Introduction 
"Note - not enabled for OS X (Macs) unless server Samba includes vfs_fruit module and fruit:copyfile = yes in smb.conf."

**Describe the solution you'd like**
add setting "fruit:copyfile = yes " to  /etc/samba/smb.conf

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by HannesJo0139** [comment]
I wonder if this really works for you? I also noticed this doc long time ago and added `fruit:copyfile = yes` to extra options field. Still MacOs (only) is copying files via client. Only when I do a Cut & Paste it is done server-side.

**Comment by mi-hol** [comment]
> I wonder if this really works for you?

I can't test because I own no Apple device.

> Only when I do a Cut & Paste it is done server-side.

well then it works as specified, there was no mention that this option applies to all use cases.

**Comment by votdev** [comment]
> I wonder if this really works for you?

I can not test that because i have no such Apple hardware. I only rely on the information the community and Google provides.

**Comment by HannesJo0139** [comment]
> > Only when I do a Cut & Paste it is done server-side.
> 
> well then it works as specified, there was no mention that this option applies to all use cases.

Yeah that may be true. Still a bit weird, on Windows and Linux Clients you can Copy&Paste, on MacOs you have to Cut&Paste.  🙄

**Comment by mi-hol** [comment]
> Still a bit weird, on Windows and Linux Clients you can Copy&Paste, on MacOs you have to Cut&Paste.

but it would explain the reason for not making it a default

**Comment by notsle** [comment]
I know this is old.  but adding to extra options on a SMB share solves this...


```
fruit:copyfile = yes
vfs objects = fruit streams_xattr  
fruit:metadata = stream
fruit:model = MacSamba
fruit:veto_appledouble = no
fruit:nfs_aces = no
fruit:wipe_intentionally_left_blank_rfork = yes 
fruit:delete_empty_adfiles = yes 
fruit:posix_rename = yes 
```

**Comment by votdev** [comment]
> I know this is old. Adding the following to "extra options" on a SMB share solves this...
> 
> copyfile is important but the other options are recommended for Mac Clients [wiki.samba.org/index.php/Configure_Samba_to_Work_Better_with_Mac_OS_X](https://wiki.samba.org/index.php/Configure_Samba_to_Work_Better_with_Mac_OS_X)
> 
> ```
> vfs objects = fruit streams_xattr  
> fruit:metadata = stream
> fruit:model = MacSamba
> fruit:veto_appledouble = no
> fruit:nfs_aces = no
> fruit:wipe_intentionally_left_blank_rfork = yes 
> fruit:delete_empty_adfiles = yes 
> fruit:posix_rename = yes 
> fruit:copyfile = yes
> ```

In OMV7 these options do nt need to be set via `Extra options`. OMV already deploys the Samba config with the recommended fruit configs.
