### ISSUE TITLE
openmediavault-check_ssl_cert_expiry after update to 6.0.42 

### ISSUE THREAD

**Issue by EVOTk** [openmediavault/openmediavault#1397]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**
after update to 6.0.42, I get an error email:
```
/etc/cron.daily/openmediavault-check_ssl_cert_expiry:
Can't open /etc/ssl/certs/openmediavault-*.crt for reading, No such file or directory
140362095797568:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('/etc/ssl/certs/openmediavault-*.crt','r')
140362095797568:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
unable to load certificate
```

**To Reproduce**
1. Update to 6.0.42 

**Expected behavior**
I do not use a certificate, so I would like not to receive an error message

**Screenshots**
![image](https://user-images.githubusercontent.com/45015615/192704774-727023cb-8409-4c72-af3d-55de68072115.png)

![image](https://user-images.githubusercontent.com/45015615/192705546-1026ded5-fcf6-4e98-96c6-336547f61594.png)

![image](https://user-images.githubusercontent.com/45015615/192705582-af683358-85dd-4fb0-aa89-0ab5dfccbd0e.png)

![image](https://user-images.githubusercontent.com/45015615/192705602-2a4d2553-779f-4f33-8321-9b7ca0809a0d.png)

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: `Linux citrouille 5.18.0-0.deb11.4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1~bpo11+1 (2022-08-12) x86_64 GNU/Linux`
- openmediavault version: `6.0.42-1`

**Client (please complete the following information):**

- Device: PC
- OS: Windows 10
- Browser: Firefox
- Version: 105

**Additional context**
X

Thx

**Comment by votdev** [comment]
Fixed with e60742ffceb4b4dfe2f65913a74b02b755bc8578.
