### ISSUE TITLE
 Updates not visible in WebUI

### ISSUE THREAD

**Issue by sebeksd** [openmediavault/openmediavault#1398]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

My report did not have any response so reporting here.

**Describe the bug**
Hi, I have 3x OMV6 servers, two of them were updated from OMV5.

On one of them (one that was updated from OMV5 last) is not showing updates on WEB, if Im correct it was showing them at the beginning and stopped after some update (recent one, 1-2 months ago).

Updates are visible with sudo apt update/ list --upgradable.

This still persists through 2-3 updates (with machine restarts). This server has nothing special configured (only docker, backup plugin).

I left newest updates without installing them so if there was something to check on this server to have a test case.

**To Reproduce**
1. Press check updates button on WebUI
2. List is empty
3. do apt update and apt list --upgradable in terminal
4. Updates are present (containing updates for OMV6 and/or plugins and/or kernel)

**Expected behavior**
List should show available updates and allow to install them.

**Screenshots**
![Obraz ze schowka (26)](https://user-images.githubusercontent.com/18705953/192982293-415636d8-b764-4607-81c1-9c9b75426d35.png)
![Obraz ze schowka (59)](https://user-images.githubusercontent.com/18705953/192982298-2be6010f-be5b-4cbe-8e04-4e5947da9262.jpg)
![Obraz ze schowka (23)](https://user-images.githubusercontent.com/18705953/192982302-c3463de3-f3a6-4844-a19b-083a4855a025.png)
![image](https://user-images.githubusercontent.com/18705953/192982389-840e4ed4-4386-4e4e-acee-f1df030821bc.png)

**Reference to Forum**
https://forum.openmediavault.org/index.php?thread/44704-updates-not-visible-in-webui/

**openmediavault Server (please complete the following information):**
- OS version: Linux NEXTSRV04 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
- openmediavault version: 
ii  openmediavault                    6.0.40-2                       all          openmediavault - The open network attached storage solution
ii  openmediavault-backup             6.0.8                          all          backup plugin for OpenMediaVault.
ii  openmediavault-keyring            1.0                            all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg       6.1.1                          all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-remotemount        6.0.2                          all          Remote mount plugin for OpenMediaVault.
ii  openmediavault-sharerootfs        6.0-4                          all          openmediavault share root filesystem plugin

**Client (please complete the following information):**
- Device: PC
- OS: Windows 10
- Browser Chrome
- Version 105

**Comment by votdev** [comment]
Could you please run the command `ls -alh /var/lib/openmediavault/apt/` and post the output here?

**Comment by sebeksd** [comment]
Sure:
```
ls -alh /var/lib/openmediavault/apt/

razem 72K
drwxr-xr-x 2 root root 4,0K 2021-05-28  .
drwxr-xr-x 7 root root 4,0K 09-24 10:18 ..
-rw-r--r-- 1 root root  59K 06-28 11:21 pluginsindex.json
-rw-r--r-- 1 root root    2 06-28 11:21 upgradeindex.json
```

```
cat /var/lib/openmediavault/apt/upgradeindex.json
[]
```

```
sudo apt list --upgradable
Listing... Gotowe
openmediavault-sharerootfs/shaitan,shaitan 6.0.2-1 all [upgradable from: 6.0-4]
openmediavault/shaitan,shaitan 6.0.42-2 all [upgradable from: 6.0.40-2]
```
![image](https://user-images.githubusercontent.com/18705953/193220768-1921214d-cd27-44a9-9010-5810bbb550a2.png)

**Comment by votdev** [comment]
What happens when you run 
```
$ omv-mkaptidx
$ ls -alh /var/lib/openmediavault/apt/
$ cat /var/lib/openmediavault/apt/upgradeindex.json
```

**Comment by sebeksd** [comment]
```
root@NEXTSRV04:~ # omv-mkaptidx
root@NEXTSRV04:~ # ls -alh /var/lib/openmediavault/apt/
razem 72K
drwxr-xr-x 2 root root 4,0K 2021-05-28  .
drwxr-xr-x 7 root root 4,0K 09-24 10:18 ..
-rw-r--r-- 1 root root  59K 06-28 11:21 pluginsindex.json
-rw-r--r-- 1 root root    2 06-28 11:21 upgradeindex.json
root@NEXTSRV04:~ # cat /var/lib/openmediavault/apt/upgradeindex.json
[]root@NEXTSRV04:~ #

```

**Comment by votdev** [comment]
Could you please run the following Python code and post everything:
```
root@omv6box:/home/vagrant# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import apt
>>> cache = apt.cache.Cache()
>>> cache.upgrade(True)
>>> print(len(cache.get_changes()))
>>> pkgs = [pkg.name for pkg in cache.get_changes()]
>>> print(pkgs)
```

**Comment by sebeksd** [comment]
```
root@NEXTSRV04:~ # python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import apt
>>> cache = apt.cache.Cache()
>>> cache.upgrade(True)
>>> print(len(cache.get_changes()))
2
>>> pkgs = [pkg.name for pkg in cache.get_changes()]
>>> print(pkgs)
['openmediavault', 'openmediavault-sharerootfs']
>>>

```

**Comment by votdev** [comment]
What about that?
```
root@omv6box:/home/vagrant# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import apt
>>> cache = apt.cache.Cache()
>>> cache.upgrade(True)
>>> print(len(cache.get_changes()))
>>> pkgs = [{'name': pkg.name, 'candidate': pkg.candidate} for pkg in cache.get_changes()]
>>> print(pkgs)
```

**Comment by sebeksd** [comment]
```
root@NEXTSRV04:~ # python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import apt
>>> cache = apt.cache.Cache()
>>> cache.upgrade(True)
>>> print(len(cache.get_changes()))
2
>>> pkgs = [{'name': pkg.name, 'candidate': pkg.candidate} for pkg in cache.get_changes()]
>>> print(pkgs)
[{'name': 'openmediavault', 'candidate': <Version: package:'openmediavault' version:'6.0.42-2'>}, {'name': 'openmediavault-sharerootfs', 'candidate': <Version: package:'openmediavault-sharerootfs' version:'6.0.2-1'>}]
>>>
[1]+  Zatrzymano              python3
root@NEXTSRV04:~ # apt-cache policy openmediavault-sharerootfs
openmediavault-sharerootfs:
  Zainstalowana: 6.0-4
  Kandydująca:   6.0.2-1
  Tabela wersji:
     6.0.2-1 500
        500 http://packages.openmediavault.org/public shaitan/main amd64 Packages
        500 http://openmediavault.github.io/packages shaitan/main amd64 Packages
 *** 6.0-4 100
        100 /var/lib/dpkg/status

```

**Comment by votdev** [comment]
Is this env variable customized?
```
$ omv-env get OMV_APT_UPGRADE_INDEX_FILE
```

**Comment by sebeksd** [comment]
```
root@NEXTSRV04:~ # omv-env get OMV_APT_UPGRADE_INDEX_FILE
root@NEXTSRV04:~ #

```

**Comment by ryecoaaron** [comment]
@votdev there was no output from omv-mkaptidx.  So, it is still a bash script from the upgrade which evidently didn't go well.

sudo dpkg-divert --remove --rename /usr/sbin/omv-mkaptidx

**Comment by sebeksd** [comment]
```
root@NEXTSRV04:~ # rm -rf omv-mkaptidx
root@NEXTSRV04:~ # wget https://raw.githubusercontent.com/votdev/openmediavault/issue_1398/deb/openmediavault/usr/sbin/omv-mkaptidx
--2022-09-30 12:49:55--  https://raw.githubusercontent.com/votdev/openmediavault/issue_1398/deb/openmediavault/usr/sbin/omv-mkaptidx
Translacja raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Łączenie się z raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 200 OK
Długość: 9418 (9,2K) [text/plain]
Zapis do: `omv-mkaptidx'

omv-mkaptidx                             100%[================================================================================>]   9,20K  --.-KB/s     w 0s

2022-09-30 12:49:55 (51,9 MB/s) - zapisano `omv-mkaptidx' [9418/9418]

root@NEXTSRV04:~ # chmod 750 ./omv-mkaptidx
root@NEXTSRV04:~ # ./omv-mkaptidx --verbose
Creating index of upgradeable packages ...
Added package 'openmediavault'
Added package 'openmediavault-sharerootfs'
Index file '/var/lib/openmediavault/apt/upgradeindex.json' successfully updated.
Creating index of plugins ...
Added package 'openmediavault-anacron'
Added package 'openmediavault-apttool'
Added package 'openmediavault-autoshutdown'
Added package 'openmediavault-backup'
Added package 'openmediavault-borgbackup'
Added package 'openmediavault-clamav'
Added package 'openmediavault-compose'
Added package 'openmediavault-cputemp'
Added package 'openmediavault-diskstats'
Added package 'openmediavault-downloader'
Added package 'openmediavault-fail2ban'
Added package 'openmediavault-filebrowser'
Added package 'openmediavault-flashmemory'
Added package 'openmediavault-forkeddaapd'
Added package 'openmediavault-kernel'
Added package 'openmediavault-kvm'
Added package 'openmediavault-locate'
Added package 'openmediavault-luksencryption'
Added package 'openmediavault-lvm2'
Added package 'openmediavault-mergerfs'
Added package 'openmediavault-minidlna'
Added package 'openmediavault-nut'
Added package 'openmediavault-omvextrasorg'
Added package 'openmediavault-onedrive'
Added package 'openmediavault-owntone'
Added package 'openmediavault-photoprism'
Added package 'openmediavault-remotemount'
Added package 'openmediavault-resetperms'
Added package 'openmediavault-rsnapshot'
Added package 'openmediavault-s3'
Added package 'openmediavault-sftp'
Added package 'openmediavault-shairport'
Added package 'openmediavault-sharerootfs'
Added package 'openmediavault-snapraid'
Added package 'openmediavault-snmp'
Added package 'openmediavault-symlinks'
Added package 'openmediavault-tftp'
Added package 'openmediavault-tgt'
Added package 'openmediavault-usbbackup'
Added package 'openmediavault-wakealarm'
Added package 'openmediavault-wetty'
Added package 'openmediavault-wireguard'
Added package 'openmediavault-wol'
Added package 'openmediavault-zfs'
Index file '/var/lib/openmediavault/apt/pluginsindex.json' successfully updated.
root@NEXTSRV04:~ #

```

**Comment by votdev** [comment]
Please do as @ryecoaaron suggested.

**Comment by sebeksd** [comment]
```
root@NEXTSRV04:~ # sudo dpkg-divert --remove --rename /usr/sbin/omv-mkaptidx
Usuwanie "lokalne ominięcie /usr/sbin/omv-mkaptidx do /usr/sbin/omv-mkaptidx.real"
dpkg-divert: błąd: zmiana nazwy oznacza nadpisanie "/usr/sbin/omv-mkaptidx"
  innym plikiem "/usr/sbin/omv-mkaptidx.real", co nie jest dozwolone
root@NEXTSRV04:~ #
```
Error translation:
error: changing name will overwrite "/usr/sbin/omv-mkaptidx" with different file "/usr/sbin/omv-mkaptidx.real" which is not allowed

**Comment by votdev** [comment]
Use `sudo dpkg-divert --remove /usr/sbin/omv-mkaptidx`

**Comment by sebeksd** [comment]
```
root@NEXTSRV04:~ # sudo dpkg-divert --remove /usr/sbin/omv-mkaptidx
dpkg-divert: ostrzeżenie: proszę jawnie podać --no-rename, --rename stanie się domyślne w 1.20.x
Brak ominięcia "dowolne ominięcie /usr/sbin/omv-mkaptidx", nic nie usunięto.
```
warning: please explicitly use --no-rename 

```
root@NEXTSRV04:~ # sudo dpkg-divert --remove --no-rename /usr/sbin/omv-mkaptidx
Brak ominięcia "dowolne ominięcie /usr/sbin/omv-mkaptidx", nic nie usunięto.
```
This one is little bit strange in Polish but will try to translate it:
No bypass "any bypass /usr/sbin/omv-mkaptidx", nothing was removed

**Comment by ryecoaaron** [comment]
He told you how to fix a few posts up.  The post with the wget command to install a new copy of omv-mkaptidx.

**Comment by sebeksd** [comment]
I did that, and after that updates appeared in WebUI (look at screenshots). Then votdev said that I should also do what you proposed:
> Please do as @ryecoaaron suggested.
So I was trying to do that to, without a success.

**Comment by ryecoaaron** [comment]
I misread where you were at.  Hence why I deleted my post.

There is nothing for you to do.  The dpkg-divert command had nothing to do.  This isn't a problem.  Are you still having issues using OMV?  If not, you should be good to go.

**Comment by sebeksd** [comment]
Thank you, I will check it further tomorrow. (right now I have no access to the server)

**Comment by sebeksd** [comment]
Working correctly after when new update was available :) Thank you.
![image](https://user-images.githubusercontent.com/18705953/194746582-d0bccf9a-16a8-4090-a737-8741478cd452.png)
