### ISSUE TITLE
Add some helpful basic files to the repo

### ISSUE THREAD

**Issue by tooomm** [openmediavault/openmediavault#140]
See https://github.com/openmediavault/openmediavault/community

Examples are:
- [ ] missing contributing file
https://openmediavault.readthedocs.io/en/latest/development/contribute.html
- [ ] missing license, should be GPLv3
https://www.openmediavault.org/licensing.html

**Comment by ryecoaaron** [comment]
Licenses are here - https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/var/www/openmediavault/licenses

**Comment by votdev** [comment]
Licenses are clearly listed for all packages in debian/copyright.
