### ISSUE TITLE
BTRFS filesystem is missing

### ISSUE THREAD

**Issue by dontobi** [openmediavault/openmediavault#1408]
**Describe the bug**
I was told by OMV that I should restart my system. The system was running for over 5 weeks at this point. I decided to reboot and subsequently found that the file system widget in the OMV Dashboard was not displaying any data. I then looked in the File System menu item and found that my btrfs file system was showing as missing. I checked to see if the btrfs file system was mounted correctly and found that everything was fine at the system level. All files and folders were present, could be read and I could write and delete files/folders.

I therefore assume a bug from OMV and therefore decided to write this issue (without instruction from a moderator).

**To Reproduce**
1. Open the OMV Dashboard and activate the file system widget. No data is displayed.
2. Open the File System menu item. The BTRFS file system is displayed as "Missing".

**Expected behavior**
Before the reboot, the widget was displayed correctly in the dashboard and also the list under the File System menu item.

**Screenshots**
![image](https://user-images.githubusercontent.com/19261667/196603895-3c97de04-8f92-4aa7-93e5-cd58784437d6.png)
![image](https://user-images.githubusercontent.com/19261667/196603978-51a7d321-a94e-4516-8a92-832efcf2c09d.png)
![image](https://user-images.githubusercontent.com/19261667/196604067-16350a26-5872-41f2-98ea-ecc5e841eff2.png)

**Command Line Outputs**
```
root@raspberrypi4:~# btrfs fi show
Label: none  uuid: 2d5c6bf1-2735-4d1f-a118-d3332a0a80cd
        Total devices 2 FS bytes used 2.94TiB
        devid    1 size 3.64TiB used 1.61TiB path /dev/sdb
        devid    2 size 3.64TiB used 1.61TiB path /dev/sdc
```
```
root@raspberrypi4:~# blkid
/dev/mmcblk0p1: LABEL_FATBOOT="boot" LABEL="boot" UUID="BF72-A655" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="1d0b061c-01"
/dev/mmcblk0p2: UUID="3b48b212-7df7-40ab-9420-35393c1cb4eb" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="1d0b061c-02"
/dev/sda1: LABEL="USBDrive" BLOCK_SIZE="512" UUID="94225562225549FE" TYPE="ntfs" PARTUUID="3961d35f-01"
/dev/sdb: UUID="2d5c6bf1-2735-4d1f-a118-d3332a0a80cd" UUID_SUB="3a167ae9-94d3-4337-b029-7d5c9bffbc09" BLOCK_SIZE="4096" TYPE="btrfs"
/dev/sdc: UUID="2d5c6bf1-2735-4d1f-a118-d3332a0a80cd" UUID_SUB="61d60201-3a7f-4814-9046-4207052aacda" BLOCK_SIZE="4096" TYPE="btrfs"
```
```
root@raspberrypi4:~# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    1 119.3G  0 disk 
└─sda1        8:1    1 119.2G  0 part /srv/dev-disk-by-uuid-94225562225549FE
sdb           8:16   0   3.6T  0 disk /srv/dev-disk-by-id-usb-ST4000DM_000-1F2168_SSI7632000000001-0-0
sdc           8:32   0   3.6T  0 disk 
mmcblk0     179:0    0  56.4G  0 disk 
├─mmcblk0p1 179:1    0   256M  0 part /boot
└─mmcblk0p2 179:2    0  56.2G  0 part /
```
```
root@raspberrypi4:~# cat /etc/fstab
proc            /proc           proc    defaults          0       0
PARTUUID=1d0b061c-01  /boot           vfat    defaults          0       2
PARTUUID=1d0b061c-02            /       ext4    noatime,nodiratime,defaults     0 1
# >>> [openmediavault]
/dev/disk/by-id/usb-ST4000DM_000-1F2168_SSI7632000000001-0:0            /srv/dev-disk-by-id-usb-ST4000DM_000-1F2168_SSI7632000000001-0-0        btrfs   autodefrag,commit=120,compress-force=zstd:3,discard=async,noatime,space_cache=v2,nossd,nofail     0 2
/dev/disk/by-uuid/94225562225549FE              /srv/dev-disk-by-uuid-94225562225549FE  ntfs    defaults,nofail,big_writes      0 2
# <<< [openmediavault]
```
```
root@raspberrypi4:~# omv-confdbadm read --prettify conf.system.filesystem.mountpoint
[
    {
        "comment": "",
        "dir": "/srv/dev-disk-by-id-usb-ST4000DM_000-1F2168_SSI7632000000001-0-0",
        "freq": 0,
        "fsname": "/dev/disk/by-id/usb-ST4000DM_000-1F2168_SSI7632000000001-0:0",
        "hidden": false,
        "opts": "autodefrag,commit=120,compress-force=zstd:3,discard=async,noatime,space_cache=v2,nossd,nofail",
        "passno": 2,
        "type": "btrfs",
        "usagewarnthreshold": 85,
        "uuid": "607084b9-525a-4dd1-9d0f-f3d88bacb182"
    },
    {
        "comment": "",
        "dir": "/",
        "freq": 0,
        "fsname": "/dev/mmcblk0p2",
        "hidden": true,
        "opts": "noatime,nodiratime,defaults",
        "passno": 1,
        "type": "ext4",
        "usagewarnthreshold": 85,
        "uuid": "79684322-3eac-11ea-a974-63a080abab18"
    },
    {
        "comment": "",
        "dir": "/srv/dev-disk-by-uuid-94225562225549FE",
        "freq": 0,
        "fsname": "/dev/disk/by-uuid/94225562225549FE",
        "hidden": false,
        "opts": "defaults,nofail,big_writes",
        "passno": 2,
        "type": "ntfs",
        "usagewarnthreshold": 85,
        "uuid": "a04d246e-e955-41a0-9a47-d65015ad2c1c"
    }
]
```

**Reference to Forum**
[URL link to forum post](https://forum.openmediavault.org/index.php?thread/44921-btrfs-filesystem-is-missing/#post326835)

**openmediavault Server**
- OS version: Linux raspberrypi4 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
- openmediavault version: openmediavault 6.0.44-1, openmediavault-keyring 1.0, openmediavault-omvextrasorg 6.1.1 and openmediavault-sharerootfs 6.0.2-1

**Clients**
- Device: Lenovo Ideapad Duet 5
- OS: ChromeOS 107.0.5304.32
- Browser: Chrome
- Version 107.0.5304.32

- Device: Google Pixel 6
- OS: Android 13 - Build TPA1A.221005.002
- Browser: Chrome
- Version 106.0.5249.126

**Additional context**
I would like to downgrade to OMV version 6.0.39-1. According to my research, this was current at the time of my last reboot. I did not notice the error with this version. Unfortunately an apt-get install openmediavault=6.0.39-1 does not work. Therefore I can't check if it works with the old version.

I briefly removed the BTRFS file system from /etc/openmediavault/config.xml. After that the widget was displayed correctly in the dashboard again. In the File System menu, the BTRFS file system was no longer displayed and could not be included.

**Comment by votdev** [comment]
Does the problem still occur?

To display the existing filesystem in the dropdown menu in the `Mount` form, the filesystem needs to be unmounted, otherwise OMV recognises that and does not display it in the mount candidates list.

**Comment by dontobi** [comment]
I rebuilt my host and the problem did not occur again.

**Comment by imyoric** [comment]
> Does the problem still occur?
> 
> To display the existing filesystem in the dropdown menu in the `Mount` form, the filesystem needs to be unmounted, otherwise OMV recognises that and does not display it in the mount candidates list.

It cannot be unmounted, the button for this is inactive
