### ISSUE TITLE
gpodder podcast dl plugin

### ISSUE THREAD

**Issue by HACKER-3000** [openmediavault/openmediavault#141]
what about adding a plugin wich can dl rss podcast based on maybe 'gpo' or sth like that.

**Comment by HACKER-3000** [comment]
or `podget`

**Comment by ryecoaaron** [comment]
Plugin really should be requested in the forum.  This particular request can be easily satisfied by installing the docker plugin and following a tutorial https://forum.openmediavault.org/index.php/Thread/19553-OMV-Docker-plugin-media-server-Plex-PlexPy-Ombi-Libresonic-NZBGet-ruTorrent-Sona/ or https://forum.openmediavault.org/index.php/Thread/23005-Installation-and-Setup-Videos-Beginning-Intermediate-and-Advanced/

**Comment by votdev** [comment]
I do not see the need for this, but this does not mean that others will implement that as plugin. But I suggest to use docker instead.
