### ISSUE TITLE
"Apply Change" requires community to contribute descriptions

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1413]
**Is your feature request related to a problem? Please describe.**
This comment on closed issue  https://github.com/openmediavault/openmediavault/issues/1377#issuecomment-1292704590
is asking for community engagement, but I fear without a proper reference issue, the task will go unnoticed.

**Describe the solution you'd like**
A clear and concise description of what should be happening in code.

instead of "Examples:

https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/module/avahi.inc#L34" 

a better description might be:

- add public function named "getDescription" like below example and replace embedded "??text??" with a meaningful description of modules function
```
public function getDescription() {
		return gettext("??description of modules function??");
	}
```

- anything else to be done? (i.e. how to localize the description,..)

The up-to-date list of modules to be updated:

- [ ] https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/usr/share/openmediavault/engined/module
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-clamav/usr/share/openmediavault/engined/module/clamav.inc
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-filebrowser/usr/share/openmediavault/engined/module/filebrowser.inc
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-forkeddaapd/usr/share/openmediavault/engined/module/forkeddaapd.inc
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-nut/usr/share/openmediavault/engined/module/nut.inc
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-onedrive/usr/share/openmediavault/engined/module/onedrive.inc
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-owntone/usr/share/openmediavault/engined/module/owntone.inc
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-photoprism/usr/share/openmediavault/engined/module/photoprism.inc
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-s3/usr/share/openmediavault/engined/module/minio.inc
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-shairport/usr/share/openmediavault/engined/module/shairport.inc
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-snmp/usr/share/openmediavault/engined/module/snmp.inc
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-tftp/usr/share/openmediavault/engined/module/tftp.inc
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-usbbackup/usr/share/openmediavault/engined/module/usbbackup.inc
- [ ] https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-wetty/usr/share/openmediavault/engined/module/wetty.inc

@votdev, does above describe the tasks correctly and completely?

**Comment by votdev** [comment]
Yes, but you need to take care that [master/deb/openmediavault/usr/share/openmediavault/engined/module](https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/usr/share/openmediavault/engined/module?rgh-link-date=2022-11-02T13%3A36%3A10Z) contains > 40 more entries that are not listed seperately here.
