### ISSUE TITLE
n5105+i225v/226v，在安装过程中，没有以太网连接，也就是网卡不支持，是否可以更新最新的内核和驱动进行支持呢？谢谢，thank you

### ISSUE THREAD

**Issue by sss132919** [openmediavault/openmediavault#1414]
n5105+i225v/226v，在安装过程中，没有以太网连接，也就是网卡不支持，是否可以更新最新的内核和驱动进行支持呢？谢谢，thank you

**Comment by votdev** [comment]
Quelle variante d'installation avez-vous choisie ? quel matériel utilisez vous? En principe, cependant, le projet OMV ne peut rien faire ici.

**Comment by sss132919** [comment]
device cpu n5105+intel i226 2.5g lan, 
esxi
thanks you .
one thinking ，linux-kernel-5.15 and more lasted include the driver of i225/i226 , so i think maybe can replace the debian's kernel to solved it. 
of coures if can't do that , its dosen't matter. 
thank for you reply

**Comment by votdev** [comment]
The kernel packages are maintained by the Debian project. OMV is only using their infrastructure, so if Debian releases kernel 5.15 for Debian 11, then OMV will also participate from this.

**Comment by votdev** [comment]
OMV is using the kernel backports, so my current OMV6 test machine is running 5.19.0.

Which OMV version are you talking about? How did you install your system?

**Comment by votdev** [comment]
By the way, if you are using the official OMV ISO image and this does not include all your needed hardware drivers, try using the Debian Netinst ISO instead and manually install OMV. Check out https://docs.openmediavault.org/en/stable/installation/on_debian.html for more information.

**Comment by sss132919** [comment]
i know it can be update omv's kernel to 5.19, but this must be after installed it . in installing process , it can't know my network devices.
i use the .iso install it  on esxi/vmware, and direct io my i226 network device

**Comment by votdev** [comment]
> in installing process , it can't know my network devices.

In this case, please use the Debian Netinst ISO instead.

**Comment by votdev** [comment]
I'm closing this issue because there are alternative solutions to workaround this issue.
