### ISSUE TITLE
Adding shared folders to FTP gives Error 500

### ISSUE THREAD

**Issue by OfficialMuffin** [openmediavault/openmediavault#1418]
This may be related to issue #1148 as I had issues with enabling the proftpd server giving the same error as below. I managed to enable it somehow, I just undid the changes and tried enabling it again and it worked. However, my issue is that when adding a shared folder to FTP, the web UI shows a 500 Error when attempting to apply the changes made. I am unable to find this error in any of the logs. 

I checked the `/etc/proftpd/proftpd.conf` and the lines were added to the file showing the shares were correctly added.
Successfully connected to the proftpd server and all of my added shares were viewable and editable.

**Comment by OfficialMuffin** [comment]
I managed to grab the error text before it disappears. Hope this helps.

> _500 - OK
> Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color proftpd 2>&1' with exit code '1': server: ---------- ID: configure_proftpd_mod_core Function: file.managed Name: /etc/proftpd/proftpd.conf Result: True Comment: File /etc/proftpd/proftpd.conf updated Started: 22:17:27.039399 Duration: 288.556 ms Changes: ---------- diff: --- +++ @@ -64,62 +64,3 @@ </Limit> </Directory> -<IfModule mod_auth.c> - DefaultRoot /srv/ftp - MaxClients 50 - MaxLoginAttempts 2 - RequireValidShell on - # This option is useless because this is handled via the PAM - # pam_listfile.so module, so set it to 'off' by default. - UseFtpUsers off -</IfModule> -<IfModule mod_auth_pam.c> - AuthPAM on - AuthPAMConfig proftpd -</IfModule> -<IfModule mod_ban.c> - BanEngine off - BanControlsACLs all allow user root - BanLog /var/log/proftpd/ban.log - BanMessage Host %a has been banned ..._

**Comment by OfficialMuffin** [comment]
Not sure if this fixed it after a lot of frustration playing around with the omv web UI but all seems OK now. I took these steps via ssh terminal:

1. `sudo systemctl restart monit`
2. Used the `omv-salt` command to manually apply changes.

**Comment by votdev** [comment]
> I managed to grab the error text before it disappears. Hope this helps.
> 
> > _500 - OK
> > Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color proftpd 2>&1' with exit code '1': server: ---------- ID: configure_proftpd_mod_core Function: file.managed Name: /etc/proftpd/proftpd.conf Result: True Comment: File /etc/proftpd/proftpd.conf updated Started: 22:17:27.039399 Duration: 288.556 ms Changes: ---------- diff: --- +++ @@ -64,62 +64,3 @@   - - DefaultRoot /srv/ftp - MaxClients 50 - MaxLoginAttempts 2 - RequireValidShell on - # This option is useless because this is handled via the PAM - # pam_listfile.so module, so set it to 'off' by default. - UseFtpUsers off - - - AuthPAM on - AuthPAMConfig proftpd - - - BanEngine off - BanControlsACLs all allow user root - BanLog /var/log/proftpd/ban.log - BanMessage Host %a has been banned ..._

You have cut the most interesting part here, this only contains white noise. Please post the whole error message.

**Comment by OfficialMuffin** [comment]
I mentioned this already 

> I am unable to find this error in any of the logs.

Or am I looking in the wrong place.
I've looked in `/var/log/` already. I can only see the error when it shows in the web ui.

**Comment by votdev** [comment]
> I mentioned this already
> 
> > I am unable to find this error in any of the logs.
> 
> Or am I looking in the wrong place. I've looked in `/var/log/` already. I can only see the error when it shows in the web ui.

Open the notification sidebar and copy the whole error message into the clipboard.

**Comment by OfficialMuffin** [comment]
I'll post it here when it decides to show up again. Seems OK now

**Comment by OfficialMuffin** [comment]
Closing as the error does not appear. Will reopen if it shows again
