### ISSUE TITLE
Data Failed to Compile

### ISSUE THREAD

**Issue by ItzChr1s1** [openmediavault/openmediavault#1421]
Hello i've been having trouble for some time with this, i'm trying to share the root directory / with smb but it gives an error? I looked through different articles i used this command `sudo omv-salt deploy run avahi`
 it gives the following error:

    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.avahi.services.filebrowser' failed: Jinja error: 'NoneType' object has no attribute 'get_dict'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 20, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 465, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 44, in get
    return objs.get_dict()
AttributeError: 'NoneType' object has no attribute 'get_dict'

; line 20

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

{% set config = salt['omv_conf.get']('conf.service.filebrowser') %}    <======================
{% set ssl_enabled = config.sslcertificateref | length > 0 %}
{% set zeroconf_enabled = salt['pillar.get']('default:OMV_FILEBROWSER_ZEROCONF_ENABLED', 1) %}
{% set zeroconf_name = salt['pillar.get']('default:OMV_FILEBROWSER_ZEROCONF_NAME', '%h - File Browser') %}

{% if not (config.enable | to_bool and zeroconf_enabled | to_bool) %}
[...]
---

________________________________

This is what is shows when I apply changes to add the directory:

500 - Internal Server Error
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color avahi 2>&1' with exit code '1': raspberrypi: Data failed to compile: ---------- Rendering SLS 'base:omv.deploy.avahi.services.filebrowser' failed: Jinja error: 'NoneType' object has no attribute 'get_dict' Traceback (most recent call last): File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl output = template.render(**decoded_context) File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1090, in render self.environment.handle_exception() File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 832, in handle_exception reraise(*rewrite_traceback_stack(source=source)) File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 28, in reraise raise value.with_traceback(tb) File "<template>", line 20, in top-level template code File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 465, in call return __context.call(__obj, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__ return self.loader.run(run_func, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_a...

**Comment by ryecoaaron** [comment]
You should never share / over samba.

**Comment by votdev** [comment]
Beside the comment from @ryecoaaron it seems your installation of the plugin was not successful. Try to run `apt-get install --reinstall openmediavault-filebrowser` to populate the database correctly.

**Comment by ItzChr1s1** [comment]
> Beside the comment from @ryecoaaron it seems your installation of the plugin was not successful. Try to run `apt-get install --reinstall openmediavault-filebrowser` to populate the database correctly.

I attempted that command and for some reason it says this:
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package openmediavault-filebrowser`

**Comment by votdev** [comment]
> > Beside the comment from @ryecoaaron it seems your installation of the plugin was not successful. Try to run `apt-get install --reinstall openmediavault-filebrowser` to populate the database correctly.
> 
> I attempted that command and for some reason it says this: `Reading package lists... Done Building dependency tree Reading state information... Done E: Unable to locate package openmediavault-filebrowser`

It that's the case, then the openmediavault package repository is not configured properly which tells me something weird is going on at your system.

**Comment by ItzChr1s1** [comment]
> > > Beside the comment from @ryecoaaron it seems your installation of the plugin was not successful. Try to run `apt-get install --reinstall openmediavault-filebrowser` to populate the database correctly.
> > 
> > 
> > I attempted that command and for some reason it says this: `Reading package lists... Done Building dependency tree Reading state information... Done E: Unable to locate package openmediavault-filebrowser`
> 
> It that's the case, then the openmediavault package repository is not configured properly which tells me something weird is going on at your system.

i'm able to use SMB for a folder right now as well. Creating new ones don't work, I'm not 100% certain but this may have started after a reboot
