### ISSUE TITLE
Is there a way to create a Dashboard widget that shows the output of a shell command?

### ISSUE THREAD

**Issue by ohadpr** [openmediavault/openmediavault#1422]
I see examples of simple plugins which display text, but these all seem to be executing built-in System commands.
I'm looking for a simple example or spec guiding how to build a dashboard widget that executes a shell command and shows the text output in the widget.

I've looked at what I could find for a doc/spec of dashboard widgets, namely the following links, but couldn't find what I'm looking for.

- https://docs.openmediavault.org/en/latest/development/plugins.html
- https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/src/app/core/components/dashboard/models/dashboard-widget-config.model.ts

Thanks

**Comment by votdev** [comment]
OMV does not provide a general purpose RPC to execute any command because of security issues. You need to implement that RPC via PHP yourself. To display the data you can use the text-widget[https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/workbench/src/app/core/components/dashboard/dashboard-widget-text]() .

**Comment by ryecoaaron** [comment]
Look at the lm-sensors part of the cputemp plugin

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-cputemp

**Comment by ohadpr** [comment]
Thanks @votdev and @ryecoaaron. The `cputemp` is perfect.

**Comment by ohadpr** [comment]
Hey,

I followed the example and created a new Dashboard widget and RPC service. The widget shows in the dashboard but the RPC call fails.

`{"response":null,"error":{"code":0,"message":"RPC service 'Dropbox' not found.","trace":"OMV\\HttpErrorException: RPC service 'Dropbox' not found. in \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc:100\nStack trace:\n#0 \/usr\/sbin\/omv-engined(537): OMV\\Rpc\\Rpc::call('Dropbox', 'getStatus', NULL, Array, 1)\n#1 {main}"}}`

Do I need to do anything else to get my rpc service to get loaded within OMV? I assume it just loads all .inc files in the directory?

Thanks!

The files I've added:

`/usr/share/openmediavault/workbench/dashboard.d`

```
version: "1.0"
type: dashboard-widget
data:
  id: d7430373-d1ec-4436-8307-cddfe9731659
  permissions:
    role:
      - admin
  title: _("Dropbox")
  description: _("Displays information about Dropbox sync status")
  type: text
  reloadPeriod: 3000
  text:
    request:
      service: Dropbox 
      method: getStatus
```

`/usr/share/openmediavault/engined/rpc/dropbox.inc`

```
?php
/**
 * Copyright (C) 2022 OpenMediaVault Plugin Developers
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
class OMVRpcServiceDropbox extends \OMV\Rpc\ServiceAbstract
{
    public function getName()
    {
        return "Dropbox";
    }

    public function initialize()
    {
        $this->registerMethod("getStatus");
    }

    public function getStatus($params, $context)
    {
        // Validate the RPC caller context.
        $this->validateMethodContext($context, ["role" => OMV_ROLE_ADMINISTRATOR]);
        $cmd = new \OMV\System\Process("/usr/local/bin/dropbox status");
        $cmd->execute($output, $exitStatus);
        return (implode('<br/>', $output));
    }
}

```

**Comment by ryecoaaron** [comment]
Did you restart omv-engined?  monit restart om-engined

**Comment by ohadpr** [comment]
No, but I did restart the whole machine.
Went ahead and ran `sudo monit restart omv-engined`, no error but also nothing else printed out.
Rebooted again to make sure, same error.

**Comment by ryecoaaron** [comment]
Did you:
sudo omv-mkworkbench all

I would start omv-engined in debug to see if the module registered.

sudo monit stop omv-engined
sudo omv-engined -df

**Comment by ohadpr** [comment]
Thanks, this made it super easy to debug.

My `dropbox.inc` file started with `?php` rather than `<?php` :-)

**Comment by ryecoaaron** [comment]
Oops.  I didn't even look at that.
