### ISSUE TITLE
Add a option in GUI to enable/disable startup/shutdown beeps

### ISSUE THREAD

**Issue by corzocone** [openmediavault/openmediavault#1423]
Shutdown/startup beeps are not helpful to me, though I understand they are helpful to others. 

I'd love a simple option to enable/disable this feature (I may want it back in the future for some reason)

I know there are CLI options, but I feel like this would be a very simple toggle in the GUI.

**Comment by votdev** [comment]
I am closing this issue because it is the OMV common way to not provide a knob for everything.

**Comment by corzocone** [comment]
Got it, thank you. Can I use the same commands replacing disable with enable if I want to add the feature back in the future?

Thank you,
Cory
________________________________

**Comment by votdev** [comment]
> Got it, thank you. Can I use the same commands replacing disable with enable if I want to add the feature back in the future? Thank you, Cory

Sure
