### ISSUE TITLE
Error 500 when saving changes to FTP

### ISSUE THREAD

**Issue by Shawn9347** [openmediavault/openmediavault#1428]
Hi,

When saving anything on FTP settings I'm getting this error. Whatever I do always this error. Forums don't respond so that's why I post here. 

I'm on the latest version. 

`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color avahi 2>&1' with exit code '1': Traceback (most recent call last): File "/sbin/omv-salt", line 152, in <module> sys.exit(main()) File "/sbin/omv-salt", line 147, in main cli() File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/sbin/omv-salt", line 133, in deploy_run caller = salt.client.Caller(mopts=mopts) File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2098, in __init__ import salt.minion File "/usr/lib/python3/dist-packages/salt/minion.py", line 36, in <module> import salt.pillar File "/usr/lib/python3/dist-packages/salt/pillar/__ini...`

**Comment by ryecoaaron** [comment]
> Forums don't respond so that's why I post here.

You need to wait more than 20 hours...  The forum is volunteers.
