### ISSUE TITLE
Collectd crash when OMV-nut is enabled

### ISSUE THREAD

**Issue by Killator** [openmediavault/openmediavault#1430]
Hi OMV Team,

I think I found a bug on OMV NUT (core plugin)

Context:
- Linux omv 5.19.0-0.deb11.2-686-pae #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1~bpo11+1 (2022-10-03) i686 GNU/Linux
- OMV 6.0.46-5 / up-to-date
- OMV-nut 6.0.1-1 / up-to-date

To reproduce:

- When I enable collectd without NUT, everything is OK.
- When I enable NUT without collectd, everything is OK (OMV communicate with my UPS / Mode : Standalone / driver : usbhid-ups / port : auto)

BUT...

When I try to enable collectd when NUT is UP, I have a crash... A parsing error...

Logs below (journalctl -xe):

```
░░ Automatic restarting of the unit collectd.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Nov 22 14:42:51 omv systemd[1]: Stopped Statistics collection and monitoring daemon.
░░ Subject: A stop job for unit collectd.service has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A stop job for unit collectd.service has finished.
░░ 
░░ The job identifier is 32835 and the job result is done.
Nov 22 14:42:51 omv postfix/smtp[18269]: 0514D3FEAD: replace: header Subject: Undelivered Mail Returned to Sender: Subject: [omv.klz] Undelivered Mail Returned to Sender
Nov 22 14:42:51 omv systemd[1]: Starting Statistics collection and monitoring daemon...
░░ Subject: A start job for unit collectd.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit collectd.service has begun execution.
░░ 
░░ The job identifier is 32835.
Nov 22 14:42:51 omv collectd[19132]: plugin_load: plugin "cpu" successfully loaded.
Nov 22 14:42:51 omv collectd[19132]: plugin_load: plugin "df" successfully loaded.
Nov 22 14:42:51 omv collectd[19132]: plugin_load: plugin "disk" successfully loaded.
Nov 22 14:42:51 omv collectd[19132]: plugin_load: plugin "interface" successfully loaded.
Nov 22 14:42:51 omv collectd[19132]: plugin_load: plugin "load" successfully loaded.
Nov 22 14:42:51 omv collectd[19132]: plugin_load: plugin "memory" successfully loaded.
Nov 22 14:42:51 omv collectd[19132]: plugin_load: Could not find plugin "nut" in /usr/lib/collectd
Nov 22 14:42:51 omv collectd[19132]: There is configuration for the `nut' plugin, but the plugin isn't loaded. Please check your configuration.
Nov 22 14:42:51 omv collectd[19132]: plugin_load: plugin "rrdcached" successfully loaded.
Nov 22 14:42:51 omv collectd[19132]: plugin_load: plugin "syslog" successfully loaded.
Nov 22 14:42:51 omv collectd[19132]: plugin_load: plugin "unixsock" successfully loaded.
Nov 22 14:42:51 omv collectd[19132]: plugin_load: plugin "uptime" successfully loaded.
Nov 22 14:42:51 omv collectd[19132]: Error: Parsing the config file failed!
Nov 22 14:42:51 omv systemd[1]: collectd.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStart= process belonging to unit collectd.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Nov 22 14:42:51 omv systemd[1]: collectd.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit collectd.service has entered the 'failed' state with result 'exit-code'.
Nov 22 14:42:51 omv systemd[1]: Failed to start Statistics collection and monitoring daemon.
░░ Subject: A start job for unit collectd.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit collectd.service has finished with a failure.
░░ 
░░ The job identifier is 32835 and the job result is failed.
```

Something looks weird in the log > "_There is configuration for the **`nut'** plugin_"

And here, the /etc/collectd/collectd.conf.d/nut.conf file:
```
LoadPlugin nut
<Plugin nut>
    UPS "apc_es_700g@localhost:3493"
</Plugin>
```

I don't understand why it crashes. Maybe this is the double quote ?
Maybe the error is somewhere else ? ("_the plugin isn't loaded_")

Could you please help me ?

Thanks a lot !

Regards,
Killator

**Comment by votdev** [comment]
Can not reproduce the issue. Could you please run the following commands and post their output.
```
# collectd -t; echo $?
# collectd -T
```

**Comment by Killator** [comment]
Hello !

Thanks for your help !

First command return '0'

Second command:
```
root@qnap:~# collectd -T
plugin_load: plugin "cpu" successfully loaded.
plugin_load: plugin "df" successfully loaded.
plugin_load: plugin "disk" successfully loaded.
plugin_load: plugin "interface" successfully loaded.
plugin_load: plugin "load" successfully loaded.
plugin_load: plugin "memory" successfully loaded.
plugin_load: Could not find plugin "nut" in /usr/lib/collectd
There is configuration for the `nut' plugin, but the plugin isn't loaded. Please check your configuration.
plugin_load: plugin "rrdcached" successfully loaded.
Error: Parsing the config file failed!
root@qnap:~#
```

I hope it will help you to find something...

(OMV-NUT is working fine)

**Comment by votdev** [comment]
Please post the output of 
```
# dpkg -l | grep collectd
# apt-cache policy collectd
```
I assume you've installed the wrong `collectd` package version which does not include the nut plugin.

**Comment by Killator** [comment]
dpkg -l | grep collectd:
```
ii  collectd                             5.12.0-7                      i386         statistics collection and monitoring daemon
ii  collectd-core                        5.12.0-7                      i386         statistics collection and monitoring daemon (core system)
```

apt-cache policy collectd;
```
  Installed: 5.12.0-7
  Candidate: 5.12.0-7
  Version table:
 *** 5.12.0-7 500
        500 http://deb.debian.org/debian bullseye/main i386 Packages
        100 /var/lib/dpkg/status
```

does this confirm the suspicion of the wrong collectd ? If yes, is there an easy way to fix this ?

**Comment by votdev** [comment]
> I'm on a +10 years old QNAP with a 32Bits CPU... Could this explain the issue ?

Yes, that's the case. There is no i386 'collectd` package in the OMV repository that fixes a bug (missing NUT extension/plugin in collectd) in the official Debian `collectd` package.

**Comment by Killator** [comment]
OK. I understand...

Is it possible to make an exception in the OMV configuration to have OMV-NUT (32Bit) enable and only collect-nut plugin disable ? In SSH, in the salt stack description files may be ?

**Comment by MrTwinkles47** [comment]
I also have this issue, but on a 64bit OS. 

The currently installed `collectd` version is `5.12.0-7` on OMV6. With `apt-cache policy collectd`, I can see that the patched `5.12.0-7.1` version is available through the openmediavault repository. If I try to `apt-get install` this specific version, I am greeted with `apt` wanting to remove `openmediavault*` packages. This seems dangerous?

**Comment by votdev** [comment]
> I also have this issue, but on a 64bit OS.
> 
> The currently installed `collectd` version is `5.12.0-7` on OMV6. With `apt-cache policy collectd`, I can see that the patched `5.12.0-7.1` version is available through the openmediavault repository. If I try to `apt-get install` this specific version, I am greeted with `apt` wanting to remove `openmediavault*` packages. This seems dangerous?

Can not test this behaviour, but the collectd version from the OMV package repository should be installed automatically because it has a higher version than the package in the Debian repository. So i am asing myself how it can happen that the incorrect version is installed.
You should be able to install the latest version with `apt-get install collectd=5.12.0-7.1` without uninstalling openmediavault.

**Comment by MrTwinkles47** [comment]
Oh, I agree--a higher version should have priority, right? It seemed like odd behavior, which is why I haven't continued with installing the `.1` version.
Here's some screenshots:

`apt-cache policy collectd`
![image](https://user-images.githubusercontent.com/64985827/210487359-9a9193fd-bd4c-4afa-b503-185c9d08c184.png)
`apt-get install collectd-core=5.12.0-7.1`
![image](https://user-images.githubusercontent.com/64985827/210487611-6f2b3916-6678-406c-a82d-9e6f9146c266.png)

**Comment by votdev** [comment]
Hmmm, that's strange, the Debian repository has a higher priority than the OMV repo. That's why the OMV package is not installed.

That's how it looks on my machines:
```
collectd:
  Installed: 5.12.0-7.1
  Candidate: 5.12.0-7.1
  Version table:
 *** 5.12.0-7.1 500
        500 http://packages.openmediavault.org/public shaitan/main amd64 Packages
        500 https://openmediavault.github.io/packages shaitan/main amd64 Packages
        100 /var/lib/dpkg/status
     5.12.0-7 500
        500 https://deb.debian.org/debian bullseye/main amd64 Packages
```

@MrTwinkles47 How did you install OMV?

Can you please run `ls -alh /etc/apt/preferences.d/` and post the output.

**Comment by MrTwinkles47** [comment]
This OMV6 bare-metal install is a release-upgrade from OMV5. Previously, I used [dleidert's scripts](https://github.com/dleidert/openmediavault-upgrade) to upgrade from OMV3->OMV4, and then OMV4->OMV5. OMV3 was originally installed from the ISO. I can imagine all these in-place upgrades haven't helped...

```
root@mediaserver:~# ls -alh /etc/apt/preferences.d/
total 16K
drwxr-xr-x  2 root root 4.0K Jan  4 00:06 .
drwxr-xr-x 13 root root 4.0K Dec 31 15:52 ..
-rw-r--r--  1 root root 1.5K Nov 17 09:39 omv-extras-org
-rw-r--r--  1 root root   44 May  4  2017 openmediavault-local.pref
```

**Comment by votdev** [comment]
Can you please run `cat /etc/apt/preferences.d/openmediavault-local.pref` and `cat /etc/apt/preferences.d/omv-extras-org`?

**Comment by MrTwinkles47** [comment]
`cat /etc/apt/preferences.d/openmediavault-local.pref`
```
Package: *
Pin: origin ""
Pin-Priority: 995
```
`cat /etc/apt/preferences.d/omv-extras-org`
```
Package: virtualbox*
Pin: release a=stretch-backports
Pin-Priority: 500

Package: zfs*
Pin: release a=stretch-backports
Pin-Priority: 500

Package: spl
Pin: release a=stretch-backports
Pin-Priority: 500

Package: spl-dkms
Pin: release a=stretch-backports
Pin-Priority: 500

Package: libnvpair1linux
Pin: release a=stretch-backports
Pin-Priority: 500

Package: libzfs2linux
Pin: release a=stretch-backports
Pin-Priority: 500

Package: libzpool2linux
Pin: release a=stretch-backports
Pin-Priority: 500

Package: libuutil1linux
Pin: release a=stretch-backports
Pin-Priority: 500

Package: linux-compiler-gcc-6-x86
Pin: release a=stretch-backports
Pin-Priority: 500

Package: xrdp
Pin: release a=stretch-backports
Pin-Priority: 500

Package: certbot python3-acme python3-certbot python3-cffi-backend python3-chardet python3-configargparse python3-configobj
  python3-cryptography python3-future python3-idna python3-josepy python3-mock python3-openssl python3-parsedatetime
  python3-pbr python3-pyasn1 python3-requests python3-rfc3339 python3-urllib3 python3-zope.component
  python3-zope.event python3-zope.hookable python3-zope.interface
Pin: release a=stretch-backports
Pin-Priority: 500

Package: borgbackup
Pin: release a=stretch-backports
Pin-Priority: 500

Package: *
Pin: release n=arrakis, origin dl.bintray.com
Pin-Priority: 995

Package: *
Pin: release n=arrakis-docker, origin dl.bintray.com
Pin-Priority: 996

Package: *
Pin: release o=download.docker.com
Pin-Priority: 1001
```

**Comment by votdev** [comment]
I am currently out of ideas why and how the 990 priority for the Debian repository is configured. By default it should be 500. See https://wiki.debian.org/AptConfiguration

**Comment by votdev** [comment]
Maybe it is in /etc/apt/apt.conf which is deprecated but you told that this was an OMV5. Please post the content of this file.

**Comment by MrTwinkles47** [comment]
`cat /etc/apt/apt.conf`
```
root@mediaserver:~# cat /etc/apt/apt.conf
APT::Default-Release "bullseye";
```

**Comment by votdev** [comment]
Is there a file called `/etc/apt/preferences`?

**Comment by MrTwinkles47** [comment]
There is no file called `preferences`. 

I truly appreciate the help troubleshooting this weird issue. Don't worry about it. 
I'll end up "fixing" it with a fresh install to move to UEFI booting anyway.
