### ISSUE TITLE
Local Directory File System

### ISSUE THREAD

**Issue by sandreas** [openmediavault/openmediavault#1433]
I use a Proxmox homeserver with a custom OpenMediaVault LXC container. Now I would like the excellent sharing and management features of OpenMediaVault, but because OMV requires a block based file system and there is no such thing in the LXC container, it is not possible to add a filesystem in the web UI. 

This is an actual problem, because a filesystem is required to do ANYTHING in OMV (shares, etc.). 

As a solution I would love to have an Option for Local Directory File System, that does not require a block device but only a simple local directory anywhere. This would be kind of a virtual Filesystem, but at least you could share things in case of a non existing block device or mount option.

Would that be possible?

**Comment by votdev** [comment]
OMV is not designed to run in containers. It's planned as NAS on dedicated hardware. As workaround you can install the `openmediavault-sharerootfs` plugin which will add the root filesystem as mounted filesystem, thus you can use it to create shared folders.

**Comment by sandreas** [comment]
Thank you for the quick response. I understand the `wontfix` tag in that case, but I'm still confused because I installed the `rootfs` plugin and it does not change anything.

I did the following:
- Install OMV  6.0.46-5 (Shaitan)
- Install OMV Extras Plugin via `wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install | bash`
- Install `rootfs` plugin via Plugins
- performed a reboot

In `System / omv-extras` the `rootfs` Plugin does not show up (only settings, docker, portainer and yacht), but I think that is expected. However, even with the plugin installed I cannot:

- Create a Filesystem
- Mount a Filesystem
- Create a shared folder

In every case the *Filesystem* dropdown is empty and does not show any option.

Should I create a new issue for that? If so, where? And do you need any logs?

**Comment by votdev** [comment]
> Should I create a new issue for that?

No

> And do you need any logs?

Please post the output of the following commands:

```
# dpkg -l | grep openmediavault
# omv-confdbadm read --prettify conf.system.filesystem.mountpoint
```

**Comment by sandreas** [comment]
> Please post the output of the following commands:

Ok, may take a while, I'm on vacation right now :-)

**Comment by jo-me** [comment]
Same situation here. 
installation of OMV in LXC container on Proxmox 7.3 via script from https://tteck.github.io/Proxmox/
I want to create a file share based on "/mnt/media" but the filesystem drop down remains empty after installation of sharerootfs.

```

root@omv:~# dpkg -l | grep openmediavault
ii  openmediavault                 6.1.3-1                        all          openmediavault - The open network attached storage solution
ii  openmediavault-keyring         1.0                            all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg    6.1.1                          all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-sharerootfs     6.0.2-1                        all          openmediavault share root filesystem plugin 

root@omv:~# omv-confdbadm read --prettify conf.system.filesystem.mountpoint
[]

root@omv:~# mount
/dev/mapper/pve-vm--108--disk--0 on / type ext4 (rw,relatime,stripe=16)
tank/media on /mnt/media type zfs (rw,noatime,xattr,noacl)
none on /dev type tmpfs (rw,relatime,size=492k,mode=755,inode64)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
proc on /proc/sys/net type proc (rw,nosuid,nodev,noexec,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
sysfs on /sys/devices/virtual/net type sysfs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
proc on /dev/.lxc/proc type proc (rw,relatime)
sys on /dev/.lxc/sys type sysfs (rw,relatime)
none on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)
lxcfs on /proc/cpuinfo type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/diskstats type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/loadavg type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/meminfo type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/stat type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/swaps type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/uptime type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /sys/devices/system/cpu/online type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1026)
devpts on /dev/ptmx type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1026)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1026)
devpts on /dev/tty1 type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1026)
devpts on /dev/tty2 type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1026)
none on /proc/sys/kernel/random/boot_id type tmpfs (ro,nosuid,nodev,noexec,relatime,size=492k,mode=755,inode64)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run type tmpfs (rw,nosuid,nodev,size=3232128k,nr_inodes=819200,mode=755,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
sunrpc on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /tmp type tmpfs (rw,relatime,inode64)

**Comment by ryecoaaron** [comment]
Containers are not supported.  sharerootfs can't work without a real device for the root directory.  LXC does not offer that.  It would take a lot of work.
