### ISSUE TITLE
When a file system can't be mounted, web UI should not give errors and should allow shared folder changes

### ISSUE THREAD

**Issue by deTTriTTus** [openmediavault/openmediavault#1434]
**Is your feature request related to a problem? Please describe.**
When a file system can't be mounted, web UI does not allow to edit the problematic FS (404 error) and user can't edit or add shared folders (list of drives is empty). Other operations might also be impossible. No torough review was done.

**Describe the solution you'd like**
The UI should allow any operation despite a file system not being able to be mounted.

**Describe alternatives you've considered**
Currently, user has to stop the FS, apply the changes to be able to do certain operations. When user want's to reuse the temporary drive, user will have to enable it again (I'm not 100% sure about this last part)

**Additional context**
This is especially problematic for temporary USB drive a user might want to use sporadicaly.

**Comment by ryecoaaron** [comment]
It doesn't make sense to allow operations like creating shared folders on a filesystem that isn't mounted because part of the process is creating folders and setting permissions.

**Comment by deTTriTTus** [comment]
@ryecoaaron 
I'm talking about operations on other, mounted filesystems. Here's the exact use case I came accross this morning:

- FS on USB drive (currently disconnected) is not mounted.
- Want to create a new shared folder (on different, currently mounted FS)
  - Not possible since list of FS in "shared folder | create" screen is empty, with red error popup. I wish this screen gave me the list of mounted FS.
- So, I went to file systems and clicked edit on the unmounted FS. I tought maybe I could disable it. Instead, this gave me a 404
  - I had to select the unmounted FS ans click stop. It also means (i'm guessing) next time I plug the USB drive, I'll need to go back to the FS screen and mount it again. I wish I didn't have to do that.

**Comment by ryecoaaron** [comment]
It shouldn't work that way.  You should be able to have many mounted or unmounted filesystems without breaking the filesystem dropdown in sharedfolders.  It seems like you mounted a usb drive, remove it without unmounting, and have a stray mntent entry in the database.

**Comment by deTTriTTus** [comment]
Quite possible I did exactly that. I realize now I should have unmouted first, which I didn't do out of laziness (there was no data transfer involved).
