### ISSUE TITLE
Allow user to disable background animation on login screen

### ISSUE THREAD

**Issue by gitname** [openmediavault/openmediavault#1435]
**Is your feature request related to a problem? Please describe.**

The OMV web UI login screen has an animated, "The Matrix"-style background on it (i.e. animated letters falling like rain). 

When I am working in the OMV web UI and then switch my focus to some other window (e.g. File Explorer), OMV will eventually automatically log me out and display the OMV web UI login screen, whose background will eventually switch from a static image of disks to a "The Matrix"-style animation. 

Once the "The Matrix"-style animation appears, the OMV web UI login screen continues to pull at my attention (i.e. I find it distracting).

I think, if the background of the OMV web UI login screen weren't animating, I would find it less distracting.

**Describe the solution you'd like**

I would like for the background of the OMV login screen to remain showing a static image instead of switching to an animated background. Assuming some of the developers want to have the animated version, I propose adding a toggle switch to the login screen. It could be labeled "[Reduce motion](https://a11y-101.com/development/reduced-motion)".

**Describe alternatives you've considered**

- When not using the OMV web UI, the user can close, minimize, or switch away from the browser tab running the OMV web UI
- The web UI could check and honor the `prefers-reduced-motion` user preference; i.e. https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Additional context**

Here is a GIF screencast of the static background transitioning into the animated, "The Matrix"-style background. This often happens when I am working in a different window.

![2022-12-04_12-52-04](https://user-images.githubusercontent.com/7143133/205514943-594fca79-6fcb-43cf-af7b-20c2e9ea330b.gif)

### OMV Version

```
6.0.46-5 (Shaitan)
```

**Comment by gitname** [comment]
For anyone else that wants to disable the animation, here's a temporary workaround:

1. When on the login page, [open the web browser's JavaScript console](https://webmasters.stackexchange.com/a/77337)
2. Paste the following code into the console:
    ```js
    document.getElementsByTagName("omv-green-rain")[0].hidden = true;
    ```
3. Press `Enter`

**Comment by ryecoaaron** [comment]
Have you set the auto logout to never?  This topic of the login animation has really been discussed to death and changes have been made to compromise.

**Comment by gitname** [comment]
Hi, thanks for replying.

>Have you set the auto logout to never?

Not to "Never," specifically; but, since opening this Issue, I have increased it from 5 minutes to 30 minutes. That has improved the situation for me, in my opinion.

**Comment by votdev** [comment]
Thank you for sharing your opinion. i know that you can't please everyone in an open source project. Adding a button contradicts the philosophy of OMV which is NOT to have a knob for every possible feature. I see the animation as art, or as a way of paying homage to great things in my past. There are several such things in the UI if you look closely. 
I am trying to find a way to integrate your concerns.

**Comment by votdev** [comment]
The `prefers-reduced-motion` seems to be a good solution.
