### ISSUE TITLE
Monitoring docker

### ISSUE THREAD

**Issue by df911** [openmediavault/openmediavault#1440]
Hello,

I use docker plugin into OMV.
I would like to collect system informations (cpu , ram, network, ...) into Home Assistant.
How to publish or enable the API docker ? 

Thanks

**Comment by votdev** [comment]
You can get the information via the RPC [System::getInformation](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/system.inc#L362).

Check out this how to call this RPC:

- https://www.openmediavault.org/?p=2089
- https://www.openmediavault.org/?p=2167
