### ISSUE TITLE
add some sshd config parameters to custom configuration

### ISSUE THREAD

**Issue by MrOnak** [openmediavault/openmediavault#1441]
**Is your feature request related to a problem? Please describe.**
I'm using the [Lynis security auditing tool](https://cisofy.com/lynis/) ([github](https://github.com/CISOfy/Lynis)) to help harden my systems. Lynis does suggest a couple of config changes to the ssh daemon through the sshd_config. Currently OMV does allow customization of only a part of these parameters. 
I'd like to avoid hacking the config / salt stack manually and I don't see harm in adding the below mentioned parameters to `omv-env`

**Describe the solution you'd like**
Add the following sshd_conf parameters to be customizable through `omv-env`

- ClientAliveCountMax
- MaxAuthTries
- MaxSessions
- AllowAgentForwarding

**Describe alternatives you've considered**
More an extension than an alternative: You could take this one step further and ship OMV with defaults that match the hardening suggestions by Lynis. They are a bit restrictive though so I see why this would be a potential issue. Regardless, all hardening suggestions for sshd by Lynis are [on github](https://github.com/CISOfy/lynis/blob/master/include/tests_ssh) starting from line 124

**Comment by votdev** [comment]
These settings are not managed and written to the `/etc/ssh/sshd_config` file by OMV. In that case simply add them to the `Extra Options` field.
