### ISSUE TITLE
Pequeña errata

### ISSUE THREAD

**Issue by josegd83** [openmediavault/openmediavault#1446]
He detectado esta pequeña errata en Español en el apartado certificados/SSH

Donde dice clave publica deberia decir clave privada...

![Captura de pantalla 2022-12-20 a las 14 15 57](https://user-images.githubusercontent.com/91919238/208689239-17607647-3168-426a-9ac6-e7d7ae7fe5cc.png)

**Comment by votdev** [comment]
Please use english language.

**Comment by votdev** [comment]
Please check https://docs.openmediavault.org/en/stable/development/contribute.html#how-to-become-a-translator how to become a translator to support the localization of openmediavault.

**Comment by josegd83** [comment]
I have detected this small typo in Spanish in the certificates/SSH section

Where it says public key, it should say private key...

**Comment by raulfg3** [comment]
I do not find error:  
<img width="894" alt="image" src="https://user-images.githubusercontent.com/12611785/216763256-4825880c-9295-45df-8a05-303f2d37d45d.png">

**Comment by raulfg3** [comment]
perdon, encontrado y corregido:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/12611785/216763303-ce31dcdd-30c3-4e8f-8c39-431029674998.png">

**Comment by josegd83** [comment]
Perfecto!Saludos, José María GDEl 4 feb 2023, a las 10:59, raulfg3 ***@***.***> escribió:﻿
perdon, encontrado y corregido:

**Comment by raulfg3** [comment]
please close this thread.
