### ISSUE TITLE
Add upgrade count on top line

### ISSUE THREAD

**Issue by donhwy** [openmediavault/openmediavault#1447]
**Is your feature request related to a problem? Please describe.**Not really 

**Describe the solution you'd like** 

Please add the count of pending updates to the top line.

**Describe alternatives you've considered**

**Additional context**

If there are more than one update pending you have to scroll to the bottom. Sometimes there are many updates. The count could show in the general area of the cursor in the screenshot.

Thanks
![Screenshot at 2022-12-21 10-14-55](https://user-images.githubusercontent.com/31188495/208966953-f3b3279f-63f5-46e7-8c2f-94516b2da576.png)

**Comment by votdev** [comment]
Available with `openmediavault 6.1.3`.

![Bildschirmfoto vom 2022-12-21 20-59-17](https://user-images.githubusercontent.com/1897962/208992789-3193e19b-a683-4be5-bc4b-366d16e832d2.png)

**Comment by donhwy** [comment]
Nicely done. Thank you!

**Comment by donhwy** [comment]
Maybe you could also add a notification that updates are available to the bell icon?

Thanks again.

**Comment by votdev** [comment]
> Maybe you could also add a notification that updates are available to the bell icon?
> 
> Thanks again.

No, but the system information widget is displaying an info when new updates are available.

**Comment by votdev** [comment]
> Without a notification, no display of the number 0 is necessary. This looks a bit strange. Just leave it out, then it fits.
> 
> ![image](https://user-images.githubusercontent.com/76697859/210768306-4f6a79bd-17b8-4320-b5e8-f68863fa7809.png)

Fixed with https://github.com/openmediavault/openmediavault/commit/ffa4b5f500e0a80a72a0c31174b11ffdcf02db7b in next version.
