### ISSUE TITLE
Advanced Gui - Change the Mount Point

### ISSUE THREAD

**Issue by JokerGermany** [openmediavault/openmediavault#1448]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the mount points aren't human readable.
Yes i know i can use symlinks, but it would be cool if you could change the mountpoint in the gui

**Describe the solution you'd like**
(If you enabled Advanced Gui) there is another input-box under #/storage/filesystems/mount , where you can add an custom mountpoint.

**Describe alternatives you've considered**
symlink or hacky change the /etc/fstab

**Comment by votdev** [comment]
This issue is closed because the UI provides solutions (e.g. copy path to clipboard) to work with the uncomfortable mount paths.
The first priority of mount point handling is to ensure there will be no conflicts. Allowing the user to manage them lowers that top priority.

**Comment by JokerGermany** [comment]
Okay my usecase:
I will add many mounts on my own.
e.G. /media/cloud for nextcloud.
I can add this in the fstab, but the omv-webgui will ignore manual added mountpoints.

**Comment by ryecoaaron** [comment]
You are doing it wrong for docker then.  Create a sharedfolder in the web interface, get its full mount point from the web interface, and then use the symlinks plugin to add a docker symlink (ie /srv/docker).  When you enter the path for docker, all you have to do is enter /srv/docker/homeassistant, /srv/docker/nextcloud, /srv/docker/matrix.
