### ISSUE TITLE
MergerFS not properly uninstalled

### ISSUE THREAD

**Issue by dt-dev** [openmediavault/openmediavault#1449]
After the uninstall of mergerfs, error 500 shows "Internal Server Error" "No file system backend exists for fuse.mergerfs",

Upon reinstalling mergerfs and attempting to create a new mount point, error 500 shows "Failed to execute XPath query '/config/services/mergerfs/pools/pool[uuid=...]

**Comment by votdev** [comment]
This issue is related to an omv-extras.org plugin. Please raise the issue here: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-mergerfs
