### ISSUE TITLE
Beeing able to mount devices in the webgui, which didn't start with `/dev/dm`

### ISSUE THREAD

**Issue by JokerGermany** [openmediavault/openmediavault#1452]
**Is your feature request related to a problem? Please describe.**
I would like to be able to mount devices in the webgui, which didn't start with `/dev/dm`
![grafik](https://user-images.githubusercontent.com/30293477/209484235-b3a0d7a3-c19f-49e5-a141-1d26a028ec11.png)
(The three Filesystems from the top didn't appear in #/storage/filesystems/mount )

**Describe alternatives you've considered**
Using a Terminal, which i have to at the moment

**Comment by JokerGermany** [comment]
After reboot they good a /dev/dm name

**Comment by votdev** [comment]
Would be interested to find out why the device files are not created. Is udev acting correctly? Is it something else that is not triggered? Is it a kernel issue?

**Comment by JokerGermany** [comment]
> Would be interested to find out why the device files are not created. Is udev acting correctly? Is it something else that is not triggered? Is it a kernel issue?

The think was that this was the corresponding pvs weren't detected because they were lvs.
I had to change `scan_lvs=0` to `scan_lvs=1` in /etc/lvm/lvm.conf
( https://matrix.to/#/#debian:matrix.debian.social/$yoTwf4mUynAZ8Y4OlQ0zmPJsZvCNiahUzvpps7zYKBg?via=matrix.debian.social&via=matrix.org&via=envs.net )
Therefore the vg and the corresponding lvs were activated after boot.

I suppose it wasn't triggered, because it only trigger on boot?

**Comment by ryecoaaron** [comment]
I've never need to change scan_lvs.  If you are going to use LVs created from outside of OMV, you can probably just do a vgscan then lvscan from the command line.
