### ISSUE TITLE
NFS service won't start

### ISSUE THREAD

**Issue by wallart1** [openmediavault/openmediavault#1455]
I looked everywhere on the forum and could not find how to start a post.

**Describe the bug**

A red error pop-up is shown when trying to start the NFS service:
500 - Internal Server Error
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color nfs 2>&1' with exit code '1': debian: ---------- ID: configure_default_nfs-kernel-server Function: file.managed Name: /etc/default/nfs-kernel-server Result: True Comment: File /etc/default/nfs-kernel-server is in the correct state Started: 06:24:11.128349 Duration: 16.089 ms Changes: ---------- ID: configure_nfsd_exports Function: file.managed Name: /etc/exports Result: True Comment: File /etc/exports is in the correct state Started: 06:24:11.144511 Duration: 18.118 ms Changes: ---------- ID: start_rpc_statd_service Function: service.running Name: rpc-statd Result: True Comment: The service rpc-statd is already running Started: 06:24:11.169935 Duration: 16.729 ms Changes: ---------- ID: start_nfs_server_service Function: service.running Name: nfs-server Result: False Comment: Job for nfs-server.service canceled. Started: 06:24:11.187166 Duration: 34.383 ms Changes: Summary for debian ------------ Succeeded: 3 Failed: 1 ------------ Total states run: 4 Total run time: 85.319 ms

**To Reproduce**

1. In the GUI, go to Services -> NFS -> Settings
2. Tick "Enabled". Click on Save. Click the check mark in the yellow banner. Click "Confirm" and "Yes."
3. A large red pop-up appears containing the above text.

**Expected behavior**

NFS starts.

**Screenshots**

![Screenshot from 2022-12-30 06-42-12](https://user-images.githubusercontent.com/84820338/210066711-710a2b0a-29c7-40c3-b11c-868130066893.png)

**Reference to Forum**

(Unable to start a post on the forum.)

**openmediavault Server (please complete the following information):**

- OS version: [uname -a]
![Screenshot from 2022-12-30 06-45-01](https://user-images.githubusercontent.com/84820338/210066935-d03e2cd5-9e3b-4bc4-a41e-fb610e4a1cca.png)

- openmediavault version: [dpkg -l | grep openmediavault]
![Screenshot from 2022-12-30 06-47-52](https://user-images.githubusercontent.com/84820338/210067160-663c98df-6ef7-4d38-9cc3-139c0ff9dd98.png)

**Client (please complete the following information):**

- Device: Desktop
- OS: Linux Mint 20.3
- Browser Brave
- Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)](https://brave.com/latest/)

**Additional context**

I've tried applying all the maintenance (including held-back) updates.
Tried applying the maintenance without the held-back updates.
Tried reinstalling with no maintenance.
Openmediavault is running as a VM in Proxmox VE. 
I am able to share a file system with the SMB/CIFS service. But NFS fails when I try to enable it. Same file system.

**Comment by wallart1** [comment]
Forgot to include the NFS shares I have defined.
![Screenshot from 2022-12-30 06-58-10](https://user-images.githubusercontent.com/84820338/210067988-c94c45eb-2c02-4b00-b67e-228e2cacc2ff.png)

**Comment by ryecoaaron** [comment]
Please update your system.  There have been many releases since 6.0.24 that you get from the install ISO.  This might fix your issue too.

**Comment by wallart1** [comment]
I just now did the update and rebooted omv. Still get a 500 error:
![Screenshot from 2022-12-30 07-20-32](https://user-images.githubusercontent.com/84820338/210069868-57e189d2-b2f0-4439-a269-e2dba9ab8dc1.png)

There are a couple of updates being held back. Should I do an apt upgrade? :

Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages have been kept back:
  linux-image-amd64 openmediavault
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

END OF LINE

**Comment by votdev** [comment]
> There are a couple of updates being held back. Should I do an apt upgrade? :

Sure, the most important package has not been updated which is `openmediavault`.

**Comment by ryecoaaron** [comment]
And please copy and paste error messages from the bell in the top right of the interface.

**Comment by wallart1** [comment]
For some reason, I cannot select or copy anything from the Proxmox console window for OMV. So, I'll have to give you a screen capture instead. Sorry. I did the upgrade and got some suspicious-looking messages at the end: 
![Screenshot from 2022-12-30 10-40-23](https://user-images.githubusercontent.com/84820338/210087915-bc15ebbe-3eea-422a-87ce-c382b2371715.png)

After rebooting OMV:
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color nfs 2>&1' with exit code '1': debian:
----------
          ID: configure_default_nfs-kernel-server
    Function: file.managed
        Name: /etc/default/nfs-kernel-server
      Result: True
     Comment: File /etc/default/nfs-kernel-server is in the correct state
     Started: 10:50:41.979264
    Duration: 17.49 ms
     Changes:
----------
          ID: configure_nfsd_exports
    Function: file.managed
        Name: /etc/exports
      Result: True
     Comment: File /etc/exports is in the correct state
     Started: 10:50:41.996834
    Duration: 19.488 ms
     Changes:
----------
          ID: start_rpc_statd_service
    Function: service.running
        Name: rpc-statd
      Result: True
     Comment: Service rpc-statd is already enabled, and is running
     Started: 10:50:42.023932
    Duration: 74.303 ms
     Changes:
              ----------
              rpc-statd:
                  True
----------
          ID: start_nfs_server_service
    Function: service.running
        Name: nfs-server
      Result: False
     Comment: Job for nfs-server.service canceled.
     Started: 10:50:42.098776
    Duration: 116.801 ms
     Changes:

Summary for debian
------------
Succeeded: 3 (changed=1)
Failed:    1
------------
Total states run:     4
Total run time: 228.082 ms

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color nfs 2>&1' with exit code '1': debian:
----------
          ID: configure_default_nfs-kernel-server
    Function: file.managed
        Name: /etc/default/nfs-kernel-server
      Result: True
     Comment: File /etc/default/nfs-kernel-server is in the correct state
     Started: 10:50:41.979264
    Duration: 17.49 ms
     Changes:
----------
          ID: configure_nfsd_exports
    Function: file.managed
        Name: /etc/exports
      Result: True
     Comment: File /etc/exports is in the correct state
     Started: 10:50:41.996834
    Duration: 19.488 ms
     Changes:
----------
          ID: start_rpc_statd_service
    Function: service.running
        Name: rpc-statd
      Result: True
     Comment: Service rpc-statd is already enabled, and is running
     Started: 10:50:42.023932
    Duration: 74.303 ms
     Changes:
              ----------
              rpc-statd:
                  True
----------
          ID: start_nfs_server_service
    Function: service.running
        Name: nfs-server
      Result: False
     Comment: Job for nfs-server.service canceled.
     Started: 10:50:42.098776
    Duration: 116.801 ms
     Changes:

Summary for debian
------------
Succeeded: 3 (changed=1)
Failed:    1
------------
Total states run:     4
Total run time: 228.082 ms in /usr/share/php/openmediavault/system/process.inc:217
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(170): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(619): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusND...', '/tmp/bgoutputvs...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(192): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}

**Comment by votdev** [comment]
What is the output of `systemctl status nfs-server.service` after you run `systemctl restart nfs-server.service` again? Log the journal via `journalctl -f` while restarting the service to get more details why it is not starting.

**Comment by wallart1** [comment]
Ok. That led me to the issue. I had incorrectly specified one of the extra NFS options on the shares screen.

![Screenshot from 2022-12-30 11-18-28](https://user-images.githubusercontent.com/84820338/210091066-0d21390f-2ba8-433d-8857-857036e69851.png)

Thank you so much for sticking with me, Volker. You are a pleasure to work with.

**Comment by wallart1** [comment]
Thanks,

**Comment by votdev** [comment]
I've checked if it make sense to replace the free text input field with a multi-select dropdown that includes all NFS options to prevent typos, but cancelled that idea because there are too much options + options like xxx=yyy.
