### ISSUE TITLE
How to Remount and Reshare a Previous OMV6 Drive

### ISSUE THREAD

**Issue by schoonersoldier** [openmediavault/openmediavault#1460]
Hi All,

I have a drive that I created to shared directories on and moved files across to.  Unfortunately the Pi I was using stopped working as did the SD Card.  I have now created a new image and installed omv6 but not sure how to reinstall my drive that has existing shares on it?  Any help or pointing in the right direction of the help would be appreciated.

Thankyou

**Comment by ryecoaaron** [comment]
Better to ask on the forum because it has been covered many times.  But mount it in the filesystems tab and create new sharedfolders selecting folder in the directory chooser.  You might have to fix permissions if the users you create have different user ids.

**Comment by schoonersoldier** [comment]
> Better to ask on the forum because it has been covered many times. But mount it in the filesystems tab and create new sharedfolders selecting folder in the directory chooser. You might have to fix permissions if the users you create have different user ids.

Ah sorry I thought this was a forum :-(

**Comment by ryecoaaron** [comment]
https://forum.openmediavault.org/wsc/

**Comment by votdev** [comment]
Closed because this is not a feature request nor a bug report.
