### ISSUE TITLE
Guide for "Install on running Debian 11" doesn't block install on a Desktop environment

### ISSUE THREAD

**Issue by cravas** [openmediavault/openmediavault#1462]
**Describe the bug**

As explained on the forum thread (follow link below):
Following the method you created to install OMV6 on a running Debian 11 distro, the method still installs OMV with a Desktop environment running.

**To Reproduce**

See the below link to the forum thread to reproduce it.

**Expected behavior**

OMV installation should come to a stop.

**Screenshots**

Posted on the forum thread.

**Reference to Forum**

[URL link to forum post]
(https://forum.openmediavault.org/index.php?thread/45790-guide-for-install-on-running-debian-11-doesn-t-block-install-on-a-desktop-enviro/&postID=334302#post334302)

**openmediavault Server (please complete the following information):**

- OS version: [uname -a] Linux deb-desktop 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux

- openmediavault version: [dpkg -l | grep openmediavault] root@deb-desktop:~# dpkg -l | grep openmediavault
ii  openmediavault                       6.1.4-2                          all          openmediavault - The open network attached storage solution
ii  openmediavault-keyring               1.0                              all          GnuPG archive keys of the OpenMediaVault archive

**Comment by ryecoaaron** [comment]
We know.  Not a bug.  Commented on the forum post.
