### ISSUE TITLE
Scheduled SMART tests timing depends on SMART polling interval

### ISSUE THREAD

**Issue by wtangerine** [openmediavault/openmediavault#1466]
**Description**
When SMART polling interval (Storage->Disks->SMART->Settings->Check interval) is set too high, scheduled SMART tests will not run anywhere near their intended time. A user who tests this (such as myself) will be confused why the scheduled tests are not running.

**Steps to reproduce the behavior:**
1. Set a scheduled SMART test to run in the next hour.
2. Set "Check interval" to some high value such as 86400 (once a day)
3. The test will not run in time

**Expected behavior**
The test is expected to run at the time to which it is set.

**openmediavault Server:**

- OS version: 
> Linux omv 6.0.0-0.deb11.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19) x86_64 GNU/Linux

- openmediavault version: 6.1.4-2

**Client (please complete the following information):**

- Device: Windows PC
- OS: Windows 7
- Browser: Chrome 108.0.5359.73

**Additional context**
I had to waste a few hours researching this and eventually read the manual for smartd.conf to find out about this behavior. IMO this is unexpected behavior from a user's point of view, so this should either get fixed, or at least there should be a clear warning about it in OMV GUI.

Quote from smartd.conf manual:

>               Scheduled  tests  are  run  immediately  following  the  regularly-scheduled device
>               polling, if the current local date, time, and test type, match REGEXP.  By  default
>               the  regularly-scheduled  device polling occurs every thirty minutes after starting
>               smartd.  Take caution if you use the '-i' option to make this polling interval more
>               than  sixty  minutes:  the  poll times may fail to coincide with any of the testing
>               times that you have specified with REGEXP.  In this  case  the  test  will  be  run
>               following the next device polling.

**Comment by votdev** [comment]
What do you suggest to use as max. value? 60 mins?

**Comment by wtangerine** [comment]
> What do you suggest to use as max. value? 60 mins?

I'm new to OMV and to custom NAS building so I may be missing something, but IMO this option is not necessary to expose in the GUI to begin with. It could be exposed for an advanced user through the config file and without max limit, but with a clear warning about the possible unintended effect it has on SMART tests timing. If that's not a good option, I guess 60 mins max value limit is reasonable (but then advanced users in certain edge cases may be unhappy), and a warning in the GUI (otherwise a user will expect the test to run at the time they specified and may still have to waste much time troubleshooting).

That said, considering this is caused by upstream limitation in smartd, IMO ideally the feature would be re-implemented in OMV through cron.
