### ISSUE TITLE
Installer doesn't support USB keyboards

### ISSUE THREAD

**Issue by danhuss** [openmediavault/openmediavault#147]
After selecting "install" on the light blue "OpenMediaVault" splash screen menu, the installer doesn't seem to work with a standard USB keyboard. I'm able to continue after breaking out my old-school PS/2 keyboard (thank goodness for legacy compatibility...)

**Comment by donhwy** [comment]
There were often settings in older bios for usb support. Maybe you could check that.

**Comment by danhuss** [comment]
How old are you talking, the motherboard I'm using was purchased new in 2014. The odd thing is the keyboard works fine in the light blue boot menu, but doesn't work once I get to the dark blue and grey "Select a Language" menu.

**Comment by ryecoaaron** [comment]
Is the usb keyboard plugged into a usb3 port?

**Comment by danhuss** [comment]
I get the same problem trying to install Debian 9.5 the same way.

**Comment by fab0l1n** [comment]
If anyone comes across this, try usb3. For me usb2 has been more reliable during installations in the past, but this time it was the other way around.
