### ISSUE TITLE
SSK/TLS LDAP DIRECTORY SERVICE

### ISSUE THREAD

**Issue by informaticavera** [openmediavault/openmediavault#1471]
Hello everyone and sorry for my english from the online translator.
I am trying to configure the section "Access permissions / Directory Service"
I want to activate ssl but omv shows an error when applying the changes.
It seems that it adds in smb.conf the ssl option with single quotes

OMV VERSION
openmediavault-omvextrasorg         5.6.6  

SO VERSION
Debian GNU/Linux 10 (buster)

Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color samba 2>&1' with exit code '1': debian:
ID: configure_samba_global_ldap
Function: file.append
Name: /etc/samba/smb.conf
Result: True
Comment: Appended 10 lines
Started: 12:33:54.038344
Duration: 16.069 ms
Changes:
----------

diff:

---

+++

@@ -46,3 +46,13 @@

.........

+#======================= LDAP Settings =======================

+security = user

+passdb backend = ldapsam:ldap's'://ldap.vera.es:636

......

**Comment by votdev** [comment]
Hmmm, which plugin do you use add LDAP support? This is not part of any openmediavault plugin. I also did not find any omv-extras.org plugin.

Please also note that OMV5 is not maintained anymore because it is EOL (End-Of-Life). Consider to migrate to OMV6.

**Comment by informaticavera** [comment]
For LDAP I used an OMV5 plugin but I see that it is not available in OMV6.

I have updated, and configured LDAP from the terminal directly. That's how it seems to work.
Thanks
