### ISSUE TITLE
Add CONFIG_PERF_EVENTS in kernel config

### ISSUE THREAD

**Issue by xingoxu** [openmediavault/openmediavault#1475]
**Is your feature request related to a problem? Please describe.**
I want to use `intel_gpu_top` from `intel-gpu-tools` package but it fails since `CONFIG_PERF_EVENTS` is not enabled at kernel config.

**Describe the solution you'd like**
Is it possible to add this in the kernel config or is there an alternative method to enable this on a running omv machine?

**Describe alternatives you've considered**
Recompile the kernel and set this in the boot menu.

**Additional context**
Nothing

**Comment by votdev** [comment]
I'm sorry, but the openmediavault project does not maintain or build the kernel packages itself, the Debian project or alternatively the ARM based derivates are responsible for that.
