### ISSUE TITLE
SSH server got broken after enabling rsync server

### ISSUE THREAD

**Issue by gcevikschwibbe** [openmediavault/openmediavault#1476]
After enabling the rsync-Server I saved my configuration and SSHD got broken.
Now I am unable to establish SSH connections anymore:

```
systemd[1]: Stopping OpenBSD Secure Shell server...
systemd[1]: ssh.service: Succeeded.
systemd[1]: ssh.service: Unit process 17305 (sshd) remains running after unit stopped.
systemd[1]: ssh.service: Unit process 17306 (sshd) remains running after unit stopped.
systemd[1]: Stopped OpenBSD Secure Shell server.
systemd[1]: ssh.service: Found left-over process 17305 (sshd) in control group while starting unit. Ignoring.
systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
systemd[1]: ssh.service: Found left-over process 17306 (sshd) in control group while starting unit. Ignoring.
systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
systemd[1]: Starting OpenBSD Secure Shell server...
systemd[1]: ssh.service: Found left-over process 17305 (sshd) in control group while starting unit. Ignoring.
systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
systemd[1]: ssh.service: Found left-over process 17306 (sshd) in control group while starting unit. Ignoring.
systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
```

Version
6.1.9-1 (Shaitan)

Processor
ARMv7 Processor rev 3 (v7l)

Kernel
Linux 5.15.84-v7l+

**Comment by gcevikschwibbe** [comment]
And the Browser console exposes questionable internals to the Webapp User:
![grafik](https://user-images.githubusercontent.com/123869122/215322776-70b42585-523e-43e4-9799-bc0b57717559.png)

**Comment by votdev** [comment]
> And the Browser console exposes questionable internals to the Webapp User:

@hgschwibbe What do you think is questionable about this?

Why did you use a different GH account this time? Could it be because you always write so disparagingly? But maybe it just comes to me that way.

Unfortunately, I cannot reproduce the problem you describe. As a consultant, however, you should expect to know how to write error reports. So, what exactly do i have to configure to reproduce this issue?

**Comment by votdev** [comment]
BTW, you can copy the full error trace to clipboard in the notification side-bar. This is the first step that helps to debug the issue. And that is the reason why this `questionable` internals are forwarded to the UI; to help debugging the issues users might have. And be sure, there are no really important informations in there.

**Comment by gcevikschwibbe** [comment]
> > And the Browser console exposes questionable internals to the Webapp User:
> 
> @hgschwibbe What do you think is questionable about this?
> 
> Why did you use a different GH account this time? Could it be because you always write so disparagingly? But maybe it just comes to me that way.
> 
> Unfortunately, I cannot reproduce the problem you describe. At the job you do, however, you should expect to know how to write error reports. So, what exactly do i have to configure to reproduce this issue?

Because I am using the laptop from my wife, and credentials of the other GH account are stored in the password manager of the other computer.

**Comment by gcevikschwibbe** [comment]
> BTW, you can copy the full error trace to clipboard in the notification side-bar. This is the first step that helps to debug the issue. And that is the reason why this `questionable` internals are forwarded to the UI; to help debugging the issues users might have. And be sure, there are no really important informations in there.

I can see all passwd user names in the browser console. Do you really think that this is not security relevant?

**Comment by votdev** [comment]
> > BTW, you can copy the full error trace to clipboard in the notification side-bar. This is the first step that helps to debug the issue. And that is the reason why this `questionable` internals are forwarded to the UI; to help debugging the issues users might have. And be sure, there are no really important informations in there.
> 
> I can see all passwd user names in the browser console (/varlib/openmediavalut/authorized_keys/[username]). Do you really think this is not security relevant?

No, because this only happens as admin user and second there is no different to running a RPC which exposes the list of users to the UI.

**Comment by votdev** [comment]
Please provide the necessary information how to reproduce this issue or try to find it out yourself and share your knowledge how to improve OMV so that all other users can benefit from that.

**Comment by hgschwibbe** [comment]
As far as I remember I also added a User when I configured the rsync deamon, thats all.

What finally puts me off is the fact that the browser makes a bunch of requests to the backend even if you just change a simple checkbox. Maybe that's the reason for the side effects I've been able to experience so far. 

I saved the configuration files and made a fresh installation without OMV. I will continue with the command line and htop as my dashboard. With that I have more control about the changes. 

I wish you good luck to solve your issues.

**Comment by hgschwibbe** [comment]
A so called "Pending Change" should be an atomic operation.

If you trigger a bunch of requests for each pending change, you don't have an atomic design system anymore. Depending on the network latency requests could be received and processed in a different order. And that could lead to side effects at the end which are very hard to reproduce.

If you want to get this thing stable you should follow the rules of an atomic design system. This means:
- A pending change is one and only one request to the server.
- A set of pending changes is one request to the server that holds the list of pending change in proper order.
