### ISSUE TITLE
Open Media Vault black screen when going on the services tab - Firefox

### ISSUE THREAD

**Issue by vag34** [openmediavault/openmediavault#1478]
In today's update using Firefox I can't use the services.

Is there anything else I can provide?

Maybe due to my short time it takes to reply or see this topic.

https://photos.app.goo.gl/xWma7rw4YLS9mkka9

**Comment by votdev** [comment]
Please follow the instructions that the (red) error message suggests to fix the caching issue. Simply clear the browser cache or press Ctrl-Shift-R or Ctrl-F5 to force a hard reload of the page.
