### ISSUE TITLE
Installer requires CD-ROM when installing from USB drive.

### ISSUE THREAD

**Issue by danhuss** [openmediavault/openmediavault#148]
After selecting language and keyboard layout, the installer displays a "No CD-ROM Device Found" error message when detecting hardware and is unable to proceed with the installation.

**Comment by donhwy** [comment]
Again check your bios settings.

**Comment by danhuss** [comment]
I'm fairly sure I went through every permutation of boot option in the BIOS. I also tried two different USB drives 3 different software to "burn" the ISO to USB.

**Comment by danhuss** [comment]
yeah, I get the same problems trying to install Debian 9.5

**Comment by danhuss** [comment]
In case anyone is needing some closure, I broke down and went all 2009 and burned a CD for the install.
