### ISSUE TITLE
Portainer fails to start with the update to docker 23.0.0

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [openmediavault/openmediavault#1483]
With the update to docker 23.0.0, portainer fails to start up, which makes all containers configured with it not starting and with that unusable.
I tried to reinstall which pulled the latest version but it failed to start up:

![Bildschirmfoto vom 2023-02-02 22-14-28](https://user-images.githubusercontent.com/41188546/216452682-24c8c47e-386f-4d8c-958f-05598bd80cc0.png)

When trying to launch the container on the console, I got the following output:

![image](https://user-images.githubusercontent.com/41188546/216454136-c071e0d2-1e89-4e05-b77f-3e7b4b06df9d.png)

The workaround was to install the package apparmor-utils, which also installs apparmor.

Is apparmor now a dependency for portainer to work properly or is there another underlying issue at play here?

If this is the wrong place for this bugreport, please guide me to the right place.

**Comment by ryecoaaron** [comment]
This not an OMV issue.  It is caused by a change in the docker-ce package from the docker repo.  The forum is correct place to mentioning but the issue is already solved - https://forum.openmediavault.org/index.php?thread/46112-docker-not-working-since-omv-upgrade/&postID=337053#post337053

**Comment by Sebastian-Hirsch** [comment]
Okay, thank you for the heads up!
