### ISSUE TITLE
Warning in HomeAssistantdocker start

### ISSUE THREAD

**Issue by rodrigf-hass** [openmediavault/openmediavault#1484]
Home Assistant log:

"Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for openmediavault using this method at custom_components/openmediavault/__init__.py, line 37: hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)"

Home Assistant version: 2023.2.2

**Comment by votdev** [comment]
I'm not aware that openmediavault has a HASS integration.

@ryecoaaron Do you know anything about that?

**Comment by ryecoaaron** [comment]
Nope. I think HA might have some docs on installing with OMV but I don’t use it myself.

**Comment by votdev** [comment]
@rodrigf-hass I'm sorry but the openmediavault project does not maintain an integration or anything else that is related to HASS.
Because of that i'm closing this issue.

**Comment by votdev** [comment]
Maybe you should open the issue here: https://github.com/tomaae/homeassistant-openmediavault
