### ISSUE TITLE
End to End encryption of SMB shares

### ISSUE THREAD

**Issue by Glydric** [openmediavault/openmediavault#1485]
**Describe the solution you'd like**
The SMB 3 allows for AES-128 end2end encryption and seems that samba allows it, why this option is not included into webUI

**Comment by Hukuma1** [comment]
Anyone know if this slows down transfers or significantly adds CPU cycles? Trying to gauge risk vs reward here.

**Comment by ryecoaaron** [comment]
Probably depends on the cpu you are using and how well it uses its encryption features.

**Comment by bauxi** [comment]
For anybody wondering how this can be done:

- On the web interface, go to ``Services`` > ``SMB/CIFS`` > ``Settings``
- In ``Advanced settings`` look for ``Extra options``
- Add the line ``smb encrypt = required``

**Comment by votdev** [comment]
Will be available with `openmediavault 6.3.11`.
