### ISSUE TITLE
Networking configuration failure loop on Arrakis

### ISSUE THREAD

**Issue by unquietwiki** [openmediavault/openmediavault#149]
Debian 9.5.x, running latest Arrakis

Steps to reproduce

1. Have an existing interface configured.
2. Configure another interface.
3. UI will ask to restart to apply changes.
4. Networking will fail to restart; **systemctl restart networking** needed via SSH.
5. UI will continue to ask to apply changes; no matter what has changed in the **/etc/network/interfaces** file.

**Comment by votdev** [comment]
Sadly i'm not able to reproduce this. You or someone else having this troubles need to investigate yourself and hopefully find a solution or better submit a pull request to fix it.

**Comment by unquietwiki** [comment]
@votdev (nods) It looks like you're well on your way with version 5 efforts to have Salt State manage this stuff. I noticed a bunch of config.xml.# files with close times to each other: tried to kill off Nginx + PHP & move those out of the config folder; rebooted the server; still getting the UI request to restart. Is there a way to reset that UI flag?

**Comment by ryecoaaron** [comment]
echo "[]" > /var/lib/openmediavault/dirtymodules.json

**Comment by unquietwiki** [comment]
@ryecoaaron That worked! That should go in the FAQ or something on the website. Thanks. 👍
