### ISSUE TITLE
Please disable write docker source to sourcelist when installing OMV from Debian

### ISSUE THREAD

**Issue by PP88PP** [openmediavault/openmediavault#1492]
**Describe the bug**

When Docker installed before install OMV6.3, OMV installtion will get errors about apt-get update get docker gpg errors. Then some packages setted to install after OMV write Docker to sourcelist will not be installed.

**To Reproduce**

1. Install Docker first
2. Install OMV
3. Get apt-get errors about Docker, then some packages will not able to be installed

**Expected behavior**

OMV's docker cannot succesfully installed to my OS, So I need install the docker manully which not in OMV's source. 

- OS version: Debian Bullseye
- openmediavault version: 6.3.0-2 (Shaitan)

**Comment by ryecoaaron** [comment]
This is not an omv issue.  It is omv-extras - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues.  I doubt this is a bug though.  I would prefer you post on the forum but you can create an omv-extras issue too.
