### ISSUE TITLE
Feature: add support for TPM in LUKS

### ISSUE THREAD

**Issue by neheb** [openmediavault/openmediavault#1493]
**Is your feature request related to a problem? Please describe.**
Most OS encryption is done with TPM instead of passphrases. Except on Linux for some reason...

**Describe the solution you'd like**
TPM used if available. passphrase optional.

**Describe alternatives you've considered**
I mean...not using encryption I guess.

**Additional context**
Saw this recently: https://fedoramagazine.org/automatically-decrypt-your-disk-using-tpm2/

**Comment by votdev** [comment]
Please raise the request [here](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption). This plugin is not maintained by the openmediavault project.

**Comment by neheb** [comment]
OK
