### ISSUE TITLE
Web GUI not working after update 6.3.0-2

### ISSUE THREAD

**Issue by Stiff609** [openmediavault/openmediavault#1495]
Web GUI not working after update 6.3.0-2. There was a version 6.3.0-1.
After the update, the inscription "Loading ..." is constantly on the start page. This happened on a physical NAS. On a virtual NAS with the same update went fine.

**Comment by votdev** [comment]
Have you tried to clear the browser cache or pressed `Ctrl-Shift-R`?

**Comment by Stiff609** [comment]
> Have you tried to clear the browser cache or pressed `Ctrl-Shift-R`?
Yes.

ssh access is enable.  
```
systemctl status openmediavault-engined.service -l
nas06 systemd[1]: Starting The OpenMediaVault engine daemon that processes the RPC request...
nas06 systemd[1]: openmediavault-engined.service: Supervising process 699 which is not our child. We'll most likely not notice when it exits.
nas06 systemd[1]: Started The OpenMediaVault engine daemon that processes the RPC request.
```

**Comment by votdev** [comment]
I don't know how you access the NAS via browser, but is it possible that the IP address has changed? But i don't think that is it because you can SSH your box.

Try running `omv-salt deploy run nginx phpfpm` from CLI.

**Comment by Stiff609** [comment]
> Try running `omv-salt deploy run nginx phpfpm` from CLI.

thank you! This command it worked. Thank you very much.
