### ISSUE TITLE
Add snapshot retention management

### ISSUE THREAD

**Issue by votdev** [openmediavault/openmediavault#1498]
Add settings to manage how log snapshots are retained or how many snapshots are kept.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Manfred-Knick** [comment]
Add setting to alter snapshot naming.

BACKGROUND:
Exporting /srv/dev-disk-by-uuid-...../.snapshots as a SMB/CIFS share,
Windows is not able to digest the two ":" colons used in the ISO 8601 time part of the snapshot name;
the Windows Explorer creates a crippled random for display.
Furtheron, all snapshots are displayed with one identical date of change = date of creation.
==> The Windows user is *not* able to identify the correct snapshot he is searching for.

Changing the ":" separator to "-" like in the date part would circumvent this (M$) problem.

P.S.:
THANKS!
Working great!

**Comment by votdev** [comment]
Added with https://github.com/openmediavault/openmediavault/commit/73b58e57f7c101f6558aa85d6064eb994738701c
