### ISSUE TITLE
Integrate an option to set a retention time/amount for BTRFS snapshots

### ISSUE THREAD

**Issue by MeisterHeinz** [openmediavault/openmediavault#1499]
**Is your feature request related to a problem? Please describe.**
Using the newly integrated snapshot function for BTRFS volumes is great, specially the scheduled snapshots. But when using scheduled snapshots, I dont see any options to automatically let snapshots be purged after a specific amount of snapshots or after a set time. So the list of snapshots will get full fast.

**Describe the solution you'd like**
A setting to let OMV delete snapshots after a given time or after a specific number of snapshots, if possible per type of snapshot (as an example: Keep 12 monthly snapshots, keep 52 weekly snapshots, 7 daily....)
I am familiar with the solution from NetApp, there you can create retention policies and attach them to schedules respectively volumes.

**Describe alternatives you've considered**
At this time one must manually delete snapshots

**Additional context**
-

**Comment by ryecoaaron** [comment]
Duplicate of #1498

**Comment by MeisterHeinz** [comment]
> Duplicate of #1498

Thank you, sorry for not searching properly.
