### ISSUE TITLE
Arrakis: home folder in passwd points to disk-by-label instead of sharedfolder

### ISSUE THREAD

**Issue by etique57** [openmediavault/openmediavault#150]
Hello,

In the Users panel, I activated the Home folder and selected the sharedfolder for my homes.

But when I look into the passwd file, the home folder path is actually using the /disk-by-label/ path which I think is wrong, as it should point to the sharedfolder path (which is abstracted from the actual disk).

Do you agree?

**Comment by votdev** [comment]
Yes, you're right.

**Comment by votdev** [comment]
If the passwd file looks like ``test:x:1001:100::/srv/dev-disk-by-id-ata-VBOX_HARDDISK_VB1b48a528-ee51de1a-part1/home/test:/bin/dash`` then everything is ok.

**Comment by etique57** [comment]
Hi @votdev 

Yes, it does. But shouldn't it look like /sharedfolders/Home/ instead?

**Comment by votdev** [comment]
> But shouldn't it look like /sharedfolders/Home/ instead?

No. The path /sharedfolders should only be used by user scripts, nothing else.

**Comment by etique57** [comment]
Ok then I'll change it manually because I still don't think it's correct :)

**Comment by ryecoaaron** [comment]
In my opinion, your home folder should never point to a bind mount.
