### ISSUE TITLE
Add settings to alter snapshot naming

### ISSUE THREAD

**Issue by Manfred-Knick** [openmediavault/openmediavault#1500]
**Is your feature request related to a problem? Please describe.**
BACKGROUND:
Exporting /srv/dev-disk-by-uuid-...../.snapshots as a SMB/CIFS share,
Windows is not able to digest the two ":" colons used in the ISO 8601 time part of the snapshot name,
being a "not-allowed" character in Windows file naming conventions.
Instead, the Windows Explorer substitutes a crippled random replacement for display.
Furtheron, all snapshots are displayed with one identical date of change = date of creation.

==> The Windows user is not able to identify the correct snapshot he is searching for.

**Describe the solution you'd like**
Multiple selectable options, or a configurable option
E.g.:
Changing the ":" separator to (e.g.) "-" like in the date part would circumvent this (M$) problem.
Another alternative configuration could be to omit "-" and ":" completely, resulting in a name ending as
. . . . . _yyyymmddThhmmss

**Describe alternatives you've considered**
To me, "File-name character translation" files referred-to by registry elements 
do not shine as a viable workaround.

**Additional context**
 Invalid filenames on Windows:
    The filename doesn’t contain any of the following characters: 
" (double quote), 
* (asterisk), 
* < (less than), 
* > (greater than), 
* ? (question mark), 
* \ (backslash), 
* | (pipe), 
* / (forward slash), 
* : (colon) <-------------------------------------!

**Comment by votdev** [comment]
> Changing the ":" separator to (e.g.) "-" like in the date part would circumvent this (M$) problem

This is not supported by ISO 8601. I will not use a naming scheme that is not standardized.

> Another alternative configuration could be to omit "-" and ":" completely, resulting in a 
> name ending as . . . . . _yyyymmddThhmmss

This is the ISO 8601 basic format. Looks a little bit weird and makes the date/time really unreadable, but if Windows does not like it, there is no alternative.
