### ISSUE TITLE
[FR] Add a preclear function/plugin for new HDDs

### ISSUE THREAD

**Issue by Hukuma1** [openmediavault/openmediavault#1504]
**Is your feature request related to a problem? Please describe.**
Unraid has a plugin called [Unassigned Devices Preclear](https://forums.unraid.net/topic/120567-unassigned-devices-preclear-a-utility-to-preclear-disks-before-adding-them-to-the-array/). It stress tests a new HDD to find any issues with it that might lead to premature death of a drive. The idea is you catch errors before you add any data to it, presumably within your return purchase window as well. Would love for OMV to gain this ability to make my NAS data safer.

**Describe the solution you'd like**
A function or plugin that does the same 5-stage testing of any new drive that you add to OMV.

**Describe alternatives you've considered**
Running Unraid 30-day trial off a flash drive via USB-passthrough to a VM. It's... doable, but seems very silly just to have this ability.

**Additional context**
As of 2021, [the Bathtub curve is less relevant](https://www.backblaze.com/blog/drive-failure-over-time-the-bathtub-curve-is-leaking/), but it still doesn't mean we can't catch early duds in our systems before we add crucial data to them.

**Comment by ryecoaaron** [comment]
secure wipe and smart long test are already available.  Both would be good tests to find a drive that is going to fail in its first hours.

**Comment by Hukuma1** [comment]
I have not used those methods, but does it do the same thorough test? Preclear almost took 60 hours on my 14TB drive as a comparison.

**Comment by ryecoaaron** [comment]
The secure wipe basically does the same but no verified reads after.  Doing a secure wipe and then a long smart test might take a similar amount of time and be just as informative.

**Comment by Hukuma1** [comment]
I see. Would it be feasible to link the functions to a single button and adding the read part perhaps? So wipe + read + long smart test. Right now it seems to be all sprawled out if I'm not mistaken? Or is there a different way to do it?

`Home -> Storage -> Disks -> Wipe`

`Home -> Storage -> S.M.A.R.T. -> Scheduled Tasks -> Create -> Long self-test`

**Comment by ryecoaaron** [comment]
Personally, I don't think it is worth the effort.  Most people aren't going to use it and if they do, they are going to complain that they can't use their RPi for a week.  I have never done this at home or work.  I do a quick wipe and start using the new drive.  How often are you buying new disks?

**Comment by Hukuma1** [comment]
Maybe I'm confused. On an RPi you wouldn't be doing this, as you probably aren't linking high capacity drives to begin with? Are people daisy-chaining some USB HDDs or something to their Pi? I run my OMV off an NVMe drive on a SFF PC. And either shuck my additional drives out of said enclosures, or just buy enterprise-grade drives to begin with.
 
Can't speak for others, but I surely would trade a week (note: probably 4 days, not 7) of not being able to use my new 18TB drive in my NAS for 6+ years of peace of mind. Seems like a no-brainer trade. But again, everyone's use case is different as you pointed out.

**Comment by ryecoaaron** [comment]
I have an 18tb drive on one of my RPis.  It was just an example of a slow system.

I honestly think this test is only going to find a small percentage of early failures and won't find any mid to longer term failures.  I haven't changed my new hard drive process for 25+ years.

But anyway, I was just giving an alternative.  I don't have time to write this plugin and no one is lining up to write them.

**Comment by votdev** [comment]
Such long running tasks should be done via CLI IMO. Depending on your settings the UI will log you out automatically before it reaches the end of the task. This will surely confuse users as well. Because of that, please use the CLI.

**Comment by votdev** [comment]
I'll close this issue because it does not make sense to me. One reason is that I don't want to invest time in a feature that hardly anyone uses and which can lead to UX problems.

**Comment by votdev** [comment]
For those who want to contribute this function to OMV community as a plugin, you can see what the Unraid plugin looks like [here](https://github.com/dlandon/unassigned.devices).
