### ISSUE TITLE
Missing file systems

### ISSUE THREAD

**Issue by Lehmeiers** [openmediavault/openmediavault#1505]
Good day!
I would like it if file systems like exfat, fat32, ntfs could be used. Readable and writable, because most sticks and external hard drives use these. They are preformatted with them.

Because if I want to mount a data carrier under OMV, then I first have to copy the data (which takes a long time) and possibly restore it again, and only then can I use it.
If this data medium is only intended for exchange, there is another problem. 
The Linux file systems, for example, are not readable by most desktop systems, so if a USB stick is only to be synchronised, then it makes sense that these file systems are supported by OMV - readable and writable.
It is also an advantage, because if I want to develop OMV for users only, then I should also use what the normal user also uses at home.

For example, I have 5 different external WD Elements hard drives (4 x 4TB + 1 x 8 TB) in use, which were formatted with these file systems (for various reasons).
Unfortunately, I now have to copy all the data first and then reconnect it to OMV, which takes at least 1 -2 weeks because my computer only uses USB 1 and USB 2.
If I had been able to attach and read them all then I would empty an external hard drive and format it with ext4 and then copy one disk over after the other and then format the disk again and copy the next one over or then copy the data back again. depending on how I need the disks.

In any case, an extension of the file systems is desirable and would increase the acceptance of OMV even more.

Many thanks in advance.

Sincerely, R.Lehmeier

Translated with www.DeepL.com/Translator (free version)

**Comment by votdev** [comment]
> I would like it if file systems like exfat, fat32, ntfs could be used. Readable and writable,
> because most sticks and external hard drives use these. They are preformatted with them.

All those filesystems are supported by OMV and can be mounted in the filesystem page. The only problem with those filesystems is that they are not POSIX compliant. OMV is using POSIX features for file permission. So if you are using non-POSIX filesystems with OMV, then you might run into problems, e.g. users can not access files that are shared via services like SMB or FTP.

> The Linux file systems, for example, are not readable by most desktop systems, so if a USB 
> stick is only to be synchronised, then it makes sense that these file systems are supported 
> by OMV - readable and writable.

Normally, a NAS is operated with storage devices that are permanently installed in a system for this purpose only. OMV's design concept does not support this temporary connection of storage devices at all. Data is exchanged via services like SMB, FTP, rsync, ... or alternatively there is a plugin that allows you to sync data between the permanent storage devices and temporary attached USB devices.

**Comment by votdev** [comment]
I'm closing this issue because:

- A NAS is ment to host permanent storage devices.
- [Non-POSIX filesystems are already supported](https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/usr/share/php/openmediavault/system/filesystem/backend), but it is suggested not to use them because they might cause problems. OMV is heavily using POSIX features that are only supported by Linux filesystems.
