### ISSUE TITLE
error processing package openmediavault-diskstats (--remove)

### ISSUE THREAD

**Issue by marfier** [openmediavault/openmediavault#1508]
I am trying to reinstall OMV, but I'm getting an error when trying to remove openmediavault-diskstats (required for the reinstall).

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  openmediavault-diskstats
The following packages will be upgraded:
  openmediavault
1 upgraded, 0 newly installed, 1 to remove and 9 not upgraded.
1 not fully installed or removed.
Need to get 0 B/2600 kB of archives.
After this operation, 105 kB disk space will be freed.
Do you want to continue? [Y/n] y
Reading changelogs... Done
Preconfiguring packages ...
(Reading database ... 45494 files and directories currently installed.)
Removing openmediavault-diskstats (6.0.2-1) ...
dpkg: error processing package openmediavault-diskstats (--remove):
 installed openmediavault-diskstats package post-removal script subprocess returned error exit status 1
dpkg: too many errors, stopping
Errors were encountered while processing:
 openmediavault-diskstats
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Context: https://forum.openmediavault.org/index.php?thread/46570-omv-firstaid-wiped-config-now-getting-fatal-error-4-document-is-empty-line-1-col/&postID=341311#post341311

**Comment by votdev** [comment]
Can not reproduce this:

- Uninstall plugin via UI. Install it again via UI.
- Run `apt-get install --reinstall openmediavault-diskstats`

**Comment by votdev** [comment]
Please exactly describe step-by-step how to reproduce this issue.

**Comment by marfier** [comment]
>     * Run `apt-get install --reinstall openmediavault-diskstats`
That command seems to have managed to reinstall `openmediavault` metapackage, but now when I log in to the UI and try to do anything (e.g. enable SMB), I get this error.

```
 500 - Internal Server Error
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color avahi 2>&1' with exit code '1': DataVault.home.arpa: Data failed to compile: ---------- Rendering SLS 'base:omv.deploy.avahi.services.filebrowser' failed: Jinja error: 'NoneType' object has no attribute 'get_dict' Traceback (most recent call last): File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl output = template.render(**decoded_context) File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1090, in render self.environment.handle_exception() File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 832, in handle_exception reraise(*rewrite_traceback_stack(source=source)) File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 28, in reraise raise value.with_traceback(tb) File "<template>", line 20, in top-level template code File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 465, in call return __context.call(__obj, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__ return self.loader.run(run_func, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, i... 
```

Reinstalling OMV after accidentally wiping the config (mysterious omv-firstaid option 6 bug, couldn't reproduce again) seemed to have been a mistake. Should I have replaced it with the default config (as someone in the forum advised)?

**Comment by votdev** [comment]
> That command seems to have managed to reinstall `openmediavault` metapackage, and the UI seemed functional again, but now when I log in to the UI and try to do anything (e.g. enable SMB), I get this error.
> 
> ![image](https://user-images.githubusercontent.com/47502020/224203870-51fd6247-a240-4cb1-8f1e-ffc263367dab.png)
> 

This looks to me like there are PIP packages installed that shouldn't be. Please check https://docs.openmediavault.org/en/stable/various/apt.html#installing-software for more information.
Undoing this is difficult, i think searching the forum will help.

**Comment by marfier** [comment]
Could there be a way to fully reinstall OMV without reinstalling the OS?
