### ISSUE TITLE
File systems - disks by label, wrong file system mounted and second can not be mounted

### ISSUE THREAD

**Issue by simpletasks** [openmediavault/openmediavault#151]
Running OMV 4.1.3 as VM on virtualbox (on Ubuntu 16 LTS host). Using two additional drives for storage, both with three partitions. On each HDD partitions have same names/labels (first, second,third). I used VB ability for raw HDD and mounted created VMDK into OMV VM. HDDs are presented properly under "Storage > Disks". Also all partitions are listed on "Storage > Filesystems" in OMV web gui.
But when mounting, say, "first" partition from first drive OMV sometimes shows that "first" partition on second HDD was mounted. And when I try to mount "first" partition that is not mounted I get message like on picture:
![omv-partition-by-label-error-1](https://user-images.githubusercontent.com/27790652/43370048-59d695ee-9378-11e8-8a69-0bc9ea8a3ab6.png)

IMO at least device name plus partition label should be unique.

**Comment by votdev** [comment]
What do you expect when a filesystem label exists multiple times? This is normal behavior of the Linux kernel/userland stack, OMV has nothing to do here. Remove the duplicate labels to fix that.

**Comment by simpletasks** [comment]
Thank you for response. I know linux as much I needed for some problem. I red about labels now and checked states on my pcs. I wonder how I never have disk labels overlapping problem ? (I'll rename just to be safe)
Using/showing labels is indeed user friendly and IMHO it should stay in OMV, but improved. Please reconsider adding check (or warning) if same label is used for more than one partition and leave that partition disabled in OMV (quarantine). But in code behind rely on UUID.
BR

**Comment by petcol** [comment]
I had a similar problem from old USB External Hard Drives of the same manufacturer.  Their LABEL were the brand of the device not the manufacture of the HDD which was a different drive for each.
I used :
ntfslabel  /dev/sde3  <NEW_LABEL_NAME>

All works fine and I didn't loose any data
