### ISSUE TITLE
Integrate new BTRFS possibilities with Snapraid plugin

### ISSUE THREAD

**Issue by rjwonder** [openmediavault/openmediavault#1510]
**Is your feature request related to a problem? Please describe.**
Not a problem, it just would be nice if it would be integrated. Then Snapper would not be needed and snapraid-btrfs(-runner) would not be needed

**Describe the solution you'd like**
- Snapraid to put content file in btrfs subvolume
- OMV scheduled snapshots (/srv/disk..../ as shared folder) as RO
- Snapraid plugin to pick up the latest full disk snapshot in daily sync
- Shared folders should get the option to not be created as BTRFS subvolume - otherwise that folder would be excluded automatically by BTRFS when creating a snapshot of the /srv/disk-.../ folder

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.
- https://github.com/automorphism88/snapraid-btrfs runs by using snapper. It works, but in OMV GUI would be nice
- https://github.com/fmoledina/snapraid-btrfs-runner provides the script around it for DIFF, email, etc

**Additional context**
None

**Comment by votdev** [comment]
There are no plans to support that.

The snapshot feature is ONLY planned and implemented to work with shared folders. There were never any plans to support snapshots of the parent file system, therefore the design how subvolumes are used is as it is.

Snapshots of shared folders are writeable by intention to easily create new shared folders of them. Read-only access can be configured via ACL or roles.

**Comment by rjwonder** [comment]
ok, understood. What about the possibility to optionally **not** create a subvolume (= loose snapshot possibility for that folder) when creating a shared folder on btrfs?

**Comment by votdev** [comment]
> ok, understood. What about the possibility to optionally **not** create a subvolume (= loose snapshot possibility for that folder) when creating a shared folder on btrfs?

I'm sorry, this is not an option because this will require additional checks in the UI and the whole snapshot logic if the shared folder is a subvolume or not.

**Comment by rjwonder** [comment]
thanks for explaining the OMV thoughts around this topic!

I agree that backup in the backup does not make a lot of sense so it's good the BTRFS stops when it encounters other subvolumes.
