### ISSUE TITLE
acme/certbot integration

### ISSUE THREAD

**Issue by simonmcnair** [openmediavault/openmediavault#1511]
It would be nice if the SSL cert could be autoupdated I've seen a couple of people implement it but it never looks very maintainable.

A plugin or better still core functionality would be awesome :-)

Just an idea.

**Comment by ryecoaaron** [comment]
There was a [plugin](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-letsencrypt) but it is difficult to maintain and even more difficult to provide some functionality.

If you install certbot and configure it, it would be very easy to create a wrapper script in /etc/letsencrypt/renewal-hooks/deploy/ to call my [update_cert](https://github.com/ryecoaaron/scripts/blob/main/update_cert.sh) script.  One time command line configuration and you wouldn't have to touch it again.  No need for a plugin.  I use the script myself for using letsencrypt certs on my OMV instances.

**Comment by simonmcnair** [comment]
It maybe a lot easier with acme.  I've heard negatives about certbot myself and I believe that acmesh is just shell script and is designed to be easier to use and maintain over certbot

**Comment by ryecoaaron** [comment]
I'll look at it.  I really like certbot (use it for many things at work with a local acme intermediate CA) but my dns provider at home is godaddy.  It has special requirements that a script can't make easier and would be very difficult in a plugin.

**Comment by simonmcnair** [comment]
Thank you, that's all I would like :-).  Hopefully you've already done the heavy lifting with the architecture and it's replugging a few cmd lines in the back ground.  I know it certainly isn't trivial, but hopefully you've already broken the back of it if that makes sense.

Thanks for responding.

**Comment by ryecoaaron** [comment]
The other problem is that many people are using a proxy like swag to have one interface to all of their containers.  swag can already do the cert stuff.  I know that doesn't help with using the cert in OMV itself but creating the cert in an OMV plugin doesn't make the cert easily consumable by many docker containers.

**Comment by ryecoaaron** [comment]
>  Hopefully you've already done the heavy lifting with the architecture and it's replugging a few cmd lines in the back ground. I know it certainly isn't trivial, but hopefully you've already broken the back of it if that makes sense.

Unfortunately the letsencrypt plugin hasn't been ported to OMV 6.x.  So, the entire frontend would have to be rewritten for OMV 6.x and switching to the script would likely require the backend to be rewritten.  I'll still look at the script but it would be a lot of work either way.

**Comment by simonmcnair** [comment]
IT is a shame this wasn't done.  It would have been nice to have letsencrypt automatically updating SSL certificates.

**Comment by ryecoaaron** [comment]
There is another option.
1. Install certbot and configure it.
2. Call [my update_cert script](https://github.com/ryecoaaron/scripts/blob/main/update_cert.sh) from a hook script in /etc/letsencrypt/renewal-hooks/deploy/.
3. Done.

**Comment by simonmcnair** [comment]
sweet !  thanks :-)

**Comment by mi-hol** [comment]
> There is another option.

would this be worth a blog post on omv.org?
This now closed issues seems the only hint for such a great improvement

**Comment by mi-hol** [comment]
Even better would be adding his informaton to https://docs.openmediavault.org/en/stable/administration/general/certificates.html?highlight=ssl#letsencrypt
