### ISSUE TITLE
Allow Workbench to be reverse proxied through subfolder

### ISSUE THREAD

**Issue by EmTeedee** [openmediavault/openmediavault#1516]
**Is your feature request related to a problem? Please describe.**
I want to use a reverse proxy to access OMV through a subfolder of my main domain e.g. https://example.com/omv/

**Describe the solution you'd like**
All dependencies linked in the web ui should be using relative paths.

**Describe alternatives you've considered**
Using a separate subdomain would be an alternative, the solution would give more flexibility for users.

**Comment by votdev** [comment]
Are you sure you are fixing the issue at the right side?

**Comment by votdev** [comment]
# Testing setup

Create the file `Caddyfile` with the following content:
```
{
  debug
  admin off
}
:8080 {
  route /foo/* {
    uri strip_prefix /foo
    reverse_proxy http://<OMV_IP_ADDR>
  }
  redir /foo /foo/
}
```

Start the proxy via `podman run --replace -it --name=omv-via-proxy -v ./Caddyfile:/etc/caddy/Caddyfile:Z -p 8080:8080 docker.io/library/caddy:latest`.

The UI can now be reached via `http://localhost:8080/foo`.
