### ISSUE TITLE
Proposal: Remove filesystem label support

### ISSUE THREAD

**Issue by votdev** [openmediavault/openmediavault#152]
Remove the support of filesystem labels because it makes more troubles (see #151) as it helps. This means that labels can be set when a filesystem is created, but OMV will not use them to identify the device file via ``/dev/disk/by-label/xxxx``.

**Comment by momo42** [comment]
Please leave label support in! It helps a lot if you have multiple filesystems. I think it would be better to check for existing labels when adding new disk labels.

**Comment by votdev** [comment]
> I think it would be better to check for existing labels when adding new disk labels.

This is already done

**Comment by votdev** [comment]
One of many examples where filesystem labels make problems:

- https://github.com/openmediavault/openmediavault/commit/015829e5d48055702a68696c4f2a659c3c6dbf3a

**Comment by klorinczi** [comment]
I also use filesystem labels, I would ask to keep it.

**Comment by Samuel12321** [comment]
perhaps it would be best if the user can turn this on of off, depending on whether they need/want filesystem labels or not.

**Comment by mi-hol** [comment]
guess this work item should move to 6.x too?
