### ISSUE TITLE
UI: Network: Support configuration of secondary / multiple IPs on the same interface.

### ISSUE THREAD

**Issue by n00ris** [openmediavault/openmediavault#1526]
**Is your feature request related to a problem? Please describe.**
Hello, my use case is to bind services (e.g. managed by docker) that usually uses the same port (typically 80/443 for http/https) to different IPs on the NAS.
For example
10.10.10.10:80 is OMV
10.10:10:11:80 is a Wiki provided by a docker image, managed by portainer
10:10:10:12:80 is portainer
10:10:10:13:80 is ... the next service that provide a web interface for configuration or usage (pihole, ...)

**Describe the solution you'd like**
In the UI Network->Interfaces->Edit dialog, provide an Input field to specify (a list of) secondary IPs.

**Describe alternatives you've considered**
Currently, I bind the services to other ports than 80/443 to provide web interfaces. 
On one hand, this is not very convenient if you access them via a browser, and there are some non-technical user that uses the service, but may not even know what a network port is ;-)
On the other hand, I can add DNS entries per IP.

**Comment by nullindent** [comment]
A port number cannot be used by multiple processes, so you need to assign another port number to the container and use the reverse proxy function of nginx to access it via uri on port 80
