### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by tengyifei** [openmediavault/openmediavault#1527]
Debian Bookworm will be released later this year and comes with PHP 8 (https://packages.debian.org/bookworm/php).

When I tested upgrading to bookworm, openmediavault no longer installs. It looks like part of the reason is the PAM plugin (https://github.com/openmediavault/openmediavault/tree/master/deb/php-pam/pam-2.2.3) which requires PHP 7. When I search for `php-pam` inside https://packages.openmediavault.org/public/dists/shaitan/main/binary-arm64/Packages, it has a dependency on `phpapi-20190902` which is provided by PHP 7.4.

What would it require to make the plugin support PHP 8? I can help with this if it's feasible.

**Comment by ryecoaaron** [comment]
OMV 6.x only supports Debian 11 Bullseye.  You would need OMV 7.x to move to Debian 12 Bookworm.

**Comment by ryecoaaron** [comment]
As far as I know, OMV 7.x hasn't even been started.  If you need php8, I recommend use docker or a VM.

**Comment by tengyifei** [comment]
My particular problem is that Debian Bookworm just doesn't let you install PHP7. I don't need PHP8 per se -- I'm happy to run PHP7.4 to make things easier for OMV. But Debian Bookworm has removed PHP7.4 from their package repository.

I can try to downgrade back to Bullseye. I think the general issue of PHP8 support would still remain though. PHP8 has been released more than two years ago and PHP7.4 is no longer receiving security fixes.

**Comment by ryecoaaron** [comment]
php7.4 support from php is done but Debian will still support it.  You have no worries there.  OMV will always use the primary version of php for the Debian release it is targeting.  And since Debian is a stable distro, it will usually be behind a few versions of many packages.

**Comment by votdev** [comment]
OMV is strictly tied to Debian stable. OMV7 with PHP8 will be available in 2024 or at least when Debian 12.1 is released.

Till then OMV does not support other PHP versions.
