### ISSUE TITLE
OMV_ISSUE_APPLY_PRELOGIN_MESSAGE ignored?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [openmediavault/openmediavault#1533]
Set OMV_ISSUE_APPLY_PRELOGIN_MESSAGE="no" in /etc/default/openmediavault
Set /etc/issue back to OS default
Reboot system

Result...
/etc/issue overwritten again.

OMV version...
/# dpkg -l | grep openmediavault | head -n 1
ii  openmediavault                    6.3.8-1                        all          openmediavault - The open network attached storage solution

**Comment by ryecoaaron** [comment]
Did you just set the value in /etc/default/openmediavault or did you follow the guide on how to set custom values?  The biggest part missing what you posted that would make it take effect is the omv-salt stage run prepare command.

**Comment by ryecoaaron** [comment]
Thanks.  I was going to post the link but forgot to.

**Comment by Jibun-no-Kage** [comment]
If...

#  omv-env get OMV_ISSUE_APPLY_PRELOGIN_MESSAGE
OMV_ISSUE_APPLY_PRELOGIN_MESSAGE=no

Should I not believe the configuration is correct and active?

I have not yet done an explicit set.  Or run the prepare sequence.

**Comment by Jibun-no-Kage** [comment]
I explicitly did a set command...

\# omv-env set OMV_ISSUE_APPLY_PRELOGIN_MESSAGE no

 then applied the changes per the documentation...

\# monit restart omv-engined
\# omv-salt stage run prepare
\# omv-salt stage run deploy

I then changed /etc/issue, rebooted.  The change stuck.  The fact that the get query returned the correct value is or was confusing.  Fortunately I am familiar with salt.  Being new to OMV, did not realize initially that salt was used.

What is also interesting is that disable of the system unit file did NOT impact the change.  That was interesting.

**Comment by ryecoaaron** [comment]
> Should I not believe the configuration is correct and active?

No.  omv-env is a simple python script that just reads the contents of /etc/default/openmediavault.  Since the defaults file is used by bash, python, php, and salt, it would very slow (and not make sense in my opinion) to only show the variables that all four environments could "see".  bash and python will see the new variables right away but php requires omv-engined to be bounced and saltstack requires the prepare to be done.

**Comment by votdev** [comment]
Keep in mind that if the env variable is disabled this means that /etc/issue is not regenerated but the last deployed content still exists and is used by the login shell. With disabled variable you can customise the file to your means without being overwritten by OMV.

**Comment by Jibun-no-Kage** [comment]
Yes, I expected to have to re-establish the original content of the issue file.  I was reverting the issue file with each test/attempt.

The surprise was that using the env variable or disabling the service did not stop the behavior.  Of course, once I understood the need to do the prepare/deploy steps, it made sense... given I know how salt works.
