### ISSUE TITLE
Show Tag in monitoring alert message when filesystem threshold is reached

### ISSUE THREAD

**Issue by JokerGermany** [openmediavault/openmediavault#1538]
**Is your feature request related to a problem? Please describe.**
Some filesystem thresholds are really important others aren't that important.
Would be nice to see the tag of the filesystem in the eMail.

**Describe the solution you'd like**
That the Tag is mentioned at least in the messaged, better in the subject.
My dream solution would be:
When a Tag is set show the tag in the subject instead of the cryptic mount point.

**Comment by votdev** [comment]
I'm afraid this is not possible because the email (subject and content) is generated by monitd and can not be customized (AFAIK).
