### ISSUE TITLE
Odroid XU4 OMV Arrakis Apt Installation Failed

### ISSUE THREAD

**Issue by potter-91** [openmediavault/openmediavault#154]
Hi everyone
I tried to setup arrakis to my odroid xu4 CS...
I got this failure:

`root@Cloudshell:~# apt install openmediavault -y
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
openmediavault ist schon die neueste Version (4.1.9).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
1 nicht vollständig installiert oder entfernt.
Nach dieser Operation werden 0 B Plattenplatz zusätzlich benutzt.
openmediavault (4.1.9) wird eingerichtet ...
Creating users/groups ...
Updating local package archive ...
Updating service units ...
Updating configuration database ...
Traceback (most recent call last):
  File "/usr/sbin/omv-confdbadm", line 23, in <module>
    import openmediavault
ImportError: No module named 'openmediavault'
dpkg: Fehler beim Bearbeiten des Paketes openmediavault (--configure):
 Unterprozess installiertes post-installation-Skript gab den Fehlerwert 1 zurück
Fehler traten auf beim Bearbeiten von:
 openmediavault
Traceback (most recent call last):
  File "/usr/sbin/omv-mkaptidx", line 35, in <module>
    import apt
ImportError: No module named 'apt'
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@Cloudshell:~#
`

Please no questions why I don't use the OMV XU4 Image!

I hope someone know what's going on there.

PS: Sorry for the bad layout. I opened the Issue on mobile.

**Comment by votdev** [comment]
> No module named 'apt'

The package python3-apt is missing. Seems that the installation of the openmediavault package was not successful. Try to fix that issue by executing

# apt-get install python3-apt

If that does not help please contact the maintainer of the installation image in the forum.
