### ISSUE TITLE
Add 802.3ad xmit hash policy setting

### ISSUE THREAD

**Issue by Max-Sum** [openmediavault/openmediavault#1542]
**Is your feature request related to a problem? Please describe.**
I connect to my server through a layer-3 switch. Server are connected using 2x10G connection and bonding using 802.3ad. By default, 802.3ad uses layer-2 information (MAC address) to decide which slave nic to be used for sending packets. But since there's a router (layer-3 switch) in between, all packets are sending to the same MAC address. Thus only one NIC is used for sending.

**Describe the solution you'd like**
Linux has a solution for this. Just setting the xmit_hash_policy to "layer2+3" or "layer3+4". However, in OMV dashboard there're no such option.

**Describe alternatives you've considered**
I use if-up.d script to set the xmit_hash_policy but not an elegant way.
Switching to other bonding algorithm is also an alternative. But that's against the standard.

**Comment by votdev** [comment]
References:
- https://netplan.readthedocs.io/en/stable/netplan-yaml/#properties-for-device-type-bonds
