### ISSUE TITLE
"Failed to read bgstatusXXXXXX" - small bug

### ISSUE THREAD

**Issue by Ellestad1995** [openmediavault/openmediavault#155]
**The setup**
Running OMV on a Proxmox VM. Disks are Logical Volume Managed and are presented to OMV as scsi attached disks. 

**Error**
The error is as displayed in the screenshots below. The error have occurred both times I have created a new file system (ext4). The error comes one after another and is really annoying.

![failed_to_read_bgstatus](https://user-images.githubusercontent.com/16270816/43675609-17ff5c9a-97e3-11e8-8959-83708df7a55b.PNG)

![failed_to_read_bgstatus34nsm](https://user-images.githubusercontent.com/16270816/43675610-20109e76-97e3-11e8-8b8c-9517ba345878.PNG)

![failed_to_read_bgstatus2](https://user-images.githubusercontent.com/16270816/43675707-aea8d44a-97e4-11e8-9eb0-7cd9b9fc943d.PNG)
![failed_to_read_bgstatus3](https://user-images.githubusercontent.com/16270816/43675708-aec1db66-97e4-11e8-9c46-cf5b3fc82cfb.PNG)
![failed_to_read_bgstatus4](https://user-images.githubusercontent.com/16270816/43675709-aed8e3b0-97e4-11e8-9f9c-955218f05101.PNG)

It doesn't seem that the error is something big. OMV runs fine and the shares is working too. 
What even is bgstatus? 
**`The file system creation has completed successfully.`**

**Comment by ryecoaaron** [comment]
This was fixed in OMV 4.1.6.  If you just installed from the 4.1.3 ISO, you need to update the system in the updates tab.  If that isn't working then use omv-update from the command line.

**Comment by Ellestad1995** [comment]
Yes. The error messages are gone in OMV 4.1.6.
