### ISSUE TITLE
SSL error in Chrome with trusted certificate

### ISSUE THREAD

**Issue by legacycode** [openmediavault/openmediavault#156]
Hi,

i use a trusted certificate that works great in Edge and Firefox. But Chrome is complaining about linked ressources that points to unsafe locations.

![grafik](https://user-images.githubusercontent.com/668759/43991107-ab2cd362-9d65-11e8-88f1-72b643991bd8.png)

In the html source i found the following content that could be the possible reason:

![grafik](https://user-images.githubusercontent.com/668759/43991109-b73a16f6-9d65-11e8-8692-370e3641e5e5.png)

In the Chrome developer tools i could identify the following link:

![grafik](https://user-images.githubusercontent.com/668759/43991100-98fa95bc-9d65-11e8-8fcd-eb857be78891.png)

Changing the urls to https should solve this problem.

Best regards.

legacycode

**Comment by ky0nch3ng** [comment]
Check with incognito windows and reset you cache again.

Check error certificate wether belongs to your name.

**Comment by legacycode** [comment]
This is not an issue with the SSL certificate. It works great in Edge and Firefox. Please have a look at the following link. The problem is called "[Mixed Content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content)".

**Comment by votdev** [comment]
Fixed in openmediavault 4.1.10, see https://github.com/openmediavault/openmediavault/commit/c1c38ca782c58cbf8df963266db772bc1fb82590.
