### ISSUE TITLE
Plex plug-in

### ISSUE THREAD

**Issue by MaddTheSane** [openmediavault/openmediavault#1562]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be an easy/simple way to set-up Plex on an Open Media Vault installation. 

**Describe the solution you'd like**
Perhaps adding either a plug-in or a script will help making the set-up easier.

**Describe alternatives you've considered**
There is a guide over at https://www.wundertech.net/how-to-install-plex-on-openmediavault/ that goes over all the steps needed.

**Additional context**
I came from TOS 4 which has an app installation for Plex.

**Comment by ryecoaaron** [comment]
There are guides on the forum on how to install it using docker. There is also an example docker compose in the compose plugin.

**Comment by votdev** [comment]
I'm closing this issue because the installation via the mentioned openmediavault-compose plugin should be trivial. In most cases howtos for Docker installations can be mapped 1:1 to the OMV plugin.
