### ISSUE TITLE
New feature suggestions: Add files manager

### ISSUE THREAD

**Issue by h0wardch3ng** [openmediavault/openmediavault#157]
Such as

![](https://box.kancloud.cn/fe12a1dedf38a93fd91c60e9290e55ea_1601x1082.png)

Functions:

* Enter path to browser files list
* Add folder/Rename files/Copy and paste and move files
* Set premission
* Set files owner or group owner

Screenshot from this repo https://github.com/zijiwork/bt-panel

http://docs.bt.cn/424266?silsta=eo84v&xwfsdc=tn8wx2

Thx!

**Comment by sirgogo** [comment]
I second this request. This would be invaluable. Not sure how the directory-tree parsing/etc would be handled though.

**Comment by donhwy** [comment]
I think at one time there was a plugin for that. That is probably the way to do it.

**Comment by ryecoaaron** [comment]
There was an extplorer plugin but it has permissions issues since it wasn't running as root (dangerous).  You can always use winscp or mc from command line or install webmin.

**Comment by donhwy** [comment]
"or install webmin." Waiting for votdev's wrath. lol

**Comment by ryecoaaron** [comment]
It is all over the forum and he doesn't want to create the file manager.  So, I should be safe :)

**Comment by zero77** [comment]
it's simple but this is another option:
https://github.com/jcampbell1/simple-file-manager

**Comment by zero77** [comment]
@ryecoaaron 
Yes, I was thinking it would be easier to implement and support.

**Comment by ryecoaaron** [comment]
Personally, I stopped creating php plugins because they are very easy to add to the nginx plugin.  Feel free to create a plugin but I'm pretty sure Volker is going to add it - especially something that isn't integrated into the web interface.

**Comment by votdev** [comment]
> I'm pretty sure Volker isn't going to add it

You're right :-) This is something that is really hard to maintain, i don't want to create a new package/update every week because such tools are frequently updated. If someone else is encouraged to do this, i'm happy.
