### ISSUE TITLE
OMV6 Crashed when attempting to add second hard drive. "Software failure"

### ISSUE THREAD

**Issue by RNZB** [openmediavault/openmediavault#1570]
I am attempting to add a second hard drive to my OMV6 instance running on a Raspberry Pi 4b. As soon as i plug in my second hard drive it crashes my raspberry pi. As soon as I remove one of the hard drives it all works fine. I am at a complete loss as to why this is occurring. I have run out of space on my current hard drive and i need to add an expansion. Could anyone please assist me in fixing this?

**Comment by votdev** [comment]
Please raise this question in the forum because if the Pi crashes this has nothing to do with OMV. I guess it is a power consumption problem of your hardware.

**Comment by RNZB** [comment]
I should have phrased this a little bit better. So I am using the genuine rasp pi power supply. I have had a 2tb hard drive working with OMV for ages. I recently filled it. i purchased a 4tb hard drive. When i plug it in and go to create a file system with the new hard drive, both of my hard drives are "missing" it also seems to effect my ability to SSH into the pi. 

![Xnip2023-08-06_13-42-37](https://github.com/openmediavault/openmediavault/assets/134199171/e8662b5e-569c-4cc2-b8f9-f12d4263f346)
![Xnip2023-08-06_13-43-03](https://github.com/openmediavault/openmediavault/assets/134199171/56f9cd5d-b611-452e-8fcf-cd4722a92099)

**Comment by RNZB** [comment]
Here it goes with a fresh reboot of the pi. I log into OMV and it prompts me to save preferences. As it is saving it loads my 2 drives then whilst it is still loading it then fails. I have no issue using just 1 hard drive. either of the hard drives work perfectly fine by themselves but as soon as i try to add a second filesystem this happens. I just can not ge the two to work in OMV

![Xnip2023-08-06_14-17-47](https://github.com/openmediavault/openmediavault/assets/134199171/899283fa-af5b-45ce-b036-ee2eff63345c)
![Xnip2023-08-06_14-18-02](https://github.com/openmediavault/openmediavault/assets/134199171/b6a22fcf-38f2-4c4c-9b46-5b99df0b7ec2)

**Comment by ryecoaaron** [comment]
If you are using drives powered by the RPi, you are going to have problems with more than one no matter what power supply you use. Your system is probably undervolting and you can see this in dmesg. You should use externally powered drives.  Nothing OMV can do to help this.

**Comment by flmaxey** [comment]
-> [Power - a Common R-PI Problem](https://wiki.omv-extras.org/doku.php?id=omv6:utilities_maint_backup#usb_power_-_a_common_raspberry_pi_problem)
