### ISSUE TITLE
OMV6 over debian11 : netplan has no config

### ISSUE THREAD

**Issue by olaulau** [openmediavault/openmediavault#1573]
**Describe the bug**

debian11 doesn't use netplan out of the box.
it seems to be a dependency fo openmediavault, but not config are generated under /etc/netplan during install.
so after a reboot, the network is broken (no DNS resolution).

**To Reproduce**

- install debian 11 netinst (no packages, just SSH)
- install OMV6 over it (as describe in documentation : https://docs.openmediavault.org/en/latest/installation/on_debian.html)
--> network is still working
- reboot
-->network doesn't resolves hostnames, so I cannot apt install anything ...

**Expected behavior**

I'm not an expert of netplan but I hope that it generates at least one valid configuration for existing network during package install, so that we don't have bat surprise after reboot

**openmediavault Server (please complete the following information):**

- OS version: Debian 11
- openmediavault version: 6.5.6-1

**Additional context**

workaround : go into the webui, change network config (such as adding DNS), to force OMV to generate netplan conf files

**Comment by ryecoaaron** [comment]
If you run the install script, you won't have this problem - https://forum.openmediavault.org/index.php?thread/28789-installing-omv6-or-omv5-on-raspberry-pi-s-armbian-sbc-s-i386-32-bit-platforms/

Otherwise, you can just run omv-firstaid to configure the network adapter from the command line after install OMV.

**Comment by votdev** [comment]
The docs are missing the command `omv-salt deploy run systemd-networkd`.

**Comment by olaulau** [comment]
> If you run the install script, you won't have this problem - https://forum.openmediavault.org/index.php?thread/28789-installing-omv6-or-omv5-on-raspberry-pi-s-armbian-sbc-s-i386-32-bit-platforms/
> 
> Otherwise, you can just run omv-firstaid to configure the network adapter from the command line after install OMV.

can't find your script.

**Comment by ryecoaaron** [comment]
The guide links to it.

**Comment by votdev** [comment]
> maybe a bug if you think `omv-confdbadm populate` should do the job.

This depends on how the network is configured at that time. On many systems `ifupdown` is used, others are using `NetworkManager` or `systemd`. OMV supports only `/etc/network/interfaces` which is used by `ifupdown`.

**Comment by olaulau** [comment]
I just tried : 
followed this doc : https://wiki.omv-extras.org/doku.php?id=omv6:i386_32-bit_install
and run : `
wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash`
--> no config generated under /etc/netplan, DNS broken after reboot

**Comment by olaulau** [comment]
then `omv-firstaid` works as expected.
should be in the end of official documentation ;-)

**Comment by votdev** [comment]
Documentation has been adapted: https://github.com/openmediavault/openmediavault-docs/commit/d9e5fe37b32c758e80693bdcafb5489560e33853

**Comment by votdev** [comment]
> I just tried : followed this doc : [wiki.omv-extras.org/doku.php?id=omv6:i386_32-bit_install](https://wiki.omv-extras.org/doku.php?id=omv6:i386_32-bit_install) and run : ` wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash` --> no config generated under /etc/netplan, DNS broken after reboot

The install script is deploying the configuration if necessary, see https://github.com/OpenMediaVault-Plugin-Developers/installScript/blob/master/install#L608.

**Comment by olaulau** [comment]
Hi ;
just made another test :
`omv-salt deploy run systemd-networkd` fixes the problem, so adding it to the doc is fine, thanks.

just a little comment : only running `omv-confdbadm populate` with a stock debian11 DHCP conf in `/etc/network/interfaces` does not generates netplan conf.

**Comment by votdev** [comment]
> Hi ; just made another test : `omv-salt deploy run systemd-networkd` fixes the problem, so adding it to the doc is fine, thanks.

👍

> just a little comment : only running `omv-confdbadm populate` with a stock debian11 DHCP conf in `/etc/network/interfaces` does not generates netplan conf.

Yes that is right. It only populates the database with the existing settings of interest.

The NEW configuration is deployed with the command you mentioned above.
