### ISSUE TITLE
latest openmediavault generates invalid configuration for nfs rpc

### ISSUE THREAD

**Issue by zapotah** [openmediavault/openmediavault#1578]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

nfs-server fails to start with
´´´
Aug 12 18:25:26 vault rpc.mountd[4083353]: /usr/sbin/rpc.mountd: bad version number: 0
´´´

**To Reproduce**

1. update to 6.5.7

**Expected behavior**

NFS works

**openmediavault Server (please complete the following information):**

- OS version: debian 11.7 with 6.1.20-2~bpo11+1

**Additional context**

something in salt creates an erroneous /etc/default/nfs-kernel-server config
Options for rpc.nfsd.
RPCNFSDOPTS="--no-nfs-version 2 --nfs-version 3 --nfs-version --nfs-version 4 --nfs-version 4.1 --nfs-version 4.2 "

Options for rpc.mountd.
RPCMOUNTDOPTS="--no-nfs-version 2 --nfs-version 3 --nfs-version --nfs-version 4 --nfs-version 4.1 --nfs-version 4.2 --manage-gids"

edit this by hand  to remove the empty nfs-version statement and everything works as expected

**Comment by zapotah** [comment]
this is apparently in accordance to the release notes so doing what the release notes say will fix this. closing but archiving for others looking for this info.

**Comment by ryecoaaron** [comment]
https://www.openmediavault.org/?p=3550
https://forum.openmediavault.org/index.php?thread/49141-nfs-down-with-omv-6-5-7-update/&postID=361420#post361420

**Comment by skazi0** [comment]
@votdev There is still a problem with nfs after `omv-confdbadm populate`.
It seems to be introduced by https://github.com/openmediavault/openmediavault/commit/c953f9c07c6494d8689db0699513a50260365423.
The `tr -s '[[:space:]]' ','` considers `\n` as whitespace too and adds `,` at the end.

Note that `sed` and `tr` handles this differently:
```
$ echo -e "x x\nx" | sed 's/[[:space:]]/,/'
x,x
x
$ echo -e "x x\nx" | tr '[:space:]' ','
x,x,x,
```

my versions just in case:
```
ii  sed                                4.7-1                          amd64        GNU stream editor for filtering/transforming text
ii  coreutils                          8.32-4+b1                      amd64        GNU core utilities
# Debian GNU/Linux 11 (bullseye)
```

**Comment by votdev** [comment]
> @votdev There is still a problem with nfs after `omv-confdbadm populate`. It seems to be introduced by [c953f9c](https://github.com/openmediavault/openmediavault/commit/c953f9c07c6494d8689db0699513a50260365423). The `tr -s '[[:space:]]' ','` considers `\n` as whitespace too and adds `,` at the end.
> 
> Note that `sed` and `tr` handles this differently:
> 
> ```
> $ echo -e "x x\nx" | sed 's/[[:space:]]/,/g'
> x,x
> x
> $ echo -e "x x\nx" | tr '[:space:]' ','
> x,x,x,
> ```
> 
> my versions just in case:
> 
> ```
> ii  sed                                4.7-1                          amd64        GNU stream editor for filtering/transforming text
> ii  coreutils                          8.32-4+b1                      amd64        GNU core utilities
> # Debian GNU/Linux 11 (bullseye)
> ```

Should be finally fixed with https://github.com/openmediavault/openmediavault/commit/21222e553c92a2fb8e31dd5d94ab8590a3b56c7d#diff-57ce1d19a27e042112239c4aa932f7d99236b1dd8178be4a5d7023c915690ab0R30
