### ISSUE TITLE
Netbios implementation

### ISSUE THREAD

**Issue by robl45** [openmediavault/openmediavault#1579]
First and foremost right in the name, this is a media server.  Many media devices are only using Netbios for SMB shares especially the very popular Zidoo devices and I'm sure there are many others.  While Netbios may pose a minor security risk, I think it would be better to have it turned on given that many media appliances are not going to get SMB without it and most people have no idea why.   I spent at least 5 months trying to figure out why SMB didn't work and there was one thread on the open media vault forums that went on for 2 pages and no one knew the answer was to turn on Netbios.  If Openmediavault is meant for beginners and I would assume it is because advanced users wouldn't need a GUI, then Netbios should be on so SMB works seamlessly with most thing.  I found the answer on the Zidoo forum almost by accident trying to google for the problem.  

At the very least, I would suggest a button that would enable netbios as even the instructions that I did find in the forum related to enabling netbios did not get it working for me.  There were I guess steps missing as the steps listed on the Zidoo forum got it working.  I may not seem like it, but I know a lot more than the typical beginner about this stuff and I'm very basic in Linux.  If I'm having trouble, plenty of others are having trouble with this.

As specified before, for the beginner aspect, I would suggest Netbios be enabled by default.  If the security risk is such a concern (I don't think it would be for 95% of users), then a warning screen could flash on new installations/upgrades etc that says Netbios might not be secure and we suggest you turn it off.  This could be a warning screen that needs active intervention to remove such that people won't easily miss it.  Again I think this is truthfully overkill as the people that likely are going to want to disable netbios are going to know it is a problem.  This solution would ideally go with a button on the SMB services page to allow easy enable and disable.

Finally and reason for a button for netbios if nothing else is that beginners really shouldn't be messing with the command line if they don't have to.  A button would eliminate that and from what I can tell, many people are going to need to enable this for it to play nice with devices that use SMB.

**Comment by votdev** [comment]
Enabling something with a high potential of security risks by default is a no go. In windows environments NMBD is replaced by WSD and not needed and used anymore. But adding a knob to allow the user to enable it when necessary makes sense.

References:
- https://forum.openmediavault.org/index.php?thread/46746-new-samba-shares-cannot-be-accessed-from-android-zidoo-media-server/&pageNo=2
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=Netbios
- https://linux-blog.anracom.com/2020/05/24/samba-4-shares-wsdd-and-windows-10-how-to-list-linux-samba-servers-in-the-win-10-explorer/
-

**Comment by votdev** [comment]
Could you please share the link to the Zidoo form you mentioned?

**Comment by votdev** [comment]
You should also think about raising an issue at Zidoo to support SMB using modern protocols. Microsoft has disabled SMB1 which relies on NetBIOS with reason in the latest Windows versions.

**Comment by robl45** [comment]
Link on Zidoo forum http://forum.zidoo.tv/index.php?threads/can-not-access-my-truenas-shared-smb.95883/

**Comment by votdev** [comment]
> Link on Zidoo forum http://forum.zidoo.tv/index.php?threads/can-not-access-my-truenas-shared-smb.95883/

Too bad that Zidoo has not answered which SMB version they support. But based on the knowledge that NetBIOS is required I guess they only support SBBv1 which is a big security problem. Microsoft has disabled that in newer versions with reasons. You should force Zidoo to support the more secure SMBv3. I mean, you have paid for the product which comes out is insecure.

**Comment by robl45** [comment]
Yes was coming to say I confirmed as you that v3 is supported. But somehow appears to need netbios
