### ISSUE TITLE
Several dashboard widgets are down after very last OMV update 6.7.0-1

### ISSUE THREAD

**Issue by Jerome-Herbinet** [openmediavault/openmediavault#1585]
Event after full reboot, several dashboard widgets are down since very last OMV update. Any idea ? (all of them were working fine before this little update)

![2023-08-24_09-31](https://github.com/openmediavault/openmediavault/assets/33763786/f23800bc-ff67-4c48-a131-545b09ae6043)

Some details : 
OMB 6.7.0-1 on Raspberry Pi 4 (Raspberry Pi OS 11).

**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: [uname -a]
- openmediavault version: [dpkg -l | grep openmediavault]

**Client (please complete the following information):**

**Additional context**

**Comment by pierrejo** [comment]
Same for me on Raspeberry Pi 4

**Comment by votdev** [comment]
Fixed with https://github.com/openmediavault/openmediavault/commit/d24c8b94c54627de083779c47631848e2fdf7c69
