### ISSUE TITLE
Missing shared folder reference in permissions GUI

### ISSUE THREAD

**Issue by luke6464** [openmediavault/openmediavault#1591]
I would like to point out the lack of reference to the shared folder whose permissions you want to change in the GUI as per the attached screenshots. It might be a good idea to include this in the next OMV update because it is inconvenient not to have the shared folder name on this screen as you tend to forget which folder you are working on.

I also point out the lack of the Italian translation of the message shown in the screenshots.

Thank you

![screenshot_20230904_005847](https://github.com/openmediavault/openmediavault/assets/3793119/65d4fbbf-55b5-47a0-aa69-97d795b5c357)

**Comment by votdev** [comment]
> I also point out the lack of the Italian translation of the message shown in the screenshots.

If you want you can become a translator. Check the following [documentation how to become one](https://docs.openmediavault.org/en/stable/development/contribute.html#how-to-become-a-translator).

**Comment by votdev** [comment]
> I would like to point out the lack of reference to the shared folder whose permissions you want to change in the GUI as per the attached screenshots. It might be a good idea to include this in the next OMV update because it is inconvenient not to have the shared folder name on this screen as you tend to forget which folder you are working on.

Fully agree, but the problem here is the page that is responsible for rendering the data only gets the UUID (the database identifier of the shared folder) to fetch the privileges. The whole UI does not support the firing of several API calls during the initialisation of a page. This requires a huge rewrite of the declarative UI framework.

**Comment by votdev** [comment]
![grafik](https://github.com/openmediavault/openmediavault/assets/1897962/272eae83-a61b-4e15-85b1-bba699d3dc6f)
