### ISSUE TITLE
Inherit permissions for Home dir

### ISSUE THREAD

**Issue by sebeksd** [openmediavault/openmediavault#1592]
**Is your feature request related to a problem? Please describe.**
I'm using clamav to scan home directories, because I'm using default clamav user and not a root user, clamav is unable to scan users home directories. Right now when creating directory inside Home directories (through SMB) by default group rights are "0".

To combat that I can configure parent folder so child directories will have group that clamav has access (but other users do not have) and make SMB inherit rights when creating directory. However this is impossible to setup through WebUI because there are no "inherit ACLs/permissions" options in SMB Homes configuration. This can be done manually by editing smb.conf file but it will be lost when WebUI overwrites it.

**Describe the solution you'd like**
Add inherit ACLs/permissions checkboxes for Home directories similar to standard SMB shares:
![image](https://github.com/openmediavault/openmediavault/assets/18705953/16e2574a-b987-476c-884e-7c0edaaabdf4)

**Describe alternatives you've considered**
Not sure.

**Additional context**
https://forum.openmediavault.org/index.php?thread/49317-clamav-home-directories/

**Comment by votdev** [comment]
Asked the other way around, which SMB options should be set by default for user home directories in a normal setup? Adding a new checkbox doesn't help users at all if they don't understand what the implications are.

**Comment by sebeksd** [comment]
> Asked the other way around, which SMB options should be set by default for user home directories in a normal setup? Adding a new checkbox doesn't help users at all if they don't understand what the implications are.

Default option would be same as now (unchecked).

I think that other solution that might work for all people would be to make OMV create Home folders with different group then "users" for example group that normally users have no rights but with RW permissions and then in SMB make it inherit rights by default. Then we could simply add clamav to this group.

Right now directories are created with "users" group so to prevent other users from accessing other people files is to set group permission to 0.
