### ISSUE TITLE
Web interface software crash

### ISSUE THREAD

**Issue by KrishnaSai2020** [openmediavault/openmediavault#1597]
**Describe the bug**

When logging in to the web interface and installing the newest updates the interface repeatedely crashes when trying to access storage devices. refreshing the page, rebooting the server does not fix the issue.
**To Reproduce**

Steps to reproduce the behaviour:
1.  install the newest updates from the web interface
2. Click on storage
3. see error
4. If you manage to not see an error - click on disks the error page will appear

**Expected behavior**

Expected behaviour is for the interface not to crash and open disks and file-systems

**Screenshots**
<img width="1792" alt="Screenshot 2023-09-18 at 14 08 29" src="https://github.com/openmediavault/openmediavault/assets/63070026/2e40a5d5-de7c-43be-a9db-f8ec763c4d89">

**openmediavault Server **

- OS version: 6.9.0-1 (Shaitan)

**Client **

- Device: macbook pro 2019 16 inch
- OS: mac os ventura
- Browser google chrome and on safari

**Comment by KrishnaSai2020** [comment]
This also occurs when using the services tab as well.

**Comment by votdev** [comment]
This is not a bug. The error message clearly explains what to do. This behaviour always occurs whenever the JS bundle files change due changes in the UI code. Because of that the hash codes of the bundle files change and the Angular runtime detects that which results in this error message.

**Comment by KrishnaSai2020** [comment]
Thanks for your help but you see thats why I had opened a bug report - the fixes the error message suggests do not work(initially)

What I have discovered just now is I had pressed control instead of command which meant the page did not reload since i am on Darwin so I kept reloading the page by loggin out and in to the webpage which did not actually reload the cache. Just a thought but may be worth a slight rewording of the message by specifying this maybe?

**Comment by votdev** [comment]
> may be worth a slight rewording of the message by specifying this maybe?

I think it does not make sense to enumerate each combination of keys that need to be pressed on every browser. The mentioned key combinations are the most common. IMO, the rest of the message should point the user in the right direction to "hard reload" the page.

**Comment by votdev** [comment]
> may be worth a slight rewording of the message by specifying this maybe?

Please make a suggestion.
