### ISSUE TITLE
Update bundled Transmission to 4

### ISSUE THREAD

**Issue by MaddTheSane** [openmediavault/openmediavault#1599]
**Is your feature request related to a problem? Please describe.**
There are a few torrents that won't load on the bundled Transmission 3.

**Describe the solution you'd like**
Update the bundled Transmission to 4.

**Describe alternatives you've considered**
The alternative is to spin up a Docker container, but I'd rather not as I have the non-Docker version set up.

**Additional context**
None comes to mind.

**Comment by votdev** [comment]
Are you talking about the Transmission plugin that was released with OMV 0.3?

if you are talking about the Transmission Debian package, then the OMV project is the wrong place to request that. OMV does not maintain upstream packages. You need to request that at the Debian project.

**Comment by MaddTheSane** [comment]
Yes, I am talking about the Transmission Debian package.

**Comment by votdev** [comment]
> Yes, I am talking about the Transmission Debian package.

As already said, the openmediavault project is not responsible for that. Please request that at the Debian project or the Tranmission project itself.
