### ISSUE TITLE
debian 12 install omv

### ISSUE THREAD

**Issue by dossec** [openmediavault/openmediavault#1601]
I encountered the following error when installing omv on debian12：

The following packages have unmet dependencies:
 php-pam : Depends: phpapi-20190902 but it is not installable
E: Unable to correct problems, you have held broken packages.

Does omv not support debian12 yet?

**Comment by votdev** [comment]
Debian 12 is only supported by OMV7 which is currently under development. You have to use Debian 11 for OMV6.
