### ISSUE TITLE
Dashboard device status sync fails during drive disconnection

### ISSUE THREAD

**Issue by damelco** [openmediavault/openmediavault#1602]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

having temporarily disconnected a usb drive, the status in the Dashboard displays invalid information.

**To Reproduce**

`File Systems`
`Missing`
`/dev/sdc1: Not mounted`
`/dev/sde1: 7.28TiB`

`S.M.A.R.T.`
`/dev/sda - GREEN`
`/dev/sdc - GREEN`
`/dev/sde - AMBER`

**Expected behavior**

device status' should still be in sync

**Screenshots**

tried to add four times?!

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: Linux 6.1.0-0.deb11.11-amd64
- openmediavault version: 6.9.0-1

**Client (please complete the following information):**

- Device: PC
- OS: Win7
- Browser FF
- Version current ESR

**Additional context**

**Comment by votdev** [comment]
Could you please be more specific. I really have no idea what the problem exactly is. How can we reproduce this. Please add a step by step description.
