### ISSUE TITLE
SMB Encryption/ Transport encryption option has the wrong syntax

### ISSUE THREAD

**Issue by edominicci** [openmediavault/openmediavault#1605]
The Samba version of OMV 6.9.2-1 (Shaitan) is 4.13.13, and the syntax for "Transport encryption" per share is currently set as:
`server smb encrypt = required`

That previous syntax is for Samba v4.14 and above. The correct syntax for v4.13 and older is:
`smb encrypt = required`

I was able to verify this and reproduce it. Once OMV/Debian starts using v4.14, this syntax would need to be fixed again.

**Comment by votdev** [comment]
I'm wondering that `samba-tool testparm` has not detected that misconfiguration.

**Comment by votdev** [comment]
> I was able to verify this and reproduce it. Once OMV/Debian starts using v4.14, this syntax would need to be fixed again.

No, this is not necessary:

```
smb encrypt (S)

    This is a synonym for [server smb encrypt](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#SERVERSMBENCRYPT).

    Default: smb encrypt = default
```

**Comment by edominicci** [comment]
Well, you are 100% absolutely right. Not sure why it wasn't working earlier, but as soon as you said that, I deleted the share and re-created it with transport encryption and now it works.

It could have been an old misconfig from a long time ago, my OMV server has been upgrated several times since version 3.xx
