### ISSUE TITLE
Add multiple shared folders in openmediavault-filebrowser 

### ISSUE THREAD

**Issue by lucad987** [openmediavault/openmediavault#1611]
**Is your feature request related to a problem? Please describe.**
Actually only one shared folder is possible to be added in openmediavault-filebrowser plugin while it is possible to add multiple shared folders in the docker version of fileborser.

**Describe the solution you'd like**
Adding multiple shared folders to choose in the openmediavault-filebrowser settings UI ( /services/filebrowser ).

**Describe alternatives you've considered**
A fallback could be editing the appropriate files directly in the OMV once the plugin is already enabled and configured for one shared folder only.

**Comment by votdev** [comment]
Only one shared folder is supported because if you design your shared folder topography clever, you only need one root shared folder. This is because OMV supports shared folders in shared folders.

**Comment by lucad987** [comment]
You can easily achieve it by creating different volumes.

volumes:
  - yourPath/disk1:/srv/disk1
  - yourPath/disk2:/srv/disk2


Il Mar 10 Ott 2023, 17:00 Volker Theile ***@***.***> ha
scritto:

**Comment by lucad987** [comment]
You can easily achieve it by creating different volumes.

```
volumes:
  - yourPath/disk1:/srv/disk1
  - yourPath/disk2:/srv/disk2
```

**Comment by votdev** [comment]
> You can easily achieve it by creating different volumes.
> 
> 
> 
> ```
> 
> volumes:
> 
>   - yourPath/sharedFolder1:/srv/folder1
> 
>   - yourPath/sharedFolder2:/srv/folder2
> 
> ```
> 
> 
> 
> https://github.com/hurlenko/filebrowser-docker/issues/7

As mentioned above, using a clever shared folder topology this can be done without changing one line of code.

**Comment by votdev** [comment]
You can also create a shared folder and manually symlink the shared folders you want to have as children there.

You can also use the `openmediavault-symlinks` plugin from omv-extras.org to create the symlinks via UI.

**Comment by votdev** [comment]
The issue has been closed because there are several solutions to achieve the requested feature without modifying the plugin itself.
