### ISSUE TITLE
Add SD-Card Support to openmediavault-usbbackup Plugin

### ISSUE THREAD

**Issue by HeyMeco** [openmediavault/openmediavault#1622]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Being able to select /dev/mmcblkX as a device to be mounted, copy the files to selected shared folder and unmounted.

**Describe alternatives you've considered**
A systemd script but it would not be as clean and integrated.

**Additional context**
As someone who handles lots of SD Cards I would love to just connect them to my OMV Server and them being ingested to a shared folder in which a folder named by the current date is the copy location.

Maybe usbbackup can become "externalbackup"

**Comment by votdev** [comment]
Why not using SD card USB adapter?

**Comment by HeyMeco** [comment]
@votdev > Why not using SD card USB adapter?

As many devices especially Single Board Computers already have a Reader it would make sense to be able to use the capabilities which are already there.

**Comment by votdev** [comment]
If the community contributes the feature i am fine with that.

**Comment by superenginegit** [comment]
I'd like to contribute this, if no one is working on it
