### ISSUE TITLE
omv-firstaid doesn't allow dynamic MAC configuration of network card

### ISSUE THREAD

**Issue by sashaluda2** [openmediavault/openmediavault#1623]
**Is your feature request related to a problem? Please describe.**
After some reconfiguration and reboot my network card didn't get automatically configured. I decided to change configuration from command line using omv-firstaid. I successfully added my eth0 network card, but after reboot my network didn't autoconfigure again. Turns out that I have a dinamic MAC address on my device (Orange Pi 5). I had to manually remove two lines from netplan yaml file since the step-by-step procedure in omv-firstaid doesn't allow a dynamic MAC configuration. 

**Describe the solution you'd like**
Add an option not to bind network configuration to a specific MAC address in omv-firstaid procedure.

**Describe alternatives you've considered**
Of course I can configure the network card using yaml (debian 11), but I mustn't count on or must be warned that omv-firstaid doesn't support dynamic MAC network cards.

**Additional context**

**Comment by votdev** [comment]
> I had to manually remove two lines from netplan yaml file

Which lines do you have to remove?

**Comment by votdev** [comment]
After checking the sources OMV is already respecting interfaces with non-permanent MAC address. 

See:
- https://github.com/openmediavault/openmediavault/issues/1589
- https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/netplan/files/ethernet.j2#L6

**Comment by votdev** [comment]
Please upgrade your system to the latest version. Reopen the issue if the issue still appears.

**Comment by sashaluda2** [comment]
I now I don't have them, so I can't reproduce them with accuracy, but the
meaning was something like this:

bind
   MAC 22:33:44:55:66:77

It might have been some other term (may be not bind, maybe constrain_to or
limit_to... )
