### ISSUE TITLE
btrfs filesystems not reporting the correct sizes

### ISSUE THREAD

**Issue by sbe-arg** [openmediavault/openmediavault#1624]
btrfs filesystems show the incorrect size

![image](https://github.com/openmediavault/openmediavault/assets/23391642/e34a7213-0825-4828-831f-369e7dec754f)

![image](https://github.com/openmediavault/openmediavault/assets/23391642/56a35d0e-4066-492a-b9cd-b3ded614540c)

**Comment by votdev** [comment]
Already fixed with https://github.com/openmediavault/openmediavault/commit/09e5eaffa10c49428a518fec32c1fe68d2339fed.

**Comment by sbe-arg** [comment]
Hahaha I missed that commit!
Thanks!
