### ISSUE TITLE
Openmediavault 6.9.8-1 (Shaitan) Clamav install broken

### ISSUE THREAD

**Issue by infinitydaemon** [openmediavault/openmediavault#1632]
Same error message appears when applying (starting) Clamav plugin on multiple Raspberry devices. Older version didn't have this issue. 
![Screen Shot 2023-11-16 at 11 36 07 AM](https://github.com/openmediavault/openmediavault/assets/101006007/a74e1a01-1783-4342-9ef6-4c1ccc962dca)

**Comment by votdev** [comment]
The problem seems to be 
```
Nov 16 11:26:16 omv6box freshclam[10147]: Thu Nov 16 11:26:16 2023 -> !Can't create temporary directory /var/lib/clamav/tmp.ed5c010963
Nov 16 11:26:16 omv6box freshclam[10147]: Thu Nov 16 11:26:16 2023 -> Hint: The database directory must be writable for UID 112 or GID 119
```
BUT, i still get this error when `/var/lib/clamav` looks like this:
```
# ls -alh /var/lib/clamav
total 12K
drw-rw-r--  2 clamav clamav 4.0K Nov 16 11:17 .
drwxr-xr-x 42 root   root   4.0K Nov 16 11:17 ..
-rw-r--r--  1 clamav clamav   69 Nov 16 11:17 freshclam.dat
```
