### ISSUE TITLE
Getting unsigned error on apt-get update when following "Install OMV7 on Debian 12 (Bookworm)"

### ISSUE THREAD

**Issue by bnorquist** [openmediavault/openmediavault#1633]
error: ```Get:7 http://packages.openmediavault.org/public sandworm InRelease [12.8 kB]
Err:7 http://packages.openmediavault.org/public sandworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7E7A6C592EF35D13 NO_PUBKEY 24863F0C716B980B
Reading package lists... Done
W: GPG error: http://packages.openmediavault.org/public sandworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7E7A6C592EF35D13 NO_PUBKEY 24863F0C716B980B
E: The repository 'http://packages.openmediavault.org/public sandworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.```

**To Reproduce**

Followed instructions here exactly as root: https://forum.openmediavault.org/index.php?thread/50222-install-omv7-on-debian-12-bookworm/

using sudo as Debian user the gpg file would not write for some reason

**Comment by ryecoaaron** [comment]
You either need openmediavault-keyring package installed correctly and/or set your system’s time correctly.

**Comment by votdev** [comment]
Do you have a network connection when running the wget command? The problem seems that the command does not fail if the file can not be downloaded. This there is crap in the cert file.

**Comment by votdev** [comment]
What is the output of
```
# dpkg -l | grep openmediavault
``````

**Comment by votdev** [comment]
> using sudo as Debian user the gpg file would not write for some reason

This is the problem. Simply run `sudo su` to switch the user.

**Comment by bnorquist** [comment]
I was able to download the file and also run the command via root. This error I get in my session after running `sudo su`. I tried downloading, running the gpg command on the key and moving it manually to the correct dir but still getting the issue.

**Comment by bnorquist** [comment]
```debian@omv:~$ dpkg -l | grep openmediavault
debian@omv:~$```

**Comment by bnorquist** [comment]
Here is the full process: 

```
root@omv:/home/debian# cat /etc/apt/sources.list.d/openmediavault.list
deb http://packages.openmediavault.org/public sandworm main
# deb http://downloads.sourceforge.net/project/openmediavault/packages sandworm main
## Uncomment the following line to add software from the proposed repository.
# deb http://packages.openmediavault.org/public sandworm-proposed main
# deb http://downloads.sourceforge.net/project/openmediavault/packages sandworm-proposed main
## This software is not part of OpenMediaVault, but is offered by third-party
## developers as a service to OpenMediaVault users.
# deb http://packages.openmediavault.org/public sandworm partner
# deb http://downloads.sourceforge.net/project/openmediavault/packages sandworm partner

root@omv:/home/debian# export LANG=C.UTF-8
export DEBIAN_FRONTEND=noninteractive
export APT_LISTCHANGES_FRONTEND=none
root@omv:/home/debian#
root@omv:/home/debian#
root@omv:/home/debian# apt-get install --yes gnupg
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gnupg is already the newest version (2.2.40-1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@omv:/home/debian# wget --quiet --output-document=- https://packages.openmediavault.org/public/archive.key | gpg --dearmor --yes --output "/usr/share/keyrings/openmediavault-archive-keyring.gpg"
root@omv:/home/debian# apt-get update
Get:1 file:/etc/apt/mirrors/debian.list Mirrorlist [30 B]
Get:5 file:/etc/apt/mirrors/debian-security.list Mirrorlist [39 B]
Hit:2 https://deb.debian.org/debian bookworm InRelease
Get:3 https://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:4 https://deb.debian.org/debian bookworm-backports InRelease [56.5 kB]
Hit:6 https://deb.debian.org/debian-security bookworm-security InRelease
Get:7 https://deb.debian.org/debian bookworm-backports/main Sources.diff/Index [63.3 kB]
Get:8 https://deb.debian.org/debian bookworm-backports/main Sources T-2023-11-18-0205.58-F-2023-11-18-0205.58.pdiff [33 B]
Get:8 https://deb.debian.org/debian bookworm-backports/main Sources T-2023-11-18-0205.58-F-2023-11-18-0205.58.pdiff [33 B]
Get:9 http://packages.openmediavault.org/public sandworm InRelease [12.8 kB]
Err:9 http://packages.openmediavault.org/public sandworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7E7A6C592EF35D13 NO_PUBKEY 24863F0C716B980B
Reading package lists... Done
W: GPG error: http://packages.openmediavault.org/public sandworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7E7A6C592EF35D13 NO_PUBKEY 24863F0C716B980B
E: The repository 'http://packages.openmediavault.org/public sandworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@omv:/home/debian#
```

**Comment by bnorquist** [comment]
@votdev mind re-opening?

**Comment by ryecoaaron** [comment]
There isnt a bug to reopen it for. I would run the install script if you want to install on Debian.  Just use the -b beta flag.
https://github.com/OpenMediaVault-Plugin-Developers/installScript

Post on the forum if you have more issues.

**Comment by bnorquist** [comment]
Thanks I'll try that. Still curious what the issue is here.

**Comment by votdev** [comment]
> @votdev mind re-opening?

There is no bug in the documentation because i successfully deployed a [dev system via Vagrant](https://github.com/openmediavault/openmediavault/tree/master/vagrant/debian) right at the moment. The [install script](https://github.com/openmediavault/openmediavault/blob/master/vagrant/debian/install.sh#L44) is doing exactly the same as the [forum guide](https://forum.openmediavault.org/index.php?thread/50222-install-omv7-on-debian-12-bookworm/) and the [docs](https://docs.openmediavault.org/en/stable/installation/on_debian.html).

**Comment by bnorquist** [comment]
I'm on detain 12 and get this with the install script. ```[2023-11-18 18:51:21+0000] [omvinstall] Unsupported version.  Only Debian 10 (Buster) and 11 (Bullseye) are supported.  Exiting..```

**Comment by bnorquist** [comment]
I'm not saying there is necessarily a bug and I appreciate the help. But this is a fresh Debian 12 VM so I'm a bit confused about what is causing the issue here.

**Comment by votdev** [comment]
OK, then it is related to your installation because as mentioned above i am able to deploy a system successfully and there are already users out there that successfully installed OMV7.
Without having access to the system it is hard to find out what is going wrong on this system if it is not reproducible in general.

```
# apt-get update
Get:1 file:/var/cache/openmediavault/archives  InRelease
Ign:1 file:/var/cache/openmediavault/archives  InRelease
Get:2 file:/var/cache/openmediavault/archives  Release
Ign:2 file:/var/cache/openmediavault/archives  Release
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en 
Ign:4 file:/var/cache/openmediavault/archives  Translation-en 
Get:3 file:/var/cache/openmediavault/archives  Packages       
Ign:3 file:/var/cache/openmediavault/archives  Packages       
Get:4 file:/var/cache/openmediavault/archives  Translation-en 
Ign:4 file:/var/cache/openmediavault/archives  Translation-en 
Get:3 file:/var/cache/openmediavault/archives  Packages       
Ign:3 file:/var/cache/openmediavault/archives  Packages       
Get:4 file:/var/cache/openmediavault/archives  Translation-en 
Ign:4 file:/var/cache/openmediavault/archives  Translation-en 
Get:3 file:/var/cache/openmediavault/archives  Packages       
Ign:3 file:/var/cache/openmediavault/archives  Packages       
Get:4 file:/var/cache/openmediavault/archives  Translation-en 
Ign:4 file:/var/cache/openmediavault/archives  Translation-en 
Get:3 file:/var/cache/openmediavault/archives  Packages       
Ign:3 file:/var/cache/openmediavault/archives  Packages       
Get:4 file:/var/cache/openmediavault/archives  Translation-en 
Ign:4 file:/var/cache/openmediavault/archives  Translation-en 
Get:3 file:/var/cache/openmediavault/archives  Packages       
Ign:3 file:/var/cache/openmediavault/archives  Packages       
Get:4 file:/var/cache/openmediavault/archives  Translation-en 
Ign:4 file:/var/cache/openmediavault/archives  Translation-en 
Get:3 file:/var/cache/openmediavault/archives  Packages       
Get:4 file:/var/cache/openmediavault/archives  Translation-en 
Ign:4 file:/var/cache/openmediavault/archives  Translation-en 
Hit:5 http://packages.openmediavault.org/public sandworm InRelease
Hit:6 http://security.debian.org/debian-security bookworm-security InRelease                                
Get:7 http://httpredir.debian.org/debian bookworm-backports InRelease [56.5 kB]                             
Hit:8 https://deb.debian.org/debian bookworm InRelease                                                      
Hit:9 https://deb.debian.org/debian bookworm-updates InRelease
Get:10 http://security.debian.org/debian-security bookworm-security/contrib Sources [852 B]
Get:11 https://openmediavault.github.io/packages sandworm InRelease [12.8 kB]
Get:12 http://security.debian.org/debian-security bookworm-security/contrib amd64 Packages [644 B]
Get:13 http://security.debian.org/debian-security bookworm-security/contrib Translation-en [372 B]
Get:14 http://httpredir.debian.org/debian bookworm-backports/main amd64 Packages [136 kB]
Get:15 http://httpredir.debian.org/debian bookworm-backports/main Translation-en [114 kB]
Get:16 http://httpredir.debian.org/debian bookworm-backports/contrib amd64 Packages [4936 B]
Get:17 http://httpredir.debian.org/debian bookworm-backports/contrib Translation-en [4528 B]
Get:18 http://httpredir.debian.org/debian bookworm-backports/non-free amd64 Packages [1284 B]
Get:19 http://httpredir.debian.org/debian bookworm-backports/non-free Translation-en [544 B]
Get:20 https://openmediavault.github.io/packages sandworm/main amd64 Packages [7410 B]
Fetched 339 kB in 1s (559 kB/s)    
Reading package lists... Done
N: Repository 'Debian bookworm' changed its 'non-free component' value from 'non-free' to 'non-free non-free-firmware'
N: More information about this can be found online in the Release notes at: https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.html#non-free-split
```
You need to check the certs if the have been installed correctly.

**Comment by ryecoaaron** [comment]
You didn’t add the -b flag for beta. The link tells you how to run the script with flags.

**Comment by bnorquist** [comment]
Ah ok thanks, I figured it out regardless. I was following the instructions [here](https://forum.openmediavault.org/index.php?thread/50222-install-omv7-on-debian-12-bookworm/) which were missing `[signed-by=/usr/share/keyrings/openmediavault-archive-keyring.gpg]` in the /etc/apt/sources.list.d/openmediavault.list file. All working now, thanks for taking a look all.

**Comment by votdev** [comment]
OK, strange behaviour in Debian 12. The forum guide indeed does not use `signed-by` which worked fine in Debian 11. I've adapted the forum guide.

**Comment by ryecoaaron** [comment]
It should still work if the key was put in /etc/apt/trusted.gpg.d/ instead of /usr/share/keyrings/.

**Comment by shaunVorster** [comment]
For me, it seems like removing the signed by section and then running update sorted it out.

The package that was being blocked was openmediavault.keyring.

Now that it has been installed adding back the signed by section works fine
