### ISSUE TITLE
after several days of login (unknown amount of time) browser interface login will indicate "Software Failure"

### ISSUE THREAD

**Issue by winksmith** [openmediavault/openmediavault#1636]
I leave myself logged in to my OMV6 instance regularly. After a few days (unknown amount of time) the "Software Failure" screen is displayed (URI redirected to "/#/503").

![image](https://github.com/openmediavault/openmediavault/assets/1887566/873187b5-daae-49a2-94aa-6779a413ccb3)

The system continues to work properly. I just delete the "#/503" part in the URI and it works fine.

I have searched through my logs searching for "503" but have found nothing so I don't have a good idea as to when this occured or what is causing it:

```shell
cd /var/log
zgrep -wi 503 * */*
``` 

I'm up to date with all updates. It has been happening since I've installed the system last year, but I've just been ignoring it until now.

I have setup my login using the "Never logout" feature.

**Reference to Forum**

https://forum.openmediavault.org/index.php?thread/50289-software-failure-screen-arises-often-when-i-leave-myself-logged-in/&postID=372482#wcf27

**openmediavault Server (please complete the following information):**
- OS version: Linux nas 6.1.0-0.deb11.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4~bpo11+1 (2023-08-08) x86_64 GNU/Linux

- openmediavault version: 6.9.8-1 (but has been failing with all versions)

**Client (please complete the following information):**

- Device: Linux mark 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- OS: Ubuntu 22.04.3 LTS
- Browser Chrome
- Version 119.0.6045.105

[sysinfo.txt](https://github.com/openmediavault/openmediavault/files/13405998/sysinfo.txt

**Comment by votdev** [comment]
What is the output of
```
# journalctl -u monit
# journalctl -u nginx
```

**Comment by winksmith** [comment]
[nginx.txt](https://github.com/openmediavault/openmediavault/files/13419042/nginx.txt)
[monit.txt](https://github.com/openmediavault/openmediavault/files/13419043/monit.txt)

**Comment by votdev** [comment]
Your system has a high load from time to time which might be the reason for that (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503). In rare situations a 503 can also be raised when there are DNS issues on the client side.

**Comment by winksmith** [comment]
DNS is being provided locally in a docker which seems to be working well. I haven't noticed any excessively high loads.

![image](https://github.com/openmediavault/openmediavault/assets/1887566/89350a56-a0ad-4699-bebf-fb502e1bc6b2)

This only happens when I ask the system to leave me logged in all the time.

How should I proceed?

**Comment by votdev** [comment]
Without having logs nor a qualified error it will probably be impossible to find out what has happened here. The only thing left to do is to wait until the problem occurs again and then immediately search the logs for helpful information.

**Comment by winksmith** [comment]
The problem happens every few days without fail so reproducibility is not an issue. The problem is that I won't be there when it happens so narrowing that down will be a problem. Is there anyway I can increase the log level to the point where it says it outputs a 503? Or somehow identify when it happens?

**Comment by votdev** [comment]
You may also have a look into `/var/log/nginx/openmediavault-webgui_access.log` and `/var/log/nginx/openmediavault-webgui_error.log`.

To increase the [log level](http://nginx.org/en/docs/ngx_core_module.html#error_log) use the `OMV_NGINX_SITE_WEBGUI_LOGLEVEL` [environment variable](https://docs.openmediavault.org/en/stable/various/advset.html#environmental-variables) and run `omv-salt stage run prepare; omv-salt deploy run ngix`.

**Comment by winksmith** [comment]
What would be an appropriate value. I randomly picked "info." Is that enough?
