### ISSUE TITLE
Shareroot plugin doesn't work with btrfs

### ISSUE THREAD

**Issue by ken8521** [openmediavault/openmediavault#1638]
Not sure if this is a feature request or a bug report.

I installed OMV over Debian, and used btrfs as my OS filesystem.  When I installed the shareroot plugin, it doesn't show my OS filesystem under Filesystems, so I can't use the OS drive for shared folders.

I reinstalled using ext4 as my OS filesystem, and the plugin worked as expected.

**Comment by votdev** [comment]
What is the output of `salt-call --local --retcode-passthrough --no-color --out=json mount.fstab` when you are using a Btrfs root file system?

**Comment by ken8521** [comment]
Sorry, I thought i tagged this OMV 7....

Not sure what happened.  I reinstalled OMV 7 with btrfs to get the info you wanted, and now it's working.  Must have just been a hiccup with salt when it ran the first time.  Here's the info you requested however, but the issue seems resolved...

` root@omv7-test:~# salt-call --local --retcode-passthrough --no-color --out=json mount.fstab
/usr/lib/python3/dist-packages/salt/utils/http.py:8: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  import cgi
/usr/lib/python3/dist-packages/salt/utils/jinja.py:9: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
/usr/lib/python3/dist-packages/salt/grains/core.py:2711: DeprecationWarning: Use setlocale(), getencoding() and getlocale() instead
  ) = locale.getdefaultlocale()
{
    "local": {
        "/": {
            "device": "UUID=a5399326-1607-4c57-ae14-c1d469694aec",
            "fstype": "btrfs",
            "opts": [
                "defaults",
                "subvol=@rootfs"
            ],
            "dump": "0",
            "pass": "0"
        },
        "none": {
            "device": "UUID=a00c8dc1-19a6-490c-b2a2-22b501c07ece",
            "fstype": "swap",
            "opts": [
                "sw"
            ],
            "dump": "0",
            "pass": "0"
        },
        "/media/cdrom0": {
            "device": "/dev/sr0",
            "fstype": "udf,iso9660",
            "opts": [
                "user",
                "noauto"
            ],
            "dump": "0",
            "pass": "0"
        }
    }
}
root@omv7-test:~# 

 `

Thanks
