### ISSUE TITLE
Status inconsistent issue for Service->VirtualBox->Virtual Machines 

### ISSUE THREAD

**Issue by weyou** [openmediavault/openmediavault#164]
OMV version: 4.1.9
Location: Service->VirtualBox->Virtual Machines 

Background:  I only have one virtual machine. 

Select the virtual machine, click "Start" button to start it. After the VM status changed to "running",  the "Start" button is still enabled. and the "Stop" button is disabled(grayed out).  If I'd like to stop the VM, I have to change to other menu item and then back to this page to enable the "Stop" button.

The same situation happens after stopping the VM.  The "Stop" button is enabled and the "Start" button is disabled as is.

**Comment by votdev** [comment]
I don't know exactly which plugin you're refering, but i assume it is one of the following:

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-virtualbox
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-docker-gui

Please report the issue there. Thx.
