### ISSUE TITLE
OMV 7.0 Gui takes too long to load

### ISSUE THREAD

**Issue by rmstrait** [openmediavault/openmediavault#1640]
**Describe the bug**

When the PC is started or reboot performed OMV loads quickly but the gui takes over 2 minutes to load.

The commands "systemd-analyze" and "systemd-alalyze blame" reveal that "systemd-networkd-wait-online.service" is the culprit.

```
"~$ sudo systemd-analyze
Startup finished in 15.506s (firmware) + 6.430s (loader) + 2.351s (kernel) + 2min 3.946s (userspace) = 2min 28.235s
graphical.target reached after 2min 3.469s in userspace."
```

```
:~$ sudo systemd-analyze blame
2min 32ms systemd-networkd-wait-online.service
  30.682s apt-daily.service
   2.734s fstrim.service
   2.702s openmediavault-issue.service
   2.408s webmin.service
   2.101s nextpvr-server.service
    614ms plocate-updatedb.service
    433ms openmediavault-beep-up.service
```

**To Reproduce**

Reboot system

**Expected behavior**
Reboot or startup should take less than 1 minute.

**openmediavault Server:**
Hardware: Beelink MINI S12 n95 CPU

- OS version: Linux beelink 6.1.0-13-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

- openmediavault version:
ii  openmediavault                    7.0-10                              all          openmediavault - The open network attached storage solution
ii  openmediavault-cputemp            7.0                                 all          cpu temperature plugin for openmediavault
ii  openmediavault-keyring            1.0.2-2                             all          GnuPG archive keys of the openmediavault archive
ii  openmediavault-locate             7.0                                 all          locate plugin for OpenMediaVault.
ii  openmediavault-md                 7.0-3                               all          openmediavault Linux MD (Multiple Device) plugin
ii  openmediavault-omvextrasorg       7.0                                 all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-remotemount        7.0                                 all          Remote mount plugin for OpenMediaVault.
ii  openmediavault-resetperms         7.0                                 all          Reset Permissions
ii  openmediavault-sharerootfs        7.0-1                               all          openmediavault share root filesystem plugin
ii  openmediavault-symlinks           7.0                                 all          OpenMediaVault symlinks plugin

**Client (please complete the following information):**
- Device: Dell inspiron
- OS: Windows 11
- Browser Google Chrome
- Version latest

**Additional context**
The Beelink MINI S12 has both ethernet port and wifi. Only the ethernet port is used and the wifi is not configured.

Possibly the system is waiting for the wifi connection?

**Comment by rmstrait** [comment]
Here is the output...
```
$ systemctl cat systemd-networkd-wait-online.service
# /lib/systemd/system/systemd-networkd-wait-online.service
#  SPDX-License-Identifier: LGPL-2.1-or-later
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Wait for Network to be Configured
Documentation=man:systemd-networkd-wait-online.service(8)
DefaultDependencies=no
Conflicts=shutdown.target
BindsTo=systemd-networkd.service
After=systemd-networkd.service
Before=network-online.target shutdown.target

[Service]
Type=oneshot
ExecStart=/lib/systemd/systemd-networkd-wait-online
RemainAfterExit=yes

[Install]
WantedBy=network-online.target
```

I have the wifi device configured and disabled. currently

**Comment by ryecoaaron** [comment]
Did you try disabling the wifi at the bios level?  Or just removing it if you can?  What kind of media is the OS installed on?

**Comment by rmstrait** [comment]
So, I enabled and  configured the wifi AND plugged in the ethernet then I got a fast gui.

Here is the output of systemd-analyze blame now..

```
~$ sudo systemd-analyze blame
[sudo] password for rex:
8.373s systemd-networkd-wait-online.service
2.884s openmediavault-issue.service
2.219s webmin.service
2.081s nextpvr-server.service
 432ms openmediavault-beep-up.service
 386ms dev-nvme0n1p2.device
 306ms systemd-networkd.service
 257ms smbd.service
 195ms quotaon.service
 168ms systemd-udev-trigger.service
 162ms systemd-fsck@dev-disk-by\x2duuid-4e2684d3\x2d89ef\x2d44a5\x2d9740\x2d3c46510581da.service
 153ms proc-fs-nfsd.mount
 151ms nfs-server.service
 133ms user@1000.service
 130ms loadcpufreq.service
 119ms php8.2-fpm.service
 114ms boot-efi.mount
 109ms samba-ad-dc.service
 106ms keyboard-setup.service
 102ms systemd-resolved.service
 101ms rrdcached.service
 100ms systemd-journald.service
  90ms systemd-udevd.service
  90ms lvm2-monitor.service
  87ms srv-dev\x2ddisk\x2dby\x2duuid\x2d4e2684d3\x2d89ef\x2d44a5\x2d9740\x2d3c46510581da.mount
  82ms systemd-logind.service
  81ms systemd-journal-flush.service
  80ms modprobe@drm.service
  76ms chrony.service
  74ms openmediavault-engined.service
  66ms systemd-sysctl.service
  65ms apparmor.service
  61ms modprobe@dm_mod.service
  61ms systemd-modules-load.service
  58ms modprobe@efi_pstore.service
  55ms modprobe@loop.service
  54ms networking.service
  51ms ssh.service
  49ms nginx.service
  41ms dev-hugepages.mount
  40ms systemd-network-generator.service
  40ms dev-mqueue.mount
  39ms systemd-remount-fs.service
  38ms sys-kernel-debug.mount
  37ms sys-kernel-tracing.mount
  36ms modprobe@fuse.service
  35ms systemd-fsck@dev-disk-by\x2duuid-C393\x2dAE70.service
  35ms collectd.service
  34ms monit.service
  34ms systemd-sysusers.service
  32ms systemd-binfmt.service
  31ms kmod-static-nodes.service
  31ms nfs-mountd.service
  30ms systemd-tmpfiles-setup.service
  30ms modprobe@configfs.service
  28ms e2scrub_reap.service
  26ms rpc-statd.service
  24ms cpufrequtils.service
  24ms smartmontools.service
  23ms systemd-quotacheck.service
  21ms sys-kernel-config.mount
  17ms systemd-random-seed.service
  16ms lm-sensors.service
  16ms console-setup.service
  16ms avahi-daemon.service
  16ms nfsdcld.service
  15ms nfs-idmapd.service
  15ms openmediavault-cleanup-monit.service
  13ms openmediavault-cleanup-php.service
  13ms systemd-tmpfiles-setup-dev.service
  12ms user-runtime-dir@1000.service
  11ms dbus.service
  11ms systemd-user-sessions.service
  11ms rsyslog.service
  10ms proc-sys-fs-binfmt_misc.mount
   9ms wpa_supplicant.service
   8ms sys-fs-fuse-connections.mount
   8ms dev-disk-by\x2duuid-25a6b711\x2d3d2b\x2d4503\x2d8cb7\x2d805a056d21ac.swap
   7ms systemd-update-utmp.service
   6ms rpc-statd-notify.service
   6ms rpcbind.service
   6ms run-rpc_pipefs.mount
   6ms systemd-update-utmp-runlevel.service
   5ms systemd-rfkill.service
   3ms ifupdown-pre.service
   2ms tmp.mount
  54us blk-availability.service
lines 47-87/87 (END)
```
If I unplug the ethernet or disable the wifi then I'm back to a 3 minute wait for the web gui.

**Comment by ryecoaaron** [comment]
You could blacklist the wifi module at the kernel level in /etc/modproble.d/.  You could try rfkill as well.

**Comment by rmstrait** [comment]
Disabling wifi with `rfkill block  wlan` causes the gui delay.  I expect blacklist with have the same effect.

Also, the wifi chip is soldered on the board.

Looks like I'm stuck with it.

**Comment by rmstrait** [comment]
Well, I just now tried deleting the wifi device from the OMV gui then rebooted. Now the gui come up right away.  Tried a few more reboots to be sure I don't have the delay.

So, the fix for me was to configure the wifi device in the gui, verify wifi is working properly, then delete the device from the gui.
