### ISSUE TITLE
Missing "Software RAID" menu under "Storage" Category

### ISSUE THREAD

**Issue by Tareku99** [openmediavault/openmediavault#1645]
Decided to install omv7 to test it out, everything is working pretty well so far. 
I do have a RAID5 in my server and I mounted it successfully from under "Filesystems".

I believe that in omv6 we had a "Software RAID" Menu under "Storage"
![image](https://github.com/openmediavault/openmediavault/assets/25750256/15591399-b514-437e-be25-cfbc63fa9de5)

But it seems missing in omv7 
![image](https://github.com/openmediavault/openmediavault/assets/25750256/738ac7ea-ade7-4132-9d94-7fc782eb389a)

I would like to request this feature for om7 as well since it was very useful to have included.

**Comment by votdev** [comment]
There is a separate plugin called `md` for that.

**Comment by Tareku99** [comment]
Makes sense! Thank you for the replies. 
Prob a good note later on for changelogs!

**Comment by ryecoaaron** [comment]
It already is in the changelog - https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/debian/changelog#L4.  I'm sure it will be in the release announcement when OMV 7 is actually released.
