### ISSUE TITLE
Compile openmediavault

### ISSUE THREAD

**Issue by alamedawo** [openmediavault/openmediavault#1646]
Good night,

I wonder how could I compile the project from source code.

First I have cloned the repository to my local and then in /deb run make command, however i don't know how to continue its the first time im trying to compile a project like this. I know I can install it from the images available however i need to do it as well like this for a project.

Thanks in advance

**Comment by votdev** [comment]
To build the Debian packages simply go to `debs/openmediavault` for example and run `fakeroot debian/rules clean binary`. Make sure you have installed all packages that are [required for building the package](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/debian/control#L5).
Alternatively use the [buildenvadm.sh](https://github.com/openmediavault/openmediavault/blob/master/buildenvadm.sh) to install a build environment.

**Comment by votdev** [comment]
> I know I can install it from the images available however i need to do it as well like this for a project.

Note, the openmediavault project does not provide scripts to build ARM images. There are only scripts to build the packages, nothing more.
