### ISSUE TITLE
omv7-on-debian-12-bookworm instructions rewrote /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by simtcrom** [openmediavault/openmediavault#1648]
I was trying omv7-on-debian-12-bookworm instructions from https://forum.openmediavault.org/index.php?thread/50222-install-omv7-on-debian-12-bookworm/ on a raspberry pi 4 running bookworm.

After running below command, 

`apt-get --yes --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages --no-install-recommends --option DPkg::Options::="--force-confdef" --option DPkg::Options::="--force-confold" install openmediavault-keyring openmediavault`

it completely changed my  /etc/ssh/sshd_config

I restored my original sshd_config and it worked fine.

**Comment by votdev** [comment]
This is with reason because this file is now under control of OMV.
