### ISSUE TITLE
OMV7 - Display of Shared Folder Permission Options

### ISSUE THREAD

**Issue by flmaxey** [openmediavault/openmediavault#1649]
**Is your feature request related to a problem? Please describe.**

There are two different file and folder permissions tool sets available in OMV.  **Standard Linux Permissions (Owner, Group, Other)** and **Extended permissions (ACL's)**.  Both types are displayed, on the same page, under Storage, Shared Folders, ACL.

Currently, when creating a new Shared Folder, the file and folder permissions offered to the user are **Standard Linux Permissions** (Owner, Group, Others). During the creation process Owner, Group, Others is presented, in the GUI, as **Administrator, Users, Others**.

However when "editing" permissions, under **Storage**, **Shared Folder**, **Access Control List**, ACL's are at the top and Standard Linux permissions are below.  With this arrangement, users are likely to begin clicking ACL boxes without understanding that ACL's can conflict with, or even cancel, Standard Linux Permissions that are presented below, in a relatively small 3 line box.

Given that Standard Permissions have already been assigned to a Shared Folder, when a Shared Folder is edited, the current graphical arrangement is prone to causing new users to make the mistake of "clicking the boxes" at the top which results in mixing ACL's with Standard Linux Permissions.

**Describe the solution you'd like**

Separate Standard Permissions from ACL's, giving each type their own Icon.  
To minimize confusion, I believe the arrangement of Icons, running left to right, should be "Permissions"  (Owner, Group and Others only), "Privileges", and "ACL's" .  

Most Linux home users will only need Standard Linux File Permissions.  If Shared File Folder permissions are separated from ACL's, users will be less likely to click buttons under ACL's, on the far right.

Currently, a document exists that explains how OMV handles permissions in the OMV5 and 6 GUI's.  If the proposed change is made in OMV7, a new document will be created for OMV7 that reflects the change.

**Comment by votdev** [comment]
I don't think splitting the `ACL` page into two seperate pages will make it more useful for the users; IMO the opposite will happen and will make them more confused.

Maybe we should rearrange the page and shift the dir settings to the top and the ACL user settings to the bottom of the page + some more hints what they are exactly for.
