### ISSUE TITLE
Misleading "updates available" widget

### ISSUE THREAD

**Issue by rabelux** [openmediavault/openmediavault#1654]
I don't know whether I hadn't spotted it in version 6, but I just upgraded to 7 (worked great btw) and I noticed the "updates available" widget sounds misleading. It seems to tell me that there are updates available but there are none.

![grafik](https://github.com/openmediavault/openmediavault/assets/16120882/451066f3-9605-46ea-ac7d-a964f7b2c308)

![grafik](https://github.com/openmediavault/openmediavault/assets/16120882/cb36125b-e5a3-4391-a397-5dbb0b74ae17)

- OS: [Windows 10]
- Browser [firefox]
- Version [120]

**Comment by ryecoaaron** [comment]
This widget did exist in OMV 6.x.  But it should say Yes or No under the title.  I would hit ctrl-shift-R to see if it fixes it.  If no, then hit Check in the Update Management -> Updates tab.

It is working fine for me. I had updates available and it said Yes in the widget.  After installing them, it said No.
![image](https://github.com/openmediavault/openmediavault/assets/1914475/421010f4-1dab-44af-8f21-7220b7097401)

**Comment by rabelux** [comment]
It's working now, thanks for your fast reply!
Unfortunately I can't tell what did the trick. I reconfigured my dashboard, changed theme, installed a plugin.
After doing all of that I realized that the widged now looks like your screenshot.
