### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [openmediavault/openmediavault#1657]
Dear @openmediavault team,

It will be nice to remove old parts like:
- https://sourceforge.net/p/openmediavault/code/

There is a link to a dead docs website (to remove too):
- https://sourceforge.net/projects/openmediavault/support

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/openmediavault/

To disable/delete tabs, go here: https://sourceforge.net/projects/openmediavault/
To add a new tab, go here: https://sourceforge.net/projects/openmediavault/
To change informations, go here: https://sourceforge.net/p/openmediavault/admin/overview
To export, go here: https://sourceforge.net/p/openmediavault/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/openmediavault/admin/overview
- A new tab, go here: https://sourceforge.net/projects/openmediavault/

Thanks in advance.

**Comment by ryecoaaron** [comment]
Where did you read that omv is migration from sourceforge?  That is where the isos and a copy of the repo live.

**Comment by Neustradamus** [comment]
@ryecoaaron: The code part needs to be removed:
- https://sourceforge.net/p/openmediavault/code/

And it is possible to add the moved box like other projects.

Files can be on SF of course or/and on GitHub too.

**Comment by votdev** [comment]
The code is still there for archiving reasons.

**Comment by Neustradamus** [comment]
@votdev: Thanks!
