### ISSUE TITLE
Add build tags in tags section

### ISSUE THREAD

**Issue by Neustradamus** [openmediavault/openmediavault#1658]
Dear @openmediavault team,

Can you add tags like all other projects here?
- https://github.com/openmediavault/openmediavault/tags

Thanks in advance.

**Comment by ryecoaaron** [comment]
Why do you need tags?

**Comment by Neustradamus** [comment]
@ryecoaaron: Currently it is not possible to easy found each version in sourcecode...

There is no version:
- https://github.com/openmediavault/openmediavault/tags

-> Each version has not the same code...

And website is not good, no all announcements:
- https://forum.openmediavault.org/index.php?board/31-announcements/
- https://www.openmediavault.org/blog.html
- https://www.openmediavault.org/download.html

Example, no 7.0 versions etc.

**Comment by votdev** [comment]
This is not possible because of the structure of the repository and how the plugins are located within.

**Comment by Neustradamus** [comment]
@votdev: It is possible, this commit for example:
- https://github.com/openmediavault/openmediavault/commit/99f3da70cd1576e2942ee43195d1e15d1e654885

**Comment by votdev** [comment]
If it were somehow possible without too much effort, I would have done it long ago. I have no desire to use sub-repositories to make tags for individual Debian package versions. This is a hobby project of mine which does not have to meet the standards of big or commercial projects.

**Comment by Neustradamus** [comment]
Tag this commit for example with the version:
- 7.0-16: https://github.com/openmediavault/packages/commit/903ef3d8898bca6a2540dad5a37d65b32a20d6ac
- 7.0-15: https://github.com/openmediavault/packages/commit/fe4d8a0f0e3b9f9f4e03513f0059f62d64c482f3
- ...

**Comment by votdev** [comment]
> Tag this commit for example with the version:
> 
>     * 7.0-16: [openmediavault/packages@903ef3d](https://github.com/openmediavault/packages/commit/903ef3d8898bca6a2540dad5a37d65b32a20d6ac)
> 
>     * 7.0-15: [openmediavault/packages@fe4d8a0](https://github.com/openmediavault/packages/commit/fe4d8a0f0e3b9f9f4e03513f0059f62d64c482f3)
> 
>     * ...

This GH repo is being misused by me to host a Debian package repository. It really does not make sense to use tags here.
