### ISSUE TITLE
Remove unused "packages" sections

### ISSUE THREAD

**Issue by Neustradamus** [openmediavault/openmediavault#1659]
Dear @openmediavault team,

Can you remove "packages" sections?
- https://github.com/openmediavault/openmediavault
- https://github.com/orgs/openmediavault/packages
- https://github.com/openmediavault/openmediavault-docs
- https://github.com/openmediavault/wsdd
- https://github.com/openmediavault/shairport

It is here and disable it:
- https://github.com/organizations/openmediavault/settings/packages

Organization settings gear.

Thanks in advance.

**Comment by votdev** [comment]
It is not possible to disable the packages tab.

**Comment by Neustradamus** [comment]
@votdev: It is possible, I have done in my organizations.

I have already done the link to do it ;)

**Comment by votdev** [comment]
> @votdev: It is possible, I have done in my organizations.
> 
> I have already done the link to do it ;)

No, it is not possible.

> As of my last knowledge update in January 2022, GitHub does not have a built-in feature or setting to disable the Packages tab on an organization's page. The visibility of the Packages tab is determined by the presence of packages (such as npm, NuGet, Maven, Docker, etc.) that have been published or used within the organization's repositories.

On all your projects you're assigned to the `Packages` tab is still visible, even if it is empty.

![grafik](https://github.com/openmediavault/openmediavault/assets/1897962/cf4d0365-a510-4326-b33b-6bca37ea3c70)

![grafik](https://github.com/openmediavault/openmediavault/assets/1897962/68878d91-9f7a-4f8b-8491-148514d0a129)

![grafik](https://github.com/openmediavault/openmediavault/assets/1897962/4bfe3502-fe5a-488c-8c59-77f8190f2977)

**Comment by Neustradamus** [comment]
At right of the repository, not in organization :)

Look:
```
Releases
No releases published

Packages
No packages published

Contributors
```

**Comment by Neustradamus** [comment]
@votdev: Have you looked?

Can disable feature here:
- https://github.com/organizations/openmediavault/settings/packages

Thanks in advance.

**Comment by votdev** [comment]
IT IS NOT POSSIBLE TO DISABLE THE `Packages` TAB.
