### ISSUE TITLE
WordPress permalinks to be better

### ISSUE THREAD

**Issue by Neustradamus** [openmediavault/openmediavault#1660]
Dear @openmediavault team,

Can you improve the OMV WordPress and uses %postname% permalinks instead of a number?
- https://wordpress.org/documentation/article/customize-permalinks/

Thanks in advance.

**Comment by votdev** [comment]
Thanks for the hint, but this does not make sense for the OMV blog because 99% of the posts have the same name.

**Comment by Neustradamus** [comment]
There is a SEO problem currently without it...

Can you look this problem?

**Comment by votdev** [comment]
> There is a SEO problem currently without it...
> 
> Can you look this problem?

As mentioned, it is not possible because new package announcements ALWAYS have the same name which is `New update available` or `New updates available`.

BTW, I don't care about SEO optimazations.

**Comment by Neustradamus** [comment]
It is easy to update the news with the good title, for example latest (6.x):
- https://www.openmediavault.org/?p=3615 -> openmediavault 6.9.10

Note: There is no 7.x news.
I have found by chance after looking the source code.
