### ISSUE TITLE
Missing homepage link on the forum

### ISSUE THREAD

**Issue by Neustradamus** [openmediavault/openmediavault#1661]
Dear @openmediavault team,

There is no link to home website page on the forum:
- https://forum.openmediavault.org/

There are only two tabs in header:
- Dashboard
- Forum

Nothing in footer too.

Can you add it?

Other links are missing too, there are on website in header and footer.

Thanks in advance.

**Comment by votdev** [comment]
> Can you add it?

Why do you need it? Is there a special reason?

**Comment by votdev** [comment]
A link has been added to the footer area.

**Comment by Neustradamus** [comment]
@votdev: To return on website...

It is not possible to have?
- Homepage
- Dashboard
- Forum

**Comment by PrplHaz4** [comment]
> > Can you add it?
> 
> Why do you need it? Is there a special reason?

One of my most common reasons would be to go back to search the docs after reading something in the forum.

**Comment by Neustradamus** [comment]
@PrplHaz4: Yes etc.

It is important to have a top and a bottom links.

@votdev: Can you add it?

**Comment by votdev** [comment]
> @PrplHaz4: Yes etc.
> 
> It is important to have a top and a bottom links.
> 
> @votdev: Can you add it?

Adding a separate link to the footer area makes no sense anymore because the link at the top is ALWAYS accessible in desktop/mobile mode.

**Comment by Neustradamus** [comment]
@votdev: To follow your comment here:
- https://github.com/openmediavault/openmediavault/issues/1659#issuecomment-1864081189

You must to disable "Internal" :)

Screenshot:
- https://i.ibb.co/NKRNkPp/github-organization-settings-packages.png

Thanks in advance.

**Comment by votdev** [comment]
> @votdev: To follow your comment here:
> 
>     * [Remove unused "packages" sections #1659 (comment)](https://github.com/openmediavault/openmediavault/issues/1659#issuecomment-1864081189)
> 
> 
> You must to disable "Internal" :)
> 
> Screenshot:
> 
>     * [i.ibb.co/NKRNkPp/github-organization-settings-packages.png](https://i.ibb.co/NKRNkPp/github-organization-settings-packages.png)
> 
> 
> Thanks in advance.

That does not help. It is not possible to hide this tab. Please raise a feature request at GitHub. i don't understand your doggedness and lack of understanding on this point.

**Comment by Neustradamus** [comment]
@votdev: Ok but it is the solution, I have removed in my cases...

**Comment by Neustradamus** [comment]
@votdev: Ok but it is the solution, I have removed in my cases...

Currently in this openmediavault repository:
- https://i.ibb.co/fYdghFp/github-organization-settings-packages-openmediavault-at-repository-right.png

**Comment by ryecoaaron** [comment]
Is it causing a problem?

**Comment by Neustradamus** [comment]
@ryecoaaron: Feature does not used, better to hide this part...

**Comment by votdev** [comment]
Now i get it. You are talking about the `openmediavault` repo and not the organsiation page. You always pointed to that page and your links where to adjust that always pointed to the organisation.

**Comment by Neustradamus** [comment]
@votdev: I have specified you :)
- https://github.com/openmediavault/openmediavault/issues/1659#issuecomment-1862372775

**Comment by votdev** [comment]
> @votdev: I have specified you :)
> 
>     * [Remove unused "packages" sections #1659 (comment)](https://github.com/openmediavault/openmediavault/issues/1659#issuecomment-1862372775)
> 
> 
> Like I have specified you: "Internal" here: [github.com/organizations/openmediavault/settings/packages](https://github.com/organizations/openmediavault/settings/packages)

That's the wrong place for that setting. It has to be done in the repository settings.
![grafik](https://github.com/openmediavault/openmediavault/assets/1897962/0e7ca2ea-dac1-44c6-9596-9108223440de)

**Comment by Neustradamus** [comment]
@votdev: Oh yes, good catch! :)

**Comment by Neustradamus** [comment]
@votdev: Oh yes, good catch! :)

Please do in all repositories:
- https://github.com/orgs/openmediavault/repositories
