### ISSUE TITLE
Please completely replace shutdown command if custom `OMV_POWERMGMT_POWEROFF` variable is present

### ISSUE THREAD

**Issue by geckolinux** [openmediavault/openmediavault#1666]
Hi there, I'm running OMV Sandworm on a Raspberry Pi with a SATA -> USB adapter board and a PWM fan. The instructions say to not use the normal Linux shutdown command because it won't shut off the fan. Instead it uses a special shutdown script at `/usr/local/bin/x-c1-softsd.sh` . This is a relatively common quirk of many SBC models  used with more permanent installations and accessories.

I followed the instructions [here](https://docs.openmediavault.org/en/6.x/various/advset.html#environmental-variables) to set the `OMV_POWERMGMT_POWEROFF` variable:

    omv-env set -- OMV_POWERMGMT_POWEROFF "/usr/local/bin/x-c1-softsd.sh"
    monit restart omv-engined
    omv-salt stage run prepare
    omv-salt stage run deploy

However, it doesn't work as expected when I hit the OMV shutdown button, as it adds the `OMV_POWERMGMT_POWEROFF` value as an argument after `systemctl` , whereas I would expect it to completely replace the shutdown command with the custom variable value.

```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; systemctl /usr/local/bin/x-c1-softsd.sh 2>&1' with exit code '1': Unknown command verb /usr/local/bin/x-c1-softsd.sh.

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; systemctl /usr/local/bin/x-c1-softsd.sh 2>&1' with exit code '1': Unknown command verb /usr/local/bin/x-c1-softsd.sh. in /usr/share/php/openmediavault/system/process.inc:247
Stack trace:
#0 /usr/share/php/openmediavault/system/powermanagement.inc(45): OMV\System\Process->execute()
#1 /usr/share/php/openmediavault/system/powermanagement.inc(109): OMV\System\PowerManagement->exec()
#2 /usr/share/openmediavault/engined/rpc/system.inc(167): OMV\System\PowerManagement->shutdown()
#3 [internal function]: Engined\Rpc\System->shutdown()
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#5 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#6 /usr/sbin/omv-engined(535): OMV\Rpc\Rpc::call()
#7 {main}
```

It would seem that this problem could be easily avoided without affecting the primary development direction of OMV by simply making the custom `OMV_POWERMGMT_POWEROFF` variable completely replace the normal shutdown command instead of concatenating it after `systemctl` .

Meanwhile I am using this workaround:

`omv-env set -- OMV_POWERMGMT_POWEROFF "start xoff.service"`

/etc/systemd/system/xoff.service
```
[Unit]
Description=Make OMV run the NASPi custom shutdown script
Before=shutdown.target

[Service]
Type=simple
ExecStart=/usr/local/bin/x-c1-softsd.sh

[Install]
WantedBy=shutdown.target

**Comment by votdev** [comment]
IMO the solution described [here](https://www.psdn.io/posts/systemd-shutdown-unit/) fits much better into the systemd ecosystem.

**Comment by votdev** [comment]
I will close this because there are ways to customise systemd to do what you want.

**Comment by votdev** [comment]
BTW, I think you should have a look at https://github.com/geekworm-com/xscript which is adapted to systemd.

If your SBC image ships the old-style bash script you should better request an feature request upstream to replace these scripts with the more modern one.
