### ISSUE TITLE
Help with Windows 11 connecting to NFS share on OpenMediaVault?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [openmediavault/openmediavault#1669]
Help with Windows 11 connecting to NFS share on OpenMediaVault?  Windows 11 NFS client installed, configuration on OMV for NFS done.  Running showmount -e on Linux system shows nfs mounts.  Same visible to Windows.

Doing anon connection works from Windows 11, as using Windows 11 GUI/File explorer.  But any attempt to create file or folder, results in error 0x8000FFFF.  This is a generic error, not much help.  Set Samba/SMB share to same storage on OMV, works fine.  I set the registry keys for default user and group ids to 1000 each... which is correct for a valid user in OMV, that works, with Samba as noted above.

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ClientForNFS\CurrentVersion\Default]
"AnonymousUID"=dword:000003e8
"AnonymousGID"=dword:000003e8

C:\Users\jibun>mount -o nolock anon \\192.168.1.144\export\Storage N:
N: is now successfully connected to \\192.168.1.144\export\Storage

The command completed successfully.

C:\Users\jibun>showmount -e 192.168.1.144
Exports list on 192.168.1.144:
/export/Storage                    192.168.1.0/24
/export                            192.168.1.0/24

C:\Users\jibun>dir \\192.168.1.144\export\Storage
 Volume in drive \\192.168.1.144\export has no label.
 Volume Serial Number is 0000-0000

 Directory of \\192.168.1.144\export\Storage

12/25/2023  04:08 PM    <DIR>          .
12/25/2023  04:08 PM    <DIR>          ..
               0 File(s)          8,192 bytes
               2 Dir(s)  18,209,161,216 bytes free

N:\>dir
 Volume in drive N has no label.
 Volume Serial Number is 0000-0000

 Directory of N:\

12/25/2023  04:08 PM    <DIR>          .
12/25/2023  04:08 PM    <DIR>          ..
               0 File(s)          8,192 bytes
               2 Dir(s)  18,208,997,376 bytes free

N:\>echo 'test' > test.txt
The media is write protected.
```

Any suggestions?  What is really interesting is that if I try to use the actual id/password... not the anonymous/default in the registry...

```
C:\Users\jibun>mount -u:jibun -p:password \\192.168.1.144\export\Storage N:
Network Error - 1326

Type 'NET HELPMSG 1326' for more information.
```

**Comment by Jibun-no-Kage** [comment]
Forgot to illustrate Linux validation...

```
\# showmount -e 192.168.1.144
Export list for 192.168.1.144:
/export         192.168.1.0/24
/export/Storage 192.168.1.0/24

\# mkdir /mnt/storage
\#  mount -t nfs 192.168.1.144:/export/Storage /mnt/storage

\# mount | grep 192.168.1.144
192.168.1.144:/export/Storage on /mnt/storage type nfs (rw,relatime,vers=3,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.1.144,mountvers=3,mountport=55939,mountproto=udp,local_lock=none,addr=192.168.1.144)

\# cd /mnt/storage
\# touch touch test.txt
```

The above makes sense since root was assumed as the id?  Right?  Well... no... so something in OMV for NFS is not set right, for example...

```
\# mount -O user=jibun,pass=_P@ssw0rd -t nfs 192.168.1.144:/export/Storage /mnt/storage
\# mount | grep 192.168.1.144
192.168.1.144:/export/Storage on /mnt/storage type nfs (rw,relatime,vers=3,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.1.144,mountvers=3,mountport=55939,mountproto=udp,local_lock=none,addr=192.168.1.144)
\# cd /mnt/storage
\# touch test.txt
touch: cannot touch 'test.txt': Permission denied
```
Behavior is consistent between Windows 11 and Linux... can mount/map as anonymous in Windows and Linux, but the result is no read write permissions?  At least on Linux makes no sense, the mount clearly shows 'rw'.  And if I look at the user 'jibun' it does have read/write on the folder on the disk.  Samba SMB share works!  Only NFS is failing, common factor is OMV its self based on all of the above.

And per the OVM UI...

![image](https://github.com/openmediavault/openmediavault/assets/96628648/3f09fe11-9382-4571-96e2-ae597bd1e5d1)

**Comment by votdev** [comment]
> The root of the path is 'ro' but the actual share is 'rw', is this correct? Are not the NFS permissions inherited, or limited by parent path/directory?

You are using NFSv3, so the NFSv4 pseudo root does not affect you.

**Comment by votdev** [comment]
Make sure the file permissions match. The settings in the shared folder `Permissions` page do not affect the NFS service. This is for services with an abstract permission layer like SMB or FTP. This is mentioned in the hint `These settings are used by the services to configure the user and group access rights. Please note that these settings have no effect on file system permissions.`.
You need to set the file permissions in the `Access control list` page.

**Comment by Jibun-no-Kage** [comment]
Ah... I will double check permissions.

**Comment by Jibun-no-Kage** [comment]
Well, per the UI... NFS share permissions, globally are read/write...

![image](https://github.com/openmediavault/openmediavault/assets/96628648/c1d92c79-cdf7-40ed-b9b6-4d2c82c93884)

The shared folders permissions, for the single user created, jibun, is read/write at user and jibun group read/write...

![image](https://github.com/openmediavault/openmediavault/assets/96628648/f8d16a1b-a27d-48a5-9a70-14629efa3399)

**Comment by Jibun-no-Kage** [comment]
Well, just as a test, I added no_root_squash the exported nfs share, then uninstalled and reinstalled the Client for NFS in Windows.  I had already added the AnonymousGID and AnoymouseUID registry keys, so I fully expected the anonymouse (i.e. GID/UID of root) to work... and it did.  To me that pretty much nails down it is a permissions issue between Windows and NFS, not a surprise.

I then created a Debian 11 VM, installed NFS server, configured it explicitly and that worked as well.  Using the same NFS client I just used to validate the stand alone NFS server, I tried connecting to the OMV NFS share, as root.  That worked as well, which makes sense with the file system permissions for the exported share set for user = root group = users.

I then did an explicit mount using the jibun user on the Linux client, that actually worked, had read write access.  I believe the following syntax is right, to force a specific user authentication on a remote NFS share mount, no?

```
# mount -t nfs -O user=jibun,pass=password 192.168.1.144:/export/Storage /test
```

So then I tried same in Windows... worked... but only because I enabled no_root_squash, right?  So there is still some odd permission mapping issue in OMV and Windows.
