### ISSUE TITLE
Process execution env variable problem

### ISSUE THREAD

**Issue by sotux** [openmediavault/openmediavault#167]
https://github.com/openmediavault/openmediavault/blob/1688996223aedc3ad98fc751c79f42836c3b6bdb/deb/openmediavault/usr/share/php/openmediavault/system/process.inc#L38

I reviewed the file "usr/share/php/openmediavault/system/process.inc" and found the default LANG is C, I think this is not a good defualt value. Because I'm a CJK user, my folder or file contains CJK characters. When the LANG is C, many program can't recognize these CJK folders or files.
For example, I installed downloader plugin and use youtube-dl to download a video to a CJK folder, with this LANG env, youtube-dl can't recognize the folder and put the file to a wrong place.
My OMV default LANG is zh_CN.utf8, my notebook installed ubuntu 18.04 and also set LANG=zh_CN.utf8, most program works well with this LANG value, so I think OMV should use user's default LANG and do not change it to C.

**Comment by votdev** [comment]
LANG=C is used because the backend should run ALL commands without translating their output. It is not really helpful if the backend returns error messages in chinese which can't be read by the maintainers of the plugins or if you need to post the output in the forum to get any help.

**Comment by sotux** [comment]
Maybe set LC_MESSAGES=C is a better choice?

**Comment by votdev** [comment]
> Maybe set LC_MESSAGES=C is a better choice?

Does not really work.

The problem can be solved by the plugin maintainer by telling the \OMV\System\Process not to use the environment variable. I think i will enhance the class to switch on/off LANG=C environment variable without loosing other defaul env variables. See https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/process.inc#L36 and https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/process.inc#L131.

**Comment by sotux** [comment]
I see. Thank you very much.
