### ISSUE TITLE
NFS Share improved UI documentation / regex check

### ISSUE THREAD

**Issue by HomeLabineer** [openmediavault/openmediavault#1673]
**Please only open an issue here, when advised by a moderator in openmediavault forum.** - yea, no - see my comment on this down below

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

NFS sharing page let's me attempt to save config w/ invalid subnet list (not white-space separated)

**To Reproduce**

1. Go to 'services > nfs > shares'
2. Add or edit an existing share
3. Save it
4. Apply it

Received the following:
```
----------
          ID: start_nfs_server_service
    Function: service.running
        Name: nfs-server
      Result: False
     Comment: Job for nfs-server.service canceled.
     Started: 08:50:44.706775
    Duration: 171.948 ms
     Changes:
```

Checked a couple things, found this:

```
root@vm-omv-01:~# sudo systemctl status nfs-server.service
● nfs-server.service - NFS server and services
     Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-12-29 08:50:44 CST; 3min 21s ago
    Process: 13937 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=1/FAILURE)
    Process: 13938 ExecStopPost=/usr/sbin/exportfs -au (code=exited, status=0/SUCCESS)
    Process: 13939 ExecStopPost=/usr/sbin/exportfs -f (code=exited, status=0/SUCCESS)
        CPU: 10ms

Dec 29 08:50:44 vm-omv-01 exportfs[13937]: exportfs: Invalid prefix `24,' for 192.168.11.0/24,
Dec 29 08:50:44 vm-omv-01 exportfs[13937]: exportfs: No options for /export 192.168.11.0/24,: suggest 192.168.11.0/24,(sync) to avoid warning
Dec 29 08:50:44 vm-omv-01 exportfs[13937]: exportfs: /etc/exports [3]: Neither 'subtree_check' or 'no_subtree_check' specified for export "192.168.11.0/24,:/export".
Dec 29 08:50:44 vm-omv-01 exportfs[13937]:   Assuming default behaviour ('no_subtree_check').
Dec 29 08:50:44 vm-omv-01 exportfs[13937]:   NOTE: this default has changed since nfs-utils version 1.0.x
Dec 29 08:50:44 vm-omv-01 exportfs[13937]: exportfs: Invalid prefix `24,' for 192.168.11.0/24,
Dec 29 08:50:44 vm-omv-01 exportfs[13937]: exportfs: Invalid prefix `24,' for 192.168.11.0/24,
Dec 29 08:50:44 vm-omv-01 systemd[1]: nfs-server.service: Control process exited, code=exited, status=1/FAILURE
Dec 29 08:50:44 vm-omv-01 systemd[1]: nfs-server.service: Failed with result 'exit-code'.
Dec 29 08:50:44 vm-omv-01 systemd[1]: Stopped NFS server and services.
```

**Expected behavior**
Under "Client", add your subnets and hit save then apply successfully

**Screenshots**

![image](https://github.com/openmediavault/openmediavault/assets/128737614/33417471-bffa-451b-9f73-9ad3ee04d383)

**Reference to Forum**

- This part is silly, I am trying to help improve the in app documentation, if you really want me to go to the forums first then the effort I need to exert is too much and I no longer care so I am skipping this part and if this is ignored as a result, so be it.  

**openmediavault Server (please complete the following information):**

- OS version: [uname -a]

Linux vm-omv-01 6.1.0-0.deb11.13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1~bpo11+1 (2023-10-08) x86_64 GNU/Linux

- openmediavault version: [dpkg -l | grep openmediavault]

root@vm-omv-01:~# dpkg -l | grep openmediavault
ii  openmediavault                     6.9.11-3                     all          openmediavault - The open network attached storage solution
ii  openmediavault-keyring             1.0.2-2                      all          GnuPG archive keys of the openmediavault archive

**Client (please complete the following information):**

- Device: [PC]
- OS: [Win10 / Ubuntu]
- Browser [Firefox]
- Version [121.0]

**Additional context**

So what SHOULD happen here

At the very least, make a tooltip/message or w/e on the GUI side indicating this should be white-space separated, not comma or anything else.  I tossed in a comma because, idk I just did.  The docs state it should be white-space which is good but it should be right in the UI.

REALLY, there should be a regex check when I hit save in order to save me from myself

**Comment by votdev** [comment]
> REALLY, there should be a regex check when I hit save in order to save me from myself

The config is too complex for a regex here. You can enter here so much different things which will blow up the regex and make it unmaintainable. There is currently no check because i tried to do that years ago with no satisfying result.

**Comment by votdev** [comment]
> At the very least, make a tooltip/message or w/e on the GUI side indicating this should be white-space separated, not comma or anything else.

The form field hint does not mention anything that several IP addresses or FQDN are allowed here: `Clients allowed to mount the file system, e.g. 192.168.178.0/24.`. So why should it be checked. Second, the NFS config itself does not provide that feature. because of the complexity of that field the docs are mentioned/linked in the form field hint.

**Comment by HomeLabineer** [comment]
I guess close it out.  It caught me up so I thought I would mention it.
