### ISSUE TITLE
OMV 7 doesn't install on debian when in an LXC container

### ISSUE THREAD

**Issue by nerdoc** [openmediavault/openmediavault#1678]
Simply put: OMV 7 doesn't install correctly on Debian when in an LXC container. After installing, chrony doesn't start.

Steps to reproduce: Start an LXC container with Debian, install OMV 7 there (any method)

```
omv-salt deploy run chrony
----------
          ID: configure_chrony
    Function: file.managed
        Name: /etc/chrony/chrony.conf
      Result: True
     Comment: File /etc/chrony/chrony.conf is in the correct state
     Started: 15:10:42.951022
    Duration: 121.023 ms
     Changes:   
----------
          ID: start_chrony_service
    Function: service.running
        Name: chrony
      Result: False
     Comment: Job for chrony.service failed because the control process exited with error code.
              See "systemctl status chrony.service" and "journalctl -xeu chrony.service" for details.
     Started: 15:10:43.795695
    Duration: 77.767 ms
     Changes:   
```

**Expected behavior**

chrony should start, even on an LXC container

**openmediavault Server (please complete the following information):**

- OS version: Linux <hostname> 5.15.104-1-pve #1 SMP PVE 5.15.104-2 (2023-04-12T11:23Z) x86_64 GNU/Linux

- openmediavault version: 7.0-23

**Client (please complete the following information):**

not applicable

There is a fix on [serverfault](https://serverfault.com/questions/1052509/chronyd-inside-lxc-conatiner). I opened a [PR](https://github.com/openmediavault/openmediavault-docs/pull/129) to include a hint in the debian install docs.

**Comment by ryecoaaron** [comment]
OMV requires real or virtualized hardware.  An LXC container does not provide this.

**Comment by votdev** [comment]
As already mentioned OMV is not designed to run in a container environment and there are no plans to support that.

If chrony can be tweaked by adding the `-x` argument, this can be done easily by adding it to `DAEMON_OPTS` in `/etc/default/chrony`. This file is not under control of OMV, so custom modifications are not overwritten.

**Comment by votdev** [comment]
I'm closing this issue because it only affects LXC setups which are not supported by OMV.

**Comment by nerdoc** [comment]
OK, I didn't know that LXC is not supported. Sorry for the spam then.
