### ISSUE TITLE
Install OMV7 on Debian 12 (Bookworm) - failed

### ISSUE THREAD

**Issue by mutti2324** [openmediavault/openmediavault#1679]
**Describe the bug**

I have the following setup:
- Raspberry Pi 5 8GB Board
- Raspberry Pi OS 64-Bit, 11-Dec-2023, Debian 12 bookworm 

**To Reproduce**

1. flashing the os on the sd card 
2. plug in the sd card in the raspberry 
3. power on the raspberry
4. boot from sd card
5. update and upgrade os
6. install omv by executing wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash
7. Error occurs and installation failed "Failed to preset unit, unit sshd.service does not exist."

![IMG_0650](https://github.com/openmediavault/openmediavault/assets/105969346/778d5a0e-aeee-4025-a896-d79b075c1413)

**Comment by ryecoaaron** [comment]
Did you follow the [install guide](https://wiki.omv-extras.org/doku.php?id=omv6:raspberry_pi_install)?  It works fine for OMV 7 as well.
Attaching the omv_install.log file that the install script generates would be helpful.  Or at least all of the output from the script.

**Comment by mutti2324** [comment]
No! I will follow the installation guide you provided, and I'll share my results here. thx

**Comment by votdev** [comment]
There are no differences between the OMV6 and OMV7 installation, therefore the current available docs should fit.

I am wondering about the error message and this let me believe that there was a problem during the installation because the SSH package is a hard dependency of OMV and is therefore automatically installed by the Debian package management.

**Comment by BstAA** [comment]
>  because the SSH package is a hard dependency of OMV

Perhaps it helps, to just use the [Raspi-Imager](https://downloads.raspberrypi.org/imager/imager_latest.exe) to flash the SD-Card and to activate SSH during imager setup. After that login to Raspi via SSH i.e. PuTTy etc.

**Comment by mutti2324** [comment]
hello @ryecoaaron I did everything you wrote above: 

1. installing regarding [install guide](https://wiki.omv-extras.org/doku.php?id=omv6:raspberry_pi_install) - see Step01-Step19 below
2. execute `dpkg -l | grep ssh` - see Step20 below
3. download `omv_install.log` - see Step21 below

**My Summary:** 
OMV7 has been successfully installed on the Raspberry Pi 5. It's important to note that two red highlighted traces appeared during the installation process, as depicted in the screenshot below. For a comprehensive overview of each step (Step01-Step19) undertaken in the OMV7 installation on the Raspberry Pi 5, please refer to the detailed description provided below.
![Mein großartiges Spiel - Meine großartige Aufnahme_2024-01-10_19-47-25](https://github.com/openmediavault/openmediavault/assets/105969346/445cb01c-ef1c-49ef-a283-9ca27fd5462d)

Step01: plug in micro sd card to a windows pc
![09-01-2024_18-11-00](https://github.com/openmediavault/openmediavault/assets/105969346/51b6b8d7-ac56-4016-aef5-6d13ce616180)

Step02: download the image (Raspberry Pi OS 64-Bit, 11-Dec-2023, Debian 12 bookworm)
![09-01-2024_18-11-01](https://github.com/openmediavault/openmediavault/assets/105969346/68f8172c-c0ee-46de-a56d-b404e41ccc23)
![09-01-2024_18-11-16](https://github.com/openmediavault/openmediavault/assets/105969346/ebc8f0b6-dc3a-46ed-bd50-dc92319ddd2d)

Step03: download the imager
![09-01-2024_18-11-48](https://github.com/openmediavault/openmediavault/assets/105969346/f9e6ed47-c855-4bf3-85ac-2e02e94ef166)
![09-01-2024_18-12-43](https://github.com/openmediavault/openmediavault/assets/105969346/51450ed9-2d47-44f7-b482-7f3c179752c3)

Step04: install imager
![09-01-2024_18-13-57](https://github.com/openmediavault/openmediavault/assets/105969346/9549c89c-c56c-4940-9f5b-85355545d4c4)
![09-01-2024_18-14-29](https://github.com/openmediavault/openmediavault/assets/105969346/499bc1e3-3c6b-4648-8684-520db5bfcd3c)

Step05: start imager
![09-01-2024_18-15-05](https://github.com/openmediavault/openmediavault/assets/105969346/0dc1e3a9-fa31-447d-9fd3-5a3bb1dd3c86)

Step06: Select `Raspberry Pi 5`, `2023-12-11-raspios-bookworm-arm64-lite.img.xz` and the micro sd card and continue
![09-01-2024_18-17-51](https://github.com/openmediavault/openmediavault/assets/105969346/87667dad-3d97-4c45-aaa8-d8f50a28725e)

Step07: edit the settings
![09-01-2024_18-19-16](https://github.com/openmediavault/openmediavault/assets/105969346/ac697f3b-8b44-4f00-bbbd-cb073021ec8f)

Step08: activate ssh
![09-01-2024_18-36-36](https://github.com/openmediavault/openmediavault/assets/105969346/a5618f0a-a495-4903-bd3d-12e592c4a5d4)

Step09: choose username and password
![09-01-2024_18-37-07](https://github.com/openmediavault/openmediavault/assets/105969346/9f95c6d0-84fc-4762-9d12-8f4eaa63ce28)

Step10: continue by press <yes> button
![09-01-2024_18-38-49](https://github.com/openmediavault/openmediavault/assets/105969346/dd063f7f-0492-4698-b379-99f30409be60)

Step11: continue by press <yes> button
![09-01-2024_18-38-58](https://github.com/openmediavault/openmediavault/assets/105969346/6a34ddf8-3e7c-4dcd-a579-700e6ffd3161)

Step12: write to micro sd card
![09-01-2024_18-39-34](https://github.com/openmediavault/openmediavault/assets/105969346/617e808f-06eb-42b7-a654-cd39d7e935c6)

Step13: micro sd card has been flashed successfully 
![09-01-2024_18-44-16](https://github.com/openmediavault/openmediavault/assets/105969346/b3f6f067-e50c-49e3-a2cc-ebb95100781f)

Step14: boot raspberry pi board with the flashed micro sd card

Step15: command line: `login to the raspberry `

Step16: command line: `sudo apt-get update`

Step17: command line: `sudo apt-get upgrade -y`

Step18: command line: `wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash`

Step19: installation has been completed
![Mein großartiges Spiel - Meine großartige Aufnahme_2024-01-10_19-49-55](https://github.com/openmediavault/openmediavault/assets/105969346/33f26db2-c452-4418-b2bc-7c0f5dc06d07)
![Mein großartiges Spiel - Meine großartige Aufnahme_2024-01-10_19-51-58](https://github.com/openmediavault/openmediavault/assets/105969346/44716d19-4571-460e-86ee-35d58dde230f)

Step20: command line: `dpkg -l | grep ssh`
![Mein großartiges Spiel - Meine großartige Aufnahme_2024-01-10_20-11-51](https://github.com/openmediavault/openmediavault/assets/105969346/3d398d1d-171b-4222-880a-a75390b99716)

Step21: download `omv_install.log` and attach to this comment
[omv_install.log](https://github.com/openmediavault/openmediavault/files/13892090/omv_install.log)

**Comment by mutti2324** [comment]
This issue can be close since OMV7 could be installed successfully on RPi5 (Debian 12 Bookworm) regarding [install guide](https://wiki.omv-extras.org/doku.php?id=omv6:raspberry_pi_install)

**Comment by minesmitch** [comment]
I am trying to install OMV onto a Pi 5 4Gb. I've followed the steps here about 8 times and am having the same issue. It gets 99% of the way through and freezes on installation. I see the last line you show in Step 19 first picture (Unblocking wifi with rfkill), but run into an issue 2 lines later. The next lines are "Adding eth0 to openmediavault database" and "IP address may change and you could lose connection if running this script via ssh." After the IP address line, it freezes and nothing happens even after an hour. 

This is my first Pi project, so If I could get any help on this, that would be fantastic!

**Comment by ryecoaaron** [comment]
@minesmitch follow this guide exactly - https://wiki.omv-extras.org/doku.php?id=omv7:raspberry_pi_install

If you still have problems, please post on the forum - https://forum.openmediavault.org/
