### ISSUE TITLE
Incorrect Download Link to v7.0-24 and ISO files

### ISSUE THREAD

**Issue by djot** [openmediavault/openmediavault#1680]
Where we may download the v7.0-24 ISO files?

Incorrect Download Link to v7.0-24 as described here:
https://www.openmediavault.org/?page_id=1271

![image](https://github.com/openmediavault/openmediavault/assets/1754128/d55e2a70-7c56-427f-af4b-15fab169bdce)

![image](https://github.com/openmediavault/openmediavault/assets/1754128/3863b073-bade-42cc-85b1-9ab8974939ba)

![image](https://github.com/openmediavault/openmediavault/assets/1754128/ec1471f5-6c72-4014-8418-200000e9020e)

**Comment by ryecoaaron** [comment]
It would be very difficult to release an ISO for every version of OMV.  You can upgrade from the ISO version to the latest version in the Updates tab.  No need to use omv-upgrade but that is an option as well.  Updates are something that you should do regularly.  This is the same as Debian and even Windows.  This is documented https://docs.openmediavault.org/en/stable/various/apt.html#update-management and https://wiki.omv-extras.org/doku.php?id=omv6:new_user_guide

**Comment by djot** [comment]
Yeah, thank you. I am new to this all. Got my mini PC this week. Proxmox and OMV**7.0-25** are running already.

**Comment by djot** [comment]
Not a bug, not even on the website.
