### ISSUE TITLE
RPI 4B 8GB - system unresponsive.

### ISSUE THREAD

**Issue by lucid3ye** [openmediavault/openmediavault#1684]
I have seen this issue multiple times on clean loads of OMV7 Release prior to RC1 as well as RC1 itself.    I do a clean load of PIOS Bookwoorm - set up the fan, expand the flash, reboot, OMV7 script from official site.   OMV completes setup - I can configure just one option for instance the USB SSD - or the SMB/CIFS options - or configure everything I want to set up and it will all be working - until I reboot.

First reboot across 5 clean loads - even one skipping the OMV network stack.  Any combination I could think of - same end.  You get it all configured, reboot it and it goes unresponsive.

Power off the PI, power it back on, you can watch it boot from the card - and it gets about 40 seconds in and hangs - you can't SSH in or access website.    Just bricks.

**Comment by votdev** [comment]
Is this related to the eth0 vs end0 interface post in the forum?

**Comment by lucid3ye** [comment]
Yup close it Sent from my iPhoneOn Jan 22, 2024, at 2:24 PM, Volker Theile ***@***.***> wrote:﻿
Is this related to the eth0 vs end0 interface post in the forum?

**Comment by votdev** [comment]
https://forum.openmediavault.org/index.php?thread/51130-clean-install-of-omv7-hangs-multiple-attempts/
