### ISSUE TITLE
omv-release-upgrade freezes at anacron update and omv7 install not completed

### ISSUE THREAD

**Issue by Peppa123** [openmediavault/openmediavault#1686]
Today I tried upgrading omv6 to omv6 on my hp microserver gen8 via "omv-release-upgrade". The omv6 version was up-2-date and the upgrade was running and the procedure in upgrading the packages stopped/freezes at the anacron update. During the upgrade the monit service tried to start each few minutes and failed because of deactived 7.4 php version.

Checking the ps output shows running sub processes for this package but I forgot to take a screenshot which processes were running. So I killed the subprocesses and the upgrading was running further. Don't know if something is missing now on this package. A dpkg-reconfigure didn't show anything.

Maybe at the end of the upgrading process also the omv configuration stopped at some point (is there a log file somewhere) so the omv webgui was not completed and login was not possible (502 bad gateway).

After some research I found command "omv-salt deploy run phpfpm" and it seems that the missing configuration for php was completed. 

But how to check if the omv upgrade procedure is really complete now? Which omv-salt command to trigger to check the hole installation for omv7?

**Comment by votdev** [comment]
Run `omv-salt stage run all` to re-deploy all configurations.
