### ISSUE TITLE
omv-salt error when create new user in web control

### ISSUE THREAD

**Issue by DejaVuyan** [openmediavault/openmediavault#1697]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**
when I create a new user, I will get a error 
`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color postfix 2>&1' with exit code '1': debian:`

I have tried omv 6.5 and omv 7.1, all of them have same problem, in omv 7.1, my salt version is `3006`.

How can I solve this problem？

**Comment by votdev** [comment]
> fatal: file /etc/postfix/main.cf: parameter mydomain: bad parameter value: 168.0.112

Your domain name is not configured correctly. Go to the `Network | General` page and set the correct values.
