### ISSUE TITLE
Don't show S.M.A.R.T. data on Dashboard for devices that have S.M.A.R.T. monitoring disabled

### ISSUE THREAD

**Issue by supermarkert** [openmediavault/openmediavault#1698]
**Is your feature request related to a problem? Please describe.**
I have passed through (6) drives to my OMV installation; (2) are virtual drives from Proxmox and so SMART monitoring is not possible, but the other (4) drives are directly passed through and do support SMART monitoring.
On the (2) drives that don't support it, I have disabled S.M.A.R.T. monitoring from the OMV settings. However, they still show up on the dashboard as a Black box and data as "unknown".  
If I have disabled Monitoring, then there is no reason to show a black box on the dashboard.

**Describe the solution you'd like**
If I have disabled monitoring for a drive, then don't include it on the Dashboard at all.

**Describe alternatives you've considered**
n/a

**Additional context**
See screenshots below.

![image](https://github.com/openmediavault/openmediavault/assets/15205204/d91fc043-dc1f-41d0-be6a-6b24b6e99291)

![image](https://github.com/openmediavault/openmediavault/assets/15205204/623edd4a-dcec-43fd-b806-b4097fa5cf8a)

**Comment by votdev** [comment]
To enable SMART monitoring ALL available devices must be displayed in this table. Otherwise it's like a chicken egg problem.
