### ISSUE TITLE
OMV-firstaid network configuration issue

### ISSUE THREAD

**Issue by thidasi** [openmediavault/openmediavault#1699]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

First i did install raspbian 64 bit lite to a raspberry pi 5. I set up wifi connection. After I had installed OMV, I lost the WIFI configuration due systemd-networkd installation. Later i tried to configure wlan0 interface but omv-firstaid didn't recognize the wlan0 interface. It was a horror to me.

**To Reproduce**

1. Take a raspberry pi 5
2. Get raspbian 64 bit lite
3. wget OMV
4. run omv-firstaid
5. check network configuration, missing interfaces

**Expected behavior**
recognize interfaces

# **Screenshots**

# **Reference to Forum**

**openmediavault Server (please complete the following information):**

- OS version: Linux rpi 6.1.0-rpi8-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux
- openmediavault version: [dpkg -l | grep openmediavault]
ii  openmediavault                       7.0-27                              all          openmediavault - The open network attached storage solution
ii  openmediavault-backup                7.0                                 all          backup plugin for OpenMediaVault.
ii  openmediavault-clamav                7.0-5                               all          openmediavault ClamAV plugin
ii  openmediavault-compose               7.0.6                               all          OpenMediaVault compose plugin
ii  openmediavault-cputemp               7.0                                 all          cpu temperature plugin for openmediavault
ii  openmediavault-flashmemory           7.0                                 all          folder2ram plugin for openmediavault
ii  openmediavault-keyring               1.0.2-2                             all          GnuPG archive keys of the openmediavault archive
ii  openmediavault-omvextrasorg          7.0                                 all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-sharerootfs           7.0-1                               all          openmediavault share root filesystem plugin

**Client (please complete the following information):**

- Device: raspberry pi 5
- OS: raspbian 64 bit lite
# - Browser [e.g. stock browser, safari]
# - Version [e.g. 22]

# **Additional context**

**Comment by ryecoaaron** [comment]
There is a very specific way to setup wifi for the install script to support.  That is covered in the RPi install guide (this works for OMV 7 too) https://wiki.omv-extras.org/doku.php?id=omv6:raspberry_pi_install

**Comment by votdev** [comment]
@ryecoaaron Is there something that can be improved in the omv-firstaid, or is this something that can not be addressed here?

**Comment by ryecoaaron** [comment]
The first issue with RPis is the renaming of eth0 to end0 when removing network-manager.  I think that is solved with the latest version of the install script.  I haven't done anything with wifi.  So, it is possible it is being renamed from wlan0 causing the issue.  I don't think omv-firstaid needs to change.

**Comment by thidasi** [comment]
There was only end0 in network configuration.
________________________________
Feladó: Aaron Murray ***@***.***>
Elküldve: 2024. február 1., csütörtök 18:20
Címzett: openmediavault/openmediavault ***@***.***>
Másolatot kap: thidasi ***@***.***>; Author ***@***.***>
Tárgy: Re: [openmediavault/openmediavault] OMV-firstaid network configuration issue (Issue #1699)


The first issue with RPis is the renaming of eth0 to end0 when removing network-manager. I think that is solved with the latest version of the install script. I haven't done anything with wifi. So, it is possible it is being renamed from wlan0 causing the issue. I don't think omv-firstaid needs to change.

**Comment by thidasi** [comment]
![image](https://github.com/openmediavault/openmediavault/assets/113590380/14a3969a-afe7-4be7-a821-d66f71ce2f1d)

**Comment by ryecoaaron** [comment]
What is the output of:  ip a

**Comment by thidasi** [comment]
at the very first time:
![image](https://github.com/openmediavault/openmediavault/assets/113590380/59591169-88f7-4a9f-b5b6-2bda4866efdf)

after successfull configuration
![image](https://github.com/openmediavault/openmediavault/assets/113590380/7e53cd6a-c167-4949-b147-5e76f376261c)

at that point i was able to open gui and finish the configuration from there (i have had no chance to use the lan port)

**Comment by thidasi** [comment]
i did configure wpa_supplicant
then i woke up wlan0 
sudo ip link set wlan0 down
sudo ip link set wlan0 up

and i run through some guides to get on lan

still no wlan0 in omv-firstaid

**Comment by thidasi** [comment]
by the way ifup says:
ifup: unknown interface wlan0
