### ISSUE TITLE
Language bug: WEbGUI doesn't accept password if you install omv in Turkish Language

### ISSUE THREAD

**Issue by smntsn** [openmediavault/openmediavault#170]
I have a problem with my installation, everyime. I think this is a bug. Not fixed for a long time. All OMV 4x series have this bug. (also latest **OMV 4.1.3**)

If I make installation in **Turkish language**, web interface doesn't accept password. Generates error. Changing web interface language not fixing because **base system installed with Turkish language**.
If I make base installation in English, works without problem but I want to use OMV in my native language.

![omv4x-error](https://user-images.githubusercontent.com/13038415/45060009-d5090d00-b0a6-11e8-9d48-f909016950ce.PNG)

![selecttur](https://user-images.githubusercontent.com/13038415/45059978-b86cd500-b0a6-11e8-9cf4-4c42b231d9ec.PNG)

**Comment by votdev** [comment]
Please execute the ``omv-engined -d -f`` command in the CLI and post the output here. You should also get an error message in the syslog which might be helpful.

**Comment by votdev** [comment]
I've currently checked the Debian package, the missing file exists there. Did you have installed additional plugins? Something is deleting the file, it does not happen magically. Is it possible that the filesystem is corrupt?

**Comment by smntsn** [comment]
No,
I started virtualbox to show this issue. Inserted iso image, installed with Turkish language option. Nothing added, nothing changed. Entered OMV 4.1.3 web page "admin", "openmediavault" and error popup. I know this issue for a long time. Fresh install comes with this issue.

**Comment by votdev** [comment]
Using mb_strtolower instead of strtolower in the PHP autoloader fixes that issue. Hopefully there are no more issues which are introduced by foreign locales.

**Comment by ryecoaaron** [comment]
I don't know if this is necessary but I noticed the Smarty template engine uses mb_detect_encoding to determine if the string is utf8 or iso-8859-1 and only uses mb_strtoupper if it is one of those.  It also specifies an encoding every time.

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-teamspeak3/blob/master/usr/share/ts3wi/libs/Smarty/libs/plugins/modifiercompiler.upper.php#L24

**Comment by votdev** [comment]
@ryecoaaron PHP always uses UTF-8 internally now.
