### ISSUE TITLE
Rpi4:  s.m.a.r.t does not show devices

### ISSUE THREAD

**Issue by picard12** [openmediavault/openmediavault#1703]
My NAS build (Argon Eon with raspberry rp4 since some system updates, it has not shown the devices managed by smartools, if I try to retrieve information with smartctl it seems that there is no recognized USB bridge

`sudo smartctl --xall /dev/sda
smartctl 7.3 2022-02-28 r5338 [aarch64-linux-6.1.21-v8+] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sda: Unknown USB bridge [0x174e:0x1155 (0x100)]
![SMART](https://github.com/openmediavault/openmediavault/assets/5871987/ec745d89-4ac9-4819-99d5-328936dfc965)
`
OMV 6.12/7.0.29

**Comment by votdev** [comment]
What OMV version are you using?

Please post the output of
```
# cat /proc/partitions
```

**Comment by votdev** [comment]
Maybe the problem can be fixed by adding correct values to the SMART database to allow smartctl to handle your hardware correct. You might look here:

- https://github.com/openmediavault/openmediavault/issues/1667#issuecomment-1868312422
- https://www.smartmontools.org/wiki/FAQ#SmartmontoolsDatabase
- https://www.smartmontools.org/wiki/FAQ#Couldmissingdrivedatabaseentriesbeaddedlocally

**Comment by picard12** [comment]
latest update to omv 7.0.31 smart widget now show my devices but give this error:
`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; smartctl --attributes --format=brief --info --health --log=selftest /dev/sdd 2>&1' with exit code '1': smartctl 7.3 2022-02-28 r5338 [aarch64-linux-6.1.21-v8+] (local build) Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org /dev/sdd: Unknown USB bridge [0x1741:0x1156 (0x100)] Please specify device type with the -d option. Use smartctl -h to get a usage summary `

**Comment by votdev** [comment]
> latest update to omv 7.0.31 smart widget now show my devices but give this error: `Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; smartctl --attributes --format=brief --info --health --log=selftest /dev/sdd 2>&1' with exit code '1': smartctl 7.3 2022-02-28 r5338 [aarch64-linux-6.1.21-v8+] (local build) Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org /dev/sdd: Unknown USB bridge [0x1741:0x1156 (0x100)] Please specify device type with the -d option. Use smartctl -h to get a usage summary `

Can you post the full error message. I need the PHP stack trace to understand where the problem comes from.

**Comment by picard12** [comment]
Where i can look for this full stack trace?

**Comment by picard12** [comment]
On omv 6.14:
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; smartctl --xall /dev/sda 2>&1' with exit code '1': smartctl 7.2 2020-12-30 r5155 [aarch64-linux-6.1.21-v8+] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sda: Unknown USB bridge [0x174e:0x1155 (0x100)]
Please specify device type with the -d option.

Use smartctl -h to get a usage summary


OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; smartctl --xall /dev/sda 2>&1' with exit code '1': smartctl 7.2 2020-12-30 r5155 [aarch64-linux-6.1.21-v8+] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sda: Unknown USB bridge [0x174e:0x1155 (0x100)]
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
 in /usr/share/php/openmediavault/system/storage/smartinformation.inc:138
Stack trace:
#0 /usr/share/php/openmediavault/system/storage/smartinformation.inc(169): OMV\System\Storage\SmartInformation->getData()
#1 /usr/share/openmediavault/engined/rpc/smart.inc(431): OMV\System\Storage\SmartInformation->getAttributes()
#2 [internal function]: Engined\Rpc\Smart->getAttributes(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getAttributes', Array, Array)
#5 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Smart', 'getAttributes', Array, Array, 1)
#6 {main}

**Comment by votdev** [comment]
Ah, you are trying to display the details of a disk. As you can see in the error message, smartctl has problems with your disk as r the hardware in general. OMV can not do anything here.

**Comment by kangolo** [comment]
I ran into a similar issue that's been going on for a while. This used to work on the same hardware, but I'm not sure when that changed, it's been a while.

`/etc/openmediavault/config.xml` has an entry for `devicetype`, which omv seems to use for self tests, but not for device info
```
    <smart>
      <enable>1</enable>
      <interval>1800</interval>
      <powermode>never</powermode>
      <tempdiff>10</tempdiff>
      <tempmax>45</tempmax>
      <monitor>
        <device>
          <uuid>....</uuid>
          <enable>1</enable>
          <devicefile>/dev/disk/by-id/ata-SATA_SSD_....</devicefile>
          <devicetype>sat</devicetype>
          <tempdiff>0</tempdiff>
          <tempmax>0</tempmax>
        </device>
      </monitor>
```

Running smartctl from the command line I was getting the same error as above:
```
$ smartctl -x /dev/sda
smartctl 7.2 2020-12-30 r5155 [aarch64-linux-6.1.21-v8+] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sda: Unknown USB bridge [0x13fe:0x2580 (0x100)]
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
```

I created an /etc/smart_drivedb.h file:
```
{ "USB: ; EMTEC X200",
  "0x13fe:0x2580",
  "",
  "",
  "-d sat"
}
```
where the second line is the unknown bridge id from the smartctl error. This gets added to smartct's db when it tries to look up the controller.

Now smartctl and omv are happy. Hopefully this helps people running into the same issue.

**Comment by votdev** [comment]
> I ran into a similar issue that's been going on for a while. This used to work on the same hardware, but I'm not sure when that changed, it's been a while.
> 
> `/etc/openmediavault/config.xml` has an entry for `devicetype`, which omv seems to use for self tests, but not for device info
> 
> ```
>     <smart>
>       <enable>1</enable>
>       <interval>1800</interval>
>       <powermode>never</powermode>
>       <tempdiff>10</tempdiff>
>       <tempmax>45</tempmax>
>       <monitor>
>         <device>
>           <uuid>....</uuid>
>           <enable>1</enable>
>           <devicefile>/dev/disk/by-id/ata-SATA_SSD_....</devicefile>
>           <devicetype>sat</devicetype>
>           <tempdiff>0</tempdiff>
>           <tempmax>0</tempmax>
>         </device>
>       </monitor>
> ```
> 
> Running smartctl from the command line I was getting the same error as above:
> 
> ```
> $ smartctl -x /dev/sda
> smartctl 7.2 2020-12-30 r5155 [aarch64-linux-6.1.21-v8+] (local build)
> Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org
> 
> /dev/sda: Unknown USB bridge [0x13fe:0x2580 (0x100)]
> Please specify device type with the -d option.
> 
> Use smartctl -h to get a usage summary
> ```
> 
> I created an /etc/smart_drivedb.h file:
> 
> ```
> { "USB: ; EMTEC X200",
>   "0x13fe:0x2580",
>   "",
>   "",
>   "-d sat"
> }
> ```
> 
> where the second line is the unknown bridge id from the smartctl error. This gets added to smartct's db when it tries to look up the controller.
> 
> Now smartctl and omv are happy. Hopefully this helps people running into the same issue.

Maybe you should contribute that to the smartmontools project, so that these changes are added to the official driver database. This way other users of smartmontools will benefit from that.

**Comment by picard12** [comment]
I add some line to /var/lib/smartmontools/drivedb/drivedb.h
and work very well.

**Comment by kangolo** [comment]
@picard12 that file will get replaced if there's a smartmontools update.
Adding the same lines to /etc/smart_drivedb.h should persist across updates.
