### ISSUE TITLE
Partition table already gone before confirmation (OMV 7)

### ISSUE THREAD

**Issue by travnick** [openmediavault/openmediavault#1704]
**Describe the bug**
Being on partition disk screen, I'd expect that no modifications were performed on the selected disk.

Unfortunately, it looks like the partition table of selected disk is already gone, and this screen only asks if to apply the new one.

It looks like partition table is gone because running the installer again didn't show the partitions that were on the disk before.

**To Reproduce**

1. Run installer
2. Proceed until disk partitioning

**Expected behavior**

Partition table remains touched until explicitly confirmed on this screen.

**Screenshots**

![image](https://github.com/openmediavault/openmediavault/assets/619590/d5f8f950-9caf-48d4-86c4-3056529d9811)
(borrowed image from https://github.com/openmediavault/openmediavault/issues/638)

**openmediavault Server (please complete the following information):**

- OS version: `Linux xxx 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux`
- openmediavault version: `7.0-20`

**Comment by votdev** [comment]
> Unfortunately, it looks like the partition table of selected disk is already gone, and this screen only asks if to apply the new one.

Hmmm, that's not so good.

OMV is using a preseed configuration, which looks like

```
### Partitioning
# This makes partman automatically partition without confirmation.
d-i partman-auto/method string regular
d-i partman-auto/init_automatically_partition select some_device
d-i partman-auto/choose_recipe select atomic
d-i partman/default_filesystem string ext4
d-i partman/choose_partition select finish
d-i partman/confirm_write_new_label boolean true
d-i partman/confirm_nooverwrite boolean true
#d-i partman/confirm boolean true
d-i partman-lvm/device_remove_lvm boolean true
d-i partman-md/device_remove_md boolean true
```

Need to find out what is wrong here.

**Comment by votdev** [comment]
I think i have to uncomment `d-i partman/confirm boolean true` to do not display the confirmation page and to behave as expected in the above comment: `This makes partman automatically partition without confirmation.`

**Comment by votdev** [comment]
The issue will be fixed in the next released ISO.
