### ISSUE TITLE
cpu dashboard tiles shrink themselves

### ISSUE THREAD

**Issue by fuzzzor** [openmediavault/openmediavault#1712]
On dashboard, cpu dashboard tiles shrink themselves !

a short video is better than a long explanation
Watch stange effect in video [here](https://drive.google.com/file/d/1mvf-4a00489GJ_PYb0fkc3Kjh7YDinA2/view?usp=sharing)

Version
6.9.13-1 (Shaitan)

Kernel
Linux 6.1.0-0.deb11.13-amd64

Browser Google Chrome Version 121.0.6167.185 (Build officiel) (64 bits)

**Comment by votdev** [comment]
Can not reproduce this with Firefox 123.0 and Chrome Version 121.0.6167.184

![Peek 2024-02-18 17-01](https://github.com/openmediavault/openmediavault/assets/1897962/28756c6c-c4cd-4ec8-81c1-46d77ca10144)

**Comment by fuzzzor** [comment]
I can confirm that this does not happen on firefox. Only on Chrome and Edge.
