### ISSUE TITLE
Please support OpenZFS

### ISSUE THREAD

**Issue by guilt** [openmediavault/openmediavault#1716]
**Is your feature request related to a problem? Please describe.**

Looking to build a really cheap Pi based NAS with periodic FS snapshotting and disk scrubbing. 

Both Raspberry Pi and Orange Pi now support PCIe devices and high speed ethernet, making this an excellent opportunity for people to jump into using these for NAS hosting and adoption. 

The amount of RAM available in these devices is 8GB-32GB and it's no more constrained by just RAM. Single disk vdevs are okay for a starter but it's already easy to add multiple disks either via USB as well. 

When you take larger machines such as Ampere Astra you can already use multiple large disks on it quite well, making it a good SMB choice.

The best option to have something close to that I've seen on Arm64 machines is OpenMediaVault. TrueNAS is not available there and it's hard to tell whether they will do it.

From the official documentation it does not appear like ZFS support is available. But in forums, there seems to be a mention of a plugin, hence this ticket. If it were, and not advertised, please let this ticket serve as documentation.

(I also checked the forums and the posts there were updated as of 2020 as well. Just need something current on how to use it with OMV 7)

**Describe the solution you'd like**

Ideally, I would like OpenZFS based ZFS creation to be supported in OMV through the end user UI as well. Plus running configuring periodic snapshots and scrubbing. That's it.

**Describe alternatives you've considered**

I already have tried running Debian Bookworm and a UI like webmin; in addition to all ways to use the console on the now available Sandworm. The end user experience is never the same. Would prefer supporting this FS officially. A lot of people can install the required packages from Debian backports.

**Additional context**

I have built and administered many systems in production with this FS. It does copy on write updates, so it avoids many kinds of in place block change issues.. This is the sort of thing that never gets noticed but helps people run their own toasters with few issues over the years.

I felt this would be a welcome feature to most people starting off with modest devices and OMV who are also looking for more reliability and recovery from their systems, if only it were available out of the box.

Hence this request. I tried searching for other tickets for it. Couldn't find a good match, except in one thread where there is talk of licensing issues.

 I think that if people are agreeing to such a license, shipping it as a DKMS / built module is still okay. There are at least two projects which use this with Debian: Proxmox and TrueNAS Scale. Not available on Arm64 though.

Unsure how much people are willing to look at it, but leaving this ticket here as a reference for any future work and as documentation for this issue.

**Comment by ryecoaaron** [comment]
[omv-extras](https://wiki.omv-extras.org/) provides a ZFS plugin.  If you are on amd64, omv-extras provides a kernel plugin to use the proxmox kernel.  I run the proxmox kernel on all of my amd64 omv systems.

**Comment by guilt** [comment]
I am only interested in the Arm64 option. Please do not close this issue in the current situation.

**Comment by ryecoaaron** [comment]
The zfs plugin works on arm64 and is in the omv-extras repo.  There are a few users of it.  You will have to build the zfs module with dkms because OMV does not supply kernels.

**Comment by ryecoaaron** [comment]
If your arm64 board does not have sata ports, OMV does not support usb raid arrays.  You will have to create the pool from the command line if you insist on using usb.  After that, the plugin will work with these manually created pools.

**Comment by votdev** [comment]
OMV will never include ZFS into the core project because of licensing issues. But there is the omv-extras.org plugin. You can alternatively use Btrfs which is fully integrated into OMV and has no license issues; thus it comes out of the box with Debian.

**Comment by guilt** [comment]
> If your arm64 board does not have sata ports, OMV does not support usb raid arrays. You will have to create the pool from the command line if you insist on using usb. After that, the plugin will work with these manually created pools.

Thank you for the detailed response. I guess it would generally make sense to be able to create and mount volumes made on any block device though, if it shows on **lsblk**.

Many such devices are available through the USB ports on the Pi 4, like this Argon One reviewed here.

https://youtu.be/rLBdi8B5Wgk

Do let me know if you would be interested in adding such a functionality for USB based disks to the plugin. Would be happy to test and emit tiny patches as required.

**Comment by guilt** [comment]
> OMV will never include ZFS into the core project because of licensing issues. But there is the omv-extras.org plugin. You can alternatively use Btrfs which is fully integrated into OMV and has no license issues; thus it comes out of the box with Debian.

Thank you. that Btrfs may not be for me, had more issues with it before I settled to ZFS.

**Comment by votdev** [comment]
> Do let me know if you would be interested in adding such a functionality for USB based disks to the plugin. Would be happy to test and emit tiny patches as required.

OMV actively presents that in the UI with reason. We faced many many problems with USB MD-Raids in the past; that’s why OMV does not support that via UI. Users can still create them in CLI. sich MD devices can be managed via UI afterwards.

**Comment by ryecoaaron** [comment]
CDDL is not compatible with GPL3 and is one of the reasons zfs is not in the kernel and OMV.

There is a zfs plugin that provides zfs on OMV.  If it doesn't do something that you need (and can't be done from the command line), then feel free to contribute to it.  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs

There is also a luks plugin available.
