### ISSUE TITLE
NIC intel corp ethernet conn I219-lm

### ISSUE THREAD

**Issue by pbecks1963** [openmediavault/openmediavault#1719]
On a HP Prodesk 600 G2 SFF i had OMV 6.9-14 running, I upgraded to 7. The NIC doesn´t get an ip anymore now. If i set a static ip (192.168.1.22, 255.255.255.0, 192.168.1.1) i get a bad gateway error in the GUI. Tried omv-firstaid.

ps: also did a clean install. same result

**Comment by votdev** [comment]
Have you tried DHCP?

**Comment by pbecks1963** [comment]
Tried dhcp and static

**Comment by pbecks1963** [comment]
NOOOO i was locked out (3 times wrong password/username). Now i am logged in :-)
