### ISSUE TITLE
Description field inside Snapshot List (SharedFolders\Snapshots)

### ISSUE THREAD

**Issue by MarcS1975** [openmediavault/openmediavault#1720]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I dont know what SharedFolder Snapshot relates to what purpose. When I take manual snapshots I usually do it before a major change to servers (e.g. Wordpress). That process can be repeated several times if something doesn't work out. The Snapshots are a brilliant way to roll back to a working version of the folder. But in a multi-step process it is very hard to keep track of manual Snapshots and at whats stage and why they were taken.

**Describe the solution you'd like**
A simple small text field where we can write a comment regarding the particular snapshot (e.g. reason for taking)
We could then just leave comments like "before code change w/ new email functionality"

**Describe alternatives you've considered**
Documenting snapshots outside of OMV -> very cumbersome to make the link to inside OMV

**Additional context**
It would help tremendously to document reasons so we can pick the correct snapshot for our roll-backs

**Comment by votdev** [comment]
I fully understand that but OMV does not store any information about snapshots in the internal database. Snapshots are managed directly using Btrfs tools, which does not support comments. If OMV now starts to maintain references to snapshots in the database, it will be complicated to keep this information up to date as the user can still create and delete snapshots via CLI.

**Comment by MarcS1975** [comment]
Aren't you already keeping snapshot data in the omv database? It just needs 1 more field. And cli snapshots can be disregarded as they dont show up in your omv list anyway.

**Comment by votdev** [comment]
> Aren't you already keeping snapshot data in the omv database?

No

**Comment by MarcS1975** [comment]
So where do get content for the field Referenced from?

**Comment by votdev** [comment]
The shared folder name is encoded in the snapshot name.

**Comment by MarcS1975** [comment]
yes but in the GUI you show a field "**Referenced**"
see here: https://prnt.sc/po6y4lqkxnK_
which gets a tick sometimes. I assume that data is stored in your OMV database. No?

**Comment by votdev** [comment]
> which gets a tick sometimes. I assume that data is stored in your OMV database. No?

The `Referenced` information is calculated based on the shared folder data in the database. But there is NO information about Btrfs snapshots in the database.

Please believe me, if i say it is not working, then it is not working.
