### ISSUE TITLE
NUT plugin : nut-driver on OMV 7.x start even with service is Netclient

### ISSUE THREAD

**Issue by llevet** [openmediavault/openmediavault#1721]
Hi,
On plugin UPS, when mode is Netclient, the nut-driver is still enable and activate.
So it generate a constant error in journal every 15 seconds :

...
Mar 08 16:08:27 storage nut-driver@ups[513993]: Network UPS Tools - Generic HID driver 0.47 (2.8.0)
Mar 08 16:08:27 storage nut-driver@ups[513993]: USB communication driver (libusb 1.0) 0.43
Mar 08 16:08:27 storage nut-driver@ups[513993]: libusb1: Could not open any HID devices: insufficient permissions on everything
Mar 08 16:08:27 storage nut-driver@ups[513993]: No matching HID UPS found
Mar 08 16:08:27 storage nut-driver@ups[513992]: Driver failed to start (exit status=1)
Mar 08 16:08:27 storage nut-driver@ups[513992]: Network UPS Tools - UPS driver controller 2.8.0
Mar 08 16:08:27 storage systemd[1]: nut-driver@ups.service: Control process exited, code=exited, status=1/FAILURE
Mar 08 16:08:27 storage systemd[1]: nut-driver@ups.service: Failed with result 'exit-code'.
Mar 08 16:08:27 storage systemd[1]: Failed to start nut-driver@ups.service - Network UPS Tools - device driver for NUT device 'ups'.
Mar 08 16:08:42 storage systemd[1]: nut-driver@ups.service: Scheduled restart job, restart counter is at 18.
Mar 08 16:08:42 storage systemd[1]: Stopped nut-driver@ups.service - Network UPS Tools - device driver for NUT device 'ups'.
Mar 08 16:08:42 storage systemd[1]: Starting nut-driver@ups.service - Network UPS Tools - device driver for NUT device 'ups'...
Mar 08 16:08:42 storage nut-driver@ups[514044]: Network UPS Tools - Generic HID driver 0.47 (2.8.0)
Mar 08 16:08:42 storage nut-driver@ups[514044]: USB communication driver (libusb 1.0) 0.43
Mar 08 16:08:42 storage nut-driver@ups[514044]: libusb1: Could not open any HID devices: insufficient permissions on everything
Mar 08 16:08:42 storage nut-driver@ups[514044]: No matching HID UPS found
Mar 08 16:08:42 storage nut-driver@ups[514043]: Driver failed to start (exit status=1)
Mar 08 16:08:42 storage nut-driver@ups[514043]: Network UPS Tools - UPS driver controller 2.8.0
Mar 08 16:08:42 storage systemd[1]: nut-driver@ups.service: Control process exited, code=exited, status=1/FAILURE
Mar 08 16:08:42 storage systemd[1]: nut-driver@ups.service: Failed with result 'exit-code'.
Mar 08 16:08:42 storage systemd[1]: Failed to start nut-driver@ups.service - Network UPS Tools - device driver for NUT device 'ups'.
...

Normally, when UPS  is in mode = Netclient, only nut-monitor.service must be start.

Thanks.

**Comment by llevet** [comment]
Ok, found the problem.

Switching form Standalone to Netclient don't remove nut-driver@ups.service
So, even if you change the to mode = netclient , service nut-driver@ups.service still present and active.

Only removing pluging and removing nut package via "apt remove nut-client nut-server nut" to have a clean state and reinstall the pluging and chose directly mode = Netclient  work.

**Comment by votdev** [comment]
Has the problem fixed with the latest update `openmediavault-nut 7.0.3-1`?

**Comment by Joci78** [comment]
Hi,

The problem also exists with version 7.0.5-1 (Sandworm). I uninstalled, cleaned, and then installed as described. Now it is working!

Thanks!

**Comment by remlei** [comment]
this issue needs to be reopened. 

I have the same issue and my UPS is connected behind a firewall (pfsense with NUT package).
OMV is configured to connect to pfsense nut server to get UPS status

`Feb 01 16:30:15 nas systemd[1]: nut-driver@cp1500pfclcd.service: Control process exited, code=exited, status=1/FAILURE
Feb 01 16:30:15 nas systemd[1]: nut-driver@cp1500pfclcd.service: Failed with result 'exit-code'.
Feb 01 16:30:15 nas systemd[1]: Failed to start nut-driver@cp1500pfclcd.service - Network UPS Tools - device driver for NUT device 'cp1500pfclcd'.
Feb 01 16:30:30 nas systemd[1]: nut-driver@cp1500pfclcd.service: Scheduled restart job, restart counter is at 65.
Feb 01 16:30:30 nas systemd[1]: Stopped nut-driver@cp1500pfclcd.service - Network UPS Tools - device driver for NUT device 'cp1500pfclcd'.
Feb 01 16:30:31 nas systemd[1]: Starting nut-driver@cp1500pfclcd.service - Network UPS Tools - device driver for NUT device 'cp1500pfclcd'...
Feb 01 16:30:31 nas nut-driver@cp1500pfclcd[13595]: Network UPS Tools - Generic HID driver 0.47 (2.8.0)
Feb 01 16:30:31 nas nut-driver@cp1500pfclcd[13595]: USB communication driver (libusb 1.0) 0.43
Feb 01 16:30:31 nas nut-driver@cp1500pfclcd[13595]: libusb1: Could not open any HID devices: insufficient permissions on everything
Feb 01 16:30:31 nas nut-driver@cp1500pfclcd[13595]: No matching HID UPS found
Feb 01 16:30:31 nas nut-driver@cp1500pfclcd[13594]: Driver failed to start (exit status=1)
Feb 01 16:30:31 nas nut-driver@cp1500pfclcd[13594]: Network UPS Tools - UPS driver controller 2.8.0
`

the logs pertains finding a USB connected UPS but I have that connected to my pfsense via serial rs232.
doing as the posted on 2nd post comment did fix the issue, basically nuking everything NUT related on the system and install and configure from fresh start. Probably had something to do in OMV update process that messed this up.

**Comment by votdev** [comment]
> this issue needs to be reopened.
> 
> I have the same issue and my UPS is connected behind a firewall (pfsense with NUT package). OMV is configured to connect to pfsense nut server to get UPS status
> 
> `Feb 01 16:30:15 nas systemd[1]: nut-driver@cp1500pfclcd.service: Control process exited, code=exited, status=1/FAILURE Feb 01 16:30:15 nas systemd[1]: nut-driver@cp1500pfclcd.service: Failed with result 'exit-code'. Feb 01 16:30:15 nas systemd[1]: Failed to start nut-driver@cp1500pfclcd.service - Network UPS Tools - device driver for NUT device 'cp1500pfclcd'. Feb 01 16:30:30 nas systemd[1]: nut-driver@cp1500pfclcd.service: Scheduled restart job, restart counter is at 65. Feb 01 16:30:30 nas systemd[1]: Stopped nut-driver@cp1500pfclcd.service - Network UPS Tools - device driver for NUT device 'cp1500pfclcd'. Feb 01 16:30:31 nas systemd[1]: Starting nut-driver@cp1500pfclcd.service - Network UPS Tools - device driver for NUT device 'cp1500pfclcd'... Feb 01 16:30:31 nas nut-driver@cp1500pfclcd[13595]: Network UPS Tools - Generic HID driver 0.47 (2.8.0) Feb 01 16:30:31 nas nut-driver@cp1500pfclcd[13595]: USB communication driver (libusb 1.0) 0.43 Feb 01 16:30:31 nas nut-driver@cp1500pfclcd[13595]: libusb1: Could not open any HID devices: insufficient permissions on everything Feb 01 16:30:31 nas nut-driver@cp1500pfclcd[13595]: No matching HID UPS found Feb 01 16:30:31 nas nut-driver@cp1500pfclcd[13594]: Driver failed to start (exit status=1) Feb 01 16:30:31 nas nut-driver@cp1500pfclcd[13594]: Network UPS Tools - UPS driver controller 2.8.0 `
> 
> the logs pertains finding a USB connected UPS but I have that connected to my pfsense via serial rs232. doing as the posted on 2nd post comment did fix the issue, basically nuking everything NUT related on the system and install and configure from fresh start. Probably had something to do in OMV update process that messed this up.

Have you configured the plugin properly? If you have configured the plugin in `Netclient` mode, then the `nut-driver@xxx.service` [should have been stopped](https://github.com/openmediavault/openmediavault/blob/9a54418d3d224c962fdd414e820141a4b9073048/deb/openmediavault-nut/srv/salt/omv/deploy/nut/default.sls#L212).

**Comment by learmj** [comment]
Hi. This still seems to be a problem today. OMV8 on Debian Trixie arm64:
```
$ sudo cat /etc/nut/nut.conf 
# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.
MODE=netclient
```
```
Jun 18 13:51:39 tank systemd[1]: Starting nut-driver@ups.service - Network UPS Tools - device driver for NUT device 'ups'...
Jun 18 13:51:39 tank nut-driver@ups[593492]: Network UPS Tools - Generic HID driver 0.52 (2.8.1)
Jun 18 13:51:39 tank nut-driver@ups[593492]: USB communication driver (libusb 1.0) 0.46
Jun 18 13:51:39 tank nut-driver@ups[593492]: libusb1: Could not open any HID devices: insufficient permissions on everything
Jun 18 13:51:39 tank nut-driver@ups[593492]: No matching HID UPS found
Jun 18 13:51:39 tank nut-driver@ups[593492]: upsnotify: notify about state 4 with libsystemd: was requested, but not running as a service unit now, will not spam more about it
Jun 18 13:51:39 tank nut-driver@ups[593492]: upsnotify: failed to notify about state 4: no notification tech defined, will not spam more about it
Jun 18 13:51:39 tank nut-driver@ups[593465]: Driver failed to start (exit status=1)
Jun 18 13:51:39 tank nut-driver@ups[593465]: Network UPS Tools - UPS driver controller 2.8.1
Jun 18 13:51:39 tank systemd[1]: nut-driver@ups.service: Control process exited, code=exited, status=1/FAILURE
Jun 18 13:51:39 tank systemd[1]: nut-driver@ups.service: Failed with result 'exit-code'.
Jun 18 13:51:39 tank systemd[1]: Failed to start nut-driver@ups.service - Network UPS Tools - device driver for NUT device 'ups'.
```
It continually tries to restart, spamming the logs, so I've had to mask it to stop it running...
```
$ sudo systemctl status nut-driver@ups.service
● nut-driver@ups.service - Network UPS Tools - device driver for NUT device 'ups'
     Loaded: loaded (/usr/lib/systemd/system/nut-driver@.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/nut-driver@ups.service.d
             └─nut-driver-enumerator-generated-checksum.conf, nut-driver-enumerator-generated.conf
     Active: activating (auto-restart) (Result: exit-code) since Thu 2026-06-18 13:56:13 BST; 12s ago
 Invocation: 0fa222fe6fb24b7ca5e141aee09b700b
    Process: 594160 ExecStartPre=/usr/bin/systemd-tmpfiles --create /usr/lib/tmpfiles.d/nut-common-tmpfiles.conf (code=exited, status=0/SUCCESS)
    Process: 594162 ExecStart=/bin/sh -c NUTDEV="`/usr/libexec/nut-driver-enumerator.sh --get-device-for-service ups`" && [ -n "$NUTDEV" ] || { echo "FATAL: Could not find a NUT device section for>
        CPU: 46ms
```
Furthermore, NUT monitoring starts before networking is up, but this only really makes sense if not connected to a UPS locally rather than monitoring a UPS over the network. The unfortunate side effect of this however is that if OMV is configured for UPS event notification, this results in several notifications (emails) about connection being lost before connection is established (ie when networking comes up). Architecturally, I imagine there is little that can be done about this since both NUT and OMV are behaving as expected.
