### ISSUE TITLE
Transfer Rate Drops when Firefox is closed in OMV7

### ISSUE THREAD

**Issue by D-G-L** [openmediavault/openmediavault#1723]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: [uname -a]
- openmediavault version: [dpkg -l | grep openmediavault]

**Client (please complete the following information):**

**Additional context**

**Comment by votdev** [comment]
Can you please a little bit more descriptive what this issue is about?

**Comment by D-G-L** [comment]
A strange Behaviour when files are copied from a Synology NAS to the OMV 7 Installation:
When I copy files (Copy-Paste) from an Synology NAS Share to a OMV 7 Share the Data Rate is suddenly dropping down. (see Pictures) and connection to Copy Box is lost,
System copied from: Win 8.1 with Synology NAS in Network,System copied to OMV 7 runs under Bookworm on a Raspberry 4 (4 GB).
![Firefox](https://github.com/openmediavault/openmediavault/assets/80029567/0aac2b2d-3903-46b9-a6b4-fbd1d6f29eb3)
![Firefox2](https://github.com/openmediavault/openmediavault/assets/80029567/a3c721f6-2a7c-4f7f-a895-5704c8a6cefd)

**Comment by votdev** [comment]
> The dents in Data Transfer rate appear exactly when Firefox is closed.

That's strange indeed, but i do not see any relation here. When a browser is closed, the network connection on port 80 or 443 is dropped, nothing more; no more network activity.
