### ISSUE TITLE
Formatting on filesystem creation progress box breaks down

### ISSUE THREAD

**Issue by cfhsncb** [openmediavault/openmediavault#1726]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

**To Reproduce**

1. Create a filesystem on a volume with >100,000 inode tables. 
2. Watch progress
3. Once the created inode table count increases above 100,000 the formatting breaks and progress is repeatedly printed on the same line scrolling to the right endlessly.

**Expected behavior**

Formatting should stay consistent even when creating filesystems with > 100,000 inode tables.

**Screenshots**

![Screenshot from 2024-03-09 19-49-34](https://github.com/openmediavault/openmediavault/assets/59964848/cf5b5d2f-8aa6-4515-8303-e6967ead5d01)
![Screenshot from 2024-03-09 19-49-16](https://github.com/openmediavault/openmediavault/assets/59964848/3d38800c-1b32-4c6b-82ed-2fb777c81148)
![Screenshot from 2024-03-09 19-49-03](https://github.com/openmediavault/openmediavault/assets/59964848/cb173042-039e-41ee-9fdd-c33cf9aa83bc)

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: [Linux iota 6.1.0-0.deb11.13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1~bpo11+1 (2023-10-08) x86_64 GNU/Linux]
- openmediavault version: [6.9.14-1]

**Client (please complete the following information):**

- Device: [x86-64 PC]
- OS: [Linux Mint 21.3]
- Browser [Firefox for Linux Mint (mint-001 - 1.0)]
- Version [123.0]

**Additional context**

Discovered when creating EXT4 file system on RAID 5 array with 4x 8TB disks.

**Comment by votdev** [comment]
I can not do anything here because the CLI command is using techniques to reposition the cursor in the CLI which can not reproduced in the UI.

**Comment by votdev** [comment]
At the moment i can only say that this [code](https://github.com/openmediavault/openmediavault/blob/ae818a1922c4e7fd0575667c67212059783e6934/deb/openmediavault/workbench/src/app/shared/components/task-dialog/task-dialog.component.ts#L187) is the reason for this behaviour; but nothing more.

**Comment by votdev** [comment]
The line is correctly broken at the line break, see attached video. So i think it's because the output of mkfs.ext4 which surely uses some special characters to reposition the cursor and not using line breaks.

![Peek 2024-03-10 17-15](https://github.com/openmediavault/openmediavault/assets/1897962/09909048-17f9-4d7b-b7a4-4dabc7899e71)

**Comment by votdev** [comment]
This is what the backend submits to the frontend:
```
\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008done                            
Creating journal (262144 blocks): done
Writing superblocks and filesystem accounting information:    0/2800\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008         \u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008done

```

```
Creating new GPT entries in memory.
Disk /dev/sdc: 734003200 sectors, 350.0 GiB
Model: QEMU HARDDISK   
Sector size (logical/physical): 512/512 bytes
Disk identifier (GUID): 1D3C3178-B426-4133-AC24-D0F1910242E3
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 734003166
Partitions will be aligned on 2048-sector boundaries
Total free space is 2014 sectors (1007.0 KiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048       734003166   350.0 GiB   8300  
The operation has completed successfully.
mke2fs 1.47.0 (5-Feb-2023)
Discarding device blocks:        0/91750139\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008                 \u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008done                            
Creating filesystem with 91750139 4k blocks and 22937600 inodes
Filesystem UUID: b7c8d9e8-57d2-4adb-87cc-91dd17ede3ce
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968

Allocating group tables:    0/2800\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008         \u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008done                            
Writing inode tables:    0/2800\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008"
```
As already mentioned, `mkfs` is repositioning the cursor when run in CLI. This output can not be displayed the same way in the UI.

Because the UI has to take care not to consume too much resources (otherwise the browser will crash), the displayed output has to be shrunk. 

Normally CLI commands output their content line by line. The algorithm for cutting out output that has already been displayed implements precisely this behavior. It searches for the next possible line break. If this is not found, the output is simply cut off at a certain point. And this is exactly what happens with the problem described here. The output of `mkfs` uses virtually no line breaks. This is why the output is displayed so unattractively after a certain point.

**Comment by jasonhollis** [comment]
<img width="1182" alt="Image" src="https://github.com/user-attachments/assets/e1d63f60-a5ba-47ae-8807-6349b872ef5b" />

I'm not sure how this couldn't be something considered for a fix.  I'm trying to build a 32gig filesystem and at this point I have no idea when the job will complete?  Is it hours or days?

**Comment by votdev** [comment]
> <img alt="Image" width="1182" src="https://private-user-images.githubusercontent.com/19743618/442472815-e1d63f60-a5ba-47ae-8807-6349b872ef5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY5NDc4MzksIm5iZiI6MTc0Njk0NzUzOSwicGF0aCI6Ii8xOTc0MzYxOC80NDI0NzI4MTUtZTFkNjNmNjAtYTViYS00N2FlLTg4MDctNjM0OWI4NzJlZjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTExVDA3MTIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMTRlZTYxN2E3Mjk1NDM0NTMyNjgyMzdmOGZjNDMwZjQxNzc5NTQzM2VlYmFlMDdlY2E4ZTdmZTkzYjhlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._oU39PYcb0prrikFeTgnHVE76P85FsyJa9FTiZUR7M0">
> I'm not sure how this couldn't be something considered for a fix. I'm trying to build a 32gig filesystem and at this point I have no idea when the job will complete? Is it hours or days?

If the mkfs CLI tool used for formatting does not even show the expected time, how is the UI backend supposed to do this? Guessing?
The UI can only display what the tool outputs.

**Comment by jasonhollis** [comment]
If I ran it from the command line I would know where I was in the process.  It's almost impossible to know this from the UI.  If I spend 10 minutes scrolling right I might be able to find out.  In a bash shell I would know exactly where I was relative to completion.

**Comment by votdev** [comment]
> If I ran it from the command line I would know where I was in the process. It's almost impossible to know this from the UI. If I spend 10 minutes scrolling right I might be able to find out. In a bash shell I would know exactly where I was relative to completion.

This issue contains several explanations why it is like it is.
If you think you can do it better feel free to contribute the improvement, the community will thank you.

**Comment by jasonhollis** [comment]
I have read all of the thread.  It does not mean it's not a bug.  Formatting a volume through this mechanism - the GUI does not provide the same things as the command line does for more than 100 blocks.  I will contemplate it and contribute if I have time but if that means re-architecture or what ever it means it should be addressed.  This is only a 32 gig filesystem.  They are not going to get smaller.  This issue will continue to be commented on until it's addressed.
