### ISSUE TITLE
[Feature request] Use Unattended-Upgrades

### ISSUE THREAD

**Issue by zero77** [openmediavault/openmediavault#173]
Hi
Can you please use unattended-upgrades to automatically check for and install updates, it can also be configured to uninstall unused software and a rainge of other related things.

To my knowledge it now comes installed by default on a lot of modern Linux distros like ubuntu but, it needs configuring to take care of updates.
Thanks

https://github.com/mvo5/unattended-upgrades

**Comment by ryecoaaron** [comment]
OMV by default will update the package list and download updates.  Ubuntu by default only updates the package list.  While I thinking automatically installing packages works well on Debian and Ubuntu, it should never be the default.

unattend-upgrades is a package in the Debian and Ubuntu repos.  You can install/configure easily or even create plugin.

**Comment by zero77** [comment]
> OMV by default will update the package list and download updates.

Will OMV also by default install the updates, or is this some thing that needs configuring.
If so, is this somewhere in the documentation.

**Comment by votdev** [comment]
You have to setup this yourself, OMV will never install updates automatically because of security and stability issues. This is something the administrator must trigger and he has to take responsibility.
