### ISSUE TITLE
Enhanced Info Request for BTRFS filesystems.

### ISSUE THREAD

**Issue by KrisbeeOMV** [openmediavault/openmediavault#1731]
BTRFS multiple device filesystems lacks the kind of info in the WebUI that exists for MD RAID.  With MD RAID there is a separate "details" page in the WebUI and "details" are also included in the "Diagnostic | Report".  

With BTRFS, unless a user "tags" a BTRFS filesytems, there is no "at-a-glance" indication of the BTRFS profile in use on the "Storage|Filesystems" page, no separate "details" page you can go to and no BTRFS filesystem details in the diagnostic report. The output of either "btrfs fi show ..." and/or "brtfs fi us -T ... " and/or "brtfs dev stats ... " is not included. 

There is a second serious information gap that relates to drive failures in BTRFS.  With MD RAID, if a drive drops out of an array a "Fail event on /dev/md.." notification rapidly follows and the MD RAID "details" in the WebUI will show the device as "removed". There is no equivalent for BTRFS as it has no in-built daemon or utility to report such events.  So there is nothing in OMV to monitor & notify for a "missing device" and catch such an event on a BTRFS RAID filesystem, no "BTRFS RAID" box to tick on the WebUI "System | Notification | Events" page.

Reacting to logged BTRFS kernel messages seems an obvious choice and one way of doing this might be to use the lightweight "simple event correlator" (https://tracker.debian.org/pkg/sec) which runs as systemd service (See for example https://marc.merlins.org/perso/btrfs/post_2014-03-19_Btrfs-Tips_-Btrfs-Scrub-and-Btrfs-Filesystem-Repair.html and https://github.com/simple-evcorr/rulesets/blob/master/systemd.md and https://simple-evcorr.github.io/man.html). The sec program works with traditional logs as inputs, i.e. syslog, messages, kern.log, etc., as per debian versions prior to debian 12. As OMV7 has retained rsyslog for its remote login function all that is needed is to restore the /etc/rsyslog.conf to debian 11 format.  Superficially at least, using sec appears to be a way of creating BTRFS error/warning messages without relying on cron or systemd timers, generating notifications in near real-time.  Thus it may be a way to add BTRFS monitoring to the existing OMV "System Notifications Events".

Requests:

1. Consider adding the same level of detail as MD RAID on a dedicated WebUI page and in "Diagnostic | Reports" for BTRFS systems.

2.  If the "sec" package is an appropriate tool,  consider its use to provide BTRFS specific notifications for BTRFS errors and warnings, including missing device errors.  

(See forum post:   https://forum.openmediavault.org/index.php?thread/51942-why-the-btrfs-information-gap/ )

**Comment by votdev** [comment]
Replacing rsyslog by sec has been rejected because it is required for the syslog forwarding feature. This is sad because sec is a really cool tool. But the email feature can also be done with rsyslog; but not as nice as with sec, the syntax is much more complicated.

- https://github.com/openmediavault/openmediavault/issues/1730
- https://github.com/openmediavault/openmediavault/blob/cfcb2f92bb5824f09ca2066b29bfd215a36d37d2/deb/openmediavault/etc/rsyslog.d/openmediavault-pamfaillock.conf#L1
