### ISSUE TITLE
OMV 7.x Missing Snapshots Schedule Tasks Choice : Custom / Yearly

### ISSUE THREAD

**Issue by llevet** [openmediavault/openmediavault#1736]
When you schedule a new Snapshots Schedule Tasks it miss the choice for Custom / Yearly on the array.
So you need to chose an other choice like Hourly/Daily/Weekly/Monthly and modify "time execution" after. 
But the command line of the snapshot is not modify automaticaly when you change the "time execution".
The consequence is the bad naming in the command line and then "omv-sfsnapadm cleanup" will don't execute properly for a Custom/ Yearly file retention.
I know you can edit the command line but it is not clean.

![Snap](https://github.com/openmediavault/openmediavault/assets/13711825/81eb0a4a-3c86-410c-8d99-5e78c8c0d4ea)

**Comment by llevet** [comment]
And also, it miss in smb.conf the snapprefix for "custom".

We have for example vol1: 
shadow:snapprefix = ^vol1\(@hourly\)\{0,1\}\(@daily\)\{0,1\}\(@weekly\)\{0,1\}\(@monthly\)\{0,1\}\(@yearly\)\{0,1\}$
Instead of : 
shadow:snapprefix = ^vol1\(@custom\)\{0,1\}\(@hourly\)\{0,1\}\(@daily\)\{0,1\}\(@weekly\)\{0,1\}\(@monthly\)\{0,1\}\(@yearly\)\{0,1\}$

**Comment by votdev** [comment]
IMO a yearly snapshot does nothing t make sense.

**Comment by votdev** [comment]
Custom snapshots can be created manually via the UI at any time. Do not see any reason for doing that programmatically via cron.

**Comment by llevet** [comment]
> IMO a yearly snapshot does not make sense. Could you give a good reason for doing that?

Because it exists everywhere ... 

![snap2](https://github.com/openmediavault/openmediavault/assets/13711825/c2b87a20-44e8-4343-8cb8-f536e0c589d5)
![snap3](https://github.com/openmediavault/openmediavault/assets/13711825/dced614d-67cc-4cf8-aa7f-988d319da34e)

/**************/

> Custom snapshots can be created manually via the UI at any time. Do not see any reason for doing that programmatically via cron.

I don't said to add it programmatically via cron, it already exists.
I said this entry in the menu must be add to have the proper "command" like below : 

![snap6](https://github.com/openmediavault/openmediavault/assets/13711825/a3b15da6-d75f-4936-b101-28ae954ad300)

Snapshot "custom" is reference of reserved word of script /usr/sbin/omv-sfsnapadm for snapshot maintenance. 
For example if i want to have 2 snapshots on the day i need to use it, and the only modifiable template is "custom" called in Time execution "Certain Date"
So "custom" on Snapshots / Schedule Task will be give us : 

![snap4](https://github.com/openmediavault/openmediavault/assets/13711825/d4e957f7-dfde-46e1-99da-e50d994812ca)

and it will obey to this rule :

![snap5](https://github.com/openmediavault/openmediavault/assets/13711825/0291cc68-77e5-4cd8-9024-2f825586965f)

Without it, it is not possible to automatic purge custom snapshots. 
The purge script (/usr/sbin/omv-sfsnapadm) clearly reference this possibility. 
  
I don't see a other place on openmediavault where the word "custom" is use in command on scheduled Task.

**Comment by madihy** [comment]
If this is something the team wants implemented I'd be happy to knock it out.

**Comment by votdev** [comment]
Snapshots that are triggered manually via UI are named „custom“; this pattern is not meant to be used by scheduled snapshot tasks. This is by the way technical not possible because the scheduled tasks are automatically generated by the backend when they are clicked in the UI. For a „custom“ scheduled task all necessary info is not available due that UI action. Because of that this type will never be available for scheduled tasks.
But yearly scheduled tasks can be implemented, even if the IMO do not make sense due their long time range.
Second, a snapshot is not meant to be a backup.

**Comment by llevet** [comment]
Ok, just see the snapshots that are triggered manually via UI are flagged as "custom" (and not named as custom).
![snap8](https://github.com/openmediavault/openmediavault/assets/13711825/d45378d9-1b2a-425b-b18a-21d0a433000e)

So, i found an other way to have automatic multiple snapshots a day at desired time :
1) In Snapshot/ Sheduled tasks chose "Daily"
2) Validate 
3) edit the task
4) change task "Time of execution"  from "Daily" to "Certain date"
5) Change "Hour" and "Minute" according your need
6) add to the Tags, for example, "12h00" "00h00"
7) Save
8) Adjust the "The number of dailly snapshots to keep" in "Settings" acording to the number you will to keep.
For example in my case : 7 days with 2 snapshots => 14 (intead of 7 by default).

Like this, all is working as desired.

As you can see, this shapshoot is made by this method ( defined to be execute at 13h10)
![snap9](https://github.com/openmediavault/openmediavault/assets/13711825/f76fb017-e3ac-4242-b520-e65f45959e37)

Perfectly scheduled ;
![snap10](https://github.com/openmediavault/openmediavault/assets/13711825/aa0fa699-7fb2-4575-9d91-aa45435bc377)

![snap11](https://github.com/openmediavault/openmediavault/assets/13711825/5b73ab7e-a9e4-4a55-9efb-a0fe1bd4178b)

![snap12](https://github.com/openmediavault/openmediavault/assets/13711825/1a32a187-3d34-479f-a88f-db7f51ca46ac)

My error mainly comes from a lack of documentation about this functionality, but we finally get there.

If it can help someone ...

And i'm agree with you, snapshot is not a backup. But it i the first step :-)

**Comment by votdev** [comment]
> My mistake mainly comes from a lack of documentation about this functionality, but we finally get there.

Now that you know how to it can be done, what about contributing your knowledge to the [documentation](https://github.com/openmediavault/openmediavault-docs), so that other users can benefit from your investigation?

**Comment by llevet** [comment]
Why not ... 
I will try to do something , but my english is far from perfect :-)
