### ISSUE TITLE
omv-mkconf monit script may calculate incorrect number of cpus

### ISSUE THREAD

**Issue by gmuller2** [openmediavault/openmediavault#174]
I found a minor issue in the mkconf script /usr/share/openmediavault/mkconf/monit.d/system.

Line 45 reads:
             numcpu=$(grep -ci processor /proc/cpuinfo)

This may return an incorrect value if any other line in /proc/cpuinfo also contains the string 'processor'; e.g. a Helios4 system only has 2 processors, but the 'model name' line contains 'ARMv7 Processor rev 1 (v7l)'.  As the result the above grep command returns '4' instead of '2' and hence the loadavg thresholds for 1min and 5min are incorrect.

The correct result is achieved by changing the above line 45 to:
             numcpu=$(grep -ci ^processor /proc/cpuinfo)

System details:
Helios4 (gen 1) board
OS: Debian 9.5
OMV: 4.1.11

**Comment by votdev** [comment]
Can you please post the output of ``/proc/cpuinfo``?

**Comment by ryecoaaron** [comment]
Or just use nproc (or maybe nproc -all)

**Comment by votdev** [comment]
[nproc](https://packages.debian.org/stretch/coreutils) is not available for powerpc which is currently supported by OMV. So we have to use the regex.

**Comment by ryecoaaron** [comment]
> [nproc](https://packages.debian.org/stretch/coreutils) is not available for powerpc which is currently supported by OMV. So we have to use the regex.

Volker, the powerpc arch was dropped in Debian Stretch.  That is why you don't see it.  So, OMV 4+ can't support powerpc either.  Maybe ppc64el but that has nproc as well.

**Comment by votdev** [comment]
> > [nproc](https://packages.debian.org/stretch/coreutils) is not available for powerpc which is currently supported by OMV. So we have to use the regex.
> 
> Volker, the powerpc arch was [dropped](https://lists.debian.org/debian-devel-announce/2016/10/msg00008.html) in Debian Stretch. That is why you don't see it. So, OMV 4+ can't support powerpc either. Maybe ppc64el but that has nproc as well.

Thanks for the info Aaron.

**Comment by gmuller2** [comment]
Volker, I noticed you already committed the fix.  Thanks.  Sorry I couldn't respond earlier.  Below is the output of /proc/cpuinfo on the Helios4 ARMv7 board.

```
# cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 1 (v7l)
BogoMIPS        : 25.00
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x4
CPU part        : 0xc09
CPU revision    : 1

processor       : 1
model name      : ARMv7 Processor rev 1 (v7l)
BogoMIPS        : 25.00
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x4
CPU part        : 0xc09
CPU revision    : 1

Hardware        : Marvell Armada 380/385 (Device Tree)
Revision        : 0000
Serial          : 0000000000000000
```

And output of _nproc_  : 
```
# nproc
2
```
