### ISSUE TITLE
.sh-script in Openmediavault 

### ISSUE THREAD

**Issue by knilix** [openmediavault/openmediavault#1742]
I would really appreciate it if you could add an app or something similar where I can create my .sh scripts and also manage and execute them straight away. At the moment I take the detour via the terminal, create my scripts there and execute them at the end via "Scheduled tasks". That works quite well. However, it could be a little easier to use.

Incidentally, I have seen this with other NAS software. This function is available there and is added via the community plugin offered.

Translated with DeepL.com (free version)

**Comment by ryecoaaron** [comment]
I have been working on a plugin like this.  I will post more when I have a working plugin.

**Comment by ryecoaaron** [comment]
Testing version available.  See this forum thread - https://forum.openmediavault.org/index.php?thread/52298-openmediavault-scripts-plugin/
