### ISSUE TITLE
OMV7 Fresh install on RPi 5 8GB - default admin user and password not working.

### ISSUE THREAD

**Issue by Coxis** [openmediavault/openmediavault#1749]
**Describe the bug**

I installed OMV7 onto a RPi5 8GB  using the guide here: 

https://wiki.omv-extras.org/doku.php?id=omv6:raspberry_pi_install

Everything went swimmingly until OMV7 finished installing. I opened the GUI, and despite what the guide says, the default username of admin and password of openmediavault are not working. I'm not copy pasting, I'm typing manually and being careful that there aren't any leading or trailing spaces. When I burned the RPI OS Lite 64bit image onto the SD card, the username I added for ssh access was NOT named admin. It was named something completely different... like billy, for example. It wasn't pi either. Does it have to be pi?

I can no longer ssh into the pi using the username "billy" I created during SD card imaging. I assume this is the expected behavior.

I can actually log into the GUI using that same "billy" user I set up during SD card imaging, but I can't do anything, there's only buttons to log out and change language, nothing else. I assume due to lack of privileges.

**To Reproduce**

Follow this guide to install OMV7 on a RPi5 8GB
https://wiki.omv-extras.org/doku.php?id=omv6:raspberry_pi_install
after the script finishes, go into the GUI and admin / openmediavault won't work.

**Expected behavior**A clear and concise description of what the bug is.A clear and concise description of what the bug is.

admin / openmediavault user and password combination should work.

**Screenshots**

![omv7error](https://github.com/openmediavault/openmediavault/assets/19175380/9dcb3efd-9555-45a9-b1d2-d464e075d582)

**Client (please complete the following information):**

Firefox 125.0.2 (64-bit) for Windows 11 and Debian 12.

**Comment by cravas** [comment]
The correct wiki to follow for Pi5/OMV7 is this:
https://wiki.omv-extras.org/doku.php?id=omv7:raspberry_pi_install

Redo the steps, and don't skip.
Take extra care with the preinstall script

**Comment by auron2k** [comment]
Just installed onto a N100 (with openmediavault_7.0-32-amd64.iso), same problem when trying to log into the dashboard with the supposed default password.

Did 'omv-firstaid' to change password and then 'omv upgrade' as in the previous post to get in.

**Comment by ryecoaaron** [comment]
I've installed twice today with that same iso and on an odroid hc4.  didn't have an issue.

**Comment by Coxis** [comment]
It would appear I did use the incorrect guide. After using the supplied one in the second comment install and log in went fine. Thanks.
