### ISSUE TITLE
IsDirty: Exception when executed without parameters

### ISSUE THREAD

**Issue by edgd1er** [openmediavault/openmediavault#1751]
the return of the command: `/usr/sbin/omv-rpc -u admin config isDirty 2>&1| jq` .should return true or false. With omv6 it was ok.

Hereunder is the return since I migrated to OMV7. I have the same error on two separate servers.
``` 
/usr/sbin/omv-rpc -u admin config isDirty 2>&1| jq .
{
"response": null,
"error": {
"code": 0,
"message": ": The value \"null\" is not an object.",
"trace": "OMV\\Json\\SchemaValidationException: : The value \"null\" is not an object. in /usr/share/php/openmediavault/json/schema.inc:395\nStack trace:\n#0 /usr/share/php/openmediavault/json/schema.inc(289): OMV\\Json\\Schema->validateObject()\n#1 /usr/share/php/openmediavault/json/schema.inc(261): OMV\\Json\\Schema->validateType()\n#2 /usr/share/php/openmediavault/rpc/paramsvalidator.inc(59): OMV\\Json\\Schema->validate()\n#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(179): OMV\\Rpc\\ParamsValidator->validate()\n#4 /usr/share/openmediavault/engined/rpc/config.inc(59): OMV\\Rpc\\ServiceAbstract->validateMethodParams()\n#5 [internal function]: Engined\\Rpc\\Config->isDirty()\n#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()\n#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod()\n#8 /usr/sbin/omv-engined(535): OMV\\Rpc\\Rpc::call()\n#9 {main}"
}
}
```

https://github.com/openmediavault/openmediavault/blob/0a326a200927cce1c333ee561537882bee86fc0b/deb/openmediavault/usr/share/openmediavault/engined/rpc/config.inc#L59C3-L59C62

params is validated even if is null or empty: https://github.com/openmediavault/openmediavault/blob/0a326a200927cce1c333ee561537882bee86fc0b/deb/openmediavault/usr/share/php/openmediavault/rpc/serviceabstract.inc#L172

rpc.config.isDisrty model  includes information about params not being required:
https://github.com/openmediavault/openmediavault/blob/0a326a200927cce1c333ee561537882bee86fc0b/deb/openmediavault/usr/share/openmediavault/datamodels/rpc.config.json#L2-L12

as mentionned in [forum](https://forum.openmediavault.org/index.php?thread/52311-omv7-rpc-admin-u-admin-config-isdirty-the-value-null-is-not-an-object/&postID=389400#post389400)  the workaround to use isDirty could be `sudo omv-rpc -u admin config isDirty "{\"modules\":$(</var/lib/openmediavault/dirtymodules.json)}"` or `sudo omv-rpc -u admin config isDirty '{"modules":[]}'`

Would it be possible to use isDirty without supplying $params as previously ?

**Comment by votdev** [comment]
With the PR https://github.com/openmediavault/openmediavault/pull/1757 the RPC can be called via `omv-rpc -u admin config isDirty '{}'`. That's all i can do.
