### ISSUE TITLE
re-creating a logical volume causes error 500

### ISSUE THREAD

**Issue by niko2** [openmediavault/openmediavault#1763]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

A deleted LV keeps file-system information and that prevents to create it again

**To Reproduce**

create a logical volume
create a file-system on this LV
delete file-system
delete LV
re-create the same LV

**Expected behavior**

wipefs should be bone when LV is deleted to allow re-creattion
I have seen the bug and the related commit where you deleted the ability to wipe a file-system
this is not same situation

**Screenshots**

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; lvcreate --name 'minio' --extents 19%VG 'data' 2>&1' with exit code '5': File descriptor 3 (/usr/sbin/omv-engined) leaked on lvcreate invocation. Parent PID 13842: sh
File descriptor 4 (socket:[20233]) leaked on lvcreate invocation. Parent PID 13842: sh
File descriptor 5 (socket:[50499]) leaked on lvcreate invocation. Parent PID 13842: sh
**WARNING: xfs signature detected on /dev/data/minio at offset 0. Wipe it? [y/n]: [n]
  Aborted wiping of xfs.
  1 existing signature left on the device.
  Failed to wipe signatures on logical volume data/minio.
  Aborting. Failed to wipe start of new LV.**

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; lvcreate --name 'minio' --extents 19%VG 'data' 2>&1' with exit code '5': File descriptor 3 (/usr/sbin/omv-engined) leaked on lvcreate invocation. Parent PID 13842: sh
File descriptor 4 (socket:[20233]) leaked on lvcreate invocation. Parent PID 13842: sh
File descriptor 5 (socket:[50499]) leaked on lvcreate invocation. Parent PID 13842: sh
WARNING: xfs signature detected on /dev/data/minio at offset 0. Wipe it? [y/n]: [n]
  Aborted wiping of xfs.
  1 existing signature left on the device.
  Failed to wipe signatures on logical volume data/minio.
  Aborting. Failed to wipe start of new LV. in /usr/share/php/openmediavault/system/process.inc:247
Stack trace:
#0 /usr/share/php/openmediavault/system/storage/storagedevicelvm.inc(283): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/logicalvolumemgmt.inc(692): OMV\System\Storage\StorageDeviceLvm::create()
#2 [internal function]: OMVRpcServiceLogicalVolumeMgmt->createLogicalVolume()
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#5 /usr/sbin/omv-engined(535): OMV\Rpc\Rpc::call()
#6 {main}

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: Linux nas 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
- openmediavault version: 7.0.5-1

**Client (please complete the following information):**

- Device: laptop
- OS: Manjaro Linux
- Browser: Google Chrome
- Version 124.0.6367.118

**Additional context**

**Comment by niko2** [comment]
You don't support deleting a filesystem: got it ! 
But, since deleting a LV is supported, re-creating it must work.
Thus, LV deletion should not be supported as well.
I can't wipe my disks since they are active in a raid device.
Wipping my raid device is not helpful either. Even if I do it manually, there is no effet on the file system header in the previous LV.
So the only solution is to allow lvcreate to wipe te previous filesystem header (what I've done manually using command from the error log), or to prevent user from deleting a LV and then all storage (raid device) must be deleted ?

What is exactly your concern with deleting a filesystem ? I don't see any option to recover a filesystem that was accidentaly deleted. Aim of OMV is to manage storage, right ? Deleting a filesystem is just an operation like creating, growing, etc.

**Comment by votdev** [comment]
> What is exactly your concern with deleting a filesystem ?

Years of experience with users who mistakenly deleted their file system and lost their data as a result. Asking twice via dialog boxes didn't stop them. In addition to the fact that this functionality is only needed very rarely that is why i removed the functionality from the UI. If you still need to delete a file system, you can still do this via the CLI.

**Comment by votdev** [comment]
> Aim of OMV is to manage storage, right ? 

No, the UI is only designed to set it up easily, not to do management.

**Comment by votdev** [comment]
Can you test if `lvcreate --zero y --name 'minio' --extents 19%VG 'data'` will automatically answer the `WARNING: xfs signature detected on /dev/data/minio at offset 0. Wipe it? [y/n]:` question and proceeds with creating the LV?

**Comment by niko2** [comment]
> Can you test if `lvcreate --zero y --name 'minio' --extents 19%VG 'data'` will automatically answer the `WARNING: xfs signature detected on /dev/data/minio at offset 0. Wipe it? [y/n]:` question and proceeds with creating the LV?

I tried different options and the only one that works is
`lvcreate --wipesignatures y --yes --name 'minio' --extents 19%VG 'data'`
I think `--yes` does the trick

by reading manual about `--zero` option, I was not sure i would mount it, but it did it; don't know if it is needed though

**Comment by niko2** [comment]
> > What is exactly your concern with deleting a filesystem ?
> 
> Years of experience with users who mistakenly deleted their file system and lost their data as a result. Asking twice via dialog boxes didn't stop them. In addition to the fact that this functionality is only needed very rarely that is why i removed the functionality from the UI. If you still need to delete a file system, you can still do this via the CLI.

Thank you for your hard work.
I am not so glad what OMV became because of these arguments.
I ran 2.7 for years and I am running 5.1 now, and I was really happy with them.
I plan to go for the last version, so i am testing now.
Hopefully, I have the knowledge to do everything by hand, by I would prefer to use a no brainer UI, for the exact same reason: not doing mistakes because UI asks me if I really want to do it !

thanks again and keep it up !

**Comment by votdev** [comment]
> I think --yes does the trick

Indeed. At the time of writing the comment i was only able to check https://linux.die.net/man/8/lvcreate which does not mention `--yes`.
