### ISSUE TITLE
Imported groups with GID > 65500 do not appear in the GUI

### ISSUE THREAD

**Issue by finestream** [openmediavault/openmediavault#1764]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**
groups with GID > 65500 do not appear in the GUI when imported with the import function
**To Reproduce**
1. Clean install of OMV
2. Go to Users / Group
3. Click on (+)
4. Select import 
5. Type 
` # <groupname>;<gid>;<tags>`
  `low;1050;low`
  `hi;65500;hi`
7. Only low appears in the UI

**Expected behavior**
both low and hi appear in the UI

**Screenshots**

**Reference to Forum**

**openmediavault Server (please complete the following information):**

- OS version: [uname -a] Linux mobi 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
- openmediavault version: [dpkg -l | grep openmediavault]
ii  openmediavault                  7.1.0-1                              all          openmediavault - The open network attached storage solution
ii  openmediavault-apttool          7.0                                  all          apt tool plugin for OpenMediaVault.
ii  openmediavault-backup           7.1.4                                all          backup plugin for OpenMediaVault.
ii  openmediavault-compose          7.2                                  all          OpenMediaVault compose plugin
ii  openmediavault-cputemp          7.0.1                                all          cpu temperature plugin for openmediavault
ii  openmediavault-diskstats        7.0-2                                all          openmediavault disk monitoring plugin
ii  openmediavault-fail2ban         7.0.1                                all          OpenMediaVault Fail2ban plugin
ii  openmediavault-flashmemory      7.0                                  all          folder2ram plugin for openmediavault
ii  openmediavault-keyring          1.0.2-2                              all          GnuPG archive keys of the openmediavault archive
ii  openmediavault-lvm2             7.0-2                                all          openmediavault Logical Volume Manager (LVM2) plugin
ii  openmediavault-md               7.0-7                                all          openmediavault Linux MD (Multiple Device) plugin
ii  openmediavault-mounteditor      7.0.2                                all          openmediavault mount editor plugin
ii  openmediavault-omvextrasorg     7.0                                  all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-remotemount      7.0.1                                all          Remote mount plugin for OpenMediaVault.
ii  openmediavault-sharerootfs      7.0-1                                all          openmediavault share root filesystem plugin

- Device: Mac
- OS: macOS Sonoma
- Browser safari

**Additional context**

the groups are visible in config.xml and users can be added to these groups in the user mask

**Comment by ryecoaaron** [comment]
You need to change UID_MAX and GID_MAX in /etc/login.defs.
