### ISSUE TITLE
SSL-certs - something creates an empty folder named like a openmediavault cert - anacron job "check_ssl_cert_expiry" fails

### ISSUE THREAD

**Issue by FF-Design** [openmediavault/openmediavault#1766]
**Describe the bug**

After my previous SSL-cert expired i created a new one and changed the reference via the webgui. Afterwards i used the webgui as well to delete the older cert.
So far so good I thought. But i remained getting e-mails about anacron errors during the "check_ssl_cert_expiry" because anacron is unable to load the cert.
After some digging i found following thread: [Check ssl cert expiry cronjob fails to load a certificate and stops with an error](https://forum.openmediavault.org/index.php?thread/46413-check-ssl-cert-expiry-cronjob-fails-to-load-a-certificate-and-stops-with-an-erro/)

I can confirm i have the same problem, meaning an empty folder (with cert naming scheme) in the /ssl/certs folder.
I deleted it multiple times but it reappeared every time.

**To Reproduce**

1. Create new SSL-cert via webgui, change reference, delete old cert. (Might not be the only reason for the behaviour but were the steps before it surfaced)
2. After some time the anacron job "check_ssl_cert_expiry" throws errors because its "unable to load cert"
3. The named cert is a folder instead of a real cert
4. After deleting the folder it always reappears. 

**Expected behavior**

Deleting the cert and referecing a newly created one should work without problems. 
There shouldn't be a folder named like a cert that reappears after deleting it.

**Reference to Forum**

https://forum.openmediavault.org/index.php?thread/52656-ssl-certs-something-creates-an-empty-folder-named-like-a-openmediavault-cert-ana/)

**openmediavault Server (please complete the following information):**

- OS version: 6.1.0-0.deb11.17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1~bpo11+1 (2024-01-05) x86_64 GNU/Linux
- openmediavault version: 6.9.15-2  

**Client (please complete the following information):**

N.A.

**Comment by votdev** [comment]
Can not reproduce the issue using the following steps:

1. Create new SSL cert
2. Use SSL cert in `System | Workbench`
3. Apply changes
4. Run 
```
# ls -alh /etc/ssl/certs/openmediavault-*
-rw-r--r-- 1 root root 1.9K May 21 16:17  openmediavault-53e83b9c-09f7-4a0c-8420-87f86b9a692d.crt
```
5. Run `/etc/cron.daily/openmediavault-check_ssl_cert_expiry`
6. Create another new SSL cert
7. Use this SSL cert in `System | Workbench`
8. Apply changes
9. Run 
```
# ls -alh /etc/ssl/certs/openmediavault-*
-rw-r--r-- 1 root root 1.9K May 21 16:17  openmediavault-53e83b9c-09f7-4a0c-8420-87f86b9a692d.crt
-rw-r--r-- 1 root root 1.9K May 21 16:17  openmediavault-95e7eb37-8e85-4e4e-adeb-dfb4c5d5d701.crt
```
10. Run `/etc/cron.daily/openmediavault-check_ssl_cert_expiry`
11. Delete unreferenced SSL cert.
8. Apply changes
9. Run 
```
# ls -alh /etc/ssl/certs/openmediavault-*
-rw-r--r-- 1 root root 1.9K May 21 16:17  openmediavault-95e7eb37-8e85-4e4e-adeb-dfb4c5d5d701.crt
```
10. Run `/etc/cron.daily/openmediavault-check_ssl_cert_expiry`

**Comment by FF-Design** [comment]
Thank you for your testing. 

I did some more testing on my device aswell. 

1. Cd into /etc/ssl/certs 
2. rmdir the folder named "openmedia-{xxx}.crt" 
3. ls and checked that folder is not appearing anymore
4. Rebooted system via the webgui "Reboot"

6. ssh into the device after reboot
7. Using ls again in the /etc/ssl/certs folder. 
8. Folder is there again

Repeated the process again with the same outcome.

Tried to use the "audit" system to figure out what process is creating the folder but am unfamiliar with the correct use. No inside gained up to now.

**Comment by votdev** [comment]
I can not reproduce the issue, even when rebooting the system.

A software unknown to me must be responsible for recreating the SSL certificates on restart or somehow trying to restore them from a cache.

I have now simply adapted the script so that it ignores directories with the search pattern `openmediavault-*.crt`.
