### ISSUE TITLE
Updating PhotoPrism

### ISSUE THREAD

**Issue by Ilovemyhous** [openmediavault/openmediavault#1768]
**Is your feature request related to a problem? Please describe.**
While I was organizing my pictures, I noticed that the OMV **plugin** runs an old version of [PhotoPrism](https://github.com/photoprism/photoprism)
![image](https://github.com/openmediavault/openmediavault/assets/50217071/a7930165-533c-4529-8683-1df00380a4b1)

**Describe the solution you'd like**
While I don't plead to have the latest version on day 1 release, at least trying to keep it up to date would be nice.

**Describe alternatives you've considered**
I could try an run it myself in a Docker container, but I'm honestly inexperienced with Docker, and I'm not sure if I could port my existing settings over, without too much trouble.

**Additional context**
__OMV version__
6.9.16-1 (Shaitan)

__Kernel__
Linux 6.1.0-0.deb11.18-amd64

**Comment by votdev** [comment]
You can use the `OMV_PHOTOPRISM_APP_CONTAINER_IMAGE` [environment variable](https://docs.openmediavault.org/en/stable/various/advset.html#environmental-variables) to configure the version of the container image. It defaults to `docker.io/photoprism/photoprism:latest`.

To upgrade to the latest version, keep the environment variable as it is and simply remove the container and force the pull of the latest image via:
```
podman rmi docker.io/photoprism/photoprism:latest
omv-salt deploy run photoprism
```

**Comment by votdev** [comment]
alternatively install the `openmediavault-podman` plugin, go to the `Images` page, select the PhotoPrism image and press the `Pull` button to download the latest image.

Then run `systemctl restart container-photoprism-app`.

**Comment by nbcjr** [comment]
> alternatively install the `openmediavault-podman` plugin, go to the `Images` page, select the PhotoPrism image and press the `Pull` button to download the latest image.
> 
> Then run `systemctl restart container-photoprism-app`.


i have done this and it asks me to select the tag, all have numbers beginning with 2020, i don't know which is the latest.

**Comment by votdev** [comment]
> > alternatively install the `openmediavault-podman` plugin, go to the `Images` page, select the PhotoPrism image and press the `Pull` button to download the latest image.
> > Then run `systemctl restart container-photoprism-app`.
> 
> i have done this and it asks me to select the tag, all have numbers beginning with 2020, i don't know which is the latest.

You can alternatively enter the tag you want, in this case use `latest`. The dropdown only suggests what the manifest provides.
