### ISSUE TITLE
Web GUI Shared Folders does not create smb.conf entries

### ISSUE THREAD

**Issue by robs-uk** [openmediavault/openmediavault#177]
Hi,

New install of OMV 4.1.11, setup fine so far, but when I create a Shared Folder, no entries turn up in the smb.conf file.

I have tried restarting and using omv-mkconf samba.  I have also tried deleting and recreating shared folders in multiple orders and with different choices of permissions settings on the initial Create dialogue.

It does mount the folders under the /sharedfolders path and correctly applies any ACL changes to the folder structure, so it does all the actual manipulation of the folders, just doesn't add them to Samba.

Output of the Report page attached.  This seems like a really basic function for this software to have broken, so maybe I've missed a step.

Regards,
Rob.

[report.log](https://github.com/openmediavault/openmediavault/files/2434461/report.log)

**Comment by votdev** [comment]
Creating the shared folders is not enough, you need to tell the services (in your case SMB) which shared folders the service should use. So simply go to the SMB service page and configure the shares in the 'Shares' tab.

![auswahl_002](https://user-images.githubusercontent.com/1897962/46299699-35a24180-c5a2-11e8-83a1-55feb9160f45.png)

**Comment by robs-uk** [comment]
Ahh, thank you, thought I was missing something.  I had only added the Shared Folder, I didn't realise I also had to map it to Samba.  Works now.

Thanks,
Rob.
