### ISSUE TITLE
Add OMV_S3_APP_CONTAINER_START_OPTIONS to set MinIO env-var specific settings

### ISSUE THREAD

**Issue by benniekiss** [openmediavault/openmediavault#1782]
**Is your feature request related to a problem? Please describe.**

MinIO only allows setting certain configuration options via environment variables. For instance, `MINIO_BROWSER_REDIRECT_URL` is required in order to access the admin console via a subpath, [and there is no other way to set this other than through an environment variable](https://min.io/docs/minio/linux/reference/minio-server/settings/console.html#browser-redirect-url).

**Describe the solution you'd like**

Add an enviroment variable, `OMV_S3_APP_CONTAINER_START_OPTIONS`, to allow passing additional arguments to the `podman run` command for the S3 app. The Filebrowser app offers `OMV_FILEBROWSER_APP_CONTAINER_START_OPTIONS`, which accomplishes similar functionality.

**Describe alternatives you've considered**

The other option is to manually configure these options through custom state files, or go without them.

**Additional context**

None.

**Comment by votdev** [comment]
The env variable `OMV_S3_APP_CONTAINER_CMD_ARGS` already exists and is used to pass custom options to the container.
I will rename it to `OMV_S3_APP_CONTAINER_START_OPTIONS` so that the variable name schema is the same in all container-based plugins.

**Comment by benniekiss** [comment]
Maybe I'm mistaken, but I believe `OMV_S3_APP_CONTAINER_CMD_ARGS` is used to pass additional arguments to the MinIO `server` command, but there are certain arguments that can't be passed this way; they can only be passed via env_var. I'm requesting the ability to pass additional arguments to `podman run`, in this case, `-e MINIO_BROWSER_REDIRECT_URL`

**Comment by votdev** [comment]
> Maybe I'm mistaken, but I believe `OMV_S3_APP_CONTAINER_CMD_ARGS` is used to pass additional arguments to the MinIO `server` command, but there are certain arguments that can't be passed this way; they can only be passed via env_var. I'm requesting the ability to pass additional arguments to `podman run`, in this case, `-e MINIO_BROWSER_REDIRECT_URL`

You are right. Commit https://github.com/openmediavault/openmediavault/commit/a4e6c1fb1d9f3a21de1f059c0b1d179a760f33eb will fix that.

**Comment by benniekiss** [comment]
Wonderful. Thank you!
