### ISSUE TITLE
Protect OMV against SW supply chain attacks

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1788]
**Is your feature request related to a problem? Please describe.**
OMV is a very attractive solution for private file sharing with growing user base, hence becoming attractive for potential malicious attacks too.
 SW supply chain attacks are now a common attack vector (i.e: [Polyfill.io serving malware for months via its CDN](https://socket.dev/blog/namecheap-takes-down-polyfill-io-service-following-supply-chain-attack) and  [npm malware](https://x.com/npm_malware))

**Describe the solution you'd like**
I'd suggest to integrate a tool to protect against supply chain attacks in development workflow.

**Describe alternatives you've considered**
A potential tool could be [Socket](https://socket.dev) as it offers a free plan for OSS.
There might be other better alternatives too, my intent is just to raise awareness

**Comment by votdev** [comment]
GitHub already provides Dependabot for NPM packages used in the UI. OMV does not use Python PIP nor PHP Composer to import external Python or PHP packages, so it does not make sense to use [Socket](https://docs.socket.dev/docs/language-support) because there is simply nothing that this service can check.

**Comment by mi-hol** [comment]
in a recent blog pot from GitHub it was mentioned "June 25, 2024
Dependabot version updates requires developers to configure and check in a dependabot.yml file. In the past, it was challenging for administrators to **configure a dependabot.yml** that works for all repositories without per-repo customization. With this change, you can now specify multiple directories of dependency manifests using the directories key."

But I didn't see this config file in repo
![image](https://github.com/openmediavault/openmediavault/assets/22799428/1540cf54-5f1f-4857-a3d1-5d6602f6f5d3)

**Comment by votdev** [comment]
According to https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide the `.github/dependabot.yml` is optional. OMV does not want to [update the packages automatically](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) by Dependabot, so this file seems not to be required.

**Comment by mi-hol** [comment]
ok, so lets close
