### ISSUE TITLE
File system displays incorrect size of free memory

### ISSUE THREAD

**Issue by HeikoS1979** [openmediavault/openmediavault#1791]
I am a beginner with OMV and have little experience. Maybe I have done things wrong.
I would like to make a Raid 1 with BTRFS file system.

This is how I proceeded:
- I go to my drives
- I delete both drives /dev/sda and dev/sdb
- I go to the menu item File systems and create a new file system with BTRFS and Raid 1.
- I am not using Linux MD
- After creating the file system, however, I am shown 14.55 TiB of memory. This is wrong for a Raid 1, it should only be 7.28 TiB. It is also not a display problem of the browser. Several browsers have been tested and the browser cache has also been cleared.

My system:
Hard disc type: TOSHIBA MG08ADA800E
Size: 7,28 TiB

OMV Version: 7.3.0-5
Linux 6.1.0-22
Processor: Intel N100

Can anyone help me with this? Is this a bug or have I done something wrong?

![HDDs](https://github.com/openmediavault/openmediavault/assets/174409326/887ba752-c76e-425f-9d7d-3bc09901e1ec)
![Filesystem_BTRFS_Info](https://github.com/openmediavault/openmediavault/assets/174409326/6f398eeb-21cf-44d8-9545-2bd2614c7c94)
![Filesystem_BTRFS](https://github.com/openmediavault/openmediavault/assets/174409326/7e652eda-5ca8-4f0b-89b9-b1923e53fea1)

**Comment by ryecoaaron** [comment]
From what I have seen on the forum, this is an issue with a new btrfs filesystem and the btrfs tools reporting the freespace. The tools "fix" themselves when you write to filesystem the first time.

**Comment by votdev** [comment]
Oh right, i remember such situation and a forum post where this was discussed. 

@HeikoS1979 Please report back if we can close the issue.

**Comment by HeikoS1979** [comment]
He's right. When I make a share and save data on it, the display repaired themself.
I have another question. Is the problem because of the BTRFS-Progs or on the Linux Kernel?
You can close the issue. Thanks for the fast help.

**Comment by votdev** [comment]
> Is the problem because of the BTRFS-Progs or on the Linux Kernel?

I'm sorry, i have no answer for that.
