### ISSUE TITLE
OMV7 Makes problems with latest HW / Please Update Kernel!

### ISSUE THREAD

**Issue by crazybanane** [openmediavault/openmediavault#1794]
**Describe the bug**

I got latest HW that is not fully supported by OMV7 and the installed Kernel-Version. Caused Problems with Network.

My System is based on:
Mobo. Gigabyte B650I AX (ITX)
CPU. AMD Ryzen 5 8600G
DDR 5 32GB Ram
some HDDs

With the original Kernel i don`t get any Connection, not with LAN or WIFI because drivers are not availlable. With manual try to install Drivers the Hardware can sometimes be found (only LAN) but didnt get Activated caused of Kernel. If i Install Xanmod Kernel every driver work and Network function are availlable LAN/WIFI. But i cant install not every ADD-On failure free. (tried package openmediavault-zfs) failure Kernel to new. (supported only up to Build 6.2)

**openmediavault Server (please complete the following information):**

- OS version: Debian latest V12
- openmediavault version: openmediavault 7.3.1-1

**Comment by votdev** [comment]
The OMV project does not maintain the kernel packages itself, it fully relies on the Debian project or the projects that are derived of it (ARM releated platforms). Therefore the OMV project can not do anything here.
