### ISSUE TITLE
SMART on HP MicroGen8 with P222 Controller

### ISSUE THREAD

**Issue by pentroxx** [openmediavault/openmediavault#1795]
I run OMV7 on HP Micro Gen8 with 2 HDD in Raid1 + 1SSD + 1HDD. 

SMART does not work.
smartctl wants the -d cciss,N option. 
If do in command line, works fine but will be great to see in OMV. Read la lot about it, but can't find a solution. 

Is it possible to solve the problem?

**Comment by votdev** [comment]
OMV requires that smartmontools auto-detects the hardware. There are several ways to achive that, e.g. by adding a local database entry. Check the following links:

- https://github.com/openmediavault/openmediavault/issues/1619#issuecomment-1788959178
- https://docs.openmediavault.org/en/stable/faq.html
- https://forum.openmediavault.org/index.php?thread/50161-after-update-from-6-9-6-1-to-2-smart-stopped-working-w-error/
- https://forum.openmediavault.org/index.php?thread/51543-smart-statuses-are-not-working-on-omv7-debian-12-raspi4/&postID=382936#post382936

For several controller cards OMV has added hard-coded solutions. To implement that i need several information. Please check the following links of other controllers that are supported by OMV to get an idea what you need to deliver to support your hardware:

- https://github.com/openmediavault/openmediavault/issues/535
- https://github.com/openmediavault/openmediavault/issues/959

**Comment by votdev** [comment]
> I run OMV7 on HP Micro Gen8 with 2 HDD in Raid1 + 1SSD + 1HDD.

OMV does not support SMART monitoring of such constellations because in that case the devices are hidden behind the RAID device file. You can only run that controller in pass-through mode where every device is visible to the kernel (and OMV) via individual device files.

If you need a RAID, then use the openmediavault-md plugin to use mdadm software RAID or use a Btrfs RAID.

**Comment by votdev** [comment]
I am closing this issue because RAID support of hardware controllers is NOT supported and will not be supported in future.
