### ISSUE TITLE
openmediavault-update-smart-drivedb is executed weekly with bash -l

### ISSUE THREAD

**Issue by gromeck** [openmediavault/openmediavault#1799]
`/etc/cron.weekly/openmediavault-update-smart-drivedb` is the only cronjob script which uses `#!/usr/bin/bash -l` for its execution.
As the `-l` is used, the output of the script always contains messages which normally only login-shells would see (e.g. a dynamic greeting).
The effect is that the weekly execution of `openmediavault-update-smart-drivedb` will always send a mail.

**To Reproduce**

1. login to omv instance as root via ssh
2. execute
     `echo -e '#!/bin/bash\necho *** Welcome to $( hostname --short ) ***' >/etc/profile.d/welcome.sh`
4. re-login to omv instance as root via ssh
5. observe that the welcome message ("`*** Welcome to ... ***`") appears
6. wait until saturday morning
7. check your mailbox
8. observe that a mail with the welcome message was received

**Expected behavior**

No mail should be received.

**Screenshots**

n/a

**Reference to Forum**

n/a

**openmediavault Server:**

- OS version: Linux omv 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux
- openmediavault version: 7.4.3-1

**Client:**

n/a

**Additional context**

n/a

**Proposed Fix**

Please change the first line in `/etc/cron.weekly/openmediavault-update-smart-drivedb` from

    #!/usr/bin/bash -l

to

    #!/usr/bin/env dash

as it is done in all the other openmediavault cron scripts.

Thanks a lot for openmediavault,
gromeck

**Comment by votdev** [comment]
This was intentionally done by https://github.com/openmediavault/openmediavault/commit/617ff78654a790feff3c03fd114dc0403c930ba4. 

Can you confirm that it works with a `#!/usr/bin/env dash` shebang?

**Comment by gromeck** [comment]
Hmm, understood. Quite ugly that this is only the case for `openmediavault-update-smart-drivedb`.

I made the proposed change on my system (`#!/usr/bin/env dash` shebang) and moved the cron job testwise from weekly to hourly as I didn't wan't to wait until next saturday ;-)  I can see it's execution in the syslog, with no mail generated -- as expected.

To test the proxy stuff, I configured also a proxy host in openmediavault and added an `export` command to the cronjob script. The cron mail shows hat the environment has `http_proxy` only set, if the shebang uses the `-l` option.

But I think, that the use case here is not a login-shell and the handling of proxy settings should be handled therefore via `/etc/default/openmediavault` or `/usr/share/openmediavault/scripts/helper-functions`. But this might lead to a design or even an philosophical descussion ;-)

**Comment by votdev** [comment]
> But I think, that the use case here is not a login-shell and the handling of proxy settings should be handled therefore via /etc/default/openmediavault or /usr/share/openmediavault/scripts/helper-functions. But this might lead to a design or even an philosophical descussion ;-)

I don't think this is the correct approach. The handling of the proxy settings has to be done by the shell or the script by sourcing the `/etc/profile`.

**Comment by gromeck** [comment]
> closed this as [completed](https://github.com/openmediavault/openmediavault/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/openmediavault/openmediavault/pull/1800

The change in #1800 does not fix my initial problem _"output of the script always contains messages which normally only login-shells would see (e.g. a dynamic greeting)"_ as `/etc/profile` will still be called for the necessary environment (e.g. proxy settings).
To fix the initial problem, I ensured that my `/etc/profile.d/*` scripts will only output to stdout if the executing shell is an interactive shell (see `$-` in bash man page).

Anyway, thanks a lot!

**Comment by votdev** [comment]
> > closed this as [completed](https://github.com/openmediavault/openmediavault/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in #1800
> 
> The change in #1800 does not fix my initial problem _"output of the script always contains messages which normally only login-shells would see (e.g. a dynamic greeting)"_ as `/etc/profile` will still be called for the necessary environment (e.g. proxy settings). To fix the initial problem, I ensured that my `/etc/profile.d/*` scripts will only output to stdout if the executing shell is an interactive shell (see `$-` in bash man page).
> 
> Anyway, thanks a lot!

This might be a solution as well, but `. /etc/profile 1>/dev/null` will prevent all output to stdout.

**Comment by gromeck** [comment]
Ah, sorry, didn't realize the `/dev/null` -- yes, this fixes #1799 -- thanks again.
