### ISSUE TITLE
Send "X package update(s)" email only if packages changed

### ISSUE THREAD

**Issue by wnhrt** [openmediavault/openmediavault#1809]
**Is your feature request related to a problem? Please describe.**
Notification emails are sent daily if packages are not updated (subject: `X package update(s) available`), even if no new packages need to be updated compared to yesterday. This can clutter the mailbox without value and be numbing to this kind of email.

**Describe the solution you'd like**
OMV should check whether the packages to be updated have changed compared to the previous day. If not, the notification email should not be sent.

**Describe alternatives you've considered**
Automatic deletion of this email/marking it as read, which would be counterproductive.

**Additional context**
//

**Comment by votdev** [comment]
> Notification emails are sent daily if packages are not updated (subject: X package update(s) available), even if no new packages need to be updated compared to yesterday.

In this case, however, the reminder email is correct. the packages shown in the previous email have not yet been updated. It therefore makes sense to list them again in the email.

> OMV should check whether the packages to be updated have changed compared to the previous day.

Why? If the packages listed in the last email have not yet been installed and are then no longer listed in the current email, important information will be suppressed and lost.

**Comment by wnhrt** [comment]
To clarify, I only address the case where yesterdays email contains packages A and todays email also only contains packages A. In this case the email is redundant. If yesterday packages A needed updates and today packages A and B need updates the todays emails should contain A and B.

See following example emails. The only difference is the date at the top, so the email from Tuesday is noise.

```
apticron report [Mon, 15 Jul 2024 15:51:54 +0200]
========================================================================

apticron has detected that some packages need upgrading on:

	OMV_HOSTNAME 
	[ ... ]

The following packages are currently pending an upgrade:

	openmediavault 7.4.0-2

========================================================================

Package Details:

... [omitted] ...

========================================================================

You can perform the upgrade by issuing the command:

	apt-get dist-upgrade

as root on OMV_HOSTNAME

--
apticron
```

and


```
apticron report [Tue, 16 Jul 2024 15:51:56 +0200]
========================================================================

apticron has detected that some packages need upgrading on:

	OMV_HOSTNAME 
	[ ... ]

The following packages are currently pending an upgrade:

	openmediavault 7.4.0-2

========================================================================

Package Details:

... [omitted] ...

========================================================================

You can perform the upgrade by issuing the command:

	apt-get dist-upgrade

as root on OMV_HOSTNAME

--
apticron
```

---

> I there a strong reason to do so?

Objectively regular package updates are not critical and don't need immediate action. Because of that I believe daily notifications with the exact same information are unnecessary.

My email workflow is to keep unfinished matters inside my inbox and move/delete them after they are done, so I do not need a reminder.

---

I looked into apticrons configuration and `DIFF_ONLY="0"` should  give the result I imagine. I'll give it a try.

```
#
# Set DIFF_ONLY to "1" to only output the difference of the current run
# compared to the last run (ie. only new upgrades since the last run). If there
# are no differences, no output/email will be generated. By default, apticron
# will output everything that needs to be upgraded.
#
# DIFF_ONLY="1"
#
```

**Comment by votdev** [comment]
> Objectively regular package updates are not critical and don't need immediate action. Because of that I believe daily notifications with the exact same information are unnecessary.

That is your view of things, but not that of the openmediavault project.

The notification about the packages to be updated should not be based on knowledge that is distributed over several emails, as this may result in information being lost.

Your workflow does not match that of the project. Unfortunately, there is also no way to modify the apticron configuration file via OMV environment variables, so that manual modifications to the file are overwritten with each update.

**Comment by votdev** [comment]
With `openmediavault 7.4.5` it will be possible to customize the apticron configuration via [environment variables](https://docs.openmediavault.org/en/stable/various/advset.html#environmental-variables).

**Comment by wnhrt** [comment]
> The notification about the packages to be updated should not be based on knowledge that is distributed over several emails, as this may result in information being lost.

Understandable, I see why `DIFF_ONLY="1"` would not work for OMV.

> With openmediavault 7.4.5 it will be possible to customize the apticron configuration via [environment variables](https://docs.openmediavault.org/en/stable/various/advset.html#environmental-variables).

Thank you for this quick update, it is very helpful for me.
