### ISSUE TITLE
ClamAV Status site

### ISSUE THREAD

**Issue by crazybanane** [openmediavault/openmediavault#1811]
**Is your feature request related to a problem? Please describe.**
Hello, I look always for a function like what ClamAV does or on what Version it is how old the Antivirus Database is and an other live view out off the automatic opening Terminal so that i can work and ClamAV can work in the background without opening a new TAB in the Browser. Even i wish there is something like a Percentage state. 

**Describe the solution you'd like**
A Status site in ClamAV where the most interresting things showing up. And some Buttons like Start Scan, Update, Stop Service Start Service so that i dont have to switch to other Panels

**Describe alternatives you've considered**

**Additional context**

Thanks

**Comment by votdev** [comment]
> an other live view out off the automatic opening Terminal so that i can work and ClamAV can work in the background without opening a new TAB in the Browser.

I'm sorry, that is not possible because the "modal" dialog behaviour is by design and with reason.

**Comment by votdev** [comment]
> And some Buttons like ..., Stop Service, Start Service so that i dont have to switch to other Panels

Starting and stopping services with one-click is not implemented by design because there are more things done in the background than calling `systemd stop|start xxxx` for example.

**Comment by crazybanane** [comment]
Hi my english is not the best i tried to Paint what i meant.
![clamav 1](https://github.com/user-attachments/assets/d7dc7746-c846-4666-b86a-804fb3c6ad5a)
![clamav2](https://github.com/user-attachments/assets/9d1383a3-8719-4dd7-86bf-824144abe87a)
