### ISSUE TITLE
** Connection Lost *

### ISSUE THREAD

**Issue by RaBe1310** [openmediavault/openmediavault#1820]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; docker compose --file '/srv/dev-disk-by-uuid-6bed1646-09bb-44fb-9568-6b1d817e00c5/Docker/adguard/adguard.yml' --env-file '/srv/dev-disk-by-uuid-6bed1646-09bb-44fb-9568-6b1d817e00c5/Docker/adguard/adguard.env' --env-file '/srv/dev-disk-by-uuid-6bed1646-09bb-44fb-9568-6b1d817e00c5/Docker/global.env' up -d 2>&1': network MyMacVlan declared as external, but could not be found

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; docker compose --file '/srv/dev-disk-by-uuid-6bed1646-09bb-44fb-9568-6b1d817e00c5/Docker/adguard/adguard.yml' --env-file '/srv/dev-disk-by-uuid-6bed1646-09bb-44fb-9568-6b1d817e00c5/Docker/adguard/adguard.env' --env-file '/srv/dev-disk-by-uuid-6bed1646-09bb-44fb-9568-6b1d817e00c5/Docker/global.env' up -d 2>&1': network MyMacVlan declared as external, but could not be found in /usr/share/openmediavault/engined/rpc/compose.inc:805
Stack trace:
#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(622): OMVRpcServiceCompose->{closure}()
#1 /usr/share/openmediavault/engined/rpc/compose.inc(780): OMV\Rpc\ServiceAbstract->execBgProc()
#2 [internal function]: OMVRpcServiceCompose->doCommand()
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#5 /usr/sbin/omv-engined(544): OMV\Rpc\Rpc::call()
#6 {main}

**To Reproduce**

**Expected behavior**

** Connection Lost **
**Screenshots**
![grafik](https://github.com/user-attachments/assets/6ae2c83f-1db6-4ede-9d09-fd0411b0dd5f)
![grafik](https://github.com/user-attachments/assets/8d94789f-1e9c-4e79-a50e-e5b9682be912)

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: [uname -a] 7.4.5-1 (Sandworm) Linux 6.1.0-23-amd64
- openmediavault version: [dpkg -l | grep openmediavault]

**Client (please complete the following information):**

**Additional context**

always ** Connection Lost **
ons after new install and by the end of update 
this on after install docker by install adblock by compose bring it up

**Comment by votdev** [comment]
The error is `network MyMacVlan declared as external, but could not be found` which causes the command to fail and therefor the UI displays connection lost because there is no data to display anymore.

Please raise the question in the forum how to fix your `Docker compose` problem.

As mentioned in the GH issue template, this tracker is for the core system only. Plugins like Docker compose have to be raised in their corresponding GH trackers, e.g. [here](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen).
