### ISSUE TITLE
OMV 7 doesn't support Xen predictive network interface naming (enX0)

### ISSUE THREAD

**Issue by klou** [openmediavault/openmediavault#1825]
After an in-place upgrade from OMV6->OMV7 on a Xen VM, the GUI shows the previous ```eth0``` but without any data.  The interface can be deleted, but the renamed interface ```enX0``` is not detected.  Network functionality is unaffected, but management from within OMV is not possible.

Bookworm upgraded to ```systemd``` v252, and v250+ added support for Xen naming with predictive network interfaces:
```
 * The predictable naming logic for network interfaces has been extended
      to generate stable names from Xen netfront device information.
```
As a result, Bookworm renamed Xen interfaces from ```eth0``` to ```enX0```.

https://github.com/openmediavault/openmediavault/blob/8da2da7c3983874e998e43a5e35515b3000adc6a/deb/openmediavault/usr/share/php/openmediavault/system/net/networkinterfacebackend/ethernet.inc#L59-L65 references v242 as the source for interface support. 

It'd be nice to have this updated for OMV7.

**Comment by votdev** [comment]
Additional references:
- https://bugs.debian.org/1032268
- https://www.freedesktop.org/software/systemd/man/latest/systemd.net-naming-scheme.html

**Comment by klou** [comment]
Thanks!  I can now add an ```enX0``` interface, and it'll show (with the current IP) on the Dashboard.

Though -- this is odd, but it's a one-time oddity that probably doesn't need further work -- the previously-configured ```eth0``` does NOT show on the Dashboard, even though I have not yet deleted it.  I don't recall if it showed before.  But simple enough to delete it as part of the cleanup.
