### ISSUE TITLE
Backports-Problem

### ISSUE THREAD

**Issue by uwenr5** [openmediavault/openmediavault#1826]
Hallo,
auf mein neues Nas (x86) hab ich omv 7.4.7-1 aufgespielt. anscheinend habe ich beim einrichten in omv-extras wohl "enable backport" eingeschaltet. bei apt update bekomme ich folgende meldung:
 `Holen:1 file:/var/cache/openmediavault/archives  InRelease
Ign:1 file:/var/cache/openmediavault/archives  InRelease
Holen:2 file:/var/cache/openmediavault/archives  Release
Ign:2 file:/var/cache/openmediavault/archives  Release
Holen:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Holen:4 file:/var/cache/openmediavault/archives  Translation-de
Ign:4 file:/var/cache/openmediavault/archives  Translation-de         
Holen:5 file:/var/cache/openmediavault/archives  Translation-en       
Ign:5 file:/var/cache/openmediavault/archives  Translation-en
Holen:6 file:/var/cache/openmediavault/archives  Translation-de_DE                       
Ign:6 file:/var/cache/openmediavault/archives  Translation-de_DE                         
Holen:3 file:/var/cache/openmediavault/archives  Packages                                                                                            
Ign:3 file:/var/cache/openmediavault/archives  Packages                                                                                              
Holen:4 file:/var/cache/openmediavault/archives  Translation-de                                                                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-de                                                                                         
Holen:5 file:/var/cache/openmediavault/archives  Translation-en                                                                                       
Ign:5 file:/var/cache/openmediavault/archives  Translation-en                                                                                         
Holen:6 file:/var/cache/openmediavault/archives  Translation-de_DE                                                                                    
Ign:6 file:/var/cache/openmediavault/archives  Translation-de_DE                                                                                      
Holen:3 file:/var/cache/openmediavault/archives  Packages                                                                                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                                                                                               
Holen:4 file:/var/cache/openmediavault/archives  Translation-de                                                                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-de                                                                                         
Holen:5 file:/var/cache/openmediavault/archives  Translation-en                                                                                       
Ign:5 file:/var/cache/openmediavault/archives  Translation-en                                                                                         
Holen:6 file:/var/cache/openmediavault/archives  Translation-de_DE                                                                                    
Ign:6 file:/var/cache/openmediavault/archives  Translation-de_DE                                                                                      
Holen:3 file:/var/cache/openmediavault/archives  Packages                                                                                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                                                                                               
Holen:4 file:/var/cache/openmediavault/archives  Translation-de                                                                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-de                                                                                         
Holen:5 file:/var/cache/openmediavault/archives  Translation-en                                                                                       
Ign:5 file:/var/cache/openmediavault/archives  Translation-en                                                                                         
Holen:6 file:/var/cache/openmediavault/archives  Translation-de_DE                                                                                    
Ign:6 file:/var/cache/openmediavault/archives  Translation-de_DE                                                                                      
Holen:3 file:/var/cache/openmediavault/archives  Packages                                                                                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                                                                                               
Holen:4 file:/var/cache/openmediavault/archives  Translation-de                                                                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-de                                                                                         
Holen:5 file:/var/cache/openmediavault/archives  Translation-en                                                                                       
Ign:5 file:/var/cache/openmediavault/archives  Translation-en                                                                                         
Holen:6 file:/var/cache/openmediavault/archives  Translation-de_DE                                                                                    
Ign:6 file:/var/cache/openmediavault/archives  Translation-de_DE                                                                                      
Holen:3 file:/var/cache/openmediavault/archives  Packages                                                                                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                                                                                               
Holen:4 file:/var/cache/openmediavault/archives  Translation-de                                                                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-de                                                                                         
Holen:5 file:/var/cache/openmediavault/archives  Translation-en                                                                                       
Ign:5 file:/var/cache/openmediavault/archives  Translation-en                                                                                         
Holen:6 file:/var/cache/openmediavault/archives  Translation-de_DE                                                                                    
Ign:6 file:/var/cache/openmediavault/archives  Translation-de_DE                                                                                      
Holen:3 file:/var/cache/openmediavault/archives  Packages                                                                                             
Holen:4 file:/var/cache/openmediavault/archives  Translation-de                                                                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-de                                                                                         
Holen:5 file:/var/cache/openmediavault/archives  Translation-en                                                                                       
Ign:5 file:/var/cache/openmediavault/archives  Translation-en                                                                                         
Holen:6 file:/var/cache/openmediavault/archives  Translation-de_DE                                                                                    
Ign:6 file:/var/cache/openmediavault/archives  Translation-de_DE                                                                                      
OK:7 http://packages.openmediavault.org/public sandworm InRelease                                                                                     
OK:8 http://deb.debian.org/debian bookworm InRelease                                                                                                  
OK:9 http://deb.debian.org/debian bookworm-updates InRelease                                                                                          
OK:10 http://security.debian.org/debian-security bookworm-security InRelease                                                                          
OK:11 https://openmediavault-plugin-developers.github.io/packages/debian sandworm InRelease                                                           
OK:12 https://openmediavault.github.io/packages sandworm InRelease                                                                                    
Holen:13 https://deb.debian.org/debian bookworm-backports InRelease [59,0 kB]                                                                         
OK:14 https://download.docker.com/linux/debian bookworm InRelease                                    
OK:15 https://deb.nodesource.com/node_20.x nodistro InRelease
Holen:16 http://deb.debian.org/debian bookworm/main Translation-de [1.748 kB]
Holen:17 http://deb.debian.org/debian bookworm/main Translation-de_DE [830 B]
Fehl:13 https://deb.debian.org/debian bookworm-backports InRelease      
  Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Paketlisten werden gelesen… Fertig
W: GPG-Fehler: https://deb.debian.org/debian bookworm-backports InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: Das Depot »https://deb.debian.org/debian bookworm-backports InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
`
auch wenn ich backports wieder ausschalte in omv-extras erhalte ich diese meldung weiter. 
meine sources.list:
`deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware

  bookworm-updates, to get updates before a point release is made;
  see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_updates_and_backports
deb http://deb.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware

  This system was installed using small removable media
  (e.g. netinst, live or single CD). The matching "deb cdrom"
  entries were disabled at the end of the installation process.
  For information about how to configure apt package sources,
  see the sources.list(5) manual.
`
durch den fehler mit backports und dem schlüssel bekomme ich auch keine updates hin. bin schon stunden am suchen und finde keine antwort (oder bin mir nicht sicher was da gemacht wird). 
kann mir jemand helfen?
danke
was wird noch gebraucht?

**Comment by votdev** [comment]
Es sieht so aus als ob die entsprechenden SSL Zertifikate nicht im System vorhanden sind. Einfach mal die Zeilen löschen und die Backports in der UI deaktivieren.

Ansonsten bitte solche Probleme immer erst im Forum ansprechen, dort sind viel mehr User die Dir bei Deinem Problem helfen können. Das GH Issue Template spricht das auch explizit an.

Der Issue wird geschlossen da es sich um keinen Bug handelt.
