### ISSUE TITLE
Please don't redirect for errors, I always have to remove 503 etc from url to reload a rebooting server

### ISSUE THREAD

**Issue by knowncolor** [openmediavault/openmediavault#1827]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by votdev** [comment]
I can not reproduce that. The browser is redirected to the previous page.

[Bildschirmaufzeichnung vom 2024-09-29 10-26-46.webm](https://github.com/user-attachments/assets/ec5e7c2f-1a03-45f9-8976-b4f21980c0ac)
