### ISSUE TITLE
After installing it works perfectly fine but then after a reboot it stops working idk hu

### ISSUE THREAD

**Issue by Rahul120934** [openmediavault/openmediavault#1834]
**Describe the bug**  
I was setting up OpenMediaVault (OMV) on my Raspberry Pi and encountered the following error messages:  
- `Failed to stop ntp.service: Unit ntp.service not loaded.`  
- `Unit ntp.service does not exist, proceeding anyway.`  
- `Created symlink /etc/systemd/system/ntp.service → /dev/null.`  
- `Failed to stop systemd-timesyncd.service: Unit systemd-timesyncd.service not loaded.`

**To Reproduce**  
1. Start the setup process for OMV on Raspberry Pi.  
2. During the configuration, services related to time synchronization failed with the mentioned errors.

**Expected behavior**  
I expected the NTP service to load or be managed without generating error messages.

**openmediavault Server (please complete the following information):**  
- OS version: Raspberry Pi OS Lite (64-bit)  
- openmediavault version: Latest version available

**Client (please complete the following information):**  
- Device: Raspberry Pi 5 (8GB RAM)  
- OS: Raspberry Pi OS Lite  
- Browser: Not applicable (using terminal setup)

**Additional context**  
Immediately after the installation and first reboot, the system works fine. However, after a second reboot, it stops connecting to the internet, even with a hardwired Ethernet connection. Let me know if you need more information about my hardware or setup

**Comment by ryecoaaron** [comment]
OMV uses chrony which is why it is trying to disable ntp.  This is not a problem.

Did you follow the RPi guide?  https://wiki.omv-extras.org/doku.php?id=omv7:raspberry_pi_install

**Comment by votdev** [comment]
These are messages that are thrown when openmediavault tries to disable NTP during the package installation. These can be ignored.

The network problem is not related to this issue.
