### ISSUE TITLE
OMV on ZFS needs urbackupsrv run as root

### ISSUE THREAD

**Issue by chymian** [openmediavault/openmediavault#184]
Using OMV on ZFS needs urbackupsrv run as root hence `/etc/default/urbackup` with Parameter `USER=root`.

manual adding `USER=root` to `/etc/default/urbackup` gets rewritten on OMV's save config.

Addition 1:
from the urbacksrv-manual:
> In order to create and remove ZFS snapshots UrBackup installs a setuid executable urbackup_ snapshot_helper. However, currently ZFSOnLinux calls mount in turn which will fail when urbackup_ snapshot_helper is run as non-priviledged user. So you must run UrBackup server as root user (urbackupsrv run -u root). You should create a separate ZFS dataset in which the image backups will be stored e.g. tank/images. UrBackup server will read this dataset from /etc/urbackup/dataset and the backup storage path from /etc/urbackup/backupfolder. Setup by e.g.

**Comment by ryecoaaron** [comment]
This should be filed here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-urbackup-server/issues
