### ISSUE TITLE
Web Login fails if root drive is 100% capacity

### ISSUE THREAD

**Issue by PirateIncognito** [openmediavault/openmediavault#1840]
[A clear and concise description of what the bug is.]

Web Login fails if root drive is 100% capacity.

There are no errors/warnings or UI feedback to indicate the problem. The screen appears to just reload (like a failed login attempt but with no message).

**To Reproduce**
Fill a disk to 100% using dd or some other method.

Attempt login - the screen flickers and the login prompt reloads. This is confusing to the user

**Expected behavior**

Web UI should login or present warning about disk being full indicating the problem to the user.

**openmediavault Server (please complete the following information):**

- OS version: Linux omv 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux
- openmediavault version: [dpkg -l | grep openmediavault]
ii  openmediavault                  7.4.10-1                             all          openmediavault - The open network attached storage solution
ii  openmediavault-compose          7.2.14                               all          OpenMediaVault compose plugin
ii  openmediavault-keyring          1.0.2-2                              all          GnuPG archive keys of the openmediavault archive
ii  openmediavault-omvextrasorg     7.0                                  all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-sharerootfs      7.0-1                                all          openmediavault share root filesystem plugin

**Client (please complete the following information):**

- Device: PC
- OS: Windows 10
- Browser Chrome
- Version Version 130.0.6723.69 (Official Build) (64-bit)

**Additional context**

I spent 30 minutes googling this problem and trouble shooting why I couldn't login. I reboot, reset cache, reset master password, I found a random reddit post that helped me (there are many results for "openmediavault login not working")

I feel like for OMV to be polished software this kind problem should notify the user. Since it is a known condition, it's not beyond a measure of control.

**Comment by votdev** [comment]
Disk space warnings are sent via email. Additionally there is a disk usage graph in the filesystem page and finally a dashboard widget.
IMO there are already a plenty of solutions that might notify the attentive administrator.

**Comment by PirateIncognito** [comment]
`Additionally there is a disk usage graph in the filesystem page and finally a dashboard widget.`

None of those can be accessed if you can't login...Do you understand what I'm saying? web UI login FAILS when the disk is full.

**Comment by ryecoaaron** [comment]
Yes, he understands. His point was that if you are watching those graphs and/or reading the warning emails on a regular basis, you would see the filesystem growing and know to fix the system before the filesystem fills.  This is the way we do it in the enterprise. The problem with doing other things is that they also fail when the root filesystem is full.  If you can’t login via the web interface, you can still ssh into the system as root.
