### ISSUE TITLE
SMART data "Read Device Identity failed" on eSATA drive

### ISSUE THREAD

**Issue by neeqkowlah** [openmediavault/openmediavault#1844]
Hello,

With OMV 6.x, when I activate SMART to one of my disk, a 4Tb seagate expansion, which is in a rack plugged with eSata cable. I have in the GUI the Status "unknown" while I have a good status for the others disk in the same eSata rack.

When i check the "extended informations" for this disk, i can see the following message

```
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-6.1.0-0.deb11.21-amd64] (local build)

Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org
Read Device Identity failed: scsi error unsupported field in scsi command
A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.

```

I found on the web that smartmontoolsi should work if I add the option -d
[Supported_USB-Devices – smartmontools](https://www.smartmontools.org/wiki/Supported_USB-Devices)

but I don't know how to add this option because the GUI does not propose it ?

thank you very much

**Comment by votdev** [comment]
You need to add a custom smartmontools device database to teach the tools how to handle your hardware.

Please check the following links:
- https://www.smartmontools.org/wiki/FAQ#Couldmissingdrivedatabaseentriesbeaddedlocally
- https://www.smartmontools.org/wiki/FAQ#SmartmontoolsDatabase
- https://raw.githubusercontent.com/mirror/smartmontools/master/drivedb.h
- https://docs.openmediavault.org/en/stable/faq.html
- https://forum.openmediavault.org/index.php?thread/53058-upgrade-to-7-3-0-1-breaks-storage-disks-display/&postID=394149#post394149
