### ISSUE TITLE
error when try to add apt sources at update management -> other software

### ISSUE THREAD

**Issue by mckaygerhard** [openmediavault/openmediavault#1849]
**Describe the bug**

I try to add another sources.list source software for apt, at update management -> other software and gives me error log its at last of this report

**To Reproduce**

1. Go to system -> update management -> other software
2. Click on create button
3. add the respectives entries
4. See error in log section of this bug 

**Screenshots**

![image](https://github.com/user-attachments/assets/43e38f77-ebf6-4e88-a44c-ad130de13e46)

**Reference to Forum**

This link is outdated info.. it seems related but not applied cos i dont see any jobs there for any apt

https://forum.openmediavault.org/index.php?thread/15223-error-message-failed-to-execute-xpath-query/

checked the xml file does not have any thing related

**openmediavault Server (please complete the following information):**

- OS version: 

`Linux importacion 6.1.0-27-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.115-1 (2024-11-01) x86_64 GNU/Linux`

- openmediavault version: 

```
ii  openmediavault                        7.4.12-3                            all          openmediavault - The open network attached storage solution
ii  openmediavault-apt                    7.0-2                               all          openmediavault APT management plugin
ii  openmediavault-apttool                7.1.1                               all          apt tool plugin for OpenMediaVault.
ii  openmediavault-fail2ban               7.0.1                               all          OpenMediaVault Fail2ban plugin
ii  openmediavault-omvextrasorg           7.0                                 all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-snmp                   7.0-2                               all          openmediavault SNMP (Simple Network Management Protocol) plugin
ii  openmediavault-wireguard              7.0.7                               all          openmediavault WireGuard plugin
```

**Client (please complete the following information):**

- Device: AMD64 16 cores i9900K
- OS: Debian 12
- Browser brave, also tested in firefox ESR
- Version lasted, 122-esr respectyivelly

### Additional context

```
Failed to execute XPath query '//system/apt/sources'.

OMV\Config\DatabaseException: Failed to execute XPath query '//system/apt/sources'. in /usr/share/php/openmediavault/config/database.inc:272
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/config.inc(329): OMV\Config\Database->set()
#1 [internal function]: Engined\Rpc\Config->set()
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#4 /usr/share/openmediavault/engined/rpc/aptmgmt.inc(51): OMV\Rpc\Rpc::call()
#5 [internal function]: Engined\Rpc\AptMgmt->setSource()
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#8 /usr/sbin/omv-engined(544): OMV\Rpc\Rpc::call()
#9 {main}
```

**Comment by ryecoaaron** [comment]
I didn't have any problem adding that repo (other than it doesn't seem to have a Release file).  This is a second database issue now on your system.  What does the following report:  sudo omv-showkey apt

**Comment by mckaygerhard** [comment]
```
root@importacion:/etc/openmediavault# sudo omv-showkey apt
    <apt>
      <distribution>
        <proposed>0</proposed>
        <partner>1</partner>
      </distribution>
    </apt>
root@importacion:/etc/openmediavault# 
```

**Comment by mckaygerhard** [comment]
i repeat installation again in two ways:

1. using debian debootstrap over DELL i9 9900K and OVM packages.. this error of Xpath (no error of the ftp plugin cos i dont installed)
2. using debian OVM oficial ISO in qemu VM no error reported (ftp plugin included but does not report error, i do not upgraded anything)
3. using debian OVM oficial ISO over DELL i9 9900K no error reported neither ftp plugin error
4. using debian debootstrap over QEMU and OVM packages.. this error of Xpath (no error of the ftp plugin cos i dont installed neither upgrade anything after install)

**Comment by votdev** [comment]
Can not reproduce the error as well.

> This is a second database issue now on your system.

I can only agree, something is wrong with your database.

**Comment by votdev** [comment]
> ```
> root@importacion:/etc/openmediavault# sudo omv-showkey apt
>     <apt>
>       <distribution>
>         <proposed>0</proposed>
>         <partner>1</partner>
>       </distribution>
>     </apt>
> root@importacion:/etc/openmediavault# 
> ```

According to this the `openmediavault-apt` plugin was not installed correct and the database is missing the necessary entries. This means the database migration has not been executed, e.g. the package installation was interrupted or you copied a database backup file over the original/migrated one manually.

**Comment by ryecoaaron** [comment]
I have tried to report the issue on four OMV machines now.  No issue on any of them.

**Comment by votdev** [comment]
Try to reinstall the package with `apt-get install --reinstall openmediavault-apt`.

**Comment by mckaygerhard** [comment]
ok it seems there is something with upgrades today.. as i reported when i installed from the older ISO from OVM oficial download site everything works great! 

as i said installed in VM and also in the DELL machien and works.. after upgrade (both deactivating recommends on apt) got to break!  **got the error `Failed to execute XPath query '//system/` on any operation related to modification of files on root filesystem**

on my broken system i **got to work after removal of all plugins..** ok then as you suggested @votdev  reinstall apt OVM plugin and got it work:

![image](https://github.com/user-attachments/assets/3e85d1fd-944f-4898-8278-0b7b525d6184)

you must check updates .. cos seems only happened when i manually install OVM not when use the ISO method
