### ISSUE TITLE
error if trying to disable user home directory when no managed users exits

### ISSUE THREAD

**Issue by mckaygerhard** [openmediavault/openmediavault#1859]
**Describe the bug**

I try to disable the user home directory by uncheck the flag and set to none, but there already users present not managed by OVM and neither into any filesystem

**There is a user named "firtsuser" not in any filesystem, with no home.** But seems OVM assumes is present or managed by!

**To Reproduce**

1. Go to Users->Users
2. Click on each user and delete all the existing users (exept by those that are not part or created by OMV)
3. Go to Users->Settings
4. Disable user homes directory

**Expected behavior**

Disabling home user directorys so then i can reformat the ETX4 partition into HPFS+2

**openmediavault Server (please complete the following information):**

- OS version: 

`Linux devel-systemas0 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux`

- openmediavault version:

```
ii  openmediavault                        7.4.12-3                            all          openmediavault - The open network attached storage solution
ii  openmediavault-apt                    7.0-2                               all          openmediavault APT management plugin
ii  openmediavault-apttool                7.1.1                               all          apt tool plugin for OpenMediaVault.
ii  openmediavault-snmp                   7.0-2                               all          openmediavault SNMP (Simple Network Management Protocol) plugin
```

**Client (please complete the following information):**

**Additional context**

```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; usermod --home '' 'firtsuser' 2>&1' with exit code '3': usermod: homedir must be an absolute path

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; usermod --home '' 'firtsuser' 2>&1' with exit code '3': usermod: homedir must be an absolute path in /usr/share/php/openmediavault/system/process.inc:247
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/usermgmt.inc(1115): OMV\System\Process->execute()
#1 [internal function]: Engined\Rpc\UserMgmt->setSettings()
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#4 /usr/sbin/omv-engined(544): OMV\Rpc\Rpc::call()
#5 {main}
```

**Comment by votdev** [comment]
This looks like a regression in the usermod command. The changes were introduced with https://github.com/shadow-maint/shadow/commit/9d37173b24345160a41a6a1f8be75a0ed87b2445#diff-054037cae6ab0b5c83d68483828ad9e20c3f1cc4a32198e176c76b093df6d899R1113.

**Comment by mckaygerhard** [comment]
thanks @votdev  as you know i have several installations of OMV and this one was using  debootstrap so many packages was not installed and i confirmed login packaged has no reverse dependencies related to OMV or any base essential package already installed;  so it makes sense..
