### ISSUE TITLE
Snapshot via Bash Console

### ISSUE THREAD

**Issue by Mitch187** [openmediavault/openmediavault#1870]
Hi,

is there any way to make a omv-snapshot (btrfs) via bash konsole?
I mean a snapshot that i found in the web-menu, after i make it. And i use to sheduled delete them via webmenu, when it it time to delete.

Best Regards,
Mitch

**Comment by votdev** [comment]
> is there any way to make a omv-snapshot (btrfs) via bash konsole?

Yes, you can use the `btrfs subvolume snapshot` command by passing the correct arguments.

Alternatively you can call the RPC the same way the UI is calling it. Run the following as root.

Get the UUID of the shared folder from which you want to create a snapshot:
```
# omv-confdbadm read --prettify conf.system.sharedfolder | jq
...
  {
    "comment": "",
    "mntentref": "15b84f3a-16c6-451b-abe5-9702d8503f10",
    "name": "test",
    "privileges": {
      "privilege": []
    },
    "reldirpath": "test/",
    "uuid": "9811a426-7648-419a-b7f8-0362f98f08fd"
  },
...
```

Run the RPC:
```
# omv-rpc -u admin 'ShareMgmt' 'createSnapshot' '{"uuid": "9811a426-7648-419a-b7f8-0362f98f08fd"}'
```

**Comment by votdev** [comment]
> Can you recommend a forum for such requests?

https://forum.openmediavault.org
