### ISSUE TITLE
Make snapshots accessible from linux via samba 

### ISSUE THREAD

**Issue by buergi** [openmediavault/openmediavault#1871]
**Is your feature request related to a problem? Please describe.**
For me snapshots are one of the primary feature of a NAS, and with openmediavault they are working perfectly out of the box in combination with windows ("previous versions"), but I couldn't find a way to access the snapshots via linux via samba.

**Describe the solution you'd like**
Ideally linux would be able to browse/mount the previous versions similar to windows, but as far as I know there is no possibility to do this (why?). However, most other NAS software solves this by having a folder called .snapshots, @Recently-Snapshot or similar, inside the share folder, which allows browsing the snapshots for each share.

**Describe alternatives you've considered**
Creating snapshots within the share itself e.g.

    btrfs subvolume snapshot /srv/dev/share /srv/dev/share/.snapshots/20241215T1200

would be a simple work around, but all snapshots created with the omv frontend are stored outside of the share in `/srv/dev/.snapshots` and are therefore not accessible via samba.
I could bind-mount the .snapshot folder into the share folder

    mount -o bind /srv/dev/.snapshots /srv/dev/share/.snapshots

but that way all snapshots of all share folders would be listed in the share's snapshot folder.
For this to work it would help a lot if the snapshots are not called `/srv/dev/.snapshots/share_20241215T120000` but `/srv/dev/.snapshots/share/20241215T120000`.
A simple solution would be to allow the user to choose where the snapshots generated by openmediavault for a given share are stored. What is the reason why snapshots are not stored in `share/.snapshots` by default?

**Comment by votdev** [comment]
You can create a shared folder from a snapshot and share it via Samba.

**Comment by votdev** [comment]
> Ideally linux would be able to browse/mount the previous versions similar to windows, but as far as I know there is no possibility to do this (why?)

You have to ask this question someone else, maybe the guys from Gnome that have implemented SMB support into Nautilus.

> What is the reason why snapshots are not stored in share/.snapshots by default?

To make things simpler, e.g. prevent SMB users from browsing snapshots.

> all snapshots created with the omv frontend are stored outside of the share

This is done with reason.

Creating a shared folder from a snapshot fits completely in the OMV design and philosophy.

**Comment by buergi** [comment]
Thanks for your quick answers @votdev. I wouldn't consider creating a shared folder a solution, as it is only possible for the admin but not for a normal user, and it is quite complicated.

I agree that there are good reasons to not put the .snapshots folder inside the share, most notably, that btrfs snapshots are writeable by default. Nevertheless, I would consider the option to have the snapshots accessible via samba very convenient, especially when non-admins like to restore some of their files.

Just changing the naming convention of the snapshots, as proposed above, to `share/data` instead of `share_date` together with a simple bind mount (should be read only by default) would allows this. It could for example be enabled with a simple checkbox in the properties of a share.

**Comment by votdev** [comment]
I am sorry but OMV will not provide such a feature because this does not fit into the design and already implemented toolset and the following really important issues:

Recursive snapshots. A snapshot will include other snapshots. This will also lead to performance issues.

You can hard/softlink snapshots manually if you want to do so.

> Just changing the naming convention of the snapshots, as proposed above, to share/data instead of share_date together with a simple bind mount (should be read only by default) would allows this. It could for example be enabled with a simple checkbox in the properties of a share.

You can not change anything like this without breaking existing snapshots. Another reason to not implement that.

**Comment by buergi** [comment]
You are definitely write that it would break existing snapshots, it could be easily fixed manually but you are right. I don't fully see the problem of recursive snapshots, which is actually something btrfs does not support anyway. But i accept your arguments that it is probably more effort than I expected. I still don't share the same opinion but at least using softlinks is a viable solution, although not a pretty one. I quickly tested it, it requires the following extra options in samba settings

    [global]
    allow insecure wide links = yes

and these extra options in the settings for each share

    follow symlinks = yes
    wide links = yes

and of course a snapshot directory which contains softlinks to the corresponding snapshots

    cd /srv/dev/share/.snapshots/
    ln -s ../../.snapshots/share_20241215T120000/

These softlinks could be generated (and also cleaned up) via a bash script which runs as a cron job. On the other hand, this opens some potential security problems as it might allow users to access data out of the shared folders.

**Comment by votdev** [comment]
PR https://github.com/openmediavault/openmediavault/pull/1872 might simplify the setup.
