### ISSUE TITLE
[build] Info on kernel and package build for Chinese SBC FriendlyElec NAS Kit

### ISSUE THREAD

**Issue by eabase** [openmediavault/openmediavault#1873]
It's my understanding that you built the package and kernel for the `FriendlyElec NAS Kit` SBC board:

* [CM3588 NAS Kit](https://wiki.friendlyelec.com/wiki/index.php/CM3588_NAS_Kit)
* [CM3588 Get Started](https://wiki.friendlyelec.com/wiki/index.php/CM3588#Get_Started)
* [Getting Started with OpenMediaVault](https://wiki.friendlyelec.com/wiki/index.php/Getting_Started_with_OpenMediaVault)
* [rk3588-eflasher-openmediavault-6.1-arm64-20241112.img.gz](https://drive.google.com/drive/folders/149wf74MZcaWJdY2mL-hSrNBbzeTcpoPT)   **`<-- THIS ONE`**

```bash
# cat /proc/version

Linux version 6.1.57 (fa@jensen) (aarch64-linux-gcc (ctng-1.25.0-119g-FA) 11.3.0, GNU ld (GNU Binutils) 2.38)  
#25 SMP Fri Oct 11 19:56:28 CST 2024
```

Do you have any documentation on the build and modifications you made? 
Do you have a build script?

Are you planning to update this to use a later kernel and OMV?
If not, how can I best proceed trying to repeat what you did?

**Comment by ryecoaaron** [comment]
That was created by Friendly the maker of the board.
