### ISSUE TITLE
Make default ethernet connection hardware agnostic

### ISSUE THREAD

**Issue by Prophet-Phoenix** [openmediavault/openmediavault#1877]
**Is your feature request related to a problem? Please describe.**
Installing OMV on a machine without graphic output is a bit complicated, because the interface matching by netplan is done via name. I followed [this german guide](https://www.bachmann-lan.de/terramaster-f2-220-nas-mit-openmediavault/) and installed to a VM first, changed the interface name in config.xml matching terramasters naming scheme (eth0 to enp2s0), hard power-off the VM and wrote the VM image to a flash drive, which booted fine on the terramaster nas, but what a journey.
Still, troubleshooting ethernet connection issues is very troubling as i have to move the flash drive to another computer, boot there, omv first-aid, but then again do weird stuff to the config file with hard power off and hoping it works if i put the flash drive back in the NAS device.

**Describe the solution you'd like**
I use unRaid on another machine and it is designed with a hardware agnostic philosophy: basically as long as the spinning harddrives are there, you can move the flash drive to any other machine and your server will work. You can still bork the ethernet configuration but not on interface level, only DHCP or static IP level (which is easier to debork without switching (boot) flash drives).
So i think troubleshooting on smaller or older NAS devices (like Terramaster) without graphical output would be more easy, if the default behaviour of OMV would be to ensure at least one working ethernet port by default. One could still enable the netplan matching via name or mac if one wants this behaviour.

**Describe alternatives you've considered**
I considered first installing vanilla debian on the flash drive, then ssh-ing headless to the no-graphic NAS device and installing omv via script, therefore having working ehternet connection due to the right inferface names from the get go.
Still, troubleshooting a not working interface/ethernet connection requires me to move the flash drive to another machine and then theres the interface name matching problem/journey again.

**Additional context**
Many newer NAS devices have graphical output, so troubleshooting is a lot easier. I'm using the somewhat old Terramaster because its a perfectly good small network attached storage for your daily small data remote storage needs and i already own it. Also i loved using OMV so far, its way better than the dafeult terramaster software, wich was a pia.

**Comment by votdev** [comment]
Debian and therefor OMV are using predictable device names for network interfaces and storage devices because using names like eth0 or sda1 will make more trouble than it helps.

**Comment by votdev** [comment]
Please see https://wiki.debian.org/NetworkInterfaceNames for more information.

**Comment by votdev** [comment]
> One could still enable the netplan matching via name or mac if one wants this behaviour.

This is not possible because OMV will not work against the established and de facto standard workflows of Debian.

**Comment by Prophet-Phoenix** [comment]
I understand that it creates trouble going against standard debian workflow and didn't intend that. I thought more of a failsafe behaviour like falling back to first physical ethernet port found, if the configured ethernet port isn't physically there in the machine so one could at least ssh to the machine.
But i also get if that creates security concerns and read the warning in the article you mentioned about machines not reachable if interface names change.

A failsafe could also be documentation about changing configuration without the system beeing booted and only write acces to a boot drive (flash drive) connected to another machine, which would also be helpful in a situation like this.
