### ISSUE TITLE
Feature request: Add support for tiered storage

### ISSUE THREAD

**Issue by Samuel12321** [openmediavault/openmediavault#189]

**Comment by votdev** [comment]
Doesn't seem to be something that is required in a home scenario. Right?

**Comment by Samuel12321** [comment]
Trying to use an ssd to speedup nas (120gb ssd + 2tb HDD, in raid, uploaded data goes to ssd for fast write times, then is later moved across to hdd when not in use). Is this possible?

**Comment by jdainen** [comment]
This would be something like bcache.
