### ISSUE TITLE
openmediavault-cups 3.1.2 bug

### ISSUE THREAD

**Issue by thk70** [openmediavault/openmediavault#194]
Virtual omv 4.1.12 on ESXi vSphere 6 Hypervisor
Trying to enable the plugin "printing" but it errors when click "Save":

`Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; omv-cups 'enableSharing' 2>&1' with exit code '1': Traceback (most recent call last):
  File "/usr/sbin/omv-cups", line 305, in <module>
    apg = OMVCups()
  File "/usr/sbin/omv-cups", line 73, in __init__
    self.conn = cups.Connection()
RuntimeError: failed to connect to server in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/cups.inc(428): OMV\System\Process->execute(Array)
#1 /usr/share/openmediavault/engined/rpc/cups.inc(135): OMV\Engined\Rpc\Cups->runCupsCommand('enableSharing')
#2 [internal function]: OMV\Engined\Rpc\Cups->setSettings(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('setSettings', Array, Array)
#5 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Cups', 'setSettings', Array, Array, 1)
#6 {main}`

**Comment by votdev** [comment]
Please report the bug here: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-cups

**Comment by ryecoaaron** [comment]
This is the wrong place to ask about this plugin.

**Comment by votdev** [comment]
Please report this issue here: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-cups
