### ISSUE TITLE
Implement Debian workaround for bonded network interfaces non-DHCP "cannot send bond option because the bond has slaves"

### ISSUE THREAD

**Issue by jefft4** [openmediavault/openmediavault#204]
I have a bonded interface on my OMV server. I need to set it up with a static address, in order to force the default gateway (an issue with Plex behaving stupidly, don't ask...)

If I set the interface as static, I get a complaint from the Debian OS at boot, 'cannot send bond option because the bond has slaves', and the interface does not function. If I leave it DHCP, I can't set the default gateway (ok, I can edit /etc/network/interfaces directly but that's dangerous with OMV thinking it controls the file).

The problem is a known Debian screw-up, bug report here: bugs.debian.org/cgi-bin/bugreport.cgi?bug=870633 - but no sign of anyone fixing it. There is, on that thread, a workaround involving moving the bond options to a different config file.

Any chance that OMV could implement the workaround, please?

**Comment by votdev** [comment]
I don't think there will be implemented a workaround in OMV because this is definitely a upstream bug and making changes in a really important subsystem at this stage of the release is not good. In OMV5 the network handling is now done by systemd, so this issue is resolved in OMV5.
