### ISSUE TITLE
Power button configuration not working correctly

### ISSUE THREAD

**Issue by eraseromv** [openmediavault/openmediavault#208]
OMV 4.1.13-1 
Debian 9.6
4.18.0-0.bpo.1-amd64
System -> Power Managment -> Settings -> Power button = Nothing
When I press Power Button, server shutdowns.
As written here 
https://wiki.archlinux.org/index.php/Power_management#Power_management_with_systemd 
systemd handles some power-related ACPI events.

To work correctly you need define 
HandlePowerKey=ignore
in /etc/systemd/logind.conf 
or redisign Power Managment via systemd logind.

**Comment by votdev** [comment]
Any idea if there is an equivalent for ``pm-is-supported [--suspend | --hibernate | --suspend-hybrid ]``? Suspend/Hibernate/hybrid-sleep/... seem to be complicated to setup via systemd.

For OMV4 i will stay on using acpid, but for OMV5 it would be nice to use systemd wherever possible.

**Comment by votdev** [comment]
Please note, systemd-logind.service is not restarted, so the changes to /etc/systemd/logind.conf take action after the next reboot. This is done to simplify the implementation because these changes are permanent.
