### ISSUE TITLE
Feature Request:  Bcache

### ISSUE THREAD

**Issue by jdainen** [openmediavault/openmediavault#221]
The idea is to enable Bcache, so the array can power down.  The cache would then automatically transfer at time such as 3am.

**Comment by jdainen** [comment]
For what its worth, I also found this almost solution. 
https://raid6.com.au/posts/fs_ext4_external_journal/

**Comment by Samuel12321** [comment]
I think that would be a great feature.

**Comment by Samuel12321** [comment]
Perhaps a good feature for 5.x

**Comment by mi-hol** [comment]
@votdev , as this had no comments from you I wonder if it should be accepted to backlog or closed. Please advise

**Comment by votdev** [comment]
Keep it open if someone is encouraged to implement such a feature via plugin.
