### ISSUE TITLE
[Feature Request] change watchdog from dependency to suggestion

### ISSUE THREAD

**Issue by niko2** [openmediavault/openmediavault#224]
Hello,

Is it possible to remove watchdog as a dependency and move it as a suggestion ?

Since there is no entry in GUI to configure/disable it, I would prefer not to suffer unwanted reboots.

**Comment by votdev** [comment]
The watchdog feature is an essential part of OMV, so it won't be removed. If you are running a headless NAS then it is absolutely important that the system will be rebooted if it is in a dead state.

The problem on your side is not the watchdog, something else brings your system into a dead state where watchdog is simply doing it's job. Identify the problem and your fine.

You can simply disable the watchdog unit file to tell systemd to do not start it if you really do not want to use it.

**Comment by serkamil** [comment]
Hello,

I also ask to move watchdog from dependency to suggestion.

In one configuration, I have to remove watchdog and I cannot do it because OMV requere it.
In my configuration I don't use it and disable don't resolve my problem.
Please, analyze if it not should be as different module (package) in OMV (like openmediavault-diskstats or openmediavault-snmp) installed default but possible to uninstall this package on particular situation.

Best regards,
Kamil

**Comment by niko2** [comment]
Hello @serkamil,

Despite the fact this issue is closed, I may give you my insight.

Since watchdog will stay as OMV package dependency, I decided to rebuild packages (still using 4.x, but should work with 5.x as well) with a simple patch.
Take a look at my fork.

**Comment by N0NameN0** [comment]
@niko2 any plan about patching 6.x Shaitan ??

**Comment by niko2** [comment]
> 

I don't think so.
I have removed proxmox from my NAS...
Good Luck. The patch is not so hard
The most work is to maintain packages and there are many updates on 5.x or 6.x
I was thinking about a pipeline to do it automatically when OMV repo is updating.

**Comment by ryecoaaron** [comment]
@votdev It looks like we could use just systemd for the watchdog.
Setting 
RuntimeWatchdogSec=10
in
/etc/systemd/system.conf
should watch /dev/watchdog and reset the system if not responsive in 10 secs.  This should allow the watchdog package to not even be used.  I don't have a good way to test this though.
