### ISSUE TITLE
Feature Request: Add last USB-Backup time and status

### ISSUE THREAD

**Issue by gituser2a** [openmediavault/openmediavault#225]
I like the stable and silent behavior of the USB-Backup service. Anyhow, sometimes I would like to know when the last backup did rund and if it was successfull or not - without having to search the rsync-job logs.
So could you please add in one of the next releases two additional columns to the USB Backup page of the omv GUI showing last runtime and status of a paricular backup (including a "still running" flag if it is not finished yet).

**Comment by mi-hol** [comment]
very similar to #686
