### ISSUE TITLE
Support to sync files/ folders with Onedrive and other cloud providers

### ISSUE THREAD

**Issue by Samuel12321** [openmediavault/openmediavault#227]
This is not backing up to a cloud this is syncing files on a nas with onedrive.
Synergy has a similar thing with CloudSync.
This would be quite a usefull feature

**Comment by ryecoaaron** [comment]
Have you looked at the duplicati plugin from omv-extras?

**Comment by Samuel12321** [comment]
Hi thanks for your suggestion, unfortunatly duplicati only saves backups of a nas to onedrive, i am attemting to have a file sync normally with onedrive like it would if on a windows computer.

**Comment by jdainen** [comment]
Try rsync or insync.  https://youtu.be/5UmU0M7lM-Q

**Comment by Samuel12321** [comment]
that is basically what i am trying to do, however it would be nice if there was a simpler free alternitive

**Comment by awehrfritz** [comment]
Wouldn’t Rclone do the job? It runs on pretty much any Linux, supports OneDrive and has at even an experimental two-way sync feature.
Not sure how this would work with OMV, as I’m new to it and haven’t really tested it in the wild.
