### ISSUE TITLE
HP 320GB ioDrive Duo and disable smart 

### ISSUE THREAD

**Issue by Fever-Wits** [openmediavault/openmediavault#228]
Hello,
I installed an HP 320GB ioDrive Duo (Fusion-io ioDrive Duo) on my server. When I try to see smart disk status I get the following error

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; smartctl -x '/dev/fioa' 2>&1' with exit code '1': smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.18-9-pve] (local build) Copyright (C) 2002-16, Bruce Allen, Christian Franke, smartmontools.org /dev/fioa: Unable to detect device type Please specify device type with the -d option. Use smartctl -h to get a usage summary

Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; smartctl -x '/dev/fioa' 2>&1' with exit code '1': smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.18-9-pve] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, smartmontools.org

/dev/fioa: Unable to detect device type
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
in /usr/share/php/openmediavault/system/storage/smartinformation.inc:161
Stack trace:
#0 /usr/share/php/openmediavault/system/storage/smartinformation.inc(193): OMV\System\Storage\SmartInformation->getData()
#1 /usr/share/php/openmediavault/system/storage/smartinformation.inc(377): OMV\System\Storage\SmartInformation->getAttributes()
#2 /usr/share/openmediavault/engined/rpc/smart.inc(86): OMV\System\Storage\SmartInformation->getTemperature()
#3 [internal function]: OMVRpcServiceSmart->enumerateDevices(NULL, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#5 /usr/share/openmediavault/engined/rpc/smart.inc(165): OMV\Rpc\ServiceAbstract->callMethod('enumerateDevice...', NULL, Array)
#6 [internal function]: OMVRpcServiceSmart->getList(Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#8 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('getList', Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(565): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatustW...', '/tmp/bgoutputr3...')
#10 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#11 /usr/share/openmediavault/engined/rpc/smart.inc(200): OMV\Rpc\ServiceAbstract->callMethodBg('getList', Array, Array)
#12 [internal function]: OMVRpcServiceSmart->getListBg(Array, Array)
#13 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#14 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getListBg', Array, Array)
#15 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Smart', 'getListBg', Array, Array, 1)
#16 {main}

I know this device does not have smart support, but I do not know how to tell the system to ignore it.
Has anyone had a similar problem?
How can I hide or disable scanning on the fio device?

**Comment by ryecoaaron** [comment]
Volker, for reference - https://forum.openmediavault.org/index.php/Thread/25067-HP-320GB-ioDrive-Duo-and-smart/

**Comment by Fever-Wits** [comment]
This is my post in which I have been directed to look here. I did not find a topic to solve my problem and I opened this topic.
