### ISSUE TITLE
Enable customizing uid/gid when creating user/group

### ISSUE THREAD

**Issue by xmstspider** [openmediavault/openmediavault#231]
Hi,

when creating a new user/group, there is no way how to manually set uid/gid beside of running vipw/vigr later.
Sometimes I need to have a user or group with a particular id and this functionality should be part of the new user/group dialog in the GUI.

**Comment by votdev** [comment]
Such things do not fit into the concept and design of OMV. You can use the CLI to create such user/group and manage them later via WebUI.

**Comment by hobopoppa** [comment]
I have found two problems with CLI user account administration and OMV:
1.  users created via CLI do not appear in the web GUI. 
2.  if a web GUI created user uid is modified at the CLI then that user no longer appears in the web GUI after it is modified.

I'm evaluating a transition from FreeNAS. There the UID can be specified when creating users. Now when creating NFS shares on the OMV machine to the FreeNAS box the UIDs do not match between the two systems.

Sure, user accounts can be managed completely via the CLI, then the OMV user administration function is entirely abandoned. However, I find the FreeNAS user management approach very easy. I can look at the users that I have created at a glance in the GUI and tweak to my hearts content. Yup, can do the same thing via the CLI, just more visceral in the GUI.

Regarding "does not fit into the concept of OMV": 
Without wanting to be confrontational, OMV has specifically stated: 
_"It is a simple and easy to use out-of-the-box solution that will allow everyone to install and administrate a Network Attached Storage without deeper knowledge."_

I take this as a mission statement of sorts to introduce new users (including those new to Linux) to building their own NAS function. From this perspective, features that make system administration easier seem to fit right in.  :)

**Comment by votdev** [comment]
> 1. users created via CLI do not appear in the web GUI.

In this case the UID and GID is out of the range which is defined in ``/etc/login.defs``.

> 2. if a web GUI created user uid is modified at the CLI then that user no longer appears in the web GUI after it is modified.

See answer for 1.

OMV does not support UID and GID settings because this makes it more complex and error prone for normal users. And because of the missing of this features the dictum of OMV is fully fulfilled.

As workaround you can use the user/group import dialog to manually set the UID/GID.

**Comment by neo-neo1** [comment]
Changing the UID of user accounts in the WebUI is not only useful, it is a near requirement for configuring NFS permissions and other things. As stated above, changing the user account UID in CLI simply removes the account from the WebUI. Until this feature is expanded/fixed the user account Administration in OpenMediaVault is incomplete and partially broken.

**Comment by ryecoaaron** [comment]
In my opinion, if you need matching UIDs across multiple systems, you should be using LDAP.  And there is an LDAP plugin.

**Comment by neo-neo1** [comment]
UID is a classic permission authority for NFS. No need to reinvent the wheel.

**Comment by ryecoaaron** [comment]
ldap is basically a central UID database.  Not sure how that is reinventing the wheel.  If you have 1 client, just change the UID on the client.

**Comment by neo-neo1** [comment]
> ldap is basically a central UID database. Not sure how that is reinventing the wheel. If you have 1 client, just change the UID on the client.

I rather change the UID on a new OMV install rather than change it on a client machine and break the system. Thanks for giving us Administration tips though.
