### ISSUE TITLE
openmediavault login user password not change issue.

### ISSUE THREAD

**Issue by iamneo2416** [openmediavault/openmediavault#234]
I just use "**admin**" and "**openmediavault**" to login and download extras and install it. After a system reboot, I tried to login again, but it keeps says invalid password.

I don't change default username or password setting. Why it is not working anymore ?

**Comment by iamneo2416** [comment]
This happen two times already. I retry a clean install. After web session time out, it seems cannot use default admin / openmediavault to login.

**Comment by LukaMatkic** [comment]
Any update on this ? I have changed admin password, used it in past 2 days to setup everything. Now when I try to log in it says password is wrong...

**Comment by ryecoaaron** [comment]
If your OS drive is filled, you won't be able to login.

**Comment by LukaMatkic** [comment]
There is definitely problem with password. I know my OMV admin password, but yesterday I had the same "wrong password" problem. After rebooting server problem was gone. If this happens again I will take a look into logs.
OS drive is Kingston SSD 120GB, it has more than enought space...

**Comment by Gremlingroj** [comment]
I confirm, I had the same problem. Resetting via omv-firstaid helped, although I had to use a simple password like 12345678, and after successfully logging in via GUI, change it to a more complicated, strange problem.

**Comment by votdev** [comment]
Which install method we are talking about here? ISO image, manually on a pre-installed Debian or a ARM image?

**Comment by Gremlingroj** [comment]
> Which install method we are talking about here? ISO image, manually on a pre-installed Debian or a ARM image?

ISO image with editing preseed.cfg (for manual use function of Partitioning)

**Comment by votdev** [comment]
If it works one day and the other not then this is not a general problem of OMV, in most cases this is caused by a full or corrupted file system.

**Comment by votdev** [comment]
Looking into /var/log/auth.log may also help to find out the reason.

**Comment by votdev** [comment]
Please reopen if necessary.

**Comment by petitsurfeur** [comment]
Same problem (RPI3).
Fresh install. I did all the updates, I created a user and rebooted. I can't login using SSH (root or user) or GUI (admin). I'm stuck, I need to install again...

**Comment by votdev** [comment]
@petitsurfeur Maybe you did not let your system enough time to resize the filesystem. This mostly results in a broken system. This is a common user error.

**Comment by petitsurfeur** [comment]
Hi
I installed again and I really gave enough time to resize and I have the same SSH problem. I allowed root access and it worked (I restarted the service to make sure). I didn't update. And after reboot I can no more log in using my password or the default one whereas GUI access works. :(

**Comment by votdev** [comment]
Can not repdroduce this, so i assume this is an issue of the RPI image which is not maintained by the OMV project.

**Comment by DieterVDW** [comment]
`User 'admin' has been banned after 12 failed login attempts`

After a few login attempts, the above happens which makes things very confusing.
Even after resetting the admin password, you'll keep getting access denied until the timeout has passed (seems to be a few minutes, no idea where that is configured).

**Comment by votdev** [comment]
@DieterVDW Resetting the password does not help, a PAM plugin takes care about failed logins. You need to use `omv-firstaid` to reset the failed login counter.

**Comment by DieterVDW** [comment]
@votdev : I'm pretty sure I did that though, and I still couldn't log in.
The problem seemed to resolve itself after a few minutes, but right after using `ovm-firstaid` I'm pretty sure I couldn't log in...

**Comment by shell3000** [comment]
This problem is in OMV for years. Again. After a fresh Installation of OMV5 i can not SSH-Login as pi-User. Which is awful because it was possible before the installation .. argh.
It seems OMV remove the ssh-group-functionality from the user, but you can re-edit it in the GUI under User > Pi > Edit > Groups > turn on "SSH".
After that i can SSH-Login as the (usual) Pi-User AGAIN. This ominous Root-User-Login never worked for me and it seems it never worked for anybody ...

**Comment by votdev** [comment]
> It seems OMV remove the ssh-group-functionality from the user, but you can re-edit it in the GUI under User > Pi > Edit > Groups > turn on "SSH".

No, this is not true.

**Comment by ryecoaaron** [comment]
> It seems OMV remove the ssh-group-functionality from the user, but you can re-edit it in the GUI under User > Pi > Edit > Groups > turn on "SSH".
After that i can SSH-Login as the (usual) Pi-User AGAIN. This ominous Root-User-Login never worked for me and it seems it never worked for anybody ...

And everything I have written about using OMV on the RPi tells you to not use the pi user.  The first thing you should do after installing OMV is create a new user in the ssh and sudo groups from the web interface.  You don't need to login as root or keep using the pi user.  As much as I want to delete the pi user, I will just have my installScript (not sure if you used it), add the damn pi user to the ssh group...

**Comment by ccwanggl** [comment]
Use omv-firstaid though ssh client to config network interface solves my problem.

**Comment by lotsalu** [comment]
> You can reset the password with the `omv-firstaid` CLI tool. You need to log in to the terminal as root user to execute it.

it`s ok, 1、change admin`s password, then clear the attempt login failed cache, and you will be ok.

**Comment by chrismyers81** [comment]
> > It seems OMV remove the ssh-group-functionality from the user, but you can re-edit it in the GUI under User > Pi > Edit > Groups > turn on "SSH".
> 
> No, this is not true.

This happened to me as well.

I'd installed my rpi 3B from the usual raspbian image, created a new user, deleted the "pi" user, and have been working with it without issue for a fair while, including several reboots. Installed OMV via https://openmediavault.readthedocs.io/en/5.x/installation/on_debian.html , rebooted, let it sit for half an hour, and couldn't log in via SSH like I'd done a dozen times before. I know that the SSH service was running, confirmed by both the GUI and the fact that I was getting an "invalid password" error.

Tried the fix above (re-adding the ssh group through the GUI) and could SSH again.

Either OMV made this change, or one of the co-requisite packages did.

**Comment by votdev** [comment]
> Either OMV made this change, or one of the co-requisite packages did.

OMV does not do something like that on it's own.

**Comment by alexswan** [comment]
same stupid error. fresh install on old ssd (with old install). new boot. password not recognized. openmediavault 45.6.13-1. it didn't worked after i changed the default password in web interface. after that i did another install and aftar that i could not login on console.

**Comment by Mesyu** [comment]
It seems the password issue has still not been resolved! I just installed OMV6 on a BMAX B2 pc and admin should be wrong!
I was not asked for a name, only a password. SSH into OMV6 accepts admin but next says the pw is wrong...
Re-install o r what???

**Comment by ryecoaaron** [comment]
If something creates the admin user before OMV is installed, OMV is not going to change the password.  And admin cannot ssh into OMV since it is not in the ssh group and has a shell of nologin.

**Comment by ryecoaaron** [comment]
If you need to ssh in, either create a user in the web interface and put that user in the ssh group OR login as root.  You set the root password when installing.

**Comment by Mesyu** [comment]
I'll go and try again...

**Comment by Mesyu** [comment]
Thanks ryecoaaron, after carefull reinstallation it works well!

**Comment by ABRUPTLY** [comment]
Столкнулся с тем, что после чистой установки не пускает в WEB интерфейс, при установке был указан пароль для ROOT ,
собственно как и во всех нормальных системах вводишь логин root по умолчанию  и пароль тот который вводил при установке OMV а там всемирный облом!!!! при этом в SSH пускает. 
- все перепробовал, и смену пароля и сброс ошибок входа ничего не помогало 
- думаю ладно, делаю сброс пароля ввожу стандартный пароль openmediavault через omv-firstaid CLI
- login admin / pass openmediavault и че думаете ? эта падла пускает! 
- ей нужно после установки обязательно залогиниться под стандартной учеткой  !

**Comment by djdmx85** [comment]
This bug is still present: after fresh installation of OMV7 (no other OS on disk) I changed admin password from GUI. From this time I can't login with admin user, nor GUI or SSH.
I can login with root from CLI/SSH, but if I run omv-firstaid and change admin password, it doesn't solve the problem!
