### ISSUE TITLE
Openmediavault does not honor systemctl for reboot/poweroff/suspend(standby) in web gui.

### ISSUE THREAD

**Issue by davekr8** [openmediavault/openmediavault#237]
From my point of view the systemctl concept should be the preferred way for switching the runlevels. In my current installation (4.1.15-1 (Arrakis)) it seem not to be consistently managed.

Also the "autoshutdown" plugin is stick to "pm-*" concept for the shutdown commands, rather than the systemctl calls. 

Is there any profund reasoning for the current state?

**Comment by votdev** [comment]
Already fixed in OMV5

**Comment by davekr8** [comment]
Great!
