### ISSUE TITLE
Accessing APM causes HDD to not mount 

### ISSUE THREAD

**Issue by vtalikka** [openmediavault/openmediavault#242]
When I change the HDD's APM settings the following happens:
- the HDD does not mount anymore after reboot
- I can mount the HDD manually but the mount point is different 
- rebooting takes a very long time
- monit sends an alert: "filesystem flags changed to 0x1008" (the flags are sometimes different) 

I did a fresh install with the same hardware but without changing APM settings and everything works fine. Reboot takes about a minute and the HDD mounts automatically, also no monit alerts.

Symptoms seem almost exactly the same as described here: https://forum.openmediavault.org/index.php/Thread/24288-Odroid-HC2-8TB-WD-red-too-big/

I'm using OMV 4.14.69 with ODROID-HC2. HDD is WD Red 4TB SATA.

**Comment by votdev** [comment]
Please submit more information, e.g. screenshots and syslogs.

**Comment by vtalikka** [comment]
@votdev : Can you specify which logs and screenshots should I post?

**Comment by votdev** [comment]
hdparm errors are hard to debug because udev triggers this tool now. So i can only direct you to the blog post https://blog.dachary.org/2016/11/30/logging-udev-events-at-boot-time/ which explains how to debug udev events. This might help to identify the problem.

**Comment by vtalikka** [comment]
Thanks! I'll try that once I have time to set my mind to it.

**Comment by vtalikka** [comment]
Thanks for the link, I managed to get thorough logs using udev_log="debug". The log file immediately after boot is about 6MB; what should I search for and post here?

**Comment by votdev** [comment]
I don't know, search for any errors.

**Comment by donhwy** [comment]
Try forcing a log rotate maybe?

**Comment by mi-hol** [comment]
4.x is EOL
