### ISSUE TITLE
Create iSCSI target plugin

### ISSUE THREAD

**Issue by votdev** [openmediavault/openmediavault#258]
https://www.tecmint.com/setup-iscsi-target-and-initiator-on-debian-9/

**Comment by HarvsG** [comment]
This would be great, and based on [this historic post](https://www.openmediavault.org/?p=2199), maybe it is time to bring it back.

**Comment by payback007** [comment]
I also highly appreciate it, is there any chance coming in 5.x?

**Comment by ryecoaaron** [comment]
Guessing not since the 5.x tag was removed.

**Comment by greenvespa** [comment]
+1
I'm still use ISCSI plugin on OMV3 and I don't want to change nas distro.

**Comment by Jontron123** [comment]
+1
I too am stuck on OMV3 because I need iSCSI functionality.
I am guessing there are many people stuck on OMV3 for the same reason.

**Comment by jdelker** [comment]
+1
Also stuck on OMV3, waiting desperately on reappearance of working iSCSI target plugin in a more recent version.
In fact, I'm somewhat irritated, that this does not get more attention. I would consider this a core functionality of any storage server.

**Comment by arevindh** [comment]
+1

**Comment by hh-it-co** [comment]
+1

**Comment by ryecoaaron** [comment]
I wrote a very simple tgt plugin that is in the omv-extras testing repo for OMV 5.x. 
 https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-tgt

**Comment by mi-hol** [comment]
any feedback from users of the plufin?

**Comment by ryecoaaron** [comment]
plugin seems good enough to close this issue.

**Comment by hh-it-co** [comment]
The plugin is fine as it does what it is supposed to.
Nice to have would be another tab with some monitoring-information. For example with the output of

tgtadm --lld iscsi --op show --mode target

or so.

Since i am using multi-pathing, it would be nice to have the option to add multiple intiator-addresses. Currently i am using the advanced options-field for that, so there is no actual need for that - but it would be nice ;-)

**Comment by mi-hol** [comment]
I searched on [bintray ](https://bintray.com/beta/#/openmediavault-plugin-developers/usul?tab=packages)for iSCSI but had no hit.
As it was apparently a prt of OMV4, should it be mentioned in a doc?

**Comment by ryecoaaron** [comment]
@hh-it-co Please file an issue here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-tgt/issues

@mi-hol The plugin is named openmediavault-tgt and was created for OMV 5.x.

**Comment by mi-hol** [comment]
the open question is in my view: How would someone searching for iSCSI find this great plugin?

**Comment by ryecoaaron** [comment]
tgt is the most popular iscsi target right now. If a noob doesn’t know that, I’m not sure how they would find it. I guess the plugin’s description could be added to.

**Comment by ryecoaaron** [comment]
Actually the plugin has the term iscsi in its description. So, if you put iscsi in the search box on the Plugin tab in the omv web interface, it comes up.

**Comment by ramji047** [comment]
+1
