### ISSUE TITLE
Setting Date & Time Fresh Installation Arrakis 4.1.1-2 (on Debian Stretch)

### ISSUE THREAD

**Issue by khalsajing** [openmediavault/openmediavault#259]
Recommend "Low Priority" because the action seems to 'stick' after clicking OK on the error:
OS: Linux omv 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

Error #0:
OMV\Exception: Failed to open file (filename=/tmp/bgstatustFzQtx, mode=r). in /usr/share/php/openmediavault/json/file.inc:78
Stack trace:
#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(384): OMV\Json\File->open('r')
#1 /usr/share/openmediavault/engined/rpc/exec.inc(151): OMV\Rpc\ServiceAbstract->getBgProcStatus('/tmp/bgstatustF...')
#2 [internal function]: OMVRpcServiceExec->isRunning(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('isRunning', Array, Array)
#5 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Exec', 'isRunning', Array, Array, 1)
#6 {main}

**Comment by ryecoaaron** [comment]
Update your system to a new version of the OMV package.  This was fixed around 4.1.2 or 4.1.3.

**Comment by khalsajing** [comment]
Thank you.
