### ISSUE TITLE
Proposal: Remove support for non POSIX compliant filesystems to host shared folders

### ISSUE THREAD

**Issue by votdev** [openmediavault/openmediavault#262]
Remove the support of non POSIX compliant filesystems (e.g. FAT[32]) to host shared folders because of the amount of problems users run into, including the resulting maintenance in the forum.

OMV excessively uses POSIX features like ACL which are not supported by the mentioned file systems, so errors and limited usage will be the result.

**Comment by ryecoaaron** [comment]
I think this is a good idea.  Do you envision people using the usbbackup plugin to sync a non-POSIX filesystem to a shared folder?

**Comment by votdev** [comment]
I think using the usbbackup or similar plugins should be the preferred way to import and export data.

**Comment by hegyre** [comment]
Hello,
Do you mean NTFS drives will not anymore be able to be shared ?

**Comment by votdev** [comment]
Yes, NTFS will be only supported for backup issues like openmediavault-usbbackup.

**Comment by mi-hol** [comment]
is this issue intentional not on the ToDo list for 5.x?

**Comment by jefbam** [comment]
If I'm reading this correctly, this issue is proposing the removal of NTFS support for smb/cifs shared folders? If this is the case, we will need to find another NAS solution. This has been working very well for us with some tweaks, and with great performance.
Very disappointed to hear this.

**Comment by flmaxey** [comment]
> If I'm reading this correctly, this issue is proposing the removal of NTFS support for smb/cifs shared folders?

You're not reading it correctly.  There's a difference between storing DOS files in an SMB share, Linux servers support this, and using NTFS formatted disks as storage media on a Linux Server.  Storing NTFS (or DOS) files will always be supported, inside SMB shares.  

What is not supported is using NTFS formatted **disks**, directly connected to the Linux server, as a source for shared folders.  Why?  NTFS permissions can not be reconciled cleanly with POSIX permissions.  With an SMB network share acting as a translator, of a sort, NTFS files can be stored on POSIX file systems without permissions issues.

**Comment by jefbam** [comment]
Yes, thank you for pointing out the distinction. The concern stands. They are directly-connected disks with ntfs partitions that I am referring to. Removing this functionality in future builds would require us to stop updating OMV and look for another solution.

I can only say that we've been running smb/cifs shares on direct-connected ntfs partitions for a very long time with no problems and great performance. I'd hope to see this functionality retained.

**Comment by ryecoaaron** [comment]
No need to stop using OMV.  While ntfs isn't good for a lot of things on Linux, it should be fine to use with samba.  And since omv can't restrict a sharedfolder to only work with one service, you can manually mount the filesystem and add an entry outside of the openmediavault tags in /etc/fstab.  Then install the sharerootfs and just add a shared folder using the path you mounted.  

With paragon working on adding their ntfs read write driver to the kernel, ntfs will probably become a lot more popular on Linux.

**Comment by jefbam** [comment]
Yikes. Thanks for the info. We chose omv as a solution almost specifically for it's ease of use of the gui for managing file shares and user privileges--it does this very well I'd say. Avoiding administrators manually editing the fstab, etc. to perform these tasks is what OMV has solved for us.

Thanks for the info on the paragon ntfs driver. I don't know what that means yet but I'll look it up.

**Comment by mi-hol** [comment]
@jefbam would you mind to share more detail of your use case & number of installations?
Understanding these details helps developers to make the right decisions.

**Comment by mi-hol** [comment]
> With paragon working on adding their ntfs read write driver to the kernel,

@ryecoaaron, would you have a link to this work in progress?

**Comment by ryecoaaron** [comment]
phoronix has written many stories about Paragon trying to mainline their ntfs driver. Here is one - https://www.phoronix.com/scan.php?page=news_item&px=NTFS3-v14-Compression

**Comment by mi-hol** [comment]
Considering the progress to enhance & integrated NTFS driver into linux kernel, I'd suggest to put this on hold for now.
Based on progress over the next 3 months it might be appropriate to cancel the proposal.
@votdev what is your view?

**Comment by mi-hol** [comment]
@votdev adding emojis doesn't trigger an update notification, hence risk of your feedback being overseen unintentionally is very high! Please consider to write a short response

**Comment by mi-hol** [comment]
re-reading the proposal, would it still be appropriate to remove FAT, FAT32 & exFAT file systems?

**Comment by votdev** [comment]
> re-reading the conversation & proposal my question is:
> Would it still be appropriate to remove FAT, FAT32 & exFAT file systems?

[exFAT](https://de.wikipedia.org/wiki/File_Allocation_Table#exFAT) supports ACL.

Removing FAT and FAT32 would make sense.

**Comment by mi-hol** [comment]
With this clarification, to avoid further confusion, could you please revise the first comment, in particular "Remove the support of non POSIX compliant filesystems (e.g. FAT32 and NTFS)" to reflect the current understanding?

**Comment by mi-hol** [comment]
@votdev the labels and assignment to Project 6.x are out-of-sync.
May I suggest to align them?
