### ISSUE TITLE
"Select a Drive" dialog doesn't open a dialog

### ISSUE THREAD

**Issue by paul-hammant** [openmediavault/openmediavault#264]
![2019-01-12_1141](https://user-images.githubusercontent.com/82182/51072807-22057d00-165f-11e9-88a0-e6b539c34b64.png)

This happens for Chrome 71.0.3578.98, Safari 12.0.2 and Firefox 64. OMV 4.1.17.1 and there's nothing in the browser console that would lead me to believe this is a JavaScript problem.  Otherwise this is an Odroid HC1 with all updates applied to OMV install. 

.. and why'd y'all sprinkle `unselectable="on"` through the source? I'd prefer to copy/paste 4.1.17.1 into bug reports.

**Comment by ryecoaaron** [comment]
Did you mount a filesystem in the filesystems tab?  That is the only way a device will show up in that dropdown.  You can't use the OS drive for data.  You should watch a few of these videos - https://forum.openmediavault.org/index.php/Thread/23005-Installation-and-Setup-Videos-Beginning-Intermediate-and-Advanced/?pageNo=1

As for the unselectable, that is probably part of the extjs framework that OMV uses.

**Comment by paul-hammant** [comment]
Yup. that's it. I'd put some text in there - in lieu of the whole drop-box or the popup, have "go to the drives/fileSystem tab and mount one there first, then come back here"

**Comment by votdev** [comment]
> .. and why'd y'all sprinkle `unselectable="on"` through the source?

That's done by the Sencha ExtJS framework.

**Comment by votdev** [comment]
> Yup. that's it. I'd put some text in there - in lieu of the whole drop-box or the popup, have "go to the drives/fileSystem tab and mount one there first, then come back here"

Is the problem solved now?

**Comment by paul-hammant** [comment]
Yes, thanks.
