### ISSUE TITLE
Smart Schedule Test  - Uses wrong device file - Results in no scheduled tests

### ISSUE THREAD

**Issue by hurricanehrndz** [openmediavault/openmediavault#268]
```
omv-rpc "Smart" "enumerateMonitoredDevices" "{}"
```
This command never returns the devicelinks in the same order, because udevadm never does. The assumption that the first value in the array is the same as the value returned by `getPredictableDeviceFile` is wrong.

In the following file:
https://github.com/openmediavault/openmediavault/blob/7d68989681a819ec7929f48fb6a9adb5b10597a4/deb/openmediavault/var/www/openmediavault/js/omv/module/admin/storage/smart/ScheduledJobs.js#L86-L115

enumeratedMonitoredDevices is referenced and the first item in the device links array is used as the PredictableDeviceFile. The PredictableDeviceFile is the one used in the omv db. i.e.
```
    "monitor": {
        "device": [
            {
                "devicefile": "/dev/disk/by-id/ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E3KA2T92",
                "devicetype": "",
                "enable": true,
                "uuid": "0a3e5037-9084-480e-a4fa-f03a1b1b9854"
            },
            {
                "devicefile": "/dev/disk/by-id/ata-ST4000VN008-2DR166_WDH1F558",
                "devicetype": "",
                "enable": true,
                "uuid": "4a45aace-dee8-4afb-9551-e51c89901fa0"
            },
            {
                "devicefile": "/dev/disk/by-id/ata-SK_hynix_SC311_SATA_128GB_EJ75N429211805D6A",
                "devicetype": "sat",
                "enable": true,
                "uuid": "d535d05b-3b11-46d0-bb00-ecc9051cef1a"
            },
            {
                "devicefile": "/dev/disk/by-id/ata-WDC_WD40EFRX-68N32N0_WD-WCC7K6HJVF1L",
                "devicetype": "",
                "enable": true,
                "uuid": "a5881a6a-4ae0-4854-ad17-1e042872f6de"
            }
        ]
    }
```
This issue basically makes the schedule smart tests interface work unpredictably since there is no telling what device link will be set. i.e you might end up with a scheduledtests config that uses the disk "World Wide ID".
```
            {
                "comment": "",
                "dayofmonth": "*",
                "dayofweek": "*",
                "devicefile": "/dev/disk/by-id/wwn-0x5ace42e0903141fd",
                "enable": true,
                "hour": "02",
                "month": "*",
                "type": "S",
                "uuid": "4a5ccb42-ef69-4409-b974-43075381f438"
            }
```

In order to solve the issues enumerateDevices and MonitoredDevices should probably included the PredictableDeviceFile or sort the devicelinks accordingly so that the first item in the array is the Predictable Device File

**Comment by hurricanehrndz** [comment]
As a work around I have modified line
https://github.com/openmediavault/openmediavault/blob/7d68989681a819ec7929f48fb6a9adb5b10597a4/deb/openmediavault/var/www/openmediavault/js/omv/module/admin/storage/smart/ScheduledJobs.js#L95
to the following
```
if (RegExp("^\/dev\/disk\/by-id\/ata.+$",
```

**Comment by hurricanehrndz** [comment]
Here is probably a real world experience of a user being affected by this bug:
https://forum.openmediavault.org/index.php/Thread/23930-Automated-SMART-tests-not-starting/?pageNo=1

**Comment by votdev** [comment]
This is strange, because when SMART is enabled for a device the backend uses the predictable device file to store in the database (https://github.com/openmediavault/openmediavault/blob/4.x/deb/openmediavault/usr/share/openmediavault/engined/rpc/smart.inc#L312). When setting a scheduled job, the device file submitted by the UI is used to request the predictable device file of this device, see https://github.com/openmediavault/openmediavault/blob/4.x/deb/openmediavault/usr/share/openmediavault/engined/rpc/smart.inc#L525. According to the code the predictable device file is ALWAYS stored in the database, so both for the device settings and the scheduled job should be equal.

**Comment by hurricanehrndz** [comment]
@votdev 

Yes the rpc code is not at fault, the problem is with the ui and line you pointed out. And you are correct the Predictable Device File name is the only name ever populated into the monitored database, but the same can not be said about the scheduledtest. Looking at smart.inc and line 525 I would have to agree that this is very strange. With information on hand, I would have to agree with you, that there is no way the world wide id should be ending up in the database.

Here is the output of the command you asked:
```
DEVLINKS=/dev/disk/by-id/wwn-0x5ace42e0903141fd /dev/disk/by-path/pci-0000:00:14.0-usb-0:1.2:1.0-scsi-0:0:0:0 /dev/disk/by-id/ata-SK_hynix_SC311_SATA_128GB_EJ75N429211805D6A
DEVNAME=/dev/sdd
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1.2/2-1.2:1.0/host4/target4:0:0/4:0:0:0/block/sdd
DEVTYPE=disk
ID_ATA=1
ID_ATA_DOWNLOAD_MICROCODE=1
ID_ATA_FEATURE_SET_APM=1
ID_ATA_FEATURE_SET_APM_ENABLED=0
ID_ATA_FEATURE_SET_HPA=1
ID_ATA_FEATURE_SET_HPA_ENABLED=1
ID_ATA_FEATURE_SET_PM=1
ID_ATA_FEATURE_SET_PM_ENABLED=1
ID_ATA_FEATURE_SET_SECURITY=1
ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=2
ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=2
ID_ATA_FEATURE_SET_SMART=1
ID_ATA_FEATURE_SET_SMART_ENABLED=1
ID_ATA_ROTATION_RATE_RPM=0
ID_ATA_SATA=1
ID_ATA_SATA_SIGNAL_RATE_GEN1=1
ID_ATA_SATA_SIGNAL_RATE_GEN2=1
ID_ATA_WRITE_CACHE=1
ID_ATA_WRITE_CACHE_ENABLED=1
ID_BUS=ata
ID_MODEL=SK_hynix_SC311_SATA_128GB
ID_MODEL_ENC=SK\x20hynix\x20SC311\x20SATA\x20128GB\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_PART_TABLE_TYPE=dos
ID_PART_TABLE_UUID=fd6b0760
ID_PATH=pci-0000:00:14.0-usb-0:1.2:1.0-scsi-0:0:0:0
ID_PATH_TAG=pci-0000_00_14_0-usb-0_1_2_1_0-scsi-0_0_0_0
ID_REVISION=70000P10
ID_SERIAL=SK_hynix_SC311_SATA_128GB_EJ75N429211805D6A
ID_SERIAL_SHORT=EJ75N429211805D6A
ID_TYPE=disk
ID_WWN=0x5ace42e0903141fd
ID_WWN_WITH_EXTENSION=0x5ace42e0903141fd
MAJOR=8
MINOR=48
SUBSYSTEM=block
TAGS=:systemd:
USEC_INITIALIZED=2730991
```
