### ISSUE TITLE
getdata is not queued, ata error on devices increase unecessarily

### ISSUE THREAD

**Issue by hurricanehrndz** [openmediavault/openmediavault#270]
https://github.com/openmediavault/openmediavault/blob/d14742c27927213378ca20f2f6637a03b92eca06/deb/openmediavault/usr/share/php/openmediavault/system/storage/smartinformation.inc#L143-L164

This command should probably be processed by a command queue so as to avoid simultaneous commands against a device that would put said device in an position to ABRT of one the request.

Please see the following issue within S.M.A.R.T forums
https://sourceforge.net/p/smartmontools/mailman/message/18547229/

There is many who have reported said issue within OMV's own forums:
https://forum.openmediavault.org/index.php/Thread/23386-ATA-Error-Count-increasing-when-reading-smart-status-from-within-omv-GUI/

```
Error 12 occurred at disk power-on lifetime: 145 hours (6 days + 1 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  04 51 0b 00 00 00 00  Error: ABRT

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  b0 d5 01 e1 4f c2 00 08   5d+00:40:09.504  SMART READ LOG
  b0 d6 01 e0 4f c2 00 08   5d+00:40:09.503  SMART WRITE LOG
  b0 d6 01 e0 4f c2 00 08   5d+00:40:09.502  SMART WRITE LOG

Error 11 occurred at disk power-on lifetime: 145 hours (6 days + 1 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  04 51 0b 00 00 00 00  Error: ABRT

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  b0 d5 01 e1 4f c2 00 08   5d+00:38:33.603  SMART READ LOG
  b0 d5 01 e1 4f c2 00 08   5d+00:38:33.603  SMART READ LOG
  b0 d6 01 e0 4f c2 00 08   5d+00:38:33.602  SMART WRITE LOG
  b0 d6 01 e0 4f c2 00 08   5d+00:38:33.601  SMART WRITE LOG
  b0 d5 01 e0 4f c2 00 08   5d+00:38:33.601  SMART READ LOG
```

As you can see from the above smart logs, there seem to be nearly simultaneous `SMART READ LOG`  commands being issued and thus the drive will abrt one and thus increase the ata error count.

**Comment by votdev** [comment]
Maybe it could be easily done by using a semaphore. Will give it a try.

**Comment by hurricanehrndz** [comment]
Thanks for looking into this.
