### ISSUE TITLE
RPi: two routes for ethernet connection

### ISSUE THREAD

**Issue by Felix-Franz** [openmediavault/openmediavault#273]
Just after the installation of omv on the Raspberry Pi 3 B, the `ip r s` command shows following routes:

```
default via 192.168.72.1 dev enxb827eb3716d7 
default via 192.168.72.1 dev enxb827eb3716d7 proto static metric 100 
192.168.72.0/24 dev enxb827eb3716d7 proto kernel scope link src 192.168.72.119 metric 100 
```

Is there a reason for the route `192.168.72.0/24`?
After deleting this route everything seems fine, but after a restart this route will be added again.

This cause an error in the openvpn plugin OpenMediaVault-Plugin-Developers/openmediavault-openvpn#20

**System Infromation**
* Device: Raspberry Pi 3 Model B
* OMV Version: 4.1.17-1 (Arrakis)
* Kernel: Linux 4.14.79-v7+

**Comment by ryecoaaron** [comment]
Personally, I think this belongs in the forum since I think it an RPi only issue that is technically not an official release.

**Comment by votdev** [comment]
Is this an OMV issue or more related by Raspian?

**Comment by ThomasKaiser** [comment]
> Is this an OMV issue or more related to Raspian?

I guess it's neither/nor. The 'related' OpenVPN issue can be solved by ignoring routes to link local subnets (just commented there) and I don't see anything wrong with a net route.

@votdev on the OMV images for ARM devices there are three 'specialities' present regularly causing support efforts (I won't call them 'problems' or 'issues'):

* the @ayufan images for Rock64 and RockPro64 use a file in `/etc/network/interfaces.d/` for eth0
* installations based on Raspbian or Armbian have the `avahi-autoipd` package installed resulting in the device fetching a link local address from the 169.254.0.0/16 range
* networking on the Armbian based images is done by NetworkManager by default  (etc/network/interfaces` empty by intention) which confuses both users and supporters who think Debian's ifupdown mechanism would be the only thing existing
