### ISSUE TITLE
[Request] Don't restart every sharedfolder service on change

### ISSUE THREAD

**Issue by sparx82** [openmediavault/openmediavault#276]
There are many reasons why a shared folder is blocked:
- Running scripts
- Backups
- Open SMB connections
- ...

When I want to change something in the shared folders tab in OMV (e.g. add a new sharedfolder, remove one..), OMV restarts the services for every sharedfolder which doesn't work, as the system cannot unmount a folder when it is being used. But this wouldn't be necessary anyway because except for one specific shared folder which is changed, added or removed, the others are not affected. I have e.g. a backup to a cloud storage which take approx. 2 weeks and during this time I'm not able to change anything in the shared folders which is pretty annoying as shared folders are used everywhere.

My request: Only restart the service of  the specific shared folder which is affected by the change.

**Comment by sparx82** [comment]
Ok, it's only half as bad as the actual change is still executed, but because of the error, the config change message doesn't disappear

**Comment by votdev** [comment]
This is would be a great feature, but can't be done with the current concept of how everthing works in the OMV backend.
