### ISSUE TITLE
OMV_4_Raspberry_Pi_2_3_3Plus.img.xz issue kernel version and modules are not compatable causing NFS to fail.

### ISSUE THREAD

**Issue by roybarnard** [openmediavault/openmediavault#278]
Hi,

I have identified an issue with 'OMV_4_Raspberry_Pi_2_3_3Plus.img.xz' on a raspberrypi 3+.
It appears that the installed kernel and the kernel modules in /lib/modules are not compatible.
I have included as much evidence as I can, but please contact me if you would like me to provide any further information.

Symptoms:
	Can not configure or use NFS.

Example:
	Login to the Web Interface
	Click on 'NFS' under 'Services'
		Click on 'Enable' slider switch
		Click on 'Save'
		Click on 'Apply' to 'The configuration has been changed. You must apply the changes in order for them to take effect.' message
		Click on 'Yes' to 'Do you really want to apply the configuration chnages?' message

	Web Error Message:
		Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin;
		 export LANG=C; systemctl start 'nfs-kernel-server' 2>&1' with exit code '1'
		: A dependency job for nfs-server.service failed. See 'journalctl -xe' for details.

Evidence:
	Extract from 'journal -ex' on recommendation of Web Error Messages:

		.......
		-- Unit proc-fs-nfsd.mount has failed.
		-- 
		-- The result is failed.
		Jan 30 09:42:43 raspberrypi systemd[1]: Dependency failed for NFS Mount Daemon.
		-- Subject: Unit nfs-mountd.service has failed
		-- Defined-By: systemd
		-- Support: https://www.debian.org/support
		-- 
		-- Unit nfs-mountd.service has failed.
		-- 
		-- The result is dependency.
		Jan 30 09:42:43 raspberrypi systemd[1]: Dependency failed for NFS server and services.
		-- Subject: Unit nfs-server.service has failed
		-- Defined-By: systemd
		-- Support: https://www.debian.org/support
		-- 
		-- Unit nfs-server.service has failed.
		-- 
		-- The result is dependency.
		Jan 30 09:42:43 raspberrypi systemd[1]: Dependency failed for NFSv4 ID-name mapping service.
		-- Subject: Unit nfs-idmapd.service has failed
		-- Defined-By: systemd
		-- Support: https://www.debian.org/support
		-- 
		-- Unit nfs-idmapd.service has failed.
		-- 
		-- The result is dependency.
		Jan 30 09:42:43 raspberrypi systemd[1]: nfs-idmapd.service: Job nfs-idmapd.service/start failed with result 'dependency'.
		Jan 30 09:42:43 raspberrypi systemd[1]: nfs-server.service: Job nfs-server.service/start failed with result 'dependency'.
		Jan 30 09:42:43 raspberrypi systemd[1]: nfs-mountd.service: Job nfs-mountd.service/start failed with result 'dependency'.
		Jan 30 09:42:43 raspberrypi systemd[1]: proc-fs-nfsd.mount: Unit entered failed state.
		Jan 30 09:42:43 raspberrypi systemd[1]: Started Preprocess NFS configuration.
		-- Subject: Unit nfs-config.service has finished start-up
		.......

Additional Information:
	
	Extract from 'journalctrl -b <boot-id>'
		..........
		May 31 10:09:46 raspberrypi systemd[1]: Failed to mount NFSD configuration filesystem.
		May 31 10:09:47 raspberrypi systemd[1]: Dependency failed for NFS Mount Daemon.
		May 31 10:09:47 raspberrypi systemd[1]: Dependency failed for NFS server and services.
		May 31 10:09:47 raspberrypi systemd[1]: Dependency failed for NFSv4 ID-name mapping service.
		May 31 10:09:47 raspberrypi systemd[1]: nfs-idmapd.service: Job nfs-idmapd.service/start failed with result 'dependency'.
		May 31 10:09:47 raspberrypi systemd[1]: nfs-server.service: Job nfs-server.service/start failed with result 'dependency'.
		May 31 10:09:47 raspberrypi systemd[1]: nfs-mountd.service: Job nfs-mountd.service/start failed with result 'dependency'.
		May 31 10:09:47 raspberrypi systemd[1]: proc-fs-nfsd.mount: Unit entered failed state.
		May 31 10:09:47 raspberrypi systemd[1]: Started Preprocess NFS configuration.
		..........

	Output from 'grep "modprobe" /var/log/syslog'

		May 31 10:01:15 raspberrypi sh[1957]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.80-v7+/modules.dep.bin'
		May 31 10:01:15 raspberrypi sh[1957]: modprobe: FATAL: Module softdog not found in directory /lib/modules/4.9.80-v7+
		May 31 10:01:16 raspberrypi sh[1963]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.80-v7+/modules.dep.bin'
		May 31 10:01:16 raspberrypi sh[1963]: modprobe: FATAL: Module softdog not found in directory /lib/modules/4.9.80-v7+
		May 31 10:02:50 raspberrypi sh[1077]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.80-v7+/modules.dep.bin'
		May 31 10:02:50 raspberrypi sh[1077]: modprobe: FATAL: Module softdog not found in directory /lib/modules/4.9.80-v7+
		May 31 10:02:50 raspberrypi sh[1081]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.80-v7+/modules.dep.bin'
		May 31 10:02:50 raspberrypi sh[1081]: modprobe: FATAL: Module softdog not found in directory /lib/modules/4.9.80-v7+

	Output from 'uname -r'

		4.9.80-v7+

	Output from 'ls -lh /lib/modules'

		total 4.0K
		drwxr-xr-x 3 root root 4.0K May 31 09:59 4.14.47-rockchip

	Output from 'lsmod'
		Module                  Size  Used by

	Output from 'omv-initsystem'

		/boot/initrd.img-4.14.47-rockchip does not exist. Cannot update.

Synopsis:
	The running kernel version does not match the installed kernel modules.
	This will cause other kernel issues, I have not investigated but expect iptables firewalling would not work.

Rectification:

	login as root
		apt-get install --reinstall --yes raspberrypi-bootloader raspberrypi-kernel
		apt-get purge --yes linux-image-next-rockchip
		reboot

	Output from 'uname -r'

		4.14.79-v7+

	Output from 'ls -lh /lib/modules'

		total 4.0K
		drwxr-xr-x 3 root root 4.0K Jan 30 11:06 4.14.79+
		drwxr-xr-x 3 root root 4.0K Jan 30 11:06 4.14.79-v7+

	Output from 'lsmod'

		Module                  Size  Used by
		lzo                    16384  16
		lzo_compress           16384  1 lzo
		zram                   28672  4
		zsmalloc               24576  1 zram
		brcmfmac              307200  0
		brcmutil               16384  1 brcmfmac
		joydev                 20480  0
		snd_bcm2835            32768  0
		evdev                  24576  2
		cfg80211              573440  1 brcmfmac
		snd_pcm                98304  1 snd_bcm2835
		snd_timer              32768  1 snd_pcm
		rfkill                 28672  2 cfg80211
		snd                    69632  3 snd_timer,snd_bcm2835,snd_pcm
		uio_pdrv_genirq        16384  0
		uio                    20480  1 uio_pdrv_genirq
		fixed                  16384  0
		sg                     28672  0
		ax88179_178a           24576  0
		r8152                  53248  0
		nfsd                  299008  13
		ip_tables              24576  0
		x_tables               32768  1 ip_tables
		ipv6                  425984  70

Result:
	Now I can configure and use NFS from the Web interface.

Many Thanks,
roy_barnard@yahoo.co.uk

**Comment by votdev** [comment]
Thanks for investigating this issue, but the OMV project can not do anything here. Because of such issues the OMV project has decided NOT to maintain kernel packages, instead the upstream packages are used. Please report this issue in the Raspian or Debian forum.

**Comment by ThomasKaiser** [comment]
Where you most probably downloaded my image https://sourceforge.net/projects/openmediavault/files/Raspberry%20Pi%20images/ there's a file called `readme.txt`. This has been written for a reason.

In there is explained what happens at first boot and why Internet connection is required. You're on kernel 4.9 which is an indication you missed `readme.txt`. Simply start over from scratch, let the OMV installation do its housekeeping at first boot and you end up on kernel 4.14 automagically and no problems whatsoever.
