### ISSUE TITLE
Total/average Uptime

### ISSUE THREAD

**Issue by jonathanmmm** [openmediavault/openmediavault#281]
Hi OMV Team,

I see the great graphs with CPU usage and so on.

I am using autoshutdown to hibernate the system.

Is there a way to see e.g. average uptime (hibernate excluded) in the web gui?
Or is this somehow planned?

Many are using probably autoshutdown and so you can see how many hours the system is really on and drawing Power.
You could also see on which day the machine was running more or if the demand got bigger.

I am switching the machine on with WOL through a Webpage on a Raspberry Pi.
(If somehow wants to know, it is also from GitHub).

Thank You for your Help :)

**Comment by votdev** [comment]
- https://collectd.org/wiki/index.php/Plugin:Uptime
- http://hosting.pilsfree.net/cacti/graph.php?action=properties&local_graph_id=928&rra_id=0&view_type=tree&graph_start=1402160547&graph_end=1402246947
