### ISSUE TITLE
Installation issue with ryzen 2200g

### ISSUE THREAD

**Issue by Agraphie** [openmediavault/openmediavault#289]
Hi there,

I have a ryzen 2200g and I can't run the installation properly. As soon as I select "Install" in the menu, everything afterwards becomes fractured/glitched and you can't read anything on the screen. This seems to be a driver issue. Is there a way to resolve this?

**Comment by votdev** [comment]
Use the latest Debian 9 netinst CD and install OMV manually as suggested in the [forum](https://forum.openmediavault.org/index.php/Thread/21234-Install-OMV4-on-Debian-9-Stretch/).
