### ISSUE TITLE
hash sum mismatch error

### ISSUE THREAD

**Issue by Xuyuanp** [openmediavault/openmediavault#295]
`apt-get update` got an error

```
Get:7 http://59.80.44.99/packages.openmediavault.org/public arrakis/main amd64 Packages [6,214 B]
Err:7 http://59.80.44.99/packages.openmediavault.org/public arrakis/main amd64 Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:6214 [weak]
   - SHA256:4cfe6170065f088eb66fc228882d39f3bf01801bf10cce2b268c485f96cb882e
   - SHA1:e82a6d601471a878a4aa1dc00736c827def047e5 [weak]
   - MD5Sum:f767d0184ea632f85918663fe66d6b90 [weak]
  Hashes of received file:
   - SHA256:e1f26198b3debc373a6859a70cd9593c04e45846203c4345d8525e916fe45c68
   - SHA1:40918beed8b705ce7a51676a7c3f3ca3b7bbdf00 [weak]
   - MD5Sum:b45ea01417a8073d53f6f1783d5558d1 [weak]
   - Filesize:6220 [weak]
  Last modification reported: Mon, 04 Feb 2019 11:06:24 +0000
  Release file created at: Sat, 09 Feb 2019 10:10:09 +0000
Fetched 19.0 kB in 1s (10.9 kB/s)
```

**Comment by votdev** [comment]
I can not reproduce this.

**Comment by loveboylion** [comment]
Same issue here 
Get:13 http://packages.openmediavault.org/public arrakis/main amd64 Packages [6,220 B]
Err:13 http://packages.openmediavault.org/public arrakis/main amd64 Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:6220 [weak]
   - SHA256:e1f26198b3debc373a6859a70cd9593c04e45846203c4345d8525e916fe45c68
   - SHA1:40918beed8b705ce7a51676a7c3f3ca3b7bbdf00 [weak]
   - MD5Sum:b45ea01417a8073d53f6f1783d5558d1 [weak]
  Hashes of received file:
   - SHA256:4cfe6170065f088eb66fc228882d39f3bf01801bf10cce2b268c485f96cb882e
   - SHA1:e82a6d601471a878a4aa1dc00736c827def047e5 [weak]
   - MD5Sum:f767d0184ea632f85918663fe66d6b90 [weak]
   - Filesize:6214 [weak]
  Last modification reported: Sat, 09 Feb 2019 10:10:09 +0000
  Release file created at: Mon, 04 Feb 2019 11:06:24 +0000

**Comment by votdev** [comment]
Repo has been re-indexed.
