### ISSUE TITLE
TypeError: unorderable types: int() < str()

### ISSUE THREAD

**Issue by fransvanberckel** [openmediavault/openmediavault#297]
While doing this some times Debian # apt-get upgrade does error ...

Get:2 http://packages.openmediavault.org/public usul/main amd64 openmediavault all 5.0-1 [1,931 kB]

Preparing to unpack .../7-openmediavault_5.0-1_all.deb ...
Unpacking openmediavault (5.0-1) over (5.0-1) ..

Setting up openmediavault (5.0-1) ...
Creating configuration database ...
Migrating configuration database ...
Traceback (most recent call last):
  File "/usr/sbin/omv-confdbadm", line 74, in <module>
    sys.exit(main())
  File "/usr/sbin/omv-confdbadm", line 70, in main
    return cmd_inst.execute(*sys.argv)
  File "/usr/share/openmediavault/confdbadm/commands.d/migrate.py", line 76, in execute
    if LooseVersion(parts[1]) < LooseVersion(cmd_args.version):
  File "/usr/lib/python3.5/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.5/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: unorderable types: int() < str()
dpkg: error processing package openmediavault (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Errors were encountered while processing:
 openmediavault
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by votdev** [comment]
How can we reproduce this? Did you upgrade OMV4 to OMV5? If yes, this is not supported at the moment.

**Comment by votdev** [comment]
Please post the output of ``ls -alh /usr/share/openmediavault/confdb/migrations.d``.

**Comment by fransvanberckel** [comment]
Preparing to unpack .../7-openmediavault_5.0-1_all.deb ...
Unpacking openmediavault (5.0-1) over (5.0-1) ..

**Comment by fransvanberckel** [comment]
The machine is off-line now. I will turn it on tomorrow, okay, to check ls.
