### ISSUE TITLE
Auto remove older kernels

### ISSUE THREAD

**Issue by donhwy** [openmediavault/openmediavault#299]
I see every once in a while someone with a full root drive in the forums. I think some of it may be old kernel versions. Some of my vm's seem to take care of old versions automatically. Would be great if OMV did also. 

root@OMV4:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            443M     0  443M   0% /dev
tmpfs            93M  3.1M   90M   4% /run
/dev/sda1       7.9G  3.9G  3.6G  53% /
tmpfs           462M     0  462M   0% /dev/shm
...

root@OMV4:~# dpkg -l |grep image |grep ii
ii  libnginx-mod-http-image-filter            1.10.3-1+deb9u2                amd64        HTTP image filter module for Nginx
ii  libwebp6:amd64                            0.5.2-1                        amd64        Lossy compression of digital photographic images.
ii  linux-base                                4.5                            all          Linux image base package
ii  linux-image-4.15.0-0.bpo.2-amd64          4.15.11-1~bpo9+1               amd64        Linux 4.15 for 64-bit PCs
ii  linux-image-4.16.0-0.bpo.1-amd64          4.16.5-1~bpo9+1                amd64        Linux 4.16 for 64-bit PCs
ii  linux-image-4.16.0-0.bpo.2-amd64          4.16.16-2~bpo9+1               amd64        Linux 4.16 for 64-bit PCs
ii  linux-image-4.17.0-0.bpo.1-amd64          4.17.8-1~bpo9+1                amd64        Linux 4.17 for 64-bit PCs
ii  linux-image-4.17.0-0.bpo.3-amd64          4.17.17-1~bpo9+1               amd64        Linux 4.17 for 64-bit PCs
ii  linux-image-4.18.0-0.bpo.3-amd64          4.18.20-2~bpo9+1               amd64        Linux 4.18 for 64-bit PCs
ii  linux-image-4.19.0-0.bpo.1-amd64-unsigned 4.19.12-1~bpo9+1               amd64        Linux 4.19 for 64-bit PCs
ii  linux-image-4.19.0-0.bpo.2-amd64          4.19.16-1~bpo9+1               amd64        Linux 4.19 for 64-bit PCs (signed)
ii  linux-image-amd64                         4.19+102~bpo9+1                amd64        Linux for 64-bit PCs (meta-package)

After removing all but two older versions.

root@OMV4:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            443M     0  443M   0% /dev
tmpfs            93M  3.1M   90M   4% /run
/dev/sda1       7.9G  2.2G  5.3G  30% /
tmpfs           462M     0  462M   0% /dev/shm
...

Thanks

**Comment by votdev** [comment]
Hmm, you're right, but this is the same issue as with auto-update packages. OMV does not install packages unintended because it may break a system in a bad case. Removing kernels may remove the possibility to boot the system if the latest kernel does not work correct. Because of that the admin should do such actions, because in this case it's his fault.
I will close this issue because OMV will not implement such a feature because of the reasons and worries mentioned above.
