### ISSUE TITLE
nginx installed with wrong configuration RPI3

### ISSUE THREAD

**Issue by alejandrofm** [openmediavault/openmediavault#300]
I made a fresh install of OMV, last RPI3 version, had to edit sites-available and comment the line that specifies the port, without that comment nginx -t throws a configuration error and doesn´t start.

**Comment by votdev** [comment]
What was the error? Is IPv6 kernel module enabled? Does your interfaces have IPv6 link local addresses?

**Comment by alejandrofm** [comment]
The boot error was:
failed to start a high performance web server.

when I executed nginx -t it told me that it were a configuration error.

Ipv6 is enabled on my router buy I never use it, I have a windows with it disabled, a linux with it enabled, I use ipv4 in my LAN, in any case OMV must be ready for ipv4 and/or ipv6 connection I think.

Thank you!

**Comment by votdev** [comment]
> when I executed nginx -t it told me that it were a configuration error.

Sorry, this comment does not really help. We need the exact error message.

Please post the output of ``cat /proc/net/if_inet6``.

**Comment by alejandrofm** [comment]
Will see if there's anything remaining in the log. (already solved it so I don´t receive the error anymore)
But if I am the only one reporting this it must be something about my rpi o lan config.
Thank you

**Comment by ThomasKaiser** [comment]
> failed to start a high performance web server.

@votdev usually this is an RPi user not following the readme.txt at download location. OMV installation needs to finalize on first boot with the RPi image and if there's no Internet connection then this will fail and as such OMV won't be reachable with this error message shown in console.
