### ISSUE TITLE
omv autoshutdown ist not working on debian 9

### ISSUE THREAD

**Issue by gersel** [openmediavault/openmediavault#303]

**Comment by votdev** [comment]
Please report this issue here: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by gersel** [comment]
1. autoshutdown.sh contains error: line 1179 (NIC list) : eth0 will be not used anymore in Debian 9,
    new naming scheme!  possible detect existent NICs with "ifquery --list"
2. ifconfig command is outdated, use "ip addr show" furthermore
