### ISSUE TITLE
Fresh system, web panel: after installation creation of file systems on the both data disks is impossible

### ISSUE THREAD

**Issue by Wikinaut** [openmediavault/openmediavault#311]
I installed OMV on a 128GB SSD and wanted to create a RAID1 array of the two other empty 1TB HDDs.

After obtaining web access (the network was not detected in the first boots), I cannot add new file systems, pls. look what the GUI says:

``` 
Bitte warten, das Dateisystem wird erstellt ...

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; mkfs -V -t ext4 -b 4096 -m 0 -E lazy_itable_init=0,lazy_journal_init=0 -O 64bit -L 'D' '/dev/sdb1' 2>&1' with exit code '1': mke2fs 1.44.5 (15-Dec-2018) Found a dos partition table in /dev/sdb1 Proceed anyway? (y,N)

Fehler #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; mkfs -V -t ext4 -b 4096 -m 0 -E lazy_itable_init=0,lazy_journal_init=0 -O 64bit -L 'D' '/dev/sdb1' 2>&1' with exit code '1': mke2fs 1.44.5 (15-Dec-2018)
Found a dos partition table in /dev/sdb1
Proceed anyway? (y,N) in /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc:642

****** here, there is no chance to say "y"(yes) in the web interface !!! ********
****** I can only show the details or close the error pop up ******


Stack trace:
#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(536): OMVRpcServiceFileSystemMgmt->{closure}('/tmp/bgstatusf9...', '/tmp/bgoutputgc...')
#1 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(658): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure), NULL, Object(Closure))
#2 [internal function]: OMVRpcServiceFileSystemMgmt->create(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('create', Array, Array)
#5 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('FileSystemMgmt', 'create', Array, Array, 1)
#6 {main}
```

**Comment by ryecoaaron** [comment]
You need to wipe the disks in the Physical Disks tab first.

**Comment by Wikinaut** [comment]
Question 1:
Should be caught in the code.


Question 2:
When wiping, I see this insane display on a clean Ubuntu/Linuxmint system:

![grafik](https://user-images.githubusercontent.com/1151915/53660712-cfa80c00-3c5e-11e9-8337-a924c1c725ab.png)

**Comment by Wikinaut** [comment]
and then
![grafik](https://user-images.githubusercontent.com/1151915/53660826-1ac21f00-3c5f-11e9-973d-cbb90536afbb.png)

**Comment by Wikinaut** [comment]
Is Openmediavault a buggy beta software? Just asking for a friend.

**Comment by Wikinaut** [comment]
And then, after mounting, I cannot create a RAID1
![grafik](https://user-images.githubusercontent.com/1151915/53661190-121e1880-3c60-11e9-928b-ad99034455c1.png)

What is going on here? Giving up.

**Comment by ryecoaaron** [comment]
The display looks weird because it is interactive output that is trying to displayed from a text file.  Not an easy way to fix that.

Buggy software?  The read file error was fixed a long time ago.  Since this is a fresh install, did you fully the update the system first?

The disks didn't wipe properly.  If you can't invest an hour into this, then you should probably buy a commercial NAS.  They don't have bugs...

**Comment by Wikinaut** [comment]
Regarding the disks: in another system I used gparted to delete the partitions and changed from msdos to gpt, apparently, this was not enough. BTW: these data disks were formerly used as RAID-1 disks.

**Comment by Wikinaut** [comment]
The "Failed to read file '/tmp/...." should be also be caught, I mean, what's the reason to have this for every disk you wipe?

**Comment by ryecoaaron** [comment]
leaving gpt on there is not needed.  wipefs -a /dev/sdX is what you want.

The failed to read /tmp error has been fixed.  Update the packages in the Updates tab.

**Comment by Wikinaut** [comment]
@ryecoaaron I did not know that I first have to update a fresh installation, expected, to see a notification "Updates available". I give now OMV a second chance.

**Comment by ryecoaaron** [comment]
Unfortunately, creating the ISO takes a lot of time.  So, they aren't updated very often.  But, installs can easily be brought up to date.

**Comment by Wikinaut** [comment]
@ryecoaaron I set up the disk, created filesystems, but why are no disks listed, so I cannot set up a RAID?
![grafik](https://user-images.githubusercontent.com/1151915/53667972-de98b980-3c72-11e9-97cd-c8c626914f42.png)

**Comment by ryecoaaron** [comment]
You can't have filesystems on disks that are to be used in an array.  This isn't an OMV rule.  You need to wipe those filesystems (unmount them if you mounted them).  Then you should be able to create an array.

**Comment by Wikinaut** [comment]
okay, thanks, works

**Comment by votdev** [comment]
If the devices are connected via USB then they are not displayed. Thus drives are causing too much errors.

**Comment by votdev** [comment]
> and then
> ![grafik](https://user-images.githubusercontent.com/1151915/53660826-1ac21f00-3c5f-11e9-973d-cbb90536afbb.png)

This is an indication that you do not have installed the latest version. Please update your system.

**Comment by Wikinaut** [comment]
@votdev Hi, yes, this was the reason. It was not clear that I have to update before first use of OMV. I hope, a newer version checks after installation and informs the user.

My OMV-based NAS is working now (RAID-1). Thanks to everyone.
