### ISSUE TITLE
Feature Request: Additional BTRFS support in OMV5

### ISSUE THREAD

**Issue by flmaxey** [openmediavault/openmediavault#312]
Request additional BTRFS feature support, in OMV5, that equates to some of the features currently available in the ZFS plugin, that supports ZFS.

If sub-volume creation, snapshots, and other BTRFS features are available in the GUI, users may make use them and provide meaningful feedback.

**Comment by votdev** [comment]
IMHO snapshots make only sense with the proposal #101 where shared folders are based on sub-folders. In most cases users create shared folders with sense because they keep special data like photos, videos and so on. It does not make sense to snapshot a whole device that that contains all mixed data. For example if you delete important photos, then you only want to role back the photos shared folder, and not photos, video, documents and so on, because in this case you loose all other data that you won't see too be restored to an older state.

**Comment by flmaxey** [comment]
Understood.
I ran into the same consideration when setting up ZFS;  snapshot the entire pool or segregate specific data types into child file systems, where individual snapshot intervals and settings where possible. And, more importantly, rolling back or creating a clone would apply only to a file system sub-set, not the entire pool.
It would have been nice to look at BTRFS and ZFS side by side, for comparison, but (not being a Dev) I have no idea of the work necessary to make that possible.
Thanks for taking a look.

**Comment by PelleHanses** [comment]
If you want to restore some files from a previous snapshot, you can mount the snapshot under a different name and then just copy the desired files. You do not need to mount the snapshot over the original. This is the case with ZFS anyway and I can't imagine it being handled differently in BTRFS.
Therefore, saving one or all directories in a snapshot doesn't matter much, except you may not want to save unnecessary data in a snapshot.

**Comment by ulinuxp** [comment]
#629 would be great if the btrfs snapshots can also be served with samba.

**Comment by MarcS1975** [comment]
Hi - I saw this conversation and was wondering what the developers update view is on a BTRFS plugin in the OMV gui. Would be nice to have basic management like with ZFS inside the gui. Any thoughts?

**Comment by claell** [comment]
@votdev I don't think I agree with your statement. I think this makes sense at this state already. At least when I correctly understand this proposal. I think it is requesting support for BTRFS features in OVM that are supported for ZFS in OVM.

Those features most likely already make sense (else why would they be availbale for ZFS in the first place).

**Comment by mi-hol** [comment]
#101

**Comment by mi-hol** [comment]
there is no version label but "planned" label.
Will this be worked on for 6.x oder 7.x ?

**Comment by mi-hol** [comment]
#1159 is related
