### ISSUE TITLE
Add UPS client (netclient) support in NUT plugin

### ISSUE THREAD

**Issue by jjakob** [openmediavault/openmediavault#318]
The current openmediavault-nut plugin doesn't support nut's netclient mode, the only way to get nut working in netclient mode is to not install the plugin and install nut manually.
As there are many cases in which another server is already set up as a nut server, I think it would be a wanted feature.

**Comment by votdev** [comment]
Don't expect that this will be implemented in near future, there are other thing with higher priority.

**Comment by ryecoaaron** [comment]
Helpful post - https://forum.openmediavault.org/index.php/Thread/25558-Network-UPS-Tools-to-second-Openmediavault-server/?postID=192648#post192648

**Comment by ne20002** [comment]
I second that. Seems to be an useful feature.

**Comment by rareshornet** [comment]
this would be nice

**Comment by daniel0076** [comment]
Hi, 
Is it ok for the community users to help develop the plugin?
I will be willing to implement this feature.

**Comment by ryecoaaron** [comment]
@daniel0076 Yes, pull requests are accepted.  Here is the license agreement - https://cla-assistant.io/openmediavault/openmediavault

**Comment by votdev** [comment]
> Hi,
> Is it ok for the community users to help develop the plugin? (any guidelines or CoC?)
> I will be willing to try to implement this feature.

PRs are welcome. Please check https://openmediavault.readthedocs.io/en/latest/development/index.html for more details how to contribute.

**Comment by daniel0076** [comment]
Thanks a lot for the information.
Will soon get my hands on :)
