### ISSUE TITLE
OMV5 Install on Debian 10 error

### ISSUE THREAD

**Issue by adoris123** [openmediavault/openmediavault#322]
I try to install OMV5 to fresh Debian 10 installation and encounter to next error:

[
CRITICAL] Rendering SLS 'base:omv.setup.fstab.default' failed: Jinja error: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 393, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 60, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/omv_utils.py", line 110, in is_block_device
    return openmediavault.device.is_block_device(path)
  File "/usr/lib/python3/dist-packages/openmediavault/device/utils.py", line 36, in is_block_device
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

```
; line 60

---
[...]
#   "dump": "0",
#   "fstype": "ext4"
# }
{% set root_fstab_entry = fstab_entries['/'] %}

{% if nonrot_options | difference(root_fstab_entry.opts) | length > 0 and    <======================
      salt['omv_utils.is_block_device'](parent_root_fs_device) and
      not salt['omv_utils.is_rotational'](parent_root_fs_device) %}

update_root_fstab_entry:
  module.run:
[...]
---
´´´

**Comment by votdev** [comment]
Can you please execute the following commands and post the results.
```
root@omv5box:/home/vagrant# python3
Python 3.7.2+ (default, Feb  2 2019, 14:31:48) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openmediavault.fs
>>> root_fs_device = openmediavault.fs.Filesystem.from_mount_point('/')
>>> print(root_fs_device.device_file)
/dev/sda3
>>> fs = openmediavault.fs.Filesystem(root_fs_device.device_file)
>>> parent = fs.get_parent_device_file()
>>> print(parent)
/dev/sda
>>> 
```

**Comment by kanatanssi** [comment]
Heya,
Got the same error during install. Got the following output with the commands you gave there:
```
root@varasto:/# python3
Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openmediavault.fs
>>> root_fs_device = openmediavault.fs.Filesystem.from_mount_point('/')
>>> print(root_fs_device.device_file)
/dev/dm-0
>>> fs = openmediavault.fs.Filesystem(root_fs_device.device_file)
>>> parent = fs.get_parent_device_file()
>>> print(parent)
None
>>> 
```
