### ISSUE TITLE
Typo in the "S.M.A.R.T Information" interface

### ISSUE THREAD

**Issue by AdiProdan** [openmediavault/openmediavault#324]
In the OMV web interface, under Storage > S.M.A.R.T. > Devices > Information > Attributes, there is a column called "Treshold", which should most probably be called "Threshold". 
<img width="1210" alt="Screenshot 2019-03-17 at 04 57 13" src="https://user-images.githubusercontent.com/31631549/54484988-743a6880-4871-11e9-89dd-4bfadbac0a7e.png">

**Comment by votdev** [comment]
Fixed in openmediavault 4.1.20.
