### ISSUE TITLE
Favourite group

### ISSUE THREAD

**Issue by Ansem93** [openmediavault/openmediavault#326]
Hi,
I would ask if it's possible to add a favourite group where we can group the most used function of the other groups like shared folders, dockers, dashboard, ecc.
If possible it would also be cool to be able to select the order of the tabs.

**Comment by Ansem93** [comment]
Hi,
since I read that for OMV6 is planned a new UI (BTW it looks great from the screenshot!) do you think it will be possible to implement this feature?

**Comment by votdev** [comment]
I think this can be easily implemented via plugin then.

**Comment by Ansem93** [comment]
Is it possible to add a new group (like System,Storage,Services, ecc.) with a plugin?

**Comment by votdev** [comment]
You can do that in OMV3 to OMV5.
