### ISSUE TITLE
optional support for turning ntlm support bacj on.

### ISSUE THREAD

**Issue by rmalchow** [openmediavault/openmediavault#329]
this is a bit stupid, since ntlm truly isnt a very good thing. however, there are actual usecases for this. for example: the sonos multiroom speaker system still needs it (this is my personal usecase). it would be a matter of addind one line to `10global` and having a checkbox (ideally with a big fat warning) in the UI. i had to do this a couple of times, when my local changes where overwritten by some update, and it really isnt a big deal if this is not supported, at least for me. but other people might have the same or similar problems.

**Comment by rmalchow** [comment]
specifically, i add this:

`  -o "ntlm auth = yes" -n \`

to `/usr/share/openmediavault/mkconf/samba.d/10global` ... this would probably have to be changed to something like:

`    -o "ntlm auth = ${OMV_SAMBA_LEGACY_NTLM}" -n \ `

... if i had any idea how to fiddle with the UI, i would probably do a pull request.

**Comment by ryecoaaron** [comment]
Just add ntlm auth = yes to the extra options box on the settings tab of the smb plugin.

**Comment by rmalchow** [comment]
true. good enough, i guess
