### ISSUE TITLE
Feature request: make docker packages easier to install, setup and use like the current plugins

### ISSUE THREAD

**Issue by Samuel12321** [openmediavault/openmediavault#330]
Currently docker packages are not very user frendly, especially if you have little or no experience using docker packages or are a less technically minded person(general consumer). With many plugins going to cease development and become docker apps in the future due to their many advantages, an easier to use more user friendly system is needed.

**Comment by ryecoaaron** [comment]
This really should be here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-docker-gui/issues

That said, it would be difficult to do this with a lot of dockers.  Have you watched the long list of videos about setting up dockers on OMV?  https://forum.openmediavault.org/index.php/Thread/23005-Installation-and-Setup-Videos-Beginning-Intermediate-and-Advanced/

**Comment by Samuel12321** [comment]
Ok will Create issue there, thanks for the suggestion

**Comment by votdev** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-docker-gui/issues/79
