### ISSUE TITLE
Assign static ip to a LACP ( 802.3ad) Bond

### ISSUE THREAD

**Issue by Adefx** [openmediavault/openmediavault#331]
When you create a LACP ( 802.3ad) Bond it's impossible to assign a static IP ( DHCP work )

Complete description in this forum topic: 
https://forum.openmediavault.org/index.php/Thread/23127-Apply-config-loop-failure-bonded-network-interfaces/?postID=200043#post200090

**Comment by votdev** [comment]
My experience is that static IP configuration in Debian is buggy. I didn't find a problem in the configuration OMV4 generates for static IP, so i'm currently out of ideas.

My experiences with OMV5 is much better, but here the network configuration is completely done via systemd.
