### ISSUE TITLE
Bug: Removing a plugin doesnt remove it from the services menu

### ISSUE THREAD

**Issue by Samuel12321** [openmediavault/openmediavault#333]

**Comment by ryecoaaron** [comment]
It isn't a bug.  It is your browser cache.  Read problem #1 - https://forum.openmediavault.org/index.php/Thread/21269-Solutions-to-common-problems/

**Comment by Samuel12321** [comment]
ok thanks

**Comment by Samuel12321** [comment]
Should OMV Automatically suggest clearing cache or clear cache in this situation?

**Comment by Samuel12321** [comment]
Have created  #336 to address underlying issue
