### ISSUE TITLE
MTU setting issue

### ISSUE THREAD

**Issue by donhwy** [openmediavault/openmediavault#334]
I set mtu to 9000 in the webui, saved and applied. Ran
`root@OMV4:~# netstat -i
Kernel Interface table
Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
ens18     1500     4915      0      0 0          3749      0      0      0 BMRU
lo       65536       21      0      0 0            21      0      0      0 LRU
root@OMV4:~#
Rebooted and still get the same as above. The webui shows 9000.

Thanks`

**Comment by votdev** [comment]
The network interface page/table in WebUI shows the config values, not the real values.
