### ISSUE TITLE
Just installed some plugins from omv-extras.org stable and now I’m getting some errors that seem to be related to mounted directories and/or permissions.

### ISSUE THREAD

**Issue by GNUBro** [openmediavault/openmediavault#335]
While reloading plugins:
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; apt-get update 2>&1' with exit code '100': Get:1 file:/var/cache/openmediavault/archives InRelease Ign:1 file:/var/cache/openmediavault/archives InRelease Get:2 file:/var/cache/openmediavault/archives Release Ign:2 file:/var/cache/openmediavault/archives Release Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Get:3 file:/var/cache/openmediavault/archives Packages [1100 B] Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Hit:5 http://linux.teamviewer.com/deb stable InRelease Hit:7 https://downloads.plex.tv/repo/deb ./public InRelease Ign:8 http://ftp.us.debian.org/debian stretch InRelease Hit:9 https://openmediavault.github.io/packages arrakis InRelease Get:10 http://ftp.us.debian.org/debian stretch-updates InRelease [91.0 kB] Get:6 http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease [91.9 kB] Hit:11 https://download.docker.com/linux/debian stretch InRelease Hit:12 http://apt.syncthing.net syncthing InRelease Hit:13 http://security.debian.org/debian-security stretch/updates InRelease Hit:14 http://packages.openmediavault.org/public arrakis InRelease Hit:15 http://ftp.us.debian.org/debian stretch Release Ign:16 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch InRelease Ign:17 http://hwraid.le-vert.net/debian stretch InRelease Ign:18 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-plex stretch InRelease Hit:19 http://packages.openmediavault.org/public arrakis-proposed InRelease Ign:20 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-sync stretch InRelease Hit:21 http://hwraid.le-vert.net/debian stretch Release Ign:22 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch InRelease Ign:23 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-docker stretch InRelease Ign:24 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-teamviewer stretch InRelease Get:25 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch Release [4389 B] Hit:25 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch Release Get:29 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-plex stretch Release [3540 B] Hit:29 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-plex stretch Release Get:31 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-sync stretch Release [3540 B] Hit:31 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-sync stretch Release Ign:33 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch Release Get:34 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-docker stretch Release [3540 B] Hit:34 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-docker stretch Release Get:36 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-teamviewer stretch Release [2691 B] Hit:36 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-teamviewer stretch Release Ign:38 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main amd64 Packages Ign:39 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main all Packages Ign:40 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main Translation-en Ign:38 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main amd64 Packages Ign:39 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main all Packages Ign:40 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main Translation-en Ign:38 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main amd64 Packages Ign:39 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main all Packages Ign:40 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main Translation-en Ign:38 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main amd64 Packages Ign:39 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main all Packages Ign:40 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main Translation-en Ign:38 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main amd64 Packages Ign:39 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main all Packages Ign:40 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main Translation-en Err:38 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main amd64 Packages 404 Not Found Ign:39 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main all Packages Ign:40 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch/main Translation-en Fetched 183 kB in 4s (44.3 kB/s) Reading package lists... W: The repository 'https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid stretch Release' does not have a Release file. E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/arrakis-hwraid/dists/stretch/main/binary-amd64/Packages 404 Not Found E: Some index files failed to download. They have been ignored, or old ones used instead.
Error #0: OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; apt-get update 2>&1' with exit code '100': Get:1 file:/var/cache/openmediavault/archives InRelease Ign:1 file:/var/cache/openmediavault/archives InRelease Get:2 file:/var/cache/openmediavault/archives Release Ign:2 file:/var/cache/openmediavault/archives Release Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Translation-en Ign:4 file:/var/cache/openmediavault/archives Translation-en Get:3 file:/var/cache/openmediavault/archives

While doing RAID: (What I was able to copy, as it keeps spitting out the same error)
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; zfs list -H -o name,mountpoint -t filesystem' with exit code '1':
Error #0
OMV\ExecException: Failed to execute command ’
Stack trace:
#1 user/share/omvzfs/Utilis.php(432): OMV/System

Can someone help me solve this please?
Thank you for your help.

**Comment by ryecoaaron** [comment]
This should be two issues.  The first should be [here](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues) but you really just need to disable the hwraid repo since there are no plugins in it.

The second belongs [here](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/issues) but really should be posted in the forum first since it is probably a configuration error.

**Comment by GNUBro** [comment]
Well thees aren't developer issues and I suspect that the issues are related... since it only added a few new plugins. I can remove the plugin from and remove the hwraid raid repo, but it looks like a permission issue as it effects all the repos from omv-extras.org. Unless the issue requires remounting some of the directories.

**Comment by ryecoaaron** [comment]
They aren't related.  The omv-extras plugin itself does nothing that would run into a permissions issue or mounting of directories.  The fact that you only see a few plugins means apt-get update is not running properly.

**Comment by GNUBro** [comment]
To clarify, I said only installed a few new plugins, not can only see a few plugins. I had this running for a few months without any issue and did regular updates with most of the plugins installed, the only plugins I installed recently (just before the problems happened) were Plex, TeamView and a backup utility. I’ll just reinstall and slowly add back in the plugins with a reload, until it breaks again, reinstall again without the offending plugin and find an alternative... if I need it. I’ll let you know what one it was.

**Comment by GNUBro** [comment]
After a fresh install, upgrading, distro upgrading, reinstalling the plugins, resetting up RAID 1, and going through all my settings again; the only issue was an error during update:

Processing triggers for openmediavault (4.1.21-1) ...
Updating locale files ...
Updating file permissions ...
Purging internal cache ...
Restarting engine daemon ...
Cannot create socket to [localhost]:2812 -- Connection refused
Processing triggers for systemd (232-25+deb9u10) ...
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f69599307b8>
Traceback (most recent call last):
File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f69599307b8>
Traceback (most recent call last):
File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

But I found others with the same error, so I'm sure I will figure it out... if I care enough to do so, as it isn't causing any issues with anything so fare.

**Comment by ryecoaaron** [comment]
There are lots of threads about that on the forum - here is one - https://forum.openmediavault.org/index.php/Thread/19658-Upgrade-Debian-9-and-4-x/?pageNo=1
