### ISSUE TITLE
OMV Should Automatically suggest clearing cache or clear cache in situations where it is required

### ISSUE THREAD

**Issue by Samuel12321** [openmediavault/openmediavault#336]
See:
#333 
#75 

It is a common re-occuring problem that needs a better solution.

> We have meta cache control already but set it to 14 days or something else to reduce load on small devices.  (votdev)

Yes i agree with reducing load on smaller devices, but perhaps it should be overidden if a significant change occurs such as the uninstallation of a plugin?

**Comment by votdev** [comment]
The cache is automatically cleared after package installation and update. If this does not occur then the plugin is not implemented correctly.

**Comment by votdev** [comment]
The UI reloads the page when you install or uninstall packages via UI.

**Comment by Samuel12321** [comment]
Is the cache cleared when you uninstall a packege

> The cache is automatically cleared after package installation and update. If this does not occur then the plugin is not implemented correctly.

**Comment by ryecoaaron** [comment]
What plugin were you removing when this happened?  I'm pretty sure all of the plugins implement their uninstall properly but I will confirm this.

**Comment by Samuel12321** [comment]
Plex

**Comment by Samuel12321** [comment]
@ryecoaaron any update?

**Comment by ryecoaaron** [comment]
I guess Volker is correct.  Quite a few of the plugins including plex execute dpkg-trigger update-fixperms (which clears the cache) on installation but don't execute it on removal.  I will make sure it is in the plugin for OMV 5.x but I'm not going to go update every plugin in OMV 4.x just for this.

**Comment by votdev** [comment]
Should be fixed with https://github.com/openmediavault/openmediavault/commit/018a913d52b875a272fa1561b180e4cf438d7a34.

**Comment by Samuel12321** [comment]
great, thanks
