### ISSUE TITLE
Feature request: active directory integration

### ISSUE THREAD

**Issue by akurzawa** [openmediavault/openmediavault#339]
Hi

Are we able to create plugin or native function to connect omv to domain and use groups and users from Active Directory?

https://www.openmediavault.org/?p=782 - here we have information about active directory, but the info is from 2012, 7 years old... and unfortunaltely still no option to use omv with Active Directory

**Comment by votdev** [comment]
Contributions are welcome

**Comment by akurzawa** [comment]
So long story short there are no developers interested in writing such a functionality for OMV?

**Comment by ryecoaaron** [comment]
Volker and myself are pretty much the only people developing.  There have been a few attempts to write an AD plugin but most OMV users don't have an AD infrastructure (including myself).  So, it is difficult to write it when you have no AD to test against.  If I did write one, it would probably use sssd but I have seen a lot of problems with sssd authing against AD at work (very large AD).

**Comment by votdev** [comment]
I do not use Windows so i have no infrastructure for testing and no need to implement such a plugin. And to be honest, this is a open source project, everyone can contribute, missing functions do not have to be implemented by the main developers itself. It seems to me that the pain is not as big that there will be a volunteer that implements such a plugin.

**Comment by Gremlingroj** [comment]
I am ready to become a plug-in tester, I also really need it for convenience. I have been using OMV for a long time, and it has always been lacking, manual integration through winbind or sssd always goes wrong.

**Comment by Flo3561** [comment]
Any updates on that FR? https://jumpcloud.com/ offers a free LDAP server solution for small organizations/groups with less than 10 accounts. Maybe a good solution for infrastructure testing.

**Comment by mi-hol** [comment]
to be addressed via #1143
