### ISSUE TITLE
Cannot create physical LVM volume

### ISSUE THREAD

**Issue by webcompas** [openmediavault/openmediavault#342]
If I try to create a physical LVM volume I get the following error:
> Invalid RPC response. Please check the syslog for more information.

In the syslog only the following lines are added:
> Apr 23 17:06:45 test-omv5 omv-engined[1276]: PHP Fatal error: Uncaught Error: Call to undefined method OMV\System\Storage\StorageDevice::assertStorageDeviceExists() in /usr/share/openmediavault/engined/rpc/logicalvolumemgmt.inc:187
Apr 23 17:06:45 test-omv5 omv-engined[1276]: Stack trace:
Apr 23 17:06:45 test-omv5 omv-engined[1276]: #0 [internal function]: OMVRpcServiceLogicalVolumeMgmt->createPhysicalVolume(Array, Array)
Apr 23 17:06:45 test-omv5 omv-engined[1276]: #1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
Apr 23 17:06:45 test-omv5 omv-engined[1276]: #2 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('createPhysicalV...', Array, Array)
Apr 23 17:06:45 test-omv5 omv-engined[1276]: #3 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('LogicalVolumeMg...', 'createPhysicalV...', Array, Array, 1)
Apr 23 17:06:45 test-omv5 omv-engined[1276]: #4 {main}
Apr 23 17:06:45 test-omv5 omv-engined[1276]:   thrown in /usr/share/openmediavault/engined/rpc/logicalvolumemgmt.inc on line 187

**Comment by votdev** [comment]
Please reinstall the package.
