### ISSUE TITLE
Approximative size whencreating a new logical volume

### ISSUE THREAD

**Issue by dethegeek** [openmediavault/openmediavault#350]
Hi

I want to create a new logical volume. I can use the slider to set the size I want for my volume, but I cannot set a size by typing a integer in the textbox.

As an example : I try to create a 16GB volume. I cannot move the slider to 16.00 GB 

![image](https://user-images.githubusercontent.com/5788361/56763838-95ad3f00-67a3-11e9-8aa3-24aa0c12d007.png)

If the textbox on the right of the slider can be enabled, users would be able to type the value he wants.

**Comment by votdev** [comment]
The validation of the input is too complicated and finally the volume will never be exactly the size you entered. Don't expect that this will be implemented soon. I mark it as a feature request, maybe someone else will contribute it.

**Comment by Styx13** [comment]
Hello, just a suggestion about a way to potentially implement something that would help with sizing volume with more precision:
In addition to the slider, use the up and down arrow keys (or another combination of keys) to allow small step adjustments.
For example:  up and down would increase/decrease by 0.1 and round it: so 10.13 would become 10.20 when pushing arrow up, then 10.30 pushing arrow up again.)
Left and right arrows would increase/decrease by 1 so 10.20 would become 9.20 when pushing left arrow, then 8.20 if pushing again, .. you get the idea.

This would still prevent user from giving direct input (which I agree can be complex to validate), but this would give the precision that a lot of people are looking for.

@dethegeek a trick to get a big more precision: resize the create a new volume panel to the full width of your screen, this will allow the slider to have a bit more precision.

**Comment by btry** [comment]
Hi

I believe (needs to be verified) that we can get the granularity of the volume group to find the nearest possible value.

Knowing this value gives several options
- a modal submitting the appropriate value
- an auto adjustment to the nearest value (maybe a bit complex from a UX point of view)

Using arrows may be a bit frustrating if the user is far from the value he wants to set.
