### ISSUE TITLE
Feature Request: Improved OMV Control Pannel support for mobile devices

### ISSUE THREAD

**Issue by Samuel12321** [openmediavault/openmediavault#351]
Currently OMV control panel user interface does not work very well at all if viewed on a mobile device, Touch support is very limited and windows do not resize well.
Just tried to quickly change a setting on my phone, but was unable to.

Tested on chrome and samsung internet on android device with 5" display

**Comment by votdev** [comment]
On touch devices all windows/dialogs are sized to the max display size, resizing is disabled. I haven’t tested it since some time but it should work. Please note that ExtJS is really old and does not support touch devices very well.

**Comment by mi-hol** [comment]
@vordev, will this improve with version 6.x?

**Comment by votdev** [comment]
Version 6.x will address this issue.
