### ISSUE TITLE
[Feature request] Add option to disable relay host in email notification settings

### ISSUE THREAD

**Issue by jjakob** [openmediavault/openmediavault#354]
Currently settings do not allow a configuration with no relayhost. This configuration is commonly used where the system is set up at a remote location and sends mail to multiple email domains directly.
Either:
a) allow empty "SMTP server" field and add a note that specifying no SMTP server will send out emails directly. Renaming SMTP server/port to Relay server/port would lessen the confusion.
or
b) add a separate toggle that enables/disables relayhost parameter and grays out the SMTP server/port fields.

**Comment by mi-hol** [comment]
@votdev is this accepted for backlog or schould be closed?
