### ISSUE TITLE
openmediavault 'usul main' repository 'php-pam' dependency error

### ISSUE THREAD

**Issue by thecodesucker** [openmediavault/openmediavault#355]
### Info:
- System info (hardware): Raspberry Pi Zero v1.3
- OS: Raspbian GNU/Linux 9 (stretch)
- Kernel version: 4.14.98+
- openmediavault repo: usul main
- repo link: [http://packages.openmediavault.org/public/dists/usul/main/binary-armhf/Packages](http://packages.openmediavault.org/public/dists/usul/main/binary-armhf/Packages)

### Issue:
Although I faced this issue in Raspberry Pi - I believe this issue _may_ exist in all platforms.
When i tried to install openmediavault in Raspbery Pi - I get the following error:
`php-pam : Depends: phpapi-20180731 but it is not installable`
This happens bacause `phpapi-20180731` is listed as a dependency to `php-pam` in the [packages file](http://packages.openmediavault.org/public/dists/usul/main/binary-armhf/Packages) for release `usul`, instead it should have been something like: `phpapi (>= x.y)`.

This version of php-pam may have been compiled against the dev version of phpapi.

### Expected behavior:
successfully install openmediavault

### Reproduce:
install openmediavault in linux (preferably raspbian)

### Relevant Code:
Add the OpenMediaVault repository and grab the gpg key
`echo "deb http://packages.openmediavault.org/public erasmus main" | sudo tee -a /etc/apt/sources.list.d/openmediavault.list`
`wget -O - http://packages.openmediavault.org/public/archive.key | sudo apt-key add -`

Update and install OpenMediaVault including a keyring fix
`sudo apt-get update`
`sudo apt-get install openmediavault-keyring postfix -y`
`sudo apt-get install php-apcu openmediavault -y`

the last command to install `openmediavault` throws error
` openmediavault : Depends: php-pam but it is not going to be installed`

**Comment by votdev** [comment]
OMV5 is based on Debian 10.

**Comment by thecodesucker** [comment]
@votdev - correct.
Also the package in question `phpapi-20180731` is a virtual package. I didn't realize it. This package becomes available by installing php7.3 or adding php7.3 repo.
