### ISSUE TITLE
OMV Repository Problem - Armv61 Confirmed Defective - Armv7+ Confirmed Effective (OMV Install // Php7.+)

### ISSUE THREAD

**Issue by diveyez** [openmediavault/openmediavault#357]
After a long weekend, and much testing, I can confirm that any install on an Armv61 device (Rpi1-2-0w) will likely fail, I can also confirm that Armv7+ was effective and it is working.

Even with a self configured build of php to avoid dependency issues the install of OMV still failed with other errors, I am going to make a fresh system and start the process again to see if I can figure out why, and fix it.

**Comment by diveyez** [comment]
When installing on a fresh system on the Armv61everything functions properly, until I start adding the repositories for OMV. Once I do that, the php that apt gets breaks.

**Comment by ryecoaaron** [comment]
RPi1 is arm cortex-a7.  This is armel and will cause problems.  RPi2 and newer is arm cortex-a53.  This is armhf and works fine.  I have an RPi2 running right now.  RPi2 will support an armel install though.  You really shouldn't using an old, super slow armel system anyway.  If you want more info, post in the forum.

**Comment by diveyez** [comment]
Im using Armhf's Rpi0w and Rpi3b

I can now confirm that php-fpm works with the distro's repository packages
I can now confirm that php-fpm does not work when using OMV's repository packagesl

**Comment by diveyez** [comment]
This is the script I wrote using the information on the OMV website. This did work for x64x86 but is not working for ANY Arm devices AT ALL right now. Especially not with the broken php-fpm etc... that is in the OMV repositories.
```
#!/bin/bash
echo "WARNING: This is the official install instructions and will break Armv6+ and Armv7 Raspberry Pi Systems";
echo "Press Ctrl+C to stop this now, or we will continue with the install in 30 seconds...";
sleep 30
echo "Continuing with the install!"
# ROOT CHECK!
if [ $USER != 'root' ]
then
   echo
   echo "Error: You are running as $USER - please run as root"
   exit
fi
# GOT ROOT?
# REPOSITORY ADDING
cat <<EOF >> /etc/apt/sources.list.d/openmediavault.list
deb http://packages.openmediavault.org/public arrakis main contrib non-free
# deb http://downloads.sourceforge.net/project/openmediavault/packages arrakis main
## Uncomment the following line to add software from the proposed repository.
# deb http://packages.openmediavault.org/public arrakis-proposed main
# deb http://downloads.sourceforge.net/project/openmediavault/packages arrakis-proposed main
## This software is not part of OpenMediaVault, but is offered by third-party
## developers as a service to OpenMediaVault users.
deb http://packages.openmediavault.org/public arrakis partner
# deb http://downloads.sourceforge.net/project/openmediavault/packages arrakis partner
EOF
sleep 5

# OMV INSTALL
export LANG=C
export DEBIAN_FRONTEND=noninteractive
export APT_LISTCHANGES_FRONTEND=none
apt-get update
apt-get --allow-unauthenticated install openmediavault-keyring -y
apt-get update
apt-get --auto-remove --show-upgraded \
    --allow-downgrades --allow-change-held-packages \
    --no-install-recommends \
    --option Dpkg::Options::="--force-confdef" \
    --option DPkg::Options::="--force-confold" \
    install postfix openmediavault -y
sleep 5
# HMMMM # apt install openmediavault -y
# Initialize the system and database.
echo "Initializing the OpenMediaVault System for you.....";
omv-initsystem

```

**Comment by diveyez** [comment]
php-fpm received signal "ILL" lol, I am guessing that means the package has a cold, bless you

**Comment by ryecoaaron** [comment]
Why aren't you using the RPi image?https://sourceforge.net/projects/openmediavault/files/Raspberry%20Pi%20images/

**Comment by diveyez** [comment]
Because I like to solve complex problems and would rather build my own system, however this seems to be the only option at the time due to broken packages across the board. I am now going to close and comment, and try that.

**Comment by ryecoaaron** [comment]
I understand that you want to build your own system but we spent a lot of time creating an image optimized for an RPi.  The packages work because the image existing proves they work.  An RPi really isn't worth the time to use as a NAS though.

**Comment by votdev** [comment]
There is no php-fpm package in the OMV repository. OMV uses the Debian repo and packages for that.

**Comment by diveyez** [comment]
There was a **gpg key** repo side `out of date` apparently. I removed it yesterday and everything is fine as far as that goes but the __backports__ problem still exists. 

-   __ __

> CLOSING
