### ISSUE TITLE
Add Support for RSA 4096 SSH Pubkey in OMV Panel

### ISSUE THREAD

**Issue by diveyez** [openmediavault/openmediavault#359]
I would code this into OMV and issue a pull request but I have no idea where to begin, if anyone can point me in that direction, or help me do that, I would love to help improve OMV with this!

That RSA key is the standard, why DSA is being used it beyond me.

**Comment by ryecoaaron** [comment]
Adding the line to /usr/share/openmediavault/usr/share/openmediavault/engined/rpc/certificatemgmt.inc after line 419 link to below would do it:
		$cmdArgs[] = "-b 4096";

But it is creating an RSA key:
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/certificatemgmt.inc#L419

**Comment by diveyez** [comment]
How can we make it functional for both? RSA DSA. Dont want to remove DSA just want to add RSA

**Comment by diveyez** [comment]
Oh BTW. I am not into changing the key creator, its the part that allows user ssh keys to be added I want to add RSA to

**Comment by ryecoaaron** [comment]
I don't see DSA anywhere.  My user on my systems is using a 4096 bit RSA key.  Importing a key in the Certificates->SSH tab or adding a public in the User's public key tab doesn't change the key.

**Comment by votdev** [comment]
You simply need to adapt the global SSH config to do that.
