### ISSUE TITLE
Add multiple nameservers (DNS Servers) in /etc/resolv.conf

### ISSUE THREAD

**Issue by parthdmaniar** [openmediavault/openmediavault#361]
Hi, I am not a developer hence pardon any errors terms used to describe the problem. 

I flashed OMV on RPi using latest version of etcher on an Ubuntu VM. I had to use an VM due to the fact that Etcher does not work on host OS - Windows 10. I have verified the image for integrity post downloading it inside the VM box.

Post successful image writing and verification, I attached RPi to my ISP provided router and let it sit there to update and configure. **However this kept failing.** I saw following services which were failing:

1. Failed to start kernel modules.
2. I am seeing failed to start realtek H5 bluetooth support.
3. failed to start a high performance web server and a reverse proxy server.

The installation would not proceed at all.

I traced the issue to `/etc/resolv.conf`

It has only one nameserver which is 1.1.1.1. It seems that my ISP (Hatway from India) is disallowing access to this nameserver. Check [here ](https://community.cloudflare.com/t/1-1-1-1-is-not-working-with-hathway-broadband-indian-isp/16866/38)and [here](https://community.cloudflare.com/t/1-1-1-1-issues-with-hathway-india/15925/5). I tried to ping google.com which came back negative. However pinging 8.8.8.8 worked just fine.

I flashed the image using etcher on a memory card and mounted the paritions on an Ubuntu VM. I tried to edit /etc/resolv.conf which seemed to have a symbolic link but this failed. I deleted the link and created a new file called resolv.conf and manually fed in 2 IP address (nameservers / DNS servers). This allowed the Pi to communicate to the internet.

I installed RPi firmware upgrade tool, rpi-date. I upgraded the firmware to latest release  (18e0a0f9a31e7a3a47d9c4301c7705b980ab0516). After this during the reboot I did not notice kernel error.

Upon reboot resolv.conf had single nameserver, again - 1.1.1.1. After  editing the file, connecting to the internet I am able to update and complete installation. 

Hence it is my request to the developers that you include multiple name servers such as quad9 or 9.9.9.9.

I am now successfully using same flashed image over Wifi (do not get angry) :)

**Comment by votdev** [comment]
The RPi images are not officially from the OMV project, they are supported by external devs. According to your report this is not an OMV issue, it seems to be a problem of the image itself. Please post the problem in the forum, so the image developers might notice it.

**Comment by ThomasKaiser** [comment]
Just for the record (and others stumbling across this). Running `rpi-update` is wrong on the RPi OMV image. Discussion / 'DNS fix' / follow-up here: https://forum.openmediavault.org/index.php/Thread/27156-OMV-on-Raspberry-Pi-3B-post-installation-issue/?postID=203597#post203597
