### ISSUE TITLE
Add support for installation with offical omv iso in UEFI mode

### ISSUE THREAD

**Issue by flowercow** [openmediavault/openmediavault#363]
The official install iso only support legacy bios mode, can uefi mode be added for later architecture computers?

**Comment by votdev** [comment]
Will try to get it working. In the meanwhile you can install Debian and then OMV on top. See https://openmediavault.readthedocs.io/en/latest/installation/on_debian.html for more information.

**Comment by votdev** [comment]
Note, Debian supports that starting with Debian 10 which will be used in OMV5.

**Comment by flowercow** [comment]
i have download the omv 5 iso, still in bios mode. you mean that may be available in the release version?

**Comment by votdev** [comment]
> i have download the omv 5 iso, still in bios mode. you mean that may be available in the release version?

In one of the next published ISO versions. But as far as i understood the manual page of live-build it is not possible to support UEFI ISO images.

```
--bootloaders grub-legacy|grub-pc|syslinux|grub-efi
    defines which bootloader is being used in the generated image. This has only an effect if the selected binary image type lets you choose the bootloader. For example, if you build a iso, always syslinux (or more precise, isolinux) is being used.
```

To me it seems not possible to use ``grub-efi`` for ISO images because `` syslinux`` it is always used for this type of image.

**Comment by votdev** [comment]
Please give it a try when ISO is available at https://sourceforge.net/projects/openmediavault/files/5.0.1beta/.

**Comment by MuenYu** [comment]
so,could it boot in uefi now?
I have no device to test now, do you have the answer?

**Comment by ryecoaaron** [comment]
Yes, it does.
