### ISSUE TITLE
Remove weak RSA key lengths and offer ECC for certificates

### ISSUE THREAD

**Issue by jannispinter** [openmediavault/openmediavault#370]
In the current beta of OMV5, the webgui offers multiple choices for the key length when generating a new certificate. Besides RSA 4096 and RSA 2048, there is also RSA 1024 and RSA 512 available.

Would it be possible to remove both RSA 512 and RSA 1024 from the list of choices? I think users who, for some obscure reason, might need a certificate with such short keys, can use the import dialog to do that.

Additionally, it would be pretty cool to allow ECC certificates besides RSA certificates here. In order to use ECC keys, it is necessary to rework some of the code in the RPC and frontend code. If there is interest for this among the maintainers, I would work out the necessary code changes and submit them as a pull request, where they can be discussed further.

**Comment by votdev** [comment]
> Additionally, it would be pretty cool to allow ECC certificates besides RSA certificates here. In order to use ECC keys, it is necessary to rework some of the code in the RPC and frontend code. If there is interest for this among the maintainers, I would work out the necessary code changes and submit them as a pull request, where they can be discussed further.

Could they be imported? If yes, then i do not see any strange reason to support them via UI. Please keep in mind that OMV follows the KISS principle, not every feature must be available in UI.

**Comment by jannispinter** [comment]
> Could they be imported? If yes, then i do not see any strange reason to support them via UI. 

I didn't think of this yet, I think it is an excellent idea. Importing ECC certificates works fine. The only thing that could be changed then is the text in the import dialog, which currently states:

> Paste a RSA certificate in X.509 PEM format here.

Which could be changed to something like:

> Paste a RSA or ECC certificate in X.509 PEM format here.

Or simply remove the key type entirely:

> Paste a certificate in X.509 PEM format here.
