### ISSUE TITLE
Making the OMV web GUI more accessible

### ISSUE THREAD

**Issue by vincejansen** [openmediavault/openmediavault#375]
Hello, 

My name is Vince Jansen, and I'm a blind IT enthousiast and a big fan of OMV because I can install it without sighted assistance, thanks to the native support of refreshable braille displays that's build-in to Debian. 

The web GUI is also quite accessible with most webbrowsers and the free and Open Source screenreader NVDA, which can be found at 
[This website](https://www.nvaccess.org/)

There are still some accessibility bugs to be fixed. This is a short list of what I found so far: 

- There is no first letter navigation available when navigating the three view 

- Some checkboxes aren't labeled correctly, for example when you want to change user rights on a folder or add users to a group.  

I think those kind of issues can be fixed quite easily by a web developer, which I currently don't have the skills for. But if there is some one who can do this, we can work on this together. Please let me know in the commends. If we make OMV more accessible for visually impaired people, it will be better for every one. 

Thanks and best regards.

**Comment by votdev** [comment]
My knowledge in ARIA and ExtJS is little bis not existing, so external contributions are welcome.

**Comment by vincejansen** [comment]
I know one contriutor of the NVDA project in person, so I could ask him to help with this. He is a software developer at [Babbage](https://github.com/BabbageCom) and knows quite a lot about web programming and Linux as well.
