### ISSUE TITLE
Need rpc-statd started?

### ISSUE THREAD

**Issue by mathieubolla** [openmediavault/openmediavault#380]
### Description of issue/question

If I mount an NFS export on a macOS client, it is very slow to open any file for reading, showing the "color wheel of death", then eventually working fine.

On the OMV box logs, shows multiple:
`kernel[259377.264975] lockd: cannot monitor some-redacted-local-client-hostname`

Discovered here and there that doing this on server:
`systemctl start rpc-statd`
`systemctl enable rpc-statd`
(as root in SSH shell) fixes the issue.

### Versions report

Client: macOS 10.13.6, last patch update (17G7024)
Server (extract from "Report"):

```
================================================================================
= OS/Debian information
================================================================================
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 9.9 (stretch)
Release: 9.9
Codename: stretch

================================================================================
= openmediavault information
================================================================================
Release: 4.1.22-1
Codename: Arrakis
```

**Comment by ryecoaaron** [comment]
I don't have this problem on my five amd64 systems using nfs.  Is this an arm board?  If so, which one?

**Comment by votdev** [comment]
I do not find any resource that explicitly mention that rpc-statd is required to run NFS. I'm missing something?

**Comment by skarekrow** [comment]
AFAIK it's required for remote locks. Possibly required for NFSv4 as well?

**Comment by mathieubolla** [comment]
Hi, sorry, didn't read about this issue for a while... 

This is on a retired Dell Optiplex 360 (Intel CPU i7 870, pretty standard hardware)

The client is a recent Mac Book Pro, running up to date software

The resources didn't say it is required, but says it sometimes solve the problem. My experience here proved it to be true, albeit I have no idea why.

Here is part of a book I found recently stating that NFS on Mac needs rpc-statd to allow file locking. Maybe that's the mechanism at work in this issue? https://books.google.fr/books?id=zrI-U0KWj3cC&pg=PA454&lpg=PA454&dq=macos+rpc-statd&source=bl&ots=rFxwxLGtn-&sig=ACfU3U17qDHtAjRqH4D9VNyixLHzKE6Nrg&hl=fr&sa=X&ved=2ahUKEwiajo6StMjjAhUSExoKHXCLAaUQ6AEwCHoECAkQAQ#v=onepage&q=macos%20rpc-statd&f=false

Thanks,

Mathieu

**Comment by votdev** [comment]
Fixed for OMV5.
