### ISSUE TITLE
Still seeing / filling up

### ISSUE THREAD

**Issue by donhwy** [openmediavault/openmediavault#383]
I still see forum posts about / filling up. There are many causes for this and would be hard to prevent. And it can break things completely.

 I think it would be good to provide a warning if the disk is using more than a reasonable size or percentage. This would give the user a chance to fix things before a catastrophe happens.

Thanks

**Comment by votdev** [comment]
This feature already exists. You only need to enable notifications, then monit will send an email if [filesystem gets filled up above 85%](https://github.com/openmediavault/openmediavault/blob/4.x/deb/openmediavault/usr/share/openmediavault/mkconf/monit.d/filesystem#L35).

**Comment by donhwy** [comment]
Since it is still happening maybe something more is required?

**Comment by votdev** [comment]
The problem is sitting in front of the monitor, so i don't think there is more to do than notifying the admin.

**Comment by donhwy** [comment]
If you see the child reaching for the hot plate, would you remind them? 
I will never see this problem but those that do are the least prepared to handle it.

**Comment by votdev** [comment]
> Since it is still happening maybe something more is required?

Maybe you've a good suggestion or solution? I can only repeat myself, what more shall be done than notifying the admin?

**Comment by donhwy** [comment]
Here is how the latest version of proxmox handles old kernels. FYI

Automatic cleanup of old kernel images

    Old kernel images are not longer marked as NeverAutoRemove - preventing problems when /boot is mounted on a small partition.
    By default the following images are kept installed (all others can be automatically removed with `apt autoremove`):
        the currently running kernel
        the version being newly installed on package updates
        the two latest kernels
        the latest version of each kernel series (e.g. 4.15, 5.0)
