### ISSUE TITLE
When adding new users $homedir is not created

### ISSUE THREAD

**Issue by ThomasKaiser** [openmediavault/openmediavault#384]
When testing with both OMV4 and OMV5 I had to realize that when creating a new user account the corresponding `$homedir` is not created and as such using features like Samba's userhome's feature can't work. I guess it's related to [this code](https://github.com/openmediavault/openmediavault/blob/576ddb0f332c2005f714078901ccd36413383b94/deb/openmediavault/usr/share/openmediavault/engined/rpc/usermgmt.inc#L548-L557) but have to admit I do not fully understand what's happening.

Debug output catched on 5.0.2-1 via `omv-engined -d -f` when creating new user 'ml':

    Child process forked (pid=29418)
    Executing RPC (service=UserMgmt, method=setUser, params={"name":"ml","comment":"Mieschen L\u00fcller","email":"","password":"lala123","shell":"\/bin\/sh","disallowusermod":false,"groups":["users"],"sshpubkeys":[]}, context={"username":"admin","role":1}) ...
    RPC response (service=UserMgmt, method=setUser): {"response":{"uuid":"a65246e0-29a9-4ad2-8090-0e4905ca01a2","name":"ml","email":"","disallowusermod":false,"sshpubkeys":[],"comment":"Mieschen L\u00fcller","password":"lala123","shell":"\/bin\/sh","groups":["users"]},"error":null}
    SIGCHLD received ...
    Child (pid=29418) terminated with exit code 0
    Child process forked (pid=29465)
    Executing RPC (service=UserMgmt, method=getUserList, params={"start":0,"limit":25,"sortfield":"name","sortdir":"ASC"}, context={"username":"admin","role":1}) ...
    RPC response (service=UserMgmt, method=getUserList): {"response":{"total":3,"data":[{"name":"ml","uid":1002,"gid":100,"comment":"Mieschen L\u00fcller","dir":"\/home\/ml","shell":"\/bin\/sh","lastchanged":"18043","minimum":"0","maximum":"99999","warn":"7","inactive":"","expire":"","reserved":"","groups":["users"],"system":false,"email":"","disallowusermod":false,"sshpubkeys":[]},{"name":"tk","uid":1000,"gid":100,"comment":"Thomas Kaiser,,,","dir":"\/home\/tk","shell":"\/bin\/bash","lastchanged":"18037","minimum":"0","maximum":"99999","warn":"7","inactive":"","expire":"","reserved":"","groups":["users","cdrom","floppy","sudo","audio","dip","video","plugdev","netdev","ssh","tk"],"system":false,"email":"","disallowusermod":false,"sshpubkeys":[]},{"name":"bb","uid":1001,"gid":100,"comment":"Bjoern Borg","dir":"\/home\/bb","shell":"\/bin\/bash","lastchanged":"18040","minimum":"0","maximum":"99999","warn":"7","inactive":"","expire":"","reserved":"","groups":["users","sudo","ssh","sambashare","openmediavault-config","openmediavault-engined","openmediavault-webgui"],"system":false,"email":"b.borg@gmx.de","disallowusermod":false,"sshpubkeys":[]}]},"error":null}
    SIGCHLD received ...
    Child (pid=29465) terminated with exit code 0

Checking process list for `useradd` in a loop reveals this when adding the user:

    root     29429  0.0  0.0  14252  3264 pts/0    S+   12:25   0:00 useradd --gid users --shell /bin/sh --comment Mieschen Lüller --groups users --password $1$13uO.KkP$mEJOaw1yibIGmP87IMb24. ml

So neither `--home` nor `--create-home` supplied as arguments. Is this by intention or an error?

Or more generally speaking: how are user homes expected to work if OMV tries to keep share data away from the OS drive (where usually `/home` resides)? Would a new variable defining `$USERHOME` pointing to a mounted filesystem be an option and if the `$USERHOME` directory exists and is not on the rootfs then OMV will create the directory there using the `--create-home` argument with `useradd` and further allows users to mount their homedir and to store data there?

**Comment by votdev** [comment]
No user home dir is created by intention to do not pollute the root filesystem and to fulfill the design decisions of OMV to not store any user data on the root filesystem, too. The home dir is only created when the home dirs are stored on a shared folder.

Maybe we need to add a check which validates that user dirs are stored on a shared folder when an admin wants to enable SMB user home dir sharing. Need to check if this is already done.

**Comment by votdev** [comment]
> Maybe we need to add a check which validates that user dirs are stored on a shared folder when an admin wants to enable SMB user home dir sharing. Need to check if this is already done.

The check already exists: https://github.com/openmediavault/openmediavault/blob/576ddb0f332c2005f714078901ccd36413383b94/deb/openmediavault/usr/share/openmediavault/engined/rpc/smb.inc#L83

**Comment by ThomasKaiser** [comment]
> The home dir is only created when the home dirs are stored on a shared folder

Totally fine with this restriction and I understand the design decision to keep the rootfs free from user data.

But how to proceed with average users in mind or let's better say without the need to use the CLI? As far as I understood OMV when creating users simply relies on defaults so without adjusting `HOME=/path/to/omv/share` in `/etc/default/useradd` new users will always get `/home/$username` as their homedir and since `/home/` can't be a shared folder homedir creation will fail?

**Comment by votdev** [comment]
> But how to proceed with average users in mind or let's better say without the need to use the CLI? As far as I understood OMV when creating users simply relies on defaults so without adjusting `HOME=/path/to/omv/share` in `/etc/default/useradd` new users will always get `/home/$username` as their homedir and since `/home/` can't be a shared folder homedir creation will fail?

I can not follow you. If a new user is created via UI then no home dir is created, except the home dir feature is enabled via UI, so OMV will create the home dir automatically. The problem only occurs if a user is created via CLI because the defaults are not adapted. What is your expectation?

**Comment by ThomasKaiser** [comment]
Sorry, my mistake. I completely missed the setting. Apologies for wasting your time.

**Comment by votdev** [comment]
> Sorry, my mistake. I completely missed the setting. Apologies for wasting your time.

Hehe, no problem. The issues section is exactly the location where to discuss such issues.
