### ISSUE TITLE
DHCP options

### ISSUE THREAD

**Issue by lameventanas** [openmediavault/openmediavault#387]
### Description of issue/question
OMV ignores some desirable DHCP options: DNS servers, DNS domain, timezone, NTP.

This is a feature request to implement them.
### Versions report
4.1.7

**Comment by votdev** [comment]
OMV does not change any DHCP options, so the default Debian settings are used, and this includes your mentioned options. So i'm wondering why this happens to you. How did you install OMV? Are you using AMD64 or ARM, ...?

**Comment by lameventanas** [comment]
> OMV does not change any DHCP options, so the default Debian settings are used, and this includes your mentioned options. So i'm wondering why this happens to you. How did you install OMV? Are you using AMD64 or ARM, ...?

I'm using an image I downloaded from the website, for the Odroid HC2.

It seems to be using 1.1.1.1 as DNS server, timezone is UTC, and DNS domain is unconfigured unless I set it manually.
Now I can see the NTP server from DHCP is correctly written to /etc/ntp.conf.

**Comment by ryecoaaron** [comment]
The arm images are using armbian's dhcp config.  This isn't a core OMV issue.  I would post on the forum about this.

**Comment by donhwy** [comment]
It is confusing because you need to enable ntp but leave the server blank. I think it should show the server it is using. Maybe showing it came from dhcp too.
Thanks
