### ISSUE TITLE
[Feature request] Add notification services 

### ISSUE THREAD

**Issue by Ansem93** [openmediavault/openmediavault#390]
Hi, I wanted to ask if it would be possible to add more notification services in OMV.
Right now we are forced to insert some email to use any kind of notifation service, like Telegram.

I propose to add something like that:
https://github.com/caronc/apprise
https://github.com/containrrr/shoutrrr

So that at least some of the most important services are supported. 
I don't think that it should be updated often since both of them support popular notification services like Discord and Telegram. I don't know about the other, so I would go for email, telegram, discord and maybe pushbullet and pushover.

**Comment by votdev** [comment]
There is a guide how to integrate additional services, like [Telegram](https://forum.openmediavault.org/index.php/Thread/14919-GUIDE-Use-Telegram-as-notification-service/).

The email notification MUST be used in all cases to get notifications working because most apps/services are submitting notifications via email interface. OMV will redirect them via Postfix to the above mentioned framework that will allow the integration of other notification services.

**Comment by Ansem93** [comment]
I already use Telegram for my notification, but I think that it should be integrated in the system since telegram is widely used today (at least in EU).
I also think that email notifactions are outdated. It's way easier to manage them in telegram or an other app that will show all of them as a normal chat.

**Comment by votdev** [comment]
It is still not possible to replace the email subsystem with something else, otherwise NO Linux application like smartmontools, monit and many others won’t be able to communicate with the outer world. Those apps must support such a protocol BEFORE OMV can do that. In the meanwhile a E-Mail bridge is necessary to support notifications.

Telegram can be supported via plugin if necessary.

**Comment by vadyalex** [comment]
@votdev I might be interested in creating Telegram plugin for notifications.

Would you might to point me to the right place where I can learn about OMV notification sub-system from developer perspective as well as OMV Plugin development to explore possibilities?

**Comment by mi-hol** [comment]
> There is a guide how to integrate additional services, like [Telegram](https://forum.openmediavault.org/index.php/Thread/14919-GUIDE-Use-Telegram-as-notification-service/).
> 
> The email notification MUST be used in all cases to get notifications working because most apps/services are submitting notifications via email interface. OMV will redirect them via Postfix to the above mentioned framework that will allow the integration of other notification services.

the linked guide says "Note: Emails will still be send, there is no workaround in the moment, postfix needs to be configured."

Does this mean: other notification services can NOT substitute email as transfer technique (they are only used as additional transfer technique )?

**Comment by votdev** [comment]
> > There is a guide how to integrate additional services, like [Telegram](https://forum.openmediavault.org/index.php/Thread/14919-GUIDE-Use-Telegram-as-notification-service/).
> > The email notification MUST be used in all cases to get notifications working because most apps/services are submitting notifications via email interface. OMV will redirect them via Postfix to the above mentioned framework that will allow the integration of other notification services.
> 
> the linked guide says "Note: Emails will still be send, there is no workaround in the moment, postfix needs to be configured."
> 
> Does this mean: other notification services can NOT substitute email as transfer technique (they are only used as additional transfer technique )?

No, because services like monit, mdadm, (other userland apps) ... only know about about email for notifications beside syslog.

**Comment by votdev** [comment]
> they are only used as additional transfer technique

Right. Postfix is the proxy to collect notifications from userland apps like mdadm, collectd, ... that only know about email and redirects them to other services via the given OMV notification interface.
