### ISSUE TITLE
Letsencrypt help needed

### ISSUE THREAD

**Issue by donhwy** [openmediavault/openmediavault#392]
I have written a script to import my Letsencrypt wildcard cert. It works fine to get the cert loaded and working. Only issue is it shows wrong in the web ui. Perhaps you can suggest an addition to update the expire date in the web ui.
Thanks

`#!/bin/bash

#letsencrypt is a host on my network that gets the cert.

scp root@letsencrypt:/etc/letsencrypt/live/example.com/privkey.pem /etc/ssl//private/openmediavault-bb53...49f9.key

scp root@letsencrypt:/etc/letsencrypt/live/example.com/fullchain.pem /etc/ssl/certs/openmediavault-bb53...49f9.crt

systemctl restart nginx`

**Comment by Samuel12321** [comment]
Sorry, i personally dont know the answer to this question, however the OMV Forum [https://forum.openmediavault.org/](OMV Forum) might be a better place to try.
