### ISSUE TITLE
APT Update / Upgrade with error messages

### ISSUE THREAD

**Issue by ricardoj-br** [openmediavault/openmediavault#393]
When running apt update or apt upgrade there are some error messages

I see those messages on two OMV installation - one physical and one virtual

**apt update**

Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7ff53dbbc598>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7ff53dbbc598>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

**apt upgrade**

Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f4ccec5e7b8>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f4ccec5e7b8>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

**Current version**

Linux nas-03 4.19.0-0.bpo.5-amd64 #1 SMP Debian 4.19.37-3~bpo9+1 (2019-05-18) x86_64 GNU/Linux

OMV Version : 4.1.22-1 (Arrakis)

**Comment by votdev** [comment]
This issue can only be fixed by Debian upstream. You can ignore this error, it does not limit the functionality.
