### ISSUE TITLE
Postfix will resolve SMTP server with ipv6 even if ipv6 is explicitly disabled in WebUI

### ISSUE THREAD

**Issue by lukasmrtvy** [openmediavault/openmediavault#394]
### Description of issue/question
Postfix will resolve SMTP server with ipv6 even if ipv6 is explicitly disabled in WebUI

### Steps to reproduce issue
- Disable ipv6 in WebUI
- Try to send notification (for example smpt.gmail.com)
- Error shows up in log: (connect to smtp.gmail.com[2a00:1450:400c:c08::6d]:587: Network is unreachable)

### Versions report
4.1.22-1
### Workaround
```
postconf -e 'inet_protocols = ipv4'
systemctl restart postfix
```
/etc/network/interfaces
```
# Include additional interface stanzas.
source-directory interfaces.d

# The loopback network interface
auto lo
iface lo inet loopback

# enp3s0 network interface
auto enp3s0
allow-hotplug enp3s0
iface enp3s0 inet static
    address 192.168.1.251
    gateway 192.168.1.1
    netmask 255.255.255.0
    dns-nameservers 8.8.8.8
iface enp3s0 inet6 manual
    pre-down ip -6 addr flush dev $IFACE
```
ip addr
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether d0:50:99:93:4f:69 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.251/24 brd 192.168.1.255 scope global enp3s0
       valid_lft forever preferred_lft forever
```

**Comment by adyanth** [comment]
Is this fixed on OMV5? I am hitting the exact situation and the config file does not have the proto set to v4

**Comment by votdev** [comment]
> Is this fixed on OMV5? 

Yes, this is also included in OMV5 and later.

> I am hitting the exact situation and the config file does not have the proto set to v4

In this case IPv6 is enabled on your system.

**Comment by adyanth** [comment]
![image](https://user-images.githubusercontent.com/33192449/118282979-7ac5d880-b4ec-11eb-88fd-4ba2fbad09fa.png)
It is not
![image](https://user-images.githubusercontent.com/33192449/118283057-94672000-b4ec-11eb-8661-3015be8853ea.png)
Same issue seen?

Anything else I need to check?

**Comment by votdev** [comment]
> ![image](https://user-images.githubusercontent.com/33192449/118282979-7ac5d880-b4ec-11eb-88fd-4ba2fbad09fa.png)
> It is not
> ![image](https://user-images.githubusercontent.com/33192449/118283057-94672000-b4ec-11eb-8661-3015be8853ea.png)
> Same issue seen?
> 
> Anything else I need to check?
> 
> I'm guessing that it is because the interface is set to localhost here which would have ipv6 enabled? If so, how do I change that?
> ![image](https://user-images.githubusercontent.com/33192449/118283288-d2fcda80-b4ec-11eb-959c-83dca529f993.png)

I do not see any relation to IPv6 enabled/disabled. Instead the postfix error clearly says that snmp.gmail.com can not be reached. This can have many reasons, missing DNS, ... Make sure your system can connect the internet, than the problem should have been solved.

**Comment by adyanth** [comment]
Thanks @votdev ! Setting it manually changed the error shown on the syslog to a TLS error, and once I changed the encryption to auto, it works without the manual fix too. It just was a red herring before then about the unable to reach network? I did not get that with ipv4 set
![image](https://user-images.githubusercontent.com/33192449/118285713-5f100180-b4ef-11eb-8c7f-8ef0f5e2bbc1.png)
