### ISSUE TITLE
For sending notification with smtp.gmail.com -> You need to enable access for less secure applications in google account settings

### ISSUE THREAD

**Issue by lukasmrtvy** [openmediavault/openmediavault#395]
### Description of issue/question
For sending notification with smtp.gmail.com -> You need to enable `access for less secure applications` in google account settings.

Some kind of clarification in docs (https://openmediavault.readthedocs.io/en/latest/administration/general/notifications.html) will be a good starter info.

### Steps to reproduce issue
Send notification with smtp.gmail.com with default google account. 

### Versions report
4.1.22-1

**Comment by votdev** [comment]
I do not use Gmail, so anyone can update the docs?

**Comment by Samuel12321** [comment]
[](https://github.com/openmediavault/openmediavault-docs/pull/50)
