### ISSUE TITLE
[BUG] [V5.0.2-1] Can't create a Mirror RAID.

### ISSUE THREAD

**Issue by luluwebmaster** [openmediavault/openmediavault#400]
Hello,

Yesterday, I have added two disk of 2TB in my OVM NAS ( V5.0.2-1 ), but when I try to create a Mirror RAID with these disks, I have this error : 

Error : 
`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-mkraid /dev/md1 -l mirror -n 2 -N documents /dev/sda /dev/sdb 2>&1' with exit code '1': mdadm: Note: this array has metadata at the start and may not be suitable as a boot device. If you plan to store '/boot' on this device please ensure that your boot-loader understands md/v1.x metadata, or use --metadata=0.90 mdadm: size set to 1953382464K mdadm: automatically enabling write-intent bitmap on large array mdadm: creation continuing despite oddities due to --run mdadm: Fail create md1 when using /sys/module/md_mod/parameters/new_array mdadm: Defaulting to version 1.2 metadata mdadm: ADD_NEW_DISK for /dev/sda failed: Invalid argument`

Full details : 

```
Erreur #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-mkraid /dev/md1 -l mirror -n 2 -N documents /dev/sda /dev/sdb 2>&1' with exit code '1': mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: size set to 1953382464K
mdadm: automatically enabling write-intent bitmap on large array
mdadm: creation continuing despite oddities due to --run
mdadm: Fail create md1 when using /sys/module/md_mod/parameters/new_array
mdadm: Defaulting to version 1.2 metadata
mdadm: ADD_NEW_DISK for /dev/sda failed: Invalid argument in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/raidmgmt.inc(265): OMV\System\Process->execute()
#1 [internal function]: Engined\Rpc\RaidMgmt->create(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('create', Array, Array)
#4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('RaidMgmt', 'create', Array, Array, 1)
#5 {main}
```

And when I try to create the RAID, I see this error in `/var/log/syslog` : 

```
Jun 24 16:39:34 nas-luc kernel: [45707.285804] md: sda does not have a valid v1.2 superblock, not importing!
Jun 24 16:39:34 nas-luc kernel: [45707.285811] md: md_import_device returned -22
```

I did a lot of research on the question, but I did not find a relevant answer to my question ...

Can you help me ?

Note : Sorry for my bad English, I'm French.

Thank you !

**Comment by votdev** [comment]
This seems to me more an issue of mdadm and not OMV. Please note that Debian 10 is not called stable until now, so there still might some issues.
