### ISSUE TITLE
NTP server option omv 4

### ISSUE THREAD

**Issue by rradar** [openmediavault/openmediavault#401]
### Description of issue/question

I need my omv server to serve time via ntp to other clients in the network.

There is a option in the smb settings to act as a time server

1. Am I forced to activate smb for this? Looks like..
2. Is this time server option (in smb) a generic ntp server? (Important because there is not one windows client but many others)
3. Where does it get the time from? From upstream ntp? From rtc?

**Comment by votdev** [comment]
OMV can not act as time server.

**Comment by donhwy** [comment]
Then why does OMV offer it under smb?
![time server](https://user-images.githubusercontent.com/31188495/60445306-353fe100-9bdc-11e9-9b19-b8c8e3dd95f7.png)

**Comment by votdev** [comment]
This is a feature of SMB and is only for Windows.

**Comment by rradar** [comment]
Any reason for this? Is their a chance for conflict with omv if a ntp server is configured in the base system (debian)?

**Comment by votdev** [comment]
Yes, OMV will override your changes if it detects configuration changes that might affect NTP. OMV was never designed to act as NTP server.

**Comment by ryecoaaron** [comment]
Can always run an ntp server in docker if you need one.
