### ISSUE TITLE
[Issue] missing login icon

### ISSUE THREAD

**Issue by libalis** [openmediavault/openmediavault#402]
If you try to log in to openmediavault's web interface and leave the user blank, the box will turn red and try to display an icon.
But the problem is that this icon can not be displayed!
![Bildschirmfoto](https://user-images.githubusercontent.com/45124869/60339971-92545080-99aa-11e9-8ed9-e172beb18583.png)
I know that this is a really small issue, but it would still be verry nice if this issue could be solved!
Thanks in advance and keep up the great work!

**Comment by votdev** [comment]
Which browser and OMV version are you using.

**Comment by libalis** [comment]
I'm using Chromium version 76.0.3809.87 with the latest stable OMV version 4.1.22!
Sorry for my late reply and thank you for your quick response!

**Comment by libalis** [comment]
Since this issue is old and has already been fixed I am closing it now.
