### ISSUE TITLE
[4.1.23-1] RAID with LUKS: Boot timeout 1 min 30: Job dev-disk-by\x2dlabel-cryptnas.device/start timed out.

### ISSUE THREAD

**Issue by Wikinaut** [openmediavault/openmediavault#403]
### Description of issue/question

Everytime when I boot up my OMV machine with RAID and LUKS, the boot has a 90 seconds timeout:

```
dev-disk-by\x2dlabel-cryptnas.device: Job dev-disk-by\x2dlabel-cryptnas.device/start timed out.
Timed out waiting for device dev-disk-by\x2dlabel-cryptnas.device.
```

Perhaps you can assist how to drop (or fix) this issue.

### Versions report
* Everything up-to-date
* Running 4.1.23-1

**Comment by ryecoaaron** [comment]
This isn’t an OMV issue. It is caused by your LUKS container not being auto unlocked.See the forum for ways to do that. The LUKS plugin doesnt have a method to do this currently.

**Comment by Wikinaut** [comment]
Okay, so this has (currently) regarded as "normal behaviour"? Hmm, schade...

**Comment by Wikinaut** [comment]
Note to myself: https://forum.openmediavault.org/index.php/Thread/18290-A-start-job-is-running-for-LUKS-encrypted-disk/

**Comment by ryecoaaron** [comment]
Yes, this is “normal” behavior since a lot
of users consider auto unlocking to defeat the purpose of encryption.

**Comment by Wikinaut** [comment]
@ryecoaaron of course!  I was only puzzled because of the unnecessary, and non communicated boot delay.

Solution: see above (decrease the delay in fstab).

**Comment by Wikinaut** [comment]
I noticed that now and then my deliberate modification (timeout 2 seconds) of ```/etc/fstab``` is reverted (i. e. the old /etc/fstab is reestablished with the default timeout of 90 seconds).

Do you have any idea why this can happen?

**Comment by ryecoaaron** [comment]
@Wikinaut fstab is re-written by OMV quite often. If you want to change something permanently, you should change the mount options in OMV's database (/etc/openmediavault/config.xml) in the mntent section.

**Comment by Wikinaut** [comment]
@ryecoaaron thanks! Is it documented?

**Comment by ryecoaaron** [comment]
I don't think so.  Take a backup of the file before editing and it is relatively easy to understand what you need to edit once you get to the mntent section.  You will see the same option string that you see in fstab.

**Comment by Wikinaut** [comment]
@ryecoaaron you misunderstood, of course I found the place to fix that. I just wanted to know whether the described behaviour (your post) of OMV is documented elsewhere.

**Comment by ryecoaaron** [comment]
@Wikinaut I have mentioned it many times on the forum but I don't know of any documentation elsewhere.
