### ISSUE TITLE
communication Error

### ISSUE THREAD

**Issue by Karlo1964** [openmediavault/openmediavault#406]
### Description of issue/question
OMV Show short an Window with "communikation Error" when i wan't to see the hard Disk under "Drives" Laufwerke. No Drives where shown. No possibility that there is acsess to the hard Disk in Network... First only LVM Show any Disk in the popup window. I Think this is an Debian.
4.1.22 works
### Steps to reproduce issue
(Include debug logs if possible and relevant.)

### Versions report
4.1.23 on HP Miniserver Gen 8

**Comment by Karlo1964** [comment]
Fehler #0:
OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:186
Stack trace:
#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(95): OMV\Rpc\Rpc::call('Exec', 'getOutput', Array, Array, 3)
#1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#2 {main}

**Comment by votdev** [comment]
As the error message tells: Please check the syslog for more information. We need that to find out what is going wrong.

**Comment by Samuel12321** [comment]
No response in 4 months, seems to be an isolated issue, probably not even due to OMV issue.
Suggest close

**Comment by votdev** [comment]
@Samuel12321 A bot will close issues after some time automatically.
