### ISSUE TITLE
[Suggestion] Merge "Systeminformation" and "About" ("Über") menu sections

### ISSUE THREAD

**Issue by Wikinaut** [openmediavault/openmediavault#408]
![grafik](https://user-images.githubusercontent.com/1151915/60765025-df63b100-a093-11e9-8883-804ad5301f65.png)

I my view, the "About" ("Über") section does not add any valuable information. Let me suggest to drop this section and/or to merge it with what is available under "Systeminformation".

As a newbie and non-insider of OMV, when I want to look up the OMV version information...

... I am always puzzled that there are two similar looking entries in the menu, and angry, respectfully stated: very disappointed, that I can't find the version info in the "Über" ("About") section.

**Comment by Samuel12321** [comment]
A better name for the about menu would probably be a good idea as "about" does usually suggest system info/ versions.
Perhaps the 3 sub pages on the about selection can be merged into one or 2 pages.

**Comment by mi-hol** [comment]
@votdev Was this already completed in #893?

**Comment by votdev** [comment]
> @votdev Was this already completed in #893?

Not really. In version 6.x there is no `About` page anymore, only the system information page and dashboard widget. I will not implement anything else because displaying the version information because of technical reasons (it's not worth to spent more time into this).
