### ISSUE TITLE
Update error caused by release of Debian 10

### ISSUE THREAD

**Issue by webcompas** [openmediavault/openmediavault#409]
Checking for updates isn't possible anymore (using version 5.0.3-1). Neither via Web GUI nor via SSH. According to the error messages it is caused by the release of Debian 10 some days ago. The following error messages are displayed:

> N: Repository 'http://ftp-stud.hs-esslingen.de/debian buster InRelease' changed its 'Version' value from '' to '10.0'
E: Repository 'http://ftp-stud.hs-esslingen.de/debian buster InRelease' changed its 'Suite' value from 'testing' to 'stable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
N: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Version' value from '' to '10'

To solve this, `apt-get update` has to be executed once with the `--allow-releaseinfo-change` option. Afterwards update checking works normally.

**Comment by brunopereira81** [comment]
This is caused by the release of Debian 10 (https://www.debian.org/releases/stable/releasenotes): hardly anything that can be done besides reading the release notes and fixing the apt source files.

**Comment by votdev** [comment]
The issue has been solved with the latest ISO and should not happen anymore if you install OMV manually because Debian 10 is stable now. If you have installed it before the official release it was labeled ``testing``.
