### ISSUE TITLE
Debian buster does not have monit package

### ISSUE THREAD

**Issue by stefaang** [openmediavault/openmediavault#410]
### Description of issue/question
Fresh Debian 10.0.0 netinst iso installation complained about monit package not found.
Indeed, it's not available: https://packages.debian.org/buster/monit

### Steps to reproduce issue
(Include debug logs if possible and relevant.)
https://forum.openmediavault.org/index.php/Thread/25062-Install-OMV5-on-Debian-10-Buster/

### Versions report
OMV5 installation on Debian Buster.

### Workaround
Download the package from [unstable](https://packages.debian.org/sid/monit) and install it with dpkg.

**Comment by votdev** [comment]
I know, the monit package has been removed in Debian 10. We need to build it on our own till Debian ships it again.

**Comment by votdev** [comment]
Fixed

**Comment by lsaffre** [comment]
I tried to install monit on buster as follows:

  wget http://ftp.fr.debian.org/debian/pool/main/m/monit/monit_5.26.0-3_amd64.deb
  sudo dpkg --install monit_5.26.0-3_amd64.deb

But it says:
  dpkg: dependency problems prevent configuration of monit:
   monit depends on libcrypt1 (>= 1:4.1.0); however:
    Package libcrypt1 is not installed.

I then tried "sudo apt install libcrypt1", but it says "E: Package 'libcrypt1' has no installation candidate".

Is it easier to wait until monit has made it into stable? When can I expect this to happen?

**Comment by votdev** [comment]
You need to use apt or apt-get to install dependencies, dpkg does not do that.

**Comment by lsaffre** [comment]
Yes, that's what I tried. But apt did't find libcrypt. But don't worry, I think I will simply wait until monit has made it into stable.

**Comment by votdev** [comment]
> Yes, that's what I tried. But apt did't find libcrypt. But don't worry, I think I will simply wait until monit has made it into stable.

It will never be in Debian 10 as far as i know, it will be back in Debian 11.

I can not see that monit depends on libcrypt1: https://packages.debian.org/bullseye/monit or https://packages.debian.org/buster-backports/monit. I also do not see a libcrypt1 in Debian Buster or Bullseye. It's only in Sid: https://packages.debian.org/search?suite=sid&searchon=names&keywords=libcrypt1

IMO your whole repository setting is faulty.

**Comment by votdev** [comment]
It seems to me you installed monit from Debian Sid which has indeed a dependency to libcrypt1: https://packages.debian.org/sid/monit

**Comment by votdev** [comment]
That's the dependency list of monit installed from the OMV package repository:
```
# apt-cache depends monit
monit
  Depends: libc6
  Depends: libpam0g
  Depends: libssl1.1
  Depends: zlib1g
  Depends: lsb-base
 |Suggests: <default-mta>
    exim4-daemon-light
 |Suggests: postfix
  Suggests: <mail-transport-agent>
    citadel-server
    courier-mta
    dma
    esmtp-run
    exim4-daemon-heavy
    exim4-daemon-light
    msmtp-mta
    nullmailer
    opensmtpd
    postfix
    qmail-run
    sendmail-bin
  Suggests: sysvinit-core
```

**Comment by lsaffre** [comment]
Oops seems that I asked my question in the wrong place. I don't use OMV, I am running postfix on a virtual machine.

**Comment by ryecoaaron** [comment]
Strange that you were following the guide to install OMV when you don't use OMV.
