### ISSUE TITLE
Success Message with false SMTP-Settings

### ISSUE THREAD

**Issue by usfabsl** [openmediavault/openmediavault#415]
### Description of issue/question
I discovered some issues by setting up the SMTP.
There is now validity check if SMTP Server is wrong or does not exist.
A certain notification pops up with a "declared succeded" configuration message but it seems like it's not checking if the SMTP Server is not correct or empty.

### Versions report
My OpenMediaVault: 4.1.23-1 (Arrakis)

**Comment by votdev** [comment]
How can we reproduce this. Please provide a step by step description.

**Comment by votdev** [comment]
And maybe a screenshot

**Comment by usfabsl** [comment]
Thanks for the quick reply!
Sorry, I fogot to mention that after sending a Test Email the notification pops up.
I just attached a screenshot to this comment.

The SMTP-Server I used to test that issue is: fake.server.f as you can see in the picture.

![openmediavault_problem](https://user-images.githubusercontent.com/53862107/62621174-8f3e6f80-b91b-11e9-87c1-1c4f9426b7c8.PNG)

**Comment by votdev** [comment]
The success message is correct because the email was send successfully. This is independent from the postfix settings, so you will get a success message either with an incorrect SMTP server config. It's not possible to check the SMTP server settings for correctness.

**Comment by usfabsl** [comment]
Okay that makes sense.
I was confused because I just typed the Server wrong by accident and when I realised my mistake I already hit the send button. The notification just seemed to positive to me but of course you can't just collect all possible SMTP-Servers to check.
Thank You for taking your time!

**Comment by Julian-O** [comment]
I was tricked by the same issue. I was told the email was sent successfully but the log reported that the authentication had failed. Perhaps the message should be less confident. For example:

> An attempt to send the test email has been made. Please check your mailbox. If the email does not arrive, check any spam folders and also check there are no postfix-related errors in the [log].
