### ISSUE TITLE
Remove Dep on apt-transport-https

### ISSUE THREAD

**Issue by hpreusse** [openmediavault/openmediavault#416]
I just noticed that OMV5 (made for Debian buster) declares a Dep on apt-transport-https. This package is:

Description-en: transitional package for https support
 This is a dummy transitional package - https support has been moved into
 the apt package in 1.5. It can be safely removed.

So, consider to remove that Dep. Thanks!

**Comment by votdev** [comment]
https://github.com/openmediavault/openmediavault/commit/795d7d12b4ac08c3f189f702af9f5dc79125e0b7
