### ISSUE TITLE
SSH Login failed with 'bad ownership or modes for directory /'

### ISSUE THREAD

**Issue by aristipp** [openmediavault/openmediavault#418]
### Description of issue/question
SSH login is not working, easily fixed with chmod / 755, /  was at 775. 

### Steps to reproduce issue
It is a fresh install of OMV 5.05 but i have created some users and enabled SMB, maybe one of these actions caused the issue...
(Include debug logs if possible and relevant.)
Aug 21 22:35:09 omv5 sshd[9592]: Authentication refused: bad ownership or modes for directory /

### Versions report
5.05

**Comment by votdev** [comment]
I'm a little bit confused, you mean root / has incorrect permissions?

**Comment by aristipp** [comment]
I was also a bit confused, but 'stat /' gaves me 775... i changed  the permissiosn to 755 and SSH works. As i said. I am very sure that i have not changed accidentially the permissions of /..., it happens after i have created my user and configured SSH via the Web GUI. Maybe i can reproduce the issue, i will try.

**Comment by gunvirranu** [comment]
@votdev I recently had the same issue, but it seems 756353b should fix this.
