### ISSUE TITLE
Issue with NFS shares on OMV5.0.5-1

### ISSUE THREAD

**Issue by krejler** [openmediavault/openmediavault#419]
### Description of issue/question
OMV 5.0.5-1 on a ESXi 6.7 host
First NFS share works fine.. Second, third, fourth and so on is pointing to the first share when mounting it, even when mounting it localhost on omv.

### Steps to reproduce issue
Fresh install of OMV 5.0.5-1 on a ESXi 6.7 host.
I have shared more folders via NFS, they all pointing to same location in the end.
All directories looks fine in my /export folder and they matches the folders in /sharedfolders, but when mounting they are all hitting the same place - the first NFS share.

### Versions report
OMV 5.0.5-1

**Comment by krejler** [comment]
Same issue here:
https://forum.openmediavault.org/index.php/Thread/28384-Issue-with-OMV5-and-ESXI/

**Comment by krejler** [comment]
Newbie question... How do i apply this fix? Thx

Jakob

**Comment by votdev** [comment]
You have to wait until a new version is released or modify the files manually according the [diff](https://github.com/openmediavault/openmediavault/commit/e0946474bd6b9a234b25e675903a8d179881ec44#diff-d23e1c6eda8ecfed81e29515e06ed468).
