### ISSUE TITLE
Btrfs Samba and Quotas

### ISSUE THREAD

**Issue by ricardoj-br** [openmediavault/openmediavault#420]
I'm running OMV + BtrFS + SAMBA

I noticed some LOG message like : "sys_path_to_bdev() failed for path"

After searching for this I found a "long" Samba thread about it and OMV 

- https://www.spinics.net/lists/samba/msg157244.html

Is this something we must be worried about ?

### Steps to reproduce issue
Install BtrFS from GUI create subvolumes from command line and use them as Samba shares

### Versions report

openmediavault                   4.1.23-1
samba-common                  2:4.5.16+dfsg-1+deb9u2
btrfs-progs                          4.20.1-2~bpo9+1

**Comment by votdev** [comment]
OMV consumes Debian packages but is not involved into the development. If this is a bug, then it must be fixed upstream.

**Comment by votdev** [comment]
Concerning https://github.com/openmediavault/openmediavault/issues/101 this info is new to me. Currently the plans for using BTRFS as core filesystem has been scheduled. Maybe BTRFS gets more stable in the meantime. Alternatively there is still ZFS, maybe the license issues or how to handle them will be solved until the plans mentioned in #101 will be realized.

**Comment by ricardoj-br** [comment]
If I correctly understand the samba thread I pointed out, quotas can also affect ZFS.

**Comment by mi-hol** [comment]
4.x is EOL

**Comment by votdev** [comment]
This is a really old issue of Samba and Btrfs. Samba says Btrfs subvolumes break the concept of SMB, but i didn't find any suggested solution. So it took me several hours of research to sum up this:

- https://codeberg.org/davidak/nixos-config/issues/5
- https://archive.kernel.org/oldwiki/btrfs.wiki.kernel.org/index.php/Quota_support.html
- https://www.diyenjoying.com/2022/05/18/btrfs-with-samba/
- https://forums.freebsd.org/threads/samba-quota-errors-logged.68832/#post-411217
- https://lists.samba.org/archive/samba/2019-May/223040.html
- https://askubuntu.com/questions/1145766/disk-un-mounting-after-write-operations-on-samba

Let's see how to use this info to create a working workaround/solution. I'm really wondering that there is no official guideline how to get Btrfs and Samba work in harmony with their different quota concepts.
