### ISSUE TITLE
Feature Request: webgui manual configuration or "use existing nginx configuration"

### ISSUE THREAD

**Issue by vpistis** [openmediavault/openmediavault#421]
### Description of feature request
Please, if possible, would be fantastic to have a command line to manually configure the webgui through a specific nginx configuration file.

### Example
I use others vhosts into the same server and, in some situations, I want use a specific nginx configuration for the omv webgui. 

### Actual behaviour
At the moment when I make a manual change into the omv nginx conf file, the web gui want to override my changes, but I do not want this.

### Actual workaround
Simply override changes through webgui and after override the nginx conf with my specific configuration.

Thank you for this great project!

**Comment by votdev** [comment]
Please use Docker to host other websites. This will also encapsulate your system for security issues.
