### ISSUE TITLE
when i am updating after few minutes showing this error

### ISSUE THREAD

**Issue by laddu38732** [openmediavault/openmediavault#424]
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; apt-get update 2>&1' with exit code '100': Get:1 file:/var/cache/openmediavault/archives InRelease Ign:1 file:/var/cache/openmediavault/archives InRelease Get:2 file:/var/cache/openmediavault/archives Release Ign:2 file:/var/cache/openmediavault/archives Release Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Contents (deb) Ign:4 file:/var/cache/openmediavault/archives Contents (deb) Get:5 file:/var/cache/openmediavault/archives Contents (deb) Ign:5 file:/var/cache/openmediavault/archives Contents (deb) Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Contents (deb) Ign:4 file:/var/cache/openmediavault/archives Contents (deb) Get:5 file:/var/cache/openmediavault/archives Contents (deb) Ign:5 file:/var/cache/openmediavault/archives Contents (deb) Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Contents (deb) Ign:4 file:/var/cache/openmediavault/archives Contents (deb) Get:5 file:/var/cache/openmediavault/archives Contents (deb) Ign:5 file:/var/cache/openmediavault/archives Contents (deb) Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Contents (deb) Ign:4 file:/var/cache/openmediavault/archives Contents (deb) Get:5 file:/var/cache/openmediavault/archives Contents (deb) Ign:5 file:/var/cache/openmediavault/archives Contents (deb) Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Contents (deb) Ign:4 file:/var/cache/openmediavault/archives Contents (deb) Get:5 file:/var/cache/openmediavault/archives Contents (deb) Ign:5 file:/var/cache/openmediavault/archives Contents (deb) Get:3 file:/var/cache/openmediavault/archives Packages Ign:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Contents (deb) Ign:4 file:/var/cache/openmediavault/archives Contents (deb) Get:5 file:/var/cache/openmediavault/archives Contents (deb) Ign:5 file:/var/cache/openmediavault/archives Contents (deb) Get:3 file:/var/cache/openmediavault/archives Packages Get:4 file:/var/cache/openmediavault/archives Contents (deb) Ign:4 file:/var/cache/openmediavault/archives Contents (deb) Get:5 file:/var/cache/openmediavault/archives Contents (deb) Ign:5 file:/var/cache/openmediavault/archives Contents (deb) Hit:6 http://security.debian.org stretch/updates InRelease Hit:7 http://packages.openmediavault.org/public arrakis InRelease Hit:10 http://packages.openmediavault.org/public arrakis-proposed InRelease Ign:9 http://cdn-fastly.deb.debian.org/debian stretch InRelease Hit:11 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease Hit:12 http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease Hit:13 http://cdn-fastly.deb.debian.org/debian stretch Release Get:14 https://archive.raspberrypi.org/debian stretch InRelease [25.4 kB] Ign:15 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch InRelease Get:16 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch Release [4389 B] Hit:16 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch Release Ign:19 https://openmediavault.github.io/packages arrakis InRelease Err:20 https://openmediavault.github.io/packages arrakis Release server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none Hit:8 https://apt.armbian.com stretch InRelease Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x762585d0> Traceback (most recent call last): File "/usr/lib/python3.5/weakref.py", line 117, in remove TypeError: 'NoneType' object is not callable Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x762585d0> Traceback (most recent call last): File "/usr/lib/python3.5/weakref.py", line 117, in remove TypeError: 'NoneType' object is not callable Reading package lists... W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Contents-deb (main/Contents-armhf) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Contents-deb (main/Contents-all) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Packages (contrib/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Packages (contrib/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Contents-deb (contrib/Contents-armhf) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Contents-deb (contrib/Contents-all) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Packages (non-free/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Packages (non-free/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Contents-deb (non-free/Contents-armhf) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Contents-deb (non-free/Contents-all) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 E: The repository 'https://openmediavault.github.io/packages arrakis Release' does no longer have a Release file. W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Contents-deb (main/Contents-armhf) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Contents-deb (main/Contents-all) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Packages (contrib/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Packages (contrib/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Contents-deb (contrib/Contents-armhf) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Contents-deb (contrib/Contents-all) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Packages (non-free/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Packages (non-free/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Contents-deb (non-free/Contents-armhf) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1 W: Target Contents-deb (non-free/Contents-all) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1

**Comment by Samuel12321** [comment]
Suggest Close,
As @ryecoaaron said, not OMV issue
