### ISSUE TITLE
'System information' empty after clean install

### ISSUE THREAD

**Issue by brunopereira81** [openmediavault/openmediavault#430]
### Description of issue/question

After installing OMV the 'System information' panel in the dashboard, and from the tree menu is empty.

![img](https://imgur.com/download/b1NzMKW)

### Versions report

ISO used: openmediavault_5.0.5-amd64.iso
Current installed openmediavault version package (after running an apt update, upgrade):

```
root@nasty:/var/log# apt info openmediavault
Package: openmediavault
Version: 5.0.6-1
Priority: optional
Section: admin
Maintainer: Volker Theile <volker.theile@openmediavault.org>
Installed-Size: 9,146 kB
Depends: perl:any, libjs-extjs6, php-fpm, libpam-modules, php-json, php-cgi, php-cli, php-mbstring, php-pam, sudo, ethtool, python3-dialog, acl, iproute2, xfsprogs, jfsutils, ntfs-3g, hdparm, wsdd (>= 0.3-2), sdparm, mdadm, postfix, libsasl2-modules, bsd-mailx, python3-dbus, cpufrequtils, rsyslog, logrotate, smartmontools, openssl, openssh-server, uuid, tzdata,nfs-kernel-server, proftpd-basic, lsb-release, sshpass, wget, util-linux, samba, samba-common-bin, rsync, apt-utils, avahi-daemon, libnss-mdns, iptables, monit, beep, php-bcmath, gdisk, rrdtool, collectd, cron, anacron, cron-apt, quota, php-xml, quotatool, whiptail, lvm2,watchdog, ca-certificates, perl, libjson-perl, liblocale-po-perl, proftpd-mod-vroot, libjavascript-minifier-xs-perl, coreutils, xmlstarlet, mount, parted, bash, diffutils, lsof, isc-dhcp-client, socat, rrdcached, locales, nginx, bash-completion, python3, python3-apt, wpasupplicant, systemd, systemd-sysv, btrfs-progs, samba-vfs-modules, pciutils, python3-pyudev,python3-natsort, jq, chrony, python3-netifaces, udev, python3-lxml, salt-minion, php-yaml,python-click, python3-click, debconf (>= 0.5) | debconf-2.0
Homepage: http://www.openmediavault.org
Download-Size: 1,665 kB
APT-Manual-Installed: yes
APT-Sources: https://packages.openmediavault.org/public usul/main amd64 Packages
Description: openmediavault - The open network attached storage solution
 openmediavault is a small and simple to use network attached storage system
 with a smart WebGUI.
```

**Comment by votdev** [comment]
Can you please start the browser developer tools and check if there is an error?

**Comment by brunopereira81** [comment]
Edge beta, Windows 10: Version 78.0.249.1 (Official build) dev (64-bit)

Weirdly enough it started suddenly working as expected, I am not sure why. Doing another clean install and repeating what I have done until now.

**Comment by brunopereira81** [comment]
For some reason everything seems to be fine after the install. Seems to be an browser specific issue.

Thanks

**Comment by wombat01** [comment]
Same issue:
`Release: 5.2.1-1
Codename: Usul`

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

1) [https://i.ibb.co/Wg1Br5F/image.png](url)
Completely deleted site data (cookies, ...)

2) [https://i.ibb.co/zbjH4Fx/image.png](url)
Works in incognito mode

3) Console output
`Uncaught TypeError: OMV.util.Format.binaryUnitRenderer is not a function
    at Plugin.js:140
Packages.js:120 Uncaught TypeError: OMV.util.Format.binaryUnitRenderer is not a function
    at Packages.js:120`

**Comment by votdev** [comment]
> Same issue:
> `Release: 5.2.1-1 Codename: Usul`
> 
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
> 
>     1. [i.ibb.co/Wg1Br5F/image.png](https://i.ibb.co/Wg1Br5F/image.png)
>        Completely deleted site data (cookies, ...)
> 
>     2. [i.ibb.co/zbjH4Fx/image.png](https://i.ibb.co/zbjH4Fx/image.png)
>        Works in incognito mode
> 
>     3. Console output
>        `Uncaught TypeError: OMV.util.Format.binaryUnitRenderer is not a function at Plugin.js:140 Packages.js:120 Uncaught TypeError: OMV.util.Format.binaryUnitRenderer is not a function at Packages.js:120`

Have you upgraded from OMV4? The mentioned code lines are the ones from the OMV4 UI code, so maybe clearing the browser cache will fix the issue.

**Comment by wombat01** [comment]
Yes, upgrade from 4. After some time it repaired itself.
