### ISSUE TITLE
Samba options are ignored

### ISSUE THREAD

**Issue by elfhack** [openmediavault/openmediavault#434]
I'm on OMV 5.0.6. In the past versions i used a couple of OMV_SAMBA options in /etc/defaults/openmediavault, such as OMV_SAMBA_SHARE_VFSOBJECTS. These work in 4.x but seem to be ignored in 5.x I can see them referenced in the salt modules, but they don't seem to be taken into effect. This is on a clean install.

**Comment by votdev** [comment]
Don't forget to run ``omv-salt stage run prepare`` after changing ``/etc/defaults/openmediavault``, otherwise the Salt pillar data is not updated.
