### ISSUE TITLE
omv-confdbadm update un-indents config.xml

### ISSUE THREAD

**Issue by subzero79** [openmediavault/openmediavault#436]
### Description of issue/question
Just debugging a mkconf script for a plugin that i maintain personally i found out that updating the db via command line produces the xml entries lines to be merged into  one
### Steps to reproduce issue
Fetch a db entry, example mount entry

```shell
root@nb:/etc/openmediavault # omv-confdbadm read --uuid 4adf0892-cf63-466f-a5aa-80a152b8dea6 conf.system.filesystem.mountpoint 
{"uuid": "4adf0892-cf63-466f-a5aa-80a152b8dea6", "type": "fuse.mergerfs", "opts": "noauto,", "freq": 0, "passno": 0, "dir": "/media/a448c5e9-7a50-4d48-b73d-48cadbe0326e", "fsname": "a448c5e9-7a50-4d48-b73d-48cadbe0326e", "hidden": true}
root@nb:/etc/openmediavault # omv-confdbadm read --uuid 4adf0892-cf63-466f-a5aa-80a152b8dea6 conf.system.filesystem.mountpoint | jq -rc '.opts|=""'
{"freq":0,"uuid":"4adf0892-cf63-466f-a5aa-80a152b8dea6","fsname":"a448c5e9-7a50-4d48-b73d-48cadbe0326e","opts":"","dir":"/media/a448c5e9-7a50-4d48-b73d-48cadbe0326e","hidden":true,"passno":0,"type":"fuse.mergerfs"}
root@nb:/etc/openmediavault # send=$(omv-confdbadm read --uuid 4adf0892-cf63-466f-a5aa-80a152b8dea6 conf.system.filesystem.mountpoint | jq -rc '.opts|=""')
root@nb:/etc/openmediavault # omv-confdbadm update conf.system.filesystem.mountpoint "$send"
root@nb:/etc/openmediavault # 
```

This here i am removing the options

Then config.xml shows the relevant entry in one line

![image](https://user-images.githubusercontent.com/7058119/64475890-d85c3a80-d1cb-11e9-98b9-9823bdfdb164.png)

This doesn't break the xml file, it just cosmetic but i a wondering if i am sending the object correctly using the tool

### Versions report
4.x

**Comment by votdev** [comment]
XML does not take care about formatting and indention. So no worry.
