### ISSUE TITLE
Samba VFS objects duplication when a share is a Time Machine destination

### ISSUE THREAD

**Issue by elfhack** [openmediavault/openmediavault#438]
If a user uses OMV_SAMBA_SHARE_VFSOBJECTS in /etc/default/openmediavault and uses a share as a time machine destination, it is possible to have duplicate vfs objects in the share. For example, i use
```OMV_SAMBA_SHARE_VFSOBJECTS="catia fruit streams_xattr"```
because I serve shares to mac clients and these are beneficial. However the share that hosts time machine backups ends up with 
```vfs objects = catia fruit streams_xattr catia fruit streams_xattr```

**Comment by votdev** [comment]
Can be fixed in OMV5 only.

**Comment by elfhack** [comment]
Oh, I didn't mention this was about 5.x, sorry :( 4.x didn't have support for Time Machine on samba
