### ISSUE TITLE
UI Headers don't render in Safari

### ISSUE THREAD

**Issue by elfhack** [openmediavault/openmediavault#439]
OMV 5.0.6. This was also an issue in 4.x. Safari 12.1.2. Left is Chrome, right is Safari
<img width="874" alt="Screenshot 2019-09-07 at 20 33 49" src="https://user-images.githubusercontent.com/18247748/64478859-fe271680-d1ae-11e9-95b3-67fa08f737ca.png">

**Comment by votdev** [comment]
Can not be fixed, ExtJS does not provide any fixes anymore. That’s why I switch to Angular UI in OMV6.
