### ISSUE TITLE
How to build Openmediavault ISO IMAGE from source?

### ISSUE THREAD

**Issue by AnClark** [openmediavault/openmediavault#441]
Hello everyone. As OMV doesn't provide any X86 ISO images, I'm going to build from source by my own. But I cannot find any **really relevant** guides.

So would anybody has an idea?

**Comment by votdev** [comment]
Use Debian Live-Build for example.

**Comment by AnClark** [comment]
@votdev Any references?

**Comment by votdev** [comment]
The OMV project does not publish the config files and script to create the ISO images because i do not want to make it too easy for companies to use OMV in their products.

Use https://live-team.pages.debian.net/live-manual/html/live-manual/index.en.html as a reference.

**Comment by AnClark** [comment]
No wonder! Thanks a lot!
