### ISSUE TITLE
WOL is not enabled with kernel 5.2.0

### ISSUE THREAD

**Issue by Mister-XY** [openmediavault/openmediavault#442]
### Description of issue/question
I have installed OMV 5.0.5 and update to 5.0.6-1 with kernel 5.2.0-0.bpo. With that kernel, the wol flag did not set correctly.
Every time, wol is set to wol d instead of og wol g.
If i switch back to Kernel 4.19.0-5 i can use wol and the flag is set to wol g.
There must be an error with the 5.2.0 Kernel.
### Steps to reproduce issue
Switch between the kernels to see the wrong wol flag.

**Comment by ryecoaaron** [comment]
The only obvious difference I see between the kernels is CONFIG_PM_WAKELOCKS is not set in the 5.2 kernel.  Either way, OMV uses the Debian kernel and doesn't compile one just for OMV.  You can switch to the proxmox 5.0 kernel using omv-extras.

**Comment by votdev** [comment]
As @ryecoaaron already told, OMV does not ship his own kernel packages, instead we are totally based on Debian upstream. Because of that we can not do anything here.

**Comment by sdevine01** [comment]
FWIW, I worked around this by adding a cronjob to run at startup:

/usr/sbin/ethtool -s eth0 wol g

...so far so good.

**Comment by Mister-XY** [comment]
I have tested your improvement from here https://github.com/openmediavault/openmediavault/commit/866bae5914e95968367c5cf0a49888a30d37e73b
and i did not see a line with ethtool -s (device_name) wol g.
In that case, the wol is not enabled and with ethtool enp3s0, i see that wol is also disabled. but i have it enabled via webgui.
Wake-on: d
That are my two new files 99-openmediavault-enp3s0.link and 99-openmediavault-enp3s0.network

`[Match]
Name=enp3s0

[Network]
IPv6AcceptRA=no
LinkLocalAddressing=no
DHCP=ipv4
Domains=fritz.box

[Link]


[IPv6Prefix]
`

`[Match]
OriginalName=enp3s0

[Link]
WakeOnLan=magic`

**Comment by votdev** [comment]
According to the docu i found abaout systemd-networkd link files the ``WakeOnLan=magic`` should activate it on the NIC.

**Comment by votdev** [comment]
According to https://manpages.debian.org/buster/udev/systemd.link.5.en.html the ``OriginalName`` is correct.

```
udevadm info /sys/class/net/ens6
P: /devices/pci0000:00/0000:00:06.0/virtio2/net/ens6
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:06.0/virtio2/net/ens6
E: INTERFACE=ens6
E: IFINDEX=2
E: SUBSYSTEM=net
E: USEC_INITIALIZED=1377091
E: ID_NET_NAMING_SCHEME=v240
E: ID_NET_NAME_MAC=enx5254000a1f74
E: ID_NET_NAME_PATH=enp0s6
E: ID_NET_NAME_SLOT=ens6
E: ID_BUS=pci
E: ID_VENDOR_ID=0x1af4
E: ID_MODEL_ID=0x1000
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Red Hat, Inc.
E: ID_MODEL_FROM_DATABASE=Virtio network device
E: ID_PATH=pci-0000:00:06.0
E: ID_PATH_TAG=pci-0000_00_06_0
E: ID_NET_DRIVER=virtio_net
E: ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/ens6
E: TAGS=:systemd:
```

**Comment by Mister-XY** [comment]
Is it possible that magic does not work, because in 5.2 kernel is WOL disabled?

**Comment by votdev** [comment]
> Is it possible that magic does not work, because in 5.2 kernel is WOL disabled?

That would make sense IMO.

**Comment by Mister-XY** [comment]
Strange, if i copy WakeOnLan=magic to 99-default.link in /usr/lib/systemd/network i get the g in Wake-on: g

**Comment by votdev** [comment]
> Strange, if i copy WakeOnLan=magic to 99-default.link in /usr/lib/systemd/network i get the g in Wake-on: g

Hmmm, interesting. Seems to be a priority issue.

But according to the systemd.link docu the link files are sorted by name, thus 99-openmediavault-enp3s0.link should be applied AFTER 99-default.link.

**Comment by Mister-XY** [comment]
If i copy the the 99-default.link to /etc/systemd/network and add the line WakeOnLan=magic, i have also Wake-on: g

**Comment by votdev** [comment]
Could you undo all changes and modify the openmediavault-enp3s0.link file:

```
[Match]
MACAddress=<INSERT_MAC_ADDR_HERE>
```

and give it another try.

**Comment by votdev** [comment]
Could you please post the output of ``udevadm info /sys/class/net/enp3s0``please.

**Comment by Mister-XY** [comment]
I will test it.  Is it possible, that i have found a solution

**Comment by Mister-XY** [comment]
You will see, if i call it 98-openmediavault-enp3s0.link that is loaded in E: ID_NET_LINK_FILE=/etc/systemd/network/98-openmediavault-enp3s0.link
If i called it 99-openmediavault-enp3s0.link, than 99-default.link will load

**Comment by votdev** [comment]
Oh great, thanks for helping. So i will rename the file to get it fixed.

**Comment by Mister-XY** [comment]
But change the Originalname= to the Macadresse

**Comment by Mister-XY** [comment]
I have also tested it without any entry in Match
```
[Link]
WakeOnLan=magic
```
Even these two lines have been enough for me

**Comment by votdev** [comment]
A empty ``[Match]`` section is like a wildcard, thus ALL interface will have WOL enabled. That's not what is intended.
