### ISSUE TITLE
Additional servers on nginx using the same ports do not work cause of the use of ipv6only and deferred parameters

### ISSUE THREAD

**Issue by EzequielB** [openmediavault/openmediavault#444]
### Additional servers on nginx using the same ports do not work cause of the use of ipv6only and deferred parameters
Since `ipv6only` and `deferred` parameters forces a new bind call on nginx http://nginx.org/en/docs/http/ngx_http_core_module.html, other servers can't be set on the same ports.
The use case here is having OMV as the main linux distro and adding custom servicies on top that would reuse nginx service.
Removing the ipv6only and adding both ipv4 and ipv4 listen configurations remediates the use of ipv6only flag.

### Steps to reproduce issue
Add a new server on the nginx configuration inside site-enabled (for example a default server)
´´´
server {
	listen 80 default_server;
	listen [::]:80 default_server;

        if ($scheme = http) {
            # Force redirection to HTTPS.
            return 301 https://$host:443$request_uri;
        }
        
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        
        ssl_certificate [SOME_CERT];
        ssl_certificate_key [SOME_KEY];
}
´´´
Try to restart nginx.

### Versions report
4.x

**Comment by votdev** [comment]
> The use case here is having OMV as the main linux distro and adding custom servicies on top that would reuse nginx service.

Please use Docker for that.

The current implementation of the nginx config will not be changed anymore because there are reasons we do it this way. Check the history of the file and you'll see that there are many changes related this thing because it causes errors on other systems if we do it NOT that way.

**Comment by EzequielB** [comment]
The idea is to use docker and have nginx as a forward proxy. With the current state, you just can't listen on the same ports (80 or 443) with different domains or paths.
Maybe in v5 it can be modified, let me know if I can help there.
Thanks for the reply.

**Comment by votdev** [comment]
As said, i don't want to change such issues in the stable branch. OMV5 is in beta phase, so this is ok to do such changes that might introduce regressions.

**Comment by votdev** [comment]
> Maybe in v5 it can be modified, let me know if I can help there.

This would be great if you could provide a PR for OMV5.

**Comment by ryecoaaron** [comment]
> With the current state, you just can't listen on the same ports (80 or 443) with different domains or paths.

I use the jwilder/nginx-proxy image to do exactly that.  I have multiple nginx containers - one for each domain - all listening on the same ports.  The nginx-proxy sends traffic to the appropriate container based on url.  Works very well and will never causes problems with the omv web interface.  You just change the OMV web interface to use a different port.
