### ISSUE TITLE
Syslog is flooded with messages complaining about smtpd_relay_restrictions and smtpd_recipient_restrictions

### ISSUE THREAD

**Issue by jimmymasaru** [openmediavault/openmediavault#446]
### Description of issue/question
Syslog is flooded with messages complaining about smtpd_relay_restrictions and smtpd_recipient_restrictions

### Steps to reproduce issue
- Set up notification
- Wait for a while. A system restart might help speeding up.
- Check syslog
- Syslog is flooded with the following message
> fatal: in parameter smtpd_relay_restrictions or smtpd_recipient_restrictions, specify at least one working instance of: reject_unauth_destination, defer_unauth_destination, reject, defer, defer_if_permit or check_relay_domains

### Versions report
5.0 beta

**Comment by votdev** [comment]
A better solution is to set compatibility_level to 2, thus the default config of Postfix will be used. See https://github.com/openmediavault/openmediavault/commit/2ab78f559da88e1683b8cc7d2c086d3dfaaba0cf.
