### ISSUE TITLE
SharedFolders do not mount on ZFS File system - OMV 4.1.24-1

### ISSUE THREAD

**Issue by Griffo** [openmediavault/openmediavault#452]
### Description of issue/question

On the most recent version of OMV 4.1.24-1 (at least, potentially 23 as well) shared folders that are pointing to a ZFS volume do not mount on reboot. This causes numerous plugins that require the use of shared folders in their configuration to fail.

### Steps to reproduce issue
Create shared folder on ZFS volume.
Reboot server
View shared folder via SSH etc, will be empty. No mount point has been created from the .mount files in systemd/system.

### Versions report
4.1.24-1

**Comment by votdev** [comment]
https://forum.openmediavault.org/index.php/Thread/28722-Shared-Folders-all-empty-after-reboot/?postID=213937#post213944
