### ISSUE TITLE
"omv-mkconf" not found on clean omv5.0.8 install

### ISSUE THREAD

**Issue by hahyes** [openmediavault/openmediavault#453]
### Description of issue/question

I have problem with clean installation of OMV 5.0.8. Command "omv-mkconf" seems to not be installed properly. When OMV tries to make config files, errors with exit code 127 happens. There is some way to install "omv-mkconf" other than reinstallation, because I didn't find package with mkconf?

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

**Comment by votdev** [comment]
``omv-mkconf`` does not exist anymore in OMV5. It's superseded by ``omv-salt``.

What error occurs in your case, exit code 127 does not say anything.

**Comment by hahyes** [comment]
> What error occurs in your case, exit code 127 does not say anything.

Exit code 127 says "command not found". I uses Syncthing plugin prepared to OMV 4.x and it's uses "omv-mkconf" to adding new web interface and that's giving me error. I thought problem was with corrupted installation. Problem solved I guess, I will install OMV 4.x to use Syncthing.

**Comment by votdev** [comment]
That's the reason, you can not use OMV4 plugins in OMV5.
