### ISSUE TITLE
No prompt to apply changes when modifying group membership

### ISSUE THREAD

**Issue by rjdza** [openmediavault/openmediavault#455]
Using OMV Version 4.1.24-1 (Latest as far as I can tell)

### Description of issue/question
When modifying group membership there is no prompt to apply the changes.  Apart from the annoyance of having to manually trigger an apply, this is also a security issue since it means that the person removed from (or added to) the group still has the same access privileges they had before being added to the group until the change is applied.

### Steps to reproduce issue
Modify group membership from the Web UI.

### Tests done
I tested this by giving a group write access to a CIFS share and triggering an apply.  The user had read access to the share.  

I then removed the person from the group.  They still had write access until I triggered an apply.

(NOTE: The group had access to the share using the SMB "write list = @group" option.)

(NOTE 2: I tried sacrificing my neighbours annoying cat to the gods of OMV, but ended up getting badly scratched and the shed burned down after the cat knocked over the candles.  Subsequent tests showed no noticable change in OMV behaviour, but the neighbours cat now avoids me and my cat, so I'm calling it a win. )

(NOTE3: No cats were harmed in the reporting of this bug (not due to lack of trying, but still))

**Comment by votdev** [comment]
> Apart from the annoyance of having to manually trigger an apply,

There are good reasons to do it this way:

- Not everyone will see the changes applied immediatelly.
- Applying the changes immediatelly means a huge cost when expensive operations needs to be done repeatingly on low-end systems. Applying changes takes much time on low powered hardware.
- Administrators want to review their changes before they are applied.

**Comment by rjdza** [comment]
I think there has been a misunderstanding.  Generally, when I make changes it prompts me to apply, and I apply when I'm done making changes and am ready to apply.

When I change group membership, it doesn't prompt me to apply.  I have to do something like turn CIFS off and on, or edit a share, to get the apply prompt.

This is not about having to manually apply, it's about the apply prompt not appearing when group membership changes.

Jason

**Comment by votdev** [comment]
At my current understanding it is not necessary to rewrite the smb.conf when you remove a user from a group because this check is done by SMB via PAM at the end.  Need to do some more investigation.

**Comment by rjdza** [comment]
I tested before posting, just tested again.

SMBD needs to be restarted (a reload doesn't work).  (Tested with service smbd reload (doesn't work), and service smbd restart (works, changes are refelected).

FWIW, I confirmed that changes to the group membership are immediately reflected in the /etc/group file.

**Comment by rjdza** [comment]
Testing this:

From the smbd(8) man page:

The configuration file, and any files that it includes, are automatically reloaded every minute, if they change. You can force a reload by sending a SIGHUP to the server. Reloading the configuration file will not affect connections to any service that is already established. Either the user will have to disconnect from the service, or smbd killed and restarted.

**Comment by votdev** [comment]
> FWIW, I confirmed that changes to the group membership are immediately reflected in the /etc/group file.

That is because of technical reasons. System settings like users and groups are not stored in the OMV database, so they MUST be applied immediatelly.

Hmmm, looks like the smbd deamon must be restarted if there are changes to groups. I didn't expect such a behaviour.

**Comment by rjdza** [comment]
OK, I understand the problem.  As noted, current / existing sessions are not affected by changes.  The restart is needed in order to kill all sessions.

**Comment by rjdza** [comment]
There WILL be times when you want to grant or revoke access immediately, but from what I can see there is no elegant way to currently do it.

Since resetting connections (I.E. killing samba) will interfere with file operations in progress, a suggested solution would be:

Issue a warning (when modifying groups) that changes will not immediately be applied, but add a manual "Apply Changes" / "Apply Group Changes" / "Whatever" button in the CIFS tab that implements a SMBD restart.

Jason

**Comment by rjdza** [comment]
An additional / alternate solution may be to include an "active sessions" tab under CIFS that shows smbd processes owned by users (I.E. not root).

Killing a specific users process will force the group changes to be applied when they reconnect (which is automatic) and will not affect other users.

**Comment by votdev** [comment]
> Since resetting connections (I.E. killing samba) will interfere with file operations in progress

Yes, that's not so good.

> Issue a warning (when modifying groups) that changes will not immediately be applied,

This might be a solution.

> but add a manual "Apply Changes" / "Apply Group Changes" / "Whatever" button in the CIFS tab that implements a SMBD restart.

This doesn't fit into the OMV and how it works.

**Comment by votdev** [comment]
> Killing a specific users process will force the group changes to be applied when they reconnect (which is automatic) and will not affect other users.

These informations are already displayed in the Diagnostics | Services | SMB page. But managing processes from within the UI is overkill and, sorry i have to say that, isn't the way how OMV works.

**Comment by votdev** [comment]
OMV6 will have a page to restart services from within the UI. This will finally solve the problem, an administrator knowing about the behaviour of SMB can then restart the daemon manually.

Implementing such a feature in OMV5 is too late bacause of feature freeze and the fact that i will not change any UI code in OMV <= version 5 anymore because the UI is rewritten from scratch for OMV6.

**Comment by rjdza** [comment]
I understand that this may be something that cannot be fixed, so the following is just an observation.

If you need to grant or deny permissions quickly, there needs to be a more elegant solution than:

* stop CIFS
* save
* Apply
* Start CIFS
* save
* Apply

If OMV doesn't handle it from the webui, the only options available are:

* the 6 steps above, or
* access the console (ssh or directly) and restart smbd (or kill user session), or
* Tell the user they need to reboot their machine.

**Comment by rjdza** [comment]
Even a simple, permanent  "Apply changes" button somewhere would help with this.
