### ISSUE TITLE
NGinx report "bad gateway"

### ISSUE THREAD

**Issue by hpreusse** [openmediavault/openmediavault#457]
### Description of issue/question
I upgraded my OMV from 4.1.23 to 5.0.9 (not sure if that plays a role here). Then I configured the nginx web server to Disable the Auto Logout after x minutes of inactivity. After doing so, the web does not start properly, instead a "502 Bad Gateway" is reported.

### Steps to reproduce issue
For me it was: Debian 10 running 4.1.23 (all fine, the option worked). Then I upgraded to 5.0.6 or 5.0.9 and I could reproduce the issue. I'm using SSL only if that plays a role here.

### Versions report
5.0.6 & 5.0.9.

**Comment by votdev** [comment]
> Then I configured the nginx web server to Disable the Auto Logout after x minutes of inactivity.

Are you talking about the nginx OMV plugin?

**Comment by hpreusse** [comment]
Not sure, what the nginx OMV plugin should be. I had installed:

ii  openmediavault           4.1.27-1     all          openmediavault - The open
ii  openmediavault-diskstats 4.0.2-1      all          OpenMediaVault disk monit
ii  openmediavault-keyring   1.0          all          GnuPG archive keys of the
ii  openmediavault-lvm2      4.0.7-1      all          OpenMediaVault Logical Vo

I upgraded the OS below to Debian stable (buster) and then the OMV to usul:

ii  openmediavault           5.1.1-1      all          openmediavault - The open
ii  openmediavault-diskstats 5.0.1-1      all          OpenMediaVault disk monit
ii  openmediavault-keyring   1.0          all          GnuPG archive keys of the
ii  openmediavault-lvm2      5.0.1-1      all          OpenMediaVault Logical Vo

After doing so it is not possible any more to set the parameter "General settings" -> Auto Logout to "Disabled" (did not try other values). The web page of OMV is not reachable any more after doing so, the nginx reports bad gateway. Attached is the log of the OMV upgrade and the logs of nginx in the error situation. Rebooting the server did not solve the issue.
This is my OMV T stage: a Virtual box carrying a few snap shots. After resetting the VM back to arrakis (on buster) I can again set this parameter.

[upgrade_log.txt](https://github.com/openmediavault/openmediavault/files/3907601/upgrade_log.txt)
[nginx_logs.zip](https://github.com/openmediavault/openmediavault/files/3907604/nginx_logs.zip)

**Comment by votdev** [comment]
I'm sorry, but i can not reproduce this with latest version 5.1.1. I checked without and with SSL including forced SSL. I always can connect to the WebUI -> configuration files seems to be correct. So i'm currently out of ideas what is going wrong on your system because the log files do not report any errors.

**Comment by guny74** [comment]
Hello,

I am very new to OMV but I installed today from scratch also the latest Version and got the same issue.

How could it be solved ?

Thanks

Regards
  Thorsten

**Comment by dmkjr** [comment]
I, too, am having the same issue on a fresh install with Raspberry Pi.  

Followed the directions listed here, https://forum.openmediavault.org/index.php/Thread/28789-Installing-OMV5-on-Raspberry-PI-s-Armbian-Supported-SBC-s/ ,  without skipping a step and getting a Bad Gateway NGINX error when completed.

I have followed this tutorial in the past (week or two ago) and was able to get it up and running.  My guess is something has changed in the past few days causing the issue on fresh installs?

**Comment by ryecoaaron** [comment]
@dmkjr you are having a different issue.  Try the fix here - https://forum.openmediavault.org/index.php/Thread/30094-Trouble-installing-OMV-on-pi4-No-access-to-GUI/?postID=223614#post223614

**Comment by votdev** [comment]
Can this be closed now?

**Comment by dmkjr** [comment]
Yes, this was the issue with the repository for those few hours.  Thanks.
