### ISSUE TITLE
Delay docker startup until all shared folders is mounted

### ISSUE THREAD

**Issue by ejalal** [openmediavault/openmediavault#458]
### Description of issue/question
I just noticed recently that when I reboot my omv 4 NAS, all my docker containers start fresh like new, which scared the hell outnof me at the first place... but when I restarted them after a few minutes they worked just fine.
My docker containers have their persistent volumes on /sharedfolders/media/appdata where "media" is a mounted folder from my raid5 array.

A quick fix is probably to delay docker service startup until all HDD/Raid/Shares are mounted

### Steps to reproduce issue
Where can I find these logs?

### Versions report
Release: 4.1.25-1
Codename: Arrakis
Linux openmediavault 4.19.0-0.bpo.5-amd64 #1 SMP Debian 4.19.37-5+deb10u2~bpo9+1 (2019-08-16) x86_64 GNU/Linux

**Comment by ryecoaaron** [comment]
You could just add an override file to the docker unit.
systemctl edit docker.service

then add:

[Unit]
After=local-fs.target

**Comment by ejalal** [comment]
Thanks for the tip, just thought that could be defaulted in docker installation in OMV for non experts like me.
I'll try that shortly.

**Comment by ryecoaaron** [comment]
@ejalal You are the first one that I remember reporting this problem.  So, I guess it hasn't come up. I can look at some options.

**Comment by redespace** [comment]
I am having the same problem. I am running 5 containers on OMV-Docker (Sonarr, Radarr, Jackett, Transmission and pihole). I configured them so that appdata is on one of the shared folders (an external HDD) so that it doesn't consume my small internal flash.

Unfortunately, I noticed that after OMV boot, the containers seem to start before the HDD is mounted, so Docker starts the new containers (without the existing data). It would be good to either have an option to delay on the plugin or somewhere easy to find.

I will try ryecoaaron's instructions. Hope it helps :)

**Comment by ryecoaaron** [comment]
No one has ever reported if this works.  So, I didn't add it.  Let me know if it works.

**Comment by PrplHaz4** [comment]
> 
> 
> No one has ever reported if this works. So, I didn't add it. Let me know if it works.

I have been using this for a while and it's been working great.  Thanks!

I'd also recommend it being added as a default - seems like a common enough use-case, and should only add a few seconds to startup time.

**Comment by ryecoaaron** [comment]
Sounds ok to me.  I just didn't want to add it if it wasn't working.  Thanks!

**Comment by ejalal** [comment]
It didn't work for me, I still have to restart docker service one my nas finishes booting up.

**Comment by ryecoaaron** [comment]
Of course it didn't.  I just pushed the update out.  grrr...

What filesystems?  mergerfs?  zfs?  I need more details.  You must have a filesystem that isn't using localfs.

**Comment by redespace** [comment]
@ryecoaaron 
I will check tonight and report back tomorrow if it worked. In the meantime my system:

`root@odroidxu4:~# df -Th | grep "^/dev"
/dev/mmcblk0p2 btrfs     7.4G  2.2G  4.2G  35% /
/dev/mmcblk0p1 ext4       58M   23M   33M  42% /boot
/dev/sda1      fuseblk   1.9T  1.3T  627G  67% /sharedfolders/MOVIES
/dev/sdb1      fuseblk   1.9T  1.8T   82G  96% /sharedfolders/TVSeries
/dev/sdc3      fuseblk   489G   54G  435G  12% /sharedfolders/Sys_Backup
/dev/sdc2      fuseblk   1.3T  607M  1.3T   1% /sharedfolders/Movies2
/dev/sdc1      fuseblk   2.0T  1.5T  419G  79% /sharedfolders/TVSeries2`

**Comment by ryecoaaron** [comment]
@redespace do you have any local disks?  The command I added won't wait for remote mounts.

**Comment by ryecoaaron** [comment]
@redespace what filesystems are those disks?  They are fuse mounted which makes me think they are ntfs.  The localfs might not wait for fuse mounts.

**Comment by redespace** [comment]
@ryecoaaron No I don't :( The 'local' flash is mmcblk0p2.
What do you mean by ''remote'? the drives are connected directly via USB.
The filesystem in those disks are indeed NTFS (I started using them with a Windows PC, then migrated them to OMV/odroid). They are 3 Physical disks sda, sdb and sdc.

I setup all docker containers to use the appdata folder on sdc3. As described by ejalal, after boot the containers come up 'as new'. Need to manually login to OMV and restart the containers on the GUI.
Is there a chance that localfs might wait for them to mount? I really hope so :)

**Comment by ryecoaaron** [comment]
I deleted the remote comment after I looked at your output more.  I don't think ntfs will work.  we need a native Linux filesystem.

**Comment by redespace** [comment]
found this:

```
The system doesn’t know that there is a disk there until the hotplug event occurs, up until that point it has no idea whether a drive might or might not appear within a few seconds and whether it should be waiting for one or not. Once the hotplug event occurs the drive will be mounted almost immediately.

So unfortunately there are only really two solutions:

1. Mount the drive manually in fstab to a different location such as /mnt - now there is an fstab entry systemd knows that a drive is expected to appear at this location and you could wait on this using After
2. Just add a several second delay to the launch of the service. You could do that with an ExecStartPre:

[Service]
ExecStartPre=/bin/sleep 10
```

What would you recommend? Option 2 sounds simpler: add ExecStartPre to docker service?

**Comment by redespace** [comment]
OK, I just found a solution!! yeiii :)

1. SSH/login to your device.
2. Run: `systemctl list-unit-files | grep “.mount”`
3. Identify the disk that you would like to wait for. In my case was "sharedfolders-Sys_Backup.mount"
4. Run: `systemctl edit docker.service`
5. Then add:
```
[Unit]
Requires=xxx.mount
After=xxx.mount
```

I tried this, and after rebooting, all my containers started perfectly! Im so happy :)
@ryecoaaron Maybe you can add to the plugin this functionality? not sure it's easy, but hey maybe it''s possible.

**Comment by ryecoaaron** [comment]
A delay of a set amount of time is either annoying on systems that don't need it or not long enough on systems that need 11 seconds for instance.

Your probably is that you are using the /sharedfolder bind mounts as well.  These are disabled by default in OMV 5.x now for the exact reason you are running into.  If you should use the absolute path which is viewable in the Sharedfolder tab.  omv-extras should not add any info about waiting for a mount because nothing would trigger it to change if the mount changed.  You can put that in your own override if that fixes your system but most people should not need it if using actual mountpoints instead of bind mounts.

**Comment by cvigo** [comment]
Same issue and fixed with the @redespace solution. Thanks!!

> OK, I just found a solution!! yeiii :)
> 
> 1. SSH/login to your device.
> 2. Run: `systemctl list-unit-files | grep “.mount”`
> 3. Identify the disk that you would like to wait for. In my case was "sharedfolders-Sys_Backup.mount"
> 4. Run: `systemctl edit docker.service`
> 5. Then add:
> 
> ```
> [Unit]
> Requires=xxx.mount
> After=xxx.mount
> ```
> 
> *of course, replace the xxx with your mount name
> I tried this, and after rebooting, all my containers started perfectly! Im so happy :)
> @ryecoaaron Maybe you can add to the plugin this functionality? not sure it's easy, but hey maybe it''s possible.

**Comment by ryecoaaron** [comment]
@cvigo omv-extras is already doing this - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/usr/sbin/omv-installdocker#L310

**Comment by AndreaPro** [comment]
> @cvigo omv-extras is already doing this - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/usr/sbin/omv-installdocker#L310

I've had this issue and fixed it following redespace suggestion. I've installed latest OMV version in february 2021 but the issue was still there

**Comment by similicious** [comment]
Just to publicly document: I ran into a similar issue. The docker installation from omv-extras will wait for mounts, but as it seems not for ever. The filesystem of my drive was corrupted and for some reason the mount failed or took some time. After I ran a fschk for the filesystem the issue was resolved and the mounts of the containers worked again.
