### ISSUE TITLE
Feature request: Infiniband support in Network Interfaces

### ISSUE THREAD

**Issue by republicus** [openmediavault/openmediavault#459]
I see a patch @ https://sourceforge.net/p/openmediavault/code/2031
made to include Infiniband support to adding network interfaces via the web gui for OMV 2.X. I am using OMV 5.X and wish to request the same support be made for later versions of OMV.

I've added my infiniband network config to /etc/network/interfaces

```
# Infiniband Port 1
auto ibs16
iface ibs16 inet static
       address  10.12.12.174
       netmask  255.255.255.0
       mtu 65520
       pre-up modprobe mlx4_core
       pre-up modprobe mlx4_ib
       pre-up modprobe ib_umad
       pre-up modprobe ib_uverbs
       pre-up modprobe ib_ipoib
       pre-up echo connected > /sys/class/net/ibs16/mode
```

This works until I reboot. After making a change via the web-gui to the Ethernet interface from DHCP to static -- my /etc/network/interfaces modifications for infiniband are removed.

**Comment by votdev** [comment]
The mentioned code is still in OMV5, why should it have been removed? I'm don't think your custom /etc/network/interfaces changes can be adapted in OMV. It's too specific. Best way is to configure this on your own.

P.S.: OMV5 uses systemd for network configuration.

**Comment by republicus** [comment]
I do not see that code included in a clean OMV5 install; neither is there any means of adding, configuring, or viewing the infiniband device through the GUI.  Ive set the modules to load at /etc/modules-load.d/ which makes the interface configuration trivial in modifying the address/netmask and mtu through the GUI 

https://forum.openmediavault.org/index.php/Thread/12005-How-to-create-charts-to-show-infiniband-network-traffic/?postID=99463#post99463 

The interface is working how I have it configured, but it seems the code should make the interface and its traffic accessible via the GUI, which would be a nice addition.

**Comment by votdev** [comment]
> The interface is working how I have it configured, but it seems the code should make the interface and its traffic accessible via the GUI, which would be a nice addition.

I'm sorry, but this will not happen because your hardware is special and not the target for OMV. The main aim for OMV is to support custom hardware. But i think OMV will give you all the freedom to include your setting beside the OMV configuration to benefit from other services supported by OMV.
