### ISSUE TITLE
Feature request: omv-sensors for omv 5.x

### ISSUE THREAD

**Issue by lukasmrtvy** [openmediavault/openmediavault#462]
### Description of issue/question
Is there any plan to port omv-sensors plugin to 5.X ?
According to this:
https://forum.openmediavault.org/index.php/Thread/22050-Sensors-OMV-Sensors-in-OMV-4-1-x/?pageNo=3
whole plugin is abandoned.

I would like to have sensors plugin directly in omv. ( Of course there is possible, maybe even better to integrate whole monitoring with netdata. )

### Versions report
4.1.26

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-sensors/issues/13
