### ISSUE TITLE
open media vault error applying changes

### ISSUE THREAD

**Issue by filou263** [openmediavault/openmediavault#465]
Hi, being pretty new to this forum, let me introduce myself. am an IT enthousiast since a while but i'mù currently having a small issue on openmediavault: 
i set up the server on an gen 8 micro server on the SSD and  attached currently 1 8TB drive in bay one. in created in the HP provisionning 2 arrays 0 ( 1 for the SSD and 1 for the data). 
i then created several forlders on the data drive and map them ( samba) to my desktop PC. 
I then started populating the new drive with all the films, app etc... contained previously on the desktop. 
I finally added serviio etc.... 
While trying to apply the changes, please find hereunder the error log obtained..... 
i tried to restart the server, no changes.... can anyone help please? 

Erreur

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; systemctl restart 'sharedfolders-Series.mount' 2>&1' with exit code '1': Job for sharedfolders-Series.mount failed. See "systemctl status sharedfolders-Series.mount" and "journalctl -xe" for details.
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; systemctl restart 'sharedfolders-Series.mount' 2>&1' with exit code '1': Job for sharedfolders-Series.mount failed.
See "systemctl status sharedfolders-Series.mount" and "journalctl -xe" for details. in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/system/systemctl.inc(86): OMV\System\Process->execute(Array, 1)
#1 /usr/share/php/openmediavault/system/systemctl.inc(160): OMV\System\SystemCtl->exec('restart', NULL, false)
#2 /usr/share/openmediavault/engined/module/sharedfolders.inc(66): OMV\System\SystemCtl->restart()
#3 /usr/share/openmediavault/engined/rpc/config.inc(194): OMVModuleSharedfolders->startService()
#4 [internal function]: OMVRpcServiceConfig->applyChanges(Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(565): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusQs...', '/tmp/bgoutputCJ...')
#8 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#9 /usr/share/openmediavault/engined/rpc/config.inc(213): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#10 [internal function]: OMVRpcServiceConfig->applyChangesBg(Array, Array)
#11 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#12 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#13 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#14 {main}

**Comment by votdev** [comment]
I assume you are using ``/sharedfolders/xxx`` paths somewhere in your plugins. This is [not allowed](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/debian/changelog#L556) because this will end in the problems above.

**Comment by votdev** [comment]
Are we talking about OMV4 or OMV5?

**Comment by filou263** [comment]
hi OMV 4. Does that means i should stop poiting the serviio plugin on the shared drives?

**Comment by votdev** [comment]
Simply use the ``/srv/<FILESYSDEVNAME>/<SFPATH>`` path instead.

**Comment by Kasperx** [comment]
I have the same error and can find the problem config in my dropdownmenu. I want to delete it.
How can I use a different way while I use the config of omv? Makes no sence to me.
![Screenshot_20200510_104142](https://user-images.githubusercontent.com/10506030/81494673-f8885000-92aa-11ea-9f81-588f25a1ee24.png)

**Comment by janwels89** [comment]
I also have this error. It seems related to my shares loosing the "Relative Path" Entry in the webinterface. I am Running OMV4 on "Debian GNU/Linux 9 (stretch)" and my filesystems are zfs.

![image](https://user-images.githubusercontent.com/57909534/85061491-2d8b9a80-b1a7-11ea-9be8-fdd674ed5e3a.png)

```
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; systemctl restart 'sharedfolders-Backup.mount' 2>&1' with exit code '1': Job for sharedfolders-Backup.mount failed.
See "systemctl status sharedfolders-Backup.mount" and "journalctl -xe" for details. in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/system/systemctl.inc(86): OMV\System\Process->execute(Array, 1)
#1 /usr/share/php/openmediavault/system/systemctl.inc(160): OMV\System\SystemCtl->exec('restart', NULL, false)
#2 /usr/share/openmediavault/engined/module/sharedfolders.inc(66): OMV\System\SystemCtl->restart()
#3 /usr/share/openmediavault/engined/rpc/config.inc(194): OMVModuleSharedfolders->startService()
#4 [internal function]: OMVRpcServiceConfig->applyChanges(Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(565): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusuu...', '/tmp/bgoutput4y...')
#8 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#9 /usr/share/openmediavault/engined/rpc/config.inc(213): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#10 [internal function]: OMVRpcServiceConfig->applyChangesBg(Array, Array)
#11 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#12 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#13 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#14 {main}
```

**Comment by mi-hol** [comment]
4.x is EOL
