### ISSUE TITLE
OpenMediaVault 4 : Error when checking NIC.

### ISSUE THREAD

**Issue by atomic83GitHub** [openmediavault/openmediavault#466]
### Description of issue/question

On OMV, checking a NIC to identify a ethernet interface don't work, it always shows an error:

![image](https://user-images.githubusercontent.com/26351275/66760989-6d291680-eea3-11e9-9be4-5a6ca68df4af.png)

For now, only Virtualbox work.

### Steps to reproduce issue

Goes into network setings, check a web interface, see the error.

### Versions report

OMV 4.1.26

**Comment by votdev** [comment]
The error message clearly says that the hardware does not support that.

**Comment by votdev** [comment]
Please list the interfaces via 

# ip addr show

**Comment by votdev** [comment]
I think the problem is simple, the NIC doesn’t support that command (according to the ethtool error message).
