### ISSUE TITLE
OMV5 + Debian10 = proftpd disconnect client ipcam (dahua)

### ISSUE THREAD

**Issue by emwu88** [openmediavault/openmediavault#473]
Hi,
on OMV 5 I have issue with PROFTPD deamon, when ipcam write stream to ftp server on OMV5, server disconnect client after random time (1-5minut), stream is cuttered, and ipcam make new connection itd etc.
On OMV 4 everything is OK, stream is continous, client establish connection, write 60minut file (1280MB), correct close it, and establish next connection with new file.

I tested OMV5 on 2 different PC - on both this same issue, when I install on this same pc OMV4 is OK.
System installed from OMVx.iso.

This same situation is when I install clean debian10 server, I think it look like is something wrong with debian 10 (buster) distro. OMV5 installed on clean buster - this same.

PC: Intel NUC with N3050 and ITX with i5-4670T.

**Comment by votdev** [comment]
I'm sorry, but we can not do anything here. This sounds like an upstream issue of ProFTPd. If you think this should be fixed, then open a bugreport for the [Debian package](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=proftpd-basic;dist=unstable) or for the [project](http://www.proftpd.org/bugs.html) itself.
