### ISSUE TITLE
nginx fails: [::]:80 address family not supported by protocol 

### ISSUE THREAD

**Issue by schokotets** [openmediavault/openmediavault#477]
### Description of issue/question
Nginx fails to start on the Raspberry Pi 3B when only an IPv4 address is provided via LAN.
`nginx [emerg] socker() [::]:80 failed (97: Address family not supported by protocol)`

### My Setup
I am using a Raspberry Pi 3B to run OpenMediaVault. My laptop shares its WiFi connection with the RasPi via Ethernet, but only provides an IPv4 address, causing the Raspberry Pi to not launch.

### Manual Fix
Manually editing `/etc/nginx/sites-enabled/openmediavault-webgui` fixes the issue. I changed `listen [::]:80 ipv6only=off;` to `listen 80;`. I believe that [this file](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/nginx/files/site-webgui.j2) is responsible and not triggering correctly or not supporting IPv4 only setups.

### Versions report
openmediavvault 4.1.7 (Arrakis) raspberrypi tty1

**Comment by votdev** [comment]
The problem here is surely that your system reports IPv6 is enabled but has some strange problems with it. Maybe disabling IPv6 in the kernel solves your problem. OMV works and behaves correctly, so there is no bug in OMV.

**Comment by woodongwong** [comment]
same question

**Comment by woodongwong** [comment]
When I try to execute the "omv_utils.is_ipv6_enabled" function, I get the following error:

``` UnboundLocalError: local variable 's' referenced before assignment```

**Comment by votdev** [comment]
> When I try to execute the "omv_utils.is_ipv6_enabled" function, I get the following error:
> 
> ` UnboundLocalError: local variable 's' referenced before assignment`

Will be fixed in openmediavault 5.0.11, see https://github.com/openmediavault/openmediavault/commit/005a184cd5917824698ac453ba3bfdf180e093a8

**Comment by woodongwong** [comment]
@votdev Executing ```socket.socket(socket.AF_INET6)``` in my Raspberry Pi 3B will get the following error:
```[Errno 97] Address family not supported by protocol```

But the execution on the pc is ok. I don't know about python.

**Comment by votdev** [comment]
> @votdev Executing `socket.socket(socket.AF_INET6)` in my Raspberry Pi 3B will get the following error:
> `[Errno 97] Address family not supported by protocol`
> 
> But the execution on the pc is ok. I don't know about python.

Fixed, see https://github.com/openmediavault/openmediavault/commit/b10a578161b5f232dd2dfeed678727e754049959.
