### ISSUE TITLE
Add options to disable '--manage-gids' for NFS in Gui

### ISSUE THREAD

**Issue by nerdalertdk** [openmediavault/openmediavault#478]
### Description of issue/question

When using the NFS server as an Data Store for Ovirt Hypervisor, Ovirt will fail during installation because `--manage-gids`is enabled in the NFS settings (`/etc/default/nfs-kernel-server`) on OMV

Could we get an option to disable `--manage-gids` for NFS in Gui and possible an options to disable a NFS version (`--no-nfs-version 3` , `--no-nfs-version 4`)

Some background on -g/--manage-gids:

> Accept  requests  from  the kernel to map user id numbers into  lists of group id numbers for use in access control.  An NFS request will normally (except when using Kerberos or other crypto‐graphic authentication) contains a user-id and a list of group-ids.  Due to a limitation in the NFS protocol, at most 16 groups ids can be listed.  If you use the -g flag, then  the  list  of group  ids  received  from the client will be replaced by a list of group ids determined by an appropriate lookup on the server. Note that the 'primary' group id i

**Comment by votdev** [comment]
You can already customize this via environment variable. Simply add ``OMV_NFSD_MOUNTDOPTS=""`` to ``/etc/default/openmediavault``. Then ``omv-salt deploy run nfs`` to apply the settings.

**Comment by votdev** [comment]
I will close this issue because there are too much command line options for NFS. Starting with this will end in a never ending story to add switches/options to the UI to fulfill all user requirements.

All options can be customized via existing features.

**Comment by nerdalertdk** [comment]
So is omv-salt installed pr. default on your debian package ?

```
root@san1:~# omv-salt
-bash: omv-salt: command not found
```

**Comment by ryecoaaron** [comment]
You must have installed OMV 4.x  Use:  omv-mkconf nfsd

**Comment by nerdalertdk** [comment]
Hi,

So i upgrade to 5.x, but the `omv-salt deploy run nfs` cmd do not change the default file `/etc/default/nfs-kernel-server`

```
root@san1:~# cat /etc/default/openmediavault | grep OMV_NFSD_MOUNTDOPTS
OMV_NFSD_MOUNTDOPTS="--no-nfs-version 3"
```

```
root@san1:~# omv-salt deploy run nfs
san1.142.io:
----------
          ID: configure_default_nfs-kernel-server
    Function: file.managed
        Name: /etc/default/nfs-kernel-server
      Result: True
     Comment: File /etc/default/nfs-kernel-server is in the correct state
     Started: 17:01:31.683612
    Duration: 25.903 ms
     Changes:
----------
          ID: configure_nfsd_exports
    Function: file.managed
        Name: /etc/exports
      Result: True
     Comment: File /etc/exports is in the correct state
     Started: 17:01:31.709615
    Duration: 43.831 ms
     Changes:
----------
          ID: start_rpc_statd_service
    Function: service.running
        Name: rpc-statd
      Result: True
     Comment: The service rpc-statd is already running
     Started: 17:01:31.760671
    Duration: 21.891 ms
     Changes:
----------
          ID: start_nfs_kernel_server_service
    Function: service.running
        Name: nfs-kernel-server
      Result: True
     Comment: The service nfs-kernel-server is already running
     Started: 17:01:31.783220
    Duration: 17.718 ms
     Changes:

Summary for san1.142.io
------------
Succeeded: 4
Failed:    0
------------
Total states run:     4
Total run time: 109.343 ms
```

```
root@san1:~# cat /etc/default/nfs-kernel-server
# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.

# Number of servers to start up
RPCNFSDCOUNT=8
# Runtime priority of server (see nice(1))
RPCNFSDPRIORITY=0
# Options for rpc.mountd.
RPCMOUNTDOPTS="--manage-gids"
# Do you want to start the svcgssd daemon? It is only required for Kerberos
# exports.
NEED_SVCGSSD=
# Options for rpc.svcgssd.
RPCSVCGSSDOPTS=
```

**Comment by votdev** [comment]
See https://openmediavault.readthedocs.io/en/5.x/various/advset.html?highlight=environment
