### ISSUE TITLE
feat req. improve information displayed at fs panel

### ISSUE THREAD

**Issue by subzero79** [openmediavault/openmediavault#490]
### Description of issue/question
The backend retrieves the same information for device, parent device and device(s) all display the same. This is a ss of the panel mostly composed of logical volumes, which all of them (except EFI) have they have identifying names in the device mapper path.

![image](https://user-images.githubusercontent.com/7058119/68094622-2b155280-feee-11e9-8694-ec003bb88af5.png)

```
dev/disk$ tree -a
.
├── by-id
│   ├── dm-name-data-storage -> ../../dm-2
│   ├── dm-name-data_storage--vg-music -> ../../dm-5
│   ├── dm-name-data_storage--vg-other -> ../../dm-3
│   ├── dm-name-data_storage--vg-pictures -> ../../dm-6
│   ├── dm-name-data_storage--vg-videos -> ../../dm-4
│   ├── dm-name-elqui--vg-root -> ../../dm-0
│   ├── dm-name-elqui--vg-swap_1 -> ../../dm-1
│   ├── dm-uuid-CRYPT-LUKS2-256b1a69064344388bded917abe90459-data-storage -> ../../dm-2
│   ├── dm-uuid-LVM-PfftZ13Qtw1N97yE41a8ctuxTGXjtGvU7qZCScUJvoAivi83MJf7jNYqmBGUZAYU -> ../../dm-5
│   ├── dm-uuid-LVM-PfftZ13Qtw1N97yE41a8ctuxTGXjtGvUFQtv0ykgIFZYxuBJt5E07c4DGgNrHefY -> ../../dm-4
│   ├── dm-uuid-LVM-PfftZ13Qtw1N97yE41a8ctuxTGXjtGvUWIs27V7TpX6EsxTWZWw2pxgZn4kl1GoC -> ../../dm-3
│   ├── dm-uuid-LVM-PfftZ13Qtw1N97yE41a8ctuxTGXjtGvUYNo6eh2HK6gtAQiQtUpWhKBjql9GrtCU -> ../../dm-6
│   ├── dm-uuid-LVM-uSB3m1gZWMLpF4CL5HCQguRp3wZ5k2leZSxIVR1CeEJfPdECkcdfVko3E37KmlRF -> ../../dm-1
│   ├── dm-uuid-LVM-uSB3m1gZWMLpF4CL5HCQguRp3wZ5k2leaeEPqE1AVXAtM2VCfkuQQU7aFD5XrXNi -> ../../dm-0
│   ├── lvm-pv-uuid-IWJ2mR-AX3M-k9ZY-SAfq-ZCvj-zO47-CZWK6v -> ../../dm-2
│   ├── lvm-pv-uuid-hgcQaJ-PpkP-0tdN-847X-mGI1-yMek-A9zRzW -> ../../sda
│   ├── scsi-0QEMU_QEMU_HARDDISK_drive-scsi0 -> ../../sda
│   ├── scsi-0QEMU_QEMU_HARDDISK_drive-scsi1 -> ../../sdb
│   ├── scsi-0QEMU_QEMU_HARDDISK_drive-scsi1-part1 -> ../../sdb1
│   └── scsi-0QEMU_QEMU_HARDDISK_drive-scsi2 -> ../../sdc
├── by-label
│   ├── EFI -> ../../sdb1
│   ├── music -> ../../dm-5
│   ├── other -> ../../dm-3
│   ├── pictures -> ../../dm-6
│   ├── rootfs -> ../../dm-0
│   ├── rust-storage\x2fvm-111-disk-0 -> ../../sdc
│   └── videos -> ../../dm-4
├── by-partuuid
│   └── 1890835c-01 -> ../../sdb1
├── by-path
│   ├── pci-0000:01:01.0-scsi-0:0:0:0 -> ../../sda
│   ├── pci-0000:01:02.0-scsi-0:0:0:1 -> ../../sdb
│   ├── pci-0000:01:02.0-scsi-0:0:0:1-part1 -> ../../sdb1
│   └── pci-0000:01:03.0-scsi-0:0:0:2 -> ../../sdc
└── by-uuid
    ├── 0293545a-d0bd-4263-91bc-5ceabd055cb9 -> ../../dm-0
    ├── 198a34a8-5992-4ffa-8f6d-416665d5f7b4 -> ../../dm-6
    ├── 256b1a69-0643-4438-8bde-d917abe90459 -> ../../sdc
    ├── 3866063e-be48-41f9-a650-b158635234c8 -> ../../dm-1
    ├── 5525-F951 -> ../../sdb1
    ├── ed4e1388-e3dd-42b9-8bf6-37826b14c850 -> ../../dm-5
    ├── f3fc9576-26f2-4aa8-9dd0-61d8b67ab995 -> ../../dm-4
    └── f609aeda-2e89-43bd-b648-f7e36d3c2e2a -> ../../dm-3
```
```
:/dev/mapper$ tree -a
.
├── control
├── data-storage -> ../dm-2
├── data_storage--vg-music -> ../dm-5
├── data_storage--vg-other -> ../dm-3
├── data_storage--vg-pictures -> ../dm-6
├── data_storage--vg-videos -> ../dm-4
├── elqui--vg-root -> ../dm-0
└── elqui--vg-swap_1 -> ../dm-1

0 directories, 8 files
```

In this case i am helping myself identifying by labels

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

**Comment by votdev** [comment]
You know from the forum that labels, and explicit /dev/disk/by-label, is a bad idea. Or how shall i understand this feature rrequest.

**Comment by subzero79** [comment]
Sorry i didn't explain better. It would be better to help identify the the devices associated to the fs if the dev/by-id or for LVM the mapper device name would be displayed there, i am not saying we change how we mount devices. 

In this case i am saying the only thing helping me identify each fs to a device is the label. 

Look here before formatting

![Screenshot_2019-11-04_22-10-18](https://user-images.githubusercontent.com/7058119/68120229-837d3c00-ff50-11e9-87c9-0e426222183e.

Shouldn't we display that in at least one of the columns, or a new one.

Even for a brief moment during fs initialisation you can see the /dev/mapper name, then it goes into canonical dm-X name

I haven't use omv in bare metal since a long time but i guess it would be the same for directly attached disks

**Comment by votdev** [comment]
can you re-upload the image, it's not visible.

**Comment by subzero79** [comment]
i've updated the screenshot

**Comment by myomv100** [comment]
What if the file system is on top of a RAID array? Should the label of the array displayed or the drives that are parts of it.. like this

raidarray1_label
     sdb
     sdc

**Comment by votdev** [comment]
> i wish there is a guide on how to prepare a working development environment from this git repo..

YOu should use Vagrant for that: https://github.com/openmediavault/openmediavault/tree/master/vagrant

**Comment by votdev** [comment]
@subzero79 The filesystem device file and the parent device file are equal because OMV does not create partitions for filesystems on DM devices.

Would you like to see something like that?
![Bildschirmfoto vom 2019-12-11 16-49-53](https://user-images.githubusercontent.com/1897962/70636756-5a7a5600-1c36-11ea-86d2-3127110b8de9.png)
