### ISSUE TITLE
proposal: LUKS as default option and full integration for your data disks

### ISSUE THREAD

**Issue by DEvil0000** [openmediavault/openmediavault#496]
At the moment you need to install a plugin to get LUKS to the UI.

I think LUKS should be the default option for a storage disk what ever else (FS or RAID) is used.
So it should be integrated in the UI and the setup process for a new NAS.

**Comment by votdev** [comment]
Using plugins is the main concept of OMV. With OMV6 some more already included features like FTP will be outsourced as plugins.

**Comment by DEvil0000** [comment]
how about some plugins like this beeing installed by default?

**Comment by votdev** [comment]
I think shipping a clean core system with the ability to install plugins with some clicks is the better choice.

For example, do you like the pre-installed apps on your smartphone or newly bought Windows PC? The most people uninstall them at first.

**Comment by DEvil0000** [comment]
well. crypto is core functionality to me and not really optional. I do not store any private or business data without. for everything else I favour plugins.

**Comment by ryecoaaron** [comment]
Personally, I have no need for crypto.  If I was going to use it, I would probably use zfs which wouldn't need the LUKS plugin.  So, I think this should still be a plugin.
