### ISSUE TITLE
proposal: a ansible playbook for setting up a NAS with OMV would be nice

### ISSUE THREAD

**Issue by DEvil0000** [openmediavault/openmediavault#498]
debian packages are nice but they do not help you configure it consistently.
ansible would be a nice fit to configure it in a consistent way. even the UI could just write yaml or json config and call a ansible playbook to apply it.
this way you can track changes more easy and one would not need the web ui at all to configure it in a easy to use and reproducable manner.

**Comment by DEvil0000** [comment]
I found this project: https://github.com/forestnd/MY-NAS

It is not a complete or quite usable ansible playbook + roles but its a start

**Comment by ryecoaaron** [comment]
Uh, OMV 5.x uses saltstack already.

**Comment by votdev** [comment]
OMV5 is based on Saltstack.

**Comment by johncant** [comment]
Apologies if this is the wrong place to ask etc., and I appreciate that there's no reason for OMV to implement an ansible module when it already uses saltstack.

If you use ansible to deploy your services, what would be the best way of automatically configuring users/shares/permissions etc. in OMV? This is after OMV is already installed but other services need users/shares set up in OMV.

Yesterday I got this working by using ansible to make the correct calls to omv-rpc. It works but it's quite messy and I'm wondering if there's a more sensible/reliable/maintainable way.

**Comment by ryecoaaron** [comment]
The whole idea of OMV is to use the web interface to configure services, users, shares, etc and then OMV uses saltstack to do the config management.  I don't see any better way to get ansible to replace the web interface in a more maintainable way.

**Comment by votdev** [comment]
> If you use ansible to deploy your services, what would be the best way of automatically configuring users/shares/permissions etc. in OMV?

It is not the intention of OMV to ship SaltStack/Ansible formulas to end-users to do the config deployment. OMV is based on a UI guided user experience. For the sake of simplicity and to not reinvent the wheel, SaltStack is used to do the configuration deployment.

**Comment by johncant** [comment]
@ryecoaaron @votdev thanks for explaining.

**Comment by axelsimon** [comment]
> The whole idea of OMV is to use the web interface to configure services, users, shares, etc and then OMV uses saltstack to do the config management. I don't see any better way to get ansible to replace the web interface in a more maintainable way.

Wait, so under the hood OMV uses an automation tool, SaltStack, but the only way to configure it is using a highly manual non-automatable process of clicking in a web interface?

Couldn't the result of the manual GUI configuration steps be exported in order to quickly configure a fresh OMV instance?

**Comment by ryecoaaron** [comment]
> the only way to configure it is using a highly manual non-automatable process of clicking in a web interface?

No, you could configure everything by editing the database if you knew the schema or you could make rpc calls from a script.

> Couldn't the result of the manual GUI configuration steps be exported in order to quickly configure a fresh OMV instance?

You could just use the database IF everything on the system was exactly the same (disks, filesystem uuids, user and their IDs, etc).  You can check out this script which might be close to what you are looking for - https://github.com/xhente/omv-regen
