### ISSUE TITLE
OMV 5 prevents persistent device naming

### ISSUE THREAD

**Issue by elfhack** [openmediavault/openmediavault#500]
At some point the /etc/systemd/network/10-openmediavault-enp7s0.link file got included in my initrd. After that, udev would refuse to rename the interface (in my case eth2), making the network fail. It looks like the link file is missing the name.

This is not a problem when initially installing OMV5, as the initramfs doesn't get regenerated (i guess?) but it's a problem nontheless. I think it should include Name= in the [Link] section

**Comment by votdev** [comment]
Fixed in openmediavault 5.0.14.
