### ISSUE TITLE
samba avahi service should respect OMV_SAMBA_FRUIT_MODEL

### ISSUE THREAD

**Issue by elfhack** [openmediavault/openmediavault#503]
Right now /srv/salt/omv/deploy/avahi/services/files/smb.j2 has hardcoded
<txt-record>model=Xserve</txt-record>

It should respect what's being passed in at OMV_SAMBA_FRUIT_MODEL

**Comment by votdev** [comment]
Hmmm, right now it's hardcoded `model=RackMac`, but you're right, it should respect the `OMV_SAMBA_FRUIT_MODEL`.

**Comment by votdev** [comment]
Thx for the bugreport. Fixed in openmediavault 5.0.15.
