### ISSUE TITLE
Improve error behaviour when session expires.

### ISSUE THREAD

**Issue by Julian-O** [openmediavault/openmediavault#504]
### Description of issue/question

When a WebUI session expires, the browser displays an aggressive warning message. It should be softened, better explained, or even better removed.

[You may notice a theme amongst the issues I raise; they are items that confused me as a newbie, and I am trying to help improve the experience for the newbies that follow me.]

In particular:

It says "Software Failure." This is not a software failure. It is just an expected user timeout.

It says "Press left mouse button to continue." On touch devices, there may be no mouse. Some people click with the right button. This should be changed to "Click to continue" or even better have an explicit button (labelled "Reload", "Retry", "Refresh", "Ok" or similar) where there is no need to tell people how to interact with it.

Ultimately, is the error message necessary at all? Would simply refreshing (will bring up the login screen) be sufficient, or does that risk confusing the user if they were mid-way through a interaction and won't be able to guess why it was aborted?

### Steps to reproduce issue

* Login to the web interface.
* Wait for the session to expiry (If I understand correctly, this works better if http and no-cookies are used.)
* Note the display is updated with a blackbox at the top, with red writing that reads "Software Failure.   Press left mouse button to continue. Session expired."

### Versions report
4.1.26-1 (Arrakis)

**Comment by votdev** [comment]
The error messages are based on the Amiga Guru Meditation and a tribute to the Amiga computer, so the message is at it is.

I don’t think this will change for ONV4 and OMV5. The new UI in version 6 will adapt this.

**Comment by nigel-dewar** [comment]
It freaked it me out seeing this message as well!, but now I see your answer it made me laugh so hard, no I like it. Im glad I know what it means now,

I was going to throw the old PC I installed OMV on out, as I thought there was something wrong with it hardware wise that was affecting the software. Glad I dont have to do that

**Comment by DaveBKC** [comment]
> The new UI in version 6 will adapt this.

I really hope that's not the case.  It took me five minutes to look it up and realize it's an homage.  IMO it adds personality and it makes me smile every time I see it.

**Comment by mi-hol** [comment]
there is no version label but "planned" label.
Will this be worked on for 6.x oder 7.x ?

**Comment by votdev** [comment]
Fixed in OMV6.

**Comment by votdev** [comment]
Fixed in OMV6.
