### ISSUE TITLE
Explain cron-apt output.

### ISSUE THREAD

**Issue by Julian-O** [openmediavault/openmediavault#505]
### Description of issue/question

If "Software Updates" notifications are turned on, emails will be sent daily listing the output of `cron-apt`, with insufficient context for a newbie admin to understand what is happening.

The cron job should detect if cron-apt has produced any output, and if so, prefix it with a covering note such as:

> Periodically, openmediavault runs cron-apt which checks for the latest versions of software components. However, it only downloads them, and does not install them. 
> The output is included below. Any packages that are listed as "will be upgraded" are merely downloaded and ready to install. 
> Log in to the web interface, and select System | Upgrade Management to list the currently pending upgrades, and decide which to install.
> Unsubscribe from these messages by selecting select System | Notifications, and turning off Software Upgrade notifications.

----

### Steps to reproduce issue

* Turn on Software update notifications.
* Wait until a new piece of software is published.
* Receive cryptic email, like this:

> CRON-APT RUN [/etc/cron-apt/config]: Mon Nov 11 00:09:22 AEDT 2019 CRON-APT SLEEP: 2915, Mon Nov 11 00:57:57 AEDT 2019 CRON-APT ACTION: 3-download CRON-APT LINE: /usr/bin/apt-get -o Acquire::http::Dl-Limit=25 dist-upgrade -d -y -o APT::Get::Show-Upgraded=true Reading package lists...
> Building dependency tree...
> Reading state information...
> Calculating upgrade...
> The following packages will be upgraded:
>   openmediavault
> 1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Need to get 0 B/1919 kB of archives.
> After this operation, 1024 B of additional disk space will be used.
> Download complete and in download only mode

### Versions report

4.1.26-1 (Arrakis)

**Comment by votdev** [comment]
Sadly this is not possible because cron does not work that way to implement your suggestion.

**Comment by Julian-O** [comment]
I imagine this would need a bash script (or similar) that runs cron-apt, redirecting stdout and std error to a temporary log file, then check if the log file is empty. If not, output the above text followed by catting the file.

**Comment by votdev** [comment]
Contributions are welcome.

**Comment by auanasgheps** [comment]
Hey, I vote this issue!

I did not know OMV checks updates by default just by turning on notifications. Don't get me wrong: it's a great idea, but the output is not clear at all.

On my machine I configured a cron job to run **omv-update** every 7 days, but one day I received the output of this check. I could not understand what happened, mostly because was written `Download complete and in download only mode` and I got confused.

I did not had the time to investigate, but now I am happy there is an explanation.

If you want to keep things simple, please add the message that @Julian-O has suggested, and update accordingly the subject of the email.

**Comment by votdev** [comment]
> EDIT: I had a look at /usr/sbin/cron-apt, unfortunately it's too complicated for my skills.

And this is the total wrong approach. OMV CAN'T modify this script otherwise it will break package updates for cron-apt. If there would be an easy way, then it would have been added already.

**Comment by Julian-O** [comment]
Good news: I found an easy way to do it with cron-apt configuration. No need to patch cron-apt. No need for custom bash scripts

Bad news: I haven't submitted a patch, because I am not familiar enough with how salt does the deployment to make this config changes happen.

Two small edits are required.

* In the existing directory `/etc/cron-apt/errormsg.d`, create a new file called `3-download` which contains the text of the prefixed message. (I submitted a suggestion in the initial issue.

* In the existing file `/etc/cron-apt/config` (which is deployed by `openmediavault/deb/openmediavault/srv/salt/omv/deploy/cronapt/files/etc_cron-apt_config.j2`) add a line:

    ERRORMSGDIR="/etc/cron-apt/errormsg.d"

**Comment by Julian-O** [comment]
This was closed last month, without explanation. While I haven't submitted a patch, I have provided details of a fairly straightforward change. It seems to be free of any of the raised concerns, and was working on my machine for months.

**Comment by votdev** [comment]
Could you please explain why `ERRORMSGDIR="/etc/cron-apt/errormsg.d"` should be added to `/etc/cron-apt/config`? The environment variable is already set to this in `/usr/sbin/cron-apt` before `/etc/cron-apt/config` is sourced.

```
...
############################## defaults #######################################

ACTIONDIR="/etc/cron-apt/action.d"
ACTIONCONFDIR="/etc/cron-apt/config.d"
MAILMSGDIR="/etc/cron-apt/mailmsg.d"
MAILONMSGSDIR="/etc/cron-apt/mailonmsgs"
SYSLOGONMSGSDIR="/etc/cron-apt/syslogonmsgs"
REFRAINFILE="/etc/cron-apt/refrain"
NOLOCKWARN=""
ERRORMSGDIR="/etc/cron-apt/errormsg.d"
SYSLOGMSGDIR="/etc/cron-apt/syslogmsg.d"
LOGMSGDIR="/etc/cron-apt/logmsg.d"
LOGDIR="/var/log/cron-apt"

...

DIFFONCHANGES=prepend

export DEBIAN_FRONTEND="noninteractive"
export LANG="C"
export LC_ALL="C"

# Read configuration.
for cfg in $ALLCONFIGS; do
  if [ -f "$cfg" ] ; then
    . "$cfg"
  else
    echo >&2 "The config file $cfg does not exist."
  fi
done
...
```

> In the existing directory /etc/cron-apt/errormsg.d, create a new file called 3-download which contains the text of the prefixed message.

How does this work? Does it mean that the content of the file is appended to the command output in case of an error? What errors are included here?

**Comment by Julian-O** [comment]
> Could you please explain why ERRORMSGDIR="/etc/cron-apt/errormsg.d" should be added to /etc/cron-apt/config?

I don't recall if I found this to be necessary. It may be belt and braces, in case a default configuration changes to another directory. Again, I am not familiar with how Salt configures the system as to whether this is a risk.

> How does this work? Does it mean that the content of the file is appended to the command output in case of an error? What errors are included here?

[This readme](https://raw.githubusercontent.com/D3luxee/puppet-cronapt/master/cron-apt-readme.txt) was the best explanation I found:

> ERRORMSGDIR="/etc/cron-apt/errormsg.d"

>  The directory where messages that will be prepended to the error message
  (per action) is stored. The message file must have the same name as
  the action file.

So, *prepended*, not appended, which is good. This will be added to all *errors* in the action *3-download* (i.e. "Downloads the updated packages but do not install them".) It appears successful downloading and not updating is classified as an error by apt-cron.

**Comment by auanasgheps** [comment]
I do really like this now! Great improvement!

**Comment by Dalan94** [comment]
I have this error just after the upgrade related to this issue:
```
          ID: create_cron-apt_download_msg
    Function: file.managed
        Name: /etc/cron-apt/mailmsg.d/3-download
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 21:44:00.668217
    Duration: 2.692 ms
     Changes: 
```

How can I fix it ?

**Comment by votdev** [comment]
> I have this error just after the upgrade related to this issue:
> 
> ```
>           ID: create_cron-apt_download_msg
>     Function: file.managed
>         Name: /etc/cron-apt/mailmsg.d/3-download
>       Result: False
>      Comment: Unable to manage file: none of the specified sources were found
>      Started: 21:44:00.668217
>     Duration: 2.692 ms
>      Changes: 
> ```
> 
> How can I fix it ?

The full error trace would be helpful because it should contain additional information.

Please execute the following commands and post the output:
```
# ls -alh /srv/salt/omv/deploy/cronapt/files
# ls -alh /etc/cron-apt
# dpkg -l | grep cron
```

**Comment by Dalan94** [comment]
Here are the full error trace and the output of the commands.

Thanks.

```
Erreur #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color cronapt 2>&1' with exit code '1': debian:
----------
          ID: remove_cron-apt_refrain_file
    Function: file.absent
        Name: /etc/cron-apt/refrain
      Result: True
     Comment: File /etc/cron-apt/refrain is not present
     Started: 19:51:06.350736
    Duration: 0.82 ms
     Changes:
----------
          ID: create_cron-apt_config
    Function: file.managed
        Name: /etc/cron-apt/config
      Result: True
     Comment: File /etc/cron-apt/config is in the correct state
     Started: 19:51:06.351646
    Duration: 28.622 ms
     Changes:
----------
          ID: create_cron-apt_download_msg
    Function: file.managed
        Name: /etc/cron-apt/mailmsg.d/3-download
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 19:51:06.380372
    Duration: 2.69 ms
     Changes:

Summary for debian
------------
Succeeded: 2
Failed:    1
------------
Total states run:     3
Total run time:  32.132 ms in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusyS...', '/tmp/bgoutputdN...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

```
➜  ~ ls -alh /srv/salt/omv/deploy/cronapt/files
total 16K
drwxr-xr-x 2 root root 4,0K janv. 18 21:13 .
drwxr-xr-x 3 root root 4,0K janv. 18 21:13 ..
-rw-r--r-- 1 root root 2,4K sept. 30 17:53 etc_cron-apt_config.j2
-rw-r--r-- 1 root root  407 janv. 12 13:11 etc_cron-apt_mailmsgd_3-download.j2
```

```
➜  ~ ls -alh /etc/cron-apt
total 44K
drwxr-xr-x  10 root root 4,0K juin  22  2020 .
drwxrwxr-x 107 root root 4,0K janv. 18 21:13 ..
drwxr-xr-x   2 root root 4,0K mai   16  2020 action.d
-rw-r--r--   1 root root 2,1K juin  22  2020 config
drwxr-xr-x   2 root root 4,0K juin  19  2018 config.d
drwxr-xr-x   2 root root 4,0K juin  19  2018 errormsg.d
drwxr-xr-x   2 root root 4,0K juin  19  2018 logmsg.d
drwxr-xr-x   2 root root 4,0K janv. 18 21:38 mailmsg.d
drwxr-xr-x   2 root root 4,0K juin  19  2018 mailonmsgs
drwxr-xr-x   2 root root 4,0K juin  19  2018 syslogmsg.d
drwxr-xr-x   2 root root 4,0K juin  19  2018 syslogonmsgs
```

```
➜  ~ dpkg -l | grep cron
ii  anacron                              2.3-28                              amd64        cron-like program that doesn't go by time
ii  cron                                 3.0pl1-134+deb10u1                  amd64        process scheduling daemon
ii  cron-apt                             0.13.0                              all          automatic update of packages using apt-get
```

**Comment by votdev** [comment]
According to other SaltStack isses `Unable to manage file: none of the specified sources were found` i think your package installation was not successful. Please run `omv-salt stage run sync refresh` and afterwards `omv-salt deploy run cronapt`. Does it fix the issue.

**Comment by Dalan94** [comment]
The commands doesn't works:
```
➜  ~ omv-salt stage run sync refresh
Usage: omv-salt stage run [OPTIONS] NAME
Try "omv-salt stage run --help" for help.

Error: Got unexpected extra argument (refresh)
```

```
➜  ~ omv-salt stage run sync
debian:
    Data failed to compile:
----------
    No matching sls found for 'omv.stage.sync' in env 'base'
```

```➜  ~ omv-salt stage run refresh     
debian:
    Data failed to compile:
----------
    No matching sls found for 'omv.stage.refresh' in env 'base'
```

I tried to re-install the package with dpkg but it doesn't fix the issue:
```
➜  ~ dpkg -i /var/cache/apt/archives/openmediavault_5.5.23-1_all.deb 
(Lecture de la base de données... 304899 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../openmediavault_5.5.23-1_all.deb ...
Dépaquetage de openmediavault (5.5.23-1) sur (5.5.23-1) ...
Paramétrage de openmediavault (5.5.23-1) ...
Creating configuration database ...
Migrating configuration database ...
Setting up Salt environment ...
Processing system modifications ...
Traitement des actions différées (« triggers ») pour rsyslog (8.1901.0-1) ...
Traitement des actions différées (« triggers ») pour openmediavault (5.5.23-1) ...
Restarting engine daemon ...
Updating locale files ...
Updating file permissions ...
Purging internal cache ...
➜  ~ omv-salt deploy run cronapt                                    
debian:
----------
          ID: remove_cron-apt_refrain_file
    Function: file.absent
        Name: /etc/cron-apt/refrain
      Result: True
     Comment: File /etc/cron-apt/refrain is not present
     Started: 21:15:45.237743
    Duration: 0.819 ms
     Changes:   
----------
          ID: create_cron-apt_config
    Function: file.managed
        Name: /etc/cron-apt/config
      Result: True
     Comment: File /etc/cron-apt/config is in the correct state
     Started: 21:15:45.238650
    Duration: 28.483 ms
     Changes:   
----------
          ID: create_cron-apt_download_msg
    Function: file.managed
        Name: /etc/cron-apt/mailmsg.d/3-download
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 21:15:45.267240
    Duration: 2.703 ms
     Changes:   

Summary for debian
------------
Succeeded: 2
Failed:    1
------------
Total states run:     3
Total run time:  32.005 ms

```

**Comment by votdev** [comment]
Please try to reinstall Salt using `apt-get install --reinstall salt-minion salt-common`. If that does not help i have no idea. I never saw that error nor does it seem to be a general problem.

**Comment by Dalan94** [comment]
It's not better after reinstalling salt.
So I commented the new lines in `/srv/salt/omv/deploy/cronapt/default.sls ` and copied the file manually.
I hope it will not happen again.

**Comment by votdev** [comment]
I have absolutely no idea anymore because all files are according your command outputs all there where they should be.

Please try the following commands, maybe one of them will magically fix the issue: `salt-call saltutil.clear_cache` and `salt-call saltutil.sync_all`.

**Comment by Dalan94** [comment]
After the two command, it works !
Thanks !

**Comment by votdev** [comment]
You do not know which command exactly fixed the issue?

**Comment by henkall** [comment]
Sorry to just jump in to this thread but I just want to say: 
Thank you very much...
The two last commands also fixed my problem. I had kind of the same problem.

```
          ID: create_cron-apt_download_msg
    Function: file.managed
        Name: /etc/cron-apt/mailmsg.d/3-download
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 21:15:45.267240
    Duration: 2.703 ms
     Changes:   
```
