### ISSUE TITLE
OMV 5 install docker message not helpfull

### ISSUE THREAD

**Issue by Samuel12321** [openmediavault/openmediavault#506]
not very helpfull, Should say installing docker
![Annotation 2019-11-12 211558](https://user-images.githubusercontent.com/35312698/68653930-af707100-0591-11ea-9443-0035702054de.png)

**Comment by votdev** [comment]
Please report here: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-docker-gui because this plugin is not maintained by the OMV project.

**Comment by ryecoaaron** [comment]
I accidentally typed 1 instead of 0 - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/var/www/openmediavault/js/omv/module/admin/system/omvextras/Settings.js#L311. Not hard to fix.

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/f9818ed2ad6d678da79bf0d0bf3edd14b2367a3f
