### ISSUE TITLE
Actual network configuration and Web-GUI out of sync

### ISSUE THREAD

**Issue by m4tt075** [openmediavault/openmediavault#507]
### Description of issue/question
Installation of a new PCIe device screws up network configuration in Web-GUI

### Steps to reproduce issue
- I use a motherboard with two ethernet ports, originally labelled as `eno1` and `enp7s0`, respectively
- I've added a new PCIe card (does not matter which one). This apparently changed the labeling of the second network port to `enp8s0`, causing LOTS of pain and time to understand what happened. But that is another story...
- The web-GUI still showed the obsolete `enp7s0` port. I've deleted it and wanted to create a new `enp8s0` port. That threw an error message, that the port could not be configured.
- Logging in via `ssh` and using `ifconfig` I could see that `enp8s0` was actually up and running correctly. 
- However, in the Web-GUI only `eno1` appears. The state is "inconsistent". 

Could you let me know how to correct that?

### Versions report
OMV 4.x.x (latest)

**Comment by votdev** [comment]
The network device naming is done by the kernel. The [consistent device naming](https://en.wikipedia.org/wiki/Consistent_Network_Device_Naming) should prevent such a renaming, but under special circumstances it is still possible. It seems you hit this special case.

The WebUI shows the device names stored in the database, so this is correct. How does the error message look when you try to add the configuration for the new device? Can you post it here, please?

**Comment by m4tt075** [comment]
Sure. Here the error message:
```shell
Fehler #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; systemctl start 'networking' 2>&1' with exit code '1': Job for networking.service failed because the control process exited with error code.
See "systemctl status networking.service" and "journalctl -xe" for details. in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/system/systemctl.inc(86): OMV\System\Process->execute(Array, 1)
#1 /usr/share/php/openmediavault/system/systemctl.inc(146): OMV\System\SystemCtl->exec('start', NULL, false)
#2 /usr/share/openmediavault/engined/module/networking.inc(44): OMV\System\SystemCtl->start()
#3 /usr/share/openmediavault/engined/rpc/config.inc(194): OMVModuleNetworking->startService()
#4 [internal function]: OMVRpcServiceConfig->applyChanges(Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(565): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatus7l...', '/tmp/bgoutputZl...')
#8 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#9 /usr/share/openmediavault/engined/rpc/config.inc(213): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#10 [internal function]: OMVRpcServiceConfig->applyChangesBg(Array, Array)
#11 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#12 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#13 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#14 {main}
```
I guess it fails, because it tries to create an interface that exists already and is up and running...

**Comment by mi-hol** [comment]
4.x is EOL
