### ISSUE TITLE
Smart Schedule test be like Schedule Jobs (4.x) (enchancement)

### ISSUE THREAD

**Issue by fumantsu** [openmediavault/openmediavault#508]
### Description of issue/question
The SMART Schedule test schedules window is not like like Schedule Jobs, which is not convinient. I would be nice to be like it (and be standarized in general as window).

### Versions report
4.1.27.1

**Comment by votdev** [comment]
I don't understand what you want to change. The SMART scheduled job looks like the other window except the ability to enter an individual command line which is absolutely not necessary in SMART. The windows shows the fields that make sense to create a scheduled SMART test.

**Comment by fumantsu** [comment]
yea, I will give some screenshots to make it easier. 
![image](https://user-images.githubusercontent.com/7147643/68840325-cc589180-06c2-11ea-99be-b02afe18f4d5.png)
![image](https://user-images.githubusercontent.com/7147643/68840328-cf538200-06c2-11ea-8eea-4b94812f15d0.png)

**Comment by votdev** [comment]
SMART scheduled jobs (run via [smartd](https://www.smartmontools.org/browser/trunk/smartmontools/smartd.conf.5.in)) do not provide that detailed configuration.

**Comment by fumantsu** [comment]
So they are not set via cron jobs (using of course smartd)?

**Comment by votdev** [comment]
Yes
