### ISSUE TITLE
Raspberry Pi 4 lacks WiFi support.

### ISSUE THREAD

**Issue by lucasff** [openmediavault/openmediavault#509]
### Description of issue/question
Install latest OpenMediaVault 4.x in a Raspberry Pi 4. You won't be able to activate any WLAN interface.

### Steps to reproduce issue
- See Description

### Possible fix
Distribute OpenMediaVault with a bigger boot partition on the SDcard, so the firmware can be updated and support for brcm80211 can be enabled. The Raspbian people recommend at least 400MB for the boot partition, from a previous 64MB.

**Comment by ryecoaaron** [comment]
The SBC OMV images including the RPi image are third party images.  With OMV 5, you will download the Raspbian Buster Lite image and install using the script - https://github.com/OpenMediaVault-Plugin-Developers/installScript.  So, it should work for anything the RPi foundation sees fit.
