### ISSUE TITLE
OMV 4 + Raspberry Pi 4 new installation kernel and kernel modules mismatch

### ISSUE THREAD

**Issue by toMeloos** [openmediavault/openmediavault#513]
### Description of issue/question

I've read the warnings on the SourceForge page carefully. I believe this is not about kernel `4.9` versus `4.14`!

On a fresh install of OMV 4 on a Raspberry Pi 4B 4GB, the kernel seems to be upgraded to `4.19.50-v7l+`. However the only kernel modules available seem to be for `4.14.47-rockchip`. The only directory inside `/lib/modules/` is that of `4.14.47-rockchip`, while I would expect it to be for 4.19.

I didn't even notice it initially. OMV 4 seems fine. Installing Docker however fails because the docker daemon won't start since it it's missing the `ip_tables` kernel module. Running `lsmod` also returns zero results. Booting also shows FAILED to start Realtek H5 bluetooth support.

### Steps to reproduce issue

1. Download, md5sum and burn to SD card using Etcher of latest `OMV_4_Raspberry_Pi_2_3_3Plus_4.img.xz` image.
2. Plug the SD card into the Raspberry Pi 4 and power it.
3. Wait for it to boot, to install OMV, to reboot and to print the OMV MOTD
4. Unplug it, remove the SD card, mount the disk on a linux machine, edit the NGINX configuration and fix the IPv6 `listen [::]:80` issue since the webserver wouldn't start automatically, as recommended in #477.
5. Turn the Raspberry Pi 4 back on and log into OMV now that the web interface is operational.
6. Add a user, allow SSH and log in remotely.
7. Run `uname -a && lsmod && ls /lib/modules/`.

### Expected result

I would expect one of the following two outcomes:

1. OMV 4 on Raspberry Pi 4 is pinned to and running the `4.14.47-rockchip` kernel, as these are the modules installed.
2. OMV 4 on Raspberry Pi 4 is running the `4.19.50-v7l+` kernel and it's modules are installed.

**Comment by ryecoaaron** [comment]
This is a third party image that is not maintained anymore.  I recommend this:  https://forum.openmediavault.org/index.php/Thread/29591-Raspberry-pi-wifi-connecting-to-2-4-instead-of-5ghz/?postID=219499#post219499
