### ISSUE TITLE
Samba avahi service is not reloaded

### ISSUE THREAD

**Issue by elfhack** [openmediavault/openmediavault#516]
This one's really simple. If I reconfigure samba to for example, use a different share for time machine, avahi will not pick up the changes until samba gets disabled and then re-enabled

**Comment by votdev** [comment]
Which version are we talking about?

**Comment by elfhack** [comment]
This is on newest OMV 5

**Comment by votdev** [comment]
Can you please describe step-by-step how to reproduce this behavior.

**Comment by elfhack** [comment]
Sure.

Let's say we have 2 shared folders, test1 and test2. We add them both to samba, and samba itself is disabled. Then we mark test1 as avaible to time machine. We hit save&apply. Samba is now started and avahi got it's service file, and is now broadcasting that test1 is a time machine target. 

We now reconfigure samba, disabling test1 as a time machine target, but enabling test2 as a time machine target. We hit save, then apply. Samba gets restarted, and has a new config. However the avahi .service is untouched, and is still broadcasting test1 as a time machine target, while test2 is nowhere to be found. 

We now turn off samba altogether, save & apply - now the avahi service file disappears. We then enable samba, save&apply, samba is started, and the avahi service file is recreated properly

As a personal note, I'd like to say that it would just be better to make samba to this by itself, or at least give the user the option for that (eg omv NOT making the service file, and lettings samba communicate with avahi via dbus as per the default).

**Comment by votdev** [comment]
> As a personal note, I'd like to say that it would just be better to make samba to this by itself, or at least give the user the option for that (eg omv NOT making the service file, and lettings samba communicate with avahi via dbus as per the default).

OMV does it it's own way to be able to allow the user to customize the announcement text.

**Comment by votdev** [comment]
Fixed in openmediavault 5.1.1

**Comment by elfhack** [comment]
@votdev Could you elaborate what you mean about "customizing the annoucement text"? If you mean the hostname field, where in by default OMV gives a (SMB/CIFS) suffix, then I don't think this is still necessary, as I believe it was primarily used to differenciate between SMB and AFS on MacOS system. Since AFS is deprecated, and not even present by default on OMV5, I don't think there's a huge need for this anymore.

**Comment by votdev** [comment]
That might be right, but at the moment i do not see any necessity to change the working implementation.
