### ISSUE TITLE
Enable additional arguments for wsdd

### ISSUE THREAD

**Issue by elfhack** [openmediavault/openmediavault#517]
I need to add additional options to wsdd, it seems the discovery packets get lost unless i specify my interface by hand (probably has to do with my k8s CNI interface doing freaky stuff)

Can I ask for a OMV_SAMBA_WSDD_OPTS?
(This is on OMV5)

**Comment by votdev** [comment]
I am currently not sure (need to check that), but I think you can use systemd to override unit file settings.

**Comment by elfhack** [comment]
Yeah I can overlay my own .service, and make my own settings file in /etc/default (since salt will overwrite /etc/default/wsdd on provision). I just thought this would be a cleaner way.

**Comment by votdev** [comment]
By the way, does it make sense to set the interface automatically, e.g. by using the interface with the default route?

**Comment by votdev** [comment]
To apply custom options open `/etc/default/openmediavault` and add the variable `OMV_WSDD_OPTIONS`. After that run `omv-salt stage run prepare`to recreate the pillar data. After that run `omv-salt deploy run samba`.

**Comment by votdev** [comment]
Available in openmediavault 5.1.1.

**Comment by elfhack** [comment]
> By the way, does it make sense to set the interface automatically, e.g. by using the interface with the default route?

I'm not sure, but I can imagine someone using their machine as a gateway (having more than 2 interfaces of course) and not wanting to announce their samba server to the internet
