### ISSUE TITLE
How do I use MBR partition installation

### ISSUE THREAD

**Issue by wangchang54** [openmediavault/openmediavault#518]
My motherboard is too old to support MBR startup, and the installation program USES GPT by default. Is there any useful solution? Thank you very much!

**Comment by ryecoaaron** [comment]
Install Debian first and then follow the guide to install OMV - https://forum.openmediavault.org/index.php/Thread/25062-Install-OMV5-on-Debian-10-Buster/ or use my install script - https://github.com/OpenMediaVault-Plugin-Developers/installScript

**Comment by wangchang54** [comment]
thank you

**Comment by votdev** [comment]
Please use the [forum](https://forum.openmediavault.org) to ask such questions next time.
