### ISSUE TITLE
Setting MTU on VLAN interface

### ISSUE THREAD

**Issue by Pro-Idler** [openmediavault/openmediavault#519]
With the release of version 4.1.27, the option to change the MTU on a VLAN interface was removed.
I assume the reason for this is because of a misunderstanding of how Linux handles MTU settings on interfaces.
The MTU of a VLAN interface must be the same or lower than the MTU setting of the parent interface.

For example, trying to set a VLAN interface to anything higher than the default 1500 while not changing the parent interface will make it seem like it's a broken feature (which it's not).
The setting itself has to be made kind of backwards. If you want just one VLAN interface with 9000 MTU, you have to set the parent interface to 9000 and ALL other VLAN interfaces to 1500.
This is because changing the MTU of the parent interface automatically changes the default MTU of all VLAN interfaces attached to it.

As someone using this feature to enable jumbo frames on a specific VLAN, I now have to resort to editing the config.xml file manually, which seems unnecessary for something that used to just work.
Maybe the GUI could hide the MTU on VLAN interfaces if the parent interface uses the default MTU?

**Comment by votdev** [comment]
The form field is shown again.
