### ISSUE TITLE
Use fstrim.timer instead of discard fstab option

### ISSUE THREAD

**Issue by elfhack** [openmediavault/openmediavault#520]
Multiple linux distros discourage using the discard option because of it's performance penalty on fsync() operations. Instead fstrim.timer should be enabled - it's provided by util-linux

https://askubuntu.com/questions/1034169/is-trim-enabled-on-my-ubuntu-18-04-installation
https://wiki.debian.org/SSDOptimization#Mounting_SSD_filesystems
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/ch02s04.html

**Comment by votdev** [comment]
https://wiki.archlinux.org/index.php/Solid_state_drive
http://blog.neutrino.es/2013/howto-properly-activate-trim-for-your-ssd-on-linux-fstrim-lvm-and-dmcrypt/
