### ISSUE TITLE
Set the format of Monit messages to include context.

### ISSUE THREAD

**Issue by Julian-O** [openmediavault/openmediavault#523]
### Description of issue/question

OMV uses monit to take care of monitoring services and issueing alerts.

However, there is little mention of monit in the documentation, and the emails from monit are short of context. Here is an example:

    Subject: [nas.lan] monit alert --  Resource limit succeeded rootfs

    Resource limit succeeded Service rootfs 
    
    	Date:        Sat, 30 Nov 2019 01:52:33
    	Action:      alert
    	Host:        nas
    	Description: space usage test succeeded [current space usage=29.0%]
    
    Your faithful employee,
    Monit

The administrator is expected to have enough background knowledge to understand that monit is part of OMV, and why they are being contacted.

I am proposing that the monit format be modified to include more context.

The file `deb/openmediavault/srv/salt/omv/deploy/monit/files/etc-monit-monitorrc.j2` should be changed.

The line:

     set mail-format { from: {{ email_config.sender }} }

should read: 

    set mail-format {
        from: {{ email_config.sender }}
        subject: $HOST: OpenMediaVault $ACTION: $EVENT
        message: openmediavault is running on $HOST.
    
                 Its monitoring system detected:
                 Event: $EVENT
                 Description: $DESCRIPTION
                 Service: $SERVICE
                 Date: $DATE
    
                 This triggered the monitoring system to: $ACTION.
    
                 This email was sent to the email address specified under System/Settings in the openmediavault web interface.
    }

So, why don't I just make the change and submit it as a PR?

Well, I haven't (yet) built a test environment where I can try this out, and I haven't yet understood how this config file is deployed. (I imagined I need to build a whole deb, and deploy it as a new installation? Sounds painful.) Note: **This means I haven't tested the above text. It is a first draft.**

Also, I haven't understood the translation system. Is an English-only version of this acceptable? If not, where are the translations deployed?

(This issue is thematically related to #505.)

### Steps to reproduce issue
* Turn on email notifications.
* Damage the server in a way that monit will notice (e.g. fill up the OS drive)
* View the resulting email.

### Versions report
4.1.27-1

**Comment by votdev** [comment]
Please submit PR only for OMV5, OMV4 does not get new features anymore.
Note that the OMV5 configuration build process is based on Salt now.

**Comment by Julian-O** [comment]
Thanks. The proposed changes are against the current files in Github, so I believe the issue applies to OMV5 as well (although I discovered in on a production machine running OMV4, which is why I quote it in the version number.)

The proposed edit is to a Salt file which configures and deploys the monitrc file. I think that is what is required in OMV5, but I am still new to the code, so maybe I have misunderstood.

**Comment by votdev** [comment]
Can you please post the original and modified email content the better compare them and to see if it is worth to continue this issue.

**Comment by Julian-O** [comment]
An example of the confusing message (as above):

    Subject: [nas.lan] monit alert --  Resource limit succeeded rootfs

    Resource limit succeeded Service rootfs 
    
    	Date:        Sat, 30 Nov 2019 01:52:33
    	Action:      alert
    	Host:        nas
    	Description: 
    
    Your faithful employee,
    Monit


A mockup of what I believe the new message will look like is below:

    Subject: [nas.lan] OpenMediaValue alert: Resource limit succeeded rootfs

    openmediavault is running on nas.lan.

    Its monitoring system detected:
    Event: Resource limit succeeded rootfs
    Description: space usage test succeeded [current space usage=29.0%]
    Service: rootfs 
    Date: Sat, 30 Nov 2019 01:52:33

    This triggered the monitoring system to: alert

    This email was sent to the email address specified under System/Settings in the openmediavault web interface.


I think I should have put $HOST in the subject should have in square brackets to make this appear this way, sorry.

Of course, you should feel free to edit the text. My goals included:
* Making it clear that OMV is the agent behind the email.
* Not referring to monit, which is a behind-the-scenes module the admin does not need to know about. (At the very least, not making monit's role assumed knowledge.)
* This wasn't a directly requested email, and might end up being spam to a person who doesn't want it (e.g. someone who is no longer maintaining the NAS or has forgotten it exists). It should include details of *why* they are receiving this email and how they can stop receiving them.
