### ISSUE TITLE
OMV fail to set permissions on shared folder with multi levels path

### ISSUE THREAD

**Issue by SimoB** [openmediavault/openmediavault#528]
### Description of issue/question

OMV fail to set permissions on shared folder with multi levels path

### Steps to reproduce issue

Add a shared folder with multi level path ie:

/Shares/Arc

permission on "Shares" are "drwx------ 4 root root" so "Arc" is not accessible to "users" group

![Annotazione 2019-12-06 160321](https://user-images.githubusercontent.com/4073645/70332573-37b8fd80-1842-11ea-853b-299d78bdf524.png)
![Annotazione 2019-12-06 160204](https://user-images.githubusercontent.com/4073645/70332586-3e477500-1842-11ea-8b51-66a47a685fef.png)
![Annotazione 2019-12-06 160244](https://user-images.githubusercontent.com/4073645/70332590-41426580-1842-11ea-8010-e0b43f5e8484.png)
![Annotazione 2019-12-06 160403](https://user-images.githubusercontent.com/4073645/70332598-44d5ec80-1842-11ea-82dc-2c314112e318.png)

### Versions report
[report.txt](https://github.com/openmediavault/openmediavault/files/3932706/report.txt)

**Comment by votdev** [comment]
This is strange because when you create a new shared folder the group is set to `users`. See https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/sharemgmt.inc#L339.

As workaround simply use the `ACL`dialog and set the file system permissions manually.

**Comment by SimoB** [comment]
> This is strange because when you create a new shared folder the group is set to `users`. See https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/sharemgmt.inc#L339.
> 
> As workaround simply use the `ACL`dialog and set the file system permissions manually.

Is set to users only on the last level folder, so "Archive" folder is ok, is the upper folder "Shares" that is not ok, also the ACL dialog do not show the upper folders at all, so it's not possible to fix the problem that way.

p.s.
I did fix the problem myself creating the "Shares" folder via ssh as sudo with permission drvxr-xr-x- and everything is working now, but that's not the point imho.

If omv cannot manage permissions on a multilevel folder path just do not allow them to be created in the interface.

**Comment by SimoB** [comment]
Sorry if I am wrong, but there is not -R option in PHP chgrp, so I don't see how this should work 🤔

**Comment by votdev** [comment]
Yes, it does not work for folders with a depth > 1. But this should bee say to fix.

**Comment by SimoB** [comment]
So I see in the code the permission 0755 is saved to a var in https://github.com/openmediavault/openmediavault/blob/5edb6b3a487e1c9799978eff4f17d2591590cf92/deb/openmediavault/usr/share/openmediavault/engined/rpc/sharemgmt.inc#L307 and used later https://github.com/openmediavault/openmediavault/blob/5edb6b3a487e1c9799978eff4f17d2591590cf92/deb/openmediavault/usr/share/openmediavault/engined/rpc/sharemgmt.inc#L330

but as suggested here https://www.php.net/manual/en/function.mkdir.php#96990 chmod needs to be called on every folder in the path when the recursive option of mkdir is used

Also in the mkdir I think should be better for readability to use 0755 also instead of 0700 https://github.com/openmediavault/openmediavault/blob/5edb6b3a487e1c9799978eff4f17d2591590cf92/deb/openmediavault/usr/share/openmediavault/engined/rpc/sharemgmt.inc#L323

**Comment by ryecoaaron** [comment]
What if a sharedfolder is created at /level1 with x permissions and you create another sharedfolder at /level1/level2 with y permissions.  On one hand, if /level1 is too restrictive, you won't be able to access /level1/level2.  On the other hand, you can't assume /level1 permissions should y permissions like /level1/level2.

And directories are create at 700 because that is the most restrictive you can make a sharedfolder.  They are changed to the selected permissions a few lines later.  You shouldn't default them to wide open permissions because people may want them more restrictive.

**Comment by SimoB** [comment]
> What if a sharedfolder is created at /level1 with x permissions and you create another sharedfolder at /level1/level2 with y permissions. On one hand, if /level1 is too restrictive, you won't be able to access /level1/level2. On the other hand, you can't assume /level1 permissions should y permissions like /level1/level2.
> 
> And directories are create at 700 because that is the most restrictive you can make a sharedfolder. They are changed to the selected permissions a few lines later. You shouldn't default them to wide open permissions because people may want them more restrictive.

Ok, but you need at least 711 to allow traversing the folder tree, last folder, the one that is shared is not accessible otherwise, even if you assign the group to users.

**Comment by ryecoaaron** [comment]
I understand what it takes to traverse subdirectories but 700 is an option for a sharedfolder. So, if I ask for 700 on a sharedfolder, it shouldn’t be set for 711. 

And the last folder should be what you ask for in the permissions dropdown not just 775.

**Comment by SimoB** [comment]
@ryecoaaron 775 is what is in the code now as default, 711 is needed for only for parent folders, if you create a sharedfolder with 700 I think is because you want take the ownership via the ACL menu with your user (default is own by root), but you always need to have the parent folders as 711 because they are owned by root (and you can't change that via the ACL menu).

**Comment by votdev** [comment]
If you have a sub folder as shared folder then why do you not create a share of the root folder, then you can administrate it via UI. That is the main workflow the UI is implemented for. Because of that i do not think it is a good idea to modify a upper directory because you can not be sure that another share want to have other privileges. The UI nor the backend can take care of your directory structure and because of that it will never do assumptions on the privileges. I think the current implementation is exactly reflecting the workflow it is designed for.

**Comment by SimoB** [comment]
@votdev I strongly disagree with that, I don't wont to share the upper root folder.

If you don't want to mess with permissions just do not allow multi level folders to be created that way, in the "Add shared folder" UI.

Now if I create a new shared folder with a path like `/Parent/Folder` and `Parent` does not exists permission on `Parent` are set as 700 and the `Folder` will be not accessible, that's a bug.

We can discuss days on what is the best way to solve this problem but please don't say it's fine, it's the intended workflow, because it is not.

**Comment by votdev** [comment]
I can not reproduce this behaviour, i can copy a file into the shared folder directory via SMB.

```
root@omv5box:/home/vagrant/openmediavault/openmediavault# ls -alh /srv/dev-disk-by-id-scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-1-part1
total 28K
drwxr-xr-x  4 root root 4.0K Dec  9 10:29 .
drwxr-xr-x  6 root root 4.0K Dec  2 09:46 ..
drwx--x---+ 3 root root 4.0K Dec  9 10:16 bar
drwx------  2 root root  16K Nov 20 16:48 lost+found
root@omv5box:/home/vagrant/openmediavault/openmediavault# ls -alh /srv/dev-disk-by-id-scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-1-part1/bar/
total 12K
drwx--x---+ 3 root root 4.0K Dec  9 10:16 .
drwxr-xr-x  4 root root 4.0K Dec  9 10:29 ..
drwx--x---+ 3 root root 4.0K Dec  9 10:30 baz
root@omv5box:/home/vagrant/openmediavault/openmediavault# ls -alh /srv/dev-disk-by-id-scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-1-part1/bar/baz/
total 12K
drwx--x---+ 3 root root  4.0K Dec  9 10:30 .
drwx--x---+ 3 root root  4.0K Dec  9 10:16 ..
drwxrwsr-x  2 root users 4.0K Dec  9 10:31 foo
root@omv5box:/home/vagrant/openmediavault/openmediavault# ls -alh /srv/dev-disk-by-id-scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-1-part1/bar/baz/foo/
total 4.4M
drwxrwsr-x  2 root users 4.0K Dec  9 10:31 .
drwx--x---+ 3 root root  4.0K Dec  9 10:30 ..
-rw-rw-r--  1 vot  users 4.4M Dec  9 09:07 teuthology.log
```
