### ISSUE TITLE
USB devices not showing up when creating RAID

### ISSUE THREAD

**Issue by mike391** [openmediavault/openmediavault#529]
I know this was a recent fix to exclude USB devices from available disks when creating a RAID. However, sometimes this is our only option regardless of how unreliable it can be.  It would be more convenient to have a toggle "Show USB disks (DANGEROUS)" or something of the sort. That way by default they arent shown but a user is able to enable them if needed.
 Its a real pain to go into command line to add these USB disks when it really should be available through the WEBUI.

**Comment by ryecoaaron** [comment]
No one will stop using usb disks for
raid if it is just a warning. If you really must make the bad decision to use usb disks, it is one command to create the array. You can do everything else in the web interface. I still have yet to hear a valid reason for using usb disks in a raid array.

**Comment by votdev** [comment]
If you want to do this please use the CLI, we have had enough broken RAIDs in the forum, thus the UI will never support USB devices in the RAID page.
