### ISSUE TITLE
Problem in Mounting FileSystem in OMV5

### ISSUE THREAD

**Issue by vinayak-goyal** [openmediavault/openmediavault#534]
### Description of issue/question
I have installed OMV5 on Single Board Computer, Orange Pi Win Plus using documentation provided here[https://github.com/OpenMediaVault-Plugin-Developers/docs/blob/master/Adden-A-Installing_OMV5_on_Armbian.pdf]

Installation is on Armbian based on Buster. Everything was followed step by step matching exactly as was described in the Guide.

Now, I have attached 2x128GB flash drives to my OrangePiWinPlus, wiped it from OMV GUI, made a File System on them of ext4, when clicking on Mount, I'm getting this error.

```Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run fstab 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/utils/path.py:265: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working if not isinstance(exes, collections.Iterable): /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly *salt.utils.args.get_function_argspec(original_function) orangepiwin: ---------- ID: create_filesystem_mountpoint_3daff230-090b-4294-bc36-e8ef09b1da4d Function: file.accumulated Result: True Comment: Accumulator create_filesystem_mountpoint_3daff230-090b-4294-bc36-e8ef09b1da4d for file /etc/fstab was charged by text Started: 17:11:27.263985 Duration: 4.367 ms Changes: ---------- ID: mount_filesystem_mountpoint_3daff230-090b-4294-bc36-e8ef09b1da4d Function: mount.mounted Name: /srv/dev-disk-by-label-FMV Result: False Comment: mount: /srv/dev-disk-by-label-FMV: wrong fs type, bad option, bad superblock on /dev/sda1, missing codepage or helper program, or other error. Started: 17:11:27.272247 Duration: 1144.131 ms Changes: ---------- ID: append_fstab_entries Function: file.blockreplace Name: /etc/fstab Result: True Comment: Changes were made Started: 17:11:28.420482 Duration: 66.508 ms Changes: ---------- diff: --- +++ @@ -1,5 +1,5 @@ UUID=351e454d-f822-4fed-97e8-c338fe6ffec8 / ext4 defaults,noatime,nodiratime,commit=600,errors=remount-ro 0 1 tmpfs /tmp tmpfs defaults,nosuid 0 0 # >>> [openmediavault] -/dev/disk/by-label/FOMV1 /srv/dev-disk-by-label-FOMV1 ext4 defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2 +/dev/disk/by-label/FMV /srv/dev-disk-by-label-FMV ext4 defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2 # <<< [openmediavault] Summary for orangepiwin ------------ Succeeded: 2 (changed=1) Failed: 1 ------------ Total states run: 3 Total run time: 1.215 s```

Kindly assist at the earliest. I am making a system for my office and downtime is messing work hours. Really appreciate your time and help.

Regards

**Comment by votdev** [comment]
I looks like `/dev/sda1`is in a bad condition which let the system not mount the filesystem.

**Comment by votdev** [comment]
Do you have wiped the devices before creating the filesystem? It sometimes happens that old fragments of whatever (LVM, MD, filesystem headers, boot manager, ...) confuses the system which leads in a filesystem that is not mountable. Don't know the reasons, but saw that many times.

**Comment by vinayak-goyal** [comment]
Yes.. everything was wiped before making the new file system but the issue was persistent.
Seems like the issue was with the ext4 filesystem.
Drives mounted fine when changed file system to btrfs.

But facing file corruption at a large scale with this fs. Don't know if this issue is with fs or otherwise, akthough btrfs is known for most secure fs with least chances of corrupted files. 
Haven't faced such large scale file corruptions, ever till this.

OMV is most of the time out of sync with time although ntp time servers are set, and file versioning isn't working to recover previous versions of corrupted files.


I figured out maybe file versioning will work if I install rsnapshot(Don't know for sure).
rsnapshot isn't installing giving this below error.

`Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  libbluetooth3 libmm-glib0 libndp0 libnm0 libteamdctl0
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  liblchown-perl rsnapshot
The following NEW packages will be installed:
  liblchown-perl openmediavault-rsnapshot rsnapshot
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 171 kB of archives.
After this operation, 819 kB of additional disk space will be used.
Err:1 http://httpredir.debian.org/debian buster/main arm64 liblchown-perl arm64 1.01-3+b5
  Could not resolve 'httpredir.debian.org'
Ign:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
Ign:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
  Could not resolve 'dl.bintray.com'
Err:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
  Could not resolve 'httpredir.debian.org'

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-rsnapshot 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following packages were automatically installed and are no longer required:
  libbluetooth3 libmm-glib0 libndp0 libnm0 libteamdctl0
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  liblchown-perl rsnapshot
The following NEW packages will be installed:
  liblchown-perl openmediavault-rsnapshot rsnapshot
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 171 kB of archives.
After this operation, 819 kB of additional disk space will be used.
Err:1 http://httpredir.debian.org/debian buster/main arm64 liblchown-perl arm64 1.01-3+b5
  Could not resolve 'httpredir.debian.org'
Ign:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
Ign:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
  Could not resolve 'dl.bintray.com'
Err:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
  Could not resolve 'httpredir.debian.org'
Unable to correct missing packages.
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/libl/liblchown-perl/liblchown-perl_1.01-3+b5_arm64.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/r/rsnapshot/rsnapshot_1.4.2-1_all.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-rsnapshot/openmediavault-rsnapshot_5.0.1_all.deb  Could not resolve 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-rsnapshot 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following packages were automatically installed and are no longer required:
  libbluetooth3 libmm-glib0 libndp0 libnm0 libteamdctl0
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  liblchown-perl rsnapshot
The following NEW packages will be installed:
  liblchown-perl openmediavault-rsnapshot rsnapshot
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 171 kB of archives.
After this operation, 819 kB of additional disk space will be used.
Err:1 http://httpredir.debian.org/debian buster/main arm64 liblchown-perl arm64 1.01-3+b5
  Could not resolve 'httpredir.debian.org'
Ign:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
Ign:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
  Could not resolve 'dl.bintray.com'
Err:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
  Could not resolve 'httpredir.debian.org'
Unable to correct missing packages.
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/libl/liblchown-perl/liblchown-perl_1.01-3+b5_arm64.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/r/rsnapshot/rsnapshot_1.4.2-1_all.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-rsnapshot/openmediavault-rsnapshot_5.0.1_all.deb  Could not resolve 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-rsnapshot 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following packages were automatically installed and are no longer required:
  libbluetooth3 libmm-glib0 libndp0 libnm0 libteamdctl0
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  liblchown-perl rsnapshot
The following NEW packages will be installed:
  liblchown-perl openmediavault-rsnapshot rsnapshot
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 171 kB of archives.
After this operation, 819 kB of additional disk space will be used.
Err:1 http://httpredir.debian.org/debian buster/main arm64 liblchown-perl arm64 1.01-3+b5
  Could not resolve 'httpredir.debian.org'
Ign:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
Ign:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
  Could not resolve 'dl.bintray.com'
Err:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
  Could not resolve 'httpredir.debian.org'
Unable to correct missing packages.
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/libl/liblchown-perl/liblchown-perl_1.01-3+b5_arm64.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/r/rsnapshot/rsnapshot_1.4.2-1_all.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-rsnapshot/openmediavault-rsnapshot_5.0.1_all.deb  Could not resolve 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-rsnapshot 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following packages were automatically installed and are no longer required:
  libbluetooth3 libmm-glib0 libndp0 libnm0 libteamdctl0
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  liblchown-perl rsnapshot
The following NEW packages will be installed:
  liblchown-perl openmediavault-rsnapshot rsnapshot
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 171 kB of archives.
After this operation, 819 kB of additional disk space will be used.
Err:1 http://httpredir.debian.org/debian buster/main arm64 liblchown-perl arm64 1.01-3+b5
  Could not resolve 'httpredir.debian.org'
Ign:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
Ign:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
  Could not resolve 'dl.bintray.com'
Err:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
  Could not resolve 'httpredir.debian.org'
Unable to correct missing packages.
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/libl/liblchown-perl/liblchown-perl_1.01-3+b5_arm64.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/r/rsnapshot/rsnapshot_1.4.2-1_all.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-rsnapshot/openmediavault-rsnapshot_5.0.1_all.deb  Could not resolve 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-rsnapshot 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following packages were automatically installed and are no longer required:
  libbluetooth3 libmm-glib0 libndp0 libnm0 libteamdctl0
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  liblchown-perl rsnapshot
The following NEW packages will be installed:
  liblchown-perl openmediavault-rsnapshot rsnapshot
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 171 kB of archives.
After this operation, 819 kB of additional disk space will be used.
Err:1 http://httpredir.debian.org/debian buster/main arm64 liblchown-perl arm64 1.01-3+b5
  Could not resolve 'httpredir.debian.org'
Ign:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
Ign:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
  Could not resolve 'dl.bintray.com'
Err:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
  Could not resolve 'httpredir.debian.org'
Unable to correct missing packages.
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/libl/liblchown-perl/liblchown-perl_1.01-3+b5_arm64.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/r/rsnapshot/rsnapshot_1.4.2-1_all.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-rsnapshot/openmediavault-rsnapshot_5.0.1_all.deb  Could not resolve 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-rsnapshot 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following packages were automatically installed and are no longer required:
  libbluetooth3 libmm-glib0 libndp0 libnm0 libteamdctl0
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  liblchown-perl rsnapshot
The following NEW packages will be installed:
  liblchown-perl openmediavault-rsnapshot rsnapshot
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 171 kB of archives.
After this operation, 819 kB of additional disk space will be used.
Err:1 http://httpredir.debian.org/debian buster/main arm64 liblchown-perl arm64 1.01-3+b5
  Could not resolve 'httpredir.debian.org'
Ign:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
Ign:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
  Could not resolve 'dl.bintray.com'
Err:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
  Could not resolve 'httpredir.debian.org'
Unable to correct missing packages.
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/libl/liblchown-perl/liblchown-perl_1.01-3+b5_arm64.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/r/rsnapshot/rsnapshot_1.4.2-1_all.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-rsnapshot/openmediavault-rsnapshot_5.0.1_all.deb  Could not resolve 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-rsnapshot 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following packages were automatically installed and are no longer required:
  libbluetooth3 libmm-glib0 libndp0 libnm0 libteamdctl0
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  liblchown-perl rsnapshot
The following NEW packages will be installed:
  liblchown-perl openmediavault-rsnapshot rsnapshot
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 171 kB of archives.
After this operation, 819 kB of additional disk space will be used.
Err:1 http://httpredir.debian.org/debian buster/main arm64 liblchown-perl arm64 1.01-3+b5
  Could not resolve 'httpredir.debian.org'
Ign:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
Ign:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
  Could not resolve 'dl.bintray.com'
Err:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
  Could not resolve 'httpredir.debian.org'
Unable to correct missing packages.
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/libl/liblchown-perl/liblchown-perl_1.01-3+b5_arm64.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/r/rsnapshot/rsnapshot_1.4.2-1_all.deb  Could not resolve 'httpredir.debian.org'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-rsnapshot/openmediavault-rsnapshot_5.0.1_all.deb  Could not resolve 'dl.bintray.com'
E: Aborting install.
<<< *************************************
`

**Comment by votdev** [comment]
> OMV is most of the time out of sync with time although ntp time servers are set, and file versioning isn't working to recover previous versions of corrupted files.

Do you run an internal NTP? If you use an external one, then i do not wonder that it does not work because your system seems to have no connection to the internet, otherwise this error would not occur: `Could not resolve 'httpredir.debian.org'`.

Please make sure to wipe the disk with `secure` mode, IMO this is one of the reasons why you can not mount the filesystem.

**Comment by vinayak-goyal** [comment]
But orangePi is able to connect to internet.. sudo apt-get update and apt-get updrage working perfectly

Does omv need other settings to connect to internet apart from the server itself? If yes.. how does it need to be done.

**Comment by votdev** [comment]
> But orangePi is able to connect to internet.. sudo apt-get update and apt-get updrage working perfectly
> 
> Does omv need other settings to connect to internet apart from the server itself? If yes.. how does it need to be done.

Don't know what you are talking about, but the command output you posted above clearly says it can not resolve HTTP addresses, that's an indication that the DNS of your system does not work.

```
Could not resolve 'httpredir.debian.org'
Ign:2 dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
Ign:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
Err:2 dl.bintray.com/openmediavault-plugin-developers/usul buster/main arm64 openmediavault-rsnapshot all 5.0.1
Could not resolve 'dl.bintray.com'
Err:3 http://httpredir.debian.org/debian buster/main arm64 rsnapshot all 1.4.2-1
Could not resolve 'httpredir.debian.org'
Unable to correct missing packages.
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/libl/liblchown-perl/liblchown-perl_1.01-3+b5_arm64.deb Could not resolve 'httpredir.debian.org'
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/r/rsnapshot/rsnapshot_1.4.2-1_all.deb Could not resolve 'httpredir.debian.org'
E: Failed to fetch dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-rsnapshot/openmediavault-rsnapshot_5.0.1_all.deb Could not resolve 'dl.bintray.com'
```

**Comment by votdev** [comment]
Are you able to mount the filesystem manually via CLI?

**Comment by vinayak-goyal** [comment]
> Are you able to mount the filesystem manually via CLI?

Mounted by selecting BTRFS as FileSystem while creating. It worked. Not working with ext4.



> Don't know what you are talking about, but the command output you posted above clearly says it can not resolve HTTP addresses, that's an indication that the DNS of your system does not work.

Yup.. my bad. Checked in Network settings, DNS field was blank their. Updated with Google's 8.8.8.8 and now its working.

Thank you so much for your generous help.

**Comment by vinayak-goyal** [comment]
Also, I've enabled recyble bin in shared folder.
I'm the admin of system, but I'm unable to open recycle bin of other users. Can only open my own recycle bin for shared folders.
Searched all the google but unable to get an answer for accessing ".Recycle" of other users by admin.

**Comment by votdev** [comment]
> Mounted by selecting BTRFS as FileSystem while creating. It worked. Not working with ext4.

This indicates this not a problem of OMV, but i have no idea what's going on here.



> I'm the admin of system, but I'm unable to open recycle bin of other users. Can only open my own recycle bin for shared folders.

I think you need to modify the ACL settings manually.

**Comment by vinayak-goyal** [comment]
> I think you need to modify the ACL settings manually.

Can you help me with how this can be done. I'll be highly grateful.

**Comment by vinayak-goyal** [comment]
Ok your last suggestion helped. Just went into shares and clicked ACL > Recursive - Apply Permissions to Folders and Subfolders > Enabled it. And voila its done.

Thank you so much. Couldn't thank you enough.
