### ISSUE TITLE
SMART error on hardware RAID array

### ISSUE THREAD

**Issue by PrplHaz4** [openmediavault/openmediavault#535]
### Description of issue/question
Accessing Storage -> SMART throws the below error.
- /dev/sda is a hardware RAID array - which makes sense that SMART doesn't work (I think)
- there's a MicroSD card and USB hdd attached which should probably be showing SMART stats

### Steps to reproduce issue
1. Open OMV in Browser
2. Navigate to Storage -> SMART
3. See Error below
4. No devices are shown in "Devices" list
```
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; smartctl -x '/dev/sda' 2>&1' with exit code '1': smartctl 6.6 2017-11-05 r4594 [x86_64-linux-5.3.0-0.bpo.2-amd64] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sda: requires option '-d cciss,N'
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
 in /usr/share/php/openmediavault/system/storage/smartinformation.inc:166
Stack trace:
#0 /usr/share/php/openmediavault/system/storage/smartinformation.inc(198): OMV\System\Storage\SmartInformation->getData()
#1 /usr/share/php/openmediavault/system/storage/smartinformation.inc(382): OMV\System\Storage\SmartInformation->getAttributes()
#2 /usr/share/openmediavault/engined/rpc/smart.inc(90): OMV\System\Storage\SmartInformation->getTemperature()
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(635): Engined\Rpc\Smart->Engined\Rpc\{closure}()
#4 /usr/share/openmediavault/engined/rpc/smart.inc(105): OMV\Rpc\ServiceAbstract->asyncProc(Object(Closure))
#5 [internal function]: Engined\Rpc\Smart->enumerateDevices(NULL, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#7 /usr/share/openmediavault/engined/rpc/smart.inc(172): OMV\Rpc\ServiceAbstract->callMethod('enumerateDevice...', NULL, Array)
#8 [internal function]: Engined\Rpc\Smart->getList(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('getList', Array, Array)
#11 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatus0n...', '/tmp/bgoutputOz...')
#12 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#13 /usr/share/openmediavault/engined/rpc/smart.inc(207): OMV\Rpc\ServiceAbstract->callMethodBg('getList', Array, Array)
#14 [internal function]: Engined\Rpc\Smart->getListBg(Array, Array)
#15 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#16 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getListBg', Array, Array)
#17 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Smart', 'getListBg', Array, Array, 1)
#18 {main}
```

### Versions report
OMV 5.1.3

**Comment by votdev** [comment]
It seems that the backend does not identify the device as a hardware RAID, thus it can not find out whether the device supports SMART or not. Note, OMV can not collect SMART information from underlying devices of a RAID, it can only process directly attached devices. So you will never get information for your attached MicroSD card and USB hdd.

Sadly your RAID seems not to have an individual device name (like [CCISS HBA](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/storage/backend/cciss.inc)) which might help to identify it and [disable SMART processing](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/storage/storagedevicefio.inc#L34).

Can you provide any information that may help to enhance the device detection in the backend to support your type of RAID and tell OMV that it should not request SMART data.

**Comment by PrplHaz4** [comment]
I figured that would be true for the array...

Here is udev for the array - now I need to figure out how to find the actual raid card...
```
$ udevadm info /dev/sda
P: /devices/pci0000:00/0000:00:01.1/0000:06:00.0/host0/target0:1:0/0:1:0:0/block/sda
N: sda
L: 0
S: disk/by-path/pci-0000:06:00.0-scsi-0:1:0:0
S: disk/by-id/scsi-3600508b1001c81ca2f095dea262b637a
S: disk/by-id/wwn-0x600508b1001c81ca2f095dea262b637a
E: DEVPATH=/devices/pci0000:00/0000:00:01.1/0000:06:00.0/host0/target0:1:0/0:1:0:0/block/sda
E: DEVNAME=/dev/sda
E: DEVTYPE=disk
E: MAJOR=8
E: MINOR=0
E: SUBSYSTEM=block
E: USEC_INITIALIZED=2164548
E: ID_SCSI=1
E: ID_VENDOR=HP
E: ID_VENDOR_ENC=HP\x20\x20\x20\x20\x20\x20
E: ID_MODEL=LOGICAL_VOLUME
E: ID_MODEL_ENC=LOGICAL\x20VOLUME\x20\x20
E: ID_REVISION=7.00
E: ID_TYPE=disk
E: ID_SERIAL=3600508b1001c81ca2f095dea262b637a
E: ID_SERIAL_SHORT=600508b1001c81ca2f095dea262b637a
E: ID_WWN=0x600508b1001c81ca
E: ID_WWN_VENDOR_EXTENSION=0x2f095dea262b637a
E: ID_WWN_WITH_EXTENSION=0x600508b1001c81ca2f095dea262b637a
E: ID_SCSI_SERIAL=PDNNK0BRH660JJ
E: ID_BUS=scsi
E: ID_PATH=pci-0000:06:00.0-scsi-0:1:0:0
E: ID_PATH_TAG=pci-0000_06_00_0-scsi-0_1_0_0
E: ID_PART_TABLE_UUID=62e3696c-e5de-4104-9d18-2614b456fd8a
E: ID_PART_TABLE_TYPE=gpt
E: DEVLINKS=/dev/disk/by-path/pci-0000:06:00.0-scsi-0:1:0:0 /dev/disk/by-id/scsi-3600508b1001c81ca2f095dea262b637a /dev/disk/by-id/wwn-0x600508b1001c81ca2f095dea262b637a
E: TAGS=:systemd:
```

**Comment by votdev** [comment]
What is the vendor and product name of the hardware RAID? According to the UDEV info it is from HP.

**Comment by PrplHaz4** [comment]
@votdev it is an HP H240 - apparently uses hpsa driver not cciss
```
Smart HBA H240 in Slot 2 (RAID Mode)
   Bus Interface: PCI
   Slot: 2
   Serial Number: xxx
   Cache Serial Number: xxx
   Controller Status: OK
   Hardware Revision: B
   Firmware Version: 7.00-0
   Rebuild Priority: High
   Expand Priority: Medium
   Surface Scan Delay: 3 secs
   Surface Scan Mode: Idle
   Parallel Surface Scan Supported: Yes
   Current Parallel Surface Scan Count: 1
   Max Parallel Surface Scan Count: 16
   Queue Depth: Automatic
   Monitor and Performance Delay: 60  min
   Elevator Sort: Enabled
   Degraded Performance Optimization: Disabled
   Wait for Cache Room: Disabled
   Surface Analysis Inconsistency Notification: Disabled
   Post Prompt Timeout: 15 secs
   Cache Board Present: False
   Drive Write Cache: Disabled
   Controller Memory Size: 0.2
   SATA NCQ Supported: True
   Spare Activation Mode: Activate on physical drive failure (default)
   Controller Temperature (C): 88
   Number of Ports: 2 Internal only
   Encryption: Not Set
   Express Local Encryption: False
   Driver Name: hpsa
   Driver Version: 3.4.20
   Driver Supports SSD Smart Path: True
   PCI Address (Domain:Bus:Device.Function): 0000:06:00.0
   Negotiated PCIe Data Rate: PCIe 3.0 x8 (7880 MB/s)
   Controller Mode: RAID Mode
   Pending Controller Mode: RAID
   Port Max Phy Rate Limiting Supported: False
   Latency Scheduler Setting: Disabled
   Current Power Mode: MaxPerformance
   Survival Mode: Disabled
   Host Serial Number: xxx
   Sanitize Erase Supported: True
   Primary Boot Volume: None
   Secondary Boot Volume: None
```

**Comment by votdev** [comment]
OK, thx for the info.

To support that HW RAID in OMV we need to find a generic way to identify it via UDEV, sysfs or something else, but NO additional command line tool specific for that controller, e.g. tw_cli for 3Ware RAID's.

**Comment by votdev** [comment]
Maybe the serial number can be used like it is possible to identify the vendor of a NIC based on the MAC address.

**Comment by votdev** [comment]
THE HBA should be supported by OMV when using the CCISS driver.

**Comment by votdev** [comment]
`ID_VENDOR=HP` and `ID_MODEL=LOGICAL_VOLUME` seem to be specific for the HBA. Additional the WWN number can be used to identify the vendor,  600508bxxxx => 00508B is HP.

**Comment by PrplHaz4** [comment]
Sorry @votdev not sure how else to help - lmk if you have a command i can run to get more info...here is an excerpt from `udevadm info -q all -a /dev/sg0`
```
  looking at parent device '/devices/pci0000:00/0000:00:01.1/0000:06:00.0':
    KERNELS=="0000:06:00.0"
    SUBSYSTEMS=="pci"
    DRIVERS=="hpsa"
    ATTRS{local_cpus}=="f"
    ATTRS{local_cpulist}=="0-3"
    ATTRS{current_link_width}=="8"
    ATTRS{subsystem_vendor}=="0x103c"
    ATTRS{msi_bus}=="1"
    ATTRS{revision}=="0x01"
    ATTRS{irq}=="17"
    ATTRS{max_link_speed}=="8 GT/s"
    ATTRS{numa_node}=="0"
    ATTRS{consistent_dma_mask_bits}=="32"
    ATTRS{driver_override}=="(null)"
    ATTRS{dma_mask_bits}=="64"
    ATTRS{current_link_speed}=="8 GT/s"
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x010400"
    ATTRS{enable}=="1"
    ATTRS{subsystem_device}=="0x21c7"
    ATTRS{d3cold_allowed}=="1"
    ATTRS{device}=="0x3239"
    ATTRS{vendor}=="0x103c"
    ATTRS{max_link_width}=="8"
    ATTRS{ari_enabled}=="0"
```

**Comment by votdev** [comment]
Can you please have a look into the sysfs, e.g. /sys/block/sda/ if there is any other useful information. Maybe you'll find some more info in /sys/, too.

**Comment by PrplHaz4** [comment]
Not having much luck - does a related/parent device with hpsa driver help at all?  That would likely require a bit of traversal to arrive at the right device...

Maybe working backward from?
`/sys/bus/pci/drivers/hpsa/`

**Comment by votdev** [comment]
Using the vendor and model as a trigger to do some deeper search is a good starting point for the OMV hpsa „driver“. I don’t think traversing and searching the sysfs is too expensive. I will try to implement a first shoot next week. And I will request help in the forum, maybe others have additional ideas how to clearly identify tha HBA. I will also have a look into the sources of the HP CLI tool, but I think PHP will come to it’s limits there.

**Comment by votdev** [comment]
Can you please post the output of `/sys/block/sda/device/model` and `/sys/block/sda/device/vendor`?

**Comment by votdev** [comment]
Useful infos: https://h50146.www5.hpe.com/products/software/oe/linux/mainstream/support/whitepaper/pdfs/c02677069.pdf

**Comment by PrplHaz4** [comment]
Thanks for looking at this @votdev!  Here's the requested info...

/sys/block/sda/device/model
`LOGICAL VOLUME`

/sys/block/sda/device/vendor
`HP`

cat /proc/scsi/scsi
`cat: /proc/scsi/scsi: No such file or directory`

ls -alh /sys/bus/pci/drivers/hpsa/
```
total 0
drwxr-xr-x  2 root root    0 Dec 18 11:20 .
drwxr-xr-x 23 root root    0 Dec 18 11:20 ..
lrwxrwxrwx  1 root root    0 Dec 18 11:20 0000:06:00.0 -> ../../../../devices/pci0000:00/0000:00:01.1/0000:06:00.0
--w-------  1 root root 4.0K Dec 18 11:20 bind
lrwxrwxrwx  1 root root    0 Dec 18 11:20 module -> ../../../../module/hpsa
--w-------  1 root root 4.0K Dec 18 11:20 new_id
--w-------  1 root root 4.0K Dec 18 11:20 remove_id
--w-------  1 root root 4.0K Dec 18 11:20 uevent
--w-------  1 root root 4.0K Dec 18 11:20 unbind
```

cat /sys/bus/pci/drivers/hpsa/0000\:06\:00.0/device
`0x3239`

cat /sys/bus/pci/drivers/hpsa/0000\:06\:00.0/subsystem_device
`0x21c7`

cat /sys/bus/pci/drivers/hpsa/0000\:06\:00.0/vendor
`0x103c`

cat /sys/bus/pci/drivers/hpsa/0000\:06\:00.0/subsystem_vendor
`0x103c`

cat /sys//devices/pci0000:00/0000:00:01.1/0000:06:00.0/host0/target0:1:0/0:1:0:0/block/sda/device/model
`LOGICAL VOLUME`

cat /sys//devices/pci0000:00/0000:00:01.1/0000:06:00.0/host0/target0:1:0/0:1:0:0/block/sda/device/vendor
`HP`

ls -alh /sys/devices/pci0000:00/0000:00:01.1/0000:06:00.0/host0
```
total 0
drwxr-xr-x 6 root root    0 Dec 18 08:54 .
drwxr-xr-x 5 root root    0 Dec 18 08:54 ..
drwxr-xr-x 2 root root    0 Dec 18 11:25 power
drwxr-xr-x 3 root root    0 Dec 18 11:25 sas_host
drwxr-xr-x 3 root root    0 Dec 18 11:25 scsi_host
lrwxrwxrwx 1 root root    0 Dec 18 11:25 subsystem -> ../../../../../bus/scsi
drwxr-xr-x 4 root root    0 Dec 18 08:54 target0:1:0
-rw-r--r-- 1 root root 4.0K Dec 18 11:25 uevent
```

cat /sys/devices/pci0000:00/0000:00:01.1/0000:06:00.0/host0/scsi_host/host0/proc_name
`hpsa`

**Comment by votdev** [comment]
Thanks for the info, but i think it's enough to test the name of the device driver.

Can you please test the code and report if it works. I've already merged the PR into master, so you can get the code from there or the PR.

**Comment by votdev** [comment]
The sysfs entry of interest is now `ls -alh /sys/block/sda/device/driver` or `readlink /sys/block/sda/device/driver`. I hope this is something like `../../../../../../../bus/pci/drivers/hpsa`.

**Comment by PrplHaz4** [comment]
Unfortunately doesn't look like it...

ls -alh /sys/block/sda/device/driver
```
lrwxrwxrwx 1 root root 0 Dec 18 11:44 /sys/block/sda/device/driver -> ../../../../../../../bus/scsi/drivers/sd
```

**Comment by votdev** [comment]
> Unfortunately doesn't look like it...
> 
> ls -alh /sys/block/sda/device/driver
> 
> ```
> lrwxrwxrwx 1 root root 0 Dec 18 11:44 /sys/block/sda/device/driver -> ../../../../../../../bus/scsi/drivers/sd
> ```

👿

**Comment by votdev** [comment]
Please test the PR https://github.com/openmediavault/openmediavault/pull/539 if possible.

**Comment by PrplHaz4** [comment]
I patched the files in place, then rebooted the server (assuming that is a valid test).

I'm still getting the same error when I go to SMART...not sure how else to test the change - it doesn't appear anything else is working differently than before

```
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; smartctl -x '/dev/sda' 2>&1' with exit code '1': smartctl 6.6 2017-11-05 r4594 [x86_64-linux-5.3.0-0.bpo.2-amd64] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sda: requires option '-d cciss,N'
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
 in /usr/share/php/openmediavault/system/storage/smartinformation.inc:166
Stack trace:
#0 /usr/share/php/openmediavault/system/storage/smartinformation.inc(198): OMV\System\Storage\SmartInformation->getData()
#1 /usr/share/php/openmediavault/system/storage/smartinformation.inc(382): OMV\System\Storage\SmartInformation->getAttributes()
#2 /usr/share/openmediavault/engined/rpc/smart.inc(90): OMV\System\Storage\SmartInformation->getTemperature()
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(635): Engined\Rpc\Smart->Engined\Rpc\{closure}()
#4 /usr/share/openmediavault/engined/rpc/smart.inc(105): OMV\Rpc\ServiceAbstract->asyncProc(Object(Closure))
#5 [internal function]: Engined\Rpc\Smart->enumerateDevices(NULL, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#7 /usr/share/openmediavault/engined/rpc/smart.inc(172): OMV\Rpc\ServiceAbstract->callMethod('enumerateDevice...', NULL, Array)
#8 [internal function]: Engined\Rpc\Smart->getList(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('getList', Array, Array)
#11 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatuswJ...', '/tmp/bgoutput97...')
#12 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#13 /usr/share/openmediavault/engined/rpc/smart.inc(207): OMV\Rpc\ServiceAbstract->callMethodBg('getList', Array, Array)
#14 [internal function]: Engined\Rpc\Smart->getListBg(Array, Array)
#15 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#16 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getListBg', Array, Array)
#17 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Smart', 'getListBg', Array, Array, 1)
#18 {main}
```

**Comment by votdev** [comment]
Could you please execute `cat /sys/block/sda/device/../../../driver`?

**Comment by PrplHaz4** [comment]
cat /sys/block/sda/device/../../../driver
```
cat: /sys/block/sda/device/../../../driver: Is a directory
```

ls /sys/block/sda/device/../../../driver
```
0000:06:00.0  bind  module  new_id  remove_id  uevent  unbind
```

**Comment by votdev** [comment]
I've updated the `isHPSA` function. Please update that on your system and reboot. After that it should work.

**Comment by PrplHaz4** [comment]
Sorry for the delay - finally tested f920aa7 and things seem to be working ok...no errors on the Disks or SMART pages anymore.

/dev/sda is the disk exposed by my hardware RAID array

![image](https://user-images.githubusercontent.com/841414/71281482-fccbc500-232b-11ea-9798-2599c57f1643.png)

![image](https://user-images.githubusercontent.com/841414/71281551-37356200-232c-11ea-9e05-5c6e5cc040d4.png)

**Comment by Max-Sum** [comment]
Is there a plan to support showing individual disks in HPSA controlled raid?

**Comment by votdev** [comment]
> Is there a plan to support showing individual disks in HPSA controlled raid?

No, the current backend does not support that.
