### ISSUE TITLE
Raspberry Pi Watchdog Not Working - Proposed Solution Inside

### ISSUE THREAD

**Issue by RFBomb** [openmediavault/openmediavault#542]
Raspberry Pi Watchdog Fix

I don't know how to do a 'pull' request, so I'm noting it here. 

OpenMediaVault uses the 'softdog' watchdog module by default. Raspian does not support this, as 'softdog' is a missing module. The reason the Raspian group will not provide it is likely due to the fact that there is a hardware watchdog built into the board that can be utilized. The proposed changes below allow use of that hardware watchdog to enable it to perform a full system reboot on system hang (whereas before the watchdog daemon would be errored out, and a system hang would result in someone walking over and pulling the power cable out of the Pi for a hard reset.)

Forum Link for my fix: https://forum.openmediavault.org/index.php/Thread/30063-Raspberry-Pi-4-Watchdog-Not-Working/?postID=223220#post223220

------------------------------------------------------------------------------------------
Additional lines to `/etc/watchdog.conf`
```
watchdog-timeout=14
max-load-1 = 24
```
The watchdog daemon defaults to 60s. The Pi hardware is only capable of running a 15s watchdog max. So the parameter must be specified in the config file to be less than 15 seconds. 

Changes to `/etc/default/watchdog`
`watchdog_module="bcm2835_wdt"` -- Changed from 'softdog' to look at the hardware device on the RPI. -- THIS is the important one!

`watchdog_options="softboot"` -- Optional Change -- This calls for a full reboot of the system. Same as if power was cycled (without actually cycling power --It works perfectly fine to exclude this option. The hardware watchdog acts by disabling power to the Pi, so (in theory) this should prevent that power loss while still resulting in a successful reboot. (I've tested with and without it)

OMV File that controls these modifications:
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/watchdog/default.sls

--------
I can understand why the softboot is the current method -  it should be hardware agnostic. And checking for hardware means owning up to possible future support of it too. I don't know what your code is written in, so I can't begin to recommend the change required to accomplish this type of check. Maybe the easiest way would be by using a user-set file or a setting within the GUI? (Have it display if the watchdog is functional or errored out in the Diagnostic screen. Then be able have the user type in / select their hardware parameters to customize the file. 

In the mean-time, I used 
`sudo nano /srv/salt/omv/deploy/watchdog/default.sls`
 to modify that file. I replaced "softdog" with "bcm2835_wdt" and added the two necessary lines for the watchdog-timeout and max-load to the correct section. 

This way, if OMV does decide to overwrite those files, its using the correct settings.

**Comment by RFBomb** [comment]
A forum mod mentioned that the user can modify some file to set the OMV defaults, then the 'salt' command can be run to initiate the change. This is a great way to do this, but it will require the timer value to be added to the base file.

I propose adding a new parameter to the base salt file to have a custom timer.

`{% set watchdog_timeout = salt['pillar.get']('default:OMV_WATCHDOG_WATCHDOGTIMER', '60') %}`

then under 'realtime' option, specify:
`watchdog-timeout= {{ watchdog_timeout }}`

Then, a user would be able to customize their watchdog timer for their hardware with ease, using the method you suggest:
Add / Modify the lines in /etc/default/openmediavault
```
OMV_WATCHDOG_WATCHDOGMODULE="bcm2835_wdt"
OMV_WATCHDOG_WATCHDOGTIMER="14"
```
then execute `omv-salt deploy run watchdog` to declare the changes.

**Comment by votdev** [comment]
> I can understand why the softboot is the current method - it should be hardware agnostic. And checking for hardware means owning up to possible future support of it too. I don't know what your code is written in, so I can't begin to recommend the change required to accomplish this type of check. Maybe the easiest way would be by using a user-set file or a setting within the GUI? (Have it display if the watchdog is functional or errored out in the Diagnostic screen. Then be able have the user type in / select their hardware parameters to customize the file.

OMV has not the capability to implement a hardware detection to setup the watchdog correctly for any hardware. I also don't want to implement a UI for that. The default 'softdog' works on 99% of the systems. Systems that do not work correctly must be customized manually.

**Comment by RFBomb** [comment]
@votdev 
> OMV has not the capability to implement a hardware detection to setup the watchdog correctly for any hardware. I also don't want to implement a UI for that. The default 'softdog' works on 99% of the systems. Systems that do not work correctly must be customized manually.

Like I said, I completely understand the desire to not want to hard-code in hardware support. Which is why I added a second comment with a much better proposed fix, after an admin from the forums pointed out the /etc/default/openmediavault file to me. 

What I think should be added is the "watchdog-timeout" setting as a parameter, with a default value of 60 (which is the default timer if not specified). This would allow the user to modify the defaults in 1 location to specify the correct module + a compatible timer for their system, while also not requiring OMV to perform any hardware checks.  This problem is fixed by 3 additional lines of code, per my second comment on the thread.

**Comment by votdev** [comment]
Everything has been implemented with https://github.com/openmediavault/openmediavault/commit/acbfcea5137a75d1cf5f01887c1d239d4f98c3dc.

**Comment by RFBomb** [comment]
@votdev  Thank you for the update. OMV is awesome and I very much appreciate your hard work.

**Comment by rabelux** [comment]
came upon this issue and without having tested it, I think the correct lines to be added should be
```
OMV_WATCHDOG_DEFAULT_MODULE="bcm2835_wdt"
OMV_WATCHDOG_CONF_WATCHDOG_TIMEOUT="14"
```

**Comment by votdev** [comment]
> came upon this issue and without having tested it, I think the correct lines to be added should be
> 
> ```
> OMV_WATCHDOG_DEFAULT_MODULE="bcm2835_wdt"
> OMV_WATCHDOG_CONF_WATCHDOG_TIMEOUT="14"
> ```

@ryecoaaron I think this is a good candidate to be added to the install script, e.g.
```
if [[ "${distributor}" == "Raspbian" ]]; then
	omv_set_default "OMV_WATCHDOG_DEFAULT_MODULE" "bcm2835_wdt"
	omv_set_default "OMV_WATCHDOG_CONF_WATCHDOG_TIMEOUT" "14"
fi
```

**Comment by ryecoaaron** [comment]
I will add those. Thanks.

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/installScript/commit/0ba0cb4b26f1f335791ac4a84b2ac20d09991dc3
