### ISSUE TITLE
Read-only shares missing from FTP

### ISSUE THREAD

**Issue by fred-cardoso** [openmediavault/openmediavault#549]
After configuring a share on Shared Folders section as Read-only for a specified user, that user can't see the folder using FTP. If the same folder is changed and set as Read/Write, the user can see the folder.

To test this issue is quite simple:
1 - Create two users
2 - Create a shared folder, and give read only access to one of the users and read/write to the other one
3 - Add the newly created shared folder to the FTP Shares section
4 - Access via FTP using the read only user's account
5 - Access via FTP using the read write user's account
6 - One can see the share, the other can't

After using `cat ` the output is this:
`
<Directory /Filmes>
  <Limit ALL>
    AllowUser OR fred
    DenyAll
  </Limit>
  <Limit READ DIRS>
    AllowUser OR fred
    DenyAll
  </Limit>
</Directory>
<Directory /Empires>
  <Limit ALL>
    DenyAll
  </Limit>
  <Limit READ DIRS>
    DenyAll
  </Limit>
</Directory>
`

So, the directory Filmes is configured as Read/Write and the Empires one as Read only for the user fred. As seen, the user fred is not allowed in the Empires directory at all.

**Comment by votdev** [comment]
Which OMV version are we talking about?

**Comment by fred-cardoso** [comment]
Hi @votdev !

Current version is: 5.2.1-1 (Usul).

Thank you and Happy new Year!

**Comment by votdev** [comment]
Please describe how to create the shared folder `Filmes`and `Empires`. Are they on the same lefel or is `Empires` sub-dir of `Filmes`?

I can not reproduce this issue when creating a share called `Data`and give a user read-only and another one read-write access.

**Comment by fred-cardoso** [comment]
They are on the same level. Actually, they are different hard drives, and on both I created a shared folder pointing to them.

**Comment by mi-hol** [comment]
@fred-cardoso is this still an open issue?

**Comment by fred-cardoso** [comment]
Hi @mi-hol,

I never tested this again as I found some workarounds. But I can test this later and then open if needed.
I am closing the issue for now.

Thanks!
