### ISSUE TITLE
Invalid RPC response on "Encryption"/"File systems" page

### ISSUE THREAD

**Issue by assoc** [openmediavault/openmediavault#550]
### Description of issue/question
My system contains a few LUKS encrypted drives, all of them were configured outside of OMV. OMV v.4.1.26 shown those drives on the "Encryption" page and allowed to backup keys/headers without issues. When I updated OMV to v.4.1.30 this page causes the error "Invalid RPC response" (see below). "File systems" page also produces the same error, but silently: it shows up in the log, but the page appears to be loading (infinitely).

### Details (encryption page)
`Error #0:
OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:186
Stack trace:
#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('LuksMgmt', 'getContainersLi...', Array, Array, 3)
#1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#2 {main}`

`omv-engined[29076]: PHP Fatal error: Uncaught TypeError: Argument 2 passed to array_keys_exists() must be of the type array, null given, called in /usr/share/php/openmediavault/system/filesystem/backend/manager.inc on line 284 and defined in /usr/share/php/openmediavault/functions.inc:140#012Stack trace:#012#0 /usr/share/php/openmediavault/system/filesystem/backend/manager.inc(284): array_keys_exists(Array, NULL)#012#1 /usr/share/php/openmediavault/system/filesystem/backend/manager.inc(130): OMV\System\Filesystem\Backend\Manager->enumerate()#012#2 /usr/share/php/openmediavault/system/filesystem/filesystem.inc(855): OMV\System\Filesystem\Backend\Manager->getBackendById('/dev/mapper/sdb...')#012#3 /usr/share/openmediavault/engined/rpc/fstab.inc(178): OMV\System\Filesystem\Filesystem::getImpl('/dev/mapper/sdb...')#012#4 [internal function]: OMVRpcServiceFsTab->getByFsName(Array, Array)#012#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)#012#6 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod in /usr/share/php/openmediavault/functions.inc on line 140`

**Comment by assoc** [comment]
Another error on System information -> Performance statistics -> Disk usage graph:
`omv-engined[12624]: PHP Fatal error: Uncaught TypeError: Argument 2 passed to array_keys_exists() must be of the type array, null given, called in /usr/share/php/openmediavault/system/filesystem/backend/manager.inc on line 284 and defined in /usr/share/php/openmediavault/functions.inc:140#012Stack trace:#012#0 /usr/share/php/openmediavault/system/filesystem/backend/manager.inc(284): array_keys_exists(Array, NULL)#012#1 /usr/share/php/openmediavault/system/filesystem/backend/manager.inc(130): OMV\System\Filesystem\Backend\Manager->enumerate()#012#2 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(225): OMV\System\Filesystem\Backend\Manager->getBackendById('/dev/disk/by-la...')#012#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(612): OMVRpcServiceFileSystemMgmt->{closure}()#012#4 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(284): OMV\Rpc\ServiceAbstract->asyncProc(Object(Closure))#012#5 [internal function]: OMVRpcServiceFileSystemMgmt->enumerateMountedFilesystems(Array, Array)#012#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123):  in /usr/share/php/openmediavault/functions.inc on line 140`

**Comment by alpapad** [comment]
Same problem here, with btrfs configured outside of OMV


Dec 31 00:09:41 openmediavault omv-engined[2714]: PHP Fatal error: Uncaught TypeError: Argument 2 passed to array_keys_exists() must be of the type array, null given, called in /usr/share/php/openmediavault/system/filesystem/backend/manager.inc on line 284 and defined in 
                                                  Stack trace:
                                                  #0 /usr/share/php/openmediavault/system/filesystem/backend/manager.inc(284): array_keys_exists(Array, NULL)
                                                  #1 /usr/share/php/openmediavault/system/filesystem/filesystem.inc(816): OMV\System\Filesystem\Backend\Manager->enumerate()
                                                  #2 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(69): OMV\System\Filesystem\Filesystem::getFilesystems()
                                                  #3 [internal function]: OMVRpcServiceFileSystemMgmt->enumerateFilesystems(NULL, Array)
                                                  #4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
                                                  #5 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(320): OMV\Rpc\ServiceAbstract->callMethod('enumerateFilesy...', NULL, Array)
                                                  #6 [internal function]: OMVRpcServiceFileSystemMgmt->getList(Array, Array)
                                                  #7 /usr/share/ in /usr/share/php/openmediavault/functions.inc on line 140



**In the ui:**

Error #0:
OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:186
Stack trace:
#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('FileSystemMgmt', 'enumerateFilesy...', Array, Array, 3)
#1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#2 {main}


This is happening after upgrading to 4.1.30-1

**Comment by assoc** [comment]
After manual edit of filesystem/backend/btrfs.inc (lines 68-70 of 3dec1f4) and nginx + php7.0-fpm restart the error persists.

**Comment by ryecoaaron** [comment]
Did you restart engined?

**Comment by assoc** [comment]
@ryecoaaron Did that and it solved the problem. Thanks.
