### ISSUE TITLE
Files Getting Corrupted

### ISSUE THREAD

**Issue by vinayak-goyal** [openmediavault/openmediavault#553]
Files in OMV5 Shares getting corrupted very often even after properly saving them before exiting. Next time someone opens it, it is corrupted. Mainly using Excel & PDF Files.

Also, to tackle this issue I wanted to make a Restore Previous Version function in windows working, but not able to do that as well with rsnapshot right now(I have little know-how of rsnapshot working, maybe thats why).

But files are constantly getting corrupted. OMV5 is having shares which are Mapped as Network Drives on 5 PCs. No 2 PCs access the same files at the same time which were corrupted.
People work on an excel file. They save it and go home. Next day they come in and all their work is gone with excel not able to even repair those files.

I've installed OMV5 on an OrangePi Win Plus with 2 Flash Drives 128 GBs each. 1 MicroSD Card 32GB as OS Drive. File System for both FlashDrives is BTRFS. Followed everything based on the SBC Installation Guide on SourceForge, i.e. checked Memory Card before writing OS to it, burned it with etcher and not Rufus for data integrity checks.

Please help, I switched to OMV5 from Google Drive and Dropbox to increase the reliability and control of the data but it is working the other way round with files getting corrupted every now and then.

**Comment by votdev** [comment]
Sorry, the OMV project can't do anything here.

**Comment by vinayak-goyal** [comment]
Why is this not an omv issue?
Please enlighten I might be misunderstanding this software concept.

**Comment by ryecoaaron** [comment]
OMV only configures samba (assuming you are using samba).  OMV does not create the package or the networking that Linux and Debian provide.  In my opinion, this seems to be a storage media issue or networking issue.  There is nothing OMV can do to help with those issues.

**Comment by vinayak-goyal** [comment]
Ok Thank You for clarifying.
Yes I'm using SMB Shares to Map Network Drive.
Can you please help me sort this thing out though I understand it is out of scope of OMV.
Also when we open an excel file and do some work in it, does the processing consumed is of OMV Server or the Node on which the file is opened ( Such as I researched for video files that in Plex processing/encoding for videos take place in Server but in Kodi the encoding takes place at the node video is being watched)

Kindly ignore/bear my little knowldge in this subject.

**Comment by ryecoaaron** [comment]
Please open a new thread on the forum to get more help on this.  https://forum.openmediavault.org/
