### ISSUE TITLE
[bug] minidlna config generator doesn't randomize serial number

### ISSUE THREAD

**Issue by xeros** [openmediavault/openmediavault#555]
### Description of issue/question
openmediavault-minidlna plugin always puts "serial=31446138" to /etc/minidlna.conf instead of random number that will be stored in OMV configuration.

It's not a problem until you'll have two or more OMV servers with DLNA in single network.
Having two different OMV servers with DLNA shared content using the same serial confused all my DLNA clients/renderers in my network, resulting in inability to show any reachable DLNA server (even they were doing some queries in background to both minidlna servers).

### Steps to reproduce issue
Enable minidlna plugin, enable it, add some share, apply changes.

$ grep serial /etc/minidlna.conf
serial=31446138
$

It's also visible in /var/log/minidlna.log after setting up debug logging and accessing DLNA from DLNA client/renderer:
$ grep serial /var/log/minidlna.log | sed -e 's#.*\(<serial.*/serialNumber>\).*#\1#g'
<serialNumber>31446138</serialNumber>
$

### Workaround
Adding "serial=(any_different_number)" to additional options field doubles 'serial' options in /etc/minidlna.conf but luckily manually added number is near the end of file and overrides the "serial=31446138" put earlier:

$ grep serial /etc/minidlna.conf
serial=31446138
serial=12345678
$ grep serial /var/log/minidlna.log | sed -e 's#.*\(<serial.*/serialNumber>\).*#\1#g'
<serialNumber>12345678</serialNumber>
$

### Versions report
Tested & confirmed versions:
OMV 4.1.23 & 4.1.30 (openmediavault-minidlna 3.3.11)
OMV 5.2.1 (openmediavault-minidlna 5.0.2)

**Comment by ryecoaaron** [comment]
This issue belongs on the plugin’s repo - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-minidlna/issues
