### ISSUE TITLE
Additional build dependencies

### ISSUE THREAD

**Issue by jjakob** [openmediavault/openmediavault#556]
### Description of issue/question
On a debian buster system with APT::Install-Recommends disabled, the build process fails on missing dependencies.
Extra dependencies need to be installed:
```
apt-get install python3-setuptools python3-dev
pip3 install --upgrade wheel
```
### Steps to reproduce issue

cloned git repo, installed make, sudo, ran make install

**Comment by jjakob** [comment]
see also https://gist.github.com/jjakob/c9ab333d15105b986008863e9f4f5db8

**Comment by ryecoaaron** [comment]
Seems to be a mipsel-specific problem.  I've never had this problem on armhf, arm64, i386, or amd64.

**Comment by ryecoaaron** [comment]
And why are you building the openmediavault package itself?  You could download the packages for everything except for php-pam and install them since they are architecture independent.  Building from git master branch can cause problems.

**Comment by jjakob** [comment]
I didn't know that before I went building. I tried to install it from the repo and there was no mipsel arch available. I see now that all packages except php-pam are for all arches. Good to know for next time.
It may be due to the way it was installed - with debootstrap, and APT::Install-Recommends disabled after the bootstrap, before starting to build.
