### ISSUE TITLE
RU localization mistake in "Add shared folder" window, permissions section

### ISSUE THREAD

**Issue by alekskomp** [openmediavault/openmediavault#557]
Hello
Found mistake in RU localization 
"Add shared folder" window, permissions (default item):

"нет доступа" instead of "только чтение" ("no access" instead of "read only")

Version: 4.1.30-1 (Arrakis)

![Annotation 2020-01-07 143524](https://user-images.githubusercontent.com/45537705/71892813-ffffe700-315a-11ea-87ea-27f0e0518bd9.png)

![Annotation 2020-01-07 143741](https://user-images.githubusercontent.com/45537705/71893093-b2d04500-315b-11ea-94ae-c18cbb97e571.png)

**Comment by votdev** [comment]
Fixed on https://translate.openmediavault.org for OMV5.
