### ISSUE TITLE
file in interfaces.d is not being loaded

### ISSUE THREAD

**Issue by Matty666** [openmediavault/openmediavault#559]
### Description of issue/question
I have a file to add an ip address alias to an interface in the `interfaces.d` folder, which has stopped working, I think since I changed a setting and it regenerated the `/etc/network/interfaces` file, the ip alias no longer is applied

I manually edited `/etc/network/interfaces` and changed the `source interfaces.d` to `source-directory interfaces.d` and then `systemctl restart networking` and it applied the alias.

I saw that recently it was changed from `source-directory` to `source` and so I'm not sure if what I've done is right, as I'm sure there is a good reason it was changed.

I also realise that the changes I have made will disappear at the next config regeneration, so looking for a more permanent solution.

Thanks!

### Versions report
4.1.30-1 (Arrakis)

**Comment by votdev** [comment]
You're right. This issue was changed in 4.1.29. I've checked the man pages that time and i really don't know why i was sure to change it according the manual. Maybe something was wrong that time with the man pages.

Fixed in `openmediavault 4.1.32`.

**Comment by Matty666** [comment]
Thanks @votdev, and for the quick response!
