### ISSUE TITLE
ACLs auf ZFS Dateifreigabe ändern

### ISSUE THREAD

**Issue by XtraLarge** [openmediavault/openmediavault#563]
Hallo,
ich setzte Openmediavault 5 in der aktuellen Version 5.2.2-1 auf drei Rechnern ein. Da ich durch Proxmox ein fan von ZFS geworden bin, verwende ich ZFS auch mit dem entsprechenden Plugin auf Openmediavault. 
Bei einer Basisfunktion funktioniert jedoch die Verwendung von ZFS nicht.  Hierbei handelt es sich um das Setzen von ACLs bei Dateifreigaben, die auf einem ZFS Volume liegen.
Ich glaube das ist klar, da setfacl verwendet wird und das geht nicht bei ZFS Volumes. Ich glaube hierfür müsste eine Ausnahme gescripted werden.

### Steps to reproduce issue
1. Laufwerk mit ZFS Dateisystem erstellen
2. Dateifreigabe auf dem erstellen Volume anlegen
3. ACL Button drücken und einen Benutzer oder eine Gruppe ändern und anschließend Anwenden drücken.
>> Es erscheint eine Meldung wie beispielsweise: 
```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; setfacl --remove-all -M '/tmp/setfacll5ICzs' -- '/ZTank/TimeMachine/TimeMachine' 2>&1' with exit code '1': setfacl: /ZTank/TimeMachine/TimeMachine: Operation not supported
```
### Versions report
Openmediavault 5 in der aktuellen Version 5.2.2-1

**Comment by votdev** [comment]
Da ZFS nicht offiziel im Linux Kernel und von Debian ausgeliefert wird (und daher auch nicht von OMV offiziel unterstützt wird) sehe ich momentan auch keine Notwendigkeit dieses verhalten zu berücksichtigen.

Ich gehe aber davon aus dass das ZFS Plugin die entsprechenden Schalter setzt um den ACL Knopf in der WebUI für ZFS Dateisysteme zu deaktivieren.

**Comment by votdev** [comment]
Schnell gegoogled und https://de.wikibooks.org/wiki/ZFS_auf_Linux/_ACLs überflogen  sieht es so aus als ob ZFS doch POSIX ACLs unterstützt.

**Comment by XtraLarge** [comment]
Soll ich mal probieren und die beiden ZFS flags setzen?

**Comment by votdev** [comment]
Wenn es keine Produktivdaten sind, warum nicht.

**Comment by XtraLarge** [comment]
Funktioniert!
zfs set acltype=posixacl <DATASET>
zfs set xattr=sa <DATASET>
gesetzt und Rechte werden ohne Fehler gesetzt.

root@OpenMediaVault:/ZTank/TimeMachine# ls -la
insgesamt 12
drwxr-xr-x  3 root        root  3 Jan  8 21:46 .
drwxr-xr-x  7 root        root  7 Jan  8 21:43 ..
drwxrwsr-x+ 3 TimeMachine users 3 Jan  9 15:15 TimeMachine

An dem "+" erkennt man auch, dass erweiterte Rechte gesetzt wurden ;)

Danke Dir!

lG
Willi

**Comment by XtraLarge** [comment]
root@OpenMediaVault:/ZTank/TimeMachine# getfacl TimeMachine
# file: TimeMachine
# owner: TimeMachine
# group: users
# flags: -s-
user::rwx
group::rwx
other::r-x
default:user::rwx
default:group::rwx
default:other::r-x

**Comment by ryecoaaron** [comment]
> However, I assume that the OMV-Extras ZFS plugin sets the appropriate switches to deactivate the ACL button in the WebUI for ZFS file systems.

Unfortunately, the backend says that ACLs are supported.  I'm not sure if the default for the Debian zfs package changed or not but since people might have that flag enabled, we needed to keep ACLs supported by the backend.

**Comment by XtraLarge** [comment]
Sorry, that i wrote this issue in German.
After Volkers quoted comment he found a howto acrtice that describes how zfs on linux can support ACLs. The arcticle wrote that you must set the flags "acltype=posixacl" and "xattr=sa". The commands are:
```
zfs set acltype=posixacl <DATASET>
zfs set xattr=sa <DATASET>
```

So it would be better if the plugin checks that the flags are set and after the check the acls could be set,

**Comment by ryecoaaron** [comment]
The plugin doesn't set any flags currently.  That is why you are able to specify flags from the plugin.  Since I rarely maintain any of the code in this plugin, I would rather not change it.  It seems that most zfs users are either setting the flag manually if they use ACLs or not using ACLs (most likely).

**Comment by XtraLarge** [comment]
I understand your oppinion, but I don't think that it make sense to show a button that throws an cryptic error message. 
I would suggest to disable the ACL button if the filesystem is ZFS und the flag posixacl ist not set.

**Comment by ryecoaaron** [comment]
I understand that but if we disable the ACL button by changing the filesystem backend, then you can never use it even if you enable the flag on the OS.

**Comment by XtraLarge** [comment]
Is there no chance to disable the button only in the case  the filesystem is ZFS und the flag posixacl ist not set?

Perhaps Volker has an idea? ;)

**Comment by ryecoaaron** [comment]
Here is the line that enables it - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/blob/master/usr/share/php/openmediavault/system/filesystem/backend/zfs.inc#L11 - and while it might be able to poll the filesystem, it would most likely be slow and I don't have time to look into it.

I will gladly disable it all the time since I hate ACLs but that doesn't help much.  Volker probably doesn't want to deal with this since it is a third party plugin.

**Comment by votdev** [comment]
> Is there no chance to disable the button only in the case the filesystem is ZFS und the flag posixacl ist not set?
> 
> Perhaps Volker has an idea? ;)

The backend has no support for enabling/disabling the filesystem backend properties dynamically. Because of that we can only enable or disable the ACL button.
