### ISSUE TITLE
ARECA RAID card support

### ISSUE THREAD

**Issue by dev-sngy** [openmediavault/openmediavault#567]
This post is in reply to [https://forum.openmediavault.org/index.php/Thread/30358-Where-do-I-post-fixes-to-misconfigurations-in-the-code-base/](url) and [https://forum.openmediavault.org/index.php/Thread/13801-We-need-your-help-to-improve-the-SMART-support-of-Areca-RAID-contollers-in-OMV/](url) on the OMV forum page.

Please see the attached file below for all the requested command output:

[areca_info.tar.gz](https://github.com/openmediavault/openmediavault/files/4057139/areca_info.tar.gz)

Please specify if each output should be listed here instead it being in a file.

Kind regards
Julian

**Comment by votdev** [comment]
Great :-)
