### ISSUE TITLE
NFS: Kerberos (GSS) authenticated exports cannot be mounted by clients

### ISSUE THREAD

**Issue by Aearsis** [openmediavault/openmediavault#569]
## Description of issue/question

Due to implicit `sec=sys` option on the NFSv4 root, kerberized exports do not have the root defined, and mounting such exports fails.

### Steps to reproduce issue

Define NFS export with `sec=krb5`, configure kerberos properly. Even then mounting fails:

```
# mount nas:/Share /mnt/nas -o sec=krb5,vers=4.2 -vv
mount.nfs4: timeout set for Sat Jan 18 22:36:18 2020
mount.nfs4: trying text-based options 'sec=krb5,vers=4.2,addr=1.2.3.4,clientaddr=5.6.7.8'
mount.nfs4: mount(2): Operation not permitted
mount.nfs4: Operation not permitted
```

This can be fixed simply by adding the `sec=krb5` to the root export options.

**Comment by votdev** [comment]
You can customize that by adding `OMV_NFSD_V4_DEFAULT_EXPORT_OPTIONS="ro,fsid=0,root_squash,no_subtree_check,hide,sec=krb5p:krb5i:krb5:sys"` to `/etc/default/openmediavault` and run
```
# omv-salt stage run prepare
# omv-salt deploy run nfs
```

**Comment by Aearsis** [comment]
Sure, I even tried it, but did not run the `stage run prepare` and it did not work. Also, I had to read the source code to know which variable to change, which is rather suboptimal :)

Couldn't the option be accessible from the web gui? There is plenty of space on the NFS settings tab.

**Comment by votdev** [comment]
> Couldn't the option be accessible from the web gui? There is plenty of space on the NFS settings tab.

No, OMV will not become something like Webmin where you can configure everything.

**Comment by Aearsis** [comment]
It just seems weird to me that you can directly specify options for exports, but not for the root.

In the beginning of setting up, I have added the option there manually, and made everything work. After a reboot, it took me quite long to realize what was overwritten to make it work again. I'm just trying to prevent others from making the same mistakes - if you think that current state is OK, just close this issue and PR, no problem on my side.

**Comment by mi-hol** [comment]
closing due to votdev's   "no"  response

**Comment by PunisherHD92** [comment]
In case anyone like me is googling this issue for OMV8 and finding this page, it looks like the option name has changed in /etc/default/openmediavault.
The new line is:
`OMV_NFSD_V4_PSEUDO_ROOT_OPTIONS="ro,fsid=0,root_squash,no_subtree_check,hide,sec=krb5p:krb5i:krb5:sys"`
