### ISSUE TITLE
OMV5 openmediavault-usbbackup: Some Job Options inactive when drive not connected

### ISSUE THREAD

**Issue by HannesJo0139** [openmediavault/openmediavault#573]
Sometimes the Job Options "Preserve Permissions", "Preserve Owner", "Preserve Group", "Preserve ACL" are forced to disabled and it is not possible to activate them.

This behavior only occurs when editing an existing job and the USB drive is not connected. Connecting USB drive solves the problem.

**Comment by votdev** [comment]
This is a normal behaviour because the options make only sense if the target filesystem is POSIX compliant. If the device is not connected, then it's not possible to do that checks -> the checkboxes are disabled.

**Comment by HannesJo0139** [comment]
I see. Maybe a tooltip or hint in the doc would be nice.
