### ISSUE TITLE
Add openmedia-netatalk plugin again

### ISSUE THREAD

**Issue by tolanger** [openmediavault/openmediavault#576]
Have read that the openmediavault-netatalk plugin should be obsolete, but it isn't!

Please again add openmediavault-netatalk plugin to OMV 5.

If you ever used Mac OS, Mac OSX and OSX your are comfortable with:

- special characters ( ' # ? * / \ " ) in Filename where on SMB and CIFS those files and folders will be hidden

- using nearly 254 characters in filename. On SMB an CIFS you only have 254 characters WITH the file- and folderpath, altogether is counting in these 254 characters!

- oldstyle file are separated in Datafork and Programfork. So copying those files the infomation stored in Programfork will be lost and the datafile will be 0Kb!

It is hard and nearly hopeless to migrate a grown datavault of Mac files to SMB, cause the user have used special characters in a massive manner!!

**Comment by votdev** [comment]
I have to tell that i can not maintain this plugin anymore because of less time and not having any Apple Mac hardware to do any tests.

But i would be happy to see contributions from the community.

**Comment by phradr** [comment]
The lack of performance in file transfers with smb over afp would be a much greater benefit for (as I think) most users combining OS X and OMV5. The caching behavior of OS X with the smb protocol is horrible implemented and brings up a folder listing with only one subfolder after MINUTES (described in detail [here](https://forum.openmediavault.org/index.php?thread/28632-netatalk/&postID=234202#post234202)).

**Comment by latel** [comment]
I'd like AFP to be kept too

**Comment by tophee** [comment]
Hope this is not a dumb question, but what is the difference between this plugin and installing netatalk on the command line?

**Comment by votdev** [comment]
> Hope this is not a dumb question, but what is the difference between this plugin and installing netatalk on the command line?

You simply have to fill the UI forms and the rest is done by the plugin. You do not need to know which and how the config files must be populated.

**Comment by tophee** [comment]
OK, so that means it is still possible to run netatalk on OMV but you have to do all the config manually (and perhaps there are pitfalls in doing so?).

**Comment by votdev** [comment]
> OK, so that means it is still possible to run netatalk on OMV but you have to do all the config manually (and perhaps there are pitfalls in doing so?).

This is correct.

**Comment by ylluminate** [comment]
Has anyone put any work into this? I have a use case where it is still useful and ameliorates a few problems with SMB (especially with older systems that won't be going away anytime soon for some in some industries).

**Comment by mi-hol** [comment]
to be addressed in a later verion via #1143
