### ISSUE TITLE
No space available on btrfs after upgrade to Linux 5.4

### ISSUE THREAD

**Issue by rlhelinski** [openmediavault/openmediavault#578]
I am having the issue described here:

https://www.reddit.com/r/btrfs/comments/ehlpo7/df_reporting_no_space_left_but_btrfs_fi_usage/

`df` was showing something like
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       7.3T  3.7T     0 100% /sharedfolders/home
```

but btrfs was showing
```
ryan@omv:~$ sudo btrfs filesystem show /srv/dev-disk-by-label-btr/
Label: 'btr'  uuid: 8bf9c5b6-9637-43ab-a350-bbf65822d429
	Total devices 2 FS bytes used 3.64TiB
	devid    1 size 7.28TiB used 3.64TiB path /dev/sda1
	devid    2 size 7.28TiB used 3.64TiB path /dev/sdb1
```

I changed the line in my `/etc/default/grub` file from
```
GRUB_DEFAULT=0
```
to
```
GRUB_DEFAULT="gnulinux-5.3.0-0.bpo.2-amd64-advanced-46eb8037-5148-427c-944d-cda9518d0f87"
```

Then, I ran `sudo update-grub` and `sudo reboot`. The usage is back to normal with Linux 5.3, but I had to recreate my docker containers before everything was back to normal.

Sorry, am I the only one using `btrfs` on OMV 5?

**Comment by ryecoaaron** [comment]
As the reddit says, this is a Debian backports kernel bug.  omv-extras offers the option to install the proxmox (ubuntu) 5.3 kernel that would probably make this go away.  If you don't want to do that, the kernel tab of omv-extras allows you to select which kernel the system boots from without using the command line.

As for btrfs, since the official ISO creates an ext4 partition, you are going to be in the minority.

**Comment by rlhelinski** [comment]
I wanted to confirm that after upgrading to Linux 5.4.0-0.bpo.3-amd64 today I have not yet seen the 0 blocks available issue.

Also, I wanted to say that I have been considering installing OMV 4 instead of 5, but as long as the team keeps fixing issues with `btrfs`, I would be happy to continue testing and reporting bugs. Thanks for your help so far.

**Comment by rlhelinski** [comment]
Update: The 5.4.0-0.bpo.3 kernel did eventually exhibit the issue. I switched to the proxmox kernel and that has been running well.
