### ISSUE TITLE
Invalid RPC Response while adding a new shared folder

### ISSUE THREAD

**Issue by coffinbearer** [openmediavault/openmediavault#582]
Similar to #550 i get an Invalid RPC Responce error in the device selection during adding a shared folder from a btrfs 4-drive pool while opening the select device dropdown.
I was able to add shared folders from a single btrfs drive.
fresh install of openmediavault:
Release: 5.2.6-1
Linux 5.4.0-0.bpo.2-amd64 #1 SMP Debian 5.4.8-1~bpo10+1 (2020-01-07) x86_64 GNU/Linux

Syslog:
`Jan 31 18:28:45 omv28756 omv-engined[2974]: PHP Fatal error: Uncaught Error: Call to a member function getImpl() on null in /usr/share/php/openmediavault/system/filesystem/filesystem.inc:898
Jan 31 18:28:45 omv28756 omv-engined[2974]: Stack trace:
Jan 31 18:28:45 omv28756 omv-engined[2974]: #0 /usr/share/openmediavault/engined/rpc/sharemgmt.inc(88): OMV\System\Filesystem\Filesystem::getImplByMountPoint('/srv/dev-disk-b...')
Jan 31 18:28:45 omv28756 omv-engined[2974]: #1 [internal function]: Engined\Rpc\ShareMgmt->getCandidates(Array, Array)
Jan 31 18:28:45 omv28756 omv-engined[2974]: #2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
Jan 31 18:28:45 omv28756 omv-engined[2974]: #3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getCandidates', Array, Array)
Jan 31 18:28:45 omv28756 omv-engined[2974]: #4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('ShareMgmt', 'getCandidates', Array, Array, 1)
Jan 31 18:28:45 omv28756 omv-engined[2974]: #5 {main}
Jan 31 18:28:45 omv28756 omv-engined[2974]:   thrown in /usr/share/php/openmediavault/system/filesystem/filesystem.inc on line 898`

WebUI:
`Error #0:
OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187
Stack trace:
#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('ShareMgmt', 'getCandidates', Array, Array, 3)
#1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#2 {main}`

**Comment by Helly1206** [comment]
It seems that all filesystems that do not refer to /dev/xxxx cause this issue. I made a workaround to search the fs by type if the backend cannot be detected. I created a pull request.

**Comment by votdev** [comment]
> It seems that all filesystems that do not refer to /dev/xxxx cause this issue. I made a workaround to search the fs by type if the backend cannot be detected. I created a pull request.

I don't like workarounds, only solid solutions that fix the problem. Nevertheless, i will have a look into it.

**Comment by votdev** [comment]
Duplicate, see https://github.com/openmediavault/openmediavault/issues/583.
