### ISSUE TITLE
SSL/TLS : The value is not an object.

### ISSUE THREAD

**Issue by incorsa** [openmediavault/openmediavault#589]
When trying to setup SMTP with SSL/TLS
Happens all attempts.

Error #0:
OMV\Json\SchemaValidationException: : The value is not an object. in /usr/share/php/openmediavault/json/schema.inc:391
Stack trace:
#0 /usr/share/php/openmediavault/json/schema.inc(285): OMV\Json\Schema->validateObject(Array, Array, '')
#1 /usr/share/php/openmediavault/json/schema.inc(257): OMV\Json\Schema->validateType(Array, Array, '')
#2 /usr/share/php/openmediavault/rpc/paramsvalidator.inc(59): OMV\Json\Schema->validate(Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(179): OMV\Rpc\ParamsValidator->validate('[]')
#4 /usr/share/openmediavault/engined/rpc/notification.inc(149): OMV\Rpc\ServiceAbstract->validateMethodParams(Array, 'rpc.common.obje...')
#5 [internal function]: Engined\Rpc\Notification->get(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('get', Array, Array)
#8 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Notification', 'get', Array, Array, 1)
#9 {main}

### Versions report
5.2.7-1

**Comment by ryecoaaron** [comment]
Did you try clearing your browser cache or ctrl-shift-R?

**Comment by votdev** [comment]
How can we reproduce that? Which values have you entered?

**Comment by votdev** [comment]
Have you migrated from OMV4?

**Comment by incorsa** [comment]
Apologies, I am not used to reporting bugs and was hesitant even for this one.

ctrl-shift-R has removed the error message from showing up and I can now add the necessary data to the fields.   Before I logged the error I did reboot and the error was still showing.

This was a clean install.
