### ISSUE TITLE
FTP does not support non-ASCII characters

### ISSUE THREAD

**Issue by sanbrother** [openmediavault/openmediavault#590]
### Description of issue/question
When connected using Filezilla, I'm prompted that: "Server does not support non-ASCII characters"
I found this reference
[http://www.proftpd.org/docs/modules/mod_core.html#MultilineRFC2228](http://www.proftpd.org/docs/modules/mod_core.html#MultilineRFC2228)
Then I changed it to 'off' manually, but doesn't work.

BTW, as I remembered, 4.x doesn't have such issue.
### Steps to reproduce issue
(Include debug logs if possible and relevant.)

### Versions report
5.2.7-1

**Comment by votdev** [comment]
`Server does not support non-ASCII characters` is only a warning.

> BTW, as I remembered, 4.x doesn't have such issue.

I don't know, never saw this message.

To fix that issue you have to modify the configuration of your FTP client, see https://www.strato.com/faq/en_us/hosting/how-do-i-respond-to-the-error-code-server-does-not-support-non-ascii-characters for example.

**Comment by sanbrother** [comment]
Sorry, quite likely it is my own fault.

I have to TV-Boxes running armbian, one is running Debian 9, another running Debian 10.
I compared the two, finding that the locales are different.

The OK one has the en_US.UTF-8 locale, the NG one has the C.UTF-8 locale
I don't quite understand the difference, and will do more search.

Thank you very much.
