### ISSUE TITLE
[FEATURE REQUEST] SyncThing - because nextcloud is so "stressy" :-)

### ISSUE THREAD

**Issue by explanar** [openmediavault/openmediavault#592]
because nextcloud is complicated with php version in OMV4 and with docker / nginx / mariadb (or alternatively virtualbox) in OMV5 i switched to SyncThing installed in debian directly as a fast shot:

- install via deb repo as described
- generated user "syncthing" in OMV, 
- mkdir /home/syncthing and 
- chown syncthing:users
- generate a shared volume with rw access for the user syncthing

For autostart (quick'n'dirty) i added in /etc/rc.local
`su syncthing -c 'syncthing >/home/syncthing/syncthing.log 2>&1' &`

After the first execution of /usr/bin/syncthing the config is generated, edited acces rules to 0.0.0.0:8384 instead of 127.0.0.1:8384 so i can access UI from outside localhost. Restart.

Installation is now ready, access ST via http://IP-OMV-SERVER:8384 and optionally change to force https in settings.

**Comment by ryecoaaron** [comment]
What are you requesting?  If you want syncthing not in docker (not sure why and it doesn't require nginx and mariadb), you should port the 4.x plugin to 5.x.  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-syncthing

**Comment by explanar** [comment]
All right, thanks.
