### ISSUE TITLE
Webinterface file systems sorting bug

### ISSUE THREAD

**Issue by SadButTrueAT** [openmediavault/openmediavault#597]
### Description of issue/question
file systems is (un)sorted every few seconds even if it is sorted by "devices". this is very annoying/dangerous!

### Steps to reproduce issue
just go to the omv webinterface and klick on "file systems"

### Versions report
OMV 5.3.0-1

**Comment by votdev** [comment]
The sorting has been disabled for the `Device(s)` column because the data is an array which can contain various device files. I will not touch the ExtJS code anymore, thus disabling is the easiest way.

**Comment by SadButTrueAT** [comment]
thx!
