### ISSUE TITLE
Timeout on File Systems page when having many FS

### ISSUE THREAD

**Issue by Skaronator** [openmediavault/openmediavault#60]
Hey,

this is a long standing issue but it should be fixed at some point. Even when you end up increasing the timeout for this specific page. The current code is _probably_ query each FS in a row. Maybe it would be possible to make this async so it'll query all FS at the same time and wait for all results.

As temporary workaround I'd be fine to increase the timeout of the Webinterface but **how?** I've already increased the PHP timeout to 300 seconds but that didn't helped it still kicks the timeout after 30 seconds.

**Comment by Skaronator** [comment]
Aww thanks!

**Comment by Skaronator** [comment]
Still really bad... It takes 2 min 30 sec to load the file systems page! Another 2 min 30 sec to switch to page 2 and another 2 min 30 sec to switch to page 3! Still unusable. Here is a video (10 times speed): https://streamable.com/dck9h

CPU usage of the OMV command is ~10%. Looks like it always generate the data for all pages and regenerate the data for all pages when you change your page. It should have some kind of pagination.

Beside reducing the executed code for each page, would it be good to speed up the code itself. It only use 10% CPU and **most of the Filesystems are SSD only** so the drive is probably not bottlenecking the OMV code.


Also I got this error popup:
`: Missing 'required' attribute 'filename'.`

**Comment by votdev** [comment]
I'm sorry, processing and collecting data of 130 filesystems takes some time. If you have any idea how to improve this i'm open for contributions.

**Comment by Skaronator** [comment]
Where can I find the full stack trace? Here is a screenshot of the error:

![image](https://user-images.githubusercontent.com/2886913/37912243-5b681a0e-3112-11e8-8c70-92ba00dd4ea7.png)

**Comment by Skaronator** [comment]
> I'm sorry, processing and collecting data of 130 filesystems takes some time.

The main issue is that docker creates 120 filesystems and I'm just running 12 containers with 12 images (in total) and 16 volumes. Looks like there is no way to reduce it since Docker uses layered file systems by design.

Pagination might help alot without changing alot on the code.

**Comment by ryecoaaron** [comment]
> The main issue is that docker creates 120 filesystems and I'm just running 12 containers with 12 images (in total) and 16 volumes. Looks like there is no way to reduce it since Docker uses layered file systems by design.
Are your containers using zfs?

**Comment by votdev** [comment]
> Also I got this error popup:
: Missing 'required' attribute 'filename'.

The issue will be fixed in 4.1.3, see https://github.com/openmediavault/openmediavault/commit/765f60d9d6f1865729df5ab989db0fe373b362ea.

**Comment by Skaronator** [comment]
>Please press the 'Show details' buuton and post the full stack trace.

Oh damn I'm blind:
```
Error #0:
OMV\Json\SchemaValidationException: : Missing 'required' attribute 'filename'. in /usr/share/php/openmediavault/json/schema.inc:618
Stack trace:
#0 /usr/share/php/openmediavault/json/schema.inc(395): OMV\Json\Schema->checkProperties(Object(stdClass), Array, '')
#1 /usr/share/php/openmediavault/json/schema.inc(285): OMV\Json\Schema->validateObject(Object(stdClass), Array, '')
#2 /usr/share/php/openmediavault/json/schema.inc(257): OMV\Json\Schema->validateType(Object(stdClass), Array, '')
#3 /usr/share/php/openmediavault/rpc/paramsvalidator.inc(59): OMV\Json\Schema->validate(Object(stdClass))
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(173): OMV\Rpc\ParamsValidator->validate('{"pos":0}')
#5 /usr/share/openmediavault/engined/rpc/exec.inc(86): OMV\Rpc\ServiceAbstract->validateMethodParams(Array, 'rpc.exec.getout...')
#6 [internal function]: OMVRpcServiceExec->getOutput(Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#8 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getOutput', Array, Array)
#9 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Exec', 'getOutput', Array, Array, 1)
#10 {main}
```

>Are your containers using zfs?

Yes my ZFS Pool `StorageSSD/Docker` is mounted in `/var/lib/docker`.

**Comment by ryecoaaron** [comment]
> Yes my ZFS Pool StorageSSD/Docker is mounted in /var/lib/docker.

This is why it is slow for you.  aufs and overlayfs are not shown (or processed) in the filesystem tab and do not slow the list down.  zfs is shown.  We need to improve the zfs plugin to do something different in the filesystem backend (I think).

**Comment by Skaronator** [comment]
Which commands does the plugin use? When using `list -r -o name,available,used,mounted,mountpoint` it'll return everything I can see in the table:
```
NAME                                                                                     AVAIL   USED  MOUNTED  MOUNTPOINT
StorageHDD                                                                                160G  27,9T      yes  /srv/StorageHDD
StorageHDD/Backup                                                                         160G   453G      yes  /srv/StorageHDD/Backup
StorageHDD/Multimedia                                                                     160G  27,2T      yes  /srv/StorageHDD/Multimedia
StorageHDD/Temp                                                                           160G   245G      yes  /srv/StorageHDD/Temp
StorageSSD                                                                                657G   241G      yes  /srv/StorageSSD
StorageSSD/Docker                                                                         657G  2,82G      yes  /var/lib/docker
....
and all 120 other filesystems
```

within 0,2 second!
```
real    0m0,259s
user    0m0,024s
sys     0m0,233s
```

**Comment by votdev** [comment]
Use the source, Luke :-) There are more things done than running ONE command.

**Comment by ryecoaaron** [comment]
Now make it show if it is referenced in OMV.  Oh, and you need to show other filesystem types :)

**Comment by Skaronator** [comment]
@ryecoaaron 
> This is why it is slow for you. aufs and overlayfs are not shown (or processed) in the filesystem tab and do not slow the list down. zfs is shown.

Looks like I can't use overlayfs and overlayfs2 on top of ZFS (see [here](https://github.com/moby/moby/pull/10315/files)). And aufs isn't supported in Docker CE on Debian Stretch (see [here](https://docs.docker.com/storage/storagedriver/aufs-driver/) > Prerequisites).
