### ISSUE TITLE
Error with clamav-onaccess

### ISSUE THREAD

**Issue by Styx13** [openmediavault/openmediavault#607]
### Description of issue/question

Error when adding a shared folder for On Access Scans

### Steps to reproduce issue

Add a shared folder to On Access Scans
Apply configuration
Error appear: [clamav-onaccess-error.txt](https://github.com/openmediavault/openmediavault/files/4211484/clamav-onaccess-error.txt)

### Versions report
Debian 10.3
OMV 5.3.2-1
openmediavault-clamav 5.0.3-1

### Observations
Looking at the logs of the clamav-daemon.service it looks like it dies because of permission error on the socket `/run/clamav/clamd.ctl`
The socket belongs to `s--------- 1 root root 0 Feb 16 20:56 clamd.ctl`
After deleting the socket + manually modifying the /etc/clamav/clamd.conf and replace
`User root` by `User clamav`
It seems to all work.

Looks like this change may be related to the issue:
https://github.com/openmediavault/openmediavault/commit/66c77d114d8572c1d550ee53a52f4615b2ff08f4#diff-d3f59fcaade8bf6207cc5c6d6f740972R66

**Comment by votdev** [comment]
i had the same issue and could not get it running with `clamav` anymore, only `root` worked. The problem is the modified systemd unit file for `clamav-daemon` which is done by the Debian package maintainers. The directory permissions are hardcoded to `root`.

**Comment by Styx13** [comment]
I tried with both users (clamav & root), as long as I set the `LocalSocketGroup` and `User` (in `clamd.conf`) to the user and correspond group  (so root:root or clamav:clamav), there are no more complain about clamd having permission issues on the socket.

However `clamonacc` does not start right away and complains about "no space left on device", while I still have a lot of space in all my filesystems. After some googling, I found out it's a misleading error message, the real issue is not enough inotify watches.
According to Clamav documentation, `fs.inotify.max_user_watches` should be set to `524288` (https://www.clamav.net/documents/on-access-scanning#troubleshooting)

After that, `clamonacc` finally starts but now I have another issue: as soon as I try to access a file that's in one of the directory that clamav on access is wathing, it actually hangs. Looking at system activity, I can see clamav using all the CPU and memory (4 cores 16GB on my system, clamav tries to take everything ..). So I had to kill it.
It looks like there might be some clamav configuration tweaking required.

**Comment by Styx13** [comment]
Digging a little more, i found the reason for my problem: `clamd` could not open the files because of `apparmor`. I updated the `apparmor` profile for `/usr/sbin/clamd` to be allowed read access to `/srv/**` and now it works as expected.

That being said, the impact on the performance is not neglible (i.e. the time to open a file that gets scan, if you are for example browsing picture ... each picture takes way longer than without clamav on access .. to be expected I guess).

**Comment by plsm5882** [comment]
Downloaded and installed today. I am getting the same error when I try and enable on-access scanning, but only when adding more than one shared folder. Adding 2nd folder produces this error:

ID: start_clamav_onaccess_service
    Function: service.running
        Name: clamav-onaccess
      Result: False
     Comment: Service clamav-onaccess is already enabled, and is dead

None of the above actions, and some others, resolved it for me. I am new to Linux so I have no idea where to go from here.

RPi4, lastest Raspbian Lite (Rasbios Buster I think) and lastest OMV.
