### ISSUE TITLE
rsync jobs doesn't respect port

### ISSUE THREAD

**Issue by fumantsu** [openmediavault/openmediavault#608]
### Description of issue/question
I have create a job to do remote rsync and I'm using custom port. It seems from the job output that this is not the case if I use extra parameter for ssh (-e '/usr/bin/ssh -oStrictHostKeyChecking=no'). If I remove the specific one, looks that port is working but of course I'm getting the host key check error. Even with --port= or putting the port in the host doesn't work.
### Steps to reproduce issue
(Include debug logs if possible and relevant.)
![image](https://user-images.githubusercontent.com/7147643/74656211-fae87b80-518d-11ea-8f0c-7ad2cd9ea4b5.png)
![image](https://user-images.githubusercontent.com/7147643/74656222-fde36c00-518d-11ea-8887-bc0e27b19822.png)
![image](https://user-images.githubusercontent.com/7147643/74656488-8235ef00-518e-11ea-8f22-9bdb3a4186fc.png)

### Versions report
4.1.34-1

**Comment by fumantsu** [comment]
I think an option to disable the host checking would be nice

**Comment by ryecoaaron** [comment]
I would guess your extra option to disable strictHostkeychecking is overriding the OMV code that uses a different port.  Try the job without that extra option.

**Comment by fumantsu** [comment]
without the extra option is doesn't work since it is the first time connecting and the key is not inside known_hosts. If I add inside the extra option the -p then rsync works and I can remove the extra option  afterwards and everything working as should but... I think doesn't look nice that I have to do first a manual connect to add the host key.

**Comment by ryecoaaron** [comment]
I understand but not sure what to tell you.  Disabling strictHostkeychecking by default is a bad security practice and OMV can't parse your extra options to try to do the "right" thing.

**Comment by fumantsu** [comment]
I fully agree that in general it is a bad practice to have disabled the host key checking. Just putting into table a way to bypass for first time, since it puts me in to the process of connecting via ssh, finding the private etc...
Maybe, since (in my case) I'm using ssh key can be these two connected? A flag?

**Comment by votdev** [comment]
In OMV5 you can copy the public key of an SSH certificate created via UI to the target system.

![Bildschirmfoto vom 2020-02-17 14-54-21](https://user-images.githubusercontent.com/1897962/74659900-6bdf6180-5195-11ea-8edb-7fc8879d3211.png)

**Comment by mi-hol** [comment]
4.x is EOL
