### ISSUE TITLE
[Arrakis] [plexmediaserver] [PlexPy / Tautulli]

### ISSUE THREAD

**Issue by explanar** [openmediavault/openmediavault#609]
**PLEXMESIASERVER:**

openmediavault/mkconf/plexmediaserver : 
**REMOVE OR UNCOMMENT** 

> # EnvironmentFile=/etc/default/plexmediaserver

in [Service] Section.
Writing this Line to db_folder.conf causes Error.

`rm /opt/plexcodecs/Codecs` (only if Symlink to another Symlik back - causes Loop)
`mkdir /opt/plexcodecs/Codecs`
`chown plex:nogroup /opt/plexcodecs/Codecs`
`systemctl daemon-reload && systemctl start plexmediaserver`

Now Plex should Start, also Restart or if neccessary Reset your BROWSER!

**PlexPy / TAUTULLI:**
Set User and Group in `/lib/systemd/system/plexpy.service` to plex, Not tautulli, 
or the developer should change the complete plexmediaserver-plugin to create additional user tautulli

**Comment by ryecoaaron** [comment]
This belongs in the plex plugin issues - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver/issues - but I'm not maintaining that plugin anymore in favor of using docker.
