### ISSUE TITLE
add license text please

### ISSUE THREAD

**Issue by DEvil0000** [openmediavault/openmediavault#611]
this repo is missing a license file.
the website states it is GPL v3 so please add the license file here to the code.

**Comment by votdev** [comment]
That's not possible because this repository contains code that is not GPLv3, e.g. https://github.com/openmediavault/openmediavault/blob/master/deb/php-pam/debian/copyright.

**Comment by votdev** [comment]
GPLv3 only applies to the OMV sources which is spread across this GIT repo.

**Comment by DEvil0000** [comment]
how about git subrepositories for things licensed differently?

**Comment by ryecoaaron** [comment]
Why?

**Comment by votdev** [comment]
Why make it easy when you can make it complicated.

**Comment by votdev** [comment]
If you need to do license management, then do it yourself. All necessary information is available.
