### ISSUE TITLE
clamav doesn't start after install on OMV5

### ISSUE THREAD

**Issue by dt64** [openmediavault/openmediavault#614]
### Description of issue/question
clamav doesn't start

### Steps to reproduce issue
- fresh install of OMV5 
- install clamav using OMV5 GUI
- clamav service reported as not running
- deinstall and reinstall doesn't change things
- there is nothing in /var/log/clamav.log
- do all the above using a small uplink (<15MBit/s, see next comment)

# systemctl status clamav-daemon.service
● clamav-daemon.service - Clam AntiVirus userspace daemon
   Loaded: loaded (/lib/systemd/system/clamav-daemon.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/clamav-daemon.service.d
           └─extend.conf
   Active: failed (Result: exit-code) since Sat 2020-02-15 16:09:09 CET; 4 days ago
Condition: start condition failed at Wed 2020-02-19 23:25:15 CET; 9min ago
     Docs: man:clamd(8)
           man:clamd.conf(5)
           https://www.clamav.net/documents/
 Main PID: 624 (code=exited, status=1/FAILURE)

**Comment by dt64** [comment]
investigation showed that clamd can't start without database which needs to be provided by freshclam(d).
manual run of freshclam kept being unsuccessful because of short timeouts set:
:~# freshclam
Wed Feb 19 23:44:30 2020 -> ClamAV update process started at Wed Feb 19 23:44:30 2020
Wed Feb 19 23:44:30 2020 -> ^Your ClamAV installation is OUTDATED!
Wed Feb 19 23:44:30 2020 -> ^Local version: 0.102.1 Recommended version: 0.102.2
Wed Feb 19 23:44:30 2020 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
Wed Feb 19 23:44:30 2020 -> daily database available for download (remote version: 25728)
Wed Feb 19 23:45:00 2020 -> ^Download failed (28) Wed Feb 19 23:45:00 2020 -> ^ Message: Timeout was reached
Wed Feb 19 23:45:00 2020 -> ^getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Wed Feb 19 23:45:00 2020 -> Trying again in 5 secs...
Wed Feb 19 23:45:05 2020 -> daily database available for download (remote version: 25728)
Wed Feb 19 23:45:35 2020 -> ^Download failed (28) Wed Feb 19 23:45:35 2020 -> ^ Message: Timeout was reached
Wed Feb 19 23:45:35 2020 -> ^getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Wed Feb 19 23:45:35 2020 -> Trying again in 5 secs...
Wed Feb 19 23:45:40 2020 -> daily database available for download (remote version: 25728)
Wed Feb 19 23:46:10 2020 -> ^Download failed (28) Wed Feb 19 23:46:10 2020 -> ^ Message: Timeout was reached
Wed Feb 19 23:46:10 2020 -> ^getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Wed Feb 19 23:46:10 2020 -> Trying again in 5 secs...
Wed Feb 19 23:46:15 2020 -> daily database available for download (remote version: 25728)
Wed Feb 19 23:46:45 2020 -> ^Download failed (28) Wed Feb 19 23:46:45 2020 -> ^ Message: Timeout was reached
Wed Feb 19 23:46:45 2020 -> ^getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Wed Feb 19 23:46:45 2020 -> Trying again in 5 secs...
Wed Feb 19 23:46:50 2020 -> daily database available for download (remote version: 25728)
Wed Feb 19 23:47:20 2020 -> !Download failed (28) Wed Feb 19 23:47:20 2020 -> ! Message: Timeout was reached
Wed Feb 19 23:47:20 2020 -> !getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Wed Feb 19 23:47:20 2020 -> Giving up on https://database.clamav.net...
Wed Feb 19 23:47:20 2020 -> !Update failed for database: daily
Wed Feb 19 23:47:20 2020 -> ^fc_update_databases: fc_update_database failed: Connection failed (5)
Wed Feb 19 23:47:20 2020 -> !Database update process failed: Connection failed (5)
Wed Feb 19 23:47:20 2020 -> !Update failed.

the daily DB takes about 33 seconds on a slower home link (16MBit/s), the main DB takes about 70secs.
**Timeout is set in /etc/clamav/freshclam.conf to "ReceiveTimeout 30".**
**this needs to be increased to a more realistic value, e.g. 180 or 300.**

Does OMV configure /etc/clamav/freshclam.conf at install using GUI?

**Comment by votdev** [comment]
Already fixed, see https://github.com/openmediavault/openmediavault/commit/c8041112a920cbf939a2271f55a2223fe31c8993.

**Comment by dt64** [comment]
running OMV 5.3.2-1, no update available

**Comment by ryecoaaron** [comment]
The fix is in 5.0.4 version of the plugin which hasn't been uploaded yet.
