### ISSUE TITLE
Request for a more Mac friendly exprience 

### ISSUE THREAD

**Issue by mbgroen** [openmediavault/openmediavault#615]
1. I noticed the Service Discovery tab under the System -> Network menu item is missing in OMV version 5 (Will this return in the GA release?) I'm using it to change the name of the SMB/CIFS name in a Macintosh environment and would also like to be able to set the mimicked Avahi model type there (or set it default to Xserve that mostly resembles a NAS system).  

2. It would be great if it was possible to use the web UI to turn off NetBIOS, setting the "disable netbios = yes" option in the SMB/CIFS Advanced Settings doesn't seem to do anything. A toggle switch would be more user friendly then stopping and disabling  it from the cli. This helps preventing two computer icons showing up in the Finders Network browser (1 via Avahi and one ugly BSOD icon via NetBIOS)

And my last Mac related request... It would be nice if the VCF fruit options could be set in a more user friendly / descriptive  manner on the SMB/CIFS configuration page. Maybe a couple toggle switches with some explanatory text in a Macintosh related section together with my feature request for a NetBIOS toggle switch (

These request would help overcome the missing of the AFP protocol in OMV5 a bit ;-)

I really like OMV and am a happy user of version 4 now, this could just make the experience for Mac users a bit better.

Thanks for this nice piece of software,

Michiel

**Comment by votdev** [comment]
>     1. I noticed the Service Discovery tab under the System -> Network menu item is missing in OMV version 5 (Will this return in the GA release?)

This will never come back because OMV will not provide a UI for everything. It will be reduced to the minimum what is needed to get a system working. Everything else can be customized via env variables. You can use the `OMV_SAMBA_ZEROCONF_NAME` [environment variable](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/avahi/services/smb.sls#L27) to tweak that to your needs. Simply add it to `/etc/default/openmediavault`.


> And my last Mac related request... It would be nice if the VCF fruit options could be set in a more user friendly / descriptive manner on the SMB/CIFS configuration page. Maybe a couple toggle switches with some explanatory text in a Macintosh related section together with my feature request for a NetBIOS toggle switch

There will be no more options, OMV is no Webmin UI where everything can be configured. This is not and will never be the concept of OMV.


>     2\. It would be great if it was possible to use the web UI to turn off NetBIOS, setting the "disable netbios = yes" option in the SMB/CIFS Advanced Settings doesn't seem to do anything. A toggle switch would be more user friendly then stopping and disabling  it from the cli. This helps preventing two computer icons showing up in the Finders Network browser (1 via Avahi and one ugly BSOD icon via NetBIOS)

This would be a good enhancement. Any information how to switch off netbios would be great to be able to implement that feature. I can not research everything myself.

**Comment by mbgroen** [comment]
Thanks for your quick response. The OMV_SAMBA_ZEROCONF_NAME was what I was looking for under point 1. That's a good work around.

For point 2, just 1 toggle switch "Optimize for Mac-only client environments" could be an an option? Maybe just adding the Samba Mac optimizations to the "Advanced Settings" text field (min protocol = SMB2, vfs objects = catia fruit streams_xattr, fruit:metadata = stream, fruit:posix_rename = yes, fruit:veto_appledouble = no fruit:wipe_intentionally_left_blank_rfork = yes, fruit:delete_empty_adfiles = yes i.e.) Or invisible to the user? I don't think it matters much when you add them twice, when you add them later in the Advanced Settings field too by mistake.

Point 3 can be added to point 2 as well then. But otherwise it could just be a switch that checks if nmdb is running and / or enabled and if so runs systemctl stop nmbd.service and if enabled also systemctl disable nmbd.service.

**Comment by mbgroen** [comment]
Would it be possible to create an variable for the displayed icon in the Finder as well? 
Something like OMV_SAMBA_ZEROCONF_MODEL. 
I add to following to /usr/share/openmediavault/mkconf/avahiservices.d/smb in OMV 4 to realize this:

    <service>
        <type>_device-info._tcp</type>
        <port>0</port>
        <txt-record>model=Xserve</txt-record>
    </service>

Or is there another way to add this in OMV 5 that is sticky after UI updates ?

**Comment by votdev** [comment]
> Would it be possible to create an variable for the displayed icon in the Finder as well?
> Something like OMV_SAMBA_ZEROCONF_MODEL.
> I add to following to /usr/share/openmediavault/mkconf/avahiservices.d/smb in OMV 4 to realize this:
> 
> ```
> <service>
>     <type>_device-info._tcp</type>
>     <port>0</port>
>     <txt-record>model=Xserve</txt-record>
> </service>
> ```
> 
> Or is there another way to add this in OMV 5 that is sticky after UI updates ?

Use `OMV_SAMBA_FRUIT_MODEL`, see https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/avahi/services/files/smb.j2#L1.

**Comment by votdev** [comment]
> Maybe just adding the Samba Mac optimizations to the "Advanced Settings" text field (min protocol = SMB2, vfs objects = catia fruit streams_xattr, fruit:metadata = stream, fruit:posix_rename = yes, fruit:veto_appledouble = no fruit:wipe_intentionally_left_blank_rfork = yes, fruit:delete_empty_adfiles = yes i.e.) Or invisible to the user?

You can use `OMV_SAMBA_SHARE_VFSOBJECTS`, see https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/samba/files/shares.j2#L1.

Additional options that are not written by OMV can be added in the `Extra options`field per SMB share.

**Comment by mbgroen** [comment]
Thanks a lot, that was exactly what I was looking for!

**Comment by votdev** [comment]
>     2\. It would be great if it was possible to use the web UI to turn off NetBIOS, setting the "disable netbios = yes" option in the SMB/CIFS Advanced Settings doesn't seem to do anything.

The issue should have been fixed since years: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866125

**Comment by mi-hol** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866125 is closed now
