### ISSUE TITLE
Unwanted Slash (\) in alert emails

### ISSUE THREAD

**Issue by auanasgheps** [openmediavault/openmediavault#618]
### Description of issue/question
Since alert email formats has been changed, my device hostname appears with a backslash `\` in both the body and the email subject.
Obviously my hostname does not contain such character.
### Steps to reproduce issue
Get an email alert and observe the unwanted `\`

![email](https://user-images.githubusercontent.com/20586878/75123356-e719a980-56a6-11ea-899e-75a82b59deb6.jpg)

### Versions report
OMV 5.3.2-1

**Comment by votdev** [comment]
Monit is doin that; it's not possible to remove or fix this.

**Comment by bytebuster463** [comment]
> Monit is doing that; it's not possible to remove or fix this.

I think [this line](https://github.com/openmediavault/openmediavault/blob/0fc2562522392b9142ed6223ee87aca6364be791/deb/openmediavault/srv/salt/omv/deploy/monit/services/files/system.j2#L10) causes the problem.
It goes unchanged to `/etc/monit/conf.d/openmediavault-system.conf`.
Editing the latter and invoking `monit reload` fixes the issue.

**Comment by votdev** [comment]
> > Monit is doing that; it's not possible to remove or fix this.
> 
> I think [this line](https://github.com/openmediavault/openmediavault/blob/0fc2562522392b9142ed6223ee87aca6364be791/deb/openmediavault/srv/salt/omv/deploy/monit/services/files/system.j2#L10) causes the problem. It goes unchanged to `/etc/monit/conf.d/openmediavault-system.conf`. Editing the latter and invoking `monit reload` fixes the issue.

Nice catch. I only had [this file](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/monit/files/etc-monit-monitrc.j2#L34) on the radar.

**Comment by auanasgheps** [comment]
Thanks for catching and fixing the problem!
