### ISSUE TITLE
OMV5 - Problem with nginx activating multiple virtual hosts due to missing "default_server"

### ISSUE THREAD

**Issue by sseide** [openmediavault/openmediavault#620]
### Description of issue/question
The OMV web UI uses an nginx and adds a file with a `server{}` config to the `/etc/nginx/sites-enabled/` directory. When i want to add another additional virtual host to this directory (e.g. TLS enabled reverse proxy for portainer as it does not support TLS by now) i just link another file inside the `site-enabled/` directory also listening to the 80 and/or 443 port.

As soon as there is another file i cannot change configuration data inside the OMV-UI anymore which are connected to reconfiguring nginx, because after applying the changes the OMV UI does not work anymore / cannot be called anymore.

To fix this problem the LISTEN directive of the OMV UI has to be changed to include the `default_server` parameter. Adding this manually the OMV-UI works again as expected and the additional site is available under the `server_name` configured.

current OMV-UI config created (/etc/nginx/sites-enabled/openmediavault-webgui):
```
# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.

server {
    server_name openmediavault-webgui;
    root /var/www/openmediavault;
    ...
    listen [::]:80 ipv6only=off;
    listen [::]:443 ipv6only=off ssl deferred;
    ...
}    
```

How the file should look like to allow multiple virtual hosts inside the nginx:
```
# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.

server {
    server_name openmediavault-webgui;
    root /var/www/openmediavault;
    ...
    listen [::]:80 ipv6only=off default_server;
    listen [::]:443 ipv6only=off ssl deferred default_server;
    ...
}    
```

### Steps to reproduce issue
Add another nginx site with `server_name` attribute and at least on `listen` directive using the same port as OMV-UI to the nginx config (new config file file with `server { ...}` block inside the `/etc/nginx/sites-enabled/` directory.

Even when there are no other virtual sites configured adding the `default_server` parameter to `listen` does not hurt and should be the default i think.

### Versions report
OMV 5.3.2-1 (usul)
all updates installed as of today

Thanks for this wonderful software so far,
Stefan

**Comment by votdev** [comment]
Fixed in openmediavault 5.3.4

**Comment by mortee** [comment]
How can this behavior of adding default_server _disabled_? I would like to make a different app the default server.

**Comment by votdev** [comment]
> How can this behavior of adding default_server _disabled_? I would like to make a different app the default server.

That's not possible.

**Comment by mortee** [comment]
Should I open a new Issue to request this? I think it would be reasonable to make this configurable.

Not to mention that [apparently](https://forum.openmediavault.org/index.php?thread/12307-changing-omv-default-behavior-nginx-configuration/), back in the v2.x days, this exact same problem was addressed, and the default_server directive _removed_. Which got added back in v5.3.4

**Comment by votdev** [comment]
> Should I open a new Issue to request this? I think it would be reasonable to make this configurable.
> 
> Not to mention that [apparently](https://forum.openmediavault.org/index.php?thread/12307-changing-omv-default-behavior-nginx-configuration/), back in the v2.x days, this exact same problem was addressed, and the default_server directive _removed_. Which got added back in v5.3.4

The problem is that no configuration can fit all requirements. Please open a issue, so we have a number for the changelog. I think the easiest way would be to introduce a new environment variable that can switch on/off the `default_server` option.

**Comment by mortee** [comment]
Honestly, I fail to see why can't a toggle called "Make default web server" be added in General Settings / Web Administration / General Settings. Anyway, I'll open an issue.

**Comment by sseide** [comment]
reading the old issue it was definitely not the exact same problem but a very different one.

Old issue: adding a second ip address for an virtual host and someone wants a different webpage displayed on this new ip
with a _second_ nginx instance running on this new ip (not just a new virtualhost).

This issue: multiple sites on this same main ip address - served by the already running nginx available under different names. And no need to add a second nginx.

But i agree it might be helpful from time to time to have a different default site instead of OMV...

**Comment by ryecoaaron** [comment]
Most people don't need this because they run their nginx (or whatever) in docker with OMV on a non-standard port.  If they want OMV to respond on port 80, they add a proxy.  That is one of the main reasons the nginx plugin went away.

**Comment by mortee** [comment]
For historic reasons, I run OMV directly on my metal, and use nginx in front of it to reverse proxy for other services in docker containers. But for security reasons, I don't want to expose OMV when not specifically asked for in the Host header.

**Comment by ryecoaaron** [comment]
Why not run the proxy in docker and not expose OMV to the proxy at all?  i agree with not wanting OMV exposed easily.

**Comment by Dazix** [comment]
@mortee in fact there is solution or more like workaround... You can disable adding `default_server` option by setting env variable `OMV_NGINX_SITE_WEBGUI_LISTEN_PARAMS` to just space e.g. `omv-env set OMV_NGINX_SITE_WEBGUI_LISTEN_PARAMS " "` and than run 
```
# monit restart omv-engined
# omv-salt stage run prepare
# omv-salt stage run deploy
```
for more info check https://openmediavault.readthedocs.io/en/latest/various/advset.html

**Comment by mortee** [comment]
> @mortee in fact there is solution or more like workaround... You can disable adding `default_server` option by setting env variable `OMV_NGINX_SITE_WEBGUI_LISTEN_PARAMS` 

Yeah thanks, that variable just got added specifically because after the above exchange, I opened an [issue](https://github.com/openmediavault/openmediavault/pull/1190) asking for it, and @votdev was kind enough to implement it in an extremely short time.
