### ISSUE TITLE
USBBackup-Plugin - please add feedback on web UI if backup job is running

### ISSUE THREAD

**Issue by sseide** [openmediavault/openmediavault#621]
### Description of issue/question

after installing the USB-Backup plugin i can configure new jobs that should run after a external storage is connected. Even using an internal disk within a hot-swap case works fine. Thanks!

As some jobs may run a long time i seem to have no way to check via web UI if the backup job is running or has completed. Therefor i do not know when i may unplug the disk again..

Please add some feedback on the UI to show to the user if a job is running or not. Having multiple backup jobs configured it may not be needed to show which job is running, the information "something" is running may be enough to know when backup is finished and disk can be removed.

### Steps to reproduce issue
* Install USBBackup plugin
* Configure backup jobs via "USB Backup" menu
* Reconnect USB drive and jobs get startet
* only way to check by now is SSH into machine and do `ps axf | grep usbbackup.d` to check if there are some processes running

### Versions report
OMV 5.3.2-1
USB-Backup plugin 5.0.2-1

Thanks,
Stefan

**Comment by votdev** [comment]
Unfortunately it is not possible to implement this in the UI with reasonable effort. When you enable the email checkbox then you'll get notified when a job is done.

**Comment by sseide** [comment]
Ok, thanks. This is a usable alternative too i'll check out.
And thanks for the other issue fast fix!
