### ISSUE TITLE
OMV5 - Portainer UI is unsecure - please activate TLS

### ISSUE THREAD

**Issue by sseide** [openmediavault/openmediavault#622]
### Description of issue/question

Currently its possible to use OMV5 to run docker containers (very helpful!). As an UI "portainer" is used, but current one-click deployment via OMV web UI does not use TLS to encrypt communication with browser. Please update the portainer installation to use TLS.

### Steps to reproduce issue
activate OMV extras plugin, on the left click on Menu "OMV-Extras", then "Docker" -> "Portainer" -> "Install"
Portainer is installed but can only be used without TLS encryption. Updating docker deployment afterwards to enable TLS is not working.

### Steps to do to enable encryption
As i understand the following steps are needed to use SSL/TLS encryption for the web-ui in portainer.
* Update "OMV-Extras" -> "Docker" web ui, add checkbock "Enable TLS" and dropdown list with all SSL certificates configured within OMV
* Modify Portainer installation call
  a) bind mount the choosen certificate (key and cert file) into docker container
  b) add command line parameters needed to the docker CMD option to enable ssl (`--ssl --sslcert /tmp/ssl/cert.pem --sslkey /tmp/ssl/cert.key`) - see portainer documentation at https://portainer.readthedocs.io/en/stable/deployment.html#secure-portainer-using-ssl

Depending on how portainer is installed the following changes are needed on portainer installation.
Example with "docker run" command (docker compose file is similiar). For this example i assume the file name of the certificate choosen is "openmediavault-123"
```
docker run -v /etc/ssl/private/openmediavault-123.key:/tmp/ssl/cert.key -v /etc/ssl/certs/openmediavault-123.crt:/tmp/ssl/cert.pem <all other params> /portainer --ssl --sslcert /tmp/ssl/cert.pem --sslkey /tmp/ssl/cert.key
```

### Versions report
OMV 5.3.2-1
omvextrasorg 5.2.4

**Comment by votdev** [comment]
Please report this at https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-docker or https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-docker-gui. I don't know which plugin is related to Docker and Portainer in OMV5. Maybe Aaron reads this and can clarify us.

**Comment by ryecoaaron** [comment]
This is installed by omv-extras itself. The portainer install button is just supposed to be helpful. If you need TLS, you can manually add portainer via command line. The issue should be here though - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues
