### ISSUE TITLE
Failed to execute command

### ISSUE THREAD

**Issue by boredCat66** [openmediavault/openmediavault#623]
### Description of issue/question
I am currently unable to use my USB Stick in openmediavault, I plug it in and try to delete the filesystem, however I always get an error that the USB is being used.
I have a desktop connected to my raspberry pi, there are no windows open using the USB Stick, I cant seem to figure out why it wont use my USB stick
`Fehler #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; mkfs -V -t ext4 -b 4096 -m 0 -E lazy_itable_init=0,lazy_journal_init=0 -L 'USB1' '/dev/sda1' 2>&1' with exit code '1': mke2fs 1.44.5 (15-Dec-2018)
/dev/sda1 is apparently in use by the system; will not make a filesystem here! in /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc:672
Stack trace:
#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): Engined\Rpc\OMVRpcServiceFileSystemMgmt->Engined\Rpc\{closure}('/tmp/bgstatusAZ...', '/tmp/bgoutput10...')
#1 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(688): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure), NULL, Object(Closure))
#2 [internal function]: Engined\Rpc\OMVRpcServiceFileSystemMgmt->create(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('create', Array, Array)
#5 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('FileSystemMgmt', 'create', Array, Array, 1)
#6 {main}`
![Error1](https://user-images.githubusercontent.com/35631454/75275584-10504c00-5805-11ea-99b1-d1a40ba19db7.PNG)
![Error2](https://user-images.githubusercontent.com/35631454/75275586-10e8e280-5805-11ea-830c-bcf156c2e291.PNG)

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

**Comment by votdev** [comment]
Make sure all shared folders referencing this volume are not used by any service.  Reboot the system to be sure that no service is using it. After that delete the shared folders. Now you should be able to format the device.

I will close this issue because i can not do anything else. The volume IS in use by something, it is your part to find out what because i don't know what you've installed on your system.

**Comment by boredCat66** [comment]
it is an empty usb stick that has never been used, there is nothing on it, on my desktop there is no window open indicating use of the usb drive 
I also dont have any shared  folders, i am trying to start with omv but cant because my usb drive gives this error message :/

**Comment by ryecoaaron** [comment]
You should post on the forum.  And I hope the RPi does not have a desktop environment installed on it.
