### ISSUE TITLE
x-tab-default-top is uninteligeible as a tab

### ISSUE THREAD

**Issue by MarkFirewhal** [openmediavault/openmediavault#624]
#### Theme color styling makes it impossible to know the text at the top of body is a tab.

If you view the default theme-triton, there is no visual indication to the user that the text you've placed at the top of the body section are tabs. It just looks like text at the top of a screen -- until you hover across it -- there's no visual clue.

Please consider ADA when making style choices. Many of us are visually impaired and using bright colors with white text right on top does not help. Please modify the CSS to reflect the needs of the visually impaired. 

My suggestion would be: Modify background-color.
The current hover state `background-color rgba(0,0,0,.2)` does not change the background to represent any real change:
https://color.a11y.com/ContrastPair/?bgcolor=5DACDF&fgcolor=569FCE

Just pick a contrasting color to the current background and apply it to the `x-tab-default-top`

https://designsystem.digital.gov/design-tokens/color/system-tokens/
I’m not saying change your Corporate colors, just fix the tab. That way new visually impaired users are not left behind.

**Comment by votdev** [comment]
Is it possible to provide a before/after screenshot of what you're talking about?
