### ISSUE TITLE
test

### ISSUE THREAD

**Issue by superwinni2** [openmediavault/openmediavault#626]
### Description of issue/question
My OMV 5 is running as VM on Proxmox.
Syslog is writing errors that rrdcached.sock is not there. Due to that the the disk runs full.

### Steps to reproduce issue
I can only give you the syslog. Nothing special configured in OMV5.
syslog:
`root@openmediavault:~# tail -f /var/log/syslog
Feb 26 08:57:51 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
Feb 26 08:57:51 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
Feb 26 08:57:51 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
Feb 26 08:57:51 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
Feb 26 08:57:51 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
Feb 26 08:57:51 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
Feb 26 08:57:51 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
Feb 26 08:57:51 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
Feb 26 08:57:51 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
Feb 26 08:57:51 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
Feb 26 08:58:01 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
Feb 26 08:58:01 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
Feb 26 08:58:01 openmediavault collectd[1479]: rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2)
`

### Versions report
OMV Version: 5.3.0-1 (Usul)
Linux openmediavault 5.4.0-0.bpo.2-amd64 #1 SMP Debian 5.4.8-1~bpo10+1 (2020-01-07) x86_64 GNU/Linux

then also tried to update to latest version:
5.4.13-1 (Usul)
Linux openmediavault 5.4.0-0.bpo.3-amd64 #1 SMP Debian 5.4.13-1~bpo10+1 (2020-02-07) x86_64 GNU/Linux

**Comment by fajanisch** [comment]
Same issue after a clean new install - works on one system, but not the other...

**Comment by votdev** [comment]
Can you please find out why rrdcached is not running? OMV has no special configuration, it's more or less the default configuration shipped when you install the Debian package.

**Comment by floodi** [comment]
I have the same error. Omv5 clean install. /sbin/start-stop-daemon is zero length file. Could be the reason?

**Comment by fajanisch** [comment]
Found this command in an older thread: /usr/bin/rrdcached -B -F -f 3600 -w 900 -b /var/lib/rrdcached/db/ -j /var/lib/rrdcached/journal/ -p /var/run/rrdcached.pid -l unix:/var/run/rrdcached.sock - execution in console starts rrdcached and monitoring works. Where in the startup scripts is rrdcached started? I guess something wrong there... Thanks for any advise

**Comment by votdev** [comment]
> Found this command in an older thread: /usr/bin/rrdcached -B -F -f 3600 -w 900 -b /var/lib/rrdcached/db/ -j /var/lib/rrdcached/journal/ -p /var/run/rrdcached.pid -l unix:/var/run/rrdcached.sock - execution in console starts rrdcached and monitoring works. Where in the startup scripts is rrdcached started? I guess something wrong there... Thanks for any advice

systemd is responsible for starting rrdcached. The condiguration is generated [here](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/rrdcached/default.sls).
