### ISSUE TITLE
USB CDVD Drive: Eject issues

### ISSUE THREAD

**Issue by atomic83GitHub** [openmediavault/openmediavault#630]
# Description of issue/question

When inserting a disc into a usb cdvd drive, it will remain stuck inside (even if it is readable).

Thus, I must reboot and go into the Bios to eject the disc. The drive tested is the Xbox 360 HD DVD usb drive.

### Steps to reproduce issue

Put a disc inside a USB disc drive.

### Versions report
4.1.34-1

**Comment by votdev** [comment]
I don't think this is related to OMV only.
