### ISSUE TITLE
Can't create a new drive disk/by-label/

### ISSUE THREAD

**Issue by Zettt** [openmediavault/openmediavault#631]
### Description of issue/question

Hello,

I'm having an issue getting a disk properly mounted. It's labeled/named Backup2. I've had this disk mounted before, and for some reason couldn't write to it. I've tried using the web interface to wipe/formate the disk but no luck. Now, when I try to mount the drive, OMV tells me the disk Backup2 is already in use. As far as I can tell, this is an issue with the disk being labelled the same as a disk that has been in use before, or something along those lines. Is it possible to remove that drive from the list of "known devices"/

Any help appreciated. Thank you.

```
omv
Page
1
of 1
Displaying items 1 - 6 of 6
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; mount -v --source '/dev/disk/by-label/Backup2' 2>&1' with exit code '32': mount: /srv/dev-disk-by-label-Backup2: wrong fs type, bad option, bad superblock on /dev/sdc1, missing codepage or helper program, or other error.
```

**Comment by votdev** [comment]
If there is a filesystem with the same label in the database, then you should remove it before you try to mount another filesystem with the same label. It is not possible to mount filesystems with the same label at the same time.

> `mount: /srv/dev-disk-by-label-Backup2: wrong fs type, bad option, bad superblock on /dev/sdc1, missing codepage or helper program, or other error.`

This error indicates that something is wrong with your filesystem. You should reboot the system to ensure that absolutely nothing uses the disk before you wipe and create a new filesystem.

**Comment by Zettt** [comment]
Thank you for your help. Unfortunately it won't get any sort of attention in [the forum](https://forum.openmediavault.org/index.php/Thread/31211-Can-t-create-a-new-drive-disk-by-label/). As written in the post, I'm looking for ways to remove the disk label from the database. I can't find a way to remove it from the web interface. Hence my confusion, and hence my question. Since I couldn't find that function in the interface, I felt it belongs here.

Anyway, the main question is unanswered, still. 

How do I remove a disk from the database?
