### ISSUE TITLE
SMB speed too slow on Mac os 10.15 

### ISSUE THREAD

**Issue by 81pla** [openmediavault/openmediavault#633]
### Description of issue/question

SMB speed too slow on Mac os 10.15

only 100M-200Mbps  . but in Windows can 1Gbps

Is there any way to improve speed？

I know openmediavault-netatlk  Not  available on OMV5.X

### Versions report

Omv 5.3.6

**Comment by votdev** [comment]
Have you tried jumbo frames in the network interface (MTU=9000)?

**Comment by 81pla** [comment]
> Have you tried jumbo frames in the network interface (MTU=9000)?

I use WIFI  to access the omv 。 MTU max is 1500。

**Comment by 81pla** [comment]
I tried SMB and NFS on mac.   both 100M-200Mbps。

but use SFTP can up to 1Gbps。

**Comment by votdev** [comment]
I'm afraid I can't help here.

**Comment by FuntKlakow** [comment]
> I use WIFI to access the omv 

Use a cable connection instead. WIFI will never bring you close to GBit. In fact, 200MBit is probably the best you will get using WIFI.

**Comment by votdev** [comment]
And keep in mind that FTP is a much more trivial protocol than SMB, so you should assume that SMB is slower than FTP.
