### ISSUE TITLE
OMV 5 no Disk I/O Disk Usage Graphs

### ISSUE THREAD

**Issue by ricardoj-br** [openmediavault/openmediavault#634]
### Description of issue/question
There is no Graphs for Disk I/O and Disk Usage TAB under System Information | Performance Statistics

### Steps to reproduce issue
Just open System Information | Performance Statistics | Disk I/O or System Information | Performance Statistics | Disk Usage

I can see PNG files at /var/lib/openmediavault/rrd# ls disk*
disk-octets-sda-day.png    disk-octets-sdc-hour.png   disk-ops-sda-month.png  disk-ops-sdc-week.png    disk-time-sda-year.png
disk-octets-sda-hour.png   disk-octets-sdc-month.png  disk-ops-sda-week.png   disk-ops-sdc-year.png    disk-time-sdc-day.png
disk-octets-sda-month.png  disk-octets-sdc-week.png   disk-ops-sda-year.png   disk-time-sda-day.png    disk-time-sdc-hour.png
disk-octets-sda-week.png   disk-octets-sdc-year.png   disk-ops-sdc-day.png    disk-time-sda-hour.png   disk-time-sdc-month.png
disk-octets-sda-year.png   disk-ops-sda-day.png       disk-ops-sdc-hour.png   disk-time-sda-month.png  disk-time-sdc-week.png
disk-octets-sdc-day.png    disk-ops-sda-hour.png      disk-ops-sdc-month.png  disk-time-sda-week.png   disk-time-sdc-year.png

Files are updated from time to time but not available from GUI

### Versions report

OMV 5.3.6-1 (Usul)

Kernel  - 5.4.0-0.bpo.3-amd64

S.M.A.R.T is enabled as well

**Comment by votdev** [comment]
The PNG files you see in the filesystem are the one that are displayed in the UI. These files include the error images, too. So the interesting part is what is below `/var/lib/rrdcached/db/localhost/disk-xxx`. I assume that there is no RRD file.

On my system a SSD only shows a small number of infos compared to a HDD.

```
root@titan:~# ls -alh /var/lib/rrdcached/db/localhost/disk-md0
insgesamt 592K
drwxr-xr-x  2 root root 4,0K Mär  5 15:04 .
drwxr-xr-x 17 root root 4,0K Mär  5 15:04 ..
-rw-r--r--  1 root root 289K Mär  5 15:08 disk_octets.rrd
-rw-r--r--  1 root root 289K Mär  5 15:08 disk_ops.rrd
root@titan:~# ls -alh /var/lib/rrdcached/db/localhost/disk-sde/
insgesamt 1,5M
drwxr-xr-x  2 root root 4,0K Mär  5 15:04 .
drwxr-xr-x 17 root root 4,0K Mär  5 15:04 ..
-rw-r--r--  1 root root 289K Mär  5 15:04 disk_io_time.rrd
-rw-r--r--  1 root root 289K Mär  5 15:04 disk_merged.rrd
-rw-r--r--  1 root root 289K Mär  5 15:15 disk_octets.rrd
-rw-r--r--  1 root root 289K Mär  5 15:15 disk_ops.rrd
-rw-r--r--  1 root root 289K Mär  5 15:15 disk_time.rrd
```

I fear that i can not do anything here because if the `collectd disk` plugin can't collect the data, then the UI can not display a graph. I can not tell you why there are some cases that the `collectd disk` plugin can not collect them and in other cases it works.

**Comment by ricardoj-br** [comment]
Hi,

Here is my /var/lib/rrdcached/db/localhost/disk-sda directory

ls /var/lib/rrdcached/db/localhost/disk-sda -alh

total 1.5M
drwxr-xr-x  2 root root 4.0K Mar  5 07:47 .
drwxr-xr-x 14 root root 4.0K Mar  5 07:47 ..
-rw-r--r--  1 root root 289K Mar  5 18:10 disk_io_time.rrd
-rw-r--r--  1 root root 289K Mar  5 18:10 disk_merged.rrd
-rw-r--r--  1 root root 289K Mar  5 18:15 disk_octets.rrd
-rw-r--r--  1 root root 289K Mar  5 18:15 disk_ops.rrd
-rw-r--r--  1 root root 289K Mar  5 18:15 disk_time.rrd

If I access http://My-IP/rrd.php?name=disk-time-sda-day.png I can see the graph.

Thank you.

**Comment by ricardoj-br** [comment]
Hi,

It looks like this

![image](https://user-images.githubusercontent.com/20463353/76096481-f2bd7800-5fa4-11ea-81aa-e80ce70e2a6a.png)

Even "Refresh" button is missing.

From F12 the block that must present "Refresh" button + images I have 

`<div id="ext-comp-1441-body" data-ref="body" class="x-panel-body x-panel-body-default x-panel-body-default x-noborder-trbl" role="presentation" style="width: 908px; left: 0px; height: 574px; top: 44px;"></div>`

Regards

**Comment by votdev** [comment]
I realized that yesterday, too. But the tabs appear after some time. I think collecting the data in the backend takes some time sometimes. If there is no error displayed in the browser tools, then i have no idea what's going on.

**Comment by votdev** [comment]
The issue is reproducible when devices are stopped via hdparm. The UI requests a list of devices which will take some time until the devices are wake up and the RPC request succeeds. The tabs appear after some time automatically.

**Comment by ghemberg** [comment]
I have the same issue here: neither "Disk usage" nor "Disk I/O" (from openmediavault-diskstats plugin) tab list any of my drives, since upgrading to OMV5 (upgraded in July 2020 using method described [here](https://forum.openmediavault.org/index.php?thread/27909-omv-5-0-finally-out/&postID=219830#post219830)). PNG-files are generated regularly and contain actual data.

No drive-tabs show up, not even after waiting for 15 minutes.
Developer-tools in browser don't show anything peculiar, save for the regular HTTP-POSTs to rpc.php (every few seconds).

Occurs with OMV v5.5.4-1; kernel 5.6.0-0.bpo.2-amd64.

**Comment by mervincm** [comment]
I saw this when I had a missing disk. Once I had cleaned up the share and the file systems then the I/O and usage graphs showed up.

**Comment by ghemberg** [comment]
I forgot to leave a comment here as well (I posted my [issue on the OMV forum](https://forum.openmediavault.org/index.php?thread/33629-no-disk-tabs-shown-in-disk-usage-nor-disk-i-o/) as well):

Found the cause: I had an entry as follows in config.xml:
```xml
<mntent>
  <uuid>e8ab8481-4f9a-4ecb-a439-9fc5a12ea10f</uuid>
  <fsname>/srv/86531979-48b9-42be-a7d1-e0d735bd7880</fsname>
  <dir>/srv/86531979-48b9-42be-a7d1-e0d735bd7880</dir>
  <type>fuse.mergerfs</type>
  <opts></opts>
  <freq>0</freq>
  <passno>0</passno>
  <hidden>1</hidden>
</mntent>
```

Note the bad "fsname" value. Problem went away when I replaced it by "86531979-48b9-42be-a7d1-e0d735bd7880".

**Comment by GrayXu** [comment]
> I forgot to leave a comment here as well (I posted my [issue on the OMV forum](https://forum.openmediavault.org/index.php?thread/33629-no-disk-tabs-shown-in-disk-usage-nor-disk-i-o/) as well):
> 
> Found the cause: I had an entry as follows in config.xml:
> 
> ```
> <mntent>
>   <uuid>e8ab8481-4f9a-4ecb-a439-9fc5a12ea10f</uuid>
>   <fsname>/srv/86531979-48b9-42be-a7d1-e0d735bd7880</fsname>
>   <dir>/srv/86531979-48b9-42be-a7d1-e0d735bd7880</dir>
>   <type>fuse.mergerfs</type>
>   <opts></opts>
>   <freq>0</freq>
>   <passno>0</passno>
>   <hidden>1</hidden>
> </mntent>
> ```
> 
> Note the bad "fsname" value. Problem went away when I replaced it by "86531979-48b9-42be-a7d1-e0d735bd7880".

Great! I had same problem, and the reason is the info of a "missing" (plug out) filesystem is still in config.xml. Remove the wrong 
fsname entry, and everything works fine
