### ISSUE TITLE
Bug in the installer

### ISSUE THREAD

**Issue by Ansem93** [openmediavault/openmediavault#638]
Just installed OMV 5.
After selecting the disk it force to create the OS partition+swap. If i use "No" it will reload the same page, it won't ask me for a different configuration like just installing omv on a single partition without swap.
From this screen:
![immagine](https://user-images.githubusercontent.com/6626218/76330529-39390c80-62ee-11ea-9fb7-1e7e39e9cb36.png)
if you press no it will just reload endlessly, no further changes can be made.

**Comment by votdev** [comment]
That's by design. If you want to have the freedom to do that, then you should use Debian netinst ISO and manually install OMV according the [guideline](https://forum.openmediavault.org/index.php/Thread/25062-Install-OMV5-on-Debian-10-Buster/) in the forum.

**Comment by travnick** [comment]
I also was surprised by this action loop. Probably it would be nice to have a better explanation here in the installer.
