### ISSUE TITLE
Disk not found bc. OMV Disk Section uses /dev/disk/by-id?

### ISSUE THREAD

**Issue by OnkelM** [openmediavault/openmediavault#639]
### Description of issue/question
It seems omv is not using uuid for disk listing on WebGui disk section and SMART section but instead uses /dev/disk/by-id
Which conflicts on drives with same ids

The question is, how to deal with drives which seems to get recognized with the same ids and so on.

Look how jmicron is linked to sda but -part1 is linked to sdb1 which seems weird and maybe is dangerous

### Steps to reproduce issue
> `pi@RPi:/ $ ls -l /dev/disk/by-id/ | awk '{print $9,$10,$11}'`
> 
> ata-WDC_WD5000LPCX-22VHAT0_WD-WXL1A176XV2U -> ../../sdc
ata-WDC_WD5000LPCX-22VHAT0_WD-WXL1A176XV2U-part1 -> ../../sdc1
mmc-SE32G_0x53551492 -> ../../mmcblk0
mmc-SE32G_0x53551492-part1 -> ../../mmcblk0p1
mmc-SE32G_0x53551492-part2 -> ../../mmcblk0p2
usb-JMicron_Generic_0123456789ABCDEF-0:0 -> ../../sda
usb-JMicron_Generic_0123456789ABCDEF-0:0-part1 -> ../../sdb1
usb-TrekStor_DS_pocket_x.u_00e606cb-0:0 -> ../../sdd
usb-TrekStor_DS_pocket_x.u_00e606cb-0:0-part1 -> ../../sdd1
usb-TrekStor_DS_pocket_x.u_00e606cb-0:0-part2 -> ../../sdd2
wwn-0x50014ee60764c76e -> ../../sdc
wwn-0x50014ee60764c76e-part1 -> ../../sdc1

compared to uuid
> `pi@RPi:/ $ ls -l /dev/disk/by-partuuid/ | awk '{print $9,$10,$11}'`
> 
> 0edacb14-01 -> ../../sda1
1e3004d3-4375-476b-9e05-c6c741220595 -> ../../sdd2
738a4d67-01 -> ../../mmcblk0p1
738a4d67-02 -> ../../mmcblk0p2
9bf0f685-01 -> ../../sdb1
e64d937e-01 -> ../../sdc1
f105861f-5438-41da-b82b-d599ed8ef833 -> ../../sdd1

### Versions report
OMV5 on rpi4 with USB Hub

**Comment by votdev** [comment]
> Which conflicts on drives with same ids

If that happens, then something else has gone wrong before.

```
usb-JMicron_Generic_0123456789ABCDEF-0:0 -> ../../sda
usb-JMicron_Generic_0123456789ABCDEF-0:0-part1 -> ../../sdb1
```

As you see here, the kernel already gets confused. A partition should NEVER change the device name, only change the number. In this case it should be `sda1`.

> Look how jmicron is linked to sda but -part1 is linked to sdb1 which seems weird and maybe is dangerous

Things are already in a really really bad state. You should change the USB hub. Otherwise you will get data lost sometime.

This is not an OMV issue, it's a kernel driver or hardware issue. Using a different device path does not fix the problem.
