### ISSUE TITLE
OMV 5: no graphs are working

### ISSUE THREAD

**Issue by rabelux** [openmediavault/openmediavault#642]
### Description of issue/question
All graphs under `system information->performance statistics` are either empty/display "nan" or can't be displayed.
The ones that can't be displayed are only the ones for the second and third filesystems, all other graphs are empty.
![image](https://user-images.githubusercontent.com/16120882/76537396-fdcd4800-647d-11ea-8cba-fde460659cd7.png)

### Versions report
OMV: 5.3.7-1
Kernel: 4.19.97-v8
System: Raspberry Pi 4, ARMv7

**Comment by ToldoDM** [comment]
I had the same issue, try to see if in the system log there is a spam of message

> rrdcached plugin: Failed to connect to RRDCacheD at unix:/var/run/rrdcached.sock: Unable to connect to rrdcached: No such file or directory (status=2). 

I've solve this with:
```
cd /sbin/
mv start-stop-daemon.REAL start-stop-daemon
```

and then reboot. Now my graphs are showing.

**Comment by rabelux** [comment]
Hey, thanks for your suggestion! 
Unfortunately there is no such message and no `start-stop-daemon.REAL`.
My syslog shows following failures:
```
Mar 19 04:07:11 raspberrypi monit[1082]: 'nginx' failed protocol test [HTTP] at [127.0.0.1]:80 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Mar 19 20:48:15 raspberrypi blkmapd[150]: open pipe file /run/rpc_pipefs/nfs/blocklayout failed: No such file or directory
Mar 19 20:48:15 raspberrypi kernel: [    0.296504] simple-framebuffer: probe of 0.framebuffer failed with error -12
Mar 19 20:48:15 raspberrypi kernel: [    0.404614] bcmgenet fd580000.genet: failed to get enet clock
Mar 19 20:48:15 raspberrypi smartd[635]: Device: /dev/disk/by-id/ata-ST95005620AS_5YX0V3QX [SAT], open() failed: No such device
Mar 19 20:48:15 raspberrypi smartd[635]: Device: /dev/disk/by-id/usb-Seagate_Expansion+_NAAG6P10-0:0 [SAT], open() failed: No such device
```

**Comment by qntris** [comment]
Same issue here.

**Comment by Splitframe** [comment]
I had the same Issue and it started working by setting a time zone and enabling NTP.

**Comment by rabelux** [comment]
> My syslog did show a timestamp error though so it's probably a different problem.
Unfortunately true, timezone + NTP were set

**Comment by bka-git** [comment]
same issue, fixed by renaming the start-stop-daemon.REAL like described above.

**Comment by Tilmann-Glaeser** [comment]
I had the same issue on my Raspberry. 
The root cause was that the collectd daemon process was not running.
I fixed the issue with the commands:
`sudo systemctl enable collectd.service` to ensure that de daemon process is started after (re)booting 
`sudo systemctl start collectd.service` to start the daemon process
`sudo systemctl status collectd.service` to check the status
and you can use `ps -eaf | grep collectd` to check the PID of the process

I hop this helps for you as well.

**Comment by rabelux** [comment]
That did it, thank you! And also appreciate the detailed answer :+1:
May I ask how you tracked that down?

**Comment by rabelux** [comment]
@votdev I just did a clean install of omv on my raspberry pi 4 via the script from OpenMediaVault-Plugin-Developers/installScript and the collectd-service is disabled by default. Is that a bug or intended behaviour?

**Comment by ryecoaaron** [comment]
@rabelux the install script disables it because monitoring is disk intensive and hard on SD cards.

**Comment by Tilmann-Glaeser** [comment]
Make sense to install OMV on a Raspberry with a disabled
monitoring subsystem if the OS and application is on a SD card. I am
running the OS and applications on a SSD and the SD card is used for
booting the device only.
But it would be great if this would be mentioned  in the documentation or
script output.

Am Do., 11. Juni 2020 um 14:05 Uhr schrieb Aaron Murray <
notifications@github.com>:

**Comment by ryecoaaron** [comment]
It has been the recommended way for years on arm boards.  Every image has always been this way too.  Most people don't look at any of the script output either.

Message added - https://github.com/OpenMediaVault-Plugin-Developers/installScript/commit/85ea092ce07e1958974d4c84c67153e19536b924

**Comment by rabelux** [comment]
Thanks @ryecoaaron for clearing that up.
It does indeed make sense and hopefully people will either read your added message or find this issue to know what's going on
