### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by andre-bisa** [openmediavault/openmediavault#643]
Hello,
I unstalled OMV on my Raspberry Pi 3. During the installation (I used the install script in master branch) I've seen a lot of python "DeprecationWarning: SOMELIBRARY is deprecated since Python 3.5. Use SOMEOTHERLIBRARY". Often it said also "this will stop working in Python 3.8

**Comment by ryecoaaron** [comment]
This is just a warning and nothing to be concerned with.

**Comment by votdev** [comment]
I think your talking about the SaltStack generated Python warnings. We can not do anything here. Hopefully they will fix this in one of the next versions.
