### ISSUE TITLE
WebUI not working on chromebook

### ISSUE THREAD

**Issue by Ingenlys** [openmediavault/openmediavault#65]
I have a new installation of OMV 4.0.1 
When logged in to the WebUI on my chromebook the left hand panel is collapsed and impossible to expand.  This error is not present in chrome on windows or linux.

**Comment by votdev** [comment]
This is normal behaviour on touch devices.

**Comment by Ingenlys** [comment]
Additional info: The top row of buttons is not working either, making any navigation in the interface impossible, its stuck on the dashboard after login.

**Comment by votdev** [comment]
Can not reproduce this, sorry.
