### ISSUE TITLE
OMV5: ZFS import fails after OMV creates directories below the mount point

### ISSUE THREAD

**Issue by bp0** [openmediavault/openmediavault#651]
### Description of issue/question
ZFS mount (import), auto or manual, fails after OMV creates the shared path below the mount point.

### Steps to reproduce issue
(Include debug logs if possible and relevant.)
* Have a ZFS pool+filesystem with shares used by NFS or SMB.
* temporarily take the pool offline for a short time, or change its configuration outside of OMV. I can't figure out exactly what happens here to cause the path to be created.
  * for me: once by disconnecting disks, and once by adding a new mirror vdev to a pool
* reconnect the pool, try to import.
* the ZFS pool can not be mounted (imported) because the shared folder path has been created at the mount point.

### Versions report
OMV 5.3.8-1 usul

**Comment by votdev** [comment]
ZFS is not supported officially because of the unclear license issue. But we are open for community based PRs to fix that issue.
