### ISSUE TITLE
Feature Request: list the configuration changes that be applied when saying "yes" in the confirmation dialog

### ISSUE THREAD

**Issue by bp0** [openmediavault/openmediavault#652]
Sometimes you are required to say Yes or No to configuration changes without any indication of what is being changed or updated. It would be nice if the confirmation dialog would list the changes that are to be made.

**Comment by votdev** [comment]
This is not possible in a way i like to see because the backend only knows about the modules that have the be re-deployed, but not about the specific changes. You can use omv-firstaid to show a diff of various configuration changes. But there is no way to show them in a nice way in the UI.

**Comment by votdev** [comment]
PRs are welcome. Please check https://openmediavault.readthedocs.io/en/latest/development/index.html for more details how to contribute.

**Comment by bp0** [comment]
How can omv-firstaid be used to show the configuration diff?

**Comment by votdev** [comment]
Start it and you'll find the correct menu entry; i don't have every detail in mind.
