### ISSUE TITLE
Feature Request: Web UI add /dev/disk/by-label to Storage/SMART/Devices/Device Symlinks OMV5

### ISSUE THREAD

**Issue by RonOsborne** [openmediavault/openmediavault#655]
![SymlinksRequest](https://user-images.githubusercontent.com/21074099/77411901-daed4d00-6e08-11ea-9027-bbea46d69211.GIF)

###  Storage/SMART/Devices/Device Symlinks gives great detail of storage structure.
It's just missing  /dev/disk/by-label

**Comment by votdev** [comment]
If the UI does not display /dev/disk/by-label/<LABEL> then there is no devicefile like this for this device. OMV uses UDEV to get these symlinks.

**Comment by RonOsborne** [comment]
Hi
I'm new to linux, so please excuse me but I don't know anything about UDEV.
Each of my HDD/SSD have labels, and /dev/disk/by-label/ lists all of the devicefiles by thier label name.
What am I missing here?

**Comment by votdev** [comment]
Please post the output of `ls -alh /dev/disk/by-label` here.

> Each of my HDD/SSD have labels, and /dev/disk/by-label/ lists all of the devicefiles by thier label name.

These are the devicefiles for the filesystems on these disks.

**Comment by RonOsborne** [comment]
Thanks for taking the time on this votdev
Time I went and learnt about UDEV.

ls -alh /dev/disk/by-label
total 0
drwxr-xr-x 2 root root 300 Mar 24 21:25 .
drwxr-xr-x 7 root root 140 Mar 24 16:38 ..
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d03 -> ../../sdb1
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d11 -> ../../sdd1
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d12 -> ../../sde1
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d13x -> ../../sdc1
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d14 -> ../../sdg1
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d15 -> ../../sdf1
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d16 -> ../../sdh1
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d17 -> ../../sdj1
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d18x -> ../../sdi1
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d21 -> ../../sdk1
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d22 -> ../../sdl1
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d25 -> ../../sdm1
lrwxrwxrwx 1 root root  10 Mar 24 22:06 d26 -> ../../sdn1

blkid
/dev/sde1: LABEL="d12" UUID="224036c8-ea70-4165-829c-790cbda59633" TYPE="ext4" PARTUUID="6c88a055-01"
/dev/sdc1: LABEL="d13x" UUID="258a53e4-d8ef-4955-8979-44acb1c2f16f" TYPE="ext4" PARTUUID="dcf77da8-827d-47e7-a70e-3806f883bcb7"
/dev/sdd1: LABEL="d11" UUID="04adc2fb-e1ff-4de9-a848-737b7cf5172d" TYPE="ext4" PARTUUID="c2e322af-f7be-4767-942b-7b045189fd9e"
/dev/sdb1: LABEL="d03" UUID="365fd816-aa87-456c-921e-d2b1e91791fa" TYPE="ext4" PARTUUID="e64726bb-91fb-4406-bc3f-2d3713363cdc"
/dev/sda1: UUID="1b5b612d-258e-4a00-a8b8-801db8c97b39" TYPE="ext4" PARTUUID="d06bb79b-01"
/dev/sda5: UUID="36e5f9bc-c37b-4d80-9e2f-2aac37a14115" TYPE="swap" PARTUUID="d06bb79b-05"
/dev/sdg1: LABEL="d14" UUID="573a5844-b02f-4ea2-9f91-37ad0ed6b985" TYPE="ext4" PARTUUID="55e574b6-01"
/dev/sdi1: LABEL="d18x" UUID="a84af8cb-42fc-4b4f-b438-409a2b5d42df" TYPE="ext4" PARTUUID="341ae320-01"
/dev/sdj1: LABEL="d17" UUID="c5d27028-c4fc-42b9-92be-ea551271697f" TYPE="ext4" PARTUUID="95168bf9-01"
/dev/sdl1: LABEL="d22" UUID="a649fc62-a974-4925-b762-4366856e84cd" TYPE="ext4" PARTUUID="3ff0974e-ba4d-40cc-ac5b-eb0fe596c672"
/dev/sdk1: LABEL="d21" UUID="19fc6091-7b3f-424b-b0e3-d5240cb3aa20" TYPE="ext4" PARTUUID="876281e3-d420-4736-ba89-9ce87e920296"
/dev/sdh1: LABEL="d16" UUID="d638245b-c8db-4185-b0b3-b5a4340a9799" TYPE="ext4" PARTUUID="0009c3ba-01"
/dev/sdf1: LABEL="d15" UUID="cfc37168-76ef-4f38-83c9-1d1bd8920659" TYPE="ext4" PARTUUID="8c974552-01"
/dev/sdm1: LABEL="d25" UUID="24d6c5b8-63c5-4032-a791-62cdd36a7eb5" TYPE="ext4" PARTUUID="99b3b0d4-4954-47b3-a90b-9c45c1e7259e"
/dev/sdn1: LABEL="d26" UUID="eede5da5-7a2b-4fdf-af34-2eb4f1002c74" TYPE="ext4" PARTUUID="b83e262d-01"

**Comment by votdev** [comment]
> lrwxrwxrwx 1 root root 10 Mar 24 22:06 d03 -> ../../sdb1

That are ALL filesystems and no disks that can be displayed in the `SMART devices` table.

**Comment by RonOsborne** [comment]
Ok, thanks for the explanation, I see what you mean now about the disk and partition label differences.
I find it funny as I used GParted to partition and format the disks, and it only refers to labeling the disk.
Thanks again for your time and keep up the great work on OMV, it's a powerful and great OS.
