### ISSUE TITLE
Empty value for name = 'mtu'

### ISSUE THREAD

**Issue by anton** [openmediavault/openmediavault#659]
https://github.com/openmediavault/openmediavault/blob/c22a36ae42d3e60d90a51384b6a65cddb1a7ed28/deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py#L290

During the installation, I've observed for name = 'mtu', the variable value is empty, which makes the installation fail. It fails on line 290 in datamodel.py while trying to convert the empty variable to int(). Is this a consequence of a faulty parser somewhere else which is trying to obtain the mtu from ifconfig or similar?

**Comment by votdev** [comment]
Which version are you talking about?

**Comment by votdev** [comment]
I only know about the one place where `mtu` is touched during the package installation and [there](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/confdb/populate.d/40interfaces.sh#L71) it is set to 0.

How can we try to reproduce this? It must be a special workflow, otherwise this error must occur thousands of times.

**Comment by anton** [comment]
`# dpkg -l openmediavault | tail -1`
`ii  openmediavault 5.3.9-1      all          openmediavault - The open network attached storage solution`

**Comment by anton** [comment]
I had an old installation of openmediavault which I upgraded by first upgrade debian two versions, then reinstall the openmediavault package. I don't remember in which order I did steps. I guess you definitely can treat this issue as being part of a special workflow. I've patched the python file manually for now, because I got the same error when trying to add NFS shares.

I can see how this is one of the less good bug reports, and it's completely fine with me if we close it.

**Comment by anton** [comment]
The issue can be mitigated temporary by doing the following change

`289             elif "integer" == prop_schema['type']:
290                 if value.isdigit():
291                     result = int(value)
292                 else:          
293                   if name == 'mtu':
294                       result = 1500
295                   else:                                                           
296                       raise ValueError("Failed to convert property '{}'".format(name))
`
