### ISSUE TITLE
OMV 5 omv-salt deploy run ngingx fail due to ssl certificate incorrect generation

### ISSUE THREAD

**Issue by cotemok** [openmediavault/openmediavault#660]
### Description of issue/question
I recently upgraded from OMV 4 to OMV5 and had the following issue https://forum.openmediavault.org/index.php?thread/31648-omv-salt-deploy-run-nginx-rewrite-ssl-cert-and-keys-with-spaces/

I have investigated and this issue is linked to issue #352 (https://github.com/openmediavault/openmediavault/issues/352). commit 27c38099b1905a2ec09ab258aac91f2c665210a2 on file ssl.sls.

As I understand in issue 352 the key and the cert were generated without end of line.
Now there are generated with a 8 character space indent.
I am not a jinja developer and tried few things to correct it but I did not make it.
The bug fix would be to just make an new line with no indent, but I do not know how to do it.

### Steps to reproduce issue
The server needs to have the OMV ssl port activated and then run "omv-salt deploy run nginx".
I do not know if it mus be after an upgrade from OMV4 to OMV5, its my case so it my help to mention it.

**Comment by votdev** [comment]
Without the database which contains the SSL cert data i fear i can not reproduce this issue. I migrated my production system with SSL cert from OMV4 to OMV5 without problems.

**Comment by votdev** [comment]
The `indent` Jinja filter does not change anything in the SSL files, it only takes care that there are no Salt render errors in the SLS file.

```
root@omv5box:/home/vagrant# omv-salt deploy run certificates 
omv5box:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.certificates.ssl' failed: could not find expected ':'
```

**Comment by votdev** [comment]
Is it possible that the database looks like this
```
      <sslcertificate>
        <uuid>9f9daab5-878f-4f93-828f-03693c5aa729</uuid>
        <certificate>-----BEGIN CERTIFICATE-----
        MIIFOTCCAyGgAwIBAgIUdgkQtgYjEtIC/PqfdnqJaDxjB+YwDQYJKoZIhvcNAQEL
        BQAwITELMAkGA1UEBhMCQVMxEjAQBgNVBAMMCWxvY2FsaG9zdDAeFw0yMDAzMjYx
        NzQxMzNaFw0yMTAzMjYxNzQxMzNaMCExCzAJBgNVBAYTAkFTMRIwEAYDVQQDDAls
        b2NhbGhvc3QwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDdsULllmnr
        pGL+vC+w0vHFh0WOcx7j7pNIMWPTzHSzHUUgnAHRn0oiYmCd0xHALM9ugiQgGCJA
        ...
```
instead of 
```
      <sslcertificate>
        <uuid>9f9daab5-878f-4f93-828f-03693c5aa729</uuid>
        <certificate>-----BEGIN CERTIFICATE-----
MIIFOTCCAyGgAwIBAgIUdgkQtgYjEtIC/PqfdnqJaDxjB+YwDQYJKoZIhvcNAQEL
BQAwITELMAkGA1UEBhMCQVMxEjAQBgNVBAMMCWxvY2FsaG9zdDAeFw0yMDAzMjYx
NzQxMzNaFw0yMTAzMjYxNzQxMzNaMCExCzAJBgNVBAYTAkFTMRIwEAYDVQQDDAls
b2NhbGhvc3QwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDdsULllmnr
pGL+vC+w0vHFh0WOcx7j7pNIMWPTzHSzHUUgnAHRn0oiYmCd0xHALM9ugiQgGCJA
...
```
