### ISSUE TITLE
sys log error

### ISSUE THREAD

**Issue by yfdoor** [openmediavault/openmediavault#663]
### Description of issue/question

This log appears every one minute in system log, so if it's a error? I didn't set any 
“Planning tasks”

sys Log:
`Apr  3 20:40:01 omv CRON[25633]: (root) CMD (   test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)
Apr  3 20:41:01 omv CRON[25646]: (root) CMD (   test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)
Apr  3 20:42:01 omv CRON[25657]: (root) CMD (   test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)
Apr  3 20:43:01 omv CRON[25687]: (root) CMD (   test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)
Apr  3 20:44:01 omv CRON[25698]: (root) CMD (   test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)
Apr  3 20:45:01 omv CRON[25715]: (root) CMD (/usr/sbin/omv-mkrrdgraph >/dev/null 2>&1)
Apr  3 20:45:01 omv CRON[25714]: (root) CMD (   test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)
Apr  3 20:46:01 omv CRON[25832]: (root) CMD (   test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)
`

### Versions report
5.3.9

**Comment by votdev** [comment]
Please report the error [here](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wakealarm).

**Comment by votdev** [comment]
> This log appears every one minute in system log, so if it's a error?

No, according the [cron file](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wakealarm/blob/master/etc/cron.d/wakealarm) this is correct.

>I didn't set any “Planning tasks”

I'm not maintaining the wakealarm plugin, but as soon as you install the plugin the a cron job is executed continuously.

So i think there is no need to open a new ticket.

**Comment by yfdoor** [comment]
> > This log appears every one minute in system log, so if it's a error?
> 
> No, according the [cron file](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wakealarm/blob/master/etc/cron.d/wakealarm) this is correct.
> 
> > I didn't set any “Planning tasks”
> 
> I'm not maintaining the wakealarm plugin so i might be wrong, but as soon as you install the plugin the a cron job is executed continuously.
> 
> So i think there is no need to open a new ticket.

Ok, thanks, I remove wakealarm plugin, it's clear now. ....
