### ISSUE TITLE
Shared folders not mounting

### ISSUE THREAD

**Issue by VictorJosso** [openmediavault/openmediavault#664]
### Description of issue/question
Shared folders created from the web interface are not mounted into /sharedfolders.
```
root@openmediavault:~# lsblk -f
NAME   FSTYPE  LABEL        UUID                                 FSAVAIL FSUSE% MOUNTPOINT
sda
├─sda1 ext4                 fb4407f4-9d62-4198-aeca-7b89d7023eb8  101,1G     2% /
├─sda2
└─sda5 swap                 9984c020-156a-4d3d-92ff-7db90e117c34                [SWAP]
sdb
└─sdb1 ext4    OldSynoHDD   ef92641b-2567-4eff-9aed-76cbeba5a523   91,2G    90% /srv/dev-disk-by-label-OldSynoHDD
sdc
└─sdc1 ext4    New4TBHDD    e0f11ee6-8c59-4932-97d3-49c74864cdaa      3T    18% /srv/dev-disk-by-label-New4TBHDD
sdd
├─sdd1 hfsplus APconfig     3c602e56-50c9-3ed3-9ce7-977aa14c0429
├─sdd2 hfsplus APswap       4978ac72-fcb9-355b-a912-7c5a0d1d0e76
└─sdd3 ext4                 48dae1d6-00d4-425f-90eb-b7cf5b8a4bd2  367,3G    14% /srv/dev-disk-by-id-ata-ST3500630NS_Q_9QG8R0TL-part3
sde
└─sde1 ext4    1.41.12-3259 6c8dce2c-8ad3-4811-ba7b-337545c0d23c     18G    99% /srv/dev-disk-by-label-1.41.12-3259
sdf
└─sdf1 ext4    1.41.12-3252 19860caf-bb44-4c70-bf35-cbcbd954b48c  156,8G    66% /srv/dev-disk-by-label-1.41.12-3252
sdg
└─sdg1 ext3    1.41.3-1157  db81137f-755b-47d7-bb01-be27f13b06f9   75,7G    92% /srv/dev-disk-by-label-1.41.3-1157
```
Moreover, when I create a shared folder `test` the folder is created on the drive. But it seems that the system don't know this sharedfolder exists : 
```
root@openmediavault:~# systemctl restart 'sharedfolders-test.mount'
Failed to restart sharedfolders-test.mount: Unit sharedfolders-test.mount not found.
```
I really don't know what to do...

### Steps to reproduce issue
- Fresh install of OMV 5.3.9-1
- Basic config (time, users, filesystems, OMV Extras)
- Creating sharedfolders with the web interface
- Navigate to /sharedfolders through ssh. `ls` doesn't display anything
### Versions report
Openmediavault 5.3.9-1 (Usul) on Linux 5.4.0-0.bpo.4-amd64

**Comment by VictorJosso** [comment]
@ryecoaaron Sorry I don't get what you mean. In the past, shared folders have always been available in /sharedfolders folder immediately after addind them through the web interface. I encountered this issue since I reinstalled OMV after a massive crash...

**Comment by ryecoaaron** [comment]
And as of 5.3.4 (i think), the bind mount at /sharedfolder/SharedFoldeRName is disabled. you can still access the folder at their true mount of /srv/devicewhatever. The forum has plenty of threads about this.

**Comment by VictorJosso** [comment]
Okay thanks. Any way to enable it? It was much more convenient than
accessing files under /srv/ folder...

Le ven. 3 avr. 2020 à 21:54, Aaron Murray <notifications@github.com> a
écrit :

**Comment by VictorJosso** [comment]
Ok I have found myself thanks
https://forum.openmediavault.org/index.php?thread/30592-applying-configurations-in-the-web-interface-takes-forever/&postID=232947#post232947
