### ISSUE TITLE
wondershaper plugin

### ISSUE THREAD

**Issue by dev-sngy** [openmediavault/openmediavault#668]
Hi, I couldn't find anything about plugins that limit bandwidth of a specific network interface so I was curious if that's something ever planned. If not can I make one? :)

also, ```Please select the labels (on the right side) that match your issue/question.``` right where?

I might need some guidance on packaging the project if this ever becomes a thing.
Kind regards

**Comment by votdev** [comment]
> Hi, I couldn't find anything about plugins that limit bandwidth of a specific network interface so I was curious if that's something ever planned.

There are no plans to support that.

> I might need some guidance on packaging the project if this ever becomes a thing.

OMV plugins are simply Debian packages. Have a look into the already existing plugins like https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault-tftp.

**Comment by dev-sngy** [comment]
Hi I'be been tackling the source trying to figure things out.
I'm currently stuck in trying to figure this structure found in many of the "conf.service.~" models (i.e "conf.service.smb.json"):
```json
         "extraoptions": {
              "type": "string"
          },
          "shares": {
              "type": "object",
              "properties": {
                  "share": {
                      "type": "array",
                      "items": {
                          "type": "object",
                          "properties": {
                              "uuid": {
                                  "type": "string",
                                  "format": "uuidv4"
                              },
```

Why is "shares" an "object" type when it seems logical if it were an "array" type?
Why is "share" an "array" type when is seems logical if it were "object" type just like it is in "conf.service.smb.share.json"? 

I'm actually losing my mind over this lol. 

Help is much appreciated!!

**Comment by votdev** [comment]
The datamodel is described using json schema. You also need to keep in mind that the database uses XML which looks a little bit different than when you would use JSON.

**Comment by dev-sngy** [comment]
> The datamodel is described using json schema. You also need to keep in mind that the database uses XML which looks a little bit different than when you would use JSON.

Hi! Yes I'm aware.
So, 
> Why is "shares" an "object" type when it seems logical if it were an "array" type?
> Why is "share" an "array" type when is seems logical if it were "object" type just like it is in "conf.service.smb.share.json"?

I'm taking this as an example because I want a similar behavior for the plugin.

But I could be missing something so i'll take a look into JSON schema as suggested. Many thanks

**Comment by dev-sngy** [comment]
I was able to figure it out 👍 Many thanks

**Comment by dev-sngy** [comment]
I have another question. Are referenced config objects indestructible by default?

**Comment by votdev** [comment]
> I have another question. Are referenced config objects indestructible by default?

No, but you can forward the `_used` set to `True` field in a RPC response when you request a list of shares for example. The UI will disable the `Delete` button automatically in this case.

See https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/sharemgmt.inc#L178 or https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/var/www/openmediavault/js/omv/workspace/grid/Panel.js#L267.

**Comment by mi-hol** [comment]
@dev-sngy could this issue be closed?
