### ISSUE TITLE
Bond interface does not get an DHCP address

### ISSUE THREAD

**Issue by myomv100** [openmediavault/openmediavault#669]
Hi Everyone

When creating a bond interface from two Ethernet interfaces, it's expects that it gets an IP from the DHCP if IPv4 is set to DHCP. Unfortunately it does not any IP. Even if I set a static IP, it's not accessible from outside the machine.

**Comment by votdev** [comment]
Which OMV version is this related?

**Comment by myomv100** [comment]
It's the latest development release

**Comment by votdev** [comment]
It seems you need to reboot the system to force systemd-networkd to take the bond interface into action.

**Comment by votdev** [comment]
With Debian 11 (or systemd 244) we can use `networkctl` to reload a configuration. See https://unix.stackexchange.com/questions/262000/systemd-networkd-how-to-force-new-configuration-without-reboot#comment1057984_262000.

But until then it seems the system must be rebooted to take the changes into action.

**Comment by ryecoaaron** [comment]
netplan makes this very easy on Ubuntu and is already available on Ubuntu 18.04 :)

**Comment by votdev** [comment]
> netplan makes this very easy on Ubuntu and is already available on Ubuntu 18.04 :)

https://github.com/openmediavault/openmediavault/pull/676

**Comment by ryecoaaron** [comment]
Nice.  I didn't realize netplan.io was available on buster.
