### ISSUE TITLE
OpenVPN plugin not working on OMV 4

### ISSUE THREAD

**Issue by infestdead** [openmediavault/openmediavault#67]
​Hello,

I recently updated to OMV 4, and noticed that the OpenVPN doesn't start anymore, when applying changes it says:
`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; omv-mkconf openvpn setup 2>&1' with exit code '2': iptables: No chain/target/match by that name. iptables v1.6.0: option "--to" requires an argument Try `iptables -h' or 'iptables --help' for more information.

Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; omv-mkconf openvpn setup 2>&1' with exit code '2': iptables: No chain/target/match by that name.
iptables v1.6.0: option "--to" requires an argument
Try `iptables -h' or 'iptables --help' for more information. in /usr/share/php/openmediavault/system/process.inc:175
Stack trace:
#0 /usr/share/openmediavault/engined/module/openvpn.inc(88): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(168): OMV\Engined\Module\OpenVpn->applyConfig()
#2 [internal function]: OMVRpcServiceConfig->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(150): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(528): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatus11...', '/tmp/bgoutput7G...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(151): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(213): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: OMVRpcServiceConfig->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}`

I ssh-ed and created the postrouting masquarade rule manually for the VPN network, and manually started openvpn and it works, but GUI is still broken.

**Comment by votdev** [comment]
According to www.omv-extras.org there is no openvpn plugin for OMV4. Please report your issue here: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-openvpn
