### ISSUE TITLE
New NFS share with space in the name is improperly formatted in /etc/fstab

### ISSUE THREAD

**Issue by hardtimes** [openmediavault/openmediavault#671]
### Description of issue/question
First field of /etc/fstab improperly leaves a space in the path when adding a share to NFS, for example:

"/svr/ID/Folder Name/"
Mount throws error "see --help for usage".

Version 4.x of OMV put in "/svr/ID/Folder\040Name", which the mount command accepts.

### Steps to reproduce issue
(Include debug logs if possible and relevant.)
create a share with a space in the path.  Share that share via NFS.
### Versions report
5.3.9-1

**Comment by votdev** [comment]
Please not that after this fix it is still not possible to use and mount shared folders with blanks because of an bug in SaltStack.
