### ISSUE TITLE
OMV4 - Borg Backup Plugin - Add Archive menu is out of navigator view

### ISSUE THREAD

**Issue by githule** [openmediavault/openmediavault#674]
### Description of issue/question
- When I try to add an Archive via the BorgBackup/Archive menu I cant set every parameters because a part of the overlay window is out of the range of the navigator
- Tested with Chrome and Firefox.
- Resizing / Unzooming is not a workaround
### Steps to reproduce issue
![image](https://user-images.githubusercontent.com/34939356/79250395-de5f7b80-7e7e-11ea-9031-45ade68c0109.png)

### Versions report
- OMV Version is 4.1.35-1
- Borg plugin is 4.0.3

**Comment by ryecoaaron** [comment]
Issues for the borg plugin should be filed here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/issues
But I would guess you need to clear your browser cache.

**Comment by votdev** [comment]
A scrollbar should be displayed to allow you to scroll the form. IMO the dialog should automatically scale to the window size.

I fear i can not do anything here because the ExtJS library used to render the UI is somewhat outdated. That's why OMV6 will introduce a new UI to fix such issues.

**Comment by githule** [comment]
I found the issue here, don't know why the coordinate is negative : 
![image](https://user-images.githubusercontent.com/34939356/79270229-06aaa280-7e9e-11ea-9256-4d1a48ecb25c.png)

For the moment I use this trick by the developer mode of the browser.
Sorry, I didn't know about the plugin repo. I will post in the good one next time.
If UI is reworked in OMV6, I think that we can wait for the new version and close this ticket if you are ok.
