### ISSUE TITLE
Nitpick: Small display issue on login screen.

### ISSUE THREAD

**Issue by atomic83GitHub** [openmediavault/openmediavault#678]
In openmediavault 5, I have a small issue which do not affect the server usability but still worth mentioning.

The login screen appear like this at boot as it should:
![image](https://user-images.githubusercontent.com/26351275/79466226-949c9f80-7ffc-11ea-8272-dd3f9ee9ad97.png)

But later on (around 20 seconds or so) it appear like this (openmediavault login disapear):
![20200416_160427](https://user-images.githubusercontent.com/26351275/79466291-ac742380-7ffc-11ea-9529-05bf106d1d30.jpg)

Note that this doesn't affect in any way the login, you can still log in or just press enter without any login and the "openmediavault login" message will appear once again.

**This issue started to appear when installing a plugin or package but I don't remember which one, if anyone have this issue, please post it below**

**Comment by votdev** [comment]
Can not reproduce this.
![boot](https://user-images.githubusercontent.com/1897962/79467291-ebef3f80-7ffd-11ea-9b28-1bf3374eb8d6.gif)
I also have no idea about a reason for this.

**Comment by atomic83GitHub** [comment]
I think this should come from a specific plugin or package as it used to be fine for me before I install several things, I think the only way of testing this would be to run a 100% identical OMV install with every package I installed.

**Comment by atomic83GitHub** [comment]
Here is a video of my issue:

![20200416-163810-1](https://user-images.githubusercontent.com/26351275/79472436-20fe9080-8004-11ea-9e84-1d99ff5548d7.gif)

**Comment by votdev** [comment]
Hmmm, i can see something similar on another system. I don't know which subsystem is related, but it seems that the process which displays the boot kernel messages tries to print something after the welcome/login message has been displayed.
I think this is far out of the scope of OMV. Will keep this issue open.

**Comment by mi-hol** [comment]
@atomic83GitHub could you please post output of following?
OS Version: [uname -a]
OMV Version: [dpkg -l | grep openmediavault]

**Comment by mi-hol** [comment]
@votdev, doesn't look like this issue will affect usability, hence suggest to close
