### ISSUE TITLE
Rare race condition: Samba keep dead shared folders and make mntent confused

### ISSUE THREAD

**Issue by ghost** [openmediavault/openmediavault#679]
**I can happen a couple of user actions can cause a rare race condition:**

Here is one caused by the samba part on OMV in conjuction with the rootfs plugin, creating a shared folder on the root hard drive, then, referencing it in samba, then, removing the samba share but keeping the shared folder on root.

After those steps, reboot the machine and because of buggy bios, the drive name change.

But, dead samba share (which was removed) will still point the old drive name and make mntent thinking a drive is missing, thus, requiring the user to manualy edit mntent to remove the old hard drive (which is not anymore existant as it appear with a another name).

**Recreating the samba share after the issue is enough to correct the verbose syslog login and allow to remove the old mntent entry which do not appear anymore.**

**A way of fixing this issue would be to completely erase any sort of removed/dead samba shared folders in config files when the user remove the samba share but NOT the shared folder.**

**Comment by atomic83GitHub** [comment]
I know what was the issue and I can tell you the root of the issue.

**Comment by atomic83GitHub** [comment]
Also, this cause the share to have a N/A hard drive, how can I fix this in config files? 
![image](https://user-images.githubusercontent.com/26351275/79561202-3da0d400-80a9-11ea-9fae-6c5449621647.png)

**Comment by mi-hol** [comment]
@votdev sounds like a plugin related issue, could you please review ?

**Comment by votdev** [comment]
This sounds like a shared folder unit file issue. Because of that reason this feature has been disabled since a long time in OMV5.

> After those steps, reboot the machine and because of buggy bios, the drive name change.

Nevertheless, the problem is mentioned above. If the device file changes, then nothing can prevent the system from running wild. The only fix is by preventing the system to change the device files via BIOS update or whatever.
