### ISSUE TITLE
When updating settings OMV\Exception

### ISSUE THREAD

**Issue by SimonMcN** [openmediavault/openmediavault#68]
Hi,
I get this error when updating settings sometimes.  I'm on OMV 4.1.1-1 (Arrakis).
Thank you.

OMV\Exception: Failed to read file '/tmp/bgstatusgO158S' (size=0). in /usr/share/php/openmediavault/json/file.inc:199
Stack trace:
#0 /usr/share/php/openmediavault/json/file.inc(214): OMV\Json\File->getContents()
#1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(306): OMV\Json\File->read()
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(536): OMV\Rpc\ServiceAbstract->finalizeBgProcStatus('/tmp/bgstatusgO...', '', Object(OMV\Exception))
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(151): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#4 /usr/share/openmediavault/engined/rpc/config.inc(213): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#5 [internal function]: OMVRpcServiceConfig->applyChangesBg(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#8 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#9 {main}

**Comment by ryecoaaron** [comment]
There is a long thread about this in the forum.  We haven't found a solution and it seems to be a php bug.

**Comment by votdev** [comment]
Seems to be a PHP issue. To get more information i've improved the error message, see https://github.com/openmediavault/openmediavault/commit/8513749c820ae64b9d024d2f88cc333500bc1ac1.
