### ISSUE TITLE
When trying to apply configuration changes on SMB/CIFS I get this error.

### ISSUE THREAD

**Issue by JonnyGilchrist** [openmediavault/openmediavault#680]
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run samba 2>&1' with exit code '1': debian:
----------
          ID: configure_samba_global
    Function: file.managed
        Name: /etc/samba/smb.conf
      Result: True
     Comment: File /etc/samba/smb.conf updated
     Started: 20:56:03.478139
    Duration: 30.865 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -35,4 +35,3 @@
                   multicast dns register = no
                   # Special configuration for Apple's Time Machine
                   fruit:aapl = yes
                  -#======================= Share Definitions =======================
----------
          ID: configure_samba_shares
    Function: file.append
        Name: /etc/samba/smb.conf
      Result: True
     Comment: Appended 1 lines
     Started: 20:56:03.509091
    Duration: 30.207 ms
     Changes:
              ----------
              diff:
                  ---

                  +++

                  @@ -35,3 +35,4 @@

                   multicast dns register = no
                   # Special configuration for Apple's Time Machine
                   fruit:aapl = yes
                  +#======================= Share Definitions =======================
----------
          ID: configure_samba_recyclebin_cron
    Function: file.managed
        Name: /etc/cron.daily/openmediavault-samba-recycle
      Result: True
     Comment: File /etc/cron.daily/openmediavault-samba-recycle is in the correct state
     Started: 20:56:03.539383
    Duration: 0.95 ms
     Changes:
----------
          ID: remove_samba_recyclebin_cron_scripts
    Function: module.run
      Result: True
     Comment: file.find: []
     Started: 20:56:03.540734
    Duration: 0.477 ms
     Changes:
              ----------
              file.find:
----------
          ID: configure_default_wsdd
    Function: file.managed
        Name: /etc/default/wsdd
      Result: True
     Comment: File /etc/default/wsdd is in the correct state
     Started: 20:56:03.541281
    Duration: 0.894 ms
     Changes:
----------
          ID: test_samba_service_config
    Function: cmd.run
        Name: samba-tool testparm --suppress-prompt
      Result: False
     Comment: Command "samba-tool testparm --suppress-prompt" run
     Started: 20:56:03.542566
    Duration: 51.757 ms
     Changes:
              ----------
              pid:
                  2421
              retcode:
                  255
              stderr:
                  netbios name OPENMEDIAVAULTSERVER is not a valid netbios name
                  ERROR: Invalid smb.conf
              stdout:
                  # Global parameters
                  [global]
                  	disable spoolss = Yes
                  	encrypt passwords = Yes
                  	guest account = nobody
                  	log file = /var/log/samba/log.%m
                  	logging = syslog
                  	log level = 0
                  	max log size = 1000
                  	pam password change = Yes
                  	panic action = /usr/share/samba/panic-action %d
                  	passdb backend = tdbsam
                  	passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
                  	passwd program = /usr/bin/passwd %u
                  	printcap name = /dev/null
                  	server string = %h server
                  	socket options = TCP_NODELAY IPTOS_LOWDELAY
                  	unix extensions = Yes
                  	workgroup = WORKGROUP
                  	fruit:aapl = yes
                  	aio read size = 16384
                  	aio write size = 16384
                  	create mask = 0777
                  	directory mask = 0777
                  	use sendfile = Yes
----------
          ID: start_samba_service
    Function: service.running
        Name: smbd
      Result: False
     Comment: One or more requisite failed: omv.deploy.samba.default.test_samba_service_config
     Started: 20:56:03.601206
    Duration: 0.003 ms
     Changes:
----------
          ID: start_samba_service_nmbd
    Function: service.running
        Name: nmbd
      Result: False
     Comment: One or more requisite failed: omv.deploy.samba.default.start_samba_service
     Started: 20:56:03.601406
    Duration: 0.002 ms
     Changes:
----------
          ID: start_wsdd_service
    Function: service.running
        Name: wsdd
      Result: True
     Comment: The service wsdd is already running
     Started: 20:56:03.601442
    Duration: 18.515 ms
     Changes:

Summary for debian
------------
Succeeded: 6 (changed=4)
Failed:    3
------------
Total states run:     9
Total run time: 133.670 ms in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusv0...', '/tmp/bgoutputER...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}

**Comment by ryecoaaron** [comment]
While your hostname is valid for Linux and nfs, etc, it is too long for samba.

**Comment by JonnyGilchrist** [comment]
This worked, thank you very much

**Comment by votdev** [comment]
Fixed with https://github.com/openmediavault/openmediavault/commit/407dba39a52a471013f0ccbde0da6e3886c7c406 and https://github.com/openmediavault/openmediavault/commit/64cef8d7cfcb2dea622a1513b2c8d621b81c4dd4.
