### ISSUE TITLE
fresh install can't setup eth0

### ISSUE THREAD

**Issue by sagitt** [openmediavault/openmediavault#682]
### Description of issue/question
Fresh install today on RPi4 with official script, adding ethernet do this.
nothing changed, only add etherent.

![Schermata 2020-04-21 alle 20 09 44](https://user-images.githubusercontent.com/169086/79898823-2c8af680-840c-11ea-960d-8b670fd19899.png)

`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run systemd-networkd 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/utils/path.py:265: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working if not isinstance(exes, collections.Iterable): raspberrypi: ---------- ID: configure_etc_network_interfaces Function: file.managed Name: /etc/network/interfaces Result: True Comment: File /etc/network/interfaces updated Started: 20:09:38.308782 Duration: 66.602 ms Changes: ---------- diff: --- +++ @@ -1,7 +1,8 @@ +# This file is auto-generated by openmediavault (https://www.openmediavault.org) +# WARNING: Do not edit this file, your changes will get lost. + # interfaces(5) file used by ifup(8) and ifdown(8) - -# Please note that this file is written to be used with dhcpcd -# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf' +# Better use netplan.io or systemd-networkd to configure additional interface stanzas. # Include files from /etc/network/interfaces.d: source-directory /etc/network/interfaces.d ---------- ID: remove_systemd_networkd_config_files Function: module.run Result: True Comment: file.find: [] Started: 20:09:38.376883 Duration: 2.053 ms Changes: ---------- file.find: ---------- ID: remove_netplan_config_files Function: module.run Result: True Comment: file.find: [] Started: 20:09:38.379223 Duration: 1.962 ms Changes: ---------- file.find: ---------- ID: configure_netplan_default Function: file.managed Name: /etc/netplan/10-openmediavault-default.yaml Result: True Comment: File /etc/netplan/10-openmediavault-default.yaml updated Started: 20:09:38.381475 Duration: 17.541 ms Changes: ---------- diff: New file mode: 0644 ---------- ID: configure_netplan_ethernet_eth0 Function: file.managed Name: /etc/netplan/20-openmediavault-eth0.yaml Result: True Comment: File /etc/netplan/20-openmediavault-eth0.yaml updated Started: 20:09:38.399316 Duration: 59.896 ms Changes: ---------- diff: New file mode: 0644 ---------- ID: apply_netplan_config Function: cmd.run Name: netplan apply Result: False Comment: Command "netplan apply" run Started: 20:09:38.460932 Duration: 356.522 ms Changes: ---------- pid: 2124 retcode: 1 stderr: Traceback (most recent call last): File "/usr/sbin/netplan", line 23, in <module> netplan.main() File "/usr/share/netplan/netplan/cli/core.py", line 50, in main self.run_command() File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command self.func() File "/usr/share/netplan/netplan/cli/commands/apply.py", line 43, in run self.run_command() File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command self.func() File "/usr/share/netplan/netplan/cli/commands/apply.py", line 93, in command_apply stderr=subprocess.DEVNULL) File "/usr/lib/python3.7/subprocess.py", line 347, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo']' returned non-zero exit status 1. stdout: Summary for raspberrypi ------------ Succeeded: 5 (changed=6) Failed: 1 ------------ Total states run: 6 Total run time: 504.576 ms
``
### Steps to reproduce issue
(Include debug logs if possible and relevant.)

**Comment by votdev** [comment]
This seems to be a problem in the RPi image you are using. Simply delete the file `/etc/systemd/network/99-default.link`.

See https://forum.openmediavault.org/index.php?thread/32153-raspberry-pi-add-network-interface-fail/

**Comment by sagitt** [comment]
well i'll try, i already done 5 fresh install... same problem. Changing hostname too.

I used last script with changes (1.0.5)

**Comment by votdev** [comment]
The problem seems to be fixed, see https://github.com/OpenMediaVault-Plugin-Developers/installScript/commit/bd2a715006feeaa04661ae2e998019ac7ce146ab.

**Comment by sagitt** [comment]
> The problem seems to be fixed, see [OpenMediaVault-Plugin-Developers/installScript@bd2a715](https://github.com/OpenMediaVault-Plugin-Developers/installScript/commit/bd2a715006feeaa04661ae2e998019ac7ce146ab).

WELL!!!

**Comment by ryecoaaron** [comment]
Why five installations? Just killing your sd card.  I only saw the issue on armbian not raspian. My RPi upgraded fine. I will have to look at the rpi

**Comment by sagitt** [comment]
> Why five installations? Just killing your sd card. I only saw the issue on armbian not raspian. My RPi upgraded fine. I will have to look at the rpi

i tried some ways.... i hoped doing this. before new installation i upgraded and works fine but i want fresh installation for some reason and now.....

**Comment by ryecoaaron** [comment]
I don't see how the same fix is not fixing this issue.  What is the output of:

sudo udevadm -d test-builtin net_setup_link  /sys/class/net/lo

**Comment by sagitt** [comment]
> I don't see how the same fix is not fixing this issue. What is the output of:
> 
> sudo udevadm -d test-builtin net_setup_link /sys/class/net/lo

i just done NOW a fresh install, rpi4, raspbian buster, all operation of the OMV5 Installation PDF (passwd, update, adduser pi ssh etc.), executed the script and at the finish doing ls /etc/systemd/network i even see the file!

![Schermata 2020-04-21 alle 22 41 51](https://user-images.githubusercontent.com/169086/79911856-5f8bb500-8421-11ea-8e09-308845dd54aa.png)

**Comment by votdev** [comment]
Are you sure you are using OMV 5.4.0? To me it does not look like this. The file `/etc/systemd/network/openmediavault-eth0.network should not exist. Also the content of `/etc/network/interfaces`looks different in `5.4.0` according to your screenshot.

**Comment by sagitt** [comment]
i installed fresh raspbian 2020-02-13-raspbian-buster-lite after an sd card format, with balenaEtcher. I only executed the script: 

wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash

from UI:

![Schermata 2020-04-21 alle 23 00 54](https://user-images.githubusercontent.com/169086/79913499-fd807f00-8423-11ea-9422-74014741738d.png)

I installed it NOW.

**Comment by ryecoaaron** [comment]
@votdev the install script creates the openmediavault-eth0 file.  I need to come up with a better way to switch Armbian's networkmanager over to OMV's style (which now needs to be netplan).

**Comment by ryecoaaron** [comment]
@sagitt stop installing until we fix it then.

**Comment by sagitt** [comment]
> i installed fresh raspbian 2020-02-13-raspbian-buster-lite after an sd card format, with balenaEtcher. I only executed the script:
> 
> wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash
> 
> from UI:
> 
> ![Schermata 2020-04-21 alle 23 00 54](https://user-images.githubusercontent.com/169086/79913499-fd807f00-8423-11ea-9422-74014741738d.png)
> 
> I installed it NOW.



> @sagitt stop installing until we fix it then.

of course, now that i know tu bug, i'll wait... or maybe there is a way to install the older version?

**Comment by ryecoaaron** [comment]
it still isn't an openmediavault or installscript bug but we need to come up with a workaround for people lacking patience.

**Comment by sagitt** [comment]
> it still isn't an openmediavault or installscript bug but we need to come up with a workaround for people lacking patience.

well :). so there is not a way to install older version, right?

**Comment by ryecoaaron** [comment]
just wait.........

**Comment by votdev** [comment]
@ryecoaaron netplan.io can render configs for NetworkManager, too. Maybe this can be easily switched via environment variable for ARMbian and other NetworkManager based distros.

**Comment by ryecoaaron** [comment]
If you want to make that change, it doesn't bother me but I just committed the installscript with the netplan changes.

**Comment by votdev** [comment]
> If you want to make that change, it doesn't bother me but I just committed the installscript with the netplan changes.

No, if it works with the current behavior then it is ok. There are other many other things to do, no time to rest.

**Comment by sagitt** [comment]
if someone need a remote desktop for test the issue, tell me. is the only help that i can do.

**Comment by Slevinski** [comment]
I deleted the file /etc/systemd/network/99-default.link and rebooted.  I ran sudo omv-firstaid.  Chose option 1 to fix network interface.  It didn't hang and completed successfully.  One more reboot and then I opened OMV.  eth0 is available.  Things seem to be working...

**Comment by sagitt** [comment]
> I deleted the file /etc/systemd/network/99-default.link and rebooted. I ran sudo omv-firstaid. Chose option 1 to fix network interface. It didn't hang and completed successfully. One more reboot and then I opened OMV. eth0 is available. Things seem to be working...

i'll try!

so you installed raspbian, installed omv with script, deleted file, rebooted, omv-firstaid on network and all works fine?

**Comment by Slevinski** [comment]
No promises, but that worked for me so far.

**Comment by sagitt** [comment]
> No promises, but that worked for me so far.

ok i'll try. anyway this issue are closed. i think is better re-open it.

**Comment by IsonCode** [comment]
Hello, i have the same problem and when i exec this: sudo rm /etc/systemd/network/99-default.link the system stops working and i need to format the sd.
Have you found any solution?
thx

**Comment by votdev** [comment]
> Hello, i have the same problem and when i exec this: sudo rm /etc/systemd/network/99-default.link the system stops working and i need to format the sd.

This is a meaningless statement. Does it freeze, do you have no network connection after reboot, ... ???

Have you used `omv-firstaid` to reconfigure the network?

**Comment by IsonCode** [comment]
I just can't have any access to rasp with ssh

**Comment by IsonCode** [comment]
Do i need to remove this /etc/systemd/network/99-default.link Before or after exec the omv-install script?
