### ISSUE TITLE
OMV 5.3.10 and nginx file not found

### ISSUE THREAD

**Issue by gpongelli** [openmediavault/openmediavault#685]
### Description of issue/question
Hello, first of all thanks for this awesome software.
Playing with my raspberry, I came in a situation where :

- Openmediavault web interface was not available for timeout
- omv-firstaid, called to change the web port, exited with error without solving the issue (sorry I don't have the log now)

Panic!

I've tried to look at the `sudo omv-firstaid` logs into the console, and I've found a "file not found" issue for `/var/log/nginx/access.log` .
I've looked at the /var/log , surprisingly I didn't have any "nginx" folder. 

Homemade solution: 
Creating the nginx folder and touching the "access.log" and "error.log", Openmediavault web interface starts working again.

Now, is it possible to improve omv-firstaid to create the `/var/log/nginx/` folder and touching the two `/var/log/nginx/access.log` and `/var/log/nginx/error.log` if their open() calls raises a FileNotFound exception ?

Thanks.

ps
if it's an easy task, I could submit a PR.

### Versions report
Openmediavault 5.3.10 installed as a Debian package on raspberry pi 4 model B.

**Comment by votdev** [comment]
> Now, is it possible to improve omv-firstaid to create the /var/log/nginx/ folder and touching the two /var/log/nginx/access.log and /var/log/nginx/error.log if their open() calls raises a FileNotFound exception ?

No, I don’t like dirty hacks like this. I never saw this issue, so I guess your using some sort of tmpfs for /var to limit write access to your USB disk, right?

**Comment by gpongelli** [comment]
> No, I don’t like dirty hacks like this. There is no direct link between omv-firstaid and nginx. The only relation is that omv-firstaid restarts nginx when you reconfigure the network. 

This was the case, I was trying to change the omv port, this is why I thought it was an omv "issue". 

> The origin problem is that the environment for nginx is not in a correct state. No job for the first aid tool. The problem lies somewhere else and must be fixed there.
> 
> I never saw this issue, so I guess your using some sort of tmpfs for /var to limit write access to your USB disk, right?

I'm using log2ram, to limit memory card use. I'll check and try to fix that, thanks!

**Comment by votdev** [comment]
> I'm using log2ram, to limit memory card use. I'll check and try to fix that, thanks!

Then I am right with my expectation. Yes, log2ram seems not to setup the environment for nginx correctly.
