### ISSUE TITLE
[Feature Request] USB Backup logging

### ISSUE THREAD

**Issue by auanasgheps** [openmediavault/openmediavault#686]
### Description of issue/question

Currently "USB Backup plugin" does not have a dedicated logging section like other plugins do. Would be great to have that, so a user could go back in time and see when backup(s) was executed and how long it has taken to complete. 
I know the plugin makes a beep sound when it starts and finishes, but would be great to have it logged. 

I can see logs like this in _Syslog_ section like
`systemd[1]: Starting Execute the rsync backup jobs when /dev/disk/by-label/10TB is plugged in...`
and very detailed information in _Rsync - Jobs_ section, but I'm not into that detail.

I would like to see a _USB Backup_ section that simply tells me when backup started and ended.

**Comment by votdev** [comment]
> Currently "USB Backup plugin" does not have a dedicated logging section  like other plugins do.

That will not change. The USB backup plugin uses rsync under the hood, so the already available rsync log is used.

>  would like to see a USB Backup section that simply tells me when backup started and ended.

The plugin logs the starting and stopping to syslog. You can configure a job to send an email when it is finished.

**Comment by auanasgheps** [comment]
The option to send emails is enabled, but I don't get anything because (I guess) there are no errors produced?

**Comment by mi-hol** [comment]
very similar to #686

**Comment by tooomm** [comment]
> very similar to ~~#686~~ #225

**Comment by mi-hol** [comment]
@votdev from my view the 2 issues show usability gaps & issues clearly .
Would setting a log "topic" and adding a button wit link to a filter in log screen be a feasible solution?

**Comment by votdev** [comment]
> @votdev from my view the 2 issues show usability gaps & issues clearly .
> Would setting a log "topic" and adding a button with link to a matching filter in log screen be a feasible solution?

Does not work in OMV5 because it has no router, but may work in OMV6.

**Comment by mi-hol** [comment]
would router solve #793 too?

**Comment by votdev** [comment]
> would "router" address #793 too?
> BTW: "router" is a very generic term leading to misunderstandings, maybe there is a better term & description that could be used?

No.

> Does not work in OMV5 because it has no router, but may work in OMV6.

ExtJS does not provide routes, everything happens under the same URL. OMV6 is based on Angular which supports different urls per every page.

**Comment by votdev** [comment]
By the way, the USB backup plugin uses rsync to perform the backup. Because of that everything should be visible when selecting 'Rsync - Jobs' in the log page.
