### ISSUE TITLE
Network Manager Weird Problem on RasPI 3B+ (or SBCs in general)

### ISSUE THREAD

**Issue by Nio9345** [openmediavault/openmediavault#688]
So I had the following problem, after the initial setup I changed my ip on eth0 from DHCP to static, did some updates and restarted. After that I had no connection and I had to use an HDMI connection in order to see what's going on and I found the following:
1) The interface was forced to DOWN according to "ip a"
2) The interface name changed from "eth0" to "enxb827ebde65d4"
3) I had to run omv-firstaid as sudo (when instructions I found said that sudo wasn't required) to change from static to dhcp and then the interface came up.
So, I don't know if I did something wrong or there is a bug, but I felt the need to point it out.

**Comment by ryecoaaron** [comment]
OMV doesn't use network manager.  If your system is, you must have set it up that way (using a desktop environment??)
You must have changed something like a udev rule for it to change the interface name.
Instructions probably mention that you are to run the commands as root and in that case, sudo would not be needed.

**Comment by votdev** [comment]
> The interface name changed from "eth0" to "enxb827ebde65d4"

`enxb827ebde65d4` is the normal way of naming interfaces nowadays. It's called predictable names and is supported by Debian since  8 or 9.

**Comment by Nio9345** [comment]
> 
> 
> OMV doesn't use network manager. If your system is, you must have set it up that way (using a desktop environment??)
> You must have changed something like a udev rule for it to change the interface name.
> Instructions probably mention that you are to run the commands as root and in that case, sudo would not be needed.

Yes I used the GUI but, I didn't touch anything except admin password and eth0 from DHCP to static did an update and reboot. So I don't know if that changed something by itself but I'm sure I didn't.

**Comment by Nio9345** [comment]
> 
> 
> > The interface name changed from "eth0" to "enxb827ebde65d4"
> 
> `enxb827ebde65d4` is the normal way of naming interfaces nowadays. It's called predictable names and is supported by Debian since 8 or 9.

Ok, good to know, but why OMV changed the name (in the gui) from eth0 to this ?

**Comment by chiva** [comment]
I've just checked and Raspbian Buster uses old style naming "eth0"
Even OMV's installation script for Raspberry uses "eth0" to refer to the wired interface

It seems after installing networkd it switches into predictable interface naming when rebooting.
