### ISSUE TITLE
Releases section is empty

### ISSUE THREAD

**Issue by Neustradamus** [openmediavault/openmediavault#691]
Can you add releases in the Releases section?
- https://github.com/openmediavault/openmediavault/releases

**Comment by ryecoaaron** [comment]
Everything released is here - https://github.com/openmediavault/packages and more specifically - https://github.com/openmediavault/packages/tree/master/pool/main/o/openmediavault

Are you looking for a changelog?

**Comment by votdev** [comment]
OMV has a Debian package repository at https://packages.openmediavault.com.

**Comment by votdev** [comment]
Alternatively you can find the package repository at https://github.com/openmediavault/packages.
