### ISSUE TITLE
Bad request errors on notification settings

### ISSUE THREAD

**Issue by fumantsu** [openmediavault/openmediavault#692]
### Description of issue/question
Bad request on notification settings in various steps. Fresh installation from official ISO. fully updated.

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

 Just getting to the page of notification a bad request is happening:

`{"response":null,"error":{"code":0,"message":": The value [] is not an object.","trace":"OMV\\Json\\SchemaValidationException: : The value [] is not an object. in \/usr\/share\/php\/openmediavault\/json\/schema.inc:391\nStack trace:\n#0 \/usr\/share\/php\/openmediavault\/json\/schema.inc(285): OMV\\Json\\Schema->validateObject(Array, Array, '')\n#1 \/usr\/share\/php\/openmediavault\/json\/schema.inc(257): OMV\\Json\\Schema->validateType(Array, Array, '')\n#2 \/usr\/share\/php\/openmediavault\/rpc\/paramsvalidator.inc(59): OMV\\Json\\Schema->validate(Array)\n#3 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(179): OMV\\Rpc\\ParamsValidator->validate('[]')\n#4 \/usr\/share\/openmediavault\/engined\/rpc\/notification.inc(149): OMV\\Rpc\\ServiceAbstract->validateMethodParams(Array, 'rpc.common.obje...')\n#5 [internal function]: Engined\\Rpc\\Notification->get(Array, Array)\n#6 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(123): call_user_func_array(Array, Array)\n#7 \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod('get', Array, Array)\n#8 \/usr\/sbin\/omv-engined(537): OMV\\Rpc\\Rpc::call('Notification', 'get', Array, Array, 1)\n#9 {main}"}}`

After I fill server/port/sender/primary email I'm getting this bad request:

`{"response":null,"error":{"code":0,"message":"tls: The value false is not a string.","trace":"OMV\\Json\\SchemaValidationException: tls: The value false is not a string. in \/usr\/share\/php\/openmediavault\/json\/schema.inc:366\nStack trace:\n#0 \/usr\/share\/php\/openmediavault\/json\/schema.inc(297): OMV\\Json\\Schema->validateString(false, Array, 'tls')\n#1 \/usr\/share\/php\/openmediavault\/json\/schema.inc(627): OMV\\Json\\Schema->validateType(false, Array, 'tls')\n#2 \/usr\/share\/php\/openmediavault\/json\/schema.inc(395): OMV\\Json\\Schema->checkProperties(Object(stdClass), Array, '')\n#3 \/usr\/share\/php\/openmediavault\/json\/schema.inc(285): OMV\\Json\\Schema->validateObject(Object(stdClass), Array, '')\n#4 \/usr\/share\/php\/openmediavault\/json\/schema.inc(257): OMV\\Json\\Schema->validateType(Object(stdClass), Array, '')\n#5 \/usr\/share\/php\/openmediavault\/rpc\/paramsvalidator.inc(59): OMV\\Json\\Schema->validate(Object(stdClass))\n#6 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(179): OMV\\Rpc\\ParamsValidator->validate('{\"enable\":true,...')\n#7 \/usr\/share\/openmediavault\/engined\/rpc\/notification.inc(271): OMV\\Rpc\\ServiceAbstract->validateMethodParams(Array, 'rpc.emailnotifi...')\n#8 [internal function]: Engined\\Rpc\\OMVRpcServiceEmailNotification->set(Array, Array)\n#9 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(123): call_user_func_array(Array, Array)\n#10 \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod('set', Array, Array)\n#11 \/usr\/sbin\/omv-engined(537): OMV\\Rpc\\Rpc::call('EmailNotificati...', 'set', Array, Array, 1)\n#12 {main}"}}`

### Versions report
5.4.2-1

**Comment by votdev** [comment]
Clearing your browser cache should solve this. It seems your browser caches the UI Javascipt code from an older OMV version.
