### ISSUE TITLE
802.3ad bond not fully configured from the Web UI

### ISSUE THREAD

**Issue by kgkolev** [openmediavault/openmediavault#693]
### Description of issue/question
`/etc/systemd/network/10-openmediavault-bond0.network` was generated with following content:
```ini
[Network]
VLAN=bond0.100
```
I had to specify links & Name manually to enforce proper discovery, otherwise I was getting "MII Status: down" & "bond bond0 has no active aggregator" in /proc/net/bonding/bond0
```ini
[Match]
Name=bond0

[Network]
VLAN=bond0.100
BindCarrier=eno1 eno2 eno3 eno4
```
I also manually specified "TransmitHashPolicy=layer2+3" in .netdev (not sure if that was required also):
```ini
[NetDev]
Name=bond0
Kind=bond

[Bond]
Mode=802.3ad
LACPTransmitRate=fast
TransmitHashPolicy=layer2+3
PrimaryReselectPolicy=always
MIIMonitorSec=0.1s
UpDelaySec=0.2s
DownDelaySec=0.2s
```

### Steps to reproduce issue
1. Configure bond from UI and select all four adapters.
2. Add a VLAN on top of the bond in DHCP mode
3. Apply the above two changes
4. Reboot system

### Versions report
OMV 5.3.9-1

**Comment by votdev** [comment]
Please try the latest version 5.4.2 which now uses netplan.io to deploy the network configuration.

**Comment by votdev** [comment]
Closed because OMV does not deploy systemd-networkd manually anymore.
