### ISSUE TITLE
error on creation of SharedFolder from a readOnly Remote Mount (CIFS)

### ISSUE THREAD

**Issue by wreggyl** [openmediavault/openmediavault#694]
### Description
i mounted a CIFS (SMB 3.0) share with the RemoteMount plugin with a readOnly user account on that share. The mount is visible and working. But if i want to create a shared folder from this mount point (e.g.: needed for rsync) i get the following errors:

`Error #0:
OMV\Exception: Failed to create the directory '/srv/<cifs_mount_with_readonly_user>/<share_name>/':  in /usr/share/openmediavault/engined/rpc/sharemgmt.inc:325
Stack trace:
#0 [internal function]: Engined\Rpc\ShareMgmt->set(Array, Array)
#1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#2 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('set', Array, Array)
#3 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('ShareMgmt', 'set', Array, Array, 1)
#4 {main}`

### Steps to reproduce issue

- mount a CIFS share with a user which only has read access (share source in my example is a synology)

- create a shared folder - select the remote mount and try to create it and you get the error
- grant the used user account write access on the source shared folder and repeat and it is working correctly

It looks like the OMV shared folder itself will be generated in the mounted shared folder, due to readonly this will not work. And adding an absolute path on the "add shared folder" UI is not working, everytime it takes the input as relative to the source mount

### Versions report
5.4.2-1(Usul)

Thx in advance

**Comment by ryecoaaron** [comment]
When you create a new sharedfolder, it tries to create the directory and set permissions. Obviously, it can’t do this on a read only share. So, no way to fix this.

**Comment by wreggyl** [comment]
> When you create a new sharedfolder, it tries to create the directory and set permissions. Obviously, it can’t do this on a read only share. So, no way to fix this.

So what is the right way of mount a shared folder from another system and reshare via OMV? It is working if you mount it with write access, but this is not an solution. But i think the usecase of what i want to do is valid - I do not want to grant OMV write access to my other NAS - just read access. And even this would not be a problem, but rsync and all of the plugins like BorgBackup are only working on shared folders and not on the mounts.

**Comment by ryecoaaron** [comment]
This is how OMV is designed. The plugin can’t change that. You could make the remote share read write and the sharedfolder you create on it read only.

If you could put borg on the original server, you wouldn’t need to worry about the remote mount.

**Comment by wreggyl** [comment]
> This is how OMV is designed. The plugin can’t change that. You could make the remote share read write and the sharedfolder you create on it read only.
> 
> If you could put borg on the original server, you wouldn’t need to worry about the remote mount.

If i put borgbackup on original NAS, no need for having OMV running ;-) But this is not the question. If there is no option, i think my workaround will work, but maybe there is an option improvement

**Comment by wreggyl** [comment]
@synaomen: what should the thump down emoji tell me? Workaround not good, no place for improvement, or i do stupid things?

**Comment by ryecoaaron** [comment]
I understand borgbackup wasn't the question but it was a alternative suggestion.  In order for this to be implemented, a read only checkbox would have to be added and the sharedfolder path would already have to exist.  The backend would skip creating the folder and set permissions.  The problem is that every plugin that uses sharedfolders would possibly have to be updated to never try to write if it was read only.  This would be a huge undertaking.  Obviously the original NAS has readwrite share.  Why does the share have to be read only between NASes?  What is the danger in having that link be read write if anything re-shared was read only.

**Comment by wreggyl** [comment]
what i want to do is a backup from the original NAS - in my opinion for doing this a readOnly access should be sufficient. there is no real danger in my thought, but the original NAS part i want to backup is limited writeable for specific people, but readable by all of them. For now having a backup of this, there was no need for me to make changes on the original NAS
