### ISSUE TITLE
dot in path for rsync module

### ISSUE THREAD

**Issue by patatetom** [openmediavault/openmediavault#695]
### Description of issue/question

rsync `--backup-dir=...` option is not working as excepted if dot is in `path` for module.
I push my data to `rsync://omv/module/client/lastest/` target with `--delete` and `--backup --backup-dir=../$( date +%Y.%m.%d )/` and
- I've a desired structure with the manualy removed dot in `/etc/rsyncd.conf` :
```
client/
├── 2020.05.01/
├── 2020.05.02/
└── lastest/
```
- I've a bad structure with the defined `path` :
```
client/
└── lastest\
    ├── 2020.05.01\
    └── 2020.05.02\
```
**is this intended ?**

### Steps to reproduce issue

turn on `rsync` server and add a new module `test`.
now have a look with ssh in `/etc/rsyncd.conf` : `path` variable include a dot between device shared and folder shared.
like me, try to push some data with and without this dot...

### Versions report

5.2.4-1

**Comment by votdev** [comment]
I think you should check the manual page of rsync. OMV only uses the entered configuration to build the rsync config scripts/files.

**Comment by votdev** [comment]
Please check the manual page of rsync how it behaves with dots in paths.

**Comment by votdev** [comment]
This issue will be closed because OMV is not responsible for the behavior of rsyncd combined with options that are added via `Extra options`.

**Comment by patatetom** [comment]
thank you for the clarification and sorry for the inconvenience.
indeed the presence of the `dot-dir` in the module's `path` is an additional security.

in this case, is it possible to obtain the same organization as the one desired ?
```
client/
├── 2020.05.01/
├── 2020.05.02/
└── lastest/
```
