### ISSUE TITLE
Install on debain 9 "The following packages have unmet dependencies:"

### ISSUE THREAD

**Issue by X3rl34** [openmediavault/openmediavault#696]
Following the install guide on https://openmediavault.readthedocs.io/en/5.x/installation/on_debian.html

after this command

`apt-get --yes --auto-remove --show-upgraded \
    --allow-downgrades --allow-change-held-packages \
    --no-install-recommends \
    --option Dpkg::Options::="--force-confdef" \
    --option DPkg::Options::="--force-confold" \
    install openmediavault-keyring openmediavault`

I get the following

`Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openmediavault : Depends: php-pam but it is not going to be installed
                  Depends: netplan.io but it is not installable
                  Depends: monit but it is not going to be installed
                  Depends: salt-minion but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

**Comment by ryecoaaron** [comment]
You can't install OMV 5 on Debian 9.  OMV 5 requires Debian 10.

**Comment by X3rl34** [comment]
How can't belive that what a dick I am! I didn't even think that. Thanks ryecoaaron.

**Comment by jagoosw** [comment]
I am having this issue on Debian 10

**Comment by ryecoaaron** [comment]
@jagoosw please follow this guide which uses the isntall script - https://forum.openmediavault.org/index.php?thread/28789-installing-omv5-on-raspberry-pi-s-armbian-sbc-s-i386-32-bit-platforms/.  If you still have the problem, you are probably missing debian repos in /etc/apt/sources.list.  Posting on the forum will get you better help because more people will see it.

**Comment by jagoosw** [comment]
I tried with the installer originally and got the same error but have possibly overcome it now with aptitude (still running but past that point I believe). Thanks for your help

**Comment by ryecoaaron** [comment]
I would love to see output where the install script isn't working.  aptitude doesn't do anything that apt-get can't.
