### ISSUE TITLE
Unable to load web UI by domain name w/ TLS/SSL enabled

### ISSUE THREAD

**Issue by theogravity** [openmediavault/openmediavault#697]
### Description of issue/question

- When I installed OMV, I used a hostname of `nas.home`

![image](https://user-images.githubusercontent.com/855434/81023690-03179500-8e26-11ea-8427-d8839f605c4f.png)

- Enabled SSL/TLS w/ Force SSL/TLS
- Using a valid SSL/TLS certificate for `nas.home` (no validation issues when visiting either the IP or domain name, has proper CN and SAN)
- The domain name has a proper A record to the server IP

- When I visit the OMV using `https://<server IP>`, the GUI loads appropriately
- When I visit OMV using the domain name (in my case it is https://nas.home), I get a "requested page not found"

![image](https://user-images.githubusercontent.com/855434/81023482-68b75180-8e25-11ea-9e1c-7b021c9a9b12.png)

![image](https://user-images.githubusercontent.com/855434/81023812-70c3c100-8e26-11ea-9fb9-7df4d71614fd.png)

- Disabling force SSL / TLS does not resolve this.

This is probably an `nginx` related issue, but unsure how to fix this. Doing the following does not fix this in the generated `/etc/nginx/sites-enabled/openmediavault-webgui` file after doing a restart on `nginx`:

```
server_name openmediavault-webgui nas.home
```

### Versions report

- Version 5.4.2-1 of OMV

![image](https://user-images.githubusercontent.com/855434/81023706-1460a180-8e26-11ea-8032-6715015707e3.png)

**Comment by votdev** [comment]
Can not reproduce this issue. What makes me wonder is the redirect.html url. OMV does not have such a file. To me it looks like that an additional software causes the problem.

**Comment by theogravity** [comment]
it's a bare-bones install using the OMV iso, with latest updates, the OMV extras and the ZFS plugin (no custom kernel installed).

Given that you said `redirect.html` doesn't exist, I can use that info to poke a bit more. Thanks.

**Comment by theogravity** [comment]
Hm, it mysteriously works now.

I was using `ag` to find references to `redirect.html` and found only entries in the access/error log, but nothing specific to code. 

Thanks for responding.
