### ISSUE TITLE
Install script on Raspberry Pi 4 broke network interfaces

### ISSUE THREAD

**Issue by Stephen988** [openmediavault/openmediavault#698]
After installing script on Raspberry Pi 4, the installation broke wlan0 and eth0 on my raspberry without success to restore it.
Before open omv webgui I have digits on terminal this commands:
sudo rm /etc/systemd/network/99-default.link
sudo netplan apply
sudo omv-salt deploy run systemd-networkd
and in network setting on OMV when I create manual interface (there is nothing on it first access) after saving setting there is a infinite charging and then interface dead.

**Comment by ryecoaaron** [comment]
This should be here - https://github.com/OpenMediaVault-Plugin-Developers/installScript/issues

But, those instructions are old.  The script and OMV itself have been updated to do those things.  The script will break wlan0 because the install script should be run before setting up networking.  Otherwise, you will need to run omv-firstaid AFTER running the install script.

**Comment by Stephen988** [comment]
> This should be here - https://github.com/OpenMediaVault-Plugin-Developers/installScript/issues
> 
> But, those instructions are old. The script and OMV itself have been updated to do those things. The script will break wlan0 because the install script should be run before setting up networking. Otherwise, you will need to run omv-firstaid AFTER running the install script.

No, I have do it some minutes ago, and after install script: wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash

my wlan0 and eth0 are dead.
in network setting in omv there is nothing and when I try to create it I got errors.
instead in omv-firstaid enabling interface get stuck in please wait when confirm.
raspbian installation is fresh make some minute before omv.

**Comment by ryecoaaron** [comment]
I tested it yesterday (or the day before) 3 times on just an RPi4 (also rpi3,odroid-n2,rock64).  Are you sure you didn't get a new IP address (which is expected)?  And the script doesn't add database entries (yet, I'm testing that).  So, when you go to the network tab, there shouldn't be anything in there unless you ran omv-firstaid.

**Comment by ryecoaaron** [comment]
And just to reiterate, wlan0 will be dead after the script is run.

**Comment by Stephen988** [comment]
> I tested it yesterday (or the day before) 3 times on just an RPi4 (also rpi3,odroid-n2,rock64). Are you sure you didn't get a new IP address (which is expected)? And the script doesn't add database entries (yet, I'm testing that). So, when you go to the network tab, there shouldn't be anything in there unless you ran omv-firstaid.

Ok I want repeat again, what is the correct procedure step by step?:
1- install raspbian (and in my case I set install on ssd and work perfectly before omv)
2- install omv script
3- after finish open webgui
then?

**Comment by ryecoaaron** [comment]
That is the correct procedure other than moving to an SSD.  And if you need wireless, you have to run omv-firstaid.  I have never tested moving to SSD since I don't think that is necessary.

**Comment by Stephen988** [comment]
> That is the correct procedure other than moving to an SSD. And if you need wireless, you have to run omv-firstaid. I have never tested moving to SSD since I don't think that is necessary.

I can confirm the on my other raspi in the past weeks all works perfectly on ssd with this fix:sudo rm /etc/systemd/network/99-default.link
sudo netplan apply
sudo omv-salt deploy run systemd-networkd
but you tell me is no more ncessary.
So you suggest my proceed before on microsd, after install I do nothing, only reboot? no manual connection or other? I need only eth0, but would be great also not broke wifi

**Comment by ryecoaaron** [comment]
After you open the webgui, you don't have to do anything other than configure OMV to your liking.  If you *want* the network to show in the network tab, you can add it but it isn't required.

**Comment by ryecoaaron** [comment]
> I can confirm the on my other raspi in the past weeks all works perfectly on ssd with this fix:sudo rm /etc/systemd/network/99-default.link
sudo netplan apply
sudo omv-salt deploy run systemd-networkd

The install script and OMV as of 5.4.2 are doing these steps.  You should not have to do those.

After you install OMV, yes, reboot.  After that, I don't know what you are asking.  You should have a working OMV install.

If you want wifi, run omv-firstaid after running the script.  I will not add wifi stuff to the script.

If the regular script isn't working, try the test script - change install to install.test in the url.

**Comment by Stephen988** [comment]
ok can I confirm that install omv on raspberry using an ssd broke all network interfaces, I don't understand why, because after a fresh install of raspbian and moving filesystem all works well.
I have tried only with microsd and in fact omv work.
there is a solution?

**Comment by Stephen988** [comment]
> > I can confirm the on my other raspi in the past weeks all works perfectly on ssd with this fix:sudo rm /etc/systemd/network/99-default.link
> > sudo netplan apply
> > sudo omv-salt deploy run systemd-networkd
> 
> The install script and OMV as of 5.4.2 are doing these steps. You should not have to do those.
> 
> After you install OMV, yes, reboot. After that, I don't know what you are asking. You should have a working OMV install.
> 
> If you want wifi, run omv-firstaid after running the script. I will not add wifi stuff to the script.
> 
> If the regular script isn't working, try the test script - change install to install.test in the url.

Hi @ryecoaaron I have done another try, installed raspbian, then omv and after moving microsd on ssd, now eth0 work but open raspy ip on browser not open omv webgui, at startup I see 3 errors about:
failed to start a high performance web server and a reverse proxy server nginx and similar error but reference to LSB, what I can do?

**Comment by ryecoaaron** [comment]
I have no idea how you are moving it to ssd (still don't know why you are doing that) but post your method on the forum for more help on that.

**Comment by Stephen988** [comment]
> I have no idea how you are moving it to ssd (still don't know why you are doing that) but post your method on the forum for more help on that.

for two reason:
1- need to run several container on docker
2- microsd have a very poor I/O performance (and is more probably suddenly dead)

**Comment by ryecoaaron** [comment]
1 - Run the containers on the data drive.  That is why omv-extras allows you to move the docker location.
2 - I/O performance of the SD card only slightly affects the web interface.  It will not affect NAS functions that use the data drives.  If you have the flash memory plugin installed, the most heavily written directories are running from ram which will negate the I/O performance problem and make the card last MUCH longer.  One of my NASes has been running for over four years on a card.

**Comment by Stephen988** [comment]
> 1 - Run the containers on the data drive (use the ssd as the data drive). That is why omv-extras allows you to move the docker location.
> 2 - I/O performance of the SD card only slightly affects the web interface. It will not affect NAS functions that use the data drives. If you have the flash memory plugin installed, the most heavily written directories are running from ram which will negate the I/O performance problem and make the card last MUCH longer. One of my NASes has been running for over four years on a card.

change microsd and repeat, finally work all.
thanks for patience

**Comment by neuronflow** [comment]
after running
```
wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash
```
my Pi 4 is not reachable. It does not even get an IP from the router anymore neither via LAN nor W-LAN.

**Comment by ryecoaaron** [comment]
@neuronflow please don't post the same thing in two places.  As I mentioned in your other issue, you need to post on the forum.

**Comment by neuronflow** [comment]
thanks, sorry I found the other repo after posting here.

**Comment by NoahYau** [comment]
> after running
> 
> ```
> wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash
> ```
> 
> my Pi 4 is not reachable. It does not even get an IP from the router anymore neither via LAN nor W-LAN.

Excuse me, do you know where is the another repo after you posting here?

**Comment by ryecoaaron** [comment]
@NoahYau  Repo for what?  You are posting on a closed ticket.
