### ISSUE TITLE
error creating docker network on omv 5.0

### ISSUE THREAD

**Issue by Peppa123** [openmediavault/openmediavault#699]
I have set up omv 5.4.2 on my two odroid n2 with the following fresh installation:

- flashed sd-card with armbian image (Armbian_20.02.5_Odroidn2_buster_legacy_4.9.216)
- installed armbian including basic config (user, time, keyboard)
- setup omv 5 with armbian-config / software / softy / omv
- wait and reboot os
- basic configuration omv and installed docker / portainer using omv webinterface
- changed docker folder from sd card to separate path on usb disc

When I try to add a new user network in bridged mode I get the following error:

docker network create --driver=bridge --subnet=192.168.151.0/24 --gateway=192.168.151.1 home

Error response from daemon: Failed to program FILTER chain: iptables failed: iptables --wait -I FORWARD -o br-7a5194cdef64 -j DOCKER: iptables v1.8.2 (nf_tables): RULE_INSERT failed (Invalid argument): rule in chain FORWARD

(exit status 4) 

The error occurs on both odroid n2 and I don't find anything googling this error.

**Comment by ryecoaaron** [comment]
This isn't an OMV issue but have you tried changing iptables to iptables-legacy instead of iptables-nft?  There are threads about this on the forum.

**Comment by Peppa123** [comment]
Ok do you have a hint how to change iptables? I will search the forum again.

**Comment by ryecoaaron** [comment]
https://wiki.debian.org/iptables

**Comment by Peppa123** [comment]
Someone wrote about "/etc/systemd/system/openmediavault-firewall.service". I do not find this service on my installation. Was there a change in service installation?

**Comment by ryecoaaron** [comment]
It is on my system:

**Comment by Peppa123** [comment]
I have no files regarding openmediavault:

drwxr-xr-x  2 root root 4096 May  1 12:25 basic.target.wants
lrwxrwxrwx  1 root root   34 May  1 12:27 chronyd.service -> /lib/systemd/system/chrony.service
drwxr-xr-x  2 root root 4096 May  1 12:20 collectd.service.d
lrwxrwxrwx  1 root root   42 Mar  9 20:18 dbus-fi.w1.wpa_supplicant1.service -> /lib/systemd/system/wpa_supplicant.service
lrwxrwxrwx  1 root root   40 May  1 12:11 dbus-org.freedesktop.Avahi.service -> /lib/systemd/system/avahi-daemon.service
lrwxrwxrwx  1 root root   44 May  1 12:20 dbus-org.freedesktop.network1.service -> /lib/systemd/system/systemd-networkd.service
lrwxrwxrwx  1 root root   44 May  1 12:20 dbus-org.freedesktop.resolve1.service -> /lib/systemd/system/systemd-resolved.service
lrwxrwxrwx  1 root root   45 Mar  9 20:03 dbus-org.freedesktop.timesync1.service -> /lib/systemd/system/systemd-timesyncd.service
drwxr-xr-x  2 root root 4096 May  1 12:19 default.target.wants
drwxr-xr-x  2 root root 4096 May  1 12:21 getty.target.wants
drwxr-xr-x  2 root root 4096 May  1 12:25 halt.target.wants
drwxr-xr-x  2 root root 4096 May  3 19:47 multi-user.target.wants
drwxr-xr-x  2 root root 4096 May  1 12:28 network-online.target.wants
drwxr-xr-x  2 root root 4096 May  2 09:32 nfs-server.service.wants
drwxr-xr-x  2 root root 4096 May  1 12:21 poweroff.target.wants
drwxr-xr-x  2 root root 4096 May  1 12:25 reboot.target.wants
drwxr-xr-x  2 root root 4096 May  1 12:20 remote-fs.target.wants
lrwxrwxrwx  1 root root    9 May  1 12:20 samba-ad-dc.service -> /dev/null
drwxr-xr-x  2 root root 4096 May  1 12:25 shutdown.target.wants
drwxr-xr-x  2 root root 4096 May  3 20:48 sockets.target.wants
lrwxrwxrwx  1 root root   31 Mar  9 20:21 sshd.service -> /lib/systemd/system/ssh.service
drwxr-xr-x  2 root root 4096 May  1 12:24 sysinit.target.wants
lrwxrwxrwx  1 root root   35 Mar  9 20:10 syslog.service -> /lib/systemd/system/rsyslog.service
drwxr-xr-x  2 root root 4096 May  1 12:21 timers.target.wants
-rw-r--r--  1 root root  289 May  1 12:22 tmp.mount

**Comment by ryecoaaron** [comment]
OMV creates it.  omv-salt deploy run iptables

Please post on the forum so more people can help with this issue.

**Comment by Peppa123** [comment]
ok one first success, after changing iptables behaviour to legacy docker network is working. I will ask in the forum if there is something wrong or missing for omv iptables deployment.

**Comment by ryecoaaron** [comment]
Yep, docker doesn't support iptables-nft yet.

**Comment by Peppa123** [comment]
ok I will close case.
