### ISSUE TITLE
WebUI - 504 Gateway Time-out

### ISSUE THREAD

**Issue by meequz** [openmediavault/openmediavault#70]
I have just burned `OMV_3_0_99_RaspberryPi_2_3_4.9.80.img.xz` with `etcher-1.3.1-x86_64.AppImage` on MicroSD card. Insert the card in my RPi 3 and power it on, connected to a local network with Ethernet cable. Then go to it's IP address from my laptop ASUS G550JK with Linux Mint 18.3 MATE x64 and webbrowser Firefox 59.0.1 (64-bit). Login screen appears. After entering default credentials I got this:

![untitled](https://user-images.githubusercontent.com/2832374/37872950-c912d59c-301a-11e8-8ff8-96b6474310c8.png)

Addons enabled in the browser are 'Adblock Plus' and 'Tree Style Tab'.
I got the error after pressing CTRL+F5 too, every time.

**Comment by ryecoaaron** [comment]
This isn’t a problem with OMV.  It is either a problem with the RPi image or you didn’t wait for the first boot changes to finish (needs network and can take half an hour or more). Please post in the forum about this.

**Comment by meequz** [comment]
Then I have 2 questions

1. RPi image is prepared not by OMV team and such issues should be reported to another bug tracker?

>you didn’t wait for the first boot changes to finish
2. Shouldn't WebUI tell me that, so I know I should wait?

**Comment by ryecoaaron** [comment]
1 - There isn't really a bug tracker for the RPi image.  The forum is the best option.

2 - It can't since the OS is still being setup and update.  The instructions tell you this where you downloaded the image.
