### ISSUE TITLE
Netplan Bond WOL problem

### ISSUE THREAD

**Issue by nrandon** [openmediavault/openmediavault#701]
## Description of issue/question
If WOL is selected for a bonded network an invalid WOL entry is added to the bond rather than the individual interfaces. This results in netplan apply falling as follows in salt:

----------
          ID: apply_netplan_config
    Function: cmd.run
        Name: netplan apply
      Result: False
     Comment: Command "netplan apply" run
     Started: 21:02:53.230190
    Duration: 69.78 ms
     Changes:
              ----------
              pid:
                  27157
              retcode:
                  78
              stderr:
                  /etc/netplan/40-openmediavault-bond0.yaml:22:7: Error in network definition: unknown key 'wakeonlan'
                        wakeonlan: true
                        ^
              stdout:

Summary for bcroftmediavault.local

The fix is sight forward in salt bond.j2 move line 60-62 to 11-13 (move the wol to the interfaces)

### Steps to reproduce issue
Set WOL and a bonded network interface

### Versions report
latest

**Comment by votdev** [comment]
Thx for the hint.
