### ISSUE TITLE
ClamAV missing main.cvd but db is up-to-date

### ISSUE THREAD

**Issue by Max-Sum** [openmediavault/openmediavault#702]
### Description of issue/question
Same as #646. (Installing Clamav and starting service fails with "Specified path /var/lib/clamav/main.cvd does not exist")
I check the clamav-freshclam log. It tells me I have up-to-date database.
If the update is not started, there wouldn't be any .cvd file so the process stucked.
```
5月 09 16:32:47 omv systemd[1]: Started ClamAV virus database updater.
5月 09 16:32:47 omv freshclam[56045]: Sat May  9 16:32:47 2020 -> ClamAV update process started at Sat May  9 16:32:47 2020
5月 09 16:32:47 omv freshclam[56045]: Sat May  9 16:32:47 2020 -> daily.cld database is up to date (version: 25806, sigs: 2373675, f-level: 63, builder: raynman)
5月 09 16:32:47 omv freshclam[56045]: Sat May  9 16:32:47 2020 -> main.cld database is up to date (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
5月 09 16:32:47 omv freshclam[56045]: Sat May  9 16:32:47 2020 -> bytecode.cld database is up to date (version: 331, sigs: 94, f-level: 63, builder: anvilleg)
```
### Steps to reproduce issue
See #646 

### Versions report
OMV 5.4.3

**Comment by votdev** [comment]
What is the output of `/var/lib/clamav`?

**Comment by Max-Sum** [comment]
> 
> 
> What is the output of `/var/lib/clamav`?

You mean the content? 
```
# ls /var/lib/clamav
bytecode.cld  daily.cld  main.cld  mirrors.dat
```

**Comment by votdev** [comment]
You can get it working with `rm /var/lib/clamav/main.cld`and `omv-salt deploy run clamav`. I didn't find a documentation what's the difference between `main.cvd` and `main.cld` is.

**Comment by Max-Sum** [comment]
> 
> 
> You can get it working with `rm /var/lib/clamav/main.cld`and `omv-salt deploy run clamav`. I didn't find a documentation what's the difference between `main.cvd` and `main.cld` is.

I have got around by `touch main.cvd`. It seems that `cld` stands for ClamAV Local Database.
[https://linux.die.net/man/5/freshclam.conf](https://linux.die.net/man/5/freshclam.conf)
