### ISSUE TITLE
Usage of webgui_title env variable leaves salt in broken state

### ISSUE THREAD

**Issue by subzero79** [openmediavault/openmediavault#703]
### Description of issue/question
Placed this in `/etc/default/openmediavault'

`OMV_WEBGUI_TITLE="omv - {{fqdn}}"`

to change the tab title

Ran `omv-salt stage run prepare`

```
elqui.kst:
----------
          ID: sync_runners
    Function: salt.runner
        Name: saltutil.sync_runners
      Result: True
     Comment: Runner function 'saltutil.sync_runners' executed.
     Started: 11:25:18.984265
    Duration: 3320.85 ms
     Changes:   
              ----------
              return:
----------
          ID: sync_modules
    Function: salt.runner
        Name: saltutil.sync_modules
      Result: True
     Comment: Runner function 'saltutil.sync_modules' executed.
     Started: 11:25:22.305325
    Duration: 3235.628 ms
     Changes:   
              ----------
              return:
----------
          ID: populate_pillar
    Function: salt.runner
        Name: omv.populate_pillar
      Result: True
     Comment: Runner function 'omv.populate_pillar' executed.
     Started: 11:25:25.541238
    Duration: 3635.322 ms
     Changes:   
              ----------
              return:
                  True
----------
          ID: run_state_sync
    Function: salt.state
      Result: False
     Comment: Run failed on minions: elqui.kst.raktor.zone
     Started: 11:25:29.176873
    Duration: 100.856 ms
     Changes:   
              elqui.kst:
                  Data failed to compile:
              ----------
                  Pillar failed to render with the following messages:
              ----------
                  Rendering SLS 'omv' failed. Please see master log for details.

Summary for elqui.kst
------------
Succeeded: 3 (changed=3)
Failed:    1
------------
Total states run:     4
Total run time:  10.293 s
```

After this any changes in the webgui fail. To revert back i have to delete lines that of OMV_WEBGUI_TITLE from /srv/pillar/omv/default.sls to make it work again

Looks like salt is trying to parse the double curly braces maybe?

A question does the php backend reads the files from /etc/default/openmediavault or from /srv/pillar/omv/defaults.sls?

Just for general knowledge does every env variable change or add now requires a salt stage prepare and deploy? 

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

### Versions report
5.4.5-1

**Comment by Wikinaut** [comment]
@votdev Hi Volker, is my today's problem https://forum.openmediavault.org/index.php?thread/32544-omv5-regression-in-5-4-5-1-shared-folder-cannot-be-removed-anymore-omv-fails-to/#post239031 perhaps related?

**Comment by votdev** [comment]
> @votdev Hi Volker, is my today's problem [forum.openmediavault.org/index.php?thread/32544-omv5-regression-in-5-4-5-1-shared-folder-cannot-be-removed-anymore-omv-fails-to/#post239031](https://forum.openmediavault.org/index.php?thread/32544-omv5-regression-in-5-4-5-1-shared-folder-cannot-be-removed-anymore-omv-fails-to/#post239031) perhaps related?

I don't see a error message that helps to identify the issue. So maybe yes or no.

**Comment by Wikinaut** [comment]
@votdev I filed my - may be different issue - as https://github.com/openmediavault/openmediavault/issues/704
