### ISSUE TITLE
[OMV5 regression?] After restart and decrypting, a formerly mounted LUKS drive is often not mounted

### ISSUE THREAD

**Issue by Wikinaut** [openmediavault/openmediavault#706]
* OMV Release: 5.4.6-1
* 5.4.34-1-pve

![grafik](https://user-images.githubusercontent.com/1151915/81752760-78343b80-94b2-11ea-9bd2-92500082a681.png)

With OMV 5 I noticed this:
* Assume the situation when I have successfully decrypted that crypto disk and mounted that disk which, yes, has referenced folders.

#### Problem
* After a reboot ; and
* after having it again decrypted

the crypto disk is **not regularly automatically mounted** (after having decrypted that) **after a reboot** (after/when decrypting it). I noticed that the disk *was* mounted after a few reboots but on further subsequent reboots the system "forgot to mount" my decrypted disk.

With OMV 4, as far as I remember, the disk was everytime automatically mounted _as_ I decrypted the disk.

/etc/openmediavault/config.xml:

```
      <mntent>
        <uuid>48e1f210-c267-4c5e-bd19-634253dd617b</uuid>
        <fsname>/dev/disk/by-label/cryptonas10neu</fsname>
        <dir>/srv/dev-disk-by-label-cryptonas10neu</dir>
        <type>ext4</type>
        <opts>defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl,x-systemd.device-timeout=2</opts>
        <freq>0</freq>
        <passno>2</passno>
        <hidden>0</hidden>
      </mntent>
    </fstab>
```

/etc/fstab:
```
....
# >>> [openmediavault]
/dev/disk/by-label/cryptonas10neu               /srv/dev-disk-by-label-cryptonas10neu   ext4    defaults,nofail,user_xattr,noexec,usrjquota=aquota.us$
# <<< [openmediavault]
```

**Comment by votdev** [comment]
Please report the issue here https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption because this plugin is not maintained by the OMV project.

**Comment by Wikinaut** [comment]
@votdev Your point! and bingo: it has been already filed by others there as https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/issues/35
