### ISSUE TITLE
Change admin email or notifications

### ISSUE THREAD

**Issue by m3rcuriel** [openmediavault/openmediavault#707]
### Description of issue/question

Whenever I log in as admin, I get the following email to my main notification email:

> Dear admin,

> your user account was used to log in to ###########.com (#########) via a web browser.

>Date and time: Wed, 13 May 2020 14:35:59 -0700
>Remote address: ########
>User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/##### (KHTML, like Gecko) Chrome/######### Safari/#####

>If you recently logged in to the control panel, you can disregard this email. If you have not logged in recently and believe someone may have accessed your account, you should reset your password.

>Sincerely,
>your openmediavault system

Immediately followed by a domain not found issue, because of course admin@########.com is not a valid email address.

I would like to either change the admin email, which seems to default to admin@hostname or disable this notification. Happy to ssh in and change a file if necessary.

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

### Versions report
OMV version 5.3.9-1on Linux 5.4.19

**Comment by votdev** [comment]
Update to the latest version and everything should work. The issue has been fixed in 5.3.10, see https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/debian/changelog#L74.

To be absolutely sure you can run `omv-salt deploy run postfix` after the update.

**Comment by m3rcuriel** [comment]
Thank you! Sorry I didn't see that.
