### ISSUE TITLE
Failed in log in the web UI with unavailable docker 

### ISSUE THREAD

**Issue by huangwb8** [openmediavault/openmediavault#708]
### Description of issue/question
+ Failed to log in the web UI

### Steps to reproduce issue
The problems can be summarized as following:
+ Failed to log in the web UI. The web can be visited, but I cannot log in with right accounts. Meanwhile, the monitoring alerts are all stopping so that I cannot receive any automatic report from my NAS
+ Docker daemon not running. 
```
$ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
+ Successful ZFS file system. My win10 computer can access the files in NAS
+ Successful ssh visit
+ Reboot is useless

### Something important?
The last message I received from my nas:
```
The system monitoring needs your attention.

Host:        \openmediavault.local
Date:        Sun, 05 Apr 2020 10:33:42
Service:     rootfs
Event:       Resource limit matched
Description: space usage 85.7% matches resource limit [space usage > 85.0%]

This triggered the monitoring system to: alert
```
But I'm not sure the connection between it and the problems.
The bug seems to appear suddenly. No special commands or operations had been made before.

### Versions report
Linux openmediavault.local 5.3.18-2-pve #1 SMP PVE 5.3.18-2 (Sat, 15 Feb 2020 15:11:52 +0100) x86_64 GNU/Linux

**Comment by mi-hol** [comment]
@huangwb8 is the issue still open using latest versions?

**Comment by mi-hol** [comment]
closing due to no response
