### ISSUE TITLE
Upgrade change log improvement request.

### ISSUE THREAD

**Issue by donhwy** [openmediavault/openmediavault#709]
The other day there were quite a few updates available in the webui. To read the change log you need to select the package then click the change log button. To get to another you have to uncheck the first one, select the next and then hit the change log button. Repeat for all the others you want to read.

It would be nice if you could just double click the package and have the change log pop up. 

Thanks

**Comment by votdev** [comment]
I don't think it makes sense to implement this in OMV5 and miss it in OMV6 again because OMV6 does not support double-clicks in tables anymore.
