### ISSUE TITLE
Handle /var/log/ == tmpfs

### ISSUE THREAD

**Issue by smoneck** [openmediavault/openmediavault#71]
### Behavior
```
~# reboot
~# omv-initsystem
/usr/sbin/omv-initsystem: 38: /usr/sbin/omv-initsystem: cannot create /var/log/openmediavault/initsystem.log: Directory nonexistent
```
### Resolution
resolved by `mkdir -pv /var/log/openmediavault`. 

### Expected Behavior

Create dir if not existent.

### Setup

`Linux hostname 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux`
```
~# cat /etc/fstab
tmpfs /var/log tmpfs defaults,noatime,nosuid,mode=0755,size=100m 0 0
[...]
```

OMW version 4.1.2-1

**Comment by votdev** [comment]
This indicates an improperly installed openmediavault package because these dirs are created by the package, see https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/debian/openmediavault.dirs.

**Comment by smoneck** [comment]
I am not completely sure whether you got what I wanted to bring across. Yes, `var/log/openmediavault` is being installed by the package. But in the nature of a `tmpfs`, it is gone after reboot and OMV apparantly can't deal with it. Hence my suggestion: OMV creates it if gone.

**Comment by ryecoaaron** [comment]
/var/log on OMV shouldn't be on tmpfs without a few other changes.  OMV creates them once and shouldn't have to on every boot.  That is why the folder2ram package and openmediavault-flashmemory plugin were created.
https://github.com/bobafetthotmail/folder2ram
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-flashmemory
