### ISSUE TITLE
base 10 sizes

### ISSUE THREAD

**Issue by neheb** [openmediavault/openmediavault#711]
Any way to get OMV to report SI sizes? I currently have 3TB that shows up as 2.73TB. SI sizes are better.

https://randomascii.wordpress.com/2016/02/13/base-ten-for-almost-everything/

macOS and GNOME (not sure about KDE) have already switched to displaying base 10 since it makes a lot more sense than base 2.

### Versions report
OMV5

**Comment by votdev** [comment]
OMV will stay on base 2 because KiB or MiB clearly tells this the user, whereas KB or MB could be base 2 or 10.

**Comment by neheb** [comment]
I don’t agree but OK.
