### ISSUE TITLE
PHP still 7.0 after update from OMV4 to 5

### ISSUE THREAD

**Issue by jonathanmmm** [openmediavault/openmediavault#713]
Hi,

I have on my system installed php 7.0, 7.3 and 7.4
7.3 was before for other webservices.
Now that I am on Debian 10 through manual update I would like to ask, can I somehow migrate to php 7.3 or is even 7.4 supported by the webinterface? And if yes, which files have to be modified?
I would like to have 7.0 removed and maybe also 7.3 if I don't need it. Just less stuff and 7.0 also not updated anymore.

I used the Guide from TechnoDadLife to manually update, he got it from the omv forum.
Everything works, is just that I would like to switch, if supported and don't know exactly how without breaking stuff.

**Comment by ryecoaaron** [comment]
If php7.0 was still installed, you must have had something using it on OMV 4.x.  You can purge it since OMV 5.x only uses 7.3 (cannot use 7.4).

**Comment by votdev** [comment]
OMV is strictly tied to the PHP version that is shipped with the Debian release OMV is based on. So all files shipped with OMV are already using the latest PHP version it supports. So i am not clear what the intention of your question is.

**Comment by votdev** [comment]
You should be able to do a `apt-get autoremove` to uninstall unused packages. OMV5 needs PHP7.3, so all older versions can be removed from an OMV perspective. If the package management does not uninstall them, then some other packages still require PHP7.0.

**Comment by jonathanmmm** [comment]
Yes, but the socket is still listed in /etc/php/7.0/fpm/pool.d.
Can I just copy the files over to 7.3, because I couldn't find them there?

**Comment by votdev** [comment]
Please note that OMV does not support a migration from OMV4 to OMV5 officially exactly because of those things. This was clearly communicated in the blog when OMV5 was released.

To make sure OMV5 works as expected run `omv-salt stage run deploy`, after that the system should work like a new installation.

**Comment by jonathanmmm** [comment]
Ok, I have now removed php7.0 and disabled php7.3 the sockets for omv5 have I moved to php7.4 and the Ui works as expected.
When something does'nt work I will use that command, thanks :)

**Comment by drajar** [comment]
I always have problem with php version used by openmediavault because I use testing version of debian. I think the correct solution is to let us choose what version of php want to use. For example, now php 7.3 is used only by openmediavalut, all other app use php 7.4, but I cannot remove 7.3 because is used by openmediavault...

**Comment by ryecoaaron** [comment]
Debian Testing isn’t supported and if you need newer php for other apps, run them in docker.

**Comment by votdev** [comment]
> I think the correct solution is to let us choose what version of php want to use. For example, now php 7.3 is used only by openmediavalut, all other app use php 7.4, but I cannot remove 7.3 because is used by openmediavault...

No, OMV is strictly tied to the Debian version it is based on. To prevent exactly those errors like yours OMV only supports the Debian stable branch.

**Comment by drajar** [comment]
There are only few hardcoded php7.3 that usually I replace manually. Hardcoding is not best practice in programming.

```
 grep php7.3 -r /usr/share/openmediavault/
/usr/share/openmediavault/scripts/helper-functions:     _valid=$(php7.3 -n -r "filter_var('$1', FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) ? print 0 : print 1;")
/usr/share/openmediavault/scripts/helper-functions:     _valid=$(php7.3 -n -r "filter_var('$1', FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) ? print 0 : print 1;")
/usr/share/openmediavault/scripts/helper-functions:     php7.3 -c /etc/openmediavault <<EOF
/usr/share/openmediavault/scripts/helper-functions:     _dirty=$(php7.3 -c /etc/openmediavault -r \
/usr/share/openmediavault/scripts/helper-functions:     _rc=$(php7.3 -c /etc/openmediavault <<EOF
/usr/share/openmediavault/engined/inc/99phpfpm.inc:        'filepath' => '/var/log/php7.3-fpm.log',
```

**Comment by ryecoaaron** [comment]
The hard coding does not matter.  The php-pam package that is essential to OMV is compiled against a specific version of the php api.  There is no way to specify a dependency in apt/dpkg to pick the right php-pam package based on which php you install.

**Comment by votdev** [comment]
I told you the technical reasons.

> There are only few hardcoded php7.3 that usually I replace manually. Hardcoding is not best practice in programming.

This is true, but this IS the only way to avoid users from breaking OMV.
