### ISSUE TITLE
rtnl: received non-static neighbor, ignoring.

### ISSUE THREAD

**Issue by henfri** [openmediavault/openmediavault#717]
### Description of issue/question
I get these messages in thousands in my syslog:
```
May 22 12:26:55 homeserver systemd-networkd[3492399]: rtnl: received non-static neighbor, ignoring.
May 22 12:26:55 homeserver systemd-networkd[3492399]: rtnl: received non-static neighbor, ignoring.
May 22 12:26:57 homeserver systemd-networkd[3492399]: rtnl: received non-static neighbor, ignoring.
May 22 12:26:57 homeserver systemd-networkd[3492399]: rtnl: received non-static neighbor, ignoring.
May 22 12:26:57 homeserver systemd-networkd[3492399]: rtnl: received non-static neighbor, ignoring.
May 22 12:26:57 homeserver systemd-networkd[3492399]: rtnl: received non-static neighbor, ignoring.
May 22 12:27:00 homeserver systemd-networkd[3492399]: rtnl: received non-static neighbor, ignoring.
```
I had the suspicion, that it was related to ipv6 (DHCP), but I deactivated ipv6 and the messages still come.

### Steps to reproduce issue
Not sure. These messages just appear in syslog.
ipv4 is configured static, ipv6, I tried auto and DHCP
I have also filed a bug upstream: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961268, but this also may be related with OMV.

### Versions report

ii  omvextras-unionbackend                                      5.0.2                               all          union filesystems backend plugin for openmediavault
ii  openmediavault                                              5.4.5-1                             all          openmediavault - The open network attached storage solution
ii  openmediavault-backup                                       5.2                                 all          backup plugin for OpenMediaVault.
ii  openmediavault-borgbackup                                   5.1                                 all          borgbackup plugin for OpenMediaVault.
ii  openmediavault-diskstats                                    5.0.5-1                             all          openmediavault disk monitoring plugin
ii  openmediavault-keyring                                      1.0                                 all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-nut                                          5.1.0-1                             all          openmediavault Network UPS Tools (NUT) plugin
ii  openmediavault-omvextrasorg                                 5.3.1                               all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-rsnapshot                                    5.0.3                               all          OpenMediaVault rsnapshot backup plugin.
ii  openmediavault-snapraid                                     5.0.5                               all          snapraid plugin for OpenMediaVault.
ii  openmediavault-unionfilesystems                             5.1.2                               all          Union filesystems plugin for OpenMediaVault.
rc  openmediavault-wireguard                                    5.0.2                               all          openmediavault WireGuard plugin

**Comment by mi-hol** [comment]
@henfri is the issue still open using latest versions?

**Comment by henfri** [comment]
Seems to be solved.
