### ISSUE TITLE
install script wrecks network configuration if multiple WLAN SSID/passwords are configured

### ISSUE THREAD

**Issue by dg1sek** [openmediavault/openmediavault#719]
I installed Openmediavault on Raspberry pi 4 standard installation.
I had several WLAN APs in my network config. 
I had not used netplan to configure my network.

After running the installation script, netplan crashed with a defective YAML file /etc/netplan/30-openmediavault-wlan0.yaml that contained several lines for the several SSID's and passwords.
However, it seems that the design of Openmediavault is not adapted to support multiple WiFi AP configurations. In network/interface/wlan0 user interface I could actually see the SSIDs were all concatenated. And of course, after the install script run, the whole machine was no longer reachable over the network after the next reboot, which is quite annoying.

I would advocate that the install script shouldn't mess around with the network configuration of the host machine at all. But if it does, then it should either select only one WiFi AP or handle the list of multiple WiFi AP correctly.

**Comment by votdev** [comment]
I think you are talking about the [install script](https://github.com/OpenMediaVault-Plugin-Developers/installScript) from omv-extras.org.

Please report the issue there. But i don't think it will support such complicated setups.

**Comment by ryecoaaron** [comment]
@dg1sek That is my bad.  I didn't even want the script to support wireless let alone mulitple SSIDs.  I will look at a flag to skip networking and do a better job parsing the wpa_supplicant.conf file.

**Comment by ryecoaaron** [comment]
Flag (-n) added and it will only use the first ssid now.
