### ISSUE TITLE
Delay usb-backup run until shared folders are mounted

### ISSUE THREAD

**Issue by wdckwrth** [openmediavault/openmediavault#720]
**Description of issue/question**
I have several hard drives that I use with the USB Backup plugin. When I reboot OMV with the configured USB drives attached OMV recognizes the drives prior to the shared folders being online. For jobs with the option set to delete files on receiving side that don't exist on sender it ends up deleting everything on the USB drive.

A fix is for me to remember to pull the drives after the backup is complete. A fix that would save me from myself would be to delay the USB Backup plugin run until all HDD/Raid/Shares are mounted.

**Steps to Reproduce Issue**
- Install USB Backup plugin
- Setup jobs with "Delete files on receiving side that don't exist on sender" option set.
- Plugin USB drive. Back up.
- Restart OMV.
- Watch files on USB drive get deleted.

**Versions Report**
Release: 5.5.0-1
Codename: Usul
Linux 4.14.180-odroidxu4 #16 SMP PREEMPT Wed May 20 19:58:06 CEST 2020 armv7l GNU/Linux
USB Backup 5.0.4-1

**Comment by mi-hol** [comment]
@votdev would #932 be related?

**Comment by votdev** [comment]
Fixed in `openmediavault-usbbackup 5.0.7`.
