### ISSUE TITLE
"secure" and "httpOnly" session cookie not enabled on https

### ISSUE THREAD

**Issue by mathieubolla** [openmediavault/openmediavault#721]
### Description of issue/question

After running a vulnerability scanner on my own OMV (version 4.1.30-1), I see there are two issues with the session cookie being sent without "secure" attribute, and without "httpOnly" attribute

I think one can solve this by setting the following:

```
php_value[session.cookie-secure] = On
php_value[session.cookie_httponly] = On
```

at:

`deb/openmediavault/srv/salt/omv/deploy/phpfpm/10webgui.sls` (around line 63)

PHP docs related to this config: https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-secure
https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-httponly
#### Important note

I'm unsure this would work for http (non SSL) web gui, as the browser would refuse the session cookie if sent over http. One would need to use conditionals. However, I'm unsure how to do this in that specific case (unfamiliar with Salt and how OMV config works at runtime)

### Steps to reproduce issue

Install a bare bones Open Media Vault (any recent version)
Configure it to use SSL for the web gui, with self signed certificates if needed for tests
Point a vulnerability scanner at it (I used OpenVAS 11 in Docker: https://hub.docker.com/r/securecompliance/gvm)

### Versions report

```
================================================================================
= OS/Debian information
================================================================================
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 9.11 (stretch)
Release: 9.11
Codename: stretch

================================================================================
= openmediavault information
================================================================================
Release: 4.1.30-1
Codename: Arrakis

================================================================================
= Date
================================================================================
Wed May 27 10:04:35 CEST 2020

================================================================================
= Hostname
================================================================================
mediavault.local

================================================================================
= Locale
================================================================================
C.UTF-8

================================================================================
= System information
================================================================================
Linux mediavault 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u2~bpo9+1 (2019-11-12) x86_64 GNU/Linux

```

**Comment by votdev** [comment]
I will add `php_value[session.cookie_httponly] = On` as default to the OMV fpm configuration, `session.cookie-secure = On` will be set in the nginx configuration if SSL is enabled and forced. If SSL is enabled without forcing it HTTP and HTTPS are available in parallel and then `session.cookie-secure = On` will break the HTTP connection.
