### ISSUE TITLE
No confirmation on web admin password change

### ISSUE THREAD

**Issue by tooomm** [openmediavault/openmediavault#722]
### Description of issue/question
Changing the web gui password requires you go to `General --> Web Administrator Password`.

I see two issues here (Confused me, too! That's why I came here):
 1) The interface should clearly tell you that you should enter the new one right away, instead let the user make assumptions.
A simple phrasing like "New password" instead "Password" would do the trick.
 2) There is no confirmation if you want to apply that change or at the very least no message that the change was succesfull. For me, only the text fields cleared and I had no clue what just happened. Was there a mistake? Did the passwords not match? Everything ok? Or do I have to type the old password first? ...

### Versions report
OMV 5.3.9-1 Usul

**Comment by votdev** [comment]
>     1. The interface should clearly tell you that you should enter the new one right away, instead let the user make assumptions.
>        A simple phrasing like "New password" instead "Password" would do the trick.

Sounds ok.


>     2. There is no confirmation if you want to apply that change or at the very least no message that the change was succesfull. For me, only the text fields cleared and I had no clue what just happened. Was there a mistake? Did the passwords not match? Everything ok? Or do I have to type the old password first? ...

The UI does not show notifications on success thus this page will not break this behavior. If there is a mistake (PRC call, password do not match), errors will be shown in a dialog (default behavior).

**Comment by tooomm** [comment]
>The UI does not show notifications on success thus this page will not do this too because this will break the default behavior. If there is a mistake (PRC call, password do not match), errors will be shown in a dialog (default behavior).

Please consider changing that with OMV 6 and give the user some sort of feedback or "Applied" message/check mark...

For the vast majority of changes you see a `The configuration has been changed. You must apply the changes in order for them to take effect.` message on the top in OMV 5.
Something along the lines in green could be displayed for successful changes as well, and keep the yellow ones once a confirmation is needed for more critical changes (as it is now).

**Comment by votdev** [comment]
> But please consider changing that with e.g. OMV 6 and give the user some sort of feedback or "Applied" message/check mark...

OMV6 will handle this better.

**Comment by votdev** [comment]
The OMV6 workflow looks like
![Peek 2020-05-27 15-02](https://user-images.githubusercontent.com/1897962/83022086-49c66c80-a02b-11ea-950c-bb5cfa88bd14.gif)

**Comment by tooomm** [comment]
Thanks for sharing, Volker. That looks very promising!

Really looking forward to the next release.
