### ISSUE TITLE
Labels for issues are not accessible

### ISSUE THREAD

**Issue by tooomm** [openmediavault/openmediavault#723]
### Description of issue/question
When you open an issue for this repo, you'll see this comment on the very top:
```
<!--
Thank you for opening an issue! Here are some tips on creating a well formatted contribution.

Please select the labels (on the right side) that match your issue/question.
-->
```

Unfortunately, it's not possible to select any label (e.g. `OMV 5.x`) and attach it to the fresh created issue.

### Steps to reproduce issue
- Open an issue in this GitHub repo
- On the right you'll only see the community guidlines, but no labels can be selected
(also once the issue is opened, the creator can't help with categorizing as asked for)

**Comment by votdev** [comment]
This is how Github works. Labels can only be set by project members with write access. I will adapt the issue text.

**Comment by votdev** [comment]
c4e602ace1ebc42f5e9fe09576b4aec542409392
