### ISSUE TITLE
allow floats for monit values

### ISSUE THREAD

**Issue by Zixim** [openmediavault/openmediavault#725]
### Description of issue/question
on a 2-core cpu,
setting this : `OMV_MONIT_SERVICE_SYSTEM_LOADAVG_5MIN_MULT=3.5`
does not result in 7 in this line : 
`if loadavg (5min) > {{ grains['num_cpus'] * loadavg_5min_mult | int }}`
because of the `int` filter.

int was added because : 
https://github.com/openmediavault/openmediavault/issues/431#issuecomment-527497057

Wouldn't `float` be better ?
`if loadavg (5min) > {{ grains['num_cpus'] * loadavg_5min_mult | float }}`
### Steps to reproduce issue
(Include debug logs if possible and relevant.)

**Comment by votdev** [comment]
Can you confirm that this will work?

**Comment by Zixim** [comment]
I've not made the edit to the system.j2 file on a running system.
However `{{ grains['num_cpus'] * loadavg_5min_mult | float }}`  evaluates to expected values.
{{ 2 * 3.5 | float }} returns 7
{{ 2 * 3.5 | int }} returns 6

I wanted some kind of feedback before doing it on a running system.
Is there a reason you decided to use `int`?

**Comment by votdev** [comment]
> Is there a reason you decided to use int?

I don't remember, but i think it was to make sure the calculation does nothing weird.

I would like to prefer `{{ grains['num_cpus'] * loadavg_5min_mult | float(1.0) | round(1) }}`.

**Comment by Zixim** [comment]
Will test & post back here in a day or so.

**Comment by Zixim** [comment]
just rcvd a couple of monit notifications, with float values, change works as expected.
