### ISSUE TITLE
BTRFS RAID1C34 Support

### ISSUE THREAD

**Issue by gabotronix** [openmediavault/openmediavault#726]
### Description of issue/question
I'm using BTRFS RAID1 on both of my secondary disks. I recently learned that newer versions of BTRFS now support RAID1c3 and RAID1c4. I would like to take advantage of this in the near future, when I add a 3rd disk.

If I understand it correctly, this is not yet supported in the latest OMV 5. Can support for BTRFS RAID1c3 and c4 be added in a future OMV 5 update?

Here are some references on it:

[Debian Wiki - BTRFS](https://wiki.debian.org/Btrfs#History)
> Linux ≥ 5.5 and btrfs-progs ≥ 5.4 finally bring support for checksum algorithms that are stronger than CRC32C. xxHash, SHA256, and BLAKE2 are supported with kernel+btrfs-progs newer than these. Additionally, with these releases raid1c3 and raid1c4 profiles have finally been introduced. These new profiles have enhanced data redundancy. Where the well-tested raid1 profile supports two copies on N devices, raid1c3 supports three copies, and raid1c4 supports four. When a failing disk needs to be replaced it is now possible to add a third disk, rebalance to raid1c3, then drop the failing disk from the array. As the degraded chunk problem has not yet been solved in linux-5.5 (AFAICT, please feel free to update this page when it's fixed) an additional rebalance to raid1 is necessary, which rewrites all data and metadata a second time.

[BTRFS Wiki](https://btrfs.wiki.kernel.org/index.php/Changelog#By_feature)
- btrfs-progs v5.4 (Dec 2019)
- support new hash algorithms (kernel 5.5):
- mkfs.btrfs and btrfs-convert with --csum, crc32c, xxhash, sha256, blake2
- mkfs: support new raid1c3 and raid1c4 block group profiles (kernel 5.5)

### Versions report
OMV: 5.5.0-1 (Usul)
`uname -mrs` : Linux 5.5.0-0.bpo.2-amd64 x86_64
`btrfs --version` : btrfs-progs: v4.20.1

**Comment by ryecoaaron** [comment]
This would require btrfs-progs to at least be in buster-backports and it is not (5.2 is).  So, this will have to wait for Debian to put it there.

**Comment by votdev** [comment]
You'll get the features if Debian will make this package version available in Debian 10 (stable). Note, OMV does not support backports. You can try to install the package manually, but without warranty. Using backports in OMV may result in unexpected behavior of the system.

**Comment by prahal** [comment]
I plan to set up my BTRFS for OMV by hand, but still noted this report was valid nowadays. But I noticed OMV 7.4.7 does not to have support for RAID1c3/4. Even if only for metadata.
Thus resurrecting this bug report.

**Comment by votdev** [comment]
> I plan to set up my BTRFS for OMV by hand, but still noted this report was valid nowadays. But I noticed OMV 7.4.7 does not to have support for RAID1c3/4. Even if only for metadata. Thus resurrecting this bug report.

I am not up-to-date what is supported in Debian 12. if the UI does not support orbit does not mean that you can not do it via CLI.

**Comment by g6094199** [comment]
i´ m curious how is the state of this in 2026 with trixie?


> > I plan to set up my BTRFS for OMV by hand, but still noted this report was valid nowadays. But I noticed OMV 7.4.7 does not to have support for RAID1c3/4. Even if only for metadata. Thus resurrecting this bug report.
> 
> I am not up-to-date what is supported in Debian 12. If the UI does not support it does not mean that you can not do it via CLI.

isnt the goal of OMV (and other frontends) to enable the ordinary users to NOT to be forced to use the cli? .....the target is a broader audience?!?
