### ISSUE TITLE
SMB config for MacOS

### ISSUE THREAD

**Issue by stalinCCCP415** [openmediavault/openmediavault#727]
if you have at least one share enabled for time machine then

`fruit:aapl = yes` 

gets set globally and

`vfs objects =  catia fruit streams_xattr`

Gets set only on the time machine share.

The global behavior is as I would expect, but only the time machine share getting the vfs object parameters is counter what I’ve seen from the samba wiki. It recommends to set this on all shares if set on any of them. From samba wiki:

`Be careful when mixing shares with and without vfs_fruit. OS X clients negotiate SMB2 AAPL protocol extensions on the first tcon, so mixing shares with and without fruit will globally disable AAPL if the first tcon is without fruit.`

Behavior should be to at least set 

 `vfs objects =  catia fruit streams_xattr` on all shares if

`fruit:aapl = yes` is set globally.

**Comment by votdev** [comment]
What about setting `vfs objects = catia fruit streams_xattr` in `[Global]` in this case instead of added it to every share?

**Comment by stalinCCCP415** [comment]
I think that should work.

I noticed that the shares with time-machine enabled set the below at the share level (left out the time-machine directive):

`fruit:encoding = private
fruit:locking = none
fruit:metadata = netatalk
fruit:resource = file`

I don't think these are explicitly necessary to be set on other shares as they are the current samba defaults, but could be useful if that changes.

**Comment by stalinCCCP415** [comment]
Looks like if you set 
`vfs objects = catia fruit streams_xattr`
globally, but do not specify it in every share, testparm still gives the warning. I don't know if setting it at a share level explictly is also neccessary?
