### ISSUE TITLE
Linux root on ZFS doesn't work

### ISSUE THREAD

**Issue by artiomn** [openmediavault/openmediavault#73]
Exception in the function assertIsUnique [/usr/share/php/openmediavault/config/database.inc:495].
Look at [this instruction](https://github.com/zfsonlinux/zfs/wiki/Debian-Stretch-Root-on-ZFS).
rpool has mountpoint "/" and rpool/ROOT/debian has mountpoint "/".
It's normal and not prohibited.
But you check mountpoint uniqueness, that is not correct.

Assert commenting "solved" this problem:
```php
        /** 
         * Assert that a configuration object with the value of the specified
         * property is unique.
         * @param object The configuration object to use.
         * @param property The name of the data model property.
         * @return void
         * @throw \OMV\AssertException
         */
        public function assertIsUnique(ConfigObject $object, $property) {
              /*if (FALSE === $this->isUnique($object, $property)) {
                        throw new \OMV\AssertException("The configuration object '%s' is ".
                          "not unique. An object with the property '%s' and value '%s' ".
                          "already exists.", $object->getModelId(), $property,
                          $object->get($property));
        }*/
        }
```

This "fix" breaks monitd config:
```
# Alert if disk space of root filesystem gets low
check filesystem rootfs with path /
  if space usage > 85% for 5 times within 15 cycles
    then alert else if succeeded for 10 cycles then alert

check filesystem filesystem_ with path "/"
  if space usage > 85% for 5 times within 15 cycles
    then alert else if succeeded for 10 cycles then alert

check program mountpoint_ with path "/bin/mountpoint '/'"
  if status != 0 then alert
check filesystem filesystem_ with path "/"
  if space usage > 85% for 5 times within 15 cycles
    then alert else if succeeded for 10 cycles then alert

check program mountpoint_ with path "/bin/mountpoint '/'"
  if status != 0 then alert
check filesystem filesystem_home with path "/home"
  if space usage > 85% for 5 times within 15 cycles
    then alert else if succeeded for 10 cycles then alert
```

**Comment by votdev** [comment]
Commenting out code does not solve a problem. Checking the uniqueness has a reason.

**Comment by artiomn** [comment]
Yes, I have noticed this below. But this code breaks ZFS plugin. You need to allow the creation of multiple records with the same mountpoint for ZFS and make special processing, to avoid breaking other stuff, like monitd and etc.

**Comment by artiomn** [comment]
Notice, that Linux root on ZFS will be a common way in the near future, and FreeBSD uses this configuration already.

**Comment by votdev** [comment]
ZFS will never official part of Debian because of the license issue, thus it will not be supported by OMV officially. I'm open for contributions to workaround this, but i will not invest any time into this issue because of the reasons above.

**Comment by artiomn** [comment]
Thank you for your friendliness and responsibility. :-/

It works:
```
diff Utils.php /usr/share/omvzfs/Utils.php 
178c178
<             if (($mntpoint != "none") && ($mntpoint !== "legacy"))
---
>             if (($mntpoint != "none") && ($mntpoint !== "legacy") && strpos($name, '/'))
```

Is it enough?
