### ISSUE TITLE
Feature suggestion: smb.conf options to follow symlinks

### ISSUE THREAD

**Issue by geckolinux** [openmediavault/openmediavault#732]
Hi there, I think it might be helpful to offer a toggle in the SMB/CIFS options to make Samba follow symlinks. I found that the following extra options allow me to access an external mounted USB drive when the `/media` directory is symlinked into my Public SMB share:
``````````````
follow symlinks = yes
wide links = yes
unix extensions = no
``````````````
This would be especially useful in conjunction with the **sharerootfs** plugin.

**Comment by votdev** [comment]
I do not like to see such a feature because of security issues. I think if a user wants to use this they can use the `Extra options` field.

**Comment by votdev** [comment]
By the way you can use the environment variable `OMV_SAMBA_SHARE_FOLLOWSYMLINKS` to customize the OMV setting via `/etc/default/openmediavault`. To apply the customization run `omv-salt stage run prepare; omv-salt deploy run samba`.

**Comment by geckolinux** [comment]
> I do not like to see such a feature because of security issues

Thanks, could you elaborate a bit more on what the potential risks are? Could somebody break into the `/` directory somehow? Or are you referring to security risks of sharing the contents of the USB drive?

**Comment by votdev** [comment]
I don't like to support symlinks because this will allow services to break out of the shared folders. OMV provides enough possibilities to customize it to your needs. I only do not want to support it via UI.
