### ISSUE TITLE
Error on web login when OMV it not yet completely ready

### ISSUE THREAD

**Issue by tooomm** [openmediavault/openmediavault#735]
### Description of issue/question
It should not be possible to login before everything is 100% ready.
Once the login page appears the user expect that he can fully interact with it.

Error message shown after trying to login:
```
Error #0:
OMV\HttpErrorException: Invalid IP address. in /usr/share/php/openmediavault/session.inc:185
Stack trace:
#0 /usr/share/php/openmediavault/session.inc(207): OMV\Session->validateIpAddress()
#1 /var/www/openmediavault/index.php(34): OMV\Session->validate()
#2 {main}
```

### Steps to reproduce issue
- Restart server
- Go to the web interface before OMV is fully booted up, it loads already and looks ready
- Login

### Versions report
OMV 5.5.1

**Comment by votdev** [comment]
The `Invalid IP address.` is thrown when you login with another `host` IP address than the session was started. IMO this has nothing to do with your mentioned scenario.

**Comment by tooomm** [comment]
I will look into it again in the next days and post here 👍

**Comment by tooomm** [comment]
After checking again, I guess you must be right and I messed it up.

Still trying to get used to all the settings. Looks like the docs are quite comprehensive.
However, there is no "Getting Started" tutorial or "Quick-Start" guide to get some simple SMB share setup as first time user with only limited linux pre-knowledge...

**Comment by ryecoaaron** [comment]
@tooomm https://forum.openmediavault.org/index.php?thread/23005-installation-and-setup-videos-beginning-intermediate-and-advanced/

**Comment by tooomm** [comment]
I did not check the forums yet... Thanks a lot for sharing and linking the videos from TechnoDadLife! @ryecoaaron 

I saw already some of his videos - next to others - on YouTube. While they are helpful, I was more looking for a written guide (maybe + pics) with a the basic steps. Videos do have their benefits and are nice for a first watch. But for checking something it's not ideal, it can be more time consuming and not all environments or situations allow to watch a video (not to mention sound).

Do you know of any written compendium/tutorials as well by chance?

**Comment by ryecoaaron** [comment]
Maybe the Getting Started guide? https://github.com/OpenMediaVault-Plugin-Developers/docs/blob/master/Getting_Started-OMV5.pdf

**Comment by tooomm** [comment]
That looks very promising! Will give it a shot. Thank you :)
