### ISSUE TITLE
Installing docker breaks DNS

### ISSUE THREAD

**Issue by fcimeson** [openmediavault/openmediavault#740]
### Description of issue/question
After installing docker, my raspberry pi is not able to reach the internet. The local network is ok.

### Steps to reproduce issue
Install docker
![Screenshot from 2020-06-16 22-32-43](https://user-images.githubusercontent.com/3228114/84848537-54b85f80-b021-11ea-9963-293bc89d3dd3.png)

### Versions report
* Rasbian Buster Lite
* openmediavault-backup/buster,now 5.2 all [installed]
* openmediavault-diskstats/usul,usul,now 5.0.5-1 all [installed]
* openmediavault-keyring/usul,usul,now 1.0 all [installed]
* openmediavault-omvextrasorg/buster,now 5.3.3 all [installed]
* openmediavault-unionfilesystems/buster,now 5.1.2 all [installed]
* openmediavault/usul,usul,now 5.5.2-1 all [installed]

```
$ ping www.google.ca
ping: www.google.ca: Name or service not known

$ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:d6:25:85:31  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.4  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::6af6:4a3e:30a:1483  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:ad:97:d6  txqueuelen 1000  (Ethernet)
        RX packets 43123  bytes 62798382 (59.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24532  bytes 6166667 (5.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         _gateway        0.0.0.0         UG    202    0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.1.0     0.0.0.0         255.255.255.0   U     202    0        0 eth0
```

**Comment by antipiot** [comment]
So, if you uninstall docker it starts working again?
Have you tried with another DNS server to double check?

Can you post content of: 
"cat /etc/network/interfaces"

**Comment by fcimeson** [comment]
Yes, sorry, it is solved by using this [install script](https://github.com/OpenMediaVault-Plugin-Developers/installScript).

**Comment by tarmacalastair** [comment]
Not quite sure why this has been closed. It happened to me a week ago. Somehow I managed to reinstall OMV and got it working. Then I messed up permissions in OMV so reinstalled OMV today, added Docker and now DNS is broken again!

It's not fixed!

**Comment by votdev** [comment]
> It's not fixed!

Maybe this is now the point to investigate this issue why it breaks YOUR setup and how fixing YOUR system might help other users. Please provide community contributions here https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg because this issue seems not OMV core related.

**Comment by ryecoaaron** [comment]
@tarmacalastair It must be something special with iptables on your system?  Because I have install docker hundreds of time from omv-extras and it has never broken dns.  But I agree, this is not an OMV core issue.

**Comment by tarmacalastair** [comment]
> > It's not fixed!
> 
> @tarmacalastair Maybe this is now the point to investigate this issue why it breaks YOUR setup and how fixing YOUR system might help other users. Please provide community contributions here https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg because this issue seems not OMV core related.
> 
> > Yes, sorry, it is solved by using this install script.
> > PS. A number of things were fixed by this install script.
> 
> By the way, the issue has been closed by the creator itself. He mentioned how the issue was fixed.

Yeah, but how do I run the script if I can't resolve the DNS name? And the script then pulls further stuff needing DNS I think, maybe not.
I am trying to work out the cause to help myself and others.
So far, the steps I have taken on a brand new Odroid HC4 are:
1. Boot from an SD card with petit boot preinstalled
2. Chosen netboot_default from its menu
3. Installed Debian 10 with command line only plus ssh
4. Downloaded OMV installer with wget -O omv_install.sh https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install , made it executable and run it. Steps taken from https://wiki.odroid.com/odroid-hc4/software/install_omv_nas
5. Within OMV: Ticked the Pre-release updates and Community-maintained updates from under Update Management
6. Within OMV: Ticked Testing, Extras & Backport under OMV Extras
7. Installed Docker and DNS no longer working so could then not install Portainer or anything else.

Unless I can fix the DNS then I'm going to have to start the whole process again from the very beginning and the only things I think I can do differently are to not enable the extra repositories and then enable them one at a time until it breaks.

Sorry to be a pain - completely new to OMV and Docker this week.

**Comment by ryecoaaron** [comment]
I have an HC4 but I disabled petitboot and am using armbian buster.  Stop enabling pre-release, community, testing, and extras repos.  You can leave backports.  What is the output of:
systemctl status systemd-resolved
ls -al /etc/resolv.conf

**Comment by tarmacalastair** [comment]
Thanks. I ran your commands and got:

> al@odroidhc4:~$ systemctl status systemd-resolved :
● systemd-resolved.service - Network Name Resolution
   Loaded: loaded (/lib/systemd/system/systemd-resolved.service; enabled; vendor preset: enabled)
  Drop-In: /usr/lib/systemd/system/systemd-resolved.service.d
           └─resolvconf.conf
   Active: active (running) since Thu 2019-02-14 10:12:02 GMT; 1 years 11 months ago
     Docs: man:systemd-resolved.service(8)
           https://www.freedesktop.org/wiki/Software/systemd/resolved
           https://www.freedesktop.org/wiki/Software/systemd/writing-network-configuration-managers
           https://www.freedesktop.org/wiki/Software/systemd/writing-resolver-clients
 Main PID: 1819 (systemd-resolve)
   Status: "Processing requests..."
    Tasks: 1 (limit: 3385)
   Memory: 4.5M
   CGroup: /system.slice/systemd-resolved.service
           └─1819 /lib/systemd/systemd-resolved

> ls -al /etc/resolv.conf :
> lrwxrwxrwx 1 root root 32 Jan 22 08:59 /etc/resolv.conf -> /run/systemd/resolve/resolv.conf

I am so confused. Last night I uninstalled Docker and rebooted and still no DNS. Left it and went to bed. This morning DNS was working again. Frustrated, I thought I'd download that script above on my PC. I downloaded it to a text file and compared it (with diff) to the script I ran when I first installed OMV and it is identical. I reran it and rebooted. I've just reinstalled Docker and again DNS is broken. I can ping external IP addresses but not DNS names....
Ran the script another time and DNS working....installed Portainer and DNS broken again....Ran script yet again and IP4 on the main NIC now not working so had to use omv-firstaid to reset it. Portainer now complaining that it has no endpoints configured and as I'm a complete beginner I'm going to have to start again from scratch, this time with only the repos that you recommend.

**Comment by tarmacalastair** [comment]
Update: After five minutes or so I tried installing Yacht and it was successful. Portainer now recognises my Docker. Not sure if the install of Yacht fixed this or if I was too hasty or perhaps my browser cache had messed things up.
Anyway, the upshot seems to be that rerunning the script after installing Docker and then again after installing Portainer, plus running omv-firstaid to fix the NIC seems to have fixed it.
All rather long winded and unsatisfactory but it works.

**Comment by ryecoaaron** [comment]
I can't reproduce any of this.  How is your network setup on the system?

**Comment by tarmacalastair** [comment]
Hmm, I can't do anything other than reproduce this - I've installed multiple times now and DNS breaks every time as soon as I install Docker. 

Network - single NIC on the Odroid board running Debian 10 out of the box. I've manually disabled Ip6 within OMV on the card.
Physical network - Odroid Nic connected to home router via Cat5 cable. 

The router doles out IP settings via DHCP so could that be where my network settings differ? See below.

Interesting observation - after much searching on my issue and after reading https://forum.openmediavault.org/index.php?thread/30065-upgrade-to-openmediavault-5-1-3-1-breaks-dns-reolution/ , I added the IP of my router as a DNS server in the advanced network settings within OMV and this seems to sort out the resolution, allowing me to continue setting up Docker, Portainer, etc.

So adding a manual DNS server could be a workaround to this issue but I wouldn't describe it as a fix.

Thanks for your patience here.

**Comment by ryecoaaron** [comment]
What odroid?  A Debian 10 image from the hardkernel forum?  I have many odroids and have installed Docker on them many times without this issue but I use armbian images.

When docker is installed, it creates a bridge and makes some changes to iptables.  omv-extras can't do anything about either of those.  I don't know why they would break DNS though.

The things the post mention are the same reason I asked for output of those two commands.  If you have to manually add a DNS server, that tells me it is either something with your router (I know it works before docker) and/or something weird with the Debian image you are using.

**Comment by tarmacalastair** [comment]
Sorry for the slow response.

Odroid is an HC4, just purchased and running Debian 10 installed via petit boot which was pre-installed when the Odroid arrived. I then ran "netboot_default" from the menu and proceeded to install Debian 10 from the resulting menu (Debian 11 didn;t like the OMV from https://wiki.odroid.com/odroid-hc4/software/install_omv_nas)

Please see above for my output to the commands you asked for.

Another interesting observation which is probably not related: Somewhere during the installation of OMV and getting Docker and Portainer installed, my user password is changed from what I set, to "openmediavault". I keep discovering this when I try to ssh into my Odroid.

**Comment by ryecoaaron** [comment]
You can't use Debian 11.  I haven't used the Debian 10 install using your method.  I do have an hc4 running OMV but once again, it is using Armbian.  Not even sure what to ask for output on to figure out the dns issue.  Still seems to be something weird with your setup.

Is your username "admin"?  If it is, then that is why it is changed.

**Comment by tarmacalastair** [comment]
OK, well thanks for your efforts to help. You say it seems to something weird with my setup but I am using a brand new HC4 and am following the instructions in the Odroid wiki at https://wiki.odroid.com/odroid-hc4/software/install_omv_nas so the only other thing that I can think could be different is my physical network. 

For now, I'll live with adding my DNS IPs manually within OMV unless someone can get to the bottom of this.

No my username is not admin. It's a custom username that I set up during the Debian installation. The OMV setup process also disabled my ssh access for that user and I had to manually add myself afterwards to the "ssh" group inside OMV.

**Comment by ryecoaaron** [comment]
When I say the setup is weird, I was referring to the physical network.  And while there is an odroid wiki, it is running my install script which is tested heavily on Armbian.  It shouldn't have a problem with a debian 10 netinstall but seems to have something weird in the dns setup unless that is just your network.  I don't want to re-enable petitboot to test on the hc4 since it is the only odroid using it.

OMV didn't change the password if it is not admin.  The installation of OMV does change the setup of ssh to require the user to be in the ssh group.  If you ran the install script as that user, it would automatically add the user to the ssh group.  If you run the install script as root, then it doesn't know to do that.
