### ISSUE TITLE
Question - why copy from Web UI is not allowed?

### ISSUE THREAD

**Issue by yuriw** [openmediavault/openmediavault#747]
Any entries like logs:

![image](https://user-images.githubusercontent.com/3876474/86069550-1b272180-ba2f-11ea-82c4-4130d329424c.png)

Or File Systems:

![image](https://user-images.githubusercontent.com/3876474/86069578-35f99600-ba2f-11ea-9bc5-0c30c3860027.png)

(see yellow selected line) - can not be copied to the clipboard.
Is there any reason for such unfriendly behavior ?

**Comment by votdev** [comment]
> Is there any reason for such unfriendly behavior ?

Yes, there was no need to do so until now. After many years this is the first request for that. Because the use of the ExtJS framework is counted, i will not invest any time to implement that anymore. Maybe a good feature for the Angular based UI in OMV6.

**Comment by votdev** [comment]
@yuriw Nice to see that you're using OMV. I thought you've running a Ceph cluster at home :-) Greetings from a Dashboard member.

**Comment by auanasgheps** [comment]
I actually wanted to copy some stuff from the GUI in the past and retrieved the text from the page code. Clunky but worked. If you can implement copy in OMV 6, it would be great.

**Comment by yuriw** [comment]
@votdev Hello :) no ceph at home ...

**Comment by yuriw** [comment]
@votdev This is not dead drop issue, but a bit odd not being able to copy a line from log files or mount point setting.  If doable pls consider implementing.

**Comment by tooomm** [comment]
>After many years this is the first request for that.

I noted that in #724 already. There are probably more who miss that behavior.

But I'm fine seeing copyable text in OMV 6! 👍

**Comment by yuriw** [comment]
Side note - it's funny to see OMV videos on YouTube when people using right mouse click, inspect web element object, copy to get  absolute path into clipboard.   I am sure they will appreciate to see this in OMV 6 !

**Comment by mi-hol** [comment]
@yuriw would you please change the title to "[Feature Request] enable copy & paste in OMV UI table views"

**Comment by votdev** [comment]
Fixed in OMV6.

![Peek 2020-12-18 11-36](https://user-images.githubusercontent.com/1897962/102605371-7952d880-4125-11eb-8650-782967f76a8e.gif)
