### ISSUE TITLE
Using the `omv-firstaid` kills network connection

### ISSUE THREAD

**Issue by yuriw** [openmediavault/openmediavault#749]
I documented more details in this post https://forum.openmediavault.org/index.php?thread/33270-killed-network-how-modify-via-file-s-on-sd-card/&postID=244119#post244119

Long story short.
I noticed that OMV is not friendly with WiFi on R Pi.  All installation tries resulted in WiFi be left nonfunctional.
 
So the `omv-firstaid` tool promoted a user to modify WiFi and add user and password.  
And I decided to give it a try.
However `omv-firstaid` saved settings and apparently disabled unchecked WiFi interface and disabled normally working Ethernet interface and thus left a user with disconnected from the network R Pi OMV box.

I think it would be more reasonable to either disallow WiFi all together if it's not support (not sure if this is true, is it?) or verify connectivity of WiFi interface before committing changes. It also unclear why Ethernet interface needed to be disabled.

**Comment by ryecoaaron** [comment]
While I don't like wifi on a NAS ever, I have tested wifi with OMV 5 and my RPi4 and it works fine.

**Comment by yuriw** [comment]
I've never seen WiFi working on R Pi right after installing OMV, and tried many many times.  My guess is the OMV install script disables it - guessing here.
I am not advocating for WiFi all and understand as it relates to NAS in general.
But then let's remove it all together, otherwise it has to work and not harm novice users.

**Comment by ryecoaaron** [comment]
The install script does kill it if you don't set it up according to the rpi foundation method - https://www.raspberrypi.org/documentation/configuration/wireless/headless.md.  And having wrote the script and tested hundreds of times now, I have had wifi working right after the install script reboots.

Try to remember the RPi isn't the only thing OMV and the install script works on.  So, one users luck doesn't mean the feature should be removed.

**Comment by yuriw** [comment]
I am not advocating to remove it either - just providing a use case that is dangerous.

**Comment by ryecoaaron** [comment]
I have done it two ways and those are the ways that will work with the script.

1 - install raspian buster lite and setup the wpa_supplicant file in the link. Then run the script. Do nothing else in between those steps.

2 - install raspbian buster lite then run the script. Setup wifi in the web interface and reboot with the ethernet cord disconnected.

I don’t know how any of it is dangerous. you can always plug a keyboard and mouse in to fix or start over.

**Comment by yuriw** [comment]
@ryecoaaron 
Just reread you post "reboot with the ethernet cord disconnected"
Does it mean that OMV can use only one interface at the time but not both ?

(That would explain my problems as I was trying to make them both work)

**Comment by ryecoaaron** [comment]
I would have to try it but if the wired connection and wifi connection both specify the same gateway, it is going to cause a lot of problems.  I would not use both at the same time on the same network.
