### ISSUE TITLE
Confusing behaviour with plugin uninstallation

### ISSUE THREAD

**Issue by artiomn** [openmediavault/openmediavault#75]
After uninstalling plugin, sometimes it remains in the sidebar.
Engine restarting doesn't help.
I thought, that it's problem with an plugin uninstallation logic or the server's cache, but I realized, that it's a browser cache, probably (I'm not sure).
I'm use Chromium to access OMV.
After refreshing page, using Ctrl+F5, old plugins images disappeared.

Maybe, you need to control cache, using meta cache-control?

**Comment by votdev** [comment]
We have meta cache control already but set it to 14 days or something to reduce load on small devices.

**Comment by artiomn** [comment]
Ok, but it's really confusing behavior. And is not simple to understand, where the problem is.
Maybe you need to mark cache dirty after the engine was restarted?
