### ISSUE TITLE
Rsync connection issue

### ISSUE THREAD

**Issue by Galiwyx** [openmediavault/openmediavault#751]
Hello,

I'm trying to configure a rsync connection with a remote server.  It displayed an error. I test to CD the directory and it exists !

```
Please wait, syncing <[alex586@]xxx:/home11/alex586/files/completed/> to </srv/dev-disk-by-label-Files/Files/Syncthing/> ...

sending incremental file list
rsync: change_dir "/[alex586@]xxx:/home11/alex586/files/completed" failed: No such file or directory (2)

sent 20 bytes  received 12 bytes  64.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]

The synchronisation has completed successfully.
```
SSH:
![image](https://user-images.githubusercontent.com/206181/86304636-ca225380-bc0f-11ea-9549-1a11166ee6c1.png)
Thank you !!

**Comment by votdev** [comment]
Please use the [forum](https://forum.openmediavault.org/) for such issues, Github is only for bugs. You'll get a broader audience at the forum, too.
