### ISSUE TITLE
Logon Display

### ISSUE THREAD

**Issue by sechanbask** [openmediavault/openmediavault#756]
### Description of issue/question

On web site logon page, the logon frame is to small

https://ibb.co/RCb7yTW

<a href="https://imgbb.com/"><img src="https://i.ibb.co/9qgGtHj/2020-07-10-22h08-59.png" alt="2020-07-10-22h08-59" border="0"></a>

### Steps to reproduce issue
use french language web GUI, and go to the admin web page

### Versions report
5.5.3-1 (Usul)

cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by votdev** [comment]
Can not reproduce this with Firefox 78.0.1 and Chrome 83.0.4103.116.

![screenshot](https://user-images.githubusercontent.com/1897962/87338438-7b48b800-c545-11ea-98a5-f0aa7f7a03fe.gif)
