### ISSUE TITLE
Moving install to a different network broke networking

### ISSUE THREAD

**Issue by tamasberes** [openmediavault/openmediavault#757]
### Description of issue/question
I've moved my install to another network, with a different IP configuration.
Old network: 10.1.1.0/24
New network: 10.0.0.0/24
After moving to the new network, everything seemed to work fine. After a while, I have noticed that the box lost access to the internet.

### Steps to reproduce issue
Web GUI shows that I'm using DHCP.
I'm not sure what happened, but /etc/dhcpcd.conf still had the old Static IP setup from my old network, which obviously should not work...but it did. Local LAN worked fine, and I did have the expected new new network IP trough DHCP. 
```
...
interface eth0
        static ip_address=10.1.1.101/24
        static routers=10.1.1.1
        static domain_name_servers=1.1.1.1 1.0.0.1

```

I had to manually edit /etc/dhcpcd.conf and fix the IPs.
On the web GUI it still shows that I'm using DHCP, but at least I have access to the internet again.

### Versions report
5.5.3-1 
running on a raspberry pi 4 - 4Gb version.

**Comment by votdev** [comment]
Rebooting the system should fix that. You can also do that manually by running `netplan apply` or rebuild the whole network configuration with `omv-salt deploy run systemd-networkd`.
