### ISSUE TITLE
Errors reported after attempting notifications

### ISSUE THREAD

**Issue by Jscotts** [openmediavault/openmediavault#758]
### Initial set up notification email worked but then cron system errors reported.
5 minutes later I received an email 
/etc/cron.daily/openmediavault-cron-apt:
postdrop: warning: unable to look up public/pickup: No such file or directory
/etc/cron.daily/openmediavault-flush-mailq:
postsuper: fatal: scan_dir_push: open directory hold: No such file or directory
run-parts: /etc/cron.daily/openmediavault-flush-mailq exited with return code 1

I have not set up any cron jobs so I do not know what caused this or the potential impact.
What action is required ?
Clean install with OMV EXTRAS and PROXMOX kernel for ZFS

**Comment by Jscotts** [comment]
[syslog.txt](https://github.com/openmediavault/openmediavault/files/4921038/syslog.txt)
[content1594756932.txt](https://github.com/openmediavault/openmediavault/files/4921044/content1594756932.txt)
[syslog.txt](https://github.com/openmediavault/openmediavault/files/4921046/syslog.txt)

**Comment by Jscotts** [comment]
closed in error

**Comment by votdev** [comment]
IMO the problem comes from the `openmediavault-flashmemory` which does not restore the `/var/spool/postfix/public/pickup` directory correctly.

**Comment by ryecoaaron** [comment]
openmediavault-flashmemory will restore whatever it saves off *unless* you don't shutdown your system correctly. Even if it had a cron job to sync everything in tmpfs to disk, it is still possible it would miss something.  Not sure how to fix this while still reducing writes.
