### ISSUE TITLE
Add option to usbbackup plugin - select more than one source and more that one target

### ISSUE THREAD

**Issue by antipiot** [openmediavault/openmediavault#759]
### Description of Suggestion:
It would be great if the USB backup plugin would let the user select one or more sources aswell as one or more target.
Actually if you want to sync 3 folder and have kind of a rotation between target drives, you'll have to setup 15 jobs in order.

### Steps to reproduce issue
Install plugin
Create a job - cant select more than one sources and / or more than one targets

### Versions report
OMV: 5.5.4-1 Usul
USBBACKUP 5.4.0.1

Thanks to all the team, maintainers and contributers :-)

Regards - JS

**Comment by votdev** [comment]
`rsync` can not copy data to multiple targets at once, so how should this work? The mentioned scenario can not be implemented based on rsync, so i close this issue.
Using a clever shared folder structure with sub-folders can help in such situations.
