### ISSUE TITLE
Services inside containers

### ISSUE THREAD

**Issue by artiomn** [openmediavault/openmediavault#76]
OMV has Docker GUI plugin, it's good, but installing most of plugins, as a docker containers is better.
I.e., I want to have a backup server and use Urbackup for it.
Now, OMV will install urbackup-server package, and an interface plugin, which will try to manage locally launched server.
But I want control interface inside OMV and Urbackup inside a container, which I can access using domain name (using nginx-proxy+companion for the SSL certs) or port.
This way is more secure, more portable and doesn't pollute the system with bunch of packages.

This is not a bug, of course, it's a suggestion.
Is it possible to implement?

**Comment by votdev** [comment]
Please raise this for the [urbackup](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-urbackup-server) plugin.

**Comment by artiomn** [comment]
It's not about urbackup, I mentioned it as an example.
A good idea is to run **all** services inside containers.

**Comment by mcarbonneaux** [comment]
it's clear all internal plugin must use docker to deploy in place of dpkg package... is less intrusive...
use only the host system for the admin ui, storage server part only...

**Comment by ryecoaaron** [comment]
While I think a lot of plugins work well in docker, I don't think all plugins must use docker.  Here is my list of what omv-extras plugins will use docker or native - https://forum.openmediavault.org/index.php/Thread/24545-Why-should-you-use-or-not-use-dockers/?postID=186122#post186122

**Comment by mcarbonneaux** [comment]
This liste seem to be good, iok not all plug-in can or must be dockerized...

And Portainer.io to replace docker gui plug-in are a good solution....

Shellinbox can be replaced by apache guacamole... Already in docker image...
