### ISSUE TITLE
Separate logins under IP and server.local?

### ISSUE THREAD

**Issue by tophee** [openmediavault/openmediavault#760]
### Description of issue/question
My OMV is accessible under `192.168.1.4` as well as `server.local` but I have to login separately under the IP and under the domain. And when I logout from one of them, I'm still logged in under the other. Is this intentional? I think logging in or logging out under the IP address should also give you access under the domain and vice versa. And, most importantly: when you log out, you should be logged out either way.

### Versions report
5.5.4.1

**Comment by votdev** [comment]
This is exactly how sessions work in PHP. Please see https://stackoverflow.com/a/11836947.
