### ISSUE TITLE
tutorial about how to install the software

### ISSUE THREAD

**Issue by ardeal** [openmediavault/openmediavault#761]
Hi,

Is there any tutorial about how to install OMV software?

I know that there are many videos about how to install it, but those videos couldn't be played because of my network.
https://forum.openmediavault.org/index.php?thread/23005-installation-and-setup-videos-beginning-intermediate-and-advanced/

Thanks,

**Comment by votdev** [comment]
See https://docs.openmediavault.org

**Comment by ryecoaaron** [comment]
There is also info here - https://forum.openmediavault.org/index.php?thread/28789-installing-omv5-on-raspberry-pi-s-armbian-sbc-s-i386-32-bit-platforms/

**Comment by ardeal** [comment]
Thank you all!

@ryecoaaron ,
Those files in your link couldn't be opened.
I am not sure whether there is something wrong with my network or those files.

**Comment by ardeal** [comment]
@votdev ,
according the instruction in your link: https://docs.openmediavault.org, I couldn't find out whether OMV should be installed as a indepent OS or software in my current OS?

If the instruction in your link is clearer, it might be much for my understanding.

**Comment by ryecoaaron** [comment]
@ardeal They are all working for me.  Did you try to download them?
