### ISSUE TITLE
IP address isn't displayed in console

### ISSUE THREAD

**Issue by tooomm** [openmediavault/openmediavault#767]
### Description of issue/question
Normally, after boot, the current IP address of the OMV box should be displayed in the console if a screen is available.
In my case the MAC address of the network interface "enp3s0" is shown instead.

I use DHCP, and the server gets assigned an address correctly. The router shows the device in his list next to the IP as well. I can connect to the web GUI via host name or IP address.
The AsRock J4105-ITX mainboard has a single Realtek network interface. No WiFi card installed. IPv6 disabled.

### Versions report
OMV Usul 5.5.4-1 with backported kernel 5.6.0

**Comment by votdev** [comment]
What you think is a MAC address is the IPv6 address of the interface. It looks impossible that a MAC address is shown there because the data is delivered by SaltStack, see https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/issue/files/etc-issue.j2. 

You may validate this with running `salt-call grains.get ip_interfaces`.

Examples:
```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:1f:a1:50 brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.25/24 brd 192.168.121.255 scope global dynamic ens6
       valid_lft 3534sec preferred_lft 3534sec
    inet6 fe80::5054:ff:fe1f:a150/64 scope link 
       valid_lft forever preferred_lft forever
3: ens7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:64:08:93 brd ff:ff:ff:ff:ff:ff
    inet 192.172.16.28/24 brd 192.172.16.255 scope global dynamic ens7
       valid_lft 3534sec preferred_lft 3534sec
4: ens8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:33:77:74 brd ff:ff:ff:ff:ff:ff
    inet 192.172.16.25/24 brd 192.172.16.255 scope global ens8
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe33:7774/64 scope link 
       valid_lft forever preferred_lft forever

# salt-call grains.get ip_interfaces
local:
    ----------
    ens6:
        - 192.168.121.25
        - fe80::5054:ff:fe1f:a150
    ens7:
        - 192.172.16.28
    ens8:
        - 192.172.16.25
        - fe80::5054:ff:fe33:7774
    lo:
        - 127.0.0.1
        - ::1
```
![screenshot](https://user-images.githubusercontent.com/1897962/88040953-f6176180-cb49-11ea-9c12-7ca09206f17b.png)

**Comment by tooomm** [comment]
You are totally right, it's the local link (fe80:) IPv6 address! Not the MAC of course. 🙈 
I didn't know that is created anyway, even when IPv6 is disabled and not used.

However, It only shows that one address in a single line and no IPv4 address at all. Other than in your picture, I don't see several values for the same network interface. The salt-call and ifconfig commands show them.

Also, when I first experienced with this box and OMV, the DHCP IP(v4) address showed up there (and only that!), which is awesome and very handy! That's why came here and asked for help.
I've no clue why this isn't the case anymore after I reinstalled OMV and want to set it up for production now...

**Comment by votdev** [comment]
This is all a timing issue. The systemd unit to create the welcome message already waits for the network unit, but sometimes it took longer to configure the network.

**Comment by tooomm** [comment]
Unlucky, seems like it takes always too long for me then.

**Comment by ryecoaaron** [comment]
This only happens with dhcp and the chances your dhcp address changes is pretty rare (unless your system is off extended periods). Set a static dhcp address  on your router if it is.  And normally you can use the dns name.   I dont see why this is a problem.
