### ISSUE TITLE
cannot install on raspbery pi 4 ubuntu 64bit

### ISSUE THREAD

**Issue by mzramna** [openmediavault/openmediavault#768]
when installing to an raspberry pi 4 with the 64bit system it says it is not works on this architecture
probly because of the architecture ,there is any possibility to made this compatible?
since it can run all the softwares from armhf it could just be avaliable in this architecture in compatibility mode or anything like that

**Comment by ryecoaaron** [comment]
OMV on works with Debian.  OMV 5.x requires Debian 10 - https://forum.openmediavault.org/index.php?thread/28789-installing-omv5-on-raspberry-pi-s-armbian-sbc-s-i386-32-bit-platforms/

**Comment by mzramna** [comment]
I actually use Ubuntu on my raspberry pi with omv

**Comment by ryecoaaron** [comment]
But you shouldn't.  Ubuntu is not supported.

**Comment by yuriw** [comment]
raspbian OS works fine FYI

**Comment by williamgurzoni** [comment]
> I actually use Ubuntu on my raspberry pi with omv

Hey @mzramna, have you managed to install on your Ubuntu? I'm facing the same situation. Thank you.

**Comment by votdev** [comment]
> > I actually use Ubuntu on my raspberry pi with omv
> 
> Hey @mzramna, have you managed to install on your Ubuntu? I'm facing the same situation. Thank you.

OMV does not work on Ubuntu.
