### ISSUE TITLE
Feature request: support for SMART monitoring SAS drives.

### ISSUE THREAD

**Issue by Loki44** [openmediavault/openmediavault#769]
Currently, OMV doesn't seem to support SMART monitoring with SAS drives, when it is enabled on them it still shows a grey ball under "status".  It would be good if it could support SAS drives.  I understand they don't report attributes in the same way as ATA drives, but most will report an overall "SMART Health Status" through smartctl.

**Comment by votdev** [comment]
Without the hardware for testing i can not implement that feature. Because of that someone else from the community with the hardware and knowledge of OMV must contribute this feature.

**Comment by votdev** [comment]
May it be possible that smartmontools does not support SAS drives? See https://www.smartmontools.org/wiki/FAQ#MySCSISASdriveisnotinthesmartctlsmartddatabase

**Comment by skyajal** [comment]
smartmontools does work with SAS drives. I tested this on my server with SAS drives using JBOD mode on the raid controller. Below is an example query for info on a drive.

# smartctl -i /dev/sde
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.4.0-42-generic] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               SEAGATE
Product:              ST4000NM0023
Revision:             0003
Compliance:           SPC-4
User Capacity:        4,000,787,030,016 bytes [4.00 TB]
Logical block size:   512 bytes
LU is fully provisioned
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000c50057fdc36f
Serial number:        xxxxxxxxxxxxxxxxxx
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Wed Jul 22 10:16:04 2020 EDT
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Enabled

**Comment by votdev** [comment]
Have you done this on the OMV system? I'm asking because on Debian 10 `smartmontools` in at [6.6](https://packages.debian.org/buster/smartmontools).

**Comment by votdev** [comment]
OMV uses `smartctl -x /dev/xxx` to get the information. If there are no `SMART Attributes Data Structur` then it is not possible to display such information or the current disk state (which is calculated based on these attribute values). As far as i remember those attributes are not delivered by SAS drives.

**Comment by ryecoaaron** [comment]
@votdev You are correct. smartctl (even 7.1) does not show the smart attributes.

**Comment by skyajal** [comment]
Sorry, no it was not done on an OMV system. As you may of saw, I am using smartctl 7.1. I did a quick test and using -x does work for SAS but it doesn't return SMART Attributes Data Structure

**Comment by votdev** [comment]
> Sorry, no it was not done on an OMV system. As you may of saw, I am using smartctl 7.1. I did a quick test and using -x does work for SAS but it doesn't return SMART Attributes Data Structure

Then it will not work for SAS drives because as already mentioned various values from the `Attributes Data Structure` are used to assess the drive state. See https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/storage/smartinformation.inc#L483 for more information.

**Comment by Loki44** [comment]
Yes, smartctl does work with SAS, but doesn't include a data structure like it does with SATA, as SCSI drives don't report in that format.

(it's worth noting that there's a bug with smartctl 7.1 that means not all data from some SAS drives is reported, this doesn't exist in 7.0 and below, and it's been fixed in dev.)

Thanks for the links votdev, I think the temperature part is a great example, as if there's no data structure it falls back to finding the data elsewhere.  I'm suggesting that OMV should do a similar thing with with overall drive health, if there is no data structure found, it should fallback to looking for the `SMART Health Status: OK` or similar line.

This is an example from my OMV installation, but I'm running the proxmox kernel so it's version 7.0:
```
smartctl 7.0 2018-12-30 r4883 [x86_64-linux-5.4.44-2-pve] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               SEAGATE
Product:              ST2000NMCLAR2000
Revision:             PS10
Compliance:           SPC-3
User Capacity:        2,000,398,934,016 bytes [2.00 TB]
Logical block size:   512 bytes
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000c50055b442d3
Serial number:        xxx
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Mon Jul 27 19:29:08 2020 BST
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Disabled or Not Supported
Read Cache is:        Enabled
Writeback Cache is:   Enabled

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

Current Drive Temperature:     31 C
Drive Trip Temperature:        68 C
```

There's more but that is the important part.

**Comment by Loki44** [comment]
Great, thanks.
