### ISSUE TITLE
OMV produces an error when upgrading from 4.1.3-1 to 4.1.4-1

### ISSUE THREAD

**Issue by petaramesh** [openmediavault/openmediavault#77]
Hello,
I upgraded this morning using OMV's web interface, from OMV 4.1.3-1 to 4.1.4-1.

It spit an error about an RPC issue which I hadn't seen in any previous upgrades.

So I checked the syslog, and found : 

avril 01 08:43:42 nasgul omv-engined[23403]: PHP Fatal error: Uncaught Error: Class 'OMV\Rpc\BgStatusFile' not found in /usr/share/openmediavault/engined/rpc/exec.inc:88
                                             Stack trace:
                                             #0 [internal function]: OMVRpcServiceExec->getOutput(Array, Array)
                                             #1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
                                             #2 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getOutput', Array, Array)
                                             #3 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Exec', 'getOutput', Array, Array, 1)
                                             #4 {main}
                                               thrown in /usr/share/openmediavault/engined/rpc/exec.inc on line 88
avril 01 08:43:47 nasgul omv-engined[23541]: PHP Fatal error: Uncaught Error: Class 'OMV\Rpc\BgStatusFile' not found in /usr/share/openmediavault/engined/rpc/exec.inc:88
                                             Stack trace:
                                             #0 [internal function]: OMVRpcServiceExec->getOutput(Array, Array)
                                             #1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
                                             #2 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getOutput', Array, Array)
                                             #3 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Exec', 'getOutput', Array, Array, 1)
                                             #4 {main}
                                               thrown in /usr/share/openmediavault/engined/rpc/exec.inc on line 88

Hope this helps.

Kind regards.

**Comment by donhwy** [comment]
Try running " omv-initsystem".

**Comment by votdev** [comment]
The problem should be gone after the omv-engined process has been restarted (which is done during the update). Sometimes it happens that not all child processes are killed, so i assume this happens here.
