### ISSUE TITLE
Could the NAS on OMV be accessed by cell phone like a folder?

### ISSUE THREAD

**Issue by ardeal** [openmediavault/openmediavault#770]
Hi,

I have already run OpenMediaVault on my VMware.
I could access the IP address on my Windows browser, and could see all configurations on the browser page.

Could I access the NAS of storage on OMV like a folder(I would like to write/read the files in the folder)?

Thanks,
Ardeal

**Comment by votdev** [comment]
Use an app that supports NFS, SMB or FTP and your fine.

**Comment by ardeal** [comment]
@votdev ，

Thank you!

is there any Android APP recommended?

**Comment by jes1417** [comment]
For Android I use FX file explorer
https://play.google.com/store/apps/details?id=nextapp.fx
