### ISSUE TITLE
OMV-Extras icon is the only one with non-transparent background

### ISSUE THREAD

**Issue by tooomm** [openmediavault/openmediavault#771]
### Description of issue/question
![omve](https://user-images.githubusercontent.com/9874850/88276103-cc437380-ccde-11ea-8514-8538f6f7e00a.png)
Spotted this on Firefox 78.0.2 (Windows) and mobile Safari.

Or is this something to report at https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg?

### Steps to reproduce issue
Click on the `Home` icon.

### Versions report
5.5.4-1

**Comment by ryecoaaron** [comment]
This belongs here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues

**Comment by tooomm** [comment]
Moved.
