### ISSUE TITLE
Improvement - centralize scheduled tasks 

### ISSUE THREAD

**Issue by yuriw** [openmediavault/openmediavault#772]
@votdev 

It feels that scheduled tasks are not centralized at the moment in consistent manner.

For example the backup plugin adds a line into Scheduled Tasks tab
But Rsync jobs don't do it and it's unclear when rsync tasks will run.

Please consider centralizing all schedule related items under the same umbrella, say Scheduled Tasks tab

Thx

**Comment by ryecoaaron** [comment]
That is up to the plugin.  The backup plugin is one of the few plugins that adds a scheduled job like that.  And some things like rsync or rsnapshot are much more complicated and would not fit in the scheduled jobs tab.

**Comment by yuriw** [comment]
Given I don't know much internal details, but then if rsync can't be added to Scheduled Tasks tab, then its own page

![image](https://user-images.githubusercontent.com/3876474/88315021-a0b68e00-ccca-11ea-8e74-92f0363b51d1.png)

should include information about schedules, time, min etc

So I guess if "centralizing" is not an option, then maybe decentralize will work ?

**Comment by votdev** [comment]
OMV follows the concept that the configuration options should be there where they belong to, that means e.g. all rsync related options should be located under the menu rsync, same for FTP, SMB, anti-virus, ...

**Comment by yuriw** [comment]
As long as we have consistency :)

**Comment by rabelux** [comment]
Would it be possible to add a scheduling-column to rsync like there is in scheduled jobs?

**Comment by yuriw** [comment]
@rabelux related #793

**Comment by rabelux** [comment]
Already left a thumbs-up there.
But #793 talks about history, which is different to the schedule that better fits here

**Comment by votdev** [comment]
> Would it be possible to add a scheduling-column to rsync like there is in scheduled jobs?

Done in `openmediavault 5.5.10`, see https://github.com/openmediavault/openmediavault/commit/1e182c27a8188dcf6d45bcda1589c3ba51988e9d.

**Comment by rabelux** [comment]
Awesome, thanks!

**Comment by mi-hol** [comment]
@yuriw @rabelux can this be closed?

**Comment by yuriw** [comment]
up to @votdev

**Comment by votdev** [comment]
I'm struggling because the suggested behavior is against the design and concept of OMV where all configuration pages are below the main navigation node of a service.
