### ISSUE TITLE
Salt error installing OMV v 5.5.5.1 - workaround found but unsure of cause

### ISSUE THREAD

**Issue by mjnaylor8** [openmediavault/openmediavault#775]
### apt-get install openmediavault error 
ModuleNotFoundError: No module named 'distro'

### Steps to reproduce issue
(Include debug logs if possible and relevant.)
This seems to be linked to an error in the install of salt or python - maybe only my environment.
I checked and distro is available and in /usr/local/lib/python3.7/site-packages
Salt is running from /usr/lib/python3/dist-packages when run from OMV
I could not get the salt-minion service running either for the same missing distro package
I checked the python os path and it includes /usr/local/lib/python3.7/site-packages

Workround was to copy the distro.py from /usr/local/lib/python3.7/site-packages to /usr/lib/python3/dist-packages

apt-get then threw another error
Setting up Salt environment ...
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3001', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 466, in salt_call
    import salt.cli.call
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 6, in <module>
    import salt.cli.caller
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 18, in <module>
    import salt.loader
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 34, in <module>
    import salt.utils.event
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 72, in <module>
    import salt.payload
  File "/usr/lib/python3/dist-packages/salt/payload.py", line 19, in <module>
    import salt.transport.frame
  File "/usr/lib/python3/dist-packages/salt/transport/frame.py", line 8, in <module>
    import salt.utils.msgpack
  File "/usr/lib/python3/dist-packages/salt/utils/msgpack.py", line 57, in <module>
    Packer = msgpack.Packer
NameError: name 'msgpack' is not defined

I then installed msgpack-pythion using pip3.
Same error occurred

so I copied msgpack from /usr/local/lib/python3.7/site-packages to /usr/lib/python3/dist-packages

reran the apt-get install and all now OK.

Is the error my system?

**Comment by ryecoaaron** [comment]
How did you install OMV?  Was it on Debian 10?  You should never have to use pip.

**Comment by mjnaylor8** [comment]
Hi.  Yes Debian 10.  Installed originally using the upgrade from 4-->5 here https://forum.openmediavault.org/index.php?thread/27909-omv-5-0-finally-out/&postID=219830#post219830 (or a variation thereof)
I only used pip as a way of getting round the issue.  Prior updates from 5.5.3 to 5.5.4 was fine (on 14th July).
I have been doing some python development on the same box so wondering if I have somehow "upset" the python paths somewhere.... but everything else seems to be working fine.

**Comment by ryecoaaron** [comment]
It is very likely you caused the issue if you are doing python dev on the box.  Are you not using virtualenv?

**Comment by mjnaylor8** [comment]
Hi Aaron -  :-)- I am using venv but wanted to debug the cause of this as not normally sloppy and just want to get to root cause!

**Comment by mjnaylor8** [comment]
Solved.
PYTHONPATH was not set correctly.
Removed manually installed items in /usr/lib/python3/dist-packages and reran apt-get install --reinstall openmediavault and all worked OK.
Aaron thanks for your time ..... sorry if I wasted some of it!
