### ISSUE TITLE
Web Gui not responding.

### ISSUE THREAD

**Issue by SupperCraft5000** [openmediavault/openmediavault#78]
When i save a setting in the web gui than there is a communication failure every time.

http://prntscr.com/izpklb
http://prntscr.com/izpksr
http://prntscr.com/izpl1s

**Comment by votdev** [comment]
Please execute the following CLI commands to identify the problem:
```
# monit stop omv-engined
# omv-engined -d -f
```
After that repeat your UI actions and check the console output for errors.

**Comment by NeroBurner** [comment]
@damianperera please write down how you fixed it. Then everyone with the same problem can fix it too when stumbling about this issue. Thanks in advance

**Comment by damianperera** [comment]
@NeroBurner my issue was directly related to filesystems and was documented by another user in this [thread](https://forum.openmediavault.org/index.php/Thread/19231-communication-failure/ ) and raised in the previous [bug tracker](http://bugtracker.openmediavault.org/view.php?id=1796) (deprecated). Unfortunately I don't remember how I fixed it, but I might be able to help out here.

@SupperCraft5000 a communication failure in OMV generally occurs when the OMV frontend was not able to execute a linux command successfully (either the command fails or a timeout occurs). If you can login to the CLI of your OMV instance and execute the command you were trying to apply in the web app, you will be able to see more detailed a info/error output.

You can also directly view the console output via the CLI by following the procedure outlined by @votdev.
