### ISSUE TITLE
The method 'setPassword' does not exist for the RPC service 'WebGui'.

### ISSUE THREAD

**Issue by HannesJo0139** [openmediavault/openmediavault#780]
Fresh OMV5 install for testing purposes. 
1. Installed OMV
2. Pulled updates
3. Installed OMV Extras
4. Tried to change admin passwort via webgui the common way.

Getting Error "The method 'setPassword' does not exist for the RPC service 'WebGui'."
`Fehler #0:
OMV\HttpErrorException: The method 'setPassword' does not exist for the RPC service 'WebGui'. in /usr/share/php/openmediavault/rpc/rpc.inc:91
Stack trace:
#0 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('WebGui', 'setPassword', Array, Array, 1)
#1 {main}`

**Comment by ryecoaaron** [comment]
Did you clear your browser cache?

**Comment by HannesJo0139** [comment]
Should have tried that before -.-
