### ISSUE TITLE
Version 5.5.7: Fresh install error in network configuration with 'slaves' property

### ISSUE THREAD

**Issue by pandabear41** [openmediavault/openmediavault#782]
### Description of issue/question
Getting an error with a fresh install of OMV (after patching) and I can't seem to solve it.
I am not using bonding, but it is still giving error. I have tried doing `omv-firstaid`. Tried resetting config to default. Nothing seems to work.

ERROR:
```
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run collectd 2>&1' with exit code '1': debian:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.collectd.plugins.interface' failed: Jinja error: slaves: The value '' doesn't match the pattern '^(((eth|venet|wlan)\d+|(en|veth|wl)\S+|(bond)\d+)(\.\d+)?,)*((eth|venet|wlan)\d+|(en|veth|wl)\S+|(bond)\d+)(\.\d+)?$'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 400, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 21, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 82, in get_by_filter
    objs = db.get_by_filter(id_, openmediavault.config.DatabaseFilter(filter_), **kwargs)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 125, in get_by_filter
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 695, in execute
    self._response = self._elements_to_object(elements)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 473, in _elements_to_object
    obj.validate()
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 235, in validate
    self.model.validate(self.get_dict())
  File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 200, in validate
    self.schema.validate(data)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 170, in validate
    self._validate_type(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 224, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 195, in _validate_type
    self._validate_object(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 300, in _validate_object
    self._check_properties(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 508, in _check_properties
    self._validate_type(value[propk], propv, path)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 224, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 204, in _validate_type
    self._validate_string(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 275, in _validate_string
    self._check_pattern(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 385, in _check_pattern
    % (value, schema['pattern']),
openmediavault.json.schema.SchemaValidationException: slaves: The value '' doesn't match the pattern '^(((eth|venet|wlan)\d+|(en|veth|wl)\S+|(bond)\d+)(\.\d+)?,)*((eth|venet|wlan)\d+|(en|veth|wl)\S+|(bond)\d+)(\.\d+)?$'.

; line 21

---
[...]
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

{% set interfaces = [] %}
{% for interface in salt['omv_conf.get_by_filter'](    <======================
  'conf.system.network.interface',
  {'operator': 'or', 'arg0': {'operator': 'stringEquals', 'arg0': 'type', 'arg1': 'ethernet'}, 'arg1': {'operator': 'stringEquals', 'arg0': 'type', 'arg1': 'wifi'}}) %}
{% set used_by = salt['omv_conf.get_by_filter'](
  'conf.system.network.interface',
  {'operator': 'stringContains', 'arg0': 'slaves', 'arg1': interface.devicename}) %}
[...]
--- in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusU3...', '/tmp/bgoutputxf...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

### Steps to reproduce issue
1. Install OMV version 5.3.9 via iso in Virtualbox (this might work with other platforms).
1a. (optional) Login to web interface, create some shared folders. (Everything works fine)
2. Update OMV to version 5.5.7.
3. Reboot
4. Login to web interface and safe some config. (or do any omv command that pushes config).

**Comment by votdev** [comment]
> (after patching)

What does this mean? Did you modify the file `/etc/openmediavault/config.xml`manually?

> (or do any omv command that pushes config).

What are those commands? Are they executed via CLI?

**Comment by votdev** [comment]
With openmediavault 5.5.7 the configuration object verification is more strict. Missed to update the network interface datamodel.

**Comment by gordonf130** [comment]
Is this a fix for omv on a raspberry pi running raspberry light os. If so what are the commands and dose it need to be a fresh install of omv. Because at the moment is has no Internet to download any new packages

**Comment by gordonf130** [comment]
I am new to all of this so can someone please explain the steps of fixing this

**Comment by votdev** [comment]
> Is this a fix for omv on a raspberry pi running raspberry light os. If so what are the commands and dose it need to be a fresh install of omv. Because at the moment is has no Internet to download any new packages

If you can not assign an IP manually to get internet access (Google will help you here), then you need to reinstall it from scratch.

**Comment by gordonf130** [comment]
> > Is this a fix for omv on a raspberry pi running raspberry light os. If so what are the commands and dose it need to be a fresh install of omv. Because at the moment is has no Internet to download any new packages
> 
> If you can not assign an IP manually to get internet access (Google will help you here), then you need to reinstall it from scratch.

Is the install scrip updated to install 5.5 8

**Comment by ryecoaaron** [comment]
The install script installs the latest always.

**Comment by gordonf130** [comment]
pi@raspberrypi:~ $sudo wget -O - https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/installScript/master/install | sudo
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] file ...
--2020-08-14 11:33:26--  https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/installScript/master/install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.60.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.60.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14532 (14K) [text/plain]
Saving to: ‘STDOUT’

-                                                             0%[                                                                                                                                         ]       0  --.-KB/s    in 0s


Cannot write to ‘-’ (Broken pipe).

**Comment by pandabear41** [comment]
@votdev Thank you for fixing. Sorry if my issue wasn't super clear on what was happening.
