### ISSUE TITLE
 Firewall doesn't allow the "All" Protocol option

### ISSUE THREAD

**Issue by yllekz** [openmediavault/openmediavault#786]
### Description of issue/question
Hey there, I've noticed what appears to be a bug in the OMV firewall options. You are never allowed to select "All" in the protocol dropdown, it says it's a disallowed option despite being in a multiple-choice list.

### Steps to reproduce issue
(Include debug logs if possible and relevant.)
Example rule scenario where I cannot select "all" as the protocol:
![image](https://user-images.githubusercontent.com/28446638/90304620-aa758080-de87-11ea-9a2b-958dcfd2e89e.png)

### Versions report
OMV v 5.5.8-1 (Usul)

**Comment by votdev** [comment]
Protocol `All` does not work if you specify a source or destination port.
```
# iptables -A INPUT -p all --source 172.16.10.200/32 --sport 1194:65535 --destination 172.16.10.210/32 --dport 1194 -j DROP
iptables v1.8.2 (nf_tables): unknown option "--sport"

# iptables -A INPUT -p all --destination 172.16.10.210/32 --dport 1194 -j DROP
iptables v1.8.2 (nf_tables): unknown option "--dport"
```
You will find many related posts using Google.
