### ISSUE TITLE
Read-only users or groups are not used in proftp config

### ISSUE THREAD

**Issue by Marsup** [openmediavault/openmediavault#789]
### Description of issue/question

I believe there's an issues with both ifs [here](https://github.com/openmediavault/openmediavault/blob/aa329e2547cd392b28f5f070ca466fb367ea42b6/deb/openmediavault/srv/salt/omv/deploy/proftpd/modules/files/mod_core.j2#L142-L147) as it will only work if you have at least one user or group with perms 7, not if your list only consists of perms 5 (which is my case). I believe those ifs should concatenate the lists before checking the length.

### Steps to reproduce issue
I believe you just need to only include a single group with read-only permissions on a share.

### Versions report
5.5.8-1

**Comment by votdev** [comment]
You're right, `AllowUser OR ...` configuration line already concats the lists. Seems the concatenation was missed in the `if` clause.
