### ISSUE TITLE
Feature request - config files based backup

### ISSUE THREAD

**Issue by yuriw** [openmediavault/openmediavault#791]
This is inspired by `pfSense project` backup feature.
https://docs.netgate.com/pfsense/en/latest/backup/configuration-backup-and-restore.html?highlight=restore

In case of a catastrophic failure, assuming that the latest `config.xml` file with full configuration (including Acme certificates(!) etc...) was saved, it very simple to re-installed a fresh software and restore full configuration.

Please consider this for future versions as I am sure it will benefit lots of users.  Current solution to do a full disk dump and then restore is extremely time consuming !

@votdev pls consider

**Comment by votdev** [comment]
I think about that feature and how to implement it since a very long time. If OMV does not support plugins OMV5 would be the version where this feature could be implemented as easy because with the SaltStack based configuration backend it is really simple to deploy the configuration with one command. BUT, plugins make it currently impossible to implement this feature. Imagine the following scenario: The user creates a backup with plugin `foo` at version 5.1. The plugin implements a new feature in 5.2 which requires a database migration. Time goes by and we are at version 5.5 with another bunch of database migrations. Now the user wants to restore the configuration backup... The problem now is OMV does not know that the configuration section generated by the plugin is for 5.1 and because of that it can not run the migration scripts from 5.1 -> 5.5. I don't see such a feature in the pfSense code, it simply copies the uploaded file to the target location. 

* https://github.com/pfsense/pfsense/blob/master/src/usr/local/www/uploadconfig.php#L50
* https://github.com/pfsense/pfsense/blob/b55b5c18c2ba158f35a50d5ad5d2d7ebcc303d6c/src/etc/inc/config.lib.inc#L702

That's trivial, but that does not work for OMV. At the current state there is no way to implement that feature how i want to see it and how users expect it how it works. The database needs a complete rewrite to support that meta-information that is needed for the migration or a more or less complex import/export format that will append that information. I think that should be the way to go because other solutions might break the plugin compatibility.

**Comment by yuriw** [comment]
I don't know much about pfsense backup internals.  But I think with plugins pfsense is also having challenges.

During the last major upgrade I was a victim of it.  They prompted somewhere that plugins have to upgraded after the major upgrade because of some PHP changes; and I and bunch of other users of cause, missed it.  
It was very painful to lose the router ! But after a little time and restore it worked like a charm.

That's why I am suggesting this.

Maybe some things can be achieved not only by doing perfect coding, but by process, warnings and pop up boxes ?

**Comment by votdev** [comment]
> Maybe some things can be achieved not only by doing perfect coding, but by process, warnings and pop up boxes ?

That's not how i'm coding and how i maintain the OMV project. I try to implement only perfect solutions.

**Comment by votdev** [comment]
For the moment the easiest solution is to copy the backup file to `/etc/openmediavault/config.xml` and run `omv-salt stage run all`. This will deploy everything and bring the system into the correct state. This only works if there are no database/datamodel changes since the backup.

**Comment by ryecoaaron** [comment]
You could always use the openmediavault-backup plugin that copies the entire os drive. not perfect either but a good start

**Comment by yuriw** [comment]
> You could always use the openmediavault-backup plugin that copies the entire os drive. not perfect either but a good start

Very long process :(

**Comment by yuriw** [comment]
> For the moment the easiest solution is to copy the backup file to `/etc/openmediavault/config.xml` and run `omv-salt stage run all`. This will deploy everything and bring the system into the correct state.

Is it reliable ?

> This only works if there are no database/datamodel changes since the backup.

How do users know that ?

*** I am not sure if I want to try it on live system...

**Comment by ryecoaaron** [comment]
> Very long process

only to restore but more accurate than restoring the config could ever be.  if you are looking for something to roll back mistakes, install the OS on btrfs and take scheduled snapshots.

**Comment by yuriw** [comment]
Maybe another options might-be be to allow users to export all settings from OVM in some form (TXT, XML or else) so they are able to manually recreate them later.  At least it will give some piece of mind.

**Comment by that-coding-human** [comment]
I think every component should have an own config backup. The core OMV with the config.xml and the plugins others. What OMV could offer is an interface for plugins to trigger the export of settings in the UI and write them to a folder. 
The export of all settings can then be triggered centralized from OMV, while the exact handling of what settings get exported and how, is left to the plugin developers. 
When recovering from a crash by redeploying, one can first rebuild OMV, then the plugins, and import the settings for the plugins. This way the implementation of how to import/export the plugin configs, can be left to the plugin developers, and does not cause a mess of dependencies that have to be covered by core OMV. 

Of course some plugins will support such an interface, some others will not. But the opportunity exists. 

An important aspect for me is that the export (and maybe import) of the configurations can be triggered by command line. So you can setup a job that regularly exports configs and safes them somewhere. So you are ready to recover.

By the way ... I think saltstack, and how it is used here, is a very good choice for automating the deployment of OMV. Keep up the good work!

**Comment by ryecoaaron** [comment]
most of the plugins that people want to backup are plugins that depend on filesystems or on share folders which depend on filesystems.  If the filesystem and its associated mntent entry and/or the shared folders do not exist, then restoring the config is almost worthless.

**Comment by that-coding-human** [comment]
> 
> 
> most of the plugins that people want to backup are plugins that depend on filesystems or on share folders which depend on filesystems. If the filesystem and its associated mntent entry and/or the shared folders do not exist, then restoring the config is almost worthless.

Yes. This is true. By using my approach from above this can be covered. The user can decide if he wants to recover this information as well, or just the core OMV settings. Also one could backup core and plugin, then configure the plugin backup config manually to adjust it to the new environment. 
Basically every successful recovery relies on the environment to match the requirements of the backup (e.g. file paths). If it does not match, the user needs to adjust the backup data.

**Comment by votdev** [comment]
The feature is on the ToDo list for one of the next releases.

**Comment by lessload** [comment]
Export and Import config should be the one of main feature but OMV doesn't have it. Why not learn from TrueNAS or OpenWRT.

**Comment by votdev** [comment]
> Export and Import config should be the one of main feature but OMV doesn't have it. Why not learn from TrueNAS or OpenWRT.

Have you read my [comment](https://github.com/openmediavault/openmediavault/issues/791#issuecomment-676765504)? If it would be trivial, a export/import feature would be implemented already. But right now there are too many things that are not under control of OMV to implement a 100% working solution. I do not invest my private time in a solution that might cause troubles that will cost me my private time again by commenting on problems in the forum or here. If you think you are more clever then mine, please feel free to contribute an implementation via PR.
