### ISSUE TITLE
Changed my router IP address and now OMV cannot connect to the internet

### ISSUE THREAD

**Issue by dushyantahuja** [openmediavault/openmediavault#792]
### Description of issue/question
Hi all, I've recently had to change my network settings so that the router IP address is now [192.168.78.1](https://192.168.78.1) (was previously [192.168.1.1](https://192.168.1.1)). I've set up the network interface using the web front-end and can access the OMV server using it's new IP address [192.168.78.2](https://192.168.78.2) (both front-end and ssh); however, when I try to run ping [1.1.1.1](https://1.1.1.1) from ssh, I get the following error:

>`From 192.168.1.61 icmp_seq=1 Destination Host Unreachable`

"ip a" shows:

 

>`2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000`  
>  
>`link/ether 84:39:be:67:c2:f5 brd ff:ff:ff:ff:ff:ff`  
>  
>`inet 192.168.78.2/24 brd 192.168.78.255 scope global dynamic enp1s0`  
>  
>`valid_lft 86218sec preferred_lft 86218sec`  
>  
>`inet 192.168.1.61/24 brd 192.168.1.255 scope global noprefixroute enp1s0`  
>  
>`valid_lft forever preferred_lft forever`  
>  
>`inet6 fe80::70d9:49bc:a35f:6385/64 scope link`   
>  
>`valid_lft forever preferred_lft forever` 

[192.168.1.61](https://192.168.1.61) is my old IP address and I'm not able to find any way to remove it from the settings. Please help

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

Change the IP address of the router

### Versions report
5.5

**Comment by dushyantahuja** [comment]
Can someone please help - I don't want to reformat my server.

**Comment by ryecoaaron** [comment]
You would probably get more help if you posted on the forum - https://forum.openmediavault.org/

**Comment by dushyantahuja** [comment]
Found the issue - /etc/dhcpcd.conf had the IP address defined.

```
systemctl stop dhcpcd
systemctl disable dhcpcd
```

disabled the extra IP addresses I was getting

**Comment by votdev** [comment]
Hmmm, `dhcpcd` is not installed by OMV.

**Comment by ryecoaaron** [comment]
and my install script uninstalls dhcpcd.

**Comment by dushyantahuja** [comment]
not sure how or when it was installed. Though didn't get uninstalled when I upgraded to v5.

**Comment by OrangeManLives** [comment]
I resolved this by editing the /etc/netplan/20-openmediavault-eth0.yaml file which defined the network settings.
