### ISSUE TITLE
Feature request - history for scheduled jobs

### ISSUE THREAD

**Issue by yuriw** [openmediavault/openmediavault#793]
Currently there is no historical information about scheduled jobs or any other plugins the are using schedulers (power management, rsync etc)

Please consider such a feature for future releases.

**Comment by mi-hol** [comment]
Are the instruction in forum to add logs files correct?
https://forum.openmediavault.org/index.php?thread/15438-guide-add-custom-log-files-to-webui/

**Comment by votdev** [comment]
> Are the instruction in forum to add logs files correct?
> [forum.openmediavault.org/index.php?thread/15438-guide-add-custom-log-files-to-webui](https://forum.openmediavault.org/index.php?thread/15438-guide-add-custom-log-files-to-webui/)

They should be correct for OMV5, otherwise https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/usr/share/openmediavault/engined/inc/90logfilespec.inc should be used as reference.

**Comment by mi-hol** [comment]
Any suggestion how to fix the the apparently incorrectly defined date format string encountered in [this forum post](https://forum.openmediavault.org/index.php?thread/39429-solved-add-additional-log-file-to-the-web-gui/&postID=289154#post289154) ?
