### ISSUE TITLE
i did run the update and evernything is gone

### ISSUE THREAD

**Issue by icf20** [openmediavault/openmediavault#794]
### Description of issue/question

every single file appears removed running du over ssh
```
du -sh /nas
17M	/nas

```

ZFS gui still show the files in there

![image](https://user-images.githubusercontent.com/17784575/90992391-c8419480-e5af-11ea-88d4-2288edde9c85.png)

### Steps to reproduce issue

run update from GUI

### Versions report
dpkg -l | grep openmediavault
ii  openmediavault                   5.5.8-1                             all          openmediavault - The open network attached storage solution
ii  openmediavault-diskstats         5.0.5-1                             all          openmediavault disk monitoring plugin
ii  openmediavault-flashmemory       5.0.7                               all          folder2ram plugin for OpenMediaVault
ii  openmediavault-keyring           1.0                                 all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg      5.3.4                               all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-resetperms        5.0                                 all          Reset Permissions
ii  openmediavault-zfs               5.0.5                               amd64        OpenMediaVault plugin for ZFS

**Comment by votdev** [comment]
This looks to me like a ZFS issue.

**Comment by icf20** [comment]
@votdev my bad i totally forgot to update

1 after the update the ZFS is not mounted correctly in my case /nas

2 i deleted the /nas folder after halting every plugin/app/ using that folder

3 reboot OMV

4 log-in and go to ZFS there i got the typical warning about changes ".... apply" so i did hit apply gui reloads and ZFS got mounted correctly on /nas

5 start everything from point 2
