### ISSUE TITLE
Rsync of non-shared folder

### ISSUE THREAD

**Issue by rabelux** [openmediavault/openmediavault#796]
### Description of issue/question
Hey guys, I would like use rsync to backup my "photos"-folder and came across a few barriers within OMV.

First and major issue: "photos" is within the "media"-folder and I only want to sync this subfolder of the shared "media"-folder.
This issue has also been posted in the [forums](https://forum.openmediavault.org/index.php?thread/32036-rsync-to-non-shared-folder/&postID=236111#post236111) by a different user and didn't get a response.

My ideas of solving this:
1. Edit `/var/lib/openmediavault/cron.d/rsync-xyz` and revoke rights for omv
  I guess this will lead to errors in the web-interface so maybe that's not the best solution
2. Copy that scipt to a custom location and create a cron-job within OMV
 Question: Would that work? I mean I would like to have the benefits of OMV which means a status-led when logging in and a notification/mail if something goes wrong
3. Beg you(@votdev) to allow entering a string _instead of_ or _in addition to_ the target/source-dropdown
4. If possible, edit the omv-configuration and tell it not to rebuild rsync-files
5. Ask for an _**advanced-mode**_, where users can enter the rsync-command themselves
5.1 My command that works in a shell is `rsyinc -ayzce "ssh -p 1234" --stats --delete-delay /srv/dev-disk-by-label-HDD1/Media/Photos/ user@server:/target/folder/`
So for me it would be easier to just enter this instead of fiddling around with the gui
5.2 Maybe also add the option to choose a user this command is executed by. I have set up ssh with private key that is stored in my user-profile. I know that I can create a key with OMV it's just that it I have to dig into that again whereas it would just work if executed as my user.

I guess solution 5 would be my favourite followed by No. 3.

Thanks in advance,
Rabelux

### Versions report
5.5.8-1 usul

**Comment by ryecoaaron** [comment]
Just create another shared folder for the photos subfolder.  Then you can use the rsync plugin as designed.

**Comment by rabelux** [comment]
> 
> 
> Just create another shared folder for the photos subfolder. Then you can use the rsync plugin as designed.

Thanks for your quick response!
When adding that subfolder I have to specify permissions, although I don't want to mess up existing permissions (ACLs). Is there a solution for that?

**Comment by ryecoaaron** [comment]
If you set the permissions to the same setting as the parent shared folder, there shouldn't be a problem.  The sharedfolder won't be created if it already exists.  It will change the owner to root:users and set the setgid bit but it won't be recursive.  So, if that is the wrong permissions, change it back to what you need and it should be a one time fix.

**Comment by rabelux** [comment]
Ok good to know that there's a way to solve this.
I'll still wait for a reply from Volker what he thinks about this, as the shared-folders-within-shared-folders-thing doesn't sound like an elegant solution to me.

**Comment by yuriw** [comment]
I used rsync command line and add it as scheduled job to achieve this.

**Comment by votdev** [comment]
The concept of OMV related to shared folder is as it is. Subfolders are the key to get it working as you would see it. There is no need for `advanced`settings.

**Comment by rabelux** [comment]
Just an update about the solution I found:
There are include/exclude options available for rsync so adding the extra option `--exclude-from /pathtofile` is a workaround I'm quite happy with
The referenced file contains all foldernames I don't want to be synced, one per line
