### ISSUE TITLE
Can't change admin password with omv-firstaid

### ISSUE THREAD

**Issue by Systemac** [openmediavault/openmediavault#797]
I just upgrade omv4 to omv5 with this tutorial : https://y-news.info/mettre-a-jour-openmediavault-4-version-5/
but i can't login to the UI, Even using the utility omv-firstaid...

and if i want to change web port interface, i have the following error : "failed: Jinja error: tls: Invalid value \'0\',"

**Comment by votdev** [comment]
> and if i want to change web port interface, i have the following error : "failed: Jinja error: tls: Invalid value '0',"

This happens because the database has not been migrated, something went wrong during your upgrade. Try to run `omv-confdbadm migrate "conf" 5.0.0` to fix this.

**Comment by Systemac** [comment]
Thank's for the reply.

for the auth.log, i just found that :

"Aug 27 18:27:33 nas omv-engined[10933]: pam_unix(openmediavault:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=admin
Aug 27 18:27:36 nas openmediavault-webgui[10932]: Unauthorized login attempt from ::ffff:192.168.1.XX [username=admin, user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 OPR/70.0.3728.106]"

I clear the cache before retry...

**Comment by votdev** [comment]
You may check if the user `admin` is blocked. OMV will do that after 3 failed logins. You can use `omv-firstaid` to unblock an user.

**Comment by Systemac** [comment]
Lol....

I just see that 

![image](https://user-images.githubusercontent.com/7353752/91470359-e7347500-e894-11ea-8d4b-bda367d98aec.png)

same as admin does not exist...

**Comment by Systemac** [comment]
![image](https://user-images.githubusercontent.com/7353752/91470665-47c3b200-e895-11ea-83db-1491024d846c.png)

I need to find commad to list all the users of OMV  ;)

**Comment by votdev** [comment]
> Lol....
> 
> I just see that
> 
> ![image](https://user-images.githubusercontent.com/7353752/91470359-e7347500-e894-11ea-8d4b-bda367d98aec.png)
> 
> same as admin does not exist...

OMV does not create home dirs for users.

**Comment by Systemac** [comment]
Oh... Sorry...

So admin isn't blocked and exist in the list of the users

![image](https://user-images.githubusercontent.com/7353752/91471120-e94b0380-e895-11ea-8da5-023a081b513f.png)

**Comment by votdev** [comment]
I see the problem. The package update totally failed on your system, thus the database migration and system adaptions were not executed.

Simply run `usermod -a -G openmediavault-admin admin` to add the group `openmediavault-admin` to the user `admin`.

**Comment by Systemac** [comment]
Oh !!!

Thank's so much !!!!
