### ISSUE TITLE
Quotas are not configured after creating an ext4 file system

### ISSUE THREAD

**Issue by levtecaccess** [openmediavault/openmediavault#800]
When creating an ext4 file system, in /etc/fstab the file system is referenced with quotas enabled, however quotas are not configured after file system creation.
The command "quotacheck -u -g -c -m $devicefile" needs to be added to the RPC execution sequence if $type is ext4.

**Comment by votdev** [comment]
Can you please provide references that clearly describe this behavior. Are there any error messages in the logs that tell that there is a problem when `quotacheck` is not executed?

**Comment by levtecaccess** [comment]
After creating the file system on a new setup, the aquota.user and aquota.group files were not present.
After rebooting and running "systemctl status quota" i found that the service had failed to start because the quota files were missing.
I did not check the openmediavault logs but did look at the code when I got home.
The file system creation function does not contain any code that I could find for configuring the quota service for newly created file systems.
After some additional checking I found that there is additionally no code to run quotaoff prior to removing an ext4 file system.
Granted I haven't done a whole lot of digging, however I just tested a new installation in a VM and the same thing happened.
I will test my code additions tomorrow and see whether it makes a difference.

**Comment by votdev** [comment]
As said, OMV behaves like this since years without getting notice about problems. Please make sure this is a general issue and not only related to your system or Debian flavor (Rasbian, ...).

**Comment by votdev** [comment]
> The file system creation function does not contain any code that I could find for configuring the quota service for newly created file systems.

IMO there is no need to do that.

> After some additional checking I found that there is additionally no code to run quotaoff prior to removing an ext4 file system.

IMO there is no need to do that.

**Comment by levtecaccess** [comment]
After creating the file system, the fstab entry references the quota files, which don't get created unless created with quotachk or quotatool.
I'm not saying that if you come to later configure quotas for users and groups it won't work, my observations are simply that the creation of a file system referencing non-existant quota files is causing the quota service to fail when booting.
Granted it's not something I have observed prior to today, however now that I have observed it, it definitely would fall in the unwanted behavior category and should be considered a bug.
I can't say whether anyone else has observed this behavior or even bothered to take the time to look, but there is always a first.

**Comment by levtecaccess** [comment]
I aim to do some more testing, I expect the files are created with no problem after enabling quotas for an account.
To be clear, this should not be considered a bug in the quota system, rather a bug in the file system creation function.
After giving file system deletion some more thought, I agree that it would be unnecessary to run quotaoff prior to deletion since all resources previously using the file system will have already been removedd

**Comment by votdev** [comment]
> causing the quota service to fail when booting.

I can not confirm that.

```
root@omv5box:/home/vagrant# ls -alh /srv/dev-disk-by-label-wq/
total 40K
drwxr-xr-x 3 root root 4.0K Aug 29 23:47 .
drwxr-xr-x 7 root root 4.0K Aug 29 23:47 ..
-rw------- 1 root root 6.0K Aug 29 23:49 aquota.group
-rw------- 1 root root 7.0K Aug 29 23:49 aquota.user
drwx------ 2 root root  16K Aug 29 23:46 lost+found

root@omv5box:/home/vagrant# ls -alh /srv/dev-disk-by-label-woq/
total 24K
drwxr-xr-x 3 root root 4.0K Aug 29 23:46 .
drwxr-xr-x 7 root root 4.0K Aug 29 23:47 ..
drwx------ 2 root root  16K Aug 29 23:46 lost+found

root@omv5box:/home/vagrant# systemctl status quota
● quota.service - Initial Check File System Quotas
   Loaded: loaded (/lib/systemd/system/quota.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sat 2020-08-29 23:49:38 CEST; 1min 1s ago
     Docs: man:quotacheck(8)
  Process: 271 ExecStart=/usr/share/quota/quota-initial-check.sh (code=exited, status=0/SUCCESS)
 Main PID: 271 (code=exited, status=0/SUCCESS)

Aug 29 23:49:38 omv5box quota-initial-check.sh[271]: Checking quotas...done.

root@omv5box:/home/vagrant# journalctl -u quota.service 
-- Logs begin at Sat 2020-08-29 23:49:38 CEST, end at Sat 2020-08-29 23:50:23 CEST. --
Aug 29 23:49:38 omv5box quota-initial-check.sh[271]: Checking quotas...done.
```

**Comment by votdev** [comment]
After doing some more checks i can confirm now that the `quotaon` service fails at startup.
```
root@omv5box:/home/vagrant# systemctl status quotaon.service 
● quotaon.service - Enable File System Quotas
   Loaded: loaded (/lib/systemd/system/quotaon.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-08-30 00:04:53 CEST; 1min 33s ago
     Docs: man:quotaon(8)
  Process: 452 ExecStart=/sbin/quotaon -aug (code=exited, status=2)
 Main PID: 452 (code=exited, status=2)

Aug 30 00:04:53 omv5box systemd[1]: Starting Enable File System Quotas...
Aug 30 00:04:53 omv5box quotaon[452]: quotaon: cannot find /srv/dev-disk-by-label-woq/aquota.group on /dev/sdb1 [/srv/dev-disk-by-label-
Aug 30 00:04:53 omv5box quotaon[452]: quotaon: cannot find /srv/dev-disk-by-label-woq/aquota.user on /dev/sdb1 [/srv/dev-disk-by-label-w
Aug 30 00:04:53 omv5box systemd[1]: quotaon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 30 00:04:53 omv5box systemd[1]: quotaon.service: Failed with result 'exit-code'.
Aug 30 00:04:53 omv5box systemd[1]: Failed to start Enable File System Quotas.
```
The fix for the problem is not as trivial as your PR looks like. I need to think about how to fix that in an elegant way.

**Comment by levtecaccess** [comment]
I have very mittle experience with Salt so am unsure of exactly how to implement this, I will leave it to you to do so.
