### ISSUE TITLE
webGUI : Failed to connect to socket: Connection refused

### ISSUE THREAD

**Issue by Systemac** [openmediavault/openmediavault#804]
I just want to connect today, but can't...

I also can connect to portainer...

I can acces with root by ssh...

logs :

Erreur #0:
OMV\Rpc\Exception: Failed to connect to socket: Connection refused in /usr/share/php/openmediavault/rpc/rpc.inc:141
Stack trace:
#0 /var/www/openmediavault/rpc/session.inc(57): OMV\Rpc\Rpc::call('UserMgmt', 'authUser', Array, Array, 2, true)
#1 [internal function]: OMVRpcServiceSession->login(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('login', Array, Array)
#4 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('Session', 'login', Array, Array, 3)
#5 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#6 {main}

**Comment by votdev** [comment]
Please log in via SSH and try to start `omv-engined -d -f`. Are there any error messages printed?

**Comment by Systemac** [comment]
I really dont understand...

I start omv-engined -d -f, log with credentials and it's okay, no error.... But 5 minutes before no...

sorry .....

**Comment by Systemac** [comment]
ok... so if i stop the monitoring, i got this error : Failed to connect to socket: No such file or directory...

**Comment by votdev** [comment]
`systemctl unmask openmediavault-engined` should fix your problem. Seems a package upgrade was faulty or interrupted.
