### ISSUE TITLE
Repair update window - shell output

### ISSUE THREAD

**Issue by Peppa123** [openmediavault/openmediavault#805]
I have one omv5 installation (prod) where there is no shell output anymore when I install os updates (armbian / omv5) via openmediavault webpage / aktualisierungsverwaltung / installieren.

On my omv5 installation (test) - same os installation (armbian / omv5 ) this browser window is ok with shell output.

On the prod installation I only get the browser window without shell output (the browser windows leaves small).

Is there a way to repair this?

**Comment by ryecoaaron** [comment]
Did you try clearing your browser cache?

**Comment by Peppa123** [comment]
I am not sure, on next updates I will try IE or Chrome with cleared cache for comparison.

**Comment by Peppa123** [comment]
Yes cleared cache fixed the problem. Sorry that I did not try before.
