### ISSUE TITLE
Docker Storage - 'Leave blank' not possible

### ISSUE THREAD

**Issue by jerkball** [openmediavault/openmediavault#808]
Leaving OMV Docker Settings 'Docker Storage' empty causes an error...

![grafik](https://user-images.githubusercontent.com/6619363/92532409-8449c300-f230-11ea-8759-40e02e54c0d7.png)

Details:
`Error #0:
OMV\Json\SchemaValidationException: optout: The value 'null' is not a boolean. in /usr/share/php/openmediavault/json/schema.inc:334
Stack trace:
#0 /usr/share/php/openmediavault/json/schema.inc(285): OMV\Json\Schema->validateBoolean(NULL, Array, 'optout')
#1 /usr/share/php/openmediavault/json/schema.inc(261): OMV\Json\Schema->validateType(NULL, Array, 'optout')
#2 /usr/share/php/openmediavault/config/datamodel.inc(155): OMV\Json\Schema->validate(NULL, 'optout')
#3 /usr/share/php/openmediavault/config/configobject.inc(190): OMV\Config\DataModel->validateProperty('optout', NULL)
#4 /usr/share/openmediavault/engined/rpc/omvextras.inc(161): OMV\Config\ConfigObject->set('optout', NULL)
#5 [internal function]: OMVRpcServiceOmvExtras->setDocker(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('setDocker', Array, Array)
#8 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('OmvExtras', 'setDocker', Array, Array, 1)
#9 {main}`

Explanation Text tells us: Path to Docker images and containers storage. Leave blank to use custom /etc/docker/daemon.json.

So custom daemon.json seems not to be possible...

OMV-Version 5.5.9-1

**Comment by ryecoaaron** [comment]
This should have been filed here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues

But, you are having a browser cache issue.  I doesn't like that optout value you are passing because it has been removed but is still in your browser cache.
