### ISSUE TITLE
NFS error 

### ISSUE THREAD

**Issue by Rubarius** [openmediavault/openmediavault#809]
OMV 5.5.9-1
Linux 4.1.17

When starting nfs, it gives an error.
The system is new, did nothing else.

`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run nfs 2>&1' with exit code '1': wdduo: ---------- ID: configure_default_nfs-kernel-server Function: file.managed Name: /etc/default/nfs-kernel-server Result: True Comment: File /etc/default/nfs-kernel-server is in the correct state Started: 03:51:06.285093 Duration: 323.373 ms Changes: ---------- ID: configure_nfsd_exports Function: file.managed Name: /etc/exports Result: True Comment: File /etc/exports is in the correct state Started: 03:51:06.609027 Duration: 166.965 ms Changes: ---------- ID: start_rpc_statd_service Function: service.running Name: rpc-statd Result: True Comment: Service rpc-statd is already enabled, and is running Started: 03:51:06.822737 Duration: 645.644 ms Changes: ---------- rpc-statd: True ---------- ID: start_nfs_kernel_server_service Function: service.running Name: nfs-kernel-server Result: False Comment: A dependency job for nfs-server.service failed. See 'journalctl -xe' for details. Started: 03:51:07.472341 Duration: 267.421 ms Changes: Summary for wdduo ------------ Succeeded: 3 (changed=1) Failed: 1 ------------ Total states run: 4 Total run time: 1.403 s
`
[syslog.txt](https://github.com/openmediavault/openmediavault/files/5200725/syslog.txt)

**Comment by votdev** [comment]
What type of system do you have? Have you used the ISO or an ARM based image?

**Comment by votdev** [comment]
OK, seems your on ARM. Which distro are you using?
