### ISSUE TITLE
Date & Time Setting Option to use pool instead of server in chronyc.conf file

### ISSUE THREAD

**Issue by Jerry2840** [openmediavault/openmediavault#810]
### Description of issue/question
If you use:
server pool.ntp.org iburst
Then you only get 1 time server.  The other option is to list a bunch of time servers.
It would be nice to be able to use the pool option so that you can take advantage of all the time servers in the pool and not have to list them all out.
It would change to look like:
pool pool.ntp.org iburst

https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/srv/salt/omv/deploy/chrony/files/etc-chrony-chrony_conf.j2#L11
server {{ timeserver }} iburst
Would become:
{{pool_server}} {{ timeserver }} iburst

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

**Comment by votdev** [comment]
You mean you want a environmemnt variable like `OMV_CHRONY_POOL_SERVER` to customize the configuration? My question is, can't we simply change `server` to `pool`? Or does this fail in case the NTP server does not act like a pool?

**Comment by Jerry2840** [comment]
You could just change server to pool.  I would be fine with that.  Most people are probably using pool.ntp.org and don't know that they are only getting 1 time server when they do that.  I tried pool 216.126.233.109 iburst and it doesn't like it.
I think it would be safer to add a switch to use pool instead of server.  Some people might want to enter a bunch of time servers.  I don't think that is really the case.  I bet most people only enter 1.
