### ISSUE TITLE
Visu Dossier Partagé absente sur l'interface Web

### ISSUE THREAD

**Issue by Ludovic184** [openmediavault/openmediavault#811]
Lorsque je me loggue en tant qu'administrateur sur l'interface web d'Openmediavault:
1) Je ne peux pas sélectionner la langue français, je peux le sélectionner mais il ne reste pas. Il se remet en anglais. Ce n'est pas le plus embêtant
2) Lorsque je rentre dans l'interface web, dans le menu Acces Rights Management, je n'ai que le choix User et Groupe mais pas **Dossier Partagé** et c'est mon plus gros problème

Versions OMV 3.0.89  (erasmus)

**Comment by ryecoaaron** [comment]
OMV 3.x hasn't been supported in a long time but I would try clearing your browser cache.

**Comment by Ludovic184** [comment]
I did it but nothing has changed

**Comment by ryecoaaron** [comment]
It is possible there is something in the OMV 3.x web interface that doesn't render properly in current browsers.  I recommend a fresh install of OMV 5.x.

**Comment by Ludovic184** [comment]
It worked last week. So if i came back to an old version of my browsers it should worked?

**Comment by ryecoaaron** [comment]
No idea.  I haven't used OMV 3.x in almost 3 years.

**Comment by Ludovic184** [comment]
No solution
