### ISSUE TITLE
Question - hostname in GUI vs /etc/hostname

### ISSUE THREAD

**Issue by yuriw** [openmediavault/openmediavault#813]
I ran into the problem when had unknowingly a too long `hostname` in the Network/General settings.
The error was "The DNS hostname is limited to 15 characters when using SMB/CIFS." (which was correct)

The real issue was that I did have a good value in `/etc/hostname`

What is the purpose to allow `hostname` in OMV GUI and  `/etc/hostname` be different ?

**Comment by ryecoaaron** [comment]
Changing the hostname in the web interface should change the hostname in /etc/hostname using hostnamectl - https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/hostname/default.sls#L28

**Comment by yuriw** [comment]
@ryecoaaron ok cool and other way around?  changing the `hostname` in `/etc/hostname` will be reflected in the GUI ?

This is probably the issue

**Comment by votdev** [comment]
> @ryecoaaron ok cool and other way around? changing the `hostname` in `/etc/hostname` will be reflected in the GUI ?
> 
> This is probably the issue

No, OMV and the settings in the database entered via the UI is the source of thruth. You can re-populate the database with changes done to a small number of files, but this is only for populating the database after installing the system the first time.

**Comment by yuriw** [comment]
@votdev ok then the original question "What is the purpose to allow hostname in OMV GUI and /etc/hostname be different ?"

**Comment by ryecoaaron** [comment]
@yuriw OMV doesn't.  If you change something from the command line, OMV doesn't know about it.

**Comment by yuriw** [comment]
I think if it's possible it'd be great if you consider changing this behavior to work in both directions, otherwise, as I learned on my experience, it may create unpleasant user experience.

**Comment by votdev** [comment]
> I think if it's possible it'd be great if you consider changing this behavior to work in both directions, otherwise, as I learned on my experience, it may create unpleasant user experience.

No, this will never happen. This is not the idea of OMV. If you like to have this behavior, OMV is not the right choice, better use [webmin](https://www.webmin.com/) then.

**Comment by ryecoaaron** [comment]
Why would you ever "need" to change the hostname from the command line instead of the web interface?

**Comment by yuriw** [comment]
Why not ?  I did it ! On all distro this is the "default" way !  If OMV allows to have different names in both places, it's better have a way to reconcile this.  This is about making it better.  If you think it's a stupid idea and unrealistic use case, ok shot me down !

**Comment by ryecoaaron** [comment]
The whole concept of OMV is reduce command line interaction because OMV completely controls the config files it owns (/etc/hostname is one of them) and to do things from the web interface.  None of the config files that OMV owns will change the database and/or notify OMV if they are changed.  What you are suggesting would change the fundamental nature of OMV.

Just think about what it would take for OMV to allow changing the hostname from the command line (and hostname is the easier one):
- OMV would have to use something like inotify that the file even changed
- OMV would have to hope the change was a valid change
- OMV would then have to change the database to update the hostname stored there splitting off the domain and updating the domain if found
- OMV would have to make an rpc call to the change name function to update the many places hostname is used (not just /etc/hostname)

This may not seem tough but it would be.  And other config files would be a nightmare.

And I can't shoot you down since I am just a plugin dev.

**Comment by yuriw** [comment]
Hey I am pretty happy as long as know how to manage my way thru, the rest is up to you :) 

You get users' feedback, digest it and do what you think it right.  If you ask me for importance of this issue, I would not rate it too high - "very nice to have", but I see that this is opening a can of worms.

To add some oil to the fire - if OMV manages `hostname` why wold not  it manage `/etc/hostnames`then ?  What makes one thing to be it and another to be out ?  That also would reduce command line interaction

But I do see your point !

**Comment by ryecoaaron** [comment]
/etc/hosts you mean? OMV does manage that file. But why are you adding things to that file? You should be adding dns entries to your dns server.

**Comment by yuriw** [comment]
Yes of cause  `/etc/hosts`, I am not just using it as illustration point

**Comment by donhwy** [comment]
Would be good to add a warning if editing files that OMV owns that things will be broken.

**Comment by votdev** [comment]
> Would be good to add a warning if editing files that OMV owns that things will be broken.

I'm sure this nearly done for all files that are controlled by OMV and support comments, e.g. [/etc/hosts](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/hosts/10default.sls#L36). The file `/etc/resolv.conf` is generated by systemd-networkd, so OMV can't add a comment.
