### ISSUE TITLE
Wrong port listed on console for web UI access when "Cockpit" enabled

### ISSUE THREAD

**Issue by jrowe88** [openmediavault/openmediavault#814]
Hello, I noticed on rebooting that the console tells me the OMV webui should be accessed on "https://192.168.1.3:9090".  The ports that I have set in Settings->General are "8080" and  "8443" for https.   The "9090" port is what is assigned to Cockpit within OMV-Extras.

================================================================================
= OS/Debian information
================================================================================
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 10 (buster)
Release: 10
Codename: buster

================================================================================
= openmediavault information
================================================================================
Release: 5.5.10-1
Codename: Usul

================================================================================
= Date
================================================================================
Thu Sep 17 07:45:53 MDT 2020

**Comment by votdev** [comment]
Did you have set 9090 for OMV UI before?

**Comment by votdev** [comment]
Can you please provide a screenshot to know what you are talking about. The welcome message ([/etc/issue](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/issue/files/etc-issue.j2)) that is displayed on the CLI login screen does not list ports, only interfaces.

**Comment by ryecoaaron** [comment]
cockpit adds its own motd that lists the ip and port for its web interface.  It is not telling you OMV's ip and port.

**Comment by votdev** [comment]
I close this issue because it seems you're talking about the [Cockpit motd](https://github.com/cockpit-project/cockpit/blob/master/src/ws/update-motd) which is not related to OMV.
