### ISSUE TITLE
WebUI : User management : Delete a comment

### ISSUE THREAD

**Issue by stephane-21** [openmediavault/openmediavault#816]
### Description of issue/question
If you have assigned a comment to a user, you can't delete the comment.

### Steps to reproduce issue
WebUI > Access Rights Management > User
Create a user without email but with a comment (just bellow the name box)
Try to delete the comment
You can modify the comment but you can't delete it (empty string).

### Versions report
OMV version 5.5.11-1 (Usul)

**Comment by votdev** [comment]
Fixed in `openmediavault 5.5.12`.
