### ISSUE TITLE
omv-salt deploy run phpfpm fails

### ISSUE THREAD

**Issue by uyouthe** [openmediavault/openmediavault#818]
### Description of issue/question

I tried to install OMV on my Pi Zero W. It kinda worked but it displays "502 Bad Gateway / Nginx". I tried running these commands as I found that they solved some issues:
```
omv-salt deploy run nginx
omv-salt deploy run phpfpm
```
but the second one fails with this:

```
----------
          ID: test_phpfpm_service_config
    Function: cmd.run
        Name: php-fpm7.3 --test
      Result: False
     Comment: Command "php-fpm7.3 --test" run
     Started: 18:53:52.920602
    Duration: 236.379 ms
     Changes:   
              ----------
              pid:
                  3105
              retcode:
                  -4
              stderr:
              stdout:
----------
          ID: restart_phpfpm_service
    Function: service.running
        Name: php7.3-fpm
      Result: False
     Comment: One or more requisite failed: omv.deploy.phpfpm.default.test_phpfpm_service_config
     Started: 18:53:53.352245
    Duration: 0.1 ms
     Changes:   
----------
          ID: monitor_phpfpm_service
    Function: module.run
        Name: monit.monitor
      Result: False
     Comment: One or more requisite failed: omv.deploy.phpfpm.default.restart_phpfpm_service
     Started: 18:53:53.376829
    Duration: 0.099 ms
     Changes:   

```

What should I do?

### Steps to reproduce issue

1. `sudo apt-get install monit=1:5.25.2-3` because it doesn't work out of the box
2. `wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash`
3. Go to `raspberrypi.local` and see the 502
4. `sudo omv-salt deploy run phpfpm` to see the error

### Versions report
I'm using the latest OMV available now.

**Comment by votdev** [comment]
Where does the `monit` package come from? OMV only provides 5.26 via repositories and Debian does not have it in Debian 10 (Buster).

**Comment by uyouthe** [comment]
@votdev I don't know, I just entered it and it worked. How do I check this?

**Comment by uyouthe** [comment]
I also tried `sudo apt-get install openmediavault --reinstall`. Reinstallation went without errors but the 502 is still here.

**Comment by votdev** [comment]
> @votdev I don't know, I just entered it and it worked. How do I check this?

`apt-cache policy monit`

**Comment by uyouthe** [comment]
@votdev 
```
monit:
  Installed: 1:5.25.2-3
  Candidate: 1:5.26.0-1
  Version table:
     1:5.26.0-1 500
        500 http://packages.openmediavault.org/public usul/main armhf Packages
        500 https://openmediavault.github.io/packages usul/main armhf Packages
     1:5.26.0-1~bpo10+1 100
        100 http://httpredir.debian.org/debian buster-backports/main armhf Packages
 *** 1:5.25.2-3 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
        100 /var/lib/dpkg/status

```

**Comment by votdev** [comment]
> @votdev
> 
> ```
> monit:
>   Installed: 1:5.25.2-3
>   Candidate: 1:5.26.0-1
>   Version table:
>      1:5.26.0-1 500
>         500 http://packages.openmediavault.org/public usul/main armhf Packages
>         500 https://openmediavault.github.io/packages usul/main armhf Packages
>      1:5.26.0-1~bpo10+1 100
>         100 http://httpredir.debian.org/debian buster-backports/main armhf Packages
>  *** 1:5.25.2-3 500
>         500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
>         100 /var/lib/dpkg/status
> ```

OK, it comes form the RasPi repo. And what exactly is wrong with the version in the OMV repo? I do not see any connection to this issue. IMO the problem is phpfpm and its configuration.
Can you run `php-fpm7.3 --test` and post the output?

**Comment by uyouthe** [comment]
@votdev it just prints "Illegal instruction"

**Comment by votdev** [comment]
Run `journalctl -f` in a separate CLI; are there any useful information? IMO it looks like a bug in PHPFPM on ARM.

**Comment by uyouthe** [comment]
`journalctl -f`
```
Sep 26 20:14:53 raspberrypi systemd[1]: openmediavault-engined.service: Control process exited, code=killed, status=4/ILL
Sep 26 20:14:53 raspberrypi systemd[1]: openmediavault-engined.service: Failed with result 'signal'.
Sep 26 20:14:53 raspberrypi systemd[1]: Failed to start The OpenMediaVault engine daemon that processes the RPC request.
Sep 26 20:15:01 raspberrypi CRON[7386]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep 26 20:15:01 raspberrypi CRON[7385]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep 26 20:15:01 raspberrypi CRON[7394]: (root) CMD (/usr/sbin/omv-mkrrdgraph >/dev/null 2>&1)
Sep 26 20:15:01 raspberrypi CRON[7396]: (root) CMD (/usr/sbin/omv-ionice >/dev/null 2>&1)
Sep 26 20:15:01 raspberrypi CRON[7385]: pam_unix(cron:session): session closed for user root
Sep 26 20:15:19 raspberrypi CRON[7386]: pam_unix(cron:session): session closed for user root
Sep 26 20:15:23 raspberrypi monit[689]: 'omv-engined' failed to start (exit status 1) -- '/bin/systemctl start openmediavault-engined': Job for openmediavault-engined.service failed because a fatal signal was delivered to the control process.
                                        See "systemctl status openmediavault-engined.service" and "journalctl -xe" for details.
Sep 26 20:15:53 raspberrypi monit[689]: 'php-fpm' process is not running
Sep 26 20:15:53 raspberrypi monit[689]: 'php-fpm' trying to restart
Sep 26 20:15:53 raspberrypi monit[689]: 'php-fpm' start: '/bin/systemctl start php7.3-fpm'
Sep 26 20:15:54 raspberrypi systemd[1]: Starting The PHP 7.3 FastCGI Process Manager...
Sep 26 20:15:54 raspberrypi systemd[1]: php7.3-fpm.service: Main process exited, code=killed, status=4/ILL
Sep 26 20:15:54 raspberrypi systemd[1]: php7.3-fpm.service: Failed with result 'signal'.
Sep 26 20:15:54 raspberrypi systemd[1]: Failed to start The PHP 7.3 FastCGI Process Manager.
Sep 26 20:16:01 raspberrypi CRON[7488]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep 26 20:16:01 raspberrypi CRON[7492]: (root) CMD (/usr/sbin/omv-ionice >/dev/null 2>&1)
Sep 26 20:16:01 raspberrypi CRON[7488]: pam_unix(cron:session): session closed for user root
```

`systemctl status openmediavault-engined.service`
```
● openmediavault-engined.service - The OpenMediaVault engine daemon that processes the RPC request
   Loaded: loaded (/lib/systemd/system/openmediavault-engined.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Sat 2020-09-26 20:16:25 BST; 28s ago
  Process: 7508 ExecStart=/usr/sbin/omv-engined (code=killed, signal=ILL)

Sep 26 20:16:25 raspberrypi systemd[1]: Starting The OpenMediaVault engine daemon that processes the RPC request...
Sep 26 20:16:25 raspberrypi systemd[1]: openmediavault-engined.service: Control process exited, code=killed, status=4/ILL
Sep 26 20:16:25 raspberrypi systemd[1]: openmediavault-engined.service: Failed with result 'signal'.
Sep 26 20:16:25 raspberrypi systemd[1]: Failed to start The OpenMediaVault engine daemon that processes the RPC request.

```

`journalctl -xe`
```
-- Subject: A stop job for unit nginx.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A stop job for unit nginx.service has finished.
-- 
-- The job identifier is 13781 and the job result is done.
Sep 26 20:16:24 raspberrypi monit[689]: 'nginx' start: '/bin/systemctl start nginx'
Sep 26 20:16:24 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
-- Subject: A start job for unit nginx.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit nginx.service has begun execution.
-- 
-- The job identifier is 13782.
Sep 26 20:16:25 raspberrypi systemd[1]: Started A high performance web server and a reverse proxy server.
-- Subject: A start job for unit nginx.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit nginx.service has finished successfully.
-- 
-- The job identifier is 13782.
Sep 26 20:16:25 raspberrypi monit[689]: 'omv-engined' process is not running
Sep 26 20:16:25 raspberrypi monit[689]: 'omv-engined' trying to restart
Sep 26 20:16:25 raspberrypi monit[689]: 'omv-engined' start: '/bin/systemctl start openmediavault-engined'
Sep 26 20:16:25 raspberrypi systemd[1]: Starting The OpenMediaVault engine daemon that processes the RPC request...
-- Subject: A start job for unit openmediavault-engined.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit openmediavault-engined.service has begun execution.
-- 
-- The job identifier is 13851.
Sep 26 20:16:25 raspberrypi systemd[1]: openmediavault-engined.service: Control process exited, code=killed, status=4/ILL
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit openmediavault-engined.service has exited.
-- 
-- The process' exit code is 'killed' and its exit status is 4.
Sep 26 20:16:25 raspberrypi systemd[1]: openmediavault-engined.service: Failed with result 'signal'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit openmediavault-engined.service has entered the 'failed' state with result 'signal'.
Sep 26 20:16:25 raspberrypi systemd[1]: Failed to start The OpenMediaVault engine daemon that processes the RPC request.
-- Subject: A start job for unit openmediavault-engined.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit openmediavault-engined.service has finished with a failure.
-- 
-- The job identifier is 13851 and the job result is failed.
Sep 26 20:16:56 raspberrypi monit[689]: 'omv-engined' failed to start (exit status 1) -- '/bin/systemctl start openmediavault-engined': Job for openmediavault-engined.service failed because a fatal signal was delivered to the control proc
                                        See "systemctl status openmediavault-engined.service" and "journalctl -xe" for details.
Sep 26 20:17:02 raspberrypi CRON[7512]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep 26 20:17:02 raspberrypi CRON[7511]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep 26 20:17:02 raspberrypi CRON[7519]: (root) CMD (/usr/sbin/omv-ionice >/dev/null 2>&1)
Sep 26 20:17:02 raspberrypi CRON[7522]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Sep 26 20:17:02 raspberrypi CRON[7511]: pam_unix(cron:session): session closed for user root
Sep 26 20:17:02 raspberrypi CRON[7512]: pam_unix(cron:session): session closed for user root
```

**Comment by uyouthe** [comment]
I was able to install pihole easily and pihole also installed something related to php7. Pihole worked just fine.

**Comment by votdev** [comment]
> I was able to install pihole easily and pihole also installed something related to php7. Pihole worked just fine.

You mean you installed it on OMV directly? Hmmm, that might be the reason. If you've added additional Debian repos to install that software, packages that are not supported by OMV might be installed and broke your installation. Better use Docker or any other container technology to install additional software.

I will close that issue because you seem responsible for the problems. The OMV can not do anything here. OMV is strictly tied to Debian stable.

**Comment by uyouthe** [comment]
Disappointed with your assumptions. 

I gave up on omv, then I reflashed my microsd and then I installed pihole. I mentioned it because pihole also uses php and it works fine.

Should I try raspbian instead of raspbian lite though?

**Comment by ryecoaaron** [comment]
No, you should not use the desktop version.  You should use Raspberry Pi OS Buster Lite.  Did you use the install script to install OMV?

**Comment by uyouthe** [comment]
@ryecoaaron excuse me, I forgot about the rename. I used Raspberry Pi OS Buster Lite and the install script. I listed the exact reproduction commands in my original comment.

**Comment by ryecoaaron** [comment]
@uyouthe just trying to help.  I didn't read the entire thread.  Looking at your original commands, you are doing what I advise against.  You should write the image and run the script.  Nothing else in between those steps. The script will install the right version of monit.  If that is not working, there must be something weird with the pi zero (not sure I would ever recommend using one for a NAS).  The entire output of the install script would be needed to help more.  Posting in the forum would much easier too.

**Comment by uyouthe** [comment]
@ryecoaaron should I use pi os lite or just the pi os though?

**Comment by votdev** [comment]
> @votdev Disappointed with your assumptions.
> 
> I gave up on omv, then I reflashed my microsd and then I installed pihole. I mentioned it because pihole also uses php and it works fine.
> 
> Should I try raspbian instead of raspbian lite though?

Based on the given information and phrasing this was my assumption. I'm sorry if was wrong. Nevertheless, your setup looks not really healthy. I assume something went terrible wrong during the installation. The amount of errors is not normal and i do not see a red line in all those reported problems.

**Comment by ryecoaaron** [comment]
@uyouthe Always the lite version which basically means server version.  Lite also means no desktop which is what OMV needs.  The desktop environment causes problems with OMV because they are both trying to manage config files.

**Comment by uyouthe** [comment]
So if it’s not the regular vs lite version, it’s probably the fact that I’m using a zero w. What do you think? Should I try it with a pi 4 instead?

**Comment by ryecoaaron** [comment]
The RPi4 is a much better NAS.  I have installed OMV 5 on an RPi4 hundreds of times.
