### ISSUE TITLE
Dashboard on mobile not adjusting to 100% screen size

### ISSUE THREAD

**Issue by alejandrofm** [openmediavault/openmediavault#819]
Hi, this been happening for a while, I must not be the only one

### Description of issue/question
On mobile, the dashboard (landing page) size is 50% of the screen, the other screens adjust to 100%.
![image](https://user-images.githubusercontent.com/19591174/94378440-1c381f80-0100-11eb-90f4-81ad7e608630.png)

### Steps to reproduce the issue
Login on mobile and the home screen (dashboard) will not use 100% of the width and even using horizontal scrolling is hard to read because it needs things like resize table columns.

### Versions report
Version: 5.5.11-1 (Usul)

Thank you!

**Comment by votdev** [comment]
Fixed with `openmediavault 5.5.12`. You need to run the `Reset UI to defaults` menu in the breadcrumb menu or clear all browser cookies.
