### ISSUE TITLE
Inappropriate IOCTL

### ISSUE THREAD

**Issue by EruIluvatar** [openmediavault/openmediavault#82]
I just got a mail with the content:
> /etc/cron.weekly/openmediavault-update-smart-drivedb:
> mesg: ttyname failed: Unpassender IOCTL (I/O-Control) für das Gerät

The forum suggests a fix for `/root/.profile`.
But could the problem also be avoided by not executing the script as a login shell, by making the shebang `#! /bin/sh` instead of `#! /bin/sh -l` like here?

https://github.com/openmediavault/openmediavault/commit/3b080600ff2d23e12c0068d8a51be785649e1a87#diff-3d0f72f14b9a4eb86127299f58aec433

**Comment by votdev** [comment]
Please check https://forum.openmediavault.org/index.php/Thread/20966-mesg-ttyname-failed-Inappropriate-ioctl-for-device/?postID=163028#post163028 how to fix that.

**Comment by votdev** [comment]
Fixed by https://github.com/openmediavault/openmediavault/commit/bec9ba52cbde3fc3ef32435aa66ca2e14dbc3c1b in OMV5.
