### ISSUE TITLE
NFS (disabled) showing as running on dashboard

### ISSUE THREAD

**Issue by alejandrofm** [openmediavault/openmediavault#820]
Hi, I'm currently using SMB/CIFS (SAMBA)

### Description of issue/question
NFS is disabled
![image](https://user-images.githubusercontent.com/19591174/94439829-47aa2100-0177-11eb-942a-cddd3d681f89.png)

But it shows as running on services
![image](https://user-images.githubusercontent.com/19591174/94439759-2f3a0680-0177-11eb-83f8-16975bafe828.png)

### Steps to reproduce issue
I didn't change anything that I remember

### Versions report
5.5.11-1 (Usul)

Why is a disabled service running?
Thank you!

**Comment by votdev** [comment]
Ask the Debian maintainers why [this code](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/debian/openmediavault.postinst#L125) sometimes work and sometimes not. You can disable it finally by running `omv-salt deploy run nfs`.

I will close this issue as know issue.
