### ISSUE TITLE
Add ability to define transmit-hash-policy of bond interface in the UI

### ISSUE THREAD

**Issue by stalinCCCP415** [openmediavault/openmediavault#823]
Just a UI feature request. Can the ability to define the transmit-hash-policy be added to the UI as a selectable list for bond interfaces? I like to define this, and have had to do this via the filesystem for a few OMV versions now. Seems like a pretty easy thing to add.

OMV 5

**Comment by mi-hol** [comment]
there is no version label but "planned" label.
Will this be worked on for 6.x oder 7.x ?
