### ISSUE TITLE
Unable to reset failed login attempt counter for user [NONAME]

### ISSUE THREAD

**Issue by TitanSpirit** [openmediavault/openmediavault#824]
### Description of issue/question
I receive from OMV e-mail like this:
```
The following users are locked/banned or are candidates for too many failed login attempts:

Login           Failures Latest failure     From
[NONAME]            1    07/03/19 12:45:13  unknown

You can reset their counters and unlock them via the omv-firstaid command.
```

but when I try to reset counter via SSH terminal i receive:

```
user@omv:~$ sudo omv-firstaid
Reset failed login attempt counter for user '[NONAME]'.
pam_tally2: pam_get_uid; no such user [NONAME]
pam_tally2: Unknown user
ERROR: Command '['pam_tally2', '--quiet', '--reset=0', '--user', '[NONAME]']' returned non-zero exit status 1
```

### Steps to reproduce issue
1. Add e-mail credentials in System > Notifications via OMV web panel.
2. Choose settings like these:
![obraz](https://user-images.githubusercontent.com/39647585/95666083-c54a3580-0b56-11eb-8cf8-01f6ba0e6bf2.png)
3. Check your mailbox to see the e-mail message sent from OMV to you.
4. Log in to your OMV via SSH and enter 
`sudo omv-firstaid`
5. Choose option nr 4
![obraz](https://user-images.githubusercontent.com/39647585/95666157-55887a80-0b57-11eb-8beb-2884527eb163.png)
6. Choose [NONAME]
![obraz](https://user-images.githubusercontent.com/39647585/95666217-ce87d200-0b57-11eb-82c8-b592b2f8b091.png)

### Versions report
![obraz](https://user-images.githubusercontent.com/39647585/95666129-1d813780-0b57-11eb-9f67-a491a79ec98b.png)

**Comment by TitanSpirit** [comment]
The problem is now solved. According to this topic: https://forum.openmediavault.org/index.php?thread/17450-locked-user-noname-cannot-be-cleared/

The solution is to execute in terminal:
`pam_tally2 --reset`

**Comment by votdev** [comment]
I mark this as a known issue because i really have no idea how to reproduce this and it seems like this is a pam_tally2 bug according to the reports i found.

**Comment by mi-hol** [comment]
4.x is EOL
