### ISSUE TITLE
smartctl and spindown hd

### ISSUE THREAD

**Issue by legolas0802** [openmediavault/openmediavault#827]
### Description of issue/question
smartctl does not allow hard disk spindowns, it wakes them up every minute. Even with all S.M.A.R.T options disabled
### Steps to reproduce issue
(Include debug logs if possible and relevant.)
I idle a hd with hdparm -y and in the meantime I checked the same with btrace, this is what comes when he wakes up:
`  8,16   3        2    60.031028976 16282  D   R 512 [(null)]
  8,16   3        3    60.053521454 16282  D   R 512 [(null)]
  8,16   2       45    60.026569181 16282  D   R 36 [smartctl]
  8,16   2       46    60.026588210    21  C   R [0]
  8,16   2       47    60.026613242 16282  D   R 512 [smartctl]
  8,16   2       48    60.030977946 12174  C   R [0]
  8,16   2       49    60.036947471  3796  C   R [0]
  8,16   2       50    62.896444362     0  C   R [0]
  8,16   2       51    62.896746303   171  D   R 512 [kworker/2:1H]
  8,16   2       52    64.054692730     0  C   R [0]
  8,16   2       53    64.054983792   171  D   N 0 [kworker/2:1H]
  8,16   2       54    64.317720383     0  C   N [0]
  8,16   2       55    64.337059232   171  D   R 512 [kworker/2:1H]
  8,16   2       56    64.337458967     0  C   R [0]
  8,16   2       57    64.337763990   171  D   R 512 [kworker/2:1H]
  8,16   1        2    65.237128392 16282  D   R 512 [smartctl]
  8,16   1        3    65.243927559 16282  D   R 512 [smartctl]
  8,16   2       58    65.236870954     0  C   R [0]
  8,16   2       59    65.243757844     0  C   R [0]
  8,16   2       60    65.272105058     0  C   R [0]
  8,16   2       61    65.272374975   171  D   R 512 [kworker/2:1H]
  8,16   2       62    65.272840750     0  C   R [0]
  8,16   2       63    65.275334215   171  D   R 512 [kworker/2:1H]
  8,16   2       64    65.275764368     0  C   R [0]
  8,16   2       65    65.277352457   171  D   W 512 [kworker/2:1H]
  8,16   2       66    65.279770161     0  C   W [0]
  8,16   2       67    65.279942129   171  D   R 512 [kworker/2:1H]
  8,16   2       68    65.280423638     0  C   R [0]
  8,16   2       69    65.280442921 16282  D   R 512 [smartctl]
  8,16   2       70    65.280839820     0  C   R [0]
  8,16   2       71    65.281482969 16282  D   R 512 [smartctl]
  8,16   2       72    65.297921927     0  C   R [0]
  8,16   2       73    65.297983306 16282  D   R 512 [smartctl]
  8,16   2       74    65.314591432     0  C   R [0]
  8,16   2       75    65.314689604 16282  D   R 512 [smartctl]
  8,16   3        4    65.347958129 16282  D   R 512 [smartctl]
  8,16   2       76    65.331231280     0  C   R [0]
  8,16   2       77    65.331315338 16282  D   R 512 [smartctl]
  8,16   2       78    65.347890217 16319  C   R [0]
  8,16   2       79    65.364571605 16317  C   R [0]
  8,16   3        5    65.364678378 16282  D   R 512 [smartctl]
  8,16   3        6    65.381323220 16282  D   R 512 [smartctl]
  8,16   2       80    65.381217546 16319  C   R [0]
  8,16   2       81    65.381826107 16319  C   R [0]`

### Versions report
omv 5 ver. 5.5.12-1

**Comment by votdev** [comment]
How does your `/etc/smartd.conf` look and what is the output of `omv-confdbadm read --prettify conf.service.smartmontools`?

**Comment by legolas0802** [comment]
> How does your `/etc/smartd.conf` look and what is the output of `omv-confdbadm read --prettify conf.service.smartmontools`?

smartd.conf:
`# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.

/dev/disk/by-id/ata-Hitachi_HDS723030ALA640_MK0311YHG7KKJA -a -o on -S on -T pe$
/dev/disk/by-id/ata-PNY_CS900_120GB_SSD_PNY44191911011504766 -a -o on -S on -T $
/dev/disk/by-id/ata-ST2000DM008-2FR102_WFL2KBPS -a -o on -S on -T permissive -W$
/dev/disk/by-id/ata-Samsung_SSD_840_EVO_120GB_S1D5NSAF925610T -a -o on -S on -T$
/dev/disk/by-id/ata-WDC_WD10EACS-00D6B0_WD-WCAU40622400 -a -o on -S on -T permi$
/dev/disk/by-id/ata-WDC_WD40EZRX-00SPEB0_WD-WCC4ENA8P2CU -a -o on -S on -T perm$`

omv-confdbadm read --prettify conf.service.smartmontools:
`{
    "enable": true,
    "interval": 604000,
    "monitor": {
        "device": [
            {
                "devicefile": "/dev/disk/by-id/ata-Hitachi_HDS723030ALA640_MK031                                                                                        1YHG7KKJA",
                "devicetype": "",
                "enable": true,
                "uuid": "cee32edb-12d2-44e4-8be9-7daa7ab2cf66"
            },
            {
                "devicefile": "/dev/disk/by-id/ata-PNY_CS900_120GB_SSD_PNY441919                                                                                        11011504766",
                "devicetype": "",
                "enable": true,
                "uuid": "a33bf748-56af-4a3b-9e03-27a11456bb82"
            },
            {
                "devicefile": "/dev/disk/by-id/ata-ST2000DM008-2FR102_WFL2KBPS",
                "devicetype": "",
                "enable": true,
                "uuid": "9b36d378-b8f2-4fc5-b5e9-7fe349fd665a"
            },
            {
                "devicefile": "/dev/disk/by-id/ata-Samsung_SSD_840_EVO_120GB_S1D                                                                                        5NSAF925610T",
                "devicetype": "",
                "enable": true,
                "uuid": "46936817-cb03-47ba-b4a2-0f69d2000838"
            },
            {
                "devicefile": "/dev/disk/by-id/ata-WDC_WD10EACS-00D6B0_WD-WCAU40                                                                                        622400",
                "devicetype": "",
                "enable": true,
                "uuid": "724fa709-e3bd-4e8f-a3f3-5789aec0c71b"
            },
            {
                "devicefile": "/dev/disk/by-id/ata-WDC_WD40EZRX-00SPEB0_WD-WCC4E                                                                                        NA8P2CU",
                "devicetype": "",
                "enable": true,
                "uuid": "5be7f921-c162-49d3-9a0f-04c95084ec6e"
            }
        ]
    },
    "powermode": "standby",
    "scheduledtests": {
        "job": []
    },
    "tempcrit": 0,
    "tempdiff": 0,
    "tempinfo": 0
}`

I want to clarify that as I said in the first post even if I disable all the s.m.a.r.t. parameters i find a reading every minute on all hard drives by smartctl which wakes up the drives

**Comment by votdev** [comment]
The `smartd.conf`is not complete, you cut-off the most important part. But according to your configuration the important setting should be `-n standby,q`. This means according to the [manual](https://www.smartmontools.org/browser/trunk/smartmontools/smartd.conf.5.in):

```
-n POWERMODE[,N][,q]
    [ATA only] This 'nocheck' Directive is used to prevent a disk from being spun-up when it is periodically polled by smartd.

...

    standby - check the device unless it is in SLEEP or STANDBY mode. In these modes most disks are not spinning, so if you want to prevent a laptop disk from spinning up each time that smartd polls, this is probably what you want. 
```

I think OMV is configuring SMART correctly, so i'm not sure how to fix this.

**Comment by legolas0802** [comment]
> The `smartd.conf`is not complete, you cut-off the most important part. But according to your configuration the important setting should be `-n standby,q`. This means according to the [manual](https://www.smartmontools.org/browser/trunk/smartmontools/smartd.conf.5.in):
> 
> ```
> -n POWERMODE[,N][,q]
>     [ATA only] This 'nocheck' Directive is used to prevent a disk from being spun-up when it is periodically polled by smartd.
> 
> ...
> 
>     standby - check the device unless it is in SLEEP or STANDBY mode. In these modes most disks are not spinning, so if you want to prevent a laptop disk from spinning up each time that smartd polls, this is probably what you want. 
> ```
> 
> I think OMV is configuring SMART correctly, so i'm not sure how to fix this.

the smartd configuration is just that, in the file I have nothing else. I have been trying for two days to solve and I have tried all possible combinations to no avail. The strangest thing is that with everything disabled, smarctl continues to query the disks. Now to try it out, I deleted the smartctl file from the system and the disks went into regular spin down

**Comment by mi-hol** [comment]
@legolas0802 is the issue still happening with openmediavault (5.5.17-3)?
I case yes, please provide more details about OS and hardware.

**Comment by mi-hol** [comment]
closing due to no response
