### ISSUE TITLE
FTP on NTFS + anonymous login --> empty folder

### ISSUE THREAD

**Issue by himijendrix24** [openmediavault/openmediavault#829]
### Description of issue/question

When I access a share folder on an NTFS filesystem via anonymous FTP it shows only an empty folder.

Accessing a shared folder on an EXT4 filesystem it works.
Also when accessing the NTFS folder using a user-login with set permissions.

anonymous FTP access was done with ...
... windows 10 explorer using "ftp://IPADDRESS/FOLDER"
... foobar on android using "ftp://@IPADDRESS/FOLDER"

### Versions report

ODROID N2
Openmediavault 5.5.12-1 Usul
Linux NAS 4.9.236+ #1 SMP PREEMPT Tue Oct 13 17:03:36 CEST 2020 aarch64 GNU/Linux

**Comment by votdev** [comment]
Does it help to set read/write permissions for the user `ftp` in the ACL dialog?
