### ISSUE TITLE
Diskstats plugin not showing for non-OMV mounted drive

### ISSUE THREAD

**Issue by sbocquet** [openmediavault/openmediavault#83]
Hi,

I'm using the ZFS pluging to manage a pool of disk.
At the moment, the plugin is using this function to populate the list of watched disks in the UI. https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/filesystemmgmt.inc#L166

The disks are not "mounted" by/in OMV but it can still be usefull to have some info on them as you just need to add them in the collectd conf file to have the data generated and the graph too.

Only the UI is blocking at the moment.

```
root@home-server:/# cat /etc/collectd/collectd.conf.d/disk.conf
LoadPlugin disk
<Plugin disk>
  Disk "sda"
  Disk "sdb"
  Disk "sdc"
  Disk "sde"
  Disk "sdf"
  Disk "sdg"
  Disk "sdh"
  Disk "sdi"
  IgnoreSelected false
</Plugin>
```

```
root@home-server:/# ls -al /var/lib/rrdcached/db/localhost/
total 120
drwxr-xr-x 30 root root 4096 avril 16 17:30 .
drwxr-xr-x  3 root root 4096 mars  15 10:13 ..
drwxr-xr-x  2 root root 4096 avril 17 11:11 cpu-0
drwxr-xr-x  2 root root 4096 avril 17 11:11 cpu-1
drwxr-xr-x  2 root root 4096 avril 17 11:11 df-root
drwxr-xr-x  2 root root 4096 avril 17 11:11 df-srv-dev-disk-by-id-ata-SAMSUNG_MZ7LN512HCHP-000L1_S1ZKNXAG526958-part5
drwxr-xr-x  2 root root 4096 avril 17 11:11 df-StoragePool
drwxr-xr-x  2 root root 4096 avril 17 11:11 disk-sda
drwxr-xr-x  2 root root 4096 avril 17 11:11 disk-sdb
drwxr-xr-x  2 root root 4096 avril 17 11:11 disk-sdc
drwxr-xr-x  2 root root 4096 avril 17 11:11 disk-sdd
drwxr-xr-x  2 root root 4096 avril 17 11:11 disk-sde
drwxr-xr-x  2 root root 4096 avril 17 11:11 disk-sdf
drwxr-xr-x  2 root root 4096 avril 17 11:11 disk-sdg
drwxr-xr-x  2 root root 4096 avril 17 11:11 disk-sdh
drwxr-xr-x  2 root root 4096 avril 17 11:11 disk-sdi
```

**Comment by sbocquet** [comment]
OK, I have replaced that one
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/filesystemmgmt.inc#L166

with

https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/diskmgmt.inc#L55

and that works.

Any chance to have this change accepted ? ;)

**Comment by votdev** [comment]
Please create a PR to discuss this. I want to have something for testing.

**Comment by votdev** [comment]
One problem is that DiskMgmt::enumerateDevices returns data that is not "static". If the configuration is created at a time a USB device is plugged in it will be added to the collectd configuration. Some minutes later the USB device is unplugged and the collectd config becomes invalid and will produce errors.
Therefore, I tend not to accept such a PR.

**Comment by sbocquet** [comment]
OK. That's a good reason. Maybe there a way to know the 'static' disk vs the USB one ?
Or maybe select the requested disks within the UI ? The user should delect the correct disks, which add those in the collectd conf file.

Sorry for the Pull Request, I'm new to github... I have to learn how to use it !

**Comment by votdev** [comment]
I think you misunderstood me. With 'static' i mean something that is stored in the OMV database.

> Or maybe select the requested disks within the UI ? The user should select the correct disks, which add those in the collectd conf file.
No, that's not possible because this will break the OMV concept. OMV is no webmin UI where you can configure everything, instead the configuration for all services is done from a small configuration that is done by the user via UI. All services and other things derive their information from this config. In the current case the information which disks are monitored is derived from the filesystem mount config.

**Comment by TobbeJ** [comment]
Reviving this old issue.
i think this is still a problem, i got a device with a single sata disk that is shared over iscsi (the whole disk)
this means i cannot use a filesystem mount on it directly on the openmediavault box and therefor the stats page will not work as it is now and that is very unfortunate and a problem.

**Comment by votdev** [comment]
> Reviving this old issue.
> 
> i think this is still a problem, i got a device with a single sata disk that is shared over iscsi (the whole disk)
> 

What does this mean? Shared via block or file? If block, then the diskstat plugin can't be used because a filesystem is required.

> this means i cannot use a filesystem mount on it directly on the openmediavault box and therefor the stats page will not work as it is now and that is very unfortunate and a problem.
> 

Without a filesystem (which is unter control of OMV) the disk stats plugin may not work.

**Comment by TobbeJ** [comment]
> > Reviving this old issue.
> > i think this is still a problem, i got a device with a single sata disk that is shared over iscsi (the whole disk)
> 
> What does this mean? Shared via block or file? If block, then the diskstat plugin can't be used because a filesystem is required.
> 
block device shared over iscsi using the tgt plugin

> > this means i cannot use a filesystem mount on it directly on the openmediavault box and therefor the stats page will not work as it is now and that is very unfortunate and a problem.
> 
> Without a filesystem (which is unter control of OMV) the disk stats plugin may not work.

true, because of how the web page showing the stats is designed and that's where the problem is.
i can edit /etc/collectd/collectd.conf.d/disk.conf and add my sata disk and collectd will store the stats as expected.
web interface wont show it because it only includes block devices with a filesystem on it but if i adjust the html code in the browser by adjusting the url to rrd.php a little the graph shows up.
so collecting and displaying it is possible.

also disk is referenced via the web ui so it is not like i've done something outside of the openmediavault web ui.

adding removable disks to collectd probably makes not much sense so they can be ignored but other block devices should imo be included.

**Comment by votdev** [comment]
> > > Reviving this old issue.
> > > i think this is still a problem, i got a device with a single sata disk that is shared over iscsi (the whole disk)
> > 
> > 
> > What does this mean? Shared via block or file? If block, then the diskstat plugin can't be used because a filesystem is required.
> 
> block device shared over iscsi using the tgt plugin
> 
> > > this means i cannot use a filesystem mount on it directly on the openmediavault box and therefor the stats page will not work as it is now and that is very unfortunate and a problem.
> > 
> > 
> > Without a filesystem (which is unter control of OMV) the disk stats plugin may not work.
> 
> true, because of how the web page showing the stats is designed and that's where the problem is.
> i can edit /etc/collectd/collectd.conf.d/disk.conf and add my sata disk and collectd will store the stats as expected.
> web interface wont show it because it only includes block devices with a filesystem on it but if i adjust the html code in the browser by adjusting the url to rrd.php a little the graph shows up.
> so collecting and displaying it is possible.
> 
> also disk is referenced via the web ui so it is not like i've done something outside of the openmediavault web ui.
> 
> adding removable disks to collectd probably makes not much sense so they can be ignored but other block devices should imo be included.

Please open the issue here: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-tgt/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

It is the job of the plugin to ship the Salt state files for services like collectd.
