### ISSUE TITLE
ExtendVolumeGroup via omv-rpc

### ISSUE THREAD

**Issue by mrakoris** [openmediavault/openmediavault#833]
### Description of issue/question
Hi all! I am try resize volumegroup via omv-rpc, 
How to expand volume group via omv-rpс?
When I try to execute the command I get the error.
Maybe I'm passing the wrong parameters or this bug?

### Steps to reproduce issue
**Run command:**
omv-rpc -u admin 'logicalvolumemgmt' 'extendVolumeGroup' '{"devicefile": "vgname", "devices": "/dev/sdc" }'

**Log**
`
{"response":null,"error":{"code":0,"message":"devicefile: The value 'vgname' is no device file.","trace":"OMV\\Json\\SchemaValidationException: devicefile: The value 'vgname' is no device file. in \/usr\/share\/php\/openmediavault\/datamodel\/schema.inc:53\nStack trace:\n#0 \/usr\/share\/php\/openmediavault\/json\/schema.inc(377): OMV\\DataModel\\Schema->checkFormat('vgname', Array, 'devicefile')\n#1 \/usr\/share\/php\/openmediavault\/json\/schema.inc(301): OMV\\Json\\Schema->validateString('vgname', Array, 'devicefile')\n#2 \/usr\/share\/php\/openmediavault\/json\/schema.inc(631): OMV\\Json\\Schema->validateType('vgname', Array, 'devicefile')\n#3 \/usr\/share\/php\/openmediavault\/json\/schema.inc(399): OMV\\Json\\Schema->checkProperties(Object(stdClass), Array, '')\n#4 \/usr\/share\/php\/openmediavault\/json\/schema.inc(289): OMV\\Json\\Schema->validateObject(Object(stdClass), Array, '')\n#5 \/usr\/share\/php\/openmediavault\/json\/schema.inc(261): OMV\\Json\\Schema->validateType(Object(stdClass), Array, '')\n#6 \/usr\/share\/php\/openmediavault\/rpc\/paramsvalidator.inc(59): OMV\\Json\\Schema->validate(Object(stdClass))\n#7 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(179): OMV\\Rpc\\ParamsValidator->validate('{\"devicefile\":\"...')\n#8 \/usr\/share\/openmediavault\/engined\/rpc\/logicalvolumemgmt.inc(537): OMV\\Rpc\\ServiceAbstract->validateMethodParams(Array, 'rpc.logicalvolu...')\n#9 [internal function]: OMVRpcServiceLogicalVolumeMgmt->extendVolumeGroup(Array, Array)\n#10 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(123): call_user_func_array(Array, Array)\n#11 \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod('extendVolumeGro...', Array, Array)\n#12 \/usr\/sbin\/omv-engined(537): OMV\\Rpc\\Rpc::call('logicalvolumemg...', 'extendVolumeGro...', Array, Array, 1)\n#13 {main}"}}`
### Versions report

os: Debian10
omv: 5.5.12-1

**Comment by votdev** [comment]
Every RPC in OMV has a signature specification in JSON schema. The [logicalvolumemgmt::extendVolumeGroup](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-lvm2/usr/share/openmediavault/datamodels/rpc.logicalvolumemgmt.json#L72) RPC wants a [device file](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/datamodel/schema.inc#L51) like `/dev/sda` for the `devicefile` property.
