### ISSUE TITLE
Certificate info 

### ISSUE THREAD

**Issue by donhwy** [openmediavault/openmediavault#838]
This is not critical only cosmetic. I use a script to pass my letsencrypt wildcard cert to OMV. It works and the cert shows correctly on the browser. If I look at system > certificates > ssl the display is an old version. If I click details it is the updated cert info.
Thanks

**Comment by votdev** [comment]
Is this script importing this SSL certificate into the OMV database and deploys it afterwards? If not, then you're working around OMV and should not wonder that it does not work as expected.

**Comment by donhwy** [comment]
The script does replace the certs directly. How can I write a script to insert them into the database?

**Comment by votdev** [comment]
You can write a SSL certificate to the database using the `CertificateMgmt::set` RPC. You can use `omv-rpc -u admin 'CertificateMgmt' 'set' <JSON>` to do that. Alternatively you can use `omv-confdbadm update conf.system.certificate.ssl <data>` to do that.

In both cases you need to know the `uuid` of the database object that you want to modify.

Useful links:
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/certificatemgmt.inc#L127
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/datamodels/rpc.certificatemgmt.json#L3
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/datamodels/conf.system.certificate.ssl.json

**Comment by PrplHaz4** [comment]
This seems like it is becoming an increasingly common use case (automatically rotating let's encrypt certs somewhat frequently) - not sure what a feature request should look like.

If it's between full LE support or more simply, the ability to detect an updated cert and overwrite the database entry, I would prefer the latter

**Comment by votdev** [comment]
> This seems like it is becoming an increasingly common use case (automatically rotating let's encrypt certs somewhat frequently) - not sure what a feature request should look like.
> 
> If it's between full LE support or more simply, the ability to detect an updated cert and overwrite the database entry, I would prefer the latter

This seems to me an issue for the `Let's Encrypt` plugin and should be reported here: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-letsencrypt/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by donhwy** [comment]
I have an interactive script to update my wildcard cert in another vm. The script then updates a number of vm's. I will look into your advice above next time I need to redo certs. Thanks
