### ISSUE TITLE
Impossible to apply some changes

### ISSUE THREAD

**Issue by lucajust** [openmediavault/openmediavault#845]
### Hi to all, I have a problem with my OMV machine. After routine updates, today it stop to apply some change from GUI.

For example, when i try to create a NFS shared folder and confirm, this is the error update. I'm totally newbie and i doesn't know how to solve. 
```
> Errore #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color monit 2>&1' with exit code '1': debian:
    Data failed to compile:
>----------
>    Rendering SLS 'base:omv.deploy.monit.default' failed: Jinja error: tls: Invalid value '0', allowed values are 'none, ssl, starttls, auto'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 498, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 37, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 39, in get
    objs = db.get(id_, identifier)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 724, in execute
    self._response = self._elements_to_object(elements)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 485, in _elements_to_object
    result.validate()
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 235, in validate
    self.model.validate(self.get_dict())
  File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 200, in validate
    self.schema.validate(data)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 170, in validate
    self._validate_type(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 224, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 195, in _validate_type
    self._validate_object(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 300, in _validate_object
    self._check_properties(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 508, in _check_properties
    self._validate_type(value[propk], propv, path)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 224, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 204, in _validate_type
    self._validate_string(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 279, in _validate_string
    self._check_enum(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 468, in _check_enum
    % (valuev, ", ".join(schema['enum'])),
openmediavault.json.schema.SchemaValidationException: tls: Invalid value '0', allowed values are 'none, ssl, starttls, auto'.

; line 37

---
[...]
# http://www.debianadmin.com/monitoring-debian-servers-using-monit.html
# http://www.uibk.ac.at/zid/systeme/linux/monit.html
# http://wiki.ubuntuusers.de/Monit
# http://viktorpetersson.com/2010/07/09/setting-up-monit-to-monitor-apache-and-postgresql-on-ubuntu

{% set email_config = salt['omv_conf.get']('conf.system.notification.email') %}    <======================

configure_default_monit:
  file.managed:
    - name: "/etc/default/monit"
    - contents:
[...]
--- in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusoI...', '/tmp/bgoutputR7...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

**Comment by votdev** [comment]
Your database is invalid. You need to run `omv-confdbadm migrate conf 5.2.0` to fix it.

**Comment by votdev** [comment]
I close the issue because running the mentioned command should fix it.

**Comment by lucajust** [comment]
> Your database is invalid. You need to run `omv-confdbadm migrate conf 5.2.0` to fix it.

Thanks for the help, I obtain this output:

root@NASfichera:~# omv-confdbadm migrate conf 5.2.0
  Running migration conf_5.2.0
  Running migration conf_5.5.0
  Running migration conf_5.5.3
WARNING: The node 'clients' already exists at XPath '/config/system/time/ntp'.

**Comment by lucajust** [comment]
now the error is:

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color nfs 2>&1' with exit code '1': debian: ---------- ID: configure_default_nfs-kernel-server Function: file.managed Name: /etc/default/nfs-kernel-server Result: True Comment: File /etc/default/nfs-kernel-server is in the correct state Started: 22:08:01.674238 Duration: 93.16 ms Changes: ---------- ID: configure_nfsd_exports Function: file.managed Name: /etc/exports Result: True Comment: File /etc/exports updated Started: 22:08:01.767599 Duration: 63.377 ms Changes: ---------- diff: --- +++ @@ -3,5 +3,7 @@ # /etc/exports: the access control list for filesystems which may be exported # to NFS clients. See exports(5). +/export/Storage 192.168.1.2/200(fsid=1,ro,subtree_check,insecure) # NFSv4 - pseudo filesystem root +/export 192.168.1.2/200(ro,fsid=0,root_squash,no_subtree_check,hide) ---------- ID: start_rpc_statd_service Function: service.running Name: rpc-statd Result: True Comment: The service rpc-statd is already running Started: 22:08:01.848995 Duration: 116.111 ms Changes: ---------- ID: start_nfs_kernel_server_service Function: service.running Name: nfs-kernel-server Result: False Comment: Job for nfs-server.service canceled. Started: 22:08:02.018776 Duration: 3807.462 ms Changes: Summary for debian ------------ Succeeded: 3 (changed=1) Failed: 1 ------------ Total states run: 4 Total run time: 4.080 s

**Comment by votdev** [comment]
What is the output of `systemctl status nfs-kernel-server`?

**Comment by lucajust** [comment]
root@NASfichera:~# systemctl status nfs-kernel-server
● nfs-server.service - NFS server and services
   Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-11-09 22:17:44 CET; 9min ago
  Process: 1042 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=1/FAILURE)
  Process: 1047 ExecStopPost=/usr/sbin/exportfs -au (code=exited, status=0/SUCCESS)
  Process: 1049 ExecStopPost=/usr/sbin/exportfs -f (code=exited, status=0/SUCCESS)

nov 09 22:17:44 NASfichera.local systemd[1]: Starting NFS server and services...
nov 09 22:17:44 NASfichera.local exportfs[1042]: exportfs: Invalid prefix `200' for 192.168.1.2/200
nov 09 22:17:44 NASfichera.local exportfs[1042]: exportfs: Invalid prefix `200' for 192.168.1.2/200
nov 09 22:17:44 NASfichera.local systemd[1]: nfs-server.service: Control process exited, code=exited, status=1/FAILURE
nov 09 22:17:44 NASfichera.local systemd[1]: nfs-server.service: Failed with result 'exit-code'.
nov 09 22:17:44 NASfichera.local systemd[1]: Stopped NFS server and services.

**Comment by votdev** [comment]
You've configured your NFS share incorrect: `NASfichera.local exportfs[1042]: exportfs: Invalid prefix 200' for 192.168.1.2/200`

**Comment by lucajust** [comment]
> You've configured your NFS share incorrect: `NASfichera.local exportfs[1042]: exportfs: Invalid prefix 200' for 192.168.1.2/200`

ok thanks, now it work correctly
