### ISSUE TITLE
Locking issue in SMB recycle bin cleanup

### ISSUE THREAD

**Issue by eMPai-git** [openmediavault/openmediavault#846]
### Description of issue

So the locking issue in SMB recycle bin cleanup resurfaced for me.

I do have 3 smb shares set up in the webgui with recycle bins that should clean after 30 days. But that does not happen.
Each running of `cron.daily` creates a `samba-recycle-*` lockfile in folder `/run/` which does not get removed.

Example:

- day 1 - `/run/samba-recycle-1`
- day 2 - `/run/samba-recycle-1` and `/run/samba-recycle-2`
- day 3 - `/run/samba-recycle-1` and `/run/samba-recycle-2` and `/run/samba-recycle-3`

Manually removing the lockfiles doesn't help. They get created one by one during the next runnings of `cron.daily`.

Removing the lockfiles and manually executing the recycle scripts in `/var/lib/openmediavault/cron.d/` did clean the recycle bin (which was much, because I didn't notice the issue for a year).

### Steps to reproduce issue

I do not have any debug logs as there are no log information about openmediavault-samba-recycle.

I did:

- a fresh install of openmediavault 5.5.12 taking the _Installation on Debian_ installation variant
- choosed an existing RAID from old OMV 4 installation as file storage
- created the SMB shares in the webgui with recycle bins and cleaning after 30 days
- wondered why no cleanup happend and noticed the lockfiles

### Versions report

I started using openmediavault with version 4.1.27 and updating till 4.1.35.
Then I upgraded the machine to openmediavault 5.5.12 (fresh install) which is the version I'm running now.

### Workaround

After searching the forums and github I wanted to create a scheduled job which removes the lockfiles and executes the recycle scripts in `/var/lib/openmediavault/cron.d/`. But I was not happy with that solution.

I read through [Why doesn't set -e (or set -o errexit, or trap ERR) do what I expected?](https://mywiki.wooledge.org/BashFAQ/105) trying to understand `set -e` in the `samba-recycle-*` scripts.

I did notice that the fix from d903f25 is not included in `openmediavault/deb/openmediavault/srv/salt/omv/deploy/samba/files/cron-recyclebin-script.j2`.

So I removed the ` >/dev/null 2>&1` part in my scripts and they are working as expected since a week.

I do sometimes check back if the cleanup happend with `find /path/to/.recycle -amin +43200` and everything is fine.

### Questions

1. Could this issue be related to `set -e` and the lockfile if-statement?
2. Why is the fix from d903f25 not included in OMV 5?

**Comment by votdev** [comment]
> Why is the fix from d903f25 not included in OMV 5?

I don't know. But i've included the changes in `openmediavault 5.5.17`. Thanks for investigating this issue.

**Comment by eMPai-git** [comment]
Thank you. Glad I could help.
