### ISSUE TITLE
OMV5 not surviving first reboot

### ISSUE THREAD

**Issue by Kasperx** [openmediavault/openmediavault#850]
Hi

sry, double post, but here for 1st time...

[https://forum.openmediavault.org/index.php?thread/31980-omv5-not-surviving-first-reboot/](url)

I would like to ask for some help.
Thanks

**Comment by mi-hol** [comment]
please wait for advise from forum before opening an issue

**Comment by Kasperx** [comment]
Sry for commenting a closed issue.
@mi-hol which forum do u mean? This is 1st issue on that problem. The omv-forum-issue was (also) not answered by now.

**Comment by mi-hol** [comment]
the quoted forum thread had the solution  "Commented out all drives in /etc/fstab (but not system drive xD) and my system booted as expected." added on Nov 11th 2020.
if this doesn't work for you please continue the forum thread

**Comment by Kasperx** [comment]
Thx for answer
I continued forum thread but without further reaction there. I found the same (?) project here on github and hope to find more interest for that problem.
The described solution is a temporary workaround by commenting out the line in main system file. Therefore it should not be a recommented solution. I don't know whether problem level is on omv or debian as fstab file is a main debian file.

**Comment by geoffae** [comment]
> Thx for answer
> I continued forum thread but without further reaction there. I found the same (?) project here on github and hope to find more interest for that problem.
> The described solution is a temporary workaround by commenting out the line in main system file. Therefore it should not be a recommented solution. I don't know whether problem level is on omv or debian as fstab file is a main debian file.

What's your username on the forum

**Comment by Kasperx** [comment]
There its 'titango', the last answer.
Ups did I read wrong? Well the accepted answer there is the temporary solution with `/etc/fstab`. I don't understand why its closed (is it?).

**Comment by geoffae** [comment]
> There its 'titango', the last answer.
> Ups did I read wrong? Well the accepted answer there is the temporary solution with `/etc/fstab`. I don't understand why its closed (is it?).

Yes, because you haven't stated or outlined your problem just reference a thread on the forum, the forum post is about mergerfs. Which if a drives fails within the pool a server will fail to start, the solution was to add the 'no fail' flag to the pools mount point, that should not be necessary, but it's the solution.
Your comment in that thread thanks one of the users then proceeds to say that you had to comment everything from /etc/fstab which in itself made no sense. As you said it solved your problem, why would someone reply? 
If your not using mergerfs I would suggest leaving this thread alone and that forum thread and try reposting with information regarding your specific problem.

**Comment by Kasperx** [comment]
Thanks for answers.

Maybe I lost the focus for main aspect of mergefs. I can start a new thread if you are more happy with that. Just for understanding, I will continue here.

- One of (temporary(?)) solutions for mergefs problem to not boot:
adding `no-fail` (?) to `/etc/fstab` file.  Well, omv5 does it already by default, so its just a check. If it works it would be a full solution in my opinion (=not temporary, but permament). Unfortunately it doesn't work for my system.

- other temporary solution:
uncomment problem lines in `/etc/fstab`
Temporary, because why should I "fix" a main file in debian thats finally handled by 3rd-party-system = omv.? Btw I need to activate lines after boot to be able to use the problem-drives. Otherwise system doesnt know them.
