### ISSUE TITLE
Add a new drive/path to an existing mergerfs folder NOT working

### ISSUE THREAD

**Issue by westforest** [openmediavault/openmediavault#853]
### Description of issue/question
I added a new path on a new drive to an existing mergerfs folder via the webUI "mergerfs folders" tab "Edit". It asked me to either remount or reboot the machine. I did a reboot. But nothing seems to be changed. I created some files in the new path, and they don't show up in the mergerfs folder, which still shows the old capacity--a sum of old drives.

When I check /etc/fstab I see the fuse mount entry was not updated with the new drive-path. It's still pointing to the same old paths.

OK, I ended up manually editing the fuse.mergerfs entry in the fstab file to include the newly added path, and remount it to see it take effect. Apparently the omv's config.xml took in the change I made from the WebUI, but didn't do anything to populate the downstream changes.

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

### Versions report
5.5.16-1 (Usul)

**Comment by votdev** [comment]
The issue may relate to https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-mergerfsfolders, but i try to help.

After changing the settings in the UI, have you pressed the yellow `Apply` button? I'm not familar with the plugin, but accordingly to the sources running `omv-salt deploy run fstab` manually should update the configuration.

**Comment by westforest** [comment]
The issue is I don't see the the yellow Apply button popping up as I see for all other configs changes. Instead, what I only see is an Information popup: "NOTE: The changes won't take effect until you've restarted the system or manually remounted the filesystem.".

**Comment by westforest** [comment]
I ran " sudo omv-salt deploy run fstab" to successfully upate the fstab. I just had to run "sudo unmount <mnt>; sudo mount <mnt>" for it to pick up the new mount configs.

**Comment by votdev** [comment]
@ryecoaaron Any idea what is going wrong here?

**Comment by ryecoaaron** [comment]
looks like it only updates the mntent entry if it is a new pool.  I will have to fix that.

**Comment by ryecoaaron** [comment]
nevermind.  The branches aren't stored in the mntent entry.  I just edited a pool and added a branch.  It worked fine.  It popped up the yellow bar and updated fstab.  An edit will only trigger this if the name or paths changes.  Not sure what is happening.  I would like to see the before and after settings.

**Comment by mi-hol** [comment]
@westforest did you see ryecoaaron request for more information?

**Comment by mi-hol** [comment]
no feedback received, closing
