### ISSUE TITLE
omv runing on raspberry pi

### ISSUE THREAD

**Issue by chaoxiaodi** [openmediavault/openmediavault#856]
Do you have a plan for provide omv iso image at raspberry pi; 
### Steps to reproduce issue
(Include debug logs if possible and relevant.)

**Comment by votdev** [comment]
RasPi does not need ISO images, instead so called images are used. It would be nice to see out-of-the-box images, but this requires contributors from the community they will build and maintain such images. At the moment the best solution is to use the official Raspberry images and install OMV on top.

A guide can be found [here](https://forum.openmediavault.org/index.php?thread/28789-installing-omv5-on-raspberry-pi-s-armbian-sbc-s-i386-32-bit-platforms/).

**Comment by mi-hol** [comment]
Reminder: Link to "New User Guide" should be added to README.md (together with other enhancements)

**Comment by mi-hol** [comment]
Apologize don't understand the meaning of "until OMV works in chroot, images can't really be built the proper way". Would appreciate a pointer to a doc explaining it further or a comment here :)

**Comment by ryecoaaron** [comment]
In order to build an OS image, it has to be in its own "environment".  chroot is kind of like a docker container.  This "environment" can be built in chroot or docker.  Since neither is a real device, OMV's saltstack calls fail.  Therefore, a fully automated OMV image builder is not really possible.  But that doesn't really matter since Armbian and the RPi foundation provide images that you can easily run the install script on.

**Comment by mi-hol** [comment]
so an approach like used on https://github.com/guysoft/CustomPiOS wouldn't work for OMV, right?

**Comment by ryecoaaron** [comment]
No. OMV would still have to be installed in chroot or docker which does not work.

**Comment by ryecoaaron** [comment]
I don’t think maintaining many images is a good idea either. The install script is working well.

**Comment by mi-hol** [comment]
@chaoxiaodi could you please update issue title to "plan to provide OMV image for raspberry pi"?

**Comment by mi-hol** [comment]
@votdev for OMV6 are you considering to obsolete installation via ISO image?

**Comment by mi-hol** [comment]
my question was raised to end the current confusion about how to install OMV.
I.e. people still use the abandoned ARMBIAN images found on SourceForge, see forum post [here](https://forum.openmediavault.org/index.php?thread/37827-recommended-image-for-odroid-hc2/&postID=277186#post277186)

**Comment by votdev** [comment]
> @votdev for OMV6 are you considering to obsolete installation via ISO image?

Why should i do that, ISO images are the way to go to install the OS on a AMD64 system.

> my question was raised to end the current confusion about how to install OMV.
> I.e. people still use the abandoned ARMBIAN images found on SourceForge, see forum post [here](https://forum.openmediavault.org/index.php?thread/37827-recommended-image-for-odroid-hc2/&postID=277186#post277186)

If the community want images for that platform, then they have to contribute it. That's how open source works.

**Comment by ryecoaaron** [comment]
I don't see a problem with different install methods on different platforms since they are already very different.  And as I have mentioned before, pre-made images were much more problematic than the install script has been.  The install script helps users who install Debian first.

**Comment by votdev** [comment]
> I don't see a problem with different install methods on different platforms since they are already very different. And as I have mentioned before, pre-made images were much more problematic than the install script has been. The install script helps users who install Debian first.

I also prefer this way. Pre-made images delivered by the OMV project requires contributors that maintain these images.

**Comment by mi-hol** [comment]
so both of you prefer the install script approach (as it requires far less effort than creating an ISO Image).
Linked to the conversation on [simplifying install documentation here](https://github.com/openmediavault/openmediavault-docs/issues/79)
I'd like to ask again: Shall installation of OMV6 stick to install script approach as standard method?

**Comment by votdev** [comment]
> I'd like to ask again: Shall installation of OMV6 stick to install script approach as standard method?

This depends on the platform. For AMD64 an installation via ISO is the standard procedure IMO, ARM based devices are normally installed via flashing an image. Until we do not have contributors that maintain OMV builds for those devices, the installation is based on Raspbian and other images + @ryecoaaron install scripts.

**Comment by mi-hol** [comment]
For a good first user experience, does it help to have to consider platform specifics?

**Comment by votdev** [comment]
> For a good first user experience, does it help to have to consider platform specifics?

I do not understand the question or what you're getting at. Could you please explain it more detailed.

**Comment by mi-hol** [comment]
@votdev its a complex issue that requires about 1 hour time in order to get the same understanding of context and allow for informed decision making later.
From my experience it seems impossible to achieve this via written communication only.
An online session with screen sharing and discussion is what I can offer.

**Comment by mi-hol** [comment]
I still stand to my offer.
