### ISSUE TITLE
Update the website to also show BTRFS support

### ISSUE THREAD

**Issue by claell** [openmediavault/openmediavault#857]
When I came around OMV today I browsed the website to look which features it supports: https://www.openmediavault.org/features.html.

Currently it does not list BTRFS for supported file systems. However, reading forum posts and issues here, it seems that it is supported. Is there a reason why it is not listed on the website, or has that just slipped through?

**Comment by yllekz** [comment]
It's supported partially but more advanced features like the snapshots are not supported right now.

Check out [this page for details.](https://openmediavault.readthedocs.io/en/5.x/administration/storage/filesystems.html)

**Comment by claell** [comment]
Ah, alright. That makes kind of sense. As an interested possible user, I would prefer some details about this also on the features page, maybe with a link to the docs. I plan to use BTRFS and when seeing it not listed I feared it would not work with OVM.

**Comment by mi-hol** [comment]
planned for 6.x #101

**Comment by votdev** [comment]
> planned for 6.x #101

No, not at the moment, maybe 7.x.

**Comment by mi-hol** [comment]
Ok, to flag this fact for users, I'd suggest  add a new label "backlog" and assign it?

**Comment by mi-hol** [comment]
linked to #312

**Comment by votdev** [comment]
Website has been updated.
