### ISSUE TITLE
Can't create Stripe raid with two disks

### ISSUE THREAD

**Issue by k-matti** [openmediavault/openmediavault#859]
The newest OMV as VM on Esix, pass-through two disks, tried to wipe first and reboot but did not helped:

![image](https://user-images.githubusercontent.com/66017397/99851997-64b00e80-2b80-11eb-8436-795347a9e2b7.png)

```
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-mkraid /dev/md0 -l stripe -n 2 -N DATA /dev/sdb /dev/sdc 2>&1' with exit code '1': mdadm: chunk size defaults to 512K
mdadm: Defaulting to version 1.2 metadata
mdadm: RUN_ARRAY failed: Unknown error 524 in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/raidmgmt.inc(300): OMV\System\Process->execute()
#1 [internal function]: Engined\Rpc\RaidMgmt->create(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('create', Array, Array)
#4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('RaidMgmt', 'create', Array, Array, 1)
#5 {main}
```

**Comment by votdev** [comment]
Have you tried to create the RAID in the CLI? Is this successful? It looks to me a problem with mdadm and not OMV.

**Comment by k-matti** [comment]
I haven't tried to use CLI, how should I know the command to use in CLI.

**Comment by votdev** [comment]
Searching with Google for 'mdadm: RUN_ARRAY failed: Unknown error 524' finds the ​below links. ​According to them your system and kernel do some different things as usual. You need to set the default layout for the array.

* https://www.linuxquestions.org/questions/linux-general-1/raid-arrays-not-assembling-4175662774/
* https://serverfault.com/questions/1017257/mdadm-error-524-when-assembling-array-configuration-reset-after-reboot​

**Comment by k-matti** [comment]
Ok, I am closing this.
Problem was because I wanted to create stripe raid with two disks with different size
