### ISSUE TITLE
Stuck at libc-bin when updating

### ISSUE THREAD

**Issue by LeducH** [openmediavault/openmediavault#862]
### Description of issue/question
I want to update my open media vault installation 

### Steps to reproduce issue
ssh  as root into the system and run the steps from [this](https://forum.openmediavault.org/index.php?thread/27909-omv-5-0-finally-out/&postID=219830#post219830) suggestion. 

The terminal is stuck at this screen now for about 8h. how can I debug this? or what seems to be the problem? 

```
$ wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/upgrade4to5 | sudo bash
...
The following packages were automatically installed and are no longer required:
  containerd.io docker-ce docker-ce-cli imagemagick-6-common liblqr-1-0 libmagickcore-6.q16-3
  libmagickwand-6.q16-3 php-curl php-imagick php7.0-curl
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  openmediavault-docker-gui*
0 upgraded, 0 newly installed, 1 to remove and 95 not upgraded.
4 not fully installed or removed.
After this operation, 688 kB disk space will be freed.
Setting up libc-bin (2.24-11+deb9u4) ...
```

### Versions report
```
$ uname -r
4.19.0-0.bpo.6-amd64


$ apt show openmediavault 
Package: openmediavault
Version: 4.1.36-1
Priority: optional
Section: admin
```

**Comment by votdev** [comment]
You need to report that at https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg.

**Comment by LeducH** [comment]
Sorry my bad.
