### ISSUE TITLE
Can't login with Firefox for Android

### ISSUE THREAD

**Issue by alfonder** [openmediavault/openmediavault#864]
### Description of issue/question
Mobile Firefox after successful login jumps back to login page.
Mobile Chrome on the same device with the same host works as expected.
### Steps to reproduce issue
- Open OMV web-interface in mobile Firefox
- Enter admin credentials
- No error reported
- "Loading, please wait" message appears
- Login page displayed again

Clearing the site cache/cookies doesn't help.
### Versions report
Firefox 83.0 on Android 10 (OnePlus 7 Pro)

$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ cat /etc/issue
openmediavault 5.5.17-2 (Usul) \n \l

**Comment by votdev** [comment]
Do you see a error message in `/var/log/nginx/openmediavault-webgui_error.log` or `/var/log/php7.3-fpm.log`?

**Comment by alfonder** [comment]
Yes, I see multiple error messages in /var/log/syslog:

Dec  4 06:28:45 pampa php: Unknown or deprecated time zone [tz=]. Please reconfigure your time zone settings.
Dec  4 06:28:45 pampa omv-engined[10761]: Unknown or deprecated time zone [tz=]. Please reconfigure your time zone settings.

**Comment by votdev** [comment]
Please go to the `System | Date & Time` page and select the correct time zone. Debian installer or other images may set an incorrect time zone that PHP does not know about.

**Comment by alfonder** [comment]
Thank you for advice. Now error messages are gone form /var/log/syslog .
Nevertheless Firefox keeps jumping back to login page after successful login. So the issue still exists.

**Comment by votdev** [comment]
I'm currently out of ideas, sorry. If it is because of PHP session issues, then an error is reported in the UI and syslog. If this is missing, hmmm...

**Comment by buster** [comment]
I have the same issue. Firefox nightly for Android and I can login, and it immediately redirects to login. I do receive an email that someone logged in as admin, so the login seems to be successful,but that doesn't help if you look at the login immediately again.

**Comment by buster** [comment]
I juts tested with opera touch and opera works, so it seems to be related to Firefox for mobile.

**Comment by mi-hol** [comment]
external issue unrelated to OMV

**Comment by votdev** [comment]
I also think this is not related to OMV because otherwise syslog or the UI would show an error. The only think that comes to my mind is [this issue](https://github.com/openmediavault/openmediavault/issues/884) that has been fixed in `openmediavualt 5.5.18`. But if that would be the case, the UI should display a warning message what does not happen in your case.

**Comment by karnasw** [comment]
Hi, I created an issue report on Firefox github, but i don't have external IP to create temporary server for testing purposes. Can someone help?

**Comment by firewire10000** [comment]
I created a forum [here](https://forum.openmediavault.org/index.php?thread/36777-accessing-webgui-with-firefox-mobile/) because I too couldn't access OMV on Firefox for Android yet the desktop version works perfectly fine. The last version of Firefox that's available before they re-worked it was 68.11.0. I have installed the APK directly from their website and I can confirm that the old version of Firefox allows me to login successfully into OMV.

All the Firefox for Android releases can be found [here](https://archive.mozilla.org/pub/mobile/releases/) The version I have used is [android-aarch](https://archive.mozilla.org/pub/mobile/releases/68.11.0/android-aarch64/)

**Comment by firewire10000** [comment]
> Hi, I created an issue report on Firefox github, but i don't have external IP to create temporary server for testing purposes. Can someone help?

Someone could spin up a Digital Ocean VPS, install Debian, run the OMV install script, setup a dummy account and then allow webGUI access to port 80/443.

**Comment by votdev** [comment]
> I may have just found a potential cause to the problem. I managed to login once on the 68.11.0 version of Firefox for Android. I switched between a few apps on my phone sending the app into the background. As Android does to save memory sometimes, the page left in Firefox reloads itself when you switch back to the app. This caused the page to refresh sending me back to the login screen. Upon entering my login details and what I thought would be another successful login, I was presented with the following error code:
> 
> `Error #0: OMV\HttpErrorException: Invalid User-Agent. in /usr/share/php/openmediavault/session.inc:198 Stack trace: #0 /usr/share/php/openmediavault/session.inc(208): OMV\Session->validateUserAgent() #1 /var/www/openmediavault/index.php(34): OMV\Session->validate() #2 {main}`
> 
> Immediately after this I switch to the Edge (Chromium based) browser on Android with the same login credentials and was able to login without a hiccup.

OMV stores the HTTP_USER_AGENT at login and compares it while processing every request. If the above mentioned error occurs, then this means that Firefox sends a different HTTP_USER_AGENT after the app is going into the foreground again. This looks like a bug in Firefox to me.

**Comment by karnasw** [comment]
Firefox developer write me that in https://github.com/mozilla-mobile/fenix/issues/17280: 
I tested on Firefox desktop and I see the same issue, when I switch the user agent to Chrome I see the panel without redirects. This is an issue for the developers of openmediavault they are intentionally redirecting when they find Firefox's user agent, I think you could reopen the initial issue openmediavault/openmediavault#864 and let them know that the website is not working on Firefox as they are allowing Firefox's user agent.

**Comment by votdev** [comment]
If the HTTP_USER_AGENT switches within a session then this might be a security issue. Because of that OMV exactly checks and prevents this.

**Comment by Amejia481** [comment]
> If the HTTP_USER_AGENT switches within a session then this might be a security issue. Because of that OMV exactly checks and prevents this. This is all meant to increase security by making it hard for somebody to hijack active sessions.

👋🏽  to clarify the issue is reproducible in Firefox desktop and Android, even without switching the user agent.  @votdev  please try to login in Firefox desktop and you will be able to see the issue.

I did multiple tests, but I can't login when using Firefox (Android or Desktop) but if I open a new session and change the user agent to Chrome I'm able to login.

**Comment by votdev** [comment]
> 👋🏽 to clarify the issue is reproducible in Firefox desktop and Android, even without switching the user agent. @votdev please try to login in Firefox desktop and you will be able to see the issue.

I can not reproduce it. I always use Firefox since years, so i should have realized that behaviour.

**Comment by Amejia481** [comment]
> > 👋🏽 to clarify the issue is reproducible in Firefox desktop and Android, even without switching the user agent. @votdev please try to login in Firefox desktop and you will be able to see the issue.
> 
> I can not reproduce it. I always use Firefox since years, so i should have realized that behaviour.
> 
> The question is, why should the HTTP_USER_AGENT change during a session? I do not see any requirement to do that.

I was able to reproduce in Firefox nightly (desktop)  yesterday, now I'm not able to reproduce, back to the whiteboard


> The question is, why should the HTTP_USER_AGENT change during a session? I do not see any requirement to do that. 

I'm not aware that we are changing the user agent, I switched it while I was testing to see if the issue was related to a webcompat issue.

**Comment by ryecoaaron** [comment]
Maybe an Firefox add-on is causing your problem?  I use chrome and firefox on Linux and Windows (safari on iOS) and have never had a login issue.

**Comment by Amejia481** [comment]
> > 👋🏽 to clarify the issue is reproducible in Firefox desktop and Android, even without switching the user agent. @votdev please try to login in Firefox desktop and you will be able to see the issue.
> 
> I can not reproduce it. I always use Firefox since years, so i should have realized that behaviour.
> 
> The question is, why should the HTTP_USER_AGENT change during a session? I do not see any requirement to do that.

@votdev is there away for you to log the two possible HTTP_USER_AGENTs that could be causing the issue?

**Comment by votdev** [comment]
> > > 👋🏽 to clarify the issue is reproducible in Firefox desktop and Android, even without switching the user agent. @votdev please try to login in Firefox desktop and you will be able to see the issue.
> > 
> > 
> > I can not reproduce it. I always use Firefox since years, so i should have realized that behaviour.
> > The question is, why should the HTTP_USER_AGENT change during a session? I do not see any requirement to do that.
> 
> @votdev is there away for you to log the two possible HTTP_USER_AGENTs that could be causing the issue?

Sure, that's easy. The related code is [this](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/session.inc#L198).

Open `/usr/share/php/openmediavault/session.inc` and modify line 198 to
```
throw new HttpErrorException(401, sprintf("Invalid User-Agent. session=%s HTTP_USER_AGENT=%s", $_SESSION['useragent'], $_SERVER['HTTP_USER_AGENT']));
```

Thanks for digging into the issue.

**Comment by Amejia481** [comment]
Thanks for all the details, to be honest I'm not familiar with openmediavault or its stack to do the modification will take a long time for me as I will have to install and setup everything vs somebody that already has the environment and know what to build it, if you don't mind would be able to do the modification and report the result. Thanks in advance 🙏🏽

**Comment by ryecoaaron** [comment]
# from the command line
sudo systemctl stop openmediavault-engined
# change the line Volker mentioned above in /usr/share/php/openmediavault/session.inc
sudo omv-engined -df
# watch for output showing user agents

**Comment by knox** [comment]
I can't login with Firefox 85.1.2 from my Android into OMV 5.5.23 either and found that pending discussion here. So i've tried to figure out these changing user agents in question but this does not seem to be the case.

Here's an anonymized log of the login attempt:
```
omv-engined[31826]: SIGCHLD received ...
omv-engined[31826]:
omv-engined[31834]: Child process forked (pid=31834)
omv-engined[31834]:
omv-engined[31834]: Executing RPC (service=UserMgmt, method=authUser, params={"username":"knox","password":"xxxxxxxxxxx"}, context={"username":"knox","role":1,"_SERVER":{"SERVER_PROTOCOL":"HTTP\/1.1","GATEWAY_INTERFACE":"CGI\/1.1","SERVER_SOFTWARE":"nginx\/1.14.2","REMOTE_ADDR":"::ffff:192.168.x.y","REMOTE_PORT":"40878","SERVER_ADDR":"::ffff:192.168.x.y","SERVER_PORT":"443","SERVER_NAME":"openmediavault-webgui","HTTPS":"on","REDIRECT_STATUS":"200","HTTP_HOST":"example.org","HTTP_ORIGIN":"https:\/\/example.org","HTTP_USER_AGENT":"Mozilla\/5.0 (Android 11; Mobile; rv:85.0) Gecko\/85.0 Firefox\/85.0","HTTP_CONTENT_TYPE":"application\/json","HTTP_REFERER":"https:\/\/example.org\/"}}) ...
omv-engined[31834]:
omv-engined[31834]: RPC response (service=UserMgmt, method=authUser): {"response":{"authenticated":true,"username":"knox","permissions":{"role":"admin"}},"error":null}
omv-engined[31834]:
omv-engined[31826]: SIGCHLD received ...
omv-engined[31826]:
omv-engined[31826]: Child (pid=31834) terminated with exit code 0
omv-engined[31826]:
```

**Comment by Amejia481** [comment]
Thanks @knox for the logs.

@votdev looking to the logs above seem to be the same user, right? Would you mind confirming? I just want to help to pin point where is the issue.

**Comment by votdev** [comment]
> Thanks @knox for the logs.
> 
> @votdev looking to the logs above seem to be the same user, right? Would you mind confirming? I just want to help to pin point where is the issue.

Yes, one line is the request and the other the response send back.

**Comment by firewire10000** [comment]
I've created a script [here](https://gist.githubusercontent.com/firewire10000/098216932ed6bac981d9a8c0d47533f4/raw/20c09c555e48576666dc6a5bbd46662b07c84957/OMV_Web_GUI_%2520Firefox_fix.sh) if anyone wants a temporary fix

**Comment by karnasw** [comment]
> I've created a script [here](https://gist.githubusercontent.com/firewire10000/098216932ed6bac981d9a8c0d47533f4/raw/20c09c555e48576666dc6a5bbd46662b07c84957/OMV_Web_GUI_%2520Firefox_fix.sh) if anyone wants a temporary fix

Thanks, it works.
