### ISSUE TITLE
Timesever Change not work

### ISSUE THREAD

**Issue by votdev** [openmediavault/openmediavault#865]
PROXMOX Kernel + ZFS

Timesever Change not work:

Fehler #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color chrony 2>&1' with exit code '1': QNAPNAS:
----------
          ID: configure_chrony
    Function: file.managed
        Name: /etc/chrony/chrony.conf
      Result: True
     Comment: File /etc/chrony/chrony.conf is in the correct state
     Started: 23:04:57.731881
    Duration: 37.605 ms
     Changes:
----------
          ID: start_chrony_service
    Function: service.running
        Name: chrony
      Result: False
     Comment: Job for chrony.service failed because the control process exited with error code.
              See "systemctl status chrony.service" and "journalctl -xe" for details.
     Started: 23:04:57.778689
    Duration: 58.435 ms
     Changes:

Summary for QNAPNAS
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:  96.040 ms in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatuscE...', '/tmp/bgoutputxg...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}

**Comment by votdev** [comment]
What is the output of `systemctl status chrony` and `journalctl -u chrony`?

**Comment by mi-hol** [comment]
is this issue a result of a forum thread?

**Comment by votdev** [comment]
No, @Soliver84 wanted to open an issue, but erroneously opened a PR. I created the issue based on the information given in the PR.

**Comment by mi-hol** [comment]
@votdev is it still an open issue?

**Comment by votdev** [comment]
I don't know, requested info to get more details.

**Comment by mi-hol** [comment]
closing due to no response
