### ISSUE TITLE
PROXMOX  and Portrainer 2.0 and yacht not working.! OMV 5.5.17-3

### ISSUE THREAD

**Issue by Soliver84** [openmediavault/openmediavault#866]
PROXMOX  and Portrainer 2.0 and yacht not working.!
BUG:
https://forum.openmediavault.org/index.php?thread/31106-portainer-docker-issues/#post257215

Has anyone reported the error that it will be fixed?

I have the error.

Because: Proxmox for ZFS.

Portainer and yacht don't work! I don't let the pages open!

LOG PROXMOX install:

Supported kernel found

Get:1 file:/var/cache/openmediavault/archives InRelease

Ign:1 file:/var/cache/openmediavault/archives InRelease

Get:2 file:/var/cache/openmediavault/archives Release

Ign:2 file:/var/cache/openmediavault/archives Release

Get:3 file:/var/cache/openmediavault/archives Packages

Ign:3 file:/var/cache/openmediavault/archives Packages

Get:4 file:/var/cache/openmediavault/archives Translation-en

Ign:4 file:/var/cache/openmediavault/archives Translation-en

Get:3 file:/var/cache/openmediavault/archives Packages

Ign:3 file:/var/cache/openmediavault/archives Packages

Get:4 file:/var/cache/openmediavault/archives Translation-en

Ign:4 file:/var/cache/openmediavault/archives Translation-en

Get:3 file:/var/cache/openmediavault/archives Packages

Ign:3 file:/var/cache/openmediavault/archives Packages

Get:4 file:/var/cache/openmediavault/archives Translation-en

Ign:4 file:/var/cache/openmediavault/archives Translation-en

Get:3 file:/var/cache/openmediavault/archives Packages

Ign:3 file:/var/cache/openmediavault/archives Packages

Get:4 file:/var/cache/openmediavault/archives Translation-en

Ign:4 file:/var/cache/openmediavault/archives Translation-en

Get:3 file:/var/cache/openmediavault/archives Packages

Ign:3 file:/var/cache/openmediavault/archives Packages

Get:4 file:/var/cache/openmediavault/archives Translation-en

Ign:4 file:/var/cache/openmediavault/archives Translation-en

Get:3 file:/var/cache/openmediavault/archives Packages

Ign:3 file:/var/cache/openmediavault/archives Packages

Get:4 file:/var/cache/openmediavault/archives Translation-en

Ign:4 file:/var/cache/openmediavault/archives Translation-en

Get:3 file:/var/cache/openmediavault/archives Packages

Get:4 file:/var/cache/openmediavault/archives Translation-en

Ign:4 file:/var/cache/openmediavault/archives Translation-en

Hit:5 http://linux.teamviewer.com/deb stable InRelease

Hit:6 http://security.debian.org/debian-security buster/updates InRelease

Hit:7 http://packages.openmediavault.org/public usul InRelease

Hit:8 https://download.docker.com/linux/debian buster InRelease

Hit:9 http://deb.debian.org/debian buster InRelease

Hit:10 http://download.proxmox.com/debian buster InRelease

Ign:11 https://dl.bintray.com/openmediavault-plugin-developers/usul buster InRelease

Hit:12 http://deb.debian.org/debian buster-updates InRelease

Hit:13 https://openmediavault.github.io/packages usul InRelease

Ign:14 https://dl.bintray.com/openmediavault-plugin-developers/usul-extras buster InRelease

Get:15 https://dl.bintray.com/openmediavault-plugin-developers/usul buster Release [4363 B]

Get:16 https://dl.bintray.com/openmediavault-plugin-developers/usul-extras buster Release [3538 B]

Fetched 7901 B in 1s (8885 B/s)

Reading package lists...

Reading package lists...

Building dependency tree...

Reading state information...

pve-headers-5.4 is already the newest version (6.3-1).

pve-headers is already the newest version (6.3-1).

pve-kernel-5.4 is already the newest version (6.3-1).

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Set 5.4.73-1-pve' as default... 0

Please reboot to use the new kernel.

Fertig.

Portainer install log:

Docker storage :: /var/lib/docker

Agent port:: 8000

Web port:: 9000

Yacht port:: 8001

arch :: amd64

option :: portainer

state :: install

extras :: 5.4.2

DNS OK.

Stopping portainer ...

portainer

Removing portainer ...

portainer

Removing portainer/portainer-ce image ...

Untagged: portainer/portainer-ce:latest

Untagged: portainer/portainer-ce@sha256:0ab9d25e9ac7b663a51afc6853875b2055d8812fcaf677d0013eba32d0bf0e0d

Deleted: sha256:a0a227bf03ddc8b88bbb74b1b84a8a7220c8fa95b122cbde2a7444f32dc30659

Deleted: sha256:5d8ccdb2e9be5d114307c980f04f6b9d9b8d7f6ebbb7a7c323d76525408e31eb

Deleted: sha256:dd4969f97241b9aefe2a70f560ce399ee9fa0354301c9aef841082ad52161ec5

Pulling and starting portainer/portainer-ce ...

8bfd307cdd665dbb7af62724008eb6f98411c15b7e36d7ff74d1b218ebf8a438

Fertig.

would be grateful for a workaround

@ryecoaaron Do you have an idea? get proxmox to run with portrainer 2.0?

Thanks

**Comment by votdev** [comment]
What exactly is the error here? I don't see any.

**Comment by ryecoaaron** [comment]
This isn't a bug.  Must be user error and I posted on the forum.

**Comment by Soliver84** [comment]
This is definitely not a user error,
BUG Instructions:
Install OMV on the latest debian
Install PROXMO kernel
reboot
Install ZFS
reboot
Install Docker
reboot
Install Portrainer
Reboot.
Portrainer does not boot no web GUI available.

why is this done immediately after all user errors .. what's that!

**Comment by ryecoaaron** [comment]
All the plugin does is execute a docker run command.  You tell me where the bug is there.
