### ISSUE TITLE
Question: open ports

### ISSUE THREAD

**Issue by Noonet1** [openmediavault/openmediavault#869]
### Description of issue/question
I have a fresh installation, with currently only running SSH and SMB services. 

When I scan OMV for ports I see that there are 5 ports open, 3 are expected; 22, 80 and 445. 

The other two ports that are open are 53 and 139, I don't think these are necessary for the services I run but I can't seem to find a way to close them nor can I find why these are open in the first place.

Hope someone can help me clarify what this is caused by and if there is a use for these ports being open and, if not, how to close them. Thanks in advance.

### Steps to reproduce issue
Scan ports of OMV host.

### Versions report
5.5.17-3

**Comment by votdev** [comment]
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by Noonet1** [comment]
> https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
> 
>     * 139 is used by SMB/CIFS.
> 
>     * 53 is DNS and is surely used by Avahi (Zeroconf)

Thanks! 

Isn't port 445 sufficient to run SMB? 

It still isn't clear to me why I would need to run Avahi, this is used for discovery, right? Is there a way to close this?

**Comment by Noonet1** [comment]
I know figured out both these ports are used for network discovery:

https://openmediavault.readthedocs.io/en/5.x/administration/general/network.html?highlight=avahi#service-discovery

However, I can't find these settings in the web UI, I'll look into this, thanks for now!

**Comment by votdev** [comment]
> It still isn't clear to me why I would need to run Avahi, this is used for discovery, right? Is there a way to close this?

Zeroconf is an essential functionality of OMV in Linux environments, so it can't be disabled. The only thing you can do is to manually disable service announcements via environment variables.

* https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/srv/salt/omv/deploy/avahi/services
* https://openmediavault.readthedocs.io/en/5.x/various/advset.html#environmental-variables
