### ISSUE TITLE
Mount point renamed

### ISSUE THREAD

**Issue by niko2** [openmediavault/openmediavault#87]
I have installed an omv4 instance on February with one disk and LVM.
XFS mount point is /srv/dev-disk-by-id-dm-name-DATA-test
Then, today (all updates have been done to the server), i try to extend the XFS. Logical volume is extended OK.
Wen i try to extend XFS, i get this error : 

```bash
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; xfs_growfs '/srv/6fd1dca3-2032-45b6-9678-a1f7ea6a8dae' 2>&1' with exit code '1': xfs_growfs: /srv/6fd1dca3-2032-45b6-9678-a1f7ea6a8dae is not a mounted XFS filesystem
```
=> It appears rezising job is using another device name.

This is the same device 
```bash
$ ls -l /dev/disk/by-id/dm-name-DATA-test 
lrwxrwxrwx 1 root root 10 avril 21 17:58 /dev/disk/by-id/dm-name-DATA-test -> ../../dm-0
$ ls -l /dev/disk/by-uuid/6fd1dca3-2032-45b6-9678-a1f7ea6a8dae 
lrwxrwxrwx 1 root root 10 avril 21 17:58 /dev/disk/by-uuid/6fd1dca3-2032-45b6-9678-a1f7ea6a8dae -> ../../dm-0
```
I use several OMVs (0.2.7, 1.x, 2.x 3.x) and I was a bit surprised that mount point was not uuid anymore on OMV4

Something should have changed for mount point naming policy, but not everywhere ?

Thank you !

**Comment by votdev** [comment]
Fixed in openmediavault 4.1.5, see https://github.com/openmediavault/openmediavault/commit/c963a3675a9f6dd2d7aa280d85bfcbe5dff79d5b.
