### ISSUE TITLE
Scheduled antivirus scan fails

### ISSUE THREAD

**Issue by maichai** [openmediavault/openmediavault#870]
### Description of issue/question

scheduled scans of the (only available) share always fail with error email saying:

```
Please wait, scanning shared folder <sharename> ...
ERROR: Could not connect to clamd on LocalSocket /run/clamav/clamd.ctl: Connection refused

----------- SCAN SUMMARY -----------
Infected files: 0
Total errors: 1
Time: 0.000 sec (0 m 0 s)
ERROR: The scan failed.
```

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

schedule AV scans in Services > Antivirus > Scheduled Jobs

### Versions report

OMV 5.5.17-3
Clamav plugin 5.0.11-1

**Comment by mi-hol** [comment]
Please continue conversation on https://forum.openmediavault.org/index.php?thread/36801-clamav-error-email-check-update/&postID=257273&highlight=clamd.ctl#post257273 first before opening an issue
