### ISSUE TITLE
Repository placeholders do not get resolved

### ISSUE THREAD

**Issue by rabelux** [openmediavault/openmediavault#872]
### Description of issue/question
I think it was the update to version 5.5.17 which broke the resolution of `%s %s` in the update management screen.
Used to work before.

### Steps to reproduce issue
Open update management in web-gui, see screenshot:
![image](https://user-images.githubusercontent.com/16120882/100926251-687a5400-34e3-11eb-8c4e-94da7b0f4694.png)

### Versions report
5.5.17-3 usul on raspian

**Comment by votdev** [comment]
Fixed in 5.5.18, see https://github.com/openmediavault/openmediavault/commit/77828a7c0362fb2568f1f6e15ce3cb6208c8c872 and https://github.com/openmediavault/openmediavault/commit/9e140f62d8a6aeb6a4b20856d18df836e78ad6cc.
