### ISSUE TITLE
FTP IdentLookup on/off has no effect on config

### ISSUE THREAD

**Issue by raphmur** [openmediavault/openmediavault#873]
### Description of issue/question
When changing the FTP server settings, the parameter "Ident Protocol/Enable the ident protocol (RFC1413)" seems to have no effect on the /etc/proftpd/proftpd.conf

The other settings are well transfered, bu not this one.

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

Change option on web interface.
Check proftpd.conf file.

On my version, it is set to "on" all the time.

### Versions report
OMV 5.5.12-1 (Usul)

**Comment by votdev** [comment]
Fixed in `openmediavault 5.5.18`.
