### ISSUE TITLE
Change order of portainer/yatch installation (dokerhub quota)

### ISSUE THREAD

**Issue by alejandrofm** [openmediavault/openmediavault#874]
### Description of issue/question
Right now the process of updating/reinstalling portainer or yatch from web admin work like this:
- delete all images of it
- download image
- start image

If the cap is reached the user will lost access to those apps.

Side effects: if the user have installed something like Watchtower this will end on endless posts in forums. If the user doesn't know how to stop Watchtower from console, the posts will raise.

To avoid loosing access to this apps I think the flow should be:
- download new image
- if download OK, delete all images
- start image

### Versions report
OMV 5.5.17-3

**Comment by ryecoaaron** [comment]
This belongs on the omv-extras issues - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues - but even if you reach the cap, it is only for 6 hours.  I will look at improving it though.

**Comment by alejandrofm** [comment]
Sorry for the missplacing, it's only for 6 hours if the user doesn't have Watchtower isntalled that keeps the cap constantly trying to pull new images.

**Comment by ryecoaaron** [comment]
I think watchtower pulling images so often is the real problem here.

**Comment by ryecoaaron** [comment]
and if you are using watchtower, why would you try pulling a new portainer or yacht?

**Comment by alejandrofm** [comment]
That's a good question, let's say I was browsing OMV and think "oh, let's update portainer", and now I'm here :P.
I just stopped watchtower from command line, restarted with 3600 secs pooling and reinstaled portainer without problem, but I used the console for that, it's not a problem (for me) is the cascade of posts if someone do something similar, or simply have someone using watchtower from same IP.
This is not a bug report, is an idea to:
1.- if dockerhub doesnt respond for some reason, don't delete portainer because you cannot install a new version.
2.- if cap reached, so error on download, dont delete the current version
3.- avoid complains that will point to the users watchtower configuration or the people using watchtower on same network.

**Comment by ryecoaaron** [comment]
Here is a problem.  I was doing some testing and without removing any images, I pulled selfhostedpro/yacht:latest. Even though I already had latest installed from a few weeks ago, it still pulled 13 images.

**Comment by PrplHaz4** [comment]
> I think watchtower pulling images so often is the real problem here.

I agree and have changed my refresh to be every 8 hours. 

That being said it seems like a reasonable safety to not delete the image before having a replacement for it.

**Comment by mi-hol** [comment]
> I will look at improving it though.

> reasonable safety to not delete the image before having a replacement for it
@ryecoaaron would you perhaps have an update on this topic?

**Comment by ryecoaaron** [comment]
I haven't done anything else.

My suggestion is to install both portainer and yacht initially.  Then if you want to update portainer and it fails leaving you without portainer, you can use yacht OR wait 6 hours to download portainer (assuming you hit the download limit).  Same applies if you want to update yacht.  Worst case, you can use the command line.  Either way, there is a button that will fix it if you can wait.  I don't think this is worth rewriting the code.

**Comment by mi-hol** [comment]
@ryecoaaron updated labels according to your answer, please change label in case I got something wrong
