### ISSUE TITLE
Avahi-daemon not refresh after adding new nfs share

### ISSUE THREAD

**Issue by k-matti** [openmediavault/openmediavault#875]
### Description of issue/question
My nfs shares:
![image](https://user-images.githubusercontent.com/66017397/101351520-fe6e0000-3890-11eb-96c6-96841f7826f1.png)

### Steps to reproduce issue
Backup share is missing, can't see it on the client.
Tried restart nfs service and OMV machine but no success.

avahi-daemon logs:

![image](https://user-images.githubusercontent.com/66017397/101351490-f2823e00-3890-11eb-9bf4-542761923b6d.png)

### Versions report

The newest OMV as vm

**Comment by k-matti** [comment]
@votdev 
I see you close this and added referenced to the fix but could you tell me how to refresh avahi-daemon manually until the fix will be online?

**Comment by votdev** [comment]
Run `omv-salt deploy run avahi` to re-build the configuration and restart the `Avahi` daemon.

**Comment by votdev** [comment]
Fixed in `openmediavault 5.5.18`.
