### ISSUE TITLE
Sabrent sata to usb 3.0 adapter with JMicron chipset don't provide stable device name

### ISSUE THREAD

**Issue by NovaPixell** [openmediavault/openmediavault#876]
### Description of issue/question
I use a 250gb crucial mx500 ssd, with a sabrent sata - usb 3.0 adapter.
Every time I restart the raspberry, OpenMediaVault changes the name of the device (e.g. / dev / sdc, / dev / sda1, etc), thus causing the loss of the FTP and SMB server configurations.
Also if I try to mount it to get it recognized, OpenMediaVault gives me an error (which I don't currently have).

### Versions report
(5.5.17-3)

**Comment by votdev** [comment]
> OpenMediaVault changes the name of the device (e.g. / dev / sdc, / dev / sda1, etc)

That is not OMV, that's the kernel. Because of that OMV strictly tries to use predictable device files, and only if they are not available, devices files like /dev/sda1 are used. So the question is, why does the kernel not report /dev/disk/by-[id|path|label] report to OMV?

**Comment by NovaPixell** [comment]
pi@raspberry:~ $ **udevadm info --query=property --name=/dev/sdc**
DEVPATH=/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0                                                                                                                                                             /usb2/2-1/2-1:1.0/host2/target2:0:0/2:0:0:0/block/sdc
DEVNAME=/dev/sdc
DEVTYPE=disk
MAJOR=8
MINOR=32
SUBSYSTEM=block
USEC_INITIALIZED=1141283539
ID_VENDOR=SABRENT
ID_VENDOR_ENC=SABRENT\x20
ID_VENDOR_ID=152d
ID_MODEL=SABRENT
ID_MODEL_ENC=SABRENT
ID_MODEL_ID=1561
ID_REVISION=0204
ID_SERIAL=SABRENT_SABRENT_2023E4014131-0:0
ID_SERIAL_SHORT=2023E4014131
ID_TYPE=disk
ID_INSTANCE=0:0
ID_BUS=usb
ID_USB_INTERFACES=:080650:080662:
ID_USB_INTERFACE_NUM=00
ID_USB_DRIVER=usb-storage
ID_PATH=platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0
ID_PATH_TAG=platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_1_0-scsi-0_0_0_0
ID_PART_TABLE_UUID=71abdc92-8999-4eb2-a04c-590c35d59134
ID_PART_TABLE_TYPE=gpt
DEVLINKS=/dev/disk/by-id/usb-SABRENT_SABRENT_2023E4014131-0:0 /dev/disk/by-path/                                                                                                                                                             platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0
TAGS=:systemd:

---------------------------------
pi@raspberry:~ $ **blkid**
/dev/mmcblk0p1: LABEL_FATBOOT="boot" LABEL="boot" UUID="592B-C92C" TYPE="vfat" PARTUUID="d2ca0711-01"
/dev/mmcblk0p2: LABEL="rootfs" UUID="706944a6-7d0f-4a45-9f8c-7fb07375e9f7" TYPE="ext4" PARTUUID="d2ca0711-02"
/dev/sdc1: LABEL="NAS" UUID="bf03d027-0f92-4816-a7e9-a53b2e0c08b5" TYPE="ext4" PARTUUID="8d98024f-6270-4bde-8bb7-8888896f98bf"

---------
Here more information. Do you think this is something you can fix with an update?

**Comment by mi-hol** [comment]
@NovaPixell are there similarities with https://github.com/openmediavault/openmediavault/issues/781 ?
Please try to get support in OMV forum https://forum.openmediavault.org/

**Comment by NovaPixell** [comment]
Nop. It isn't similar at that issue.

**Comment by votdev** [comment]
> pi@raspberry:~ $ udevadm info --query=property --name=/dev/sdc
DEVPATH=/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0 /usb2/2-1/2-1:1.0/host2/target2:0:0/2:0:0:0/block/sdc
DEVNAME=/dev/sdc
DEVTYPE=disk
MAJOR=8
MINOR=32
SUBSYSTEM=block
USEC_INITIALIZED=1141283539
ID_VENDOR=SABRENT
ID_VENDOR_ENC=SABRENT\x20
ID_VENDOR_ID=152d
ID_MODEL=SABRENT

The device is attached to USB hardware that is using JMicron. See https://devicehunt.com/view/type/usb/vendor/152D. Consider to use something different or try to upgrade the firmware of your USB device.

**Comment by votdev** [comment]
Alternatively reconfigure the system from scratch so that OMV will use the `/dev/disk/by-id/usb-SABRENT_SABRENT_2023E4014131-0:0` device file in the mount point configuration which results in a /etc/fstab that points to the predictable device file.

Before doing this, please post the output of `omv-confdbadm read --prettify conf.system.filesystem.mountpoint`.

**Comment by mi-hol** [comment]
@NovaPixell may I ask you to update issue title to reflect the real root cause?
'sabrent sata - usb 3.0 adapter with JMicron chipset cause OMV reboot"

**Comment by NovaPixell** [comment]
> > pi@raspberry:~ $ udevadm info --query=property --name=/dev/sdc
> > DEVPATH=/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0 /usb2/2-1/2-1:1.0/host2/target2:0:0/2:0:0:0/block/sdc
> > DEVNAME=/dev/sdc
> > DEVTYPE=disk
> > MAJOR=8
> > MINOR=32
> > SUBSYSTEM=block
> > USEC_INITIALIZED=1141283539
> > ID_VENDOR=SABRENT
> > ID_VENDOR_ENC=SABRENT\x20
> > ID_VENDOR_ID=152d
> > ID_MODEL=SABRENT
> 
> The device is attached to USB hardware that is using JMicron. See https://devicehunt.com/view/type/usb/vendor/152D. Consider to use something different or try to upgrade the firmware of your USB device.

How can I upgrade the adapter's firmware?

**Comment by NovaPixell** [comment]
> Alternatively reconfigure the system from scratch so that OMV will use the `/dev/disk/by-id/usb-SABRENT_SABRENT_2023E4014131-0:0` device file in the mount point configuration which results in a /etc/fstab that points to the predictable device file.
> 
> Before doing this, please post the output of `omv-confdbadm read --prettify conf.system.filesystem.mountpoint`.

Here the output:

```
pi@raspberry:~ $ omv-confdbadm read --prettify conf.system.filesystem.mountpoint
Traceback (most recent call last):
  File "/usr/sbin/omv-confdbadm", line 76, in <module>
    sys.exit(main())
  File "/usr/sbin/omv-confdbadm", line 72, in main
    return cmd_inst.execute(*sys.argv)
  File "/usr/share/openmediavault/confdbadm/commands.d/read.py", line 73, in execute
    objs = db.get(cmd_args.id, cmd_args.uuid)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 723, in execute
    elements = self._execute_xpath()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 408, in _execute_xpath
    root_element = self._get_root_element()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 399, in _get_root_element
    self._load()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 378, in _load
    self._root_element = lxml.etree.parse(self._database_file)
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
OSError: Error reading file '/etc/openmediavault/config.xml': failed to load external entity "/etc/openmediavault/config.xml"

```

**Comment by mi-hol** [comment]
> How can I upgrade the adapter's firmware?

this is a question for your device's manufacturer support

**Comment by votdev** [comment]
> > Alternatively reconfigure the system from scratch so that OMV will use the `/dev/disk/by-id/usb-SABRENT_SABRENT_2023E4014131-0:0` device file in the mount point configuration which results in a /etc/fstab that points to the predictable device file.
> > Before doing this, please post the output of `omv-confdbadm read --prettify conf.system.filesystem.mountpoint`.
> 
> Here the output:
> 
> ```
> pi@raspberry:~ $ omv-confdbadm read --prettify conf.system.filesystem.mountpoint
> Traceback (most recent call last):
>   File "/usr/sbin/omv-confdbadm", line 76, in <module>
>     sys.exit(main())
>   File "/usr/sbin/omv-confdbadm", line 72, in main
>     return cmd_inst.execute(*sys.argv)
>   File "/usr/share/openmediavault/confdbadm/commands.d/read.py", line 73, in execute
>     objs = db.get(cmd_args.id, cmd_args.uuid)
>   File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
>     query.execute()
>   File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 723, in execute
>     elements = self._execute_xpath()
>   File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 408, in _execute_xpath
>     root_element = self._get_root_element()
>   File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 399, in _get_root_element
>     self._load()
>   File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 378, in _load
>     self._root_element = lxml.etree.parse(self._database_file)
>   File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
>   File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
>   File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
>   File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
>   File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
>   File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
>   File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
>   File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
> OSError: Error reading file '/etc/openmediavault/config.xml': failed to load external entity "/etc/openmediavault/config.xml"
> ```

That's not the expected output. Something is wrong with your installation. It should look like this:
```
[
    {
        "dir": "/srv/dev-disk-by-id-scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-3-part1",
        "freq": 0,
        "fsname": "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-3-part1",
        "hidden": false,
        "opts": "defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl",
        "passno": 2,
        "type": "ext4",
        "uuid": "f639ba99-d228-4feb-ae7c-33a2ffc41b93"
    }
]
```
Have you executed the command as user `root`?

**Comment by NovaPixell** [comment]
Here:

```
[
    {
        "dir": "/srv/dev-disk-by-id-usb-SABRENT_SABRENT_2023E4014131-0-0",
        "freq": 0,
        "fsname": "/dev/disk/by-id/usb-SABRENT_SABRENT_2023E4014131-0:0",
        "hidden": false,
        "opts": "defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl",
        "passno": 2,
        "type": "ext4",
        "uuid": "fb2aeb69-9325-4c2b-9ed2-a0bb701a6d14"
    }
]
```

**Comment by votdev** [comment]
Please also provide `cat /etc/fstab`.

**Comment by NovaPixell** [comment]
```
proc            /proc           proc    defaults          0       0
PARTUUID=d2ca0711-01  /boot           vfat    defaults          0       2
PARTUUID=d2ca0711-02            /       ext4    noatime,nodiratime,defaults     0 1
# >>> [openmediavault]
/dev/disk/by-id/usb-SABRENT_SABRENT_2023E4014131-0:0            /srv/dev-disk-by-id-usb-SABRENT_SABRENT_2023E4014131-0-0        ext4    defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2
# <<< [openmediavault]

```

**Comment by votdev** [comment]
From the configuration point of view everything is correct: the fstab contains a predictable device file, UDEV reports various device files. And what is the exact problem now? 

> Also if I try to mount it to get it recognized, OpenMediaVault gives me an error (which I don't currently have).

Can you provide that error message, please?

**Comment by NovaPixell** [comment]
I don't have that mistake unfortunately. But essentially if I restart the raspberry, OMV doesn't recognize the device and creates a new file system.
Sometimes if I click "Mount" I get this error. I just don't have it

**Comment by votdev** [comment]
You mean the file system is not listed in `blkid`? If that's the case, OMV can't do anything here.

Sorry to say that, but a RasPi is not really usable for a NAS, though everyone is using it. Having no real SATA interface is the real bottleneck of this hardware. And USB is not really an alternative, in conjunction with malfunction USB/SATA equipment. That is my experience with the comments and problems users have.

Maybe changing the USB/SATA adapter will solve your problems.

**Comment by mi-hol** [comment]
> RasPi is not really usable for a NAS, though everyone is using it. Having no real SATA interface is the real bottleneck of this hardware. And USB is not really an alternative, in conjunction with malfunction USB/SATA equipment.

@vordev, there are different experiences with SBCs & USB, maybe because you only get to see the issues this conclusion came up, but I've certainly seen many positive results with quality HW using USB 3 interface (my setup is using RP4 with Icy Box IB-RD3662-C31)

**Comment by NovaPixell** [comment]
anyway which usb sata adapter do you recommend? the best

**Comment by mi-hol** [comment]
this is a discussion for OMV forum.
I've published benchmark results for my setup [here](https://forum.openmediavault.org/index.php?thread/37129-slow-write-speed-9mb-s-with-rpi4-4gb-and-usb-3-hdd/&postID=258999#post258999)

**Comment by NovaPixell** [comment]
Why closed issue?

**Comment by votdev** [comment]
This issue is closed because it can't be fixed, the problem is the manufacturer of your drive enclosure. All we are doing in openmediavault is working around a behavior that is IMO a design bug in the chipset. Buy a drive enclosure that is not using JMicron, and you'll be happy.
