### ISSUE TITLE
minidlna launches before the media directories are mounted

### ISSUE THREAD

**Issue by jpo234** [openmediavault/openmediavault#880]
### Description of issue/question
After a reboot, minidlna doesn't serve any content.

### Steps to reproduce issue
Reboot the OMV server and try to access content through UPnP:

```
pi@omv-nas:~ $ service minidlna status 
● minidlna.service - MiniDLNA lightweight DLNA/UPnP-AV server
   Loaded: loaded (/lib/systemd/system/minidlna.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-12-13 20:03:51 CET; 1h 56min ago
     Docs: man:minidlnad(1)
           man:minidlna.conf(5)
  Process: 733 ExecStart=/usr/sbin/minidlnad -f $CONFIGFILE -P /run/minidlna/minidlna.pid $DAEMON_OPTS (code=exited, status=0/SUCCESS)
 Main PID: 902 (minidlnad)
    Tasks: 2 (limit: 1430)
   CGroup: /system.slice/minidlna.service
           └─902 /usr/sbin/minidlnad -f /etc/minidlna.conf -P /run/minidlna/minidlna.pid -r

Dec 13 20:03:47 omv-nas systemd[1]: Starting MiniDLNA lightweight DLNA/UPnP-AV server...
Dec 13 20:03:51 omv-nas minidlnad[733]: [2020/12/13 20:03:51] minidlna.c:631: error: Media directory "V,/srv/dev-disk-by-label-omvmaster/Video/" not accessible [No such file or directory]
Dec 13 20:03:51 omv-nas minidlnad[733]: [2020/12/13 20:03:51] minidlna.c:631: error: Media directory "A,/srv/dev-disk-by-label-omvmaster/Music/" not accessible [No such file or directory]
Dec 13 20:03:51 omv-nas minidlnad[733]: [2020/12/13 20:03:51] minidlna.c:631: error: Media directory "P,/srv/dev-disk-by-label-omvmaster/Photos/" not accessible [No such file or directory]
Dec 13 20:03:51 omv-nas systemd[1]: Started MiniDLNA lightweight DLNA/UPnP-AV server.
```
Obviously the minidlna service should depend on the media directories to be available. Mine are on two external USB drives.

### Versions report
[versioninfo.txt](https://github.com/openmediavault/openmediavault/files/5685420/versioninfo.txt)

**Comment by jpo234** [comment]
I worked around the issue by changing `/lib/systemd/system/minidlna.service`:
```
# After=network.target
After=network.target systemd-quotacheck.service
```
Howver, `systemd-quotacheck.service` doesn't seem to be the right dependency.

**Comment by votdev** [comment]
Please report this issue here: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-minidlna/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

@ryecoaaron

**Comment by votdev** [comment]
You you use union file systems?

**Comment by jpo234** [comment]
@votdev Nothing fancy. A Raspberry Pi4 with 2 external USB disks: omvmaster for the actual content and omvbackup to mirror the content with rsnapshot. Looking at the boot log shows, that minidlna gets started **BEFORE** the USB disks get mounted. There obviously seems to be a dependency issue. I tried the local-fs target, but that had no effect, so I tried "systemd-quotacheck.service". That fixes the issue, but seems like a hack. The real dependency should be "external USB disks", but I don't know what systemd service that is.

**Comment by ryecoaaron** [comment]
The plugin doesn't maintain the unit file for minidlna.  I guess I could add an override file but if local-fs.target doesn't work, it would have to be this somewhat ugly hack - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/usr/sbin/omv-installdocker#L310.

**Comment by jpo234** [comment]
> 
> 
> The plugin doesn't maintain the unit file for minidlna. I guess I could add an override file but if local-fs.target doesn't work, it would have to be this somewhat ugly hack - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/usr/sbin/omv-installdocker#L310.

@ryecoaaron I just opened an issue in the minidlna repository as @votdev  asked me to do. Please decide where to continue the discussion and close the duplicate.

**Comment by jpo234** [comment]
Issue moved to https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-minidlna/issues/16

**Comment by mi-hol** [comment]
@jpo234 would you mind to contribute your experience regarding "switched to an USB SSD disk as boot device" on the OMV forum (i.e. https://forum.openmediavault.org/index.php?thread/37041-can-t-access-webgui-anymore-after-migrating-from-micro-sd-to-usb-ssd-pi4/&postID=258400#post258400) ?
