### ISSUE TITLE
Risk of escaping sudo user jail, when pressing "Run" on a cron job definition

### ISSUE THREAD

**Issue by ragazzojp** [openmediavault/openmediavault#881]
### Description of issue/question

As discussed here: https://forum.openmediavault.org/index.php?thread/36898-cron-user-jobs-run-as-root-when-run-is-pressed, running cron jobs manually by pressing "Run" is implemented differently than what cron actually does to run the job. In particular, this is what is run:

```sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin;
export LANG=C.UTF-8; export SHELL=/bin/sh;
sudo --shell --non-interactive --user=theusername -- command 2>&1
```

`command` is not escaped, so if the command contains `&&` the second part escapes the sudo jail and runs are root. Other kinds of code injections are possible as well, using `;` for example.

Apart from being a mild security issue (it would be quite serious in general, but given the fact that the OMV admin can control anyway practically everything ...), it's uncomfortable for the admin to test cron job that should run with as a different user if the commands contain `&&`, since the second part runs as root instead of the user indicated in the job configuration, not replicating the exact conditions created by cron when it runs the job.

Last but not least, in my case, the first command is `cd` to enter in the user home directory. It would be good if the current directory of a job run as user is that user's home directory.

For uniformity with cron, I suggest the "Run" action is implemented by telling `sudo` to run the actual cron job shell script since this is available in the system and this is what cron does, instead of _pasting_ its content on the command line of `sudo` and being vulnerable to every sort of code injection.

### Steps to reproduce issue

Create a cron job with command `whoami && whoami` and pick a user different than root.
Press the "Run" button.
Observe that the two username are different, the first is the user selected, but  the second one is root.

### Versions report
4.x
5.x

**Comment by votdev** [comment]
Just as a side-note: Users can configure OMV to not allow to choose the `root`user by setting the [environment variable](https://openmediavault.readthedocs.io/en/5.x/various/advset.html#environmental-variables) `OMV_USERMGMT_ENUMERATE_USER_ROOT` to `false`.

**Comment by votdev** [comment]
I think escaping the command to run should be enough. Running the cron script is not possible (otherwise it would be implemented that way already like it is done for rsync and clamav) because all commands to be executed are in the `/etc/cron.d/openmediavault-userdefined` file and not separately. Maybe this is something for the future.

https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/cron/files/userdefined.j2

**Comment by ragazzojp** [comment]
Escaping is non-trivial, when mixed with `sudo`. The following seems to work:

```sh
sudo -u username /bin/sh -c "command"
```

Note that the command should be escaped to avoid `"` interfering. Also '\' must be escaped.

Command: `whoami && echo "hello; \"world\";"`
Result: `/bin/sh -c "whoami && echo \"hello; \\\"world\\\";\""`

If you know how to ask `sh` to escape what to put in in `-c`, then it's definitely better because I probably haven't covered all the cases. Anyway, I'm not good at shell scripts, the only safe way is going through a file.

Why do you say that all the files are in `/etc/cron.d/openmediavault-userdefined`? The actual scripts are separate, in `/var/lib/openmediavault/cron.d/userdefined-UUID`, at least on my OMV 4.

**Comment by votdev** [comment]
> Why do you say that all the files are in /etc/cron.d/openmediavault-userdefined? The actual scripts are separate, in /var/lib/openmediavault/cron.d/userdefined-UUID, at least on my OMV 4.

I didn't remember that this was already refactored. This makes the bugfix very easy.

**Comment by votdev** [comment]
Fixed in `openmediavault 5.5.18`.

**Comment by ragazzojp** [comment]
I'll gladly test it if you backport it to OMV4, otherwise I will later, when my new OMV5 system is ready.

**Comment by votdev** [comment]
> I'll gladly test it if you backport it to OMV4, otherwise I will later, when my new OMV5 system is ready.

Sorry, OMV is EOL since April 2018, so there will be no backports or updates anymore.
