### ISSUE TITLE
Text placeholder error in "Update Management" page

### ISSUE THREAD

**Issue by ffloimair** [openmediavault/openmediavault#883]
### Description of issue/question
When opening the update manager, the list of packages has an error in the packet source description:
Instead of the name of the source it shows "%s/%s"

Example (on a system with "German" as language):

> **f2fs-tools 1.11.0-1.1**
> Tools for Flash-Friendly File System
> 
> Größe: 152.48 KiB
> Betreuer: Filesystems Group <filesystem-devel@lists.alioth.debian.org>
> Homepage: http://git.kernel.org/gvit/linux/kernel/git/jaegeuk/fs2fs-tools.git
> Quelle: %s/%s

### Steps to reproduce issue
Just open the update management page on the latest version.

### Versions report
5.5.17-3 (Usul)

**Comment by ffloimair** [comment]
it's a "cosmetic" issue but probably easy to fix.

**Comment by votdev** [comment]
This issue is fixed with `openmediavault 5.5.18`.

https://github.com/openmediavault/openmediavault/commit/77828a7c0362fb2568f1f6e15ce3cb6208c8c872
https://github.com/openmediavault/openmediavault/commit/9e140f62d8a6aeb6a4b20856d18df836e78ad6cc
