### ISSUE TITLE
Missleading information in Services Overview tab

### ISSUE THREAD

**Issue by k-matti** [openmediavault/openmediavault#889]
I am using the newest OMV.

Services overview tab is showing smb/cifs service as running:
![image](https://user-images.githubusercontent.com/66017397/102690723-a081d680-4207-11eb-8ab4-fa8ea85e6f83.png)

But I am not running this service:

![image](https://user-images.githubusercontent.com/66017397/102690731-ad062f00-4207-11eb-954b-6ac8bd6e03bc.png)

I notice that this started after last OMV update

**Comment by mi-hol** [comment]
"last" is always relative to an unknown previous state :)
Could you please add version details?
OS Version: [uname -a]
OMV Version: [dpkg -l | grep openmediavault]

**Comment by k-matti** [comment]
Linux openmediavault 5.9.0-0.bpo.2-amd64 #1 SMP Debian 5.9.6-1~bpo10+1 (2020-11-19) x86_64 GNU/Linux
ii  openmediavault                  5.5.19-1                            all          openmediavault - The open network attached storage solution
ii  openmediavault-diskstats        5.0.6-1                             all          openmediavault disk monitoring plugin
ii  openmediavault-keyring          1.0                                 all          GnuPG archive keys of the OpenMediaVault archive

**Comment by votdev** [comment]
This is a problem of some Debian packages that the are restarted somehow though OMV has disabled the service while installation. Because of that the database expects the service as disabled, but in reality it is started by systemd. Run `omv-salt deploy run samba` to get them on par.

**Comment by k-matti** [comment]
That help thansk :)
