### ISSUE TITLE
Add "Help" to UI Header line, so its visible all the time

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#893]
**Is your feature request related to a problem? Please describe.**
New users frequent don't see/find the  link to OMV documentation because it's hidden at end of left navigation bar.

**Describe the solution you'd like**
move "information" to header row, like in Cockpit UI and many other web based  UIs

**Additional context**
Cockpit screenshot 
![2020-12-25 17_06_38-Overview - user@nas - Vivaldi](https://user-images.githubusercontent.com/22799428/103138793-4cc72f80-46d6-11eb-90cb-0818f6b09b8e.png)

**Comment by votdev** [comment]
![Bildschirmfoto vom 2020-12-27 08-28-16](https://user-images.githubusercontent.com/1897962/103165909-b00fa980-481d-11eb-8a50-64670b379fb8.png)

**Comment by mi-hol** [comment]
Regarding the sequence of links in help, I'd propose:

1. Documentation
2. Forum
3. Homepage

**Comment by votdev** [comment]
> Regarding the sequence of links in help, I'd propose:
> 
>     1. Documentation
> 
>     2. Forum
> 
>     3. Homepage

Done
