### ISSUE TITLE
Disabled cron job still runs.

### ISSUE THREAD

**Issue by ParadingLunatic** [openmediavault/openmediavault#894]
OMV 5.5.19-1
Scheduled jobs configured in the GUI run regardless of whether or not they're set to be disabled.

To reproduce:
1. Open the OMV Web Gui
2. go to Scheduled Jobs
3. Create new scheduled job but toggle to be disabled
4. Setup job however needed
5. Click save
6. Apply changes

Job will be listed in /etc/cron.d/openmediavault-userdefined
/etc/openmediavault/config.xml will show `<enabled>0</enabled>`
Job will run even though it is marked as disabled in GUI and in config.xml

I would imagine the job shouldn't appear in /etc/cron.d/openmediavault-userdefined and should only appear in config.xml with `<enabled>0</enabled>` set.

**Desktop (please complete the following information):**
 - OS: Linux Manjaro (stable) completely up to date.  Kernel 5.9.11-3
 - Chromium (87.0.4280.66) and Firefox (84.9.1)

**Additional context**
This happened even if I initially created the job enabled or if I create the job disabled.  The job is always added to /etc/cron.d/openmediavault-userdefined.

**Comment by votdev** [comment]
Fixed in `openmediavault 5.5.20`.
