### ISSUE TITLE
Update notifications not sent

### ISSUE THREAD

**Issue by AndreaPro** [openmediavault/openmediavault#905]
**Describe the bug**
Even if are activated I don't receive any Update notification

**To Reproduce**
1. Enable Email Notifications in the OMV UI under System > Notification > Settings
2. Check Software Updates under System > Notification > Notifications
3. Inside Diagnostics > Dashboard > System Information Updates Available is set to Yes but notification is not sent. Other notifications work fine.

**Expected behavior**
I receive other notifications checked under System > Notification > Notifications but even if Updates is checked no email is sent.

<img width="1220" alt="Screen Shot 2020-12-30 at 11 57 28" src="https://user-images.githubusercontent.com/8338665/103347608-bf019080-4a97-11eb-9de4-7fbce9b2949b.png">

**System:**
- Device: Raspberry Pi4
 - OS: Debian GNU/Linux 10 (buster)
 - Kernel: Linux 5.4.79-v8+
 - OMV: 5.5.20-1

**Comment by votdev** [comment]
Please check the syslog for error messages via `grep postfix /var/log/syslog`.

**Comment by AndreaPro** [comment]
> Sending emails works in general?
> 
> Note, when you enable emails and cron-apt was executed already by cron, you'll not receive an email from cron-apt before the next day.
> 
> Please check the syslog for error messages via `grep postfix /var/log/syslog`. `grep cron-apt /var/log/syslog` would be useful, too.

Yes, other notifications are working fine, every day I receive the notification from a cronjob or I receive notifications if a service is started or stopped or for logins. Updates are checked but never received since months, I've tried to uncheck them, apply the settings and check the option again but no issue.

I'll have to wait for the next update.

`grep postfix /var/log/syslog`
I've checked this command and all the last entries correspond to email that I've already received, if you think that can still be relevant I'll post it after purging all the private informations.

This is the output of the other command:
```
pi@raspberrypi:~ $ grep cron-apt /var/log/syslog
Dec 30 03:56:25 raspberrypi cron-apt: CRON-APT RUN [/etc/cron-apt/config]: Wed Dec 30 03:21:30 CET 2020
Dec 30 03:56:25 raspberrypi cron-apt: CRON-APT SLEEP: 2058, Wed Dec 30 03:55:48 CET 2020
Dec 30 03:56:25 raspberrypi cron-apt: CRON-APT ACTION: 0-update
Dec 30 03:56:25 raspberrypi cron-apt: CRON-APT LINE: /usr/bin/apt-get  update -o quiet=2
Dec 30 04:00:02 raspberrypi CRON[18373]: (root) CMD (test -x /usr/sbin/cron-apt && /usr/sbin/cron-apt)
Dec 30 04:37:44 raspberrypi cron-apt: CRON-APT RUN [/etc/cron-apt/config]: Wed Dec 30 04:00:02 CET 2020
Dec 30 04:37:44 raspberrypi cron-apt: CRON-APT SLEEP: 2243, Wed Dec 30 04:37:25 CET 2020
Dec 30 04:37:44 raspberrypi cron-apt: CRON-APT ACTION: 0-update
Dec 30 04:37:44 raspberrypi cron-apt: CRON-APT LINE: /usr/bin/apt-get  update -o quiet=2
```

**Comment by votdev** [comment]
Does the file `/etc/cron-apt/refrain` exist? 
```
# ls -alh /etc/cron-apt/refrain
```

**Comment by AndreaPro** [comment]
I've checked and it's not there

**Comment by votdev** [comment]
Please post the content of `/etc/cron-apt/config`. I have an idea, but want to verify it.

**Comment by AndreaPro** [comment]
```
pi@raspberrypi:/etc/cron-apt $ cat /etc/cron-apt/config
# This file is auto-generated by openmediavault (https://www.openmediavault.o
rg)
# WARNING: Do not edit this file, your changes will get lost.

# Configuration for cron-apt.
# The cron config is located in /etc/cron.d/cron-apt

# When to send email about the cron-apt results.
# Value: error   (send mail on error runs)
#        upgrade (when packages are upgraded)
#        changes (mail when change in output from an action)
#        output  (send mail when output is generated)
#        always  (always send mail)
#                (else never send mail)
MAILON="upgrade"

# The email address to send mail to.
MAILTO="myemailaddress@mail.com"

# Value: error   (syslog on error runs)
#        upgrade (when packages is upgraded)
#        changes (syslog when change in output from an action)
#        output  (syslog when output is generated)
#        always  (always syslog)
#                (else never syslog)
SYSLOGON="always"

# Value: verbose (log everything)
#        always  (always log)
#        upgrade (when packages is upgraded)
#        changes (log when change in output from an action)
#        output  (log when output is generated)
#        error   (log error runs only)
#                (else log nothing)
# DEBUG="output"

# General apt options that will be passed to all APTCOMMAND calls.
# Use "-o quiet" instead of "-q" for aptitude compatibility.
#  OPTIONS="-o quiet=1"
# You can for example add an additional sources.list file here.
#  OPTIONS="-o quiet=1 -o Dir::Etc::SourceList=/etc/apt/security.sources.list
"
# You can also set an alternative sources.list file here.
#  OPTIONS="-o quiet=1 -o Dir::Etc::SourceList=/etc/apt/security.sources.list
 -o Dir::Etc::SourceParts=\"/dev/null\""
# If you want to allow unauthenticated and untrusted packages add the
# following to your options directive.
#  OPTIONS="-o quiet=1 -o APT::Get::AllowUnauthenticated=true -o aptitude::Cm
dline::ignore-trust-violations=yes"
# To limit the bandwidth used use the following line. This example limit the
# bandwidth usage to 25 kB/s.
#  OPTIONS="-o Acquire::http::Dl-Limit=25"
OPTIONS=""
pi@raspberrypi:/etc/cron-apt $
```

**Comment by votdev** [comment]
Too bad, i thought the [rate limit issue](https://github.com/openmediavault/openmediavault/commit/9cc94067a3cd98c68044311fab782649a8720ddd) has not been applied to your config. With that, i'm currently out of ideas.

**Comment by mi-hol** [comment]
@votdev maybe an alternative to receiving update notification via email from servers running OMV, would be to subscribe to a "News" RSS feed.
Once I thought to have seen it mentioned on openmediavault.org but now I can't find it (did I dream?)
Would it be an option provide a RSS feed?

**Comment by votdev** [comment]
RSS is dead. Additionally RSS on Wordpress was used to compromise installations, so i turned it off years ago because of security reasons. News about the latest package releases are announced via Twitter.

**Comment by mi-hol** [comment]
another report of this issue [forum thread](https://forum.openmediavault.org/index.php?thread/37509-notification-for-software-updates-email/)

**Comment by votdev** [comment]
Could you please add `DEBUG="verbose"` to `/etc/cron-apt/config` and check the syslog the next day if it contains useful hints why the notification is not send?

**Comment by geoffae** [comment]
Having changed the debug option to verbose and following on from [this thread](https://forum.openmediavault.org/index.php?thread/37509-notification-for-software-updates-email/) in the forum #24 the output from the syslog is as follows;

`
Jan 18 04:00:01 kingfisher CRON[14381]: (root) CMD (test -x /usr/sbin/cron-apt && /usr/sbin/cron-apt)

Jan 18 04:55:29 kingfisher cron-apt: CRON-APT RUN [/etc/cron-apt/config]: Mon Jan 18 04:00:01 GMT 2021
Jan 18 04:55:29 kingfisher cron-apt: CRON-APT SLEEP: 3293, Mon Jan 18 04:54:54 GMT 2021
Jan 18 04:55:29 kingfisher cron-apt: CRON-APT ACTION: 0-update
Jan 18 04:55:29 kingfisher cron-apt: CRON-APT LINE: /usr/bin/apt-get  update -o quiet=2

Jan 18 08:03:49 kingfisher cron-apt: CRON-APT RUN [/etc/cron-apt/config]: Mon Jan 18 07:36:52 GMT 2021
Jan 18 08:03:49 kingfisher cron-apt: CRON-APT SLEEP: 1610, Mon Jan 18 08:03:42 GMT 2021
Jan 18 08:03:49 kingfisher cron-apt: CRON-APT ACTION: 0-update
Jan 18 08:03:49 kingfisher cron-apt: CRON-APT LINE: /usr/bin/apt-get  update -o quiet=2`

**Comment by votdev** [comment]
Seems like the `3-download` action is not executed. I'm really out of ideas. I got my notification today:
```
The following packages are already downloaded and ready to install. Go to the 'System | Update Management' page in the web interface or run 'omv-update' from the CLI to install them finally.

You have received this notification because you have enabled software update notifications on this host. To change your notification preferences, please go to the 'System | Notification' page in the web interface.

CRON-APT RUN [/etc/cron-apt/config]: Mon Jan 18 09:01:43 CET 2021
CRON-APT SLEEP: 1163, Mon Jan 18 09:21:06 CET 2021
CRON-APT ACTION: 3-download
CRON-APT LINE: /usr/bin/apt-get  dist-upgrade -d -y -o APT::Get::Show-Upgraded=true
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages will be upgraded:
  openmediavault-diskstats
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.3 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://packages.openmediavault.org/public usul/main amd64 openmediavault-diskstats all 5.0.7-1 [10.3 kB]
Fetched 10.3 kB in 5s (2029 B/s)
Download complete and in download only mode
```

**Comment by geoffae** [comment]
> Seems like the 3-download action is not executed. Maybe because there were no new packages at that time.
That appears to be the issue as another forum members replied to thread having got the notification, with 3-download, I also had the same problem with V4.
Whilst this doesn't bother me I would like to try and resolve it, but if that's possible then it's no big deal :)

**Comment by geoffae** [comment]
From memory when you set up notifications with the email information, under the notifications tab everything is set to enabled, what I would normally do is to uncheck what I don't need/use, then save and apply.
What I have done as an experiment is to uncheck everything, save, apply, reboot, then enabled what I want notifications for, save, apply, will see if that makes a difference.

**Comment by AndreaPro** [comment]
I've setup a new OMV server, the one with issue was on arm, this one is on x86, I've installed from iso. Same behaviour. Notificaitons working except for updates

**Comment by geoffae** [comment]
> I've setup a new OMV server, the one with issue was on arm, this one is on x86, I've installed from iso. Same behaviour. Notifications working except for updates

Install apticron [see here](https://forum.openmediavault.org/index.php?thread/37509-notification-for-software-updates-email/&postID=267108#post267108)

**Comment by T-6** [comment]
> Seems like the `3-download` action is not executed.

I only have 0-update in /etc/cron-apt/action.d
No 3-download.

**Comment by votdev** [comment]
> > Seems like the `3-download` action is not executed.
> 
> I only have 0-update in /etc/cron-apt/action.d
> No 3-download.
> 
> Created the file with this content:
> `autoclean -y`
> `dist-upgrade -d -y -o APT::Get::Show-Upgraded=true`
> 
> from [here](https://wiki.ubuntuusers.de/cron-apt/#action-d-3-download)
> 
> EDIT: running the cron job sends a mail
> /etc/cron.d/cron-apt

The file `/etc/cron-apt/action.d/3-download` is part of the cron-apt package, see https://packages.debian.org/buster/all/cron-apt/filelist. So there might be two reasons causing the file to be missing: 

1. the package installation was not correct
2. someone has deleted the file

But got to hear that you have fixed that issue.

**Comment by T-6** [comment]
Definitely not deleted by me.
Actually reinstalled the package several times today, but the file is not there on two systems.
1x amd64, 1x arm

**Comment by T-6** [comment]
Just checked in a VM and the file is there. The VM was installed from the ISO. The other two systems w/o the file were installed using the script. No idea, how this could make a difference regarding this.

**Comment by ryecoaaron** [comment]
I don't even remember why but the flashmemory plugin deletes the 3-download file - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-flashmemory/blob/master/srv/salt/omv/deploy/flashmemory/default.sls#L51

**Comment by votdev** [comment]
> I don't even remember why but the flashmemory plugin deletes the 3-download file - [https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-flashmemory/blob/master/srv/salt/omv/deploy/flashmemory/default.sls#L51](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-flashmemory/blob/master/srv/salt/omv/deploy/flashmemory/default.sls?rgh-link-date=2021-02-20T14%3A30%3A41Z#L51)

Argghhh... and i wondered since years why users complain why cron-apt does not send them emails. But finally we found the reason. :-)

**Comment by ryecoaaron** [comment]
I will remove the code that deletes it.

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-flashmemory/commit/e148922e47ab3df33016de4dd2e946cd7a68c4a4

**Comment by ryecoaaron** [comment]
5.0.8 is in the repo now.

**Comment by T-6** [comment]
Now I get two mails. One from cron-apt at 4:00 and another one from anacron at 7:49 AM. The same time /var/spool/anacron/cron.daily was changed.
Is there any mechanism implemented that should prevent this?

**Comment by votdev** [comment]
> Now I get two mails. One from cron-apt at 4:00 and another one from anacron at 7:49 AM. The same time /var/spool/anacron/cron.daily was changed.
> Is there any mechanism implemented that should prevent this?

No, because the job of anacron is exactly that to coordinate running the cron jobs.

**Comment by mi-hol** [comment]
@AndreaPro could you please confirm that this issue is fixed or still open?

**Comment by AndreaPro** [comment]
I don't know if on a new installation it works, but on mine I've applied the fix related to the 3-download file and notifications are working. I have an OMV VM and I will try to install flash memory and see if it works

**Comment by mi-hol** [comment]
> RSS is dead. 

well a number of open source tools publish new releases via RSS feed because it's a user friendly and low effort approach to get notified. (i.e. GitLab https://about.gitlab.com/atom.xml)
The major email readers support RSS as a source!
From my view many OMV have NOT activated email notifications for a number of good reasons. 
This leaves their users unaware of new OMV version releases.


> Additionally RSS on Wordpress was used to compromise installations,
BTW: would you switch away from Debian or PHP because of past security issues?

**Comment by mi-hol** [comment]
better place to discuss alternative notification method is https://github.com/openmediavault/openmediavault/issues/1074

**Comment by votdev** [comment]
> Old issue, but I was wondering the same.
> 
> My arm-based system also lacks the `3-download` file, but instead has a `5-openmediavault-security` with the same content that the former is supposed to have (according to the wiki page linked above), _except_ that the `--download-only` flag is missing. I can't find any setting on the OMV interface which would let me specify whether to automatically apply updates, or just download them.
> 
> In any case:
> 
> ```
> $ ls /etc/cron-apt/action.d
> 0-update
> 5-openmediavault-security
> $ sudo dpkg -L cron-apt | grep action.d
> /etc/cron-apt/action.d
> /etc/cron-apt/action.d/0-update
> /etc/cron-apt/action.d/3-download
> $ sudo dpkg -V cron-apt
> ??5?????? c /etc/cron-apt/action.d/3-download
> ??5?????? c /etc/cron.d/cron-apt
> $ sudo apt-get --reinstall install cron-apt
> ...
> 0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
> ...
> $ ls /etc/cron-apt/action.d
> 0-update
> 5-openmediavault-security
> ```

You can rebuild the configuration with omv-salt deploy run cronapt. You can disable the cron-apt cron job with the `OMV_CRON_APT_ENABLED` [environment variable](https://docs.openmediavault.org/en/stable/various/advset.html#environmental-variables). There is no option in the UI to modify this behaviour with reason.

**Comment by mortee** [comment]
I did run the mentioned salt command, but it did not even mention, nay create `/etc/cron-apt/action.d/3-download`. It did check on `/etc/cron-apt/mailmsg.d/3-download` though, which contains the message I would expect to receive when there's non-security updates available. 

So in any case, I haven't encountered in the discussion above any mention of a scenario in which that former file is _supposed_ to be missing, and it doesn't really make sense either. What further should I be checking?

**Comment by mortee** [comment]
I do have a security repo configured, and I keep receiving notifications about those having been successfully installed (I suppose that's what `5-openmediavault-security` does) - which is good.

Although, I don't receive notifications about regular updates, which would apparently be the job of `3-download` (missing on my system).

**Comment by votdev** [comment]
This is how the file structure of a properly configures cron-apt looks like:
```
# ls -alh /etc/cron-apt/*
-rw-r--r-- 1 root root 2.1K Jul 27 09:00 /etc/cron-apt/config

/etc/cron-apt/action.d:
total 20K
drwxr-xr-x  2 root root 4.0K Oct  4 22:11 .
drwxr-xr-x 10 root root 4.0K Jul 27 09:00 ..
-rw-r--r--  1 root root   18 Jan  1  2021 0-update
-rw-r--r--  1 root root   64 Jan  1  2021 3-download
-rw-r--r--  1 root root   57 Oct  4 22:11 5-openmediavault-security

/etc/cron-apt/config.d:
total 12K
drwxr-xr-x  2 root root 4.0K Oct  4 22:11 .
drwxr-xr-x 10 root root 4.0K Jul 27 09:00 ..
-rw-r--r--  1 root root  237 Oct  4 22:11 5-openmediavault-security

/etc/cron-apt/errormsg.d:
total 8.0K
drwxr-xr-x  2 root root 4.0K Jan  1  2021 .
drwxr-xr-x 10 root root 4.0K Jul 27 09:00 ..

/etc/cron-apt/logmsg.d:
total 8.0K
drwxr-xr-x  2 root root 4.0K Jan  1  2021 .
drwxr-xr-x 10 root root 4.0K Jul 27 09:00 ..

/etc/cron-apt/mailmsg.d:
total 16K
drwxr-xr-x  2 root root 4.0K Oct  4 22:11 .
drwxr-xr-x 10 root root 4.0K Jul 27 09:00 ..
-rw-r--r--  1 root root  479 Jul 27 09:00 3-download
-rw-r--r--  1 root root   69 Oct  4 22:11 5-openmediavault-security

/etc/cron-apt/mailonmsgs:
total 8.0K
drwxr-xr-x  2 root root 4.0K Jan  1  2021 .
drwxr-xr-x 10 root root 4.0K Jul 27 09:00 ..

/etc/cron-apt/syslogmsg.d:
total 8.0K
drwxr-xr-x  2 root root 4.0K Jan  1  2021 .
drwxr-xr-x 10 root root 4.0K Jul 27 09:00 ..

/etc/cron-apt/syslogonmsgs:
total 8.0K
drwxr-xr-x  2 root root 4.0K Jan  1  2021 .
drwxr-xr-x 10 root root 4.0K Jul 27 09:00 ..
```
Does that match yours?

**Comment by mortee** [comment]
Nope. Again, this is _missing_, and the cron-apt salt command doesn't do anything about it:
```
/etc/cron-apt/action.d:
-rw-r--r--  1 root root   64 Jan  1  2021 3-download
```

**Comment by votdev** [comment]
> Nope. Again, this is _missing_, and the cron-apt salt command doesn't do anything about it:
> 
> ```
> /etc/cron-apt/action.d:
> -rw-r--r--  1 root root   64 Jan  1  2021 3-download
> ```

Please post the output of `salt-call pkg.list_repos`

**Comment by votdev** [comment]
> Nope. Again, this is _missing_, and the cron-apt salt command doesn't do anything about it:
> 
> ```
> /etc/cron-apt/action.d:
> -rw-r--r--  1 root root   64 Jan  1  2021 3-download
> ```

This file is under control of the [cron-apt package](https://packages.debian.org/bullseye/all/cron-apt/filelist), not OMV. This would mean that the package is not installed correctly IMO.

Try running `apt-get install --reinstall cron-apt` to fix that.

**Comment by mortee** [comment]
I joined the conversation mentioning that I did just that, and the file still isn't there, despite `dpkg -V` (correctly) indicating that it should be.

> In any case:
> 
> ```
> $ sudo dpkg -V cron-apt
> ??5?????? c /etc/cron-apt/action.d/3-download
> ??5?????? c /etc/cron.d/cron-apt
> $ sudo apt-get --reinstall install cron-apt
> ...
> 0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
> ...
> $ ls /etc/cron-apt/action.d
> 0-update
> 5-openmediavault-security
> ```

**Comment by votdev** [comment]
> I joined the conversation mentioning that I did just that, and the file still isn't there, despite `dpkg -V` (correctly) indicating that it should be.
> 
> > In any case:
> > ```
> > $ sudo dpkg -V cron-apt
> > ??5?????? c /etc/cron-apt/action.d/3-download
> > ??5?????? c /etc/cron.d/cron-apt
> > $ sudo apt-get --reinstall install cron-apt
> > ...
> > 0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
> > ...
> > $ ls /etc/cron-apt/action.d
> > 0-update
> > 5-openmediavault-security
> > ```

Sorry, this thread is not the only one i am reading, so i can not have an overview about everything.

In that case i have no idea what is going wrong here or how to fix that. Maybe a bug in Debian, but this is actually not imaginable.

**Comment by ryecoaaron** [comment]
The /etc/cron-apt/action.d/3-download file is part of the cron-apt package.  https://packages.debian.org/bullseye/all/cron-apt/filelist 

In my opinion, it should not be something OMV ensures is there.  If the system is old, it is possible that the flashmemory plugin removed the file but that has been almost three years since I changed the plugin to stop doing that - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-flashmemory/commit/e148922e47ab3df33016de4dd2e946cd7a68c4a4

I would just recreate the file on your system and call it a day.  Here is the file content if needed:
```
$ cat /etc/cron-apt/action.d/3-download
autoclean -y
dist-upgrade -d -y -o APT::Get::Show-Upgraded=true
```

**Comment by mortee** [comment]
@votdev, sure, I didn't mean any offense. The fact that apt-get --reinstall didn't recreate the file made me think that somehow OMV's involved - now it's clear it is not.

@ryecoaaron, thanks, in that case I'll just recreate it manually. Are any special permissions/ownership required?

**Comment by votdev** [comment]
> In my opinion, it should not be something OMV ensures is there.

I don't think so, up to a certain point you should be able to rely on a behaviour of the system, here that the files are installed by the package management. Otherwise this would mean that OMV needs to take care about every other file that a service or parts of the system rely on.


> I would just recreate the file on your system and call it a day. Here is the file content if needed:
> 
> ```
> $ cat /etc/cron-apt/action.d/3-download
> autoclean -y
> dist-upgrade -d -y -o APT::Get::Show-Upgraded=true
> ```

That sounds like a good solution to me.

Nevertheless it would be interested to find out why APT does not reinstall the file if told. Probably apt somehow checks if files are deleted by the user that were installed by a package. I'm not too deep into the subject to say anything about the behavior of APT here.

**Comment by ryecoaaron** [comment]
it is owned by root:root and 0644 perms.

**Comment by ryecoaaron** [comment]
> I don't think so, up to a certain point you should be able to rely on a behaviour of the system, here that the files are installed by the package management. Otherwise this would mean that OMV needs to take care about every other file that a service or parts of the system rely on.

I did write "should **not**" be something OMV does : )

**Comment by votdev** [comment]
> > I don't think so, up to a certain point you should be able to rely on a behaviour of the system, here that the files are installed by the package management. Otherwise this would mean that OMV needs to take care about every other file that a service or parts of the system rely on.
> 
> I did write "should **not**" be something OMV does : )

Sorry, seems not my day today.
