### ISSUE TITLE
Wrong IP address reported by GUI

### ISSUE THREAD

**Issue by TheFax** [openmediavault/openmediavault#91]
Steps to reproduce the problem:
1) fresh install OMV 4 (actually, 4.1.4-1 is running on my system)
2) **assign a static IP** to the nas, and apply the changes.
3) log in into the NAS with the new IP assigned
4) **return to DHCP** mode, and apply the changes.
5) reboot OMV
6) [during reboot, OMV will ask an IP to the DHCP server]
7) log in into the NAS, using the IP assigned by DHCP
8) Now what is wrong --> **the GUI is reporting the OLD static IP**, not the DHCP assigned one.
![cattura](https://user-images.githubusercontent.com/19174767/39170519-2ea3a812-479c-11e8-8eb5-2a55701b2fac.JPG)

**Comment by votdev** [comment]
This panel does not display the current IP addresses, instead it displays the configured data only. The dashboard shows the current IP address.
