### ISSUE TITLE
Implement Time Machine quota setting

### ISSUE THREAD

**Issue by ishioni** [openmediavault/openmediavault#910]
**Is your feature request related to a problem? Please describe.**
Implement time machine quota 
**Describe the solution you'd like**
There are 2 ways to do this, dependent on samba version. For versions that implement time machine properly on vfs_fruit, it is enough to add to the share config
```
time machine max size = 200G
```

But I would discourage this, as it recalculates the share free space on every df call by the client (as seen in https://github.com/samba-team/samba/blob/master/source3/modules/vfs_fruit.c#L4985)

The better way to do this is to place a .com.apple.TimeMachine.quota.plist file in the share, with the contents
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>GlobalQuota</key>
<integer>300000000000</integer>
</dict>
</plist>
```

This works on MacOS 10.9 up to MacOS 11 Big Sur (can be checked by inspecting Info.plist in the sparsebundle under the <string>com.apple.diskimage.sparsebundle</string> key. Note that this quota works per-machine, so each machine backup gets their own quota from this limit, it is not shared.

**Describe alternatives you've considered**
Filesystem quotas do not work, since samba does not export them to the client (or at least MacOS doesn't recognize them)

**Comment by poranje** [comment]
Shouldn't .com.apple.TimeMachine.quota.plist  be name .com.apple.timemachine.quota.plist ?
(no capatalisation)

**Comment by edgimar** [comment]
@votdev, any chance this one might be reconsidered?  It seems pretty straightforward to implement -- I am not super familiar with the OMV codebase, but if you can provide suggestions on what would need to change and how, I'm sure that I or others could attempt to create a PR.
