### ISSUE TITLE
Execisve DNS queries of own local domain name

### ISSUE THREAD

**Issue by SandMouse** [openmediavault/openmediavault#911]
In my opinion OMV does a lot of unnecessary DNS queries of it's own local domain name.  Thousands per 24 hours. It seems that the OS frequently tries to resolve its own domain name. I discovered this while reviewing the log of my pihole dns server. In addition, many MX lookups are done when the configuration page for 'Notifications' is open. By many a I mean multiple queries per second. Is this functionally necessary or could the number of queries be reduced? Do others have this experience too? I'm happy to supply more details if necessary.

OMV 5.5.20-1 (Usul)
Linux 5.9.0.0-bpo.2-amd64

**Comment by votdev** [comment]
> MX lookups are done when the configuration page for 'Notifications' is open

Never seen that and it seem to me not impossible because the webui does not trigger any action itself. There are also no RPC's executed that might cause this.

**Comment by SandMouse** [comment]
@votdev The overwhelming amount of MX lookups while the 'Notifications' configuration page is open is very much reproducible. Disabling the the e-mail notifications is a work around but leaves you, obviously, without any notification.

Could my /etc/hosts be mis-configured?
`127.0.0.1	localhost localhost.localdomain
127.0.1.1	myomv myomv.ashortlocaldomain
172.31.4.225	myomv myomv.ashortlocaldomain

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters`

Or my /etc/resolv.conf?
`domain ashortlocaldomain
search ashortlocaldomain
nameserver 192.168.x.x`

**Comment by SandMouse** [comment]
By the way, did you mean to write "not impossible" since you added the tag "can't reproduce" ?

**Comment by votdev** [comment]
> By the way, did you mean to write "not impossible" since you added the tag "can't reproduce" ?

... seem to me impossible because ...

**Comment by votdev** [comment]
Maybe you've installed a plugin that adds some functionality to the notification page (i don't know every plugin that exists, so i can only guess), but openmediavault core does not do any action that might cause this. If you visit a page in the UI, the only thing that is done is to load the configuration from the database.

**Comment by SandMouse** [comment]
I do have one plug-in installed: openmediavault-omvextraorg 5.4.2. And I have installed Docker: 5:20.10.1~3-0~debian-buster. When I shut down the docker service and opened the 'Notification' configuration page. The problem persists. Could the openmediavault-omvextraorg 5.4.2. be the culprit? That seems unlikely.

**Comment by votdev** [comment]
I've checked the sources again, but there is really nothing that actively does any network actions.

https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/var/www/openmediavault/js/omv/module/admin/system/notification/Notification.js#L295
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/notification.inc#L66

I can not say anything related to `openmediavault-omvextraorg`.

**Comment by ryecoaaron** [comment]
The omv-extras plugin has no service. So it is not doing anything. It just adds repos and gives the user the ability to install docker. Maybe docker and/or container(s) are doing this??

**Comment by SandMouse** [comment]
Thank you for all the great comments. I'm dissecting my "defauilt" "omv-extras-Docker-installation" as we speak. I'll report back if I find something.

**Comment by SandMouse** [comment]
I've added:

```
extra_hosts:
    - "myomv.ashortlocaldomain:192.168.x.y"
 ```
to all of the `docker-compose.yml` file for my docker containers. This adds and entry in the `/etc/hosts` file of said containers. This should minimize the amount of dns queries to my dns server. I'll be patient and report back with the results.

**Comment by ryecoaaron** [comment]
Can I ask why you are trying to limit dns queries?  My dns server is seeing more than 200K queries a day and there is almost no load on it.  It is a rock64.

**Comment by votdev** [comment]
Closed because the issue is not related to openmediavault.
