### ISSUE TITLE
One of two devices in external Iomega USB Enclosures not shown

### ISSUE THREAD

**Issue by chunyianliew** [openmediavault/openmediavault#912]
I've attached two external harddisks to a Raspberry Pi running OpenMedia Vault.
The disks appear in the gui, but one of the two devices are not shown.

Screenshot of the Disk Listing showing the two external disks

![omv_001](https://user-images.githubusercontent.com/25181934/103459198-af8b7d00-4d0d-11eb-808a-85d47abf613b.png)

Screenshot of Device Listing showing only one of the two devices

![omv_002](https://user-images.githubusercontent.com/25181934/103459213-d8ac0d80-4d0d-11eb-8790-5f24777e01a6.png)

Why is only one of the devices showing up? I would expect that /dev/sdb1 would also be listed as one of the devices.

Output of 'sudo blkid':

> /dev/mmcblk0p1: LABEL_FATBOOT="boot" LABEL="boot" UUID="EBBA-157F" TYPE="vfat" PARTUUID="11048028-01"
> /dev/mmcblk0p2: LABEL="rootfs" UUID="b3ce35cd-ade9-4755-a4bb-1571e37fc1b9" TYPE="ext4" PARTUUID="11048028-02"
> /dev/sda1: LABEL="Iomega HDD" UUID="04D4B058D4B04E24" TYPE="ntfs" PARTUUID="42b872ce-01"
> /dev/sdb1: LABEL="IomegaBD01" UUID="04D4B058D4B04E24" TYPE="ntfs" PARTUUID="ee109927-01"
> /dev/sdc3: UUID="670a1715-0618-34d8-be25-ae24e001c2e6" LABEL="MBP_CHUN" TYPE="hfsplus" PARTLABEL="MBP_CHUN"
> /dev/sdd1: LABEL="LaCie01" UUID="78E4F861E4F82354" TYPE="ntfs" PARTUUID="454c230f-01"
> /dev/mmcblk0: PTUUID="11048028" PTTYPE="dos"
> /dev/sdc1: PARTLABEL="Apple"

Output of 'sudo udevadm info /dev/sda':

> P: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/block/sda
> N: sda
> L: 0
> S: disk/by-id/usb-ST320005_42AS_FF320005420000000000009FF0F1FF-0:0
> S: disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-scsi-0:0:0:0
> E: DEVPATH=/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/block/sda
> E: DEVNAME=/dev/sda
> E: DEVTYPE=disk
> E: MAJOR=8
> E: MINOR=0
> E: SUBSYSTEM=block
> E: USEC_INITIALIZED=5643689
> E: ID_VENDOR=ST320005
> E: ID_VENDOR_ENC=ST320005
> E: ID_VENDOR_ID=059b
> E: ID_MODEL=42AS
> E: ID_MODEL_ENC=42AS\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
> E: ID_MODEL_ID=0577
> E: ID_REVISION=010f
> E: ID_SERIAL=ST320005_42AS_FF320005420000000000009FF0F1FF-0:0
> E: ID_SERIAL_SHORT=FF320005420000000000009FF0F1FF
> E: ID_TYPE=disk
> E: ID_INSTANCE=0:0
> E: ID_BUS=usb
> E: ID_USB_INTERFACES=:080650:
> E: ID_USB_INTERFACE_NUM=00
> E: ID_USB_DRIVER=usb-storage
> E: ID_PATH=platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-scsi-0:0:0:0
> E: ID_PATH_TAG=platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_1_1_0-scsi-0_0_0_0
> E: ID_PART_TABLE_UUID=42b872ce
> E: ID_PART_TABLE_TYPE=dos
> E: DEVLINKS=/dev/disk/by-id/usb-ST320005_42AS_FF320005420000000000009FF0F1FF-0:0 /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-scsi-0:0:0:0
> E: TAGS=:systemd:
> 

Output of 'sudo udevadm info /dev/sdb':

> P: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.2/1-1.2:1.0/host1/target1:0:0/1:0:0:0/block/sdb
> N: sdb
> L: 0
> S: disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-scsi-0:0:0:0
> S: disk/by-id/usb-ST320005_42AS_FF320005420000000000009FF0F01F-0:0
> E: DEVPATH=/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.2/1-1.2:1.0/host1/target1:0:0/1:0:0:0/block/sdb
> E: DEVNAME=/dev/sdb
> E: DEVTYPE=disk
> E: MAJOR=8
> E: MINOR=16
> E: SUBSYSTEM=block
> E: USEC_INITIALIZED=6153545
> E: ID_VENDOR=ST320005
> E: ID_VENDOR_ENC=ST320005
> E: ID_VENDOR_ID=059b
> E: ID_MODEL=42AS
> E: ID_MODEL_ENC=42AS\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
> E: ID_MODEL_ID=0577
> E: ID_REVISION=010f
> E: ID_SERIAL=ST320005_42AS_FF320005420000000000009FF0F01F-0:0
> E: ID_SERIAL_SHORT=FF320005420000000000009FF0F01F
> E: ID_TYPE=disk
> E: ID_INSTANCE=0:0
> E: ID_BUS=usb
> E: ID_USB_INTERFACES=:080650:
> E: ID_USB_INTERFACE_NUM=00
> E: ID_USB_DRIVER=usb-storage
> E: ID_PATH=platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-scsi-0:0:0:0
> E: ID_PATH_TAG=platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_2_1_0-scsi-0_0_0_0
> E: ID_PART_TABLE_UUID=ee109927
> E: ID_PART_TABLE_TYPE=dos
> E: DEVLINKS=/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-scsi-0:0:0:0 /dev/disk/by-id/usb-ST320005_42AS_FF320005420000000000009FF0F01F-0:0
> E: TAGS=:systemd:
> 

Output of 'sudo udevadm test /sys/block/sda', I've set the logging level for udev to debug in /etc/udev/udev.conf using the configuration parameter 'udev_log=debug':

> This program is for debugging only, it does not run any program
> specified by a RUN key. It may show incorrect results, because
> some values may be different, or not available at a simulation run.
> 
> === trie on-disk ===
> tool version:          241
> file size:         9639868 bytes
> header size             80 bytes
> strings            2070548 bytes
> nodes              7569240 bytes
> Load module index
> Found container virtualization none.
> timestamp of '/etc/systemd/network' changed
> Parsed configuration file /usr/lib/systemd/network/99-default.link
> Created link configuration context.
> timestamp of '/etc/udev/rules.d' changed
> timestamp of '/lib/udev/rules.d' changed
> Reading rules file: /usr/lib/udev/rules.d/01-md-raid-creating.rules
> Reading rules file: /usr/lib/udev/rules.d/10-local-rpi.rules
> Reading rules file: /usr/lib/udev/rules.d/15-i2c-modprobe.rules
> Reading rules file: /usr/lib/udev/rules.d/39-usbmuxd.rules
> Reading rules file: /usr/lib/udev/rules.d/40-usb_modeswitch.rules
> Reading rules file: /usr/lib/udev/rules.d/50-firmware.rules
> Reading rules file: /usr/lib/udev/rules.d/50-udev-default.rules
> Reading rules file: /usr/lib/udev/rules.d/55-dm.rules
> Reading rules file: /usr/lib/udev/rules.d/56-lvm.rules
> Reading rules file: /usr/lib/udev/rules.d/60-block.rules
> Reading rules file: /usr/lib/udev/rules.d/60-cdrom_id.rules
> Reading rules file: /usr/lib/udev/rules.d/60-crda.rules
> Reading rules file: /usr/lib/udev/rules.d/60-drm.rules
> Reading rules file: /usr/lib/udev/rules.d/60-evdev.rules
> Reading rules file: /usr/lib/udev/rules.d/60-flashrom.rules
> Reading rules file: /usr/lib/udev/rules.d/60-input-id.rules
> Reading rules file: /usr/lib/udev/rules.d/60-persistent-alsa.rules
> Reading rules file: /usr/lib/udev/rules.d/60-persistent-input.rules
> Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage-dm.rules
> Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage-tape.rules
> Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage.rules
> Reading rules file: /usr/lib/udev/rules.d/60-persistent-v4l.rules
> Reading rules file: /usr/lib/udev/rules.d/60-rpi.gpio-common.rules
> Reading rules file: /usr/lib/udev/rules.d/60-sensor.rules
> Reading rules file: /usr/lib/udev/rules.d/60-serial.rules
> Reading rules file: /usr/lib/udev/rules.d/60-triggerhappy.rules
> Reading rules file: /usr/lib/udev/rules.d/63-md-raid-arrays.rules
> Reading rules file: /usr/lib/udev/rules.d/64-btrfs-dm.rules
> Reading rules file: /usr/lib/udev/rules.d/64-btrfs.rules
> Reading rules file: /usr/lib/udev/rules.d/64-md-raid-assembly.rules
> Reading rules file: /usr/lib/udev/rules.d/69-libmtp.rules
> Reading rules file: /usr/lib/udev/rules.d/69-lvm-metad.rules
> Reading rules file: /usr/lib/udev/rules.d/69-md-clustered-confirm-device.rules
> Reading rules file: /usr/lib/udev/rules.d/70-joystick.rules
> Reading rules file: /usr/lib/udev/rules.d/70-microbit.rules
> Reading rules file: /usr/lib/udev/rules.d/70-mouse.rules
> Reading rules file: /usr/lib/udev/rules.d/70-pcspkr-beep.rules
> Reading rules file: /usr/lib/udev/rules.d/70-power-switch.rules
> Reading rules file: /usr/lib/udev/rules.d/70-touchpad.rules
> Reading rules file: /usr/lib/udev/rules.d/70-uaccess.rules
> Reading rules file: /usr/lib/udev/rules.d/71-seat.rules
> Reading rules file: /usr/lib/udev/rules.d/73-seat-late.rules
> Reading rules file: /usr/lib/udev/rules.d/73-special-net-names.rules
> Reading rules file: /usr/lib/udev/rules.d/73-usb-net-by-mac.rules
> Reading rules file: /usr/lib/udev/rules.d/75-net-description.rules
> Reading rules file: /usr/lib/udev/rules.d/75-probe_mtd.rules
> Reading rules file: /usr/lib/udev/rules.d/78-sound-card.rules
> Reading rules file: /usr/lib/udev/rules.d/80-debian-compat.rules
> Reading rules file: /usr/lib/udev/rules.d/80-drivers.rules
> Reading rules file: /usr/lib/udev/rules.d/80-ifupdown.rules
> Reading rules file: /usr/lib/udev/rules.d/80-net-setup-link.rules
> Reading rules file: /usr/lib/udev/rules.d/80-noobs.rules
> Reading rules file: /usr/lib/udev/rules.d/85-hdparm.rules
> Reading rules file: /usr/lib/udev/rules.d/85-hwclock.rules
> Reading rules file: /usr/lib/udev/rules.d/85-regulatory.rules
> Reading rules file: /usr/lib/udev/rules.d/89-alsa-ucm.rules
> Reading rules file: /usr/lib/udev/rules.d/90-alsa-restore.rules
> Reading rules file: /usr/lib/udev/rules.d/90-console-setup.rules
> Reading rules file: /usr/lib/udev/rules.d/90-pi-bluetooth.rules
> Reading rules file: /usr/lib/udev/rules.d/95-dm-notify.rules
> Reading rules file: /usr/lib/udev/rules.d/95-upower-csr.rules
> Reading rules file: /usr/lib/udev/rules.d/95-upower-hid.rules
> Reading rules file: /usr/lib/udev/rules.d/95-upower-wup.rules
> Reading rules file: /usr/lib/udev/rules.d/97-hid2hci.rules
> Reading rules file: /etc/udev/rules.d/99-com.rules
> Reading rules file: /etc/udev/rules.d/99-openmediavault-dev-disk-by-id.rules
> Reading rules file: /etc/udev/rules.d/99-openmediavault-md-raid.rules
> Reading rules file: /etc/udev/rules.d/99-openmediavault-nonrot.rules
> Reading rules file: /etc/udev/rules.d/99-openmediavault-scheduler.rules
> Reading rules file: /usr/lib/udev/rules.d/99-systemd.rules
> Reading rules file: /usr/lib/udev/rules.d/usbmount.rules
> Rules contain 196608 bytes tokens (16384 * 12 bytes), 28706 bytes strings
> 16652 strings (140231 bytes), 14060 de-duplicated (114118 bytes), 2593 trie nodes used
> Invalid inotify descriptor.
> sda: GROUP 6 /usr/lib/udev/rules.d/50-udev-default.rules:59
> sda: IMPORT 'ata_id --export /dev/sda' /usr/lib/udev/rules.d/60-persistent-storage.rules:46
> Starting 'ata_id --export /dev/sda'
> Successfully forked off '(spawn)' as PID 6689.
> Process 'ata_id --export /dev/sda' failed with exit code 2.
> sda: IMPORT builtin 'usb_id' /usr/lib/udev/rules.d/60-persistent-storage.rules:49
> 1-1.1:1.0: if_class:8 protocol:6
> sda: LINK 'disk/by-id/usb-ST320005_42AS_FF320005420000000000009FF0F1FF-0:0' /usr/lib/udev/rules.d/60-persistent-storage.rules:54
> sda: IMPORT builtin 'path_id' /usr/lib/udev/rules.d/60-persistent-storage.rules:78
> sda: LINK 'disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-scsi-0:0:0:0' /usr/lib/udev/rules.d/60-persistent-storage.rules:80
> sda: IMPORT builtin 'blkid' /usr/lib/udev/rules.d/60-persistent-storage.rules:95
> sda: Probe /dev/sda with raid and offset=0
> sda: RUN '/lib/udev/hdparm' /usr/lib/udev/rules.d/85-hdparm.rules:1
> sda: ATTR '/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/block/sda/queue/scheduler' writing 'cfq' /etc/udev/rules.d/99-openmediavault-scheduler.rules:24
> sda: RUN '/usr/share/usbmount/usbmount add' /usr/lib/udev/rules.d/usbmount.rules:4
> sda: Handling device node '/dev/sda', devnum=b8:0, mode=0660, uid=0, gid=6
> sda: Preserve permissions of /dev/sda, 060660, uid=0, gid=6
> sda: Preserve already existing symlink '/dev/block/8:0' to '../sda'
> sda: Found 'b8:0' claiming '/run/udev/links/\x2fdisk\x2fby-id\x2fusb-ST320005_42AS_FF320005420000000000009FF0F1FF-0:0'
> sda: Preserve already existing symlink '/dev/disk/by-id/usb-ST320005_42AS_FF320005420000000000009FF0F1FF-0:0' to '../../sda'
> sda: Found 'b8:0' claiming '/run/udev/links/\x2fdisk\x2fby-path\x2fplatform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-scsi-0:0:0:0'
> sda: Preserve already existing symlink '/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-scsi-0:0:0:0' to '../../sda'
> sda: sd-device: Created db file '/run/udev/data/b8:0' for '/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/block/sda'
> DEVPATH=/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/block/sda
> DEVNAME=/dev/sda
> DEVTYPE=disk
> MAJOR=8
> MINOR=0
> ACTION=add
> SUBSYSTEM=block
> ID_VENDOR=ST320005
> ID_VENDOR_ENC=ST320005
> ID_VENDOR_ID=059b
> ID_MODEL=42AS
> ID_MODEL_ENC=42AS\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
> ID_MODEL_ID=0577
> ID_REVISION=010f
> ID_SERIAL=ST320005_42AS_FF320005420000000000009FF0F1FF-0:0
> ID_SERIAL_SHORT=FF320005420000000000009FF0F1FF
> ID_TYPE=disk
> ID_INSTANCE=0:0
> ID_BUS=usb
> ID_USB_INTERFACES=:080650:
> ID_USB_INTERFACE_NUM=00
> ID_USB_DRIVER=usb-storage
> DEVLINKS=/dev/disk/by-id/usb-ST320005_42AS_FF320005420000000000009FF0F1FF-0:0 /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-scsi-0:0:0:0
> ID_PATH=platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-scsi-0:0:0:0
> ID_PATH_TAG=platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_1_1_0-scsi-0_0_0_0
> ID_PART_TABLE_UUID=42b872ce
> ID_PART_TABLE_TYPE=dos
> .ID_FS_TYPE_NEW=
> ID_FS_TYPE=
> TAGS=:systemd:
> USEC_INITIALIZED=5643689
> run: '/lib/udev/hdparm'
> run: '/usr/share/usbmount/usbmount add'
> Unload module index
> Unloaded link configuration context.
> 

Output of 'sudo udevadm test /sys/block/sdb':

> This program is for debugging only, it does not run any program
> specified by a RUN key. It may show incorrect results, because
> some values may be different, or not available at a simulation run.
> 
> === trie on-disk ===
> tool version:          241
> file size:         9639868 bytes
> header size             80 bytes
> strings            2070548 bytes
> nodes              7569240 bytes
> Load module index
> Found container virtualization none.
> timestamp of '/etc/systemd/network' changed
> Parsed configuration file /usr/lib/systemd/network/99-default.link
> Created link configuration context.
> timestamp of '/etc/udev/rules.d' changed
> timestamp of '/lib/udev/rules.d' changed
> Reading rules file: /usr/lib/udev/rules.d/01-md-raid-creating.rules
> Reading rules file: /usr/lib/udev/rules.d/10-local-rpi.rules
> Reading rules file: /usr/lib/udev/rules.d/15-i2c-modprobe.rules
> Reading rules file: /usr/lib/udev/rules.d/39-usbmuxd.rules
> Reading rules file: /usr/lib/udev/rules.d/40-usb_modeswitch.rules
> Reading rules file: /usr/lib/udev/rules.d/50-firmware.rules
> Reading rules file: /usr/lib/udev/rules.d/50-udev-default.rules
> Reading rules file: /usr/lib/udev/rules.d/55-dm.rules
> Reading rules file: /usr/lib/udev/rules.d/56-lvm.rules
> Reading rules file: /usr/lib/udev/rules.d/60-block.rules
> Reading rules file: /usr/lib/udev/rules.d/60-cdrom_id.rules
> Reading rules file: /usr/lib/udev/rules.d/60-crda.rules
> Reading rules file: /usr/lib/udev/rules.d/60-drm.rules
> Reading rules file: /usr/lib/udev/rules.d/60-evdev.rules
> Reading rules file: /usr/lib/udev/rules.d/60-flashrom.rules
> Reading rules file: /usr/lib/udev/rules.d/60-input-id.rules
> Reading rules file: /usr/lib/udev/rules.d/60-persistent-alsa.rules
> Reading rules file: /usr/lib/udev/rules.d/60-persistent-input.rules
> Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage-dm.rules
> Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage-tape.rules
> Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage.rules
> Reading rules file: /usr/lib/udev/rules.d/60-persistent-v4l.rules
> Reading rules file: /usr/lib/udev/rules.d/60-rpi.gpio-common.rules
> Reading rules file: /usr/lib/udev/rules.d/60-sensor.rules
> Reading rules file: /usr/lib/udev/rules.d/60-serial.rules
> Reading rules file: /usr/lib/udev/rules.d/60-triggerhappy.rules
> Reading rules file: /usr/lib/udev/rules.d/63-md-raid-arrays.rules
> Reading rules file: /usr/lib/udev/rules.d/64-btrfs-dm.rules
> Reading rules file: /usr/lib/udev/rules.d/64-btrfs.rules
> Reading rules file: /usr/lib/udev/rules.d/64-md-raid-assembly.rules
> Reading rules file: /usr/lib/udev/rules.d/69-libmtp.rules
> Reading rules file: /usr/lib/udev/rules.d/69-lvm-metad.rules
> Reading rules file: /usr/lib/udev/rules.d/69-md-clustered-confirm-device.rules
> Reading rules file: /usr/lib/udev/rules.d/70-joystick.rules
> Reading rules file: /usr/lib/udev/rules.d/70-microbit.rules
> Reading rules file: /usr/lib/udev/rules.d/70-mouse.rules
> Reading rules file: /usr/lib/udev/rules.d/70-pcspkr-beep.rules
> Reading rules file: /usr/lib/udev/rules.d/70-power-switch.rules
> Reading rules file: /usr/lib/udev/rules.d/70-touchpad.rules
> Reading rules file: /usr/lib/udev/rules.d/70-uaccess.rules
> Reading rules file: /usr/lib/udev/rules.d/71-seat.rules
> Reading rules file: /usr/lib/udev/rules.d/73-seat-late.rules
> Reading rules file: /usr/lib/udev/rules.d/73-special-net-names.rules
> Reading rules file: /usr/lib/udev/rules.d/73-usb-net-by-mac.rules
> Reading rules file: /usr/lib/udev/rules.d/75-net-description.rules
> Reading rules file: /usr/lib/udev/rules.d/75-probe_mtd.rules
> Reading rules file: /usr/lib/udev/rules.d/78-sound-card.rules
> Reading rules file: /usr/lib/udev/rules.d/80-debian-compat.rules
> Reading rules file: /usr/lib/udev/rules.d/80-drivers.rules
> Reading rules file: /usr/lib/udev/rules.d/80-ifupdown.rules
> Reading rules file: /usr/lib/udev/rules.d/80-net-setup-link.rules
> Reading rules file: /usr/lib/udev/rules.d/80-noobs.rules
> Reading rules file: /usr/lib/udev/rules.d/85-hdparm.rules
> Reading rules file: /usr/lib/udev/rules.d/85-hwclock.rules
> Reading rules file: /usr/lib/udev/rules.d/85-regulatory.rules
> Reading rules file: /usr/lib/udev/rules.d/89-alsa-ucm.rules
> Reading rules file: /usr/lib/udev/rules.d/90-alsa-restore.rules
> Reading rules file: /usr/lib/udev/rules.d/90-console-setup.rules
> Reading rules file: /usr/lib/udev/rules.d/90-pi-bluetooth.rules
> Reading rules file: /usr/lib/udev/rules.d/95-dm-notify.rules
> Reading rules file: /usr/lib/udev/rules.d/95-upower-csr.rules
> Reading rules file: /usr/lib/udev/rules.d/95-upower-hid.rules
> Reading rules file: /usr/lib/udev/rules.d/95-upower-wup.rules
> Reading rules file: /usr/lib/udev/rules.d/97-hid2hci.rules
> Reading rules file: /etc/udev/rules.d/99-com.rules
> Reading rules file: /etc/udev/rules.d/99-openmediavault-dev-disk-by-id.rules
> Reading rules file: /etc/udev/rules.d/99-openmediavault-md-raid.rules
> Reading rules file: /etc/udev/rules.d/99-openmediavault-nonrot.rules
> Reading rules file: /etc/udev/rules.d/99-openmediavault-scheduler.rules
> Reading rules file: /usr/lib/udev/rules.d/99-systemd.rules
> Reading rules file: /usr/lib/udev/rules.d/usbmount.rules
> Rules contain 196608 bytes tokens (16384 * 12 bytes), 28706 bytes strings
> 16652 strings (140231 bytes), 14060 de-duplicated (114118 bytes), 2593 trie nodes used
> Invalid inotify descriptor.
> sdb: GROUP 6 /usr/lib/udev/rules.d/50-udev-default.rules:59
> sdb: IMPORT 'ata_id --export /dev/sdb' /usr/lib/udev/rules.d/60-persistent-storage.rules:46
> Starting 'ata_id --export /dev/sdb'
> Successfully forked off '(spawn)' as PID 6823.
> Process 'ata_id --export /dev/sdb' failed with exit code 2.
> sdb: IMPORT builtin 'usb_id' /usr/lib/udev/rules.d/60-persistent-storage.rules:49
> 1-1.2:1.0: if_class:8 protocol:6
> sdb: LINK 'disk/by-id/usb-ST320005_42AS_FF320005420000000000009FF0F01F-0:0' /usr/lib/udev/rules.d/60-persistent-storage.rules:54
> sdb: IMPORT builtin 'path_id' /usr/lib/udev/rules.d/60-persistent-storage.rules:78
> sdb: LINK 'disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-scsi-0:0:0:0' /usr/lib/udev/rules.d/60-persistent-storage.rules:80
> sdb: IMPORT builtin 'blkid' /usr/lib/udev/rules.d/60-persistent-storage.rules:95
> sdb: Probe /dev/sdb with raid and offset=0
> sdb: RUN '/lib/udev/hdparm' /usr/lib/udev/rules.d/85-hdparm.rules:1
> sdb: ATTR '/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.2/1-1.2:1.0/host1/target1:0:0/1:0:0:0/block/sdb/queue/scheduler' writing 'cfq' /etc/udev/rules.d/99-openmediavault-scheduler.rules:24
> sdb: RUN '/usr/share/usbmount/usbmount add' /usr/lib/udev/rules.d/usbmount.rules:4
> sdb: Handling device node '/dev/sdb', devnum=b8:16, mode=0660, uid=0, gid=6
> sdb: Preserve permissions of /dev/sdb, 060660, uid=0, gid=6
> sdb: Preserve already existing symlink '/dev/block/8:16' to '../sdb'
> sdb: Found 'b8:16' claiming '/run/udev/links/\x2fdisk\x2fby-path\x2fplatform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-scsi-0:0:0:0'
> sdb: Preserve already existing symlink '/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-scsi-0:0:0:0' to '../../sdb'
> sdb: Found 'b8:16' claiming '/run/udev/links/\x2fdisk\x2fby-id\x2fusb-ST320005_42AS_FF320005420000000000009FF0F01F-0:0'
> sdb: Preserve already existing symlink '/dev/disk/by-id/usb-ST320005_42AS_FF320005420000000000009FF0F01F-0:0' to '../../sdb'
> sdb: sd-device: Created db file '/run/udev/data/b8:16' for '/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.2/1-1.2:1.0/host1/target1:0:0/1:0:0:0/block/sdb'
> DEVPATH=/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.2/1-1.2:1.0/host1/target1:0:0/1:0:0:0/block/sdb
> DEVNAME=/dev/sdb
> DEVTYPE=disk
> MAJOR=8
> MINOR=16
> ACTION=add
> SUBSYSTEM=block
> ID_VENDOR=ST320005
> ID_VENDOR_ENC=ST320005
> ID_VENDOR_ID=059b
> ID_MODEL=42AS
> ID_MODEL_ENC=42AS\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
> ID_MODEL_ID=0577
> ID_REVISION=010f
> ID_SERIAL=ST320005_42AS_FF320005420000000000009FF0F01F-0:0
> ID_SERIAL_SHORT=FF320005420000000000009FF0F01F
> ID_TYPE=disk
> ID_INSTANCE=0:0
> ID_BUS=usb
> ID_USB_INTERFACES=:080650:
> ID_USB_INTERFACE_NUM=00
> ID_USB_DRIVER=usb-storage
> DEVLINKS=/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-scsi-0:0:0:0 /dev/disk/by-id/usb-ST320005_42AS_FF320005420000000000009FF0F01F-0:0
> ID_PATH=platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-scsi-0:0:0:0
> ID_PATH_TAG=platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_2_1_0-scsi-0_0_0_0
> ID_PART_TABLE_UUID=ee109927
> ID_PART_TABLE_TYPE=dos
> .ID_FS_TYPE_NEW=
> ID_FS_TYPE=
> TAGS=:systemd:
> USEC_INITIALIZED=6153545
> run: '/lib/udev/hdparm'
> run: '/usr/share/usbmount/usbmount add'
> Unload module index
> Unloaded link configuration context.
> 

**Additional context**
= openmediavault information
Release: 5.5.20-1
Codename: Usul
= System information
Linux rpi-omv 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux

**Comment by votdev** [comment]
The problem is the chipset in your USB enclosure, it reports the same serial ID for all attached devices. This serial IDs are used by UDEV to generate the device files which normally are unique, but in your case multiple devices share one device file. To fix that, ask the hardware manufacturer for a firmware fix or create an UDEV rule which requests the real serial ID from the device to create a unique device file.

You can find more information here:

* https://github.com/openmediavault/openmediavault/pull/909
* https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/etc/udev/rules.d/61-openmediavault-dev-disk-by-id.rules

I can not help here because the UDEv rules must be validated and checked which is impossible without having the hardware. Feel free to provide the UDEV rules here or via PR to get them included into openmediavault.

**Comment by votdev** [comment]
A rule might look like this according to the given UDEV information:
```
# https://devicehunt.com/search/type/usb/vendor/059B/device/any
ENV{ID_VENDOR_ID}=="059b", \
  ENV{ID_MODEL_ID}=="0577", \
  IMPORT{program}="serial_id %N", \
  ENV{ID_SERIAL}="$env{ID_VENDOR}_$env{ID_MODEL}_$env{ID_SERIAL_SHORT}-$env{ID_INSTANCE}", \
  SYMLINK="disk/by-path/$env{ID_PATH}", \
  SYMLINK+="disk/by-id/$env{ID_BUS}-$env{ID_SERIAL}"
```

```
ID_MODEL=42AS
ID_MODEL_ENC=42AS\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_MODEL_ID=0577
```
I'm not sure if it is better to use `ID_MODEL` or `ID_MODEL_ID`. Having an exact name/model of the enclosure will help to decide the right one maybe.

It's now up to you to validate and confirm which UDEV rule will fix the issue. After that we can include it into openmediavault.

**Comment by chunyianliew** [comment]
@votdev, the serial id's for the two drives are different?:
/dev/sda: FF320005420000000000009FF0F1FF
/dev/sdb: FF320005420000000000009FF0F01F

**Comment by votdev** [comment]
> @votdev, the serial id's for the two drives are different?:
> /dev/sda: FF320005420000000000009FF0F1FF
> /dev/sdb: FF320005420000000000009FF0F01F

Upps, too much numbers looking the same... :-) Sorry.

Then i guess the problem is this. I thought it's caused by the device file problem, but now with that information that the serial ids are different...

```
/dev/sda1: LABEL="Iomega HDD" UUID="04D4B058D4B04E24" TYPE="ntfs" PARTUUID="42b872ce-01"
/dev/sdb1: LABEL="IomegaBD01" UUID="04D4B058D4B04E24" TYPE="ntfs" PARTUUID="ee109927-01"
```
The UUID of the filesystems are unique. This will confuse the webui because by default this is a unique identifier except in some special situations. I think this is not a RAID setup?

**Comment by chunyianliew** [comment]
@votdev, oh ic, so the GUI is listing the filesystems based on their UUID. As the UUID should be unique that makes sense.
I don't have a RAID setup at this moment. Just playing around a bit with OMV using a Raspberry Pi and a few external hdd's connecting over usb.

As the filesystem of the two drives is ntfs I changed the UUID of one of the two file systems by executing the following command in a shell: 
`sudo ntfslabel --new-serial /dev/sdb1`.

This has resolved my issue. Thank you very much for your support!
