### ISSUE TITLE
Cannot reset password with omv-firstaid

### ISSUE THREAD

**Issue by CasN** [openmediavault/openmediavault#913]
I have installed OMV5 on an existing debian 10 installation which worked without any issues.
after installing lamp alongside, everything was still fine.
After a following reboot, I could not login anymore, see below:
Error #0:
OMV\HttpErrorException: Incorrect username or password. in /var/www/openmediavault/rpc/session.inc:151
Stack trace:
#0 [internal function]: OMVRpcServiceSession->login(Array, Array)
#1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#2 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('login', Array, Array)
#3 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('Session', 'login', Array, Array, 3)
#4 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#5 {main}

so I logged in with root using putty and executed omv-firstaid.
If I change the password, system replies that admin password was changed.
However after logging, get the same message that user/password not correct.
If I try to reset the number of failed login attempts, i get the message
ERROR: [Errno 2] No such file or directory: 'pam_tally2'
so something seems to be dead wrong.
Anyone some tips to get this running again?

**Comment by votdev** [comment]
> after installing lamp alongside, everything was still fine.

This has surely crashed your system because Apache as part of LAMP (Linux, Apache, MySQL, PHP/Perl/Python) does not really work in harmony with nginx which is used by openmediavault. If you want to install such software beside openmediavault, then you should use container (Docker).

**Comment by CasN** [comment]
I wanted to avoid using containers so I installed OMV using port 90 and apache2 on port 80. I read somewhere that it should not be an issue to have them both on the same system.
I will start from scratch and see if i can determine what made it crash.

**Comment by votdev** [comment]
Consider using containers because polluting the system with software other than that which is under control of openmediavault will produce side effects as you see. In this case it is impossible to give any support. I hope you can understand that.

**Comment by CasN** [comment]
Yep, I was afraid so. I come from Ubuntu with an existing web setup hence tried to reproduce that. Will play around with the containers. Is it advisable to also use portainer or not?

**Comment by votdev** [comment]
@ryecoaaron Can give you some hints about that.

**Comment by ryecoaaron** [comment]
portainer (or yacht) helps if you are new to containers.  web server containers are pretty simple and you can find lots of tutorials on the internet.
