### ISSUE TITLE
Error when applying changes in ftp/smb/rsync/etc

### ISSUE THREAD

**Issue by thecamper** [openmediavault/openmediavault#914]
When changing the configuration of ftp/smb/rsync/etc. through the WebUI, I get an error message and have to revert the canges:

```
Fehler #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color avahi 2>&1' with exit code '1': daniel-nas.local:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.avahi.services.ftp' failed: Jinja error: shares: The value '
      ' is not an object.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 498, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 20, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 39, in get
    objs = db.get(id_, identifier)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 724, in execute
    self._response = self._elements_to_object(elements)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 485, in _elements_to_object
    result.validate()
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 236, in validate
    self.model.validate(self.get_dict())
  File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 202, in validate
    self.schema.validate(data)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 175, in validate
    self._validate_type(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 229, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 200, in _validate_type
    self._validate_object(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 305, in _validate_object
    self._check_properties(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 519, in _check_properties
    self._validate_type(value[propk], propv, path)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 229, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 200, in _validate_type
    self._validate_object(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 303, in _validate_object
    % ("NULL" if (value is None) else str(value)),
openmediavault.json.schema.SchemaValidationException: shares: The value '
      ' is not an object.

; line 20

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

{% set ftp_config = salt['omv_conf.get']('conf.service.ftp') %}    <======================
{% set ftp_zeroconf_enabled = salt['pillar.get']('default:OMV_PROFTPD_ZEROCONF_ENABLED', 1) %}
{% set ftp_zeroconf_name = salt['pillar.get']('default:OMV_PROFTPD_ZEROCONF_NAME', '%h - FTP') %}

{% if not (ftp_config.enable | to_bool and ftp_zeroconf_enabled | to_bool) %}

[...]
--- in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatuskk...', '/tmp/bgoutputiD...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

**Comment by votdev** [comment]
>     Rendering SLS 'base:omv.deploy.avahi.services.ftp' failed: Jinja error: shares: The value '
      ' is not an object.

It looks like your database is broken, there is somewhere a line-break that should not be there. This mostly happens when the `config.xml` file is manually modified. Is this the case?

I can sadly not request any information, e.g. by executing a command line tool, because those tools would also break because of the invalid database. The only thing you can do is to upload the whole `/etc/openmediavault/config.xml` if you want any help. Keep in mind that the database may contain sensitive data.

**Comment by thecamper** [comment]
I did in fact edit the config.xml manually to add mntent-entries for my btrfs-subvolumes. As I edited everything through ssh, they should all have linux line endings.
The `<shares>` section inside `<ftp>` is empty.

I attached my config.xml. I hope, I deleted all sensitive information:

[config.xml.txt](https://github.com/openmediavault/openmediavault/files/5762499/config.xml.txt)

**Comment by votdev** [comment]
Replace 
```
      <shares>
      </shares>
```
by
```
      <shares></shares>
```

**Comment by thecamper** [comment]
Easy as that. Thank you!

**Comment by mi-hol** [comment]
@votdev would it makes sense to publish a XML Schema (.xsd) for /etc/openmediavault/config.xml to allow for external validation tools to catch and pinpoint errors?

**Comment by votdev** [comment]
That's not possible because of plugins. Due that fact i introduced the [datamodels](https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/usr/share/openmediavault/datamodels) in OMV4.

**Comment by mi-hol** [comment]
Could the specific .json file be used (i.e. openmediavault/usr/share/openmediavault/datamodels/conf.service.ftp.json)  used to validate the matching section of /etc/openmediavault/config.xml ?

**Comment by votdev** [comment]
> Could the specific .json file be used (i.e. openmediavault/usr/share/openmediavault/datamodels/conf.service.ftp.json) to validate the matching section of /etc/openmediavault/config.xml ?

The datamodels are always used when objects are loaded from the database or written to it.

The problem here is that the configuration file was manually modified and the XML structure was not correct. openmediavault is not responsible for errors introduced by users. Touching the database is a NO GO. If a user needs to do it, then it is his responsibility and the user should always know what they are doing with all the consequences.

**Comment by mi-hol** [comment]
> openmediavault is not responsible for errors introduced by users. Touching the database is a NO GO. If a user needs to do it, then it is his responsibility and the user should always know what they are doing with all the consequences that arises.

Well we are in agreement, but the point I try to make is that instead of current situation that a weird error is shown that always ends up in a forum discussion or github issue, a validation would show the fact "Config file <name> is invalid, OMV can't start until this is fixed" in a user friendly way.
This would allow a user to revert the change most likely without depending on external help

**Comment by votdev** [comment]
> > openmediavault is not responsible for errors introduced by users. Touching the database is a NO GO. If a user needs to do it, then it is his responsibility and the user should always know what they are doing with all the consequences that arises.
> 
> Well we are in agreement, but the point I try to make is that instead of current situation that a weird error is shown that always ends up in a forum discussion or github issue, a validation would show the fact "Config file <Affected_config_name> is invalid, OMV can't start until this is fixed. This error stems most likely from a modification outside of OMV" in a user friendly way.
> This would allow a user to revert the change most likely without depending on external help

I don't want to include such error messages because it's too vague. There are tons of reasons why this can happen. I prefer a generic error message to a false one or one that doesn't fit at the moment.

Also believe me, if i would have found a better way to report  the error, it would have been already implemented.
