### ISSUE TITLE
SMTPS: certificate not properly validated

### ISSUE THREAD

**Issue by ragazzojp** [openmediavault/openmediavault#919]
It looks like the MTA (Postfix I suppose) is not checking if SMTP server certificates are correct when sending mail.

**To Reproduce**

1. Find/Setup a misconfigured SMTPS server. For example, create a random CNAME record on a DNS under your control to point to a well-known SMTP server that supports STARTTLS and requires authentication. This server will return a certificate matching its real name, so not matching the random name specified in the CNAME.
2. Configure OMV5 to send email through the misconfigured SMTP server, putting the CNAME as server address.
3. Send a test email.
4. The test email is sent successfully: this is insecure.

**Expected behavior**

The MTA/Postfix should not send the email and not even perform authentication in case the certificate name doesn't match the server name set by the user, as the server may be compromised and traffic decrypted by a man in the middle.

OMV5 should inform the user of this situation when the "Send a test email" button is pressed.

**openmediavault Server (please complete the following information):**

- OS version: Linux omv5 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
- openmediavault version: 5.5.21

Suggestion: experiment with msmtp, its `-v` option provides good debugging information. Try to replace Postfix with msmtp, as OMV5 doesn't need Postfix features such as receiving emails or running a fully-fledged mail server.

**Comment by votdev** [comment]
> Try to replace Postfix with msmtp, as OMV5 doesn't need Postfix features such as receiving emails or running a fully-fledged mail server.

This is incorrect. openmediavault notifications are heavily based on Postfix to support other notification methods like Telegram or whatever beside email. A hook in Postfix is responsible for that. Also emails from command line tools are normally send to an MTA, so Postfix is also required to forward those emails/messages.

**Comment by votdev** [comment]
> It looks like the MTA (Postfix I suppose) is not checking if SMTP server certificates are correct when sending mail.

Pull request to fix that are welcome.

**Comment by ragazzojp** [comment]
I'll try to prepare a PR. Suggest me please the place where the postfix configuration file is written/updated.

msmtp can be used in place of Postfix, including as MTA for mdadm and any other use case excluding sending notification to Telegram, that I didn't know it's a supported option. Fine, we can configure Postfix in a stricter way without replacing it.

**Comment by votdev** [comment]
The configuration files are deployed via the Salt state [omv.deploy.postfix](https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/srv/salt/omv/deploy/postfix).

The jinja2 template files can be found [here](https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/srv/salt/omv/deploy/postfix/files).

To test the configuration after modifying the templates simply run `omv-salt deploy run postfix`.
