### ISSUE TITLE
add a rate limit when sending mail so my IAP wont block me

### ISSUE THREAD

**Issue by edgd1er** [openmediavault/openmediavault#920]
**Is your feature request related to a problem? Please describe.**
Monit upon a problem send a mail, in case of multiple failure, many mails are send at the same time. 
scheduled tasks and containers also are able to send emails.

low cost or free email server are enforcing strict rules to preserve their servers.

**Describe the solution you'd like**
I wish there was a form to define here under values:
default_destination_recipient_limit = 2
default_destination_rate_delay = 12s
omvnotificationfilter_destination_recipient_limit = 20
omvnotificationfilter_destination_concurrency_limit = 1

**Describe alternatives you've considered**
For the time being, I add lines to main.cf , but openmediavault engine overwrite this file regularly.

**Additional context**
For free or low cost mail server, more strict rules are enforced and openmediavault has no GUI to define values to limit rate emission.

**Comment by votdev** [comment]
Can you please point me to the postfix documentation for this or any howtos to get familar?

The `default_destination_xxx` looks like a Postfix config option, but `omvnotificationfilter_destination_xxx`?

**Comment by edgd1er** [comment]
Extract from [postfix site](http://www.postfix.org/TUNING_README.html#rope)

this part is the one that may be interesting.

The default_destination_concurrency_limit parameter (default: 20) controls how many messages may be sent to the same destination simultaneously. **You can override this setting for specific message delivery transports by taking the name of the master.cf entry and appending "_destination_concurrency_limit".**

if not set [smtp_destination_concurrency_limit](http://www.postfix.org/postconf.5.html#smtp_destination_concurrency_limit) take default_destination_concurrency_limit as default.

So I guess the variable precedence is: omvnotificationfilter_destination_concurrency_limit > smtp_destination_concurrency_limit > default_destination_concurrency_limit

A more fine grained configuration may be set for specific slow or strict rate rules domains  but implementation might be complex and unneeded for openmediavault. 

I'm not an expert for postfix configuration, a postfix expert may step in and suggest better settings for emitting rate control.

**Comment by votdev** [comment]
> I'm not an expert for postfix configuration, a postfix expert may step in and suggest better settings for emitting rate control.

I'm also no Postfix super expert. Modifying the Postfix configuration is really tricky and you have to keep in mind that such changes affect hundred of thousand installations. Maybe it will be better to keep this issue open for community contributions that really know what to do.

In the meanwhile you can customize your configuration by doing the following steps.

1. Create the file `/srv/salt/omv/deploy/postfix/15main.sls` with the following content:
```
configure_postfix_main_custom:
  file.append:
    - name: "/etc/postfix/main.cf"
    - text: |
        default_destination_recipient_limit = 2
        default_destination_rate_delay = 12s
        omvnotificationfilter_destination_recipient_limit = 20
        omvnotificationfilter_destination_concurrency_limit = 1
```
2. Finally run `omv-salt deploy run postfix`.

**Comment by edgd1er** [comment]
I understand that modifying postfix may disturb many many installed openmediavault systems and nobody wants unhappy users.

Thanks for your suggestion, I'll write a script that will check openmediavault sls file to keep that modification upon omv upgrades.

Thanks again for your help and having created and maintaining openmediavault.
