### ISSUE TITLE
Bond interface: can't configure wlan slave interface.

### ISSUE THREAD

**Issue by welderpb** [openmediavault/openmediavault#921]
No possibility to configure wpa security options for slave wlan interface in bond mode.
If i add 'access point' definition manually in netplan configuration, all working as expected.
OVM overrides this changes, and removes 'access point' definition while saving configuration.

1. Add new bond interface.
2. Add slaves (one wired, second wlan)
3. Apply changes.
4. Receive error:
 stderr:
       /etc/netplan/40-openmediavault-bond0.yaml:9:7: Error in network definition: wlan0: No access points defined
          addresses: []
          ^

**Expected behavior**

Possibility to setup SSID and PSK for wlan slave interface.

**openmediavault Server (please complete the following information):**

- OS version:
  Distributor ID:	Debian
  Description:	Debian GNU/Linux 10 (buster)
  Release:	10
  Codename:	buster
 
- openmediavault version: [5.5.20-1]

**Client (please complete the following information):**

- OS: [Linux]
- Browser [Chromium]
- Version [87.0.4280.66]

**Comment by votdev** [comment]
You can create a custom netplan configuration file that contains your custom configuration. netplan will then merge this file with all others created by openmediavault. See https://github.com/openmediavault/openmediavault/issues/902#issuecomment-752209577 for an example.

Can you please post your modifications as example?

Nevertheless, i don't think it makes sense to bond a wlan interface.

**Comment by mi-hol** [comment]
@vordev I'd suggest to close it, due to not adhering to instructions for opening issues

**Comment by votdev** [comment]
> @vordev I'd suggest to close it, due to not adhering to instructions for opening issues

We should keep it open because i'm interested in the issue.

**Comment by votdev** [comment]
@welderpb Can you please post the output of `/etc/netplan/40-openmediavault-bond0.yaml`? And please don't forget to post your modifications, too.

The best would be to submit a full patch because you're the one who can test it on a live system. I can't do that without having a WLAN setup on my dev system.

**Comment by welderpb** [comment]
@votdev I understand than wlan interface isn't good for balancing traffic, but for fault-tolerance it is good option. For example when you need to re-cable or change patch cord.

/etc/netplan/40-openmediavault-bond0.yaml
network:
  ethernets:
    eth0:
      addresses: []
      dhcp4: false
      dhcp6: false
      wakeonlan: true
  wifis:
    wlan0:
      addresses: []
      dhcp4: false
      dhcp6: false
      wakeonlan: true
  bonds:
    bond0:
      addresses:
      - 192.168.1.2/24
      gateway4: 192.168.1.254
      dhcp4: false
      dhcp6: false
      link-local: []
      nameservers:
        addresses:
        - 192.168.1.254
      interfaces:
      - eth0
      - wlan0
      parameters:
        mode: active-backup
        primary: eth0
        primary-reselect-policy: always
        mii-monitor-interval: 100
        up-delay: 200
        down-delay: 200

my custom working modification:
network:
  ethernets:
    eth0:
      addresses: []
      dhcp4: false
      dhcp6: false
      wakeonlan: true
  wifis:
    wlan0:
      addresses: []
      dhcp4: false
      dhcp6: false
      access-points:
        "my_ssid":
            password: "strongpsk"
  bonds:
    bond0:
      addresses:
      - 192.168.1.2/24
      gateway4: 192.168.1.254
      dhcp4: false
      dhcp6: false
      link-local: []
      nameservers:
        addresses:
        - 192.168.1.254
      interfaces:
      - eth0
      - wlan0
      parameters:
        mode: active-backup
        primary: eth0
        primary-reselect-policy: always
        mii-monitor-interval: 100
        up-delay: 200
        down-delay: 200

after applying my modification i can see all interfaces is up and belong to the master.
cat /proc/net/bonding/bond0 
Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)

Bonding Mode: fault-tolerance (active-backup)
Primary Slave: eth0 (primary_reselect always)
Currently Active Slave: eth0
MII Status: up
MII Polling Interval (ms): 100
Up Delay (ms): 200
Down Delay (ms): 200
Peer Notification Delay (ms): 0

Slave Interface: eth0
MII Status: up
Speed: 100 Mbps
Duplex: full
Link Failure Count: 0
Permanent HW addr: dc:a6:32:76:7b:12
Slave queue ID: 0

Slave Interface: wlan0
MII Status: up
Speed: Unknown
Duplex: Unknown
Link Failure Count: 0
Permanent HW addr: dc:a6:32:76:7b:13
Slave queue ID: 0

**Comment by votdev** [comment]
Hmmm, i don't know what is going on here, but the missing `access-points` configuration is written by the [wifi.j2](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/files/wifi.j2#L57) template.

**Comment by votdev** [comment]
Ahhh, found the problem.

**Comment by votdev** [comment]
The problem is bigger than expected and might cause greater changes, sadly not into the direction you want. The problem is that the UI allows adding WLAN interfaces for bridge and bond interfaces, but this is wrong. The UI has no fields that allow you to set the credentials, so the database does not know about them when the netplan.io configuration is generated. I checked the workflow in the Gnome NetworkManager UI and there you can not use WLAN interfaces for those interface types too. Because of this i will fix the openmediavault UI and backend to do not allow WLAN interfaces for bond and bridge interfaces.

**Comment by welderpb** [comment]
But you can easy add wlan interface as slave for bond using nmcli command line utility. I have working example on my laptop.
![image](https://user-images.githubusercontent.com/8425726/104034207-e27fb600-51d0-11eb-8b0c-9d45d36ef4ed.png)

**Comment by votdev** [comment]
The NetworkManager UI does not allow it. And if you think about how the UI is implemented this makes sense. I'm not encouraged to implement that, so it's open to the community to contribute this feature for OMV6 (when it's out) if this is a required feature.

**Comment by welderpb** [comment]
@votdev Thank you for help. I'v added custom netplan configuration and it is working now with wlan slave interface.

**Comment by welderpb** [comment]
> Because of that i will fix the openmediavault UI and backend to do not allow WLAN interfaces for bond and bridge interfaces.
@votdev 
So, still need to fix this.

**Comment by votdev** [comment]
> > Because of that i will fix the openmediavault UI and backend to do not allow WLAN interfaces for bond and bridge interfaces.
> 
> @votdev
> So, still need to fix this.

Yes, to prevent configuration errors the UI will not show WiFi interfaces for bond and bridge interfaces anymore. See https://github.com/openmediavault/openmediavault/issues/921.
