### ISSUE TITLE
OMV5 no display shared folder icon

### ISSUE THREAD

**Issue by skystare** [openmediavault/openmediavault#923]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: [uname -a]
- openmediavault version: [dpkg -l | grep openmediavault]

**Client (please complete the following information):**

**Additional context**

**Comment by votdev** [comment]
The issue will be closed because it does not contain any information about the problem. Based on the topic i can only suggest to clear the browser cache.
