### ISSUE TITLE
Can't select text in "Installing updates" text window

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#924]
**Describe the bug**

Can't select text in "Installing updates" text window

**To Reproduce**

1. Go to 'Update Management'
2. Click on 'Text'
3. try to mark multiple lines
4. Selected text gets unmarked, hence copy & paste impossible

**Expected behavior**

Can select text in "Installing updates" text window

**Screenshots**

see referenced  forum post below

**Reference to Forum**

[OMV forum thread](https://forum.openmediavault.org/index.php?thread/37416-can-t-select-text-in-installing-updates-text-window/&postID=261338#post261341)

**openmediavault Server (please complete the following information):**

- OS version: not relevant
- openmediavault version: 5.x

**Client (please complete the following information):**

not relevant

**Additional context**

Known limitation of ExtJs Framework

**Comment by votdev** [comment]
Fixed in `OMV6`.
