### ISSUE TITLE
Update UDEV database for JMicron device

### ISSUE THREAD

**Issue by harrison-h** [openmediavault/openmediavault#928]
References: https://github.com/openmediavault/openmediavault/pull/746

I have this external enclosure: https://www.yottamaster.com/index.php?route=product/product&path=79&product_id=113

This enclosure uses the exact same controller as the existing ORICO rule, but reports variables slightly differently. 

The output of `udevadm info --query=all --name=/dev/sde` is as follows:

```
P: /devices/pci0000:00/0000:00:05.0/usb2/2-1/2-1:1.0/host8/target8:0:0/8:0:0:3/block/sde
N: sde
L: 0
S: disk/by-path/pci-0000:00:05.0-usb-0:1:1.0-scsi-0:0:0:3
S: disk/by-id/usb-JMicron_Generic_DISK04_ID_SERIAL_SHORT=7HKAAY5J-0:3
E: DEVPATH=/devices/pci0000:00/0000:00:05.0/usb2/2-1/2-1:1.0/host8/target8:0:0/8:0:0:3/block/sde
E: DEVNAME=/dev/sde
E: DEVTYPE=disk
E: MAJOR=8
E: MINOR=64
E: SUBSYSTEM=block
E: USEC_INITIALIZED=3329567
E: ID_VENDOR=JMicron
E: ID_VENDOR_ENC=JMicron\x20
E: ID_VENDOR_ID=152d
E: ID_MODEL=Generic_DISK04
E: ID_MODEL_ENC=Generic\x20DISK04\x20\x20
E: ID_MODEL_ID=0567
E: ID_REVISION=0103
E: ID_SERIAL=JMicron_Generic_DISK04_ID_SERIAL_SHORT=7HKAAY5J-0:3
E: ID_SERIAL_SHORT=ID_SERIAL_SHORT=7HKAAY5J
E: ID_TYPE=disk
E: ID_INSTANCE=0:3
E: ID_BUS=usb
E: ID_USB_INTERFACES=:080650:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usb-storage
E: ID_PATH=pci-0000:00:05.0-usb-0:1:1.0-scsi-0:0:0:3
E: ID_PATH_TAG=pci-0000_00_05_0-usb-0_1_1_0-scsi-0_0_0_3
E: ID_PART_TABLE_UUID=4b66467c-cfbe-45c5-8f95-d0464c075ade
E: ID_PART_TABLE_TYPE=gpt
E: DEVLINKS=/dev/disk/by-path/pci-0000:00:05.0-usb-0:1:1.0-scsi-0:0:0:3 /dev/disk/by-id/usb-JMicron_Generic_DISK04_ID_SERIAL_SHORT=7HKAAY5J-0:3
E: TAGS=:systemd:
```

I'm not familiar with UDEV so I haven't made an attempt to fix this on my system yet. However, I'm wondering if a more generic rule could be used to cover all products using this controller? My example one is below, which uses ID_MODEL_ID and ID_VENDOR_ID to identify the device instead of relying on the names passed, which seem to be able to be tweaked by vendor or changes by revision.

```
ACTION=="add", KERNEL=="sd*", SUBSYSTEM=="block", \
  ENV{ID_MODEL_ID}=="0567", ENV{ID_VENDOR_ID}=="152d", \
  PROGRAM="/lib/udev/serial_id %N", \
  ENV{ID_SERIAL}="$env{ID_VENDOR}_$env{ID_MODEL}_%c-$env{ID_INSTANCE}", \
  ENV{ID_SERIAL_SHORT}="%c", \
  SYMLINK="disk/by-path/$env{ID_PATH}", \
  SYMLINK+="disk/by-id/$env{ID_BUS}-$env{ID_SERIAL}"
```

**Comment by votdev** [comment]
I'll have a look into it. making a rule more generic is always a good idea to address the issue for more enclosures.

Having more data, like yours, help to get into this direction.

**Comment by votdev** [comment]
The UDEV rule has already been improved in `openmediavault 5.5.21`, see https://github.com/openmediavault/openmediavault/commit/603e5e68964675d81274da99973417358a388d15 and https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/etc/udev/rules.d/61-openmediavault-dev-disk-by-id.rules#L206.

**Comment by mi-hol** [comment]
@votdev please see the user feedback in https://forum.openmediavault.org/index.php?thread/37294-how-to-mount-hdd-with-omv-by-label-instead-of-uuid/&postID=261975#post261975

**Comment by votdev** [comment]
> @votdev please see the user feedback in [forum.openmediavault.org/index.php?thread/37294-how-to-mount-hdd-with-omv-by-label-instead-of-uuid/&postID=261975#post261975](https://forum.openmediavault.org/index.php?thread/37294-how-to-mount-hdd-with-omv-by-label-instead-of-uuid/&postID=261975#post261975)
> 
> Are there possibilities to reduce the impact?

No, OMV always wants to use predictable device files, and `by-uuid` is the most stable one related to file systems.

**Comment by votdev** [comment]
Closing again because OMV is deciding which device file is used.
