### ISSUE TITLE
Add custom mount options on Filesystems screen

### ISSUE THREAD

**Issue by jefbam** [openmediavault/openmediavault#929]
In order to modify filesystem mount options, user must manually edit the etc/openmediavault/config.xml and /usr/share/php/openmediavault/globals.inc files.

It would be a convenient to have an option to edit mount options on the File Systems screen. For example, the ntfs mount options in the xml are "defaults,nofail" but our testing has shown that adding the big_writes option for ntfs volumes speeds up writes by considerably--almost 3x faster in fact--with no undesirable results.

The Remote Mount screen allows custom mount options such as this and has been very helpful.

**Comment by mi-hol** [comment]
please provide the required details as explained in issue template.
Specifically for "he ntfs mount options in the xml are "defaults,nofail" but our testing has shown that adding the big_writes option for ntfs volumes speeds up writes by considerably--almost 3x faster in fact--with no undesirable results."

**Comment by mi-hol** [comment]
#262

**Comment by votdev** [comment]
Adding such an option to the WebUI is a NoGo for openmediavault because it is not the concept of the project to support every possible configure option. Instead it is minimized to the minimum of necessary information to get something running.

If the default mount options for NTFS are not the best, then this is what to be improved. Please provide a diff, a PR or describe detailed what we need to change. Adding links to howtos that discuss that changes would be great to show that this is a broadly accepted improvement.

**Comment by jefbam** [comment]
Understood. Thanks for your consideration. Currently, the default ntfs mount options are:

defaults,nofail      0 2

I'm proposing the new default to include big_writes:

defaults,big_writes,nofail      0 2

Some references, which direct the use of big_writes mount option as the solution:

-Discussion that supports that no downsides to using this option, that it decreases cpu usage, and dramatically speeds up disk write performance.

https://unix.stackexchange.com/questions/536971/disadvantages-of-ntfs-3g-big-writes-mount-option

-Discusses solving slow write speeds for ntfs and increasing (by about 3x):

https://superuser.com/questions/613869/ntfs-write-speed-really-slow-15mb-s-on-ubuntu

-Solution to solve problem of slow writes on ntfs on Raspberry Pi:

https://www.raspberrypi.org/forums/viewtopic.php?t=270821#p1642438

-Solution to improve network speed over lan using smb for ntfs partitions:

http://forum.xbian.org/thread-3851.html

-There is some evidence that LibreElec default mount options to include big_writes, but I have not verified this myself:

https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/sysutils/udevil/config/udevil.conf:

i.e.,

  default_options_ntfs      = nosuid, noexec, nodev, noatime, big_writes, fmask=0133, uid=$UID, gid=$GID, utf8
