### ISSUE TITLE
Use chrony instead of ntpd

### ISSUE THREAD

**Issue by votdev** [openmediavault/openmediavault#93]
https://chrony.tuxfamily.org/doc/3.0/chrony.conf.html

**Comment by ryecoaaron** [comment]
We just switched to chrony from ntp at work.  Very happy with decision.  I think this is a good idea if there is never going to be an option to make OMV an ntp source.

**Comment by trajano** [comment]
This dependency is causing an issue with my Pi configuration which uses systemd-timesyncd but not really sure if it is a bug yet.

**Comment by votdev** [comment]
> This dependency is causing an issue with my Pi configuration which uses systemd-timesyncd but not really sure if it is a bug yet.

OMV will now ensure this service is stopped, disabled and masked.

**Comment by trajano** [comment]
I noticed that too... but then that breaks DietPi tools which need timesyncd so it's just a choice of choosing one or the other.

**Comment by votdev** [comment]
> I noticed that too... but then that breaks DietPi tools which need timesyncd so it's just a choice of choosing one or the other.

I'm sorry, but this is not supported. OMV is the master of the system if you choose to use it. It can not take care about other things, otherwise OMV breaks.

**Comment by trajano** [comment]
> > I noticed that too... but then that breaks DietPi tools which need timesyncd so it's just a choice of choosing one or the other.
> 
> I'm sorry, but this is not supported. OMV is the master of the system if you choose to use it. It can not take care about other things, otherwise OMV breaks.

Correct that is what I expected it to be based on the observation of the behaviour and look of the system.
