### ISSUE TITLE
APM and Spindown settings are not persistent for some disks/enclosures

### ISSUE THREAD

**Issue by jefbam** [openmediavault/openmediavault#930]
When using a disk enclosure (e.g., with JMicron chipset, etc.) that uses a rolling/changing serial number, the APM, AAM, and Spindown options on the Disk:Physical disk properties screen do not remain persistent between reboots; these settings are set to Disabled after reboot.

Also, old "ghost" entries corresponding to the disk-by-id (old serial number) for those disks accumulate in the hdparm section of the config.xml file after reboots.

**Comment by mi-hol** [comment]
please provide the required details as explained in issue template

**Comment by jefbam** [comment]
Yes, this is a complex issue. I can refer you to #901 if that is helpful.

After each reboot an additional record such as:

      <hdparm>                                                                                                                  <uuid>30d16c94-9372-4ed9-99c0-be5231b06415</uuid>                                                                       <devicefile>/dev/disk/by-id/usb-Elite_Pro_Dual-R1_RANDOM__9B3BB6A08401-0:0</devicefile>
        <apm>0</apm>
        <aam>0</aam>                                                                                                            <spindowntime>120</spindowntime>
        <writecache>1</writecache>                                                                                            </hdparm>'the covenant'

is added to the /etc/openmediavault/config.xml file. The resulting behavior is that the Spindown, APM, and AAM settings that had been saved before reboot are not applied/"remembered" and those settings are all set to Disabled. This is due to the /dev/disk/by-id mountpoint changing after each reboot or remount of the filesystem for drive enclosures with certain chipsets, as described in the original post. If a disk-by-uuid can be used instead, this may fix the problem.

**Comment by votdev** [comment]
The problem is your enclosure and not openmediavault. The UDEV rules shipped with openmediavault only apply to JMicron based enclosures, but UDEV reports a different vendor ID for your enclosure, so the rules are not applied.

Please try the below UDEV rule (based on #901)  and report back if it fixes your problems.
```
# https://www.owcdigital.com/products/mercury-elite-pro-dual-mini
ENV{ID_VENDOR}=="Elite", \
  ENV{ID_MODEL}=="Pro_Dual-R1", \
  IMPORT{program}="serial_id %N", \
  ENV{ID_SERIAL}="$env{ID_VENDOR}_$env{ID_MODEL}_$env{ID_SERIAL_SHORT}-$env{ID_INSTANCE}", \
  SYMLINK="disk/by-path/$env{ID_PATH}", \
  SYMLINK+="disk/by-id/$env{ID_BUS}-$env{ID_SERIAL}"
```
Apply the rule to `/etc/udev/rules.d/61-openmediavault-dev-disk-by-id.rules`, run `omv-salt deploy run initramfs` and reboot the system. After that unmount all filesystems and reconfigure from scratch.

If this does not help, then consider to by a different enclosure and complain to the manufacturer of the enclosure.

**Comment by votdev** [comment]
>  If a disk-by-uuid can be used instead, this may fix the problem.

This device files are only used by filesystems and not hardware devices because only filesystems provide a UUID that is used to create the device file.

**Comment by jefbam** [comment]
Yes, I agree. The problem certainly lies with the enclosure. Of course I'm asking OMV to fix a JMicron problem :-)

Thanks for the udev rule. I'll test with it and report back.

**Comment by jefbam** [comment]
Thanks for this--this seems to be working.

-The serial number is now referenced with a permanent string, rather than a changing one (e.g., RANDOM 9FC090397067)
-The hdparm section in the config.xml is no longer collecting orphaned records
-The APM and Spindown settings are now retained across reboots.

Thanks again, appreciate your support.
