### ISSUE TITLE
Add systemd target that waits for all omv mounted filesystems to be mounted

### ISSUE THREAD

**Issue by ryecoaaron** [openmediavault/openmediavault#932]
Right now local-fs.target doesn't seem to work for waiting for all mount points to be mounted. So, services like minidlna or docker or nfs will start before the filesystem with its database is mounted. If we created a target (/lib/systemd/system/omv-fs.target for example) that looked something like:

[Unit]
Description=Wait for OMV filesystems target
Requires=multi-user.target
Wants=local-fs.target
After=local-fs.target $(systemctl list-units --type=mount | grep /srv | awk '{ print $1 }' | tr '\n' ' ')

Then other services could have overrides added to wait/require this target to make sure they didn't start before the filesystems were mounted.

This should not cause an issue like the sharedfolders fiasco because nothing has to use this target and if a filesystem listed in after doesn't exist, it seems systemd ignores it.

systemctl list-units --type=mount

UNIT                                                                                                        LOAD   ACTIVE SUB     DESCRIPTION                  
-.mount                                                                                                     loaded active mounted Root Mount                   
dev-hugepages.mount                                                                                         loaded active mounted Huge Pages File System       
dev-mqueue.mount                                                                                            loaded active mounted POSIX Message Queue File Syst
export-plugins.mount                                                                                        loaded active mounted /export/plugins              
export-testufs.mount                                                                                        loaded active mounted /export/testufs              
proc-fs-nfsd.mount                                                                                          loaded active mounted NFSD configuration filesystem
run-docker-netns-7d7f179d29d1.mount                                                                         loaded active mounted /run/docker/netns/7d7f179d29d
run-docker-netns-fd1605b3e751.mount                                                                         loaded active mounted /run/docker/netns/fd1605b3e75
run-rpc_pipefs.mount                                                                                        loaded active mounted RPC Pipe File System         
run-user-1000.mount                                                                                         loaded active mounted /run/user/1000               
sftp-aaron-downloads.mount                                                                                  loaded active mounted /sftp/aaron/downloads        
sftp-aaron-plugins.mount                                                                                    loaded active mounted /sftp/aaron/plugins          
srv-6fc0089d\x2d6aa8\x2d4d1b\x2d8ad5\x2d1d1e915feeeb.mount                                                  loaded active mounted /srv/6fc0089d-6aa8-4d1b-8ad5-
srv-81706b29\x2de5b8\x2d4c7d\x2db28d\x2d1a5d891c1cd7.mount                                                  loaded active mounted /srv/81706b29-e5b8-4c7d-b28d-
srv-8d0d73a5\x2d246e\x2d4cf9\x2d91d0\x2dd4808eeeda41.mount                                                  loaded active mounted /srv/8d0d73a5-246e-4cf9-91d0-
srv-9c6c28ae\x2d27e0\x2d463d\x2d847e\x2dc9be211270fd.mount                                                  loaded active mounted /srv/9c6c28ae-27e0-463d-847e-
srv-9f7b6591\x2d7af0\x2d43ef\x2db8bb\x2dccaa46145ff7.mount                                                  loaded active mounted /srv/9f7b6591-7af0-43ef-b8bb-
srv-bcea7ccd\x2de113\x2d41b7\x2db922\x2dbb6bccb412a8.mount                                                  loaded active mounted /srv/bcea7ccd-e113-41b7-b922-
srv-dev\x2ddisk\x2dby\x2dlabel\x2dbackup.mount                                                              loaded active mounted /srv/dev-disk-by-label-backup
srv-dev\x2ddisk\x2dby\x2dlabel\x2dd1.mount                                                                  loaded active mounted /srv/dev-disk-by-label-d1    
srv-dev\x2ddisk\x2dby\x2dlabel\x2dd2.mount                                                                  loaded active mounted /srv/dev-disk-by-label-d2    
srv-dev\x2ddisk\x2dby\x2dlabel\x2dd3.mount                                                                  loaded active mounted /srv/dev-disk-by-label-d3    
srv-dev\x2ddisk\x2dby\x2dlabel\x2dplugins.mount                                                             loaded active mounted /srv/dev-disk-by-label-plugin
sys-fs-fuse-connections.mount                                                                               loaded active mounted FUSE Control File System     
sys-kernel-debug.mount                                                                                      loaded active mounted Kernel Debug File System     
tmp.mount                                                                                                   loaded active mounted Mount /tmp as tmpfs to reduce
var-cache-samba.mount                                                                                       loaded active mounted /var/cache/samba             
var-folder2ram-var-cache-samba.mount                                                                        loaded active mounted /var/folder2ram/var/cache/sam
var-folder2ram-var-lib-monit.mount                                                                          loaded active mounted /var/folder2ram/var/lib/monit
var-folder2ram-var-lib-openmediavault-rrd.mount                                                             loaded active mounted /var/folder2ram/var/lib/openm
var-folder2ram-var-lib-rrdcached.mount                                                                      loaded active mounted /var/folder2ram/var/lib/rrdca
var-folder2ram-var-log.mount                                                                                loaded active mounted /var/folder2ram/var/log      
var-folder2ram-var-spool.mount                                                                              loaded active mounted /var/folder2ram/var/spool    
var-folder2ram-var-tmp.mount                                                                                loaded active mounted /var/folder2ram/var/tmp      
var-lib-docker-containers-2dab8a5ad26c117c0445afa237952c56b718a1182d4b3f1e2e38137982cfd05f-mounts-shm.mount loaded active mounted /var/lib/docker/containers/2d
var-lib-docker-containers-3a15782d72bcac140ff931a14f7f3d5273230eb2d6df8f59f3b1cbd4d2d8aee5-mounts-shm.mount loaded active mounted /var/lib/docker/containers/3a
var-lib-docker-overlay2-df87cd4d3f3c2f0e91678599b96189e21018349fb1a8908d7f9cfa54af0916d4-merged.mount       loaded active mounted /var/lib/docker/overlay2/df87
var-lib-docker-overlay2-e38a9c5679348eee89dacabc83e4fa6b0c73055e770ff88964b72fc69ac65f30-merged.mount       loaded active mounted /var/lib/docker/overlay2/e38a
var-lib-monit.mount                                                                                         loaded active mounted /var/lib/monit               
var-lib-openmediavault-rrd.mount                                                                            loaded active mounted /var/lib/openmediavault/rrd  
var-lib-rrdcached.mount                                                                                     loaded active mounted /var/lib/rrdcached           
var-log.mount                                                                                               loaded active mounted /var/log                     
var-spool.mount                                                                                             loaded active mounted /var/spool                   
var-tmp.mount                                                                                               loaded active mounted /var/tmp

**Comment by ryecoaaron** [comment]
omv-extras is current adding an override to docker that seems to work well using the following:

**Comment by jpo234** [comment]
> omv-extras is current adding an override to docker that seems to work well using the following:
> [Unit]
> After=local-fs.target $(systemctl list-units --type=mount | grep /srv | awk '{ print $1 }' | tr '\n' ' ')

You can drop the grep. This should be equivqlent:
systemctl list-units --type=mount | awk '/\/srv/{ print $1 }' | tr '\n' ' '

**Comment by ryecoaaron** [comment]
I'm wondering if the OMV implemention should use filesystem mountpoint paths instead of grep/awk'ing the list of mount files in case the mount file for a new filesystem hasn't been created yet.

**Comment by jpo234** [comment]
I quite frankly don't understand why local-fs.target doesn't work:

```
pi@omv-nas:~ $ systemctl list-dependencies local-fs.target
local-fs.target
● ├─-.mount
● ├─boot.mount
● ├─srv-dev\x2ddisk\x2dby\x2dlabel\x2domvbackup.mount
● ├─srv-dev\x2ddisk\x2dby\x2dlabel\x2domvmaster.mount
● ├─systemd-fsck-root.service
● └─systemd-remount-fs.service

```

**Comment by ryecoaaron** [comment]
Not sure but many have tested that.  Pretty sure local-fs doesn't work with fuse filesystems (mergerfs is a big one there).  And we would still need something for remote filesystems since remote-fs doesn't detect fuse filesystems either.

**Comment by mi-hol** [comment]
Is #720 related?

**Comment by mi-hol** [comment]
@votdev would you please comment re: https://github.com/openmediavault/openmediavault/issues/932#issuecomment-758192556 ?

**Comment by deepdivered** [comment]
> > omv-extras is current adding an override to docker that seems to work well using the following:
> > [Unit]
> > After=local-fs.target $(systemctl list-units --type=mount | grep /srv | awk '{ print $1 }' | tr '\n' ' ')
> 
> You can drop the grep. This should be equivqlent: `systemctl list-units --type=mount | awk '/\/srv/{ print $1 }' | tr '\n' ' '`
> 
> ```
> pi@omv-nas:~ $ echo $(systemctl list-units --type=mount | grep /srv | awk '{ print $1 }' | tr '\n' ' ')
> srv-dev\x2ddisk\x2dby\x2dlabel\x2domvbackup.mount srv-dev\x2ddisk\x2dby\x2dlabel\x2domvmaster.mount
> pi@omv-nas:~ $ echo $(systemctl list-units --type=mount | awk '/\/srv/{ print $1 }' | tr '\n' ' ')
> srv-dev\x2ddisk\x2dby\x2dlabel\x2domvbackup.mount srv-dev\x2ddisk\x2dby\x2dlabel\x2domvmaster.mount
> ```

this resolved my issue of docker starting before my raid drives were mounted.

**Comment by ngrigoriev** [comment]
It seems like the same issue I am having. I am exposing a directory from ZFS volume. NFS service adds this to /etc/fstab:

```
# >>> [openmediavault]
/my-zfs-mount/myexportdir/		/export/myexportdir	none	bind,nofail,_netdev	0 0
# <<< [openmediavault]
```

As result, this fails because this volume is not mounted at the time this fstab entry is processed.
