### ISSUE TITLE
github label changes

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#936]
**Is your feature request related to a problem? Please describe.**
GH labels should be meaningful to all users of GH

**Describe the solution you'd like**
1) label 'innocent' seems to mean 'external issue' not under control of OMV development. Proposal change it to meaning
2) If "DNM" stands for "DoNotMerge"? Guess this is obsolete due to GH's "draft" PR feature
3) some (internal) issues are not directly actionable (i.e. #886 & #887). Proposal is a new label "meta".
4) A breaking change is not easy to identify. Proposal is a new label "breaking change"

**Comment by votdev** [comment]
>     1. label 'innocent' seems to mean 'external issue' not under control of OMV development. Proposal change it to meaning
> 

Done

>     2. If "DNM" stands for "DoNotMerge"? Guess this is obsolete due to GH's "draft" PR feature
> 

Label text changed. IMO this label is still useful for PR's that out of the draft state, but it comes out that they should not merged right now. That's how we handle it in the Ceph project.

>     3. some (internal) issues are not directly actionable (i.e. #886 & #887). Proposal is a new label "meta".
> 

Done. Do you have a short description for `meta`?

>     4. A breaking change is not easy to identify. Proposal is a new label "breaking change"

Done. Any idea for a short description?

**Comment by mi-hol** [comment]
> Done. Do you have a short description for `meta`?

Maybe "issue that requires several smaller changes to be resolved"?

@ryecoaaron @flmaxey please comment as native speakers you'd have perhaps a much better suggestion

**Comment by ryecoaaron** [comment]
I don't have better suggestions.  They are just tags and I don't worry much about them.

**Comment by mi-hol** [comment]
Addition: remove old, now irrelevant labels "2.x", 3.x"

**Comment by votdev** [comment]
> Addition: remove old, now irrelevant labels "2.x", 3.x"

Done

**Comment by votdev** [comment]
> > Done. Do you have a short description for `meta`?
> 
> Maybe "issue that requires several smaller changes to be resolved"?
> 
> @ryecoaaron @flmaxey please comment as native speakers you'd have perhaps a much better suggestion

OK, now i understand the meaning. I suggest `epic`, that's what Jira/Confluence is using in that case.

**Comment by mi-hol** [comment]
"epic" is great

**Comment by mi-hol** [comment]
re 'label "breaking change"  Any idea for a short description?'
requires local OMV admin to perform a manual change of OMV configuration

**Comment by votdev** [comment]
All done
