### ISSUE TITLE
Prevent download of buggy and obsolete versions from SourceForge => less forum posts

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#937]
**Is your feature request related to a problem? Please describe.**
Many forum posts are related to issues that have already been solved by latest OMV version
According to SourceForge statistics obsolete beta versions and long unsupported and buggy version are still getting downloaded. This is likely happening due to links in now obsolete tutorials spread all over the internet

**Describe the solution you'd like**
1) Only allow latest versions of all major versions to be available for download 
2) Move build and release download to github, to allow for "one stop shopping"

![image](https://user-images.githubusercontent.com/22799428/104441316-cb0b4900-5593-11eb-8fc9-a5a625cfa32b.png)

**Comment by votdev** [comment]
I would like to keep the old versions for archive issues. I also think deleting old versions is not the way how a project should handle that. Never saw such a behaviour out in the wild.

**Comment by tooomm** [comment]
I don't like simply deleting them either. That also messes a lot with download stats and history I guess.

Can you move files there?
What about a dedicated `Archive` folder and hiding everything but the most recent stable versions in there?

**Comment by votdev** [comment]
Using an `archive` folder was also my idea, but in that case we will loose the download stats, too.

**Comment by mi-hol** [comment]
Well what relevance has the number of downloads of for example a 3 year old beta version?
Telemetry of active instances would be relevant and valuable for decision making :)

**Comment by mi-hol** [comment]
Great, archive folder has been created on SourceForge and old versions got moved there :)

An open question is though, why is a new release not resulting in a new (directly downloadable) version from either github (preferred) or SourceForge (current download location) ?

**Comment by votdev** [comment]
> An open question is though, why is a new release not resulting in a new (directly downloadable) version from either github (preferred) or SourceForge (current download location) ?

It's not necessary to release an ISO for every new released package version. New ISO are only released if there are bugs caused by the openmediavault package version that is initially used to create the ISO.

**Comment by tooomm** [comment]
Looks way cleaner now. 👍
The no longer supported `4.1.22` should probably also go to the "archive" folder?

**Comment by mi-hol** [comment]
yes 4.1.22 and the 3 folders below too
![image](https://user-images.githubusercontent.com/22799428/106452892-ca761c00-6488-11eb-9070-f821dd40ee73.png)

**Comment by votdev** [comment]
> yes 4.1.22 and the 3 folders below too
> ![image](https://user-images.githubusercontent.com/22799428/106452892-ca761c00-6488-11eb-9070-f821dd40ee73.png)

`packages` is the Debian package repository, this can't be moved.

**Comment by mi-hol** [comment]
looks perfect now, closing
![image](https://user-images.githubusercontent.com/22799428/106585297-741be280-6547-11eb-9718-3e29090fbb5f.png)

**Comment by mi-hol** [comment]
test
