### ISSUE TITLE
Dashboard Enhancement

### ISSUE THREAD

**Issue by sankethguru** [openmediavault/openmediavault#939]
**Is your feature request related to a problem? Please describe.**
It would help if the dashboard is moved to the system tab than the diagnostics tab as
1. It is used repeatedly and scrolling to find it at the end of the list is tedious
2. It is a system dashboard. Not much of a diagnostic dashboard.

**Describe the solution you'd like**
1. Move it to the system tab so that it shows up on top and is easier to access.
2. Live data rates on the NIC would greatly help in knowing the traffic (something like windows task manager) and which user is causing that traffic load on the server.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by votdev** [comment]
>     1. Move it to the system tab so that it shows up on top and is easier to access.

![Bildschirmfoto vom 2021-01-14 09-40-26](https://user-images.githubusercontent.com/1897962/104566545-079b7b00-564e-11eb-853b-c5fe8f48a580.png)

Already done

>     2. Live data rates on the NIC would greatly help in knowing the traffic (something like windows task manager) and which user is causing that traffic load on the server.

The network interface RRD graphs are already available in the `Diagnostics` section (OMV5 and OMV6).

![Bildschirmfoto vom 2021-01-14 09-44-11](https://user-images.githubusercontent.com/1897962/104566766-4d584380-564e-11eb-8d31-2eb32ba883a7.png)

OMV will not provide dashboard widgets for everything by default, but it already has the ability to create custom dashboard widgets.

```
version: "1.0"
type: dashboard-widget
data:
  id: <UUID>
  type: rrd
  title: _("Network interface [ens6]")
  rrd:
    name: interface-ens6-hour.png
```

![Bildschirmfoto vom 2021-01-14 09-49-23](https://user-images.githubusercontent.com/1897962/104566895-7a0c5b00-564e-11eb-9bee-d09ce954236a.png)

![Bildschirmfoto vom 2021-01-14 09-49-45](https://user-images.githubusercontent.com/1897962/104566921-809ad280-564e-11eb-84fa-324e970c3c58.png)

**Comment by votdev** [comment]
> Live data rates on the NIC would greatly help in knowing the traffic (something like windows task manager) and which user is causing that traffic load on the server.

Live data is not available, there is no backend available that can deliver that. If this is required by the community, then it must provide such a feature via contribution to the project via PR.

**Comment by sankethguru** [comment]
Noted!

Thank you for your time. Will consider your suggestions.

**Comment by rjrudman** [comment]
Just to continue on from @votdev 's comment- I found very little documentation on *where* to put that wiget configuration file.  

By default, they live under `/usr/share/openmediavault/workbench/dashboard.d`. Then once you've got your yaml file saved there, run `omv-mkworkbench dashboard`
