### ISSUE TITLE
intall mysql 4.1.1 on OVM4,  error "Bad Gateway"

### ISSUE THREAD

**Issue by h2ofranck** [openmediavault/openmediavault#94]
hello,
unable to properly install the mysql module. Several tests, same problem. The message is "Bad Gateway" 
https://photos.app.goo.gl/HEwt4pnunXqouFcJA

**Comment by subzero79** [comment]
This is part of omv-extras, not core openmediavault plugin

**Comment by votdev** [comment]
Please report this issue [here](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-mysql/issues).
