### ISSUE TITLE
Spelling mistake in french error message

### ISSUE THREAD

**Issue by ugref** [openmediavault/openmediavault#940]
![image](https://user-images.githubusercontent.com/73405857/104838581-16876500-58bc-11eb-9c2b-e8466c55a7af.png)

When applying I get some errors but it's not important here. 

The correct spelling of this message is "Une erreur **s**'est produite", because this is the error that occurred (french grammar)

EDIT : 

![image](https://user-images.githubusercontent.com/73405857/104838641-944b7080-58bc-11eb-9b61-7e5e41f8dc49.png)

**Comment by votdev** [comment]
Fixes in `openmediavault 5.5.23`.
