### ISSUE TITLE
PVE LXC "Device '/dev/dm-0' does not exist." problem

### ISSUE THREAD

**Issue by bestlong** [openmediavault/openmediavault#944]
**Describe the bug**

Install step like [OpenMediaVault installation in LXC with attached HW block device](https://forum.proxmox.com/threads/openmediavault-installation-in-lxc-with-attached-hw-block-device.29918/)

use Proxmox VE 6.3-2, and CT Template debian-10-standard_10.5-1_amd64.tar.gz

**To Reproduce**

1. Go to 'Storage > File Systems'
2. Click on '+Create'
3. See error

**Screenshots**

![2021-01-19 16_33_40-openmediavault control panel - omv cendai com tw](https://user-images.githubusercontent.com/4023909/105276724-008be400-5bdd-11eb-9ff6-f2c637f40c3c.png)

![2021-01-21 11_07_42-pve-t - Proxmox Virtual Environment](https://user-images.githubusercontent.com/4023909/105278107-c96b0200-5bdf-11eb-8902-04b7f5552c96.png)

![2021-01-21 11_15_11-pve-t - Proxmox Virtual Environment](https://user-images.githubusercontent.com/4023909/105278140-d982e180-5bdf-11eb-827f-7681d1162676.png)

![2021-01-21 11_19_24-pve-t - Proxmox Console](https://user-images.githubusercontent.com/4023909/105278301-1d75e680-5be0-11eb-8e24-ee68f535645c.png)

**openmediavault Server (please complete the following information):**

- OS version: Linux omv 5.4.73-1-pve #1 SMP PVE 5.4.73-1 (Mon, 16 Nov 2020 10:52:16 +0100) x86_64 GNU/Linux
- openmediavault version: [dpkg -l | grep openmediavault]
```root@omv:~# dpkg -l | grep openmediavault
ii  openmediavault                  5.5.23-1                            all          openmediavault - The open network attached storage solution
ii  openmediavault-keyring          1.0                                 all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg     5.4.4                               all          OMV-Extras.org Package Repositories for OpenMediaVault
```

**Additional context**

Error detail:
```
Error #0:
OMV\Exception: Device '/dev/dm-0' does not exist. in /usr/share/php/openmediavault/system/blockdevice.inc:94
Stack trace:
#0 /usr/share/php/openmediavault/system/blockdevice.inc(244): OMV\System\BlockDevice->getCanonicalDeviceFile()
#1 /usr/share/php/openmediavault/system/storage/storagedevicedm.inc(39): OMV\System\BlockDevice->getDeviceName(true)
#2 /usr/share/php/openmediavault/system/storage/backend/dm.inc(62): OMV\System\Storage\StorageDeviceDM->getDeviceMapperSubsystem()
#3 /usr/share/php/openmediavault/system/storage/backend/dm.inc(45): OMV\System\Storage\Backend\DM->getImpl('/dev/dm-0')
#4 /usr/share/php/openmediavault/system/storage/storagedevice.inc(283): OMV\System\Storage\Backend\DM->enumerateSlaves()
#5 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(489): OMV\System\Storage\StorageDevice::enumerateUnused()
#6 [internal function]: Engined\Rpc\OMVRpcServiceFileSystemMgmt->getCandidates(Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#8 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('getCandidates', Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusfb...', '/tmp/bgoutputjf...')
#10 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#11 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(537): OMV\Rpc\ServiceAbstract->callMethodBg('getCandidates', Array, Array)
#12 [internal function]: Engined\Rpc\OMVRpcServiceFileSystemMgmt->getCandidatesBg(Array, Array)
#13 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#14 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getCandidatesBg', Array, Array)
#15 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('FileSystemMgmt', 'getCandidatesBg', Array, Array, 1)
#16 {main}
```

**Comment by jkaberg** [comment]
Hi @votdev, made an post over at [the forums](https://forum.openmediavault.org/index.php?thread/40266-device-dev-dm-2-not-found/&postID=282839#post282839) on an similar issue. This that a new issue or the same as this?
