### ISSUE TITLE
PAM unable to dlopen(pam_tally2.so)

### ISSUE THREAD

**Issue by drajar** [openmediavault/openmediavault#945]
Hi

I cannot login in webgui because:
omv-engined[3923553]: PAM unable to dlopen(pam_tally2.so): /lib/x86_64-linux-gnu/security/pam_tally2.so: cannot open shared object file: No such file or directory
omv-engined[3923553]: PAM adding faulty module: pam_tally2.so

This is because of libpam-modules (1.4.0-2) debian package that "Drop pam_tally and pam_tally2 modules, which have been deprecated  upstream in favor of pam_faillock.  Closes: #569746, LP: #772121.".

https://metadata.ftp-master.debian.org/changelogs//main/p/pam/pam_1.4.0-2_changelog

For workaround I hold the libpam-modules libpam-modules-bin packages to stop updating them, but I suggest replacing pam_tally2 with pam_faillock.

**openmediavault Server**

- OS version: Linux omv 5.9.0-5-amd64 #1 SMP Debian 5.9.15-1 (2020-12-17) x86_64 GNU/Linux
- openmediavault version: 5.5.23-1

Best regards, 
Dragos

**Comment by ryecoaaron** [comment]
While potentially good to know for OMV 6.x, OMV 5.x does not support Bullseye (Debian 11) which is the only place pam 1.4 comes from.

**Comment by votdev** [comment]
Seems we need to switch to `pam_faillock` if OMV6 is based on Debian 11.

**Comment by votdev** [comment]
Fixed by https://github.com/openmediavault/openmediavault/commit/7da153d52ac286296b71e2a507aec2e1abe912b5
