### ISSUE TITLE
SSH public key not taken into account

### ISSUE THREAD

**Issue by mickmail** [openmediavault/openmediavault#946]
Hello,

I went into an issue trying to set up server backup using Rsync through SSH with private/public key security between two OMV servers.
Release: 5.5.11-1
Codename: Usul

I created a dedicated user (csrsync) and added it to the ssh group.
After I generated a certificate on my client OMV server I copied the public key on my second server as authorized key for my csrsync user.
When trying to run, I landed on a public/private authentication error `"csrsync@192.168.10.213: Permission denied (publickey,password)"`.

The issue is not related to rsync but to ssh public key management. I finally managed to get it work by creating a /home/csrsync/.ssh/authorized_keys file to store my public key.

Looks like the following line inside /etc/ssh/sshd_config does not work as expected :
`"AuthorizedKeysFile .ssh/authorized_keys .ssh/authorized_keys2 /var/lib/openmediavault/ssh/authorized_keys/%u"
`
Public keys in the classic `/home/<user>/authorized_keys` file work but keys stored in `/var/lib/openmediavault/ssh/authorized_keys/<user>` do not.

Hope this helps !
Best regards,
Laurent

**Comment by votdev** [comment]
Have you used the OMV rsync UI to create the job? I'm wondering because OMV takes care to tell rsync where the SSH keys are located, see https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/rsync/files/cron-rsync-script.j2#L53.

**Comment by mickmail** [comment]
Hello,

Yes I used the UI but even if I landed on the issue when trying to setup Rsync, **it is not related to Rsync itself but rather to the way the ssh daemon is setup**. In fact I could reproduce the public key authentication issue by simply trying to connect using ssh.
When I create a home directory and put my public key in `/home/<user>/.ssh/authorized_keys` it works fine and I can connect without password
If instead I stick on the openmediavault UI setup (public key in `/var/lib/openmediavault/ssh/authorized_keys/<user>`), I fallback to password authentication or get a "no way" in case password is disabled.

It is told to the ssh daemon in the `/etc/ssh/sshd_config` file where to look for authorized public keys.
Inside the list, after the classical `home/<user>/.ssh/authorized_keys` is an openmediavault custom path that is `/var/lib/openmediavault/ssh/authorized_keys/%u`
I think this one is not working correctly but did not check further on the content of %u for instance.

Best regards,
Laurent

**Comment by mickmail** [comment]
Regarding the fact that OMV tells ssh to take the correct key I saw this also inside the cron task that is created as rsync job.
I then just extracted the ssh part of the command keeping the -i <path/to/private/key> but doing this still failed.

In fact the client side is just working fine... no issue with the private key passing.

The issue lays on the server side where the ssh daemon is unable to recognize `/var/lib/openmediavault/ssh/authorized_keys/<user>` as an authorized public key for my 'csrsync' user

Best regards,
Laurent

**Comment by votdev** [comment]
> The issue lays on the server side where the ssh daemon is unable to recognize `/var/lib/openmediavault/ssh/authorized_keys/<user>` as an authorized public key for my 'csrsync' user

Strange, this works at the time the feature has been implemented. Maybe something has been changed in Debian that breaks this. Need to do further investigations.

**Comment by votdev** [comment]
Have you installed the public key via the UI?

![Bildschirmfoto vom 2021-01-22 21-13-36](https://user-images.githubusercontent.com/1897962/105540607-c6166a00-5cf6-11eb-887f-f1a1b5fa8f8e.png)

OMV does not create home directories for users, thus the public keys are stored at a different location.

**Comment by votdev** [comment]
I can not reproduce the issue the following way:

* Create a SSH cert
* Copy public key to remote system. This only works for user `root` on an OMV system because only that user has a home directory.

![Bildschirmfoto vom 2021-01-22 21-21-08](https://user-images.githubusercontent.com/1897962/105541315-de3ab900-5cf7-11eb-9b6d-522a036c4cbd.png)

* Configure rsync job

![Bildschirmfoto vom 2021-01-22 21-19-48](https://user-images.githubusercontent.com/1897962/105541309-d9760500-5cf7-11eb-8ef6-d05c4c28f5bd.png)

* Execute it
```
Please wait, syncing </srv/dev-disk-by-uuid-789d5458-4e9a-494a-a7bb-23d16b3ac373/data/> to <root@192.168.178.40:/root/rsync> ...

sending incremental file list
./
aaaa.txt
bbb.txt

sent 180 bytes  received 57 bytes  158.00 bytes/sec
total size is 0  speedup is 0.00
The synchronisation has completed successfully.
Done ...
```

**Comment by votdev** [comment]
Please check if you could find something like that in your logs:
```
root@vb5box:~# tail -f /var/log/auth.log
...
Jan 22 21:49:30 omv5box sshd[18286]: Authentication refused: bad ownership or modes for directory /
Jan 22 21:49:30 omv5box sshd[18286]: Failed password for vot from 192.168.178.24 port 48442 ssh2
Jan 22 21:49:30 omv5box sshd[18286]: Failed password for vot from 192.168.178.24 port 48442 ssh2
Jan 22 21:49:30 omv5box sshd[18286]: Connection closed by authenticating user vot 192.168.178.24 port 48442 [preauth]
```
Fixing the privileges with `chmod 755 /` should fix your issue.

**Comment by mickmail** [comment]
Hello,

Thank you for the answer !
Yes I have that in my logs :

```
Jan 21 16:50:41 csbackup sshd[13747]: Authentication refused: bad ownership or modes for directory /
Jan 21 16:50:41 csbackup sshd[13747]: Connection closed by authenticating user csrsync 192.168.10.147 port 55265 [preauth]
```

So you must be right regarding the directory bad ownership issue.
However, in order to have people use public key authentication I think the steps I describe just below should work directly without any additional chmod (quite hard to guess without being OMV expert...). Just to keep OMV user friendly. 

Here are the steps (with my csrsync user but any other non root user can of course be used) :
1- [Rsync server] csrsync user creation and add it to ssh group
2- [Rsync client] Create a certificate (creation of files `/etc/ssh/openmediavault-127177f2-f788-4ed7-905a-8043fc291523` and `/etc/ssh/openmediavault-127177f2-f788-4ed7-905a-8043fc291523.pub`). Name it `Rsync_cert`
3- [Rsync client] Use `ssh-keygen -e -f /etc/ssh/openmediavault-127177f2-f788-4ed7-905a-8043fc291523.pub` to get a RFC 4716 formatted public key
4- [Rsync server] Paste the RFC 4716 formatted public key inside the public key section of the csrsync user. This puts the key inside `/var/lib/openmediavault/ssh/authorized_keys/csrsync`

Note : From this on, I would expect to be able to connect using public/private keys from the [Rsync client] to the [Rsync server] machine using the following line (but it is not the case) :
`ssh -i <path/to/private/key> csrsync@xxx.xxx.xxx.xxx`

5- [Rsync server] Enable Rsync server
6- [Rsync client] Create a job and tell it to use Rsync_cert. Set the remote server access (`csrsync@xxx.xxx.xxx.xxx:873:/srv/Volumexxxxxxxx/Shared/folder`)

As far as I understand all this works if I use root user because it is the only one having a home directory and if I copy the public key inside /root/.ssh/authorized keys.
This might not be a bug but it is a bit counter-intuitive. Why cannot we use **any user inside the ssh group** ?

May be OMV could simply take care of changing the directory privileges to 755 ?
 
What do you think ?

Best regards,
Laurent

**Comment by ryecoaaron** [comment]
> May be OMV could simply take care of changing the directory privileges to 755 ?

It should be doing that already.  The install script does this as well.
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/setup/fixmode/default.sls#L24

**Comment by mickmail** [comment]
Hello,

Ok then I don't know what happens or if I landed on an issue I'm alone to face.
At least I found a workaround by creating a home directory for my user and copy the authorized public key manually.

Thank you for your support !
Best regards,
Laurent

**Comment by votdev** [comment]
OMV already fixes the permissions after the first installation.

https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/setup/fixmode/default.sls

**Comment by votdev** [comment]
While testing the issue I realised that the workflow of the SSH public key handling is not optimal. 
The only thing I do not understand is why you manually copy the key, you can already manage this by using the UI only. But adding public keys for users via UI requires a key in RFC 4716 which needs to be manual converted from OpenSSH format. I will improve that soonish.

**Comment by votdev** [comment]
Public SSH key import via UI will be improved by https://github.com/openmediavault/openmediavault/pull/949 in `openmediavault 5.5.24`.

**Comment by votdev** [comment]
Closed because public SSH keys are taken into account as shown above. The user SSH key import via UI has been improved now, too.

**Comment by mickmail** [comment]
Hello,

I did use the UI for setting up the key for the user. However as you mention I had to convert the certificate's public key into RFC 4716 manually. Nice if that step has been automated.
Now I just put my server in production so I do not want to touch it but I'll try to test again if the public key is taken into account...

Best regards,
Laurent
