### ISSUE TITLE
REAL IP FORWARDING NGINX REVERSE PROXY <-> OpenMediaVault

### ISSUE THREAD

**Issue by dclausen1337** [openmediavault/openmediavault#950]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

with the following configuration i am not able to see real ip adresses from auth.log(/var/log/auth.log).
configuration for nginx reverse proxy: 
```
        location / {
                proxy_set_header  Host $host;
                proxy_set_header  X-Real-IP $remote_addr;
                proxy_set_header  X-Forwarded-Proto https;
                proxy_set_header  X-Forwarded-For $remote_addr;
                proxy_set_header  X-Forwarded-Host $remote_addr;
                proxy_set_header  Upgrade $http_upgrade;
                proxy_set_header  Connection 'upgrade';
                proxy_pass http://127.0.0.1:6666;
                client_max_body_size 100M;
                proxy_http_version 1.1;
                proxy_cache_bypass $http_upgrade;
                proxy_read_timeout  60;
                proxy_ssl_name $host;
                proxy_ssl_server_name on;
                proxy_ssl_session_reuse off;
                gzip off;
        }
```
in auth.log i can only see the localhost ip 

thank you in advance for help

**Comment by votdev** [comment]
Is this related to the [nginx](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-nginx) plugin?

If so, please raise the issue there. The issue template has already told you to do so.
Please also provide suggestions how to improve or fix the reported issue if possible.

**Comment by votdev** [comment]
Closing because necessary information like OMV and plugin version are missing even though the issue template requests them.
