### ISSUE TITLE
Disable the mpd feature of forked-daapd by default

### ISSUE THREAD

**Issue by douardda** [openmediavault/openmediavault#952]
The configuration file generated by omv for forked-daapd does not disable the mpd service, which then can prevent another mpd daemon from starting (if daapd has been started before).

Ideally, this should be a configuration option accessible in omv's config page for forked-daapd, but until them, simply disabling it would be better.

**Comment by votdev** [comment]
The [mpd section](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault-forkeddaapd/srv/salt/omv/deploy/forked-daapd/files/etc-forked-daapd_conf.j2#L240) is disabled by default. Are any other actions needed?

**Comment by douardda** [comment]
It's commented, but as you can read there, the default value for mpd.portt is 6600, so the mpd feature is actually enabled by default. mpd.port must be set to 0 to disable it.

**Comment by douardda** [comment]
BTW I'd be happy to make a PR for this, but I need  PR #951 to be merged before :-)

**Comment by votdev** [comment]
> BTW I'd be happy to make a PR for this, but I need PR #951 to be merged before :-)

Thx, i will do it myself in addition to other issues in this plugin.

**Comment by douardda** [comment]
@douardda thanks!

**Comment by votdev** [comment]
Fixed with https://github.com/openmediavault/openmediavault/commit/fad9f5b78ea89676c5820fc7413f8f79e4b39894 in `openmediavault-forkeddaapd 5.0.3`.

**Comment by votdev** [comment]
This issue caused an regression:
```
root@titan:~# /usr/sbin/forked-daapd -v
forked-daapd 26.4
root@titan:~# /usr/sbin/forked-daapd -f -d 5
no such option 'mpd'
```
Sadly i realised that after releasing the new package.

**Comment by votdev** [comment]
Too bad, #951 has not been backported to the 5.x branch.
