### ISSUE TITLE
"Communication failure" popup seen when attempting to create a SMART Scheduled Test

### ISSUE THREAD

**Issue by P3175** [openmediavault/openmediavault#961]
While trying to create a Scheduled test from the 'Storage' > 'S.M.A.R.T.' page on the 'Scheduled tests tab', and the 'Add' button was pressed, no devices were visible to select from the 'Device' dropdown list of the 'Add scheduled test' popup window. 
Instead a loading spinning wheel was observed. After waiting a few seconds, an 'Error' popup was observed with the text "communication failure".

Retested multiple times, making sure that two drives in system were S.M.A.R.T enabled before attempting. Issue was persistent. Rebooted system and re-attempted and observed same behaviour. Re-installed system from USB ISO image, configuring again with S.M.A.R.T monitoring enabled and two S.M.A.R.T enabled devices, and issue was repeated.

Running OMV5 on version 5.5.11-1 (Usul) with Kernel Linux 5.7.0-0.bpo.2-amd64 on a 4th gen Intel i5. Tested with brand new IronWolf NAS 2TB drives.

This prevents running any S.M.A.R.T monitoring scheduled tests on my system, which I believe is a critical function of a NAS.
See image below for error.

[
![OMV5 Usul SMART schedule test issue](https://user-images.githubusercontent.com/24324052/107128624-0eb55200-68b7-11eb-97ab-f3cd2abe437e.PNG)
](url)

**Comment by votdev** [comment]
Please update to the latest version which is 5.5.23 at the moment and try again.

**Comment by P3175** [comment]
Re-attempted with latest OS updates, running 5.5.23-1 and issue is still persistent.
![OMv5 SMART schedule test issue OS v5 5 23-1](https://user-images.githubusercontent.com/24324052/107129352-cd27a580-68bc-11eb-8f25-d755c7d3fc4e.PNG)

The error is seen after the dropdown is seen to "load".. as in the following picture:
![OMV5 add scheduled test loading v5 5 23-1](https://user-images.githubusercontent.com/24324052/107129358-de70b200-68bc-11eb-8914-72ff5f8bc721.png)

Devices connected are two 2TB IronWolf NAS HDD via SATA directly to the motherboard. The OS drive is a SATA SSD. 

Devices are accessible and responsive on the Storage > S.M.A.R.T page under Devices tab, although it takes a long time for that page to populate. All data is available for each drive when the I'nformation' button is pressed.

**Comment by P3175** [comment]
Attempted to inspect device information for OS drive from the S.M.A.R.T. page 'Devices' tab and same error was observed "communication failure". See pic:

![image](https://user-images.githubusercontent.com/24324052/107129638-a9655f00-68be-11eb-8450-36b149b76fee.png)

Curious why this is happening, since the OS drive is reported green and since OMV is still running, I dont suspect this is an OS drive issue?

**Comment by votdev** [comment]
Could you please have a look into `/var/log/syslog`, maybe you'll find some useful PHP error messages.

**Comment by votdev** [comment]
After checking the syslog, please have a look [here](https://github.com/openmediavault/openmediavault/issues/959#issuecomment-774556028) and give the latest version a try. I'm currently refactoring the SMART processing, so maybe your issue will be fixed, too.

**Comment by P3175** [comment]
Breifly looked at logs, but couldnt find a `smartctl` error when using ctrl+f.. attaching two log files for reference. The first is after powering on named 'syslog on reboot.txt' here:
[syslog on reboot.txt](https://github.com/openmediavault/openmediavault/files/5937873/syslog.on.reboot.txt)


And the second is after I re-created the dropdown error issue mentioned at the start of this ticket.
[syslog after dropdown select error.txt](https://github.com/openmediavault/openmediavault/files/5937886/syslog.after.dropdown.select.error.txt)

I will look into the other thread and report back.

**Comment by P3175** [comment]
Could you please give more instructions on the suggested fix? I ran the terminal download (as per the exact script given), and rebooted the machine, but I still see the same error. This is after checking for updates and rebooting the machine again.

Interestingly the OMV System Version still says 5.5.23-1.

**Comment by votdev** [comment]
> Could you please give more instructions on the suggested fix? I ran the terminal download (as per the exact script given), and rebooted the machine, but I still see the same error.
> 
> Interestingly, even after rebooting and checking for updates (after running the script, what appeared to be successfully) the OMV System Version still says 5.5.23-1.

Hmm, then the installation was not successful.

Is it possible to run `smartctl -x /dev/sdX`? Make sure the firmware of your drives is up-to-date. I remember that we had troubles with such issues in the past.

**Comment by P3175** [comment]
`Yes, smartctl -x /dev/sdX` passes for all drives, although there is an `ATA_READ_LOG_EXT failed: scsi error badly formed scsi parameters` message for the OS drive (sdc) - although I was not attempting to run smart tests on this drive.

Checking with Seagate, no firmware updates are available for the NAS drives. Are there any other approaches you suggest I try? I'd really like to avoid looking at alternative NAS software.

**Comment by votdev** [comment]
Could you please have a look into `/var/log/nginx/openmediavault-webgui_error.log` and check for errors.

Other than that i'm currently out of ideas. Without an error message it's impossible to know what is exactly going wrong.

**Comment by P3175** [comment]
I did some further testing including on a Raspberry Pi 2B running 5.5.17-3 and I was able to successfully create a scheduled check on that system. I then updated the OS to 5.5.23-1 and the scheduled test remained active. Using this result, I attempted on my NAS x86 Intel i5 PC with the Seagate RAID drives.

Reinstalled system using 5.3.9-1 (the closest image to 5.5.17-3 I could find in the downlods), checked BIOS is in factory defualt settings. Note even in this S/w version, I was getting the same communication errors when attempting to view the SMART page Devices tab, or trying to create a Scheduled test.

Following this, the only errors I found in logs were (note I have replaced my machines IP address): 

`2021/02/09 23:24:33 [error] 2457#2457: *18 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:192.168.0.4, server: openmediavault-webgui, request: "POST /rpc.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm-openmediavault-webgui.sock:", host: "[IP.Address.of.Host]", referrer: "http://[IP.Address.of.Host]/"`

And
`2021/02/10 18:33:48 [error] 794#794: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: ::ffff:192.168.0.4, server: openmediavault-webgui, request: "POST /rpc.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm-openmediavault-webgui.sock", host: "[IP.Address.of.Host]", referrer: "http://[IP.Address.of.Host]/"
`

As a side note, after I see the error and navigate to the System Information Performance tab, the CPU WaitIO is always at 100%.
Hope this helps.. looking forward to your reply!

**Comment by P3175** [comment]
For extra context, here is a Syslog dump from /var/log/ syslog at the exact time when I was requesting/creating a scheduled test.
[syslogDump-whileScheduleTestCreate.txt](https://github.com/openmediavault/openmediavault/files/5960857/syslogDump-whileScheduleTestCreate.txt)
 
But there was nothing in the `/var/log/nginx/openmediavault-webgui_error.log` at that time.

Note that the /var/log/nginx/error.log had the following records at a similar time when the communication error was observed:
```
2021/02/10 19:01:08 [emerg] 3699#3699: bind() to [::]:80 failed (98: Address already in use)
2021/02/10 19:02:38 [emerg] 3736#3736: bind() to [::]:80 failed (98: Address already in use)
```

**Comment by votdev** [comment]
I really have no idea what is going wrong here, IMO this is a smartctl thing that only appears with your disks (or manufacturer / disk combination).
The really last idea that comes to my mind is the following. Stop the OMV daemon and start it in debug mode, go to the SMART UI page and look what happens in the console output.

```
$ monit stop omv-engined
$ omv-engined -d -f
```

After testing (you can kill the running process with CTRL-C) you need to start the daemon again with `monit restart omv-engined`.

**Comment by P3175** [comment]
Thanks for the continued advice, here are the requested log-files
[omv-engined -d -f Console monitor output.txt](https://github.com/openmediavault/openmediavault/files/5997975/omv-engined.-d.-f.Console.monitor.output.txt)
although I couldnt make much sense from them. I assume that the RPC actions are where a smart test is being attempted / or performed.. although the status at the end of those lines is "good".

This is really my last hope before another OS. Thanks for your support so far!

**Comment by votdev** [comment]
I'm sorry, I'm at a loss. Without an error message somewhere in the logs i really have nothing to work with.

**Comment by P3175** [comment]
No worries, thanks for supporting so far. I might try openmediavault in a later release 🙂

**Comment by PrplHaz4** [comment]
> 
> 
> No worries, thanks for supporting so far. I might try openmediavault in a later release 🙂

Before you wipe the system, it may be worth installing omv-extras, enabling the backports repo, updating the kernel and explicitly updating the smart-drivedb (`update-smart-drivedb`).

Also, if you see issues on a new OS, don't rule out a bad SATA port or cable - I was troubleshooting strange drive behavior for months which were immediately resolved by replacing a SATA PCI card that had (seemingly) worked for years...
