### ISSUE TITLE
If we change anything of the network interface config, we will leave only the first wifi ap configuration in the wifi yaml file.

### ISSUE THREAD

**Issue by fennien** [openmediavault/openmediavault#964]
If we make any chang to the network interface configuration by the way of "System - Network - Interfaces - Edit". After apply the change, only the first ap configuration in the /etc/netplan/30xxx.yaml file will be left, the second and more will be lost. So, every time I make a such change, I have to restore this file again, and reboot to connect to my wifi ap again.

**Comment by mi-hol** [comment]
the issue template asks for much more information that what was provided, hence closing
