### ISSUE TITLE
Space into name groups in ACL editor

### ISSUE THREAD

**Issue by chodorenko** [openmediavault/openmediavault#975]
Hello, 
I use OMV 5.6.1-1 (Usul) with connect to AD and found bug on  ACL editor. Groups witch have space in name not correct work.

Step to reproduce:
1. Open ACL editor https://drive.google.com/file/d/1hVLV3vwCnn63ZVDGEOdGIGMD_yfThkZm/view
2. Setup rights  as you can view on it screenshot https://drive.google.com/file/d/14jxNGx6IJTf-CzexgX-gVRAX12EVPeeE/view
3. Apply rights
4. Check rights on facl   https://drive.google.com/file/d/1_boP9h1XVCZFj5YRNVOnS1h_SNulI4y3/view
5. Close editor and reopen again  https://drive.google.com/file/d/1OkCiuu2XWjmJ8RQnMJ5MyU_OJ6XB5UzL/view

After reopen editor group no have need group.

**Comment by votdev** [comment]
Could you please post the output of the command `$ getent group`?

**Comment by chodorenko** [comment]
> Could you please post the output of the command:
> 
> ```
> $ getent group
> ```

root@storage:~# getent group | grep domain
domain computers:x:1515:
domain controllers:x:1516:
domain admins:x:1512:
domain users:x:1513:
domain guests:x:1514:
read-only domain controllers:x:1521:
enterprise read-only domain controllers:x:1498:
cloneable domain controllers:x:1522:
root@storage:~#
