### ISSUE TITLE
Postfix permission denied 

### ISSUE THREAD

**Issue by OMMJAI** [openmediavault/openmediavault#977]
Hi omv team
I had a small problem in the syslog
I am unable to send mails

postfix/sendmail[1865]: fatal: chdir /var/spool/postfix: Permission denied

**Comment by votdev** [comment]
Is the filesystem corrupted? Do you use the [flashmemory](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-flashmemory) plugin?

**Comment by OMMJAI** [comment]
No I do not, I was trying to fix some permissions in postfix I think I have messed up postfix permissions

**Comment by OMMJAI** [comment]
Could you please help me with the permissions required for postfix

**Comment by votdev** [comment]
Please post such questions in the forum, the bug tracker is only for OMV related issues, and as you told yourself, you broke postfix yourself.

The permissions should look like this:
```
root@omv5box:/home/vagrant# ls -alh /var/spool/postfix/
total 80K
drwxr-xr-x 20 root    root     4.0K Jan 25 17:25 .
drwxr-xr-x  7 root    root     4.0K Jan 25 17:23 ..
```

**Comment by OMMJAI** [comment]
```
```
root@OMMJAI:~# ls -alh /var/spool/postfix/
total 80K
d--------- 20 postfix root     4.0K Mar  2 20:14 .
drwxr-xr-x  7 root    root     4.0K Mar  1 17:02 ..
drw-r--r--  2 postfix root     4.0K Mar  2 20:26 active
drw-r--r--  2 postfix root     4.0K Mar  2 20:21 bounce
drw-r--r--  2 postfix root     4.0K Sep 21 20:56 corrupt
drw-r--r--  5 postfix root     4.0K Mar  2 20:21 defer
drw-r--r--  5 postfix root     4.0K Mar  2 20:21 deferred
drw-r--r--  2 postfix root     4.0K Mar  2 20:21 dev
drw-r--r--  2 postfix root     4.0K Mar  1 17:08 etc
drw-r--r--  2 postfix root     4.0K Sep 21 20:56 flush
drw-r--r--  2 postfix root     4.0K Mar  2 20:14 hold
drw-r--r--  2 postfix root     4.0K Mar  2 20:26 incoming
drw-r--r--  2 postfix root     4.0K Jun 30  2020 lib
drw-r--r--  2 postfix postdrop 4.0K Mar  4 17:51 maildrop
drw-r--r--  2 postfix root     4.0K Mar  2 20:23 pid
drw-r--r--  2 postfix root     4.0K Mar  2 20:21 private
drw-r-Sr--  2 postfix postdrop 4.0K Mar  2 20:21 public
drw-r--r--  2 postfix root     4.0K Sep 21 20:56 saved
drw-r--r--  2 postfix root     4.0K Mar  2 20:14 trace
```
drw-r--r--  3 postfix root     4.0K Mar  1 17:02 usr

```

**Comment by OMMJAI** [comment]
sorry votdev to bother you
How do I fix this
