### ISSUE TITLE
Trying to change user from LDAP finished with an error

### ISSUE THREAD

**Issue by artiomn** [openmediavault/openmediavault#98]
```
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; usermod --gid 'users' --shell '/bin/bash' --comment 'Sergey' --groups 'ldap_users' 'sergey' 2>&1' with exit code '6': usermod: user 'sergey' does not exist in /etc/passwd in /usr/share/php/openmediavault/system/process.inc:175
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/usermgmt.inc(559): OMV\System\Process->execute()
#1 [internal function]: OMVRpcServiceUserMgmt->setUser(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('setUser', Array, Array)
#4 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('UserMgmt', 'setUser', Array, Array, 1)
#5 {main}
```

`sergey` doesn't exist in the `passwd`, because he was received from the LDAP server.

**Comment by donhwy** [comment]
I don't think omv is the proper place to manage your ldap users. It would make it nearly impossible to maintain for all possible ldap servers. Maybe add some type of disclaimer to only maintain local users?

**Comment by artiomn** [comment]
> I don't think omv is the proper place to manage your ldap users.

Now you have an interface, that doesn't work properly.

> It would make it nearly impossible to maintain for all possible ldap servers.

You can support only OpenLDAP, for example, and then improve the plugin, if necessary.

> Maybe add some type of disclaimer to only maintain local users?

Maybe, but improve interface and provide a ability to manage users is better.

**Comment by votdev** [comment]
Contributions are welcome.
