### ISSUE TITLE
Allow individual S.M.A.R.T. temperature thresholds

### ISSUE THREAD

**Issue by FreakedOutAgain** [openmediavault/openmediavault#981]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FreakedOutAgain** [comment]
OMV5 currently doesn't allow temperature settings for individual drives. Nowadays most NAS servers have a mixture of spinning hard drives and solid state drives. Spinning hard drives typically have a much lower maximum operating temperature (such as 55°C) than solid state drives (such as 85°C). I have turned on my monitoring for the drives and set the values to 50°C/55°C for the spinning drives but cannot use a different threshold such as 75°C/85°C for my SSD. Please consider enabling individual temperature setting.

**Comment by votdev** [comment]
Done in OMV6
