### ISSUE TITLE
Docker container for OpenMediaVault?

### ISSUE THREAD

**Issue by forrie** [openmediavault/openmediavault#983]
I see several outdated (3+ years) docker references to OpenMediaVault out in the wild, but would OpenMediaVault run well in a container (at least for some testing).   For example, I'm on a Mac, I have an 18TB drive attached that I could point OMV to, shared folders, etc.  That would serve some of my needs and testing prior to building a dedicated system.   If so, would it make sense to have a Dockerfile with the distribution?

**Comment by ryecoaaron** [comment]
OMV doesn’t work in a container. Even those images you found didn’t work well.

**Comment by forrie** [comment]
Thanks for clarifying.
