### ISSUE TITLE
OMV Nut better usage for UPS usage.

### ISSUE THREAD

**Issue by GothShoot** [openmediavault/openmediavault#984]
**Is your feature request related to a problem? Please describe.**
cannot monitor UPS status in OMV pannel

**Describe the solution you'd like**
Add monitoring of the UPS status

**Describe alternatives you've considered**
Usage of Nut CGI or directly parsing Nut CLI

**Additional context**
Probably simple to make with time and reflexion

**Comment by PrplHaz4** [comment]
Check Diagnostics -> Services -> UPS
![image](https://user-images.githubusercontent.com/841414/111327090-76438780-8643-11eb-8f9a-6b7cb6a5fd07.png)

There are also graphs for Charge, Load, Temperature and Voltage.  For some reason only the "Charge" graph is working for me, however...

**Comment by GothShoot** [comment]
Ho nice, effectively, nice view. 👍  sorry for useless issue. 😞 

And about multiple UPS support ? For rundondancy power supply 🤔

**Comment by votdev** [comment]
> And about multiple UPS support ? For rundondancy power supply

IMO this setup is not required for the SOHO target audience of OMV.

**Comment by GothShoot** [comment]
Yes probably, Thank's for response 😃
