### ISSUE TITLE
Enable USB RAID as an option

### ISSUE THREAD

**Issue by forrie** [openmediavault/openmediavault#985]
I understand that OVM doesn't allow for USB-based raid for reasons of unreliability (reported from the UI).

Would it be possible to allow us to make that selection (provide a warning, if you like).   I would like to experiment with a couple of USB 3.x drives using this method, but preferably through the OMV UI.

Thank you.

**Comment by ryecoaaron** [comment]
It was purposely disabled.  People will ignore the warning and do the bad thing.  All you need to do is create the array from the command line if you want to "test".  Everything else can be done from the web interface like adding the filesystem, mounting, etc.

**Comment by votdev** [comment]
Please use the CLI to create the RAID, OMV does nothing else. After that you can use the UI to manage the RAID.
