### ISSUE TITLE
Allow change apt source

### ISSUE THREAD

**Issue by septs** [openmediavault/openmediavault#987]
P.R.C China Region there are these mirror sites:

- https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/public/
- https://mirrors.bfsu.edu.cn/OpenMediaVault/public/

Suggestion to provide the function of change the mirror sites

------------

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues/51

**Comment by septs** [comment]
https://github.com/openmediavault/openmediavault/blob/1d32ba79c640619ce41ededee4cadb84624ee621/deb/openmediavault/srv/salt/omv/deploy/apt/files/etc-apt-sources_list_d-openmediavault_list.j2#L1

**Comment by septs** [comment]
but other source cannot be changed.

**Comment by ryecoaaron** [comment]
OMV cannot change the url. This needs to be done in the omv-extras plugin.
