### ISSUE TITLE
No device when creating RAID 

### ISSUE THREAD

**Issue by Backe03** [openmediavault/openmediavault#989]
I installed the OMV new on my Raspi 4. 

When I take a look on Data storage -> Drives they will show me both 1TB devices. 
![image](https://user-images.githubusercontent.com/77965234/112002058-ce84f880-8b1f-11eb-88c8-aeb856cab0c2.png)

Then I will create a new RAID. My destination is to creat a mirror RAID for both devices. 
But in the window where I can create the RAID they don't show me any device. 
![image](https://user-images.githubusercontent.com/77965234/112002386-1e63bf80-8b20-11eb-8328-75fdc96d4163.png)

Any one know why? Both devices are formatted as EXT 4. I did that also with OMV over the menu point File systems. There I made the formation and after that I deleated again. 
![image](https://user-images.githubusercontent.com/77965234/112002707-78fd1b80-8b20-11eb-8ffe-430aa18a5c7b.png)

Thanks for your help.

**Comment by ryecoaaron** [comment]
USB devices are not supported for RAID on OMV.  RAID with usb devices is a terrible idea especially on something without redundancy like an RPi.

And you need blank devices (no filesystems) for raid.  There are many threads about this on the forum.  I suggest using rsync, rsnapshot, or borgbackup to mirror one drive to the other.
