### ISSUE TITLE
OMV5, e-mail notification, disk space

### ISSUE THREAD

**Issue by the-Arioch** [openmediavault/openmediavault#993]
Release: 5.6.2-1
Codename: Usul
Linux diskoteka.local 5.10.0-0.bpo.3-amd64 #1 SMP Debian 5.10.13-1~bpo10+1 (2021-02-11) x86_64 GNU/Linux

Got e-mail

```
The system monitoring needs your attention.

Host:        \diskoteka.local
Date:        Sun, 28 Mar 2021 14:34:29
Service:     filesystem_srv_dev-disk-by-uuid-C6705D84705D7BDD
Event:       Resource limit matched
Description: space usage 98.9% matches resource limit [space usage > 85.0%]

This triggered the monitoring system to: alert

—
You have received this notification because you have enabled the system monitoring on this host.
To change your notification preferences, please go to the 'System | Notification' or 'System | Monitoring' page in the web interface.
```

Problems:

1. some weird backslash before host name
2. Service is unredable for human. There should be human-readable description of partition. It would be nice to even include short directory listing ( `ls`-like ). When reading the error human should immediately understand what it is all about.
3. There better be hyperlink in the notificaton body to directly change the setting for the notifications (in this case - the free space settings for the specific partition).
4. the afore mentioned `'System | Notification' or 'System | Monitoring' page` should have tables of the last month of alerts, so OMV admin could read them readily in place, rather than sieving through his mailbox (with many other non-OMV mails) on another computer or even phone.

5. And... it seems there is no way, in WebUI at least, to configure this alert. Running into the wall :-( 
The partition in question is long-term media archive. It is not expected to have free space. There has to be way to prohibit this specific check or to tune it up to 99,99% used rate for this one specific partition, without disabling this alert globally for the whole OMV site. _I think w.r.t. monitoring and similar configuration things, it could be nice to have some CSS-like scheme with more  specific rules overriding generic settings_

**Comment by votdev** [comment]
> 1. some weird backslash before host name

This is out of the control of OMV. The `monit` tool is responsible for printing this information.

> 2. Service is unredable for human. There should be human-readable description of partition. It would 
> be nice to even include short directory listing ( ls-like ). When reading the error human should 
> immediately understand what it is all about.

Totally understandable and i'm with you, but this is sadly out of the control of OMV. `monit` is responsible for this message. There is no way for OMV to configure monit to provide more detailed information. The only way to fix that is upstream or OMV has to implement such a tool on its own (which is no solution to be honest).

> 3. There better be hyperlink in the notificaton body to directly change the setting for the 
> notifications (in this case - the free space settings for the specific partition).

See above

> 5. And... it seems there is no way, in WebUI at least, to configure this alert. Running into the wall :-(

This is not the concept of OMV and how it is implemented to allow the user to configure everything. If you want to do that, OMV is not the right solution. You can customize such things using environment variables if there is really a need, but it will affect all device files that are monitored.

Please see https://openmediavault.readthedocs.io/en/5.x/various/advset.html and https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/srv/salt/omv/deploy/monit/services/files/filesystem.j2#L1.

**Comment by the-Arioch** [comment]
Thanks for the links.

I thought NAS is about creating different disk pools for different purposes and use patterns though.

I would understand you shooting down request for Viber/Telegram bots as "not our business", but defining disks intended usage seems to me actually being THE core NAS functionality.

**Comment by votdev** [comment]
> Twice so when you have #981 accepted as legit feature

Yes, this is a different thing because disks types act different nowadays. But storage is storage, and i do not see the need to define different warning limits. If it would be easy and trivial to implement individual limits per file system, it would have been implemented already. There are much more things to think about when this simple looking things should be implemented. When i do something or not, its because of reasons.

**Comment by votdev** [comment]
`Usage Warning Threshold` can be set when creating a mount point in OMV6.
