### ISSUE TITLE
OMV5 WebUI - error tooltips text can not be selected and can hardly be read

### ISSUE THREAD

**Issue by the-Arioch** [openmediavault/openmediavault#994]
Release: 5.6.2-1
Codename: Usul
Linux diskoteka.local 5.10.0-0.bpo.3-amd64 #1 SMP Debian 5.10.13-1~bpo10+1 (2021-02-11) x86_64 GNU/Linux

![2021-03-28 22_16_29-Мой диск – Google Диск - Vivaldi](https://user-images.githubusercontent.com/937774/112764929-5f257200-9013-11eb-8f85-092902a79298.png)

When error message tooltip pops up it is almost unreadable in default theme

White colour over bright red background is almost unreadable combo. and thin font adds to this.
From my experience, one better use either yellow text over dark red (wine) background, or use black text over light red.
Middle grounds just do not work.

And then for most but most trivial errors it would be natural to select the text - either to copy it to error reports or to jsut right-click and search in google for the error text. This however is not possible with those tooltips, the moment user tries to seelct text - they disappear. Information is lost, user is FUDed.

**Comment by votdev** [comment]
> From my experience, one better use either yellow text over dark red (wine) background

What about color blindes, does this work for them?

> or use black text over light red.

This looks really ugly.

I will not do anything related to OMV5 and GUI because i will not touch any ExtJS code anymore. OMV6 will switch to Angular (UI code has been released some days ago) where i can try to include your suggestions.

**Comment by votdev** [comment]
> And then for most but most trivial errors it would be natural to select the text - either to copy it 
> to error reports or to jsut right-click and search in google for the error text. This however is not 
> possible with those tooltips, the moment user tries to seelct text - they disappear. Information is >
> lost, user is FUDed.

Already fixed in OMV6. Validation errors will be displayed below the form fields and can be selected/copied.

**Comment by the-Arioch** [comment]
> What about color blindes, does this work for them?

I think they have different very special conditionts, and short of bi-color white-and-black nothing would work for all of them and for sure.

> This looks really ugly.

It does. But readable at least. You might observe how Excel or OpenOfiiceCalc assign "default" cell text colour. Like some ball (text color) running off the mountain slope (background color luminosity).  As you move the mountain left or right (changing backhground luminosity) the ball can find lower place left or right off the top, maximizing difference, contrast. 

In the end it is either black on white or white on black. Middile-luminosity backgrounds are hard to find contrastly readable and aesthetically pleasing colour for font. Especially so as we all have different monitors and customize different settings for them. Add subpixel antialiasing - and it becomes total mess.

There are some colour theories about "complementary colours in different models" but i failed to grok them.
In the end i am orbitting around yellow font over dark red of yellow to white text over dark magenta.

I still fondly remember Norton Utilities 6.0 for DOS, their text-only interface looked so fresh and slick then... Better than graphical Windows. Even better than their later versions.
https://i.imgur.com/KQAdf8G.jpg
https://winworldpc.com/product/norton-utilities/6x

Sadly i can not google their error boxes screenshots. I think i remember they looked great too, but maybe it is feigned memory.
