### ISSUE TITLE
RPI install - ethernet details missing?

### ISSUE THREAD

**Issue by talormanda** [openmediavault/openmediavault#995]
https://i.imgur.com/cg8xdrz.png
https://i.imgur.com/D30OBDl.png (edited to add this link)

Did a fresh install and I cannot see any ethernet adapter statistics. When I go to the interface, it seems blank and empty.

**Comment by votdev** [comment]
That is correct, this page shows the configuration data and not the real interface status. In your case DHCP is configured, so no IP static IP address is used that would be shown in the address column. The dashboard widget will show you the IP address and all the other things.

**Comment by talormanda** [comment]
> That displayed data is correct, this page shows the configuration data and not the real interface status. In your case DHCP is configured, so no IP static IP address is used that would be shown in the address column. The dashboard widget will show you the IP address and all the other things.

Sorry, I am referring to this page giving the sad graph face for the network interface even though it is in use: https://i.imgur.com/D30OBDl.png

**Comment by votdev** [comment]
As far as i know 'System | Monitoring' is disabled by default on RPi. Have a look here and enable it if necessary.

**Comment by talormanda** [comment]
> As far as i know `System | Monitoring` is disabled by default on RPi. Have a look here and enable it if necessary.

The Network Interfaces was the only one not showing up. After I enabled what you said, it shows up now. Any idea why disabled by default? Too much strain on the device?

**Comment by votdev** [comment]
This is because collecting system metrics is expensive and produces high IO. RPi users mostly use USB sticks for root devices, so writing time series every x seconds will kill these devices very fast. That's why it is disabled by default on RPi.
